/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-repo using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=timestamp_ba73d02e0e
ROOST_METHOD_SIG_HASH=timestamp_37349d99bf

Scenario 1: Setting timestamp with a non-empty Optional containing a valid positive Long value

Details:
  TestName: timestampWithNonEmptyOptionalContainingPositiveValue
  Description: This test verifies that the timestamp method correctly accepts an Optional containing a valid positive Long value and stores it in the builder's timestamp field. The method should return the builder instance for method chaining.

Execution:
  Arrange: Create a new Event.Builder instance. Prepare an Optional<Long> containing a valid positive timestamp value (e.g., 1234567890L).
  Act: Invoke the timestamp(Optional<Long>) method on the builder with the prepared Optional value.
  Assert: Verify that the method returns the same builder instance (for fluent API chaining). Build the Event object and verify that the timestamp field is set to the provided value.

Validation:
  The assertion verifies that the builder correctly stores the timestamp value from the Optional and maintains the fluent builder pattern by returning itself. This is significant for ensuring that timestamp values can be properly set during Event construction and that the builder pattern works as expected.

---

Scenario 2: Setting timestamp with an empty Optional

Details:
  TestName: timestampWithEmptyOptional
  Description: This test verifies that the timestamp method correctly handles an empty Optional<Long> value. When an empty Optional is provided, the builder should store the empty Optional, and the built Event should use the default timestamp (current time).

Execution:
  Arrange: Create a new Event.Builder instance. Prepare an empty Optional<Long> using Optional.empty().
  Act: Invoke the timestamp(Optional<Long>) method on the builder with the empty Optional.
  Assert: Verify that the method returns the same builder instance. Build the Event object and verify that the timestamp field is set to a default value (current epoch milliseconds).

Validation:
  The assertion verifies that the builder gracefully handles empty Optional values and applies appropriate default behavior. This is important for cases where timestamp is not explicitly provided, ensuring the Event always has a valid timestamp value.

---

Scenario 3: Setting timestamp with Optional containing zero value

Details:
  TestName: timestampWithOptionalContainingZero
  Description: This test verifies that the timestamp method correctly accepts an Optional containing a zero Long value (0L), which represents the Unix epoch start time (January 1, 1970, 00:00:00 UTC).

Execution:
  Arrange: Create a new Event.Builder instance. Prepare an Optional<Long> containing the value 0L.
  Act: Invoke the timestamp(Optional<Long>) method on the builder with the Optional containing 0L.
  Assert: Verify that the method returns the same builder instance. Build the Event object and verify that the timestamp field is set to 0L.

Validation:
  The assertion verifies that the builder correctly handles edge case timestamp values including zero, which is a valid timestamp representing the Unix epoch. This ensures the method doesn't incorrectly treat zero as an invalid or empty value.

---

Scenario 4: Setting timestamp with Optional containing negative Long value

Details:
  TestName: timestampWithOptionalContainingNegativeValue
  Description: This test verifies that the timestamp method accepts an Optional containing a negative Long value, which represents dates before the Unix epoch (before January 1, 1970).

Execution:
  Arrange: Create a new Event.Builder instance. Prepare an Optional<Long> containing a negative value (e.g., -1234567890L).
  Act: Invoke the timestamp(Optional<Long>) method on the builder with the Optional containing the negative value.
  Assert: Verify that the method returns the same builder instance. Build the Event object and verify that the timestamp field is set to the negative value.

Validation:
  The assertion verifies that the builder accepts negative timestamp values, which are valid for representing historical dates before 1970. This ensures the method doesn't impose unnecessary restrictions on timestamp values.

---

Scenario 5: Setting timestamp with Optional containing maximum Long value

Details:
  TestName: timestampWithOptionalContainingMaxLongValue
  Description: This test verifies that the timestamp method correctly handles an Optional containing the maximum possible Long value (Long.MAX_VALUE), representing a far future date.

Execution:
  Arrange: Create a new Event.Builder instance. Prepare an Optional<Long> containing Long.MAX_VALUE (9223372036854775807L).
  Act: Invoke the timestamp(Optional<Long>) method on the builder with the Optional containing Long.MAX_VALUE.
  Assert: Verify that the method returns the same builder instance. Build the Event object and verify that the timestamp field is set to Long.MAX_VALUE.

Validation:
  The assertion verifies that the builder correctly handles the upper boundary value for Long type, ensuring no overflow or unexpected behavior occurs with extreme timestamp values. This is important for robustness and handling edge cases.

---

Scenario 6: Setting timestamp with Optional containing minimum Long value

Details:
  TestName: timestampWithOptionalContainingMinLongValue
  Description: This test verifies that the timestamp method correctly handles an Optional containing the minimum possible Long value (Long.MIN_VALUE), representing the earliest possible timestamp.

Execution:
  Arrange: Create a new Event.Builder instance. Prepare an Optional<Long> containing Long.MIN_VALUE (-9223372036854775808L).
  Act: Invoke the timestamp(Optional<Long>) method on the builder with the Optional containing Long.MIN_VALUE.
  Assert: Verify that the method returns the same builder instance. Build the Event object and verify that the timestamp field is set to Long.MIN_VALUE.

Validation:
  The assertion verifies that the builder correctly handles the lower boundary value for Long type, ensuring the method can accept the full range of possible Long values without errors or data loss.

---

Scenario 7: Method chaining after setting timestamp

Details:
  TestName: timestampMethodChainingWithOtherBuilderMethods
  Description: This test verifies that the timestamp method properly supports method chaining by returning the builder instance, allowing subsequent builder method calls in a fluent API style.

Execution:
  Arrange: Create a new Event.Builder instance. Prepare an Optional<Long> with a valid timestamp value. Prepare other required builder parameters (id, invocationId, author).
  Act: Chain multiple builder method calls including timestamp(Optional<Long>), followed by other builder methods like id(), author(), and invocationId().
  Assert: Verify that all methods can be chained successfully. Build the Event object and verify that all fields including timestamp are set correctly.

Validation:
  The assertion verifies that the builder maintains the fluent API pattern, allowing developers to chain multiple method calls in a readable and convenient manner. This is a key aspect of the builder pattern design.

---

Scenario 8: Overwriting previously set timestamp value

Details:
  TestName: timestampOverwritesPreviousValue
  Description: This test verifies that calling the timestamp method multiple times with different Optional values correctly overwrites the previous timestamp value with the most recent one.

Execution:
  Arrange: Create a new Event.Builder instance. Prepare two different Optional<Long> values (e.g., Optional.of(1000L) and Optional.of(2000L)).
  Act: First, invoke timestamp(Optional<Long>) with the first Optional value. Then, invoke timestamp(Optional<Long>) again with the second Optional value.
  Assert: Build the Event object and verify that the timestamp field contains only the second value (2000L), confirming the first value was overwritten.

Validation:
  The assertion verifies that the builder correctly implements the last-write-wins semantics, which is expected behavior for builder setters. This ensures that developers can modify timestamp values during the building process.

---

Scenario 9: Setting timestamp with Optional after setting with primitive long

Details:
  TestName: timestampWithOptionalAfterPrimitiveLong
  Description: This test verifies the interaction between the two timestamp setter methods - timestamp(long) and timestamp(Optional<Long>) - ensuring that the Optional version can override a value set by the primitive version.

Execution:
  Arrange: Create a new Event.Builder instance. Prepare a primitive long value (e.g., 1000L) and an Optional<Long> value (e.g., Optional.of(2000L)).
  Act: First, invoke timestamp(long) with the primitive value. Then, invoke timestamp(Optional<Long>) with the Optional value.
  Assert: Build the Event object and verify that the timestamp field contains the value from the Optional (2000L).

Validation:
  The assertion verifies that both timestamp setter methods work correctly together and that the most recent call determines the final value, regardless of which overload was used. This ensures consistent builder behavior across different method signatures.

---

Scenario 10: Building Event without explicitly setting timestamp

Details:
  TestName: buildEventWithoutExplicitlySettingTimestamp
  Description: This test verifies the default behavior when timestamp is not explicitly set using the timestamp(Optional<Long>) method. The built Event should have a default timestamp value (current time).

Execution:
  Arrange: Create a new Event.Builder instance. Set only the required fields (id, invocationId, author) without calling any timestamp method.
  Act: Build the Event object without calling timestamp(Optional<Long>).
  Assert: Verify that the built Event has a timestamp field set to a reasonable default value (approximately current epoch milliseconds).

Validation:
  The assertion verifies that the builder provides sensible default behavior when optional fields are not set, ensuring that Event objects are always in a valid state even when timestamp is not explicitly provided. This is important for usability and preventing null or invalid timestamp values.

---

Scenario 11: Setting timestamp with Optional of current system time

Details:
  TestName: timestampWithOptionalOfCurrentSystemTime
  Description: This test verifies that the timestamp method correctly handles an Optional containing the current system time in milliseconds, which is a common use case for event timestamping.

Execution:
  Arrange: Create a new Event.Builder instance. Capture the current system time using Instant.now().toEpochMilli() and wrap it in an Optional<Long>.
  Act: Invoke the timestamp(Optional<Long>) method with the Optional containing the current time.
  Assert: Verify that the method returns the builder instance. Build the Event object and verify that the timestamp field is set to the captured current time value.

Validation:
  The assertion verifies that the builder correctly handles real-world timestamp values representing the current time, which is the most common use case for event timestamps. This ensures the method works correctly in typical application scenarios.

---

Scenario 12: Null safety verification for Optional parameter

Details:
  TestName: timestampWithNullOptionalParameter
  Description: This test verifies the behavior when a null Optional parameter is passed to the timestamp method, though this should be avoided in practice as the method signature expects Optional<Long>, not a nullable Optional.

Execution:
  Arrange: Create a new Event.Builder instance.
  Act: Attempt to invoke the timestamp(Optional<Long>) method with a null value (if the implementation allows it).
  Assert: Verify the behavior - either the method handles null gracefully by treating it as empty Optional, or it throws an appropriate exception (NullPointerException).

Validation:
  The assertion verifies the null-safety characteristics of the method. While passing null to an Optional parameter is generally bad practice, understanding the method's behavior in this scenario is important for defensive programming and error handling.

*/

// ********RoostGPT********

package com.google.adk.events;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import java.time.Instant;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class BuilderTimestamp481Test {

  private Event.Builder builder;

  @BeforeEach
  void setUp() {
    builder =
        Event.builder().id("test-id").invocationId("test-invocation-id").author("test-author");
  }

  @Test
  @Tag("valid")
  void timestampWithNonEmptyOptionalContainingPositiveValue() {
    Long expectedTimestamp = 1234567890L;
    Optional<Long> timestampOptional = Optional.of(expectedTimestamp);
    Event.Builder result = builder.timestamp(timestampOptional);
    assertNotNull(result);
    assertSame(builder, result);

    Event event = builder.build();
    assertEquals(expectedTimestamp, event.timestamp());
  }

  @Test
  @Tag("boundary")
  void timestampWithEmptyOptional() {
    Optional<Long> emptyOptional = Optional.empty();
    long beforeBuild = Instant.now().toEpochMilli();
    Event.Builder result = builder.timestamp(emptyOptional);
    assertNotNull(result);
    assertSame(builder, result);

    Event event = builder.build();
    long afterBuild = Instant.now().toEpochMilli();

    assertTrue(event.timestamp() >= beforeBuild && event.timestamp() <= afterBuild);
  }

  @Test
  @Tag("boundary")
  void timestampWithOptionalContainingZero() {
    Long expectedTimestamp = 0L;
    Optional<Long> timestampOptional = Optional.of(expectedTimestamp);
    Event.Builder result = builder.timestamp(timestampOptional);
    assertNotNull(result);
    assertSame(builder, result);

    Event event = builder.build();
    assertEquals(expectedTimestamp, event.timestamp());
  }

  @Test
  @Tag("valid")
  void timestampWithOptionalContainingNegativeValue() {
    Long expectedTimestamp = -1234567890L;
    Optional<Long> timestampOptional = Optional.of(expectedTimestamp);
    Event.Builder result = builder.timestamp(timestampOptional);
    assertNotNull(result);
    assertSame(builder, result);

    Event event = builder.build();
    assertEquals(expectedTimestamp, event.timestamp());
  }

  @Test
  @Tag("boundary")
  void timestampWithOptionalContainingMaxLongValue() {
    Long expectedTimestamp = Long.MAX_VALUE;
    Optional<Long> timestampOptional = Optional.of(expectedTimestamp);
    Event.Builder result = builder.timestamp(timestampOptional);
    assertNotNull(result);
    assertSame(builder, result);

    Event event = builder.build();
    assertEquals(expectedTimestamp, event.timestamp());
  }

  @Test
  @Tag("boundary")
  void timestampWithOptionalContainingMinLongValue() {
    Long expectedTimestamp = Long.MIN_VALUE;
    Optional<Long> timestampOptional = Optional.of(expectedTimestamp);
    Event.Builder result = builder.timestamp(timestampOptional);
    assertNotNull(result);
    assertSame(builder, result);

    Event event = builder.build();
    assertEquals(expectedTimestamp, event.timestamp());
  }

  @Test
  @Tag("valid")
  void timestampMethodChainingWithOtherBuilderMethods() {
    Long expectedTimestamp = 9876543210L;
    Optional<Long> timestampOptional = Optional.of(expectedTimestamp);
    String expectedId = "chained-id";
    String expectedAuthor = "chained-author";
    String expectedInvocationId = "chained-invocation-id";
    Event event =
        Event.builder()
            .id(expectedId)
            .timestamp(timestampOptional)
            .author(expectedAuthor)
            .invocationId(expectedInvocationId)
            .build();
    assertNotNull(event);
    assertEquals(expectedId, event.id());
    assertEquals(expectedAuthor, event.author());
    assertEquals(expectedInvocationId, event.invocationId());
    assertEquals(expectedTimestamp, event.timestamp());
  }

  @Test
  @Tag("valid")
  void timestampOverwritesPreviousValue() {
    Long firstTimestamp = 1000L;
    Long secondTimestamp = 2000L;
    Optional<Long> firstOptional = Optional.of(firstTimestamp);
    Optional<Long> secondOptional = Optional.of(secondTimestamp);
    builder.timestamp(firstOptional);
    builder.timestamp(secondOptional);
    Event event = builder.build();
    assertEquals(secondTimestamp, event.timestamp());
  }

  @Test
  @Tag("valid")
  void timestampWithOptionalAfterPrimitiveLong() {
    Long primitiveTimestamp = 1000L;
    Long optionalTimestamp = 2000L;
    Optional<Long> timestampOptional = Optional.of(optionalTimestamp);
    builder.timestamp(primitiveTimestamp);
    builder.timestamp(timestampOptional);
    Event event = builder.build();
    assertEquals(optionalTimestamp, event.timestamp());
  }

  @Test
  @Tag("valid")
  void buildEventWithoutExplicitlySettingTimestamp() {
    long beforeBuild = Instant.now().toEpochMilli();
    Event event = builder.build();
    long afterBuild = Instant.now().toEpochMilli();

    assertNotNull(event.timestamp());
    assertTrue(event.timestamp() >= beforeBuild);
    assertTrue(event.timestamp() <= afterBuild);
  }

  @Test
  @Tag("valid")
  void timestampWithOptionalOfCurrentSystemTime() {
    long currentTime = Instant.now().toEpochMilli();
    Optional<Long> timestampOptional = Optional.of(currentTime);
    Event.Builder result = builder.timestamp(timestampOptional);
    assertNotNull(result);
    assertSame(builder, result);

    Event event = builder.build();
    assertEquals(currentTime, event.timestamp());
  }

  @Test
  @Tag("invalid")
  void timestampWithNullOptionalParameter() {
    assertThrows(
        NullPointerException.class,
        () -> {
          builder.timestamp((Optional<Long>) null);
        });
  }

  @Test
  @Tag("valid")
  void timestampReturnsBuilderForFluentChaining() {
    Optional<Long> timestampOptional = Optional.of(5000L);
    Event.Builder result = builder.timestamp(timestampOptional);
    assertNotNull(result);
    assertTrue(result instanceof Event.Builder);
    assertSame(builder, result);
  }

  @Test
  @Tag("valid")
  void timestampWithMultipleSequentialCalls() {
    Optional<Long> first = Optional.of(100L);
    Optional<Long> second = Optional.of(200L);
    Optional<Long> third = Optional.of(300L);
    builder.timestamp(first).timestamp(second).timestamp(third);
    Event event = builder.build();
    assertEquals(300L, event.timestamp());
  }

  @Test
  @Tag("valid")
  void timestampWithOptionalAndOtherOptionalFields() {
    Optional<Long> timestampOptional = Optional.of(7777L);
    Optional<Boolean> partialOptional = Optional.of(true);
    Optional<String> errorMessageOptional = Optional.of("test error");
    Event event =
        builder
            .timestamp(timestampOptional)
            .partial(partialOptional)
            .errorMessage(errorMessageOptional)
            .build();
    assertEquals(7777L, event.timestamp());
    assertEquals(true, event.partial().get());
    assertEquals("test error", event.errorMessage().get());
  }

  @Test
  @Tag("valid")
  void timestampPreservesBuilderState() {
    String testId = "preserve-test-id";
    String testAuthor = "preserve-test-author";
    Optional<Long> timestampOptional = Optional.of(12345L);
    builder.id(testId).author(testAuthor).timestamp(timestampOptional);
    Event event = builder.build();
    assertEquals(testId, event.id());
    assertEquals(testAuthor, event.author());
    assertEquals(12345L, event.timestamp());
  }

  @Test
  @Tag("boundary")
  void timestampWithOptionalContainingOneMillisecond() {
    Long expectedTimestamp = 1L;
    Optional<Long> timestampOptional = Optional.of(expectedTimestamp);
    Event.Builder result = builder.timestamp(timestampOptional);
    Event event = result.build();
    assertEquals(expectedTimestamp, event.timestamp());
  }

  @Test
  @Tag("valid")
  void timestampWithRealisticFutureTimestamp() {
    long futureTimestamp = Instant.now().plusSeconds(86400).toEpochMilli();
    Optional<Long> timestampOptional = Optional.of(futureTimestamp);
    Event.Builder result = builder.timestamp(timestampOptional);
    Event event = result.build();
    assertEquals(futureTimestamp, event.timestamp());
    assertTrue(event.timestamp() > Instant.now().toEpochMilli());
  }

  @Test
  @Tag("valid")
  void timestampWithRealisticPastTimestamp() {
    long pastTimestamp = Instant.now().minusSeconds(86400).toEpochMilli();
    Optional<Long> timestampOptional = Optional.of(pastTimestamp);
    Event.Builder result = builder.timestamp(timestampOptional);
    Event event = result.build();
    assertEquals(pastTimestamp, event.timestamp());
    assertTrue(event.timestamp() < Instant.now().toEpochMilli());
  }
}
