/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-repo using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=finishReason_9fdfad8c6f
ROOST_METHOD_SIG_HASH=finishReason_9eaa424500

Scenario 1: Setting a Non-Null FinishReason Value

Details:
  TestName: finishReasonWithNonNullValue
  Description: This test verifies that the finishReason method correctly accepts a non-null FinishReason value and wraps it in an Optional. It ensures that the builder properly stores the provided FinishReason enum value and returns the builder instance for method chaining.
Execution:
  Arrange: Create a new Event.Builder instance and prepare a valid FinishReason enum value (e.g., FinishReason.STOP or any other valid enum constant from the FinishReason type).
  Act: Invoke the finishReason method on the builder instance, passing the non-null FinishReason value as a parameter.
  Assert: Verify that the method returns the same builder instance (for fluent API chaining). Build the Event object and verify that the finishReason field contains an Optional with the provided FinishReason value using the finishReason() getter method.
Validation:
  This assertion verifies that the builder correctly handles non-null FinishReason values by wrapping them in an Optional. This is critical for the builder pattern's fluent API, ensuring that developers can chain multiple setter calls. The test confirms that the finishReason field is properly set and can be retrieved from the built Event object, which is essential for tracking the completion status of content generation operations.

Scenario 2: Setting a Null FinishReason Value

Details:
  TestName: finishReasonWithNullValue
  Description: This test validates that the finishReason method correctly handles null input by creating an empty Optional. It ensures that passing null as the parameter results in Optional.empty() being stored in the finishReason field, following the @Nullable annotation contract.
Execution:
  Arrange: Create a new Event.Builder instance.
  Act: Invoke the finishReason method on the builder instance, passing null as the parameter.
  Assert: Verify that the method returns the same builder instance. Build the Event object and verify that the finishReason field contains an empty Optional using the finishReason() getter method and Optional.isEmpty() or asserting that it equals Optional.empty().
Validation:
  This assertion confirms that the builder properly handles null values according to the @Nullable annotation, converting them to empty Optionals rather than storing null references. This is important for null-safety and prevents NullPointerExceptions when accessing the finishReason field. The test ensures that the Optional pattern is correctly implemented, allowing consumers to safely check for the presence of a finish reason without null checks.

Scenario 3: Method Chaining Capability

Details:
  TestName: finishReasonReturnsBuilderForChaining
  Description: This test verifies that the finishReason method returns the builder instance itself, enabling fluent API method chaining. It ensures that multiple builder methods can be called in sequence without breaking the chain.
Execution:
  Arrange: Create a new Event.Builder instance and prepare a valid FinishReason value.
  Act: Invoke the finishReason method and capture the returned object. Chain additional builder methods (such as id(), author(), or invocationId()) after the finishReason call.
  Assert: Verify that the returned object from finishReason is the same instance as the original builder using reference equality (assertSame). Verify that subsequent chained method calls execute successfully and the final build() produces a valid Event object.
Validation:
  This assertion validates the builder pattern's fluent API design, which is annotated with @CanIgnoreReturnValue. Method chaining is a key feature of the builder pattern, improving code readability and reducing verbosity. This test ensures that developers can write concise, readable code like builder.finishReason(value).author("agent").build() without intermediate variable assignments.

Scenario 4: Overwriting Previously Set FinishReason Value

Details:
  TestName: finishReasonOverwritesPreviousValue
  Description: This test verifies that calling the finishReason method multiple times on the same builder instance correctly overwrites the previous value with the new one. It ensures that the last set value is the one that persists in the built Event object.
Execution:
  Arrange: Create a new Event.Builder instance and prepare two different FinishReason values (e.g., first value and second value from the FinishReason enum).
  Act: Invoke the finishReason method with the first FinishReason value, then invoke it again with the second FinishReason value on the same builder instance.
  Assert: Build the Event object and verify that the finishReason field contains an Optional with the second FinishReason value (the last one set), not the first value.
Validation:
  This assertion confirms that the builder follows the expected behavior of setter methods, where subsequent calls overwrite previous values rather than accumulating them. This is important for builder flexibility, allowing developers to modify values during the building process. The test ensures data integrity by verifying that only the most recent value is retained.

Scenario 5: Setting FinishReason After Setting to Null

Details:
  TestName: finishReasonSetAfterNull
  Description: This test validates that the builder can transition from a null finishReason (empty Optional) to a non-null value. It ensures that setting a null value first and then a valid value results in the valid value being stored.
Execution:
  Arrange: Create a new Event.Builder instance and prepare a valid FinishReason value.
  Act: First, invoke the finishReason method with null as the parameter. Then, invoke the finishReason method again with a valid FinishReason value.
  Assert: Build the Event object and verify that the finishReason field contains an Optional with the valid FinishReason value (not empty).
Validation:
  This assertion verifies that the builder correctly handles state transitions from empty to present Optional values. This is important for scenarios where a builder might be reused or configured conditionally. The test ensures that null values don't permanently lock the field into an empty state and that subsequent valid values are properly stored.

Scenario 6: Setting FinishReason to Null After Setting a Valid Value

Details:
  TestName: finishReasonSetNullAfterValidValue
  Description: This test validates that the builder can transition from a valid finishReason value to null (empty Optional). It ensures that setting a valid value first and then null results in an empty Optional being stored.
Execution:
  Arrange: Create a new Event.Builder instance and prepare a valid FinishReason value.
  Act: First, invoke the finishReason method with a valid FinishReason value. Then, invoke the finishReason method again with null as the parameter.
  Assert: Build the Event object and verify that the finishReason field contains an empty Optional using Optional.isEmpty() or asserting equality with Optional.empty().
Validation:
  This assertion confirms that the builder allows clearing previously set values by passing null. This is useful for scenarios where a builder needs to be reset or when conditional logic determines that a field should not have a value. The test ensures that null values properly overwrite existing values, maintaining the builder's flexibility.

Scenario 7: Building Event Without Setting FinishReason

Details:
  TestName: finishReasonDefaultValueWhenNotSet
  Description: This test verifies the default state of the finishReason field when the finishReason method is never called on the builder. It ensures that the field defaults to an empty Optional as defined in the Builder class initialization.
Execution:
  Arrange: Create a new Event.Builder instance and set only the required fields (id, invocationId, author) without calling the finishReason method.
  Act: Build the Event object without ever invoking the finishReason method.
  Assert: Verify that the finishReason field in the built Event object contains an empty Optional using the finishReason() getter method.
Validation:
  This assertion validates the default initialization behavior of the builder, ensuring that optional fields start with empty Optional values as declared in the field initialization (Optional<FinishReason> finishReason = Optional.empty()). This is important for understanding the builder's default state and ensures that unset optional fields don't cause unexpected behavior or null pointer exceptions.

Scenario 8: FinishReason Value Persistence Across Build Operations

Details:
  TestName: finishReasonValuePersistsInBuiltEvent
  Description: This test verifies that the finishReason value set in the builder is correctly transferred to the Event object during the build() operation and can be retrieved using the Event's finishReason() getter method.
Execution:
  Arrange: Create a new Event.Builder instance, prepare a valid FinishReason value, and set all required fields.
  Act: Invoke the finishReason method with the valid FinishReason value, then call build() to create an Event object.
  Assert: Retrieve the finishReason value from the built Event object using the finishReason() getter method and verify that it contains an Optional with the exact FinishReason value that was set in the builder.
Validation:
  This assertion ensures proper data transfer from the builder to the immutable Event object. It validates that the build() method correctly copies the finishReason field from the builder to the Event instance using the setFinishReason method. This is critical for the integrity of the builder pattern, ensuring that configured values are accurately reflected in the final object.

Scenario 9: Multiple Builder Instances Independence

Details:
  TestName: finishReasonIndependenceBetweenBuilderInstances
  Description: This test verifies that setting finishReason on one builder instance does not affect other builder instances. It ensures that each builder maintains its own independent state.
Execution:
  Arrange: Create two separate Event.Builder instances and prepare two different FinishReason values.
  Act: Set the first FinishReason value on the first builder instance and the second FinishReason value on the second builder instance.
  Assert: Build Event objects from both builders and verify that each Event contains the correct, distinct finishReason value corresponding to what was set on its respective builder.
Validation:
  This assertion confirms that builder instances are properly isolated and don't share state. This is fundamental to the builder pattern's correctness, ensuring that concurrent or sequential use of multiple builders doesn't cause data corruption or unexpected behavior. The test validates that each builder maintains its own finishReason field independently.

Scenario 10: FinishReason with ToBuilder Pattern

Details:
  TestName: finishReasonPreservedInToBuilder
  Description: This test verifies that when creating a new builder from an existing Event using the toBuilder() method, the finishReason value is correctly preserved in the new builder instance.
Execution:
  Arrange: Create an Event.Builder instance, set a valid FinishReason value, and build an Event object. Then create a new builder from this Event using the toBuilder() method.
  Act: Build a new Event object from the toBuilder() instance without modifying the finishReason field.
  Assert: Verify that the new Event object contains the same finishReason value as the original Event object.
Validation:
  This assertion validates the toBuilder() pattern implementation, ensuring that all fields including finishReason are correctly copied when creating a builder from an existing Event. This is important for scenarios where developers need to create modified copies of Event objects while preserving most fields. The test ensures data integrity during the Event-to-Builder-to-Event transformation cycle.

*/

// ********RoostGPT********

package com.google.adk.events;

import static com.google.common.truth.Truth.assertThat;
import static com.google.common.truth.Truth8.assertThat;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertSame;

import com.google.genai.types.FinishReason;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class BuilderFinishReasonTest {

  @Test
  @Tag("valid")
  void finishReasonWithNonNullValue() {
    Event.Builder builder = Event.builder();
    FinishReason finishReasonValue = FinishReason.STOP;
    Event.Builder returnedBuilder = builder.finishReason(finishReasonValue);
    assertSame(builder, returnedBuilder);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertThat(event.finishReason()).hasValue(finishReasonValue);
  }

  @Test
  @Tag("valid")
  void finishReasonWithNullValue() {
    Event.Builder builder = Event.builder();
    Event.Builder returnedBuilder = builder.finishReason(null);
    assertSame(builder, returnedBuilder);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertThat(event.finishReason()).isEmpty();
  }

  @Test
  @Tag("valid")
  void finishReasonReturnsBuilderForChaining() {
    Event.Builder builder = Event.builder();
    FinishReason finishReasonValue = FinishReason.MAX_TOKENS;
    Event.Builder returnedBuilder = builder.finishReason(finishReasonValue);
    assertSame(builder, returnedBuilder);
    Event event =
        returnedBuilder.id("test-id").author("test-author").invocationId("test-invocation").build();
    assertNotNull(event);
    assertThat(event.finishReason()).hasValue(finishReasonValue);
  }

  @Test
  @Tag("valid")
  void finishReasonOverwritesPreviousValue() {
    Event.Builder builder = Event.builder();
    FinishReason firstValue = FinishReason.STOP;
    FinishReason secondValue = FinishReason.MAX_TOKENS;
    builder.finishReason(firstValue);
    builder.finishReason(secondValue);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertThat(event.finishReason()).hasValue(secondValue);
  }

  @Test
  @Tag("valid")
  void finishReasonSetAfterNull() {
    Event.Builder builder = Event.builder();
    FinishReason validValue = FinishReason.SAFETY;
    builder.finishReason(null);
    builder.finishReason(validValue);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertThat(event.finishReason()).hasValue(validValue);
  }

  @Test
  @Tag("valid")
  void finishReasonSetNullAfterValidValue() {
    Event.Builder builder = Event.builder();
    FinishReason validValue = FinishReason.RECITATION;
    builder.finishReason(validValue);
    builder.finishReason(null);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertThat(event.finishReason()).isEmpty();
  }

  @Test
  @Tag("boundary")
  void finishReasonDefaultValueWhenNotSet() {
    Event.Builder builder = Event.builder();
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertThat(event.finishReason()).isEmpty();
  }

  @Test
  @Tag("valid")
  void finishReasonValuePersistsInBuiltEvent() {
    Event.Builder builder = Event.builder();
    FinishReason finishReasonValue = FinishReason.OTHER;
    builder
        .id("test-id")
        .invocationId("test-invocation")
        .author("test-author")
        .finishReason(finishReasonValue);
    Event event = builder.build();
    assertThat(event.finishReason()).hasValue(finishReasonValue);
  }

  @Test
  @Tag("valid")
  void finishReasonIndependenceBetweenBuilderInstances() {
    Event.Builder builder1 = Event.builder();
    Event.Builder builder2 = Event.builder();
    FinishReason firstValue = FinishReason.STOP;
    FinishReason secondValue = FinishReason.MAX_TOKENS;
    builder1.finishReason(firstValue);
    builder2.finishReason(secondValue);
    Event event1 =
        builder1.id("test-id-1").invocationId("test-invocation-1").author("test-author-1").build();
    Event event2 =
        builder2.id("test-id-2").invocationId("test-invocation-2").author("test-author-2").build();
    assertThat(event1.finishReason()).hasValue(firstValue);
    assertThat(event2.finishReason()).hasValue(secondValue);
  }

  @Test
  @Tag("integration")
  void finishReasonPreservedInToBuilder() {
    FinishReason finishReasonValue = FinishReason.SAFETY;
    Event originalEvent =
        Event.builder()
            .id("test-id")
            .invocationId("test-invocation")
            .author("test-author")
            .finishReason(finishReasonValue)
            .build();
    Event.Builder newBuilder = originalEvent.toBuilder();
    Event newEvent = newBuilder.build();
    assertThat(newEvent.finishReason()).hasValue(finishReasonValue);
    assertThat(newEvent.finishReason()).isEqualTo(originalEvent.finishReason());
  }

  @Test
  @Tag("valid")
  void finishReasonWithAllEnumValues() {
    for (FinishReason finishReasonValue : FinishReason.values()) {
      Event.Builder builder = Event.builder();
      builder.finishReason(finishReasonValue);
      Event event =
          builder.id("test-id").invocationId("test-invocation").author("test-author").build();
      assertThat(event.finishReason()).hasValue(finishReasonValue);
    }
  }

  @Test
  @Tag("valid")
  void finishReasonMultipleChainedCalls() {
    Event.Builder builder = Event.builder();
    FinishReason finishReasonValue = FinishReason.RECITATION;
    Event event =
        builder
            .id("test-id")
            .invocationId("test-invocation")
            .author("test-author")
            .finishReason(finishReasonValue)
            .partial(true)
            .turnComplete(false)
            .build();
    assertThat(event.finishReason()).hasValue(finishReasonValue);
    assertThat(event.partial()).hasValue(true);
    assertThat(event.turnComplete()).hasValue(false);
  }
}
