/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-repo using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=content_988fe1360f
ROOST_METHOD_SIG_HASH=content_22e8e58bf4

Scenario 1: Setting Content with Non-Empty Optional

Details:
  TestName: contentWithNonEmptyOptional
  Description: This test verifies that the content method correctly sets a non-empty Optional<Content> value in the Builder and returns the Builder instance for method chaining. It ensures that when a valid Optional containing a Content object is passed, the builder stores it properly.

Execution:
  Arrange: Create a new Event.Builder instance. Create a mock or test Content object and wrap it in an Optional.
  Act: Invoke the content(Optional<Content>) method on the builder with the non-empty Optional.
  Assert: Verify that the method returns the same Builder instance (for fluent API). Build the Event and verify that the content field contains the expected Optional<Content> value.

Validation:
  The assertion verifies that the builder pattern is maintained (returns this) and that the content field is properly set with the provided Optional value. This is critical for ensuring that the fluent API works correctly and that content data is preserved during the building process. This test validates the primary happy path for setting content through an Optional parameter.

---

Scenario 2: Setting Content with Empty Optional

Details:
  TestName: contentWithEmptyOptional
  Description: This test checks that the content method correctly handles an empty Optional<Content> value. It ensures that passing Optional.empty() properly sets the content field to an empty Optional without throwing exceptions.

Execution:
  Arrange: Create a new Event.Builder instance. Create an empty Optional<Content> using Optional.empty().
  Act: Invoke the content(Optional<Content>) method with the empty Optional.
  Assert: Verify that the method returns the Builder instance. Build the Event and verify that the content field is Optional.empty().

Validation:
  This assertion confirms that the builder can handle empty Optional values gracefully, which is important for cases where content may not be available or applicable. This test ensures that the absence of content is properly represented and doesn't cause null pointer exceptions or unexpected behavior in the application.

---

Scenario 3: Builder Returns Same Instance for Method Chaining

Details:
  TestName: contentReturnsBuilderForMethodChaining
  Description: This test validates that the content method returns the same Builder instance to support fluent API method chaining. This is essential for the builder pattern implementation.

Execution:
  Arrange: Create a new Event.Builder instance. Create an Optional<Content> with a test Content object.
  Act: Invoke the content method and capture the returned Builder reference.
  Assert: Use assertSame to verify that the returned Builder is the exact same instance as the original builder.

Validation:
  This assertion ensures that the builder pattern's fluent interface is correctly implemented. Method chaining is a key feature of the builder pattern, allowing developers to write more readable and concise code like builder.content(value).author(name).build(). This test confirms that the @CanIgnoreReturnValue annotation is properly supported and the pattern works as expected.

---

Scenario 4: Setting Content Multiple Times Overwrites Previous Value

Details:
  TestName: contentOverwritesPreviousValue
  Description: This test verifies that calling the content method multiple times on the same Builder instance overwrites the previous content value with the new one, ensuring that only the last set value is retained.

Execution:
  Arrange: Create a new Event.Builder instance. Create two different Content objects wrapped in Optional instances (firstContent and secondContent).
  Act: Call content(firstContent) followed by content(secondContent) on the same builder. Build the Event.
  Assert: Verify that the built Event's content field contains secondContent and not firstContent.

Validation:
  This assertion confirms that the builder correctly handles multiple invocations of the same setter method, with the last call taking precedence. This behavior is expected in builder patterns and ensures that developers can modify values during the building process. It's important for scenarios where content might be conditionally set or updated based on runtime logic.

---

Scenario 5: Setting Content with Null Optional Reference

Details:
  TestName: contentWithNullOptionalReference
  Description: This test examines the behavior when a null reference is passed as the Optional<Content> parameter. While the method signature accepts Optional<Content>, it's important to verify how the implementation handles a null Optional reference itself (not Optional.empty(), but actual null).

Execution:
  Arrange: Create a new Event.Builder instance. Prepare a null reference for Optional<Content>.
  Act: Invoke the content(Optional<Content>) method with the null reference.
  Assert: Verify the behavior - either the method handles it gracefully by setting content to Optional.empty(), or it throws a NullPointerException. Build the Event if no exception occurs and check the content field.

Validation:
  This assertion tests the robustness of the method against null inputs. While Optional is designed to avoid null references, developers might still pass null. The test validates whether the implementation includes null-safety checks or relies on the caller to provide valid Optional instances. This is important for preventing runtime exceptions in production code.

---

Scenario 6: Content Integration with Complete Event Building

Details:
  TestName: contentIntegrationWithCompleteEventBuilding
  Description: This test validates that the content method works correctly as part of a complete Event building process, ensuring proper integration with other builder methods and that the final Event object is correctly constructed.

Execution:
  Arrange: Create a new Event.Builder instance. Prepare a Content object wrapped in Optional. Prepare other required fields like id, invocationId, and author.
  Act: Chain multiple builder methods including content(Optional<Content>), id(), invocationId(), author(), and call build().
  Assert: Verify that the built Event object has all fields correctly set, including the content field with the expected Optional<Content> value.

Validation:
  This assertion ensures that the content method integrates seamlessly with the entire builder workflow. It validates that setting content doesn't interfere with other fields and that the build() method correctly transfers the content value to the final Event object. This is crucial for verifying the overall builder pattern implementation and ensuring that the Event object is properly constructed with all its fields.

---

Scenario 7: Content Method with Optional Containing Null Content Object

Details:
  TestName: contentWithOptionalContainingNull
  Description: This test checks the behavior when an Optional is created with a null Content object (Optional.ofNullable(null)), which results in Optional.empty(). It verifies that the method handles this edge case correctly.

Execution:
  Arrange: Create a new Event.Builder instance. Create an Optional<Content> using Optional.ofNullable(null), which produces Optional.empty().
  Act: Invoke the content(Optional<Content>) method with this Optional.
  Assert: Verify that the method returns the Builder instance. Build the Event and verify that the content field is Optional.empty().

Validation:
  This assertion validates that the method correctly handles the semantic difference between explicitly passing Optional.empty() and passing Optional.ofNullable(null). Both should result in the same behavior (empty Optional), but this test ensures consistency. This is important for API users who might use different approaches to create empty Optionals, ensuring predictable behavior regardless of the creation method.

---

Scenario 8: Verify Content Field Isolation Between Builder Instances

Details:
  TestName: contentFieldIsolationBetweenBuilders
  Description: This test ensures that setting content on one Builder instance does not affect other Builder instances, verifying proper encapsulation and instance isolation.

Execution:
  Arrange: Create two separate Event.Builder instances (builder1 and builder2). Create two different Content objects wrapped in Optionals (content1 and content2).
  Act: Set content1 on builder1 and content2 on builder2. Build both Events.
  Assert: Verify that event1 contains content1 and event2 contains content2, confirming no cross-contamination between builders.

Validation:
  This assertion confirms that each Builder instance maintains its own state independently. This is fundamental to the builder pattern's correctness, ensuring that multiple builders can be used concurrently without interfering with each other. This test is particularly important in multi-threaded environments or when multiple Event objects are being constructed simultaneously in the same scope.

---

Scenario 9: Content Method Behavior After Building Event

Details:
  TestName: contentMethodAfterBuildingEvent
  Description: This test verifies that the Builder can be reused after building an Event, and that calling content again properly sets a new value for subsequent builds.

Execution:
  Arrange: Create a new Event.Builder instance. Create two different Content objects wrapped in Optionals (firstContent and secondContent).
  Act: Set firstContent, build the first Event. Then set secondContent on the same builder and build a second Event.
  Assert: Verify that the first Event contains firstContent and the second Event contains secondContent.

Validation:
  This assertion validates that the Builder can be reused for creating multiple Event instances, which is a useful feature of the builder pattern. It ensures that the builder's state can be modified after a build() call and that subsequent builds reflect the new state. This is important for scenarios where similar Events need to be created with slight variations, improving code efficiency and reusability.

---

Scenario 10: Content Method with Optional Created from ofNullable with Valid Content

Details:
  TestName: contentWithOptionalOfNullableValidContent
  Description: This test verifies that the content method correctly handles an Optional created using Optional.ofNullable() with a valid (non-null) Content object.

Execution:
  Arrange: Create a new Event.Builder instance. Create a valid Content object and wrap it using Optional.ofNullable(content).
  Act: Invoke the content(Optional<Content>) method with this Optional.
  Assert: Verify that the method returns the Builder instance. Build the Event and verify that the content field contains the expected Content object within the Optional.

Validation:
  This assertion ensures that the method works correctly with Optionals created through Optional.ofNullable(), which is a common pattern for handling potentially null values. It validates that the implementation doesn't have any unexpected behavior based on how the Optional was created (ofNullable vs. of vs. empty). This test is important for ensuring API consistency and predictability across different Optional creation patterns.

---

Scenario 11: Content Field State After toBuilder Operation

Details:
  TestName: contentPreservedAfterToBuilder
  Description: This test verifies that when an Event is converted back to a Builder using toBuilder(), the content field is correctly preserved and can be retrieved from the new builder.

Execution:
  Arrange: Create an Event.Builder, set a Content object wrapped in Optional, and build an Event. Call toBuilder() on the built Event to create a new Builder.
  Act: Build a new Event from the toBuilder() result.
  Assert: Verify that the new Event's content field matches the original Event's content field.

Validation:
  This assertion validates that the toBuilder() method correctly copies the content field, ensuring that Event objects can be cloned or modified through the builder pattern without losing data. This is crucial for scenarios where existing Events need to be modified or copied, maintaining data integrity throughout the process. It ensures the builder pattern's copy functionality works correctly for the content field.

---

Scenario 12: Content Method Thread Safety Consideration

Details:
  TestName: contentMethodSingleThreadedBehavior
  Description: This test documents the expected behavior of the content method in a single-threaded context, establishing a baseline for understanding its behavior. Note: The Builder class does not appear to be thread-safe based on the provided code.

Execution:
  Arrange: Create a new Event.Builder instance in a single thread. Create a Content object wrapped in Optional.
  Act: Invoke the content method and immediately build the Event within the same thread.
  Assert: Verify that the Event is built successfully with the correct content value.

Validation:
  This assertion establishes the expected behavior in a single-threaded environment. While the Builder class doesn't appear to have thread-safety mechanisms (no synchronization or volatile keywords visible), this test documents the correct usage pattern. It serves as a baseline for understanding that the Builder should be used within a single thread or with external synchronization. This is important for API documentation and preventing misuse in concurrent scenarios.

*/

// ********RoostGPT********

package com.google.adk.events;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.genai.types.Content;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class BuilderContent312Test {

  private Event.Builder builder;

  private Content mockContent;

  @BeforeEach
  void setUp() {
    builder = Event.builder();
    mockContent = mock(Content.class);
  }

  @Test
  @Tag("valid")
  void contentWithNonEmptyOptional() {
    Optional<Content> contentOptional = Optional.of(mockContent);

    Event.Builder result = builder.content(contentOptional);

    assertSame(builder, result);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertTrue(event.content().isPresent());
    assertEquals(mockContent, event.content().get());
  }

  @Test
  @Tag("valid")
  void contentWithEmptyOptional() {
    Optional<Content> emptyOptional = Optional.empty();

    Event.Builder result = builder.content(emptyOptional);

    assertSame(builder, result);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertFalse(event.content().isPresent());
  }

  @Test
  @Tag("valid")
  void contentReturnsBuilderForMethodChaining() {
    Optional<Content> contentOptional = Optional.of(mockContent);

    Event.Builder result = builder.content(contentOptional);

    assertSame(builder, result);
  }

  @Test
  @Tag("valid")
  void contentOverwritesPreviousValue() {
    Content firstContent = mock(Content.class);
    Content secondContent = mock(Content.class);
    Optional<Content> firstOptional = Optional.of(firstContent);
    Optional<Content> secondOptional = Optional.of(secondContent);

    builder.content(firstOptional);
    builder.content(secondOptional);

    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertTrue(event.content().isPresent());
    assertEquals(secondContent, event.content().get());
    assertNotEquals(firstContent, event.content().get());
  }

  @Test
  @Tag("invalid")
  void contentWithNullOptionalReference() {
    Optional<Content> nullOptional = null;

    assertThrows(
        NullPointerException.class,
        () -> {
          builder.content(nullOptional);
          builder.id("test-id").invocationId("test-invocation").author("test-author").build();
        });
  }

  @Test
  @Tag("integration")
  void contentIntegrationWithCompleteEventBuilding() {
    Optional<Content> contentOptional = Optional.of(mockContent);
    String testId = "integration-test-id";
    String testInvocationId = "integration-invocation-id";
    String testAuthor = "integration-author";

    Event event =
        builder
            .id(testId)
            .invocationId(testInvocationId)
            .author(testAuthor)
            .content(contentOptional)
            .partial(true)
            .turnComplete(false)
            .build();

    assertNotNull(event);
    assertEquals(testId, event.id());
    assertEquals(testInvocationId, event.invocationId());
    assertEquals(testAuthor, event.author());
    assertTrue(event.content().isPresent());
    assertEquals(mockContent, event.content().get());
  }

  @Test
  @Tag("boundary")
  void contentWithOptionalContainingNull() {
    Optional<Content> optionalWithNull = Optional.ofNullable(null);

    Event.Builder result = builder.content(optionalWithNull);

    assertSame(builder, result);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertFalse(event.content().isPresent());
    assertEquals(Optional.empty(), event.content());
  }

  @Test
  @Tag("valid")
  void contentFieldIsolationBetweenBuilders() {
    Content content1 = mock(Content.class);
    Content content2 = mock(Content.class);
    Optional<Content> optional1 = Optional.of(content1);
    Optional<Content> optional2 = Optional.of(content2);

    Event.Builder builder1 = Event.builder();
    Event.Builder builder2 = Event.builder();

    builder1.content(optional1);
    builder2.content(optional2);

    Event event1 = builder1.id("id1").invocationId("invocation1").author("author1").build();
    Event event2 = builder2.id("id2").invocationId("invocation2").author("author2").build();

    assertTrue(event1.content().isPresent());
    assertTrue(event2.content().isPresent());
    assertEquals(content1, event1.content().get());
    assertEquals(content2, event2.content().get());
    assertNotEquals(event1.content().get(), event2.content().get());
  }

  @Test
  @Tag("valid")
  void contentMethodAfterBuildingEvent() {
    Content firstContent = mock(Content.class);
    Content secondContent = mock(Content.class);
    Optional<Content> firstOptional = Optional.of(firstContent);
    Optional<Content> secondOptional = Optional.of(secondContent);

    builder.content(firstOptional);
    Event firstEvent =
        builder.id("first-id").invocationId("first-invocation").author("first-author").build();

    builder.content(secondOptional);
    Event secondEvent =
        builder.id("second-id").invocationId("second-invocation").author("second-author").build();

    assertTrue(firstEvent.content().isPresent());
    assertEquals(firstContent, firstEvent.content().get());
    assertTrue(secondEvent.content().isPresent());
    assertEquals(secondContent, secondEvent.content().get());
  }

  @Test
  @Tag("valid")
  void contentWithOptionalOfNullableValidContent() {
    Content validContent = mock(Content.class);
    Optional<Content> optionalContent = Optional.ofNullable(validContent);

    Event.Builder result = builder.content(optionalContent);

    assertSame(builder, result);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertTrue(event.content().isPresent());
    assertEquals(validContent, event.content().get());
  }

  @Test
  @Tag("integration")
  void contentPreservedAfterToBuilder() {
    Optional<Content> contentOptional = Optional.of(mockContent);

    Event originalEvent =
        builder
            .id("original-id")
            .invocationId("original-invocation")
            .author("original-author")
            .content(contentOptional)
            .build();

    Event.Builder newBuilder = originalEvent.toBuilder();
    Event newEvent = newBuilder.build();

    assertTrue(newEvent.content().isPresent());
    assertEquals(originalEvent.content(), newEvent.content());
    assertEquals(mockContent, newEvent.content().get());
  }

  @Test
  @Tag("valid")
  void contentMethodSingleThreadedBehavior() {
    Optional<Content> contentOptional = Optional.of(mockContent);

    builder.content(contentOptional);
    Event event =
        builder
            .id("single-thread-id")
            .invocationId("single-thread-invocation")
            .author("single-thread-author")
            .build();

    assertNotNull(event);
    assertTrue(event.content().isPresent());
    assertEquals(mockContent, event.content().get());
  }

  @Test
  @Tag("valid")
  void contentMethodWithMultipleChainedCalls() {
    Optional<Content> contentOptional = Optional.of(mockContent);

    Event event =
        builder
            .id("chained-id")
            .content(contentOptional)
            .invocationId("chained-invocation")
            .author("chained-author")
            .partial(true)
            .turnComplete(false)
            .build();

    assertNotNull(event);
    assertTrue(event.content().isPresent());
    assertEquals(mockContent, event.content().get());
    assertEquals("chained-id", event.id());
    assertEquals("chained-invocation", event.invocationId());
    assertEquals("chained-author", event.author());
  }

  @Test
  @Tag("valid")
  void contentWithEmptyOptionalDoesNotAffectOtherFields() {
    Optional<Content> emptyOptional = Optional.empty();
    String testId = "test-id";
    String testInvocationId = "test-invocation";
    String testAuthor = "test-author";

    Event event =
        builder
            .id(testId)
            .invocationId(testInvocationId)
            .author(testAuthor)
            .content(emptyOptional)
            .partial(false)
            .build();

    assertFalse(event.content().isPresent());
    assertEquals(testId, event.id());
    assertEquals(testInvocationId, event.invocationId());
    assertEquals(testAuthor, event.author());
  }

  @Test
  @Tag("valid")
  void contentSetMultipleTimesWithMixedValues() {
    Content content1 = mock(Content.class);
    Optional<Content> optional1 = Optional.of(content1);
    Optional<Content> emptyOptional = Optional.empty();
    Content content2 = mock(Content.class);
    Optional<Content> optional2 = Optional.of(content2);

    builder.content(optional1);
    builder.content(emptyOptional);
    builder.content(optional2);

    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();

    assertTrue(event.content().isPresent());
    assertEquals(content2, event.content().get());
  }
}
