/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-repo using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=timestamp_662c1ecdd9
ROOST_METHOD_SIG_HASH=timestamp_b4272b37fb

Scenario 1: Return Empty Optional When Timestamp Is Not Set

Details:
  TestName: timestampReturnsEmptyOptionalWhenNotSet
  Description: This test verifies that the timestamp() method returns an empty Optional when no timestamp value has been set on the Builder instance. This is the default state of a newly created Builder before any timestamp value is assigned.

Execution:
  Arrange: Create a new Event.Builder instance without setting any timestamp value.
  Act: Invoke the timestamp() method on the Builder instance.
  Assert: Use JUnit assertions to verify that the returned Optional is empty using Optional.isEmpty() or assertFalse(result.isPresent()).

Validation:
  This assertion verifies that the Builder correctly initializes the timestamp field as an empty Optional by default. This is important because it allows the build() method to distinguish between an explicitly set timestamp and one that should default to the current system time (Instant.now().toEpochMilli()). This test ensures proper initialization behavior and prevents null pointer exceptions.


Scenario 2: Return Optional Containing Value When Timestamp Is Set With Long Value

Details:
  TestName: timestampReturnsOptionalWithValueWhenSetWithLong
  Description: This test verifies that the timestamp() method returns an Optional containing the correct Long value when a timestamp has been explicitly set using the timestamp(long value) setter method.

Execution:
  Arrange: Create a new Event.Builder instance and set a specific timestamp value using timestamp(1234567890L).
  Act: Invoke the timestamp() method on the Builder instance.
  Assert: Use JUnit assertions to verify that the returned Optional is present (assertTrue(result.isPresent())) and contains the expected value (assertEquals(1234567890L, result.get())).

Validation:
  This assertion confirms that the Builder correctly stores and retrieves timestamp values that are explicitly set. This is critical for ensuring that when developers want to create an Event with a specific timestamp (rather than using the current time), their value is preserved correctly. This test validates the basic setter-getter contract for the timestamp field.


Scenario 3: Return Optional Containing Value When Timestamp Is Set With Optional

Details:
  TestName: timestampReturnsOptionalWithValueWhenSetWithOptional
  Description: This test verifies that the timestamp() method returns an Optional containing the correct Long value when a timestamp has been set using the timestamp(Optional<Long> value) setter method with a non-empty Optional.

Execution:
  Arrange: Create a new Event.Builder instance and set a timestamp using timestamp(Optional.of(9876543210L)).
  Act: Invoke the timestamp() method on the Builder instance.
  Assert: Use JUnit assertions to verify that the returned Optional is present and contains the expected value (assertEquals(9876543210L, result.get())).

Validation:
  This assertion ensures that the Builder correctly handles the Optional-based setter variant. This is important for API flexibility, allowing callers to pass Optional values directly without unwrapping them first. This test validates that both setter variants (primitive long and Optional<Long>) work correctly and maintain consistency.


Scenario 4: Return Empty Optional When Timestamp Is Set With Empty Optional

Details:
  TestName: timestampReturnsEmptyOptionalWhenSetWithEmptyOptional
  Description: This test verifies that the timestamp() method returns an empty Optional when the timestamp has been explicitly set to an empty Optional using the timestamp(Optional<Long> value) method.

Execution:
  Arrange: Create a new Event.Builder instance and set the timestamp using timestamp(Optional.empty()).
  Act: Invoke the timestamp() method on the Builder instance.
  Assert: Use JUnit assertions to verify that the returned Optional is empty (assertFalse(result.isPresent())).

Validation:
  This assertion confirms that the Builder correctly handles the case where a developer explicitly wants to clear or not set a timestamp value by passing an empty Optional. This is important for API consistency and allows developers to explicitly indicate the absence of a value, which will trigger the default behavior in the build() method (using current system time).


Scenario 5: Return Latest Value When Timestamp Is Set Multiple Times

Details:
  TestName: timestampReturnsLatestValueWhenSetMultipleTimes
  Description: This test verifies that the timestamp() method returns the most recently set value when the timestamp setter is called multiple times with different values. This ensures that subsequent calls override previous values.

Execution:
  Arrange: Create a new Event.Builder instance, set timestamp to 1111111111L, then set it again to 2222222222L.
  Act: Invoke the timestamp() method on the Builder instance.
  Assert: Use JUnit assertions to verify that the returned Optional contains the latest value (assertEquals(2222222222L, result.get())).

Validation:
  This assertion validates that the Builder follows standard builder pattern semantics where the last set value takes precedence. This is crucial for ensuring predictable behavior when builders are reused or when values are updated during the building process. This test prevents bugs related to value retention or accumulation.


Scenario 6: Return Zero When Timestamp Is Set To Zero

Details:
  TestName: timestampReturnsZeroWhenSetToZero
  Description: This test verifies that the timestamp() method correctly returns an Optional containing zero when the timestamp is explicitly set to 0L. This is an edge case that tests whether the implementation distinguishes between "not set" and "set to zero".

Execution:
  Arrange: Create a new Event.Builder instance and set the timestamp to 0L using timestamp(0L).
  Act: Invoke the timestamp() method on the Builder instance.
  Assert: Use JUnit assertions to verify that the returned Optional is present and contains 0L (assertTrue(result.isPresent()) and assertEquals(0L, result.get())).

Validation:
  This assertion ensures that the Builder correctly handles the edge case of a zero timestamp value. Zero is a valid timestamp (representing the Unix epoch: January 1, 1970, 00:00:00 UTC) and should be treated as a legitimate value, not as "unset". This test is important for preventing bugs where zero might be incorrectly treated as a null or default value.


Scenario 7: Return Negative Value When Timestamp Is Set To Negative Number

Details:
  TestName: timestampReturnsNegativeValueWhenSetToNegative
  Description: This test verifies that the timestamp() method correctly returns an Optional containing a negative value when the timestamp is set to a negative long value. Negative timestamps represent dates before the Unix epoch.

Execution:
  Arrange: Create a new Event.Builder instance and set the timestamp to -1000000L using timestamp(-1000000L).
  Act: Invoke the timestamp() method on the Builder instance.
  Assert: Use JUnit assertions to verify that the returned Optional is present and contains -1000000L (assertEquals(-1000000L, result.get())).

Validation:
  This assertion validates that the Builder correctly handles negative timestamp values, which are valid in the context of Unix timestamps (representing dates before January 1, 1970). This test ensures that the implementation doesn't impose unnecessary restrictions on the timestamp range and correctly stores any valid long value.


Scenario 8: Return Maximum Long Value When Timestamp Is Set To Long.MAX_VALUE

Details:
  TestName: timestampReturnsMaxValueWhenSetToLongMaxValue
  Description: This test verifies that the timestamp() method correctly handles the maximum possible long value (Long.MAX_VALUE) when set as the timestamp. This tests the upper boundary of the acceptable range.

Execution:
  Arrange: Create a new Event.Builder instance and set the timestamp to Long.MAX_VALUE using timestamp(Long.MAX_VALUE).
  Act: Invoke the timestamp() method on the Builder instance.
  Assert: Use JUnit assertions to verify that the returned Optional is present and contains Long.MAX_VALUE (assertEquals(Long.MAX_VALUE, result.get())).

Validation:
  This assertion ensures that the Builder correctly handles extreme boundary values without overflow or data loss. While Long.MAX_VALUE represents a date far in the future (approximately year 292,277,026,596), it's a valid long value and should be stored correctly. This test validates robustness against boundary conditions.


Scenario 9: Return Minimum Long Value When Timestamp Is Set To Long.MIN_VALUE

Details:
  TestName: timestampReturnsMinValueWhenSetToLongMinValue
  Description: This test verifies that the timestamp() method correctly handles the minimum possible long value (Long.MIN_VALUE) when set as the timestamp. This tests the lower boundary of the acceptable range.

Execution:
  Arrange: Create a new Event.Builder instance and set the timestamp to Long.MIN_VALUE using timestamp(Long.MIN_VALUE).
  Act: Invoke the timestamp() method on the Builder instance.
  Assert: Use JUnit assertions to verify that the returned Optional is present and contains Long.MIN_VALUE (assertEquals(Long.MIN_VALUE, result.get())).

Validation:
  This assertion ensures that the Builder correctly handles the minimum boundary value without underflow or data loss. This test is important for validating that the implementation doesn't impose artificial restrictions on the lower bound of timestamp values and correctly handles all valid long values.


Scenario 10: Return Empty Optional After Setting Value Then Setting Empty Optional

Details:
  TestName: timestampReturnsEmptyOptionalAfterOverridingWithEmpty
  Description: This test verifies that the timestamp() method returns an empty Optional when a timestamp value is first set and then explicitly cleared by setting it to an empty Optional. This tests the ability to reset the timestamp field.

Execution:
  Arrange: Create a new Event.Builder instance, set timestamp to 5555555555L, then set it to Optional.empty().
  Act: Invoke the timestamp() method on the Builder instance.
  Assert: Use JUnit assertions to verify that the returned Optional is empty (assertFalse(result.isPresent())).

Validation:
  This assertion validates that the Builder allows developers to clear previously set values by passing an empty Optional. This is important for builder reusability and for scenarios where a value needs to be conditionally set or cleared. This test ensures that the Optional-based setter provides full control over the field's state.


Scenario 11: Maintain Independence Between Multiple Builder Instances

Details:
  TestName: timestampMaintainsIndependenceBetweenBuilderInstances
  Description: This test verifies that the timestamp() method returns values that are independent between different Builder instances. Setting a timestamp on one builder should not affect the timestamp of another builder.

Execution:
  Arrange: Create two separate Event.Builder instances (builder1 and builder2). Set timestamp to 1111111111L on builder1 and 2222222222L on builder2.
  Act: Invoke the timestamp() method on both builder instances.
  Assert: Use JUnit assertions to verify that builder1.timestamp() returns Optional containing 1111111111L and builder2.timestamp() returns Optional containing 2222222222L.

Validation:
  This assertion ensures that Builder instances maintain their own independent state and don't share mutable state. This is critical for thread safety and for preventing bugs when multiple builders are used concurrently or sequentially. This test validates proper encapsulation and instance isolation.

*/

// ********RoostGPT********

package com.google.adk.events;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class BuilderTimestamp139Test {

  @Test
  @Tag("valid")
  void timestampReturnsEmptyOptionalWhenNotSet() {
    Event.Builder builder = Event.builder();

    Optional<Long> result = builder.timestamp();

    assertFalse(result.isPresent());
    assertTrue(result.isEmpty());
  }

  @Test
  @Tag("valid")
  void timestampReturnsOptionalWithValueWhenSetWithLong() {
    Event.Builder builder = Event.builder();
    builder.timestamp(1234567890L);

    Optional<Long> result = builder.timestamp();

    assertTrue(result.isPresent());
    assertEquals(1234567890L, result.get());
  }

  @Test
  @Tag("valid")
  void timestampReturnsOptionalWithValueWhenSetWithOptional() {
    Event.Builder builder = Event.builder();
    builder.timestamp(Optional.of(9876543210L));

    Optional<Long> result = builder.timestamp();

    assertTrue(result.isPresent());
    assertEquals(9876543210L, result.get());
  }

  @Test
  @Tag("valid")
  void timestampReturnsEmptyOptionalWhenSetWithEmptyOptional() {
    Event.Builder builder = Event.builder();
    builder.timestamp(Optional.empty());

    Optional<Long> result = builder.timestamp();

    assertFalse(result.isPresent());
    assertTrue(result.isEmpty());
  }

  @Test
  @Tag("valid")
  void timestampReturnsLatestValueWhenSetMultipleTimes() {
    Event.Builder builder = Event.builder();
    builder.timestamp(1111111111L);
    builder.timestamp(2222222222L);

    Optional<Long> result = builder.timestamp();

    assertTrue(result.isPresent());
    assertEquals(2222222222L, result.get());
  }

  @Test
  @Tag("boundary")
  void timestampReturnsZeroWhenSetToZero() {
    Event.Builder builder = Event.builder();
    builder.timestamp(0L);

    Optional<Long> result = builder.timestamp();

    assertTrue(result.isPresent());
    assertEquals(0L, result.get());
  }

  @Test
  @Tag("boundary")
  void timestampReturnsNegativeValueWhenSetToNegative() {
    Event.Builder builder = Event.builder();
    builder.timestamp(-1000000L);

    Optional<Long> result = builder.timestamp();

    assertTrue(result.isPresent());
    assertEquals(-1000000L, result.get());
  }

  @Test
  @Tag("boundary")
  void timestampReturnsMaxValueWhenSetToLongMaxValue() {
    Event.Builder builder = Event.builder();
    builder.timestamp(Long.MAX_VALUE);

    Optional<Long> result = builder.timestamp();

    assertTrue(result.isPresent());
    assertEquals(Long.MAX_VALUE, result.get());
  }

  @Test
  @Tag("boundary")
  void timestampReturnsMinValueWhenSetToLongMinValue() {
    Event.Builder builder = Event.builder();
    builder.timestamp(Long.MIN_VALUE);

    Optional<Long> result = builder.timestamp();

    assertTrue(result.isPresent());
    assertEquals(Long.MIN_VALUE, result.get());
  }

  @Test
  @Tag("valid")
  void timestampReturnsEmptyOptionalAfterOverridingWithEmpty() {
    Event.Builder builder = Event.builder();
    builder.timestamp(5555555555L);
    builder.timestamp(Optional.empty());

    Optional<Long> result = builder.timestamp();

    assertFalse(result.isPresent());
    assertTrue(result.isEmpty());
  }

  @Test
  @Tag("valid")
  void timestampMaintainsIndependenceBetweenBuilderInstances() {
    Event.Builder builder1 = Event.builder();
    Event.Builder builder2 = Event.builder();
    builder1.timestamp(1111111111L);
    builder2.timestamp(2222222222L);

    Optional<Long> result1 = builder1.timestamp();
    Optional<Long> result2 = builder2.timestamp();

    assertTrue(result1.isPresent());
    assertEquals(1111111111L, result1.get());
    assertTrue(result2.isPresent());
    assertEquals(2222222222L, result2.get());
  }

  @Test
  @Tag("valid")
  void timestampReturnsCorrectValueAfterMultipleOptionalSets() {
    Event.Builder builder = Event.builder();
    builder.timestamp(Optional.of(1000L));
    builder.timestamp(Optional.of(2000L));
    builder.timestamp(Optional.of(3000L));

    Optional<Long> result = builder.timestamp();

    assertTrue(result.isPresent());
    assertEquals(3000L, result.get());
  }

  @Test
  @Tag("valid")
  void timestampReturnsCorrectValueAfterMixedSetterCalls() {
    Event.Builder builder = Event.builder();
    builder.timestamp(1000L);
    builder.timestamp(Optional.of(2000L));
    builder.timestamp(3000L);

    Optional<Long> result = builder.timestamp();

    assertTrue(result.isPresent());
    assertEquals(3000L, result.get());
  }

  @Test
  @Tag("valid")
  void timestampReturnsEmptyAfterSettingValueThenEmptyOptional() {
    Event.Builder builder = Event.builder();
    builder.timestamp(1234567890L);
    builder.timestamp(Optional.empty());

    Optional<Long> result = builder.timestamp();

    assertFalse(result.isPresent());
  }

  @Test
  @Tag("boundary")
  void timestampReturnsCorrectValueForVeryLargePositiveNumber() {
    Event.Builder builder = Event.builder();
    long largeValue = 9223372036854775806L;
    builder.timestamp(largeValue);

    Optional<Long> result = builder.timestamp();

    assertTrue(result.isPresent());
    assertEquals(largeValue, result.get());
  }

  @Test
  @Tag("boundary")
  void timestampReturnsCorrectValueForVeryLargeNegativeNumber() {
    Event.Builder builder = Event.builder();
    long largeNegativeValue = -9223372036854775807L;
    builder.timestamp(largeNegativeValue);

    Optional<Long> result = builder.timestamp();

    assertTrue(result.isPresent());
    assertEquals(largeNegativeValue, result.get());
  }

  @Test
  @Tag("valid")
  void timestampReturnsValueAfterBuilderChaining() {
    Event.Builder builder =
        Event.builder()
            .id("test-id")
            .invocationId("test-invocation")
            .author("test-author")
            .timestamp(7777777777L);

    Optional<Long> result = builder.timestamp();

    assertTrue(result.isPresent());
    assertEquals(7777777777L, result.get());
  }

  @Test
  @Tag("valid")
  void timestampReturnsEmptyWhenBuilderCreatedWithoutTimestamp() {
    Event.Builder builder =
        Event.builder().id("test-id").invocationId("test-invocation").author("test-author");

    Optional<Long> result = builder.timestamp();

    assertFalse(result.isPresent());
  }

  @Test
  @Tag("valid")
  void timestampReturnsCorrectValueWhenSetBeforeOtherFields() {
    Event.Builder builder = Event.builder();
    builder.timestamp(8888888888L);
    builder.id("test-id");
    builder.author("test-author");

    Optional<Long> result = builder.timestamp();

    assertTrue(result.isPresent());
    assertEquals(8888888888L, result.get());
  }

  @Test
  @Tag("valid")
  void timestampReturnsCorrectValueWhenSetAfterOtherFields() {
    Event.Builder builder = Event.builder();
    builder.id("test-id");
    builder.author("test-author");
    builder.timestamp(9999999999L);

    Optional<Long> result = builder.timestamp();

    assertTrue(result.isPresent());
    assertEquals(9999999999L, result.get());
  }
}
