/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-repo using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=errorMessage_4e64e663d6
ROOST_METHOD_SIG_HASH=errorMessage_b5d6e6241d

Scenario 1: Setting Error Message with Non-Empty Optional String Value

Details:
  TestName: errorMessageWithNonEmptyOptionalString
  Description: This test verifies that the errorMessage method correctly accepts an Optional containing a non-empty String value and returns the Builder instance for method chaining. The test ensures that the builder pattern works correctly when setting a valid error message.

Execution:
  Arrange: Create a new Event.Builder instance. Prepare an Optional<String> containing a non-empty error message such as "Connection timeout error".
  Act: Invoke the errorMessage method on the builder with the prepared Optional<String> value.
  Assert: Verify that the returned object is the same Builder instance (method chaining). Build the Event object and verify that the errorMessage field contains the expected Optional with the correct error message value.

Validation:
  This assertion verifies that the errorMessage method properly stores the provided Optional<String> value in the builder's errorMessage field and maintains the builder pattern by returning the same builder instance. This is significant for ensuring that error messages can be properly set during Event construction and that the fluent API pattern is maintained for a better developer experience.

---

Scenario 2: Setting Error Message with Empty Optional

Details:
  TestName: errorMessageWithEmptyOptional
  Description: This test validates that the errorMessage method correctly handles an empty Optional<String> value. It ensures that the builder can accept and store an empty Optional, which represents the absence of an error message.

Execution:
  Arrange: Create a new Event.Builder instance. Prepare an empty Optional<String> using Optional.empty().
  Act: Invoke the errorMessage method on the builder with the empty Optional.
  Assert: Verify that the method returns the same Builder instance. Build the Event object and verify that the errorMessage field contains an empty Optional.

Validation:
  This test confirms that the builder correctly handles the case where no error message is present. This is important for scenarios where an Event is created without errors, ensuring that the Optional pattern is properly maintained throughout the object lifecycle. The empty Optional signifies that no error occurred, which is a valid state for the Event object.

---

Scenario 3: Setting Error Message with Optional Containing Null String

Details:
  TestName: errorMessageWithOptionalOfNull
  Description: This test examines the behavior when the errorMessage method receives an Optional created from a null String value using Optional.ofNullable(null). It verifies that the builder handles this edge case appropriately.

Execution:
  Arrange: Create a new Event.Builder instance. Create an Optional<String> using Optional.ofNullable(null), which results in an empty Optional.
  Act: Call the errorMessage method with the Optional created from null.
  Assert: Verify that the method returns the Builder instance. Build the Event and confirm that the errorMessage field contains an empty Optional.

Validation:
  This assertion validates that the builder properly handles the edge case of an Optional created from a null value. Since Optional.ofNullable(null) produces an empty Optional, the builder should store an empty Optional in the errorMessage field. This test is crucial for ensuring robust null handling and preventing potential NullPointerExceptions in the application.

---

Scenario 4: Setting Error Message Multiple Times with Different Values

Details:
  TestName: errorMessageSetMultipleTimesWithDifferentValues
  Description: This test verifies that when the errorMessage method is called multiple times on the same builder instance with different values, the last value set is retained. This tests the overwriting behavior of the builder.

Execution:
  Arrange: Create a new Event.Builder instance. Prepare two different Optional<String> values: first with "First error message" and second with "Second error message".
  Act: Call the errorMessage method first with the first Optional value, then call it again with the second Optional value.
  Assert: Verify that both method calls return the same Builder instance. Build the Event and verify that the errorMessage field contains the second error message value, confirming that the last set value overwrites the previous one.

Validation:
  This test ensures that the builder follows the expected behavior of allowing field values to be overwritten. This is important for scenarios where error messages might need to be updated or corrected during the building process. The test confirms that the builder maintains consistency and predictability in its state management.

---

Scenario 5: Setting Error Message with Very Long String Value

Details:
  TestName: errorMessageWithVeryLongString
  Description: This test validates that the errorMessage method can handle Optional<String> values containing very long strings without issues. It ensures there are no length restrictions or performance problems with large error messages.

Execution:
  Arrange: Create a new Event.Builder instance. Generate a very long String (e.g., 10,000 characters) and wrap it in an Optional<String>.
  Act: Invoke the errorMessage method with the Optional containing the very long string.
  Assert: Verify that the method returns the Builder instance. Build the Event and verify that the errorMessage field contains the complete long string without truncation or corruption.

Validation:
  This assertion confirms that the builder can handle error messages of arbitrary length without data loss or performance degradation. This is important for real-world scenarios where detailed error messages, stack traces, or diagnostic information might be quite lengthy. The test ensures robustness in handling edge cases related to string length.

---

Scenario 6: Setting Error Message with Special Characters and Unicode

Details:
  TestName: errorMessageWithSpecialCharactersAndUnicode
  Description: This test verifies that the errorMessage method correctly handles Optional<String> values containing special characters, Unicode characters, emojis, and various character encodings.

Execution:
  Arrange: Create a new Event.Builder instance. Prepare an Optional<String> containing special characters such as newlines (\n), tabs (\t), quotes, Unicode characters (e.g., "Error: 文字化け 🚨 \"quoted\" \n\t").
  Act: Call the errorMessage method with the Optional containing special characters.
  Assert: Verify that the method returns the Builder instance. Build the Event and verify that the errorMessage field preserves all special characters and Unicode content exactly as provided.

Validation:
  This test ensures that the builder properly handles internationalization and special character encoding. This is critical for applications that operate in multiple languages or need to preserve formatting in error messages. The test validates that no character encoding issues or data corruption occurs during the building process.

---

Scenario 7: Setting Error Message with Empty String

Details:
  TestName: errorMessageWithEmptyString
  Description: This test examines the behavior when the errorMessage method receives an Optional containing an empty string (""). It verifies that the builder distinguishes between an empty Optional and an Optional containing an empty string.

Execution:
  Arrange: Create a new Event.Builder instance. Create an Optional<String> containing an empty string using Optional.of("").
  Act: Invoke the errorMessage method with the Optional containing the empty string.
  Assert: Verify that the method returns the Builder instance. Build the Event and verify that the errorMessage field contains an Optional with an empty string (not an empty Optional).

Validation:
  This assertion validates the semantic difference between "no error message" (empty Optional) and "error message exists but is empty" (Optional containing empty string). This distinction can be important for business logic that needs to differentiate between these two states. The test ensures that the builder preserves this semantic difference correctly.

---

Scenario 8: Builder Method Chaining with Error Message

Details:
  TestName: errorMessageMethodChainingWithOtherBuilderMethods
  Description: This test verifies that the errorMessage method integrates properly with the builder pattern by allowing method chaining with other builder methods. It ensures that the fluent API works correctly across multiple method calls.

Execution:
  Arrange: Create a new Event.Builder instance. Prepare test data for multiple fields including errorMessage, id, author, and errorCode.
  Act: Chain multiple builder method calls together: builder.id("test-id").author("test-author").errorMessage(Optional.of("Test error")).errorCode(Optional.of(FinishReason.SAFETY)).
  Assert: Verify that the chaining executes without errors. Build the Event and verify that all fields (id, author, errorMessage, errorCode) are set correctly with their respective values.

Validation:
  This test confirms that the errorMessage method properly implements the builder pattern by returning the builder instance, allowing for fluent method chaining. This is essential for providing a good developer experience and ensuring that the builder can be used idiomatically. The test validates that the builder maintains consistency across multiple field assignments.

---

Scenario 9: Setting Error Message After Building Event

Details:
  TestName: errorMessageSetAfterBuildDoesNotAffectBuiltEvent
  Description: This test verifies that modifying the builder's errorMessage field after building an Event does not affect the already-built Event instance. It ensures proper immutability and independence between builder and built objects.

Execution:
  Arrange: Create a new Event.Builder instance. Set an initial errorMessage with Optional.of("Initial error"). Build the Event to create event1.
  Act: After building event1, call errorMessage on the same builder with a different value Optional.of("Modified error"). Build another Event to create event2.
  Assert: Verify that event1's errorMessage contains "Initial error" and event2's errorMessage contains "Modified error". Confirm that event1 was not affected by the subsequent builder modification.

Validation:
  This assertion ensures that the builder creates independent Event instances and that modifying the builder after building does not affect previously built objects. This is crucial for maintaining data integrity and preventing unintended side effects. The test validates proper encapsulation and the independence of built objects from their builder.

---

Scenario 10: Setting Error Message with Whitespace-Only String

Details:
  TestName: errorMessageWithWhitespaceOnlyString
  Description: This test validates the behavior when the errorMessage method receives an Optional containing a string with only whitespace characters (spaces, tabs, newlines).

Execution:
  Arrange: Create a new Event.Builder instance. Create an Optional<String> containing only whitespace characters such as "   \t\n  ".
  Act: Call the errorMessage method with the Optional containing the whitespace-only string.
  Assert: Verify that the method returns the Builder instance. Build the Event and verify that the errorMessage field contains the Optional with the whitespace string preserved exactly as provided.

Validation:
  This test ensures that the builder does not perform any automatic trimming or validation on the error message content. It validates that whitespace-only strings are treated as valid error messages, which might be intentional in certain scenarios. The test confirms that the builder acts as a pure data container without imposing business logic on the content.

---

Scenario 11: Setting Error Message in Combination with Error Code

Details:
  TestName: errorMessageSetWithCorrespondingErrorCode
  Description: This test verifies that the errorMessage method works correctly when used in conjunction with the errorCode method, simulating a realistic error scenario where both error code and message are set.

Execution:
  Arrange: Create a new Event.Builder instance. Prepare an Optional<FinishReason> for errorCode and an Optional<String> for errorMessage with corresponding values (e.g., FinishReason.SAFETY and "Content filtered due to safety concerns").
  Act: Call both errorCode and errorMessage methods on the builder with their respective values.
  Assert: Verify that both methods return the Builder instance. Build the Event and verify that both errorCode and errorMessage fields are set correctly with their respective values.

Validation:
  This assertion validates that the errorMessage field works harmoniously with related fields like errorCode. This is important for ensuring that error information can be comprehensively captured in Event objects. The test confirms that multiple error-related fields can be set independently without interference, which is crucial for proper error reporting and handling in the application.

---

Scenario 12: Setting Error Message to Null Using Optional Parameter

Details:
  TestName: errorMessageWithNullOptionalParameter
  Description: This test examines the behavior when a null Optional object itself is passed to the errorMessage method (not an Optional containing null, but the Optional parameter being null).

Execution:
  Arrange: Create a new Event.Builder instance. Prepare a null Optional<String> reference.
  Act: Call the errorMessage method with the null Optional reference.
  Assert: Verify the behavior based on the implementation - either the method handles null gracefully by storing it, or it may throw a NullPointerException. Build the Event if no exception occurs and verify the errorMessage field state.

Validation:
  This test validates the builder's null-safety and error handling capabilities. While passing null to a method expecting an Optional is generally considered a programming error, the test ensures that the behavior is predictable and documented. This is important for defensive programming and preventing unexpected runtime failures. The test helps identify whether additional null-checking is needed in the implementation.

*/

// ********RoostGPT********

package com.google.adk.events;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.genai.types.FinishReason;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@DisplayName("Event.Builder errorMessage() Method Tests")
class BuilderErrorMessage864Test {

  private Event.Builder builder;

  @BeforeEach
  void setUp() {
    builder = Event.builder();
  }

  @Test
  @Tag("valid")
  @DisplayName("Setting Error Message with Non-Empty Optional String Value")
  void errorMessageWithNonEmptyOptionalString() {
    String errorMsg = "Connection timeout error";
    Optional<String> errorMessageOptional = Optional.of(errorMsg);
    Event.Builder result = builder.errorMessage(errorMessageOptional);
    assertSame(builder, result, "Builder should return same instance for method chaining");
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertTrue(event.errorMessage().isPresent(), "Error message should be present");
    assertEquals(errorMsg, event.errorMessage().get(), "Error message should match the set value");
  }

  @Test
  @Tag("valid")
  @DisplayName("Setting Error Message with Empty Optional")
  void errorMessageWithEmptyOptional() {
    Optional<String> emptyOptional = Optional.empty();
    Event.Builder result = builder.errorMessage(emptyOptional);
    assertSame(builder, result, "Builder should return same instance for method chaining");
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertFalse(event.errorMessage().isPresent(), "Error message should be empty");
  }

  @Test
  @Tag("boundary")
  @DisplayName("Setting Error Message with Optional Containing Null String")
  void errorMessageWithOptionalOfNull() {
    Optional<String> optionalOfNull = Optional.ofNullable(null);
    Event.Builder result = builder.errorMessage(optionalOfNull);
    assertSame(builder, result, "Builder should return same instance for method chaining");
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertFalse(
        event.errorMessage().isPresent(), "Error message should be empty when created from null");
  }

  @Test
  @Tag("valid")
  @DisplayName("Setting Error Message Multiple Times with Different Values")
  void errorMessageSetMultipleTimesWithDifferentValues() {
    String firstError = "First error message";
    String secondError = "Second error message";
    Optional<String> firstOptional = Optional.of(firstError);
    Optional<String> secondOptional = Optional.of(secondError);
    Event.Builder result1 = builder.errorMessage(firstOptional);
    assertSame(builder, result1, "First call should return same builder instance");
    Event.Builder result2 = builder.errorMessage(secondOptional);
    assertSame(builder, result2, "Second call should return same builder instance");
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertTrue(event.errorMessage().isPresent(), "Error message should be present");
    assertEquals(
        secondError, event.errorMessage().get(), "Error message should be the last set value");
  }

  @Test
  @Tag("boundary")
  @DisplayName("Setting Error Message with Very Long String Value")
  void errorMessageWithVeryLongString() {
    StringBuilder longStringBuilder = new StringBuilder();
    for (int i = 0; i < 10000; i++) {
      longStringBuilder.append("A");
    }
    String veryLongString = longStringBuilder.toString();
    Optional<String> longErrorOptional = Optional.of(veryLongString);
    Event.Builder result = builder.errorMessage(longErrorOptional);
    assertSame(builder, result, "Builder should return same instance for method chaining");
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertTrue(event.errorMessage().isPresent(), "Error message should be present");
    assertEquals(
        veryLongString,
        event.errorMessage().get(),
        "Error message should preserve the complete long string");
    assertEquals(
        10000, event.errorMessage().get().length(), "Error message length should be 10000");
  }

  @Test
  @Tag("valid")
  @DisplayName("Setting Error Message with Special Characters and Unicode")
  void errorMessageWithSpecialCharactersAndUnicode() {
    String specialCharsError = "Error: 文字化け 🚨 \"quoted\" \n\t";
    Optional<String> specialCharsOptional = Optional.of(specialCharsError);
    Event.Builder result = builder.errorMessage(specialCharsOptional);
    assertSame(builder, result, "Builder should return same instance for method chaining");
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertTrue(event.errorMessage().isPresent(), "Error message should be present");
    assertEquals(
        specialCharsError,
        event.errorMessage().get(),
        "Error message should preserve all special characters and Unicode");
  }

  @Test
  @Tag("boundary")
  @DisplayName("Setting Error Message with Empty String")
  void errorMessageWithEmptyString() {
    String emptyString = "";
    Optional<String> emptyStringOptional = Optional.of(emptyString);
    Event.Builder result = builder.errorMessage(emptyStringOptional);
    assertSame(builder, result, "Builder should return same instance for method chaining");
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertTrue(event.errorMessage().isPresent(), "Error message Optional should be present");
    assertEquals("", event.errorMessage().get(), "Error message should be an empty string");
  }

  @Test
  @Tag("integration")
  @DisplayName("Builder Method Chaining with Error Message")
  void errorMessageMethodChainingWithOtherBuilderMethods() {
    String testId = "test-id";
    String testAuthor = "test-author";
    String testError = "Test error";
    FinishReason testErrorCode = FinishReason.SAFETY;
    Event event =
        builder
            .id(testId)
            .author(testAuthor)
            .errorMessage(Optional.of(testError))
            .errorCode(Optional.of(testErrorCode))
            .invocationId("test-invocation")
            .build();
    assertNotNull(event, "Event should be built successfully");
    assertEquals(testId, event.id(), "ID should match");
    assertEquals(testAuthor, event.author(), "Author should match");
    assertTrue(event.errorMessage().isPresent(), "Error message should be present");
    assertEquals(testError, event.errorMessage().get(), "Error message should match");
    assertTrue(event.errorCode().isPresent(), "Error code should be present");
    assertEquals(testErrorCode, event.errorCode().get(), "Error code should match");
  }

  @Test
  @Tag("valid")
  @DisplayName("Setting Error Message After Building Event")
  void errorMessageSetAfterBuildDoesNotAffectBuiltEvent() {
    String initialError = "Initial error";
    String modifiedError = "Modified error";
    builder
        .id("test-id")
        .invocationId("test-invocation")
        .author("test-author")
        .errorMessage(Optional.of(initialError));
    Event event1 = builder.build();
    builder.errorMessage(Optional.of(modifiedError));
    Event event2 = builder.build();
    assertTrue(event1.errorMessage().isPresent(), "Event1 error message should be present");
    assertEquals(
        initialError, event1.errorMessage().get(), "Event1 should have initial error message");
    assertTrue(event2.errorMessage().isPresent(), "Event2 error message should be present");
    assertEquals(
        modifiedError, event2.errorMessage().get(), "Event2 should have modified error message");
  }

  @Test
  @Tag("boundary")
  @DisplayName("Setting Error Message with Whitespace-Only String")
  void errorMessageWithWhitespaceOnlyString() {
    String whitespaceString = "   \t\n  ";
    Optional<String> whitespaceOptional = Optional.of(whitespaceString);
    Event.Builder result = builder.errorMessage(whitespaceOptional);
    assertSame(builder, result, "Builder should return same instance for method chaining");
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertTrue(event.errorMessage().isPresent(), "Error message should be present");
    assertEquals(
        whitespaceString,
        event.errorMessage().get(),
        "Error message should preserve whitespace exactly");
  }

  @Test
  @Tag("integration")
  @DisplayName("Setting Error Message in Combination with Error Code")
  void errorMessageSetWithCorrespondingErrorCode() {
    FinishReason errorCode = FinishReason.SAFETY;
    String errorMessage = "Content filtered due to safety concerns";
    Event.Builder result1 = builder.errorCode(Optional.of(errorCode));
    assertSame(builder, result1, "errorCode should return same builder instance");
    Event.Builder result2 = builder.errorMessage(Optional.of(errorMessage));
    assertSame(builder, result2, "errorMessage should return same builder instance");
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertTrue(event.errorCode().isPresent(), "Error code should be present");
    assertEquals(errorCode, event.errorCode().get(), "Error code should match");
    assertTrue(event.errorMessage().isPresent(), "Error message should be present");
    assertEquals(errorMessage, event.errorMessage().get(), "Error message should match");
  }

  @Test
  @Tag("invalid")
  @DisplayName("Setting Error Message to Null Using Optional Parameter")
  void errorMessageWithNullOptionalParameter() {
    Optional<String> nullOptional = null;
    assertThrows(
        NullPointerException.class,
        () -> {
          builder.errorMessage(nullOptional);
        },
        "Should throw NullPointerException when Optional parameter is null");
  }
}
