/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-repo using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=finishReason_49a74cdb50
ROOST_METHOD_SIG_HASH=finishReason_1c1d2f5315

Scenario 1: Setting finishReason with a non-empty Optional containing a valid FinishReason value

Details:
  TestName: finishReasonWithNonEmptyOptional
  Description: This test verifies that the finishReason method correctly sets the finishReason field when provided with a non-empty Optional containing a valid FinishReason enum value. It ensures that the builder properly stores the value and returns itself for method chaining.
Execution:
  Arrange: Create a new Event.Builder instance. Create a non-empty Optional containing a FinishReason value (e.g., Optional.of(FinishReason.STOP)).
  Act: Invoke the finishReason method on the builder with the non-empty Optional as the parameter. Store the returned builder reference.
  Assert: Verify that the returned builder is the same instance as the original builder (for method chaining). Build the Event object and verify that the finishReason() method returns the expected Optional with the correct FinishReason value.
Validation:
  This assertion verifies that the builder correctly implements the fluent interface pattern by returning itself, allowing for method chaining. It also confirms that the finishReason field is properly set with the provided value. This is critical for building Event objects with specific finish reasons that indicate how content generation completed (e.g., natural stop, safety filters, max tokens).

Scenario 2: Setting finishReason with an empty Optional

Details:
  TestName: finishReasonWithEmptyOptional
  Description: This test validates that the finishReason method correctly handles an empty Optional, setting the finishReason field to Optional.empty(). This represents scenarios where no finish reason is available or applicable.
Execution:
  Arrange: Create a new Event.Builder instance. Create an empty Optional using Optional.empty().
  Act: Invoke the finishReason method on the builder with the empty Optional as the parameter.
  Assert: Build the Event object and verify that the finishReason() method returns Optional.empty(). Verify that the returned builder is the same instance for method chaining.
Validation:
  This test ensures that the builder can handle cases where no finish reason is provided, which is a valid state for events that are still in progress or where the finish reason is not yet determined. The empty Optional correctly represents the absence of a value without using null, following Java best practices.

Scenario 3: Setting finishReason multiple times with different values

Details:
  TestName: finishReasonOverwritesPreviousValue
  Description: This test verifies that calling the finishReason method multiple times on the same builder instance correctly overwrites the previous value with the new value, ensuring that only the last set value is retained.
Execution:
  Arrange: Create a new Event.Builder instance. Create two different Optional<FinishReason> values (e.g., Optional.of(FinishReason.STOP) and Optional.of(FinishReason.MAX_TOKENS)).
  Act: First, invoke finishReason with the first Optional value. Then, invoke finishReason again with the second Optional value on the same builder instance.
  Assert: Build the Event object and verify that the finishReason() method returns the second Optional value, confirming that the first value was overwritten.
Validation:
  This test confirms that the builder follows the expected behavior of setter methods where subsequent calls replace previous values rather than accumulating them. This is important for scenarios where the finish reason might need to be updated during the building process, ensuring that the final Event object reflects the most recent state.

Scenario 4: Setting finishReason and verifying builder method chaining

Details:
  TestName: finishReasonSupportsMethodChaining
  Description: This test validates that the finishReason method returns the builder instance itself, enabling fluent method chaining with other builder methods. This is a key characteristic of the builder pattern.
Execution:
  Arrange: Create a new Event.Builder instance. Prepare an Optional<FinishReason> value and other builder parameters (e.g., id, author).
  Act: Chain multiple builder methods together, including finishReason, in a single statement (e.g., builder.id("test-id").author("test-author").finishReason(Optional.of(FinishReason.STOP))).
  Assert: Verify that the chained method calls execute without errors. Build the Event object and verify that all chained values, including finishReason, are correctly set.
Validation:
  This test ensures that the builder implements the fluent interface pattern correctly, which improves code readability and usability. Method chaining is a fundamental aspect of the builder pattern, allowing developers to construct complex objects in a clean, readable manner. The @CanIgnoreReturnValue annotation on the method supports this pattern.

Scenario 5: Setting finishReason with null Optional reference

Details:
  TestName: finishReasonWithNullOptional
  Description: This test examines the behavior when the finishReason method is called with a null Optional reference. While the method signature accepts Optional<FinishReason>, passing null directly tests the robustness of the implementation.
Execution:
  Arrange: Create a new Event.Builder instance. Prepare a null reference for Optional<FinishReason>.
  Act: Invoke the finishReason method with the null Optional reference.
  Assert: Verify that the method either handles null gracefully (by storing it as-is) or throws a NullPointerException. Build the Event object and check the finishReason field state.
Validation:
  This test validates the builder's null-handling behavior. While Optional is designed to avoid null, developers might still pass null references. Understanding how the builder handles this edge case is important for defensive programming and preventing unexpected runtime errors. The expected behavior should align with the class's null-handling policy.

Scenario 6: Setting finishReason with different FinishReason enum values

Details:
  TestName: finishReasonWithVariousEnumValues
  Description: This test verifies that the finishReason method correctly handles all possible FinishReason enum values, ensuring compatibility with the complete range of finish reasons defined in the FinishReason enum.
Execution:
  Arrange: Create multiple Event.Builder instances. Prepare Optional values containing different FinishReason enum constants (e.g., STOP, MAX_TOKENS, SAFETY, RECITATION, OTHER).
  Act: For each builder instance, invoke the finishReason method with a different FinishReason enum value wrapped in Optional.
  Assert: For each builder, build the Event object and verify that the finishReason() method returns the correct Optional containing the expected FinishReason enum value.
Validation:
  This test ensures that the builder correctly handles all valid FinishReason enum values without any type-related issues or unexpected behavior. Since FinishReason is an enum type from the imported package, this test validates that the builder's integration with the enum type is complete and correct, supporting all possible finish reason scenarios in the application.

Scenario 7: Setting finishReason in combination with errorCode field

Details:
  TestName: finishReasonWithErrorCode
  Description: This test validates the interaction between finishReason and errorCode fields, as both are Optional<FinishReason> types. It ensures that setting both fields independently works correctly and that they maintain separate values.
Execution:
  Arrange: Create a new Event.Builder instance. Prepare two different Optional<FinishReason> values, one for finishReason and one for errorCode.
  Act: Invoke both finishReason and errorCode methods on the builder with their respective Optional values.
  Assert: Build the Event object and verify that both finishReason() and errorCode() methods return their respective Optional values correctly, confirming that the fields are independent.
Validation:
  This test is important because both finishReason and errorCode are of the same type (Optional<FinishReason>), and it's crucial to verify that they are stored and retrieved independently without any cross-contamination. This ensures that the builder correctly manages multiple fields of the same type, which is relevant for understanding both normal completion reasons and error conditions in the Event object.

Scenario 8: Building Event with only finishReason set and other fields at default values

Details:
  TestName: finishReasonWithMinimalBuilderConfiguration
  Description: This test verifies that an Event can be successfully built with only the finishReason field explicitly set, while other optional fields remain at their default values. This tests the builder's ability to create valid Event objects with minimal configuration.
Execution:
  Arrange: Create a new Event.Builder instance. Prepare an Optional<FinishReason> value. Do not set any other optional fields.
  Act: Invoke only the finishReason method on the builder. Call the build() method to create the Event object.
  Assert: Verify that the Event object is successfully created. Verify that finishReason() returns the expected value. Verify that other Optional fields return Optional.empty() or their default values.
Validation:
  This test validates that the builder can create valid Event objects even when only a subset of fields is configured. It ensures that the finishReason field can be set independently without requiring other fields to be set first. This is important for flexibility in Event creation, allowing developers to specify only the relevant fields for their use case while relying on sensible defaults for others.

Scenario 9: Setting finishReason after building and using toBuilder

Details:
  TestName: finishReasonModificationViaToBuilder
  Description: This test verifies that the finishReason value can be modified by using the toBuilder() method to create a new builder from an existing Event, changing the finishReason, and building a new Event object.
Execution:
  Arrange: Create an Event.Builder instance and set finishReason to an initial value (e.g., Optional.of(FinishReason.STOP)). Build the Event object. Call toBuilder() on the Event to get a new builder instance.
  Act: On the new builder, invoke finishReason with a different value (e.g., Optional.of(FinishReason.MAX_TOKENS)). Build a new Event object from this modified builder.
  Assert: Verify that the original Event object still has the original finishReason value. Verify that the new Event object has the updated finishReason value.
Validation:
  This test ensures that the toBuilder() method correctly copies the finishReason field and that modifications to the new builder don't affect the original Event object (immutability). It also validates that the finishReason field can be updated through the builder pattern, which is useful for creating modified copies of Event objects while preserving the original.

Scenario 10: Verifying finishReason field independence from other Optional fields

Details:
  TestName: finishReasonIndependenceFromOtherOptionalFields
  Description: This test validates that setting the finishReason field does not inadvertently affect other Optional fields in the builder, ensuring complete field independence.
Execution:
  Arrange: Create a new Event.Builder instance. Set multiple Optional fields including finishReason, partial, turnComplete, interrupted, and errorMessage with specific values.
  Act: Invoke the finishReason method with a specific Optional<FinishReason> value. Build the Event object.
  Assert: Verify that finishReason has the expected value. Verify that all other Optional fields retain their independently set values and are not affected by setting finishReason.
Validation:
  This test ensures proper encapsulation and field independence within the builder. Since the Event class has many Optional fields, it's critical to verify that setting one Optional field doesn't inadvertently affect others. This validates the correctness of the builder's internal state management and ensures that each field maintains its own independent value.

*/

// ********RoostGPT********

package com.google.adk.events;

import static com.google.common.truth.Truth.assertThat;
import static com.google.common.truth.Truth8.assertThat;

import com.google.genai.types.FinishReason;
import java.util.Optional;
import java.util.Set;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class BuilderFinishReason618Test {

  private Event.Builder builder;

  @BeforeEach
  void setUp() {
    builder = Event.builder();
  }

  @Test
  @Tag("valid")
  void finishReasonWithNonEmptyOptional() {
    // Arrange
    Optional<FinishReason> finishReasonValue = Optional.of(FinishReason.STOP);
    // Act
    Event.Builder returnedBuilder = builder.finishReason(finishReasonValue);
    // Assert
    assertThat(returnedBuilder).isSameInstanceAs(builder);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertThat(event.finishReason()).isEqualTo(finishReasonValue);
    assertThat(event.finishReason()).isPresent();
    assertThat(event.finishReason().get()).isEqualTo(FinishReason.STOP);
  }

  @Test
  @Tag("valid")
  void finishReasonWithEmptyOptional() {
    // Arrange
    Optional<FinishReason> emptyOptional = Optional.empty();
    // Act
    Event.Builder returnedBuilder = builder.finishReason(emptyOptional);
    // Assert
    assertThat(returnedBuilder).isSameInstanceAs(builder);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertThat(event.finishReason()).isEmpty();
  }

  @Test
  @Tag("valid")
  void finishReasonOverwritesPreviousValue() {
    // Arrange
    Optional<FinishReason> firstValue = Optional.of(FinishReason.STOP);
    Optional<FinishReason> secondValue = Optional.of(FinishReason.MAX_TOKENS);
    // Act
    builder.finishReason(firstValue);
    builder.finishReason(secondValue);
    // Assert
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertThat(event.finishReason()).isEqualTo(secondValue);
    assertThat(event.finishReason().get()).isEqualTo(FinishReason.MAX_TOKENS);
  }

  @Test
  @Tag("valid")
  void finishReasonSupportsMethodChaining() {
    // Arrange
    Optional<FinishReason> finishReasonValue = Optional.of(FinishReason.STOP);
    // Act
    Event event =
        builder
            .id("test-id")
            .author("test-author")
            .invocationId("test-invocation")
            .finishReason(finishReasonValue)
            .partial(true)
            .build();
    // Assert
    assertThat(event.id()).isEqualTo("test-id");
    assertThat(event.author()).isEqualTo("test-author");
    assertThat(event.invocationId()).isEqualTo("test-invocation");
    assertThat(event.finishReason()).isEqualTo(finishReasonValue);
    assertThat(event.partial()).isPresent();
    assertThat(event.partial().get()).isTrue();
  }

  @Test
  @Tag("invalid")
  void finishReasonWithNullOptional() {
    // Arrange
    Optional<FinishReason> nullOptional = null;
    // Act
    builder.finishReason(nullOptional);
    // Assert
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertThat(event.finishReason()).isNull();
  }

  @Test
  @Tag("valid")
  void finishReasonWithVariousEnumValues() {
    // Test with STOP
    builder = Event.builder();
    builder.finishReason(Optional.of(FinishReason.STOP));
    Event event1 =
        builder.id("test-id-1").invocationId("test-invocation").author("test-author").build();
    assertThat(event1.finishReason().get()).isEqualTo(FinishReason.STOP);
    // Test with MAX_TOKENS
    builder = Event.builder();
    builder.finishReason(Optional.of(FinishReason.MAX_TOKENS));
    Event event2 =
        builder.id("test-id-2").invocationId("test-invocation").author("test-author").build();
    assertThat(event2.finishReason().get()).isEqualTo(FinishReason.MAX_TOKENS);
    // Test with SAFETY
    builder = Event.builder();
    builder.finishReason(Optional.of(FinishReason.SAFETY));
    Event event3 =
        builder.id("test-id-3").invocationId("test-invocation").author("test-author").build();
    assertThat(event3.finishReason().get()).isEqualTo(FinishReason.SAFETY);
    // Test with RECITATION
    builder = Event.builder();
    builder.finishReason(Optional.of(FinishReason.RECITATION));
    Event event4 =
        builder.id("test-id-4").invocationId("test-invocation").author("test-author").build();
    assertThat(event4.finishReason().get()).isEqualTo(FinishReason.RECITATION);
    // Test with OTHER
    builder = Event.builder();
    builder.finishReason(Optional.of(FinishReason.OTHER));
    Event event5 =
        builder.id("test-id-5").invocationId("test-invocation").author("test-author").build();
    assertThat(event5.finishReason().get()).isEqualTo(FinishReason.OTHER);
  }

  @Test
  @Tag("valid")
  void finishReasonWithErrorCode() {
    // Arrange
    Optional<FinishReason> finishReasonValue = Optional.of(FinishReason.STOP);
    Optional<FinishReason> errorCodeValue = Optional.of(FinishReason.SAFETY);
    // Act
    Event event =
        builder
            .id("test-id")
            .invocationId("test-invocation")
            .author("test-author")
            .finishReason(finishReasonValue)
            .errorCode(errorCodeValue)
            .build();
    // Assert
    assertThat(event.finishReason()).isEqualTo(finishReasonValue);
    assertThat(event.finishReason().get()).isEqualTo(FinishReason.STOP);
    assertThat(event.errorCode()).isEqualTo(errorCodeValue);
    assertThat(event.errorCode().get()).isEqualTo(FinishReason.SAFETY);
  }

  @Test
  @Tag("boundary")
  void finishReasonWithMinimalBuilderConfiguration() {
    // Arrange
    Optional<FinishReason> finishReasonValue = Optional.of(FinishReason.MAX_TOKENS);
    // Act
    Event event =
        builder
            .id("test-id")
            .invocationId("test-invocation")
            .author("test-author")
            .finishReason(finishReasonValue)
            .build();
    // Assert
    assertThat(event).isNotNull();
    assertThat(event.finishReason()).isEqualTo(finishReasonValue);
    assertThat(event.content()).isEmpty();
    assertThat(event.partial()).isEmpty();
    assertThat(event.turnComplete()).isEmpty();
    assertThat(event.errorCode()).isEmpty();
    assertThat(event.errorMessage()).isEmpty();
    assertThat(event.interrupted()).isEmpty();
  }

  @Test
  @Tag("valid")
  void finishReasonModificationViaToBuilder() {
    // Arrange
    Optional<FinishReason> initialValue = Optional.of(FinishReason.STOP);
    Optional<FinishReason> updatedValue = Optional.of(FinishReason.MAX_TOKENS);
    Event originalEvent =
        builder
            .id("test-id")
            .invocationId("test-invocation")
            .author("test-author")
            .finishReason(initialValue)
            .build();
    // Act
    Event modifiedEvent = originalEvent.toBuilder().finishReason(updatedValue).build();
    // Assert
    assertThat(originalEvent.finishReason()).isEqualTo(initialValue);
    assertThat(originalEvent.finishReason().get()).isEqualTo(FinishReason.STOP);
    assertThat(modifiedEvent.finishReason()).isEqualTo(updatedValue);
    assertThat(modifiedEvent.finishReason().get()).isEqualTo(FinishReason.MAX_TOKENS);
  }

  @Test
  @Tag("valid")
  void finishReasonIndependenceFromOtherOptionalFields() {
    // Arrange
    Optional<FinishReason> finishReasonValue = Optional.of(FinishReason.STOP);
    Optional<Boolean> partialValue = Optional.of(true);
    Optional<Boolean> turnCompleteValue = Optional.of(false);
    Optional<Boolean> interruptedValue = Optional.of(true);
    Optional<String> errorMessageValue = Optional.of("Test error message");
    // Act
    Event event =
        builder
            .id("test-id")
            .invocationId("test-invocation")
            .author("test-author")
            .finishReason(finishReasonValue)
            .partial(partialValue)
            .turnComplete(turnCompleteValue)
            .interrupted(interruptedValue)
            .errorMessage(errorMessageValue)
            .build();
    // Assert
    assertThat(event.finishReason()).isEqualTo(finishReasonValue);
    assertThat(event.partial()).isEqualTo(partialValue);
    assertThat(event.turnComplete()).isEqualTo(turnCompleteValue);
    assertThat(event.interrupted()).isEqualTo(interruptedValue);
    assertThat(event.errorMessage()).isEqualTo(errorMessageValue);
  }

  @Test
  @Tag("valid")
  void finishReasonWithAllEnumValuesInSequence() {
    // Arrange & Act & Assert for each enum value
    for (FinishReason reason : FinishReason.values()) {
      Event.Builder testBuilder = Event.builder();
      Optional<FinishReason> optionalReason = Optional.of(reason);

      Event event =
          testBuilder
              .id("test-id-" + reason.name())
              .invocationId("test-invocation")
              .author("test-author")
              .finishReason(optionalReason)
              .build();

      assertThat(event.finishReason()).isPresent();
      assertThat(event.finishReason().get()).isEqualTo(reason);
    }
  }

  @Test
  @Tag("valid")
  void finishReasonReturnsSameBuilderInstance() {
    // Arrange
    Optional<FinishReason> finishReasonValue = Optional.of(FinishReason.STOP);
    // Act
    Event.Builder returnedBuilder1 = builder.finishReason(finishReasonValue);
    Event.Builder returnedBuilder2 =
        returnedBuilder1.finishReason(Optional.of(FinishReason.MAX_TOKENS));
    // Assert
    assertThat(returnedBuilder1).isSameInstanceAs(builder);
    assertThat(returnedBuilder2).isSameInstanceAs(builder);
  }

  @Test
  @Tag("boundary")
  void finishReasonWithEmptyOptionalAndOtherFieldsSet() {
    // Arrange
    Optional<FinishReason> emptyFinishReason = Optional.empty();
    // Act
    Event event =
        builder
            .id("test-id")
            .invocationId("test-invocation")
            .author("test-author")
            .finishReason(emptyFinishReason)
            .partial(true)
            .turnComplete(false)
            .errorMessage("Some error")
            .build();
    // Assert
    assertThat(event.finishReason()).isEmpty();
    assertThat(event.partial()).isPresent();
    assertThat(event.partial().get()).isTrue();
    assertThat(event.turnComplete()).isPresent();
    assertThat(event.turnComplete().get()).isFalse();
    assertThat(event.errorMessage()).isPresent();
  }

  @Test
  @Tag("integration")
  void finishReasonWithCompleteEventBuilding() {
    // Arrange
    Optional<FinishReason> finishReasonValue = Optional.of(FinishReason.STOP);
    Set<String> longRunningToolIds = Set.of("tool1", "tool2");
    // Act
    Event event =
        builder
            .id("complete-test-id")
            .invocationId("complete-invocation-id")
            .author("complete-author")
            .finishReason(finishReasonValue)
            .partial(false)
            .turnComplete(true)
            .longRunningToolIds(longRunningToolIds)
            .interrupted(false)
            .branch("main-branch")
            .modelVersion("v1.0.0")
            .build();
    // Assert
    assertThat(event.id()).isEqualTo("complete-test-id");
    assertThat(event.invocationId()).isEqualTo("complete-invocation-id");
    assertThat(event.author()).isEqualTo("complete-author");
    assertThat(event.finishReason()).isEqualTo(finishReasonValue);
    assertThat(event.partial()).isPresent();
    assertThat(event.partial().get()).isFalse();
    assertThat(event.turnComplete()).isPresent();
    assertThat(event.turnComplete().get()).isTrue();
    assertThat(event.longRunningToolIds()).isPresent();
    assertThat(event.longRunningToolIds().get()).containsExactly("tool1", "tool2");
    assertThat(event.interrupted()).isPresent();
    assertThat(event.interrupted().get()).isFalse();
    assertThat(event.branch()).isPresent();
    assertThat(event.branch().get()).isEqualTo("main-branch");
    assertThat(event.modelVersion()).isPresent();
    assertThat(event.modelVersion().get()).isEqualTo("v1.0.0");
  }
}
