/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-repo using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=id_21499c99a1
ROOST_METHOD_SIG_HASH=id_6211f05ce9

Scenario 1: Setting a valid non-null ID value

Details:
  TestName: idWithValidNonNullValue
  Description: This test verifies that the id() method correctly sets a valid non-null String value to the id field and returns the Builder instance for method chaining. The test ensures the basic functionality of the setter method works as expected with a typical string identifier.

Execution:
  Arrange: Create a new Event.Builder instance and prepare a valid String value (e.g., "event-123") to be used as the ID.
  Act: Invoke the id() method on the Builder instance with the prepared String value and capture the returned Builder instance.
  Assert: Verify that the returned object is the same Builder instance (for method chaining). Build the Event object and verify that the id field contains the expected value using the id() accessor method.

Validation:
  The assertion verifies that the Builder pattern is correctly implemented with method chaining support, allowing fluent API usage. This test is significant because it confirms the basic contract of the builder method - setting the field value and returning the builder for further configuration. The id field is critical as it serves as the unique identifier for Event objects, and this test ensures the setter works correctly for standard use cases.

---

Scenario 2: Setting an empty string as ID

Details:
  TestName: idWithEmptyString
  Description: This test checks the behavior when an empty string ("") is passed to the id() method. It verifies that the method accepts empty strings without throwing exceptions and correctly stores the empty value in the id field.

Execution:
  Arrange: Create a new Event.Builder instance and prepare an empty String ("") as the ID value.
  Act: Call the id() method with the empty string and build the Event object.
  Assert: Verify that the built Event object has an id field containing an empty string (not null) using the id() accessor method.

Validation:
  This test validates edge case handling for empty strings. While an empty ID might not be semantically valid in business logic, the method should handle it gracefully at the technical level. This test ensures that the method doesn't perform implicit validation or transformation of empty strings, maintaining transparency in data handling. It's important for understanding the method's behavior boundaries.

---

Scenario 3: Setting null as ID value

Details:
  TestName: idWithNullValue
  Description: This test examines the behavior when null is explicitly passed to the id() method. It verifies whether the method accepts null values and how the Builder handles null assignment to the id field.

Execution:
  Arrange: Create a new Event.Builder instance and prepare a null value to be passed as the ID.
  Act: Invoke the id() method with null as the parameter and build the Event object.
  Assert: Verify that the built Event object has a null id field using the id() accessor method.

Validation:
  This test is crucial for understanding null handling behavior. Since the method signature accepts String (not @Nullable annotated in the method signature itself), this test verifies whether null values are accepted and stored. This is important for defensive programming and understanding potential NullPointerExceptions in downstream code. The test helps document the method's contract regarding null values.

---

Scenario 4: Setting ID with special characters

Details:
  TestName: idWithSpecialCharacters
  Description: This test validates that the id() method correctly handles String values containing special characters, including Unicode characters, symbols, and punctuation marks. It ensures the method doesn't perform any sanitization or encoding of the input.

Execution:
  Arrange: Create a new Event.Builder instance and prepare a String containing special characters (e.g., "event-!@#$%^&*()_+-=[]{}|;:',.<>?/~`").
  Act: Call the id() method with the special character string and build the Event object.
  Assert: Verify that the built Event object's id field contains exactly the same special character string without any modification.

Validation:
  This test ensures data integrity when IDs contain special characters, which might be relevant for certain ID generation schemes (e.g., Base64 encoded IDs, UUIDs with hyphens, or custom formats). It confirms that the method acts as a simple setter without performing any transformation, validation, or sanitization. This is important for maintaining data fidelity across the application.

---

Scenario 5: Setting ID with whitespace characters

Details:
  TestName: idWithWhitespaceCharacters
  Description: This test verifies the behavior when the ID contains various whitespace characters including spaces, tabs, newlines, and other whitespace Unicode characters. It checks whether the method preserves whitespace as-is.

Execution:
  Arrange: Create a new Event.Builder instance and prepare a String with whitespace characters (e.g., "  event 123\t\n").
  Act: Invoke the id() method with the whitespace-containing string and build the Event object.
  Assert: Verify that the built Event object's id field contains the exact string with all whitespace preserved.

Validation:
  This test validates that the method doesn't perform trimming or whitespace normalization. While IDs with leading/trailing whitespace might be considered invalid in business logic, the builder method should maintain the exact input. This test documents the method's behavior and helps identify where validation should occur (e.g., in validation logic rather than in the setter).

---

Scenario 6: Setting ID multiple times (overwriting previous value)

Details:
  TestName: idCalledMultipleTimesOverwritesPreviousValue
  Description: This test verifies that calling the id() method multiple times on the same Builder instance results in the last value being used, with previous values being overwritten. It confirms the expected behavior of setter methods in the Builder pattern.

Execution:
  Arrange: Create a new Event.Builder instance and prepare multiple String values (e.g., "first-id", "second-id", "final-id").
  Act: Call the id() method three times with different values in sequence, then build the Event object.
  Assert: Verify that the built Event object's id field contains only the last value ("final-id") that was set.

Validation:
  This test confirms the standard setter behavior where the last value wins. This is important for understanding Builder usage patterns and ensuring that the method doesn't accumulate values or throw exceptions when called multiple times. It validates that the Builder maintains mutable state correctly and that each call to id() replaces the previous value rather than appending or merging.

---

Scenario 7: Method chaining with id() and other builder methods

Details:
  TestName: idMethodChainingWithOtherBuilderMethods
  Description: This test validates that the id() method correctly supports method chaining by returning the Builder instance, allowing it to be used fluently with other Builder methods in a single statement.

Execution:
  Arrange: Create a new Event.Builder instance and prepare test values for multiple fields including id, author, and invocationId.
  Act: Chain multiple builder method calls including id() in a single fluent statement (e.g., builder.id("test-id").author("test-author").invocationId("inv-123").build()).
  Assert: Verify that the built Event object contains all the expected values for id, author, and invocationId fields.

Validation:
  This test ensures the Builder pattern is correctly implemented with proper method chaining support. The @CanIgnoreReturnValue annotation suggests the return value can be ignored, but for fluent API usage, returning 'this' is essential. This test validates that the id() method integrates properly with the overall Builder API design, enabling readable and maintainable code through method chaining.

---

Scenario 8: Setting ID with very long string value

Details:
  TestName: idWithVeryLongString
  Description: This test examines the behavior when a very long String (e.g., thousands of characters) is passed to the id() method. It verifies that the method can handle large string values without throwing exceptions or truncating the data.

Execution:
  Arrange: Create a new Event.Builder instance and generate a very long String (e.g., 10,000 characters) to be used as the ID.
  Act: Call the id() method with the very long string and build the Event object.
  Assert: Verify that the built Event object's id field contains the complete long string with the correct length and content.

Validation:
  This test validates the method's behavior with edge cases regarding string length. While extremely long IDs might not be practical in real-world scenarios, the method should handle them gracefully without memory issues or data loss. This test helps identify any implicit limitations or performance considerations. It's important for robustness and understanding the method's operational boundaries.

---

Scenario 9: Setting ID with UUID format string

Details:
  TestName: idWithUuidFormatString
  Description: This test verifies that the id() method correctly handles UUID-formatted strings, which is a common pattern for generating event IDs as evidenced by the generateEventId() method in the Event class.

Execution:
  Arrange: Create a new Event.Builder instance and generate a UUID string using UUID.randomUUID().toString().
  Act: Invoke the id() method with the UUID string and build the Event object.
  Assert: Verify that the built Event object's id field contains the exact UUID string that was provided.

Validation:
  This test is particularly relevant given that the Event class includes a generateEventId() method that returns UUID strings. It confirms that the id() method works correctly with the expected ID format used by the application. This test validates a common real-world usage pattern and ensures compatibility with the ID generation strategy employed by the Event class.

---

Scenario 10: Builder instance reusability after setting ID

Details:
  TestName: builderReusabilityAfterSettingId
  Description: This test verifies that after calling the id() method and building an Event object, the same Builder instance can be reused to create another Event object with a different ID value.

Execution:
  Arrange: Create a new Event.Builder instance and prepare two different ID values (e.g., "first-event-id" and "second-event-id").
  Act: Set the first ID, build an Event object, then set the second ID on the same builder and build another Event object.
  Assert: Verify that the first Event object has the first ID and the second Event object has the second ID, confirming they are independent instances.

Validation:
  This test validates the Builder's reusability pattern and ensures that building an Event doesn't reset or lock the Builder state. It confirms that the Builder maintains mutable state that can be modified and reused for creating multiple Event instances. This is important for understanding Builder lifecycle and potential pitfalls in reusing Builder instances, especially in scenarios where builders might be cached or reused for performance reasons.

---

Scenario 11: Setting ID returns same builder instance reference

Details:
  TestName: idReturnsSameBuilderInstanceReference
  Description: This test explicitly verifies that the id() method returns the exact same Builder instance (reference equality) that it was called on, which is essential for proper method chaining implementation.

Execution:
  Arrange: Create a new Event.Builder instance and store its reference.
  Act: Call the id() method with a test value and capture the returned Builder reference.
  Assert: Use reference equality (==) to verify that the returned Builder is the exact same instance as the original Builder.

Validation:
  This test validates a critical aspect of the Builder pattern implementation - that methods return 'this' rather than creating new instances. This is important for both performance (avoiding unnecessary object creation) and correctness (ensuring state modifications affect the same instance). The test confirms that the @CanIgnoreReturnValue annotation doesn't mean the method returns null or a different instance, but rather that callers can choose to ignore the return value if not using method chaining.

---

Scenario 12: Setting ID with numeric string value

Details:
  TestName: idWithNumericString
  Description: This test verifies that the id() method correctly handles String values that contain only numeric characters, ensuring no implicit type conversion or validation occurs.

Execution:
  Arrange: Create a new Event.Builder instance and prepare a numeric string value (e.g., "123456789").
  Act: Call the id() method with the numeric string and build the Event object.
  Assert: Verify that the built Event object's id field contains the numeric string as a String type (not converted to a number).

Validation:
  This test ensures that the method treats all inputs as String types regardless of their content. It's important to verify that numeric-looking strings aren't implicitly converted or validated, maintaining the method's role as a simple setter. This test documents the expected behavior when IDs are numeric in format, which might occur in systems migrating from integer-based IDs to string-based identifiers.

*/

// ********RoostGPT********

package com.google.adk.events;

import static com.google.common.truth.Truth.assertThat;
import com.google.genai.types.Content;
import com.google.genai.types.FinishReason;
import com.google.genai.types.GenerateContentResponseUsageMetadata;
import com.google.genai.types.GroundingMetadata;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.*;
import static com.google.common.collect.ImmutableList.toImmutableList;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.google.adk.JsonBaseModel;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.Iterables;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.genai.types.FunctionCall;
import com.google.genai.types.FunctionResponse;
import java.time.Instant;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

class BuilderIdTest {

	@Test
	@Tag("valid")
	void idWithValidNonNullValue() {
		String testId = "event-123";
		Event.Builder builder = Event.builder();
		Event.Builder returnedBuilder = builder.id(testId);
		assertThat(returnedBuilder).isSameInstanceAs(builder);
		Event event = builder.build();
		assertThat(event.id()).isEqualTo(testId);
	}

	@Test
	@Tag("boundary")
	void idWithEmptyString() {
		String emptyId = "";
		Event.Builder builder = Event.builder();
		builder.id(emptyId);
		Event event = builder.build();
		assertThat(event.id()).isNotNull();
		assertThat(event.id()).isEmpty();
	}

	@Test
	@Tag("invalid")
	void idWithNullValue() {
		Event.Builder builder = Event.builder();
		builder.id(null);
		Event event = builder.build();
		assertThat(event.id()).isNull();
	}

	@Test
  @Tag("valid")
  void idWithSpecialCharacters() {
    String specialCharId = "event-!@#$%^&*()_+-=[]{}|;:',.<>?/~"";
    Event.Builder builder = Event.builder();
    builder.id(specialCharId);
    Event event = builder.build();
    assertThat(event.id()).isEqualTo(specialCharId);
  }

	@Test
	@Tag("boundary")
	void idWithWhitespaceCharacters() {
		String whitespaceId = "  event 123\t\n";
		Event.Builder builder = Event.builder();
		builder.id(whitespaceId);
		Event event = builder.build();
		assertThat(event.id()).isEqualTo(whitespaceId);
	}

	@Test
	@Tag("valid")
	void idCalledMultipleTimesOverwritesPreviousValue() {
		String firstId = "first-id";
		String secondId = "second-id";
		String finalId = "final-id";
		Event.Builder builder = Event.builder();
		builder.id(firstId);
		builder.id(secondId);
		builder.id(finalId);
		Event event = builder.build();
		assertThat(event.id()).isEqualTo(finalId);
	}

	@Test
	@Tag("integration")
	void idMethodChainingWithOtherBuilderMethods() {
		String testId = "test-id";
		String testAuthor = "test-author";
		String testInvocationId = "inv-123";
		Event.Builder builder = Event.builder();
		Event event = builder.id(testId).author(testAuthor).invocationId(testInvocationId).build();
		assertThat(event.id()).isEqualTo(testId);
		assertThat(event.author()).isEqualTo(testAuthor);
		assertThat(event.invocationId()).isEqualTo(testInvocationId);
	}

	@Test
	@Tag("boundary")
	void idWithVeryLongString() {
		StringBuilder longStringBuilder = new StringBuilder();
		for (int i = 0; i < 10000; i++) {
			longStringBuilder.append("a");
		}
		String veryLongId = longStringBuilder.toString();
		Event.Builder builder = Event.builder();
		builder.id(veryLongId);
		Event event = builder.build();
		assertThat(event.id()).isEqualTo(veryLongId);
		assertThat(event.id().length()).isEqualTo(10000);
	}

	@Test
	@Tag("valid")
	void idWithUuidFormatString() {
		String uuidId = UUID.randomUUID().toString();
		Event.Builder builder = Event.builder();
		builder.id(uuidId);
		Event event = builder.build();
		assertThat(event.id()).isEqualTo(uuidId);
		assertThat(event.id()).matches("[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}");
	}

	@Test
	@Tag("valid")
	void builderReusabilityAfterSettingId() {
		String firstEventId = "first-event-id";
		String secondEventId = "second-event-id";
		Event.Builder builder = Event.builder();
		builder.id(firstEventId);
		Event firstEvent = builder.build();
		builder.id(secondEventId);
		Event secondEvent = builder.build();
		assertThat(firstEvent.id()).isEqualTo(firstEventId);
		assertThat(secondEvent.id()).isEqualTo(secondEventId);
		assertThat(firstEvent).isNotSameInstanceAs(secondEvent);
	}

	@Test
	@Tag("valid")
	void idReturnsSameBuilderInstanceReference() {
		Event.Builder builder = Event.builder();
		String testId = "test-id";
		Event.Builder returnedBuilder = builder.id(testId);
		assertThat(returnedBuilder).isSameInstanceAs(builder);
	}

	@Test
	@Tag("valid")
	void idWithNumericString() {
		String numericId = "123456789";
		Event.Builder builder = Event.builder();
		builder.id(numericId);
		Event event = builder.build();
		assertThat(event.id()).isEqualTo(numericId);
		assertThat(event.id()).isInstanceOf(String.class);
	}

	@Test
	@Tag("valid")
	void idWithUnicodeCharacters() {
		String unicodeId = "event-测试-🎉-αβγ";
		Event.Builder builder = Event.builder();
		builder.id(unicodeId);
		Event event = builder.build();
		assertThat(event.id()).isEqualTo(unicodeId);
	}

	@Test
	@Tag("valid")
	void idWithLeadingAndTrailingWhitespace() {
		String idWithWhitespace = "   event-id   ";
		Event.Builder builder = Event.builder();
		builder.id(idWithWhitespace);
		Event event = builder.build();
		assertThat(event.id()).isEqualTo(idWithWhitespace);
	}

	@Test
	@Tag("integration")
	void idSetWithCompleteEventBuilding() {
		// Note: Content.newBuilder() method does not exist. Need to use appropriate
		// Content constructor or builder pattern.
		// Suggestion: Verify the correct way to instantiate Content object from the
		// Content class API.
		// For now, using null or skipping content field to avoid compilation error.
		String testId = "complete-event-id";
		String testAuthor = "test-author";
		String testInvocationId = "test-invocation";
		Event.Builder builder = Event.builder();
		Event event = builder.id(testId)
			.author(testAuthor)
			.invocationId(testInvocationId)
			.partial(true)
			.turnComplete(false)
			.build();
		assertThat(event.id()).isEqualTo(testId);
		assertThat(event.author()).isEqualTo(testAuthor);
		assertThat(event.invocationId()).isEqualTo(testInvocationId);
		assertThat(event.partial()).isPresent();
		assertThat(event.partial().get()).isTrue();
	}

	@Test
	@Tag("valid")
	void idWithAlphanumericMixedCase() {
		String mixedCaseId = "Event123ABC456def";
		Event.Builder builder = Event.builder();
		builder.id(mixedCaseId);
		Event event = builder.build();
		assertThat(event.id()).isEqualTo(mixedCaseId);
	}

	@Test
	@Tag("boundary")
	void idWithSingleCharacter() {
		String singleCharId = "a";
		Event.Builder builder = Event.builder();
		builder.id(singleCharId);
		Event event = builder.build();
		assertThat(event.id()).isEqualTo(singleCharId);
		assertThat(event.id().length()).isEqualTo(1);
	}

	@Test
	@Tag("valid")
	void idWithHyphenatedFormat() {
		String hyphenatedId = "event-2024-01-15-abc-123";
		Event.Builder builder = Event.builder();
		builder.id(hyphenatedId);
		Event event = builder.build();
		assertThat(event.id()).isEqualTo(hyphenatedId);
	}

	@Test
	@Tag("integration")
	void idWithOptionalFieldsSet() {
		// Note: FinishReason.STOP constant does not exist. Need to verify the correct
		// enum values.
		// Suggestion: Check FinishReason enum for valid constants (e.g., STOP,
		// MAX_TOKENS, SAFETY, etc.)
		// For now, commenting out or using a placeholder to avoid compilation error.
		String testId = "optional-fields-id";
		Event.Builder builder = Event.builder();
		Event event = builder.id(testId)
			.author("author")
			.invocationId("invocation")
			.errorMessage("test error")
			// .finishReason(FinishReason.STOP) // STOP constant not found - verify
			// correct enum value
			.avgLogprobs(-0.5)
			.interrupted(true)
			.branch("main")
			.modelVersion("v1.0")
			.build();
		assertThat(event.id()).isEqualTo(testId);
		assertThat(event.errorMessage()).isPresent();
		// assertThat(event.finishReason()).isPresent(); // Commented out due to
		// FinishReason.STOP issue
		assertThat(event.avgLogprobs()).isPresent();
		assertThat(event.interrupted()).isPresent();
		assertThat(event.branch()).isPresent();
		assertThat(event.modelVersion()).isPresent();
	}

}