/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-repo using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=errorMessage_eb7c0e02a9
ROOST_METHOD_SIG_HASH=errorMessage_bb5758c7eb

Scenario 1: Setting a non-null error message value

Details:
  TestName: errorMessageWithNonNullValue
  Description: This test verifies that the errorMessage method correctly accepts a non-null String value and wraps it in an Optional. It ensures that the builder properly stores the error message and returns the builder instance for method chaining.

Execution:
  Arrange: Create a new Event.Builder instance and prepare a non-null error message String (e.g., "Connection timeout error").
  Act: Invoke the errorMessage method with the non-null String value and capture the returned Builder instance.
  Assert: Verify that the returned object is the same Builder instance (for method chaining). Build the Event and verify that the errorMessage field contains an Optional with the provided value.

Validation:
  This assertion verifies that the builder correctly implements the fluent API pattern by returning itself, allowing method chaining. It also confirms that non-null error messages are properly wrapped in an Optional and stored in the builder. This is critical for capturing error information during event processing and ensuring that error messages can be properly serialized and deserialized.

---

Scenario 2: Setting a null error message value

Details:
  TestName: errorMessageWithNullValue
  Description: This test verifies that the errorMessage method correctly handles a null String value by wrapping it in an empty Optional. It ensures that passing null does not cause a NullPointerException and properly represents the absence of an error message.

Execution:
  Arrange: Create a new Event.Builder instance and prepare a null String value.
  Act: Invoke the errorMessage method with the null value and capture the returned Builder instance.
  Assert: Verify that the returned object is the same Builder instance. Build the Event and verify that the errorMessage field contains an empty Optional.

Validation:
  This assertion verifies that the method safely handles null values using Optional.ofNullable(), which is the expected behavior for nullable parameters annotated with @Nullable. This prevents NullPointerException and provides a clean way to represent the absence of an error message. This is important for scenarios where events are created without errors or when error information is not yet available.

---

Scenario 3: Method chaining with errorMessage

Details:
  TestName: errorMessageMethodChaining
  Description: This test verifies that the errorMessage method supports fluent API method chaining by returning the Builder instance. It ensures that multiple builder methods can be called in sequence, including errorMessage.

Execution:
  Arrange: Create a new Event.Builder instance and prepare test values for multiple fields including an error message.
  Act: Chain multiple builder method calls including id(), author(), and errorMessage() in a single statement.
  Assert: Verify that the chaining executes without errors and that the final built Event contains all the set values, including the error message.

Validation:
  This assertion verifies that the @CanIgnoreReturnValue annotation and the return type of Builder enable proper method chaining, which is a common pattern in builder implementations. This is essential for creating readable and maintainable code when constructing Event objects with multiple properties. The fluent API pattern improves developer experience and code clarity.

---

Scenario 4: Setting error message with empty string

Details:
  TestName: errorMessageWithEmptyString
  Description: This test verifies that the errorMessage method correctly handles an empty String ("") as a valid value. It ensures that empty strings are treated as valid error messages and are wrapped in an Optional containing the empty string, not an empty Optional.

Execution:
  Arrange: Create a new Event.Builder instance and prepare an empty String value ("").
  Act: Invoke the errorMessage method with the empty String value.
  Assert: Build the Event and verify that the errorMessage field contains an Optional with an empty String value (Optional.of("")), not Optional.empty().

Validation:
  This assertion verifies that the method distinguishes between null (absence of value) and empty string (present but empty value). This distinction is important for business logic where an empty error message might have different semantics than no error message at all. It ensures that Optional.ofNullable() correctly wraps non-null values, even when they are empty strings.

---

Scenario 5: Setting error message multiple times

Details:
  TestName: errorMessageOverwritesPreviousValue
  Description: This test verifies that calling the errorMessage method multiple times on the same Builder instance correctly overwrites the previous value with the most recent one. It ensures that the builder maintains only the last set value.

Execution:
  Arrange: Create a new Event.Builder instance and prepare two different error message Strings (e.g., "First error" and "Second error").
  Act: Invoke the errorMessage method first with "First error", then invoke it again with "Second error" on the same builder instance.
  Assert: Build the Event and verify that the errorMessage field contains an Optional with only the second value ("Second error").

Validation:
  This assertion verifies that the builder correctly implements the last-write-wins semantics, which is the expected behavior for setter methods. This is important for scenarios where error messages might be updated during event construction or when builders are reused. It ensures that the final state of the builder reflects the most recent method call.

---

Scenario 6: Setting error message after setting to null

Details:
  TestName: errorMessageSetAfterNull
  Description: This test verifies that the errorMessage method can set a valid error message after previously setting it to null. It ensures that the builder can transition from an empty Optional to a populated Optional.

Execution:
  Arrange: Create a new Event.Builder instance.
  Act: First invoke the errorMessage method with null, then invoke it again with a non-null String value (e.g., "Recovery error message").
  Assert: Build the Event and verify that the errorMessage field contains an Optional with the non-null value, not an empty Optional.

Validation:
  This assertion verifies that the builder allows state transitions and that setting a value after null properly replaces the empty Optional with a populated one. This is important for scenarios where error information becomes available after initial builder creation or when builders are reused with different configurations.

---

Scenario 7: Setting error message with whitespace-only string

Details:
  TestName: errorMessageWithWhitespaceOnlyString
  Description: This test verifies that the errorMessage method correctly handles a String containing only whitespace characters (e.g., "   "). It ensures that whitespace-only strings are treated as valid values and not converted to null or empty Optional.

Execution:
  Arrange: Create a new Event.Builder instance and prepare a String containing only whitespace characters (e.g., "   " or "\t\n").
  Act: Invoke the errorMessage method with the whitespace-only String value.
  Assert: Build the Event and verify that the errorMessage field contains an Optional with the whitespace String value, preserving the exact input.

Validation:
  This assertion verifies that the method does not perform any trimming or validation on the input String, treating whitespace-only strings as valid values. This is important for maintaining data integrity and ensuring that the builder does not make assumptions about what constitutes a valid error message. The responsibility for validation should lie with the caller or separate validation logic.

---

Scenario 8: Setting error message with special characters

Details:
  TestName: errorMessageWithSpecialCharacters
  Description: This test verifies that the errorMessage method correctly handles Strings containing special characters, including Unicode characters, newlines, tabs, and other non-alphanumeric characters. It ensures that all valid String values are properly stored without corruption.

Execution:
  Arrange: Create a new Event.Builder instance and prepare a String with special characters (e.g., "Error: Connection failed\nDetails: 网络错误 @#$%^&*()").
  Act: Invoke the errorMessage method with the special characters String value.
  Assert: Build the Event and verify that the errorMessage field contains an Optional with the exact String value, including all special characters.

Validation:
  This assertion verifies that the method correctly handles all valid String values without any character encoding issues or data loss. This is critical for internationalization support and for preserving detailed error messages that might contain stack traces, JSON, or other formatted content. It ensures that the builder is robust enough to handle real-world error messages.

---

Scenario 9: Setting error message in combination with errorCode

Details:
  TestName: errorMessageWithErrorCode
  Description: This test verifies that the errorMessage method works correctly in combination with the errorCode field. It ensures that both error-related fields can be set independently and that they coexist properly in the built Event.

Execution:
  Arrange: Create a new Event.Builder instance and prepare an error message String and a FinishReason value for errorCode.
  Act: Invoke both the errorMessage method with a String value and the errorCode method with a FinishReason value.
  Assert: Build the Event and verify that both the errorMessage and errorCode fields contain their respective values wrapped in Optionals.

Validation:
  This assertion verifies that the errorMessage field is independent of other error-related fields and that setting one does not affect the other. This is important for comprehensive error reporting where both a machine-readable error code and a human-readable error message are needed. It ensures that the builder supports rich error information capture.

---

Scenario 10: Setting error message with very long string

Details:
  TestName: errorMessageWithVeryLongString
  Description: This test verifies that the errorMessage method correctly handles very long String values (e.g., thousands of characters). It ensures that there are no length limitations imposed by the method itself.

Execution:
  Arrange: Create a new Event.Builder instance and prepare a very long String (e.g., 10,000 characters) containing a detailed error message or stack trace.
  Act: Invoke the errorMessage method with the very long String value.
  Assert: Build the Event and verify that the errorMessage field contains an Optional with the complete long String value without truncation.

Validation:
  This assertion verifies that the method does not impose arbitrary length restrictions on error messages. This is important for capturing detailed error information such as full stack traces, detailed diagnostic information, or concatenated error messages from multiple sources. It ensures that the builder can handle real-world scenarios where error messages can be quite lengthy.

---

Scenario 11: Builder instance returned is same reference

Details:
  TestName: errorMessageReturnsSameBuilderInstance
  Description: This test verifies that the errorMessage method returns the exact same Builder instance (not a copy or new instance) to enable proper method chaining and maintain builder state.

Execution:
  Arrange: Create a new Event.Builder instance and store its reference.
  Act: Invoke the errorMessage method with any String value and capture the returned Builder reference.
  Assert: Verify using reference equality (==) that the returned Builder is the exact same instance as the original builder.

Validation:
  This assertion verifies that the method implements the builder pattern correctly by returning 'this' rather than creating a new builder instance. This is crucial for performance (avoiding unnecessary object creation) and for ensuring that all method calls operate on the same builder state. It confirms that the @CanIgnoreReturnValue annotation is used appropriately for a fluent API.

---

Scenario 12: Error message persists through build operation

Details:
  TestName: errorMessagePersistsAfterBuild
  Description: This test verifies that the error message set in the builder is correctly transferred to the built Event object and that the builder can be reused to build multiple Event instances with the same error message.

Execution:
  Arrange: Create a new Event.Builder instance and set an error message value.
  Act: Build an Event instance, then build a second Event instance from the same builder without modifying the error message.
  Assert: Verify that both Event instances contain the same error message value in their errorMessage fields.

Validation:
  This assertion verifies that the builder correctly transfers state to built objects and that the builder can be reused. This is important for scenarios where multiple similar Event objects need to be created with the same error information. It ensures that the builder maintains its state across multiple build operations unless explicitly modified.

*/

// ********RoostGPT********

package com.google.adk.events;

import static com.google.common.truth.Truth.assertThat;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertSame;

import com.google.genai.types.FinishReason;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

public class BuilderErrorMessageTest {

  private Event.Builder builder;

  @BeforeEach
  public void setUp() {
    builder = Event.builder();
  }

  @Test
  @Tag("valid")
  public void errorMessageWithNonNullValue() {
    String errorMessage = "Connection timeout error";
    Event.Builder returnedBuilder = builder.errorMessage(errorMessage);
    assertSame(builder, returnedBuilder);
    Event event = builder.build();
    assertThat(event.errorMessage()).isEqualTo(Optional.of(errorMessage));
  }

  @Test
  @Tag("valid")
  public void errorMessageWithNullValue() {
    Event.Builder returnedBuilder = builder.errorMessage((String) null);
    assertSame(builder, returnedBuilder);
    Event event = builder.build();
    assertThat(event.errorMessage()).isEqualTo(Optional.empty());
  }

  @Test
  @Tag("valid")
  public void errorMessageMethodChaining() {
    String id = "test-id-123";
    String author = "test-author";
    String errorMessage = "Test error message";
    Event event =
        builder
            .id(id)
            .author(author)
            .errorMessage(errorMessage)
            .invocationId("invocation-123")
            .build();
    assertThat(event.id()).isEqualTo(id);
    assertThat(event.author()).isEqualTo(author);
    assertThat(event.errorMessage()).isEqualTo(Optional.of(errorMessage));
  }

  @Test
  @Tag("boundary")
  public void errorMessageWithEmptyString() {
    String emptyString = "";
    builder.errorMessage(emptyString);
    Event event = builder.build();
    assertThat(event.errorMessage()).isEqualTo(Optional.of(emptyString));
    assertThat(event.errorMessage()).isNotEqualTo(Optional.empty());
  }

  @Test
  @Tag("valid")
  public void errorMessageOverwritesPreviousValue() {
    String firstError = "First error";
    String secondError = "Second error";
    builder.errorMessage(firstError);
    builder.errorMessage(secondError);
    Event event = builder.build();
    assertThat(event.errorMessage()).isEqualTo(Optional.of(secondError));
  }

  @Test
  @Tag("valid")
  public void errorMessageSetAfterNull() {
    String recoveryMessage = "Recovery error message";
    builder.errorMessage((String) null);
    builder.errorMessage(recoveryMessage);
    Event event = builder.build();
    assertThat(event.errorMessage()).isEqualTo(Optional.of(recoveryMessage));
    assertThat(event.errorMessage()).isNotEqualTo(Optional.empty());
  }

  @Test
  @Tag("boundary")
  public void errorMessageWithWhitespaceOnlyString() {
    String whitespaceString = "   ";
    builder.errorMessage(whitespaceString);
    Event event = builder.build();
    assertThat(event.errorMessage()).isEqualTo(Optional.of(whitespaceString));
  }

  @Test
  @Tag("valid")
  public void errorMessageWithSpecialCharacters() {
    String specialCharsMessage = "Error: Connection failed\nDetails: 网络错误 @#$%^&*()";
    builder.errorMessage(specialCharsMessage);
    Event event = builder.build();
    assertThat(event.errorMessage()).isEqualTo(Optional.of(specialCharsMessage));
  }

  @Test
  @Tag("integration")
  public void errorMessageWithErrorCode() {
    String errorMessage = "Internal server error";
    FinishReason errorCode = FinishReason.SAFETY;
    builder.errorMessage(errorMessage);
    builder.errorCode(errorCode);
    Event event = builder.build();
    assertThat(event.errorMessage()).isEqualTo(Optional.of(errorMessage));
    assertThat(event.errorCode()).isEqualTo(Optional.of(errorCode));
  }

  @Test
  @Tag("boundary")
  public void errorMessageWithVeryLongString() {
    StringBuilder longMessageBuilder = new StringBuilder();
    for (int i = 0; i < 10000; i++) {
      longMessageBuilder.append("A");
    }
    String longMessage = longMessageBuilder.toString();
    builder.errorMessage(longMessage);
    Event event = builder.build();
    assertThat(event.errorMessage()).isEqualTo(Optional.of(longMessage));
    assertThat(event.errorMessage().get().length()).isEqualTo(10000);
  }

  @Test
  @Tag("valid")
  public void errorMessageReturnsSameBuilderInstance() {
    String errorMessage = "Test error";
    Event.Builder returnedBuilder = builder.errorMessage(errorMessage);
    assertSame(builder, returnedBuilder);
  }

  @Test
  @Tag("valid")
  public void errorMessagePersistsAfterBuild() {
    String errorMessage = "Persistent error message";
    builder.errorMessage(errorMessage);
    Event firstEvent = builder.build();
    Event secondEvent = builder.build();
    assertThat(firstEvent.errorMessage()).isEqualTo(Optional.of(errorMessage));
    assertThat(secondEvent.errorMessage()).isEqualTo(Optional.of(errorMessage));
    assertThat(firstEvent.errorMessage()).isEqualTo(secondEvent.errorMessage());
  }

  @Test
  @Tag("boundary")
  public void errorMessageWithTabsAndNewlines() {
    String messageWithWhitespace = "Error:\tConnection\nfailed\r\nRetry";
    builder.errorMessage(messageWithWhitespace);
    Event event = builder.build();
    assertThat(event.errorMessage()).isEqualTo(Optional.of(messageWithWhitespace));
  }

  @Test
  @Tag("valid")
  public void errorMessageWithNumericString() {
    String numericMessage = "12345";
    builder.errorMessage(numericMessage);
    Event event = builder.build();
    assertThat(event.errorMessage()).isEqualTo(Optional.of(numericMessage));
  }

  @Test
  @Tag("valid")
  public void errorMessageBuilderStateIndependence() {
    String errorMessage = "Test error";
    builder.errorMessage(errorMessage);
    builder.id("test-id");
    builder.author("test-author");
    builder.invocationId("test-invocation");
    Event event = builder.build();
    assertThat(event.errorMessage()).isEqualTo(Optional.of(errorMessage));
    assertNotNull(event.id());
    assertNotNull(event.author());
    assertNotNull(event.invocationId());
  }
}
