/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-repo using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=usageMetadata_e30373c164
ROOST_METHOD_SIG_HASH=usageMetadata_60565484e7

Scenario 1: Setting Usage Metadata with a Valid Non-Null Value

Details:
  TestName: usageMetadataWithValidNonNullValue
  Description: This test verifies that the usageMetadata method correctly accepts a non-null GenerateContentResponseUsageMetadata object and wraps it in an Optional. The method should return the Builder instance to support method chaining (fluent API pattern).

Execution:
  Arrange: Create a new Event.Builder instance and a mock or valid GenerateContentResponseUsageMetadata object.
  Act: Invoke the usageMetadata method on the builder with the non-null GenerateContentResponseUsageMetadata object.
  Assert: Verify that the method returns the same Builder instance (for method chaining). Build the Event object and verify that the usageMetadata field contains an Optional with the provided value using the usageMetadata() accessor method.

Validation:
  The assertion verifies that the builder correctly stores the non-null usage metadata value in an Optional wrapper and maintains the fluent builder pattern by returning itself. This is critical for allowing developers to chain multiple builder method calls together. The test ensures that valid usage metadata can be properly set and retrieved from the built Event object.

---

Scenario 2: Setting Usage Metadata with a Null Value

Details:
  TestName: usageMetadataWithNullValue
  Description: This test validates that the usageMetadata method correctly handles null input by wrapping it in an empty Optional. The @Nullable annotation on the parameter indicates that null is an acceptable input value.

Execution:
  Arrange: Create a new Event.Builder instance.
  Act: Invoke the usageMetadata method with a null value as the parameter.
  Assert: Verify that the method returns the Builder instance. Build the Event object and verify that the usageMetadata field contains an empty Optional using the usageMetadata() accessor method and Optional.isEmpty() or asserting that Optional.isPresent() returns false.

Validation:
  This test ensures that null values are handled gracefully by converting them to empty Optionals rather than causing NullPointerExceptions. This is important for defensive programming and aligns with the Optional pattern used throughout the codebase. The empty Optional indicates the absence of usage metadata without using null references.

---

Scenario 3: Method Chaining with Usage Metadata

Details:
  TestName: usageMetadataSupportsMethodChaining
  Description: This test verifies that the usageMetadata method returns the Builder instance, enabling fluent API method chaining with other builder methods. The @CanIgnoreReturnValue annotation indicates the return value can be ignored, but it should still support chaining.

Execution:
  Arrange: Create a new Event.Builder instance, a GenerateContentResponseUsageMetadata object, and prepare other builder parameters (e.g., id, author, invocationId).
  Act: Chain multiple builder method calls together, including usageMetadata, in a single statement (e.g., builder.id("test-id").author("test-author").usageMetadata(metadata).invocationId("inv-id")).
  Assert: Verify that the chaining executes without errors. Build the Event object and verify that all chained values, including usageMetadata, are correctly set in the built object.

Validation:
  This test confirms that the builder pattern is properly implemented with method chaining support. Developers commonly chain builder methods for cleaner, more readable code. The test ensures that usageMetadata integrates seamlessly with other builder methods and that all values are correctly preserved through the chain.

---

Scenario 4: Overwriting Previously Set Usage Metadata

Details:
  TestName: usageMetadataOverwritesPreviousValue
  Description: This test verifies that calling usageMetadata multiple times on the same Builder instance correctly overwrites the previous value with the new value, maintaining only the most recent setting.

Execution:
  Arrange: Create a new Event.Builder instance and two different GenerateContentResponseUsageMetadata objects (firstMetadata and secondMetadata).
  Act: Call usageMetadata with firstMetadata, then call it again with secondMetadata on the same builder instance.
  Assert: Build the Event object and verify that the usageMetadata field contains an Optional with secondMetadata (the most recent value), not firstMetadata.

Validation:
  This test ensures that the builder correctly implements the last-write-wins semantics expected in builder patterns. When developers call the same setter method multiple times, only the final value should be retained. This behavior is important for scenarios where configuration is built up conditionally or where default values are overridden.

---

Scenario 5: Setting Usage Metadata After Setting to Null

Details:
  TestName: usageMetadataSetAfterNull
  Description: This test validates that a valid usage metadata value can be set after previously setting it to null, ensuring the builder state is properly updated and the null value is replaced.

Execution:
  Arrange: Create a new Event.Builder instance and a valid GenerateContentResponseUsageMetadata object.
  Act: First call usageMetadata with null, then call it again with the valid GenerateContentResponseUsageMetadata object.
  Assert: Build the Event object and verify that the usageMetadata field contains an Optional with the valid object, not an empty Optional.

Validation:
  This test confirms that the builder's state management is correct and that null values don't permanently affect the builder. Developers should be able to change their mind about configuration values, including replacing null with valid values. This flexibility is essential for dynamic configuration scenarios.

---

Scenario 6: Setting Null After Setting Valid Usage Metadata

Details:
  TestName: usageMetadataSetNullAfterValidValue
  Description: This test verifies that setting usage metadata to null after previously setting a valid value correctly clears the field by replacing it with an empty Optional.

Execution:
  Arrange: Create a new Event.Builder instance and a valid GenerateContentResponseUsageMetadata object.
  Act: First call usageMetadata with the valid object, then call it again with null.
  Assert: Build the Event object and verify that the usageMetadata field contains an empty Optional.

Validation:
  This test ensures that developers can explicitly clear or unset the usage metadata field by passing null. This is important for scenarios where configuration needs to be reset or where conditional logic determines whether metadata should be included. The test validates that the Optional.ofNullable pattern correctly handles this transition.

---

Scenario 7: Usage Metadata in Built Event Object

Details:
  TestName: usageMetadataPersistedInBuiltEvent
  Description: This test verifies that the usage metadata set in the builder is correctly transferred to the Event object when build() is called, ensuring data integrity through the build process.

Execution:
  Arrange: Create a new Event.Builder instance and a GenerateContentResponseUsageMetadata object with identifiable properties.
  Act: Set the usage metadata on the builder and call build() to create an Event object.
  Assert: Verify that the Event object's usageMetadata() method returns an Optional containing the same GenerateContentResponseUsageMetadata object that was set in the builder.

Validation:
  This test confirms that the build() method correctly transfers the usage metadata from the builder to the immutable Event object. This is critical for ensuring that configuration set during the building phase is accurately reflected in the final object. The test validates the integrity of the builder-to-object data transfer.

---

Scenario 8: Default Usage Metadata Value When Not Set

Details:
  TestName: usageMetadataDefaultValueWhenNotSet
  Description: This test verifies the default state of the usageMetadata field when the usageMetadata method is never called on the builder, ensuring proper initialization.

Execution:
  Arrange: Create a new Event.Builder instance and set only required fields (id, invocationId, author) without calling usageMetadata.
  Act: Build the Event object without setting usage metadata.
  Assert: Verify that the Event object's usageMetadata() method returns an empty Optional.

Validation:
  This test ensures that the builder properly initializes the usageMetadata field to an empty Optional when not explicitly set. This default behavior is important for maintaining consistency and avoiding null pointer exceptions. The test validates that the Optional pattern is correctly applied throughout the object lifecycle, even when values are not provided.

---

Scenario 9: Builder Independence After Setting Usage Metadata

Details:
  TestName: usageMetadataBuilderIndependence
  Description: This test verifies that multiple Builder instances maintain independent state for usage metadata, ensuring that setting the value on one builder doesn't affect other builders.

Execution:
  Arrange: Create two separate Event.Builder instances (builder1 and builder2) and two different GenerateContentResponseUsageMetadata objects (metadata1 and metadata2).
  Act: Set metadata1 on builder1 and metadata2 on builder2.
  Assert: Build both Event objects and verify that the first Event contains metadata1 and the second Event contains metadata2, confirming no cross-contamination.

Validation:
  This test confirms that each Builder instance maintains its own independent state. This is crucial for scenarios where multiple Event objects are being constructed concurrently or sequentially. The test ensures that the builder pattern implementation doesn't have shared state issues that could lead to subtle bugs in multi-threaded or complex construction scenarios.

---

Scenario 10: Usage Metadata with toBuilder Pattern

Details:
  TestName: usageMetadataPreservedInToBuilder
  Description: This test verifies that when an Event object is converted back to a Builder using toBuilder(), the usage metadata value is correctly preserved in the new builder instance.

Execution:
  Arrange: Create an Event.Builder instance, set a GenerateContentResponseUsageMetadata object, and build an Event object.
  Act: Call toBuilder() on the Event object to create a new Builder instance.
  Assert: Build a new Event from the toBuilder() result and verify that the usage metadata in the new Event matches the original Event's usage metadata.

Validation:
  This test ensures that the toBuilder() method correctly copies all field values, including usage metadata, from the Event object back to a Builder. This is important for scenarios where developers need to create modified copies of existing Event objects. The test validates the round-trip integrity of the builder pattern implementation.

*/

// ********RoostGPT********

package com.google.adk.events;

import static com.google.common.truth.Truth.assertThat;
import static org.junit.jupiter.api.Assertions.*;

import com.google.genai.types.FinishReason;
import com.google.genai.types.GenerateContentResponseUsageMetadata;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class BuilderUsageMetadataTest {

  private Event.Builder builder;

  private GenerateContentResponseUsageMetadata validMetadata;

  private GenerateContentResponseUsageMetadata alternateMetadata;

  @BeforeEach
  void setUp() {
    builder = Event.builder();
    validMetadata =
        GenerateContentResponseUsageMetadata.newBuilder()
            .setPromptTokenCount(100)
            .setCandidatesTokenCount(50)
            .setTotalTokenCount(150)
            .build();
    alternateMetadata =
        GenerateContentResponseUsageMetadata.newBuilder()
            .setPromptTokenCount(200)
            .setCandidatesTokenCount(100)
            .setTotalTokenCount(300)
            .build();
  }

  @Test
  @Tag("valid")
  void usageMetadataWithValidNonNullValue() {
    Event.Builder result = builder.usageMetadata(validMetadata);
    assertThat(result).isSameInstanceAs(builder);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertThat(event.usageMetadata()).isPresent();
    assertThat(event.usageMetadata().get()).isEqualTo(validMetadata);
  }

  @Test
  @Tag("valid")
  void usageMetadataWithNullValue() {
    Event.Builder result = builder.usageMetadata((GenerateContentResponseUsageMetadata) null);
    assertThat(result).isSameInstanceAs(builder);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertThat(event.usageMetadata()).isEmpty();
  }

  @Test
  @Tag("valid")
  void usageMetadataSupportsMethodChaining() {
    Event event =
        builder
            .id("test-id")
            .author("test-author")
            .usageMetadata(validMetadata)
            .invocationId("inv-id")
            .partial(true)
            .build();
    assertThat(event.id()).isEqualTo("test-id");
    assertThat(event.author()).isEqualTo("test-author");
    assertThat(event.usageMetadata()).isPresent();
    assertThat(event.usageMetadata().get()).isEqualTo(validMetadata);
    assertThat(event.invocationId()).isEqualTo("inv-id");
    assertThat(event.partial()).isPresent();
    assertThat(event.partial().get()).isTrue();
  }

  @Test
  @Tag("valid")
  void usageMetadataOverwritesPreviousValue() {
    builder.usageMetadata(validMetadata);
    builder.usageMetadata(alternateMetadata);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertThat(event.usageMetadata()).isPresent();
    assertThat(event.usageMetadata().get()).isEqualTo(alternateMetadata);
    assertThat(event.usageMetadata().get()).isNotEqualTo(validMetadata);
  }

  @Test
  @Tag("valid")
  void usageMetadataSetAfterNull() {
    builder.usageMetadata((GenerateContentResponseUsageMetadata) null);
    builder.usageMetadata(validMetadata);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertThat(event.usageMetadata()).isPresent();
    assertThat(event.usageMetadata().get()).isEqualTo(validMetadata);
  }

  @Test
  @Tag("valid")
  void usageMetadataSetNullAfterValidValue() {
    builder.usageMetadata(validMetadata);
    builder.usageMetadata((GenerateContentResponseUsageMetadata) null);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertThat(event.usageMetadata()).isEmpty();
  }

  @Test
  @Tag("valid")
  void usageMetadataPersistedInBuiltEvent() {
    builder.usageMetadata(validMetadata);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertThat(event.usageMetadata()).isPresent();
    assertThat(event.usageMetadata().get()).isEqualTo(validMetadata);
    assertThat(event.usageMetadata().get().getPromptTokenCount()).isEqualTo(100);
    assertThat(event.usageMetadata().get().getCandidatesTokenCount()).isEqualTo(50);
    assertThat(event.usageMetadata().get().getTotalTokenCount()).isEqualTo(150);
  }

  @Test
  @Tag("valid")
  void usageMetadataDefaultValueWhenNotSet() {
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertThat(event.usageMetadata()).isEmpty();
  }

  @Test
  @Tag("valid")
  void usageMetadataBuilderIndependence() {
    Event.Builder builder1 = Event.builder();
    Event.Builder builder2 = Event.builder();
    builder1.usageMetadata(validMetadata);
    builder2.usageMetadata(alternateMetadata);
    Event event1 =
        builder1.id("test-id-1").invocationId("test-invocation-1").author("test-author-1").build();
    Event event2 =
        builder2.id("test-id-2").invocationId("test-invocation-2").author("test-author-2").build();
    assertThat(event1.usageMetadata()).isPresent();
    assertThat(event1.usageMetadata().get()).isEqualTo(validMetadata);
    assertThat(event2.usageMetadata()).isPresent();
    assertThat(event2.usageMetadata().get()).isEqualTo(alternateMetadata);
    assertThat(event1.usageMetadata().get()).isNotEqualTo(event2.usageMetadata().get());
  }

  @Test
  @Tag("valid")
  void usageMetadataPreservedInToBuilder() {
    Event originalEvent =
        builder
            .id("test-id")
            .invocationId("test-invocation")
            .author("test-author")
            .usageMetadata(validMetadata)
            .build();
    Event.Builder newBuilder = originalEvent.toBuilder();
    Event newEvent = newBuilder.build();
    assertThat(newEvent.usageMetadata()).isPresent();
    assertThat(newEvent.usageMetadata().get()).isEqualTo(originalEvent.usageMetadata().get());
    assertThat(newEvent.usageMetadata().get()).isEqualTo(validMetadata);
  }

  @Test
  @Tag("valid")
  void usageMetadataWithOptionalWrapper() {
    builder.usageMetadata(Optional.of(validMetadata));
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertThat(event.usageMetadata()).isPresent();
    assertThat(event.usageMetadata().get()).isEqualTo(validMetadata);
  }

  @Test
  @Tag("valid")
  void usageMetadataWithEmptyOptional() {
    builder.usageMetadata(Optional.empty());
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertThat(event.usageMetadata()).isEmpty();
  }

  @Test
  @Tag("boundary")
  void usageMetadataWithZeroTokenCounts() {
    GenerateContentResponseUsageMetadata zeroMetadata =
        GenerateContentResponseUsageMetadata.newBuilder()
            .setPromptTokenCount(0)
            .setCandidatesTokenCount(0)
            .setTotalTokenCount(0)
            .build();
    builder.usageMetadata(zeroMetadata);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertThat(event.usageMetadata()).isPresent();
    assertThat(event.usageMetadata().get().getPromptTokenCount()).isEqualTo(0);
    assertThat(event.usageMetadata().get().getCandidatesTokenCount()).isEqualTo(0);
    assertThat(event.usageMetadata().get().getTotalTokenCount()).isEqualTo(0);
  }

  @Test
  @Tag("boundary")
  void usageMetadataWithLargeTokenCounts() {
    GenerateContentResponseUsageMetadata largeMetadata =
        GenerateContentResponseUsageMetadata.newBuilder()
            .setPromptTokenCount(Integer.MAX_VALUE)
            .setCandidatesTokenCount(Integer.MAX_VALUE)
            .setTotalTokenCount(Integer.MAX_VALUE)
            .build();
    builder.usageMetadata(largeMetadata);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertThat(event.usageMetadata()).isPresent();
    assertThat(event.usageMetadata().get().getPromptTokenCount()).isEqualTo(Integer.MAX_VALUE);
  }

  @Test
  @Tag("integration")
  void usageMetadataWithCompleteEventConfiguration() {
    Event event =
        builder
            .id("complete-id")
            .invocationId("complete-invocation")
            .author("complete-author")
            .usageMetadata(validMetadata)
            .partial(false)
            .turnComplete(true)
            .finishReason(FinishReason.STOP)
            .avgLogprobs(-0.5)
            .interrupted(false)
            .branch("main")
            .modelVersion("gemini-1.5-pro")
            .build();
    assertThat(event.usageMetadata()).isPresent();
    assertThat(event.usageMetadata().get()).isEqualTo(validMetadata);
    assertThat(event.id()).isEqualTo("complete-id");
    assertThat(event.author()).isEqualTo("complete-author");
    assertThat(event.partial()).isPresent();
    assertThat(event.partial().get()).isFalse();
    assertThat(event.turnComplete()).isPresent();
    assertThat(event.turnComplete().get()).isTrue();
  }
}
