/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-repo using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=turnComplete_63a966002c
ROOST_METHOD_SIG_HASH=turnComplete_87597fa37d

Scenario 1: Setting turnComplete with a non-null true value

Details:
  TestName: turnCompleteWithTrueValue
  Description: This test verifies that the turnComplete method correctly accepts a non-null Boolean value of true and wraps it in an Optional. The method should store the value and return the Builder instance for method chaining.

Execution:
  Arrange: Create a new Event.Builder instance.
  Act: Call the turnComplete method with Boolean.TRUE as the parameter.
  Assert: Verify that the method returns the same Builder instance (for fluent API chaining). Verify that when build() is called, the resulting Event object has turnComplete() returning Optional.of(true).

Validation:
  This test ensures that the turnComplete method properly handles a true Boolean value and maintains the builder pattern by returning the Builder instance. This is critical for indicating that a conversational turn has been completed. The test validates that the Optional wrapping is correctly applied and the value is preserved through the build process.

---

Scenario 2: Setting turnComplete with a non-null false value

Details:
  TestName: turnCompleteWithFalseValue
  Description: This test verifies that the turnComplete method correctly accepts a non-null Boolean value of false and wraps it in an Optional. The method should store the value and return the Builder instance.

Execution:
  Arrange: Create a new Event.Builder instance.
  Act: Call the turnComplete method with Boolean.FALSE as the parameter.
  Assert: Verify that the method returns the same Builder instance. Verify that when build() is called, the resulting Event object has turnComplete() returning Optional.of(false).

Validation:
  This test confirms that the turnComplete method can handle a false Boolean value, which indicates that a turn is not yet complete. This is important for tracking partial or ongoing conversational turns. The assertion validates that false values are correctly stored and retrieved.

---

Scenario 3: Setting turnComplete with a null value

Details:
  TestName: turnCompleteWithNullValue
  Description: This test verifies that the turnComplete method correctly handles a null value by wrapping it in an Optional.empty(). The @Nullable annotation on the parameter indicates that null is an acceptable input.

Execution:
  Arrange: Create a new Event.Builder instance.
  Act: Call the turnComplete method with null as the parameter.
  Assert: Verify that the method returns the same Builder instance. Verify that when build() is called, the resulting Event object has turnComplete() returning Optional.empty().

Validation:
  This test ensures that null values are properly handled by the method, resulting in an empty Optional rather than a NullPointerException. This is essential for cases where the turn completion status is unknown or not applicable. The Optional.ofNullable() implementation should convert null to Optional.empty().

---

Scenario 4: Method chaining with turnComplete

Details:
  TestName: turnCompleteMethodChaining
  Description: This test verifies that the turnComplete method supports fluent API method chaining by returning the Builder instance, allowing multiple builder methods to be called in sequence.

Execution:
  Arrange: Create a new Event.Builder instance.
  Act: Chain multiple builder method calls including turnComplete(true), followed by other builder methods like id("test-id") and author("test-author").
  Assert: Verify that all chained method calls execute successfully without throwing exceptions. Verify that the final built Event object contains all the set values including turnComplete as Optional.of(true).

Validation:
  This test validates the builder pattern implementation, ensuring that the @CanIgnoreReturnValue annotation and return type allow for seamless method chaining. This is crucial for providing a clean and readable API for constructing Event objects with multiple properties.

---

Scenario 5: Overwriting turnComplete value

Details:
  TestName: turnCompleteOverwritePreviousValue
  Description: This test verifies that calling turnComplete multiple times on the same Builder instance correctly overwrites the previous value with the most recent one.

Execution:
  Arrange: Create a new Event.Builder instance.
  Act: Call turnComplete(true) first, then call turnComplete(false) on the same builder instance. Finally, call build() to create the Event object.
  Assert: Verify that the resulting Event object has turnComplete() returning Optional.of(false), confirming that the second call overwrote the first value.

Validation:
  This test ensures that the Builder correctly handles multiple assignments to the same field, with the last value taking precedence. This behavior is important for scenarios where builder configuration might be modified during construction, and validates that the field assignment logic works correctly.

---

Scenario 6: Setting turnComplete to true then to null

Details:
  TestName: turnCompleteFromTrueToNull
  Description: This test verifies that the turnComplete field can be reset from a non-null value to null, resulting in an empty Optional.

Execution:
  Arrange: Create a new Event.Builder instance.
  Act: Call turnComplete(true) first, then call turnComplete(null) on the same builder instance. Finally, call build() to create the Event object.
  Assert: Verify that the resulting Event object has turnComplete() returning Optional.empty(), confirming that the null value overwrote the previous true value.

Validation:
  This test validates that the Builder allows resetting a previously set value to null, which might be necessary in scenarios where the turn completion status needs to be cleared or made undefined. The Optional.ofNullable() implementation should handle this transition correctly.

---

Scenario 7: Building Event with only turnComplete set

Details:
  TestName: turnCompleteOnlyFieldSet
  Description: This test verifies that an Event can be built with only the turnComplete field explicitly set, while other optional fields remain as Optional.empty() or their default values.

Execution:
  Arrange: Create a new Event.Builder instance.
  Act: Call only turnComplete(true) on the builder, then call build() without setting other optional fields.
  Assert: Verify that the resulting Event object has turnComplete() returning Optional.of(true), and other optional fields like partial(), interrupted(), and errorMessage() return Optional.empty().

Validation:
  This test ensures that the turnComplete field can be set independently of other fields, and that the Builder correctly initializes all other optional fields to their default states. This validates the independence of builder fields and proper default value handling.

---

Scenario 8: turnComplete with true in combination with partial false

Details:
  TestName: turnCompleteWithPartialFalse
  Description: This test verifies that turnComplete can be set to true while partial is set to false, representing a complete, non-partial turn in a conversation.

Execution:
  Arrange: Create a new Event.Builder instance.
  Act: Call turnComplete(true) and partial(false) on the builder, then call build().
  Assert: Verify that the resulting Event object has turnComplete() returning Optional.of(true) and partial() returning Optional.of(false).

Validation:
  This test validates a common use case where a turn is complete and not partial, which is typical for final responses in a conversational flow. This combination of values is semantically meaningful in the context of the Event class and should be properly supported.

---

Scenario 9: turnComplete return value verification

Details:
  TestName: turnCompleteReturnsBuilderInstance
  Description: This test explicitly verifies that the turnComplete method returns the exact same Builder instance that it was called on, not a new instance.

Execution:
  Arrange: Create a new Event.Builder instance and store it in a variable.
  Act: Call turnComplete(true) on the builder and store the returned value in another variable.
  Assert: Verify using reference equality (==) that the returned Builder instance is the same object as the original Builder instance.

Validation:
  This test confirms that the method follows the builder pattern correctly by returning 'this' rather than creating a new Builder instance. This is important for performance and for ensuring that all builder method calls modify the same underlying object.

---

Scenario 10: turnComplete with boxed Boolean objects

Details:
  TestName: turnCompleteWithBoxedBooleanObjects
  Description: This test verifies that the turnComplete method correctly handles boxed Boolean objects (Boolean.TRUE and Boolean.FALSE) as opposed to primitive boolean values.

Execution:
  Arrange: Create a new Event.Builder instance.
  Act: Call turnComplete with Boolean.TRUE (boxed object), then build the Event.
  Assert: Verify that the resulting Event object has turnComplete() returning Optional.of(true) with the correct Boolean value.

Validation:
  This test ensures that the method signature accepting @Nullable Boolean (boxed type) works correctly with boxed Boolean objects. Since the parameter is a boxed type, this test validates proper handling of Boolean objects versus primitive booleans, which is important for null-safety and Optional wrapping.

---

Scenario 11: Multiple Builder instances with different turnComplete values

Details:
  TestName: turnCompleteIndependentBuilderInstances
  Description: This test verifies that different Builder instances maintain independent turnComplete values and do not interfere with each other.

Execution:
  Arrange: Create two separate Event.Builder instances.
  Act: Call turnComplete(true) on the first builder and turnComplete(false) on the second builder. Build both Event objects.
  Assert: Verify that the first Event has turnComplete() returning Optional.of(true) and the second Event has turnComplete() returning Optional.of(false).

Validation:
  This test ensures that Builder instances are properly isolated and that setting turnComplete on one builder does not affect other builder instances. This validates proper encapsulation and state management in the Builder class.

---

Scenario 12: turnComplete in combination with finishReason

Details:
  TestName: turnCompleteWithFinishReason
  Description: This test verifies that turnComplete can be set alongside finishReason, which is a common scenario when a turn completes with a specific finish reason.

Execution:
  Arrange: Create a new Event.Builder instance and obtain a FinishReason value (assuming FinishReason has accessible constants or can be instantiated).
  Act: Call turnComplete(true) and finishReason(finishReasonValue) on the builder, then build the Event.
  Assert: Verify that the resulting Event has both turnComplete() returning Optional.of(true) and finishReason() returning an Optional containing the finish reason.

Validation:
  This test validates a realistic use case where a turn is marked as complete along with a reason for completion. This combination is semantically meaningful in the context of conversation management and ensures that multiple related fields can be set together without conflicts.

*/

// ********RoostGPT********

package com.google.adk.events;

import static com.google.common.truth.Truth.assertThat;
import static com.google.common.truth.Truth8.assertThat;

import com.google.genai.types.FinishReason;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class BuilderTurnCompleteTest {

  @Test
  @Tag("valid")
  void turnCompleteWithTrueValue() {
    Event.Builder builder = Event.builder();

    Event.Builder result = builder.turnComplete(Boolean.TRUE);

    assertThat(result).isSameInstanceAs(builder);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertThat(event.turnComplete()).hasValue(true);
  }

  @Test
  @Tag("valid")
  void turnCompleteWithFalseValue() {
    Event.Builder builder = Event.builder();

    Event.Builder result = builder.turnComplete(Boolean.FALSE);

    assertThat(result).isSameInstanceAs(builder);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertThat(event.turnComplete()).hasValue(false);
  }

  @Test
  @Tag("boundary")
  void turnCompleteWithNullValue() {
    Event.Builder builder = Event.builder();

    Event.Builder result = builder.turnComplete(null);

    assertThat(result).isSameInstanceAs(builder);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertThat(event.turnComplete()).isEmpty();
  }

  @Test
  @Tag("valid")
  void turnCompleteMethodChaining() {
    Event.Builder builder = Event.builder();

    Event event =
        builder
            .turnComplete(true)
            .id("test-id")
            .author("test-author")
            .invocationId("test-invocation")
            .partial(false)
            .build();

    assertThat(event.turnComplete()).hasValue(true);
    assertThat(event.id()).isEqualTo("test-id");
    assertThat(event.author()).isEqualTo("test-author");
    assertThat(event.invocationId()).isEqualTo("test-invocation");
    assertThat(event.partial()).hasValue(false);
  }

  @Test
  @Tag("valid")
  void turnCompleteOverwritePreviousValue() {
    Event.Builder builder = Event.builder();

    builder.turnComplete(true);
    builder.turnComplete(false);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();

    assertThat(event.turnComplete()).hasValue(false);
  }

  @Test
  @Tag("boundary")
  void turnCompleteFromTrueToNull() {
    Event.Builder builder = Event.builder();

    builder.turnComplete(true);
    builder.turnComplete(null);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();

    assertThat(event.turnComplete()).isEmpty();
  }

  @Test
  @Tag("valid")
  void turnCompleteOnlyFieldSet() {
    Event.Builder builder = Event.builder();

    Event event =
        builder
            .turnComplete(true)
            .id("test-id")
            .invocationId("test-invocation")
            .author("test-author")
            .build();

    assertThat(event.turnComplete()).hasValue(true);
    assertThat(event.partial()).isEmpty();
    assertThat(event.interrupted()).isEmpty();
    assertThat(event.errorMessage()).isEmpty();
  }

  @Test
  @Tag("valid")
  void turnCompleteWithPartialFalse() {
    Event.Builder builder = Event.builder();

    Event event =
        builder
            .turnComplete(true)
            .partial(false)
            .id("test-id")
            .invocationId("test-invocation")
            .author("test-author")
            .build();

    assertThat(event.turnComplete()).hasValue(true);
    assertThat(event.partial()).hasValue(false);
  }

  @Test
  @Tag("valid")
  void turnCompleteReturnsBuilderInstance() {
    Event.Builder builder = Event.builder();

    Event.Builder returnedBuilder = builder.turnComplete(true);

    assertThat(returnedBuilder).isSameInstanceAs(builder);
  }

  @Test
  @Tag("valid")
  void turnCompleteWithBoxedBooleanObjects() {
    Event.Builder builder = Event.builder();

    builder.turnComplete(Boolean.TRUE);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();

    assertThat(event.turnComplete()).hasValue(true);
  }

  @Test
  @Tag("valid")
  void turnCompleteIndependentBuilderInstances() {
    Event.Builder builder1 = Event.builder();
    Event.Builder builder2 = Event.builder();

    builder1.turnComplete(true);
    builder2.turnComplete(false);

    Event event1 =
        builder1.id("test-id-1").invocationId("test-invocation-1").author("test-author-1").build();
    Event event2 =
        builder2.id("test-id-2").invocationId("test-invocation-2").author("test-author-2").build();

    assertThat(event1.turnComplete()).hasValue(true);
    assertThat(event2.turnComplete()).hasValue(false);
  }

  @Test
  @Tag("integration")
  void turnCompleteWithFinishReason() {
    Event.Builder builder = Event.builder();

    Event event =
        builder
            .turnComplete(true)
            .finishReason(FinishReason.STOP)
            .id("test-id")
            .invocationId("test-invocation")
            .author("test-author")
            .build();

    assertThat(event.turnComplete()).hasValue(true);
    assertThat(event.finishReason()).hasValue(FinishReason.STOP);
  }

  @Test
  @Tag("valid")
  void turnCompleteWithOptionalParameter() {
    Event.Builder builder = Event.builder();

    builder.turnComplete(Optional.of(true));
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();

    assertThat(event.turnComplete()).hasValue(true);
  }

  @Test
  @Tag("boundary")
  void turnCompleteWithEmptyOptional() {
    Event.Builder builder = Event.builder();

    builder.turnComplete(Optional.empty());
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();

    assertThat(event.turnComplete()).isEmpty();
  }

  @Test
  @Tag("valid")
  void turnCompleteMultipleTimesWithDifferentValues() {
    Event.Builder builder = Event.builder();

    builder.turnComplete(true);
    builder.turnComplete(false);
    builder.turnComplete(true);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();

    assertThat(event.turnComplete()).hasValue(true);
  }

  @Test
  @Tag("integration")
  void turnCompleteWithAllRelatedFields() {
    Event.Builder builder = Event.builder();

    Event event =
        builder
            .turnComplete(true)
            .partial(false)
            .interrupted(false)
            .finishReason(FinishReason.STOP)
            .id("test-id")
            .invocationId("test-invocation")
            .author("test-author")
            .build();

    assertThat(event.turnComplete()).hasValue(true);
    assertThat(event.partial()).hasValue(false);
    assertThat(event.interrupted()).hasValue(false);
    assertThat(event.finishReason()).hasValue(FinishReason.STOP);
  }
}
