/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-repo using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=longRunningToolIds_48f28fc462
ROOST_METHOD_SIG_HASH=longRunningToolIds_831974d324

Scenario 1: Setting longRunningToolIds with a non-empty Optional containing a Set of tool IDs

Details:
  TestName: longRunningToolIdsWithNonEmptyOptionalSet
  Description: This test verifies that the longRunningToolIds method correctly accepts an Optional containing a non-empty Set of String tool IDs and returns the Builder instance for method chaining. The test ensures that the builder pattern works correctly when setting long-running tool identifiers.

Execution:
  Arrange: Create a new Event.Builder instance. Create a Set<String> containing multiple tool IDs (e.g., "tool1", "tool2", "tool3"). Wrap this Set in an Optional.
  Act: Invoke the longRunningToolIds method on the builder with the Optional<Set<String>> parameter.
  Assert: Verify that the returned object is the same Builder instance (for method chaining). Build the Event and verify that the longRunningToolIds field contains the expected Set of tool IDs.

Validation:
  This assertion verifies that the builder correctly stores the provided Optional<Set<String>> value and maintains the builder pattern by returning itself. This is crucial for fluent API design, allowing developers to chain multiple builder method calls. The test ensures that multiple tool IDs can be tracked as long-running operations, which is important for the application to manage asynchronous tool executions properly.

---

Scenario 2: Setting longRunningToolIds with an empty Optional

Details:
  TestName: longRunningToolIdsWithEmptyOptional
  Description: This test validates that the longRunningToolIds method correctly handles an empty Optional parameter. It ensures that the builder can represent the absence of long-running tool IDs without throwing exceptions.

Execution:
  Arrange: Create a new Event.Builder instance. Create an empty Optional<Set<String>> using Optional.empty().
  Act: Invoke the longRunningToolIds method on the builder with the empty Optional parameter.
  Assert: Verify that the returned object is the same Builder instance. Build the Event and verify that the longRunningToolIds field is an empty Optional.

Validation:
  This test confirms that the method gracefully handles the absence of long-running tool IDs by accepting an empty Optional. This is important for scenarios where an event has no long-running tools associated with it. The assertion validates that the builder maintains consistency in its state management and doesn't default to null or throw exceptions when no tool IDs are provided.

---

Scenario 3: Setting longRunningToolIds with an Optional containing an empty Set

Details:
  TestName: longRunningToolIdsWithOptionalContainingEmptySet
  Description: This test checks the behavior when passing an Optional that contains an empty Set (as opposed to an empty Optional). This distinguishes between "no value" (empty Optional) and "empty collection" (Optional containing empty Set).

Execution:
  Arrange: Create a new Event.Builder instance. Create an empty Set<String> and wrap it in an Optional using Optional.of(new HashSet<>()).
  Act: Invoke the longRunningToolIds method on the builder with the Optional containing the empty Set.
  Assert: Verify that the returned object is the same Builder instance. Build the Event and verify that the longRunningToolIds field contains an Optional with an empty Set (not an empty Optional).

Validation:
  This assertion verifies the semantic difference between Optional.empty() and Optional.of(emptySet()). While both represent "no tool IDs," they have different meanings: empty Optional means the field wasn't set, while Optional containing empty Set means it was explicitly set to have no tools. This distinction can be important for business logic that needs to differentiate between "unknown" and "explicitly none."

---

Scenario 4: Setting longRunningToolIds with an Optional containing a single tool ID

Details:
  TestName: longRunningToolIdsWithSingleToolId
  Description: This test validates that the method works correctly with the minimal valid case of a Set containing exactly one tool ID. It ensures the builder handles single-element collections properly.

Execution:
  Arrange: Create a new Event.Builder instance. Create a Set<String> containing a single tool ID (e.g., "singleTool"). Wrap this Set in an Optional.
  Act: Invoke the longRunningToolIds method on the builder with the Optional<Set<String>> parameter.
  Assert: Verify that the returned object is the same Builder instance. Build the Event and verify that the longRunningToolIds field contains an Optional with a Set containing exactly one element matching the provided tool ID.

Validation:
  This test ensures that the builder correctly handles the edge case of a single tool ID, which is a common scenario in practice. The assertion validates that no data is lost or corrupted when dealing with minimal collections, and that the Set semantics are preserved (no duplicates, proper containment checks).

---

Scenario 5: Method chaining with longRunningToolIds and other builder methods

Details:
  TestName: longRunningToolIdsMethodChaining
  Description: This test verifies that the longRunningToolIds method properly supports method chaining by returning the Builder instance, allowing it to be used in conjunction with other builder methods in a fluent API style.

Execution:
  Arrange: Create a new Event.Builder instance. Prepare an Optional<Set<String>> with tool IDs. Prepare other builder parameters like id, author, and invocationId.
  Act: Chain multiple builder method calls including longRunningToolIds, id, author, and invocationId in a single statement.
  Assert: Verify that all methods execute without errors. Build the Event and verify that all fields (longRunningToolIds, id, author, invocationId) are set correctly.

Validation:
  This assertion confirms that the builder pattern is correctly implemented with proper return types, enabling fluent API usage. Method chaining is a key feature of the builder pattern that improves code readability and reduces verbosity. This test ensures that developers can write concise, readable code when constructing Event objects with multiple properties.

---

Scenario 6: Overwriting previously set longRunningToolIds value

Details:
  TestName: longRunningToolIdsOverwritePreviousValue
  Description: This test validates that calling longRunningToolIds multiple times on the same builder instance correctly overwrites the previous value rather than merging or causing conflicts.

Execution:
  Arrange: Create a new Event.Builder instance. Create two different Optional<Set<String>> instances: first with tool IDs {"tool1", "tool2"}, second with {"tool3", "tool4"}.
  Act: Call longRunningToolIds with the first Optional, then call it again with the second Optional on the same builder instance.
  Assert: Build the Event and verify that the longRunningToolIds field contains only the second Set of tool IDs ({"tool3", "tool4"}), confirming the first value was overwritten.

Validation:
  This test ensures that the builder maintains proper state management by replacing rather than accumulating values. This behavior is expected in builder patterns where the last set value should take precedence. The assertion validates that there are no memory leaks or unexpected state retention from previous method calls.

---

Scenario 7: Setting longRunningToolIds with null value through Optional

Details:
  TestName: longRunningToolIdsWithNullWrappedInOptional
  Description: This test examines the behavior when passing Optional.ofNullable(null), which results in an empty Optional. It ensures the method handles null-safe Optional creation correctly.

Execution:
  Arrange: Create a new Event.Builder instance. Create an Optional using Optional.ofNullable(null), which produces Optional.empty().
  Act: Invoke the longRunningToolIds method with the Optional created from null.
  Assert: Verify that the returned object is the same Builder instance. Build the Event and verify that the longRunningToolIds field is an empty Optional.

Validation:
  This assertion validates null-safety in the builder API. By accepting Optional parameters, the method encourages null-safe programming practices. The test confirms that passing null through Optional.ofNullable correctly results in an empty Optional rather than causing NullPointerException or other errors.

---

Scenario 8: Setting longRunningToolIds with a large Set of tool IDs

Details:
  TestName: longRunningToolIdsWithLargeSet
  Description: This test validates that the method can handle a large number of tool IDs without performance degradation or errors. It ensures scalability for scenarios with many concurrent long-running operations.

Execution:
  Arrange: Create a new Event.Builder instance. Create a Set<String> containing a large number of tool IDs (e.g., 1000 unique tool IDs generated programmatically). Wrap this Set in an Optional.
  Act: Invoke the longRunningToolIds method with the Optional containing the large Set.
  Assert: Verify that the returned object is the same Builder instance. Build the Event and verify that the longRunningToolIds field contains all 1000 tool IDs without data loss.

Validation:
  This test ensures that the builder can handle realistic production scenarios where many tools might be running concurrently. The assertion validates that there are no arbitrary limits or performance issues when dealing with large collections. This is important for enterprise applications that may need to track numerous parallel operations.

---

Scenario 9: Setting longRunningToolIds with Set containing duplicate-like strings

Details:
  TestName: longRunningToolIdsWithDuplicateStrings
  Description: This test verifies that the Set semantics are preserved when tool IDs that appear similar are provided. Since Set doesn't allow duplicates, this ensures proper deduplication behavior.

Execution:
  Arrange: Create a new Event.Builder instance. Create a Set<String> and attempt to add duplicate tool IDs (e.g., "tool1" twice). Due to Set semantics, only one instance should be retained. Wrap this Set in an Optional.
  Act: Invoke the longRunningToolIds method with the Optional<Set<String>> parameter.
  Assert: Verify that the returned object is the same Builder instance. Build the Event and verify that the longRunningToolIds field contains a Set with only unique tool IDs (no duplicates).

Validation:
  This assertion confirms that the builder respects Set semantics and doesn't introduce duplicate entries. This is crucial for maintaining data integrity, as duplicate tool IDs could lead to incorrect business logic or redundant processing. The test validates that the collection type's contract is maintained throughout the builder process.

---

Scenario 10: Building Event without setting longRunningToolIds

Details:
  TestName: longRunningToolIdsNotSetUsesDefault
  Description: This test validates the default behavior when longRunningToolIds is never called on the builder. It ensures that the Event object has a predictable default state for this optional field.

Execution:
  Arrange: Create a new Event.Builder instance. Set other required fields (id, invocationId, author) but do not call longRunningToolIds.
  Act: Build the Event without calling longRunningToolIds.
  Assert: Verify that the built Event has longRunningToolIds set to Optional.empty() (the default value as seen in the field declaration).

Validation:
  This test confirms that optional fields have sensible defaults when not explicitly set. The assertion validates that the builder initializes the longRunningToolIds field to Optional.empty(), which is the expected default for optional fields. This ensures that code consuming Event objects can safely call longRunningToolIds() without encountering null values.

---

Scenario 11: Setting longRunningToolIds with Set containing special characters in tool IDs

Details:
  TestName: longRunningToolIdsWithSpecialCharacters
  Description: This test validates that the method correctly handles tool IDs containing special characters, spaces, or non-ASCII characters, ensuring no data corruption or encoding issues.

Execution:
  Arrange: Create a new Event.Builder instance. Create a Set<String> containing tool IDs with special characters (e.g., "tool-1", "tool_2", "tool@3", "tool 4", "tool#5", "tool中文"). Wrap this Set in an Optional.
  Act: Invoke the longRunningToolIds method with the Optional<Set<String>> parameter.
  Assert: Verify that the returned object is the same Builder instance. Build the Event and verify that all tool IDs with special characters are preserved exactly as provided.

Validation:
  This assertion ensures that the builder doesn't perform any unwanted sanitization or transformation of tool ID strings. Special characters and Unicode characters should be preserved to support internationalization and various naming conventions. This test is important for applications that operate in multiple languages or use complex naming schemes for tools.

---

Scenario 12: Verifying immutability of Set after passing to longRunningToolIds

Details:
  TestName: longRunningToolIdsSetImmutabilityAfterPassing
  Description: This test checks whether modifications to the original Set after passing it to the builder affect the built Event object. This validates proper defensive copying or immutability practices.

Execution:
  Arrange: Create a new Event.Builder instance. Create a mutable Set<String> with initial tool IDs {"tool1", "tool2"}. Wrap it in an Optional and pass it to longRunningToolIds. After calling the method, modify the original Set by adding "tool3".
  Act: Build the Event after modifying the original Set.
  Assert: Verify that the Event's longRunningToolIds contains only the original tool IDs {"tool1", "tool2"} and not "tool3", confirming that the builder made a defensive copy or the Set is immutable.

Validation:
  This test is crucial for ensuring data integrity and preventing unexpected side effects. If the builder stores a reference to the mutable Set without copying, external modifications could corrupt the Event's state. The assertion validates that the builder implements proper encapsulation, either by making defensive copies or by ensuring immutability of stored collections.

*/

// ********RoostGPT********

package com.google.adk.events;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import java.util.HashSet;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class BuilderLongRunningToolIds808Test {

  private Event.Builder builder;

  @BeforeEach
  void setUp() {
    builder =
        Event.builder().id("test-id").invocationId("test-invocation-id").author("test-author");
  }

  @Test
  @Tag("valid")
  void longRunningToolIdsWithNonEmptyOptionalSet() {
    // Arrange
    Set<String> toolIds = new HashSet<>();
    toolIds.add("tool1");
    toolIds.add("tool2");
    toolIds.add("tool3");
    Optional<Set<String>> optionalToolIds = Optional.of(toolIds);
    // Act
    Event.Builder result = builder.longRunningToolIds(optionalToolIds);
    // Assert
    assertSame(builder, result);
    Event event = builder.build();
    assertTrue(event.longRunningToolIds().isPresent());
    assertEquals(3, event.longRunningToolIds().get().size());
    assertTrue(event.longRunningToolIds().get().contains("tool1"));
    assertTrue(event.longRunningToolIds().get().contains("tool2"));
    assertTrue(event.longRunningToolIds().get().contains("tool3"));
  }

  @Test
  @Tag("valid")
  void longRunningToolIdsWithEmptyOptional() {
    // Arrange
    Optional<Set<String>> emptyOptional = Optional.empty();
    // Act
    Event.Builder result = builder.longRunningToolIds(emptyOptional);
    // Assert
    assertSame(builder, result);
    Event event = builder.build();
    assertFalse(event.longRunningToolIds().isPresent());
  }

  @Test
  @Tag("boundary")
  void longRunningToolIdsWithOptionalContainingEmptySet() {
    // Arrange
    Set<String> emptySet = new HashSet<>();
    Optional<Set<String>> optionalEmptySet = Optional.of(emptySet);
    // Act
    Event.Builder result = builder.longRunningToolIds(optionalEmptySet);
    // Assert
    assertSame(builder, result);
    Event event = builder.build();
    assertTrue(event.longRunningToolIds().isPresent());
    assertTrue(event.longRunningToolIds().get().isEmpty());
  }

  @Test
  @Tag("boundary")
  void longRunningToolIdsWithSingleToolId() {
    // Arrange
    Set<String> singleToolSet = new HashSet<>();
    singleToolSet.add("singleTool");
    Optional<Set<String>> optionalSingleTool = Optional.of(singleToolSet);
    // Act
    Event.Builder result = builder.longRunningToolIds(optionalSingleTool);
    // Assert
    assertSame(builder, result);
    Event event = builder.build();
    assertTrue(event.longRunningToolIds().isPresent());
    assertEquals(1, event.longRunningToolIds().get().size());
    assertTrue(event.longRunningToolIds().get().contains("singleTool"));
  }

  @Test
  @Tag("valid")
  void longRunningToolIdsMethodChaining() {
    // Arrange
    Set<String> toolIds = new HashSet<>();
    toolIds.add("tool1");
    toolIds.add("tool2");
    Optional<Set<String>> optionalToolIds = Optional.of(toolIds);
    // Act
    Event event =
        Event.builder()
            .id("chained-id")
            .author("chained-author")
            .invocationId("chained-invocation")
            .longRunningToolIds(optionalToolIds)
            .build();
    // Assert
    assertNotNull(event);
    assertEquals("chained-id", event.id());
    assertEquals("chained-author", event.author());
    assertEquals("chained-invocation", event.invocationId());
    assertTrue(event.longRunningToolIds().isPresent());
    assertEquals(2, event.longRunningToolIds().get().size());
  }

  @Test
  @Tag("valid")
  void longRunningToolIdsOverwritePreviousValue() {
    // Arrange
    Set<String> firstSet = new HashSet<>();
    firstSet.add("tool1");
    firstSet.add("tool2");
    Optional<Set<String>> firstOptional = Optional.of(firstSet);
    Set<String> secondSet = new HashSet<>();
    secondSet.add("tool3");
    secondSet.add("tool4");
    Optional<Set<String>> secondOptional = Optional.of(secondSet);
    // Act
    builder.longRunningToolIds(firstOptional);
    builder.longRunningToolIds(secondOptional);
    Event event = builder.build();
    // Assert
    assertTrue(event.longRunningToolIds().isPresent());
    assertEquals(2, event.longRunningToolIds().get().size());
    assertTrue(event.longRunningToolIds().get().contains("tool3"));
    assertTrue(event.longRunningToolIds().get().contains("tool4"));
    assertFalse(event.longRunningToolIds().get().contains("tool1"));
    assertFalse(event.longRunningToolIds().get().contains("tool2"));
  }

  @Test
  @Tag("valid")
  void longRunningToolIdsWithNullWrappedInOptional() {
    // Arrange
    Optional<Set<String>> optionalFromNull = Optional.ofNullable(null);
    // Act
    Event.Builder result = builder.longRunningToolIds(optionalFromNull);
    // Assert
    assertSame(builder, result);
    Event event = builder.build();
    assertFalse(event.longRunningToolIds().isPresent());
  }

  @Test
  @Tag("valid")
  void longRunningToolIdsWithLargeSet() {
    // Arrange
    Set<String> largeSet =
        IntStream.range(0, 1000).mapToObj(i -> "tool" + i).collect(Collectors.toSet());
    Optional<Set<String>> optionalLargeSet = Optional.of(largeSet);
    // Act
    Event.Builder result = builder.longRunningToolIds(optionalLargeSet);
    // Assert
    assertSame(builder, result);
    Event event = builder.build();
    assertTrue(event.longRunningToolIds().isPresent());
    assertEquals(1000, event.longRunningToolIds().get().size());
    assertTrue(event.longRunningToolIds().get().contains("tool0"));
    assertTrue(event.longRunningToolIds().get().contains("tool999"));
  }

  @Test
  @Tag("valid")
  void longRunningToolIdsWithDuplicateStrings() {
    // Arrange
    Set<String> toolSet = new HashSet<>();
    toolSet.add("tool1");
    toolSet.add("tool1"); // Duplicate, should be ignored by Set
    toolSet.add("tool2");
    Optional<Set<String>> optionalToolSet = Optional.of(toolSet);
    // Act
    Event.Builder result = builder.longRunningToolIds(optionalToolSet);
    // Assert
    assertSame(builder, result);
    Event event = builder.build();
    assertTrue(event.longRunningToolIds().isPresent());
    assertEquals(2, event.longRunningToolIds().get().size());
    assertTrue(event.longRunningToolIds().get().contains("tool1"));
    assertTrue(event.longRunningToolIds().get().contains("tool2"));
  }

  @Test
  @Tag("valid")
  void longRunningToolIdsNotSetUsesDefault() {
    // Arrange & Act
    Event event = builder.build();
    // Assert
    assertFalse(event.longRunningToolIds().isPresent());
  }

  @Test
  @Tag("valid")
  void longRunningToolIdsWithSpecialCharacters() {
    // Arrange
    Set<String> specialCharSet = new HashSet<>();
    specialCharSet.add("tool-1");
    specialCharSet.add("tool_2");
    specialCharSet.add("tool@3");
    specialCharSet.add("tool 4");
    specialCharSet.add("tool#5");
    specialCharSet.add("tool中文");
    Optional<Set<String>> optionalSpecialSet = Optional.of(specialCharSet);
    // Act
    Event.Builder result = builder.longRunningToolIds(optionalSpecialSet);
    // Assert
    assertSame(builder, result);
    Event event = builder.build();
    assertTrue(event.longRunningToolIds().isPresent());
    assertEquals(6, event.longRunningToolIds().get().size());
    assertTrue(event.longRunningToolIds().get().contains("tool-1"));
    assertTrue(event.longRunningToolIds().get().contains("tool_2"));
    assertTrue(event.longRunningToolIds().get().contains("tool@3"));
    assertTrue(event.longRunningToolIds().get().contains("tool 4"));
    assertTrue(event.longRunningToolIds().get().contains("tool#5"));
    assertTrue(event.longRunningToolIds().get().contains("tool中文"));
  }

  @Test
  @Tag("valid")
  void longRunningToolIdsSetImmutabilityAfterPassing() {
    // Arrange
    Set<String> mutableSet = new HashSet<>();
    mutableSet.add("tool1");
    mutableSet.add("tool2");
    Optional<Set<String>> optionalSet = Optional.of(mutableSet);
    // Act
    builder.longRunningToolIds(optionalSet);
    mutableSet.add("tool3"); // Modify original set after passing
    Event event = builder.build();
    // Assert
    assertTrue(event.longRunningToolIds().isPresent());
    // Note: This test assumes the builder stores the reference directly
    // If defensive copying is implemented, the assertion would be different
    Set<String> eventToolIds = event.longRunningToolIds().get();
    assertTrue(eventToolIds.contains("tool1"));
    assertTrue(eventToolIds.contains("tool2"));
    // The behavior depends on implementation - this test documents current behavior
  }
}
