/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-repo using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=author_b13984b5ea
ROOST_METHOD_SIG_HASH=author_ac96470688

Scenario 1: Setting a Valid Non-Empty Author String

Details:
  TestName: authorWithValidNonEmptyString
  Description: This test verifies that the author() method correctly accepts and stores a valid non-empty string value. The method should set the author field and return the Builder instance for method chaining.

Execution:
  Arrange: Create a new Event.Builder instance and prepare a valid non-empty author string (e.g., "agent_1").
  Act: Invoke the author() method with the valid string value and capture the returned Builder instance.
  Assert: Verify that the returned object is the same Builder instance (for fluent API chaining). Build the Event object and verify that the author field is set to the expected value using the author() getter method.

Validation:
  The assertion verifies that the Builder pattern's fluent interface is maintained by returning the same Builder instance. Additionally, it confirms that the author value is correctly stored and retrievable after building the Event object. This is critical for the builder pattern's usability and ensures proper data assignment in the Event object construction process.

---

Scenario 2: Setting Author with Null Value

Details:
  TestName: authorWithNullValue
  Description: This test checks the behavior of the author() method when a null value is passed as the parameter. The method should accept null without throwing an exception and store it in the author field.

Execution:
  Arrange: Create a new Event.Builder instance.
  Act: Invoke the author() method with a null value and capture the returned Builder instance.
  Assert: Verify that the method returns the Builder instance for chaining. Build the Event object and verify that the author field is null using the author() getter method.

Validation:
  This test ensures that the method handles null values gracefully, which is important for scenarios where the author information might not be available at the time of builder initialization. The @Nullable annotation on similar methods in the class suggests that null values are acceptable. This test validates defensive programming practices and prevents NullPointerException in downstream code.

---

Scenario 3: Setting Author with Empty String

Details:
  TestName: authorWithEmptyString
  Description: This test validates that the author() method correctly handles an empty string ("") as input. The method should accept and store the empty string value.

Execution:
  Arrange: Create a new Event.Builder instance and prepare an empty string.
  Act: Invoke the author() method with the empty string and capture the returned Builder instance.
  Assert: Verify that the returned object is the same Builder instance. Build the Event object and verify that the author field contains an empty string using the author() getter method.

Validation:
  This test is important for edge case handling where an empty string might be provided instead of null or a meaningful value. It ensures that the method doesn't perform any validation or transformation on the input, maintaining the exact value provided by the caller. This behavior is consistent with the builder pattern's philosophy of accepting values as-is.

---

Scenario 4: Setting Author with Whitespace-Only String

Details:
  TestName: authorWithWhitespaceOnlyString
  Description: This test examines the behavior when the author() method receives a string containing only whitespace characters (spaces, tabs, newlines).

Execution:
  Arrange: Create a new Event.Builder instance and prepare a whitespace-only string (e.g., "   ", "\t", "\n").
  Act: Invoke the author() method with the whitespace-only string and capture the returned Builder instance.
  Assert: Verify that the method returns the Builder instance. Build the Event object and verify that the author field contains the exact whitespace string provided.

Validation:
  This test ensures that the method does not trim or validate the input string, preserving whitespace as provided. This is important for understanding the method's contract and ensuring that any validation or sanitization is performed at the appropriate layer (e.g., at the business logic level rather than the builder level).

---

Scenario 5: Setting Author Multiple Times with Different Values

Details:
  TestName: authorSetMultipleTimesWithDifferentValues
  Description: This test verifies that calling the author() method multiple times on the same Builder instance correctly overwrites the previous value with the most recent one.

Execution:
  Arrange: Create a new Event.Builder instance and prepare multiple different author strings (e.g., "agent_1", "agent_2", "user").
  Act: Invoke the author() method multiple times with different values in sequence. Build the Event object after the final invocation.
  Assert: Verify that the author field in the built Event object contains only the last value set (the most recent invocation).

Validation:
  This test validates the expected behavior of builder methods where subsequent calls override previous values rather than accumulating them. This is crucial for understanding the builder's state management and ensuring predictable behavior when the same setter is called multiple times during object construction.

---

Scenario 6: Setting Author with Special Characters

Details:
  TestName: authorWithSpecialCharacters
  Description: This test checks that the author() method correctly handles strings containing special characters, including punctuation, symbols, and Unicode characters.

Execution:
  Arrange: Create a new Event.Builder instance and prepare a string with special characters (e.g., "agent@123", "user_#1", "агент_1", "用户").
  Act: Invoke the author() method with the special character string and capture the returned Builder instance.
  Assert: Verify that the method returns the Builder instance. Build the Event object and verify that the author field contains the exact string with all special characters preserved.

Validation:
  This test ensures that the method handles international characters and special symbols correctly, which is important for applications supporting multiple languages and diverse naming conventions. It validates that no character encoding issues or sanitization occurs at the builder level.

---

Scenario 7: Setting Author with Very Long String

Details:
  TestName: authorWithVeryLongString
  Description: This test validates the behavior of the author() method when provided with a very long string value (e.g., 10,000 characters or more).

Execution:
  Arrange: Create a new Event.Builder instance and generate a very long string (e.g., repeating a pattern to create a 10,000+ character string).
  Act: Invoke the author() method with the very long string and capture the returned Builder instance.
  Assert: Verify that the method returns the Builder instance without throwing an exception. Build the Event object and verify that the author field contains the complete long string.

Validation:
  This test checks for potential memory or performance issues with large string values and ensures that the method doesn't impose arbitrary length restrictions. It's important for understanding the method's scalability and identifying any potential issues with large data inputs.

---

Scenario 8: Builder Method Chaining with Author

Details:
  TestName: authorMethodChainingWithOtherBuilderMethods
  Description: This test verifies that the author() method properly supports method chaining by returning the Builder instance, allowing it to be used in a fluent API style with other builder methods.

Execution:
  Arrange: Create a new Event.Builder instance and prepare test values for multiple fields including author, id, and invocationId.
  Act: Chain multiple builder method calls together, including author(), in a single statement (e.g., builder.id("id1").author("agent_1").invocationId("inv1")).
  Assert: Verify that the chaining executes without errors. Build the Event object and verify that all chained values, including the author, are correctly set in the resulting Event object.

Validation:
  This test validates the fluent API design pattern implementation, ensuring that the @CanIgnoreReturnValue annotation and return type are correctly implemented. Method chaining is a key feature of the builder pattern, improving code readability and usability. This test ensures that the author() method integrates seamlessly with the overall builder API.

---

Scenario 9: Setting Author Before and After Setting Other Fields

Details:
  TestName: authorSetBeforeAndAfterOtherFields
  Description: This test verifies that the order of setting the author field relative to other builder fields does not affect the final result.

Execution:
  Arrange: Create two Event.Builder instances. Prepare test values for author, id, and invocationId fields.
  Act: In the first builder, set author first, then other fields. In the second builder, set other fields first, then author. Build both Event objects.
  Assert: Verify that both Event objects have identical author values and that the order of method calls does not affect the final state.

Validation:
  This test ensures that the builder maintains independence between field setters and that the order of operations doesn't create unexpected side effects. This is important for builder pattern correctness and user confidence in using the API in any order that suits their needs.

---

Scenario 10: Setting Author with Literal "user" Value

Details:
  TestName: authorWithUserLiteralValue
  Description: This test specifically validates setting the author field to the literal string "user", which according to the documentation is a special value representing user-authored events.

Execution:
  Arrange: Create a new Event.Builder instance and prepare the string "user".
  Act: Invoke the author() method with the "user" string value.
  Assert: Verify that the method returns the Builder instance. Build the Event object and verify that the author field is exactly "user".

Validation:
  According to the class documentation, the author field can be either the name of an agent or the literal "user". This test validates that this specific use case works correctly and that the "user" value is treated as a regular string without any special processing. This is important for the semantic correctness of the Event model in distinguishing between user and agent events.

---

Scenario 11: Setting Author with Agent Name Format

Details:
  TestName: authorWithAgentNameFormat
  Description: This test validates setting the author field with typical agent name formats that might be used in the application (e.g., "agent_1", "agent_2", "primary_agent").

Execution:
  Arrange: Create a new Event.Builder instance and prepare an agent name string following typical naming conventions (e.g., "agent_1").
  Act: Invoke the author() method with the agent name string.
  Assert: Verify that the method returns the Builder instance. Build the Event object and verify that the author field contains the exact agent name provided.

Validation:
  This test ensures that typical agent naming patterns are correctly handled, which is important for the primary use case of the author field. It validates that the method works correctly for the most common scenario where events are authored by named agents in the system.

---

Scenario 12: Verifying Builder Instance Return for Fluent API

Details:
  TestName: authorReturnsBuilderInstanceForFluentApi
  Description: This test explicitly verifies that the author() method returns the exact same Builder instance (not a copy or new instance) to support the fluent API pattern.

Execution:
  Arrange: Create a new Event.Builder instance.
  Act: Invoke the author() method with any valid string value and capture the returned object.
  Assert: Use reference equality (==) or assertSame() to verify that the returned Builder instance is the exact same object as the original Builder instance.

Validation:
  This test validates a critical aspect of the builder pattern implementation: that methods return 'this' rather than creating new instances. This is essential for both performance (avoiding unnecessary object creation) and correctness (ensuring all mutations apply to the same builder instance). The @CanIgnoreReturnValue annotation indicates the return value can be ignored, but when used, it must be the same instance.

*/

// ********RoostGPT********

package com.google.adk.events;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.genai.types.Content;
import com.google.genai.types.FinishReason;
import java.util.HashSet;
import java.util.Set;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class BuilderAuthorTest {

  private Event.Builder builder;

  @BeforeEach
  void setUp() {
    builder = Event.builder();
  }

  @Test
  @Tag("valid")
  void authorWithValidNonEmptyString() {
    String validAuthor = "agent_1";

    Event.Builder returnedBuilder = builder.author(validAuthor);

    assertSame(builder, returnedBuilder);
    Event event = builder.id("test-id").invocationId("test-invocation").build();
    assertEquals(validAuthor, event.author());
  }

  @Test
  @Tag("boundary")
  void authorWithNullValue() {
    Event.Builder returnedBuilder = builder.author(null);

    assertSame(builder, returnedBuilder);
    Event event = builder.id("test-id").invocationId("test-invocation").build();
    assertNull(event.author());
  }

  @Test
  @Tag("boundary")
  void authorWithEmptyString() {
    String emptyString = "";

    Event.Builder returnedBuilder = builder.author(emptyString);

    assertSame(builder, returnedBuilder);
    Event event = builder.id("test-id").invocationId("test-invocation").build();
    assertEquals(emptyString, event.author());
  }

  @Test
  @Tag("boundary")
  void authorWithWhitespaceOnlyString() {
    String whitespaceString = "   ";

    Event.Builder returnedBuilder = builder.author(whitespaceString);

    assertSame(builder, returnedBuilder);
    Event event = builder.id("test-id").invocationId("test-invocation").build();
    assertEquals(whitespaceString, event.author());
  }

  @Test
  @Tag("valid")
  void authorSetMultipleTimesWithDifferentValues() {
    String firstAuthor = "agent_1";
    String secondAuthor = "agent_2";
    String thirdAuthor = "user";

    builder.author(firstAuthor).author(secondAuthor).author(thirdAuthor);

    Event event = builder.id("test-id").invocationId("test-invocation").build();
    assertEquals(thirdAuthor, event.author());
  }

  @Test
  @Tag("valid")
  void authorWithSpecialCharacters() {
    String[] specialCharacterAuthors = {
      "agent@123",
      "user_#1",
      "агент_1",
      "用户",
      "agent!@#$%^&*()",
      "user-with-dashes",
      "agent.with.dots"
    };

    for (String specialAuthor : specialCharacterAuthors) {
      Event.Builder testBuilder = Event.builder();
      testBuilder.author(specialAuthor);

      Event event = testBuilder.id("test-id").invocationId("test-invocation").build();
      assertEquals(specialAuthor, event.author());
    }
  }

  @Test
  @Tag("boundary")
  void authorWithVeryLongString() {
    StringBuilder longStringBuilder = new StringBuilder();
    for (int i = 0; i < 10000; i++) {
      longStringBuilder.append("a");
    }
    String veryLongString = longStringBuilder.toString();

    Event.Builder returnedBuilder = builder.author(veryLongString);

    assertSame(builder, returnedBuilder);
    Event event = builder.id("test-id").invocationId("test-invocation").build();
    assertEquals(veryLongString, event.author());
    assertEquals(10000, event.author().length());
  }

  @Test
  @Tag("integration")
  void authorMethodChainingWithOtherBuilderMethods() {
    String authorValue = "agent_1";
    String idValue = "id1";
    String invocationIdValue = "inv1";

    Event event =
        Event.builder()
            .id(idValue)
            .author(authorValue)
            .invocationId(invocationIdValue)
            .partial(true)
            .turnComplete(false)
            .build();

    assertEquals(authorValue, event.author());
    assertEquals(idValue, event.id());
    assertEquals(invocationIdValue, event.invocationId());
    assertTrue(event.partial().isPresent());
    assertTrue(event.partial().get());
    assertTrue(event.turnComplete().isPresent());
    assertFalse(event.turnComplete().get());
  }

  @Test
  @Tag("valid")
  void authorSetBeforeAndAfterOtherFields() {
    String authorValue = "agent_1";
    String idValue = "test-id";
    String invocationIdValue = "test-invocation";

    Event event1 =
        Event.builder().author(authorValue).id(idValue).invocationId(invocationIdValue).build();

    Event event2 =
        Event.builder().id(idValue).invocationId(invocationIdValue).author(authorValue).build();

    assertEquals(event1.author(), event2.author());
    assertEquals(authorValue, event1.author());
    assertEquals(authorValue, event2.author());
  }

  @Test
  @Tag("valid")
  void authorWithUserLiteralValue() {
    String userLiteral = "user";

    Event.Builder returnedBuilder = builder.author(userLiteral);

    assertSame(builder, returnedBuilder);
    Event event = builder.id("test-id").invocationId("test-invocation").build();
    assertEquals(userLiteral, event.author());
  }

  @Test
  @Tag("valid")
  void authorWithAgentNameFormat() {
    String[] agentNames = {
      "agent_1", "agent_2", "primary_agent", "secondary_agent", "agent_main", "agent_backup"
    };

    for (String agentName : agentNames) {
      Event.Builder testBuilder = Event.builder();
      testBuilder.author(agentName);

      Event event = testBuilder.id("test-id").invocationId("test-invocation").build();
      assertEquals(agentName, event.author());
    }
  }

  @Test
  @Tag("valid")
  void authorReturnsBuilderInstanceForFluentApi() {
    String authorValue = "agent_1";

    Event.Builder returnedBuilder = builder.author(authorValue);

    assertSame(builder, returnedBuilder);
    assertNotNull(returnedBuilder);
  }

  @Test
  @Tag("valid")
  void authorWithTabAndNewlineCharacters() {
    String authorWithTabs = "\tagent\t";
    String authorWithNewlines = "\nagent\n";
    String authorWithMixed = "\t\nagent\n\t";

    Event event1 =
        Event.builder()
            .id("test-id")
            .invocationId("test-invocation")
            .author(authorWithTabs)
            .build();
    assertEquals(authorWithTabs, event1.author());

    Event event2 =
        Event.builder()
            .id("test-id")
            .invocationId("test-invocation")
            .author(authorWithNewlines)
            .build();
    assertEquals(authorWithNewlines, event2.author());

    Event event3 =
        Event.builder()
            .id("test-id")
            .invocationId("test-invocation")
            .author(authorWithMixed)
            .build();
    assertEquals(authorWithMixed, event3.author());
  }

  @Test
  @Tag("integration")
  void authorWithCompleteEventBuilding() {
    String authorValue = "agent_1";
    Content mockContent = mock(Content.class);
    EventActions mockActions = EventActions.builder().build();
    Set<String> longRunningIds = new HashSet<>();
    longRunningIds.add("tool1");

    Event event =
        Event.builder()
            .id("test-id")
            .invocationId("test-invocation")
            .author(authorValue)
            .content(mockContent)
            .actions(mockActions)
            .longRunningToolIds(longRunningIds)
            .partial(true)
            .turnComplete(false)
            .finishReason(FinishReason.STOP)
            .build();

    assertEquals(authorValue, event.author());
    assertNotNull(event.id());
    assertNotNull(event.invocationId());
    assertTrue(event.content().isPresent());
    assertNotNull(event.actions());
    assertTrue(event.longRunningToolIds().isPresent());
    assertTrue(event.partial().isPresent());
    assertTrue(event.turnComplete().isPresent());
    assertTrue(event.finishReason().isPresent());
  }

  @Test
  @Tag("valid")
  void authorWithNumericString() {
    String numericAuthor = "12345";

    Event.Builder returnedBuilder = builder.author(numericAuthor);

    assertSame(builder, returnedBuilder);
    Event event = builder.id("test-id").invocationId("test-invocation").build();
    assertEquals(numericAuthor, event.author());
  }

  @Test
  @Tag("valid")
  void authorWithMixedCaseString() {
    String mixedCaseAuthor = "AgEnT_MiXeD_CaSe";

    Event.Builder returnedBuilder = builder.author(mixedCaseAuthor);

    assertSame(builder, returnedBuilder);
    Event event = builder.id("test-id").invocationId("test-invocation").build();
    assertEquals(mixedCaseAuthor, event.author());
  }

  @Test
  @Tag("boundary")
  void authorWithSingleCharacter() {
    String singleChar = "a";

    Event.Builder returnedBuilder = builder.author(singleChar);

    assertSame(builder, returnedBuilder);
    Event event = builder.id("test-id").invocationId("test-invocation").build();
    assertEquals(singleChar, event.author());
  }

  @Test
  @Tag("valid")
  void authorPreservesExactInputValue() {
    String[] testValues = {
      "  leading spaces",
      "trailing spaces  ",
      "  both sides  ",
      "UPPERCASE",
      "lowercase",
      "123numeric456"
    };

    for (String testValue : testValues) {
      Event.Builder testBuilder = Event.builder();
      testBuilder.author(testValue);

      Event event = testBuilder.id("test-id").invocationId("test-invocation").build();
      assertEquals(testValue, event.author());
    }
  }
}
