/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-repo using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=errorCode_0821fe3a69
ROOST_METHOD_SIG_HASH=errorCode_eb05013295

Scenario 1: Setting Error Code with Non-Null FinishReason Value

Details:
  TestName: errorCodeWithNonNullFinishReason
  Description: This test verifies that the errorCode method correctly accepts a non-null FinishReason value and wraps it in an Optional. It ensures that the builder properly stores the error code and returns the builder instance for method chaining.

Execution:
  Arrange: Create a new Event.Builder instance and prepare a valid FinishReason enum value (e.g., FinishReason.SAFETY).
  Act: Invoke the errorCode method on the builder with the non-null FinishReason value.
  Assert: Verify that the method returns the same builder instance (for fluent API chaining). Build the Event object and verify that the errorCode field contains an Optional with the provided FinishReason value.

Validation:
  The assertion verifies that the errorCode method correctly wraps a non-null FinishReason value in an Optional and stores it in the builder's errorCode field. This is critical for indicating error conditions in event processing, allowing downstream components to identify and handle specific error scenarios. The test ensures the builder pattern's fluent interface is maintained by returning the builder instance.

---

Scenario 2: Setting Error Code with Null Value

Details:
  TestName: errorCodeWithNullValue
  Description: This test validates that the errorCode method correctly handles null input by creating an empty Optional. It ensures that passing null as the FinishReason parameter results in Optional.empty() being stored.

Execution:
  Arrange: Create a new Event.Builder instance.
  Act: Invoke the errorCode method with a null FinishReason value.
  Assert: Verify that the method returns the builder instance. Build the Event object and verify that the errorCode field contains Optional.empty().

Validation:
  This test confirms that the method properly handles null values using Optional.ofNullable(), which is essential for avoiding NullPointerExceptions. When no error code is present, the Optional should be empty, allowing consumers to safely check for the presence of an error code without null checks. This follows Java best practices for optional value handling.

---

Scenario 3: Method Chaining with Error Code

Details:
  TestName: errorCodeMethodChaining
  Description: This test verifies that the errorCode method supports method chaining by returning the builder instance, allowing multiple builder methods to be called in sequence.

Execution:
  Arrange: Create a new Event.Builder instance and prepare a FinishReason value.
  Act: Chain multiple builder method calls including errorCode, followed by other builder methods like id(), author(), and invocationId().
  Assert: Verify that all chained method calls execute successfully and the final built Event object contains all the set values including the error code.

Validation:
  This test ensures the builder pattern's fluent interface works correctly with the errorCode method. Method chaining is a key feature of the builder pattern that improves code readability and usability. The test confirms that the errorCode method returns 'this' (the builder instance), enabling developers to construct Event objects with a clean, readable syntax.

---

Scenario 4: Overwriting Previous Error Code Value

Details:
  TestName: errorCodeOverwritesPreviousValue
  Description: This test validates that calling the errorCode method multiple times overwrites the previous value, ensuring only the last set value is retained.

Execution:
  Arrange: Create a new Event.Builder instance.
  Act: Call the errorCode method with a first FinishReason value (e.g., FinishReason.SAFETY), then call it again with a different FinishReason value (e.g., FinishReason.MAX_TOKENS).
  Assert: Build the Event object and verify that the errorCode field contains only the last set value (FinishReason.MAX_TOKENS).

Validation:
  This test confirms that the errorCode field in the builder can be updated and that subsequent calls replace the previous value rather than accumulating values. This behavior is expected in builder patterns where each setter method should update the corresponding field. It ensures predictable behavior when the same method is called multiple times during object construction.

---

Scenario 5: Error Code with Different FinishReason Enum Values

Details:
  TestName: errorCodeWithVariousFinishReasonValues
  Description: This test verifies that the errorCode method correctly handles all possible FinishReason enum values, ensuring compatibility with the entire enum range.

Execution:
  Arrange: Create multiple Event.Builder instances, one for each possible FinishReason enum value.
  Act: For each builder, invoke the errorCode method with a different FinishReason enum value.
  Assert: Build each Event object and verify that each errorCode field contains the correct Optional-wrapped FinishReason value corresponding to what was set.

Validation:
  This test ensures that the errorCode method works correctly with all valid FinishReason enum constants. Since FinishReason is an enum type from the imported package, the method should accept any valid enum value. This comprehensive test prevents issues where certain enum values might be incompatible or cause unexpected behavior.

---

Scenario 6: Error Code Null Followed by Non-Null Value

Details:
  TestName: errorCodeNullThenNonNull
  Description: This test validates the behavior when the errorCode method is first called with null and then called again with a non-null FinishReason value.

Execution:
  Arrange: Create a new Event.Builder instance.
  Act: First, call errorCode with null, then call errorCode again with a valid FinishReason value.
  Assert: Build the Event object and verify that the errorCode field contains an Optional with the non-null FinishReason value, confirming the null value was overwritten.

Validation:
  This test ensures that the builder correctly handles state transitions from empty to populated Optional values. It confirms that setting a null value doesn't permanently lock the field to empty, and subsequent non-null values are properly stored. This is important for scenarios where builder state might be conditionally modified during object construction.

---

Scenario 7: Error Code Non-Null Followed by Null Value

Details:
  TestName: errorCodeNonNullThenNull
  Description: This test validates the behavior when the errorCode method is first called with a non-null FinishReason value and then called again with null.

Execution:
  Arrange: Create a new Event.Builder instance.
  Act: First, call errorCode with a valid FinishReason value, then call errorCode again with null.
  Assert: Build the Event object and verify that the errorCode field contains Optional.empty(), confirming the non-null value was overwritten by the null value.

Validation:
  This test confirms that the builder allows clearing a previously set error code by passing null. This is useful in scenarios where error conditions might be conditionally set and then cleared based on subsequent logic. The test ensures that Optional.ofNullable() correctly converts null to Optional.empty(), maintaining consistency in the Optional-based API.

---

Scenario 8: Error Code in Complete Event Building

Details:
  TestName: errorCodeInCompleteEventConstruction
  Description: This test verifies that the errorCode method works correctly as part of building a complete Event object with all required and optional fields populated.

Execution:
  Arrange: Create a new Event.Builder instance and prepare values for all fields including id, invocationId, author, content, actions, and errorCode with a FinishReason value.
  Act: Set all fields using their respective builder methods, including errorCode, and build the Event object.
  Assert: Verify that the built Event object contains all set values, with the errorCode field properly populated with the Optional-wrapped FinishReason value.

Validation:
  This integration-style test ensures that the errorCode method works correctly in conjunction with other builder methods when constructing a complete Event object. It validates that setting the error code doesn't interfere with other fields and that the final Event object is properly constructed with all fields intact. This is important for real-world usage where multiple fields are typically set together.

---

Scenario 9: Error Code Return Type Verification

Details:
  TestName: errorCodeReturnsBuilderInstance
  Description: This test explicitly verifies that the errorCode method returns the exact same Builder instance that it was called on, confirming proper implementation of the fluent builder pattern.

Execution:
  Arrange: Create a new Event.Builder instance and store a reference to it.
  Act: Call the errorCode method with a FinishReason value and capture the returned value.
  Assert: Verify using reference equality (==) that the returned Builder instance is the exact same object as the original builder instance.

Validation:
  This test confirms that the errorCode method returns 'this' rather than creating a new builder instance. This is crucial for the builder pattern's fluent interface, ensuring memory efficiency and allowing proper method chaining. The test uses reference equality to verify that the same object instance is returned, not just an equal object.

---

Scenario 10: Error Code with @Nullable Annotation Compliance

Details:
  TestName: errorCodeNullableAnnotationCompliance
  Description: This test verifies that the errorCode method correctly honors the @Nullable annotation on its parameter, accepting null values without throwing exceptions.

Execution:
  Arrange: Create a new Event.Builder instance.
  Act: Call the errorCode method with an explicit null value.
  Assert: Verify that no exception is thrown and the method completes successfully. Build the Event object and verify that the errorCode field contains Optional.empty().

Validation:
  This test ensures that the @Nullable annotation on the method parameter is not just documentation but reflects actual behavior. The method should gracefully handle null inputs without throwing NullPointerException or other exceptions. This is important for API contracts and helps prevent runtime errors when the method is called with null values, which is explicitly allowed by the annotation.

*/

// ********RoostGPT********

package com.google.adk.events;

import static com.google.common.truth.Truth.assertThat;
import static com.google.common.truth.Truth8.assertThat;

import com.google.genai.types.FinishReason;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class BuilderErrorCodeTest {

  @Test
  @Tag("valid")
  void errorCodeWithNonNullFinishReason() {
    Event.Builder builder = Event.builder();
    FinishReason finishReason = FinishReason.SAFETY;
    Event.Builder result = builder.errorCode(finishReason);
    assertThat(result).isSameInstanceAs(builder);
    Event event = builder.id("test-id").invocationId("inv-id").author("test-author").build();
    assertThat(event.errorCode()).hasValue(finishReason);
  }

  @Test
  @Tag("valid")
  void errorCodeWithNullValue() {
    Event.Builder builder = Event.builder();
    Event.Builder result = builder.errorCode((FinishReason) null);
    assertThat(result).isSameInstanceAs(builder);
    Event event = builder.id("test-id").invocationId("inv-id").author("test-author").build();
    assertThat(event.errorCode()).isEmpty();
  }

  @Test
  @Tag("valid")
  void errorCodeMethodChaining() {
    Event.Builder builder = Event.builder();
    FinishReason finishReason = FinishReason.MAX_TOKENS;
    Event event =
        builder
            .id("test-id")
            .invocationId("inv-id")
            .author("test-author")
            .errorCode(finishReason)
            .build();
    assertThat(event.id()).isEqualTo("test-id");
    assertThat(event.invocationId()).isEqualTo("inv-id");
    assertThat(event.author()).isEqualTo("test-author");
    assertThat(event.errorCode()).hasValue(finishReason);
  }

  @Test
  @Tag("valid")
  void errorCodeOverwritesPreviousValue() {
    Event.Builder builder = Event.builder();
    FinishReason firstValue = FinishReason.SAFETY;
    FinishReason secondValue = FinishReason.MAX_TOKENS;
    builder.errorCode(firstValue);
    builder.errorCode(secondValue);
    Event event = builder.id("test-id").invocationId("inv-id").author("test-author").build();
    assertThat(event.errorCode()).hasValue(secondValue);
  }

  @Test
  @Tag("valid")
  void errorCodeWithVariousFinishReasonValues() {
    FinishReason[] finishReasons =
        new FinishReason[] {
          FinishReason.STOP,
          FinishReason.MAX_TOKENS,
          FinishReason.SAFETY,
          FinishReason.RECITATION,
          FinishReason.OTHER
        };
    for (FinishReason finishReason : finishReasons) {
      Event.Builder builder = Event.builder();
      builder.errorCode(finishReason);
      Event event = builder.id("test-id").invocationId("inv-id").author("test-author").build();
      assertThat(event.errorCode()).hasValue(finishReason);
    }
  }

  @Test
  @Tag("valid")
  void errorCodeNullThenNonNull() {
    Event.Builder builder = Event.builder();
    FinishReason finishReason = FinishReason.SAFETY;
    builder.errorCode((FinishReason) null);
    builder.errorCode(finishReason);
    Event event = builder.id("test-id").invocationId("inv-id").author("test-author").build();
    assertThat(event.errorCode()).hasValue(finishReason);
  }

  @Test
  @Tag("valid")
  void errorCodeNonNullThenNull() {
    Event.Builder builder = Event.builder();
    FinishReason finishReason = FinishReason.MAX_TOKENS;
    builder.errorCode(finishReason);
    builder.errorCode((FinishReason) null);
    Event event = builder.id("test-id").invocationId("inv-id").author("test-author").build();
    assertThat(event.errorCode()).isEmpty();
  }

  @Test
  @Tag("integration")
  void errorCodeInCompleteEventConstruction() {
    Event.Builder builder = Event.builder();
    FinishReason finishReason = FinishReason.SAFETY;
    String id = "event-123";
    String invocationId = "inv-456";
    String author = "test-author";
    EventActions actions = EventActions.builder().build();
    Event event =
        builder
            .id(id)
            .invocationId(invocationId)
            .author(author)
            .errorCode(finishReason)
            .actions(actions)
            .partial(true)
            .turnComplete(false)
            .build();
    assertThat(event.id()).isEqualTo(id);
    assertThat(event.invocationId()).isEqualTo(invocationId);
    assertThat(event.author()).isEqualTo(author);
    assertThat(event.errorCode()).hasValue(finishReason);
    assertThat(event.partial()).hasValue(true);
    assertThat(event.turnComplete()).hasValue(false);
  }

  @Test
  @Tag("valid")
  void errorCodeReturnsBuilderInstance() {
    Event.Builder builder = Event.builder();
    FinishReason finishReason = FinishReason.SAFETY;
    Event.Builder returnedBuilder = builder.errorCode(finishReason);
    assertThat(returnedBuilder).isSameInstanceAs(builder);
  }

  @Test
  @Tag("valid")
  void errorCodeNullableAnnotationCompliance() {
    Event.Builder builder = Event.builder();
    Event.Builder result = builder.errorCode((FinishReason) null);
    assertThat(result).isNotNull();
    Event event = builder.id("test-id").invocationId("inv-id").author("test-author").build();
    assertThat(event.errorCode()).isEmpty();
  }

  @Test
  @Tag("boundary")
  void errorCodeWithMultipleNullCalls() {
    Event.Builder builder = Event.builder();
    builder.errorCode((FinishReason) null);
    builder.errorCode((FinishReason) null);
    builder.errorCode((FinishReason) null);
    Event event = builder.id("test-id").invocationId("inv-id").author("test-author").build();
    assertThat(event.errorCode()).isEmpty();
  }

  @Test
  @Tag("valid")
  void errorCodeWithOptionalOverload() {
    Event.Builder builder = Event.builder();
    FinishReason finishReason = FinishReason.SAFETY;
    builder.errorCode(finishReason);
    Event event = builder.id("test-id").invocationId("inv-id").author("test-author").build();
    assertThat(event.errorCode()).hasValue(finishReason);
    Event.Builder builder2 = Event.builder();
    builder2.errorCode(Optional.of(finishReason));
    Event event2 = builder2.id("test-id").invocationId("inv-id").author("test-author").build();
    assertThat(event2.errorCode()).hasValue(finishReason);
  }

  @Test
  @Tag("valid")
  void errorCodeAlternatingNullAndNonNull() {
    Event.Builder builder = Event.builder();
    FinishReason firstValue = FinishReason.SAFETY;
    FinishReason secondValue = FinishReason.MAX_TOKENS;
    builder.errorCode(firstValue);
    builder.errorCode((FinishReason) null);
    builder.errorCode(secondValue);
    Event event = builder.id("test-id").invocationId("inv-id").author("test-author").build();
    assertThat(event.errorCode()).hasValue(secondValue);
  }

  @Test
  @Tag("integration")
  void errorCodeWithErrorMessageCombination() {
    Event.Builder builder = Event.builder();
    FinishReason finishReason = FinishReason.SAFETY;
    String errorMessage = "Content blocked due to safety concerns";
    Event event =
        builder
            .id("test-id")
            .invocationId("inv-id")
            .author("test-author")
            .errorCode(finishReason)
            .errorMessage(errorMessage)
            .build();
    assertThat(event.errorCode()).hasValue(finishReason);
    assertThat(event.errorMessage()).hasValue(errorMessage);
  }

  @Test
  @Tag("valid")
  void errorCodePreservesOtherBuilderState() {
    Event.Builder builder = Event.builder();
    String id = "test-id";
    String author = "test-author";
    FinishReason finishReason = FinishReason.SAFETY;
    builder.id(id).author(author).errorCode(finishReason);
    Event event = builder.invocationId("inv-id").build();
    assertThat(event.id()).isEqualTo(id);
    assertThat(event.author()).isEqualTo(author);
    assertThat(event.errorCode()).hasValue(finishReason);
  }
}
