/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-repo using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=branch_996d4d04f3
ROOST_METHOD_SIG_HASH=branch_19f03051d9

Scenario 1: Setting Branch with Non-Empty Optional String Value

Details:
  TestName: branchWithNonEmptyOptionalValue
  Description: This test verifies that the branch method correctly sets the branch field when provided with an Optional containing a non-empty string value. The method should store the Optional value and return the Builder instance for method chaining.

Execution:
  Arrange: Create a new Event.Builder instance. Prepare an Optional<String> containing a valid branch value such as "agent_1.agent_2.agent_3".
  Act: Invoke the branch method on the Builder instance, passing the Optional<String> with the branch value.
  Assert: Verify that the method returns the same Builder instance (for fluent API chaining). Build the Event object and verify that the branch field contains the expected Optional value with the correct string.

Validation:
  The assertion verifies that the branch method properly stores the Optional<String> parameter in the Builder's branch field and maintains the builder pattern by returning the Builder instance. This is significant because it allows developers to chain multiple builder method calls and ensures that branch information is correctly propagated to the final Event object. The branch field is used to track agent hierarchy in multi-agent scenarios where sub-agents shouldn't see peer agents' conversation history.

---

Scenario 2: Setting Branch with Empty Optional

Details:
  TestName: branchWithEmptyOptional
  Description: This test validates that the branch method correctly handles an empty Optional<String> parameter. The method should accept the empty Optional and store it in the branch field without throwing exceptions.

Execution:
  Arrange: Create a new Event.Builder instance. Prepare an empty Optional<String> using Optional.empty().
  Act: Invoke the branch method on the Builder instance, passing the empty Optional.
  Assert: Verify that the method returns the Builder instance. Build the Event object and verify that the branch field is an empty Optional.

Validation:
  This test ensures that the branch method gracefully handles the case where no branch information is provided. An empty Optional indicates that the event doesn't belong to a specific agent hierarchy branch. This is important for events that occur at the root level or don't require branch tracking. The method should not throw NullPointerException or any other exception when receiving an empty Optional.

---

Scenario 3: Setting Branch with Optional Containing Null Value

Details:
  TestName: branchWithOptionalOfNullable
  Description: This test checks the behavior when the branch method receives an Optional created from a null value using Optional.ofNullable(null). The method should handle this case correctly by storing an empty Optional.

Execution:
  Arrange: Create a new Event.Builder instance. Create an Optional<String> using Optional.ofNullable(null), which results in an empty Optional.
  Act: Invoke the branch method with the Optional created from null.
  Assert: Verify that the method returns the Builder instance. Build the Event object and confirm that the branch field is an empty Optional.

Validation:
  This test validates proper handling of Optional values that may be created from nullable sources. Even though Optional.ofNullable(null) produces an empty Optional, it's important to verify that the branch method doesn't have any special handling that might cause unexpected behavior. This ensures robustness when the method is called with Optional values derived from potentially null sources in the application.

---

Scenario 4: Setting Branch Multiple Times with Different Values

Details:
  TestName: branchCalledMultipleTimesOverwritesPreviousValue
  Description: This test verifies that calling the branch method multiple times on the same Builder instance correctly overwrites the previous branch value with the new one, maintaining only the most recent value.

Execution:
  Arrange: Create a new Event.Builder instance. Prepare two different Optional<String> values: first with "agent_1.agent_2" and second with "agent_3.agent_4.agent_5".
  Act: Call the branch method first with the first Optional value, then call it again with the second Optional value on the same Builder instance.
  Assert: Verify that both method calls return the Builder instance. Build the Event object and verify that the branch field contains only the second value ("agent_3.agent_4.agent_5").

Validation:
  This test ensures that the branch method follows the standard builder pattern behavior where subsequent calls to the same setter method replace the previous value rather than accumulating or causing errors. This is critical for scenarios where the branch might need to be updated during the builder configuration process, ensuring that only the final specified value is used in the constructed Event object.

---

Scenario 5: Setting Branch with Optional Containing Single Agent Name

Details:
  TestName: branchWithSingleAgentName
  Description: This test validates that the branch method correctly handles an Optional containing a simple single agent name without hierarchical structure (no dots).

Execution:
  Arrange: Create a new Event.Builder instance. Prepare an Optional<String> containing a single agent name such as "agent_1".
  Act: Invoke the branch method with the Optional containing the single agent name.
  Assert: Verify that the method returns the Builder instance. Build the Event object and verify that the branch field contains the Optional with the single agent name.

Validation:
  This test confirms that the branch field can store simple, non-hierarchical branch identifiers. While the documentation suggests a hierarchical format (agent_1.agent_2.agent_3), the method should not enforce this format and should accept any string value. This flexibility allows for edge cases where events might be associated with a single agent without a complex hierarchy.

---

Scenario 6: Setting Branch with Optional Containing Complex Hierarchical Path

Details:
  TestName: branchWithComplexHierarchicalPath
  Description: This test verifies that the branch method can handle Optional values containing complex, deeply nested agent hierarchies with multiple levels.

Execution:
  Arrange: Create a new Event.Builder instance. Prepare an Optional<String> with a complex hierarchical path such as "rootAgent.subAgent1.subAgent2.subAgent3.leafAgent".
  Act: Invoke the branch method with the Optional containing the complex hierarchical path.
  Assert: Verify that the method returns the Builder instance. Build the Event object and verify that the branch field contains the complete hierarchical path exactly as provided.

Validation:
  This test ensures that the branch method doesn't impose any limitations on the depth or complexity of the agent hierarchy string. It validates that the method acts as a simple setter without parsing, validating, or modifying the branch string content. This is important for supporting complex multi-agent architectures where deep nesting might be necessary.

---

Scenario 7: Setting Branch with Optional Containing Empty String

Details:
  TestName: branchWithOptionalContainingEmptyString
  Description: This test checks the behavior when the branch method receives an Optional containing an empty string ("") rather than a null value or empty Optional.

Execution:
  Arrange: Create a new Event.Builder instance. Prepare an Optional<String> containing an empty string using Optional.of("").
  Act: Invoke the branch method with the Optional containing the empty string.
  Assert: Verify that the method returns the Builder instance. Build the Event object and verify that the branch field contains an Optional with an empty string (not an empty Optional).

Validation:
  This test distinguishes between an empty Optional (no value) and an Optional containing an empty string (a value that happens to be empty). The branch method should preserve this distinction, storing the Optional with the empty string as provided. This is important for scenarios where an empty string might have semantic meaning different from the absence of a value.

---

Scenario 8: Setting Branch with Optional Containing Special Characters

Details:
  TestName: branchWithSpecialCharacters
  Description: This test validates that the branch method correctly handles Optional values containing strings with special characters, spaces, or non-alphanumeric characters.

Execution:
  Arrange: Create a new Event.Builder instance. Prepare an Optional<String> containing special characters such as "agent-1.agent_2.agent@3.agent 4".
  Act: Invoke the branch method with the Optional containing special characters.
  Assert: Verify that the method returns the Builder instance. Build the Event object and verify that the branch field contains the string with all special characters preserved exactly as provided.

Validation:
  This test ensures that the branch method doesn't perform any sanitization, encoding, or validation of the string content. It should accept and store any valid string value regardless of the characters it contains. This is important for flexibility in naming conventions and for ensuring that the method doesn't inadvertently corrupt or modify branch identifiers that might use various naming schemes.

---

Scenario 9: Builder Method Chaining After Setting Branch

Details:
  TestName: builderMethodChainingAfterBranch
  Description: This test verifies that the branch method properly supports the builder pattern by returning the Builder instance, allowing for fluent method chaining with other builder methods.

Execution:
  Arrange: Create a new Event.Builder instance. Prepare an Optional<String> with a branch value "agent_1.agent_2". Prepare other builder parameters such as id and author.
  Act: Chain multiple builder method calls including branch, id, and author in a single statement.
  Assert: Verify that the chaining executes without errors. Build the Event object and verify that all fields (branch, id, author) are set correctly.

Validation:
  This test confirms that the branch method adheres to the builder pattern convention by returning the Builder instance (indicated by the @CanIgnoreReturnValue annotation). This allows developers to write more readable and concise code by chaining multiple configuration calls. The test validates that the return value is the same Builder instance and that method chaining doesn't interfere with proper field assignment.

---

Scenario 10: Setting Branch Before and After Setting Other Optional Fields

Details:
  TestName: branchInteractionWithOtherOptionalFields
  Description: This test verifies that setting the branch field doesn't interfere with other Optional fields in the Builder, and vice versa, ensuring field independence.

Execution:
  Arrange: Create a new Event.Builder instance. Prepare Optional values for branch, errorMessage, and modelVersion fields.
  Act: Set the branch field, then set errorMessage and modelVersion, then set branch again with a different value.
  Assert: Build the Event object and verify that all three Optional fields contain their expected final values independently.

Validation:
  This test ensures that the branch field is properly isolated from other Optional fields in the Builder. Since the Builder contains multiple Optional fields (branch, errorMessage, modelVersion, etc.), it's important to verify that setting one Optional field doesn't accidentally affect others. This validates the correctness of the Builder's internal state management and ensures that each field maintains its own independent Optional value.

---

Scenario 11: Setting Branch and Building Event with Default Timestamp

Details:
  TestName: branchWithDefaultTimestamp
  Description: This test verifies that setting the branch field works correctly in conjunction with the Builder's default timestamp generation when building an Event.

Execution:
  Arrange: Create a new Event.Builder instance. Set required fields (id, invocationId, author) and set branch with an Optional value. Do not explicitly set the timestamp field.
  Act: Invoke the branch method with a valid Optional value, then call build() on the Builder.
  Assert: Verify that the built Event object has the correct branch value and that the timestamp field has been automatically set to a non-zero value (default behavior).

Validation:
  This test validates that the branch method works correctly within the complete Builder lifecycle, including the build() method's default value assignment logic. According to the build() method implementation, if timestamp is not explicitly set, it defaults to the current time. This test ensures that setting the branch field doesn't interfere with this default timestamp generation and that both fields are properly initialized in the final Event object.

---

Scenario 12: Setting Branch with Very Long String Value

Details:
  TestName: branchWithVeryLongString
  Description: This test validates that the branch method can handle Optional values containing very long strings without truncation or errors.

Execution:
  Arrange: Create a new Event.Builder instance. Prepare an Optional<String> containing a very long branch hierarchy string (e.g., 50+ agent names concatenated with dots).
  Act: Invoke the branch method with the Optional containing the very long string.
  Assert: Verify that the method returns the Builder instance. Build the Event object and verify that the branch field contains the complete long string without any truncation.

Validation:
  This test ensures that the branch method doesn't impose any length restrictions on the branch string. In complex multi-agent systems with deep hierarchies, branch paths could become quite long. The method should handle these cases without performance degradation or data loss. This validates that the implementation uses appropriate data structures (String and Optional) that can accommodate arbitrarily long values.

*/

// ********RoostGPT********

package com.google.adk.events;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class BuilderBranch384Test {

  private Event.Builder builder;

  @BeforeEach
  void setUp() {
    builder = Event.builder();
  }

  @Test
  @Tag("valid")
  void branchWithNonEmptyOptionalValue() {
    String branchValue = "agent_1.agent_2.agent_3";
    Optional<String> branchOptional = Optional.of(branchValue);
    Event.Builder result = builder.branch(branchOptional);
    assertSame(builder, result);

    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();

    assertTrue(event.branch().isPresent());
    assertEquals(branchValue, event.branch().get());
  }

  @Test
  @Tag("valid")
  void branchWithEmptyOptional() {
    Optional<String> emptyOptional = Optional.empty();
    Event.Builder result = builder.branch(emptyOptional);
    assertSame(builder, result);

    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();

    assertFalse(event.branch().isPresent());
  }

  @Test
  @Tag("valid")
  void branchWithOptionalOfNullable() {
    Optional<String> nullableOptional = Optional.ofNullable(null);
    Event.Builder result = builder.branch(nullableOptional);
    assertSame(builder, result);

    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();

    assertFalse(event.branch().isPresent());
  }

  @Test
  @Tag("valid")
  void branchCalledMultipleTimesOverwritesPreviousValue() {
    String firstBranch = "agent_1.agent_2";
    String secondBranch = "agent_3.agent_4.agent_5";

    Event.Builder result1 = builder.branch(Optional.of(firstBranch));
    Event.Builder result2 = builder.branch(Optional.of(secondBranch));
    assertSame(builder, result1);
    assertSame(builder, result2);

    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();

    assertTrue(event.branch().isPresent());
    assertEquals(secondBranch, event.branch().get());
  }

  @Test
  @Tag("boundary")
  void branchWithSingleAgentName() {
    String singleAgent = "agent_1";
    Optional<String> branchOptional = Optional.of(singleAgent);
    Event.Builder result = builder.branch(branchOptional);
    assertSame(builder, result);

    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();

    assertTrue(event.branch().isPresent());
    assertEquals(singleAgent, event.branch().get());
  }

  @Test
  @Tag("valid")
  void branchWithComplexHierarchicalPath() {
    String complexPath = "rootAgent.subAgent1.subAgent2.subAgent3.leafAgent";
    Optional<String> branchOptional = Optional.of(complexPath);
    Event.Builder result = builder.branch(branchOptional);
    assertSame(builder, result);

    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();

    assertTrue(event.branch().isPresent());
    assertEquals(complexPath, event.branch().get());
  }

  @Test
  @Tag("boundary")
  void branchWithOptionalContainingEmptyString() {
    String emptyString = "";
    Optional<String> branchOptional = Optional.of(emptyString);
    Event.Builder result = builder.branch(branchOptional);
    assertSame(builder, result);

    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();

    assertTrue(event.branch().isPresent());
    assertEquals(emptyString, event.branch().get());
  }

  @Test
  @Tag("valid")
  void branchWithSpecialCharacters() {
    String specialChars = "agent-1.agent_2.agent@3.agent 4";
    Optional<String> branchOptional = Optional.of(specialChars);
    Event.Builder result = builder.branch(branchOptional);
    assertSame(builder, result);

    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();

    assertTrue(event.branch().isPresent());
    assertEquals(specialChars, event.branch().get());
  }

  @Test
  @Tag("integration")
  void builderMethodChainingAfterBranch() {
    String branchValue = "agent_1.agent_2";
    String id = "test-id-123";
    String author = "test-author";
    Event event =
        builder
            .branch(Optional.of(branchValue))
            .id(id)
            .author(author)
            .invocationId("test-invocation")
            .build();
    assertTrue(event.branch().isPresent());
    assertEquals(branchValue, event.branch().get());
    assertEquals(id, event.id());
    assertEquals(author, event.author());
  }

  @Test
  @Tag("integration")
  void branchInteractionWithOtherOptionalFields() {
    String firstBranch = "agent_1";
    String secondBranch = "agent_2.agent_3";
    String errorMsg = "Test error message";
    String modelVer = "model-v1.0";
    Event event =
        builder
            .branch(Optional.of(firstBranch))
            .errorMessage(Optional.of(errorMsg))
            .modelVersion(Optional.of(modelVer))
            .branch(Optional.of(secondBranch))
            .id("test-id")
            .invocationId("test-invocation")
            .author("test-author")
            .build();
    assertTrue(event.branch().isPresent());
    assertEquals(secondBranch, event.branch().get());
    assertTrue(event.errorMessage().isPresent());
    assertEquals(errorMsg, event.errorMessage().get());
    assertTrue(event.modelVersion().isPresent());
    assertEquals(modelVer, event.modelVersion().get());
  }

  @Test
  @Tag("integration")
  void branchWithDefaultTimestamp() {
    String branchValue = "agent_1.agent_2";
    long beforeBuild = System.currentTimeMillis();
    Event event =
        builder
            .id("test-id")
            .invocationId("test-invocation")
            .author("test-author")
            .branch(Optional.of(branchValue))
            .build();
    long afterBuild = System.currentTimeMillis();
    assertTrue(event.branch().isPresent());
    assertEquals(branchValue, event.branch().get());
    assertTrue(event.timestamp().isPresent());
    assertTrue(event.timestamp().get() > 0);
    assertTrue(event.timestamp().get() >= beforeBuild);
    assertTrue(event.timestamp().get() <= afterBuild);
  }

  @Test
  @Tag("boundary")
  void branchWithVeryLongString() {
    StringBuilder longBranch = new StringBuilder();
    for (int i = 0; i < 50; i++) {
      if (i > 0) {
        longBranch.append(".");
      }
      longBranch.append("agent_").append(i);
    }
    String longBranchValue = longBranch.toString();
    Optional<String> branchOptional = Optional.of(longBranchValue);
    Event.Builder result = builder.branch(branchOptional);
    assertSame(builder, result);

    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();

    assertTrue(event.branch().isPresent());
    assertEquals(longBranchValue, event.branch().get());
    assertEquals(longBranchValue.length(), event.branch().get().length());
  }
}
