/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-repo using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=turnComplete_9973844fed
ROOST_METHOD_SIG_HASH=turnComplete_a68d1f577d

Scenario 1: Setting turnComplete with Optional containing true value

Details:
  TestName: turnCompleteWithOptionalTrue
  Description: This test verifies that the turnComplete method correctly sets the turnComplete field when provided with an Optional containing a Boolean true value. It ensures that the builder pattern works correctly and returns the builder instance for method chaining.

Execution:
  Arrange: Create a new Event.Builder instance.
  Act: Call the turnComplete method with Optional.of(true) and capture the returned builder instance.
  Assert: Verify that the returned object is the same builder instance (for method chaining) and that when build() is called, the resulting Event object has turnComplete set to Optional.of(true).

Validation:
  This test validates that the builder correctly stores the turnComplete value when provided as an Optional<Boolean> with a true value. This is important for indicating that a conversation turn has been completed. The test ensures the fluent builder pattern is maintained by returning the builder instance, allowing for method chaining in client code.


Scenario 2: Setting turnComplete with Optional containing false value

Details:
  TestName: turnCompleteWithOptionalFalse
  Description: This test verifies that the turnComplete method correctly sets the turnComplete field when provided with an Optional containing a Boolean false value. It ensures proper handling of the false state.

Execution:
  Arrange: Create a new Event.Builder instance.
  Act: Call the turnComplete method with Optional.of(false) and build the Event object.
  Assert: Verify that the resulting Event object has turnComplete set to Optional.of(false) by calling the turnComplete() getter method.

Validation:
  This test confirms that the builder can correctly handle a false value for turnComplete, which indicates that a conversation turn is not yet complete. This is crucial for tracking partial responses or ongoing interactions in the event system.


Scenario 3: Setting turnComplete with empty Optional

Details:
  TestName: turnCompleteWithEmptyOptional
  Description: This test verifies that the turnComplete method correctly handles an empty Optional value, representing the absence of turnComplete information.

Execution:
  Arrange: Create a new Event.Builder instance.
  Act: Call the turnComplete method with Optional.empty() and build the Event object.
  Assert: Verify that the resulting Event object has turnComplete set to Optional.empty() and that calling isPresent() on the Optional returns false.

Validation:
  This test ensures that the builder properly handles the case where turnComplete information is not available or not applicable. An empty Optional is a valid state that indicates the turnComplete status has not been set, which is important for scenarios where this information is optional or not yet determined.


Scenario 4: Method chaining capability after setting turnComplete

Details:
  TestName: turnCompleteReturnsBuilderForChaining
  Description: This test verifies that the turnComplete method returns the builder instance itself, enabling fluent method chaining as indicated by the @CanIgnoreReturnValue annotation.

Execution:
  Arrange: Create a new Event.Builder instance.
  Act: Call turnComplete with Optional.of(true) and immediately chain another builder method (such as id()) to verify chaining works.
  Assert: Verify that the chaining executes without errors and that the final built Event object contains both the turnComplete value and the chained method's value.

Validation:
  This test validates the fluent builder pattern implementation, ensuring that developers can chain multiple builder method calls in a single statement. This is a common pattern in builder classes and improves code readability and usability.


Scenario 5: Overwriting previously set turnComplete value

Details:
  TestName: turnCompleteOverwritesPreviousValue
  Description: This test verifies that calling turnComplete multiple times on the same builder instance correctly overwrites the previous value with the new value.

Execution:
  Arrange: Create a new Event.Builder instance and set turnComplete to Optional.of(true).
  Act: Call turnComplete again with Optional.of(false) on the same builder instance and build the Event object.
  Assert: Verify that the resulting Event object has turnComplete set to Optional.of(false), confirming the second call overwrote the first value.

Validation:
  This test ensures that the builder correctly handles multiple calls to the same setter method, with the last call taking precedence. This behavior is expected in builder patterns and prevents unexpected state accumulation.


Scenario 6: Setting turnComplete to empty after setting a value

Details:
  TestName: turnCompleteCanBeSetToEmptyAfterValue
  Description: This test verifies that the turnComplete field can be changed from a present value to an empty Optional, allowing for clearing previously set values.

Execution:
  Arrange: Create a new Event.Builder instance and set turnComplete to Optional.of(true).
  Act: Call turnComplete with Optional.empty() on the same builder instance and build the Event object.
  Assert: Verify that the resulting Event object has turnComplete set to Optional.empty().

Validation:
  This test confirms that the builder allows resetting the turnComplete field to an empty state, which is useful for scenarios where a previously set value needs to be cleared or when building multiple Event objects from the same builder with different configurations.


Scenario 7: Building Event without setting turnComplete

Details:
  TestName: buildEventWithoutSettingTurnComplete
  Description: This test verifies the default behavior when turnComplete is not explicitly set on the builder before calling build().

Execution:
  Arrange: Create a new Event.Builder instance and set only required fields (id, invocationId, author) without calling turnComplete.
  Act: Build the Event object without calling turnComplete.
  Assert: Verify that the resulting Event object has turnComplete set to Optional.empty() by default.

Validation:
  This test ensures that the builder has a sensible default value for the turnComplete field when it is not explicitly set. The default of Optional.empty() indicates that the turnComplete status is unspecified, which is appropriate for optional fields.


Scenario 8: Setting turnComplete with null Optional reference

Details:
  TestName: turnCompleteWithNullOptional
  Description: This test verifies the behavior when the turnComplete method is called with a null Optional reference, which should be handled gracefully or according to the method's contract.

Execution:
  Arrange: Create a new Event.Builder instance.
  Act: Call turnComplete with a null Optional value (Optional<Boolean> nullOptional = null).
  Assert: Verify that either the method handles null gracefully by treating it as Optional.empty(), or that appropriate null handling occurs based on the implementation.

Validation:
  This test checks the robustness of the method when dealing with null inputs. While the method signature accepts Optional<Boolean>, it's important to verify behavior when null is passed instead of an Optional instance, ensuring the code doesn't throw unexpected NullPointerExceptions.


Scenario 9: Integration with toBuilder method

Details:
  TestName: turnCompletePreservedInToBuilder
  Description: This test verifies that when an Event object with a set turnComplete value is converted back to a builder using toBuilder(), the turnComplete value is preserved.

Execution:
  Arrange: Create an Event object with turnComplete set to Optional.of(true) using the builder.
  Act: Call toBuilder() on the Event object to get a new builder, then build a new Event from that builder.
  Assert: Verify that the new Event object has the same turnComplete value (Optional.of(true)) as the original Event.

Validation:
  This test ensures that the toBuilder() method correctly copies all field values, including turnComplete, allowing for creating modified copies of Event objects while preserving existing values. This is important for immutability patterns and event modification scenarios.


Scenario 10: Multiple builder instances maintain independent state

Details:
  TestName: multipleBuildersIndependentTurnCompleteState
  Description: This test verifies that multiple builder instances maintain independent turnComplete states and don't interfere with each other.

Execution:
  Arrange: Create two separate Event.Builder instances.
  Act: Set turnComplete to Optional.of(true) on the first builder and Optional.of(false) on the second builder, then build both Event objects.
  Assert: Verify that the first Event has turnComplete set to Optional.of(true) and the second Event has turnComplete set to Optional.of(false).

Validation:
  This test confirms that builder instances are properly isolated and don't share state, which is crucial for thread safety and preventing unexpected side effects when multiple Event objects are being constructed concurrently or sequentially in the same scope.

*/

// ********RoostGPT********

package com.google.adk.events;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.genai.types.Content;
import com.google.genai.types.FinishReason;
import com.google.genai.types.GenerateContentResponseUsageMetadata;
import com.google.genai.types.GroundingMetadata;
import java.util.HashSet;
import java.util.Optional;
import java.util.Set;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@DisplayName("Event.Builder turnComplete Method Tests")
class BuilderTurnComplete941Test {

  private Event.Builder builder;

  @BeforeEach
  void setUp() {
    builder = Event.builder();
  }

  @Test
  @Tag("valid")
  @DisplayName("Setting turnComplete with Optional containing true value")
  void turnCompleteWithOptionalTrue() {
    Event.Builder returnedBuilder = builder.turnComplete(Optional.of(true));
    assertSame(builder, returnedBuilder, "Builder should return itself for method chaining");
    Event event =
        builder.id("test-id").invocationId("test-invocation-id").author("test-author").build();
    assertTrue(event.turnComplete().isPresent(), "turnComplete should be present");
    assertTrue(event.turnComplete().get(), "turnComplete should be true");
  }

  @Test
  @Tag("valid")
  @DisplayName("Setting turnComplete with Optional containing false value")
  void turnCompleteWithOptionalFalse() {
    Event event =
        builder
            .id("test-id")
            .invocationId("test-invocation-id")
            .author("test-author")
            .turnComplete(Optional.of(false))
            .build();
    assertTrue(event.turnComplete().isPresent(), "turnComplete should be present");
    assertFalse(event.turnComplete().get(), "turnComplete should be false");
  }

  @Test
  @Tag("boundary")
  @DisplayName("Setting turnComplete with empty Optional")
  void turnCompleteWithEmptyOptional() {
    Event event =
        builder
            .id("test-id")
            .invocationId("test-invocation-id")
            .author("test-author")
            .turnComplete(Optional.empty())
            .build();
    assertNotNull(event.turnComplete(), "turnComplete Optional should not be null");
    assertFalse(event.turnComplete().isPresent(), "turnComplete should be empty");
  }

  @Test
  @Tag("valid")
  @DisplayName("Method chaining capability after setting turnComplete")
  void turnCompleteReturnsBuilderForChaining() {
    Event event =
        builder
            .turnComplete(Optional.of(true))
            .id("chained-id")
            .invocationId("chained-invocation-id")
            .author("chained-author")
            .partial(Optional.of(false))
            .build();
    assertTrue(event.turnComplete().isPresent(), "turnComplete should be present");
    assertTrue(event.turnComplete().get(), "turnComplete should be true");
    assertEquals("chained-id", event.id(), "id should be set correctly");
    assertEquals("chained-author", event.author(), "author should be set correctly");
  }

  @Test
  @Tag("valid")
  @DisplayName("Overwriting previously set turnComplete value")
  void turnCompleteOverwritesPreviousValue() {
    Event event =
        builder
            .id("test-id")
            .invocationId("test-invocation-id")
            .author("test-author")
            .turnComplete(Optional.of(true))
            .turnComplete(Optional.of(false))
            .build();
    assertTrue(event.turnComplete().isPresent(), "turnComplete should be present");
    assertFalse(event.turnComplete().get(), "turnComplete should be false (overwritten value)");
  }

  @Test
  @Tag("valid")
  @DisplayName("Setting turnComplete to empty after setting a value")
  void turnCompleteCanBeSetToEmptyAfterValue() {
    Event event =
        builder
            .id("test-id")
            .invocationId("test-invocation-id")
            .author("test-author")
            .turnComplete(Optional.of(true))
            .turnComplete(Optional.empty())
            .build();
    assertNotNull(event.turnComplete(), "turnComplete Optional should not be null");
    assertFalse(
        event.turnComplete().isPresent(), "turnComplete should be empty after being cleared");
  }

  @Test
  @Tag("boundary")
  @DisplayName("Building Event without setting turnComplete")
  void buildEventWithoutSettingTurnComplete() {
    Event event =
        builder.id("test-id").invocationId("test-invocation-id").author("test-author").build();
    assertNotNull(event.turnComplete(), "turnComplete Optional should not be null");
    assertFalse(event.turnComplete().isPresent(), "turnComplete should be empty by default");
  }

  @Test
  @Tag("invalid")
  @DisplayName("Setting turnComplete with null Optional reference")
  void turnCompleteWithNullOptional() {
    Optional<Boolean> nullOptional = null;
    assertDoesNotThrow(
        () -> {
          builder.turnComplete(nullOptional);
        },
        "Setting turnComplete with null Optional should not throw exception");
    Event event =
        builder.id("test-id").invocationId("test-invocation-id").author("test-author").build();
    assertNotNull(event, "Event should be built successfully");
  }

  @Test
  @Tag("integration")
  @DisplayName("Integration with toBuilder method")
  void turnCompletePreservedInToBuilder() {
    Event originalEvent =
        builder
            .id("original-id")
            .invocationId("original-invocation-id")
            .author("original-author")
            .turnComplete(Optional.of(true))
            .build();
    Event copiedEvent = originalEvent.toBuilder().build();
    assertTrue(
        copiedEvent.turnComplete().isPresent(), "turnComplete should be present in copied event");
    assertTrue(copiedEvent.turnComplete().get(), "turnComplete should be true in copied event");
    assertEquals(
        originalEvent.turnComplete(),
        copiedEvent.turnComplete(),
        "turnComplete should be preserved in toBuilder");
  }

  @Test
  @Tag("valid")
  @DisplayName("Multiple builder instances maintain independent state")
  void multipleBuildersIndependentTurnCompleteState() {
    Event.Builder builder1 = Event.builder();
    Event.Builder builder2 = Event.builder();
    Event event1 =
        builder1
            .id("id-1")
            .invocationId("invocation-1")
            .author("author-1")
            .turnComplete(Optional.of(true))
            .build();
    Event event2 =
        builder2
            .id("id-2")
            .invocationId("invocation-2")
            .author("author-2")
            .turnComplete(Optional.of(false))
            .build();
    assertTrue(event1.turnComplete().isPresent(), "Event1 turnComplete should be present");
    assertTrue(event1.turnComplete().get(), "Event1 turnComplete should be true");
    assertTrue(event2.turnComplete().isPresent(), "Event2 turnComplete should be present");
    assertFalse(event2.turnComplete().get(), "Event2 turnComplete should be false");
    assertNotEquals(
        event1.turnComplete(),
        event2.turnComplete(),
        "Builder instances should maintain independent state");
  }

  @Test
  @Tag("valid")
  @DisplayName("turnComplete works with other optional fields")
  void turnCompleteWorksWithOtherOptionalFields() {
    Content mockContent = mock(Content.class);
    Set<String> toolIds = new HashSet<>();
    toolIds.add("tool-1");
    toolIds.add("tool-2");
    Event event =
        builder
            .id("test-id")
            .invocationId("test-invocation-id")
            .author("test-author")
            .turnComplete(Optional.of(true))
            .partial(Optional.of(false))
            .content(Optional.of(mockContent))
            .longRunningToolIds(Optional.of(toolIds))
            .interrupted(Optional.of(false))
            .build();
    assertTrue(event.turnComplete().isPresent(), "turnComplete should be present");
    assertTrue(event.turnComplete().get(), "turnComplete should be true");
    assertTrue(event.partial().isPresent(), "partial should be present");
    assertFalse(event.partial().get(), "partial should be false");
    assertTrue(event.content().isPresent(), "content should be present");
    assertTrue(event.longRunningToolIds().isPresent(), "longRunningToolIds should be present");
  }

  @Test
  @Tag("valid")
  @DisplayName("turnComplete with nullable Boolean method variant")
  void turnCompleteWithNullableBoolean() {
    Event event1 =
        builder
            .id("test-id-1")
            .invocationId("test-invocation-id-1")
            .author("test-author-1")
            .turnComplete((Boolean) true)
            .build();
    assertTrue(event1.turnComplete().isPresent(), "turnComplete should be present");
    assertTrue(event1.turnComplete().get(), "turnComplete should be true");
    Event.Builder builder2 = Event.builder();
    Event event2 =
        builder2
            .id("test-id-2")
            .invocationId("test-invocation-id-2")
            .author("test-author-2")
            .turnComplete((Boolean) null)
            .build();
    assertFalse(
        event2.turnComplete().isPresent(), "turnComplete should be empty when null is passed");
  }

  @Test
  @Tag("boundary")
  @DisplayName("turnComplete state after multiple build calls")
  void turnCompleteStateAfterMultipleBuilds() {
    builder
        .id("test-id")
        .invocationId("test-invocation-id")
        .author("test-author")
        .turnComplete(Optional.of(true));
    Event event1 = builder.build();
    Event event2 = builder.build();
    assertTrue(event1.turnComplete().isPresent(), "First event turnComplete should be present");
    assertTrue(event1.turnComplete().get(), "First event turnComplete should be true");
    assertTrue(event2.turnComplete().isPresent(), "Second event turnComplete should be present");
    assertTrue(event2.turnComplete().get(), "Second event turnComplete should be true");
  }

  @Test
  @Tag("integration")
  @DisplayName("turnComplete with complete Event configuration")
  void turnCompleteWithCompleteEventConfiguration() {
    GenerateContentResponseUsageMetadata mockUsageMetadata =
        mock(GenerateContentResponseUsageMetadata.class);
    GroundingMetadata mockGroundingMetadata = mock(GroundingMetadata.class);
    Event event =
        builder
            .id("complete-id")
            .invocationId("complete-invocation-id")
            .author("complete-author")
            .turnComplete(Optional.of(true))
            .partial(Optional.of(false))
            .finishReason(Optional.of(FinishReason.STOP))
            .usageMetadata(Optional.of(mockUsageMetadata))
            .avgLogprobs(Optional.of(-0.5))
            .interrupted(Optional.of(false))
            .branch(Optional.of("main"))
            .groundingMetadata(Optional.of(mockGroundingMetadata))
            .modelVersion(Optional.of("v1.0"))
            .build();
    assertNotNull(event, "Event should be built successfully");
    assertTrue(event.turnComplete().isPresent(), "turnComplete should be present");
    assertTrue(event.turnComplete().get(), "turnComplete should be true");
    assertTrue(event.finishReason().isPresent(), "finishReason should be present");
    assertEquals(FinishReason.STOP, event.finishReason().get(), "finishReason should be STOP");
  }
}
