/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-repo using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=interrupted_152f93bc89
ROOST_METHOD_SIG_HASH=interrupted_fce4ff0622

Scenario 1: Setting interrupted field with Optional containing true value

Details:
  TestName: interruptedWithOptionalTrue
  Description: This test verifies that the interrupted method correctly sets the interrupted field when provided with an Optional containing a Boolean true value. The method should store the Optional value and return the Builder instance for method chaining.
Execution:
  Arrange: Create a new Event.Builder instance. Prepare an Optional<Boolean> containing the value true.
  Act: Invoke the interrupted method on the builder with Optional.of(true) as the parameter.
  Assert: Verify that the method returns the same Builder instance (for fluent interface). Build the Event object and verify that the interrupted field contains Optional.of(true) using the interrupted() getter method.
Validation:
  The assertion verifies that the Builder correctly stores the Optional<Boolean> value when it contains true. This is important for tracking whether an event was interrupted during execution. The test ensures the builder pattern works correctly by returning the same instance for method chaining, which is a common pattern in builder implementations.

Scenario 2: Setting interrupted field with Optional containing false value

Details:
  TestName: interruptedWithOptionalFalse
  Description: This test validates that the interrupted method properly handles an Optional containing a Boolean false value. The method should accept and store this value correctly.
Execution:
  Arrange: Create a new Event.Builder instance. Prepare an Optional<Boolean> containing the value false.
  Act: Call the interrupted method with Optional.of(false) as the argument.
  Assert: Verify that the returned value is the same Builder instance. Build the Event and assert that interrupted() returns Optional.of(false).
Validation:
  This test confirms that the method can handle false values correctly, which is essential for explicitly marking events as not interrupted. This distinguishes between an unset interrupted state (Optional.empty()) and an explicitly set false state, which may have different semantic meanings in the application logic.

Scenario 3: Setting interrupted field with empty Optional

Details:
  TestName: interruptedWithEmptyOptional
  Description: This test checks the behavior when the interrupted method receives an empty Optional. The method should accept Optional.empty() and store it appropriately.
Execution:
  Arrange: Create a new Event.Builder instance. Prepare an empty Optional using Optional.empty().
  Act: Invoke the interrupted method with Optional.empty() as the parameter.
  Assert: Verify the method returns the Builder instance. Build the Event object and assert that interrupted() returns Optional.empty() using isPresent() or isEmpty() methods.
Validation:
  This test is crucial for verifying that the method can handle the absence of a value. An empty Optional indicates that the interrupted status is unknown or not applicable. This is important for scenarios where the interrupted state hasn't been determined yet or doesn't apply to the particular event type.

Scenario 4: Method chaining with interrupted and other builder methods

Details:
  TestName: interruptedMethodChainingWithOtherMethods
  Description: This test validates that the interrupted method supports fluent interface pattern by allowing method chaining with other Builder methods. This ensures the Builder pattern is correctly implemented.
Execution:
  Arrange: Create a new Event.Builder instance. Prepare test values for multiple fields including interrupted (Optional.of(true)), id ("test-id"), author ("test-author"), and invocationId ("test-invocation").
  Act: Chain multiple builder methods together: builder.id("test-id").author("test-author").invocationId("test-invocation").interrupted(Optional.of(true)).build().
  Assert: Verify that the built Event object has all the correct values: id equals "test-id", author equals "test-author", invocationId equals "test-invocation", and interrupted() returns Optional.of(true).
Validation:
  This test ensures that the interrupted method properly returns the Builder instance, enabling fluent API usage. Method chaining is a key feature of the builder pattern that improves code readability and usability. This test confirms that setting the interrupted field doesn't break the chain and all values are correctly preserved.

Scenario 5: Multiple invocations of interrupted method with different values

Details:
  TestName: interruptedMultipleInvocationsLastValueWins
  Description: This test verifies the behavior when the interrupted method is called multiple times on the same Builder instance. The last value set should be the one that persists.
Execution:
  Arrange: Create a new Event.Builder instance.
  Act: Call the interrupted method multiple times with different values: first with Optional.of(true), then with Optional.of(false), and finally with Optional.empty(). Build the Event object after the last call.
  Assert: Verify that the final Event object's interrupted() method returns Optional.empty(), which was the last value set.
Validation:
  This test confirms that the Builder follows the standard pattern where subsequent calls to the same setter method override previous values. This is important for understanding the Builder's behavior when used in complex initialization scenarios or when values need to be conditionally updated during the building process.

Scenario 6: Setting interrupted with Optional of true and verifying builder state before build

Details:
  TestName: interruptedBuilderStateBeforeBuild
  Description: This test validates that the interrupted value is stored in the Builder's internal state immediately after calling the method, even before the build() method is invoked.
Execution:
  Arrange: Create a new Event.Builder instance. Prepare Optional.of(true).
  Act: Call the interrupted method with Optional.of(true). Do not call build() yet.
  Assert: Since the Builder class doesn't expose a getter for interrupted in the provided code, verify by calling build() and then checking the Event's interrupted() method returns Optional.of(true).
Validation:
  This test ensures that the Builder correctly maintains internal state. While we cannot directly access the Builder's private interrupted field without a getter, building the Event and checking its state confirms that the value was properly stored. This is important for ensuring data integrity throughout the building process.

Scenario 7: Building Event with only interrupted field set

Details:
  TestName: interruptedOnlyFieldSet
  Description: This test verifies that an Event can be built with only the interrupted field explicitly set, while other optional fields remain at their default values.
Execution:
  Arrange: Create a new Event.Builder instance.
  Act: Call only the interrupted method with Optional.of(true), then call build().
  Assert: Verify that the built Event has interrupted() returning Optional.of(true). Also verify that other Optional fields like partial(), turnComplete(), errorCode(), etc., return Optional.empty() or their default values.
Validation:
  This test confirms that the interrupted field can be set independently of other fields and that the Builder properly initializes all other fields to their default values. This is important for ensuring that partial object construction works correctly and that unset fields don't cause null pointer exceptions or unexpected behavior.

Scenario 8: Interrupted field persistence through toBuilder

Details:
  TestName: interruptedPersistsThroughToBuilder
  Description: This test validates that when an Event with an interrupted value is converted back to a Builder using toBuilder(), the interrupted value is preserved.
Execution:
  Arrange: Create an Event.Builder, set interrupted to Optional.of(true), and build an Event.
  Act: Call toBuilder() on the created Event to get a new Builder instance. Build a new Event from this Builder.
  Assert: Verify that the new Event's interrupted() method returns Optional.of(true), matching the original Event.
Validation:
  This test ensures that the toBuilder() method correctly copies all field values, including the interrupted field. This is crucial for scenarios where Events need to be modified or cloned, ensuring data integrity is maintained throughout the object lifecycle. It validates the round-trip conversion between Event and Builder.

Scenario 9: Interrupted with null value wrapped in Optional

Details:
  TestName: interruptedWithOptionalOfNullable
  Description: This test checks the behavior when interrupted is called with Optional.ofNullable(null), which results in Optional.empty().
Execution:
  Arrange: Create a new Event.Builder instance. Prepare Optional.ofNullable(null) which evaluates to Optional.empty().
  Act: Call the interrupted method with Optional.ofNullable(null).
  Assert: Build the Event and verify that interrupted() returns Optional.empty() using isEmpty() or !isPresent().
Validation:
  This test validates that the method correctly handles Optional.ofNullable(null), which is a common pattern when the source value might be null. The method should treat this the same as Optional.empty(). This ensures robustness when dealing with potentially null values from external sources or database queries.

Scenario 10: Interrupted field in combination with error-related fields

Details:
  TestName: interruptedWithErrorFields
  Description: This test verifies that the interrupted field can be set alongside error-related fields like errorCode and errorMessage, which might be a common scenario when an event is interrupted due to an error.
Execution:
  Arrange: Create a new Event.Builder instance. Prepare Optional.of(true) for interrupted, Optional.of(FinishReason.SAFETY) for errorCode, and Optional.of("Safety violation") for errorMessage.
  Act: Chain the methods: builder.interrupted(Optional.of(true)).errorCode(Optional.of(FinishReason.SAFETY)).errorMessage(Optional.of("Safety violation")).build().
  Assert: Verify that the built Event has interrupted() returning Optional.of(true), errorCode() returning Optional.of(FinishReason.SAFETY), and errorMessage() returning Optional.of("Safety violation").
Validation:
  This test ensures that the interrupted field works correctly in conjunction with error-related fields, which is a realistic use case. When an event is interrupted due to an error condition, multiple fields need to be set together. This validates that the Builder can handle complex state combinations without conflicts or data loss.

Scenario 11: Interrupted field with partial and turnComplete fields

Details:
  TestName: interruptedWithPartialAndTurnComplete
  Description: This test validates that the interrupted field can be set together with partial and turnComplete fields, which are related to event completion status.
Execution:
  Arrange: Create a new Event.Builder instance. Prepare Optional.of(true) for interrupted, Optional.of(false) for partial, and Optional.of(false) for turnComplete.
  Act: Call builder.interrupted(Optional.of(true)).partial(Optional.of(false)).turnComplete(Optional.of(false)).build().
  Assert: Verify that the built Event has interrupted() returning Optional.of(true), partial() returning Optional.of(false), and turnComplete() returning Optional.of(false).
Validation:
  This test confirms that the interrupted field can coexist with other status-related fields. Understanding how interrupted relates to partial and turnComplete is important for correctly interpreting event states. An interrupted event might have specific values for these fields that indicate the interruption occurred mid-stream.

Scenario 12: Interrupted field default value when not explicitly set

Details:
  TestName: interruptedDefaultValueWhenNotSet
  Description: This test verifies the default value of the interrupted field when it is not explicitly set during Event building.
Execution:
  Arrange: Create a new Event.Builder instance. Set other required fields like id, invocationId, and author, but do not call the interrupted method.
  Act: Build the Event without setting the interrupted field.
  Assert: Verify that the built Event's interrupted() method returns Optional.empty().
Validation:
  This test confirms that the interrupted field defaults to Optional.empty() when not explicitly set, which is the expected behavior based on the field initialization in the Builder class. This is important for understanding the default state of Events and ensuring that unset optional fields don't cause unexpected behavior in business logic that checks the interrupted status.

*/

// ********RoostGPT********

package com.google.adk.events;

import static org.junit.jupiter.api.Assertions.*;

import com.google.genai.types.FinishReason;
import java.util.HashSet;
import java.util.Optional;
import java.util.Set;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class BuilderInterrupted371Test {

  private Event.Builder builder;

  @BeforeEach
  void setUp() {
    builder = Event.builder();
  }

  @Test
  @Tag("valid")
  void interruptedWithOptionalTrue() {
    Event.Builder result = builder.interrupted(Optional.of(true));
    assertSame(builder, result);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();

    assertTrue(event.interrupted().isPresent());
    assertTrue(event.interrupted().get());
  }

  @Test
  @Tag("valid")
  void interruptedWithOptionalFalse() {
    Event.Builder result = builder.interrupted(Optional.of(false));
    assertSame(builder, result);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();

    assertTrue(event.interrupted().isPresent());
    assertFalse(event.interrupted().get());
  }

  @Test
  @Tag("boundary")
  void interruptedWithEmptyOptional() {
    Event.Builder result = builder.interrupted(Optional.empty());
    assertSame(builder, result);
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();

    assertFalse(event.interrupted().isPresent());
    assertTrue(event.interrupted().isEmpty());
  }

  @Test
  @Tag("integration")
  void interruptedMethodChainingWithOtherMethods() {
    Event event =
        builder
            .id("test-id")
            .author("test-author")
            .invocationId("test-invocation")
            .interrupted(Optional.of(true))
            .build();
    assertEquals("test-id", event.id());
    assertEquals("test-author", event.author());
    assertEquals("test-invocation", event.invocationId());
    assertTrue(event.interrupted().isPresent());
    assertTrue(event.interrupted().get());
  }

  @Test
  @Tag("valid")
  void interruptedMultipleInvocationsLastValueWins() {
    builder
        .interrupted(Optional.of(true))
        .interrupted(Optional.of(false))
        .interrupted(Optional.empty());
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertFalse(event.interrupted().isPresent());
    assertTrue(event.interrupted().isEmpty());
  }

  @Test
  @Tag("valid")
  void interruptedBuilderStateBeforeBuild() {
    builder.interrupted(Optional.of(true));
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertTrue(event.interrupted().isPresent());
    assertTrue(event.interrupted().get());
  }

  @Test
  @Tag("boundary")
  void interruptedOnlyFieldSet() {
    builder.interrupted(Optional.of(true));
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertTrue(event.interrupted().isPresent());
    assertTrue(event.interrupted().get());
    assertFalse(event.partial().isPresent());
    assertFalse(event.turnComplete().isPresent());
    assertFalse(event.errorCode().isPresent());
    assertFalse(event.errorMessage().isPresent());
    assertFalse(event.finishReason().isPresent());
  }

  @Test
  @Tag("integration")
  void interruptedPersistsThroughToBuilder() {
    Event originalEvent =
        builder
            .id("test-id")
            .invocationId("test-invocation")
            .author("test-author")
            .interrupted(Optional.of(true))
            .build();
    Event newEvent = originalEvent.toBuilder().build();
    assertTrue(newEvent.interrupted().isPresent());
    assertTrue(newEvent.interrupted().get());
    assertEquals(originalEvent.interrupted(), newEvent.interrupted());
  }

  @Test
  @Tag("boundary")
  void interruptedWithOptionalOfNullable() {
    Boolean nullValue = null;
    builder.interrupted(Optional.ofNullable(nullValue));
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertFalse(event.interrupted().isPresent());
    assertTrue(event.interrupted().isEmpty());
  }

  @Test
  @Tag("integration")
  void interruptedWithErrorFields() {
    Event event =
        builder
            .id("test-id")
            .invocationId("test-invocation")
            .author("test-author")
            .interrupted(Optional.of(true))
            .errorCode(Optional.of(FinishReason.SAFETY))
            .errorMessage(Optional.of("Safety violation"))
            .build();
    assertTrue(event.interrupted().isPresent());
    assertTrue(event.interrupted().get());
    assertTrue(event.errorCode().isPresent());
    assertEquals(FinishReason.SAFETY, event.errorCode().get());
    assertTrue(event.errorMessage().isPresent());
    assertEquals("Safety violation", event.errorMessage().get());
  }

  @Test
  @Tag("integration")
  void interruptedWithPartialAndTurnComplete() {
    Event event =
        builder
            .id("test-id")
            .invocationId("test-invocation")
            .author("test-author")
            .interrupted(Optional.of(true))
            .partial(Optional.of(false))
            .turnComplete(Optional.of(false))
            .build();
    assertTrue(event.interrupted().isPresent());
    assertTrue(event.interrupted().get());
    assertTrue(event.partial().isPresent());
    assertFalse(event.partial().get());
    assertTrue(event.turnComplete().isPresent());
    assertFalse(event.turnComplete().get());
  }

  @Test
  @Tag("boundary")
  void interruptedDefaultValueWhenNotSet() {
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertFalse(event.interrupted().isPresent());
    assertTrue(event.interrupted().isEmpty());
  }

  @Test
  @Tag("valid")
  void interruptedReturnsSameBuilderInstance() {
    Event.Builder result1 = builder.interrupted(Optional.of(true));
    Event.Builder result2 = result1.interrupted(Optional.of(false));
    assertSame(builder, result1);
    assertSame(builder, result2);
    assertSame(result1, result2);
  }

  @Test
  @Tag("integration")
  void interruptedWithAllOptionalFieldsSet() {
    Set<String> toolIds = new HashSet<>();
    toolIds.add("tool1");

    Event event =
        builder
            .id("test-id")
            .invocationId("test-invocation")
            .author("test-author")
            .interrupted(Optional.of(true))
            .partial(Optional.of(true))
            .turnComplete(Optional.of(false))
            .longRunningToolIds(Optional.of(toolIds))
            .errorCode(Optional.of(FinishReason.STOP))
            .errorMessage(Optional.of("Test error"))
            .finishReason(Optional.of(FinishReason.STOP))
            .avgLogprobs(Optional.of(-0.5))
            .branch(Optional.of("main"))
            .modelVersion(Optional.of("v1.0"))
            .build();
    assertTrue(event.interrupted().isPresent());
    assertTrue(event.interrupted().get());
    assertTrue(event.partial().isPresent());
    assertTrue(event.turnComplete().isPresent());
    assertTrue(event.longRunningToolIds().isPresent());
    assertTrue(event.errorCode().isPresent());
    assertTrue(event.errorMessage().isPresent());
    assertTrue(event.finishReason().isPresent());
    assertTrue(event.avgLogprobs().isPresent());
    assertTrue(event.branch().isPresent());
    assertTrue(event.modelVersion().isPresent());
  }

  @Test
  @Tag("valid")
  void interruptedWithTrueAndVerifyNotNull() {
    builder.interrupted(Optional.of(true));
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertNotNull(event.interrupted());
    assertTrue(event.interrupted().isPresent());
  }

  @Test
  @Tag("valid")
  void interruptedWithFalseAndVerifyNotNull() {
    builder.interrupted(Optional.of(false));
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertNotNull(event.interrupted());
    assertTrue(event.interrupted().isPresent());
  }

  @Test
  @Tag("boundary")
  void interruptedWithEmptyOptionalAndVerifyNotNull() {
    builder.interrupted(Optional.empty());
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertNotNull(event.interrupted());
    assertFalse(event.interrupted().isPresent());
  }

  @Test
  @Tag("integration")
  void interruptedWithActionsField() {
    EventActions actions =
        EventActions.builder().skipSummarization(true).endInvocation(true).build();
    Event event =
        builder
            .id("test-id")
            .invocationId("test-invocation")
            .author("test-author")
            .interrupted(Optional.of(true))
            .actions(actions)
            .build();
    assertTrue(event.interrupted().isPresent());
    assertTrue(event.interrupted().get());
    assertNotNull(event.actions());
  }

  @Test
  @Tag("valid")
  void interruptedOverwritePreviousValue() {
    builder.interrupted(Optional.of(false));
    builder.interrupted(Optional.of(true));
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertTrue(event.interrupted().isPresent());
    assertTrue(event.interrupted().get());
  }

  @Test
  @Tag("valid")
  void interruptedFromEmptyToTrue() {
    builder.interrupted(Optional.empty());
    builder.interrupted(Optional.of(true));
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertTrue(event.interrupted().isPresent());
    assertTrue(event.interrupted().get());
  }

  @Test
  @Tag("valid")
  void interruptedFromTrueToEmpty() {
    builder.interrupted(Optional.of(true));
    builder.interrupted(Optional.empty());
    Event event =
        builder.id("test-id").invocationId("test-invocation").author("test-author").build();
    assertFalse(event.interrupted().isPresent());
  }
}
