/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test Java-ADK-11-02 using AI Type Claude AI and AI Model claude-opus-4-6

ROOST_METHOD_HASH=deleteArtifact_28d8d187c1
ROOST_METHOD_SIG_HASH=deleteArtifact_3555eed233

Scenario 1: Successful Deletion of an Existing Artifact

Details:
  TestName: deleteArtifactSuccessfullyReturnsNoContent
  Description: Verifies that when the deleteArtifact method is called with valid path variables (appName, userId, sessionId, artifactName) and the underlying artifactService.deleteArtifact completes without throwing any exception, the method returns a ResponseEntity with HTTP status 204 (No Content) and a null body.

Execution:
  Arrange: Create a mock of BaseArtifactService. Configure the mock so that calling deleteArtifact("myApp", "user1", "session1", "artifact1") does nothing (completes normally). Instantiate ArtifactController with the mocked service.
  Act: Invoke deleteArtifact("myApp", "user1", "session1", "artifact1") on the controller.
  Assert: Assert that the returned ResponseEntity has HTTP status 204 (NO_CONTENT). Assert that the response body is null. Verify that artifactService.deleteArtifact was called exactly once with the arguments "myApp", "user1", "session1", "artifact1".

Validation:
  This assertion verifies that a successful deletion returns the correct HTTP 204 No Content response, which is the standard REST convention for successful delete operations. This is the primary happy-path scenario confirming the core functionality of the endpoint.


Scenario 2: Deletion Fails Due to RuntimeException Thrown by ArtifactService

Details:
  TestName: deleteArtifactThrowsRuntimeExceptionReturnsInternalServerError
  Description: Verifies that when artifactService.deleteArtifact throws a RuntimeException, the controller catches it and throws a ResponseStatusException with HTTP status 500 (INTERNAL_SERVER_ERROR) and the message "Error deleting artifact".

Execution:
  Arrange: Create a mock of BaseArtifactService. Configure the mock so that calling deleteArtifact("myApp", "user1", "session1", "artifact1") throws a new RuntimeException("Database connection failed"). Instantiate ArtifactController with the mocked service.
  Act: Invoke deleteArtifact("myApp", "user1", "session1", "artifact1") on the controller, expecting a ResponseStatusException to be thrown.
  Assert: Assert that a ResponseStatusException is thrown. Assert that the exception's status is HttpStatus.INTERNAL_SERVER_ERROR (500). Assert that the exception's reason is "Error deleting artifact". Assert that the exception's cause is the original RuntimeException.

Validation:
  This assertion verifies that runtime exceptions from the service layer are properly caught and translated into an appropriate HTTP 500 error response. This is critical for ensuring the API does not leak internal stack traces and provides a consistent error response format.


Scenario 3: Deletion Fails Due to a Checked Exception (General Exception)

Details:
  TestName: deleteArtifactThrowsCheckedExceptionReturnsInternalServerError
  Description: Verifies that when artifactService.deleteArtifact throws a general checked Exception, the controller catches it and throws a ResponseStatusException with HTTP status 500 (INTERNAL_SERVER_ERROR).

Execution:
  Arrange: Create a mock of BaseArtifactService. Configure the mock so that calling deleteArtifact("myApp", "user1", "session1", "artifact1") throws a new Exception("Unexpected error occurred"). Instantiate ArtifactController with the mocked service.
  Act: Invoke deleteArtifact("myApp", "user1", "session1", "artifact1") on the controller, expecting a ResponseStatusException to be thrown.
  Assert: Assert that a ResponseStatusException is thrown. Assert that the exception's status is HttpStatus.INTERNAL_SERVER_ERROR. Assert that the exception's reason is "Error deleting artifact". Assert that the cause of the ResponseStatusException is the original Exception.

Validation:
  This verifies that the catch block handles all Exception subclasses, not just RuntimeExceptions. It ensures robustness of the error handling mechanism for any unexpected failure scenario in the service layer.


Scenario 4: Deletion with Empty String Path Variables

Details:
  TestName: deleteArtifactWithEmptyStringParametersCallsServiceAndReturnsNoContent
  Description: Verifies that when deleteArtifact is called with empty string values for all path variables, the method still delegates to the artifactService without performing any input validation, and returns HTTP 204 if the service completes successfully.

Execution:
  Arrange: Create a mock of BaseArtifactService. Configure the mock so that calling deleteArtifact("", "", "", "") completes normally without throwing an exception. Instantiate ArtifactController with the mocked service.
  Act: Invoke deleteArtifact("", "", "", "") on the controller.
  Assert: Assert that the returned ResponseEntity has HTTP status 204 (NO_CONTENT). Verify that artifactService.deleteArtifact was called exactly once with ("", "", "", "").

Validation:
  This test verifies that the controller does not perform input validation on path variables and delegates all parameters directly to the service layer. This confirms the controller's role as a thin pass-through layer, leaving validation responsibility to the service or framework.


Scenario 5: Deletion with Special Characters in Artifact Name

Details:
  TestName: deleteArtifactWithSpecialCharactersInArtifactNameReturnsNoContent
  Description: Verifies that the deleteArtifact method correctly handles artifact names containing special characters (e.g., spaces, dots, hyphens, underscores) and successfully returns HTTP 204 when the service completes without error.

Execution:
  Arrange: Create a mock of BaseArtifactService. Configure the mock so that calling deleteArtifact("myApp", "user1", "session1", "my-artifact_v2.0 (copy)") completes normally. Instantiate ArtifactController with the mocked service.
  Act: Invoke deleteArtifact("myApp", "user1", "session1", "my-artifact_v2.0 (copy)") on the controller.
  Assert: Assert that the returned ResponseEntity has HTTP status 204 (NO_CONTENT). Verify that artifactService.deleteArtifact was called with the exact special-character artifact name.

Validation:
  This test ensures that the controller does not alter or reject artifact names with special characters. It validates that the endpoint can handle diverse naming conventions that may arise in real-world usage.


Scenario 6: Deletion Fails Due to NullPointerException

Details:
  TestName: deleteArtifactThrowsNullPointerExceptionReturnsInternalServerError
  Description: Verifies that when the artifactService.deleteArtifact method throws a NullPointerException (e.g., due to an internal null reference), the controller catches it and wraps it in a ResponseStatusException with HTTP 500 status.

Execution:
  Arrange: Create a mock of BaseArtifactService. Configure the mock so that calling deleteArtifact("myApp", "user1", "session1", "artifact1") throws a new NullPointerException("Null session reference"). Instantiate ArtifactController with the mocked service.
  Act: Invoke deleteArtifact("myApp", "user1", "session1", "artifact1") on the controller, expecting a ResponseStatusException.
  Assert: Assert that a ResponseStatusException is thrown with status HttpStatus.INTERNAL_SERVER_ERROR. Assert that the reason is "Error deleting artifact". Assert that the cause is the NullPointerException.

Validation:
  This test confirms that even unexpected programming errors like NullPointerException are gracefully handled by the catch block, preventing unhandled exceptions from propagating to the client and ensuring a consistent error response.


Scenario 7: Deletion Fails Due to IllegalArgumentException

Details:
  TestName: deleteArtifactThrowsIllegalArgumentExceptionReturnsInternalServerError
  Description: Verifies that when the artifactService.deleteArtifact throws an IllegalArgumentException (e.g., due to invalid parameter values detected at the service level), the controller catches it and returns an HTTP 500 error wrapped in a ResponseStatusException.

Execution:
  Arrange: Create a mock of BaseArtifactService. Configure the mock so that calling deleteArtifact("myApp", "user1", "session1", "invalidArtifact") throws a new IllegalArgumentException("Invalid artifact name"). Instantiate ArtifactController with the mocked service.
  Act: Invoke deleteArtifact("myApp", "user1", "session1", "invalidArtifact") on the controller, expecting a ResponseStatusException.
  Assert: Assert that a ResponseStatusException is thrown with status HttpStatus.INTERNAL_SERVER_ERROR. Assert that the reason is "Error deleting artifact". Assert that the cause is the IllegalArgumentException.

Validation:
  This validates that service-level validation errors are caught by the generic exception handler. It highlights that the controller treats all exceptions uniformly as internal server errors, which may be a design consideration for future refinement.


Scenario 8: Deletion with Very Long Path Variable Values

Details:
  TestName: deleteArtifactWithVeryLongParameterValuesReturnsNoContent
  Description: Verifies that the deleteArtifact method handles extremely long string values for path variables without issues, successfully delegating to the service and returning HTTP 204 when the service completes normally.

Execution:
  Arrange: Create a mock of BaseArtifactService. Generate a very long string (e.g., 10,000 characters) for each path variable. Configure the mock so that calling deleteArtifact with these long strings completes normally. Instantiate ArtifactController with the mocked service.
  Act: Invoke deleteArtifact with the long string values on the controller.
  Assert: Assert that the returned ResponseEntity has HTTP status 204 (NO_CONTENT). Verify that artifactService.deleteArtifact was called exactly once with the long string values.

Validation:
  This test ensures the controller does not impose any length restrictions on path variable values and correctly passes them through to the service layer. It validates robustness against edge cases involving unusually large inputs.


Scenario 9: Verify Service Method Is Called Exactly Once

Details:
  TestName: deleteArtifactCallsServiceDeleteExactlyOnce
  Description: Verifies that the artifactService.deleteArtifact method is invoked exactly once with the correct parameters when the controller's deleteArtifact method is called, ensuring no duplicate deletion calls occur.

Execution:
  Arrange: Create a mock of BaseArtifactService. Configure the mock so that deleteArtifact("appX", "userX", "sessionX", "artifactX") completes normally. Instantiate ArtifactController with the mocked service.
  Act: Invoke deleteArtifact("appX", "userX", "sessionX", "artifactX") on the controller.
  Assert: Verify that artifactService.deleteArtifact was called exactly once with arguments "appX", "userX", "sessionX", "artifactX". Verify no other interactions occurred on the mock.

Validation:
  This test ensures idempotent behavior at the controller level — that a single HTTP DELETE request results in exactly one call to the service layer. This is important for preventing accidental double-deletion or unintended side effects.


Scenario 10: Deletion Fails Due to IllegalStateException

Details:
  TestName: deleteArtifactThrowsIllegalStateExceptionReturnsInternalServerError
  Description: Verifies that when the artifactService.deleteArtifact throws an IllegalStateException (e.g., the service is in an invalid state such as not initialized), the controller catches it and throws a ResponseStatusException with HTTP 500.

Execution:
  Arrange: Create a mock of BaseArtifactService. Configure the mock so that calling deleteArtifact("myApp", "user1", "session1", "artifact1") throws a new IllegalStateException("Service not initialized"). Instantiate ArtifactController with the mocked service.
  Act: Invoke deleteArtifact("myApp", "user1", "session1", "artifact1") on the controller, expecting a ResponseStatusException.
  Assert: Assert that a ResponseStatusException is thrown with status HttpStatus.INTERNAL_SERVER_ERROR. Assert that the reason is "Error deleting artifact". Assert that the cause is the IllegalStateException.

Validation:
  This test validates that infrastructure-level exceptions related to service state are properly handled. It ensures the API remains stable and returns meaningful error responses even when the underlying service encounters state-related issues.


Scenario 11: Response Entity Body Is Null on Successful Deletion

Details:
  TestName: deleteArtifactSuccessfulResponseHasNullBody
  Description: Verifies that the ResponseEntity returned on successful deletion has a null body, consistent with the HTTP 204 No Content specification which mandates no response body.

Execution:
  Arrange: Create a mock of BaseArtifactService. Configure the mock so that deleteArtifact("myApp", "user1", "session1", "artifact1") completes normally. Instantiate ArtifactController with the mocked service.
  Act: Invoke deleteArtifact("myApp", "user1", "session1", "artifact1") on the controller and capture the ResponseEntity.
  Assert: Assert that the response body (getBody()) is null. Assert that the status code is 204.

Validation:
  This test explicitly validates the contract of a 204 No Content response — that no body is included. This is important for REST API compliance and ensures clients can rely on the standard behavior of the DELETE endpoint.


Scenario 12: Deletion with Null Artifact Name Causes NullPointerException

Details:
  TestName: deleteArtifactWithNullArtifactNameThrowsInternalServerError
  Description: Verifies the behavior when null is passed as the artifactName parameter. If the service throws an exception when receiving null, the controller should catch it and return HTTP 500.

Execution:
  Arrange: Create a mock of BaseArtifactService. Configure the mock so that calling deleteArtifact("myApp", "user1", "session1", null) throws a NullPointerException. Instantiate ArtifactController with the mocked service.
  Act: Invoke deleteArtifact("myApp", "user1", "session1", null) on the controller, expecting a ResponseStatusException.
  Assert: Assert that a ResponseStatusException is thrown with status HttpStatus.INTERNAL_SERVER_ERROR. Assert that the reason is "Error deleting artifact".

Validation:
  This test verifies the controller's resilience when receiving null path variables that bypass Spring's framework-level validation. It ensures that even in edge cases where null values reach the controller method, the error handling mechanism provides a consistent HTTP 500 response.

*/

// ********RoostGPT********

package com.google.adk.web.controller;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.doNothing;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoMoreInteractions;
import com.google.adk.artifacts.BaseArtifactService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.server.ResponseStatusException;
import org.junit.jupiter.api.*;
import com.google.adk.artifacts.ListArtifactsResponse;
import com.google.common.collect.ImmutableList;
import com.google.genai.types.Part;
import io.reactivex.rxjava3.core.Maybe;
import io.reactivex.rxjava3.core.Single;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

class ArtifactControllerDeleteArtifactTest {

	private BaseArtifactService artifactService;

	private ArtifactController controller;

	@BeforeEach
	void setUp() {
		artifactService = mock(BaseArtifactService.class);
		controller = new ArtifactController(artifactService);
	}

	@Test
	@Tag("valid")
	void deleteArtifactSuccessfullyReturnsNoContent() {
		doNothing().when(artifactService).deleteArtifact("myApp", "user1", "session1", "artifact1");
		ResponseEntity<Void> response = controller.deleteArtifact("myApp", "user1", "session1", "artifact1");
		assertEquals(HttpStatus.NO_CONTENT, response.getStatusCode());
		assertNull(response.getBody());
		verify(artifactService, times(1)).deleteArtifact("myApp", "user1", "session1", "artifact1");
	}

	@Test
	@Tag("invalid")
	void deleteArtifactThrowsRuntimeExceptionReturnsInternalServerError() {
		RuntimeException cause = new RuntimeException("Database connection failed");
		doThrow(cause).when(artifactService).deleteArtifact("myApp", "user1", "session1", "artifact1");
		ResponseStatusException exception = assertThrows(ResponseStatusException.class,
				() -> controller.deleteArtifact("myApp", "user1", "session1", "artifact1"));
		assertEquals(HttpStatus.INTERNAL_SERVER_ERROR, exception.getStatusCode());
		assertEquals("Error deleting artifact", exception.getReason());
		assertEquals(cause, exception.getCause());
	}

	@Test
	@Tag("invalid")
	void deleteArtifactThrowsCheckedExceptionReturnsInternalServerError() {
		Exception cause = new Exception("Unexpected error occurred");
		doThrow(cause).when(artifactService).deleteArtifact("myApp", "user1", "session1", "artifact1");
		ResponseStatusException exception = assertThrows(ResponseStatusException.class,
				() -> controller.deleteArtifact("myApp", "user1", "session1", "artifact1"));
		assertEquals(HttpStatus.INTERNAL_SERVER_ERROR, exception.getStatusCode());
		assertEquals("Error deleting artifact", exception.getReason());
		assertEquals(cause, exception.getCause());
	}

	@Test
	@Tag("boundary")
	void deleteArtifactWithEmptyStringParametersCallsServiceAndReturnsNoContent() {
		doNothing().when(artifactService).deleteArtifact("", "", "", "");
		ResponseEntity<Void> response = controller.deleteArtifact("", "", "", "");
		assertEquals(HttpStatus.NO_CONTENT, response.getStatusCode());
		verify(artifactService, times(1)).deleteArtifact("", "", "", "");
	}

	@Test
	@Tag("valid")
	void deleteArtifactWithSpecialCharactersInArtifactNameReturnsNoContent() {
		String specialArtifactName = "my-artifact_v2.0 (copy)";
		doNothing().when(artifactService).deleteArtifact("myApp", "user1", "session1", specialArtifactName);
		ResponseEntity<Void> response = controller.deleteArtifact("myApp", "user1", "session1", specialArtifactName);
		assertEquals(HttpStatus.NO_CONTENT, response.getStatusCode());
		verify(artifactService, times(1)).deleteArtifact("myApp", "user1", "session1", specialArtifactName);
	}

	@Test
	@Tag("invalid")
	void deleteArtifactThrowsNullPointerExceptionReturnsInternalServerError() {
		NullPointerException cause = new NullPointerException("Null session reference");
		doThrow(cause).when(artifactService).deleteArtifact("myApp", "user1", "session1", "artifact1");
		ResponseStatusException exception = assertThrows(ResponseStatusException.class,
				() -> controller.deleteArtifact("myApp", "user1", "session1", "artifact1"));
		assertEquals(HttpStatus.INTERNAL_SERVER_ERROR, exception.getStatusCode());
		assertEquals("Error deleting artifact", exception.getReason());
		assertEquals(cause, exception.getCause());
	}

	@Test
	@Tag("invalid")
	void deleteArtifactThrowsIllegalArgumentExceptionReturnsInternalServerError() {
		IllegalArgumentException cause = new IllegalArgumentException("Invalid artifact name");
		doThrow(cause).when(artifactService).deleteArtifact("myApp", "user1", "session1", "invalidArtifact");
		ResponseStatusException exception = assertThrows(ResponseStatusException.class,
				() -> controller.deleteArtifact("myApp", "user1", "session1", "invalidArtifact"));
		assertEquals(HttpStatus.INTERNAL_SERVER_ERROR, exception.getStatusCode());
		assertEquals("Error deleting artifact", exception.getReason());
		assertEquals(cause, exception.getCause());
	}

	@Test
	@Tag("boundary")
	void deleteArtifactWithVeryLongParameterValuesReturnsNoContent() {
		String longString = "a".repeat(10000);
		doNothing().when(artifactService).deleteArtifact(longString, longString, longString, longString);
		ResponseEntity<Void> response = controller.deleteArtifact(longString, longString, longString, longString);
		assertEquals(HttpStatus.NO_CONTENT, response.getStatusCode());
		verify(artifactService, times(1)).deleteArtifact(longString, longString, longString, longString);
	}

	@Test
	@Tag("valid")
	void deleteArtifactCallsServiceDeleteExactlyOnce() {
		doNothing().when(artifactService).deleteArtifact("appX", "userX", "sessionX", "artifactX");
		controller.deleteArtifact("appX", "userX", "sessionX", "artifactX");
		verify(artifactService, times(1)).deleteArtifact("appX", "userX", "sessionX", "artifactX");
		verifyNoMoreInteractions(artifactService);
	}

	@Test
	@Tag("invalid")
	void deleteArtifactThrowsIllegalStateExceptionReturnsInternalServerError() {
		IllegalStateException cause = new IllegalStateException("Service not initialized");
		doThrow(cause).when(artifactService).deleteArtifact("myApp", "user1", "session1", "artifact1");
		ResponseStatusException exception = assertThrows(ResponseStatusException.class,
				() -> controller.deleteArtifact("myApp", "user1", "session1", "artifact1"));
		assertEquals(HttpStatus.INTERNAL_SERVER_ERROR, exception.getStatusCode());
		assertEquals("Error deleting artifact", exception.getReason());
		assertEquals(cause, exception.getCause());
	}

	@Test
	@Tag("valid")
	void deleteArtifactSuccessfulResponseHasNullBody() {
		doNothing().when(artifactService).deleteArtifact("myApp", "user1", "session1", "artifact1");
		ResponseEntity<Void> response = controller.deleteArtifact("myApp", "user1", "session1", "artifact1");
		assertNull(response.getBody());
		assertEquals(204, response.getStatusCode().value());
	}

	@Test
	@Tag("boundary")
	void deleteArtifactWithNullArtifactNameThrowsInternalServerError() {
		NullPointerException cause = new NullPointerException();
		doThrow(cause).when(artifactService).deleteArtifact("myApp", "user1", "session1", null);
		ResponseStatusException exception = assertThrows(ResponseStatusException.class,
				() -> controller.deleteArtifact("myApp", "user1", "session1", null));
		assertEquals(HttpStatus.INTERNAL_SERVER_ERROR, exception.getStatusCode());
		assertEquals("Error deleting artifact", exception.getReason());
	}

}