/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test Java-ADK-11-02 using AI Type Claude AI and AI Model claude-opus-4-6

ROOST_METHOD_HASH=listArtifactNames_48b4fb738d
ROOST_METHOD_SIG_HASH=listArtifactNames_11cba21961

Scenario 1: Successfully list artifact names when service returns multiple filenames

Details:
  TestName: listArtifactNamesReturnsMultipleFilenames
  Description: Verify that when the artifact service returns a ListArtifactsResponse containing multiple filenames, the method correctly returns all of them as a List<String>.
Execution:
  Arrange: Mock the BaseArtifactService's listArtifactKeys method to return a Single wrapping a ListArtifactsResponse that contains a list of multiple filenames (e.g., "file1.txt", "file2.txt", "file3.txt"). Create the ArtifactController with the mocked service.
  Act: Call listArtifactNames with appName="myApp", userId="user1", sessionId="session1".
  Assert: Assert that the returned list has size 3 and contains "file1.txt", "file2.txt", and "file3.txt" in the expected order.
Validation:
  This assertion verifies that the method correctly extracts and returns the filenames from the ListArtifactsResponse. This is the primary happy-path scenario ensuring the core functionality works as expected.

Scenario 2: Return empty list when service returns a ListArtifactsResponse with null filenames

Details:
  TestName: listArtifactNamesReturnsEmptyListWhenFilenamesAreNull
  Description: Verify that when the artifact service returns a ListArtifactsResponse where filenames() returns null, the method returns an empty list instead of throwing a NullPointerException.
Execution:
  Arrange: Mock the BaseArtifactService's listArtifactKeys method to return a Single wrapping a ListArtifactsResponse whose filenames() method returns null.
  Act: Call listArtifactNames with appName="myApp", userId="user1", sessionId="session1".
  Assert: Assert that the returned list is not null and is empty (Collections.emptyList()).
Validation:
  This assertion verifies the null-safety guard in the method. The code explicitly checks for null filenames and falls back to Collections.emptyList(), which is critical for preventing NullPointerExceptions downstream.

Scenario 3: Return empty list when service returns a ListArtifactsResponse with an empty filenames list

Details:
  TestName: listArtifactNamesReturnsEmptyListWhenFilenamesListIsEmpty
  Description: Verify that when the artifact service returns a ListArtifactsResponse containing an empty list of filenames, the method returns an empty list.
Execution:
  Arrange: Mock the BaseArtifactService's listArtifactKeys method to return a Single wrapping a ListArtifactsResponse whose filenames() returns an empty list (Collections.emptyList()).
  Act: Call listArtifactNames with appName="myApp", userId="user1", sessionId="session1".
  Assert: Assert that the returned list is not null and has size 0.
Validation:
  This verifies that the method correctly handles the edge case where the response is valid but contains no artifacts. This is important for sessions that have no associated artifacts.

Scenario 4: Return a single filename when service returns a response with one artifact

Details:
  TestName: listArtifactNamesReturnsSingleFilename
  Description: Verify that when the artifact service returns a ListArtifactsResponse containing exactly one filename, the method returns a list with that single entry.
Execution:
  Arrange: Mock the BaseArtifactService's listArtifactKeys method to return a Single wrapping a ListArtifactsResponse containing a single filename (e.g., "only-artifact.pdf").
  Act: Call listArtifactNames with appName="testApp", userId="userA", sessionId="sessionX".
  Assert: Assert that the returned list has size 1 and contains "only-artifact.pdf".
Validation:
  This validates the boundary case of a single artifact. It ensures the method does not inadvertently filter or modify the results when there is only one item.

Scenario 5: Exception is propagated when the artifact service throws a runtime exception

Details:
  TestName: listArtifactNamesThrowsExceptionWhenServiceFails
  Description: Verify that when the artifact service's listArtifactKeys method returns a Single that emits an error (e.g., RuntimeException), the exception propagates to the caller via blockingGet().
Execution:
  Arrange: Mock the BaseArtifactService's listArtifactKeys method to return Single.error(new RuntimeException("Service unavailable")).
  Act: Call listArtifactNames with appName="myApp", userId="user1", sessionId="session1" and expect an exception.
  Assert: Assert that a RuntimeException is thrown with the message "Service unavailable".
Validation:
  This verifies that the method does not silently swallow exceptions from the underlying service. Proper error propagation is essential for upstream error handling and debugging in production.

Scenario 6: Method correctly passes path variables to the artifact service

Details:
  TestName: listArtifactNamesPassesCorrectParametersToService
  Description: Verify that the appName, userId, and sessionId path variables are correctly forwarded to the artifactService.listArtifactKeys method.
Execution:
  Arrange: Mock the BaseArtifactService and set up listArtifactKeys to return a Single wrapping a ListArtifactsResponse with an empty list. Use argument captors or verification to check the parameters.
  Act: Call listArtifactNames with appName="specificApp", userId="specificUser", sessionId="specificSession".
  Assert: Verify that artifactService.listArtifactKeys was called exactly once with arguments "specificApp", "specificUser", and "specificSession".
Validation:
  This ensures the controller correctly delegates to the service layer with the exact parameters received from the HTTP request. Incorrect parameter passing could lead to returning artifacts for the wrong session or user.

Scenario 7: Return empty list when the ListArtifactsResponse itself is null

Details:
  TestName: listArtifactNamesReturnsEmptyListWhenResponseIsNull
  Description: Verify that when the Single from the artifact service resolves to a null ListArtifactsResponse, the method gracefully returns an empty list.
Execution:
  Arrange: Mock the BaseArtifactService's listArtifactKeys method to return Single.just() is not applicable for null, so use a workaround such as mocking blockingGet behavior or using a Single that somehow yields null (e.g., via an unsafe cast or a custom Single implementation). Alternatively, if Single cannot emit null, verify the code path by mocking the response object to be null-like.
  Act: Call listArtifactNames with appName="myApp", userId="user1", sessionId="session1".
  Assert: Assert that the returned list is not null and is empty.
Validation:
  Although RxJava's Single typically does not emit null values, this test validates the defensive null check on the response object. The code explicitly handles `response != null`, so this scenario ensures that safety net works correctly if an unexpected null somehow occurs.

Scenario 8: Handle special characters in path variables

Details:
  TestName: listArtifactNamesHandlesSpecialCharactersInPathVariables
  Description: Verify that the method works correctly when path variables contain special characters such as hyphens, underscores, or dots (e.g., appName="my-app_v2.0", userId="user@domain", sessionId="session-123_abc").
Execution:
  Arrange: Mock the BaseArtifactService's listArtifactKeys method to return a Single wrapping a ListArtifactsResponse with filenames like ["artifact-1.bin", "data_file.json"]. Set up the mock to accept the special-character parameters.
  Act: Call listArtifactNames with appName="my-app_v2.0", userId="user@domain", sessionId="session-123_abc".
  Assert: Assert that the returned list has size 2 and contains the expected filenames. Verify the service was called with the exact special-character parameters.
Validation:
  This ensures the controller does not perform any unintended sanitization or transformation on path variable values. Real-world application names, user IDs, and session IDs may contain various special characters.

Scenario 9: Handle empty string path variables

Details:
  TestName: listArtifactNamesHandlesEmptyStringParameters
  Description: Verify the behavior of the method when one or more path variables are empty strings. The method should still delegate to the service with the empty strings as-is.
Execution:
  Arrange: Mock the BaseArtifactService's listArtifactKeys method to accept empty strings and return a Single wrapping a ListArtifactsResponse with an empty filenames list.
  Act: Call listArtifactNames with appName="", userId="", sessionId="".
  Assert: Assert that the returned list is empty and verify that the service was called with empty string arguments.
Validation:
  This tests the edge case where path variables resolve to empty strings. The controller does not perform input validation, so it should pass the values through to the service layer, which is responsible for handling invalid inputs.

Scenario 10: Verify the returned list preserves the order from the service response

Details:
  TestName: listArtifactNamesPreservesOrderOfFilenames
  Description: Verify that the order of filenames in the returned list matches the order provided by the ListArtifactsResponse from the service.
Execution:
  Arrange: Mock the BaseArtifactService's listArtifactKeys method to return a Single wrapping a ListArtifactsResponse with filenames in a specific order: ["zebra.txt", "alpha.txt", "middle.txt"].
  Act: Call listArtifactNames with appName="app", userId="user", sessionId="session".
  Assert: Assert that the returned list has exactly 3 elements and that the first element is "zebra.txt", the second is "alpha.txt", and the third is "middle.txt".
Validation:
  This ensures the method does not sort or reorder the filenames. Preserving the original order from the service is important because consumers of this API may rely on the ordering for display or processing purposes.

Scenario 11: Service returns a response with a large number of filenames

Details:
  TestName: listArtifactNamesHandlesLargeNumberOfFilenames
  Description: Verify that the method correctly handles a ListArtifactsResponse containing a large number of filenames (e.g., 10,000 entries) without issues.
Execution:
  Arrange: Create a list of 10,000 filenames (e.g., "file_0", "file_1", ..., "file_9999"). Mock the BaseArtifactService's listArtifactKeys method to return a Single wrapping a ListArtifactsResponse containing this large list.
  Act: Call listArtifactNames with appName="app", userId="user", sessionId="session".
  Assert: Assert that the returned list has size 10,000 and that the first and last elements match the expected values.
Validation:
  This stress-tests the method to ensure it can handle large result sets without performance degradation or memory issues. In production, sessions may accumulate many artifacts over time.

*/

// ********RoostGPT********

package com.google.adk.web.controller;

import static com.google.common.truth.Truth.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import static org.mockito.Mockito.times;
import com.google.adk.artifacts.BaseArtifactService;
import com.google.adk.artifacts.ListArtifactsResponse;
import io.reactivex.rxjava3.core.Single;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.*;
import com.google.common.collect.ImmutableList;
import com.google.genai.types.Part;
import io.reactivex.rxjava3.core.Maybe;
import java.util.Optional;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.server.ResponseStatusException;

public class ArtifactControllerListArtifactNamesTest {

	private BaseArtifactService artifactService;

	private ArtifactController artifactController;

	@BeforeEach
	void setUp() {
		artifactService = mock(BaseArtifactService.class);
		artifactController = new ArtifactController(artifactService);
	}

	@Test
	@Tag("valid")
	void listArtifactNamesReturnsMultipleFilenames() {
		List<String> expectedFilenames = Arrays.asList("file1.txt", "file2.txt", "file3.txt");
		ListArtifactsResponse response = mock(ListArtifactsResponse.class);
		when(response.filenames()).thenReturn(expectedFilenames);
		when(artifactService.listArtifactKeys("myApp", "user1", "session1")).thenReturn(Single.just(response));
		List<String> result = artifactController.listArtifactNames("myApp", "user1", "session1");
		assertThat(result).hasSize(3);
		assertThat(result).containsExactly("file1.txt", "file2.txt", "file3.txt").inOrder();
	}

	@Test
	@Tag("boundary")
	void listArtifactNamesReturnsEmptyListWhenFilenamesAreNull() {
		ListArtifactsResponse response = mock(ListArtifactsResponse.class);
		when(response.filenames()).thenReturn(null);
		when(artifactService.listArtifactKeys("myApp", "user1", "session1")).thenReturn(Single.just(response));
		List<String> result = artifactController.listArtifactNames("myApp", "user1", "session1");
		assertThat(result).isNotNull();
		assertThat(result).isEmpty();
	}

	@Test
	@Tag("boundary")
	void listArtifactNamesReturnsEmptyListWhenFilenamesListIsEmpty() {
		ListArtifactsResponse response = mock(ListArtifactsResponse.class);
		when(response.filenames()).thenReturn(Collections.emptyList());
		when(artifactService.listArtifactKeys("myApp", "user1", "session1")).thenReturn(Single.just(response));
		List<String> result = artifactController.listArtifactNames("myApp", "user1", "session1");
		assertThat(result).isNotNull();
		assertThat(result).hasSize(0);
	}

	@Test
	@Tag("valid")
	void listArtifactNamesReturnsSingleFilename() {
		List<String> expectedFilenames = Collections.singletonList("only-artifact.pdf");
		ListArtifactsResponse response = mock(ListArtifactsResponse.class);
		when(response.filenames()).thenReturn(expectedFilenames);
		when(artifactService.listArtifactKeys("testApp", "userA", "sessionX")).thenReturn(Single.just(response));
		List<String> result = artifactController.listArtifactNames("testApp", "userA", "sessionX");
		assertThat(result).hasSize(1);
		assertThat(result).containsExactly("only-artifact.pdf");
	}

	@Test
    @Tag("invalid")
    void listArtifactNamesThrowsExceptionWhenServiceFails() {
        when(artifactService.listArtifactKeys("myApp", "user1", "session1"))
                .thenReturn(Single.error(new RuntimeException("Service unavailable")));
        RuntimeException exception = assertThrows(RuntimeException.class, () ->
                artifactController.listArtifactNames("myApp", "user1", "session1"));
        assertThat(exception).hasMessageThat().contains("Service unavailable");
    }

	@Test
	@Tag("valid")
	void listArtifactNamesPassesCorrectParametersToService() {
		ListArtifactsResponse response = mock(ListArtifactsResponse.class);
		when(response.filenames()).thenReturn(Collections.emptyList());
		when(artifactService.listArtifactKeys("specificApp", "specificUser", "specificSession"))
			.thenReturn(Single.just(response));
		artifactController.listArtifactNames("specificApp", "specificUser", "specificSession");
		verify(artifactService, times(1)).listArtifactKeys("specificApp", "specificUser", "specificSession");
	}

	@Test
	@Tag("boundary")
	void listArtifactNamesReturnsEmptyListWhenResponseIsNull() {
		@SuppressWarnings("unchecked")
		Single<ListArtifactsResponse> singleMock = mock(Single.class);
		when(singleMock.blockingGet()).thenReturn(null);
		when(artifactService.listArtifactKeys("myApp", "user1", "session1")).thenReturn(singleMock);
		List<String> result = artifactController.listArtifactNames("myApp", "user1", "session1");
		assertThat(result).isNotNull();
		assertThat(result).isEmpty();
	}

	@Test
	@Tag("valid")
	void listArtifactNamesHandlesSpecialCharactersInPathVariables() {
		List<String> expectedFilenames = Arrays.asList("artifact-1.bin", "data_file.json");
		ListArtifactsResponse response = mock(ListArtifactsResponse.class);
		when(response.filenames()).thenReturn(expectedFilenames);
		when(artifactService.listArtifactKeys("my-app_v2.0", "user@domain", "session-123_abc"))
			.thenReturn(Single.just(response));
		List<String> result = artifactController.listArtifactNames("my-app_v2.0", "user@domain", "session-123_abc");
		assertThat(result).hasSize(2);
		assertThat(result).containsExactly("artifact-1.bin", "data_file.json").inOrder();
		verify(artifactService, times(1)).listArtifactKeys("my-app_v2.0", "user@domain", "session-123_abc");
	}

	@Test
	@Tag("boundary")
	void listArtifactNamesHandlesEmptyStringParameters() {
		ListArtifactsResponse response = mock(ListArtifactsResponse.class);
		when(response.filenames()).thenReturn(Collections.emptyList());
		when(artifactService.listArtifactKeys("", "", "")).thenReturn(Single.just(response));
		List<String> result = artifactController.listArtifactNames("", "", "");
		assertThat(result).isEmpty();
		verify(artifactService, times(1)).listArtifactKeys("", "", "");
	}

	@Test
	@Tag("valid")
	void listArtifactNamesPreservesOrderOfFilenames() {
		List<String> expectedFilenames = Arrays.asList("zebra.txt", "alpha.txt", "middle.txt");
		ListArtifactsResponse response = mock(ListArtifactsResponse.class);
		when(response.filenames()).thenReturn(expectedFilenames);
		when(artifactService.listArtifactKeys("app", "user", "session")).thenReturn(Single.just(response));
		List<String> result = artifactController.listArtifactNames("app", "user", "session");
		assertThat(result).hasSize(3);
		assertThat(result.get(0)).isEqualTo("zebra.txt");
		assertThat(result.get(1)).isEqualTo("alpha.txt");
		assertThat(result.get(2)).isEqualTo("middle.txt");
		assertThat(result).containsExactly("zebra.txt", "alpha.txt", "middle.txt").inOrder();
	}

	@Test
	@Tag("boundary")
	void listArtifactNamesHandlesLargeNumberOfFilenames() {
		List<String> largeFilenameList = new ArrayList<>();
		for (int i = 0; i < 10000; i++) {
			largeFilenameList.add("file_" + i);
		}
		ListArtifactsResponse response = mock(ListArtifactsResponse.class);
		when(response.filenames()).thenReturn(largeFilenameList);
		when(artifactService.listArtifactKeys("app", "user", "session")).thenReturn(Single.just(response));
		List<String> result = artifactController.listArtifactNames("app", "user", "session");
		assertThat(result).hasSize(10000);
		assertThat(result.get(0)).isEqualTo("file_0");
		assertThat(result.get(9999)).isEqualTo("file_9999");
	}

}