/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test Java-ADK-11-02 using AI Type Claude AI and AI Model claude-opus-4-6

ROOST_METHOD_HASH=loadArtifactVersion_77d6b55164
ROOST_METHOD_SIG_HASH=loadArtifactVersion_a3f9e6006d

Scenario 1: Successfully Load an Artifact with a Specific Version

Details:
  TestName: loadArtifactVersionSuccessfullyReturnsPartWhenArtifactExists
  Description: Verify that the method returns a valid Part object when the artifact service successfully finds and returns an artifact for the given app name, user ID, session ID, artifact name, and version ID.
Execution:
  Arrange: Mock the BaseArtifactService. Configure artifactService.loadArtifact("myApp", "user1", "session1", "artifact1", Optional.of(3)) to return Maybe.just(mockPart), where mockPart is a mocked Part object.
  Act: Invoke loadArtifactVersion("myApp", "user1", "session1", "artifact1", 3) on the ArtifactController instance.
  Assert: Assert that the returned Part object is not null and is equal to the expected mockPart.
Validation:
  The assertion verifies that when the artifact service locates the requested artifact version, the controller correctly returns it. This is the primary happy-path scenario ensuring the basic retrieval functionality works as expected.

---

Scenario 2: Throw ResponseStatusException with NOT_FOUND When Artifact Version Does Not Exist

Details:
  TestName: loadArtifactVersionThrowsNotFoundWhenArtifactIsNull
  Description: Verify that the method throws a ResponseStatusException with HTTP status 404 (NOT_FOUND) when the artifact service returns an empty Maybe (i.e., the artifact version is not found).
Execution:
  Arrange: Mock the BaseArtifactService. Configure artifactService.loadArtifact("myApp", "user1", "session1", "nonExistentArtifact", Optional.of(5)) to return Maybe.empty().
  Act: Invoke loadArtifactVersion("myApp", "user1", "session1", "nonExistentArtifact", 5) on the ArtifactController instance.
  Assert: Assert that a ResponseStatusException is thrown with HttpStatus.NOT_FOUND and the message "Artifact version not found".
Validation:
  The assertion confirms that when no artifact is found for the specified version, the controller properly signals a 404 error. This is critical for proper REST API error handling and informing clients that the requested resource does not exist.

---

Scenario 3: Load Artifact Version with Version ID Zero

Details:
  TestName: loadArtifactVersionWithVersionIdZeroReturnsPartSuccessfully
  Description: Verify that the method correctly handles a version ID of 0, which is a valid integer boundary value, and returns the artifact if the service finds it.
Execution:
  Arrange: Mock the BaseArtifactService. Configure artifactService.loadArtifact("myApp", "user1", "session1", "artifact1", Optional.of(0)) to return Maybe.just(mockPart).
  Act: Invoke loadArtifactVersion("myApp", "user1", "session1", "artifact1", 0) on the ArtifactController instance.
  Assert: Assert that the returned Part is not null and equals the expected mockPart.
Validation:
  This test validates that the edge case of version ID 0 is handled correctly. Since versionId is an int, 0 is a valid value and the service should be queried with Optional.of(0). This ensures no special-case logic inadvertently skips version 0.

---

Scenario 4: Load Artifact Version with Negative Version ID

Details:
  TestName: loadArtifactVersionWithNegativeVersionIdThrowsNotFound
  Description: Verify the behavior when a negative version ID is provided. Since the service is unlikely to have negative versions, the service should return empty, and the controller should throw a NOT_FOUND exception.
Execution:
  Arrange: Mock the BaseArtifactService. Configure artifactService.loadArtifact("myApp", "user1", "session1", "artifact1", Optional.of(-1)) to return Maybe.empty().
  Act: Invoke loadArtifactVersion("myApp", "user1", "session1", "artifact1", -1) on the ArtifactController instance.
  Assert: Assert that a ResponseStatusException is thrown with HttpStatus.NOT_FOUND.
Validation:
  This test ensures that negative version IDs are gracefully handled. Even though negative versions are semantically invalid, the controller delegates to the service and properly returns a 404 when no artifact is found, rather than crashing or returning an unexpected response.

---

Scenario 5: Load Artifact Version When Service Throws an Exception

Details:
  TestName: loadArtifactVersionThrowsExceptionWhenServiceFails
  Description: Verify that if the artifact service throws a runtime exception during the loadArtifact call, the exception propagates up from the controller without being caught.
Execution:
  Arrange: Mock the BaseArtifactService. Configure artifactService.loadArtifact("myApp", "user1", "session1", "artifact1", Optional.of(1)) to return Maybe.error(new RuntimeException("Service unavailable")).
  Act: Invoke loadArtifactVersion("myApp", "user1", "session1", "artifact1", 1) on the ArtifactController instance.
  Assert: Assert that a RuntimeException is thrown with the message "Service unavailable".
Validation:
  This test verifies that unexpected service-level errors are not silently swallowed. Since the method does not have a try-catch block for general exceptions, the error should propagate, allowing Spring's exception handling mechanism to return an appropriate HTTP 500 response.

---

Scenario 6: Load Artifact Version with Empty String Path Variables

Details:
  TestName: loadArtifactVersionWithEmptyAppNameDelegatesToService
  Description: Verify the behavior when empty strings are passed as path variables (e.g., appName is an empty string). The controller should still delegate to the service and return the result or throw NOT_FOUND based on the service response.
Execution:
  Arrange: Mock the BaseArtifactService. Configure artifactService.loadArtifact("", "user1", "session1", "artifact1", Optional.of(1)) to return Maybe.empty().
  Act: Invoke loadArtifactVersion("", "user1", "session1", "artifact1", 1) on the ArtifactController instance.
  Assert: Assert that a ResponseStatusException is thrown with HttpStatus.NOT_FOUND.
Validation:
  This test checks that the controller does not perform its own validation on path variable content and instead relies on the service layer. When the service cannot find an artifact with an empty app name, the controller correctly returns a 404 response.

---

Scenario 7: Load Artifact Version with Large Version ID

Details:
  TestName: loadArtifactVersionWithLargeVersionIdReturnsPartSuccessfully
  Description: Verify that the method handles a very large version ID (e.g., Integer.MAX_VALUE) without issues and returns the artifact if the service finds it.
Execution:
  Arrange: Mock the BaseArtifactService. Configure artifactService.loadArtifact("myApp", "user1", "session1", "artifact1", Optional.of(Integer.MAX_VALUE)) to return Maybe.just(mockPart).
  Act: Invoke loadArtifactVersion("myApp", "user1", "session1", "artifact1", Integer.MAX_VALUE) on the ArtifactController instance.
  Assert: Assert that the returned Part is not null and equals the expected mockPart.
Validation:
  This test ensures that boundary integer values for versionId are handled correctly. The controller should pass the value through to the service without overflow or truncation issues, confirming robustness at integer boundaries.

---

Scenario 8: Load Artifact Version with Special Characters in Artifact Name

Details:
  TestName: loadArtifactVersionWithSpecialCharactersInArtifactName
  Description: Verify that the method correctly handles artifact names containing special characters (e.g., "my-artifact_v2.0") and delegates them to the service as-is.
Execution:
  Arrange: Mock the BaseArtifactService. Configure artifactService.loadArtifact("myApp", "user1", "session1", "my-artifact_v2.0", Optional.of(1)) to return Maybe.just(mockPart).
  Act: Invoke loadArtifactVersion("myApp", "user1", "session1", "my-artifact_v2.0", 1) on the ArtifactController instance.
  Assert: Assert that the returned Part is not null and equals the expected mockPart.
Validation:
  This test validates that artifact names with hyphens, underscores, and dots are properly passed through to the service layer. This is important because artifact names in real-world usage often contain such characters, and the controller must not alter or reject them.

---

Scenario 9: Load Artifact Version Passes Correct Optional to Service

Details:
  TestName: loadArtifactVersionPassesOptionalOfVersionIdToService
  Description: Verify that the method wraps the versionId in Optional.of() (not Optional.ofNullable or Optional.empty) when calling the artifact service, ensuring the version is always explicitly specified.
Execution:
  Arrange: Mock the BaseArtifactService. Configure artifactService.loadArtifact("myApp", "user1", "session1", "artifact1", Optional.of(7)) to return Maybe.just(mockPart).
  Act: Invoke loadArtifactVersion("myApp", "user1", "session1", "artifact1", 7) on the ArtifactController instance.
  Assert: Verify that artifactService.loadArtifact was called exactly once with the arguments "myApp", "user1", "session1", "artifact1", and Optional.of(7).
Validation:
  This test confirms the contract between the controller and the service layer. Unlike the loadArtifact method which uses Optional.ofNullable, loadArtifactVersion must always pass a present Optional since the version is a required path variable. This ensures the service always receives an explicit version number.

---

Scenario 10: Load Artifact Version with Whitespace in Path Variables

Details:
  TestName: loadArtifactVersionWithWhitespaceInUserIdDelegatesToService
  Description: Verify the behavior when path variables contain whitespace characters (e.g., userId is " user 1 "). The controller should pass the value as-is to the service.
Execution:
  Arrange: Mock the BaseArtifactService. Configure artifactService.loadArtifact("myApp", " user 1 ", "session1", "artifact1", Optional.of(2)) to return Maybe.just(mockPart).
  Act: Invoke loadArtifactVersion("myApp", " user 1 ", "session1", "artifact1", 2) on the ArtifactController instance.
  Assert: Assert that the returned Part is not null and equals the expected mockPart.
Validation:
  This test ensures the controller does not trim or sanitize path variable values before passing them to the service. Input validation and sanitization responsibilities lie elsewhere, and the controller should faithfully forward the received parameters.

---

Scenario 11: Load Artifact Version When Service Returns Maybe with Null Item

Details:
  TestName: loadArtifactVersionThrowsNotFoundWhenMaybeCompletesWithoutValue
  Description: Verify that when the artifact service returns a Maybe that completes without emitting any item (Maybe.empty()), the blockingGet() returns null and the controller throws a ResponseStatusException with NOT_FOUND status.
Execution:
  Arrange: Mock the BaseArtifactService. Configure artifactService.loadArtifact("myApp", "user1", "session1", "artifact1", Optional.of(99)) to return Maybe.empty().
  Act: Invoke loadArtifactVersion("myApp", "user1", "session1", "artifact1", 99) on the ArtifactController instance.
  Assert: Assert that a ResponseStatusException is thrown with HttpStatus.NOT_FOUND and the reason phrase "Artifact version not found".
Validation:
  This test reinforces the null-check logic in the controller. When Maybe.empty() is returned, blockingGet() yields null, triggering the NOT_FOUND exception. This is essential for ensuring that missing artifact versions are communicated correctly to API consumers via the appropriate HTTP status code.

---

Scenario 12: Load Artifact Version with Minimum Integer Version ID

Details:
  TestName: loadArtifactVersionWithMinIntegerVersionIdThrowsNotFound
  Description: Verify the behavior when Integer.MIN_VALUE is passed as the version ID. The service is expected to return empty for such an invalid version, and the controller should throw NOT_FOUND.
Execution:
  Arrange: Mock the BaseArtifactService. Configure artifactService.loadArtifact("myApp", "user1", "session1", "artifact1", Optional.of(Integer.MIN_VALUE)) to return Maybe.empty().
  Act: Invoke loadArtifactVersion("myApp", "user1", "session1", "artifact1", Integer.MIN_VALUE) on the ArtifactController instance.
  Assert: Assert that a ResponseStatusException is thrown with HttpStatus.NOT_FOUND.
Validation:
  This test covers the lower boundary of the int type for versionId. It ensures the controller handles extreme negative values gracefully without unexpected behavior, maintaining consistent error responses for non-existent versions.

*/

// ********RoostGPT********

package com.google.adk.web.controller;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import com.google.adk.artifacts.BaseArtifactService;
import com.google.genai.types.Part;
import io.reactivex.rxjava3.core.Maybe;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.web.server.ResponseStatusException;
import org.junit.jupiter.api.*;
import com.google.adk.artifacts.ListArtifactsResponse;
import com.google.common.collect.ImmutableList;
import io.reactivex.rxjava3.core.Single;
import java.util.Collections;
import java.util.List;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

class ArtifactControllerLoadArtifactVersionTest {

	private BaseArtifactService artifactService;

	private ArtifactController artifactController;

	private Part mockPart;

	@BeforeEach
	void setUp() {
		artifactService = mock(BaseArtifactService.class);
		artifactController = new ArtifactController(artifactService);
		mockPart = mock(Part.class);
	}

	@Test
    @Tag("valid")
    void loadArtifactVersionSuccessfullyReturnsPartWhenArtifactExists() {
        when(artifactService.loadArtifact("myApp", "user1", "session1", "artifact1", Optional.of(3)))
                .thenReturn(Maybe.just(mockPart));
        Part result = artifactController.loadArtifactVersion("myApp", "user1", "session1", "artifact1", 3);
        assertNotNull(result);
        assertEquals(mockPart, result);
    }

	@Test
    @Tag("invalid")
    void loadArtifactVersionThrowsNotFoundWhenArtifactIsNull() {
        when(artifactService.loadArtifact("myApp", "user1", "session1", "nonExistentArtifact", Optional.of(5)))
                .thenReturn(Maybe.empty());
        ResponseStatusException exception = assertThrows(ResponseStatusException.class, () ->
                artifactController.loadArtifactVersion("myApp", "user1", "session1", "nonExistentArtifact", 5));
        assertEquals(HttpStatus.NOT_FOUND, exception.getStatusCode());
        assertEquals("Artifact version not found", exception.getReason());
    }

	@Test
    @Tag("boundary")
    void loadArtifactVersionWithVersionIdZeroReturnsPartSuccessfully() {
        when(artifactService.loadArtifact("myApp", "user1", "session1", "artifact1", Optional.of(0)))
                .thenReturn(Maybe.just(mockPart));
        Part result = artifactController.loadArtifactVersion("myApp", "user1", "session1", "artifact1", 0);
        assertNotNull(result);
        assertEquals(mockPart, result);
    }

	@Test
    @Tag("boundary")
    void loadArtifactVersionWithNegativeVersionIdThrowsNotFound() {
        when(artifactService.loadArtifact("myApp", "user1", "session1", "artifact1", Optional.of(-1)))
                .thenReturn(Maybe.empty());
        ResponseStatusException exception = assertThrows(ResponseStatusException.class, () ->
                artifactController.loadArtifactVersion("myApp", "user1", "session1", "artifact1", -1));
        assertEquals(HttpStatus.NOT_FOUND, exception.getStatusCode());
    }

	@Test
    @Tag("invalid")
    void loadArtifactVersionThrowsExceptionWhenServiceFails() {
        when(artifactService.loadArtifact("myApp", "user1", "session1", "artifact1", Optional.of(1)))
                .thenReturn(Maybe.error(new RuntimeException("Service unavailable")));
        RuntimeException exception = assertThrows(RuntimeException.class, () ->
                artifactController.loadArtifactVersion("myApp", "user1", "session1", "artifact1", 1));
        assertEquals("Service unavailable", exception.getMessage());
    }

	@Test
    @Tag("invalid")
    void loadArtifactVersionWithEmptyAppNameDelegatesToService() {
        when(artifactService.loadArtifact("", "user1", "session1", "artifact1", Optional.of(1)))
                .thenReturn(Maybe.empty());
        ResponseStatusException exception = assertThrows(ResponseStatusException.class, () ->
                artifactController.loadArtifactVersion("", "user1", "session1", "artifact1", 1));
        assertEquals(HttpStatus.NOT_FOUND, exception.getStatusCode());
    }

	@Test
    @Tag("boundary")
    void loadArtifactVersionWithLargeVersionIdReturnsPartSuccessfully() {
        when(artifactService.loadArtifact("myApp", "user1", "session1", "artifact1", Optional.of(Integer.MAX_VALUE)))
                .thenReturn(Maybe.just(mockPart));
        Part result = artifactController.loadArtifactVersion("myApp", "user1", "session1", "artifact1", Integer.MAX_VALUE);
        assertNotNull(result);
        assertEquals(mockPart, result);
    }

	@Test
    @Tag("valid")
    void loadArtifactVersionWithSpecialCharactersInArtifactName() {
        when(artifactService.loadArtifact("myApp", "user1", "session1", "my-artifact_v2.0", Optional.of(1)))
                .thenReturn(Maybe.just(mockPart));
        Part result = artifactController.loadArtifactVersion("myApp", "user1", "session1", "my-artifact_v2.0", 1);
        assertNotNull(result);
        assertEquals(mockPart, result);
    }

	@Test
    @Tag("valid")
    void loadArtifactVersionPassesOptionalOfVersionIdToService() {
        when(artifactService.loadArtifact("myApp", "user1", "session1", "artifact1", Optional.of(7)))
                .thenReturn(Maybe.just(mockPart));
        artifactController.loadArtifactVersion("myApp", "user1", "session1", "artifact1", 7);
        verify(artifactService, times(1))
                .loadArtifact("myApp", "user1", "session1", "artifact1", Optional.of(7));
    }

	@Test
    @Tag("valid")
    void loadArtifactVersionWithWhitespaceInUserIdDelegatesToService() {
        when(artifactService.loadArtifact("myApp", " user 1 ", "session1", "artifact1", Optional.of(2)))
                .thenReturn(Maybe.just(mockPart));
        Part result = artifactController.loadArtifactVersion("myApp", " user 1 ", "session1", "artifact1", 2);
        assertNotNull(result);
        assertEquals(mockPart, result);
    }

	@Test
    @Tag("invalid")
    void loadArtifactVersionThrowsNotFoundWhenMaybeCompletesWithoutValue() {
        when(artifactService.loadArtifact("myApp", "user1", "session1", "artifact1", Optional.of(99)))
                .thenReturn(Maybe.empty());
        ResponseStatusException exception = assertThrows(ResponseStatusException.class, () ->
                artifactController.loadArtifactVersion("myApp", "user1", "session1", "artifact1", 99));
        assertEquals(HttpStatus.NOT_FOUND, exception.getStatusCode());
        assertEquals("Artifact version not found", exception.getReason());
    }

	@Test
    @Tag("boundary")
    void loadArtifactVersionWithMinIntegerVersionIdThrowsNotFound() {
        when(artifactService.loadArtifact("myApp", "user1", "session1", "artifact1", Optional.of(Integer.MIN_VALUE)))
                .thenReturn(Maybe.empty());
        ResponseStatusException exception = assertThrows(ResponseStatusException.class, () ->
                artifactController.loadArtifactVersion("myApp", "user1", "session1", "artifact1", Integer.MIN_VALUE));
        assertEquals(HttpStatus.NOT_FOUND, exception.getStatusCode());
    }

}