/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-dec-16-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=findAgent_fb90a0fcc1
ROOST_METHOD_SIG_HASH=findAgent_611fa42d7c

Scenario 1: Find Agent Returns Self When Name Matches

Details:
  TestName: findAgentReturnsSelfWhenNameMatches
  Description: This test verifies that the findAgent method returns the current agent instance when the provided name matches the agent's own name. This is the base case where the search immediately succeeds without needing to traverse sub-agents.
Execution:
  Arrange: Create a BaseAgent instance with a specific name (e.g., "TestAgent"). Ensure the agent has no sub-agents or has sub-agents with different names.
  Act: Call the findAgent method with the same name as the agent's name.
  Assert: Verify that the returned BaseAgent instance is the same as the current agent instance (using reference equality or equals method).
Validation:
  The assertion verifies that when searching for an agent by its own name, the method correctly identifies and returns itself without unnecessary traversal of the agent tree. This is critical for efficient agent lookup and ensures the method handles the simplest case correctly. This behavior is fundamental for agent identification in the agent tree structure.

Scenario 2: Find Agent Returns Direct Sub-Agent When Name Matches

Details:
  TestName: findAgentReturnsDirectSubAgentWhenNameMatches
  Description: This test checks that the findAgent method correctly identifies and returns a direct sub-agent when the provided name matches one of the immediate children in the subAgents list.
Execution:
  Arrange: Create a parent BaseAgent with a specific name (e.g., "ParentAgent"). Create one or more sub-agents and add them to the parent's subAgents list. One sub-agent should have a specific name (e.g., "ChildAgent").
  Act: Call findAgent on the parent agent with the name of the direct sub-agent.
  Assert: Verify that the returned BaseAgent is the expected sub-agent instance and that its name matches the search parameter.
Validation:
  This assertion confirms that the method correctly delegates to findSubAgent and successfully locates direct children in the agent hierarchy. This is essential for navigating one level down in the agent tree and ensures proper parent-child relationship handling.

Scenario 3: Find Agent Returns Nested Sub-Agent When Name Matches

Details:
  TestName: findAgentReturnsNestedSubAgentWhenNameMatches
  Description: This test validates that the findAgent method can locate an agent that is nested multiple levels deep in the agent hierarchy, not just direct children.
Execution:
  Arrange: Create a multi-level agent hierarchy: a root agent with a sub-agent, and that sub-agent has its own sub-agent (grandchild). Give the grandchild a unique name (e.g., "GrandchildAgent").
  Act: Call findAgent on the root agent with the name of the deeply nested agent.
  Assert: Verify that the returned BaseAgent is the grandchild agent instance with the correct name.
Validation:
  This assertion ensures that the recursive nature of findSubAgent works correctly, allowing the method to traverse multiple levels of the agent tree. This is crucial for complex agent hierarchies where agents may be nested several levels deep, demonstrating the method's ability to perform deep searches.

Scenario 4: Find Agent Returns Null When Name Not Found

Details:
  TestName: findAgentReturnsNullWhenNameNotFound
  Description: This test verifies that the findAgent method returns null when the provided name does not match the current agent or any of its sub-agents at any level.
Execution:
  Arrange: Create a BaseAgent with a specific name and optionally some sub-agents with different names. Prepare a search name that does not exist in the agent tree (e.g., "NonExistentAgent").
  Act: Call findAgent with the non-existent agent name.
  Assert: Verify that the returned value is null.
Validation:
  This assertion confirms proper error handling when an agent cannot be found. Returning null is the expected behavior as indicated by the @Nullable annotation on findSubAgent. This is important for callers to handle cases where an agent lookup fails, allowing them to implement appropriate fallback logic.

Scenario 5: Find Agent With Null Name Parameter

Details:
  TestName: findAgentWithNullNameParameter
  Description: This test examines the behavior of findAgent when a null value is passed as the name parameter, which is an edge case that should be handled gracefully.
Execution:
  Arrange: Create a BaseAgent instance with a valid name.
  Act: Call findAgent with null as the name parameter.
  Assert: Verify that the method returns null or throws a NullPointerException, depending on the expected behavior (based on the implementation, it will likely throw NPE when calling this.name().equals(name)).
Validation:
  This test ensures that the method handles invalid input appropriately. Since the code uses equals() on the agent's name with the parameter, passing null will cause a NullPointerException. This test documents the expected behavior for invalid input and helps identify whether additional null-checking is needed.

Scenario 6: Find Agent With Empty String Name

Details:
  TestName: findAgentWithEmptyStringName
  Description: This test verifies the behavior when an empty string is provided as the search name, which is a valid but edge-case input.
Execution:
  Arrange: Create a BaseAgent with a non-empty name (e.g., "TestAgent"). Optionally create sub-agents, none of which have an empty string as their name.
  Act: Call findAgent with an empty string ("") as the name parameter.
  Assert: Verify that the method returns null since no agent has an empty string as its name.
Validation:
  This assertion ensures that the method correctly handles edge-case string values. Empty strings are valid String objects but unlikely to be valid agent names. This test confirms that the equality check works correctly for such edge cases and that the method doesn't incorrectly match or fail unexpectedly.

Scenario 7: Find Agent In Tree With No Sub-Agents

Details:
  TestName: findAgentInTreeWithNoSubAgents
  Description: This test validates the behavior when searching for an agent in a tree where the current agent has an empty subAgents list.
Execution:
  Arrange: Create a BaseAgent with a specific name and an empty subAgents list (or null, which becomes an empty ImmutableList in the constructor).
  Act: Call findAgent with a name that doesn't match the current agent's name.
  Assert: Verify that the method returns null.
Validation:
  This assertion confirms that the method handles the case where there are no sub-agents to search through. The findSubAgent method should iterate over an empty list and return null. This is important for leaf nodes in the agent tree and ensures the method doesn't fail when there are no children to search.

Scenario 8: Find Agent With Multiple Sub-Agents At Same Level

Details:
  TestName: findAgentWithMultipleSubAgentsAtSameLevel
  Description: This test verifies that findAgent correctly searches through multiple sub-agents at the same level and returns the correct one when a match is found.
Execution:
  Arrange: Create a parent BaseAgent with multiple sub-agents (e.g., 3-5 sub-agents) at the same level, each with unique names. One of these sub-agents should have a specific target name.
  Act: Call findAgent on the parent with the name of one of the sub-agents (not the first one in the list).
  Assert: Verify that the returned BaseAgent is the correct sub-agent with the matching name.
Validation:
  This assertion ensures that the method correctly iterates through all sub-agents and doesn't stop prematurely or skip any agents. This is important for agent trees with multiple branches at the same level, confirming that the search algorithm examines all siblings before moving to deeper levels.

Scenario 9: Find Agent Returns First Match In Depth-First Search

Details:
  TestName: findAgentReturnsFirstMatchInDepthFirstSearch
  Description: This test validates that when multiple agents in the tree have the same name (which shouldn't happen according to the uniqueness requirement, but tests the actual behavior), the method returns the first match found in a depth-first search order.
Execution:
  Arrange: Create an agent hierarchy where multiple agents have the same name (violating the uniqueness constraint). Structure the tree so that one matching agent is at a different level than another.
  Act: Call findAgent with the duplicate name.
  Assert: Verify which agent is returned based on the depth-first search order (current agent first, then first sub-agent and its descendants, then second sub-agent and its descendants, etc.).
Validation:
  This assertion documents the actual search behavior of the method, confirming it follows a depth-first search pattern. While agent names should be unique, this test ensures predictable behavior even when that constraint is violated, which is useful for debugging and understanding the search algorithm.

Scenario 10: Find Agent When Current Agent Name Equals Search Name Ignoring Sub-Agents

Details:
  TestName: findAgentWhenCurrentAgentNameEqualsSearchNameIgnoringSubAgents
  Description: This test confirms that when the current agent's name matches the search name, the method returns immediately without searching sub-agents, even if sub-agents exist.
Execution:
  Arrange: Create a BaseAgent with a specific name (e.g., "TargetAgent") and add sub-agents to it. Ensure at least one sub-agent exists.
  Act: Call findAgent with the current agent's name.
  Assert: Verify that the returned agent is the current agent instance and that the findSubAgent method is not invoked (this can be verified through code coverage or by ensuring the method returns quickly).
Validation:
  This assertion verifies the short-circuit behavior of the method, ensuring it doesn't perform unnecessary searches when the match is found immediately. This is important for performance optimization in large agent trees and confirms that the method follows the most efficient search path.

Scenario 11: Find Agent With Case-Sensitive Name Matching

Details:
  TestName: findAgentWithCaseSensitiveNameMatching
  Description: This test verifies that the name matching in findAgent is case-sensitive, meaning "Agent" and "agent" are treated as different names.
Execution:
  Arrange: Create a BaseAgent with a name using specific casing (e.g., "TestAgent"). Create sub-agents with names that differ only in case (e.g., "testagent", "TESTAGENT").
  Act: Call findAgent with a name that differs from the agent's name only in case (e.g., search for "testagent" when the agent is named "TestAgent").
  Assert: Verify that the method returns null or a different agent, confirming that the match is case-sensitive.
Validation:
  This assertion confirms that the equals() method is used for string comparison, which is case-sensitive in Java. This is important for ensuring that agent names are matched exactly as specified, preventing accidental matches due to case differences. This behavior is critical for maintaining the uniqueness constraint of agent names.

Scenario 12: Find Agent In Complex Multi-Level Hierarchy

Details:
  TestName: findAgentInComplexMultiLevelHierarchy
  Description: This test validates the findAgent method's ability to navigate and search through a complex, multi-level agent hierarchy with multiple branches and levels.
Execution:
  Arrange: Create a complex agent tree with at least 3-4 levels of depth and multiple branches at each level. Place a target agent at a specific location in this hierarchy (e.g., third level, second branch).
  Act: Call findAgent from the root agent with the name of the deeply nested target agent.
  Assert: Verify that the correct agent is returned and that its name matches the search parameter.
Validation:
  This assertion ensures that the recursive search algorithm works correctly in realistic, complex scenarios. This test is important for validating the method's robustness in production-like agent hierarchies where multiple levels and branches are common, confirming that the depth-first search traverses the entire tree correctly.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.common.collect.ImmutableList;
import io.reactivex.rxjava3.core.Flowable;
import java.util.List;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.MockitoAnnotations;

class BaseAgentFindAgentTest {

	private TestBaseAgent testAgent;

	private TestBaseAgent subAgent1;

	private TestBaseAgent subAgent2;

	private TestBaseAgent grandchildAgent;

	@BeforeEach
	void setUp() {
		MockitoAnnotations.openMocks(this);
	}

	@Test
	@Tag("valid")
	void findAgentReturnsSelfWhenNameMatches() {
		testAgent = new TestBaseAgent("TestAgent", "Test Description", ImmutableList.of(), null, null);

		BaseAgent result = testAgent.findAgent("TestAgent");

		assertNotNull(result);
		assertSame(testAgent, result);
		assertEquals("TestAgent", result.name());
	}

	@Test
	@Tag("valid")
	void findAgentReturnsDirectSubAgentWhenNameMatches() {
		subAgent1 = new TestBaseAgent("ChildAgent", "Child Description", ImmutableList.of(), null, null);
		subAgent2 = new TestBaseAgent("AnotherChild", "Another Description", ImmutableList.of(), null, null);
		testAgent = new TestBaseAgent("ParentAgent", "Parent Description", ImmutableList.of(subAgent1, subAgent2), null,
				null);

		BaseAgent result = testAgent.findAgent("ChildAgent");

		assertNotNull(result);
		assertSame(subAgent1, result);
		assertEquals("ChildAgent", result.name());
	}

	@Test
	@Tag("valid")
	void findAgentReturnsNestedSubAgentWhenNameMatches() {
		grandchildAgent = new TestBaseAgent("GrandchildAgent", "Grandchild Description", ImmutableList.of(), null,
				null);
		subAgent1 = new TestBaseAgent("ChildAgent", "Child Description", ImmutableList.of(grandchildAgent), null, null);
		testAgent = new TestBaseAgent("RootAgent", "Root Description", ImmutableList.of(subAgent1), null, null);

		BaseAgent result = testAgent.findAgent("GrandchildAgent");

		assertNotNull(result);
		assertSame(grandchildAgent, result);
		assertEquals("GrandchildAgent", result.name());
	}

	@Test
	@Tag("valid")
	void findAgentReturnsNullWhenNameNotFound() {
		subAgent1 = new TestBaseAgent("ChildAgent", "Child Description", ImmutableList.of(), null, null);
		testAgent = new TestBaseAgent("ParentAgent", "Parent Description", ImmutableList.of(subAgent1), null, null);

		BaseAgent result = testAgent.findAgent("NonExistentAgent");

		assertNull(result);
	}

	@Test
	@Tag("invalid")
	void findAgentWithNullNameParameter() {
		testAgent = new TestBaseAgent("TestAgent", "Test Description", ImmutableList.of(), null, null);

		assertThrows(NullPointerException.class, () -> {
			testAgent.findAgent(null);
		});
	}

	@Test
	@Tag("boundary")
	void findAgentWithEmptyStringName() {
		testAgent = new TestBaseAgent("TestAgent", "Test Description", ImmutableList.of(), null, null);
		subAgent1 = new TestBaseAgent("ChildAgent", "Child Description", ImmutableList.of(), null, null);
		testAgent = new TestBaseAgent("ParentAgent", "Parent Description", ImmutableList.of(subAgent1), null, null);

		BaseAgent result = testAgent.findAgent("");

		assertNull(result);
	}

	@Test
	@Tag("boundary")
	void findAgentInTreeWithNoSubAgents() {
		testAgent = new TestBaseAgent("TestAgent", "Test Description", ImmutableList.of(), null, null);

		BaseAgent result = testAgent.findAgent("NonExistentAgent");

		assertNull(result);
	}

	@Test
	@Tag("valid")
	void findAgentWithMultipleSubAgentsAtSameLevel() {
		subAgent1 = new TestBaseAgent("Child1", "Child1 Description", ImmutableList.of(), null, null);
		subAgent2 = new TestBaseAgent("Child2", "Child2 Description", ImmutableList.of(), null, null);
		TestBaseAgent subAgent3 = new TestBaseAgent("Child3", "Child3 Description", ImmutableList.of(), null, null);
		TestBaseAgent subAgent4 = new TestBaseAgent("TargetChild", "Target Description", ImmutableList.of(), null,
				null);
		TestBaseAgent subAgent5 = new TestBaseAgent("Child5", "Child5 Description", ImmutableList.of(), null, null);

		testAgent = new TestBaseAgent("ParentAgent", "Parent Description",
				ImmutableList.of(subAgent1, subAgent2, subAgent3, subAgent4, subAgent5), null, null);

		BaseAgent result = testAgent.findAgent("TargetChild");

		assertNotNull(result);
		assertSame(subAgent4, result);
		assertEquals("TargetChild", result.name());
	}

	@Test
	@Tag("valid")
	void findAgentReturnsFirstMatchInDepthFirstSearch() {
		TestBaseAgent duplicateAgent1 = new TestBaseAgent("DuplicateName", "First Duplicate", ImmutableList.of(), null,
				null);
		TestBaseAgent duplicateAgent2 = new TestBaseAgent("DuplicateName", "Second Duplicate", ImmutableList.of(), null,
				null);

		subAgent1 = new TestBaseAgent("Child1", "Child1 Description", ImmutableList.of(duplicateAgent1), null, null);
		subAgent2 = new TestBaseAgent("Child2", "Child2 Description", ImmutableList.of(duplicateAgent2), null, null);

		testAgent = new TestBaseAgent("RootAgent", "Root Description", ImmutableList.of(subAgent1, subAgent2), null,
				null);

		BaseAgent result = testAgent.findAgent("DuplicateName");

		assertNotNull(result);
		assertSame(duplicateAgent1, result);
		assertEquals("First Duplicate", result.description());
	}

	@Test
	@Tag("valid")
	void findAgentWhenCurrentAgentNameEqualsSearchNameIgnoringSubAgents() {
		subAgent1 = new TestBaseAgent("ChildAgent", "Child Description", ImmutableList.of(), null, null);
		testAgent = new TestBaseAgent("TargetAgent", "Target Description", ImmutableList.of(subAgent1), null, null);

		BaseAgent result = testAgent.findAgent("TargetAgent");

		assertNotNull(result);
		assertSame(testAgent, result);
		assertEquals("TargetAgent", result.name());
	}

	@Test
	@Tag("valid")
	void findAgentWithCaseSensitiveNameMatching() {
		subAgent1 = new TestBaseAgent("testagent", "Lowercase Description", ImmutableList.of(), null, null);
		subAgent2 = new TestBaseAgent("TESTAGENT", "Uppercase Description", ImmutableList.of(), null, null);
		testAgent = new TestBaseAgent("TestAgent", "Mixed Case Description", ImmutableList.of(subAgent1, subAgent2),
				null, null);

		BaseAgent result = testAgent.findAgent("testagent");

		assertNotNull(result);
		assertSame(subAgent1, result);
		assertEquals("testagent", result.name());

		BaseAgent resultUppercase = testAgent.findAgent("TESTAGENT");
		assertNotNull(resultUppercase);
		assertSame(subAgent2, resultUppercase);

		BaseAgent resultMixed = testAgent.findAgent("TestAgent");
		assertNotNull(resultMixed);
		assertSame(testAgent, resultMixed);
	}

	@Test
	@Tag("integration")
	void findAgentInComplexMultiLevelHierarchy() {
		TestBaseAgent level3Agent1 = new TestBaseAgent("Level3-1", "Level 3 Agent 1", ImmutableList.of(), null, null);
		TestBaseAgent level3Agent2 = new TestBaseAgent("TargetAgent", "Target at Level 3", ImmutableList.of(), null,
				null);
		TestBaseAgent level3Agent3 = new TestBaseAgent("Level3-3", "Level 3 Agent 3", ImmutableList.of(), null, null);

		TestBaseAgent level2Agent1 = new TestBaseAgent("Level2-1", "Level 2 Agent 1", ImmutableList.of(level3Agent1),
				null, null);
		TestBaseAgent level2Agent2 = new TestBaseAgent("Level2-2", "Level 2 Agent 2",
				ImmutableList.of(level3Agent2, level3Agent3), null, null);

		TestBaseAgent level1Agent1 = new TestBaseAgent("Level1-1", "Level 1 Agent 1", ImmutableList.of(level2Agent1),
				null, null);
		TestBaseAgent level1Agent2 = new TestBaseAgent("Level1-2", "Level 1 Agent 2", ImmutableList.of(level2Agent2),
				null, null);

		testAgent = new TestBaseAgent("RootAgent", "Root Agent", ImmutableList.of(level1Agent1, level1Agent2), null,
				null);

		BaseAgent result = testAgent.findAgent("TargetAgent");

		assertNotNull(result);
		assertSame(level3Agent2, result);
		assertEquals("TargetAgent", result.name());
		assertEquals("Target at Level 3", result.description());
	}

	private static class TestBaseAgent extends BaseAgent {

		public TestBaseAgent(String name, String description, List<? extends BaseAgent> subAgents,
				List<? extends Callbacks.BeforeAgentCallback> beforeAgentCallback,
				List<? extends Callbacks.AfterAgentCallback> afterAgentCallback) {
			super(name, description, subAgents, beforeAgentCallback, afterAgentCallback);
		}

		@Override
		protected Flowable<com.google.adk.events.Event> runAsyncImpl(InvocationContext invocationContext) {
			return Flowable.empty();
		}

		@Override
		protected Flowable<com.google.adk.events.Event> runLiveImpl(InvocationContext invocationContext) {
			return Flowable.empty();
		}

	}

}
