/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-dec-16-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=name_c217d34ca2
ROOST_METHOD_SIG_HASH=name_998a4c20c1

Scenario 1: Return Agent Name When Name Is Set

Details:
  TestName: nameReturnsAgentNameWhenNameIsSet
  Description: This test verifies that the name() method correctly returns the agent's name when a valid name has been set during agent construction. It ensures the basic getter functionality works as expected for a standard use case.

Execution:
  Arrange: Create a BaseAgent instance (using a concrete implementation) with a specific name value such as "TestAgent".
  Act: Invoke the name() method on the created agent instance.
  Assert: Use assertEquals to verify that the returned value matches the expected name "TestAgent".

Validation:
  The assertion verifies that the name() method returns the exact name that was provided during agent construction. This is critical because the agent's name serves as a unique identifier within the agent tree, and accurate retrieval is essential for agent lookup, delegation, and system decision-making processes.

---

Scenario 2: Return Agent Name When Name Contains Special Characters

Details:
  TestName: nameReturnsAgentNameWithSpecialCharacters
  Description: This test checks that the name() method correctly returns agent names containing special characters such as hyphens, underscores, or dots. It validates that the method handles non-alphanumeric characters without modification or corruption.

Execution:
  Arrange: Create a BaseAgent instance with a name containing special characters, such as "test-agent_v1.0".
  Act: Call the name() method on the agent instance.
  Assert: Use assertEquals to confirm the returned name exactly matches "test-agent_v1.0".

Validation:
  This test ensures that special characters in agent names are preserved correctly. Since agent names must be unique identifiers and may follow various naming conventions (kebab-case, snake_case, versioning), it's important that the name() method returns the exact string without any transformation or sanitization.

---

Scenario 3: Return Agent Name When Name Is Empty String

Details:
  TestName: nameReturnsEmptyStringWhenNameIsEmpty
  Description: This test verifies the behavior of the name() method when the agent is constructed with an empty string as the name. It ensures the method returns the empty string without throwing exceptions or returning null.

Execution:
  Arrange: Create a BaseAgent instance with an empty string "" as the name parameter.
  Act: Invoke the name() method on the agent instance.
  Assert: Use assertEquals to verify the returned value is an empty string "".

Validation:
  While an empty name may not be a valid business case (as names should be unique identifiers), this test validates that the method handles edge cases gracefully without runtime errors. It confirms that the method is a simple getter that returns the field value as-is, which is important for defensive programming and understanding method behavior boundaries.

---

Scenario 4: Return Agent Name When Name Contains Whitespace

Details:
  TestName: nameReturnsAgentNameWithWhitespace
  Description: This test validates that the name() method correctly returns agent names that contain whitespace characters, including leading, trailing, or embedded spaces. It ensures whitespace is preserved in the returned value.

Execution:
  Arrange: Create a BaseAgent instance with a name containing whitespace, such as "  Agent With Spaces  ".
  Act: Call the name() method on the agent instance.
  Assert: Use assertEquals to verify the returned name is exactly "  Agent With Spaces  " with all whitespace preserved.

Validation:
  This test confirms that the name() method does not perform any trimming or whitespace normalization. While whitespace in agent names may indicate a data quality issue, the getter method should return the exact value stored in the field, allowing calling code to handle validation and normalization as needed.

---

Scenario 5: Return Agent Name When Name Is Very Long String

Details:
  TestName: nameReturnsVeryLongAgentName
  Description: This test checks that the name() method can handle and return very long agent names without truncation or performance issues. It validates the method's behavior with boundary-case string lengths.

Execution:
  Arrange: Create a BaseAgent instance with a very long name (e.g., 1000 characters) by generating a string with repeated characters or a long descriptive name.
  Act: Invoke the name() method on the agent instance.
  Assert: Use assertEquals to verify the returned string has the expected length and content matches the original long name.

Validation:
  This test ensures that the name() method handles large strings correctly without memory issues, truncation, or performance degradation. Since the name field is a String and Java strings can be quite large, this validates that the simple getter pattern works correctly even with extreme values.

---

Scenario 6: Return Agent Name When Name Contains Unicode Characters

Details:
  TestName: nameReturnsAgentNameWithUnicodeCharacters
  Description: This test verifies that the name() method correctly returns agent names containing Unicode characters from various languages and symbol sets, such as emoji, Chinese characters, or Arabic script.

Execution:
  Arrange: Create a BaseAgent instance with a name containing Unicode characters, such as "Agent🤖测试وكيل".
  Act: Call the name() method on the agent instance.
  Assert: Use assertEquals to confirm the returned name exactly matches "Agent🤖测试وكيل" with all Unicode characters intact.

Validation:
  This test validates that the name() method properly handles internationalization and Unicode support. In a global application, agent names might contain characters from various languages, and the method must preserve these characters correctly to maintain system integrity and support diverse user bases.

---

Scenario 7: Return Same Name On Multiple Invocations

Details:
  TestName: nameReturnsSameValueOnMultipleInvocations
  Description: This test ensures that the name() method returns consistent results when called multiple times on the same agent instance. It validates the immutability and consistency of the returned value.

Execution:
  Arrange: Create a BaseAgent instance with a specific name "ConsistentAgent".
  Act: Call the name() method multiple times (e.g., three times) and store each result.
  Assert: Use assertEquals to verify all returned values are identical and equal to "ConsistentAgent".

Validation:
  This test confirms that the name() method is idempotent and that the name field is effectively immutable (as indicated by the final modifier). This is crucial for thread safety and predictable behavior, especially since agent names are used as unique identifiers throughout the agent tree and should never change during the agent's lifetime.

---

Scenario 8: Return Agent Name When Name Contains Numeric Characters

Details:
  TestName: nameReturnsAgentNameWithNumericCharacters
  Description: This test validates that the name() method correctly returns agent names that consist entirely of or contain numeric characters, ensuring numbers are treated as valid name components.

Execution:
  Arrange: Create a BaseAgent instance with a name containing numbers, such as "Agent123" or "12345".
  Act: Invoke the name() method on the agent instance.
  Assert: Use assertEquals to verify the returned name matches the expected numeric-containing string.

Validation:
  This test ensures that numeric characters in agent names are handled correctly. Agent names might include version numbers, identifiers, or sequential numbering schemes, so the method must return these values accurately without type conversion or formatting changes.

---

Scenario 9: Return Agent Name When Name Is Single Character

Details:
  TestName: nameReturnsSingleCharacterAgentName
  Description: This test checks that the name() method correctly handles and returns agent names consisting of a single character, validating the minimum boundary case for string length.

Execution:
  Arrange: Create a BaseAgent instance with a single-character name such as "A".
  Act: Call the name() method on the agent instance.
  Assert: Use assertEquals to confirm the returned value is "A".

Validation:
  This test validates the method's behavior with minimal string length. While single-character names may not be practical for real-world use, testing this boundary case ensures the method has no hidden length requirements or assumptions and works correctly with any valid string length.

---

Scenario 10: Return Agent Name Independently Of Other Field Values

Details:
  TestName: nameReturnsCorrectValueIndependentOfOtherFields
  Description: This test verifies that the name() method returns the correct name value regardless of the values of other fields in the BaseAgent class, such as description, subAgents, or callbacks.

Execution:
  Arrange: Create multiple BaseAgent instances with the same name but different values for description, subAgents, beforeAgentCallback, and afterAgentCallback fields.
  Act: Call the name() method on each agent instance.
  Assert: Use assertEquals to verify all instances return the same name value despite having different field values.

Validation:
  This test confirms that the name() method is properly isolated and only returns the name field without being influenced by other instance variables. This validates proper encapsulation and ensures that the method's behavior is predictable and depends solely on the name field value.

---

Scenario 11: Return Agent Name After Parent Agent Is Set

Details:
  TestName: nameReturnsCorrectValueAfterParentAgentIsSet
  Description: This test ensures that the name() method continues to return the correct name value even after the parentAgent field has been modified through the parentAgent(BaseAgent) method.

Execution:
  Arrange: Create two BaseAgent instances, one as a child agent with name "ChildAgent" and another as a parent agent. Set the parent using the parentAgent() method.
  Act: Call the name() method on the child agent after setting its parent.
  Assert: Use assertEquals to verify the returned name is still "ChildAgent".

Validation:
  This test validates that the name field remains immutable and unaffected by changes to other mutable fields like parentAgent. Since the name is declared as final, this test confirms that the method's behavior is consistent throughout the agent's lifecycle, even as the agent tree structure changes.

---

Scenario 12: Return Agent Name For Root Agent

Details:
  TestName: nameReturnsCorrectValueForRootAgent
  Description: This test verifies that the name() method works correctly for a root agent (an agent with no parent), ensuring the method doesn't have any dependencies on the agent's position in the hierarchy.

Execution:
  Arrange: Create a BaseAgent instance with name "RootAgent" and no parent agent (parentAgent is null).
  Act: Invoke the name() method on the root agent instance.
  Assert: Use assertEquals to confirm the returned value is "RootAgent".

Validation:
  This test ensures that the name() method functions correctly regardless of whether the agent is a root agent or part of a hierarchy. Since the method is a simple getter for the name field, it should work identically for all agents, but this test explicitly validates the root agent case to ensure no hidden dependencies exist.

---

Scenario 13: Return Agent Name For Sub Agent

Details:
  TestName: nameReturnsCorrectValueForSubAgent
  Description: This test validates that the name() method returns the correct name for an agent that is a sub-agent of another agent, confirming the method works correctly within an agent hierarchy.

Execution:
  Arrange: Create a parent BaseAgent instance with a sub-agent that has the name "SubAgent". Access the sub-agent from the parent's subAgents list.
  Act: Call the name() method on the sub-agent instance.
  Assert: Use assertEquals to verify the returned name is "SubAgent".

Validation:
  This test confirms that sub-agents maintain their own name identity and that the name() method returns the correct value regardless of the agent's position in the hierarchy. This is important for agent lookup operations using methods like findAgent() and findSubAgent(), which rely on accurate name retrieval.

---

Scenario 14: Return Agent Name When Name Contains Reserved Keywords

Details:
  TestName: nameReturnsAgentNameWithReservedKeywords
  Description: This test checks that the name() method correctly returns agent names that match Java reserved keywords or common programming terms, ensuring no conflicts or special handling occurs.

Execution:
  Arrange: Create a BaseAgent instance with a name that is a reserved keyword, such as "class", "interface", or "return".
  Act: Invoke the name() method on the agent instance.
  Assert: Use assertEquals to verify the returned name matches the reserved keyword exactly.

Validation:
  This test validates that the name field can store any string value, including reserved keywords, since it's just a String field. While using reserved keywords as agent names might be poor practice, the method should handle them correctly without any special processing or errors.

---

Scenario 15: Return Agent Name Maintains Reference Equality

Details:
  TestName: nameReturnsSameStringReference
  Description: This test verifies whether the name() method returns the same String object reference on multiple calls, or if it creates new String instances. This validates the method's memory efficiency.

Execution:
  Arrange: Create a BaseAgent instance with a specific name.
  Act: Call the name() method twice and store both references.
  Assert: Use assertSame to check if both references point to the same String object in memory.

Validation:
  This test examines the implementation detail of whether the method returns the same String reference or creates new instances. Since the name field is final and String is immutable in Java, returning the same reference is expected and more memory-efficient. This test validates optimal implementation practices.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.agents.Callbacks.AfterAgentCallback;
import com.google.adk.agents.Callbacks.BeforeAgentCallback;
import com.google.adk.events.Event;
import com.google.common.collect.ImmutableList;
import io.reactivex.rxjava3.core.Flowable;
import java.util.List;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

class BaseAgentNameTest {

	private static class TestAgent extends BaseAgent {

		public TestAgent(String name, String description, List<? extends BaseAgent> subAgents,
				List<? extends BeforeAgentCallback> beforeAgentCallback,
				List<? extends AfterAgentCallback> afterAgentCallback) {
			super(name, description, subAgents, beforeAgentCallback, afterAgentCallback);
		}

		@Override
		protected Flowable<Event> runAsyncImpl(InvocationContext invocationContext) {
			return Flowable.empty();
		}

		@Override
		protected Flowable<Event> runLiveImpl(InvocationContext invocationContext) {
			return Flowable.empty();
		}

	}

	@Mock
	private BeforeAgentCallback mockBeforeCallback;

	@Mock
	private AfterAgentCallback mockAfterCallback;

	@BeforeEach
	void setUp() {
		MockitoAnnotations.openMocks(this);
	}

	@Test
	@Tag("valid")
	void nameReturnsAgentNameWhenNameIsSet() {
		TestAgent agent = new TestAgent("TestAgent", "Test description", null, null, null);

		String result = agent.name();

		assertEquals("TestAgent", result);
	}

	@Test
	@Tag("valid")
	void nameReturnsAgentNameWithSpecialCharacters() {
		TestAgent agent = new TestAgent("test-agent_v1.0", "Test description", null, null, null);

		String result = agent.name();

		assertEquals("test-agent_v1.0", result);
	}

	@Test
	@Tag("boundary")
	void nameReturnsEmptyStringWhenNameIsEmpty() {
		TestAgent agent = new TestAgent("", "Test description", null, null, null);

		String result = agent.name();

		assertEquals("", result);
	}

	@Test
	@Tag("valid")
	void nameReturnsAgentNameWithWhitespace() {
		TestAgent agent = new TestAgent("  Agent With Spaces  ", "Test description", null, null, null);

		String result = agent.name();

		assertEquals("  Agent With Spaces  ", result);
	}

	@Test
	@Tag("boundary")
	void nameReturnsVeryLongAgentName() {
		String longName = "A".repeat(1000);
		TestAgent agent = new TestAgent(longName, "Test description", null, null, null);

		String result = agent.name();

		assertEquals(1000, result.length());
		assertEquals(longName, result);
	}

	@Test
	@Tag("valid")
	void nameReturnsAgentNameWithUnicodeCharacters() {
		TestAgent agent = new TestAgent("Agent🤖测试وكيل", "Test description", null, null, null);

		String result = agent.name();

		assertEquals("Agent🤖测试وكيل", result);
	}

	@Test
	@Tag("valid")
	void nameReturnsSameValueOnMultipleInvocations() {
		TestAgent agent = new TestAgent("ConsistentAgent", "Test description", null, null, null);

		String result1 = agent.name();
		String result2 = agent.name();
		String result3 = agent.name();

		assertEquals("ConsistentAgent", result1);
		assertEquals("ConsistentAgent", result2);
		assertEquals("ConsistentAgent", result3);
		assertEquals(result1, result2);
		assertEquals(result2, result3);
	}

	@Test
	@Tag("valid")
	void nameReturnsAgentNameWithNumericCharacters() {
		TestAgent agent = new TestAgent("Agent123", "Test description", null, null, null);

		String result = agent.name();

		assertEquals("Agent123", result);
	}

	@Test
	@Tag("boundary")
	void nameReturnsSingleCharacterAgentName() {
		TestAgent agent = new TestAgent("A", "Test description", null, null, null);

		String result = agent.name();

		assertEquals("A", result);
	}

	@Test
	@Tag("valid")
	void nameReturnsCorrectValueIndependentOfOtherFields() {
		TestAgent agent1 = new TestAgent("SameName", "Description 1", null, null, null);
		TestAgent agent2 = new TestAgent("SameName", "Description 2", ImmutableList.of(),
				ImmutableList.of(mockBeforeCallback), null);
		TestAgent agent3 = new TestAgent("SameName", "Description 3", null, null, ImmutableList.of(mockAfterCallback));

		String result1 = agent1.name();
		String result2 = agent2.name();
		String result3 = agent3.name();

		assertEquals("SameName", result1);
		assertEquals("SameName", result2);
		assertEquals("SameName", result3);
	}

	@Test
	@Tag("valid")
	void nameReturnsCorrectValueAfterParentAgentIsSet() {
		TestAgent childAgent = new TestAgent("ChildAgent", "Child description", null, null, null);
		TestAgent parentAgent = new TestAgent("ParentAgent", "Parent description", null, null, null);

		childAgent.parentAgent(parentAgent);
		String result = childAgent.name();

		assertEquals("ChildAgent", result);
	}

	@Test
	@Tag("valid")
	void nameReturnsCorrectValueForRootAgent() {
		TestAgent rootAgent = new TestAgent("RootAgent", "Root description", null, null, null);

		String result = rootAgent.name();

		assertEquals("RootAgent", result);
		assertNull(rootAgent.parentAgent());
	}

	@Test
	@Tag("valid")
	void nameReturnsCorrectValueForSubAgent() {
		TestAgent subAgent = new TestAgent("SubAgent", "Sub description", null, null, null);
		TestAgent parentAgent = new TestAgent("ParentAgent", "Parent description", ImmutableList.of(subAgent), null,
				null);

		BaseAgent retrievedSubAgent = parentAgent.subAgents().get(0);
		String result = retrievedSubAgent.name();

		assertEquals("SubAgent", result);
	}

	@Test
	@Tag("valid")
	void nameReturnsAgentNameWithReservedKeywords() {
		TestAgent agent = new TestAgent("class", "Test description", null, null, null);

		String result = agent.name();

		assertEquals("class", result);
	}

	@Test
	@Tag("valid")
	void nameReturnsSameStringReference() {
		TestAgent agent = new TestAgent("ReferenceTest", "Test description", null, null, null);

		String result1 = agent.name();
		String result2 = agent.name();

		assertSame(result1, result2);
	}

	@Test
	@Tag("valid")
	void nameReturnsCorrectValueWithAllNumericCharacters() {
		TestAgent agent = new TestAgent("12345", "Test description", null, null, null);

		String result = agent.name();

		assertEquals("12345", result);
	}

	@Test
	@Tag("valid")
	void nameReturnsCorrectValueWithMixedCasing() {
		TestAgent agent = new TestAgent("MixedCaseAgent", "Test description", null, null, null);

		String result = agent.name();

		assertEquals("MixedCaseAgent", result);
	}

	@Test
	@Tag("valid")
	void nameReturnsCorrectValueAfterMultipleParentChanges() {
		TestAgent childAgent = new TestAgent("ChildAgent", "Child description", null, null, null);
		TestAgent parent1 = new TestAgent("Parent1", "Parent 1 description", null, null, null);
		TestAgent parent2 = new TestAgent("Parent2", "Parent 2 description", null, null, null);

		childAgent.parentAgent(parent1);
		childAgent.parentAgent(parent2);
		String result = childAgent.name();

		assertEquals("ChildAgent", result);
	}

	@Test
	@Tag("valid")
	void nameReturnsCorrectValueInAgentHierarchy() {
		TestAgent grandChild = new TestAgent("GrandChild", "Grand child description", null, null, null);
		TestAgent child = new TestAgent("Child", "Child description", ImmutableList.of(grandChild), null, null);
		TestAgent root = new TestAgent("Root", "Root description", ImmutableList.of(child), null, null);

		assertEquals("Root", root.name());
		assertEquals("Child", child.name());
		assertEquals("GrandChild", grandChild.name());
	}

	@Test
	@Tag("valid")
	void nameReturnsCorrectValueWithCallbacks() {
		TestAgent agent = new TestAgent("CallbackAgent", "Test description", null, ImmutableList.of(mockBeforeCallback),
				ImmutableList.of(mockAfterCallback));

		String result = agent.name();

		assertEquals("CallbackAgent", result);
	}

}
