/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-dec-16-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=parentAgent_17ca5f4e06
ROOST_METHOD_SIG_HASH=parentAgent_601bf13912

Scenario 1: Return Parent Agent When Parent Is Set

Details:
  TestName: parentAgentReturnsSetParentAgent
  Description: This test verifies that the parentAgent() method correctly returns the parent agent when a parent has been explicitly set for the agent. This tests the basic getter functionality of the method.
Execution:
  Arrange: Create two BaseAgent instances (a parent agent and a child agent). Set the parent agent for the child agent using the protected parentAgent(BaseAgent) setter method.
  Act: Call the parentAgent() method on the child agent.
  Assert: Assert that the returned BaseAgent instance is the same as the parent agent that was set.
Validation:
  This assertion verifies that the parentAgent() method correctly retrieves and returns the parent agent reference that was previously set. This is fundamental to maintaining the agent hierarchy structure, which is essential for traversing the agent tree and understanding agent relationships in the system.

Scenario 2: Return Null When No Parent Is Set

Details:
  TestName: parentAgentReturnsNullWhenNoParentSet
  Description: This test checks that the parentAgent() method returns null when no parent agent has been assigned to the agent. This validates the default state of an agent without a parent.
Execution:
  Arrange: Create a single BaseAgent instance without setting any parent agent. Ensure that the parentAgent field remains in its default state (null).
  Act: Call the parentAgent() method on the agent.
  Assert: Assert that the returned value is null.
Validation:
  This assertion confirms that agents without a parent correctly return null, which is the expected behavior for root agents or agents that haven't been added to any parent's sub-agent list. This is important for identifying root agents in the hierarchy and preventing null pointer exceptions when checking for parent existence.

Scenario 3: Return Parent After Constructor Establishes Parent-Child Relationship

Details:
  TestName: parentAgentReturnsParentEstablishedByConstructor
  Description: This test verifies that when a BaseAgent is created with sub-agents in its constructor, the sub-agents automatically have their parent set, and calling parentAgent() on the sub-agent returns the parent.
Execution:
  Arrange: Create a child BaseAgent instance. Create a parent BaseAgent instance with the child agent in its subAgents list through the constructor.
  Act: Call the parentAgent() method on the child agent.
  Assert: Assert that the returned BaseAgent instance is the parent agent.
Validation:
  This assertion validates that the constructor properly establishes bidirectional parent-child relationships when sub-agents are provided. The constructor code shows that it iterates through sub-agents and calls subAgent.parentAgent(this), so this test ensures that mechanism works correctly. This is crucial for maintaining consistent agent hierarchy without requiring manual parent assignment.

Scenario 4: Return Updated Parent After Parent Change

Details:
  TestName: parentAgentReturnsUpdatedParentAfterChange
  Description: This test verifies that if an agent's parent is changed (reassigned to a different parent), the parentAgent() method returns the most recently set parent agent.
Execution:
  Arrange: Create three BaseAgent instances: a child agent, an initial parent agent, and a new parent agent. First, set the initial parent for the child agent. Then, change the parent by setting the new parent agent.
  Act: Call the parentAgent() method on the child agent after the parent has been changed.
  Assert: Assert that the returned BaseAgent instance is the new parent agent, not the initial parent.
Validation:
  This assertion confirms that the parentAgent field is mutable and that the getter correctly reflects the current state after updates. This is important for scenarios where agents might be reorganized in the hierarchy, though the comment in the code notes that "one agent cannot be added to two different parents' sub-agents lists," suggesting this should be used carefully.

Scenario 5: Return Null After Parent Is Set To Null

Details:
  TestName: parentAgentReturnsNullAfterParentSetToNull
  Description: This test checks that if an agent's parent is explicitly set to null (removing the parent relationship), the parentAgent() method returns null.
Execution:
  Arrange: Create two BaseAgent instances (a parent and a child). Set the parent for the child agent. Then, explicitly set the parent to null using the parentAgent(null) method.
  Act: Call the parentAgent() method on the child agent.
  Assert: Assert that the returned value is null.
Validation:
  This assertion verifies that the parent relationship can be removed by setting it to null, and the getter correctly reflects this state. This might be useful for detaching agents from their hierarchy or resetting agent relationships during reconfiguration.

Scenario 6: Return Correct Parent In Multi-Level Hierarchy

Details:
  TestName: parentAgentReturnsImmediateParentInMultiLevelHierarchy
  Description: This test validates that in a multi-level agent hierarchy (grandparent -> parent -> child), calling parentAgent() on a child returns its immediate parent, not the grandparent or any other ancestor.
Execution:
  Arrange: Create three BaseAgent instances representing a three-level hierarchy: grandparent, parent, and child. Establish the hierarchy by adding the parent to the grandparent's sub-agents and the child to the parent's sub-agents.
  Act: Call the parentAgent() method on the child agent.
  Assert: Assert that the returned BaseAgent instance is the parent agent, and assert that it is not the grandparent agent.
Validation:
  This assertion ensures that the parentAgent() method returns only the immediate parent in the hierarchy, not any higher-level ancestors. This is critical for correctly implementing tree traversal algorithms and for the rootAgent() method which relies on iteratively calling parentAgent() to reach the root.

Scenario 7: Return Same Parent Reference For Multiple Calls

Details:
  TestName: parentAgentReturnsSameReferenceOnMultipleCalls
  Description: This test verifies that multiple consecutive calls to parentAgent() return the same object reference, confirming that the method is idempotent and doesn't create new instances.
Execution:
  Arrange: Create two BaseAgent instances (a parent and a child). Set the parent for the child agent.
  Act: Call the parentAgent() method on the child agent twice, storing both results.
  Assert: Assert that both returned references are identical using reference equality (==) or assertSame().
Validation:
  This assertion confirms that the parentAgent() method is a simple getter that returns the same reference each time, without any side effects or object creation. This is important for performance and for ensuring that identity checks (using ==) work correctly when comparing parent agents.

Scenario 8: Return Parent For Agent With Sub-Agents

Details:
  TestName: parentAgentReturnsParentForAgentWithSubAgents
  Description: This test verifies that an agent that itself has sub-agents can still correctly return its own parent agent, ensuring that being a parent doesn't affect the ability to have a parent.
Execution:
  Arrange: Create three BaseAgent instances: a grandparent, a parent (which will have sub-agents), and a child. Add the child to the parent's sub-agents list, and add the parent to the grandparent's sub-agents list.
  Act: Call the parentAgent() method on the parent agent (which has the child as a sub-agent).
  Assert: Assert that the returned BaseAgent instance is the grandparent agent.
Validation:
  This assertion validates that agents can simultaneously be both parents (having sub-agents) and children (having a parent), which is essential for building multi-level hierarchies. This ensures the parentAgent field and method work independently of the subAgents field.

Scenario 9: Return Parent Consistent With RootAgent Traversal

Details:
  TestName: parentAgentConsistentWithRootAgentMethod
  Description: This test verifies that the parentAgent() method returns values consistent with the rootAgent() method's traversal logic, ensuring the parent chain is properly maintained.
Execution:
  Arrange: Create a three-level hierarchy of BaseAgent instances: root, middle, and leaf. Establish the parent-child relationships through the constructor or setter.
  Act: Call parentAgent() on the leaf agent to get the middle agent, then call parentAgent() on the middle agent to get the root agent. Also call rootAgent() on the leaf agent.
  Assert: Assert that the root agent obtained by traversing parentAgent() calls matches the root agent returned by the rootAgent() method.
Validation:
  This assertion ensures consistency between the parentAgent() method and the rootAgent() method, which relies on repeatedly calling parentAgent() until null is reached. This validates the integrity of the parent chain and ensures that tree traversal algorithms work correctly.

Scenario 10: Return Null For Root Agent

Details:
  TestName: parentAgentReturnsNullForRootAgent
  Description: This test specifically verifies that a root agent (an agent at the top of the hierarchy with no parent) returns null when parentAgent() is called.
Execution:
  Arrange: Create a BaseAgent instance that represents a root agent. Create additional child agents and add them to the root agent's sub-agents list, but do not set any parent for the root agent itself.
  Act: Call the parentAgent() method on the root agent.
  Assert: Assert that the returned value is null.
Validation:
  This assertion confirms that root agents are properly identified by having a null parent. This is critical for the rootAgent() method's termination condition and for any logic that needs to identify the top of the agent hierarchy. Root agents serve as entry points for agent execution and must be distinguishable from non-root agents.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.agents.Callbacks.AfterAgentCallback;
import com.google.adk.agents.Callbacks.BeforeAgentCallback;
import com.google.adk.plugins.PluginManager;
import com.google.common.collect.ImmutableList;
import java.util.List;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

class BaseAgentParentAgentTest {

	@Mock
	private PluginManager pluginManager;

	private ConcreteBaseAgent childAgent;

	private ConcreteBaseAgent parentAgent;

	private ConcreteBaseAgent grandparentAgent;

	@BeforeEach
	void setUp() {
		MockitoAnnotations.openMocks(this);
	}

	@Test
	@Tag("valid")
	void parentAgentReturnsSetParentAgent() {
		// Arrange
		parentAgent = new ConcreteBaseAgent("parent", "Parent Agent", ImmutableList.of(), null, null);
		childAgent = new ConcreteBaseAgent("child", "Child Agent", ImmutableList.of(), null, null);
		childAgent.parentAgent(parentAgent);
		// Act
		BaseAgent result = childAgent.parentAgent();
		// Assert
		assertNotNull(result);
		assertSame(parentAgent, result);
		assertEquals("parent", result.name());
	}

	@Test
	@Tag("valid")
	void parentAgentReturnsNullWhenNoParentSet() {
		// Arrange
		childAgent = new ConcreteBaseAgent("child", "Child Agent", ImmutableList.of(), null, null);
		// Act
		BaseAgent result = childAgent.parentAgent();
		// Assert
		assertNull(result);
	}

	@Test
	@Tag("valid")
	void parentAgentReturnsParentEstablishedByConstructor() {
		// Arrange
		childAgent = new ConcreteBaseAgent("child", "Child Agent", ImmutableList.of(), null, null);
		parentAgent = new ConcreteBaseAgent("parent", "Parent Agent", ImmutableList.of(childAgent), null, null);
		// Act
		BaseAgent result = childAgent.parentAgent();
		// Assert
		assertNotNull(result);
		assertSame(parentAgent, result);
		assertEquals("parent", result.name());
	}

	@Test
	@Tag("valid")
	void parentAgentReturnsUpdatedParentAfterChange() {
		// Arrange
		ConcreteBaseAgent initialParent = new ConcreteBaseAgent("initialParent", "Initial Parent", ImmutableList.of(),
				null, null);
		ConcreteBaseAgent newParent = new ConcreteBaseAgent("newParent", "New Parent", ImmutableList.of(), null, null);
		childAgent = new ConcreteBaseAgent("child", "Child Agent", ImmutableList.of(), null, null);

		childAgent.parentAgent(initialParent);
		childAgent.parentAgent(newParent);
		// Act
		BaseAgent result = childAgent.parentAgent();
		// Assert
		assertNotNull(result);
		assertSame(newParent, result);
		assertNotSame(initialParent, result);
		assertEquals("newParent", result.name());
	}

	@Test
	@Tag("boundary")
	void parentAgentReturnsNullAfterParentSetToNull() {
		// Arrange
		parentAgent = new ConcreteBaseAgent("parent", "Parent Agent", ImmutableList.of(), null, null);
		childAgent = new ConcreteBaseAgent("child", "Child Agent", ImmutableList.of(), null, null);
		childAgent.parentAgent(parentAgent);
		childAgent.parentAgent(null);
		// Act
		BaseAgent result = childAgent.parentAgent();
		// Assert
		assertNull(result);
	}

	@Test
	@Tag("valid")
	void parentAgentReturnsImmediateParentInMultiLevelHierarchy() {
		// Arrange
		childAgent = new ConcreteBaseAgent("child", "Child Agent", ImmutableList.of(), null, null);
		parentAgent = new ConcreteBaseAgent("parent", "Parent Agent", ImmutableList.of(childAgent), null, null);
		grandparentAgent = new ConcreteBaseAgent("grandparent", "Grandparent Agent", ImmutableList.of(parentAgent),
				null, null);
		// Act
		BaseAgent result = childAgent.parentAgent();
		// Assert
		assertNotNull(result);
		assertSame(parentAgent, result);
		assertNotSame(grandparentAgent, result);
		assertEquals("parent", result.name());
	}

	@Test
	@Tag("valid")
	void parentAgentReturnsSameReferenceOnMultipleCalls() {
		// Arrange
		parentAgent = new ConcreteBaseAgent("parent", "Parent Agent", ImmutableList.of(), null, null);
		childAgent = new ConcreteBaseAgent("child", "Child Agent", ImmutableList.of(), null, null);
		childAgent.parentAgent(parentAgent);
		// Act
		BaseAgent firstCall = childAgent.parentAgent();
		BaseAgent secondCall = childAgent.parentAgent();
		// Assert
		assertNotNull(firstCall);
		assertNotNull(secondCall);
		assertSame(firstCall, secondCall);
		assertSame(parentAgent, firstCall);
		assertSame(parentAgent, secondCall);
	}

	@Test
	@Tag("valid")
	void parentAgentReturnsParentForAgentWithSubAgents() {
		// Arrange
		ConcreteBaseAgent leafAgent = new ConcreteBaseAgent("leaf", "Leaf Agent", ImmutableList.of(), null, null);
		parentAgent = new ConcreteBaseAgent("parent", "Parent Agent", ImmutableList.of(leafAgent), null, null);
		grandparentAgent = new ConcreteBaseAgent("grandparent", "Grandparent Agent", ImmutableList.of(parentAgent),
				null, null);
		// Act
		BaseAgent result = parentAgent.parentAgent();
		// Assert
		assertNotNull(result);
		assertSame(grandparentAgent, result);
		assertEquals("grandparent", result.name());
		assertFalse(parentAgent.subAgents().isEmpty());
	}

	@Test
	@Tag("integration")
	void parentAgentConsistentWithRootAgentMethod() {
		// Arrange
		ConcreteBaseAgent leafAgent = new ConcreteBaseAgent("leaf", "Leaf Agent", ImmutableList.of(), null, null);
		ConcreteBaseAgent middleAgent = new ConcreteBaseAgent("middle", "Middle Agent", ImmutableList.of(leafAgent),
				null, null);
		ConcreteBaseAgent rootAgent = new ConcreteBaseAgent("root", "Root Agent", ImmutableList.of(middleAgent), null,
				null);
		// Act
		BaseAgent parentOfLeaf = leafAgent.parentAgent();
		BaseAgent parentOfMiddle = parentOfLeaf.parentAgent();
		BaseAgent rootViaTraversal = parentOfMiddle;
		BaseAgent rootViaMethod = leafAgent.rootAgent();
		// Assert
		assertNotNull(parentOfLeaf);
		assertSame(middleAgent, parentOfLeaf);
		assertNotNull(parentOfMiddle);
		assertSame(rootAgent, parentOfMiddle);
		assertSame(rootViaTraversal, rootViaMethod);
		assertEquals("root", rootViaMethod.name());
	}

	@Test
	@Tag("valid")
	void parentAgentReturnsNullForRootAgent() {
		// Arrange
		ConcreteBaseAgent child1 = new ConcreteBaseAgent("child1", "Child 1", ImmutableList.of(), null, null);
		ConcreteBaseAgent child2 = new ConcreteBaseAgent("child2", "Child 2", ImmutableList.of(), null, null);
		ConcreteBaseAgent rootAgent = new ConcreteBaseAgent("root", "Root Agent", ImmutableList.of(child1, child2),
				null, null);
		// Act
		BaseAgent result = rootAgent.parentAgent();
		// Assert
		assertNull(result);
		assertFalse(rootAgent.subAgents().isEmpty());
		assertEquals(2, rootAgent.subAgents().size());
	}

	private static class ConcreteBaseAgent extends BaseAgent {

		public ConcreteBaseAgent(String name, String description, List<? extends BaseAgent> subAgents,
				List<? extends BeforeAgentCallback> beforeAgentCallback,
				List<? extends AfterAgentCallback> afterAgentCallback) {
			super(name, description, subAgents, beforeAgentCallback, afterAgentCallback);
		}

		@Override
		protected io.reactivex.rxjava3.core.Flowable<com.google.adk.events.Event> runAsyncImpl(
				InvocationContext invocationContext) {
			return io.reactivex.rxjava3.core.Flowable.empty();
		}

		@Override
		protected io.reactivex.rxjava3.core.Flowable<com.google.adk.events.Event> runLiveImpl(
				InvocationContext invocationContext) {
			return io.reactivex.rxjava3.core.Flowable.empty();
		}

	}

}
