/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-dec-16-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=afterAgentCallback_1b8942a87f
ROOST_METHOD_SIG_HASH=afterAgentCallback_dcbdb9c773

Scenario 1: Return Empty Optional When After Agent Callback Is Not Present

Details:
  TestName: afterAgentCallbackReturnsEmptyOptionalWhenNotSet
  Description: This test verifies that the afterAgentCallback() method returns an empty Optional when no after agent callbacks have been configured during the BaseAgent construction. This ensures the method correctly handles the absence of callbacks.
Execution:
  Arrange: Create a concrete implementation of BaseAgent with null afterAgentCallback parameter in the constructor.
  Act: Invoke the afterAgentCallback() method on the created BaseAgent instance.
  Assert: Use JUnit assertions to verify that the returned Optional is empty using Optional.isEmpty() or assertFalse(optional.isPresent()).
Validation:
  The assertion verifies that when no after agent callbacks are provided during agent initialization, the method returns an empty Optional rather than null or throwing an exception. This is important for safe optional handling in the application, allowing calling code to check for presence before attempting to access the callback list. This prevents NullPointerException and follows Java Optional best practices.

Scenario 2: Return Present Optional With Single Callback When One Callback Is Configured

Details:
  TestName: afterAgentCallbackReturnsPresentOptionalWithSingleCallback
  Description: This test validates that when a single AfterAgentCallback is provided during BaseAgent construction, the afterAgentCallback() method returns a present Optional containing a list with exactly one callback element.
Execution:
  Arrange: Create a mock or concrete implementation of AfterAgentCallback. Create a BaseAgent instance passing a list containing this single callback to the constructor.
  Act: Call the afterAgentCallback() method on the BaseAgent instance.
  Assert: Assert that the returned Optional is present using assertTrue(optional.isPresent()). Assert that the list size is 1. Assert that the list contains the expected callback instance.
Validation:
  This test ensures that the method correctly wraps and returns a single callback in the Optional container. It validates that the internal field is properly initialized and accessible through the getter method. This is crucial for the agent's lifecycle management where after-execution callbacks need to be invoked in sequence.

Scenario 3: Return Present Optional With Multiple Callbacks When Multiple Callbacks Are Configured

Details:
  TestName: afterAgentCallbackReturnsPresentOptionalWithMultipleCallbacks
  Description: This test checks that when multiple AfterAgentCallback instances are provided during BaseAgent construction, the afterAgentCallback() method returns a present Optional containing a list with all the configured callbacks in the correct order.
Execution:
  Arrange: Create multiple mock or concrete AfterAgentCallback instances (e.g., 3 callbacks). Create a BaseAgent instance with a list containing all these callbacks passed to the constructor.
  Act: Invoke the afterAgentCallback() method on the BaseAgent instance.
  Assert: Assert that the returned Optional is present. Assert that the list size matches the number of callbacks provided (e.g., 3). Assert that the list contains all expected callback instances in the correct order.
Validation:
  This test validates that the method preserves the order and completeness of multiple callbacks. The order is significant because callbacks are invoked sequentially until one returns a non-null result. This ensures proper callback chain execution in the agent's after-execution phase, which is critical for post-processing, logging, or cleanup operations.

Scenario 4: Return Immutable Optional Reference Across Multiple Invocations

Details:
  TestName: afterAgentCallbackReturnsConsistentOptionalAcrossMultipleInvocations
  Description: This test verifies that multiple invocations of the afterAgentCallback() method on the same BaseAgent instance return consistent results, confirming that the method is idempotent and the internal state is not modified by the getter.
Execution:
  Arrange: Create a BaseAgent instance with a configured list of AfterAgentCallback instances.
  Act: Call the afterAgentCallback() method multiple times (e.g., 3 times) on the same instance and store each result.
  Assert: Assert that all returned Optional instances have the same presence state (all present or all empty). If present, assert that the contained lists have the same size and contain the same callback instances across all invocations.
Validation:
  This test ensures that the afterAgentCallback() method is a pure getter that does not modify internal state and consistently returns the same data. This is important for thread safety and predictable behavior when the same agent instance is queried multiple times during its lifecycle. It confirms that the final field is properly encapsulated and immutable.

Scenario 5: Return Optional With Empty List When Empty List Is Provided

Details:
  TestName: afterAgentCallbackReturnsEmptyOptionalWhenEmptyListProvided
  Description: This test validates the behavior when an empty list (not null) is provided for afterAgentCallback during BaseAgent construction. It checks whether the method returns an empty Optional or a present Optional containing an empty list.
Execution:
  Arrange: Create a BaseAgent instance passing an empty ImmutableList or empty ArrayList for the afterAgentCallback parameter in the constructor.
  Act: Invoke the afterAgentCallback() method on the created BaseAgent instance.
  Assert: Assert the state of the returned Optional. Based on the constructor implementation (Optional.ofNullable), if an empty list is passed, verify whether it returns a present Optional with an empty list or an empty Optional.
Validation:
  This test clarifies the boundary condition handling for empty collections. The constructor uses Optional.ofNullable(afterAgentCallback), which means an empty list would result in a present Optional containing an empty list, not an empty Optional. This distinction is important for code that differentiates between "no callbacks configured" versus "callbacks configured but list is empty", affecting iteration and callback invocation logic.

Scenario 6: Return Optional Containing List With Wildcard Generic Type

Details:
  TestName: afterAgentCallbackReturnsOptionalWithCorrectGenericType
  Description: This test verifies that the returned Optional contains a List with the correct generic type signature (List<? extends AfterAgentCallback>), ensuring type safety and compatibility with the callback interface hierarchy.
Execution:
  Arrange: Create concrete implementations or mocks of AfterAgentCallback. Create a BaseAgent instance with these callbacks.
  Act: Call the afterAgentCallback() method and retrieve the Optional.
  Assert: Assert that the Optional is present. Extract the list from the Optional and verify that it can be assigned to a variable of type List<? extends AfterAgentCallback>. Verify that each element in the list is an instance of AfterAgentCallback.
Validation:
  This test ensures type safety and validates that the generic type bounds are correctly maintained through the getter method. The wildcard type (? extends AfterAgentCallback) allows for flexibility in callback implementations while maintaining type safety. This is crucial for polymorphic callback handling where different concrete callback implementations may be used interchangeably.

Scenario 7: Return Optional That Does Not Allow Modification Of Internal State

Details:
  TestName: afterAgentCallbackReturnsUnmodifiableOptional
  Description: This test verifies that the Optional and its contained list cannot be used to modify the internal state of the BaseAgent, ensuring encapsulation and immutability of the callback configuration.
Execution:
  Arrange: Create a BaseAgent instance with a list of AfterAgentCallback instances.
  Act: Call the afterAgentCallback() method and retrieve the Optional. If present, attempt to modify the contained list (e.g., add, remove, or clear operations).
  Assert: Assert that any modification attempt throws an UnsupportedOperationException or that the original BaseAgent's internal state remains unchanged after modification attempts.
Validation:
  This test validates proper encapsulation and immutability principles. Since afterAgentCallback is a final field and the constructor likely uses immutable collections, the returned list should be unmodifiable. This prevents external code from corrupting the agent's callback configuration after construction, ensuring the agent's behavior remains consistent and predictable throughout its lifecycle.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.agents.Callbacks.AfterAgentCallback;
import com.google.common.collect.ImmutableList;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

class BaseAgentAfterAgentCallbackTest {

	@Mock
	private AfterAgentCallback mockCallback1;

	@Mock
	private AfterAgentCallback mockCallback2;

	@Mock
	private AfterAgentCallback mockCallback3;

	private ConcreteBaseAgent agent;

	@BeforeEach
	void setUp() {
		MockitoAnnotations.openMocks(this);
	}

	@Test
	@Tag("valid")
	void afterAgentCallbackReturnsEmptyOptionalWhenNotSet() {
		agent = new ConcreteBaseAgent("testAgent", "Test Description", ImmutableList.of(), null, null);
		Optional<List<? extends AfterAgentCallback>> result = agent.afterAgentCallback();
		assertNotNull(result);
		assertTrue(result.isEmpty());
		assertFalse(result.isPresent());
	}

	@Test
	@Tag("valid")
	void afterAgentCallbackReturnsPresentOptionalWithSingleCallback() {
		List<AfterAgentCallback> callbacks = ImmutableList.of(mockCallback1);
		agent = new ConcreteBaseAgent("testAgent", "Test Description", ImmutableList.of(), null, callbacks);
		Optional<List<? extends AfterAgentCallback>> result = agent.afterAgentCallback();
		assertTrue(result.isPresent());
		assertEquals(1, result.get().size());
		assertTrue(result.get().contains(mockCallback1));
		assertSame(mockCallback1, result.get().get(0));
	}

	@Test
	@Tag("valid")
	void afterAgentCallbackReturnsPresentOptionalWithMultipleCallbacks() {
		List<AfterAgentCallback> callbacks = ImmutableList.of(mockCallback1, mockCallback2, mockCallback3);
		agent = new ConcreteBaseAgent("testAgent", "Test Description", ImmutableList.of(), null, callbacks);
		Optional<List<? extends AfterAgentCallback>> result = agent.afterAgentCallback();
		assertTrue(result.isPresent());
		assertEquals(3, result.get().size());
		assertEquals(mockCallback1, result.get().get(0));
		assertEquals(mockCallback2, result.get().get(1));
		assertEquals(mockCallback3, result.get().get(2));
		assertTrue(result.get().contains(mockCallback1));
		assertTrue(result.get().contains(mockCallback2));
		assertTrue(result.get().contains(mockCallback3));
	}

	@Test
	@Tag("valid")
	void afterAgentCallbackReturnsConsistentOptionalAcrossMultipleInvocations() {
		List<AfterAgentCallback> callbacks = ImmutableList.of(mockCallback1, mockCallback2);
		agent = new ConcreteBaseAgent("testAgent", "Test Description", ImmutableList.of(), null, callbacks);
		Optional<List<? extends AfterAgentCallback>> result1 = agent.afterAgentCallback();
		Optional<List<? extends AfterAgentCallback>> result2 = agent.afterAgentCallback();
		Optional<List<? extends AfterAgentCallback>> result3 = agent.afterAgentCallback();
		assertTrue(result1.isPresent());
		assertTrue(result2.isPresent());
		assertTrue(result3.isPresent());
		assertEquals(result1.get().size(), result2.get().size());
		assertEquals(result2.get().size(), result3.get().size());
		assertEquals(2, result1.get().size());
		assertEquals(2, result2.get().size());
		assertEquals(2, result3.get().size());
		assertSame(result1.get().get(0), result2.get().get(0));
		assertSame(result2.get().get(0), result3.get().get(0));
		assertSame(result1.get().get(1), result2.get().get(1));
		assertSame(result2.get().get(1), result3.get().get(1));
	}

	@Test
	@Tag("boundary")
	void afterAgentCallbackReturnsEmptyOptionalWhenEmptyListProvided() {
		List<AfterAgentCallback> emptyCallbacks = ImmutableList.of();
		agent = new ConcreteBaseAgent("testAgent", "Test Description", ImmutableList.of(), null, emptyCallbacks);
		Optional<List<? extends AfterAgentCallback>> result = agent.afterAgentCallback();
		assertTrue(result.isPresent());
		assertNotNull(result.get());
		assertTrue(result.get().isEmpty());
		assertEquals(0, result.get().size());
	}

	@Test
	@Tag("valid")
	void afterAgentCallbackReturnsOptionalWithCorrectGenericType() {
		List<AfterAgentCallback> callbacks = ImmutableList.of(mockCallback1, mockCallback2);
		agent = new ConcreteBaseAgent("testAgent", "Test Description", ImmutableList.of(), null, callbacks);
		Optional<List<? extends AfterAgentCallback>> result = agent.afterAgentCallback();
		assertTrue(result.isPresent());
		List<? extends AfterAgentCallback> callbackList = result.get();
		assertNotNull(callbackList);
		assertEquals(2, callbackList.size());
		for (Object callback : callbackList) {
			assertTrue(callback instanceof AfterAgentCallback);
		}
		assertTrue(callbackList.get(0) instanceof AfterAgentCallback);
		assertTrue(callbackList.get(1) instanceof AfterAgentCallback);
	}

	@Test
	@Tag("valid")
	void afterAgentCallbackReturnsUnmodifiableOptional() {
		List<AfterAgentCallback> callbacks = ImmutableList.of(mockCallback1, mockCallback2);
		agent = new ConcreteBaseAgent("testAgent", "Test Description", ImmutableList.of(), null, callbacks);
		Optional<List<? extends AfterAgentCallback>> result = agent.afterAgentCallback();
		assertTrue(result.isPresent());
		List<? extends AfterAgentCallback> callbackList = result.get();

		assertThrows(UnsupportedOperationException.class, () -> {
			((List<AfterAgentCallback>) callbackList).add(mockCallback3);
		});

		assertThrows(UnsupportedOperationException.class, () -> {
			((List<AfterAgentCallback>) callbackList).remove(0);
		});

		assertThrows(UnsupportedOperationException.class, () -> {
			((List<AfterAgentCallback>) callbackList).clear();
		});

		assertEquals(2, agent.afterAgentCallback().get().size());
		assertTrue(agent.afterAgentCallback().get().contains(mockCallback1));
		assertTrue(agent.afterAgentCallback().get().contains(mockCallback2));
	}

	@Test
	@Tag("boundary")
	void afterAgentCallbackReturnsEmptyOptionalWhenNullListProvided() {
		agent = new ConcreteBaseAgent("testAgent", "Test Description", ImmutableList.of(), null, null);
		Optional<List<? extends AfterAgentCallback>> result = agent.afterAgentCallback();
		assertNotNull(result);
		assertFalse(result.isPresent());
		assertTrue(result.isEmpty());
	}

	@Test
	@Tag("valid")
	void afterAgentCallbackMaintainsCallbackOrderInList() {
		List<AfterAgentCallback> callbacks = ImmutableList.of(mockCallback1, mockCallback2, mockCallback3);
		agent = new ConcreteBaseAgent("testAgent", "Test Description", ImmutableList.of(), null, callbacks);
		Optional<List<? extends AfterAgentCallback>> result = agent.afterAgentCallback();
		assertTrue(result.isPresent());
		List<? extends AfterAgentCallback> callbackList = result.get();
		assertEquals(3, callbackList.size());
		assertSame(mockCallback1, callbackList.get(0));
		assertSame(mockCallback2, callbackList.get(1));
		assertSame(mockCallback3, callbackList.get(2));
	}

	private static class ConcreteBaseAgent extends BaseAgent {

		public ConcreteBaseAgent(String name, String description, List<? extends BaseAgent> subAgents,
				List<? extends Callbacks.BeforeAgentCallback> beforeAgentCallback,
				List<? extends AfterAgentCallback> afterAgentCallback) {
			super(name, description, subAgents, beforeAgentCallback, afterAgentCallback);
		}

		@Override
		protected io.reactivex.rxjava3.core.Flowable<com.google.adk.events.Event> runAsyncImpl(
				InvocationContext invocationContext) {
			return io.reactivex.rxjava3.core.Flowable.empty();
		}

		@Override
		protected io.reactivex.rxjava3.core.Flowable<com.google.adk.events.Event> runLiveImpl(
				InvocationContext invocationContext) {
			return io.reactivex.rxjava3.core.Flowable.empty();
		}

	}

}
