/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-dec-16-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=subAgents_fd2554c963
ROOST_METHOD_SIG_HASH=subAgents_81ca6a79fe

Scenario 1: Return Empty List When No Sub-Agents Are Present

Details:
  TestName: subAgentsReturnsEmptyListWhenNoSubAgentsExist
  Description: This test verifies that the subAgents() method returns an empty list when a BaseAgent instance is created without any sub-agents. This ensures that the method handles the case where no sub-agents have been added to the agent.
Execution:
  Arrange: Create a concrete implementation of BaseAgent with an empty list or null for the subAgents parameter in the constructor.
  Act: Invoke the subAgents() method on the created BaseAgent instance.
  Assert: Use JUnit assertions to verify that the returned list is not null and has a size of 0.
Validation:
  The assertion verifies that when no sub-agents are provided during agent construction, the method returns an empty list rather than null. This is important for preventing NullPointerExceptions in code that iterates over sub-agents and ensures consistent behavior across the application. The test validates that the BaseAgent properly initializes the subAgents field to an empty ImmutableList when no sub-agents are provided.

Scenario 2: Return List With Single Sub-Agent

Details:
  TestName: subAgentsReturnsSingleSubAgent
  Description: This test checks that the subAgents() method correctly returns a list containing exactly one sub-agent when a BaseAgent is created with a single sub-agent.
Execution:
  Arrange: Create a concrete implementation of BaseAgent with one sub-agent in the subAgents list. Create the sub-agent instance first, then pass it in a list to the parent agent's constructor.
  Act: Call the subAgents() method on the parent agent instance.
  Assert: Verify that the returned list is not null, has a size of 1, and contains the expected sub-agent instance.
Validation:
  This test ensures that the method correctly returns a list with a single element when one sub-agent is added. It validates that the subAgents field is properly initialized and that the getter method returns the correct reference. This is crucial for agent hierarchies where a parent agent manages a single child agent.

Scenario 3: Return List With Multiple Sub-Agents

Details:
  TestName: subAgentsReturnsMultipleSubAgents
  Description: This test validates that the subAgents() method returns a list containing all sub-agents when a BaseAgent is created with multiple sub-agents.
Execution:
  Arrange: Create a concrete implementation of BaseAgent with multiple sub-agents (e.g., 3 or more) in the subAgents list. Create all sub-agent instances and pass them in a list to the parent agent's constructor.
  Act: Invoke the subAgents() method on the parent agent.
  Assert: Assert that the returned list is not null, has the expected size matching the number of sub-agents added, and contains all the expected sub-agent instances in the correct order.
Validation:
  This assertion verifies that the method correctly returns all sub-agents that were added to the parent agent. It ensures that the internal list maintains the order of sub-agents and that no sub-agents are lost during initialization. This is essential for complex agent hierarchies where a parent agent coordinates multiple child agents.

Scenario 4: Return Immutable List

Details:
  TestName: subAgentsReturnsImmutableList
  Description: This test verifies that the list returned by the subAgents() method is immutable and cannot be modified by external code.
Execution:
  Arrange: Create a concrete implementation of BaseAgent with at least one sub-agent.
  Act: Call the subAgents() method to get the list of sub-agents, then attempt to modify the returned list by adding or removing elements.
  Assert: Verify that attempting to modify the list throws an UnsupportedOperationException or similar exception indicating immutability.
Validation:
  This test ensures that the subAgents list cannot be modified externally, which is critical for maintaining the integrity of the agent hierarchy. Since the field is declared as final and the constructor uses ImmutableList, this test validates that the encapsulation is properly maintained and external code cannot corrupt the agent's internal state.

Scenario 5: Return Same List Instance On Multiple Calls

Details:
  TestName: subAgentsReturnsSameListInstanceOnMultipleCalls
  Description: This test checks that calling the subAgents() method multiple times returns the same list instance, ensuring consistency and efficient memory usage.
Execution:
  Arrange: Create a concrete implementation of BaseAgent with sub-agents.
  Act: Call the subAgents() method twice on the same BaseAgent instance and store both results.
  Assert: Use JUnit assertions to verify that both returned lists are the same instance (using reference equality).
Validation:
  This assertion verifies that the method returns a direct reference to the internal subAgents field rather than creating a new list on each call. This is important for performance and memory efficiency, especially in scenarios where the method is called frequently. It also ensures that the behavior is consistent with the implementation pattern of returning the final field directly.

Scenario 6: Return List With Correct Sub-Agent Types

Details:
  TestName: subAgentsReturnsListWithCorrectSubAgentTypes
  Description: This test validates that the subAgents() method returns a list containing sub-agents that are instances of BaseAgent or its subclasses, respecting the wildcard generic type.
Execution:
  Arrange: Create a concrete implementation of BaseAgent with sub-agents of different concrete types (all extending BaseAgent).
  Act: Invoke the subAgents() method and retrieve the list.
  Assert: Verify that each element in the returned list is an instance of BaseAgent and can be cast to the appropriate type.
Validation:
  This test ensures that the generic type declaration (List<? extends BaseAgent>) is correctly implemented and that the list can contain different concrete implementations of BaseAgent. This is important for polymorphic agent hierarchies where different types of agents can be sub-agents of a parent agent.

Scenario 7: Return List Preserving Sub-Agent Order

Details:
  TestName: subAgentsPreservesOrderOfSubAgents
  Description: This test verifies that the subAgents() method returns sub-agents in the same order they were provided during agent construction.
Execution:
  Arrange: Create a concrete implementation of BaseAgent with multiple sub-agents added in a specific order. Keep references to the sub-agents in the order they were added.
  Act: Call the subAgents() method to retrieve the list of sub-agents.
  Assert: Verify that the order of sub-agents in the returned list matches the order in which they were provided to the constructor.
Validation:
  This assertion ensures that the agent maintains the order of sub-agents, which may be important for execution order or delegation logic. The test validates that the ImmutableList preserves the insertion order and that the subAgents() method returns this ordered list correctly.

Scenario 8: Return Non-Null List Reference

Details:
  TestName: subAgentsNeverReturnsNull
  Description: This test ensures that the subAgents() method never returns null, even when the agent is created with null for the subAgents parameter.
Execution:
  Arrange: Create a concrete implementation of BaseAgent, passing null as the subAgents parameter to the constructor.
  Act: Invoke the subAgents() method on the created instance.
  Assert: Assert that the returned value is not null and is an empty list.
Validation:
  This test validates the defensive programming practice implemented in the constructor where null is converted to an empty ImmutableList. This prevents NullPointerExceptions in client code and ensures that the method always returns a valid list reference. This is a critical safety feature for robust application behavior.

Scenario 9: Return List After Parent-Child Relationship Established

Details:
  TestName: subAgentsReturnsListAfterParentChildRelationshipEstablished
  Description: This test verifies that the subAgents() method returns the correct list of sub-agents after the parent-child relationships have been established in the constructor.
Execution:
  Arrange: Create a concrete implementation of BaseAgent with sub-agents. The constructor should establish parent relationships for all sub-agents.
  Act: Call the subAgents() method to retrieve the list, then verify that each sub-agent has its parent set correctly.
  Assert: Verify that the returned list contains the expected sub-agents and that each sub-agent's parentAgent() method returns the parent agent instance.
Validation:
  This test ensures that the subAgents() method returns the list after the constructor has properly initialized the parent-child relationships. It validates that the bidirectional relationship between parent and child agents is correctly established and that the list returned by subAgents() reflects the complete agent hierarchy structure.

Scenario 10: Return List Independent of Callbacks

Details:
  TestName: subAgentsReturnsListIndependentOfCallbacks
  Description: This test verifies that the subAgents() method returns the correct list regardless of whether beforeAgentCallback or afterAgentCallback are set.
Execution:
  Arrange: Create two concrete implementations of BaseAgent with the same sub-agents but different callback configurations (one with callbacks, one without).
  Act: Call the subAgents() method on both instances.
  Assert: Verify that both instances return lists with the same sub-agents, demonstrating that callbacks do not affect the sub-agents list.
Validation:
  This test ensures that the subAgents field and its getter method are independent of the callback fields. It validates that the method's behavior is consistent regardless of other agent configuration, which is important for predictable agent hierarchy management.

*/

// ********RoostGPT********

package com.google.adk.agents;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.agents.Callbacks.AfterAgentCallback;
import com.google.adk.agents.Callbacks.BeforeAgentCallback;
import com.google.adk.events.Event;
import com.google.common.collect.ImmutableList;
import io.reactivex.rxjava3.core.Flowable;
import java.util.List;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

class BaseAgentSubAgentsTest {

	private ConcreteBaseAgent agent;

	@Mock
	private BeforeAgentCallback mockBeforeCallback;

	@Mock
	private AfterAgentCallback mockAfterCallback;

	@BeforeEach
	void setUp() {
		MockitoAnnotations.openMocks(this);
	}

	@Test
	@Tag("valid")
	void subAgentsReturnsEmptyListWhenNoSubAgentsExist() {
		agent = new ConcreteBaseAgent("testAgent", "Test Description", null, null, null);

		List<? extends BaseAgent> result = agent.subAgents();

		assertNotNull(result);
		assertEquals(0, result.size());
		assertTrue(result.isEmpty());
	}

	@Test
	@Tag("valid")
	void subAgentsReturnsSingleSubAgent() {
		ConcreteBaseAgent subAgent = new ConcreteBaseAgent("subAgent1", "Sub Agent 1", null, null, null);
		List<BaseAgent> subAgentsList = ImmutableList.of(subAgent);
		agent = new ConcreteBaseAgent("parentAgent", "Parent Agent", subAgentsList, null, null);

		List<? extends BaseAgent> result = agent.subAgents();

		assertNotNull(result);
		assertEquals(1, result.size());
		assertTrue(result.contains(subAgent));
		assertEquals(subAgent, result.get(0));
	}

	@Test
	@Tag("valid")
	void subAgentsReturnsMultipleSubAgents() {
		ConcreteBaseAgent subAgent1 = new ConcreteBaseAgent("subAgent1", "Sub Agent 1", null, null, null);
		ConcreteBaseAgent subAgent2 = new ConcreteBaseAgent("subAgent2", "Sub Agent 2", null, null, null);
		ConcreteBaseAgent subAgent3 = new ConcreteBaseAgent("subAgent3", "Sub Agent 3", null, null, null);
		List<BaseAgent> subAgentsList = ImmutableList.of(subAgent1, subAgent2, subAgent3);
		agent = new ConcreteBaseAgent("parentAgent", "Parent Agent", subAgentsList, null, null);

		List<? extends BaseAgent> result = agent.subAgents();

		assertNotNull(result);
		assertEquals(3, result.size());
		assertTrue(result.contains(subAgent1));
		assertTrue(result.contains(subAgent2));
		assertTrue(result.contains(subAgent3));
		assertEquals(subAgent1, result.get(0));
		assertEquals(subAgent2, result.get(1));
		assertEquals(subAgent3, result.get(2));
	}

	@Test
	@Tag("valid")
	void subAgentsReturnsImmutableList() {
		ConcreteBaseAgent subAgent = new ConcreteBaseAgent("subAgent1", "Sub Agent 1", null, null, null);
		List<BaseAgent> subAgentsList = ImmutableList.of(subAgent);
		agent = new ConcreteBaseAgent("parentAgent", "Parent Agent", subAgentsList, null, null);

		List<? extends BaseAgent> result = agent.subAgents();

		assertThrows(UnsupportedOperationException.class, () -> {
			((List<BaseAgent>) result).add(new ConcreteBaseAgent("newAgent", "New Agent", null, null, null));
		});

		assertThrows(UnsupportedOperationException.class, () -> {
			((List<BaseAgent>) result).remove(0);
		});
	}

	@Test
	@Tag("valid")
	void subAgentsReturnsSameListInstanceOnMultipleCalls() {
		ConcreteBaseAgent subAgent = new ConcreteBaseAgent("subAgent1", "Sub Agent 1", null, null, null);
		List<BaseAgent> subAgentsList = ImmutableList.of(subAgent);
		agent = new ConcreteBaseAgent("parentAgent", "Parent Agent", subAgentsList, null, null);

		List<? extends BaseAgent> result1 = agent.subAgents();
		List<? extends BaseAgent> result2 = agent.subAgents();

		assertSame(result1, result2);
	}

	@Test
	@Tag("valid")
	void subAgentsReturnsListWithCorrectSubAgentTypes() {
		ConcreteBaseAgent subAgent1 = new ConcreteBaseAgent("subAgent1", "Sub Agent 1", null, null, null);
		AnotherConcreteBaseAgent subAgent2 = new AnotherConcreteBaseAgent("subAgent2", "Sub Agent 2", null, null, null);
		List<BaseAgent> subAgentsList = ImmutableList.of(subAgent1, subAgent2);
		agent = new ConcreteBaseAgent("parentAgent", "Parent Agent", subAgentsList, null, null);

		List<? extends BaseAgent> result = agent.subAgents();

		assertNotNull(result);
		assertEquals(2, result.size());
		for (Object element : result) {
			assertTrue(element instanceof BaseAgent);
		}
		assertTrue(result.get(0) instanceof ConcreteBaseAgent);
		assertTrue(result.get(1) instanceof AnotherConcreteBaseAgent);
	}

	@Test
	@Tag("valid")
	void subAgentsPreservesOrderOfSubAgents() {
		ConcreteBaseAgent subAgent1 = new ConcreteBaseAgent("subAgent1", "Sub Agent 1", null, null, null);
		ConcreteBaseAgent subAgent2 = new ConcreteBaseAgent("subAgent2", "Sub Agent 2", null, null, null);
		ConcreteBaseAgent subAgent3 = new ConcreteBaseAgent("subAgent3", "Sub Agent 3", null, null, null);
		ConcreteBaseAgent subAgent4 = new ConcreteBaseAgent("subAgent4", "Sub Agent 4", null, null, null);
		List<BaseAgent> subAgentsList = ImmutableList.of(subAgent1, subAgent2, subAgent3, subAgent4);
		agent = new ConcreteBaseAgent("parentAgent", "Parent Agent", subAgentsList, null, null);

		List<? extends BaseAgent> result = agent.subAgents();

		assertNotNull(result);
		assertEquals(4, result.size());
		assertEquals(subAgent1, result.get(0));
		assertEquals(subAgent2, result.get(1));
		assertEquals(subAgent3, result.get(2));
		assertEquals(subAgent4, result.get(3));
	}

	@Test
	@Tag("boundary")
	void subAgentsNeverReturnsNull() {
		agent = new ConcreteBaseAgent("testAgent", "Test Description", null, null, null);

		List<? extends BaseAgent> result = agent.subAgents();

		assertNotNull(result);
		assertTrue(result.isEmpty());
		assertEquals(0, result.size());
	}

	@Test
	@Tag("integration")
	void subAgentsReturnsListAfterParentChildRelationshipEstablished() {
		ConcreteBaseAgent subAgent1 = new ConcreteBaseAgent("subAgent1", "Sub Agent 1", null, null, null);
		ConcreteBaseAgent subAgent2 = new ConcreteBaseAgent("subAgent2", "Sub Agent 2", null, null, null);
		List<BaseAgent> subAgentsList = ImmutableList.of(subAgent1, subAgent2);
		agent = new ConcreteBaseAgent("parentAgent", "Parent Agent", subAgentsList, null, null);

		List<? extends BaseAgent> result = agent.subAgents();

		assertNotNull(result);
		assertEquals(2, result.size());
		assertEquals(agent, subAgent1.parentAgent());
		assertEquals(agent, subAgent2.parentAgent());
		for (BaseAgent subAgent : result) {
			assertEquals(agent, subAgent.parentAgent());
		}
	}

	@Test
	@Tag("valid")
	void subAgentsReturnsListIndependentOfCallbacks() {
		ConcreteBaseAgent subAgent1 = new ConcreteBaseAgent("subAgent1", "Sub Agent 1", null, null, null);
		ConcreteBaseAgent subAgent2 = new ConcreteBaseAgent("subAgent2", "Sub Agent 2", null, null, null);
		List<BaseAgent> subAgentsList = ImmutableList.of(subAgent1, subAgent2);

		ConcreteBaseAgent agentWithCallbacks = new ConcreteBaseAgent("agentWithCallbacks", "Agent With Callbacks",
				subAgentsList, ImmutableList.of(mockBeforeCallback), ImmutableList.of(mockAfterCallback));

		ConcreteBaseAgent agentWithoutCallbacks = new ConcreteBaseAgent("agentWithoutCallbacks",
				"Agent Without Callbacks", subAgentsList, null, null);

		List<? extends BaseAgent> resultWithCallbacks = agentWithCallbacks.subAgents();
		List<? extends BaseAgent> resultWithoutCallbacks = agentWithoutCallbacks.subAgents();

		assertNotNull(resultWithCallbacks);
		assertNotNull(resultWithoutCallbacks);
		assertEquals(2, resultWithCallbacks.size());
		assertEquals(2, resultWithoutCallbacks.size());
		assertEquals(resultWithCallbacks.get(0).name(), resultWithoutCallbacks.get(0).name());
		assertEquals(resultWithCallbacks.get(1).name(), resultWithoutCallbacks.get(1).name());
	}

	private static class ConcreteBaseAgent extends BaseAgent {

		public ConcreteBaseAgent(String name, String description, List<? extends BaseAgent> subAgents,
				List<? extends BeforeAgentCallback> beforeAgentCallback,
				List<? extends AfterAgentCallback> afterAgentCallback) {
			super(name, description, subAgents, beforeAgentCallback, afterAgentCallback);
		}

		@Override
		protected Flowable<Event> runAsyncImpl(InvocationContext invocationContext) {
			return Flowable.empty();
		}

		@Override
		protected Flowable<Event> runLiveImpl(InvocationContext invocationContext) {
			return Flowable.empty();
		}

	}

	private static class AnotherConcreteBaseAgent extends BaseAgent {

		public AnotherConcreteBaseAgent(String name, String description, List<? extends BaseAgent> subAgents,
				List<? extends BeforeAgentCallback> beforeAgentCallback,
				List<? extends AfterAgentCallback> afterAgentCallback) {
			super(name, description, subAgents, beforeAgentCallback, afterAgentCallback);
		}

		@Override
		protected Flowable<Event> runAsyncImpl(InvocationContext invocationContext) {
			return Flowable.empty();
		}

		@Override
		protected Flowable<Event> runLiveImpl(InvocationContext invocationContext) {
			return Flowable.empty();
		}

	}

}
