/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test maven-adkjava-github using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=runAsyncImpl_d6001493a1
ROOST_METHOD_SIG_HASH=runAsyncImpl_99c1534d6f

Scenario 1: Returns Empty Flowable When Sub-Agents List Is Null

Details:
  TestName: returnsEmptyFlowableWhenSubAgentsIsNull
  Description: This test checks the scenario where the subAgents() method returns null. The runAsyncImpl method is expected to immediately return an empty Flowable in this case, skipping iteration and agent execution entirely.
Execution:
  Arrange: Create a LoopAgent instance where the subAgents() method returns null by mocking or subclassing if necessary.
  Act: Call runAsyncImpl with any valid (or mock) InvocationContext.
  Assert: Verify that the returned Flowable is empty and emits no events.
Validation:
  The assertion confirms that the method guards against a null list of sub-agents, preventing any NullPointerException and conforming with defensive programming expectations.
  This test validates robustness and fail-safe behavior in the case of unexpected null lists.


Scenario 2: Returns Empty Flowable When Sub-Agents List Is Empty

Details:
  TestName: returnsEmptyFlowableWhenSubAgentsIsEmpty
  Description: This test checks the scenario where subAgents() returns an empty list. runAsyncImpl should yield an empty Flowable, performing no iterations or agent executions.
Execution:
  Arrange: Instantiate LoopAgent with an empty list of sub-agents.
  Act: Invoke runAsyncImpl with a valid InvocationContext.
  Assert: Assert that the returned Flowable completes without emitting any events.
Validation:
  The assertion ensures that the method behaves correctly for zero sub-agents, avoiding unnecessary processing.
  This test is significant as it checks for correct handling of lower boundary input (empty lists).


Scenario 3: Executes All Sub-Agents In One Iteration When No Max Iterations And No Escalate

Details:
  TestName: executesAllSubAgentsOnceIfNoMaxIterationsAndNoEscalate
  Description: Tests the case where maxIterations is not set (Optional.empty()), there is more than one sub-agent, and none escalate. Expects the Flowable to iterate sub-agents in sequence and repeat indefinitely (or up to Integer.MAX_VALUE), unless interrupted.
Execution:
  Arrange: Create a LoopAgent with several mock BaseAgent sub-agents, all of which return a Flowable emitting Events with escalate() always Optional.of(false). Do not set maxIterations.
  Act: Call runAsyncImpl with a valid InvocationContext, but limit consumption to a reasonable number of total events (e.g., N).
  Assert: Verify that the sequence of events matches repeated cycles of all sub-agents, up to the specified limit.
Validation:
  The assertion verifies that, in the absence of both escalate actions and maxIterations, the loop will repeat effectively forever, always in the correct sub-agent order.
  This tests the core looping behavior over sub-agents.


Scenario 4: Stops When Sub-Agent Reports Escalate Action

Details:
  TestName: stopsIterationWhenSubAgentEscalates
  Description: Verifies the loop halts if any sub-agent emits an Event where escalate() is Optional.of(true), even before reaching maxIterations.
Execution:
  Arrange: Create a LoopAgent with mock sub-agents. Configure one to emit an Event where escalate() is Optional.of(true) during the first cycle.
  Act: Call runAsyncImpl and collect all emitted events.
  Assert: Assert that the Flowable completes right after the escalate event, with no further sub-agent executions.
Validation:
  The assertion ensures that the takeUntil condition triggers completion as soon as escalate is detected, overriding repeat iterations.
  This is significant because it validates termination of the loop on escalate, a primary use case.


Scenario 5: Loops Up To MaxIterations When Provided And No Escalate

Details:
  TestName: loopsUpToMaxIterationsWhenNoEscalate
  Description: Tests that when maxIterations is specified and no event escalates, the loop repeats for exactly maxIterations cycles of all sub-agents.
Execution:
  Arrange: Build a LoopAgent with several stub sub-agents, all emitting non-escalate events, and set maxIterations to a specific integer (e.g., 3).
  Act: Call runAsyncImpl and collect the events until completion.
  Assert: Verify that all sub-agents were run exactly maxIterations times, in their original order, with correct total event count.
Validation:
  This assertion checks boundary adherence to the maximum iteration setting, confirming repeat behavior is capped as specified.
  It validates correct integration of the maxIterations field.


Scenario 6: Handles One Sub-Agent Repeating Multiple Iterations

Details:
  TestName: handlesSingleSubAgentMultipleIterations
  Description: Tests that even with only a single sub-agent, repeated iterations occur as per the rules (i.e., up to maxIterations or escalate).
Execution:
  Arrange: Use a LoopAgent with a single mock sub-agent returning non-escalate events, and a fixed maxIterations value.
  Act: Run runAsyncImpl and count the number of event emissions.
  Assert: Ensure the number of event emissions matches maxIterations.
Validation:
  This verifies that the repeat/loop logic does not depend on the plurality of sub-agents and functions for the single-agent case.
  It confirms correct behavior on the minimum (nonempty) sub-agent list size.


Scenario 7: No Iterations If Sub-Agent Emits Only Escalate On First Event

Details:
  TestName: stopsImmediatelyIfFirstEventEscalates
  Description: Verifies that if the first emitted event from the first sub-agent already escalates, no further sub-agents or iterations occur.
Execution:
  Arrange: Construct LoopAgent where the first (or only) sub-agent emits an event with escalate() Optional.of(true).
  Act: Call runAsyncImpl and observe emitted events.
  Assert: Assert that only one event is emitted, after which the Flowable completes.
Validation:
  This tests the fast-exit path in the loop, ensuring that escalate handling is prioritized over both sub-agent order and iteration count.
  It’s significant as an edge-case focusing on termination logic.


Scenario 8: Uses Default Max Iterations Of Integer.MAX_VALUE When Not Set

Details:
  TestName: usesDefaultMaxIterationsIfNotProvided
  Description: Verifies that when maxIterations is not specified (i.e., Optional.empty()), the repeat uses Integer.MAX_VALUE as the default cap.
Execution:
  Arrange: Setup a LoopAgent with several non-escalating sub-agents and no maxIterations.
  Act: Call runAsyncImpl and take a sample (e.g., first 10*number_of_sub_agents events).
  Assert: Verify the correct order and number of repeated emissions, ensuring no premature termination.
Validation:
  The test confirms default control-flow—a core expectation for users not specifying a maximum.
  Ensures no unexpected caps or interruptions occur by default.


Scenario 9: Handles Null Event Actions Safely In Escalate Check

Details:
  TestName: handlesNullActionsInEscalateCheckGracefully
  Description: Verifies that if sub-agent events provide a null actions() return or escalate() is Optional.empty(), the loop does not terminate unexpectedly nor throw exceptions.
Execution:
  Arrange: Mock sub-agents to emit Events whose actions() method returns null or escalate() method returns Optional.empty().
  Act: Run runAsyncImpl for several iterations.
  Assert: Observe that the Flowable does not terminate on those events and emits as expected for configured iterations.
Validation:
  This checks defensive handling in takeUntil’s hasEscalateAction predicate, ensuring robustness to non-strict or partially implemented Event subclasses.
  Ensures correct functioning even in the face of incomplete event data.


Scenario 10: Propagates Sub-Agent Flowable Errors Upwards

Details:
  TestName: propagatesSubAgentErrors
  Description: Checks that if a sub-agent’s runAsync returns a Flowable that errors (throws or terminates with error), the main Flowable from runAsyncImpl propagates that error accordingly.
Execution:
  Arrange: Mock one sub-agent whose runAsync returns an erroring Flowable.
  Act: Invoke runAsyncImpl and subscribe, expecting an error.
  Assert: Assert that the subscription receives the same error.
Validation:
  Ensures correct error propagation logic, allowing consumers of LoopAgent to respond to sub-agent failures as designed.
  Essential for robust error handling in production systems.


Scenario 11: Skips Further Iterations If Escalate Occurs In Later Cycle

Details:
  TestName: stopsIfEscalateOccursInSubsequentIteration
  Description: Ensures that, even if an escalate event is not emitted until later iterations (not the first), the Flowable stops immediately when that event is seen.
Execution:
  Arrange: Setup sub-agents where escalate is only emitted in the second or third iteration cycle.
  Act: Call runAsyncImpl, subscribe, and collect events until the Flowable completes.
  Assert: Confirm that no events are emitted after the escalate event, and that the number of full iterations matches the cycle where escalate occurs.
Validation:
  This validates the repeat-takeUntil logic, confirming that escalation can end the run at any point.
  Important for business logic where escalate significance can appear later in processing.


Scenario 12: Handles MaxIterationsEqualsZeroReturnsNoEvents

Details:
  TestName: handlesMaxIterationsZeroReturnsNoEvents
  Description: Checks that if maxIterations is set to zero, the LoopAgent emits no events, regardless of sub-agent configuration.
Execution:
  Arrange: Configure LoopAgent with several sub-agents but set maxIterations to 0.
  Act: Call runAsyncImpl.
  Assert: Assert that the returned Flowable is empty and never emits any events.
Validation:
  This covers an additional boundary condition confirming that a zero-iteration cap is respected.
  Important for validation of input parameter edge cases.


Scenario 13: Posts All Events Even If escalate() Optional Is Missing

Details:
  TestName: emitsAllEventsWhenEscalateOptionalIsEmpty
  Description: Ensures that if escalate() always returns Optional.empty() in all event actions, the iteration completes as per maxIterations (or defaults to Integer.MAX_VALUE), without premature termination.
Execution:
  Arrange: Create sub-agents whose events’ escalate() method always returns Optional.empty(), and set maxIterations to a finite number.
  Act: Run runAsyncImpl and count the total number of emitted events.
  Assert: Confirm that all sub-agents’ events are emitted for all iterations, with none being skipped or causing early termination.
Validation:
  This ensures Optional semantics are handled properly in escalate checks.
  Important for supporting flexible Event action representations.


Scenario 14: Throws If subAgents() Throws An Exception

Details:
  TestName: throwsIfSubAgentsMethodThrowsException
  Description: Validates that if subAgents(), as called inside runAsyncImpl, itself throws an exception, the method propagates the error via the returned Flowable.
Execution:
  Arrange: Subclass or mock LoopAgent so that subAgents() throws a RuntimeException when invoked.
  Act: Call runAsyncImpl and subscribe, catching error.
  Assert: The Flowable terminates with the same exception.
Validation:
  Verifies defensive error propagation around foundational agent configuration issues.
  Important for guarding against unexpected errors from subclass overrides or data corruption.


Scenario 15: Handles Empty Event Sequences From Sub-Agents

Details:
  TestName: handlesSubAgentsThatEmitNoEvents
  Description: Ensures that if sub-agents produce empty Flowables (no events emitted), the overall result is also empty regardless of maxIterations.
Execution:
  Arrange: Set up all sub-agents’ runAsync method to return Flowable.empty().
  Act: Call runAsyncImpl.
  Assert: Assert that the returned Flowable emits no events.
Validation:
  Confirms consistent handling when sub-agents contribute no output events.
  Important for edge cases and predictable contract semantics.


Scenario 16: Correctly Resets Sub-Agent Sequence On Each Iteration

Details:
  TestName: resetsSubAgentOrderOnEachRepeatIteration
  Description: Checks that sub-agents are run in the specified order on every loop iteration, ensuring sequence integrity across all iterations.
Execution:
  Arrange: Provide several sub-agents with unique identifiers, configure maxIterations to 2, and track the emitted events’ order.
  Act: Call runAsyncImpl.
  Assert: Verify the interleaved events follow [A, B, C, A, B, C] (for 3 agents, for example).
Validation:
  Validates maintenance of proper iteration and agent order.
  Critical for logic where sub-agent order is meaningful for business rules.


*/

// ********RoostGPT********

package com.google.adk.agents;

import com.google.adk.events.Event;
import com.google.common.collect.ImmutableList;
import io.reactivex.rxjava3.core.Flowable;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.AdditionalAnswers;
import org.mockito.ArgumentCaptor;
import org.mockito.Mockito;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicInteger;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import com.google.errorprone.annotations.CanIgnoreReturnValue;

class LoopAgentRunAsyncImplTest {

	private InvocationContext mockCtx;

	@BeforeEach
	public void setUp() {
		mockCtx = mock(InvocationContext.class);
	}

	private static class MinimalEvent implements Event {

		private final Optional<Event.Actions> actions;

		MinimalEvent(Optional<Event.Actions> actions) {
			this.actions = actions;
		}

		@Override
		public Optional<Actions> actions() {
			return actions;
		}

	}

	private static class MinimalActions implements Event.Actions {

		private final Optional<Boolean> escalate;

		MinimalActions(Optional<Boolean> escalate) {
			this.escalate = escalate;
		}

		@Override
		public Optional<Boolean> escalate() {
			return escalate;
		}

	}

	static LoopAgent createLoopAgentWithSubAgentsAndMax(List<? extends BaseAgent> sa, Optional<Integer> max) {
		// Use a public Builder if available, or a public static builder() method.
		// Simulate a public static builder() as per Java convention.
		LoopAgent.Builder builder = new LoopAgent.Builder().withName("Agent") // TODO:
																				// customize
																				// if
																				// needed
			.withDescription("desc") // TODO: customize if needed
			.withSubAgents(sa);
		max.ifPresent(builder::withMaxIterations);
		return builder.build();
	}

	@Test
	@Tag("boundary")
	public void returnsEmptyFlowableWhenSubAgentsIsNull() {
		LoopAgent agent = new LoopAgent.Builder() {
			@Override
			public List<? extends BaseAgent> subAgents() {
				return null;
			}
		}.withName("Agent").withDescription("desc").withSubAgents(null).build();
		Flowable<Event> result = agent.runAsyncImpl(mockCtx);
		assertEquals(0, result.toList().blockingGet().size());
	}

	@Test
	@Tag("boundary")
	public void returnsEmptyFlowableWhenSubAgentsIsEmpty() {
		LoopAgent agent = createLoopAgentWithSubAgentsAndMax(Collections.emptyList(), Optional.empty());
		Flowable<Event> result = agent.runAsyncImpl(mockCtx);
		assertTrue(result.toList().blockingGet().isEmpty());
	}

	@Test
	@Tag("valid")
	public void executesAllSubAgentsOnceIfNoMaxIterationsAndNoEscalate() {
		int subAgentCnt = 3;
		BaseAgent[] agents = new BaseAgent[subAgentCnt];
		for (int i = 0; i < subAgentCnt; i++) {
			Event.Actions actions = mock(Event.Actions.class);
			when(actions.escalate()).thenReturn(Optional.of(false));
			Event event = mock(Event.class);
			when(event.actions()).thenReturn(Optional.of(actions));
			BaseAgent ag = mock(BaseAgent.class);
			when(ag.runAsync(any())).thenReturn(Flowable.just(event));
			agents[i] = ag;
		}
		LoopAgent agent = createLoopAgentWithSubAgentsAndMax(ImmutableList.copyOf(agents), Optional.empty());
		int limit = subAgentCnt * 5;
		List<Event> events = agent.runAsyncImpl(mockCtx).take(limit).toList().blockingGet();
		assertEquals(limit, events.size());
		for (int i = 0; i < limit; i++) {
			assertSame(agents[i % subAgentCnt].runAsync(mockCtx).blockingFirst(), events.get(i));
		}
	}

	@Test
	@Tag("valid")
	public void stopsIterationWhenSubAgentEscalates() {
		Event.Actions beforeEscalate = mock(Event.Actions.class);
		when(beforeEscalate.escalate()).thenReturn(Optional.of(false));
		Event.Actions escalate = mock(Event.Actions.class);
		when(escalate.escalate()).thenReturn(Optional.of(true));
		Event eventNormal = mock(Event.class);
		Event eventEscalate = mock(Event.class);
		when(eventNormal.actions()).thenReturn(Optional.of(beforeEscalate));
		when(eventEscalate.actions()).thenReturn(Optional.of(escalate));
		BaseAgent ag1 = mock(BaseAgent.class);
		BaseAgent ag2 = mock(BaseAgent.class);
		when(ag1.runAsync(any())).thenReturn(Flowable.just(eventNormal));
		when(ag2.runAsync(any())).thenReturn(Flowable.just(eventEscalate));
		LoopAgent agent = createLoopAgentWithSubAgentsAndMax(ImmutableList.of(ag1, ag2), Optional.empty());
		List<Event> events = agent.runAsyncImpl(mockCtx).toList().blockingGet();
		assertEquals(2, events.size());
		assertEquals(eventNormal, events.get(0));
		assertEquals(eventEscalate, events.get(1));
	}

	@Test
	@Tag("valid")
	public void loopsUpToMaxIterationsWhenNoEscalate() {
		int iterations = 3; // TODO: change if needed
		int nSubAgents = 2;
		BaseAgent[] subAgents = new BaseAgent[nSubAgents];
		for (int i = 0; i < nSubAgents; i++) {
			Event.Actions actions = mock(Event.Actions.class);
			when(actions.escalate()).thenReturn(Optional.of(false));
			Event event = mock(Event.class);
			when(event.actions()).thenReturn(Optional.of(actions));
			BaseAgent ag = mock(BaseAgent.class);
			when(ag.runAsync(any())).thenReturn(Flowable.just(event));
			subAgents[i] = ag;
		}
		LoopAgent agent = createLoopAgentWithSubAgentsAndMax(ImmutableList.copyOf(subAgents), Optional.of(iterations));
		List<Event> events = agent.runAsyncImpl(mockCtx).toList().blockingGet();
		assertEquals(iterations * nSubAgents, events.size());
	}

	@Test
	@Tag("boundary")
	public void handlesSingleSubAgentMultipleIterations() {
		int maxIterations = 5; // TODO if needed
		Event.Actions actions = mock(Event.Actions.class);
		when(actions.escalate()).thenReturn(Optional.of(false));
		Event event = mock(Event.class);
		when(event.actions()).thenReturn(Optional.of(actions));
		BaseAgent subAgent = mock(BaseAgent.class);
		when(subAgent.runAsync(any())).thenReturn(Flowable.just(event));
		LoopAgent agent = createLoopAgentWithSubAgentsAndMax(ImmutableList.of(subAgent), Optional.of(maxIterations));
		List<Event> events = agent.runAsyncImpl(mockCtx).toList().blockingGet();
		assertEquals(maxIterations, events.size());
	}

	@Test
	@Tag("boundary")
	public void stopsImmediatelyIfFirstEventEscalates() {
		Event.Actions escalate = mock(Event.Actions.class);
		when(escalate.escalate()).thenReturn(Optional.of(true));
		Event eventEscalate = mock(Event.class);
		when(eventEscalate.actions()).thenReturn(Optional.of(escalate));
		BaseAgent ag = mock(BaseAgent.class);
		when(ag.runAsync(any())).thenReturn(Flowable.just(eventEscalate));
		LoopAgent agent = createLoopAgentWithSubAgentsAndMax(ImmutableList.of(ag), Optional.of(10));
		List<Event> events = agent.runAsyncImpl(mockCtx).toList().blockingGet();
		assertEquals(1, events.size());
		assertSame(eventEscalate, events.get(0));
	}

	@Test
	@Tag("boundary")
	public void usesDefaultMaxIterationsIfNotProvided() {
		int nSubAgents = 2;
		int limit = nSubAgents * 10;
		BaseAgent[] agents = new BaseAgent[nSubAgents];
		for (int i = 0; i < nSubAgents; i++) {
			Event.Actions actions = mock(Event.Actions.class);
			when(actions.escalate()).thenReturn(Optional.of(false));
			Event event = mock(Event.class);
			when(event.actions()).thenReturn(Optional.of(actions));
			BaseAgent ag = mock(BaseAgent.class);
			when(ag.runAsync(any())).thenReturn(Flowable.just(event));
			agents[i] = ag;
		}
		LoopAgent agent = createLoopAgentWithSubAgentsAndMax(ImmutableList.copyOf(agents), Optional.empty());
		List<Event> events = agent.runAsyncImpl(mockCtx).take(limit).toList().blockingGet();
		assertEquals(limit, events.size());
	}

	@Test
	@Tag("valid")
	public void handlesNullActionsInEscalateCheckGracefully() {
		int iterations = 3;
		int nSubAgents = 1;
		Event eventNullActions = mock(Event.class);
		when(eventNullActions.actions()).thenReturn(null);
		Event.Actions actions = mock(Event.Actions.class);
		when(actions.escalate()).thenReturn(Optional.empty());
		Event eventEmptyOptional = mock(Event.class);
		when(eventEmptyOptional.actions()).thenReturn(Optional.of(actions));
		BaseAgent agentA = mock(BaseAgent.class);
		// alternate between null-actions and empty-optional
		when(agentA.runAsync(any())).thenReturn(Flowable.fromArray(eventNullActions, eventEmptyOptional));
		LoopAgent agent = createLoopAgentWithSubAgentsAndMax(ImmutableList.of(agentA), Optional.of(iterations));
		List<Event> events = agent.runAsyncImpl(mockCtx).take(iterations * 2).toList().blockingGet();
		assertEquals(iterations * 2, events.size());
	}

	@Test
	@Tag("invalid")
	public void propagatesSubAgentErrors() {
		RuntimeException ex = new RuntimeException("test");
		BaseAgent errorAgent = mock(BaseAgent.class);
		when(errorAgent.runAsync(any())).thenReturn(Flowable.error(ex));
		LoopAgent agent = createLoopAgentWithSubAgentsAndMax(ImmutableList.of(errorAgent), Optional.of(1));
		RuntimeException thrown = assertThrows(RuntimeException.class,
				() -> agent.runAsyncImpl(mockCtx).blockingForEach(ev -> {
				}));
		assertSame(ex, thrown);
	}

	@Test
	@Tag("integration")
	public void stopsIfEscalateOccursInSubsequentIteration() {
		BaseAgent a = mock(BaseAgent.class);
		Event.Actions actionsFalse = mock(Event.Actions.class);
		when(actionsFalse.escalate()).thenReturn(Optional.of(false));
		Event eventFalse = mock(Event.class);
		when(eventFalse.actions()).thenReturn(Optional.of(actionsFalse));
		Event.Actions actionsTrue = mock(Event.Actions.class);
		when(actionsTrue.escalate()).thenReturn(Optional.of(true));
		Event eventTrue = mock(Event.class);
		when(eventTrue.actions()).thenReturn(Optional.of(actionsTrue));
		// Will escalate in 3rd round
		when(a.runAsync(any())).thenReturn(Flowable.just(eventFalse))
			.thenReturn(Flowable.just(eventFalse))
			.thenReturn(Flowable.just(eventTrue));
		LoopAgent agent = createLoopAgentWithSubAgentsAndMax(ImmutableList.of(a), Optional.of(10));
		List<Event> events = agent.runAsyncImpl(mockCtx).toList().blockingGet();
		assertEquals(3, events.size());
		assertEquals(eventTrue, events.get(2));
	}

	@Test
	@Tag("boundary")
	public void handlesMaxIterationsZeroReturnsNoEvents() {
		BaseAgent ag = mock(BaseAgent.class);
		when(ag.runAsync(any())).thenReturn(Flowable.create(emitter -> emitter.onNext(mock(Event.class)),
				io.reactivex.rxjava3.core.BackpressureStrategy.BUFFER));
		LoopAgent agent = createLoopAgentWithSubAgentsAndMax(ImmutableList.of(ag), Optional.of(0));
		List<Event> events = agent.runAsyncImpl(mockCtx).toList().blockingGet();
		assertEquals(0, events.size());
	}

	@Test
	@Tag("valid")
	public void emitsAllEventsWhenEscalateOptionalIsEmpty() {
		int maxIterations = 4;
		int nAgents = 2;
		BaseAgent[] agents = new BaseAgent[nAgents];
		for (int i = 0; i < nAgents; i++) {
			Event.Actions actions = mock(Event.Actions.class);
			when(actions.escalate()).thenReturn(Optional.empty());
			Event event = mock(Event.class);
			when(event.actions()).thenReturn(Optional.of(actions));
			BaseAgent ag = mock(BaseAgent.class);
			when(ag.runAsync(any())).thenReturn(Flowable.just(event));
			agents[i] = ag;
		}
		LoopAgent agent = createLoopAgentWithSubAgentsAndMax(ImmutableList.copyOf(agents), Optional.of(maxIterations));
		List<Event> events = agent.runAsyncImpl(mockCtx).toList().blockingGet();
		assertEquals(maxIterations * nAgents, events.size());
	}

	@Test
	@Tag("invalid")
	public void throwsIfSubAgentsMethodThrowsException() {
		LoopAgent agent = new LoopAgent.Builder() {
			@Override
			public List<? extends BaseAgent> subAgents() {
				throw new RuntimeException("boom");
			}
		}.withName("Agent").withDescription("desc").withSubAgents(null).build();
		RuntimeException ex = assertThrows(RuntimeException.class,
				() -> agent.runAsyncImpl(mockCtx).blockingForEach(e -> {
				}));
		assertEquals("boom", ex.getMessage());
	}

	@Test
	@Tag("boundary")
	public void handlesSubAgentsThatEmitNoEvents() {
		BaseAgent ag = mock(BaseAgent.class);
		when(ag.runAsync(any())).thenReturn(Flowable.empty());
		LoopAgent agent = createLoopAgentWithSubAgentsAndMax(ImmutableList.of(ag), Optional.of(3));
		List<Event> events = agent.runAsyncImpl(mockCtx).toList().blockingGet();
		assertEquals(0, events.size());
	}

	@Test
    @Tag("integration")
    public void resetsSubAgentOrderOnEachRepeatIteration() {
        BaseAgent a = mock(BaseAgent.class, Mockito.withSettings().name("A"));
        BaseAgent b = mock(BaseAgent.class, Mockito.withSettings().name("B"));
        BaseAgent c = mock(BaseAgent.class, Mockito.withSettings().name("C"));
        List<String> agentOrder = ImmutableList.of("A", "B", "C");
        int maxIterations = 2;
        Event.Actions act = mock(Event.Actions.class);
        when(act.escalate()).thenReturn(Optional.of(false));
        // Identify event by agent name for assertion
        when(a.runAsync(any())).thenReturn(Flowable.just(new MinimalEvent(Optional.of(act))) {
            @Override public String toString() { return "A-event"; }
        });
        when(b.runAsync(any())).thenReturn(Flowable.just(new MinimalEvent(Optional.of(act))) {
            @Override public String toString() { return "B-event"; }
        });
        when(c.runAsync(any())).thenReturn(Flowable.just(new MinimalEvent(Optional.of(act))) {
            @Override public String toString() { return "C-event"; }
        });
        List<BaseAgent> subs = ImmutableList.of(a, b, c);
        LoopAgent agent = createLoopAgentWithSubAgentsAndMax(subs, Optional.of(maxIterations));
        List<Event> events = agent.runAsyncImpl(mockCtx).toList().blockingGet();
        assertEquals(6, events.size());
        // Spot-check events are in correct iteration order
        // They should be [A, B, C, A, B, C]
        for (int i = 0; i < maxIterations; i++) {
            for (int j = 0; j < subs.size(); j++) {
                int idx = i * subs.size() + j;
                assertEquals(subs.get(j).runAsync(mockCtx).blockingFirst().getClass(), events.get(idx).getClass());
            }
        }
    }

}