/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-maven-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=loadAgent_a181772a71
ROOST_METHOD_SIG_HASH=loadAgent_3a5efc3d63

Scenario 1: Successfully Load Agent When Agent Exists

Details:
  TestName: loadAgentWhenAgentExistsReturnsAgent
  Description: This test verifies that the loadAgent method successfully retrieves and returns a BaseAgent when the agent name exists in the agentSuppliers map. It tests the happy path where a valid agent name is provided and the corresponding supplier is present.

Execution:
  Arrange: Create a mock BaseAgent instance and a Supplier that returns this agent. Add the supplier to the agentSuppliers map with a specific agent name (e.g., "testAgent"). Set up the ConfigAgentLoader instance with the populated agentSuppliers map.
  Act: Call the loadAgent method with the agent name "testAgent".
  Assert: Verify that the returned BaseAgent is not null and is the same instance as the mock agent created in the Arrange step.

Validation:
  The assertion verifies that when a valid agent name is provided, the loadAgent method correctly retrieves the supplier from the agentSuppliers ConcurrentHashMap and invokes the get() method to obtain the BaseAgent instance. This is the primary use case for the method and ensures that the agent loading mechanism works correctly when agents are properly registered in the system. This test is critical for validating the core functionality of the agent loading system.

---

Scenario 2: Throw NoSuchElementException When Agent Does Not Exist

Details:
  TestName: loadAgentWhenAgentNotFoundThrowsNoSuchElementException
  Description: This test ensures that the loadAgent method throws a NoSuchElementException when attempting to load an agent that does not exist in the agentSuppliers map. It validates the error handling behavior for invalid agent names.

Execution:
  Arrange: Create a ConfigAgentLoader instance with an empty or populated agentSuppliers map that does not contain the agent name that will be requested (e.g., "nonExistentAgent").
  Act: Call the loadAgent method with the non-existent agent name "nonExistentAgent".
  Assert: Verify that a NoSuchElementException is thrown with the expected error message "Agent not found: nonExistentAgent".

Validation:
  This assertion confirms that the method properly handles the case where an invalid or non-existent agent name is provided. The NoSuchElementException is the appropriate exception type for this scenario as it clearly indicates that the requested element (agent) could not be found in the collection. This test is essential for ensuring proper error handling and preventing null pointer exceptions or undefined behavior when invalid agent names are used. It also validates that the error message provides clear information about which agent was not found, aiding in debugging.

---

Scenario 3: Load Agent With Null Agent Name

Details:
  TestName: loadAgentWithNullNameThrowsNoSuchElementException
  Description: This test verifies the behavior of the loadAgent method when a null value is passed as the agent name parameter. It ensures that the method handles null input appropriately.

Execution:
  Arrange: Create a ConfigAgentLoader instance with a populated agentSuppliers map containing at least one valid agent entry.
  Act: Call the loadAgent method with null as the agent name parameter.
  Assert: Verify that a NoSuchElementException is thrown, as the map.get(null) operation will return null, triggering the exception condition.

Validation:
  This test validates that the method handles null input gracefully by throwing a NoSuchElementException rather than causing a NullPointerException. Since ConcurrentHashMap.get(null) returns null (as the map doesn't contain a null key), the supplier will be null, and the method will throw the expected exception. This is important for defensive programming and ensures that the method behaves predictably with invalid input. The test confirms that null safety is maintained throughout the method execution.

---

Scenario 4: Load Agent With Empty String Name

Details:
  TestName: loadAgentWithEmptyStringNameThrowsNoSuchElementException
  Description: This test checks the behavior when an empty string is provided as the agent name. It ensures that empty strings are treated as invalid agent names and handled appropriately.

Execution:
  Arrange: Create a ConfigAgentLoader instance with a populated agentSuppliers map that does not contain an empty string as a key.
  Act: Call the loadAgent method with an empty string ("") as the agent name.
  Assert: Verify that a NoSuchElementException is thrown with the message "Agent not found: ".

Validation:
  This assertion ensures that empty strings are not treated as valid agent names unless explicitly registered. This test is important for validating input validation and preventing potential issues where empty strings might be accidentally used as agent identifiers. It confirms that the method consistently applies the same validation logic regardless of whether the input is null, empty, or a non-existent agent name.

---

Scenario 5: Load Multiple Different Agents Sequentially

Details:
  TestName: loadMultipleAgentsSequentiallyReturnsCorrectAgents
  Description: This test verifies that the loadAgent method can correctly load multiple different agents in sequence, ensuring that each call returns the appropriate agent instance without interference.

Execution:
  Arrange: Create multiple mock BaseAgent instances (e.g., agent1, agent2, agent3) with different names. Create suppliers for each agent and add them to the agentSuppliers map with distinct keys ("agent1", "agent2", "agent3").
  Act: Call the loadAgent method multiple times with different agent names in sequence: loadAgent("agent1"), loadAgent("agent2"), loadAgent("agent3").
  Assert: Verify that each call returns the correct corresponding agent instance and that the agents are distinct from each other.

Validation:
  This test validates that the loadAgent method maintains proper isolation between different agent instances and that the agentSuppliers map correctly manages multiple entries. It ensures that there is no cross-contamination or caching issues when loading different agents. This is crucial for multi-agent systems where multiple agents need to coexist and be loaded independently. The test confirms the thread-safe nature of the ConcurrentHashMap and the reliability of the supplier pattern.

---

Scenario 6: Load Same Agent Multiple Times

Details:
  TestName: loadSameAgentMultipleTimesReturnsSameOrNewInstance
  Description: This test examines the behavior when the same agent is loaded multiple times. It verifies whether the supplier returns the same instance or creates new instances, depending on the supplier implementation (memoized vs non-memoized).

Execution:
  Arrange: Create a mock BaseAgent instance and a Supplier (either memoized or non-memoized based on the actual implementation). Add the supplier to the agentSuppliers map with a specific agent name.
  Act: Call the loadAgent method multiple times with the same agent name (e.g., three consecutive calls to loadAgent("testAgent")).
  Assert: Verify the behavior based on the supplier type. If using Suppliers.memoize(), assert that all calls return the same instance. If using a regular supplier, verify that new instances may be created.

Validation:
  This test is important for understanding the caching behavior of the agent loading mechanism. Based on the class implementation using Suppliers.memoize(), the test should verify that the same agent instance is returned on subsequent calls, which is efficient for resource management. This validates that the memoization pattern is working correctly and that agents are not unnecessarily recreated on each load request, which could be expensive in terms of memory and initialization time.

---

Scenario 7: Load Agent After Supplier Returns Null

Details:
  TestName: loadAgentWhenSupplierReturnsNullReturnsNull
  Description: This test verifies the behavior when a supplier exists in the map but returns null when invoked. It checks whether the method handles null returns from suppliers gracefully.

Execution:
  Arrange: Create a Supplier that returns null when get() is called. Add this supplier to the agentSuppliers map with a specific agent name (e.g., "nullAgent").
  Act: Call the loadAgent method with the agent name "nullAgent".
  Assert: Verify that the method returns null without throwing an exception.

Validation:
  This test validates that the loadAgent method does not add additional null checks beyond verifying the supplier's existence. If a supplier is present but returns null, the method will return null to the caller. This behavior is consistent with the method's contract, which focuses on checking supplier existence rather than validating the supplier's return value. This test is important for understanding the method's boundaries and responsibilities, clarifying that null handling from suppliers is the caller's responsibility.

---

Scenario 8: Load Agent With Special Characters In Name

Details:
  TestName: loadAgentWithSpecialCharactersInNameReturnsAgent
  Description: This test verifies that the loadAgent method can handle agent names containing special characters, spaces, or non-alphanumeric characters, ensuring the map lookup works correctly with such keys.

Execution:
  Arrange: Create a mock BaseAgent instance and a supplier. Add the supplier to the agentSuppliers map with an agent name containing special characters (e.g., "agent-name_123", "agent.config", "agent name with spaces").
  Act: Call the loadAgent method with the special character agent name.
  Assert: Verify that the correct agent is returned and that the special characters do not interfere with the map lookup.

Validation:
  This assertion confirms that the ConcurrentHashMap correctly handles keys with special characters and that the string comparison works as expected. This is important for real-world scenarios where agent names might follow various naming conventions including hyphens, underscores, dots, or other special characters. The test ensures that the method is robust and can handle diverse naming patterns without issues.

---

Scenario 9: Load Agent With Case Sensitive Name

Details:
  TestName: loadAgentWithDifferentCaseThrowsNoSuchElementException
  Description: This test verifies that agent name lookup is case-sensitive, ensuring that "Agent1" and "agent1" are treated as different agent names.

Execution:
  Arrange: Create a mock BaseAgent and supplier, and add it to the agentSuppliers map with the key "Agent1" (capital A).
  Act: Call the loadAgent method with "agent1" (lowercase a).
  Assert: Verify that a NoSuchElementException is thrown, confirming that the lookup is case-sensitive.

Validation:
  This test validates that the method performs exact string matching when looking up agents in the map. Case sensitivity is important for maintaining consistency and avoiding ambiguity in agent identification. This test ensures that developers cannot accidentally load the wrong agent due to case mismatches and that the system enforces strict naming conventions. It confirms that the ConcurrentHashMap's default behavior of case-sensitive key comparison is preserved.

---

Scenario 10: Concurrent Load Requests For Same Agent

Details:
  TestName: concurrentLoadRequestsForSameAgentHandledCorrectly
  Description: This test verifies the thread-safety of the loadAgent method when multiple threads attempt to load the same agent simultaneously. It ensures that the ConcurrentHashMap and supplier mechanism work correctly under concurrent access.

Execution:
  Arrange: Create a mock BaseAgent and a memoized supplier. Add the supplier to the agentSuppliers map. Create multiple threads that will simultaneously call loadAgent with the same agent name.
  Act: Start multiple threads (e.g., 10 threads) that each call loadAgent("testAgent") simultaneously.
  Assert: Verify that all threads successfully retrieve an agent instance without exceptions, and if using memoized suppliers, verify that all threads receive the same instance.

Validation:
  This test is critical for validating the thread-safety guarantees of the ConfigAgentLoader class, which is annotated with @ThreadSafe. The ConcurrentHashMap ensures thread-safe access to the agentSuppliers map, and the memoized supplier ensures that only one instance is created even under concurrent access. This test confirms that the method can handle high-concurrency scenarios without race conditions, deadlocks, or inconsistent state. It validates that the implementation is suitable for multi-threaded environments.

---

Scenario 11: Concurrent Load Requests For Different Agents

Details:
  TestName: concurrentLoadRequestsForDifferentAgentsHandledCorrectly
  Description: This test verifies that multiple threads can simultaneously load different agents without interference or blocking, ensuring optimal concurrency performance.

Execution:
  Arrange: Create multiple mock BaseAgent instances and suppliers, and add them to the agentSuppliers map with different keys (e.g., "agent1", "agent2", "agent3"). Create multiple threads, each assigned to load a different agent.
  Act: Start multiple threads simultaneously, with each thread calling loadAgent with a different agent name.
  Assert: Verify that all threads successfully retrieve their respective agents without exceptions and that each thread receives the correct agent instance corresponding to its requested name.

Validation:
  This test validates that the ConcurrentHashMap allows concurrent access to different keys without blocking, ensuring good performance in multi-threaded scenarios. It confirms that the loadAgent method does not introduce unnecessary synchronization that would serialize access to different agents. This is important for scalability in systems where multiple agents need to be loaded simultaneously by different parts of the application.

---

Scenario 12: Load Agent With Very Long Name

Details:
  TestName: loadAgentWithVeryLongNameReturnsAgent
  Description: This test verifies that the loadAgent method can handle agent names of significant length without issues, ensuring there are no string length limitations in the implementation.

Execution:
  Arrange: Create a very long agent name (e.g., a string with 1000+ characters). Create a mock BaseAgent and supplier, and add it to the agentSuppliers map with the long name as the key.
  Act: Call the loadAgent method with the very long agent name.
  Assert: Verify that the correct agent is returned without any exceptions or performance issues.

Validation:
  This test ensures that the method does not impose artificial limitations on agent name length and that the underlying ConcurrentHashMap can handle long string keys efficiently. While extremely long agent names are unlikely in practice, this test validates the robustness of the implementation and ensures that edge cases related to string handling are properly managed.

---

Scenario 13: Load Agent When AgentSuppliers Map Is Empty

Details:
  TestName: loadAgentWhenMapIsEmptyThrowsNoSuchElementException
  Description: This test verifies the behavior when attempting to load an agent from an empty agentSuppliers map, ensuring proper error handling when no agents have been registered.

Execution:
  Arrange: Create a ConfigAgentLoader instance with an empty agentSuppliers map (no agents registered).
  Act: Call the loadAgent method with any agent name (e.g., "anyAgent").
  Assert: Verify that a NoSuchElementException is thrown with the appropriate error message.

Validation:
  This test validates the method's behavior in the edge case where the system has no agents registered. It ensures that the method fails gracefully with a clear error message rather than causing unexpected behavior. This is important for system initialization scenarios or error conditions where agent discovery might have failed, ensuring that the system provides clear feedback about the absence of agents.

---

Scenario 14: Load Agent With Whitespace-Only Name

Details:
  TestName: loadAgentWithWhitespaceOnlyNameThrowsNoSuchElementException
  Description: This test checks the behavior when an agent name consisting only of whitespace characters (spaces, tabs) is provided, ensuring such names are treated as invalid.

Execution:
  Arrange: Create a ConfigAgentLoader instance with a populated agentSuppliers map that does not contain whitespace-only keys.
  Act: Call the loadAgent method with a whitespace-only string (e.g., "   ", "\t\t").
  Assert: Verify that a NoSuchElementException is thrown.

Validation:
  This test ensures that whitespace-only strings are not treated as valid agent names unless explicitly registered. It validates input handling for edge cases involving whitespace, which could potentially cause issues if not properly handled. The test confirms that the method treats whitespace-only names the same as any other non-existent agent name, maintaining consistency in error handling.

---

Scenario 15: Load Agent After Supplier Throws Exception

Details:
  TestName: loadAgentWhenSupplierThrowsExceptionPropagatesException
  Description: This test verifies the behavior when a supplier exists but throws an exception when its get() method is invoked, ensuring that exceptions from suppliers are properly propagated to the caller.

Execution:
  Arrange: Create a Supplier that throws a RuntimeException (or any other exception) when get() is called. Add this supplier to the agentSuppliers map with a specific agent name.
  Act: Call the loadAgent method with the agent name.
  Assert: Verify that the exception thrown by the supplier is propagated to the caller without being caught or wrapped by the loadAgent method.

Validation:
  This test validates that the loadAgent method does not suppress or alter exceptions thrown by suppliers during agent instantiation. This is important for proper error handling and debugging, as it allows the caller to receive the original exception with its full stack trace and context. The test confirms that the method acts as a transparent pass-through for supplier exceptions, which is the expected behavior for this type of delegation pattern.

*/

// ********RoostGPT********

package com.google.adk.maven;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.agents.BaseAgent;
import java.nio.file.Path;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.Supplier;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

class ConfigAgentLoaderLoadAgentTest {

  @TempDir Path tempDir;

  private ConfigAgentLoader configAgentLoader;

  private Map<String, Supplier<BaseAgent>> agentSuppliers;

  @Mock private BaseAgent mockAgent;

  @Mock private BaseAgent mockAgent1;

  @Mock private BaseAgent mockAgent2;

  @Mock private BaseAgent mockAgent3;

  @BeforeEach
  void setUp() throws Exception {
    MockitoAnnotations.openMocks(this);
    configAgentLoader = new ConfigAgentLoader(tempDir.toString(), false);

    java.lang.reflect.Field field = ConfigAgentLoader.class.getDeclaredField("agentSuppliers");
    field.setAccessible(true);
    agentSuppliers = (Map<String, Supplier<BaseAgent>>) field.get(configAgentLoader);
    agentSuppliers.clear();
  }

  @Test
  @Tag("valid")
  void loadAgentWhenAgentExistsReturnsAgent() {
    when(mockAgent.name()).thenReturn("testAgent");
    Supplier<BaseAgent> supplier = () -> mockAgent;
    agentSuppliers.put("testAgent", supplier);
    BaseAgent result = configAgentLoader.loadAgent("testAgent");
    assertNotNull(result);
    assertSame(mockAgent, result);
  }

  @Test
  @Tag("invalid")
  void loadAgentWhenAgentNotFoundThrowsNoSuchElementException() {
    agentSuppliers.clear();
    NoSuchElementException exception =
        assertThrows(
            NoSuchElementException.class,
            () -> {
              configAgentLoader.loadAgent("nonExistentAgent");
            });
    assertEquals("Agent not found: nonExistentAgent", exception.getMessage());
  }

  @Test
  @Tag("invalid")
  void loadAgentWithNullNameThrowsNoSuchElementException() {
    when(mockAgent.name()).thenReturn("validAgent");
    Supplier<BaseAgent> supplier = () -> mockAgent;
    agentSuppliers.put("validAgent", supplier);
    NoSuchElementException exception =
        assertThrows(
            NoSuchElementException.class,
            () -> {
              configAgentLoader.loadAgent(null);
            });
    assertTrue(exception.getMessage().contains("Agent not found"));
  }

  @Test
  @Tag("boundary")
  void loadAgentWithEmptyStringNameThrowsNoSuchElementException() {
    when(mockAgent.name()).thenReturn("validAgent");
    Supplier<BaseAgent> supplier = () -> mockAgent;
    agentSuppliers.put("validAgent", supplier);
    NoSuchElementException exception =
        assertThrows(
            NoSuchElementException.class,
            () -> {
              configAgentLoader.loadAgent("");
            });
    assertEquals("Agent not found: ", exception.getMessage());
  }

  @Test
  @Tag("valid")
  void loadMultipleAgentsSequentiallyReturnsCorrectAgents() {
    when(mockAgent1.name()).thenReturn("agent1");
    when(mockAgent2.name()).thenReturn("agent2");
    when(mockAgent3.name()).thenReturn("agent3");
    Supplier<BaseAgent> supplier1 = () -> mockAgent1;
    Supplier<BaseAgent> supplier2 = () -> mockAgent2;
    Supplier<BaseAgent> supplier3 = () -> mockAgent3;
    agentSuppliers.put("agent1", supplier1);
    agentSuppliers.put("agent2", supplier2);
    agentSuppliers.put("agent3", supplier3);
    BaseAgent result1 = configAgentLoader.loadAgent("agent1");
    BaseAgent result2 = configAgentLoader.loadAgent("agent2");
    BaseAgent result3 = configAgentLoader.loadAgent("agent3");
    assertNotNull(result1);
    assertNotNull(result2);
    assertNotNull(result3);
    assertSame(mockAgent1, result1);
    assertSame(mockAgent2, result2);
    assertSame(mockAgent3, result3);
    assertNotSame(result1, result2);
    assertNotSame(result2, result3);
    assertNotSame(result1, result3);
  }

  @Test
  @Tag("valid")
  void loadSameAgentMultipleTimesReturnsSameOrNewInstance() {
    when(mockAgent.name()).thenReturn("testAgent");
    AtomicInteger callCount = new AtomicInteger(0);
    Supplier<BaseAgent> supplier =
        () -> {
          callCount.incrementAndGet();
          return mockAgent;
        };
    agentSuppliers.put("testAgent", supplier);
    BaseAgent result1 = configAgentLoader.loadAgent("testAgent");
    BaseAgent result2 = configAgentLoader.loadAgent("testAgent");
    BaseAgent result3 = configAgentLoader.loadAgent("testAgent");
    assertNotNull(result1);
    assertNotNull(result2);
    assertNotNull(result3);
    assertSame(mockAgent, result1);
    assertSame(mockAgent, result2);
    assertSame(mockAgent, result3);
    assertEquals(3, callCount.get());
  }

  @Test
  @Tag("boundary")
  void loadAgentWhenSupplierReturnsNullReturnsNull() {
    Supplier<BaseAgent> nullSupplier = () -> null;
    agentSuppliers.put("nullAgent", nullSupplier);
    BaseAgent result = configAgentLoader.loadAgent("nullAgent");
    assertNull(result);
  }

  @Test
  @Tag("valid")
  void loadAgentWithSpecialCharactersInNameReturnsAgent() {
    when(mockAgent.name()).thenReturn("agent-name_123");
    Supplier<BaseAgent> supplier = () -> mockAgent;
    agentSuppliers.put("agent-name_123", supplier);
    BaseAgent result = configAgentLoader.loadAgent("agent-name_123");
    assertNotNull(result);
    assertSame(mockAgent, result);
    when(mockAgent1.name()).thenReturn("agent.config");
    Supplier<BaseAgent> supplier2 = () -> mockAgent1;
    agentSuppliers.put("agent.config", supplier2);
    BaseAgent result2 = configAgentLoader.loadAgent("agent.config");
    assertNotNull(result2);
    assertSame(mockAgent1, result2);
    when(mockAgent2.name()).thenReturn("agent name with spaces");
    Supplier<BaseAgent> supplier3 = () -> mockAgent2;
    agentSuppliers.put("agent name with spaces", supplier3);
    BaseAgent result3 = configAgentLoader.loadAgent("agent name with spaces");
    assertNotNull(result3);
    assertSame(mockAgent2, result3);
  }

  @Test
  @Tag("valid")
  void loadAgentWithDifferentCaseThrowsNoSuchElementException() {
    when(mockAgent.name()).thenReturn("Agent1");
    Supplier<BaseAgent> supplier = () -> mockAgent;
    agentSuppliers.put("Agent1", supplier);
    NoSuchElementException exception =
        assertThrows(
            NoSuchElementException.class,
            () -> {
              configAgentLoader.loadAgent("agent1");
            });
    assertEquals("Agent not found: agent1", exception.getMessage());
  }

  @Test
  @Tag("integration")
  void concurrentLoadRequestsForSameAgentHandledCorrectly() throws InterruptedException {
    when(mockAgent.name()).thenReturn("testAgent");
    Supplier<BaseAgent> supplier = () -> mockAgent;
    agentSuppliers.put("testAgent", supplier);
    int threadCount = 10;
    ExecutorService executorService = Executors.newFixedThreadPool(threadCount);
    CountDownLatch latch = new CountDownLatch(threadCount);
    ConcurrentHashMap<Integer, BaseAgent> results = new ConcurrentHashMap<>();
    for (int i = 0; i < threadCount; i++) {
      final int index = i;
      executorService.submit(
          () -> {
            try {
              BaseAgent agent = configAgentLoader.loadAgent("testAgent");
              results.put(index, agent);
            } finally {
              latch.countDown();
            }
          });
    }
    latch.await(5, TimeUnit.SECONDS);
    executorService.shutdown();
    assertEquals(threadCount, results.size());
    for (BaseAgent agent : results.values()) {
      assertNotNull(agent);
      assertSame(mockAgent, agent);
    }
  }

  @Test
  @Tag("integration")
  void concurrentLoadRequestsForDifferentAgentsHandledCorrectly() throws InterruptedException {
    when(mockAgent1.name()).thenReturn("agent1");
    when(mockAgent2.name()).thenReturn("agent2");
    when(mockAgent3.name()).thenReturn("agent3");
    agentSuppliers.put("agent1", () -> mockAgent1);
    agentSuppliers.put("agent2", () -> mockAgent2);
    agentSuppliers.put("agent3", () -> mockAgent3);
    int threadCount = 9;
    ExecutorService executorService = Executors.newFixedThreadPool(threadCount);
    CountDownLatch latch = new CountDownLatch(threadCount);
    ConcurrentHashMap<String, BaseAgent> results = new ConcurrentHashMap<>();
    String[] agentNames = {"agent1", "agent2", "agent3"};
    for (int i = 0; i < threadCount; i++) {
      final String agentName = agentNames[i % 3];
      final int index = i;
      executorService.submit(
          () -> {
            try {
              BaseAgent agent = configAgentLoader.loadAgent(agentName);
              results.put(agentName + "_" + index, agent);
            } finally {
              latch.countDown();
            }
          });
    }
    latch.await(5, TimeUnit.SECONDS);
    executorService.shutdown();
    assertEquals(threadCount, results.size());
    for (Map.Entry<String, BaseAgent> entry : results.entrySet()) {
      assertNotNull(entry.getValue());
    }
  }

  @Test
  @Tag("boundary")
  void loadAgentWithVeryLongNameReturnsAgent() {
    String longName = "a".repeat(1000);
    when(mockAgent.name()).thenReturn(longName);
    Supplier<BaseAgent> supplier = () -> mockAgent;
    agentSuppliers.put(longName, supplier);
    BaseAgent result = configAgentLoader.loadAgent(longName);
    assertNotNull(result);
    assertSame(mockAgent, result);
  }

  @Test
  @Tag("boundary")
  void loadAgentWhenMapIsEmptyThrowsNoSuchElementException() {
    agentSuppliers.clear();
    NoSuchElementException exception =
        assertThrows(
            NoSuchElementException.class,
            () -> {
              configAgentLoader.loadAgent("anyAgent");
            });
    assertEquals("Agent not found: anyAgent", exception.getMessage());
  }

  @Test
  @Tag("boundary")
  void loadAgentWithWhitespaceOnlyNameThrowsNoSuchElementException() {
    when(mockAgent.name()).thenReturn("validAgent");
    Supplier<BaseAgent> supplier = () -> mockAgent;
    agentSuppliers.put("validAgent", supplier);
    NoSuchElementException exception1 =
        assertThrows(
            NoSuchElementException.class,
            () -> {
              configAgentLoader.loadAgent("   ");
            });
    assertEquals("Agent not found:    ", exception1.getMessage());
    NoSuchElementException exception2 =
        assertThrows(
            NoSuchElementException.class,
            () -> {
              configAgentLoader.loadAgent("\t\t");
            });
    assertEquals("Agent not found: \t\t", exception2.getMessage());
  }

  @Test
  @Tag("invalid")
  void loadAgentWhenSupplierThrowsExceptionPropagatesException() {
    Supplier<BaseAgent> throwingSupplier =
        () -> {
          throw new RuntimeException("Supplier error");
        };
    agentSuppliers.put("errorAgent", throwingSupplier);
    RuntimeException exception =
        assertThrows(
            RuntimeException.class,
            () -> {
              configAgentLoader.loadAgent("errorAgent");
            });
    assertEquals("Supplier error", exception.getMessage());
  }
}
