/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-jan-5 using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=loadAgent_a181772a71
ROOST_METHOD_SIG_HASH=loadAgent_3a5efc3d63

Scenario 1: Successfully Load Agent When Agent Name Exists

Details:
  TestName: loadAgentWhenAgentExistsReturnsAgent
  Description: This test verifies that the loadAgent method successfully retrieves and returns a BaseAgent when the provided agent name exists in the agentSuppliers map. The test ensures that the method correctly delegates to the supplier's get() method and returns the expected agent instance.

Execution:
  Arrange: Create a mock BaseAgent instance. Create a Supplier that returns this mock agent. Populate the agentSuppliers ConcurrentHashMap with an entry where the key is "testAgent" and the value is the supplier. Use reflection to inject the agentSuppliers map into the ConfigAgentLoader instance.
  Act: Invoke the loadAgent method with the agent name "testAgent".
  Assert: Verify that the returned BaseAgent is not null. Verify that the returned agent is the same instance as the mock agent created in the arrange step.

Validation:
  This assertion verifies that when an agent exists in the agentSuppliers map, the loadAgent method correctly retrieves and returns it. This is the primary happy path scenario and ensures the core functionality works as expected. The test is significant because it validates that the loader can successfully provide agents to consumers when they exist in the system.

---

Scenario 2: Throw NoSuchElementException When Agent Name Does Not Exist

Details:
  TestName: loadAgentWhenAgentNotFoundThrowsNoSuchElementException
  Description: This test verifies that the loadAgent method throws a NoSuchElementException when attempting to load an agent that does not exist in the agentSuppliers map. This ensures proper error handling for invalid agent names.

Execution:
  Arrange: Create a ConfigAgentLoader instance with an empty or minimal agentSuppliers map that does not contain the agent name "nonExistentAgent".
  Act: Invoke the loadAgent method with the agent name "nonExistentAgent".
  Assert: Verify that a NoSuchElementException is thrown. Verify that the exception message contains the text "Agent not found: nonExistentAgent".

Validation:
  This assertion verifies that the method properly handles the case where a requested agent does not exist. The NoSuchElementException is the appropriate exception type for this scenario, as it clearly indicates that the requested element (agent) was not found. This test is critical for ensuring that consumers of the API receive clear and actionable error messages when they request invalid agents.

---

Scenario 3: Load Agent With Null Agent Name

Details:
  TestName: loadAgentWithNullNameThrowsNoSuchElementException
  Description: This test verifies the behavior when null is passed as the agent name parameter. Since the Map.get() method will return null for a null key (assuming the map doesn't contain a null key), this should result in a NoSuchElementException being thrown.

Execution:
  Arrange: Create a ConfigAgentLoader instance with a populated agentSuppliers map that does not contain a null key.
  Act: Invoke the loadAgent method with null as the agent name parameter.
  Assert: Verify that a NoSuchElementException is thrown. Verify that the exception message contains "Agent not found: null".

Validation:
  This assertion verifies that the method handles null input gracefully by throwing an appropriate exception. This is important for defensive programming and ensures that the method doesn't fail with a NullPointerException or other unexpected error. The test validates that the API contract is clear about not accepting null values.

---

Scenario 4: Load Agent With Empty String Name

Details:
  TestName: loadAgentWithEmptyStringNameThrowsNoSuchElementException
  Description: This test verifies the behavior when an empty string is passed as the agent name. Unless an agent is explicitly registered with an empty string name, this should result in a NoSuchElementException.

Execution:
  Arrange: Create a ConfigAgentLoader instance with a populated agentSuppliers map that does not contain an empty string key.
  Act: Invoke the loadAgent method with an empty string "" as the agent name parameter.
  Assert: Verify that a NoSuchElementException is thrown. Verify that the exception message contains "Agent not found: ".

Validation:
  This assertion verifies that the method properly handles edge cases with empty string inputs. Empty strings are often problematic in string-based lookups, and this test ensures that the method treats them consistently with other non-existent agent names. This is important for maintaining predictable behavior across different input scenarios.

---

Scenario 5: Load Agent Multiple Times Returns Same Instance With Memoized Supplier

Details:
  TestName: loadAgentMultipleTimesWithMemoizedSupplierReturnsSameInstance
  Description: This test verifies that when using a memoized supplier (as indicated by the use of Suppliers.memoize in the class), calling loadAgent multiple times with the same agent name returns the same agent instance. This validates the caching behavior.

Execution:
  Arrange: Create a mock BaseAgent instance. Create a memoized Supplier using Suppliers.memoize that returns this mock agent. Populate the agentSuppliers map with an entry for "cachedAgent" using the memoized supplier. Use reflection to inject the agentSuppliers map into the ConfigAgentLoader instance.
  Act: Invoke the loadAgent method twice with the agent name "cachedAgent". Store both returned instances.
  Assert: Verify that both returned instances are not null. Verify that both instances are the exact same object reference (using == or assertSame).

Validation:
  This assertion verifies that the memoization pattern is working correctly, which is important for performance optimization. By returning the same instance on subsequent calls, the loader avoids repeatedly parsing YAML files and constructing agent objects. This test is significant for ensuring that the caching mechanism provides the expected performance benefits without creating unnecessary duplicate objects.

---

Scenario 6: Load Agent With Special Characters In Name

Details:
  TestName: loadAgentWithSpecialCharactersInName
  Description: This test verifies that the loadAgent method can handle agent names containing special characters, spaces, or non-alphanumeric characters. This ensures the method works with various naming conventions.

Execution:
  Arrange: Create a mock BaseAgent instance. Create a Supplier that returns this mock agent. Populate the agentSuppliers map with an entry where the key contains special characters, such as "agent-with-dashes_and_underscores.123". Use reflection to inject the agentSuppliers map into the ConfigAgentLoader instance.
  Act: Invoke the loadAgent method with the agent name "agent-with-dashes_and_underscores.123".
  Assert: Verify that the returned BaseAgent is not null. Verify that the returned agent is the expected mock agent instance.

Validation:
  This assertion verifies that the method can handle various naming conventions that might be used in real-world scenarios. Agent names derived from folder names or configuration files might contain special characters, and this test ensures the lookup mechanism works correctly regardless of the character composition. This is important for flexibility and robustness in production environments.

---

Scenario 7: Load Agent When Supplier Returns Null

Details:
  TestName: loadAgentWhenSupplierReturnsNull
  Description: This test verifies the behavior when an agent supplier exists in the map but returns null when invoked. This could happen if the agent loading process fails but doesn't throw an exception.

Execution:
  Arrange: Create a Supplier that returns null. Populate the agentSuppliers map with an entry for "nullAgent" using this null-returning supplier. Use reflection to inject the agentSuppliers map into the ConfigAgentLoader instance.
  Act: Invoke the loadAgent method with the agent name "nullAgent".
  Assert: Verify that the method returns null (or document the actual behavior if it throws an exception).

Validation:
  This assertion verifies how the method handles the edge case where a supplier exists but produces a null result. This could indicate a configuration error or a failed agent initialization. The test is important for understanding the method's contract and ensuring that consumers can handle this scenario appropriately. It also helps identify whether additional null-checking should be added to the method.

---

Scenario 8: Load Agent With Case Sensitive Name Matching

Details:
  TestName: loadAgentWithCaseSensitiveNameMatching
  Description: This test verifies that agent name matching is case-sensitive. An agent registered as "TestAgent" should not be retrievable using "testagent" or "TESTAGENT".

Execution:
  Arrange: Create a mock BaseAgent instance. Create a Supplier that returns this mock agent. Populate the agentSuppliers map with an entry for "TestAgent" (with specific casing). Use reflection to inject the agentSuppliers map into the ConfigAgentLoader instance.
  Act: Invoke the loadAgent method with the agent name "testagent" (different casing).
  Assert: Verify that a NoSuchElementException is thrown, confirming that the lookup is case-sensitive.

Validation:
  This assertion verifies that the agent lookup mechanism respects case sensitivity, which is important for maintaining consistency with file system behavior (especially on case-sensitive file systems). This test ensures that agents must be referenced with the exact name they were registered with, preventing ambiguity and potential errors in agent resolution.

---

Scenario 9: Load Agent From ConcurrentHashMap Ensures Thread Safety

Details:
  TestName: loadAgentFromConcurrentHashMapEnsuresThreadSafety
  Description: This test verifies that the loadAgent method can be safely called from multiple threads concurrently without causing race conditions or exceptions. This validates the thread-safety provided by ConcurrentHashMap.

Execution:
  Arrange: Create multiple mock BaseAgent instances. Create suppliers for each agent. Populate the agentSuppliers ConcurrentHashMap with multiple agent entries. Use reflection to inject the agentSuppliers map into the ConfigAgentLoader instance. Create multiple threads that will concurrently call loadAgent with different agent names.
  Act: Start all threads simultaneously and have them invoke loadAgent with various agent names. Wait for all threads to complete.
  Assert: Verify that all threads successfully retrieved their respective agents without throwing exceptions. Verify that no ConcurrentModificationException or other threading-related exceptions occurred.

Validation:
  This assertion verifies that the method is thread-safe and can handle concurrent access, which is critical given the @ThreadSafe annotation on the class. The use of ConcurrentHashMap should provide this safety, and this test confirms it. This is significant for production environments where multiple requests might simultaneously attempt to load agents.

---

Scenario 10: Load Agent After Agent Supplier Is Updated

Details:
  TestName: loadAgentAfterSupplierIsUpdated
  Description: This test verifies that if an agent supplier is updated in the agentSuppliers map (simulating a hot-reload scenario), the loadAgent method returns the agent from the new supplier on subsequent calls.

Execution:
  Arrange: Create two different mock BaseAgent instances (oldAgent and newAgent). Create a supplier for the old agent and populate the agentSuppliers map with it under the key "updatableAgent". Use reflection to inject the agentSuppliers map. Load the agent once to verify it returns oldAgent. Then update the agentSuppliers map entry to use a new supplier that returns newAgent.
  Act: Invoke the loadAgent method again with the agent name "updatableAgent" after the supplier has been updated.
  Assert: Verify that the returned agent is the newAgent instance, not the oldAgent. This confirms that the method uses the current supplier from the map.

Validation:
  This assertion verifies that the loadAgent method always uses the current supplier from the map, which is important for hot-reloading functionality. When configuration files change and suppliers are updated, subsequent calls to loadAgent should reflect these changes. This test is significant for validating the dynamic reloading capability of the ConfigAgentLoader, ensuring that updates are properly reflected without requiring a restart.

---

Scenario 11: Load Agent When Supplier Throws Exception

Details:
  TestName: loadAgentWhenSupplierThrowsException
  Description: This test verifies the behavior when an agent supplier exists but throws an exception when its get() method is invoked. This could happen if agent initialization fails due to configuration errors or resource unavailability.

Execution:
  Arrange: Create a Supplier that throws a RuntimeException when get() is called. Populate the agentSuppliers map with an entry for "faultyAgent" using this exception-throwing supplier. Use reflection to inject the agentSuppliers map into the ConfigAgentLoader instance.
  Act: Invoke the loadAgent method with the agent name "faultyAgent".
  Assert: Verify that the RuntimeException (or the specific exception thrown by the supplier) is propagated to the caller. Verify that the exception message or type matches what was thrown by the supplier.

Validation:
  This assertion verifies that exceptions from the supplier are properly propagated to the caller, allowing them to handle initialization failures appropriately. This is important for debugging and error handling, as it ensures that the root cause of agent loading failures is visible to consumers. The test validates that the method doesn't swallow exceptions or mask the underlying problem.

---

Scenario 12: Load Agent With Whitespace In Name

Details:
  TestName: loadAgentWithWhitespaceInName
  Description: This test verifies that the loadAgent method can handle agent names that contain leading, trailing, or internal whitespace characters. This ensures the method works with names that might come from user input or file system paths.

Execution:
  Arrange: Create a mock BaseAgent instance. Create a Supplier that returns this mock agent. Populate the agentSuppliers map with an entry where the key contains whitespace, such as " agent with spaces ". Use reflection to inject the agentSuppliers map into the ConfigAgentLoader instance.
  Act: Invoke the loadAgent method with the exact agent name " agent with spaces " (including the whitespace).
  Assert: Verify that the returned BaseAgent is not null. Verify that the returned agent is the expected mock agent instance.

Validation:
  This assertion verifies that the method performs exact string matching without trimming or normalizing whitespace. This is important for maintaining consistency with how agents are registered (likely from folder names) and ensures that the lookup mechanism is predictable. The test helps identify whether whitespace handling needs to be added or if the current behavior is acceptable.

*/

// ********RoostGPT********

package com.google.adk.maven;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.google.adk.agents.BaseAgent;
import com.google.common.base.Suppliers;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import java.lang.reflect.Field;
import java.nio.file.Path;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.Supplier;
import org.junit.jupiter.api.*;
import static java.util.stream.Collectors.toList;
import com.google.adk.agents.ConfigAgentUtils;
import com.google.adk.web.AgentLoader;
import com.google.common.collect.ImmutableList;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.stream.Stream;
import javax.annotation.Nonnull;
import javax.annotation.concurrent.ThreadSafe;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

class ConfigAgentLoaderLoadAgentTest {

	@TempDir
	Path tempDir;

	private ConfigAgentLoader configAgentLoader;

	private Map<String, Supplier<BaseAgent>> agentSuppliers;

	@BeforeEach
	void setUp() throws Exception {
		configAgentLoader = new ConfigAgentLoader(tempDir.toString(), false);
		agentSuppliers = new ConcurrentHashMap<>();
		injectAgentSuppliers(configAgentLoader, agentSuppliers);
	}

	private void injectAgentSuppliers(ConfigAgentLoader loader, Map<String, Supplier<BaseAgent>> suppliers)
			throws Exception {
		Field field = ConfigAgentLoader.class.getDeclaredField("agentSuppliers");
		field.setAccessible(true);
		field.set(loader, suppliers);
	}

	@Test
	@Tag("valid")
	void loadAgentWhenAgentExistsReturnsAgent() {
		BaseAgent mockAgent = mock(BaseAgent.class);
		Supplier<BaseAgent> supplier = () -> mockAgent;
		agentSuppliers.put("testAgent", supplier);
		BaseAgent result = configAgentLoader.loadAgent("testAgent");
		assertNotNull(result);
		assertSame(mockAgent, result);
	}

	@Test
	@Tag("invalid")
	void loadAgentWhenAgentNotFoundThrowsNoSuchElementException() {
		NoSuchElementException exception = assertThrows(NoSuchElementException.class, () -> {
			configAgentLoader.loadAgent("nonExistentAgent");
		});
		assertTrue(exception.getMessage().contains("Agent not found: nonExistentAgent"));
	}

	@Test
	@Tag("invalid")
	void loadAgentWithNullNameThrowsNoSuchElementException() {
		NoSuchElementException exception = assertThrows(NoSuchElementException.class, () -> {
			configAgentLoader.loadAgent(null);
		});
		assertTrue(exception.getMessage().contains("Agent not found: null"));
	}

	@Test
	@Tag("boundary")
	void loadAgentWithEmptyStringNameThrowsNoSuchElementException() {
		NoSuchElementException exception = assertThrows(NoSuchElementException.class, () -> {
			configAgentLoader.loadAgent("");
		});
		assertTrue(exception.getMessage().contains("Agent not found: "));
	}

	@Test
	@Tag("valid")
	void loadAgentMultipleTimesWithMemoizedSupplierReturnsSameInstance() {
		BaseAgent mockAgent = mock(BaseAgent.class);
		Supplier<BaseAgent> memoizedSupplier = Suppliers.memoize(() -> mockAgent);
		agentSuppliers.put("cachedAgent", memoizedSupplier);
		BaseAgent firstCall = configAgentLoader.loadAgent("cachedAgent");
		BaseAgent secondCall = configAgentLoader.loadAgent("cachedAgent");
		assertNotNull(firstCall);
		assertNotNull(secondCall);
		assertSame(firstCall, secondCall);
	}

	@Test
	@Tag("valid")
	void loadAgentWithSpecialCharactersInName() {
		BaseAgent mockAgent = mock(BaseAgent.class);
		Supplier<BaseAgent> supplier = () -> mockAgent;
		String specialName = "agent-with-dashes_and_underscores.123";
		agentSuppliers.put(specialName, supplier);
		BaseAgent result = configAgentLoader.loadAgent(specialName);
		assertNotNull(result);
		assertSame(mockAgent, result);
	}

	@Test
	@Tag("boundary")
	void loadAgentWhenSupplierReturnsNull() {
		Supplier<BaseAgent> nullSupplier = () -> null;
		agentSuppliers.put("nullAgent", nullSupplier);
		BaseAgent result = configAgentLoader.loadAgent("nullAgent");
		assertNull(result);
	}

	@Test
	@Tag("valid")
	void loadAgentWithCaseSensitiveNameMatching() {
		BaseAgent mockAgent = mock(BaseAgent.class);
		Supplier<BaseAgent> supplier = () -> mockAgent;
		agentSuppliers.put("TestAgent", supplier);
		NoSuchElementException exception = assertThrows(NoSuchElementException.class, () -> {
			configAgentLoader.loadAgent("testagent");
		});
		assertTrue(exception.getMessage().contains("Agent not found: testagent"));
	}

	@Test
	@Tag("integration")
	void loadAgentFromConcurrentHashMapEnsuresThreadSafety() throws InterruptedException {
		int threadCount = 10;
		int agentCount = 5;

		for (int i = 0; i < agentCount; i++) {
			BaseAgent mockAgent = mock(BaseAgent.class);
			Supplier<BaseAgent> supplier = () -> mockAgent;
			agentSuppliers.put("agent" + i, supplier);
		}
		ExecutorService executorService = Executors.newFixedThreadPool(threadCount);
		CountDownLatch latch = new CountDownLatch(threadCount);
		AtomicInteger successCount = new AtomicInteger(0);
		for (int i = 0; i < threadCount; i++) {
			final int agentIndex = i % agentCount;
			executorService.submit(() -> {
				try {
					BaseAgent agent = configAgentLoader.loadAgent("agent" + agentIndex);
					if (agent != null) {
						successCount.incrementAndGet();
					}
				}
				catch (Exception e) {
					fail("Exception occurred during concurrent access: " + e.getMessage());
				}
				finally {
					latch.countDown();
				}
			});
		}
		assertTrue(latch.await(5, TimeUnit.SECONDS));
		executorService.shutdown();
		assertEquals(threadCount, successCount.get());
	}

	@Test
	@Tag("valid")
	void loadAgentAfterSupplierIsUpdated() {
		BaseAgent oldAgent = mock(BaseAgent.class);
		BaseAgent newAgent = mock(BaseAgent.class);

		Supplier<BaseAgent> oldSupplier = () -> oldAgent;
		agentSuppliers.put("updatableAgent", oldSupplier);
		BaseAgent firstResult = configAgentLoader.loadAgent("updatableAgent");
		assertSame(oldAgent, firstResult);
		Supplier<BaseAgent> newSupplier = () -> newAgent;
		agentSuppliers.put("updatableAgent", newSupplier);
		BaseAgent secondResult = configAgentLoader.loadAgent("updatableAgent");
		assertSame(newAgent, secondResult);
		assertNotSame(oldAgent, secondResult);
	}

	@Test
	@Tag("invalid")
	void loadAgentWhenSupplierThrowsException() {
		RuntimeException expectedException = new RuntimeException("Agent initialization failed");
		Supplier<BaseAgent> faultySupplier = () -> {
			throw expectedException;
		};
		agentSuppliers.put("faultyAgent", faultySupplier);
		RuntimeException exception = assertThrows(RuntimeException.class, () -> {
			configAgentLoader.loadAgent("faultyAgent");
		});
		assertEquals("Agent initialization failed", exception.getMessage());
	}

	@Test
	@Tag("boundary")
	void loadAgentWithWhitespaceInName() {
		BaseAgent mockAgent = mock(BaseAgent.class);
		Supplier<BaseAgent> supplier = () -> mockAgent;
		String nameWithSpaces = " agent with spaces ";
		agentSuppliers.put(nameWithSpaces, supplier);
		BaseAgent result = configAgentLoader.loadAgent(nameWithSpaces);
		assertNotNull(result);
		assertSame(mockAgent, result);
	}

	@Test
	@Tag("valid")
	void loadAgentWithLeadingWhitespace() {
		BaseAgent mockAgent = mock(BaseAgent.class);
		Supplier<BaseAgent> supplier = () -> mockAgent;
		String nameWithLeadingSpace = "  leadingSpace";
		agentSuppliers.put(nameWithLeadingSpace, supplier);
		BaseAgent result = configAgentLoader.loadAgent(nameWithLeadingSpace);
		assertNotNull(result);
		assertSame(mockAgent, result);
	}

	@Test
	@Tag("valid")
	void loadAgentWithTrailingWhitespace() {
		BaseAgent mockAgent = mock(BaseAgent.class);
		Supplier<BaseAgent> supplier = () -> mockAgent;
		String nameWithTrailingSpace = "trailingSpace  ";
		agentSuppliers.put(nameWithTrailingSpace, supplier);
		BaseAgent result = configAgentLoader.loadAgent(nameWithTrailingSpace);
		assertNotNull(result);
		assertSame(mockAgent, result);
	}

	@Test
	@Tag("valid")
	void loadAgentMultipleAgentsExist() {
		BaseAgent agent1 = mock(BaseAgent.class);
		BaseAgent agent2 = mock(BaseAgent.class);
		BaseAgent agent3 = mock(BaseAgent.class);

		agentSuppliers.put("agent1", () -> agent1);
		agentSuppliers.put("agent2", () -> agent2);
		agentSuppliers.put("agent3", () -> agent3);
		BaseAgent result1 = configAgentLoader.loadAgent("agent1");
		BaseAgent result2 = configAgentLoader.loadAgent("agent2");
		BaseAgent result3 = configAgentLoader.loadAgent("agent3");
		assertSame(agent1, result1);
		assertSame(agent2, result2);
		assertSame(agent3, result3);
	}

	@Test
	@Tag("valid")
	void loadAgentWithNumericName() {
		BaseAgent mockAgent = mock(BaseAgent.class);
		Supplier<BaseAgent> supplier = () -> mockAgent;
		agentSuppliers.put("12345", supplier);
		BaseAgent result = configAgentLoader.loadAgent("12345");
		assertNotNull(result);
		assertSame(mockAgent, result);
	}

	@Test
	@Tag("valid")
	void loadAgentWithUnicodeCharacters() {
		BaseAgent mockAgent = mock(BaseAgent.class);
		Supplier<BaseAgent> supplier = () -> mockAgent;
		String unicodeName = "agent_测试_エージェント";
		agentSuppliers.put(unicodeName, supplier);
		BaseAgent result = configAgentLoader.loadAgent(unicodeName);
		assertNotNull(result);
		assertSame(mockAgent, result);
	}

	@Test
	@Tag("boundary")
	void loadAgentWithVeryLongName() {
		BaseAgent mockAgent = mock(BaseAgent.class);
		Supplier<BaseAgent> supplier = () -> mockAgent;
		String longName = "a".repeat(1000);
		agentSuppliers.put(longName, supplier);
		BaseAgent result = configAgentLoader.loadAgent(longName);
		assertNotNull(result);
		assertSame(mockAgent, result);
	}

}