/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-maven-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=build_60dfc72613
ROOST_METHOD_SIG_HASH=build_60dfc72613

Scenario 1: Build MemoryEntry with All Required and Optional Fields Set

Details:
  TestName: buildWithAllFieldsSet
  Description: This test verifies that the build() method successfully creates a MemoryEntry instance when all fields (both required and optional) are properly set. The test ensures that a complete MemoryEntry object can be constructed with content, author, and timestamp.
Execution:
  Arrange: Create a Builder instance and set all fields: content (using a valid Content object), author (a non-null String), and timestamp (a non-null String in ISO 8601 format).
  Act: Invoke the build() method on the configured Builder instance.
  Assert: Verify that the returned MemoryEntry object is not null. Verify that all fields in the built object match the values that were set in the builder using the accessor methods content(), author(), and timestamp().
Validation:
  This assertion verifies that the build() method correctly constructs a MemoryEntry with all provided values intact. This is the happy path scenario and ensures that the builder pattern works as expected when all data is provided. This is critical for application functionality as it represents the most common use case where complete memory entries are created.

Scenario 2: Build MemoryEntry with Only Required Field (Content)

Details:
  TestName: buildWithOnlyRequiredContent
  Description: This test validates that the build() method can successfully create a MemoryEntry when only the required content field is set, while optional fields (author and timestamp) are left unset or null.
Execution:
  Arrange: Create a Builder instance and set only the content field with a valid Content object. Do not set author or timestamp fields.
  Act: Invoke the build() method on the Builder instance.
  Assert: Verify that the returned MemoryEntry object is not null. Verify that content() returns the expected Content object. Verify that author() returns null. Verify that timestamp() returns null.
Validation:
  This assertion confirms that the build() method handles optional fields correctly by allowing them to be null while still creating a valid MemoryEntry object. This is important for scenarios where minimal information is available, ensuring the builder doesn't enforce unnecessary constraints on optional fields.

Scenario 3: Build MemoryEntry with Content and Author Only

Details:
  TestName: buildWithContentAndAuthor
  Description: This test checks that the build() method correctly creates a MemoryEntry when content and author are set, but timestamp is omitted.
Execution:
  Arrange: Create a Builder instance and set the content field with a valid Content object and the author field with a non-null String. Leave the timestamp field unset.
  Act: Invoke the build() method on the Builder instance.
  Assert: Verify that the returned MemoryEntry object is not null. Verify that content() returns the expected Content object. Verify that author() returns the expected author String. Verify that timestamp() returns null.
Validation:
  This assertion validates that partial population of optional fields works correctly. It ensures that the builder can handle combinations of set and unset optional fields, which is common in real-world scenarios where some metadata may be available while other metadata is not.

Scenario 4: Build MemoryEntry with Content and Timestamp Only

Details:
  TestName: buildWithContentAndTimestamp
  Description: This test verifies that the build() method successfully creates a MemoryEntry when content and timestamp are provided, but author is not set.
Execution:
  Arrange: Create a Builder instance and set the content field with a valid Content object and the timestamp field with a valid ISO 8601 formatted String. Leave the author field unset.
  Act: Invoke the build() method on the Builder instance.
  Assert: Verify that the returned MemoryEntry object is not null. Verify that content() returns the expected Content object. Verify that author() returns null. Verify that timestamp() returns the expected timestamp String.
Validation:
  This assertion ensures that the builder correctly handles the case where timestamp is provided without author information. This is important for use cases where the timing of a memory is known but the author is not tracked or relevant.

Scenario 5: Build MemoryEntry with Timestamp Set Using Instant Object

Details:
  TestName: buildWithTimestampFromInstant
  Description: This test validates that the build() method works correctly when the timestamp is set using the convenience method timestamp(Instant) which converts an Instant object to an ISO 8601 formatted String.
Execution:
  Arrange: Create a Builder instance and set the content field with a valid Content object. Create an Instant object representing a specific point in time. Use the timestamp(Instant) convenience method to set the timestamp.
  Act: Invoke the build() method on the Builder instance.
  Assert: Verify that the returned MemoryEntry object is not null. Verify that content() returns the expected Content object. Verify that timestamp() returns a String that matches the ISO 8601 representation of the Instant object (using instant.toString()).
Validation:
  This assertion confirms that the convenience method for setting timestamp from an Instant object works correctly and properly converts the Instant to the expected ISO 8601 String format. This is important for developers who work with Java time APIs and need a convenient way to set timestamps.

Scenario 6: Build MemoryEntry with Null Author Explicitly Set

Details:
  TestName: buildWithExplicitNullAuthor
  Description: This test checks that the build() method handles the case where the author field is explicitly set to null, as opposed to being left unset.
Execution:
  Arrange: Create a Builder instance and set the content field with a valid Content object. Explicitly call author(null) to set the author field to null.
  Act: Invoke the build() method on the Builder instance.
  Assert: Verify that the returned MemoryEntry object is not null. Verify that content() returns the expected Content object. Verify that author() returns null.
Validation:
  This assertion validates that explicitly setting a nullable field to null is handled correctly by the builder. This ensures that the @Nullable annotation is properly respected and that explicit null values don't cause issues during the build process.

Scenario 7: Build MemoryEntry with Null Timestamp Explicitly Set

Details:
  TestName: buildWithExplicitNullTimestamp
  Description: This test verifies that the build() method correctly handles the case where the timestamp field is explicitly set to null.
Execution:
  Arrange: Create a Builder instance and set the content field with a valid Content object. Explicitly call timestamp((String) null) to set the timestamp field to null.
  Act: Invoke the build() method on the Builder instance.
  Assert: Verify that the returned MemoryEntry object is not null. Verify that content() returns the expected Content object. Verify that timestamp() returns null.
Validation:
  This assertion ensures that explicitly setting the timestamp to null is handled properly by the builder. This is important for scenarios where a timestamp might be cleared or reset, and confirms that the nullable contract is correctly implemented.

Scenario 8: Build MemoryEntry with Empty String Author

Details:
  TestName: buildWithEmptyStringAuthor
  Description: This test validates that the build() method can create a MemoryEntry when the author field is set to an empty String, which is technically a valid non-null value.
Execution:
  Arrange: Create a Builder instance and set the content field with a valid Content object. Set the author field to an empty String ("").
  Act: Invoke the build() method on the Builder instance.
  Assert: Verify that the returned MemoryEntry object is not null. Verify that content() returns the expected Content object. Verify that author() returns an empty String ("").
Validation:
  This assertion confirms that the builder accepts empty Strings as valid values for the author field. This is important for understanding the validation boundaries of the builder and ensures that empty Strings are not treated as null or invalid.

Scenario 9: Build MemoryEntry with Empty String Timestamp

Details:
  TestName: buildWithEmptyStringTimestamp
  Description: This test checks that the build() method can create a MemoryEntry when the timestamp field is set to an empty String.
Execution:
  Arrange: Create a Builder instance and set the content field with a valid Content object. Set the timestamp field to an empty String ("").
  Act: Invoke the build() method on the Builder instance.
  Assert: Verify that the returned MemoryEntry object is not null. Verify that content() returns the expected Content object. Verify that timestamp() returns an empty String ("").
Validation:
  This assertion validates that empty Strings are accepted as valid values for the timestamp field. This helps define the validation boundaries and ensures that the builder doesn't perform implicit validation on the timestamp format during the build process.

Scenario 10: Build MemoryEntry Multiple Times from Same Builder

Details:
  TestName: buildMultipleTimesFromSameBuilder
  Description: This test verifies that calling build() multiple times on the same Builder instance produces independent MemoryEntry objects with the same values.
Execution:
  Arrange: Create a Builder instance and set all fields with valid values (content, author, and timestamp).
  Act: Invoke the build() method twice on the same Builder instance to create two MemoryEntry objects.
  Assert: Verify that both returned MemoryEntry objects are not null. Verify that both objects have the same field values. Verify that the two objects are not the same instance (using reference inequality).
Validation:
  This assertion confirms that the build() method can be called multiple times and produces independent immutable objects. This is important for understanding the builder's reusability and ensures that the AutoValue implementation correctly creates new instances on each build() call.

Scenario 11: Build MemoryEntry After Modifying Builder

Details:
  TestName: buildAfterModifyingBuilder
  Description: This test validates that modifying a Builder after calling build() does not affect the previously built MemoryEntry object, confirming immutability.
Execution:
  Arrange: Create a Builder instance and set all fields with initial values. Call build() to create the first MemoryEntry object. Modify the builder by setting different values for author and timestamp.
  Act: Call build() again to create a second MemoryEntry object.
  Assert: Verify that the first MemoryEntry object still has the original values. Verify that the second MemoryEntry object has the new modified values. Verify that the two objects are different instances with different field values.
Validation:
  This assertion ensures that MemoryEntry objects are truly immutable and that changes to the builder after building do not affect previously created instances. This is critical for maintaining data integrity in concurrent or multi-threaded environments.

Scenario 12: Build MemoryEntry with Special Characters in Author

Details:
  TestName: buildWithSpecialCharactersInAuthor
  Description: This test checks that the build() method correctly handles author names containing special characters, Unicode characters, or non-ASCII text.
Execution:
  Arrange: Create a Builder instance and set the content field with a valid Content object. Set the author field to a String containing special characters, such as "Author@123", "Auteur-Français", or "作者名".
  Act: Invoke the build() method on the Builder instance.
  Assert: Verify that the returned MemoryEntry object is not null. Verify that author() returns the exact String with special characters as it was set.
Validation:
  This assertion validates that the builder and build() method correctly preserve special characters and Unicode text in the author field. This is important for internationalization and ensuring that the system can handle diverse user names and character sets.

Scenario 13: Build MemoryEntry with Non-ISO 8601 Timestamp Format

Details:
  TestName: buildWithNonIso8601Timestamp
  Description: This test verifies that the build() method accepts timestamp Strings in formats other than ISO 8601, since the builder doesn't enforce format validation.
Execution:
  Arrange: Create a Builder instance and set the content field with a valid Content object. Set the timestamp field to a String in a non-ISO 8601 format, such as "2025-01-15 10:30:00" or "January 15, 2025".
  Act: Invoke the build() method on the Builder instance.
  Assert: Verify that the returned MemoryEntry object is not null. Verify that timestamp() returns the exact String as it was set, regardless of format.
Validation:
  This assertion confirms that the build() method does not perform format validation on the timestamp field. While the documentation suggests ISO 8601 format is preferred, this test ensures that the builder is flexible and doesn't reject non-standard formats, leaving validation to other layers of the application.

Scenario 14: Build MemoryEntry with Very Long Author String

Details:
  TestName: buildWithVeryLongAuthorString
  Description: This test validates that the build() method can handle author Strings of significant length without issues.
Execution:
  Arrange: Create a Builder instance and set the content field with a valid Content object. Set the author field to a very long String (e.g., 1000+ characters).
  Act: Invoke the build() method on the Builder instance.
  Assert: Verify that the returned MemoryEntry object is not null. Verify that author() returns the complete long String without truncation.
Validation:
  This assertion ensures that the builder doesn't impose arbitrary length restrictions on the author field. This is important for robustness and ensures that the system can handle edge cases where author information might be unusually long.

Scenario 15: Build MemoryEntry with Very Long Timestamp String

Details:
  TestName: buildWithVeryLongTimestampString
  Description: This test checks that the build() method can handle timestamp Strings of significant length.
Execution:
  Arrange: Create a Builder instance and set the content field with a valid Content object. Set the timestamp field to a very long String (e.g., a detailed timestamp with extensive metadata).
  Act: Invoke the build() method on the Builder instance.
  Assert: Verify that the returned MemoryEntry object is not null. Verify that timestamp() returns the complete long String without truncation.
Validation:
  This assertion validates that the builder doesn't impose length restrictions on the timestamp field. This ensures robustness when handling edge cases or when timestamps include additional contextual information.

*/

// ********RoostGPT********

package com.google.adk.memory;
import static com.google.common.truth.Truth.assertThat;
import com.google.genai.types.Content;
import java.time.Instant;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.*;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.google.auto.value.AutoValue;
import javax.annotation.Nullable;

class BuilderBuild987Test {
  private Content createMockContent() {
    return Content.newBuilder().build();
  }
  @Test
  @Tag("valid")
  void buildWithAllFieldsSet() {
    Content content = createMockContent();
    String author = "John Doe";
    String timestamp = "2025-01-15T10:30:00Z";
    MemoryEntry.Builder builder = MemoryEntry.builder();
    builder.content(content);
    builder.author(author);
    builder.timestamp(timestamp);
    MemoryEntry memoryEntry = builder.build();
    assertThat(memoryEntry).isNotNull();
    assertThat(memoryEntry.content()).isEqualTo(content);
    assertThat(memoryEntry.author()).isEqualTo(author);
    assertThat(memoryEntry.timestamp()).isEqualTo(timestamp);
  }
  @Test
  @Tag("valid")
  void buildWithOnlyRequiredContent() {
    Content content = createMockContent();
    MemoryEntry.Builder builder = MemoryEntry.builder();
    builder.content(content);
    MemoryEntry memoryEntry = builder.build();
    assertThat(memoryEntry).isNotNull();
    assertThat(memoryEntry.content()).isEqualTo(content);
    assertThat(memoryEntry.author()).isNull();
    assertThat(memoryEntry.timestamp()).isNull();
  }
  @Test
  @Tag("valid")
  void buildWithContentAndAuthor() {
    Content content = createMockContent();
    String author = "Jane Smith";
    MemoryEntry.Builder builder = MemoryEntry.builder();
    builder.content(content);
    builder.author(author);
    MemoryEntry memoryEntry = builder.build();
    assertThat(memoryEntry).isNotNull();
    assertThat(memoryEntry.content()).isEqualTo(content);
    assertThat(memoryEntry.author()).isEqualTo(author);
    assertThat(memoryEntry.timestamp()).isNull();
  }
  @Test
  @Tag("valid")
  void buildWithContentAndTimestamp() {
    Content content = createMockContent();
    String timestamp = "2025-01-15T14:45:30Z";
    MemoryEntry.Builder builder = MemoryEntry.builder();
    builder.content(content);
    builder.timestamp(timestamp);
    MemoryEntry memoryEntry = builder.build();
    assertThat(memoryEntry).isNotNull();
    assertThat(memoryEntry.content()).isEqualTo(content);
    assertThat(memoryEntry.author()).isNull();
    assertThat(memoryEntry.timestamp()).isEqualTo(timestamp);
  }
  @Test
  @Tag("valid")
  void buildWithTimestampFromInstant() {
    Content content = createMockContent();
    Instant instant = Instant.parse("2025-01-15T10:30:00Z");
    MemoryEntry.Builder builder = MemoryEntry.builder();
    builder.content(content);
    builder.timestamp(instant);
    MemoryEntry memoryEntry = builder.build();
    assertThat(memoryEntry).isNotNull();
    assertThat(memoryEntry.content()).isEqualTo(content);
    assertThat(memoryEntry.timestamp()).isEqualTo(instant.toString());
  }
  @Test
  @Tag("valid")
  void buildWithExplicitNullAuthor() {
    Content content = createMockContent();
    MemoryEntry.Builder builder = MemoryEntry.builder();
    builder.content(content);
    builder.author(null);
    MemoryEntry memoryEntry = builder.build();
    assertThat(memoryEntry).isNotNull();
    assertThat(memoryEntry.content()).isEqualTo(content);
    assertThat(memoryEntry.author()).isNull();
  }
  @Test
  @Tag("valid")
  void buildWithExplicitNullTimestamp() {
    Content content = createMockContent();
    MemoryEntry.Builder builder = MemoryEntry.builder();
    builder.content(content);
    builder.timestamp((String) null);
    MemoryEntry memoryEntry = builder.build();
    assertThat(memoryEntry).isNotNull();
    assertThat(memoryEntry.content()).isEqualTo(content);
    assertThat(memoryEntry.timestamp()).isNull();
  }
  @Test
  @Tag("boundary")
  void buildWithEmptyStringAuthor() {
    Content content = createMockContent();
    String author = "";
    MemoryEntry.Builder builder = MemoryEntry.builder();
    builder.content(content);
    builder.author(author);
    MemoryEntry memoryEntry = builder.build();
    assertThat(memoryEntry).isNotNull();
    assertThat(memoryEntry.content()).isEqualTo(content);
    assertThat(memoryEntry.author()).isEqualTo("");
  }
  @Test
  @Tag("boundary")
  void buildWithEmptyStringTimestamp() {
    Content content = createMockContent();
    String timestamp = "";
    MemoryEntry.Builder builder = MemoryEntry.builder();
    builder.content(content);
    builder.timestamp(timestamp);
    MemoryEntry memoryEntry = builder.build();
    assertThat(memoryEntry).isNotNull();
    assertThat(memoryEntry.content()).isEqualTo(content);
    assertThat(memoryEntry.timestamp()).isEqualTo("");
  }
  @Test
  @Tag("valid")
  void buildMultipleTimesFromSameBuilder() {
    Content content = createMockContent();
    String author = "Alice Johnson";
    String timestamp = "2025-01-15T16:20:00Z";
    MemoryEntry.Builder builder = MemoryEntry.builder();
    builder.content(content);
    builder.author(author);
    builder.timestamp(timestamp);
    MemoryEntry memoryEntry1 = builder.build();
    MemoryEntry memoryEntry2 = builder.build();
    assertThat(memoryEntry1).isNotNull();
    assertThat(memoryEntry2).isNotNull();
    assertThat(memoryEntry1.content()).isEqualTo(content);
    assertThat(memoryEntry2.content()).isEqualTo(content);
    assertThat(memoryEntry1.author()).isEqualTo(author);
    assertThat(memoryEntry2.author()).isEqualTo(author);
    assertThat(memoryEntry1.timestamp()).isEqualTo(timestamp);
    assertThat(memoryEntry2.timestamp()).isEqualTo(timestamp);
    assertThat(memoryEntry1).isNotSameInstanceAs(memoryEntry2);
  }
  @Test
  @Tag("valid")
  void buildAfterModifyingBuilder() {
    Content content = createMockContent();
    String initialAuthor = "Bob Williams";
    String initialTimestamp = "2025-01-15T09:00:00Z";
    String modifiedAuthor = "Charlie Brown";
    String modifiedTimestamp = "2025-01-15T12:00:00Z";
    MemoryEntry.Builder builder = MemoryEntry.builder();
    builder.content(content);
    builder.author(initialAuthor);
    builder.timestamp(initialTimestamp);
    MemoryEntry memoryEntry1 = builder.build();
    builder.author(modifiedAuthor);
    builder.timestamp(modifiedTimestamp);
    MemoryEntry memoryEntry2 = builder.build();
    assertThat(memoryEntry1.content()).isEqualTo(content);
    assertThat(memoryEntry1.author()).isEqualTo(initialAuthor);
    assertThat(memoryEntry1.timestamp()).isEqualTo(initialTimestamp);
    assertThat(memoryEntry2.content()).isEqualTo(content);
    assertThat(memoryEntry2.author()).isEqualTo(modifiedAuthor);
    assertThat(memoryEntry2.timestamp()).isEqualTo(modifiedTimestamp);
    assertThat(memoryEntry1).isNotSameInstanceAs(memoryEntry2);
  }
  @Test
  @Tag("boundary")
  void buildWithSpecialCharactersInAuthor() {
    Content content = createMockContent();
    String author = "Author@123-Français_作者名";
    MemoryEntry.Builder builder = MemoryEntry.builder();
    builder.content(content);
    builder.author(author);
    MemoryEntry memoryEntry = builder.build();
    assertThat(memoryEntry).isNotNull();
    assertThat(memoryEntry.author()).isEqualTo(author);
  }
  @Test
  @Tag("valid")
  void buildWithNonIso8601Timestamp() {
    Content content = createMockContent();
    String timestamp = "2025-01-15 10:30:00";
    MemoryEntry.Builder builder = MemoryEntry.builder();
    builder.content(content);
    builder.timestamp(timestamp);
    MemoryEntry memoryEntry = builder.build();
    assertThat(memoryEntry).isNotNull();
    assertThat(memoryEntry.timestamp()).isEqualTo(timestamp);
  }
  @Test
  @Tag("boundary")
  void buildWithVeryLongAuthorString() {
    Content content = createMockContent();
    StringBuilder longAuthorBuilder = new StringBuilder();
    for (int i = 0; i < 1000; i++) {
      longAuthorBuilder.append("A");
    }
    String longAuthor = longAuthorBuilder.toString();
    MemoryEntry.Builder builder = MemoryEntry.builder();
    builder.content(content);
    builder.author(longAuthor);
    MemoryEntry memoryEntry = builder.build();
    assertThat(memoryEntry).isNotNull();
    assertThat(memoryEntry.author()).isEqualTo(longAuthor);
    assertThat(memoryEntry.author()).hasLength(1000);
  }
  @Test
  @Tag("boundary")
  void buildWithVeryLongTimestampString() {
    Content content = createMockContent();
    StringBuilder longTimestampBuilder = new StringBuilder("2025-01-15T10:30:00Z");
    for (int i = 0; i < 1000; i++) {
      longTimestampBuilder.append("-metadata");
    }
    String longTimestamp = longTimestampBuilder.toString();
    MemoryEntry.Builder builder = MemoryEntry.builder();
    builder.content(content);
    builder.timestamp(longTimestamp);
    MemoryEntry memoryEntry = builder.build();
    assertThat(memoryEntry).isNotNull();
    assertThat(memoryEntry.timestamp()).isEqualTo(longTimestamp);
    assertThat(memoryEntry.timestamp().length()).isGreaterThan(1000);
  }
}