/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-maven-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=timestamp_a2d6563596
ROOST_METHOD_SIG_HASH=timestamp_a2d6563596

Scenario 1: Setting a Valid ISO 8601 Timestamp String

Details:
  TestName: timestampWithValidIso8601String
  Description: This test verifies that the timestamp method correctly accepts and stores a valid ISO 8601 formatted timestamp string. The method should successfully set the timestamp value when provided with a properly formatted date-time string.

Execution:
  Arrange: Create a Builder instance using MemoryEntry.builder(). Prepare a valid ISO 8601 timestamp string (e.g., "2025-01-15T10:30:00Z"). Create a valid Content object to satisfy the required content field.
  Act: Invoke the timestamp method on the Builder instance with the valid ISO 8601 timestamp string. Build the MemoryEntry object using the build() method.
  Assert: Use JUnit assertions to verify that the timestamp() getter on the built MemoryEntry returns the exact string that was set.

Validation:
  This assertion verifies that the Builder correctly stores and returns the timestamp value without modification. This is critical because the timestamp is forwarded to the LLM and must maintain its exact format. The test ensures the basic functionality of the setter method works as expected with standard ISO 8601 format, which is the preferred format according to the documentation.


Scenario 2: Setting a Null Timestamp

Details:
  TestName: timestampWithNullValue
  Description: This test validates that the timestamp method correctly handles null values, as indicated by the @Nullable annotation. The method should accept null without throwing exceptions and store it appropriately.

Execution:
  Arrange: Create a Builder instance using MemoryEntry.builder(). Prepare a null value for the timestamp parameter. Create a valid Content object to satisfy the required content field.
  Act: Invoke the timestamp method on the Builder instance with null as the parameter. Build the MemoryEntry object using the build() method.
  Assert: Use JUnit assertions to verify that the timestamp() getter on the built MemoryEntry returns null.

Validation:
  This assertion confirms that the Builder properly handles optional timestamp values. Since the timestamp field is marked with @Nullable, it should be possible to create a MemoryEntry without a timestamp. This test is important for scenarios where the timing information is not available or not relevant, ensuring the API's flexibility in handling incomplete data.


Scenario 3: Setting an Empty String Timestamp

Details:
  TestName: timestampWithEmptyString
  Description: This test checks the behavior when an empty string is provided as the timestamp value. While technically a valid string, an empty timestamp may have implications for downstream processing.

Execution:
  Arrange: Create a Builder instance using MemoryEntry.builder(). Prepare an empty string ("") for the timestamp parameter. Create a valid Content object to satisfy the required content field.
  Act: Invoke the timestamp method on the Builder instance with an empty string. Build the MemoryEntry object using the build() method.
  Assert: Use JUnit assertions to verify that the timestamp() getter on the built MemoryEntry returns an empty string.

Validation:
  This assertion verifies that the Builder accepts and stores empty strings without converting them to null or throwing exceptions. This is important for understanding the method's behavior with edge case inputs. Since the timestamp is forwarded to the LLM, it's crucial to know whether empty strings are preserved or need to be handled differently by the caller.


Scenario 4: Setting a Non-ISO 8601 Formatted Timestamp String

Details:
  TestName: timestampWithNonIso8601Format
  Description: This test examines the behavior when a timestamp string that does not conform to ISO 8601 format is provided. The method should still accept the string since it doesn't perform format validation.

Execution:
  Arrange: Create a Builder instance using MemoryEntry.builder(). Prepare a non-ISO 8601 formatted timestamp string (e.g., "January 15, 2025 10:30 AM"). Create a valid Content object to satisfy the required content field.
  Act: Invoke the timestamp method on the Builder instance with the non-standard timestamp string. Build the MemoryEntry object using the build() method.
  Assert: Use JUnit assertions to verify that the timestamp() getter on the built MemoryEntry returns the exact non-ISO 8601 string that was set.

Validation:
  This assertion confirms that the Builder does not perform format validation on the timestamp string. While ISO 8601 is the preferred format according to documentation, the method accepts any string value. This test is important for understanding that format validation is the caller's responsibility, and the Builder acts as a simple data container. This behavior may be relevant when dealing with legacy data or different timestamp formats.


Scenario 5: Overwriting a Previously Set Timestamp

Details:
  TestName: timestampOverwritesPreviousValue
  Description: This test verifies that calling the timestamp method multiple times on the same Builder instance correctly overwrites the previous value with the new one.

Execution:
  Arrange: Create a Builder instance using MemoryEntry.builder(). Prepare two different timestamp strings (e.g., "2025-01-15T10:30:00Z" and "2025-01-16T14:45:00Z"). Create a valid Content object to satisfy the required content field.
  Act: Invoke the timestamp method on the Builder instance with the first timestamp string. Then invoke the timestamp method again on the same Builder instance with the second timestamp string. Build the MemoryEntry object using the build() method.
  Assert: Use JUnit assertions to verify that the timestamp() getter on the built MemoryEntry returns only the second timestamp string, not the first.

Validation:
  This assertion ensures that the Builder follows the expected behavior of setter methods where subsequent calls replace previous values rather than accumulating them. This is critical for the Builder pattern's correctness, as users expect to be able to modify values before building the final object. The test confirms that there are no unexpected side effects from multiple invocations.


Scenario 6: Setting Timestamp with Whitespace-Only String

Details:
  TestName: timestampWithWhitespaceOnlyString
  Description: This test evaluates the behavior when a string containing only whitespace characters is provided as the timestamp value.

Execution:
  Arrange: Create a Builder instance using MemoryEntry.builder(). Prepare a whitespace-only string (e.g., "   " or "\t\n"). Create a valid Content object to satisfy the required content field.
  Act: Invoke the timestamp method on the Builder instance with the whitespace-only string. Build the MemoryEntry object using the build() method.
  Assert: Use JUnit assertions to verify that the timestamp() getter on the built MemoryEntry returns the whitespace string exactly as provided.

Validation:
  This assertion confirms that the Builder does not trim or sanitize input strings. Whitespace-only strings are preserved as-is, which is consistent with the method's role as a simple setter. This test is important for understanding data handling behavior and ensuring that no unexpected transformations occur. Since the timestamp is forwarded to the LLM, preserving the exact input allows the caller to control data sanitization.


Scenario 7: Setting Timestamp with Special Characters

Details:
  TestName: timestampWithSpecialCharacters
  Description: This test checks the behavior when a timestamp string containing special characters (non-alphanumeric) is provided.

Execution:
  Arrange: Create a Builder instance using MemoryEntry.builder(). Prepare a timestamp string with special characters (e.g., "2025-01-15T10:30:00+00:00" or "timestamp@#$%"). Create a valid Content object to satisfy the required content field.
  Act: Invoke the timestamp method on the Builder instance with the special character string. Build the MemoryEntry object using the build() method.
  Assert: Use JUnit assertions to verify that the timestamp() getter on the built MemoryEntry returns the string with special characters exactly as provided.

Validation:
  This assertion verifies that the Builder accepts strings with special characters without escaping or modifying them. This is important because ISO 8601 timestamps include special characters like colons, hyphens, and timezone indicators. The test ensures that valid timestamp formats with timezone information are preserved correctly, which is essential for accurate time representation across different geographical locations.


Scenario 8: Builder Method Chaining with Timestamp

Details:
  TestName: timestampReturnsBuilderForMethodChaining
  Description: This test verifies that the timestamp method returns the Builder instance itself, enabling fluent method chaining as is standard in the Builder pattern.

Execution:
  Arrange: Create a Builder instance using MemoryEntry.builder(). Prepare a valid timestamp string. Create a valid Content object and author string.
  Act: Invoke multiple Builder methods in a chained fashion, including timestamp, content, and author methods in a single statement. Build the MemoryEntry object using the build() method.
  Assert: Use JUnit assertions to verify that the built MemoryEntry contains all the values set through the chained method calls, including the timestamp value.

Validation:
  This assertion confirms that the Builder pattern is correctly implemented with fluent interface support. Method chaining is a key feature of the Builder pattern that improves code readability and usability. This test ensures that the timestamp method integrates properly with other Builder methods, allowing developers to construct MemoryEntry objects in a clean, readable manner.


Scenario 9: Setting Timestamp After Using toBuilder

Details:
  TestName: timestampAfterToBuilder
  Description: This test verifies that the timestamp method works correctly on a Builder instance created from an existing MemoryEntry using the toBuilder() method.

Execution:
  Arrange: Create an initial MemoryEntry with a specific timestamp value using the Builder. Use the toBuilder() method to create a new Builder instance from the existing MemoryEntry. Prepare a new timestamp string different from the original.
  Act: Invoke the timestamp method on the new Builder instance with the new timestamp value. Build a new MemoryEntry object using the build() method.
  Assert: Use JUnit assertions to verify that the new MemoryEntry has the updated timestamp value, while the original MemoryEntry retains its original timestamp value (immutability check).

Validation:
  This assertion ensures that the toBuilder() method creates an independent Builder instance that can modify values without affecting the original immutable MemoryEntry. This is crucial for the immutability guarantee of the AutoValue-generated class. The test validates that users can safely create modified copies of MemoryEntry objects, which is a common pattern in immutable object manipulation.


Scenario 10: Setting Very Long Timestamp String

Details:
  TestName: timestampWithVeryLongString
  Description: This test examines the behavior when an extremely long string is provided as the timestamp value, testing the method's handling of large input data.

Execution:
  Arrange: Create a Builder instance using MemoryEntry.builder(). Prepare a very long string (e.g., 10,000 characters) for the timestamp parameter. Create a valid Content object to satisfy the required content field.
  Act: Invoke the timestamp method on the Builder instance with the very long string. Build the MemoryEntry object using the build() method.
  Assert: Use JUnit assertions to verify that the timestamp() getter on the built MemoryEntry returns the complete long string without truncation.

Validation:
  This assertion confirms that the Builder does not impose arbitrary length restrictions on the timestamp string. While such a long timestamp is impractical and not a valid ISO 8601 format, the test ensures that the method handles edge cases gracefully without throwing exceptions or losing data. This is important for robustness and understanding the method's limitations, especially since the timestamp is forwarded to the LLM which may have its own input size constraints.


Scenario 11: Setting Timestamp with Unicode Characters

Details:
  TestName: timestampWithUnicodeCharacters
  Description: This test validates that the timestamp method correctly handles strings containing Unicode characters from various languages and symbol sets.

Execution:
  Arrange: Create a Builder instance using MemoryEntry.builder(). Prepare a timestamp string containing Unicode characters (e.g., "2025年1月15日" or "2025-01-15T10:30:00🕐"). Create a valid Content object to satisfy the required content field.
  Act: Invoke the timestamp method on the Builder instance with the Unicode string. Build the MemoryEntry object using the build() method.
  Assert: Use JUnit assertions to verify that the timestamp() getter on the built MemoryEntry returns the Unicode string exactly as provided.

Validation:
  This assertion ensures that the Builder properly handles internationalized text and emoji characters. Since the timestamp is forwarded to the LLM, it's important that Unicode characters are preserved correctly for multilingual support. This test validates that the method doesn't corrupt or mishandle non-ASCII characters, which is essential for global applications and diverse user bases.


Scenario 12: Setting Timestamp to Null After Setting a Value

Details:
  TestName: timestampSetToNullAfterValue
  Description: This test verifies that a previously set timestamp value can be explicitly cleared by setting it to null.

Execution:
  Arrange: Create a Builder instance using MemoryEntry.builder(). Prepare a valid timestamp string. Create a valid Content object to satisfy the required content field.
  Act: Invoke the timestamp method on the Builder instance with a valid timestamp string. Then invoke the timestamp method again with null. Build the MemoryEntry object using the build() method.
  Assert: Use JUnit assertions to verify that the timestamp() getter on the built MemoryEntry returns null, not the previously set value.

Validation:
  This assertion confirms that the Builder allows resetting optional fields to null, providing flexibility in object construction. This is important for scenarios where a timestamp might be conditionally set based on runtime logic, and the ability to explicitly clear it ensures that the Builder can handle dynamic construction requirements. The test validates that null properly overwrites previous values.

*/

// ********RoostGPT********

package com.google.adk.memory;
import static com.google.common.truth.Truth.assertThat;
import com.google.genai.types.Content;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.*;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.google.auto.value.AutoValue;
import java.time.Instant;
import javax.annotation.Nullable;

class BuilderTimestampTest {
    private static final String VALID_ISO_8601_TIMESTAMP = "2025-01-15T10:30:00Z";
    private static final String SECOND_TIMESTAMP = "2025-01-16T14:45:00Z";
    private static final String NON_ISO_8601_TIMESTAMP = "January 15, 2025 10:30 AM";
    private static final String EMPTY_STRING = "";
    private static final String WHITESPACE_ONLY = "   ";
    private static final String TIMESTAMP_WITH_SPECIAL_CHARS = "2025-01-15T10:30:00+00:00";
    private static final String UNICODE_TIMESTAMP = "2025年1月15日";
    private Content createDummyContent() {
        return Content.newBuilder().build();
    }
    @Test
    @Tag("valid")
    void timestampWithValidIso8601String() {
        // Arrange
        MemoryEntry.Builder builder = MemoryEntry.builder();
        Content content = createDummyContent();
        // Act
        MemoryEntry memoryEntry = builder
                .content(content)
                .timestamp(VALID_ISO_8601_TIMESTAMP)
                .build();
        // Assert
        assertThat(memoryEntry.timestamp()).isEqualTo(VALID_ISO_8601_TIMESTAMP);
    }
    @Test
    @Tag("valid")
    void timestampWithNullValue() {
        // Arrange
        MemoryEntry.Builder builder = MemoryEntry.builder();
        Content content = createDummyContent();
        // Act
        MemoryEntry memoryEntry = builder
                .content(content)
                .timestamp((String) null)
                .build();
        // Assert
        assertThat(memoryEntry.timestamp()).isNull();
    }
    @Test
    @Tag("boundary")
    void timestampWithEmptyString() {
        // Arrange
        MemoryEntry.Builder builder = MemoryEntry.builder();
        Content content = createDummyContent();
        // Act
        MemoryEntry memoryEntry = builder
                .content(content)
                .timestamp(EMPTY_STRING)
                .build();
        // Assert
        assertThat(memoryEntry.timestamp()).isEqualTo(EMPTY_STRING);
    }
    @Test
    @Tag("invalid")
    void timestampWithNonIso8601Format() {
        // Arrange
        MemoryEntry.Builder builder = MemoryEntry.builder();
        Content content = createDummyContent();
        // Act
        MemoryEntry memoryEntry = builder
                .content(content)
                .timestamp(NON_ISO_8601_TIMESTAMP)
                .build();
        // Assert
        assertThat(memoryEntry.timestamp()).isEqualTo(NON_ISO_8601_TIMESTAMP);
    }
    @Test
    @Tag("valid")
    void timestampOverwritesPreviousValue() {
        // Arrange
        MemoryEntry.Builder builder = MemoryEntry.builder();
        Content content = createDummyContent();
        // Act
        MemoryEntry memoryEntry = builder
                .content(content)
                .timestamp(VALID_ISO_8601_TIMESTAMP)
                .timestamp(SECOND_TIMESTAMP)
                .build();
        // Assert
        assertThat(memoryEntry.timestamp()).isEqualTo(SECOND_TIMESTAMP);
        assertThat(memoryEntry.timestamp()).isNotEqualTo(VALID_ISO_8601_TIMESTAMP);
    }
    @Test
    @Tag("boundary")
    void timestampWithWhitespaceOnlyString() {
        // Arrange
        MemoryEntry.Builder builder = MemoryEntry.builder();
        Content content = createDummyContent();
        // Act
        MemoryEntry memoryEntry = builder
                .content(content)
                .timestamp(WHITESPACE_ONLY)
                .build();
        // Assert
        assertThat(memoryEntry.timestamp()).isEqualTo(WHITESPACE_ONLY);
    }
    @Test
    @Tag("valid")
    void timestampWithSpecialCharacters() {
        // Arrange
        MemoryEntry.Builder builder = MemoryEntry.builder();
        Content content = createDummyContent();
        // Act
        MemoryEntry memoryEntry = builder
                .content(content)
                .timestamp(TIMESTAMP_WITH_SPECIAL_CHARS)
                .build();
        // Assert
        assertThat(memoryEntry.timestamp()).isEqualTo(TIMESTAMP_WITH_SPECIAL_CHARS);
    }
    @Test
    @Tag("integration")
    void timestampReturnsBuilderForMethodChaining() {
        // Arrange
        Content content = createDummyContent();
        String author = "test-author";
        // Act
        MemoryEntry memoryEntry = MemoryEntry.builder()
                .content(content)
                .author(author)
                .timestamp(VALID_ISO_8601_TIMESTAMP)
                .build();
        // Assert
        assertThat(memoryEntry.content()).isEqualTo(content);
        assertThat(memoryEntry.author()).isEqualTo(author);
        assertThat(memoryEntry.timestamp()).isEqualTo(VALID_ISO_8601_TIMESTAMP);
    }
    @Test
    @Tag("valid")
    void timestampAfterToBuilder() {
        // Arrange
        Content content = createDummyContent();
        MemoryEntry originalEntry = MemoryEntry.builder()
                .content(content)
                .timestamp(VALID_ISO_8601_TIMESTAMP)
                .build();
        // Act
        MemoryEntry newEntry = originalEntry.toBuilder()
                .timestamp(SECOND_TIMESTAMP)
                .build();
        // Assert
        assertThat(newEntry.timestamp()).isEqualTo(SECOND_TIMESTAMP);
        assertThat(originalEntry.timestamp()).isEqualTo(VALID_ISO_8601_TIMESTAMP);
    }
    @Test
    @Tag("boundary")
    void timestampWithVeryLongString() {
        // Arrange
        MemoryEntry.Builder builder = MemoryEntry.builder();
        Content content = createDummyContent();
        StringBuilder longString = new StringBuilder();
        for (int i = 0; i < 10000; i++) {
            longString.append("a");
        }
        String veryLongTimestamp = longString.toString();
        // Act
        MemoryEntry memoryEntry = builder
                .content(content)
                .timestamp(veryLongTimestamp)
                .build();
        // Assert
        assertThat(memoryEntry.timestamp()).isEqualTo(veryLongTimestamp);
        assertThat(memoryEntry.timestamp()).hasLength(10000);
    }
    @Test
    @Tag("valid")
    void timestampWithUnicodeCharacters() {
        // Arrange
        MemoryEntry.Builder builder = MemoryEntry.builder();
        Content content = createDummyContent();
        // Act
        MemoryEntry memoryEntry = builder
                .content(content)
                .timestamp(UNICODE_TIMESTAMP)
                .build();
        // Assert
        assertThat(memoryEntry.timestamp()).isEqualTo(UNICODE_TIMESTAMP);
    }
    @Test
    @Tag("valid")
    void timestampSetToNullAfterValue() {
        // Arrange
        MemoryEntry.Builder builder = MemoryEntry.builder();
        Content content = createDummyContent();
        // Act
        MemoryEntry memoryEntry = builder
                .content(content)
                .timestamp(VALID_ISO_8601_TIMESTAMP)
                .timestamp((String) null)
                .build();
        // Assert
        assertThat(memoryEntry.timestamp()).isNull();
    }
    @Test
    @Tag("boundary")
    void timestampWithTabAndNewlineCharacters() {
        // Arrange
        MemoryEntry.Builder builder = MemoryEntry.builder();
        Content content = createDummyContent();
        String whitespaceWithTabAndNewline = "\t\n";
        // Act
        MemoryEntry memoryEntry = builder
                .content(content)
                .timestamp(whitespaceWithTabAndNewline)
                .build();
        // Assert
        assertThat(memoryEntry.timestamp()).isEqualTo(whitespaceWithTabAndNewline);
    }
    @Test
    @Tag("valid")
    void timestampWithEmojiCharacters() {
        // Arrange
        MemoryEntry.Builder builder = MemoryEntry.builder();
        Content content = createDummyContent();
        String timestampWithEmoji = "2025-01-15T10:30:00🕐";
        // Act
        MemoryEntry memoryEntry = builder
                .content(content)
                .timestamp(timestampWithEmoji)
                .build();
        // Assert
        assertThat(memoryEntry.timestamp()).isEqualTo(timestampWithEmoji);
    }
    @Test
    @Tag("valid")
    void timestampWithSpecialSymbols() {
        // Arrange
        MemoryEntry.Builder builder = MemoryEntry.builder();
        Content content = createDummyContent();
        String timestampWithSymbols = "timestamp@#$%";
        // Act
        MemoryEntry memoryEntry = builder
                .content(content)
                .timestamp(timestampWithSymbols)
                .build();
        // Assert
        assertThat(memoryEntry.timestamp()).isEqualTo(timestampWithSymbols);
    }
    @Test
    @Tag("integration")
    void timestampBuilderReturnsCorrectInstance() {
        // Arrange
        MemoryEntry.Builder builder = MemoryEntry.builder();
        Content content = createDummyContent();
        // Act
        MemoryEntry.Builder returnedBuilder = builder
                .content(content)
                .timestamp(VALID_ISO_8601_TIMESTAMP);
        // Assert
        assertThat(returnedBuilder).isNotNull();
        assertThat(returnedBuilder).isSameInstanceAs(builder);
    }
}