/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-maven-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=timestamp_90ab3a5fd6
ROOST_METHOD_SIG_HASH=timestamp_7ea943c4a8

Scenario 1: Valid Instant Conversion to ISO 8601 String

Details:
  TestName: timestampWithValidInstantConvertsToIso8601String
  Description: This test verifies that when a valid Instant object is passed to the timestamp(Instant) method, it correctly converts the Instant to its ISO 8601 string representation and sets it as the timestamp value. The test ensures the convenience method properly delegates to the timestamp(String) method with the correct string format.

Execution:
  Arrange: Create a MemoryEntry.Builder instance. Create a valid Instant object representing a specific point in time (e.g., Instant.parse("2025-01-15T10:30:00Z")). Create a Content object to satisfy the required field for building MemoryEntry.
  Act: Invoke the timestamp(Instant) method on the builder with the created Instant object. Build the MemoryEntry object using the build() method.
  Assert: Use assertEquals to verify that the timestamp() method of the built MemoryEntry returns the expected ISO 8601 string representation of the Instant (e.g., "2025-01-15T10:30:00Z").

Validation:
  This assertion verifies that the timestamp(Instant) convenience method correctly converts an Instant object to its string representation using the toString() method, which produces ISO 8601 format. This is significant because it ensures that developers can use the more type-safe Instant type while the underlying storage uses the String format that will be forwarded to the LLM. The test confirms the method chain works correctly and the conversion is accurate.

---

Scenario 2: Epoch Instant Conversion

Details:
  TestName: timestampWithEpochInstantConvertsCorrectly
  Description: This test validates that the timestamp(Instant) method correctly handles the Unix epoch time (1970-01-01T00:00:00Z). This is an important edge case as epoch time is commonly used as a reference point and default value in many systems.

Execution:
  Arrange: Create a MemoryEntry.Builder instance. Create an Instant object representing the Unix epoch using Instant.EPOCH or Instant.ofEpochSecond(0). Create a Content object for the required field.
  Act: Call the timestamp(Instant) method with the epoch Instant. Build the MemoryEntry using build().
  Assert: Use assertEquals to verify that the timestamp() returns "1970-01-01T00:00:00Z".

Validation:
  This test ensures that the method correctly handles the epoch time, which is a common boundary value. The significance lies in verifying that the conversion works for the earliest representable time in the Instant class, ensuring no special handling or errors occur at this boundary. This is important for systems that might use epoch as a default or starting timestamp.

---

Scenario 3: Future Instant Conversion

Details:
  TestName: timestampWithFutureInstantConvertsCorrectly
  Description: This test checks that the timestamp(Instant) method correctly handles Instant objects representing future dates. This ensures the method works with timestamps beyond the current time, which may be relevant for scheduled or planned memory entries.

Execution:
  Arrange: Create a MemoryEntry.Builder instance. Create an Instant object representing a future date (e.g., Instant.parse("2099-12-31T23:59:59Z")). Create a Content object for the builder.
  Act: Invoke timestamp(Instant) with the future Instant. Build the MemoryEntry.
  Assert: Use assertEquals to verify that timestamp() returns "2099-12-31T23:59:59Z".

Validation:
  This assertion confirms that the method handles future timestamps correctly without any validation or restriction. This is important because memory entries might need to store planned or scheduled events. The test ensures the conversion mechanism works regardless of whether the timestamp is in the past, present, or future.

---

Scenario 4: Instant with Nanosecond Precision

Details:
  TestName: timestampWithNanosecondPrecisionPreservesDetail
  Description: This test verifies that the timestamp(Instant) method preserves nanosecond precision when converting an Instant to a string. Instant objects can represent time with nanosecond precision, and this test ensures that precision is maintained in the string representation.

Execution:
  Arrange: Create a MemoryEntry.Builder instance. Create an Instant with nanosecond precision (e.g., Instant.parse("2025-01-15T10:30:00.123456789Z")). Create a Content object.
  Act: Call timestamp(Instant) with the nanosecond-precision Instant. Build the MemoryEntry.
  Assert: Use assertEquals to verify that timestamp() returns "2025-01-15T10:30:00.123456789Z", preserving all nanosecond digits.

Validation:
  This test validates that the full precision of the Instant is maintained through the conversion process. This is significant for applications requiring high-precision timestamps, such as logging systems or event tracking where the exact sequence of events matters. The test ensures no loss of precision occurs during the conversion.

---

Scenario 5: Builder Method Chaining

Details:
  TestName: timestampReturnsBuilderForMethodChaining
  Description: This test verifies that the timestamp(Instant) method returns the Builder instance, enabling fluent method chaining. This is a common pattern in builder classes and is essential for a good developer experience.

Execution:
  Arrange: Create a MemoryEntry.Builder instance. Create a valid Instant object. Create a Content object.
  Act: Chain multiple builder methods together, including timestamp(Instant), content(), and author(), in a single statement. Build the MemoryEntry.
  Assert: Use assertNotNull to verify that the built MemoryEntry is not null. Use assertEquals to verify that all chained values (timestamp, content, author) were correctly set.

Validation:
  This assertion confirms that the timestamp(Instant) method follows the builder pattern correctly by returning the Builder instance. This is crucial for maintaining a fluent API that allows developers to chain multiple configuration calls in a readable manner. The test ensures the builder pattern implementation is consistent across all builder methods.

---

Scenario 6: Instant at Midnight UTC

Details:
  TestName: timestampWithMidnightUtcInstantConvertsCorrectly
  Description: This test validates that the timestamp(Instant) method correctly handles an Instant representing midnight UTC. Midnight is a common boundary time and should be handled correctly.

Execution:
  Arrange: Create a MemoryEntry.Builder instance. Create an Instant representing midnight UTC (e.g., Instant.parse("2025-01-15T00:00:00Z")). Create a Content object.
  Act: Call timestamp(Instant) with the midnight Instant. Build the MemoryEntry.
  Assert: Use assertEquals to verify that timestamp() returns "2025-01-15T00:00:00Z".

Validation:
  This test ensures that the method correctly handles midnight times, which are common in date-based operations and can sometimes cause issues in time handling logic. The test confirms that the conversion maintains the correct time representation without any rounding or adjustment errors.

---

Scenario 7: Instant with Maximum Supported Value

Details:
  TestName: timestampWithMaxInstantConvertsCorrectly
  Description: This test checks that the timestamp(Instant) method can handle the maximum value supported by the Instant class (Instant.MAX). This tests the upper boundary of the supported time range.

Execution:
  Arrange: Create a MemoryEntry.Builder instance. Use Instant.MAX to get the maximum supported Instant value. Create a Content object.
  Act: Invoke timestamp(Instant) with Instant.MAX. Build the MemoryEntry.
  Assert: Use assertEquals to verify that timestamp() returns the string representation of Instant.MAX ("+1000000000-12-31T23:59:59.999999999Z").

Validation:
  This assertion validates that the method can handle extreme values at the upper boundary of the Instant range. This is important for ensuring robustness and preventing overflow or conversion errors with very large timestamp values. The test confirms the method works correctly across the entire supported range of Instant values.

---

Scenario 8: Instant with Minimum Supported Value

Details:
  TestName: timestampWithMinInstantConvertsCorrectly
  Description: This test verifies that the timestamp(Instant) method can handle the minimum value supported by the Instant class (Instant.MIN). This tests the lower boundary of the supported time range.

Execution:
  Arrange: Create a MemoryEntry.Builder instance. Use Instant.MIN to get the minimum supported Instant value. Create a Content object.
  Act: Call timestamp(Instant) with Instant.MIN. Build the MemoryEntry.
  Assert: Use assertEquals to verify that timestamp() returns the string representation of Instant.MIN ("-1000000000-01-01T00:00:00Z").

Validation:
  This test ensures that the method can handle extreme values at the lower boundary of the Instant range. This is crucial for applications that might deal with historical data or need to represent very old timestamps. The test confirms that no underflow or conversion errors occur with very small timestamp values.

---

Scenario 9: Current Instant Conversion

Details:
  TestName: timestampWithCurrentInstantConvertsToValidIso8601
  Description: This test validates that the timestamp(Instant) method correctly converts the current system time (Instant.now()) to a valid ISO 8601 string. This simulates a common use case where the current time is used as the timestamp.

Execution:
  Arrange: Create a MemoryEntry.Builder instance. Capture the current Instant using Instant.now(). Store the expected string representation by calling toString() on the Instant. Create a Content object.
  Act: Call timestamp(Instant) with the current Instant. Build the MemoryEntry.
  Assert: Use assertEquals to verify that timestamp() returns the expected ISO 8601 string representation of the current time.

Validation:
  This assertion confirms that the method works correctly with dynamically generated timestamps representing the current time. This is a common use case in real applications where memory entries are timestamped with the current system time. The test ensures the conversion is accurate for real-world scenarios.

---

Scenario 10: Multiple Timestamp Calls Override Previous Value

Details:
  TestName: timestampCalledMultipleTimesUsesLastValue
  Description: This test verifies that calling the timestamp(Instant) method multiple times on the same builder instance results in the last value being used. This tests the builder's behavior when the same property is set multiple times.

Execution:
  Arrange: Create a MemoryEntry.Builder instance. Create two different Instant objects (e.g., Instant.parse("2025-01-15T10:00:00Z") and Instant.parse("2025-01-15T11:00:00Z")). Create a Content object.
  Act: Call timestamp(Instant) with the first Instant, then call it again with the second Instant. Build the MemoryEntry.
  Assert: Use assertEquals to verify that timestamp() returns the string representation of the second Instant ("2025-01-15T11:00:00Z"), confirming the last value overwrites previous values.

Validation:
  This test ensures that the builder follows the expected behavior where subsequent calls to the same setter method override previous values rather than accumulating or causing errors. This is important for understanding the builder's contract and preventing unexpected behavior when the same property is configured multiple times.

---

Scenario 11: Instant with Millisecond Precision

Details:
  TestName: timestampWithMillisecondPrecisionConvertsCorrectly
  Description: This test checks that the timestamp(Instant) method correctly handles Instant objects with millisecond precision, which is a common level of precision in many systems.

Execution:
  Arrange: Create a MemoryEntry.Builder instance. Create an Instant with millisecond precision (e.g., Instant.parse("2025-01-15T10:30:00.123Z")). Create a Content object.
  Act: Invoke timestamp(Instant) with the millisecond-precision Instant. Build the MemoryEntry.
  Assert: Use assertEquals to verify that timestamp() returns "2025-01-15T10:30:00.123Z".

Validation:
  This assertion validates that the method correctly handles the common case of millisecond precision timestamps. Many systems use millisecond precision for timestamps, making this a practical and frequently encountered scenario. The test ensures the conversion maintains the correct precision level without adding or removing digits.

---

Scenario 12: Instant Created from Epoch Milliseconds

Details:
  TestName: timestampWithInstantFromEpochMillisConvertsCorrectly
  Description: This test verifies that the timestamp(Instant) method works correctly with Instant objects created from epoch milliseconds using Instant.ofEpochMilli(). This is a common way to create Instant objects from legacy timestamp formats.

Execution:
  Arrange: Create a MemoryEntry.Builder instance. Create an Instant from epoch milliseconds (e.g., Instant.ofEpochMilli(1705315800000L) which represents 2025-01-15T10:30:00Z). Create a Content object.
  Act: Call timestamp(Instant) with the Instant created from epoch milliseconds. Build the MemoryEntry.
  Assert: Use assertEquals to verify that timestamp() returns the correct ISO 8601 string representation (e.g., "2025-01-15T10:30:00Z").

Validation:
  This test ensures that the method works correctly regardless of how the Instant object was constructed. Many systems store timestamps as epoch milliseconds, and this test confirms that converting such values to Instant and then to ISO 8601 string works correctly. This is important for interoperability with systems using different timestamp formats.

---

Scenario 13: Instant Created from Epoch Seconds

Details:
  TestName: timestampWithInstantFromEpochSecondsConvertsCorrectly
  Description: This test validates that the timestamp(Instant) method correctly handles Instant objects created from epoch seconds using Instant.ofEpochSecond(). This tests another common way of creating Instant objects.

Execution:
  Arrange: Create a MemoryEntry.Builder instance. Create an Instant from epoch seconds (e.g., Instant.ofEpochSecond(1705315800L)). Create a Content object.
  Act: Invoke timestamp(Instant) with the Instant created from epoch seconds. Build the MemoryEntry.
  Assert: Use assertEquals to verify that timestamp() returns the correct ISO 8601 string representation.

Validation:
  This assertion confirms that the method works correctly with Instant objects created from epoch seconds, which is another common timestamp format. The test ensures that the conversion process is independent of how the Instant was constructed, providing flexibility in how timestamps are provided to the builder.

---

Scenario 14: Timestamp Set After Other Builder Methods

Details:
  TestName: timestampSetAfterOtherBuilderMethodsWorksCorrectly
  Description: This test verifies that the timestamp(Instant) method works correctly when called after other builder methods have been invoked. This ensures the order of builder method calls doesn't affect the timestamp setting.

Execution:
  Arrange: Create a MemoryEntry.Builder instance. Create a Content object and an author string. Create an Instant object.
  Act: Call content() and author() methods first, then call timestamp(Instant). Build the MemoryEntry.
  Assert: Use assertEquals to verify that all three properties (content, author, timestamp) are correctly set in the built object.

Validation:
  This test ensures that the builder methods are independent and can be called in any order without affecting each other's functionality. This is important for maintaining a flexible and intuitive builder API where developers don't need to worry about the sequence of method calls.

---

Scenario 15: Timestamp Set Before Other Builder Methods

Details:
  TestName: timestampSetBeforeOtherBuilderMethodsWorksCorrectly
  Description: This test checks that the timestamp(Instant) method works correctly when called before other builder methods. This further validates that the order of builder method calls is flexible.

Execution:
  Arrange: Create a MemoryEntry.Builder instance. Create an Instant object, a Content object, and an author string.
  Act: Call timestamp(Instant) first, then call content() and author() methods. Build the MemoryEntry.
  Assert: Use assertEquals to verify that all three properties are correctly set in the built object, confirming the timestamp was preserved.

Validation:
  This assertion confirms that calling timestamp(Instant) early in the builder chain doesn't cause any issues with subsequent builder method calls. This validates the builder's robustness and ensures developers have complete freedom in organizing their builder method calls.

*/

// ********RoostGPT********

package com.google.adk.memory;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.mock;
import com.google.genai.types.Content;
import java.time.Instant;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.*;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.google.auto.value.AutoValue;
import javax.annotation.Nullable;

class BuilderTimestamp394Test {
    @Test
    @Tag("valid")
    void timestampWithValidInstantConvertsToIso8601String() {
        Instant testInstant = Instant.parse("2025-01-15T10:30:00Z");
        Content mockContent = mock(Content.class);
        
        MemoryEntry.Builder builder = MemoryEntry.builder();
        builder.content(mockContent);
        builder.timestamp(testInstant);
        MemoryEntry memoryEntry = builder.build();
        
        assertEquals("2025-01-15T10:30:00Z", memoryEntry.timestamp());
    }
    @Test
    @Tag("boundary")
    void timestampWithEpochInstantConvertsCorrectly() {
        Instant epochInstant = Instant.EPOCH;
        Content mockContent = mock(Content.class);
        
        MemoryEntry.Builder builder = MemoryEntry.builder();
        builder.content(mockContent);
        builder.timestamp(epochInstant);
        MemoryEntry memoryEntry = builder.build();
        
        assertEquals("1970-01-01T00:00:00Z", memoryEntry.timestamp());
    }
    @Test
    @Tag("valid")
    void timestampWithFutureInstantConvertsCorrectly() {
        Instant futureInstant = Instant.parse("2099-12-31T23:59:59Z");
        Content mockContent = mock(Content.class);
        
        MemoryEntry.Builder builder = MemoryEntry.builder();
        builder.content(mockContent);
        builder.timestamp(futureInstant);
        MemoryEntry memoryEntry = builder.build();
        
        assertEquals("2099-12-31T23:59:59Z", memoryEntry.timestamp());
    }
    @Test
    @Tag("valid")
    void timestampWithNanosecondPrecisionPreservesDetail() {
        Instant nanosecondInstant = Instant.parse("2025-01-15T10:30:00.123456789Z");
        Content mockContent = mock(Content.class);
        
        MemoryEntry.Builder builder = MemoryEntry.builder();
        builder.content(mockContent);
        builder.timestamp(nanosecondInstant);
        MemoryEntry memoryEntry = builder.build();
        
        assertEquals("2025-01-15T10:30:00.123456789Z", memoryEntry.timestamp());
    }
    @Test
    @Tag("valid")
    void timestampReturnsBuilderForMethodChaining() {
        Instant testInstant = Instant.parse("2025-01-15T10:30:00Z");
        Content mockContent = mock(Content.class);
        String author = "testAuthor";
        
        MemoryEntry memoryEntry = MemoryEntry.builder()
                .content(mockContent)
                .author(author)
                .timestamp(testInstant)
                .build();
        
        assertNotNull(memoryEntry);
        assertEquals("2025-01-15T10:30:00Z", memoryEntry.timestamp());
        assertEquals(mockContent, memoryEntry.content());
        assertEquals(author, memoryEntry.author());
    }
    @Test
    @Tag("boundary")
    void timestampWithMidnightUtcInstantConvertsCorrectly() {
        Instant midnightInstant = Instant.parse("2025-01-15T00:00:00Z");
        Content mockContent = mock(Content.class);
        
        MemoryEntry.Builder builder = MemoryEntry.builder();
        builder.content(mockContent);
        builder.timestamp(midnightInstant);
        MemoryEntry memoryEntry = builder.build();
        
        assertEquals("2025-01-15T00:00:00Z", memoryEntry.timestamp());
    }
    @Test
    @Tag("boundary")
    void timestampWithMaxInstantConvertsCorrectly() {
        Instant maxInstant = Instant.MAX;
        Content mockContent = mock(Content.class);
        
        MemoryEntry.Builder builder = MemoryEntry.builder();
        builder.content(mockContent);
        builder.timestamp(maxInstant);
        MemoryEntry memoryEntry = builder.build();
        
        assertEquals("+1000000000-12-31T23:59:59.999999999Z", memoryEntry.timestamp());
    }
    @Test
    @Tag("boundary")
    void timestampWithMinInstantConvertsCorrectly() {
        Instant minInstant = Instant.MIN;
        Content mockContent = mock(Content.class);
        
        MemoryEntry.Builder builder = MemoryEntry.builder();
        builder.content(mockContent);
        builder.timestamp(minInstant);
        MemoryEntry memoryEntry = builder.build();
        
        assertEquals("-1000000000-01-01T00:00:00Z", memoryEntry.timestamp());
    }
    @Test
    @Tag("valid")
    void timestampWithCurrentInstantConvertsToValidIso8601() {
        Instant currentInstant = Instant.now();
        String expectedTimestamp = currentInstant.toString();
        Content mockContent = mock(Content.class);
        
        MemoryEntry.Builder builder = MemoryEntry.builder();
        builder.content(mockContent);
        builder.timestamp(currentInstant);
        MemoryEntry memoryEntry = builder.build();
        
        assertEquals(expectedTimestamp, memoryEntry.timestamp());
    }
    @Test
    @Tag("valid")
    void timestampCalledMultipleTimesUsesLastValue() {
        Instant firstInstant = Instant.parse("2025-01-15T10:00:00Z");
        Instant secondInstant = Instant.parse("2025-01-15T11:00:00Z");
        Content mockContent = mock(Content.class);
        
        MemoryEntry.Builder builder = MemoryEntry.builder();
        builder.content(mockContent);
        builder.timestamp(firstInstant);
        builder.timestamp(secondInstant);
        MemoryEntry memoryEntry = builder.build();
        
        assertEquals("2025-01-15T11:00:00Z", memoryEntry.timestamp());
    }
    @Test
    @Tag("valid")
    void timestampWithMillisecondPrecisionConvertsCorrectly() {
        Instant millisecondInstant = Instant.parse("2025-01-15T10:30:00.123Z");
        Content mockContent = mock(Content.class);
        
        MemoryEntry.Builder builder = MemoryEntry.builder();
        builder.content(mockContent);
        builder.timestamp(millisecondInstant);
        MemoryEntry memoryEntry = builder.build();
        
        assertEquals("2025-01-15T10:30:00.123Z", memoryEntry.timestamp());
    }
    @Test
    @Tag("valid")
    void timestampWithInstantFromEpochMillisConvertsCorrectly() {
        Instant instantFromEpochMillis = Instant.ofEpochMilli(1705315800000L);
        Content mockContent = mock(Content.class);
        
        MemoryEntry.Builder builder = MemoryEntry.builder();
        builder.content(mockContent);
        builder.timestamp(instantFromEpochMillis);
        MemoryEntry memoryEntry = builder.build();
        
        assertEquals("2024-01-15T10:30:00Z", memoryEntry.timestamp());
    }
    @Test
    @Tag("valid")
    void timestampWithInstantFromEpochSecondsConvertsCorrectly() {
        Instant instantFromEpochSeconds = Instant.ofEpochSecond(1705315800L);
        Content mockContent = mock(Content.class);
        
        MemoryEntry.Builder builder = MemoryEntry.builder();
        builder.content(mockContent);
        builder.timestamp(instantFromEpochSeconds);
        MemoryEntry memoryEntry = builder.build();
        
        assertEquals("2024-01-15T10:30:00Z", memoryEntry.timestamp());
    }
    @Test
    @Tag("valid")
    void timestampSetAfterOtherBuilderMethodsWorksCorrectly() {
        Content mockContent = mock(Content.class);
        String author = "testAuthor";
        Instant testInstant = Instant.parse("2025-01-15T10:30:00Z");
        
        MemoryEntry.Builder builder = MemoryEntry.builder();
        builder.content(mockContent);
        builder.author(author);
        builder.timestamp(testInstant);
        MemoryEntry memoryEntry = builder.build();
        
        assertEquals(mockContent, memoryEntry.content());
        assertEquals(author, memoryEntry.author());
        assertEquals("2025-01-15T10:30:00Z", memoryEntry.timestamp());
    }
    @Test
    @Tag("valid")
    void timestampSetBeforeOtherBuilderMethodsWorksCorrectly() {
        Instant testInstant = Instant.parse("2025-01-15T10:30:00Z");
        Content mockContent = mock(Content.class);
        String author = "testAuthor";
        
        MemoryEntry.Builder builder = MemoryEntry.builder();
        builder.timestamp(testInstant);
        builder.content(mockContent);
        builder.author(author);
        MemoryEntry memoryEntry = builder.build();
        
        assertEquals("2025-01-15T10:30:00Z", memoryEntry.timestamp());
        assertEquals(mockContent, memoryEntry.content());
        assertEquals(author, memoryEntry.author());
    }
}