/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-maven-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=setMemories_f68c47b380
ROOST_METHOD_SIG_HASH=setMemories_1236d53c89

Scenario 1: Set Memories with Valid Non-Empty List

Details:
  TestName: setMemoriesWithValidNonEmptyList
  Description: This test verifies that the setMemories method correctly accepts a valid non-empty list of MemoryEntry objects and converts it to an ImmutableList. The method should successfully set the memories and return the Builder instance for method chaining.
Execution:
  Arrange: Create a Builder instance using SearchMemoryResponse.builder(). Create a non-empty List<MemoryEntry> containing one or more valid MemoryEntry objects.
  Act: Invoke the setMemories(List<MemoryEntry>) method on the Builder instance, passing the created list as a parameter.
  Assert: Verify that the method returns a non-null Builder instance. Build the SearchMemoryResponse object and assert that the memories() method returns an ImmutableList containing the same MemoryEntry objects that were passed in, in the same order.
Validation:
  This assertion verifies that the method correctly converts a mutable List to an ImmutableList and stores it in the Builder. This is critical for ensuring data immutability in the final SearchMemoryResponse object. The test confirms that the builder pattern works correctly and that the data is preserved during the conversion process.

Scenario 2: Set Memories with Empty List

Details:
  TestName: setMemoriesWithEmptyList
  Description: This test checks the behavior of the setMemories method when provided with an empty list. The method should handle this edge case gracefully by creating an empty ImmutableList.
Execution:
  Arrange: Create a Builder instance using SearchMemoryResponse.builder(). Create an empty List<MemoryEntry> using new ArrayList<>() or Collections.emptyList().
  Act: Invoke the setMemories(List<MemoryEntry>) method on the Builder instance with the empty list.
  Assert: Verify that the method returns a non-null Builder instance. Build the SearchMemoryResponse and assert that the memories() method returns an empty ImmutableList with size 0.
Validation:
  This test ensures that the method handles empty lists correctly without throwing exceptions. Empty lists are valid inputs and should result in an empty ImmutableList in the response object. This is important for scenarios where a search query returns no results.

Scenario 3: Set Memories with Null List

Details:
  TestName: setMemoriesWithNullList
  Description: This test verifies the error handling behavior when a null list is passed to the setMemories method. Since ImmutableList.copyOf() throws a NullPointerException when given a null argument, this test should expect that exception.
Execution:
  Arrange: Create a Builder instance using SearchMemoryResponse.builder(). Prepare a null reference for List<MemoryEntry>.
  Act: Invoke the setMemories(List<MemoryEntry>) method with the null list parameter.
  Assert: Assert that a NullPointerException is thrown when attempting to set memories with a null list.
Validation:
  This test validates that the method does not silently accept null values, which could lead to unexpected behavior later. The NullPointerException from ImmutableList.copyOf() provides clear feedback that null is not an acceptable input. This enforces defensive programming practices and helps developers identify bugs early.

Scenario 4: Set Memories Multiple Times with Different Lists

Details:
  TestName: setMemoriesMultipleTimesWithDifferentLists
  Description: This test verifies that calling setMemories multiple times on the same Builder instance correctly overwrites the previous value with the new list. Only the last set of memories should be retained.
Execution:
  Arrange: Create a Builder instance. Create two different List<MemoryEntry> objects with distinct MemoryEntry objects (firstList and secondList).
  Act: Call setMemories(firstList) on the Builder, then call setMemories(secondList) on the same Builder instance.
  Assert: Build the SearchMemoryResponse and verify that memories() returns an ImmutableList containing only the entries from secondList, not firstList.
Validation:
  This test confirms that the Builder correctly implements the setter pattern where subsequent calls overwrite previous values rather than appending to them. This is important for ensuring predictable behavior when the Builder is reused or when configuration needs to be changed before building the final object.

Scenario 5: Set Memories with List Containing Null Elements

Details:
  TestName: setMemoriesWithListContainingNullElements
  Description: This test checks the behavior when the input list contains null elements. ImmutableList.copyOf() should throw a NullPointerException when encountering null elements in the source collection.
Execution:
  Arrange: Create a Builder instance. Create a List<MemoryEntry> and add at least one null element to it (e.g., list.add(null)).
  Act: Invoke setMemories with the list containing null elements.
  Assert: Assert that a NullPointerException is thrown during the method execution.
Validation:
  This test ensures that the method enforces non-null constraints on list elements, preventing invalid data from being stored in the SearchMemoryResponse. This is crucial for maintaining data integrity and avoiding NullPointerExceptions in downstream code that processes the memories.

Scenario 6: Set Memories Returns Same Builder Instance for Method Chaining

Details:
  TestName: setMemoriesReturnsSameBuilderInstanceForMethodChaining
  Description: This test verifies that the setMemories method returns the same Builder instance (this) to enable fluent method chaining, which is a common pattern in builder implementations.
Execution:
  Arrange: Create a Builder instance. Create a valid List<MemoryEntry> with at least one MemoryEntry object.
  Act: Invoke setMemories on the Builder and capture the returned Builder instance.
  Assert: Assert that the returned Builder instance is the same object reference as the original Builder instance (using assertSame or checking reference equality).
Validation:
  This test confirms that the Builder follows the fluent interface pattern correctly, allowing developers to chain multiple setter calls together (e.g., builder.setMemories(list).build()). This improves code readability and is a standard expectation for builder pattern implementations.

Scenario 7: Set Memories with Large List

Details:
  TestName: setMemoriesWithLargeList
  Description: This test verifies that the setMemories method can handle a large list of MemoryEntry objects without performance issues or errors. This ensures the method scales appropriately.
Execution:
  Arrange: Create a Builder instance. Create a large List<MemoryEntry> containing a significant number of MemoryEntry objects (e.g., 10,000 or more entries).
  Act: Invoke setMemories with the large list.
  Assert: Verify that the method completes successfully and returns a non-null Builder. Build the SearchMemoryResponse and assert that memories() returns an ImmutableList with the correct size matching the input list size.
Validation:
  This test ensures that the method can handle realistic production scenarios where search results might contain many memory entries. It validates that the ImmutableList.copyOf() operation performs adequately with large datasets and that there are no memory or performance constraints that would cause failures.

Scenario 8: Set Memories Preserves List Order

Details:
  TestName: setMemoriesPreservesListOrder
  Description: This test verifies that the setMemories method preserves the order of elements from the input list when converting to an ImmutableList. The order of memory entries may be significant for search result ranking.
Execution:
  Arrange: Create a Builder instance. Create a List<MemoryEntry> with multiple distinct MemoryEntry objects in a specific order.
  Act: Invoke setMemories with the ordered list.
  Assert: Build the SearchMemoryResponse and verify that memories() returns an ImmutableList where elements appear in the exact same order as the input list. Compare each element by index to ensure order preservation.
Validation:
  This test confirms that the conversion from List to ImmutableList maintains element ordering, which is critical if the memories are sorted by relevance or any other criteria. ImmutableList.copyOf() should preserve iteration order, and this test validates that assumption in the context of this specific method.

Scenario 9: Set Memories Creates Defensive Copy

Details:
  TestName: setMemoriesCreatesDefensiveCopy
  Description: This test verifies that the setMemories method creates a defensive copy of the input list, ensuring that subsequent modifications to the original list do not affect the Builder's internal state.
Execution:
  Arrange: Create a Builder instance. Create a mutable List<MemoryEntry> with several MemoryEntry objects.
  Act: Invoke setMemories with the list, then modify the original list by adding or removing elements.
  Assert: Build the SearchMemoryResponse and verify that memories() returns an ImmutableList that reflects the state of the list at the time setMemories was called, not the modified state.
Validation:
  This test ensures that the Builder is protected from external modifications to the input list after setMemories is called. The ImmutableList.copyOf() method creates a defensive copy, which is essential for maintaining the immutability guarantees of the SearchMemoryResponse object and preventing unexpected side effects.

Scenario 10: Set Memories with Single Element List

Details:
  TestName: setMemoriesWithSingleElementList
  Description: This test verifies that the setMemories method correctly handles a list containing exactly one MemoryEntry object, which is a common edge case between empty and multiple-element lists.
Execution:
  Arrange: Create a Builder instance. Create a List<MemoryEntry> containing exactly one MemoryEntry object.
  Act: Invoke setMemories with the single-element list.
  Assert: Build the SearchMemoryResponse and verify that memories() returns an ImmutableList with size 1, containing the exact MemoryEntry object that was passed in.
Validation:
  This test validates the boundary condition between empty and multi-element lists. Single-element lists are common in scenarios where a search returns exactly one result, and the method should handle this case correctly without any special logic or errors.

*/

// ********RoostGPT********

package com.google.adk.memory;
import static com.google.common.truth.Truth.assertThat;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertThrows;
import com.google.common.collect.ImmutableList;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.*;
import com.google.auto.value.AutoValue;

class BuilderSetMemoriesTest {
  @Test
  @Tag("valid")
  void setMemoriesWithValidNonEmptyList() {
    // Arrange
    SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
    MemoryEntry entry1 = MemoryEntry.builder()
        .content(Content.builder().setText("Test content 1").build())
        .author("Author1")
        .timestamp("2024-01-01T10:00:00Z")
        .build();
    MemoryEntry entry2 = MemoryEntry.builder()
        .content(Content.builder().setText("Test content 2").build())
        .author("Author2")
        .timestamp("2024-01-02T10:00:00Z")
        .build();
    List<MemoryEntry> memoryList = new ArrayList<>();
    memoryList.add(entry1);
    memoryList.add(entry2);
    // Act
    SearchMemoryResponse.Builder resultBuilder = builder.setMemories(memoryList);
    // Assert
    assertThat(resultBuilder).isNotNull();
    SearchMemoryResponse response = resultBuilder.build();
    ImmutableList<MemoryEntry> memories = response.memories();
    assertThat(memories).hasSize(2);
    assertThat(memories.get(0)).isEqualTo(entry1);
    assertThat(memories.get(1)).isEqualTo(entry2);
  }
  @Test
  @Tag("boundary")
  void setMemoriesWithEmptyList() {
    // Arrange
    SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
    List<MemoryEntry> emptyList = new ArrayList<>();
    // Act
    SearchMemoryResponse.Builder resultBuilder = builder.setMemories(emptyList);
    // Assert
    assertThat(resultBuilder).isNotNull();
    SearchMemoryResponse response = resultBuilder.build();
    assertThat(response.memories()).isEmpty();
    assertThat(response.memories()).hasSize(0);
  }
  @Test
  @Tag("invalid")
  void setMemoriesWithNullList() {
    // Arrange
    SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
    List<MemoryEntry> nullList = null;
    // Act & Assert
    assertThrows(NullPointerException.class, () -> {
      builder.setMemories(nullList);
    });
  }
  @Test
  @Tag("valid")
  void setMemoriesMultipleTimesWithDifferentLists() {
    // Arrange
    SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
    MemoryEntry entry1 = MemoryEntry.builder()
        .content(Content.builder().setText("First content").build())
        .author("FirstAuthor")
        .timestamp("2024-01-01T10:00:00Z")
        .build();
    MemoryEntry entry2 = MemoryEntry.builder()
        .content(Content.builder().setText("Second content").build())
        .author("SecondAuthor")
        .timestamp("2024-01-02T10:00:00Z")
        .build();
    List<MemoryEntry> firstList = Collections.singletonList(entry1);
    List<MemoryEntry> secondList = Collections.singletonList(entry2);
    // Act
    builder.setMemories(firstList);
    builder.setMemories(secondList);
    // Assert
    SearchMemoryResponse response = builder.build();
    ImmutableList<MemoryEntry> memories = response.memories();
    assertThat(memories).hasSize(1);
    assertThat(memories.get(0)).isEqualTo(entry2);
    assertThat(memories).doesNotContain(entry1);
  }
  @Test
  @Tag("invalid")
  void setMemoriesWithListContainingNullElements() {
    // Arrange
    SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
    List<MemoryEntry> listWithNull = new ArrayList<>();
    listWithNull.add(null);
    // Act & Assert
    assertThrows(NullPointerException.class, () -> {
      builder.setMemories(listWithNull);
    });
  }
  @Test
  @Tag("valid")
  void setMemoriesReturnsSameBuilderInstanceForMethodChaining() {
    // Arrange
    SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
    MemoryEntry entry = MemoryEntry.builder()
        .content(Content.builder().setText("Test content").build())
        .author("TestAuthor")
        .timestamp("2024-01-01T10:00:00Z")
        .build();
    List<MemoryEntry> memoryList = Collections.singletonList(entry);
    // Act
    SearchMemoryResponse.Builder returnedBuilder = builder.setMemories(memoryList);
    // Assert
    assertSame(builder, returnedBuilder);
  }
  @Test
  @Tag("valid")
  void setMemoriesWithLargeList() {
    // Arrange
    SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
    List<MemoryEntry> largeList = new ArrayList<>();
    for (int i = 0; i < 10000; i++) {
      MemoryEntry entry = MemoryEntry.builder()
          .content(Content.builder().setText("Content " + i).build())
          .author("Author" + i)
          .timestamp("2024-01-01T10:00:00Z")
          .build();
      largeList.add(entry);
    }
    // Act
    SearchMemoryResponse.Builder resultBuilder = builder.setMemories(largeList);
    // Assert
    assertThat(resultBuilder).isNotNull();
    SearchMemoryResponse response = resultBuilder.build();
    assertThat(response.memories()).hasSize(10000);
  }
  @Test
  @Tag("valid")
  void setMemoriesPreservesListOrder() {
    // Arrange
    SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
    MemoryEntry entry1 = MemoryEntry.builder()
        .content(Content.builder().setText("First").build())
        .author("Author1")
        .timestamp("2024-01-01T10:00:00Z")
        .build();
    MemoryEntry entry2 = MemoryEntry.builder()
        .content(Content.builder().setText("Second").build())
        .author("Author2")
        .timestamp("2024-01-02T10:00:00Z")
        .build();
    MemoryEntry entry3 = MemoryEntry.builder()
        .content(Content.builder().setText("Third").build())
        .author("Author3")
        .timestamp("2024-01-03T10:00:00Z")
        .build();
    List<MemoryEntry> orderedList = new ArrayList<>();
    orderedList.add(entry1);
    orderedList.add(entry2);
    orderedList.add(entry3);
    // Act
    builder.setMemories(orderedList);
    // Assert
    SearchMemoryResponse response = builder.build();
    ImmutableList<MemoryEntry> memories = response.memories();
    assertThat(memories.get(0)).isEqualTo(entry1);
    assertThat(memories.get(1)).isEqualTo(entry2);
    assertThat(memories.get(2)).isEqualTo(entry3);
  }
  @Test
  @Tag("valid")
  void setMemoriesCreatesDefensiveCopy() {
    // Arrange
    SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
    MemoryEntry entry1 = MemoryEntry.builder()
        .content(Content.builder().setText("Original content").build())
        .author("OriginalAuthor")
        .timestamp("2024-01-01T10:00:00Z")
        .build();
    List<MemoryEntry> mutableList = new ArrayList<>();
    mutableList.add(entry1);
    // Act
    builder.setMemories(mutableList);
    MemoryEntry entry2 = MemoryEntry.builder()
        .content(Content.builder().setText("Modified content").build())
        .author("ModifiedAuthor")
        .timestamp("2024-01-02T10:00:00Z")
        .build();
    mutableList.add(entry2);
    // Assert
    SearchMemoryResponse response = builder.build();
    ImmutableList<MemoryEntry> memories = response.memories();
    assertThat(memories).hasSize(1);
    assertThat(memories.get(0)).isEqualTo(entry1);
    assertThat(memories).doesNotContain(entry2);
  }
  @Test
  @Tag("boundary")
  void setMemoriesWithSingleElementList() {
    // Arrange
    SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
    MemoryEntry singleEntry = MemoryEntry.builder()
        .content(Content.builder().setText("Single content").build())
        .author("SingleAuthor")
        .timestamp("2024-01-01T10:00:00Z")
        .build();
    List<MemoryEntry> singleElementList = Collections.singletonList(singleEntry);
    // Act
    builder.setMemories(singleElementList);
    // Assert
    SearchMemoryResponse response = builder.build();
    ImmutableList<MemoryEntry> memories = response.memories();
    assertThat(memories).hasSize(1);
    assertThat(memories.get(0)).isEqualTo(singleEntry);
  }
}