/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-maven-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=create_c4720e4470
ROOST_METHOD_SIG_HASH=create_f5f81571a8

Scenario 1: Successfully Create a New Builder Instance

Details:
  TestName: createReturnsNewBuilderInstance
  Description: This test verifies that the create() method successfully returns a new instance of the Builder class. The method should instantiate and return a Builder object that can be used to construct MemoryEntry objects.
Execution:
  Arrange: No specific setup is required as the create() method is a static factory method with no parameters.
  Act: Invoke the Builder.create() method to obtain a Builder instance.
  Assert: Use assertNotNull() to verify that the returned Builder instance is not null. Use assertInstanceOf() or assertTrue() with instanceof to confirm the returned object is of type MemoryEntry.Builder.
Validation:
  The assertion verifies that the create() method properly instantiates and returns a Builder object. This is critical because the Builder is the entry point for creating MemoryEntry objects using the builder pattern. A null return value would prevent any MemoryEntry creation, breaking the entire API. This test ensures the factory method works as expected and provides a valid starting point for building MemoryEntry instances.

Scenario 2: Create Returns Independent Builder Instances

Details:
  TestName: createReturnsIndependentBuilderInstances
  Description: This test ensures that multiple invocations of the create() method return distinct Builder instances rather than reusing the same object. Each call should produce a new, independent Builder to prevent state sharing between different MemoryEntry construction processes.
Execution:
  Arrange: No specific setup is required.
  Act: Call Builder.create() twice to obtain two separate Builder instances (builder1 and builder2).
  Assert: Use assertNotSame() to verify that builder1 and builder2 are different object instances. Additionally, use assertNotEquals() on the object references to confirm they are not the same object.
Validation:
  This assertion confirms that each invocation of create() produces a new Builder instance rather than returning a singleton or cached object. This is essential for thread safety and preventing unintended state sharing. If the same Builder instance were returned, modifications to one builder would affect others, leading to unpredictable behavior and potential bugs in concurrent environments. Independent instances ensure that each MemoryEntry construction process is isolated.

Scenario 3: Created Builder Can Set Content Field

Details:
  TestName: createdBuilderCanSetContentField
  Description: This test verifies that a Builder instance returned by create() can successfully use the content() method to set the Content field. This ensures the Builder is properly initialized and functional for setting required fields.
Execution:
  Arrange: Create a mock or test Content object to use as the content value.
  Act: Call Builder.create() to get a Builder instance, then invoke the content() method with the test Content object.
  Assert: Verify that the content() method call does not throw any exceptions. Optionally, verify that the method returns the Builder instance itself (for method chaining) using assertSame() or assertNotNull().
Validation:
  This test ensures that the Builder returned by create() is fully functional and can accept the required content field. Since content is a required field for MemoryEntry, the ability to set it is fundamental to the Builder's purpose. This test validates that the AutoValue-generated Builder is properly configured and that the create() method returns a usable Builder instance, not a broken or improperly initialized object.

Scenario 4: Created Builder Can Set Optional Author Field

Details:
  TestName: createdBuilderCanSetOptionalAuthorField
  Description: This test confirms that a Builder instance obtained from create() can successfully set the optional author field using the author() method. This validates that optional fields are properly supported by the created Builder.
Execution:
  Arrange: Prepare a test string value to use as the author (e.g., "Test Author").
  Act: Call Builder.create() to obtain a Builder instance, then invoke the author() method with the test string.
  Assert: Verify that the author() method executes without throwing exceptions. Confirm that the method returns the Builder instance for method chaining.
Validation:
  This assertion verifies that the Builder created by the create() method properly supports setting optional fields. The author field is marked with @Nullable, indicating it's optional. The test ensures that the Builder infrastructure correctly handles optional fields and that the create() method returns a Builder capable of accepting both required and optional parameters. This is important for the flexibility of the MemoryEntry construction process.

Scenario 5: Created Builder Can Set Optional Timestamp Field with String

Details:
  TestName: createdBuilderCanSetOptionalTimestampFieldWithString
  Description: This test validates that a Builder instance from create() can successfully set the optional timestamp field using a String value through the timestamp(String) method.
Execution:
  Arrange: Prepare a test timestamp string in ISO 8601 format (e.g., "2025-01-15T10:30:00Z").
  Act: Call Builder.create() to get a Builder instance, then invoke the timestamp(String) method with the test timestamp string.
  Assert: Verify that the timestamp() method executes without exceptions and returns the Builder instance for chaining.
Validation:
  This test ensures that the Builder returned by create() properly supports the timestamp(String) method for setting the optional timestamp field. Since timestamp is nullable and can be set with a String, this test confirms that the Builder infrastructure correctly handles this optional field type. This is crucial for scenarios where timestamps need to be set in string format, particularly when deserializing from JSON or receiving timestamp data as strings.

Scenario 6: Created Builder Can Set Timestamp Field with Instant

Details:
  TestName: createdBuilderCanSetTimestampFieldWithInstant
  Description: This test verifies that a Builder instance obtained from create() can successfully use the convenience method timestamp(Instant) to set the timestamp field using an Instant object.
Execution:
  Arrange: Create an Instant object representing a specific point in time (e.g., Instant.now() or Instant.parse("2025-01-15T10:30:00Z")).
  Act: Call Builder.create() to obtain a Builder instance, then invoke the timestamp(Instant) method with the test Instant object.
  Assert: Verify that the method executes without throwing exceptions and returns the Builder instance.
Validation:
  This assertion confirms that the Builder created by create() supports the convenience method for setting timestamps using Instant objects. This method internally converts the Instant to an ISO 8601 string format. The test validates that the Builder is fully functional with all provided methods, including convenience methods that enhance usability. This is important for developers who work with Java's time API and prefer using Instant objects rather than string representations.

Scenario 7: Created Builder Can Build Complete MemoryEntry

Details:
  TestName: createdBuilderCanBuildCompleteMemoryEntry
  Description: This test ensures that a Builder instance returned by create() can successfully build a complete MemoryEntry object after setting all required fields. This validates the end-to-end functionality of the Builder.
Execution:
  Arrange: Create a test Content object with appropriate data.
  Act: Call Builder.create(), set the required content field using content(), and then invoke the build() method.
  Assert: Use assertNotNull() to verify that the build() method returns a non-null MemoryEntry object. Use assertInstanceOf() to confirm the returned object is of type MemoryEntry.
Validation:
  This test validates the complete workflow from creating a Builder to producing a MemoryEntry object. It ensures that the create() method returns a Builder that can successfully complete the building process when all required fields are set. This is critical because it confirms that the Builder is not just instantiated but is fully functional and properly integrated with the AutoValue-generated code. A successful build indicates that the create() method fulfills its purpose as a factory method for creating functional Builders.

Scenario 8: Created Builder Can Build MemoryEntry with All Fields

Details:
  TestName: createdBuilderCanBuildMemoryEntryWithAllFields
  Description: This test verifies that a Builder from create() can build a MemoryEntry with all fields (both required and optional) properly set. This ensures comprehensive Builder functionality.
Execution:
  Arrange: Prepare test data for all fields: a Content object, an author string, and a timestamp string.
  Act: Call Builder.create(), set all fields using content(), author(), and timestamp(), then invoke build().
  Assert: Verify that build() returns a non-null MemoryEntry object. Optionally, verify that the returned MemoryEntry contains the expected values using the accessor methods (content(), author(), timestamp()).
Validation:
  This assertion confirms that the Builder created by create() can handle setting and building a MemoryEntry with all available fields populated. This tests the Builder's capability to manage both required and optional fields simultaneously. It's important for ensuring that the Builder works correctly in scenarios where clients want to provide complete information for a MemoryEntry, including all optional metadata like author and timestamp.

Scenario 9: Multiple Builders Created Independently Can Build Different Entries

Details:
  TestName: multipleCreatedBuildersCanBuildDifferentEntries
  Description: This test ensures that multiple Builder instances created by separate calls to create() can independently build different MemoryEntry objects without interfering with each other.
Execution:
  Arrange: Create two different Content objects (content1 and content2) with distinct data.
  Act: Call Builder.create() twice to get two Builder instances (builder1 and builder2). Set builder1 with content1 and builder2 with content2. Build both MemoryEntry objects (entry1 and entry2).
  Assert: Use assertNotNull() on both entries. Use assertNotSame() to verify entry1 and entry2 are different objects. Verify that entry1.content() returns content1 and entry2.content() returns content2 using assertEquals().
Validation:
  This test validates that the create() method produces truly independent Builder instances that don't share state. This is crucial for concurrent usage and general correctness of the Builder pattern. If Builders shared state, setting values in one Builder could affect another, leading to data corruption and unpredictable behavior. This test ensures that each create() call produces an isolated Builder that can safely build its own MemoryEntry without side effects on other Builders.

Scenario 10: Created Builder Supports Method Chaining

Details:
  TestName: createdBuilderSupportsMethodChaining
  Description: This test verifies that the Builder returned by create() supports fluent method chaining, allowing multiple setter methods to be called in sequence.
Execution:
  Arrange: Prepare test data: a Content object, an author string, and a timestamp string.
  Act: Call Builder.create() and chain multiple method calls: create().content(testContent).author(testAuthor).timestamp(testTimestamp).build().
  Assert: Verify that the chained method calls execute without exceptions and that build() returns a non-null MemoryEntry object.
Validation:
  This assertion confirms that the Builder created by create() properly implements the fluent interface pattern, where each setter method returns the Builder instance itself. Method chaining is a key feature of the Builder pattern that improves code readability and reduces verbosity. This test ensures that the AutoValue-generated Builder maintains this important characteristic and that the create() method returns a Builder that fully supports this programming style.

Scenario 11: Created Builder with JsonCreator Annotation Works for Deserialization

Details:
  TestName: createdBuilderWithJsonCreatorAnnotationSupportsDeserialization
  Description: This test verifies that the create() method, annotated with @JsonCreator, is properly configured to support JSON deserialization through Jackson. This ensures the Builder can be instantiated during JSON parsing.
Execution:
  Arrange: No specific setup required for this unit test, as full deserialization testing would require integration testing with Jackson ObjectMapper.
  Act: Call Builder.create() to verify the method is accessible and functional.
  Assert: Verify that the method returns a non-null Builder instance. This confirms the method is properly exposed for Jackson to use during deserialization.
Validation:
  The @JsonCreator annotation on the create() method indicates it's the designated factory method for Jackson deserialization. This test ensures the method is functional and accessible, which is a prerequisite for JSON deserialization to work. While full deserialization testing requires integration tests, this unit test confirms that the basic factory method works correctly. This is important because if the create() method fails, JSON deserialization of MemoryEntry objects would be impossible, breaking any API or persistence layer that relies on JSON serialization.

Scenario 12: Created Builder Can Be Used with toBuilder Pattern

Details:
  TestName: createdBuilderCanBeUsedWithToBuilderPattern
  Description: This test verifies that a Builder created by create() can build a MemoryEntry, and that MemoryEntry can then create a new Builder using toBuilder(), demonstrating compatibility with the copy-and-modify pattern.
Execution:
  Arrange: Create a test Content object.
  Act: Call Builder.create(), set the content field, and build a MemoryEntry. Then call toBuilder() on the created MemoryEntry to get a new Builder instance.
  Assert: Verify that both the original MemoryEntry and the new Builder from toBuilder() are not null. Verify that the new Builder is a different instance from the original Builder.
Validation:
  This test ensures that the Builder created by create() integrates properly with the toBuilder() pattern, which is commonly used for creating modified copies of immutable objects. While this test focuses on the create() method, it validates that Builders created by create() produce MemoryEntry objects that fully support the AutoValue-generated API, including toBuilder(). This is important for ensuring consistency across the entire MemoryEntry API and confirming that create() produces Builders that work seamlessly with other parts of the system.

*/

// ********RoostGPT********

package com.google.adk.memory;
import static com.google.common.truth.Truth.assertThat;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNotSame;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import com.google.genai.types.Content;
import java.time.Instant;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.*;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.google.auto.value.AutoValue;
import javax.annotation.Nullable;

class BuilderCreateTest {
    @Test
    @Tag("valid")
    void createReturnsNewBuilderInstance() {
        // Act
        MemoryEntry.Builder builder = MemoryEntry.Builder.create();
        // Assert
        assertNotNull(builder);
        assertTrue(builder instanceof MemoryEntry.Builder);
    }
    @Test
    @Tag("valid")
    void createReturnsIndependentBuilderInstances() {
        // Act
        MemoryEntry.Builder builder1 = MemoryEntry.Builder.create();
        MemoryEntry.Builder builder2 = MemoryEntry.Builder.create();
        // Assert
        assertNotNull(builder1);
        assertNotNull(builder2);
        assertNotSame(builder1, builder2);
        assertThat(builder1).isNotSameInstanceAs(builder2);
    }
    @Test
    @Tag("valid")
    void createdBuilderCanSetContentField() {
        // Arrange
        Content testContent = mock(Content.class);
        // Act
        MemoryEntry.Builder builder = MemoryEntry.Builder.create();
        MemoryEntry.Builder result = builder.content(testContent);
        // Assert
        assertNotNull(result);
        assertThat(result).isSameInstanceAs(builder);
    }
    @Test
    @Tag("valid")
    void createdBuilderCanSetOptionalAuthorField() {
        // Arrange
        String testAuthor = "Test Author";
        // Act
        MemoryEntry.Builder builder = MemoryEntry.Builder.create();
        MemoryEntry.Builder result = builder.author(testAuthor);
        // Assert
        assertNotNull(result);
        assertThat(result).isSameInstanceAs(builder);
    }
    @Test
    @Tag("valid")
    void createdBuilderCanSetOptionalTimestampFieldWithString() {
        // Arrange
        String testTimestamp = "2025-01-15T10:30:00Z";
        // Act
        MemoryEntry.Builder builder = MemoryEntry.Builder.create();
        MemoryEntry.Builder result = builder.timestamp(testTimestamp);
        // Assert
        assertNotNull(result);
        assertThat(result).isSameInstanceAs(builder);
    }
    @Test
    @Tag("valid")
    void createdBuilderCanSetTimestampFieldWithInstant() {
        // Arrange
        Instant testInstant = Instant.parse("2025-01-15T10:30:00Z");
        // Act
        MemoryEntry.Builder builder = MemoryEntry.Builder.create();
        MemoryEntry.Builder result = builder.timestamp(testInstant);
        // Assert
        assertNotNull(result);
        assertThat(result).isSameInstanceAs(builder);
    }
    @Test
    @Tag("valid")
    void createdBuilderCanBuildCompleteMemoryEntry() {
        // Arrange
        Content testContent = mock(Content.class);
        // Act
        MemoryEntry.Builder builder = MemoryEntry.Builder.create();
        MemoryEntry entry = builder.content(testContent).build();
        // Assert
        assertNotNull(entry);
        assertTrue(entry instanceof MemoryEntry);
        assertThat(entry.content()).isEqualTo(testContent);
    }
    @Test
    @Tag("valid")
    void createdBuilderCanBuildMemoryEntryWithAllFields() {
        // Arrange
        Content testContent = mock(Content.class);
        String testAuthor = "Test Author";
        String testTimestamp = "2025-01-15T10:30:00Z";
        // Act
        MemoryEntry.Builder builder = MemoryEntry.Builder.create();
        MemoryEntry entry = builder
                .content(testContent)
                .author(testAuthor)
                .timestamp(testTimestamp)
                .build();
        // Assert
        assertNotNull(entry);
        assertThat(entry.content()).isEqualTo(testContent);
        assertThat(entry.author()).isEqualTo(testAuthor);
        assertThat(entry.timestamp()).isEqualTo(testTimestamp);
    }
    @Test
    @Tag("valid")
    void multipleCreatedBuildersCanBuildDifferentEntries() {
        // Arrange
        Content content1 = mock(Content.class);
        Content content2 = mock(Content.class);
        // Act
        MemoryEntry.Builder builder1 = MemoryEntry.Builder.create();
        MemoryEntry.Builder builder2 = MemoryEntry.Builder.create();
        
        MemoryEntry entry1 = builder1.content(content1).build();
        MemoryEntry entry2 = builder2.content(content2).build();
        // Assert
        assertNotNull(entry1);
        assertNotNull(entry2);
        assertNotSame(entry1, entry2);
        assertThat(entry1.content()).isEqualTo(content1);
        assertThat(entry2.content()).isEqualTo(content2);
        assertThat(entry1.content()).isNotEqualTo(entry2.content());
    }
    @Test
    @Tag("valid")
    void createdBuilderSupportsMethodChaining() {
        // Arrange
        Content testContent = mock(Content.class);
        String testAuthor = "Test Author";
        String testTimestamp = "2025-01-15T10:30:00Z";
        // Act
        MemoryEntry entry = MemoryEntry.Builder.create()
                .content(testContent)
                .author(testAuthor)
                .timestamp(testTimestamp)
                .build();
        // Assert
        assertNotNull(entry);
        assertThat(entry.content()).isEqualTo(testContent);
        assertThat(entry.author()).isEqualTo(testAuthor);
        assertThat(entry.timestamp()).isEqualTo(testTimestamp);
    }
    @Test
    @Tag("integration")
    void createdBuilderWithJsonCreatorAnnotationSupportsDeserialization() {
        // Act
        MemoryEntry.Builder builder = MemoryEntry.Builder.create();
        // Assert
        assertNotNull(builder);
        assertTrue(builder instanceof MemoryEntry.Builder);
    }
    @Test
    @Tag("valid")
    void createdBuilderCanBeUsedWithToBuilderPattern() {
        // Arrange
        Content testContent = mock(Content.class);
        // Act
        MemoryEntry.Builder originalBuilder = MemoryEntry.Builder.create();
        MemoryEntry entry = originalBuilder.content(testContent).build();
        MemoryEntry.Builder newBuilder = entry.toBuilder();
        // Assert
        assertNotNull(entry);
        assertNotNull(newBuilder);
        assertNotSame(originalBuilder, newBuilder);
        assertThat(newBuilder).isNotSameInstanceAs(originalBuilder);
    }
    @Test
    @Tag("valid")
    void createdBuilderCanSetNullAuthor() {
        // Act
        MemoryEntry.Builder builder = MemoryEntry.Builder.create();
        MemoryEntry.Builder result = builder.author(null);
        // Assert
        assertNotNull(result);
        assertThat(result).isSameInstanceAs(builder);
    }
    @Test
    @Tag("valid")
    void createdBuilderCanSetNullTimestamp() {
        // Act
        MemoryEntry.Builder builder = MemoryEntry.Builder.create();
        MemoryEntry.Builder result = builder.timestamp((String) null);
        // Assert
        assertNotNull(result);
        assertThat(result).isSameInstanceAs(builder);
    }
    @Test
    @Tag("valid")
    void createdBuilderCanBuildWithOnlyRequiredFields() {
        // Arrange
        Content testContent = mock(Content.class);
        // Act
        MemoryEntry entry = MemoryEntry.Builder.create()
                .content(testContent)
                .build();
        // Assert
        assertNotNull(entry);
        assertThat(entry.content()).isEqualTo(testContent);
        assertThat(entry.author()).isNull();
        assertThat(entry.timestamp()).isNull();
    }
    @Test
    @Tag("valid")
    void createdBuilderWithInstantTimestampConvertsToString() {
        // Arrange
        Content testContent = mock(Content.class);
        Instant testInstant = Instant.parse("2025-01-15T10:30:00Z");
        // Act
        MemoryEntry entry = MemoryEntry.Builder.create()
                .content(testContent)
                .timestamp(testInstant)
                .build();
        // Assert
        assertNotNull(entry);
        assertThat(entry.timestamp()).isEqualTo(testInstant.toString());
    }
    @Test
    @Tag("boundary")
    void createdBuilderWithEmptyAuthorString() {
        // Arrange
        Content testContent = mock(Content.class);
        String emptyAuthor = "";
        // Act
        MemoryEntry entry = MemoryEntry.Builder.create()
                .content(testContent)
                .author(emptyAuthor)
                .build();
        // Assert
        assertNotNull(entry);
        assertThat(entry.author()).isEqualTo(emptyAuthor);
    }
    @Test
    @Tag("boundary")
    void createdBuilderWithEmptyTimestampString() {
        // Arrange
        Content testContent = mock(Content.class);
        String emptyTimestamp = "";
        // Act
        MemoryEntry entry = MemoryEntry.Builder.create()
                .content(testContent)
                .timestamp(emptyTimestamp)
                .build();
        // Assert
        assertNotNull(entry);
        assertThat(entry.timestamp()).isEqualTo(emptyTimestamp);
    }
    @Test
    @Tag("valid")
    void createdBuilderCanOverwriteFields() {
        // Arrange
        Content content1 = mock(Content.class);
        Content content2 = mock(Content.class);
        String author1 = "Author 1";
        String author2 = "Author 2";
        // Act
        MemoryEntry entry = MemoryEntry.Builder.create()
                .content(content1)
                .author(author1)
                .content(content2)
                .author(author2)
                .build();
        // Assert
        assertNotNull(entry);
        assertThat(entry.content()).isEqualTo(content2);
        assertThat(entry.author()).isEqualTo(author2);
    }
    @Test
    @Tag("valid")
    void multipleSequentialCreatesProduceIndependentBuilders() {
        // Arrange
        Content content1 = mock(Content.class);
        Content content2 = mock(Content.class);
        Content content3 = mock(Content.class);
        // Act
        MemoryEntry.Builder builder1 = MemoryEntry.Builder.create();
        MemoryEntry.Builder builder2 = MemoryEntry.Builder.create();
        MemoryEntry.Builder builder3 = MemoryEntry.Builder.create();
        MemoryEntry entry1 = builder1.content(content1).build();
        MemoryEntry entry2 = builder2.content(content2).build();
        MemoryEntry entry3 = builder3.content(content3).build();
        // Assert
        assertThat(entry1.content()).isEqualTo(content1);
        assertThat(entry2.content()).isEqualTo(content2);
        assertThat(entry3.content()).isEqualTo(content3);
        assertNotSame(entry1, entry2);
        assertNotSame(entry2, entry3);
        assertNotSame(entry1, entry3);
    }
}