/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-maven-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=build_5cdae410dd
ROOST_METHOD_SIG_HASH=build_5cdae410dd

Scenario 1: Build SearchMemoryResponse with Default Empty Memories List

Details:
  TestName: buildWithDefaultEmptyMemoriesList
  Description: This test verifies that the build() method successfully creates a SearchMemoryResponse object when no memories are explicitly set, using the default empty ImmutableList that is initialized in the builder() factory method.
Execution:
  Arrange: Create a new Builder instance using SearchMemoryResponse.builder() which initializes memories with an empty ImmutableList.
  Act: Call the build() method on the Builder instance without setting any memories.
  Assert: Verify that the returned SearchMemoryResponse object is not null and that the memories() method returns an empty ImmutableList with size 0.
Validation:
  The assertion verifies that the build() method can successfully construct a valid SearchMemoryResponse object with default values. This is important because it ensures that the builder pattern works correctly with AutoValue's default initialization, allowing users to create response objects without explicitly setting all fields. This scenario represents a valid use case where a memory search returns no results.

Scenario 2: Build SearchMemoryResponse with Single MemoryEntry

Details:
  TestName: buildWithSingleMemoryEntry
  Description: This test validates that the build() method correctly creates a SearchMemoryResponse object when a single MemoryEntry is added to the memories list using the setMemories(List<MemoryEntry>) method.
Execution:
  Arrange: Create a Builder instance and prepare a List containing one MemoryEntry object. Use setMemories() to add this list to the builder.
  Act: Invoke the build() method on the configured Builder instance.
  Assert: Verify that the returned SearchMemoryResponse is not null, that memories() returns an ImmutableList with size 1, and that the single MemoryEntry in the list matches the one that was set.
Validation:
  This assertion confirms that the build() method properly constructs the SearchMemoryResponse with a single memory entry and that the data is correctly transferred from the builder to the immutable object. This scenario is significant for testing the most basic successful search result case where exactly one memory matches the search criteria.

Scenario 3: Build SearchMemoryResponse with Multiple MemoryEntries

Details:
  TestName: buildWithMultipleMemoryEntries
  Description: This test ensures that the build() method correctly handles and constructs a SearchMemoryResponse object when multiple MemoryEntry objects are provided through the setMemories(List<MemoryEntry>) method.
Execution:
  Arrange: Create a Builder instance and prepare a List containing multiple MemoryEntry objects (e.g., 3-5 entries). Set this list using the setMemories() method.
  Act: Call the build() method on the Builder instance.
  Assert: Verify that the returned SearchMemoryResponse is not null, that memories() returns an ImmutableList with the correct size matching the number of entries added, and that all MemoryEntry objects are present in the correct order.
Validation:
  The assertion validates that the build() method can handle multiple memory entries and maintains the order and integrity of the data. This is crucial for real-world scenarios where memory searches typically return multiple results, and the application needs to process all of them in the order they were provided.

Scenario 4: Build SearchMemoryResponse After Overwriting Memories

Details:
  TestName: buildAfterOverwritingMemories
  Description: This test verifies that the build() method uses the most recently set memories list when setMemories() is called multiple times on the same Builder instance, ensuring that previous values are properly overwritten.
Execution:
  Arrange: Create a Builder instance. First, set memories with an initial list of MemoryEntry objects. Then, call setMemories() again with a different list of MemoryEntry objects.
  Act: Invoke the build() method on the Builder instance.
  Assert: Verify that the returned SearchMemoryResponse contains only the memories from the second setMemories() call, not the first, by checking the size and contents of the memories() list.
Validation:
  This assertion ensures that the builder correctly implements the overwrite behavior expected in builder patterns, where the last set value takes precedence. This is important for scenarios where the builder might be reused or where memory lists need to be updated before building the final response object.

Scenario 5: Build SearchMemoryResponse with Empty List Explicitly Set

Details:
  TestName: buildWithExplicitlySetEmptyList
  Description: This test confirms that the build() method correctly handles the case where an empty list is explicitly set using setMemories(List<MemoryEntry>) with an empty collection, as opposed to using the default empty list.
Execution:
  Arrange: Create a Builder instance and explicitly call setMemories() with an empty List<MemoryEntry> (e.g., new ArrayList<>() or Collections.emptyList()).
  Act: Call the build() method on the Builder instance.
  Assert: Verify that the returned SearchMemoryResponse is not null and that memories() returns an empty ImmutableList with size 0.
Validation:
  The assertion validates that explicitly setting an empty list produces the same result as the default behavior, ensuring consistency in the API. This scenario is important for cases where the empty list might be computed or passed from another method, and the builder should handle it gracefully without throwing exceptions.

Scenario 6: Build SearchMemoryResponse with ImmutableList Directly

Details:
  TestName: buildWithImmutableListDirectly
  Description: This test verifies that the build() method works correctly when memories are set using an ImmutableList directly through the package-private setMemories(ImmutableList<MemoryEntry>) method, which is called internally by the public setMemories(List<MemoryEntry>) method.
Execution:
  Arrange: Create a Builder instance and prepare an ImmutableList containing MemoryEntry objects. Since the setMemories(ImmutableList<MemoryEntry>) method is abstract and package-private, this scenario tests the internal behavior that occurs when the public setMemories(List<MemoryEntry>) method calls ImmutableList.copyOf().
  Act: Call setMemories() with a regular List, which internally converts it to ImmutableList, then invoke build().
  Assert: Verify that the returned SearchMemoryResponse contains an ImmutableList with the correct MemoryEntry objects and that the list is truly immutable.
Validation:
  This assertion ensures that the internal conversion to ImmutableList works correctly and that the final SearchMemoryResponse object contains an immutable collection that cannot be modified after construction. This is critical for maintaining the immutability contract of the AutoValue-generated class and preventing unintended modifications to the response object.

Scenario 7: Build Multiple SearchMemoryResponse Objects from Same Builder

Details:
  TestName: buildMultipleResponsesFromSameBuilder
  Description: This test examines whether the build() method can be called multiple times on the same Builder instance and whether each call produces a separate, independent SearchMemoryResponse object.
Execution:
  Arrange: Create a Builder instance and set memories with a list of MemoryEntry objects.
  Act: Call the build() method twice on the same Builder instance to create two SearchMemoryResponse objects.
  Assert: Verify that both returned SearchMemoryResponse objects are not null, that they are separate instances (not the same reference), and that both contain the same memory data.
Validation:
  The assertion validates that the build() method can be safely called multiple times and that each invocation creates a new independent object. This is important for understanding the builder's reusability and ensuring that modifications to one built object do not affect others. This behavior is typical of AutoValue builders and is important for scenarios where the same configuration might be used to create multiple response objects.

Scenario 8: Build SearchMemoryResponse and Verify Immutability of Memories List

Details:
  TestName: buildAndVerifyMemoriesListImmutability
  Description: This test ensures that the memories list in the built SearchMemoryResponse object is truly immutable and that attempts to modify it (if the reference is obtained) will fail, maintaining the integrity of the response object.
Execution:
  Arrange: Create a Builder instance, set memories with a mutable List of MemoryEntry objects, and build the SearchMemoryResponse.
  Act: Call build() to create the SearchMemoryResponse object, then retrieve the memories list using the memories() method.
  Assert: Verify that the returned list is an instance of ImmutableList and that any attempt to modify it (such as calling add() or remove()) throws an UnsupportedOperationException.
Validation:
  This assertion confirms that the build() method properly creates an immutable response object where the memories list cannot be modified after construction. This is crucial for thread safety and preventing bugs caused by unintended modifications to response objects. The immutability guarantee is a key feature of the AutoValue pattern and ensures that SearchMemoryResponse objects can be safely shared across different parts of the application.

Scenario 9: Build SearchMemoryResponse with Null List Handling

Details:
  TestName: buildWithNullListHandling
  Description: This test verifies the behavior of the build() method when a null value is passed to setMemories(List<MemoryEntry>), checking whether it throws a NullPointerException or handles the null value gracefully.
Execution:
  Arrange: Create a Builder instance and attempt to call setMemories() with a null List parameter.
  Act: Invoke the build() method after setting memories to null.
  Assert: Verify that either a NullPointerException is thrown during the setMemories() call (due to ImmutableList.copyOf(null)) or during the build() call, depending on when the validation occurs.
Validation:
  This assertion validates the error handling behavior of the builder when invalid input is provided. Since ImmutableList.copyOf() throws NullPointerException for null inputs, this test ensures that the builder fails fast with a clear error rather than allowing the construction of an invalid SearchMemoryResponse object. This is important for catching programming errors early and providing clear feedback to developers about invalid API usage.

Scenario 10: Build SearchMemoryResponse with Large Number of MemoryEntries

Details:
  TestName: buildWithLargeNumberOfMemoryEntries
  Description: This test validates that the build() method can handle and correctly construct a SearchMemoryResponse object when a large number of MemoryEntry objects (e.g., 1000 or more) are provided, ensuring there are no performance issues or limitations.
Execution:
  Arrange: Create a Builder instance and prepare a List containing a large number of MemoryEntry objects (e.g., 1000 entries). Set this list using setMemories().
  Act: Call the build() method on the Builder instance.
  Assert: Verify that the returned SearchMemoryResponse is not null, that memories() returns an ImmutableList with the correct size (1000), and that the build operation completes within a reasonable time frame.
Validation:
  The assertion ensures that the build() method can scale to handle realistic production scenarios where memory searches might return large result sets. This test is important for identifying potential performance bottlenecks or memory issues that could arise when dealing with large collections. It validates that the ImmutableList.copyOf() operation and the AutoValue object construction can handle large datasets efficiently.

*/

// ********RoostGPT********

package com.google.adk.memory;
import static com.google.common.truth.Truth.assertThat;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import com.google.common.collect.ImmutableList;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.*;
import com.google.auto.value.AutoValue;

class BuilderBuildTest {
  @Test
  @Tag("valid")
  void buildWithDefaultEmptyMemoriesList() {
    SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
    SearchMemoryResponse response = builder.build();
    assertNotNull(response);
    assertThat(response.memories()).isNotNull();
    assertThat(response.memories()).isEmpty();
    assertThat(response.memories()).hasSize(0);
  }
  @Test
  @Tag("valid")
  void buildWithSingleMemoryEntry() {
    MemoryEntry memoryEntry = MemoryEntry.builder()
        .setContent(createDummyContent())
        .setAuthor("testAuthor")
        .setTimestamp("2024-01-01T00:00:00Z")
        .build();
    List<MemoryEntry> memoryList = new ArrayList<>();
    memoryList.add(memoryEntry);
    SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
    builder.setMemories(memoryList);
    SearchMemoryResponse response = builder.build();
    assertNotNull(response);
    assertThat(response.memories()).isNotNull();
    assertThat(response.memories()).hasSize(1);
    assertThat(response.memories().get(0)).isEqualTo(memoryEntry);
  }
  @Test
  @Tag("valid")
  void buildWithMultipleMemoryEntries() {
    List<MemoryEntry> memoryList = new ArrayList<>();
    for (int i = 0; i < 5; i++) {
      MemoryEntry memoryEntry = MemoryEntry.builder()
          .setContent(createDummyContent())
          .setAuthor("author" + i)
          .setTimestamp("2024-01-0" + (i + 1) + "T00:00:00Z")
          .build();
      memoryList.add(memoryEntry);
    }
    SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
    builder.setMemories(memoryList);
    SearchMemoryResponse response = builder.build();
    assertNotNull(response);
    assertThat(response.memories()).isNotNull();
    assertThat(response.memories()).hasSize(5);
    for (int i = 0; i < 5; i++) {
      assertThat(response.memories().get(i)).isEqualTo(memoryList.get(i));
    }
  }
  @Test
  @Tag("valid")
  void buildAfterOverwritingMemories() {
    List<MemoryEntry> firstMemoryList = new ArrayList<>();
    MemoryEntry firstEntry = MemoryEntry.builder()
        .setContent(createDummyContent())
        .setAuthor("firstAuthor")
        .setTimestamp("2024-01-01T00:00:00Z")
        .build();
    firstMemoryList.add(firstEntry);
    List<MemoryEntry> secondMemoryList = new ArrayList<>();
    MemoryEntry secondEntry = MemoryEntry.builder()
        .setContent(createDummyContent())
        .setAuthor("secondAuthor")
        .setTimestamp("2024-01-02T00:00:00Z")
        .build();
    MemoryEntry thirdEntry = MemoryEntry.builder()
        .setContent(createDummyContent())
        .setAuthor("thirdAuthor")
        .setTimestamp("2024-01-03T00:00:00Z")
        .build();
    secondMemoryList.add(secondEntry);
    secondMemoryList.add(thirdEntry);
    SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
    builder.setMemories(firstMemoryList);
    builder.setMemories(secondMemoryList);
    SearchMemoryResponse response = builder.build();
    assertNotNull(response);
    assertThat(response.memories()).isNotNull();
    assertThat(response.memories()).hasSize(2);
    assertThat(response.memories().get(0)).isEqualTo(secondEntry);
    assertThat(response.memories().get(1)).isEqualTo(thirdEntry);
    assertThat(response.memories()).doesNotContain(firstEntry);
  }
  @Test
  @Tag("boundary")
  void buildWithExplicitlySetEmptyList() {
    List<MemoryEntry> emptyList = new ArrayList<>();
    SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
    builder.setMemories(emptyList);
    SearchMemoryResponse response = builder.build();
    assertNotNull(response);
    assertThat(response.memories()).isNotNull();
    assertThat(response.memories()).isEmpty();
    assertThat(response.memories()).hasSize(0);
  }
  @Test
  @Tag("valid")
  void buildWithImmutableListDirectly() {
    MemoryEntry memoryEntry1 = MemoryEntry.builder()
        .setContent(createDummyContent())
        .setAuthor("author1")
        .setTimestamp("2024-01-01T00:00:00Z")
        .build();
    MemoryEntry memoryEntry2 = MemoryEntry.builder()
        .setContent(createDummyContent())
        .setAuthor("author2")
        .setTimestamp("2024-01-02T00:00:00Z")
        .build();
    List<MemoryEntry> regularList = new ArrayList<>();
    regularList.add(memoryEntry1);
    regularList.add(memoryEntry2);
    SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
    builder.setMemories(regularList);
    SearchMemoryResponse response = builder.build();
    assertNotNull(response);
    assertThat(response.memories()).isNotNull();
    assertThat(response.memories()).isInstanceOf(ImmutableList.class);
    assertThat(response.memories()).hasSize(2);
    assertThat(response.memories().get(0)).isEqualTo(memoryEntry1);
    assertThat(response.memories().get(1)).isEqualTo(memoryEntry2);
  }
  @Test
  @Tag("valid")
  void buildMultipleResponsesFromSameBuilder() {
    MemoryEntry memoryEntry = MemoryEntry.builder()
        .setContent(createDummyContent())
        .setAuthor("testAuthor")
        .setTimestamp("2024-01-01T00:00:00Z")
        .build();
    List<MemoryEntry> memoryList = new ArrayList<>();
    memoryList.add(memoryEntry);
    SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
    builder.setMemories(memoryList);
    SearchMemoryResponse response1 = builder.build();
    SearchMemoryResponse response2 = builder.build();
    assertNotNull(response1);
    assertNotNull(response2);
    assertThat(response1).isNotSameInstanceAs(response2);
    assertThat(response1.memories()).hasSize(1);
    assertThat(response2.memories()).hasSize(1);
    assertThat(response1.memories().get(0)).isEqualTo(memoryEntry);
    assertThat(response2.memories().get(0)).isEqualTo(memoryEntry);
  }
  @Test
  @Tag("valid")
  void buildAndVerifyMemoriesListImmutability() {
    List<MemoryEntry> mutableList = new ArrayList<>();
    MemoryEntry memoryEntry = MemoryEntry.builder()
        .setContent(createDummyContent())
        .setAuthor("testAuthor")
        .setTimestamp("2024-01-01T00:00:00Z")
        .build();
    mutableList.add(memoryEntry);
    SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
    builder.setMemories(mutableList);
    SearchMemoryResponse response = builder.build();
    ImmutableList<MemoryEntry> memories = response.memories();
    assertNotNull(memories);
    assertThat(memories).isInstanceOf(ImmutableList.class);
    assertThrows(UnsupportedOperationException.class, () -> {
      memories.add(MemoryEntry.builder()
          .setContent(createDummyContent())
          .setAuthor("anotherAuthor")
          .setTimestamp("2024-01-02T00:00:00Z")
          .build());
    });
  }
  @Test
  @Tag("invalid")
  void buildWithNullListHandling() {
    SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
    assertThrows(NullPointerException.class, () -> {
      builder.setMemories((List<MemoryEntry>) null);
    });
  }
  @Test
  @Tag("boundary")
  void buildWithLargeNumberOfMemoryEntries() {
    List<MemoryEntry> largeMemoryList = new ArrayList<>();
    for (int i = 0; i < 1000; i++) {
      MemoryEntry memoryEntry = MemoryEntry.builder()
          .setContent(createDummyContent())
          .setAuthor("author" + i)
          .setTimestamp("2024-01-01T00:00:00Z")
          .build();
      largeMemoryList.add(memoryEntry);
    }
    SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
    builder.setMemories(largeMemoryList);
    long startTime = System.currentTimeMillis();
    SearchMemoryResponse response = builder.build();
    long endTime = System.currentTimeMillis();
    assertNotNull(response);
    assertThat(response.memories()).isNotNull();
    assertThat(response.memories()).hasSize(1000);
    assertThat(endTime - startTime).isLessThan(5000);
  }
  private Content createDummyContent() {
    return Content.builder()
        .setText("dummy content text")
        .build();
  }
}