/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test maven-adkjava-github using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=addSessionToMemory_8a630adf5c
ROOST_METHOD_SIG_HASH=addSessionToMemory_3e3003d0a0

Scenario 1: Add a Session with Multiple Non-Empty Events

Details:
  TestName: addSessionWithMultipleNonEmptyEvents
  Description: This test verifies that when a Session containing several Event instances with non-empty content and parts is added, all such events are correctly stored in the in-memory sessionEvents under the right user and session key.

Execution:
  Arrange: Construct a Session containing multiple Event objects, each with non-empty content and the content containing a non-empty list of Part objects. Ensure the session is for a particular appName and userId.
  Act: Invoke addSessionToMemory with the prepared session and wait for completion.
  Assert: Check that sessionEvents contains an entry for "appName/userId" and that the session id maps to a list containing all the events with non-empty parts.

Validation:
  The assertion verifies that all valid events (with non-empty content parts) are fully stored for the specified user/session keys, confirming correct filtering and storing logic.
  This test is significant because it validates core functionality: storing all relevant events of a session.


Scenario 2: Add a Session with All Events Having Empty Parts

Details:
  TestName: addSessionWithAllEventsEmptyParts
  Description: Verifies that if all events in the Session have content, but their parts are empty, the method produces and stores an empty event list for that session id.

Execution:
  Arrange: Create a Session with multiple Event objects, each having content present, but the parts list is empty.
  Act: Invoke addSessionToMemory and wait for completion.
  Assert: sessionEvents will contain the correct user/session key, but the associated list for the session id will be empty.

Validation:
  This assertion ensures the method properly filters out events with empty parts, preventing them from being stored.
  It checks robust event filtering, reflecting proper handling of empty or incomplete data.


Scenario 3: Add a Session with Some Events Lacking Content

Details:
  TestName: addSessionWithEventsMissingContent
  Description: Tests adding a Session where some events have an empty Optional for content, verifying that only events with present content and non-empty parts are stored.

Execution:
  Arrange: Create a Session with a mix of Event objects, some with empty content, and some with valid content and non-empty parts.
  Act: Call addSessionToMemory and wait for completion.
  Assert: Confirm that only events with present content and non-empty parts are stored in sessionEvents.

Validation:
  Asserts that the method ignores events lacking content completely, which is crucial for robust data hygiene and correct business logic.


Scenario 4: Add a Session with an Empty Event List

Details:
  TestName: addSessionWithNoEvents
  Description: Validates that adding a Session containing an empty list of events results in an empty mapping for that session id.

Execution:
  Arrange: Prepare a Session with an empty events list for a unique appName and userId.
  Act: Invoke addSessionToMemory and await completion.
  Assert: The sessionEvents map should have the session id mapped to an empty list.

Validation:
  This ensures that the method can handle empty sessions gracefully, which is essential for defensive programming and null safety.


Scenario 5: Overwrite an Existing Session for Same User

Details:
  TestName: overwriteSessionForSameUser
  Description: Ensures that adding a Session with the same appName, userId, and session id as an existing entry replaces the prior events list for that session.

Execution:
  Arrange: Add an initial Session for a given appName, userId, and session id, with one set of events. Add another Session with the same identifiers but a different set of events.
  Act: Call addSessionToMemory for both sessions, in succession.
  Assert: Confirm the session id now points to the second session's events.

Validation:
  The test verifies that put() logic indeed overwrites prior data, ensuring sessions can be refreshed as designed.


Scenario 6: Session with Mixed Events (Some Empty, Some Non-Empty)

Details:
  TestName: addSessionWithMixedEvents
  Description: Tests that if a Session contains a mixture of events (some with non-empty content/parts, some lacking parts, or with empty parts), only the valid events (non-empty, non-null) are retained.

Execution:
  Arrange: Construct a Session with a few events: at least one with non-empty parts and one with empty or missing parts.
  Act: Execute addSessionToMemory and await completion.
  Assert: sessionEvents for the user/session id contains only the non-empty, valid events.

Validation:
  Ensures selective filtering works and only meaningful data persists, underpinning accurate session reconstruction.


Scenario 7: Add Session for a New User

Details:
  TestName: addSessionForNewUser
  Description: Validates that a Session is correctly stored under a new user (different appName/userId combination) in the sessionEvents map.

Execution:
  Arrange: Add a Session for a unique appName/userId not already present in sessionEvents.
  Act: Execute addSessionToMemory and await completion.
  Assert: The sessionEvents will now contain the new "appName/userId" key with appropriate session mapping.

Validation:
  Confirms multi-user support and dynamic key creation in the map, aligning with real-world usage.


Scenario 8: Add Multiple Sessions for Same User but Different Session IDs

Details:
  TestName: addMultipleSessionsForSameUser
  Description: Checks that adding multiple Session objects (distinct session ids, same user/app) stores each session's events independently under the same user key.

Execution:
  Arrange: Create two or more Sessions with unique session ids for the same appName/userId, each with valid events.
  Act: Call addSessionToMemory for each session.
  Assert: sessionEvents contains both session ids, each mapping to their respective event lists.

Validation:
  Ensures user-wide session segmentation is accurately represented in internal storage.


Scenario 9: Events with Content but Null or Missing Parts

Details:
  TestName: addSessionWithNullPartsInEvents
  Description: Checks handling when event.content() is present, but event.content().parts() is absent or evaluates to Optional.empty(), verifying such events are omitted.

Execution:
  Arrange: Create Events where content is present, but calling .parts() yields Optional.empty().
  Act: Add the Session containing these events and wait for completion.
  Assert: The resulting event list for that session id is empty.

Validation:
  Tests Optional navigation, confirming null/missing subfields are safely handled, avoiding NullPointerException and storing only complete events.


Scenario 10: Concurrent Addition of Sessions for the Same User

Details:
  TestName: concurrentSessionAddition
  Description: Simulates concurrent additions by multiple threads adding sessions for the same appName/userId to ensure thread safety and race conditions are handled.

Execution:
  Arrange: Set up several threads, each adding a Session (different session ids, same user).
  Act: Concurrently invoke addSessionToMemory for these sessions.
  Assert: After all threads complete, verify all session ids exist under the user key with correct event lists (no lost updates or partial data).

Validation:
  Essential to demonstrate thread safety (since sessionEvents uses ConcurrentHashMap), providing confidence in multi-client usage scenarios.


Scenario 11: Add Session with a Non-ASCII appName or userId

Details:
  TestName: addSessionWithUnicodeKeys
  Description: Ensures method correctly creates and stores sessions for users or apps with Unicode strings in their identifiers.

Execution:
  Arrange: Create a Session where appName and/or userId have Unicode (internationalized) characters, with valid events.
  Act: Add the Session via addSessionToMemory and wait for completion.
  Assert: sessionEvents contains a key composed with those Unicode strings, mapping to the right event list.

Validation:
  Confirms correct handling of internationalization, encoding, and no key-collision or string errors.


Scenario 12: Large Number of Events in a Session

Details:
  TestName: addSessionWithManyEvents
  Description: Validates that the method can handle and store a Session containing a large list of Event objects, without truncation or error.

Execution:
  Arrange: Generate a Session containing a large number (e.g., 1000+) Event instances, each with valid content and parts.
  Act: Add the Session and wait for the operation to finish.
  Assert: sessionEvents for that session id contains the correct number of stored events.

Validation:
  Ensures method's scalability and lack of internal limits or resource leaks for realistic session sizes.


Scenario 13: Exception Handling When Session is Null

Details:
  TestName: addSessionWithNullInput
  Description: Checks that passing a null parameter for Session to addSessionToMemory results in an expected exception.

Execution:
  Arrange: Prepare a null session input.
  Act: Attempt to invoke addSessionToMemory(null), capturing exceptions.
  Assert: Correctly throws a NullPointerException or similar (depending on method implementation), with no state change.

Validation:
  Establishes defensive programming: that null input is not silently accepted nor causes undefined state in sessionEvents.


*/

// ********RoostGPT********

package com.google.adk.memory;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.google.adk.events.Event;
import com.google.adk.sessions.Session;
import com.google.common.collect.ImmutableList;
import com.google.genai.types.Part;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

// Only import classes/structs that exist.
public class InMemoryMemoryServiceAddSessionToMemoryTest {

  private InMemoryMemoryService memoryService;

  @BeforeEach
  public void setUp() {
    memoryService = new InMemoryMemoryService();
  }

  @Test
  @Tag("valid")
  public void testAddSessionWithMultipleNonEmptyEvents() {
    String appName = "demoApp";
    String userId = "user123";
    String sessionId = "sessionA";
    Part part1 = Mockito.mock(Part.class);
    Mockito.when(part1.text()).thenReturn(Optional.of("Hello"));
    Part part2 = Mockito.mock(Part.class);
    Mockito.when(part2.text()).thenReturn(Optional.of("World"));
    Event event1 = Mockito.mock(Event.class);
    Event event2 = Mockito.mock(Event.class);
    Event event3 = Mockito.mock(Event.class);
    // non-empty parts for event1 & event2, event3 has also non-empty part
    // event1
    com.google.genai.types.Content content1 = Mockito.mock(com.google.genai.types.Content.class);
    Mockito.when(content1.parts()).thenReturn(Optional.of(ImmutableList.of(part1)));
    Mockito.when(event1.content()).thenReturn(Optional.of(content1));
    // event2
    com.google.genai.types.Content content2 = Mockito.mock(com.google.genai.types.Content.class);
    Mockito.when(content2.parts()).thenReturn(Optional.of(ImmutableList.of(part2)));
    Mockito.when(event2.content()).thenReturn(Optional.of(content2));
    // event3
    Part part3 = Mockito.mock(Part.class);
    Mockito.when(part3.text()).thenReturn(Optional.of("FooBar"));
    com.google.genai.types.Content content3 = Mockito.mock(com.google.genai.types.Content.class);
    Mockito.when(content3.parts()).thenReturn(Optional.of(ImmutableList.of(part3)));
    Mockito.when(event3.content()).thenReturn(Optional.of(content3));
    List<Event> events = ImmutableList.of(event1, event2, event3);
    Session session = Mockito.mock(Session.class);
    Mockito.when(session.appName()).thenReturn(appName);
    Mockito.when(session.userId()).thenReturn(userId);
    Mockito.when(session.id()).thenReturn(sessionId);
    Mockito.when(session.events()).thenReturn(events);
    memoryService.addSessionToMemory(session).blockingAwait();
    String key = appName + "/" + userId;
    Map<String, Map<String, List<Event>>> field = getSessionEventsMap(memoryService); // helper
    assertEquals(true, field.containsKey(key));
    assertTrue(field.get(key).containsKey(sessionId));
    List<Event> actualEvents = field.get(key).get(sessionId);
    assertEquals(events.size(), actualEvents.size());
    assertEquals((Event) event1, actualEvents.get(0));
    assertEquals((Event) event2, actualEvents.get(1));
    assertEquals((Event) event3, actualEvents.get(2));
  }

  @Test
  @Tag("valid")
  public void testAddSessionWithAllEventsEmptyParts() {
    String appName = "demoApp";
    String userId = "userX";
    String sessionId = "sessionEmptyParts";
    // All events contain content but their parts are empty.
    Event event1 = Mockito.mock(Event.class);
    Event event2 = Mockito.mock(Event.class);
    com.google.genai.types.Content emptyPartsContent =
        Mockito.mock(com.google.genai.types.Content.class);
    Mockito.when(emptyPartsContent.parts()).thenReturn(Optional.of(ImmutableList.of()));
    Mockito.when(event1.content()).thenReturn(Optional.of(emptyPartsContent));
    Mockito.when(event2.content()).thenReturn(Optional.of(emptyPartsContent));
    List<Event> events = ImmutableList.of(event1, event2);
    Session session = Mockito.mock(Session.class);
    Mockito.when(session.appName()).thenReturn(appName);
    Mockito.when(session.userId()).thenReturn(userId);
    Mockito.when(session.id()).thenReturn(sessionId);
    Mockito.when(session.events()).thenReturn(events);
    memoryService.addSessionToMemory(session).blockingAwait();
    String key = appName + "/" + userId;
    Map<String, Map<String, List<Event>>> field = getSessionEventsMap(memoryService); // helper
    assertEquals(true, field.containsKey(key));
    assertTrue(field.get(key).containsKey(sessionId));
    List<Event> storedEvents = field.get(key).get(sessionId);
    assertEquals(0, storedEvents.size());
  }

  @Test
  @Tag("valid")
  public void testAddSessionWithEventsMissingContent() {
    String appName = "onlySomeContentApp";
    String userId = "userY";
    String sessionId = "sessionMixedContent";
    // event1 has content
    Part part1 = Mockito.mock(Part.class);
    Mockito.when(part1.text()).thenReturn(Optional.of("Present"));
    com.google.genai.types.Content content1 = Mockito.mock(com.google.genai.types.Content.class);
    Mockito.when(content1.parts()).thenReturn(Optional.of(ImmutableList.of(part1)));
    Event event1 = Mockito.mock(Event.class);
    Mockito.when(event1.content()).thenReturn(Optional.of(content1));
    // event2 missing content
    Event event2 = Mockito.mock(Event.class);
    Mockito.when(event2.content()).thenReturn(Optional.empty());
    // event3 missing content
    Event event3 = Mockito.mock(Event.class);
    Mockito.when(event3.content()).thenReturn(Optional.empty());
    List<Event> events = ImmutableList.of(event1, event2, event3);
    Session session = Mockito.mock(Session.class);
    Mockito.when(session.appName()).thenReturn(appName);
    Mockito.when(session.userId()).thenReturn(userId);
    Mockito.when(session.id()).thenReturn(sessionId);
    Mockito.when(session.events()).thenReturn(events);
    memoryService.addSessionToMemory(session).blockingAwait();
    String key = appName + "/" + userId;
    Map<String, Map<String, List<Event>>> field = getSessionEventsMap(memoryService);
    List<Event> storedEvents = field.get(key).get(sessionId);
    assertEquals(1, storedEvents.size());
    assertEquals((Event) event1, storedEvents.get(0));
  }

  @Test
  @Tag("boundary")
  public void testAddSessionWithNoEvents() {
    String appName = "appNoEvents";
    String userId = "userNone";
    String sessionId = "sessionNone";
    Session session = Mockito.mock(Session.class);
    Mockito.when(session.appName()).thenReturn(appName);
    Mockito.when(session.userId()).thenReturn(userId);
    Mockito.when(session.id()).thenReturn(sessionId);
    Mockito.when(session.events()).thenReturn(ImmutableList.of());
    memoryService.addSessionToMemory(session).blockingAwait();
    String key = appName + "/" + userId;
    Map<String, Map<String, List<Event>>> field = getSessionEventsMap(memoryService);
    assertTrue(field.containsKey(key));
    assertTrue(field.get(key).containsKey(sessionId));
    assertEquals(0, field.get(key).get(sessionId).size());
  }

  @Test
  @Tag("valid")
  public void testOverwriteSessionForSameUser() {
    String appName = "appOverwrite";
    String userId = "userOverwrite";
    String sessionId = "sessionToReplace";
    Part partA = Mockito.mock(Part.class);
    Mockito.when(partA.text()).thenReturn(Optional.of("First Session"));
    com.google.genai.types.Content contentA = Mockito.mock(com.google.genai.types.Content.class);
    Mockito.when(contentA.parts()).thenReturn(Optional.of(ImmutableList.of(partA)));
    Event eventA = Mockito.mock(Event.class);
    Mockito.when(eventA.content()).thenReturn(Optional.of(contentA));
    // First session with one event
    List<Event> eventsSession1 = ImmutableList.of(eventA);
    Session session1 = Mockito.mock(Session.class);
    Mockito.when(session1.appName()).thenReturn(appName);
    Mockito.when(session1.userId()).thenReturn(userId);
    Mockito.when(session1.id()).thenReturn(sessionId);
    Mockito.when(session1.events()).thenReturn(eventsSession1);
    memoryService.addSessionToMemory(session1).blockingAwait();
    // Second session with two different events (should overwrite)
    Part partB = Mockito.mock(Part.class);
    Mockito.when(partB.text()).thenReturn(Optional.of("Second"));
    Part partC = Mockito.mock(Part.class);
    Mockito.when(partC.text()).thenReturn(Optional.of("Third"));
    com.google.genai.types.Content contentB = Mockito.mock(com.google.genai.types.Content.class);
    Mockito.when(contentB.parts()).thenReturn(Optional.of(ImmutableList.of(partB, partC)));
    Event eventB = Mockito.mock(Event.class);
    Mockito.when(eventB.content()).thenReturn(Optional.of(contentB));
    List<Event> eventsSession2 = ImmutableList.of(eventB);
    Session session2 = Mockito.mock(Session.class);
    Mockito.when(session2.appName()).thenReturn(appName);
    Mockito.when(session2.userId()).thenReturn(userId);
    Mockito.when(session2.id()).thenReturn(sessionId);
    Mockito.when(session2.events()).thenReturn(eventsSession2);
    memoryService.addSessionToMemory(session2).blockingAwait();
    String key = appName + "/" + userId;
    Map<String, Map<String, List<Event>>> field = getSessionEventsMap(memoryService);
    List<Event> actualEvents = field.get(key).get(sessionId);
    assertEquals(eventsSession2.size(), actualEvents.size());
    assertEquals((Event) eventB, actualEvents.get(0));
  }

  @Test
  @Tag("valid")
  public void testAddSessionWithMixedEvents() {
    String appName = "appMixed";
    String userId = "userMixed";
    String sessionId = "sessionMixed";
    Part validPart = Mockito.mock(Part.class);
    Mockito.when(validPart.text()).thenReturn(Optional.of("Valid"));
    com.google.genai.types.Content contentValid =
        Mockito.mock(com.google.genai.types.Content.class);
    Mockito.when(contentValid.parts()).thenReturn(Optional.of(ImmutableList.of(validPart)));
    Event validEvent = Mockito.mock(Event.class);
    Mockito.when(validEvent.content()).thenReturn(Optional.of(contentValid));
    // Empty parts event
    com.google.genai.types.Content emptyPartsContent =
        Mockito.mock(com.google.genai.types.Content.class);
    Mockito.when(emptyPartsContent.parts()).thenReturn(Optional.of(ImmutableList.of()));
    Event emptyPartsEvent = Mockito.mock(Event.class);
    Mockito.when(emptyPartsEvent.content()).thenReturn(Optional.of(emptyPartsContent));
    // Missing parts event
    com.google.genai.types.Content missingPartsContent =
        Mockito.mock(com.google.genai.types.Content.class);
    Mockito.when(missingPartsContent.parts()).thenReturn(Optional.empty());
    Event missingPartsEvent = Mockito.mock(Event.class);
    Mockito.when(missingPartsEvent.content()).thenReturn(Optional.of(missingPartsContent));
    List<Event> events = ImmutableList.of(validEvent, emptyPartsEvent, missingPartsEvent);
    Session session = Mockito.mock(Session.class);
    Mockito.when(session.appName()).thenReturn(appName);
    Mockito.when(session.userId()).thenReturn(userId);
    Mockito.when(session.id()).thenReturn(sessionId);
    Mockito.when(session.events()).thenReturn(events);
    memoryService.addSessionToMemory(session).blockingAwait();
    String key = appName + "/" + userId;
    Map<String, Map<String, List<Event>>> field = getSessionEventsMap(memoryService);
    List<Event> storedEvents = field.get(key).get(sessionId);
    assertEquals(1, storedEvents.size());
    assertEquals((Event) validEvent, storedEvents.get(0));
  }

  @Test
  @Tag("integration")
  public void testAddSessionForNewUser() {
    String appName1 = "AppInternational";
    String userId1 = "userInt";
    String sessionId1 = "sessionA";
    Part part1 = Mockito.mock(Part.class);
    Mockito.when(part1.text()).thenReturn(Optional.of("Session A"));
    com.google.genai.types.Content content1 = Mockito.mock(com.google.genai.types.Content.class);
    Mockito.when(content1.parts()).thenReturn(Optional.of(ImmutableList.of(part1)));
    Event event1 = Mockito.mock(Event.class);
    Mockito.when(event1.content()).thenReturn(Optional.of(content1));
    List<Event> events1 = ImmutableList.of(event1);
    Session session = Mockito.mock(Session.class);
    Mockito.when(session.appName()).thenReturn(appName1);
    Mockito.when(session.userId()).thenReturn(userId1);
    Mockito.when(session.id()).thenReturn(sessionId1);
    Mockito.when(session.events()).thenReturn(events1);
    memoryService.addSessionToMemory(session).blockingAwait();
    String key = appName1 + "/" + userId1;
    Map<String, Map<String, List<Event>>> field = getSessionEventsMap(memoryService);
    assertTrue(field.containsKey(key));
    assertEquals(1, field.get(key).size());
    assertEquals(events1.size(), field.get(key).get(sessionId1).size());
    assertEquals((Event) event1, field.get(key).get(sessionId1).get(0));
  }

  @Test
  @Tag("integration")
  public void testAddMultipleSessionsForSameUser() {
    String appName = "multSessionApp";
    String userId = "sameUser";
    String session1Id = "sessionX1";
    String session2Id = "sessionX2";
    Part part1 = Mockito.mock(Part.class);
    Mockito.when(part1.text()).thenReturn(Optional.of("Session X1"));
    com.google.genai.types.Content content1 = Mockito.mock(com.google.genai.types.Content.class);
    Mockito.when(content1.parts()).thenReturn(Optional.of(ImmutableList.of(part1)));
    Event event1 = Mockito.mock(Event.class);
    Mockito.when(event1.content()).thenReturn(Optional.of(content1));
    List<Event> events1 = ImmutableList.of(event1);
    Session session1 = Mockito.mock(Session.class);
    Mockito.when(session1.appName()).thenReturn(appName);
    Mockito.when(session1.userId()).thenReturn(userId);
    Mockito.when(session1.id()).thenReturn(session1Id);
    Mockito.when(session1.events()).thenReturn(events1);
    Part part2 = Mockito.mock(Part.class);
    Mockito.when(part2.text()).thenReturn(Optional.of("Session X2"));
    com.google.genai.types.Content content2 = Mockito.mock(com.google.genai.types.Content.class);
    Mockito.when(content2.parts()).thenReturn(Optional.of(ImmutableList.of(part2)));
    Event event2 = Mockito.mock(Event.class);
    Mockito.when(event2.content()).thenReturn(Optional.of(content2));
    List<Event> events2 = ImmutableList.of(event2);
    Session session2 = Mockito.mock(Session.class);
    Mockito.when(session2.appName()).thenReturn(appName);
    Mockito.when(session2.userId()).thenReturn(userId);
    Mockito.when(session2.id()).thenReturn(session2Id);
    Mockito.when(session2.events()).thenReturn(events2);
    memoryService.addSessionToMemory(session1).blockingAwait();
    memoryService.addSessionToMemory(session2).blockingAwait();
    String key = appName + "/" + userId;
    Map<String, Map<String, List<Event>>> field = getSessionEventsMap(memoryService);
    assertTrue(field.containsKey(key));
    assertTrue(field.get(key).containsKey(session1Id));
    assertTrue(field.get(key).containsKey(session2Id));
    assertEquals(events1.size(), field.get(key).get(session1Id).size());
    assertEquals((Event) event1, field.get(key).get(session1Id).get(0));
    assertEquals(events2.size(), field.get(key).get(session2Id).size());
    assertEquals((Event) event2, field.get(key).get(session2Id).get(0));
  }

  @Test
  @Tag("invalid")
  public void testAddSessionWithNullPartsInEvents() {
    String appName = "appNullParts";
    String userId = "userNullParts";
    String sessionId = "sessionNullParts";
    // Event content present, but .parts() returns Optional.empty()
    com.google.genai.types.Content contentWithNullParts =
        Mockito.mock(com.google.genai.types.Content.class);
    Mockito.when(contentWithNullParts.parts()).thenReturn(Optional.empty());
    Event eventWithNullParts = Mockito.mock(Event.class);
    Mockito.when(eventWithNullParts.content()).thenReturn(Optional.of(contentWithNullParts));
    List<Event> events = ImmutableList.of(eventWithNullParts);
    Session session = Mockito.mock(Session.class);
    Mockito.when(session.appName()).thenReturn(appName);
    Mockito.when(session.userId()).thenReturn(userId);
    Mockito.when(session.id()).thenReturn(sessionId);
    Mockito.when(session.events()).thenReturn(events);
    memoryService.addSessionToMemory(session).blockingAwait();
    String key = appName + "/" + userId;
    Map<String, Map<String, List<Event>>> field = getSessionEventsMap(memoryService);
    assertTrue(field.containsKey(key));
    assertTrue(field.get(key).containsKey(sessionId));
    assertEquals(0, field.get(key).get(sessionId).size());
  }

  @Test
  @Tag("integration")
  public void testConcurrentSessionAddition() throws InterruptedException {
    String appName = "concurrentApp";
    String userId = "concurrentUser";
    String key = appName + "/" + userId;
    int numThreads = 10; // TODO: Adjust if you want to test with more threads
    Thread[] threads = new Thread[numThreads];
    String[] sessionIds = new String[numThreads];
    Event[] eventObjs = new Event[numThreads];
    for (int i = 0; i < numThreads; ++i) {
      String sessionId = "session-" + i;
      sessionIds[i] = sessionId;
      Part part = Mockito.mock(Part.class);
      Mockito.when(part.text()).thenReturn(Optional.of("event-" + i));
      com.google.genai.types.Content content = Mockito.mock(com.google.genai.types.Content.class);
      Mockito.when(content.parts()).thenReturn(Optional.of(ImmutableList.of(part)));
      Event event = Mockito.mock(Event.class);
      Mockito.when(event.content()).thenReturn(Optional.of(content));
      eventObjs[i] = event;
      List<Event> events = ImmutableList.of(event);
      Session session = Mockito.mock(Session.class);
      Mockito.when(session.appName()).thenReturn(appName);
      Mockito.when(session.userId()).thenReturn(userId);
      Mockito.when(session.id()).thenReturn(sessionId);
      Mockito.when(session.events()).thenReturn(events);
      threads[i] = new Thread(() -> memoryService.addSessionToMemory(session).blockingAwait());
    }
    for (int i = 0; i < numThreads; ++i) {
      threads[i].start();
    }
    for (int i = 0; i < numThreads; ++i) {
      threads[i].join();
    }
    Map<String, Map<String, List<Event>>> field = getSessionEventsMap(memoryService);
    assertTrue(field.containsKey(key));
    for (int i = 0; i < numThreads; ++i) {
      assertTrue(field.get(key).containsKey(sessionIds[i]));
      List<Event> eventsStored = field.get(key).get(sessionIds[i]);
      assertEquals(1, eventsStored.size());
      assertEquals((Event) eventObjs[i], eventsStored.get(0));
    }
  }

  @Test
  @Tag("valid")
  public void testAddSessionWithUnicodeKeys() {
    String appName = "国際化アプリ名"; // Using Japanese chars
    String userId = "юзер"; // Cyrillic
    String sessionId = "sessionUnicode";
    Part part = Mockito.mock(Part.class);
    Mockito.when(part.text()).thenReturn(Optional.of("International"));
    com.google.genai.types.Content content = Mockito.mock(com.google.genai.types.Content.class);
    Mockito.when(content.parts()).thenReturn(Optional.of(ImmutableList.of(part)));
    Event event = Mockito.mock(Event.class);
    Mockito.when(event.content()).thenReturn(Optional.of(content));
    List<Event> events = ImmutableList.of(event);
    Session session = Mockito.mock(Session.class);
    Mockito.when(session.appName()).thenReturn(appName);
    Mockito.when(session.userId()).thenReturn(userId);
    Mockito.when(session.id()).thenReturn(sessionId);
    Mockito.when(session.events()).thenReturn(events);
    memoryService.addSessionToMemory(session).blockingAwait();
    String key = appName + "/" + userId;
    Map<String, Map<String, List<Event>>> field = getSessionEventsMap(memoryService);
    assertTrue(field.containsKey(key));
    assertTrue(field.get(key).containsKey(sessionId));
    assertEquals(events.size(), field.get(key).get(sessionId).size());
    assertEquals((Event) event, field.get(key).get(sessionId).get(0));
  }

  @Test
  @Tag("boundary")
  public void testAddSessionWithManyEvents() {
    String appName = "bulkApp";
    String userId = "bulkUser";
    String sessionId = "bulkSession";
    int numEvents = 1000; // TODO: Change value to simulate large session
    ImmutableList.Builder<Event> builder = ImmutableList.builder();
    for (int i = 0; i < numEvents; ++i) {
      Part part = Mockito.mock(Part.class);
      Mockito.when(part.text()).thenReturn(Optional.of("Bulk event " + i));
      com.google.genai.types.Content content = Mockito.mock(com.google.genai.types.Content.class);
      Mockito.when(content.parts()).thenReturn(Optional.of(ImmutableList.of(part)));
      Event event = Mockito.mock(Event.class);
      Mockito.when(event.content()).thenReturn(Optional.of(content));
      builder.add(event);
    }
    List<Event> events = builder.build();
    Session session = Mockito.mock(Session.class);
    Mockito.when(session.appName()).thenReturn(appName);
    Mockito.when(session.userId()).thenReturn(userId);
    Mockito.when(session.id()).thenReturn(sessionId);
    Mockito.when(session.events()).thenReturn(events);
    memoryService.addSessionToMemory(session).blockingAwait();
    String key = appName + "/" + userId;
    Map<String, Map<String, List<Event>>> field = getSessionEventsMap(memoryService);
    assertTrue(field.containsKey(key));
    assertTrue(field.get(key).containsKey(sessionId));
    assertEquals(numEvents, field.get(key).get(sessionId).size());
  }

  @Test
  @Tag("invalid")
  public void testAddSessionWithNullInput() {
    assertThrows(
        NullPointerException.class,
        () -> {
          memoryService.addSessionToMemory(null).blockingAwait();
        });
  }

  // Helper method to access sessionEvents map using reflection without direct access,
  // preserving
  // encapsulation.
  @SuppressWarnings("unchecked")
  private static Map<String, Map<String, List<Event>>> getSessionEventsMap(
      InMemoryMemoryService svc) {
    try {
      java.lang.reflect.Field sessionEventsField =
          InMemoryMemoryService.class.getDeclaredField("sessionEvents");
      sessionEventsField.setAccessible(true);
      return (Map<String, Map<String, List<Event>>>) sessionEventsField.get(svc);
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }
}
