/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-maven-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=searchMemory_5b46a62b19
ROOST_METHOD_SIG_HASH=searchMemory_2ebd5f3610

Scenario 1: Search Memory When User Key Does Not Exist

Details:
  TestName: searchMemoryReturnsEmptyResponseWhenUserKeyNotFound
  Description: This test verifies that when searching for memories with an appName and userId combination that does not exist in the sessionEvents map, the method returns an empty SearchMemoryResponse. This ensures the method handles cases where no data has been stored for the given user.

Execution:
  Arrange: Create an instance of InMemoryMemoryService with an empty sessionEvents map. Prepare valid appName, userId, and query parameters that do not correspond to any existing entries.
  Act: Invoke the searchMemory method with the prepared appName, userId, and query parameters. Subscribe to the returned Single and block to get the result.
  Assert: Use JUnit assertions to verify that the returned SearchMemoryResponse is not null and that the memories list is empty or null.

Validation:
  The assertion verifies that the method gracefully handles the absence of user data by returning an empty response rather than throwing an exception. This is critical for application stability when querying non-existent users and ensures the method follows the fail-safe pattern.

---

Scenario 2: Search Memory With Matching Single Word Query

Details:
  TestName: searchMemoryReturnsMatchingMemoriesForSingleWordQuery
  Description: This test validates that when a single-word query matches words in stored event content, the method returns all matching MemoryEntry objects. It tests the core keyword matching functionality of the search feature.

Execution:
  Arrange: Create an InMemoryMemoryService instance and populate sessionEvents with a user key containing events with text content that includes the search word. Create Event objects with Part objects containing text that includes the query word.
  Act: Invoke searchMemory with the appName, userId, and a single-word query that matches content in the stored events.
  Assert: Verify that the returned SearchMemoryResponse contains the expected number of matching memories and that each memory's content contains the query word.

Validation:
  This assertion confirms that the keyword matching algorithm correctly identifies events containing the search term. It validates the core business logic of the memory search functionality, ensuring users can retrieve relevant memories based on keyword searches.

---

Scenario 3: Search Memory With Multiple Word Query

Details:
  TestName: searchMemoryReturnsMatchingMemoriesForMultiWordQuery
  Description: This test ensures that when a query contains multiple words separated by whitespace, the method correctly splits the query and matches events containing any of the query words. It validates the query parsing and matching logic for complex searches.

Execution:
  Arrange: Set up InMemoryMemoryService with sessionEvents containing events with various text content. Create events where some contain one query word, some contain another, and some contain both.
  Act: Call searchMemory with a query string containing multiple words separated by spaces (e.g., "hello world").
  Assert: Verify that the response includes all events that contain at least one of the query words, demonstrating the OR logic in matching.

Validation:
  The assertion validates that the method correctly implements the disjoint collection check, returning memories that match any word in the query. This is essential for flexible search functionality where users expect results matching any of their search terms.

---

Scenario 4: Search Memory With Case Insensitive Matching

Details:
  TestName: searchMemoryPerformsCaseInsensitiveMatching
  Description: This test verifies that the search functionality is case-insensitive, matching query words regardless of the case used in either the query or the stored event content. It ensures consistent search behavior across different text capitalizations.

Execution:
  Arrange: Create InMemoryMemoryService with events containing text in various cases (uppercase, lowercase, mixed case). Prepare a query with words in different cases than the stored content.
  Act: Execute searchMemory with the mixed-case query against the stored events.
  Assert: Confirm that memories are returned regardless of case differences between query and content, verifying case-insensitive matching.

Validation:
  This assertion ensures the toLowerCase(Locale.ROOT) conversion is applied correctly to both query and event content, providing a user-friendly search experience where case sensitivity doesn't affect results. This is a standard expectation in modern search interfaces.

---

Scenario 5: Search Memory With Empty Query String

Details:
  TestName: searchMemoryWithEmptyQueryReturnsEmptyResponse
  Description: This test checks the behavior when an empty string is provided as the query parameter. It validates edge case handling for invalid or minimal input.

Execution:
  Arrange: Initialize InMemoryMemoryService with populated sessionEvents containing valid events. Prepare an empty string as the query parameter.
  Act: Invoke searchMemory with appName, userId, and an empty query string.
  Assert: Verify that the returned SearchMemoryResponse contains no memories, as an empty query should not match any content.

Validation:
  The assertion confirms that empty queries are handled gracefully without throwing exceptions. Since splitting an empty string results in an empty set, the disjoint check should prevent any matches, which is the expected behavior for meaningless queries.

---

Scenario 6: Search Memory With Query Containing Only Whitespace

Details:
  TestName: searchMemoryWithWhitespaceOnlyQueryReturnsEmptyResponse
  Description: This test validates the handling of queries that contain only whitespace characters (spaces, tabs, etc.). It ensures the method doesn't incorrectly match events when given non-meaningful input.

Execution:
  Arrange: Set up InMemoryMemoryService with valid events in sessionEvents. Create a query string containing only whitespace characters (e.g., "   ").
  Act: Call searchMemory with the whitespace-only query.
  Assert: Verify that no memories are returned in the response, as whitespace-only queries should not produce matches.

Validation:
  This assertion ensures that the split operation on whitespace-only strings produces empty strings that don't match actual content. It validates robust input handling and prevents false positive matches on meaningless queries.

---

Scenario 7: Search Memory With Special Characters In Query

Details:
  TestName: searchMemoryIgnoresSpecialCharactersInQuery
  Description: This test verifies that special characters and non-alphabetic characters in the query are ignored, as the WORD_PATTERN only matches alphabetic characters. It validates that the search focuses on actual words.

Execution:
  Arrange: Create InMemoryMemoryService with events containing text with and without special characters. Prepare a query containing special characters mixed with words (e.g., "hello! world?").
  Act: Execute searchMemory with the query containing special characters.
  Assert: Verify that only the alphabetic portions of the query are used for matching, and special characters don't affect the search results.

Validation:
  The assertion confirms that the WORD_PATTERN regex correctly extracts only alphabetic words, ignoring punctuation and special characters. This ensures clean keyword matching without interference from formatting characters, which is essential for accurate search results.

---

Scenario 8: Search Memory With Events Having Empty Content

Details:
  TestName: searchMemorySkipsEventsWithEmptyContent
  Description: This test ensures that events with empty content (where content().isEmpty() returns true) are skipped during the search process and don't cause errors or affect results.

Execution:
  Arrange: Set up InMemoryMemoryService with a mix of events, some with valid content and some with empty content. Prepare a query that would match the valid events.
  Act: Invoke searchMemory with the query.
  Assert: Verify that only events with non-empty content are included in the results, and empty content events are silently skipped.

Validation:
  This assertion validates the defensive programming approach where empty content is checked before processing. It ensures the method is robust against incomplete or malformed data, preventing NullPointerExceptions or incorrect results.

---

Scenario 9: Search Memory With Events Having Empty Parts List

Details:
  TestName: searchMemorySkipsEventsWithEmptyPartsList
  Description: This test verifies that events where the parts list is empty (event.content().get().parts().isEmpty() returns true) are properly skipped during search processing.

Execution:
  Arrange: Create InMemoryMemoryService with events where content exists but the parts list is empty. Include other events with valid parts for comparison.
  Act: Call searchMemory with a query that would match the valid events.
  Assert: Confirm that events with empty parts lists are excluded from results and don't cause processing errors.

Validation:
  The assertion ensures the method correctly handles the nested optional structure of Event content and parts. This validates data integrity checks and prevents processing of incomplete event data that could lead to exceptions.

---

Scenario 10: Search Memory With Parts Having Null Or Empty Text

Details:
  TestName: searchMemorySkipsPartsWithNullOrEmptyText
  Description: This test validates that Part objects with null or empty text (checked by Strings.isNullOrEmpty) are skipped during word extraction, preventing errors and ensuring only valid text is processed.

Execution:
  Arrange: Set up InMemoryMemoryService with events containing parts where some have valid text, some have empty text, and some have null text. Prepare a matching query.
  Act: Execute searchMemory with the query.
  Assert: Verify that only parts with non-null, non-empty text contribute to the search matching, and invalid parts are silently ignored.

Validation:
  This assertion confirms proper null-safety and empty-string handling in the text extraction logic. It ensures the method is resilient to incomplete or malformed Part data, which is critical for production stability when dealing with varied data sources.

---

Scenario 11: Search Memory With Events Having No Extractable Words

Details:
  TestName: searchMemorySkipsEventsWithNoExtractableWords
  Description: This test checks that events containing only non-alphabetic characters (numbers, symbols, etc.) that don't match the WORD_PATTERN are skipped, as they produce an empty wordsInEvent set.

Execution:
  Arrange: Create InMemoryMemoryService with events containing text that has no alphabetic characters (e.g., "123 !@# 456"). Include other events with valid words.
  Act: Invoke searchMemory with a query containing valid words.
  Assert: Verify that events with no extractable words are excluded from results, and only events with valid alphabetic words are considered.

Validation:
  The assertion validates that the isEmpty() check on wordsInEvent correctly filters out events that don't contain meaningful searchable content. This ensures search efficiency and accuracy by excluding non-textual content from matching.

---

Scenario 12: Search Memory With Multiple Sessions For Same User

Details:
  TestName: searchMemorySearchesAcrossAllUserSessions
  Description: This test verifies that when a user has multiple sessions stored, the search method examines events across all sessions and returns matching memories from any session.

Execution:
  Arrange: Set up InMemoryMemoryService with a single user key containing multiple session IDs, each with different events. Create a query that matches events in different sessions.
  Act: Call searchMemory for the user.
  Assert: Verify that the response includes matching memories from all sessions, not just one session.

Validation:
  This assertion confirms that the nested loop structure correctly iterates through all sessions for a user. It validates that the search is comprehensive across the user's entire history, which is essential for complete memory retrieval functionality.

---

Scenario 13: Search Memory With Multiple Events In Single Session

Details:
  TestName: searchMemorySearchesAllEventsInSession
  Description: This test ensures that when a session contains multiple events, all events are examined for matches, and all matching events are included in the results.

Execution:
  Arrange: Create InMemoryMemoryService with a single session containing multiple events, some matching the query and some not. Prepare a query that matches specific events.
  Act: Execute searchMemory with the query.
  Assert: Verify that all matching events from the session are returned in the response, confirming complete event iteration.

Validation:
  The assertion validates that the inner loop correctly processes all events within a session. This ensures no matching memories are missed during the search, which is critical for search completeness and user satisfaction.

---

Scenario 14: Search Memory With Multiple Parts In Single Event

Details:
  TestName: searchMemoryExtractsWordsFromAllPartsInEvent
  Description: This test verifies that when an event contains multiple Part objects, words are extracted from all parts and used for matching, ensuring comprehensive content analysis.

Execution:
  Arrange: Set up InMemoryMemoryService with events containing multiple parts, where the query word appears in different parts. Create a query matching words in various parts.
  Act: Invoke searchMemory with the query.
  Assert: Confirm that events are matched when the query word appears in any part, demonstrating aggregation of words across all parts.

Validation:
  This assertion ensures the method correctly aggregates words from all parts into the wordsInEvent set before matching. It validates that the search considers the complete content of an event, not just the first part, which is essential for accurate matching.

---

Scenario 15: Search Memory With Partial Word Match

Details:
  TestName: searchMemoryDoesNotMatchPartialWords
  Description: This test validates that the search requires exact word matches and does not match partial words or substrings. For example, searching for "test" should not match "testing" or "contest".

Execution:
  Arrange: Create InMemoryMemoryService with events containing words that include the query as a substring but are not exact matches (e.g., event contains "testing", query is "test").
  Act: Call searchMemory with the partial word query.
  Assert: Verify that events containing only partial matches are not returned, confirming exact word matching behavior.

Validation:
  The assertion confirms that the WORD_PATTERN regex and the set-based matching approach require complete word matches. This validates that the search implements proper word boundary detection, preventing false positives from substring matches.

---

Scenario 16: Search Memory Returns Correct MemoryEntry Structure

Details:
  TestName: searchMemoryReturnsCorrectlyStructuredMemoryEntries
  Description: This test verifies that returned MemoryEntry objects are correctly constructed with content, author, and formatted timestamp fields populated from the matching Event objects.

Execution:
  Arrange: Set up InMemoryMemoryService with events that have known content, author, and timestamp values. Prepare a query that matches these events.
  Act: Execute searchMemory and retrieve the matching memories.
  Assert: Verify that each returned MemoryEntry has the correct content, author, and timestamp values matching the source Event, and that the timestamp is properly formatted.

Validation:
  This assertion validates the correct construction of MemoryEntry objects and the proper invocation of formatTimestamp. It ensures data integrity in the response and confirms that all relevant event information is preserved in the search results.

---

Scenario 17: Search Memory With Query Containing Duplicate Words

Details:
  TestName: searchMemoryHandlesDuplicateWordsInQuery
  Description: This test checks that duplicate words in the query are handled correctly, with the ImmutableSet deduplication ensuring efficient matching without redundant comparisons.

Execution:
  Arrange: Create InMemoryMemoryService with events containing specific words. Prepare a query with duplicate words (e.g., "test test hello test").
  Act: Invoke searchMemory with the duplicate-word query.
  Assert: Verify that the search results are the same as if the query contained each word only once, confirming proper deduplication.

Validation:
  The assertion confirms that using ImmutableSet for wordsInQuery automatically deduplicates query words, ensuring efficient matching. This validates that the implementation doesn't perform redundant comparisons and handles user input variations gracefully.

---

Scenario 18: Search Memory With Very Long Query String

Details:
  TestName: searchMemoryHandlesLongQueryStrings
  Description: This test validates that the method can handle queries with many words without performance degradation or errors, ensuring scalability of the search functionality.

Execution:
  Arrange: Set up InMemoryMemoryService with standard events. Create a query string containing a large number of words (e.g., 100+ words).
  Act: Call searchMemory with the long query string.
  Assert: Verify that the method completes successfully and returns appropriate results without throwing exceptions or timing out.

Validation:
  This assertion ensures the method is robust against unusually large inputs and validates that the set-based matching approach scales reasonably with query size. It's important for preventing denial-of-service scenarios through malformed input.

---

Scenario 19: Search Memory With Very Large Number Of Events

Details:
  TestName: searchMemoryHandlesLargeNumberOfEvents
  Description: This test verifies that the method can process a large number of events across multiple sessions without performance issues, validating scalability for users with extensive history.

Execution:
  Arrange: Create InMemoryMemoryService and populate it with a large number of sessions and events (e.g., 1000+ events). Prepare a query that matches some events.
  Act: Execute searchMemory with the query.
  Assert: Verify that the method completes in reasonable time and returns correct results, demonstrating acceptable performance with large datasets.

Validation:
  The assertion validates that the nested loop structure and matching algorithm scale adequately with data volume. While this is an in-memory prototype, it's important to ensure the algorithm doesn't have obvious performance bottlenecks that would prevent production use.

---

Scenario 20: Search Memory Returns Immutable List Of Memories

Details:
  TestName: searchMemoryReturnsImmutableMemoriesList
  Description: This test verifies that the returned SearchMemoryResponse contains an ImmutableList of memories, ensuring the response cannot be modified after creation and maintaining data integrity.

Execution:
  Arrange: Set up InMemoryMemoryService with matching events. Prepare a query that returns results.
  Act: Invoke searchMemory and retrieve the memories list from the response.
  Assert: Verify that the memories list is an instance of ImmutableList and that attempts to modify it throw UnsupportedOperationException.

Validation:
  This assertion confirms proper use of Guava's ImmutableList, ensuring thread-safety and preventing accidental modification of search results. It validates adherence to immutability principles, which is critical for concurrent access scenarios.

---

Scenario 21: Search Memory With Null AppName Parameter

Details:
  TestName: searchMemoryHandlesNullAppName
  Description: This test validates the behavior when a null appName is provided, checking whether the method throws an appropriate exception or handles it gracefully.

Execution:
  Arrange: Create InMemoryMemoryService instance. Prepare null for appName parameter and valid values for userId and query.
  Act: Invoke searchMemory with null appName.
  Assert: Verify that the method either throws a NullPointerException or handles the null gracefully based on the expected contract.

Validation:
  This assertion validates null-safety of the method. Since userKey concatenates appName with userId, a null appName would cause a NullPointerException, which is acceptable for parameter validation. This test documents the expected behavior for invalid input.

---

Scenario 22: Search Memory With Null UserId Parameter

Details:
  TestName: searchMemoryHandlesNullUserId
  Description: This test checks the behavior when a null userId is provided, validating parameter validation and error handling for required parameters.

Execution:
  Arrange: Set up InMemoryMemoryService. Prepare valid appName and query, but null for userId.
  Act: Call searchMemory with null userId.
  Assert: Verify that the method throws NullPointerException or handles null appropriately based on the method contract.

Validation:
  The assertion validates that required parameters are properly enforced. Since userKey uses userId in string concatenation, null would cause an exception, which is appropriate for invalid input and helps catch programming errors early.

---

Scenario 23: Search Memory With Null Query Parameter

Details:
  TestName: searchMemoryHandlesNullQuery
  Description: This test validates the behavior when a null query is provided, checking whether the method throws an exception during query processing.

Execution:
  Arrange: Create InMemoryMemoryService with valid events. Prepare valid appName and userId, but null for query.
  Act: Execute searchMemory with null query.
  Assert: Verify that the method throws NullPointerException when attempting to process the null query (during toLowerCase or split operations).

Validation:
  This assertion confirms that null queries are not silently accepted, preventing undefined behavior. The exception during query.toLowerCase() or split() is expected and appropriate, documenting that queries must be non-null.

---

Scenario 24: Search Memory With Query Containing Numbers Only

Details:
  TestName: searchMemoryWithNumericQueryReturnsNoMatches
  Description: This test verifies that queries containing only numbers do not match any events, as the WORD_PATTERN only matches alphabetic characters.

Execution:
  Arrange: Set up InMemoryMemoryService with events containing both text and numbers. Create a query with only numeric characters (e.g., "12345").
  Act: Invoke searchMemory with the numeric query.
  Assert: Verify that no memories are returned, as numeric-only queries produce no valid search words.

Validation:
  The assertion confirms that the WORD_PATTERN correctly filters out non-alphabetic content from queries. This validates that the search focuses on textual content and doesn't attempt to match numeric data, which aligns with keyword-based search semantics.

---

Scenario 25: Search Memory With Mixed Alphanumeric Query

Details:
  TestName: searchMemoryExtractsOnlyAlphabeticPortionsFromMixedQuery
  Description: This test validates that when a query contains mixed alphanumeric content (e.g., "test123hello"), only the alphabetic portions are extracted and used for matching.

Execution:
  Arrange: Create InMemoryMemoryService with events containing various words. Prepare a query with mixed alphanumeric content where alphabetic portions match stored words.
  Act: Call searchMemory with the mixed query.
  Assert: Verify that matches are found based only on the alphabetic portions of the query, with numbers being ignored.

Validation:
  This assertion validates that the split operation on the query and the WORD_PATTERN on event content both correctly extract only alphabetic words. It ensures consistent word extraction logic between query and content processing.

---

Scenario 26: Search Memory Preserves Event Order In Results

Details:
  TestName: searchMemoryPreservesEventProcessingOrder
  Description: This test verifies that matching memories are returned in the order they are encountered during iteration through sessions and events, maintaining a predictable result order.

Execution:
  Arrange: Set up InMemoryMemoryService with multiple sessions and events in a specific order. Create a query that matches multiple events.
  Act: Execute searchMemory and retrieve the ordered list of memories.
  Assert: Verify that the memories appear in the response in the same order they were encountered during iteration (session by session, event by event).

Validation:
  The assertion confirms that the ArrayList preserves insertion order and that the iteration order through maps and lists is consistent. This is important for predictable behavior, though the actual order may depend on ConcurrentHashMap's iteration characteristics.

---

Scenario 27: Search Memory With Single Character Query

Details:
  TestName: searchMemoryMatchesSingleCharacterWords
  Description: This test validates that single-character queries (e.g., "a", "I") are processed correctly and can match single-character words in event content.

Execution:
  Arrange: Create InMemoryMemoryService with events containing single-character words. Prepare a single-character query.
  Act: Invoke searchMemory with the single-character query.
  Assert: Verify that events containing the single-character word are matched and returned.

Validation:
  This assertion confirms that the WORD_PATTERN regex matches single alphabetic characters and that the matching logic works for minimal-length words. It validates that there are no minimum length restrictions on searchable words.

---

Scenario 28: Search Memory Returns Empty Response For No Matches

Details:
  TestName: searchMemoryReturnsEmptyResponseWhenNoMatchesFound
  Description: This test verifies that when events exist for a user but none match the query, an empty SearchMemoryResponse is returned rather than null or an error.

Execution:
  Arrange: Set up InMemoryMemoryService with events that do not contain any words matching the query. Prepare a query with words not present in any event.
  Act: Call searchMemory with the non-matching query.
  Assert: Verify that the returned SearchMemoryResponse is not null and contains an empty memories list.

Validation:
  The assertion validates proper handling of the no-match scenario, ensuring the method returns a valid empty response rather than null. This is important for client code that expects a valid response object and prevents NullPointerExceptions in calling code.

---

Scenario 29: Search Memory With Locale-Specific Characters

Details:
  TestName: searchMemoryHandlesLocaleSpecificCharacters
  Description: This test validates the behavior when queries or event content contain locale-specific characters (accented characters, umlauts, etc.), checking whether they are matched or ignored based on the WORD_PATTERN.

Execution:
  Arrange: Create InMemoryMemoryService with events containing locale-specific characters (e.g., "café", "naïve"). Prepare queries with and without these characters.
  Act: Execute searchMemory with queries containing locale-specific characters.
  Assert: Verify the matching behavior based on whether WORD_PATTERN [A-Za-z]+ includes or excludes these characters (it excludes them).

Validation:
  This assertion documents that the current WORD_PATTERN only matches ASCII alphabetic characters, excluding accented and non-English characters. This is important for understanding the limitations of the current implementation and potential internationalization issues.

---

Scenario 30: Search Memory Thread Safety With Concurrent Access

Details:
  TestName: searchMemoryHandlesConcurrentAccess
  Description: This test validates that the searchMemory method can be safely called concurrently from multiple threads without causing data corruption or exceptions, leveraging the ConcurrentHashMap backing store.

Execution:
  Arrange: Set up InMemoryMemoryService with populated sessionEvents. Create multiple threads that will call searchMemory simultaneously with different queries.
  Act: Execute searchMemory from multiple threads concurrently and collect all results.
  Assert: Verify that all threads complete successfully without exceptions and that results are consistent with the stored data.

Validation:
  This assertion validates thread-safety of the read operation, confirming that ConcurrentHashMap provides adequate concurrency support for simultaneous searches. This is critical for multi-user scenarios where multiple searches may occur simultaneously.

---

Scenario 31: Search Memory With Timestamp Formatting

Details:
  TestName: searchMemoryFormatsTimestampCorrectly
  Description: This test verifies that the timestamp in returned MemoryEntry objects is correctly formatted using the formatTimestamp method, converting epoch seconds to ISO-8601 format.

Execution:
  Arrange: Create InMemoryMemoryService with events having known timestamp values. Prepare a matching query.
  Act: Invoke searchMemory and retrieve the memories with timestamps.
  Assert: Verify that the timestamp strings in MemoryEntry objects match the expected ISO-8601 format (e.g., "2024-01-01T12:00:00Z") for the given epoch seconds.

Validation:
  The assertion confirms that formatTimestamp is correctly invoked and produces properly formatted timestamp strings. This validates data transformation in the response and ensures timestamps are human-readable and standardized.

---

Scenario 32: Search Memory With Empty SessionEvents Map

Details:
  TestName: searchMemoryWithEmptySessionEventsReturnsEmptyResponse
  Description: This test validates that when the sessionEvents map is completely empty (no users have any data), the search returns an empty response for any query.

Execution:
  Arrange: Create a new InMemoryMemoryService instance with no data added (empty sessionEvents map). Prepare valid appName, userId, and query.
  Act: Call searchMemory with the parameters.
  Assert: Verify that the returned SearchMemoryResponse contains no memories, handling the empty state gracefully.

Validation:
  This assertion validates the initial state handling of the service, ensuring it can be queried immediately after instantiation without errors. It confirms that the containsKey check properly handles the empty map case.

---

Scenario 33: Search Memory With Author Information Preserved

Details:
  TestName: searchMemoryPreservesAuthorInformation
  Description: This test verifies that the author information from matching Event objects is correctly preserved in the returned MemoryEntry objects.

Execution:
  Arrange: Set up InMemoryMemoryService with events that have specific author values. Create a matching query.
  Act: Execute searchMemory and retrieve the memories.
  Assert: Verify that each returned MemoryEntry contains the correct author value matching the source Event.

Validation:
  The assertion confirms that the MemoryEntry.builder() correctly copies the author field from Event objects. This validates data integrity in the response and ensures all relevant event metadata is preserved in search results.

---

Scenario 34: Search Memory With Content Preserved

Details:
  TestName: searchMemoryPreservesEventContent
  Description: This test validates that the complete content structure from matching Event objects is preserved in the returned MemoryEntry objects, including all parts.

Execution:
  Arrange: Create InMemoryMemoryService with events containing complex content with multiple parts. Prepare a matching query.
  Act: Invoke searchMemory and retrieve the memories.
  Assert: Verify that each returned MemoryEntry contains the complete content structure matching the source Event, with all parts intact.

Validation:
  This assertion confirms that event.content().get() is correctly passed to the MemoryEntry builder, preserving the full content structure. It validates that search results contain complete information for client consumption.

---

Scenario 35: Search Memory With Reactive Single Execution

Details:
  TestName: searchMemoryReturnsReactiveSingle
  Description: This test verifies that the method returns a properly constructed RxJava Single that can be subscribed to and produces the expected result when executed.

Execution:
  Arrange: Set up InMemoryMemoryService with test data. Prepare query parameters.
  Act: Invoke searchMemory and verify the return type is Single<SearchMemoryResponse>. Subscribe to the Single and retrieve the result.
  Assert: Verify that the Single completes successfully with a SearchMemoryResponse and that the result matches expectations.

Validation:
  The assertion validates the reactive programming contract, ensuring the method properly wraps the computation in a Single.fromCallable(). This is important for integration with reactive streams and asynchronous processing pipelines.

---

Scenario 36: Search Memory With Exception In Callable

Details:
  TestName: searchMemoryPropagatesExceptionsInSingle
  Description: This test validates that if an exception occurs during the search computation (within the callable), it is properly propagated through the Single's error channel.

Execution:
  Arrange: Create a scenario where the search computation might throw an exception (this is difficult with the current implementation but could occur with corrupted data structures).
  Act: Invoke searchMemory and subscribe to the Single with an error handler.
  Assert: Verify that exceptions are caught by the Single's error handler rather than being thrown directly.

Validation:
  This assertion validates proper reactive error handling, ensuring exceptions don't escape the reactive boundary. It confirms that the Single.fromCallable() properly wraps exceptions for reactive error handling.

---

Scenario 37: Search Memory With Word Pattern Matching Boundaries

Details:
  TestName: searchMemoryRespects WordBoundaries
  Description: This test verifies that the WORD_PATTERN regex correctly identifies word boundaries, treating punctuation and whitespace as separators.

Execution:
  Arrange: Set up InMemoryMemoryService with events containing words separated by various punctuation marks and whitespace. Prepare queries for these words.
  Act: Execute searchMemory with queries for words that appear adjacent to punctuation.
  Assert: Verify that words are correctly extracted and matched regardless of surrounding punctuation or whitespace.

Validation:
  The assertion confirms that the WORD_PATTERN regex correctly handles word boundaries, extracting words cleanly without including adjacent punctuation. This validates accurate word tokenization for reliable keyword matching.

---

Scenario 38: Search Memory With Collections.disjoint Logic

Details:
  TestName: searchMemoryUsesDisjointCheckCorrectly
  Description: This test validates that the Collections.disjoint method is used correctly to determine if query words and event words have any overlap, implementing OR logic for multi-word queries.

Execution:
  Arrange: Create InMemoryMemoryService with events containing specific words. Prepare queries where some words match and some don't.
  Act: Invoke searchMemory with the mixed-match query.
  Assert: Verify that events are matched when at least one query word appears in the event, confirming the disjoint check implements OR logic.

Validation:
  This assertion validates the core matching logic, confirming that !Collections.disjoint() correctly identifies when sets have any common elements. This is critical for the OR-based keyword matching semantics of the search.

---

Scenario 39: Search Memory With Builder Pattern Usage

Details:
  TestName: searchMemoryUsesBuilderPatternCorrectly
  Description: This test verifies that both SearchMemoryResponse.builder() and MemoryEntry.builder() are used correctly to construct response objects with proper field population.

Execution:
  Arrange: Set up InMemoryMemoryService with matching events. Prepare a query.
  Act: Execute searchMemory and examine the returned objects.
  Assert: Verify that the response and memory entry objects are properly constructed using builders and contain all expected fields.

Validation:
  The assertion validates proper use of the builder pattern for object construction, ensuring immutability and correct field initialization. This confirms adherence to the codebase's architectural patterns.

---

Scenario 40: Search Memory With ImmutableList CopyOf Usage

Details:
  TestName: searchMemoryCreatesImmutableListCopy
  Description: This test verifies that ImmutableList.copyOf() is used to create an immutable copy of the matchingMemories list, ensuring the response cannot be modified.

Execution:
  Arrange: Create InMemoryMemoryService with matching events. Prepare a query that returns results.
  Act: Invoke searchMemory and retrieve the memories list.
  Assert: Verify that the memories list is a separate immutable copy, not a reference to the internal ArrayList.

Validation:
  This assertion confirms proper defensive copying and immutability practices, ensuring internal state cannot be modified through returned references. This is critical for thread-safety and data integrity in concurrent environments.

*/

// ********RoostGPT********

package com.google.adk.memory;
import static com.google.common.collect.ImmutableList.toImmutableList;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.google.adk.events.Event;
import com.google.adk.sessions.Session;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableSet;
import com.google.genai.types.Content;
import com.google.genai.types.Part;
import io.reactivex.rxjava3.core.Single;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import org.junit.jupiter.api.*;
import com.google.common.base.Strings;
import io.reactivex.rxjava3.core.Completable;
import java.util.Collections;
import java.util.HashSet;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

class InMemoryMemoryServiceSearchMemoryTest {
    private InMemoryMemoryService memoryService;
    @BeforeEach
    void setUp() {
        memoryService = new InMemoryMemoryService();
    }
    @Test
    @Tag("valid")
    void searchMemoryReturnsEmptyResponseWhenUserKeyNotFound() {
        String appName = "testApp";
        String userId = "user123";
        String query = "test query";
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertTrue(response.memories() == null || response.memories().isEmpty());
    }
    @Test
    @Tag("valid")
    void searchMemoryReturnsMatchingMemoriesForSingleWordQuery() {
        String appName = "testApp";
        String userId = "user123";
        String query = "hello";
        Session session = createSessionWithEvents(appName, userId, "session1",
                createEvent("Hello world", "author1", 1000L));
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertNotNull(response.memories());
        assertEquals(1, response.memories().size());
        assertTrue(response.memories().get(0).content().parts().get().get(0).text().get().contains("Hello"));
    }
    @Test
    @Tag("valid")
    void searchMemoryReturnsMatchingMemoriesForMultiWordQuery() {
        String appName = "testApp";
        String userId = "user123";
        String query = "hello world";
        Session session = createSessionWithEvents(appName, userId, "session1",
                createEvent("Hello there", "author1", 1000L),
                createEvent("World news", "author2", 2000L),
                createEvent("Goodbye", "author3", 3000L));
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertNotNull(response.memories());
        assertEquals(2, response.memories().size());
    }
    @Test
    @Tag("valid")
    void searchMemoryPerformsCaseInsensitiveMatching() {
        String appName = "testApp";
        String userId = "user123";
        String query = "HELLO";
        Session session = createSessionWithEvents(appName, userId, "session1",
                createEvent("hello world", "author1", 1000L),
                createEvent("HELLO WORLD", "author2", 2000L),
                createEvent("HeLLo WoRLd", "author3", 3000L));
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertNotNull(response.memories());
        assertEquals(3, response.memories().size());
    }
    @Test
    @Tag("boundary")
    void searchMemoryWithEmptyQueryReturnsEmptyResponse() {
        String appName = "testApp";
        String userId = "user123";
        String query = "";
        Session session = createSessionWithEvents(appName, userId, "session1",
                createEvent("Hello world", "author1", 1000L));
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertTrue(response.memories() == null || response.memories().isEmpty());
    }
    @Test
    @Tag("boundary")
    void searchMemoryWithWhitespaceOnlyQueryReturnsEmptyResponse() {
        String appName = "testApp";
        String userId = "user123";
        String query = "   ";
        Session session = createSessionWithEvents(appName, userId, "session1",
                createEvent("Hello world", "author1", 1000L));
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertTrue(response.memories() == null || response.memories().isEmpty());
    }
    @Test
    @Tag("valid")
    void searchMemoryIgnoresSpecialCharactersInQuery() {
        String appName = "testApp";
        String userId = "user123";
        String query = "hello! world?";
        Session session = createSessionWithEvents(appName, userId, "session1",
                createEvent("hello world", "author1", 1000L));
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertNotNull(response.memories());
        assertEquals(1, response.memories().size());
    }
    @Test
    @Tag("valid")
    void searchMemorySkipsEventsWithEmptyContent() {
        String appName = "testApp";
        String userId = "user123";
        String query = "hello";
        Event eventWithContent = createEvent("hello world", "author1", 1000L);
        Event eventWithEmptyContent = mock(Event.class);
        when(eventWithEmptyContent.content()).thenReturn(Optional.empty());
        Session session = createSessionWithEvents(appName, userId, "session1",
                eventWithContent, eventWithEmptyContent);
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertNotNull(response.memories());
        assertEquals(1, response.memories().size());
    }
    @Test
    @Tag("valid")
    void searchMemorySkipsEventsWithEmptyPartsList() {
        String appName = "testApp";
        String userId = "user123";
        String query = "hello";
        Event eventWithParts = createEvent("hello world", "author1", 1000L);
        Event eventWithEmptyParts = mock(Event.class);
        Content emptyContent = mock(Content.class);
        when(eventWithEmptyParts.content()).thenReturn(Optional.of(emptyContent));
        when(emptyContent.parts()).thenReturn(Optional.of(ImmutableList.of()));
        Session session = createSessionWithEvents(appName, userId, "session1",
                eventWithParts, eventWithEmptyParts);
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertNotNull(response.memories());
        assertEquals(1, response.memories().size());
    }
    @Test
    @Tag("valid")
    void searchMemorySkipsPartsWithNullOrEmptyText() {
        String appName = "testApp";
        String userId = "user123";
        String query = "hello";
        Part partWithText = mock(Part.class);
        when(partWithText.text()).thenReturn(Optional.of("hello world"));
        Part partWithEmptyText = mock(Part.class);
        when(partWithEmptyText.text()).thenReturn(Optional.of(""));
        Part partWithNullText = mock(Part.class);
        when(partWithNullText.text()).thenReturn(Optional.empty());
        Content content = mock(Content.class);
        when(content.parts()).thenReturn(Optional.of(ImmutableList.of(partWithText, partWithEmptyText, partWithNullText)));
        Event event = mock(Event.class);
        when(event.content()).thenReturn(Optional.of(content));
        when(event.author()).thenReturn("author1");
        when(event.timestamp()).thenReturn(1000L);
        Session session = createSessionWithEvents(appName, userId, "session1", event);
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertNotNull(response.memories());
        assertEquals(1, response.memories().size());
    }
    @Test
    @Tag("valid")
    void searchMemorySkipsEventsWithNoExtractableWords() {
        String appName = "testApp";
        String userId = "user123";
        String query = "hello";
        Session session = createSessionWithEvents(appName, userId, "session1",
                createEvent("hello world", "author1", 1000L),
                createEvent("123 !@# 456", "author2", 2000L));
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertNotNull(response.memories());
        assertEquals(1, response.memories().size());
    }
    @Test
    @Tag("valid")
    void searchMemorySearchesAcrossAllUserSessions() {
        String appName = "testApp";
        String userId = "user123";
        String query = "hello";
        Session session1 = createSessionWithEvents(appName, userId, "session1",
                createEvent("hello from session1", "author1", 1000L));
        Session session2 = createSessionWithEvents(appName, userId, "session2",
                createEvent("hello from session2", "author2", 2000L));
        memoryService.addSessionToMemory(session1).blockingAwait();
        memoryService.addSessionToMemory(session2).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertNotNull(response.memories());
        assertEquals(2, response.memories().size());
    }
    @Test
    @Tag("valid")
    void searchMemorySearchesAllEventsInSession() {
        String appName = "testApp";
        String userId = "user123";
        String query = "hello";
        Session session = createSessionWithEvents(appName, userId, "session1",
                createEvent("hello world", "author1", 1000L),
                createEvent("goodbye", "author2", 2000L),
                createEvent("hello again", "author3", 3000L));
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertNotNull(response.memories());
        assertEquals(2, response.memories().size());
    }
    @Test
    @Tag("valid")
    void searchMemoryExtractsWordsFromAllPartsInEvent() {
        String appName = "testApp";
        String userId = "user123";
        String query = "hello world";
        Part part1 = mock(Part.class);
        when(part1.text()).thenReturn(Optional.of("hello"));
        Part part2 = mock(Part.class);
        when(part2.text()).thenReturn(Optional.of("world"));
        Content content = mock(Content.class);
        when(content.parts()).thenReturn(Optional.of(ImmutableList.of(part1, part2)));
        Event event = mock(Event.class);
        when(event.content()).thenReturn(Optional.of(content));
        when(event.author()).thenReturn("author1");
        when(event.timestamp()).thenReturn(1000L);
        Session session = createSessionWithEvents(appName, userId, "session1", event);
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertNotNull(response.memories());
        assertEquals(1, response.memories().size());
    }
    @Test
    @Tag("valid")
    void searchMemoryDoesNotMatchPartialWords() {
        String appName = "testApp";
        String userId = "user123";
        String query = "test";
        Session session = createSessionWithEvents(appName, userId, "session1",
                createEvent("testing contest", "author1", 1000L));
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertTrue(response.memories() == null || response.memories().isEmpty());
    }
    @Test
    @Tag("valid")
    void searchMemoryReturnsCorrectlyStructuredMemoryEntries() {
        String appName = "testApp";
        String userId = "user123";
        String query = "hello";
        long timestamp = 1609459200L;
        Session session = createSessionWithEvents(appName, userId, "session1",
                createEvent("hello world", "testAuthor", timestamp));
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertNotNull(response.memories());
        assertEquals(1, response.memories().size());
        MemoryEntry memory = response.memories().get(0);
        assertNotNull(memory.content());
        assertEquals("testAuthor", memory.author());
        assertEquals(Instant.ofEpochSecond(timestamp).toString(), memory.timestamp());
    }
    @Test
    @Tag("valid")
    void searchMemoryHandlesDuplicateWordsInQuery() {
        String appName = "testApp";
        String userId = "user123";
        String query = "test test hello test";
        Session session = createSessionWithEvents(appName, userId, "session1",
                createEvent("test message", "author1", 1000L));
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertNotNull(response.memories());
        assertEquals(1, response.memories().size());
    }
    @Test
    @Tag("valid")
    void searchMemoryHandlesLongQueryStrings() {
        String appName = "testApp";
        String userId = "user123";
        StringBuilder longQuery = new StringBuilder();
        for (int i = 0; i < 100; i++) {
            longQuery.append("word").append(i).append(" ");
        }
        longQuery.append("hello");
        Session session = createSessionWithEvents(appName, userId, "session1",
                createEvent("hello world", "author1", 1000L));
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, longQuery.toString()).blockingGet();
        assertNotNull(response);
        assertNotNull(response.memories());
        assertEquals(1, response.memories().size());
    }
    @Test
    @Tag("valid")
    void searchMemoryHandlesLargeNumberOfEvents() {
        String appName = "testApp";
        String userId = "user123";
        String query = "hello";
        List<Event> events = new ArrayList<>();
        for (int i = 0; i < 1000; i++) {
            events.add(createEvent("message " + i, "author" + i, 1000L + i));
        }
        events.add(createEvent("hello world", "author1000", 2000L));
        Session session = createSessionWithEvents(appName, userId, "session1", events.toArray(new Event[0]));
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertNotNull(response.memories());
        assertEquals(1, response.memories().size());
    }
    @Test
    @Tag("valid")
    void searchMemoryReturnsImmutableMemoriesList() {
        String appName = "testApp";
        String userId = "user123";
        String query = "hello";
        Session session = createSessionWithEvents(appName, userId, "session1",
                createEvent("hello world", "author1", 1000L));
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertNotNull(response.memories());
        assertThrows(UnsupportedOperationException.class, () -> {
            response.memories().add(mock(MemoryEntry.class));
        });
    }
    @Test
    @Tag("invalid")
    void searchMemoryHandlesNullAppName() {
        String userId = "user123";
        String query = "hello";
        assertThrows(NullPointerException.class, () -> {
            memoryService.searchMemory(null, userId, query).blockingGet();
        });
    }
    @Test
    @Tag("invalid")
    void searchMemoryHandlesNullUserId() {
        String appName = "testApp";
        String query = "hello";
        assertThrows(NullPointerException.class, () -> {
            memoryService.searchMemory(appName, null, query).blockingGet();
        });
    }
    @Test
    @Tag("invalid")
    void searchMemoryHandlesNullQuery() {
        String appName = "testApp";
        String userId = "user123";
        assertThrows(NullPointerException.class, () -> {
            memoryService.searchMemory(appName, userId, null).blockingGet();
        });
    }
    @Test
    @Tag("boundary")
    void searchMemoryWithNumericQueryReturnsNoMatches() {
        String appName = "testApp";
        String userId = "user123";
        String query = "12345";
        Session session = createSessionWithEvents(appName, userId, "session1",
                createEvent("hello 12345 world", "author1", 1000L));
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertTrue(response.memories() == null || response.memories().isEmpty());
    }
    @Test
    @Tag("valid")
    void searchMemoryExtractsOnlyAlphabeticPortionsFromMixedQuery() {
        String appName = "testApp";
        String userId = "user123";
        String query = "test123hello456world";
        Session session = createSessionWithEvents(appName, userId, "session1",
                createEvent("test hello world", "author1", 1000L));
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertNotNull(response.memories());
        assertEquals(1, response.memories().size());
    }
    @Test
    @Tag("valid")
    void searchMemoryPreservesEventProcessingOrder() {
        String appName = "testApp";
        String userId = "user123";
        String query = "hello";
        Session session = createSessionWithEvents(appName, userId, "session1",
                createEvent("hello first", "author1", 1000L),
                createEvent("hello second", "author2", 2000L),
                createEvent("hello third", "author3", 3000L));
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertNotNull(response.memories());
        assertEquals(3, response.memories().size());
    }
    @Test
    @Tag("boundary")
    void searchMemoryMatchesSingleCharacterWords() {
        String appName = "testApp";
        String userId = "user123";
        String query = "a";
        Session session = createSessionWithEvents(appName, userId, "session1",
                createEvent("a test message", "author1", 1000L));
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertNotNull(response.memories());
        assertEquals(1, response.memories().size());
    }
    @Test
    @Tag("valid")
    void searchMemoryReturnsEmptyResponseWhenNoMatchesFound() {
        String appName = "testApp";
        String userId = "user123";
        String query = "nonexistent";
        Session session = createSessionWithEvents(appName, userId, "session1",
                createEvent("hello world", "author1", 1000L));
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertTrue(response.memories() == null || response.memories().isEmpty());
    }
    @Test
    @Tag("valid")
    void searchMemoryHandlesLocaleSpecificCharacters() {
        String appName = "testApp";
        String userId = "user123";
        String query = "café";
        Session session = createSessionWithEvents(appName, userId, "session1",
                createEvent("café naïve", "author1", 1000L));
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertTrue(response.memories() == null || response.memories().isEmpty());
    }
    @Test
    @Tag("integration")
    void searchMemoryHandlesConcurrentAccess() throws InterruptedException {
        String appName = "testApp";
        String userId = "user123";
        Session session = createSessionWithEvents(appName, userId, "session1",
                createEvent("hello world test message", "author1", 1000L));
        memoryService.addSessionToMemory(session).blockingAwait();
        int threadCount = 10;
        ExecutorService executorService = Executors.newFixedThreadPool(threadCount);
        CountDownLatch latch = new CountDownLatch(threadCount);
        AtomicInteger successCount = new AtomicInteger(0);
        for (int i = 0; i < threadCount; i++) {
            final String query = (i % 2 == 0) ? "hello" : "test";
            executorService.submit(() -> {
                try {
                    SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
                    if (response != null && response.memories() != null && !response.memories().isEmpty()) {
                        successCount.incrementAndGet();
                    }
                } finally {
                    latch.countDown();
                }
            });
        }
        latch.await(5, TimeUnit.SECONDS);
        executorService.shutdown();
        assertEquals(threadCount, successCount.get());
    }
    @Test
    @Tag("valid")
    void searchMemoryFormatsTimestampCorrectly() {
        String appName = "testApp";
        String userId = "user123";
        String query = "hello";
        long timestamp = 1609459200L;
        Session session = createSessionWithEvents(appName, userId, "session1",
                createEvent("hello world", "author1", timestamp));
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertNotNull(response.memories());
        assertEquals(1, response.memories().size());
        String expectedTimestamp = Instant.ofEpochSecond(timestamp).toString();
        assertEquals(expectedTimestamp, response.memories().get(0).timestamp());
    }
    @Test
    @Tag("boundary")
    void searchMemoryWithEmptySessionEventsReturnsEmptyResponse() {
        String appName = "testApp";
        String userId = "user123";
        String query = "hello";
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertTrue(response.memories() == null || response.memories().isEmpty());
    }
    @Test
    @Tag("valid")
    void searchMemoryPreservesAuthorInformation() {
        String appName = "testApp";
        String userId = "user123";
        String query = "hello";
        String expectedAuthor = "testAuthor123";
        Session session = createSessionWithEvents(appName, userId, "session1",
                createEvent("hello world", expectedAuthor, 1000L));
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertNotNull(response.memories());
        assertEquals(1, response.memories().size());
        assertEquals(expectedAuthor, response.memories().get(0).author());
    }
    @Test
    @Tag("valid")
    void searchMemoryPreservesEventContent() {
        String appName = "testApp";
        String userId = "user123";
        String query = "hello";
        String expectedText = "hello world";
        Session session = createSessionWithEvents(appName, userId, "session1",
                createEvent(expectedText, "author1", 1000L));
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertNotNull(response.memories());
        assertEquals(1, response.memories().size());
        assertNotNull(response.memories().get(0).content());
        assertNotNull(response.memories().get(0).content().parts());
        assertTrue(response.memories().get(0).content().parts().get().get(0).text().get().contains("hello"));
    }
    @Test
    @Tag("valid")
    void searchMemoryReturnsReactiveSingle() {
        String appName = "testApp";
        String userId = "user123";
        String query = "hello";
        Single<SearchMemoryResponse> result = memoryService.searchMemory(appName, userId, query);
        assertNotNull(result);
        assertTrue(result instanceof Single);
        SearchMemoryResponse response = result.blockingGet();
        assertNotNull(response);
    }
    @Test
    @Tag("valid")
    void searchMemoryUsesDisjointCheckCorrectly() {
        String appName = "testApp";
        String userId = "user123";
        String query = "hello goodbye";
        Session session = createSessionWithEvents(appName, userId, "session1",
                createEvent("hello world", "author1", 1000L),
                createEvent("goodbye world", "author2", 2000L),
                createEvent("test message", "author3", 3000L));
        memoryService.addSessionToMemory(session).blockingAwait();
        SearchMemoryResponse response = memoryService.searchMemory(appName, userId, query).blockingGet();
        assertNotNull(response);
        assertNotNull(response.memories());
        assertEquals(2, response.memories().size());
    }
    private Session createSessionWithEvents(String appName, String userId, String sessionId, Event... events) {
        Session session = mock(Session.class);
        when(session.appName()).thenReturn(appName);
        when(session.userId()).thenReturn(userId);
        when(session.id()).thenReturn(sessionId);
        when(session.events()).thenReturn(ImmutableList.copyOf(events));
        return session;
    }
    private Event createEvent(String text, String author, long timestamp) {
        Part part = mock(Part.class);
        when(part.text()).thenReturn(Optional.of(text));
        Content content = mock(Content.class);
        when(content.parts()).thenReturn(Optional.of(ImmutableList.of(part)));
        Event event = mock(Event.class);
        when(event.content()).thenReturn(Optional.of(content));
        when(event.author()).thenReturn(author);
        when(event.timestamp()).thenReturn(timestamp);
        return event;
    }
}