/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test maven-adkjava-github using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=searchMemory_5b46a62b19
ROOST_METHOD_SIG_HASH=searchMemory_2ebd5f3610

Scenario 1: Search with No Sessions for App User

Details:
  TestName: searchReturnsEmptyResponseWhenNoSessionsExist
  Description: This test verifies that, when there are no sessions existing for the given appName and userId in the in-memory storage, the searchMemory method returns an empty SearchMemoryResponse (i.e., no MemoryEntry results).

Execution:
  Arrange: Prepare an instance of InMemoryMemoryService with an empty sessionEvents map—i.e., simulate the behavior before any sessions are added.
  Act: Call searchMemory with any valid appName, userId, and query.
  Assert: Assert that the returned SearchMemoryResponse is empty (contains no memories).

Validation:
  This assertion confirms that the method handles cases with no user events gracefully, without error, and returns an empty response, preserving the contract for users without history.


Scenario 2: Search with Sessions but No Matching Events

Details:
  TestName: searchReturnsEmptyWhenNoEventMatchesQuery
  Description: This test checks that, when sessions exist for the specified appName and userId but none of the events contain content/words matching the query, the result is an empty SearchMemoryResponse.

Execution:
  Arrange: Add a session for the appName/userId containing events whose contents do not contain any query keywords.
  Act: Call searchMemory with a query that does not match any event content.
  Assert: Assert that SearchMemoryResponse contains no matching memories.

Validation:
  This test ensures that searches return only relevant memories and do not return unrelated events, maintaining search result relevance.


Scenario 3: Search Where Events Match Query Keywords Exactly

Details:
  TestName: searchReturnsMatchingMemoriesForExactKeyword
  Description: This test verifies that, when one or more events contain content with exact words contained in the query, the corresponding MemoryEntry objects are returned in the SearchMemoryResponse.

Execution:
  Arrange: Add a session for the user, including an event with a part whose text contains the word "apple".
  Act: Invoke searchMemory with the query "apple".
  Assert: Confirm that the SearchMemoryResponse contains a MemoryEntry for the matching event.

Validation:
  This ensures basic keyword matching works as expected, and a relevant event is returned when its content matches the search query.


Scenario 4: Search Query Matches Case-Insensitive Keyword in Event

Details:
  TestName: searchMatchesKeywordsIgnoringCase
  Description: This test confirms the search is case-insensitive. If an event’s content contains "Apple" and the user queries "apple", the result should include this event as a match.

Execution:
  Arrange: Add an event to user sessions with a part text "Apple".
  Act: Search using query "apple" (different case).
  Assert: Assert the search returns the MemoryEntry for that event.

Validation:
  Case insensitivity provides a better user experience, verifying the system normalizes both query and content to lower case in comparisons.


Scenario 5: Multiple Events in Session, Some Matching

Details:
  TestName: searchReturnsOnlyMemoriesThatMatchQuery
  Description: This test checks if only those events matching the query terms are present in the SearchMemoryResponse, while events without matches are excluded.

Execution:
  Arrange: Add multiple events, some with and some without query words in their contents.
  Act: Search with a keyword present in only a subset of events.
  Assert: Confirm the response contains only MemoryEntry objects matching the criteria.

Validation:
  This test validates that filtering logic works correctly, and non-matching memory entries are omitted from results.


Scenario 6: Event Has Content but Parts List Is Empty

Details:
  TestName: searchIgnoresEventsWithEmptyParts
  Description: Ensure events whose content is present but parts list is empty are skipped and not considered for query matching.

Execution:
  Arrange: For a session, add an event whose content exists but has an empty parts collection.
  Act: Search for any keyword.
  Assert: SearchMemoryResponse should not include this event, regardless of the query.

Validation:
  Helps confirm the robustness of the search implementation in ignoring structurally invalid event data.


Scenario 7: Search Where Event Part Has Null or Empty Text

Details:
  TestName: searchIgnoresEventPartsWithNullOrEmptyText
  Description: Ensures that if a Part in an event has either empty or null text, it is ignored in the keyword extraction and matching process.

Execution:
  Arrange: Add an event with at least one part whose text is null/empty, and another part with valid text.
  Act: Search for keywords present only in the valid part.
  Assert: Event is matched if at least one part contains the word. If all texts are empty/null, event is not considered.

Validation:
  Validates handling of incomplete or missing text in parts, ensuring only non-empty, non-null text is evaluated.


Scenario 8: Single Event With Multiple Parts (Multi-Word) Matching Query

Details:
  TestName: searchFindsMatchAcrossMultipleParts
  Description: Tests that search is performed across all parts of an event, and any matching part causes the event to be included in the results.

Execution:
  Arrange: Add an event with several parts, at least one of which contains a query word.
  Act: Search with the query covering at least one word in these parts.
  Assert: Assert MemoryEntry is included for this event.

Validation:
  This confirms the correct aggregation of words from all parts in an event and that the search isn’t limited to a single part.


Scenario 9: Query Contains Multiple Words, One Matches an Event

Details:
  TestName: searchMatchesIfAnyKeywordInQueryIsFound
  Description: Ensures that if a query contains several words, only one of which matches words in an event, that event is included in results.

Execution:
  Arrange: Add an event whose content contains only one of several query words.
  Act: Provide query with multiple keywords, including a match.
  Assert: Event appears in the result set.

Validation:
  This affirms that the requirement is logical OR across query words, and not a logical AND.


Scenario 10: Event Content Contains Multiple Word Variants and Query Is Substring

Details:
  TestName: searchDoesNotMatchSubstringOnly
  Description: Verify that search matches complete words only, not substrings. For example, if content has "apple", a search for "app" returns no results.

Execution:
  Arrange: Add event with part "apple".
  Act: Search using query "app".
  Assert: SearchMemoryResponse is empty.

Validation:
  Validates correct use of the WORD_PATTERN regular expression to ensure partial word matches do not result in false positives.


Scenario 11: Search Handles Punctuation in Content Gracefully

Details:
  TestName: searchExtractsKeywordsIgnoringPunctuation
  Description: Test that event content containing words adjacent to punctuation marks are still matched, e.g., "apple," matches query "apple".

Execution:
  Arrange: Add event with part text "apple, banana!".
  Act: Search with "apple".
  Assert: MemoryEntry with this event is returned.

Validation:
  Ensures pattern-based splitting properly extracts keywords, not being tripped up by punctuation.


Scenario 12: Event With Multiple Sessions Per User

Details:
  TestName: searchAggregatesEventsAcrossSessions
  Description: Verifies that the search aggregates over all sessions for a user, not just a specific session.

Execution:
  Arrange: Create multiple sessions for the same user, each containing events with matching/non-matching words.
  Act: Search with query matching word(s) present in more than one session.
  Assert: All relevant MemoryEntry objects from all sessions are present.

Validation:
  Affirms complete user memory search scope across available sessions.


Scenario 13: Query Is an Empty String

Details:
  TestName: searchWithEmptyQueryReturnsNoResults
  Description: Ensures when query is the empty string, no events are returned even if they contain text.

Execution:
  Arrange: Add event(s) with valid content to user sessions.
  Act: Search with query "".
  Assert: SearchMemoryResponse returns empty (no memories).

Validation:
  This verifies the expected null-effect of an empty search query and prevents accidental "match-all" behavior.


Scenario 14: Event Content Has Only Numbers or Symbols, No Words

Details:
  TestName: searchIgnoresEventsWithNoAlphaWords
  Description: Events containing only numbers and punctuation do not produce any words via WORD_PATTERN, so should never result in matches.

Execution:
  Arrange: Add event with content/part text "123$%#@".
  Act: Search for any query.
  Assert: SearchMemoryResponse contains no entries for these events.

Validation:
  Ensures WORD_PATTERN is enforced, and no invalid "words" cause a result.


Scenario 15: Result MemoryEntry Has Correct Content, Author, Timestamp

Details:
  TestName: searchReturnsMemoryWithCorrectFields
  Description: Validates that returned MemoryEntry has the same content, author string, and formatted timestamp as expected when a match occurs.

Execution:
  Arrange: Add an event with known content, author, and epoch timestamp.
  Act: Search for a keyword present in its content.
  Assert: Assert MemoryEntry fields match input event data, and the timestamp is correctly formatted according to formatTimestamp logic.

Validation:
  Confirms data mapping and field population for positive search results, including timestamp conversion.


Scenario 16: Multiple Events Match Query—Ordering

Details:
  TestName: searchMaintainsEventOrderInResult
  Description: Checks whether the order of MemoryEntry objects in the response matches the order in which events are stored (per iteration insertion).

Execution:
  Arrange: Add multiple events with query matches to a session, keeping track of their order.
  Act: Search so all are matched.
  Assert: Ensure result list order matches input sequence.

Validation:
  Important for predictability if client expects stable ordering.


Scenario 17: Concurrent Modification of sessionEvents During Search

Details:
  TestName: searchIsThreadSafeAgainstConcurrentModification
  Description: Ensure that concurrent updates to sessionEvents do not cause the search operation to fail with errors (e.g., ConcurrentModificationException).

Execution:
  Arrange: Fill sessionEvents with sessions and events, then modify sessionEvents from another thread during search.
  Act: Call searchMemory.
  Assert: Search completes without throwing exceptions.

Validation:
  Validates the thread-safety requirements and use of ConcurrentHashMap in the implementation.


Scenario 18: Search with Query that Has Leading/Trailing Whitespace

Details:
  TestName: searchIgnoresQueryWhitespace
  Description: Ensure that leading and trailing spaces in the query do not affect matching.

Execution:
  Arrange: Add event with part "banana".
  Act: Search with query " banana ".
  Assert: Matching event is returned.

Validation:
  Ensures trimming and splitting of input query does not introduce errors in keyword extraction.


Scenario 19: Multiple Users with Separate Sessions

Details:
  TestName: searchReturnsOnlyCurrentUserResults
  Description: Test that results for a given user do not include events from sessions belonging to any other appName/userId combination.

Execution:
  Arrange: Add sessions for multiple users (different userIds and/or appNames), with similar content.
  Act: Search under one user for a keyword that exists in both users' sessions.
  Assert: Only MemoryEntry(s) for current user/app are present in results.

Validation:
  Ensures session isolation and prevents data leakage between users.


Scenario 20: Search with Special Unicode Characters in Query and Content

Details:
  TestName: searchDoesNotMatchNonAsciiWords
  Description: Checks that only words matching the [A-Za-z]+ pattern (i.e., ASCII alphabets) are considered valid for matching, and queries in non-Latin scripts are ignored.

Execution:
  Arrange: Add event with non-ASCII text, e.g., "你好" (Chinese).
  Act: Search for "你好".
  Assert: Response is empty.

Validation:
  Ensures regular expression filter works as intended and avoids false matches on non-ASCII content.


*/

// ********RoostGPT********

package com.google.adk.memory;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.events.Event;
import com.google.adk.sessions.Session;
import com.google.common.collect.ImmutableList;
import com.google.genai.types.Content;
import com.google.genai.types.Part;
import io.reactivex.rxjava3.core.Single;
import java.time.Instant;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

// Import missing Content class InMemoryMemoryServiceSearchMemoryTest it exists in the relevant
// package.
// Assuming Content is com.google.genai.types.Content
class InMemoryMemoryServiceSearchMemoryTest {

	private InMemoryMemoryService service;

	private static final String APP_NAME = "testApp";

	private static final String USER_ID = "user123";

	private static final String SESSION_ID = "sessionABC";

	private static final long EVENT_TIMESTAMP = 1710000000L; // TODO: replace with actual
																// needed epoch value if
																// test setup requires

	@BeforeEach
	public void setUp() {
		service = new InMemoryMemoryService();
	}

	// Helper to build Content with Parts
	private Content buildContentWithParts(List<Part> parts) {
		Content content = mock(Content.class);
		when(content.parts()).thenReturn(java.util.Optional.of(ImmutableList.copyOf(parts)));
		return content;
	}

	// Helper to build Event
	private Event buildEvent(Content content, String author, long timestamp) {
		Event event = mock(Event.class);
		when(event.content()).thenReturn(java.util.Optional.ofNullable(content));
		when(event.author()).thenReturn(author);
		when(event.timestamp()).thenReturn(timestamp);
		return event;
	}

	// Helper to build an empty Content
	private Content buildEmptyContent() {
		Content content = mock(Content.class);
		when(content.parts()).thenReturn(java.util.Optional.of(ImmutableList.of()));
		return content;
	}

	// Helper to create a Session
	private Session buildSession(String appName, String userId, String sessionId, List<Event> events) {
		Session session = mock(Session.class);
		when(session.appName()).thenReturn(appName);
		when(session.userId()).thenReturn(userId);
		when(session.id()).thenReturn(sessionId);
		when(session.events()).thenReturn(ImmutableList.copyOf(events));
		return session;
	}

	// Helper to build Part
	private Part buildPartWithText(String text) {
		Part part = mock(Part.class);
		when(part.text()).thenReturn(java.util.Optional.ofNullable(text));
		return part;
	}

	@Test
	@Tag("boundary")
	public void testSearchReturnsEmptyResponseWhenNoSessionsExist() {
		Single<SearchMemoryResponse> searchResp = service.searchMemory(APP_NAME, USER_ID, "apple");
		SearchMemoryResponse result = (SearchMemoryResponse) searchResp.blockingGet();
		assertNotNull(result, "SearchMemoryResponse should not be null");
		assertEquals(0, (result.memories() != null ? ((List<?>) result.memories()).size() : 0),
				"Expected no matching memories");
	}

	@Test
	@Tag("valid")
	public void testSearchReturnsEmptyWhenNoEventMatchesQuery() {
		Part partNoMatch = buildPartWithText("orange");
		Content content = buildContentWithParts(ImmutableList.of(partNoMatch));
		Event event = buildEvent(content, "authorA", EVENT_TIMESTAMP);
		Session session = buildSession(APP_NAME, USER_ID, SESSION_ID, ImmutableList.of(event));
		service.addSessionToMemory(session).blockingAwait();
		Single<SearchMemoryResponse> searchResp = service.searchMemory(APP_NAME, USER_ID, "apple");
		SearchMemoryResponse result = (SearchMemoryResponse) searchResp.blockingGet();
		assertNotNull(result);
		assertEquals(0, (result.memories() != null ? ((List<?>) result.memories()).size() : 0));
	}

	@Test
	@Tag("valid")
	public void testSearchReturnsMatchingMemoriesForExactKeyword() {
		Part part = buildPartWithText("apple");
		Content content = buildContentWithParts(ImmutableList.of(part));
		Event event = buildEvent(content, "authorA", EVENT_TIMESTAMP);
		Session session = buildSession(APP_NAME, USER_ID, SESSION_ID, ImmutableList.of(event));
		service.addSessionToMemory(session).blockingAwait();
		SearchMemoryResponse result = (SearchMemoryResponse) service.searchMemory(APP_NAME, USER_ID, "apple")
			.blockingGet();
		assertNotNull(result);
		assertEquals(1, (result.memories() != null ? ((List<?>) result.memories()).size() : 0));
		assertEquals("authorA", ((MemoryEntry) result.memories().get(0)).author());
		assertEquals(content, ((MemoryEntry) result.memories().get(0)).content());
		assertEquals(Instant.ofEpochSecond(EVENT_TIMESTAMP).toString(),
				((MemoryEntry) result.memories().get(0)).timestamp());
	}

	@Test
	@Tag("valid")
	public void testSearchMatchesKeywordsIgnoringCase() {
		Part part = buildPartWithText("Apple");
		Content content = buildContentWithParts(ImmutableList.of(part));
		Event event = buildEvent(content, "authorB", EVENT_TIMESTAMP + 1);
		Session session = buildSession(APP_NAME, USER_ID, SESSION_ID, ImmutableList.of(event));
		service.addSessionToMemory(session).blockingAwait();
		SearchMemoryResponse result = (SearchMemoryResponse) service.searchMemory(APP_NAME, USER_ID, "apple")
			.blockingGet();
		assertNotNull(result);
		assertEquals(1, ((List<?>) result.memories()).size());
		assertEquals("authorB", ((MemoryEntry) result.memories().get(0)).author());
	}

	@Test
	@Tag("valid")
	public void testSearchReturnsOnlyMemoriesThatMatchQuery() {
		Part partMatch = buildPartWithText("banana");
		Content contentMatch = buildContentWithParts(ImmutableList.of(partMatch));
		Event eventMatch = buildEvent(contentMatch, "authorC", EVENT_TIMESTAMP + 2);
		Part partNoMatch = buildPartWithText("plum");
		Content contentNoMatch = buildContentWithParts(ImmutableList.of(partNoMatch));
		Event eventNoMatch = buildEvent(contentNoMatch, "authorD", EVENT_TIMESTAMP + 3);
		Session session = buildSession(APP_NAME, USER_ID, SESSION_ID, ImmutableList.of(eventMatch, eventNoMatch));
		service.addSessionToMemory(session).blockingAwait();
		SearchMemoryResponse result = (SearchMemoryResponse) service.searchMemory(APP_NAME, USER_ID, "banana")
			.blockingGet();
		assertNotNull(result);
		assertEquals(1, ((List<?>) result.memories()).size());
		assertEquals("authorC", ((MemoryEntry) result.memories().get(0)).author());
	}

	@Test
	@Tag("boundary")
	public void testSearchIgnoresEventsWithEmptyParts() {
		Content emptyContent = buildEmptyContent();
		Event event = buildEvent(emptyContent, "authorE", EVENT_TIMESTAMP + 4);
		Session session = buildSession(APP_NAME, USER_ID, SESSION_ID, ImmutableList.of(event));
		service.addSessionToMemory(session).blockingAwait();
		SearchMemoryResponse result = (SearchMemoryResponse) service.searchMemory(APP_NAME, USER_ID, "banana")
			.blockingGet();
		assertNotNull(result);
		assertEquals(0, ((List<?>) result.memories()).size());
	}

	@Test
	@Tag("boundary")
	public void testSearchIgnoresEventPartsWithNullOrEmptyText() {
		Part part1 = buildPartWithText("");
		Part part2 = buildPartWithText(null);
		Part part3 = buildPartWithText("cherry");
		Content content = buildContentWithParts(ImmutableList.of(part1, part2, part3));
		Event event = buildEvent(content, "authorF", EVENT_TIMESTAMP + 5);
		Session session = buildSession(APP_NAME, USER_ID, SESSION_ID, ImmutableList.of(event));
		service.addSessionToMemory(session).blockingAwait();
		SearchMemoryResponse resultValid = (SearchMemoryResponse) service.searchMemory(APP_NAME, USER_ID, "cherry")
			.blockingGet();
		assertNotNull(resultValid);
		assertEquals(1, ((List<?>) resultValid.memories()).size());
		SearchMemoryResponse resultInvalid = (SearchMemoryResponse) service.searchMemory(APP_NAME, USER_ID, "date")
			.blockingGet();
		assertNotNull(resultInvalid);
		assertEquals(0, ((List<?>) resultInvalid.memories()).size());
	}

	@Test
	@Tag("valid")
	public void testSearchFindsMatchAcrossMultipleParts() {
		Part part1 = buildPartWithText("plum");
		Part part2 = buildPartWithText("grape");
		Part part3 = buildPartWithText("apple");
		Content content = buildContentWithParts(ImmutableList.of(part1, part2, part3));
		Event event = buildEvent(content, "authorG", EVENT_TIMESTAMP + 6);
		Session session = buildSession(APP_NAME, USER_ID, SESSION_ID, ImmutableList.of(event));
		service.addSessionToMemory(session).blockingAwait();
		SearchMemoryResponse result = (SearchMemoryResponse) service.searchMemory(APP_NAME, USER_ID, "apple")
			.blockingGet();
		assertNotNull(result);
		assertEquals(1, ((List<?>) result.memories()).size());
		assertTrue(((MemoryEntry) result.memories().get(0)).content().parts().isPresent());
	}

	@Test
	@Tag("valid")
	public void testSearchMatchesIfAnyKeywordInQueryIsFound() {
		Part part = buildPartWithText("peach");
		Content content = buildContentWithParts(ImmutableList.of(part));
		Event event = buildEvent(content, "authorH", EVENT_TIMESTAMP + 7);
		Session session = buildSession(APP_NAME, USER_ID, SESSION_ID, ImmutableList.of(event));
		service.addSessionToMemory(session).blockingAwait();
		SearchMemoryResponse result1 = (SearchMemoryResponse) service
			.searchMemory(APP_NAME, USER_ID, "banana peach apple")
			.blockingGet();
		assertNotNull(result1);
		assertEquals(1, ((List<?>) result1.memories()).size());
		assertEquals("authorH", ((MemoryEntry) result1.memories().get(0)).author());
	}

	@Test
	@Tag("invalid")
	public void testSearchDoesNotMatchSubstringOnly() {
		Part part = buildPartWithText("apple");
		Content content = buildContentWithParts(ImmutableList.of(part));
		Event event = buildEvent(content, "authorI", EVENT_TIMESTAMP + 8);
		Session session = buildSession(APP_NAME, USER_ID, SESSION_ID, ImmutableList.of(event));
		service.addSessionToMemory(session).blockingAwait();
		SearchMemoryResponse result = (SearchMemoryResponse) service.searchMemory(APP_NAME, USER_ID, "app")
			.blockingGet();
		assertNotNull(result);
		assertEquals(0, ((List<?>) result.memories()).size());
	}

	@Test
	@Tag("boundary")
	public void testSearchExtractsKeywordsIgnoringPunctuation() {
		Part part = buildPartWithText("apple, banana!");
		Content content = buildContentWithParts(ImmutableList.of(part));
		Event event = buildEvent(content, "authorJ", EVENT_TIMESTAMP + 9);
		Session session = buildSession(APP_NAME, USER_ID, SESSION_ID, ImmutableList.of(event));
		service.addSessionToMemory(session).blockingAwait();
		SearchMemoryResponse result = (SearchMemoryResponse) service.searchMemory(APP_NAME, USER_ID, "apple")
			.blockingGet();
		assertNotNull(result);
		assertEquals(1, ((List<?>) result.memories()).size());
	}

	@Test
	@Tag("integration")
	public void testSearchAggregatesEventsAcrossSessions() {
		Part part1 = buildPartWithText("orange");
		Content content1 = buildContentWithParts(ImmutableList.of(part1));
		Event event1 = buildEvent(content1, "authorK", EVENT_TIMESTAMP + 10);
		Part part2 = buildPartWithText("orange");
		Content content2 = buildContentWithParts(ImmutableList.of(part2));
		Event event2 = buildEvent(content2, "authorL", EVENT_TIMESTAMP + 11);
		Session session1 = buildSession(APP_NAME, USER_ID, "session1", ImmutableList.of(event1));
		Session session2 = buildSession(APP_NAME, USER_ID, "session2", ImmutableList.of(event2));
		service.addSessionToMemory(session1).blockingAwait();
		service.addSessionToMemory(session2).blockingAwait();
		SearchMemoryResponse result = (SearchMemoryResponse) service.searchMemory(APP_NAME, USER_ID, "orange")
			.blockingGet();
		assertNotNull(result);
		assertEquals(2, ((List<?>) result.memories()).size());
		Set<String> authors = new HashSet<>();
		for (MemoryEntry mem : ((List<MemoryEntry>) result.memories())) {
			authors.add(mem.author());
		}
		assertTrue(authors.contains("authorK") && authors.contains("authorL"));
	}

	@Test
	@Tag("boundary")
	public void testSearchWithEmptyQueryReturnsNoResults() {
		Part part = buildPartWithText("grapefruit");
		Content content = buildContentWithParts(ImmutableList.of(part));
		Event event = buildEvent(content, "authorM", EVENT_TIMESTAMP + 12);
		Session session = buildSession(APP_NAME, USER_ID, SESSION_ID, ImmutableList.of(event));
		service.addSessionToMemory(session).blockingAwait();
		SearchMemoryResponse result = (SearchMemoryResponse) service.searchMemory(APP_NAME, USER_ID, "").blockingGet();
		assertNotNull(result);
		assertEquals(0, ((List<?>) result.memories()).size());
	}

	@Test
	@Tag("boundary")
	public void testSearchIgnoresEventsWithNoAlphaWords() {
		Part part = buildPartWithText("123$%#@");
		Content content = buildContentWithParts(ImmutableList.of(part));
		Event event = buildEvent(content, "authorN", EVENT_TIMESTAMP + 13);
		Session session = buildSession(APP_NAME, USER_ID, SESSION_ID, ImmutableList.of(event));
		service.addSessionToMemory(session).blockingAwait();
		SearchMemoryResponse result = (SearchMemoryResponse) service.searchMemory(APP_NAME, USER_ID, "anything")
			.blockingGet();
		assertNotNull(result);
		assertEquals(0, ((List<?>) result.memories()).size());
	}

	@Test
	@Tag("valid")
	public void testSearchReturnsMemoryWithCorrectFields() {
		Part part = buildPartWithText("fig");
		Content content = buildContentWithParts(ImmutableList.of(part));
		String author = "authorO";
		long timestamp = EVENT_TIMESTAMP + 14;
		Event event = buildEvent(content, author, timestamp);
		Session session = buildSession(APP_NAME, USER_ID, SESSION_ID, ImmutableList.of(event));
		service.addSessionToMemory(session).blockingAwait();
		SearchMemoryResponse result = (SearchMemoryResponse) service.searchMemory(APP_NAME, USER_ID, "fig")
			.blockingGet();
		assertNotNull(result);
		assertEquals(1, ((List<?>) result.memories()).size());
		MemoryEntry entry = (MemoryEntry) result.memories().get(0);
		assertEquals(content, entry.content());
		assertEquals(author, entry.author());
		assertEquals(Instant.ofEpochSecond(timestamp).toString(), entry.timestamp());
	}

	@Test
	@Tag("boundary")
	public void testSearchMaintainsEventOrderInResult() {
		Part part1 = buildPartWithText("jackfruit");
		Part part2 = buildPartWithText("jackfruit");
		Content content1 = buildContentWithParts(ImmutableList.of(part1));
		Content content2 = buildContentWithParts(ImmutableList.of(part2));
		Event event1 = buildEvent(content1, "authorP", EVENT_TIMESTAMP + 15);
		Event event2 = buildEvent(content2, "authorQ", EVENT_TIMESTAMP + 16);
		Session session = buildSession(APP_NAME, USER_ID, SESSION_ID, ImmutableList.of(event1, event2));
		service.addSessionToMemory(session).blockingAwait();
		SearchMemoryResponse result = (SearchMemoryResponse) service.searchMemory(APP_NAME, USER_ID, "jackfruit")
			.blockingGet();
		assertNotNull(result);
		assertEquals(2, ((List<?>) result.memories()).size());
		assertEquals("authorP", ((MemoryEntry) result.memories().get(0)).author());
		assertEquals("authorQ", ((MemoryEntry) result.memories().get(1)).author());
	}

	@Test
	@Tag("integration")
	public void testSearchIsThreadSafeAgainstConcurrentModification() throws InterruptedException {
		// Add initial event
		Part part = buildPartWithText("kiwi");
		Content content = buildContentWithParts(ImmutableList.of(part));
		Event event = buildEvent(content, "authorR", EVENT_TIMESTAMP + 17);
		Session session = buildSession(APP_NAME, USER_ID, SESSION_ID, ImmutableList.of(event));
		service.addSessionToMemory(session).blockingAwait();
		// Thread to modify sessionEvents concurrently
		Thread modifyThread = new Thread(() -> {
			Part newPart = buildPartWithText("kiwi");
			Content newContent = buildContentWithParts(ImmutableList.of(newPart));
			Event newEvent = buildEvent(newContent, "authorS", EVENT_TIMESTAMP + 18);
			Session newSession = buildSession(APP_NAME, USER_ID, SESSION_ID + "2", ImmutableList.of(newEvent));
			service.addSessionToMemory(newSession).blockingAwait();
		});
		modifyThread.start();
		SearchMemoryResponse result = (SearchMemoryResponse) service.searchMemory(APP_NAME, USER_ID, "kiwi")
			.blockingGet();
		modifyThread.join();
		// Should not throw and should contain at least one memory
		assertNotNull(result);
		assertTrue(((List<?>) result.memories()).size() >= 1);
	}

	@Test
	@Tag("valid")
	public void testSearchIgnoresQueryWhitespace() {
		Part part = buildPartWithText("banana");
		Content content = buildContentWithParts(ImmutableList.of(part));
		Event event = buildEvent(content, "authorT", EVENT_TIMESTAMP + 19);
		Session session = buildSession(APP_NAME, USER_ID, SESSION_ID, ImmutableList.of(event));
		service.addSessionToMemory(session).blockingAwait();
		String query = "   banana   ";
		SearchMemoryResponse result = (SearchMemoryResponse) service.searchMemory(APP_NAME, USER_ID, query)
			.blockingGet();
		assertNotNull(result);
		assertEquals(1, ((List<?>) result.memories()).size());
	}

	@Test
	@Tag("integration")
	public void testSearchReturnsOnlyCurrentUserResults() {
		Part partUserA = buildPartWithText("pear");
		Content contentUserA = buildContentWithParts(ImmutableList.of(partUserA));
		Event eventUserA = buildEvent(contentUserA, "authorU", EVENT_TIMESTAMP + 20);
		Part partUserB = buildPartWithText("pear");
		Content contentUserB = buildContentWithParts(ImmutableList.of(partUserB));
		Event eventUserB = buildEvent(contentUserB, "authorV", EVENT_TIMESTAMP + 21);
		String userB = "user456";
		Session sessionA = buildSession(APP_NAME, USER_ID, "sessionA", ImmutableList.of(eventUserA));
		Session sessionB = buildSession(APP_NAME, userB, "sessionB", ImmutableList.of(eventUserB));
		service.addSessionToMemory(sessionA).blockingAwait();
		service.addSessionToMemory(sessionB).blockingAwait();
		SearchMemoryResponse resultA = (SearchMemoryResponse) service.searchMemory(APP_NAME, USER_ID, "pear")
			.blockingGet();
		SearchMemoryResponse resultB = (SearchMemoryResponse) service.searchMemory(APP_NAME, userB, "pear")
			.blockingGet();
		assertEquals(1, ((List<?>) resultA.memories()).size());
		assertEquals("authorU", ((MemoryEntry) resultA.memories().get(0)).author());
		assertEquals(1, ((List<?>) resultB.memories()).size());
		assertEquals("authorV", ((MemoryEntry) resultB.memories().get(0)).author());
	}

	@Test
	@Tag("invalid")
	public void testSearchDoesNotMatchNonAsciiWords() {
		Part part = buildPartWithText("你好");
		Content content = buildContentWithParts(ImmutableList.of(part));
		Event event = buildEvent(content, "authorW", EVENT_TIMESTAMP + 22);
		Session session = buildSession(APP_NAME, USER_ID, SESSION_ID, ImmutableList.of(event));
		service.addSessionToMemory(session).blockingAwait();
		SearchMemoryResponse result = (SearchMemoryResponse) service.searchMemory(APP_NAME, USER_ID, "你好")
			.blockingGet();
		assertNotNull(result);
		assertEquals(0, ((List<?>) result.memories()).size());
	}

}
