/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-maven-adk_clone using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=addSessionToMemory_8a630adf5c
ROOST_METHOD_SIG_HASH=addSessionToMemory_3e3003d0a0

Scenario 1: Successfully Add Session with Valid Events to Memory

Details:
  TestName: addSessionWithValidEventsSuccessfully
  Description: This test verifies that a session containing valid events with non-empty content and parts is successfully added to the in-memory storage. The method should store the session under the correct user key (appName/userId) and session ID, filtering and storing only events that have content with non-empty parts.
Execution:
  Arrange: Create a Session object with a valid appName, userId, and sessionId. Add Event objects to the session where each event contains Content with non-empty Parts. Initialize the InMemoryMemoryService instance.
  Act: Invoke the addSessionToMemory method with the prepared session and subscribe to the returned Completable to trigger execution.
  Assert: Verify that the Completable completes successfully without errors. Check that the sessionEvents map contains an entry for the user key "appName/userId" and that the nested map contains the session ID with the filtered list of events.
Validation:
  This assertion verifies that the core functionality works correctly for the happy path scenario. It ensures that valid sessions are properly stored in the concurrent hash map structure with the correct hierarchical key structure (user key -> session ID -> events list). This is critical for the memory service to function as intended, allowing later retrieval of stored sessions.

Scenario 2: Add Session with Events Containing Empty Parts

Details:
  TestName: addSessionWithEventsContainingEmptyParts
  Description: This test checks that events with content but empty parts lists are filtered out and not stored in memory. The filtering logic should exclude events where the parts list exists but is empty.
Execution:
  Arrange: Create a Session with events where some events have Content objects with empty parts lists (parts().isPresent() returns true but parts().get().isEmpty() returns true). Create the InMemoryMemoryService instance.
  Act: Call addSessionToMemory with the session containing events with empty parts and subscribe to execute the Completable.
  Assert: Verify that the Completable completes successfully. Check that the stored events list for the session does not contain events with empty parts, confirming they were filtered out.
Validation:
  This test validates the filtering logic that prevents storage of events without meaningful content. Events with empty parts provide no value for memory retrieval and should be excluded to optimize storage and search performance. This ensures the memory service maintains data quality.

Scenario 3: Add Session with Events Having No Content

Details:
  TestName: addSessionWithEventsHavingNoContent
  Description: This test verifies that events without content (where event.content() returns Optional.empty()) are properly filtered out and not stored in the session events map.
Execution:
  Arrange: Create a Session containing Event objects where the content() method returns Optional.empty(). Initialize the InMemoryMemoryService.
  Act: Invoke addSessionToMemory with the session containing events without content and subscribe to the Completable.
  Assert: Verify successful completion of the Completable. Confirm that the events list stored for the session is empty or does not contain the events without content.
Validation:
  This assertion ensures that the filtering logic correctly handles events lacking content altogether. Such events cannot contribute to memory search functionality and should be excluded. This test validates the robustness of the Optional handling in the filter predicate.

Scenario 4: Add Session with Mixed Valid and Invalid Events

Details:
  TestName: addSessionWithMixedValidAndInvalidEvents
  Description: This test validates that when a session contains a mixture of valid events (with non-empty content and parts) and invalid events (with empty parts or no content), only the valid events are stored while invalid ones are filtered out.
Execution:
  Arrange: Create a Session with multiple events: some with valid content and non-empty parts, some with empty parts, and some with no content. Create an InMemoryMemoryService instance.
  Act: Call addSessionToMemory with the mixed-content session and subscribe to execute the operation.
  Assert: Verify that the Completable completes without error. Check that only the valid events are present in the stored events list, and the count matches the number of valid events provided.
Validation:
  This test confirms that the filtering logic works correctly in realistic scenarios where sessions may contain both valid and invalid events. It ensures data integrity by storing only meaningful events while gracefully handling and excluding invalid ones. This is important for maintaining consistent memory quality across different session types.

Scenario 5: Add Multiple Sessions for the Same User

Details:
  TestName: addMultipleSessionsForSameUser
  Description: This test verifies that multiple sessions for the same user (same appName and userId but different session IDs) are stored correctly without overwriting each other. Each session should be stored under its unique session ID within the user's map.
Execution:
  Arrange: Create multiple Session objects with the same appName and userId but different session IDs, each containing valid events. Initialize the InMemoryMemoryService.
  Act: Invoke addSessionToMemory sequentially for each session and subscribe to execute each Completable.
  Assert: Verify that all Completables complete successfully. Check that the sessionEvents map contains one entry for the user key, and the nested map contains separate entries for each session ID with their respective events.
Validation:
  This assertion validates that the concurrent hash map structure correctly maintains multiple sessions per user without data loss or overwriting. The computeIfAbsent operation should create the user map only once, and subsequent sessions should add to the existing map. This is crucial for supporting multiple conversation sessions per user.

Scenario 6: Add Sessions for Different Users

Details:
  TestName: addSessionsForDifferentUsers
  Description: This test checks that sessions for different users (different appName/userId combinations) are stored in separate entries in the sessionEvents map, ensuring proper isolation of user data.
Execution:
  Arrange: Create Session objects for different users with distinct appName and userId combinations, each with valid events. Create an InMemoryMemoryService instance.
  Act: Call addSessionToMemory for each user's session and subscribe to execute the Completables.
  Assert: Verify successful completion of all Completables. Confirm that the sessionEvents map contains separate entries for each user key, and each entry contains the correct session data.
Validation:
  This test ensures proper data isolation between users, which is critical for privacy and data integrity. The userKey method should generate unique keys for different user/app combinations, and the map structure should maintain separate storage for each. This validates the multi-tenancy capability of the memory service.

Scenario 7: Overwrite Existing Session with Same Session ID

Details:
  TestName: overwriteExistingSessionWithSameSessionId
  Description: This test verifies that adding a session with the same session ID as an existing session for the same user will overwrite the previous session's events with the new events.
Execution:
  Arrange: Create two Session objects with identical appName, userId, and sessionId but different events. Initialize the InMemoryMemoryService and add the first session.
  Act: Add the first session to memory, then add the second session with the same identifiers but different events.
  Assert: Verify both Completables complete successfully. Check that the stored events for the session ID match the second session's events, not the first, confirming the overwrite behavior.
Validation:
  This assertion validates the behavior when duplicate session IDs are encountered. The Map.put operation will replace the existing value, which may be intentional for updating session data. This test documents this behavior and ensures it works as expected, though it may indicate a need for explicit update semantics in production code.

Scenario 8: Add Session with Empty Events List

Details:
  TestName: addSessionWithEmptyEventsList
  Description: This test checks the behavior when a session with an empty events list is added to memory. The method should complete successfully and store an empty list for the session.
Execution:
  Arrange: Create a Session object with valid appName, userId, and sessionId but with an empty events list. Initialize the InMemoryMemoryService.
  Act: Invoke addSessionToMemory with the session containing no events and subscribe to the Completable.
  Assert: Verify that the Completable completes successfully. Check that an entry exists for the user key and session ID, but the events list is empty.
Validation:
  This test validates graceful handling of edge cases where sessions may be created without events. The stream filtering operation should handle empty collections correctly, resulting in an empty ImmutableList. This ensures the method doesn't fail on valid but empty input.

Scenario 9: Add Session with Null Values Handling

Details:
  TestName: addSessionCausesNullPointerExceptionWithNullSession
  Description: This test verifies the behavior when null is passed as the session parameter. Since the method doesn't explicitly handle null checks, it should throw a NullPointerException when attempting to access session methods.
Execution:
  Arrange: Initialize the InMemoryMemoryService instance. Prepare to pass null as the session parameter.
  Act: Invoke addSessionToMemory with null and subscribe to the Completable.
  Assert: Verify that the Completable terminates with a NullPointerException error. Use test observer to capture the error.
Validation:
  This test documents the current behavior when null input is provided. While the method doesn't explicitly validate input, the NullPointerException will occur when trying to call session.appName(). This test serves as documentation of the expected failure mode and may indicate a need for explicit null validation in production code.

Scenario 10: Concurrent Addition of Sessions for Same User

Details:
  TestName: concurrentAdditionOfSessionsForSameUser
  Description: This test verifies thread-safety when multiple sessions for the same user are added concurrently. The ConcurrentHashMap should handle concurrent modifications safely without data corruption or exceptions.
Execution:
  Arrange: Create multiple Session objects for the same user with different session IDs. Initialize the InMemoryMemoryService. Prepare to execute addSessionToMemory calls concurrently from multiple threads.
  Act: Invoke addSessionToMemory for multiple sessions concurrently using parallel execution or multiple threads, subscribing to all Completables.
  Assert: Verify that all Completables complete successfully without exceptions. Check that all sessions are stored correctly in the sessionEvents map with no data loss.
Validation:
  This assertion validates the thread-safety of the implementation, which is critical since ConcurrentHashMap is used. The computeIfAbsent operation should be atomic, preventing race conditions when multiple threads try to create the user map simultaneously. This test ensures the service can handle concurrent requests safely in a multi-threaded environment.

Scenario 11: Add Session with Special Characters in AppName and UserId

Details:
  TestName: addSessionWithSpecialCharactersInAppNameAndUserId
  Description: This test verifies that sessions with special characters, spaces, or unusual characters in appName and userId are handled correctly and stored with the proper user key.
Execution:
  Arrange: Create a Session with appName and userId containing special characters (e.g., "app/name", "user@id", "user id with spaces"). Initialize the InMemoryMemoryService.
  Act: Call addSessionToMemory with the session containing special characters and subscribe to execute.
  Assert: Verify successful completion. Check that the session is stored under the correct user key generated by the userKey method, which concatenates with "/".
Validation:
  This test validates that the userKey generation handles special characters correctly. Since the key format is "appName/userId", having "/" in appName could potentially cause issues with key parsing if not handled properly. This test ensures the simple concatenation approach works for various input formats, though it may reveal potential key collision issues.

Scenario 12: Add Session with Very Large Number of Events

Details:
  TestName: addSessionWithVeryLargeNumberOfEvents
  Description: This test checks the performance and correctness when adding a session with a very large number of events. The method should handle large collections efficiently without memory issues or timeouts.
Execution:
  Arrange: Create a Session containing a large number of Event objects (e.g., 10,000 events) with valid content and parts. Initialize the InMemoryMemoryService.
  Act: Invoke addSessionToMemory with the large session and subscribe to the Completable.
  Assert: Verify that the Completable completes successfully within a reasonable time. Check that all valid events are stored correctly.
Validation:
  This test validates the scalability of the method when handling large data volumes. The stream filtering and ImmutableList collection should handle large collections efficiently. This is important for real-world scenarios where sessions may accumulate many events over time. It also tests memory efficiency of the in-memory storage approach.

Scenario 13: Add Session and Verify ImmutableList Storage

Details:
  TestName: addSessionAndVerifyImmutableListStorage
  Description: This test verifies that the events are stored as an ImmutableList, ensuring that the stored collection cannot be modified after storage, maintaining data integrity.
Execution:
  Arrange: Create a Session with valid events. Initialize the InMemoryMemoryService and add the session to memory.
  Act: Add the session to memory, then retrieve the stored events list from the sessionEvents map.
  Assert: Verify that the stored events list is an instance of ImmutableList. Attempt to modify the list should throw UnsupportedOperationException.
Validation:
  This assertion ensures that the implementation correctly uses ImmutableList for storing events, preventing accidental or malicious modification of stored data. This is a defensive programming practice that maintains data integrity and prevents bugs related to shared mutable state. It validates that the collect(toImmutableList()) operation works as intended.

Scenario 14: Add Session with Events Containing Multiple Parts

Details:
  TestName: addSessionWithEventsContainingMultipleParts
  Description: This test verifies that events containing multiple parts in their content are correctly stored. All parts should be preserved in the stored event.
Execution:
  Arrange: Create a Session with events where each event's content contains multiple Part objects. Initialize the InMemoryMemoryService.
  Act: Call addSessionToMemory with the session and subscribe to execute.
  Assert: Verify successful completion. Check that the stored events maintain all parts in their content, with the correct count and content.
Validation:
  This test ensures that the filtering logic doesn't inadvertently drop or modify parts within events. The filter only checks if parts are non-empty, not the individual parts themselves. This validates that complex event structures with multiple parts are preserved correctly during storage.

Scenario 15: Verify Completable Execution is Deferred

Details:
  TestName: verifyCompletableExecutionIsDeferred
  Description: This test verifies that the Completable returned by addSessionToMemory uses deferred execution, meaning the action is not executed until subscription occurs.
Execution:
  Arrange: Create a Session with valid events. Initialize the InMemoryMemoryService.
  Act: Call addSessionToMemory but do not subscribe to the returned Completable. Check the sessionEvents map immediately.
  Assert: Verify that the sessionEvents map does not contain the session data before subscription. Then subscribe and verify the data is added after subscription.
Validation:
  This assertion validates the reactive programming contract of Completable.fromAction, which should defer execution until subscription. This is important for composing reactive chains and controlling when side effects occur. It ensures the method follows RxJava best practices and allows callers to control execution timing.

*/

// ********RoostGPT********

package com.google.adk.memory;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.events.Event;
import com.google.adk.sessions.Session;
import com.google.common.collect.ImmutableList;
import com.google.genai.types.Content;
import com.google.genai.types.Part;
import io.reactivex.rxjava3.core.Completable;
import io.reactivex.rxjava3.observers.TestObserver;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

public class InMemoryMemoryServiceAddSessionToMemoryTest {

  private InMemoryMemoryService memoryService;

  @BeforeEach
  public void setUp() {
    memoryService = new InMemoryMemoryService();
  }

  @Test
  @Tag("valid")
  public void addSessionWithValidEventsSuccessfully() {
    // Arrange
    String appName = "testApp";
    String userId = "user123";
    String sessionId = "session001";
    Part part1 = mock(Part.class);
    when(part1.text()).thenReturn(Optional.of("Hello World"));
    Content content = mock(Content.class);
    when(content.parts()).thenReturn(Optional.of(ImmutableList.of(part1)));
    Event event1 = mock(Event.class);
    when(event1.content()).thenReturn(Optional.of(content));
    Session session = mock(Session.class);
    when(session.appName()).thenReturn(appName);
    when(session.userId()).thenReturn(userId);
    when(session.id()).thenReturn(sessionId);
    when(session.events()).thenReturn(ImmutableList.of(event1));
    // Act
    Completable completable = memoryService.addSessionToMemory(session);
    TestObserver<Void> testObserver = completable.test();
    // Assert
    testObserver.assertComplete();
    testObserver.assertNoErrors();
    Map<String, List<Event>> userSessions = getSessionEventsForUser(appName, userId);
    assertNotNull(userSessions);
    assertTrue(userSessions.containsKey(sessionId));
    assertEquals(1, userSessions.get(sessionId).size());
  }

  @Test
  @Tag("valid")
  public void addSessionWithEventsContainingEmptyParts() {
    // Arrange
    String appName = "testApp";
    String userId = "user123";
    String sessionId = "session002";
    Content contentWithEmptyParts = mock(Content.class);
    when(contentWithEmptyParts.parts()).thenReturn(Optional.of(ImmutableList.of()));
    Event eventWithEmptyParts = mock(Event.class);
    when(eventWithEmptyParts.content()).thenReturn(Optional.of(contentWithEmptyParts));
    Part validPart = mock(Part.class);
    when(validPart.text()).thenReturn(Optional.of("Valid content"));
    Content validContent = mock(Content.class);
    when(validContent.parts()).thenReturn(Optional.of(ImmutableList.of(validPart)));
    Event validEvent = mock(Event.class);
    when(validEvent.content()).thenReturn(Optional.of(validContent));
    Session session = mock(Session.class);
    when(session.appName()).thenReturn(appName);
    when(session.userId()).thenReturn(userId);
    when(session.id()).thenReturn(sessionId);
    when(session.events()).thenReturn(ImmutableList.of(eventWithEmptyParts, validEvent));
    // Act
    Completable completable = memoryService.addSessionToMemory(session);
    TestObserver<Void> testObserver = completable.test();
    // Assert
    testObserver.assertComplete();
    testObserver.assertNoErrors();
    Map<String, List<Event>> userSessions = getSessionEventsForUser(appName, userId);
    assertNotNull(userSessions);
    List<Event> storedEvents = userSessions.get(sessionId);
    assertEquals(1, storedEvents.size());
    assertFalse(storedEvents.contains(eventWithEmptyParts));
  }

  @Test
  @Tag("valid")
  public void addSessionWithEventsHavingNoContent() {
    // Arrange
    String appName = "testApp";
    String userId = "user123";
    String sessionId = "session003";
    Event eventWithoutContent = mock(Event.class);
    when(eventWithoutContent.content()).thenReturn(Optional.empty());
    Session session = mock(Session.class);
    when(session.appName()).thenReturn(appName);
    when(session.userId()).thenReturn(userId);
    when(session.id()).thenReturn(sessionId);
    when(session.events()).thenReturn(ImmutableList.of(eventWithoutContent));
    // Act
    Completable completable = memoryService.addSessionToMemory(session);
    TestObserver<Void> testObserver = completable.test();
    // Assert
    testObserver.assertComplete();
    testObserver.assertNoErrors();
    Map<String, List<Event>> userSessions = getSessionEventsForUser(appName, userId);
    assertNotNull(userSessions);
    List<Event> storedEvents = userSessions.get(sessionId);
    assertTrue(storedEvents.isEmpty());
  }

  @Test
  @Tag("valid")
  public void addSessionWithMixedValidAndInvalidEvents() {
    // Arrange
    String appName = "testApp";
    String userId = "user123";
    String sessionId = "session004";
    Part validPart = mock(Part.class);
    when(validPart.text()).thenReturn(Optional.of("Valid text"));
    Content validContent = mock(Content.class);
    when(validContent.parts()).thenReturn(Optional.of(ImmutableList.of(validPart)));
    Event validEvent1 = mock(Event.class);
    when(validEvent1.content()).thenReturn(Optional.of(validContent));
    Event validEvent2 = mock(Event.class);
    when(validEvent2.content()).thenReturn(Optional.of(validContent));
    Content emptyPartsContent = mock(Content.class);
    when(emptyPartsContent.parts()).thenReturn(Optional.of(ImmutableList.of()));
    Event eventWithEmptyParts = mock(Event.class);
    when(eventWithEmptyParts.content()).thenReturn(Optional.of(emptyPartsContent));
    Event eventWithoutContent = mock(Event.class);
    when(eventWithoutContent.content()).thenReturn(Optional.empty());
    Session session = mock(Session.class);
    when(session.appName()).thenReturn(appName);
    when(session.userId()).thenReturn(userId);
    when(session.id()).thenReturn(sessionId);
    when(session.events())
        .thenReturn(
            ImmutableList.of(validEvent1, eventWithEmptyParts, validEvent2, eventWithoutContent));
    // Act
    Completable completable = memoryService.addSessionToMemory(session);
    TestObserver<Void> testObserver = completable.test();
    // Assert
    testObserver.assertComplete();
    testObserver.assertNoErrors();
    Map<String, List<Event>> userSessions = getSessionEventsForUser(appName, userId);
    assertNotNull(userSessions);
    List<Event> storedEvents = userSessions.get(sessionId);
    assertEquals(2, storedEvents.size());
    assertTrue(storedEvents.contains(validEvent1));
    assertTrue(storedEvents.contains(validEvent2));
  }

  @Test
  @Tag("valid")
  public void addMultipleSessionsForSameUser() {
    // Arrange
    String appName = "testApp";
    String userId = "user123";
    String sessionId1 = "session001";
    String sessionId2 = "session002";
    Session session1 = createValidSession(appName, userId, sessionId1);
    Session session2 = createValidSession(appName, userId, sessionId2);
    // Act
    Completable completable1 = memoryService.addSessionToMemory(session1);
    TestObserver<Void> testObserver1 = completable1.test();
    Completable completable2 = memoryService.addSessionToMemory(session2);
    TestObserver<Void> testObserver2 = completable2.test();
    // Assert
    testObserver1.assertComplete();
    testObserver1.assertNoErrors();
    testObserver2.assertComplete();
    testObserver2.assertNoErrors();
    Map<String, List<Event>> userSessions = getSessionEventsForUser(appName, userId);
    assertNotNull(userSessions);
    assertEquals(2, userSessions.size());
    assertTrue(userSessions.containsKey(sessionId1));
    assertTrue(userSessions.containsKey(sessionId2));
  }

  @Test
  @Tag("valid")
  public void addSessionsForDifferentUsers() {
    // Arrange
    String appName1 = "app1";
    String userId1 = "user1";
    String sessionId1 = "session1";
    String appName2 = "app2";
    String userId2 = "user2";
    String sessionId2 = "session2";
    Session session1 = createValidSession(appName1, userId1, sessionId1);
    Session session2 = createValidSession(appName2, userId2, sessionId2);
    // Act
    Completable completable1 = memoryService.addSessionToMemory(session1);
    TestObserver<Void> testObserver1 = completable1.test();
    Completable completable2 = memoryService.addSessionToMemory(session2);
    TestObserver<Void> testObserver2 = completable2.test();
    // Assert
    testObserver1.assertComplete();
    testObserver1.assertNoErrors();
    testObserver2.assertComplete();
    testObserver2.assertNoErrors();
    Map<String, List<Event>> userSessions1 = getSessionEventsForUser(appName1, userId1);
    Map<String, List<Event>> userSessions2 = getSessionEventsForUser(appName2, userId2);
    assertNotNull(userSessions1);
    assertNotNull(userSessions2);
    assertTrue(userSessions1.containsKey(sessionId1));
    assertTrue(userSessions2.containsKey(sessionId2));
  }

  @Test
  @Tag("valid")
  public void overwriteExistingSessionWithSameSessionId() {
    // Arrange
    String appName = "testApp";
    String userId = "user123";
    String sessionId = "session001";
    Part part1 = mock(Part.class);
    when(part1.text()).thenReturn(Optional.of("First content"));
    Content content1 = mock(Content.class);
    when(content1.parts()).thenReturn(Optional.of(ImmutableList.of(part1)));
    Event event1 = mock(Event.class);
    when(event1.content()).thenReturn(Optional.of(content1));
    Session session1 = mock(Session.class);
    when(session1.appName()).thenReturn(appName);
    when(session1.userId()).thenReturn(userId);
    when(session1.id()).thenReturn(sessionId);
    when(session1.events()).thenReturn(ImmutableList.of(event1));
    Part part2 = mock(Part.class);
    when(part2.text()).thenReturn(Optional.of("Second content"));
    Content content2 = mock(Content.class);
    when(content2.parts()).thenReturn(Optional.of(ImmutableList.of(part2)));
    Event event2 = mock(Event.class);
    when(event2.content()).thenReturn(Optional.of(content2));
    Session session2 = mock(Session.class);
    when(session2.appName()).thenReturn(appName);
    when(session2.userId()).thenReturn(userId);
    when(session2.id()).thenReturn(sessionId);
    when(session2.events()).thenReturn(ImmutableList.of(event2));
    // Act
    Completable completable1 = memoryService.addSessionToMemory(session1);
    TestObserver<Void> testObserver1 = completable1.test();
    Completable completable2 = memoryService.addSessionToMemory(session2);
    TestObserver<Void> testObserver2 = completable2.test();
    // Assert
    testObserver1.assertComplete();
    testObserver2.assertComplete();
    Map<String, List<Event>> userSessions = getSessionEventsForUser(appName, userId);
    List<Event> storedEvents = userSessions.get(sessionId);
    assertEquals(1, storedEvents.size());
    assertEquals(event2, storedEvents.get(0));
  }

  @Test
  @Tag("boundary")
  public void addSessionWithEmptyEventsList() {
    // Arrange
    String appName = "testApp";
    String userId = "user123";
    String sessionId = "session001";
    Session session = mock(Session.class);
    when(session.appName()).thenReturn(appName);
    when(session.userId()).thenReturn(userId);
    when(session.id()).thenReturn(sessionId);
    when(session.events()).thenReturn(ImmutableList.of());
    // Act
    Completable completable = memoryService.addSessionToMemory(session);
    TestObserver<Void> testObserver = completable.test();
    // Assert
    testObserver.assertComplete();
    testObserver.assertNoErrors();
    Map<String, List<Event>> userSessions = getSessionEventsForUser(appName, userId);
    assertNotNull(userSessions);
    assertTrue(userSessions.containsKey(sessionId));
    assertTrue(userSessions.get(sessionId).isEmpty());
  }

  @Test
  @Tag("invalid")
  public void addSessionCausesNullPointerExceptionWithNullSession() {
    // Arrange
    Session session = null;
    // Act
    Completable completable = memoryService.addSessionToMemory(session);
    TestObserver<Void> testObserver = completable.test();
    // Assert
    testObserver.assertError(NullPointerException.class);
  }

  @Test
  @Tag("integration")
  public void concurrentAdditionOfSessionsForSameUser() throws InterruptedException {
    // Arrange
    String appName = "testApp";
    String userId = "user123";
    int numberOfSessions = 10;
    ExecutorService executorService = Executors.newFixedThreadPool(5);
    CountDownLatch latch = new CountDownLatch(numberOfSessions);
    // Act
    for (int i = 0; i < numberOfSessions; i++) {
      String sessionId = "session" + i;
      Session session = createValidSession(appName, userId, sessionId);
      executorService.submit(
          () -> {
            try {
              Completable completable = memoryService.addSessionToMemory(session);
              completable.blockingAwait();
            } finally {
              latch.countDown();
            }
          });
    }
    latch.await(10, TimeUnit.SECONDS);
    executorService.shutdown();
    // Assert
    Map<String, List<Event>> userSessions = getSessionEventsForUser(appName, userId);
    assertNotNull(userSessions);
    assertEquals(numberOfSessions, userSessions.size());
  }

  @Test
  @Tag("valid")
  public void addSessionWithSpecialCharactersInAppNameAndUserId() {
    // Arrange
    String appName = "app/name@special";
    String userId = "user id with spaces";
    String sessionId = "session001";
    Session session = createValidSession(appName, userId, sessionId);
    // Act
    Completable completable = memoryService.addSessionToMemory(session);
    TestObserver<Void> testObserver = completable.test();
    // Assert
    testObserver.assertComplete();
    testObserver.assertNoErrors();
    Map<String, List<Event>> userSessions = getSessionEventsForUser(appName, userId);
    assertNotNull(userSessions);
    assertTrue(userSessions.containsKey(sessionId));
  }

  @Test
  @Tag("valid")
  public void addSessionWithVeryLargeNumberOfEvents() {
    // Arrange
    String appName = "testApp";
    String userId = "user123";
    String sessionId = "session001";
    int numberOfEvents = 10000;
    List<Event> events = new ArrayList<>();
    for (int i = 0; i < numberOfEvents; i++) {
      Part part = mock(Part.class);
      when(part.text()).thenReturn(Optional.of("Content " + i));
      Content content = mock(Content.class);
      when(content.parts()).thenReturn(Optional.of(ImmutableList.of(part)));
      Event event = mock(Event.class);
      when(event.content()).thenReturn(Optional.of(content));
      events.add(event);
    }
    Session session = mock(Session.class);
    when(session.appName()).thenReturn(appName);
    when(session.userId()).thenReturn(userId);
    when(session.id()).thenReturn(sessionId);
    when(session.events()).thenReturn(ImmutableList.copyOf(events));
    // Act
    Completable completable = memoryService.addSessionToMemory(session);
    TestObserver<Void> testObserver = completable.test();
    // Assert
    testObserver.assertComplete();
    testObserver.assertNoErrors();
    Map<String, List<Event>> userSessions = getSessionEventsForUser(appName, userId);
    assertNotNull(userSessions);
    assertEquals(numberOfEvents, userSessions.get(sessionId).size());
  }

  @Test
  @Tag("valid")
  public void addSessionAndVerifyImmutableListStorage() {
    // Arrange
    String appName = "testApp";
    String userId = "user123";
    String sessionId = "session001";
    Session session = createValidSession(appName, userId, sessionId);
    // Act
    Completable completable = memoryService.addSessionToMemory(session);
    completable.blockingAwait();
    // Assert
    Map<String, List<Event>> userSessions = getSessionEventsForUser(appName, userId);
    List<Event> storedEvents = userSessions.get(sessionId);
    assertTrue(storedEvents instanceof ImmutableList);
    assertThrows(
        UnsupportedOperationException.class,
        () -> {
          storedEvents.add(mock(Event.class));
        });
  }

  @Test
  @Tag("valid")
  public void addSessionWithEventsContainingMultipleParts() {
    // Arrange
    String appName = "testApp";
    String userId = "user123";
    String sessionId = "session001";
    Part part1 = mock(Part.class);
    when(part1.text()).thenReturn(Optional.of("Part 1"));
    Part part2 = mock(Part.class);
    when(part2.text()).thenReturn(Optional.of("Part 2"));
    Part part3 = mock(Part.class);
    when(part3.text()).thenReturn(Optional.of("Part 3"));
    Content content = mock(Content.class);
    when(content.parts()).thenReturn(Optional.of(ImmutableList.of(part1, part2, part3)));
    Event event = mock(Event.class);
    when(event.content()).thenReturn(Optional.of(content));
    Session session = mock(Session.class);
    when(session.appName()).thenReturn(appName);
    when(session.userId()).thenReturn(userId);
    when(session.id()).thenReturn(sessionId);
    when(session.events()).thenReturn(ImmutableList.of(event));
    // Act
    Completable completable = memoryService.addSessionToMemory(session);
    TestObserver<Void> testObserver = completable.test();
    // Assert
    testObserver.assertComplete();
    testObserver.assertNoErrors();
    Map<String, List<Event>> userSessions = getSessionEventsForUser(appName, userId);
    List<Event> storedEvents = userSessions.get(sessionId);
    assertEquals(1, storedEvents.size());
    Event storedEvent = storedEvents.get(0);
    assertTrue(storedEvent.content().isPresent());
    assertTrue(storedEvent.content().get().parts().isPresent());
    assertEquals(3, storedEvent.content().get().parts().get().size());
  }

  @Test
  @Tag("valid")
  public void verifyCompletableExecutionIsDeferred() {
    // Arrange
    String appName = "testApp";
    String userId = "user123";
    String sessionId = "session001";
    Session session = createValidSession(appName, userId, sessionId);
    // Act - Create Completable but don't subscribe
    Completable completable = memoryService.addSessionToMemory(session);
    // Assert - Verify data is not added before subscription
    Map<String, List<Event>> userSessionsBefore = getSessionEventsForUser(appName, userId);
    assertNull(userSessionsBefore);
    // Now subscribe
    completable.blockingAwait();
    // Assert - Verify data is added after subscription
    Map<String, List<Event>> userSessionsAfter = getSessionEventsForUser(appName, userId);
    assertNotNull(userSessionsAfter);
    assertTrue(userSessionsAfter.containsKey(sessionId));
  }

  // Helper methods
  private Session createValidSession(String appName, String userId, String sessionId) {
    Part part = mock(Part.class);
    when(part.text()).thenReturn(Optional.of("Test content"));
    Content content = mock(Content.class);
    when(content.parts()).thenReturn(Optional.of(ImmutableList.of(part)));
    Event event = mock(Event.class);
    when(event.content()).thenReturn(Optional.of(content));
    Session session = mock(Session.class);
    when(session.appName()).thenReturn(appName);
    when(session.userId()).thenReturn(userId);
    when(session.id()).thenReturn(sessionId);
    when(session.events()).thenReturn(ImmutableList.of(event));
    return session;
  }

  private Map<String, List<Event>> getSessionEventsForUser(String appName, String userId) {
    try {
      java.lang.reflect.Field field = InMemoryMemoryService.class.getDeclaredField("sessionEvents");
      field.setAccessible(true);
      @SuppressWarnings("unchecked")
      Map<String, Map<String, List<Event>>> sessionEvents =
          (Map<String, Map<String, List<Event>>>) field.get(memoryService);
      return sessionEvents.get(appName + "/" + userId);
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }
}
