/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-maven-adk_clone using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=searchMemory_5b46a62b19
ROOST_METHOD_SIG_HASH=searchMemory_2ebd5f3610

Scenario 1: Search Memory When User Has No Sessions

Details:
  TestName: searchMemoryReturnsEmptyResponseWhenUserHasNoSessions
  Description: This test verifies that when searching for memories for a user who has no stored sessions in the sessionEvents map, the method returns an empty SearchMemoryResponse. This ensures the method handles the case where a user key does not exist in the map.

Execution:
  Arrange: Create an instance of InMemoryMemoryService with an empty sessionEvents map. Prepare valid appName, userId, and query parameters.
  Act: Invoke searchMemory() with the appName, userId, and query string.
  Assert: Verify that the returned Single emits a SearchMemoryResponse with an empty or null memories list.

Validation:
  The assertion verifies that the method correctly handles the absence of user data by returning an empty response rather than throwing an exception or returning null. This is important for graceful handling of new users or users with no memory history, preventing null pointer exceptions in downstream processing.

---

Scenario 2: Search Memory With Matching Single Word Query

Details:
  TestName: searchMemoryReturnsMatchingMemoriesForSingleWordQuery
  Description: This test validates that when a user has stored events containing text that matches a single-word query, the method correctly identifies and returns those matching memories. It tests the basic keyword matching functionality.

Execution:
  Arrange: Create an InMemoryMemoryService instance. Add a session with events containing text parts with specific words (e.g., "hello world"). Prepare a query with a single word that exists in the event text (e.g., "hello").
  Act: Call searchMemory() with the appropriate appName, userId, and the single-word query.
  Assert: Verify that the returned SearchMemoryResponse contains the expected MemoryEntry objects with matching content, correct author, and properly formatted timestamp.

Validation:
  This assertion confirms that the word extraction using WORD_PATTERN and the keyword matching logic using Collections.disjoint() works correctly for simple cases. It validates that the method can successfully match query words against event content and construct proper MemoryEntry objects with all required fields.

---

Scenario 3: Search Memory With Multi-Word Query Matching Multiple Events

Details:
  TestName: searchMemoryReturnsAllMatchingMemoriesForMultiWordQuery
  Description: This test ensures that when a query contains multiple words and multiple events contain at least one of those words, all matching events are returned in the response. It validates the OR-based matching behavior.

Execution:
  Arrange: Set up InMemoryMemoryService with multiple events in a session, where different events contain different words from the query. For example, Event 1 contains "apple", Event 2 contains "banana", and the query is "apple banana orange".
  Act: Execute searchMemory() with the multi-word query.
  Assert: Verify that the response contains MemoryEntry objects for both Event 1 and Event 2, confirming that any word match results in inclusion.

Validation:
  This test validates that the method uses an OR logic (not AND) when matching multiple query words, as implemented by Collections.disjoint(). It ensures comprehensive memory retrieval when users search with multiple keywords, which is crucial for flexible search functionality.

---

Scenario 4: Search Memory With No Matching Words

Details:
  TestName: searchMemoryReturnsEmptyResponseWhenNoWordsMatch
  Description: This test verifies that when a query contains words that do not appear in any stored event content, the method returns an empty SearchMemoryResponse, indicating no matches were found.

Execution:
  Arrange: Create an InMemoryMemoryService with events containing specific text (e.g., "cat dog"). Prepare a query with completely different words (e.g., "elephant giraffe").
  Act: Invoke searchMemory() with the non-matching query.
  Assert: Confirm that the returned SearchMemoryResponse has an empty memories list.

Validation:
  This assertion ensures that the keyword matching logic correctly identifies when there are no overlapping words between the query and event content. It prevents false positives and ensures search accuracy, which is essential for user trust in the search functionality.

---

Scenario 5: Search Memory With Case Insensitive Matching

Details:
  TestName: searchMemoryMatchesWordsIgnoringCase
  Description: This test validates that the search is case-insensitive, meaning queries with different casing (uppercase, lowercase, mixed) will match event content regardless of the original case.

Execution:
  Arrange: Set up InMemoryMemoryService with events containing text in mixed case (e.g., "Hello World"). Create a query with different casing (e.g., "HELLO", "world", or "WoRlD").
  Act: Call searchMemory() with the differently-cased query.
  Assert: Verify that the response contains the matching MemoryEntry, confirming case-insensitive matching.

Validation:
  This test confirms that the toLowerCase(Locale.ROOT) conversion is applied consistently to both query words and event text words, ensuring users can search without worrying about case sensitivity. This improves user experience and search reliability.

---

Scenario 6: Search Memory With Empty Query String

Details:
  TestName: searchMemoryHandlesEmptyQueryString
  Description: This test checks the behavior when an empty string is provided as the query parameter. It ensures the method handles this edge case gracefully.

Execution:
  Arrange: Create an InMemoryMemoryService with stored events. Prepare an empty string as the query parameter.
  Act: Execute searchMemory() with the empty query string.
  Assert: Verify that the method returns an empty SearchMemoryResponse or handles the empty query appropriately without throwing exceptions.

Validation:
  This assertion validates that the method can handle edge cases like empty queries. Since split("\\s+") on an empty string produces an array with one empty element, the test ensures this doesn't cause unexpected matches or errors, maintaining robustness.

---

Scenario 7: Search Memory With Query Containing Only Whitespace

Details:
  TestName: searchMemoryHandlesWhitespaceOnlyQuery
  Description: This test verifies the method's behavior when the query consists only of whitespace characters (spaces, tabs, etc.).

Execution:
  Arrange: Set up InMemoryMemoryService with events. Create a query string containing only whitespace (e.g., "   ", "\t\t").
  Act: Invoke searchMemory() with the whitespace-only query.
  Assert: Confirm that the method returns an empty SearchMemoryResponse without errors.

Validation:
  This test ensures that whitespace-only queries are handled gracefully. The split operation will produce empty strings, and the matching logic should not find any matches, preventing false positives and ensuring data integrity.

---

Scenario 8: Search Memory With Events Having Empty Content

Details:
  TestName: searchMemorySkipsEventsWithEmptyContent
  Description: This test validates that events with empty content (where event.content().isEmpty() returns true) are correctly skipped during the search process.

Execution:
  Arrange: Create an InMemoryMemoryService with a mix of events, some with content and some with empty content. Prepare a query that would match the non-empty events.
  Act: Call searchMemory() with the query.
  Assert: Verify that only events with non-empty content are included in the results, and empty content events are skipped.

Validation:
  This assertion confirms that the early-continue logic for empty content works correctly, preventing null pointer exceptions and ensuring only valid events are processed. This is critical for data consistency and error prevention.

---

Scenario 9: Search Memory With Events Having Empty Parts List

Details:
  TestName: searchMemorySkipsEventsWithEmptyPartsList
  Description: This test ensures that events where the parts list is empty (event.content().get().parts().isEmpty() returns true) are properly skipped during search.

Execution:
  Arrange: Set up InMemoryMemoryService with events that have content but empty parts lists. Include other events with valid parts for comparison.
  Act: Execute searchMemory() with a relevant query.
  Assert: Confirm that events with empty parts lists are excluded from the results.

Validation:
  This test validates the second early-continue condition, ensuring that events without actual text parts don't cause processing errors or appear in results. It maintains the integrity of search results by only including events with actual content.

---

Scenario 10: Search Memory With Parts Having Null or Empty Text

Details:
  TestName: searchMemorySkipsPartsWithNullOrEmptyText
  Description: This test verifies that parts within events that have null or empty text (checked by Strings.isNullOrEmpty()) are correctly skipped during word extraction.

Execution:
  Arrange: Create an InMemoryMemoryService with events containing parts where some have valid text and others have null or empty text. Prepare a query matching the valid text.
  Act: Invoke searchMemory() with the query.
  Assert: Verify that only parts with valid text contribute to the matching logic, and null/empty text parts don't cause errors.

Validation:
  This assertion ensures robust handling of incomplete or malformed data. By skipping null or empty text parts, the method prevents null pointer exceptions and ensures only meaningful content is searched, improving reliability.

---

Scenario 11: Search Memory With Events Having No Extractable Words

Details:
  TestName: searchMemorySkipsEventsWithNoExtractableWords
  Description: This test validates that events containing text but no extractable words (e.g., only numbers or special characters) are skipped when wordsInEvent is empty.

Execution:
  Arrange: Set up InMemoryMemoryService with events containing text like "123 !@# $$$" that produces no matches with WORD_PATTERN. Include a query with actual words.
  Act: Call searchMemory() with the query.
  Assert: Confirm that events with no extractable words are excluded from results.

Validation:
  This test ensures that the WORD_PATTERN regex ([A-Za-z]+) correctly filters out non-alphabetic content and that the isEmpty() check on wordsInEvent prevents these events from being included. This maintains search quality by focusing on actual textual content.

---

Scenario 12: Search Memory Across Multiple Sessions

Details:
  TestName: searchMemorySearchesAcrossAllUserSessions
  Description: This test verifies that the search functionality examines events across all sessions belonging to a user, not just a single session.

Execution:
  Arrange: Create an InMemoryMemoryService and add multiple sessions for the same user (same appName and userId), each containing different events with different text. Prepare a query that matches events in different sessions.
  Act: Execute searchMemory() with the query.
  Assert: Verify that the response contains MemoryEntry objects from multiple sessions, confirming cross-session search.

Validation:
  This assertion validates that the nested loop structure (iterating over userSessions.values() and then eventsInSession) correctly searches all sessions. This is crucial for comprehensive memory retrieval, ensuring users can find relevant information regardless of which session it was stored in.

---

Scenario 13: Search Memory With Special Characters in Query

Details:
  TestName: searchMemoryHandlesSpecialCharactersInQuery
  Description: This test checks how the method handles queries containing special characters, numbers, or punctuation, ensuring they don't cause errors or unexpected behavior.

Execution:
  Arrange: Set up InMemoryMemoryService with events containing regular text. Create a query with special characters (e.g., "hello! @world# 123").
  Act: Invoke searchMemory() with the special character query.
  Assert: Verify that the method processes the query without errors, and only alphabetic words are used for matching (since split("\\s+") preserves special characters but WORD_PATTERN only matches alphabetic sequences).

Validation:
  This test ensures that the query processing is robust against various input formats. Since the query is split by whitespace but event words are extracted using WORD_PATTERN, the test validates that this asymmetry is handled correctly and doesn't cause matching issues.

---

Scenario 14: Search Memory With Multiple Parts in Single Event

Details:
  TestName: searchMemoryExtractsWordsFromAllPartsInEvent
  Description: This test validates that when an event contains multiple parts, words are extracted from all parts and used for matching.

Execution:
  Arrange: Create an InMemoryMemoryService with an event containing multiple parts, each with different text (e.g., Part 1: "hello", Part 2: "world"). Prepare a query matching words from different parts.
  Act: Call searchMemory() with a query like "hello" or "world".
  Assert: Confirm that the event is matched regardless of which part contains the matching word.

Validation:
  This assertion verifies that the inner loop iterating over parts correctly aggregates all words from all parts into the wordsInEvent set. This ensures comprehensive matching within events and prevents missing matches due to multi-part content structure.

---

Scenario 15: Search Memory Verifies Timestamp Formatting

Details:
  TestName: searchMemoryFormatsTimestampCorrectly
  Description: This test ensures that the timestamp in returned MemoryEntry objects is correctly formatted using the formatTimestamp() method, converting epoch seconds to ISO-8601 format.

Execution:
  Arrange: Set up InMemoryMemoryService with events having known timestamps (e.g., 1609459200L for 2021-01-01T00:00:00Z). Add a query that matches these events.
  Act: Execute searchMemory() with the matching query.
  Assert: Verify that the MemoryEntry objects in the response have timestamps in the expected ISO-8601 string format.

Validation:
  This test validates that the formatTimestamp() method is correctly invoked and produces the expected output format. Proper timestamp formatting is essential for displaying memory entries to users in a readable format and for any time-based sorting or filtering operations.

---

Scenario 16: Search Memory Preserves Event Author Information

Details:
  TestName: searchMemoryPreservesAuthorInformation
  Description: This test verifies that the author information from the original event is correctly preserved in the returned MemoryEntry objects.

Execution:
  Arrange: Create an InMemoryMemoryService with events having specific author values. Prepare a query that matches these events.
  Act: Invoke searchMemory() with the query.
  Assert: Confirm that the MemoryEntry objects in the response contain the correct author information matching the original events.

Validation:
  This assertion ensures that the MemoryEntry.builder() correctly includes the event.author() value. Preserving author information is crucial for multi-user contexts where knowing who created the memory is important for context and attribution.

---

Scenario 17: Search Memory Preserves Event Content

Details:
  TestName: searchMemoryPreservesCompleteEventContent
  Description: This test validates that the complete content object from the matching event is preserved in the returned MemoryEntry, not just the matched words.

Execution:
  Arrange: Set up InMemoryMemoryService with events containing rich content objects with multiple parts. Create a query matching one word in the content.
  Act: Call searchMemory() with the query.
  Assert: Verify that the returned MemoryEntry contains the complete original content object, including all parts and their full text.

Validation:
  This test ensures that the method returns complete memory entries, not just snippets or matched portions. This is important for providing full context to users when they retrieve memories, allowing them to see the complete information rather than just fragments.

---

Scenario 18: Search Memory With Duplicate Words in Query

Details:
  TestName: searchMemoryHandlesDuplicateWordsInQuery
  Description: This test checks the behavior when the query contains duplicate words, ensuring they don't cause issues or affect matching logic.

Execution:
  Arrange: Create an InMemoryMemoryService with events. Prepare a query with duplicate words (e.g., "hello hello world world").
  Act: Execute searchMemory() with the duplicate-word query.
  Assert: Verify that the method processes the query correctly, and duplicates don't cause multiple matches or errors (since ImmutableSet.copyOf() removes duplicates).

Validation:
  This assertion validates that using ImmutableSet for wordsInQuery automatically handles duplicates, ensuring clean and efficient matching. This prevents redundant processing and ensures consistent behavior regardless of query formatting.

---

Scenario 19: Search Memory With Very Long Query

Details:
  TestName: searchMemoryHandlesVeryLongQuery
  Description: This test verifies that the method can handle queries with a large number of words without performance degradation or errors.

Execution:
  Arrange: Set up InMemoryMemoryService with events. Create a query string containing hundreds of words.
  Act: Invoke searchMemory() with the very long query.
  Assert: Confirm that the method completes successfully and returns appropriate results without timeout or memory errors.

Validation:
  This test ensures scalability and robustness when handling edge cases of query length. It validates that the data structures (ImmutableSet, HashSet) and algorithms (Collections.disjoint()) can handle large inputs efficiently, which is important for production reliability.

---

Scenario 20: Search Memory Returns Results in Correct Order

Details:
  TestName: searchMemoryReturnsResultsInSessionAndEventOrder
  Description: This test validates that matching memories are returned in the order they are encountered when iterating through sessions and events.

Execution:
  Arrange: Create an InMemoryMemoryService with multiple sessions and events in a specific order. Prepare a query that matches multiple events.
  Act: Call searchMemory() with the query.
  Assert: Verify that the order of MemoryEntry objects in the response matches the iteration order of sessions and events.

Validation:
  This assertion confirms that the method maintains a predictable ordering based on the iteration order of the underlying map structures. While ConcurrentHashMap doesn't guarantee order, the test validates that the method doesn't introduce random reordering, which is important for consistent user experience.

---

Scenario 21: Search Memory With Word Boundaries

Details:
  TestName: searchMemoryMatchesCompleteWordsOnly
  Description: This test ensures that the WORD_PATTERN regex matches complete words only, not partial matches within larger words.

Execution:
  Arrange: Set up InMemoryMemoryService with events containing words like "hello" and "helloworld". Create a query for "hello".
  Act: Execute searchMemory() with the query.
  Assert: Verify that both "hello" and "helloworld" are matched, since WORD_PATTERN extracts "hello" and "helloworld" as separate words, and the query word "hello" matches the extracted word "hello" but not as a substring of "helloworld".

Validation:
  This test validates the word extraction behavior of WORD_PATTERN, ensuring it extracts complete alphabetic sequences. Understanding this behavior is crucial for setting correct expectations about search matching and ensuring the search behaves as designed.

---

Scenario 22: Search Memory With Multiple Users

Details:
  TestName: searchMemoryIsolatesResultsByUser
  Description: This test verifies that search results are properly isolated by user, ensuring one user's search doesn't return another user's memories.

Execution:
  Arrange: Create an InMemoryMemoryService with sessions for multiple users (different userId values) under the same or different appName. Each user has events with distinct content. Prepare a query that would match events from multiple users.
  Act: Invoke searchMemory() for a specific user with the query.
  Assert: Confirm that the response contains only MemoryEntry objects from the specified user's sessions, not from other users.

Validation:
  This assertion ensures that the userKey() method correctly isolates data by user, and the search respects user boundaries. This is critical for data privacy and security, preventing information leakage between users.

---

Scenario 23: Search Memory With Multiple Applications

Details:
  TestName: searchMemoryIsolatesResultsByApplication
  Description: This test validates that search results are properly isolated by application, ensuring searches within one app don't return memories from another app.

Execution:
  Arrange: Set up InMemoryMemoryService with sessions for the same userId but different appName values. Each app has events with distinct content. Create a query matching events in multiple apps.
  Act: Call searchMemory() for a specific appName and userId combination.
  Assert: Verify that only memories from the specified application are returned, not from other applications.

Validation:
  This test confirms that the userKey() method correctly incorporates appName for data isolation. This is essential for multi-tenant scenarios where the same service supports multiple applications, ensuring data segregation and preventing cross-application data access.

---

Scenario 24: Search Memory Returns Immutable Response

Details:
  TestName: searchMemoryReturnsImmutableMemoriesList
  Description: This test verifies that the memories list in the returned SearchMemoryResponse is immutable, preventing external modification.

Execution:
  Arrange: Create an InMemoryMemoryService with matching events. Prepare a query that returns results.
  Act: Execute searchMemory() and obtain the SearchMemoryResponse.
  Assert: Verify that the memories list is an ImmutableList by attempting to modify it and confirming an UnsupportedOperationException is thrown, or by checking its type.

Validation:
  This assertion ensures that using ImmutableList.copyOf() creates a truly immutable collection, protecting the internal state from external modification. This is important for thread safety and preventing unintended side effects in concurrent environments.

---

Scenario 25: Search Memory With Null AppName

Details:
  TestName: searchMemoryHandlesNullAppName
  Description: This test checks the method's behavior when null is passed as the appName parameter.

Execution:
  Arrange: Create an InMemoryMemoryService instance. Prepare null as appName, with valid userId and query.
  Act: Invoke searchMemory() with null appName.
  Assert: Verify that the method either handles null gracefully (returning empty response) or throws an appropriate exception, depending on the expected contract.

Validation:
  This test validates error handling for invalid input. Since userKey() concatenates appName with "/", a null appName would cause a NullPointerException. The test ensures this edge case is understood and handled appropriately, either through validation or documented behavior.

---

Scenario 26: Search Memory With Null UserId

Details:
  TestName: searchMemoryHandlesNullUserId
  Description: This test verifies the method's behavior when null is passed as the userId parameter.

Execution:
  Arrange: Set up InMemoryMemoryService. Prepare valid appName, null userId, and valid query.
  Act: Call searchMemory() with null userId.
  Assert: Confirm appropriate handling, either graceful degradation or exception throwing.

Validation:
  Similar to the null appName test, this validates handling of null userId. The userKey() method would encounter a NullPointerException, so this test ensures the behavior is predictable and documented, helping developers understand the method's contract.

---

Scenario 27: Search Memory With Null Query

Details:
  TestName: searchMemoryHandlesNullQuery
  Description: This test checks how the method handles a null query parameter.

Execution:
  Arrange: Create an InMemoryMemoryService with events. Prepare valid appName and userId, but null query.
  Act: Execute searchMemory() with null query.
  Assert: Verify that the method either throws a NullPointerException or handles null gracefully, depending on the expected behavior.

Validation:
  This test validates input validation for the query parameter. Since query.toLowerCase() would throw NullPointerException on null, the test ensures this edge case is understood. Proper null handling is crucial for robust API design and preventing runtime errors.

---

Scenario 28: Search Memory With Reactive Single Behavior

Details:
  TestName: searchMemoryReturnsProperReactiveSingle
  Description: This test verifies that the method returns a proper RxJava Single that emits exactly one item and completes.

Execution:
  Arrange: Set up InMemoryMemoryService with or without matching events. Prepare valid search parameters.
  Act: Invoke searchMemory() and subscribe to the returned Single.
  Assert: Verify that the Single emits exactly one SearchMemoryResponse and then completes, without errors (in the success case).

Validation:
  This assertion ensures that the reactive contract is properly implemented. Single.fromCallable() should emit one value and complete, which is critical for reactive stream processing and integration with reactive frameworks. This test validates the asynchronous behavior.

---

Scenario 29: Search Memory With Concurrent Access

Details:
  TestName: searchMemoryHandlesConcurrentAccess
  Description: This test validates that the method can handle concurrent search requests safely, given that sessionEvents is a ConcurrentHashMap.

Execution:
  Arrange: Create an InMemoryMemoryService with events. Prepare multiple threads that will simultaneously call searchMemory() with the same or different parameters.
  Act: Execute searchMemory() from multiple threads concurrently.
  Assert: Verify that all searches complete successfully without ConcurrentModificationException or data corruption, and each returns correct results.

Validation:
  This test ensures thread safety of the search operation. Since ConcurrentHashMap is used for sessionEvents, concurrent reads should be safe. This is crucial for production environments where multiple users may search simultaneously, validating that the implementation is production-ready.

---

Scenario 30: Search Memory With Unicode Characters in Event Text

Details:
  TestName: searchMemoryHandlesUnicodeCharactersInEventText
  Description: This test verifies how the method handles events containing Unicode characters, emojis, or non-ASCII text.

Execution:
  Arrange: Set up InMemoryMemoryService with events containing Unicode text (e.g., "hello 世界 🌍"). Create a query with ASCII words.
  Act: Call searchMemory() with the query.
  Assert: Verify that the method processes the Unicode text without errors, and WORD_PATTERN correctly extracts only ASCII alphabetic words.

Validation:
  This assertion validates that the WORD_PATTERN regex ([A-Za-z]+) only matches ASCII letters, effectively filtering out Unicode characters. This test ensures the method behaves predictably with international text and doesn't crash or produce unexpected results with non-ASCII input.

---

Scenario 31: Search Memory With Locale-Specific Lowercase Conversion

Details:
  TestName: searchMemoryUsesRootLocaleForLowercaseConversion
  Description: This test verifies that the method uses Locale.ROOT for lowercase conversion, ensuring consistent behavior across different system locales.

Execution:
  Arrange: Create an InMemoryMemoryService with events containing text with locale-sensitive characters (e.g., Turkish "I" which lowercases differently in Turkish locale). Prepare a matching query.
  Act: Execute searchMemory() with the query.
  Assert: Verify that matching uses Locale.ROOT consistently, producing predictable results regardless of system locale.

Validation:
  This test ensures that using Locale.ROOT prevents locale-specific bugs, such as the Turkish "I" problem. Consistent locale handling is critical for international applications, ensuring search behaves the same way for all users regardless of their system settings.

---

Scenario 32: Search Memory With Empty Session Events Map

Details:
  TestName: searchMemoryHandlesEmptySessionEventsMap
  Description: This test validates behavior when the sessionEvents map is completely empty (no users have any sessions).

Execution:
  Arrange: Create a new InMemoryMemoryService instance without adding any sessions. Prepare valid search parameters.
  Act: Invoke searchMemory() with any appName, userId, and query.
  Assert: Confirm that the method returns an empty SearchMemoryResponse without errors.

Validation:
  This assertion ensures that the containsKey() check correctly handles the case where no data exists yet. This is important for new deployments or after data clearing, ensuring the service remains functional even with no stored data.

---

Scenario 33: Search Memory With Query Containing Only Non-Alphabetic Characters

Details:
  TestName: searchMemoryHandlesNonAlphabeticQuery
  Description: This test checks behavior when the query contains only numbers, special characters, or punctuation with no alphabetic words.

Execution:
  Arrange: Set up InMemoryMemoryService with events containing regular text. Create a query like "123 !@# $%^".
  Act: Call searchMemory() with the non-alphabetic query.
  Assert: Verify that the method returns an empty response since no alphabetic words can be extracted from the query for matching.

Validation:
  This test validates that the query processing correctly handles edge cases where split("\\s+") produces tokens but none are alphabetic words. Since event words are extracted using WORD_PATTERN (alphabetic only), no matches should occur, ensuring consistent behavior.

---

Scenario 34: Search Memory Validates MemoryEntry Builder Usage

Details:
  TestName: searchMemoryBuildsMemoryEntryWithAllRequiredFields
  Description: This test ensures that MemoryEntry objects are built with all required fields (content, author, timestamp) properly populated.

Execution:
  Arrange: Create an InMemoryMemoryService with events having all fields populated. Prepare a matching query.
  Act: Execute searchMemory() and retrieve the MemoryEntry objects.
  Assert: Verify that each MemoryEntry has non-null content, author, and timestamp fields with correct values.

Validation:
  This assertion validates that the MemoryEntry.builder() is used correctly with all necessary fields. Complete memory entries are essential for proper display and processing of search results, ensuring users receive all relevant information about each memory.

---

Scenario 35: Search Memory With Mixed Case Words in Event Text

Details:
  TestName: searchMemoryNormalizesEventTextCase
  Description: This test verifies that words extracted from event text are normalized to lowercase for matching, ensuring case-insensitive comparison.

Execution:
  Arrange: Set up InMemoryMemoryService with events containing mixed-case text (e.g., "HeLLo WoRLd"). Create a lowercase query (e.g., "hello").
  Act: Invoke searchMemory() with the lowercase query.
  Assert: Confirm that the mixed-case event text matches the lowercase query, validating case normalization.

Validation:
  This test ensures that toLowerCase(Locale.ROOT) is applied to words extracted from event text via WORD_PATTERN, enabling case-insensitive matching. This is crucial for user-friendly search where users shouldn't need to match the exact case of stored content.

---

Scenario 36: Search Memory With Partial Word in Query

Details:
  TestName: searchMemoryDoesNotMatchPartialWords
  Description: This test validates that partial words in the query don't match complete words in events (e.g., "hel" doesn't match "hello").

Execution:
  Arrange: Create an InMemoryMemoryService with events containing complete words like "hello". Prepare a query with a partial word like "hel".
  Act: Call searchMemory() with the partial word query.
  Assert: Verify that no matches are found, confirming that only complete word matches are supported.

Validation:
  This assertion ensures that the matching logic uses exact word comparison (via Collections.disjoint() on sets of complete words), not substring matching. This prevents false positives and ensures search precision, which is important for accurate memory retrieval.

---

Scenario 37: Search Memory Performance With Large Number of Events

Details:
  TestName: searchMemoryPerformsEfficientlyWithManyEvents
  Description: This test validates that the search method performs reasonably well even with a large number of stored events across multiple sessions.

Execution:
  Arrange: Set up InMemoryMemoryService with thousands of events across multiple sessions. Prepare a query that matches some events.
  Act: Execute searchMemory() and measure execution time.
  Assert: Verify that the search completes within acceptable time limits and returns correct results.

Validation:
  This test ensures scalability and performance characteristics of the search implementation. While in-memory keyword search is not optimized for large datasets, the test validates that the algorithm doesn't have obvious performance issues and can handle realistic data volumes.

---

Scenario 38: Search Memory With Empty String in Parts Text

Details:
  TestName: searchMemorySkipsEmptyStringInPartsText
  Description: This test verifies that parts with empty string text (not null, but "") are correctly handled by the Strings.isNullOrEmpty() check.

Execution:
  Arrange: Create an InMemoryMemoryService with events containing parts where some have empty string text (""). Include other parts with valid text.
  Act: Invoke searchMemory() with a query matching the valid text.
  Assert: Confirm that empty string parts are skipped and don't contribute to matching or cause errors.

Validation:
  This assertion validates that Strings.isNullOrEmpty() correctly identifies both null and empty strings, ensuring robust handling of incomplete data. This prevents processing of meaningless parts and ensures only substantive content is searched.

---

Scenario 39: Search Memory Returns New ArrayList Instance

Details:
  TestName: searchMemoryCreatesNewMatchingMemoriesList
  Description: This test verifies that each search creates a new ArrayList for matchingMemories, ensuring result isolation between searches.

Execution:
  Arrange: Set up InMemoryMemoryService with events. Perform multiple searches with different queries.
  Act: Execute searchMemory() multiple times.
  Assert: Verify that each search returns a distinct list instance, confirming no shared state between searches.

Validation:
  This test ensures that the method is stateless and thread-safe regarding result collection. Creating a new ArrayList for each search prevents cross-contamination of results and ensures each search is independent, which is critical for correctness in concurrent environments.

---

Scenario 40: Search Memory With Word Pattern Matching Behavior

Details:
  TestName: searchMemoryExtractsWordsUsingCorrectPattern
  Description: This test validates that the WORD_PATTERN regex ([A-Za-z]+) correctly extracts only sequences of alphabetic characters from event text.

Execution:
  Arrange: Create an InMemoryMemoryService with events containing text with mixed content: "hello123world test-case under_score". Prepare a query with "hello", "world", "test", "case", "under", or "score".
  Act: Call searchMemory() with the query.
  Assert: Verify that words are extracted as expected: "hello", "world", "test", "case", "under", "score" (numbers and special characters act as separators).

Validation:
  This assertion validates the word extraction logic, ensuring that the regex correctly identifies word boundaries based on alphabetic sequences. Understanding this behavior is crucial for setting correct expectations about what constitutes a "word" in the search context.

*/

// ********RoostGPT********

package com.google.adk.memory;

import static com.google.common.truth.Truth.assertThat;
import static org.mockito.Mockito.*;

import com.google.adk.events.Event;
import com.google.adk.sessions.Session;
import com.google.common.collect.ImmutableList;
import com.google.genai.types.Content;
import com.google.genai.types.Part;
import io.reactivex.rxjava3.observers.TestObserver;
import java.util.Optional;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class InMemoryMemoryServiceSearchMemoryTest {

  private InMemoryMemoryService memoryService;

  @BeforeEach
  void setUp() {
    memoryService = new InMemoryMemoryService();
  }

  @Test
  @Tag("valid")
  void searchMemoryReturnsEmptyResponseWhenUserHasNoSessions() {
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("testApp", "user123", "test query").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    testObserver.assertNoErrors();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).isEmpty();
  }

  @Test
  @Tag("valid")
  void searchMemoryReturnsMatchingMemoriesForSingleWordQuery() {
    Session session =
        createSessionWithEvents(
            "app1", "user1", "session1", createEvent("author1", "hello world", 1609459200L));
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "hello").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    testObserver.assertNoErrors();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).hasSize(1);
    assertThat(response.memories().get(0).author()).isEqualTo("author1");
    assertThat(response.memories().get(0).timestamp()).isEqualTo("2021-01-01T00:00:00Z");
  }

  @Test
  @Tag("valid")
  void searchMemoryReturnsAllMatchingMemoriesForMultiWordQuery() {
    Session session =
        createSessionWithEvents(
            "app1",
            "user1",
            "session1",
            createEvent("author1", "apple pie", 1609459200L),
            createEvent("author2", "banana bread", 1609459300L));
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "apple banana orange").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).hasSize(2);
  }

  @Test
  @Tag("valid")
  void searchMemoryReturnsEmptyResponseWhenNoWordsMatch() {
    Session session =
        createSessionWithEvents(
            "app1", "user1", "session1", createEvent("author1", "cat dog", 1609459200L));
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "elephant giraffe").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).isEmpty();
  }

  @Test
  @Tag("valid")
  void searchMemoryMatchesWordsIgnoringCase() {
    Session session =
        createSessionWithEvents(
            "app1", "user1", "session1", createEvent("author1", "Hello World", 1609459200L));
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "HELLO").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).hasSize(1);
  }

  @Test
  @Tag("boundary")
  void searchMemoryHandlesEmptyQueryString() {
    Session session =
        createSessionWithEvents(
            "app1", "user1", "session1", createEvent("author1", "hello world", 1609459200L));
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).isEmpty();
  }

  @Test
  @Tag("boundary")
  void searchMemoryHandlesWhitespaceOnlyQuery() {
    Session session =
        createSessionWithEvents(
            "app1", "user1", "session1", createEvent("author1", "hello world", 1609459200L));
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "   ").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).isEmpty();
  }

  @Test
  @Tag("valid")
  void searchMemorySkipsEventsWithEmptyContent() {
    Event eventWithContent = createEvent("author1", "hello world", 1609459200L);
    Event eventWithoutContent = mock(Event.class);
    when(eventWithoutContent.content()).thenReturn(Optional.empty());
    Session session =
        createSessionWithEvents("app1", "user1", "session1", eventWithContent, eventWithoutContent);
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "hello").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).hasSize(1);
  }

  @Test
  @Tag("valid")
  void searchMemorySkipsEventsWithEmptyPartsList() {
    Event eventWithParts = createEvent("author1", "hello world", 1609459200L);
    Event eventWithEmptyParts = createEventWithEmptyParts("author2", 1609459300L);
    Session session =
        createSessionWithEvents("app1", "user1", "session1", eventWithParts, eventWithEmptyParts);
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "hello").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).hasSize(1);
  }

  @Test
  @Tag("valid")
  void searchMemorySkipsPartsWithNullOrEmptyText() {
    Part validPart = mock(Part.class);
    when(validPart.text()).thenReturn(Optional.of("hello"));
    Part emptyPart = mock(Part.class);
    when(emptyPart.text()).thenReturn(Optional.of(""));
    Part nullPart = mock(Part.class);
    when(nullPart.text()).thenReturn(Optional.empty());
    Content content = mock(Content.class);
    when(content.parts()).thenReturn(Optional.of(ImmutableList.of(validPart, emptyPart, nullPart)));
    Event event = mock(Event.class);
    when(event.content()).thenReturn(Optional.of(content));
    when(event.author()).thenReturn("author1");
    when(event.timestamp()).thenReturn(1609459200L);
    Session session = createSessionWithEvents("app1", "user1", "session1", event);
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "hello").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).hasSize(1);
  }

  @Test
  @Tag("valid")
  void searchMemorySkipsEventsWithNoExtractableWords() {
    Session session =
        createSessionWithEvents(
            "app1", "user1", "session1", createEvent("author1", "123 !@# $$", 1609459200L));
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "hello").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).isEmpty();
  }

  @Test
  @Tag("valid")
  void searchMemorySearchesAcrossAllUserSessions() {
    Session session1 =
        createSessionWithEvents(
            "app1", "user1", "session1", createEvent("author1", "apple pie", 1609459200L));
    Session session2 =
        createSessionWithEvents(
            "app1", "user1", "session2", createEvent("author2", "banana bread", 1609459300L));
    memoryService.addSessionToMemory(session1).blockingAwait();
    memoryService.addSessionToMemory(session2).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "apple banana").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).hasSize(2);
  }

  @Test
  @Tag("valid")
  void searchMemoryHandlesSpecialCharactersInQuery() {
    Session session =
        createSessionWithEvents(
            "app1", "user1", "session1", createEvent("author1", "hello world", 1609459200L));
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "hello! @world# 123").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    testObserver.assertNoErrors();
  }

  @Test
  @Tag("valid")
  void searchMemoryExtractsWordsFromAllPartsInEvent() {
    Part part1 = mock(Part.class);
    when(part1.text()).thenReturn(Optional.of("hello"));
    Part part2 = mock(Part.class);
    when(part2.text()).thenReturn(Optional.of("world"));
    Content content = mock(Content.class);
    when(content.parts()).thenReturn(Optional.of(ImmutableList.of(part1, part2)));
    Event event = mock(Event.class);
    when(event.content()).thenReturn(Optional.of(content));
    when(event.author()).thenReturn("author1");
    when(event.timestamp()).thenReturn(1609459200L);
    Session session = createSessionWithEvents("app1", "user1", "session1", event);
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver1 =
        memoryService.searchMemory("app1", "user1", "hello").test();
    testObserver1.awaitDone(5, TimeUnit.SECONDS);
    assertThat(testObserver1.values().get(0).memories()).hasSize(1);
    TestObserver<SearchMemoryResponse> testObserver2 =
        memoryService.searchMemory("app1", "user1", "world").test();
    testObserver2.awaitDone(5, TimeUnit.SECONDS);
    assertThat(testObserver2.values().get(0).memories()).hasSize(1);
  }

  @Test
  @Tag("valid")
  void searchMemoryFormatsTimestampCorrectly() {
    Session session =
        createSessionWithEvents(
            "app1", "user1", "session1", createEvent("author1", "hello world", 1609459200L));
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "hello").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories().get(0).timestamp()).isEqualTo("2021-01-01T00:00:00Z");
  }

  @Test
  @Tag("valid")
  void searchMemoryPreservesAuthorInformation() {
    Session session =
        createSessionWithEvents(
            "app1", "user1", "session1", createEvent("testAuthor", "hello world", 1609459200L));
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "hello").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories().get(0).author()).isEqualTo("testAuthor");
  }

  @Test
  @Tag("valid")
  void searchMemoryPreservesCompleteEventContent() {
    Part part1 = mock(Part.class);
    when(part1.text()).thenReturn(Optional.of("hello"));
    Part part2 = mock(Part.class);
    when(part2.text()).thenReturn(Optional.of("world test"));
    Content content = mock(Content.class);
    when(content.parts()).thenReturn(Optional.of(ImmutableList.of(part1, part2)));
    Event event = mock(Event.class);
    when(event.content()).thenReturn(Optional.of(content));
    when(event.author()).thenReturn("author1");
    when(event.timestamp()).thenReturn(1609459200L);
    Session session = createSessionWithEvents("app1", "user1", "session1", event);
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "hello").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories().get(0).content()).isEqualTo(content);
    assertThat(response.memories().get(0).content().parts().get()).hasSize(2);
  }

  @Test
  @Tag("boundary")
  void searchMemoryHandlesDuplicateWordsInQuery() {
    Session session =
        createSessionWithEvents(
            "app1", "user1", "session1", createEvent("author1", "hello world", 1609459200L));
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "hello hello world world").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).hasSize(1);
  }

  @Test
  @Tag("valid")
  void searchMemoryHandlesVeryLongQuery() {
    Session session =
        createSessionWithEvents(
            "app1", "user1", "session1", createEvent("author1", "hello world", 1609459200L));
    memoryService.addSessionToMemory(session).blockingAwait();
    StringBuilder longQuery = new StringBuilder();
    for (int i = 0; i < 1000; i++) {
      longQuery.append("word").append(i).append(" ");
    }
    longQuery.append("hello");
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", longQuery.toString()).test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).hasSize(1);
  }

  @Test
  @Tag("valid")
  void searchMemoryReturnsResultsInSessionAndEventOrder() {
    Session session =
        createSessionWithEvents(
            "app1",
            "user1",
            "session1",
            createEvent("author1", "first match", 1609459200L),
            createEvent("author2", "second match", 1609459300L),
            createEvent("author3", "third match", 1609459400L));
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "match").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).hasSize(3);
  }

  @Test
  @Tag("valid")
  void searchMemoryMatchesCompleteWordsOnly() {
    Session session =
        createSessionWithEvents(
            "app1", "user1", "session1", createEvent("author1", "hello helloworld", 1609459200L));
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "hello").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).hasSize(1);
  }

  @Test
  @Tag("valid")
  void searchMemoryIsolatesResultsByUser() {
    Session session1 =
        createSessionWithEvents(
            "app1", "user1", "session1", createEvent("author1", "user1 data", 1609459200L));
    Session session2 =
        createSessionWithEvents(
            "app1", "user2", "session2", createEvent("author2", "user2 data", 1609459300L));
    memoryService.addSessionToMemory(session1).blockingAwait();
    memoryService.addSessionToMemory(session2).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "data").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).hasSize(1);
    assertThat(response.memories().get(0).author()).isEqualTo("author1");
  }

  @Test
  @Tag("valid")
  void searchMemoryIsolatesResultsByApplication() {
    Session session1 =
        createSessionWithEvents(
            "app1", "user1", "session1", createEvent("author1", "app1 data", 1609459200L));
    Session session2 =
        createSessionWithEvents(
            "app2", "user1", "session2", createEvent("author2", "app2 data", 1609459300L));
    memoryService.addSessionToMemory(session1).blockingAwait();
    memoryService.addSessionToMemory(session2).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "data").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).hasSize(1);
    assertThat(response.memories().get(0).author()).isEqualTo("author1");
  }

  @Test
  @Tag("valid")
  void searchMemoryReturnsImmutableMemoriesList() {
    Session session =
        createSessionWithEvents(
            "app1", "user1", "session1", createEvent("author1", "hello world", 1609459200L));
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "hello").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).isInstanceOf(ImmutableList.class);
  }

  @Test
  @Tag("invalid")
  void searchMemoryHandlesNullAppName() {
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory(null, "user1", "query").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertError(NullPointerException.class);
  }

  @Test
  @Tag("invalid")
  void searchMemoryHandlesNullUserId() {
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", null, "query").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertError(NullPointerException.class);
  }

  @Test
  @Tag("invalid")
  void searchMemoryHandlesNullQuery() {
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", null).test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertError(NullPointerException.class);
  }

  @Test
  @Tag("valid")
  void searchMemoryReturnsProperReactiveSingle() {
    Session session =
        createSessionWithEvents(
            "app1", "user1", "session1", createEvent("author1", "hello world", 1609459200L));
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "hello").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    testObserver.assertValueCount(1);
    testObserver.assertNoErrors();
  }

  @Test
  @Tag("integration")
  void searchMemoryHandlesConcurrentAccess() throws InterruptedException {
    Session session =
        createSessionWithEvents(
            "app1", "user1", "session1", createEvent("author1", "hello world", 1609459200L));
    memoryService.addSessionToMemory(session).blockingAwait();
    int threadCount = 10;
    CountDownLatch latch = new CountDownLatch(threadCount);
    ExecutorService executorService = Executors.newFixedThreadPool(threadCount);
    AtomicInteger successCount = new AtomicInteger(0);
    for (int i = 0; i < threadCount; i++) {
      executorService.submit(
          () -> {
            try {
              TestObserver<SearchMemoryResponse> testObserver =
                  memoryService.searchMemory("app1", "user1", "hello").test();
              testObserver.awaitDone(5, TimeUnit.SECONDS);
              if (testObserver.values().get(0).memories().size() == 1) {
                successCount.incrementAndGet();
              }
            } finally {
              latch.countDown();
            }
          });
    }
    latch.await(10, TimeUnit.SECONDS);
    executorService.shutdown();
    assertThat(successCount.get()).isEqualTo(threadCount);
  }

  @Test
  @Tag("valid")
  void searchMemoryHandlesUnicodeCharactersInEventText() {
    Session session =
        createSessionWithEvents(
            "app1", "user1", "session1", createEvent("author1", "hello 世界 🌍", 1609459200L));
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "hello").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).hasSize(1);
  }

  @Test
  @Tag("valid")
  void searchMemoryUsesRootLocaleForLowercaseConversion() {
    Session session =
        createSessionWithEvents(
            "app1", "user1", "session1", createEvent("author1", "HELLO WORLD", 1609459200L));
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "hello").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).hasSize(1);
  }

  @Test
  @Tag("boundary")
  void searchMemoryHandlesEmptySessionEventsMap() {
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "hello").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).isEmpty();
  }

  @Test
  @Tag("boundary")
  void searchMemoryHandlesNonAlphabeticQuery() {
    Session session =
        createSessionWithEvents(
            "app1", "user1", "session1", createEvent("author1", "hello world", 1609459200L));
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "123 !@# $%^").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).isEmpty();
  }

  @Test
  @Tag("valid")
  void searchMemoryBuildsMemoryEntryWithAllRequiredFields() {
    Session session =
        createSessionWithEvents(
            "app1", "user1", "session1", createEvent("testAuthor", "hello world", 1609459200L));
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "hello").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    MemoryEntry entry = response.memories().get(0);
    assertThat(entry.content()).isNotNull();
    assertThat(entry.author()).isNotNull();
    assertThat(entry.timestamp()).isNotNull();
  }

  @Test
  @Tag("valid")
  void searchMemoryNormalizesEventTextCase() {
    Session session =
        createSessionWithEvents(
            "app1", "user1", "session1", createEvent("author1", "HeLLo WoRLd", 1609459200L));
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "hello").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).hasSize(1);
  }

  @Test
  @Tag("valid")
  void searchMemoryDoesNotMatchPartialWords() {
    Session session =
        createSessionWithEvents(
            "app1", "user1", "session1", createEvent("author1", "hello world", 1609459200L));
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "hel").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).isEmpty();
  }

  @Test
  @Tag("valid")
  void searchMemoryPerformsEfficientlyWithManyEvents() {
    ImmutableList.Builder<Event> eventsBuilder = ImmutableList.builder();
    for (int i = 0; i < 1000; i++) {
      eventsBuilder.add(createEvent("author" + i, "event " + i + " data", 1609459200L + i));
    }
    eventsBuilder.add(createEvent("targetAuthor", "target hello data", 1609460000L));
    Session session =
        createSessionWithEvents(
            "app1", "user1", "session1", eventsBuilder.build().toArray(new Event[0]));
    memoryService.addSessionToMemory(session).blockingAwait();
    long startTime = System.currentTimeMillis();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "hello").test();
    testObserver.awaitDone(10, TimeUnit.SECONDS);
    long endTime = System.currentTimeMillis();
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).hasSize(1);
    assertThat(endTime - startTime).isLessThan(5000);
  }

  @Test
  @Tag("boundary")
  void searchMemorySkipsEmptyStringInPartsText() {
    Part validPart = mock(Part.class);
    when(validPart.text()).thenReturn(Optional.of("hello"));
    Part emptyPart = mock(Part.class);
    when(emptyPart.text()).thenReturn(Optional.of(""));
    Content content = mock(Content.class);
    when(content.parts()).thenReturn(Optional.of(ImmutableList.of(validPart, emptyPart)));
    Event event = mock(Event.class);
    when(event.content()).thenReturn(Optional.of(content));
    when(event.author()).thenReturn("author1");
    when(event.timestamp()).thenReturn(1609459200L);
    Session session = createSessionWithEvents("app1", "user1", "session1", event);
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "hello").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).hasSize(1);
  }

  @Test
  @Tag("valid")
  void searchMemoryCreatesNewMatchingMemoriesList() {
    Session session =
        createSessionWithEvents(
            "app1", "user1", "session1", createEvent("author1", "hello world", 1609459200L));
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver1 =
        memoryService.searchMemory("app1", "user1", "hello").test();
    testObserver1.awaitDone(5, TimeUnit.SECONDS);
    TestObserver<SearchMemoryResponse> testObserver2 =
        memoryService.searchMemory("app1", "user1", "world").test();
    testObserver2.awaitDone(5, TimeUnit.SECONDS);
    assertThat(testObserver1.values().get(0).memories())
        .isNotSameInstanceAs(testObserver2.values().get(0).memories());
  }

  @Test
  @Tag("valid")
  void searchMemoryExtractsWordsUsingCorrectPattern() {
    Session session =
        createSessionWithEvents(
            "app1",
            "user1",
            "session1",
            createEvent("author1", "hello123world test-case under_score", 1609459200L));
    memoryService.addSessionToMemory(session).blockingAwait();
    TestObserver<SearchMemoryResponse> testObserver =
        memoryService.searchMemory("app1", "user1", "hello world test case under score").test();
    testObserver.awaitDone(5, TimeUnit.SECONDS);
    testObserver.assertComplete();
    SearchMemoryResponse response = testObserver.values().get(0);
    assertThat(response.memories()).hasSize(1);
  }

  private Session createSessionWithEvents(
      String appName, String userId, String sessionId, Event... events) {
    Session session = mock(Session.class);
    when(session.appName()).thenReturn(appName);
    when(session.userId()).thenReturn(userId);
    when(session.id()).thenReturn(sessionId);
    when(session.events()).thenReturn(ImmutableList.copyOf(events));
    return session;
  }

  private Event createEvent(String author, String text, long timestamp) {
    Part part = mock(Part.class);
    when(part.text()).thenReturn(Optional.of(text));
    Content content = mock(Content.class);
    when(content.parts()).thenReturn(Optional.of(ImmutableList.of(part)));
    Event event = mock(Event.class);
    when(event.content()).thenReturn(Optional.of(content));
    when(event.author()).thenReturn(author);
    when(event.timestamp()).thenReturn(timestamp);
    return event;
  }

  private Event createEventWithEmptyParts(String author, long timestamp) {
    Content content = mock(Content.class);
    when(content.parts()).thenReturn(Optional.of(ImmutableList.of()));
    Event event = mock(Event.class);
    when(event.content()).thenReturn(Optional.of(content));
    when(event.author()).thenReturn(author);
    when(event.timestamp()).thenReturn(timestamp);
    return event;
  }
}
