/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test maven-adkjava-github using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=builder_c332b1f3a8
ROOST_METHOD_SIG_HASH=builder_80041265ae

Scenario 1: Validate builder Method Returns Non-Null Builder Instance

Details:
  TestName: builderReturnsNonNullBuilderInstance
  Description: This test verifies that calling the builder() static method on MemoryEntry returns a non-null instance of MemoryEntry.Builder. It checks basic instantiation and ensures that the method is functioning as expected.

Execution:
  Arrange: No special data, mocks, or test doubles are required; simply prepare to call the method.
  Act: Call the MemoryEntry.builder() method directly.
  Assert: Use JUnit assertions to check that the returned object is not null and is an instance of MemoryEntry.Builder.

Validation:
  The assertion validates the wiring and availability of the builder() method. It ensures that object creation through the builder pattern is possible, which is fundamental for the construction of MemoryEntry instances in downstream code.


Scenario 2: Check builder Method Produces New Instances Each Call

Details:
  TestName: builderCreatesDistinctInstancesOnEachInvocation
  Description: This test confirms that repeated calls to MemoryEntry.builder() produce separate instances rather than returning the same reference, safeguarding against incorrect singleton or shared builder behavior.

Execution:
  Arrange: No special setup; plan to call the method multiple times.
  Act: Invoke MemoryEntry.builder() twice (or more) and compare the returned instances.
  Assert: Use assertions to verify that each returned Builder instance has a different reference (not the same object).

Validation:
  The purpose is to confirm statelessness of the builder creation process, which is important to prevent unintentional state sharing or concurrency issues among different builds or threads using the builder.


Scenario 3: Builder Supports Setting Content Field

Details:
  TestName: builderSupportsSettingContentField
  Description: This test scenario ensures that the returned Builder instance allows setting the content field, a required property, and checks that build() for MemoryEntry does not fail when this field is set.

Execution:
  Arrange: Create a mock or real Content instance.
  Act: Obtain a Builder from MemoryEntry.builder(), set content(), and call build().
  Assert: Assert that build() produces a MemoryEntry object and that the content field is set as expected.

Validation:
  This assertion validates that the builder() can create objects with their required fields initialized, verifying the integrity of object construction via the builder pattern.


Scenario 4: Builder Allows Optional Author Field to Be Set

Details:
  TestName: builderSupportsAuthorFieldSetting
  Description: Test that the Builder returned by builder() can have its optional author field set and passed; confirms that this does not cause errors either when null or with a value.

Execution:
  Arrange: Prepare a valid Content object and both null and non-null author values.
  Act: Call MemoryEntry.builder(), set content(), set author() to both values, and call build().
  Assert: Check that MemoryEntry is created successfully under both conditions for author.

Validation:
  The validation ensures that the builder pattern handles optional fields gracefully, accommodating business needs where author data may be missing or present.


Scenario 5: Builder Accepts Timestamp Field Directly and via Instant

Details:
  TestName: builderSupportsSettingTimestampUsingStringOrInstant
  Description: The goal is to confirm that the Builder can set the timestamp by either passing a string or an Instant object, and that build() works in both cases, establishing flexibility in input formats.

Execution:
  Arrange: Prepare a mock Content and example timestamp values as string and Instant.
  Act: Use MemoryEntry.builder() to set content, then set timestamp using both string and Instant overloads, then call build().
  Assert: Assert that the MemoryEntry creation succeeds and that the timestamp property is set correctly in each case.

Validation:
  This checks input versatility for the builder, which is crucial for integration with client code that may hold timestamps in different formats.


Scenario 6: Builder Throws when Required Content Field is Missing

Details:
  TestName: builderFailsWhenRequiredContentMissing
  Description: Verify that invoking build() on Builder (returned by builder()) without first setting the required content property results in an exception, enforcing required-field constraints.

Execution:
  Arrange: Obtain a Builder instance using MemoryEntry.builder().
  Act: Call build() directly without invoking content().
  Assert: Assert that an exception (such as NullPointerException or IllegalStateException) is thrown.

Validation:
  The scenario is critical to verify field requirement enforcement, which upholds data validity and supports expected domain guarantees in immutable objects.


Scenario 7: Builder Handles Null Values for Optional Fields

Details:
  TestName: builderHandlesNullOptionalFieldsGracefully
  Description: This scenario ensures that the builder() allows optional values (author and timestamp) to be null, and such MemoryEntry objects are valid and created successfully.

Execution:
  Arrange: Prepare a Content instance and null values for author and timestamp.
  Act: Use MemoryEntry.builder() to set content, and explicitly set author and timestamp to null, then call build().
  Assert: Assert that a valid MemoryEntry object is produced and that the properties author and timestamp are null.

Validation:
  The goal is to confirm proper handling of optional data by builder(), avoiding unnecessary exceptions and supporting flexible data models.


Scenario 8: Builder Provided by builder() Supports Chainable Method Calls

Details:
  TestName: builderSupportsMethodChaining
  Description: The test checks that the Builder returned by builder() properly supports fluent method chaining, as per the builder pattern—with each setter returning Builder for chaining calls.

Execution:
  Arrange: Prepare Content, author, and timestamp values.
  Act: Use MemoryEntry.builder().content(...).author(...).timestamp(...).build() in one fluent chain.
  Assert: Assert that builder methods can be chained and produce a correct MemoryEntry.

Validation:
  This asserts builder API usability for clients, improving code readability and reducing error-prone manual intermediate variable management.


Scenario 9: Builder Provided by builder() Is of the AutoValue_MemoryEntry.Builder Implementation Type

Details:
  TestName: builderReturnsCorrectImplementationType
  Description: Verify that MemoryEntry.builder() returns an instance of the expected generated implementation class, ensuring that object construction follows the correct factory pattern.

Execution:
  Arrange: None required.
  Act: Call MemoryEntry.builder().
  Assert: Assert that the returned object's type matches AutoValue_MemoryEntry.Builder (if the implementation is public), or that it is assignable to MemoryEntry.Builder.

Validation:
  This scenario is significant for ensuring predictable and correct behavior in reflection-based or integration systems, further supporting application maintainability.


*/

// ********RoostGPT********

package com.google.adk.memory;

import com.google.genai.types.Content;
import com.google.auto.value.AutoValue;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import org.mockito.Mockito;
import java.time.Instant;
import javax.annotation.Nullable;
import org.junit.jupiter.api.*;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

public class MemoryEntryBuilderTest {

	@Test
	@Tag("valid")
	public void testBuilderReturnsNonNullBuilderInstance() {
		MemoryEntry.Builder builder = MemoryEntry.builder();
		assertNotNull((Object) builder, "Builder instance should not be null");
		assertTrue((builder instanceof MemoryEntry.Builder), "Returned instance should be of type MemoryEntry.Builder");
	}

	@Test
	@Tag("boundary")
	public void testBuilderCreatesDistinctInstancesOnEachInvocation() {
		MemoryEntry.Builder builder1 = MemoryEntry.builder();
		MemoryEntry.Builder builder2 = MemoryEntry.builder();
		assertNotSame((Object) builder1, (Object) builder2, "Each call to builder() must return a distinct instance");
	}

	@Test
	@Tag("valid")
	public void testBuilderSupportsSettingContentField() {
		Content mockContent = Mockito.mock(Content.class);
		MemoryEntry.Builder builder = MemoryEntry.builder();
		builder.content(mockContent);
		MemoryEntry entry = builder.build();
		assertNotNull((Object) entry, "build() should produce a non-null MemoryEntry object");
		assertSame((Object) mockContent, (Object) entry.content(),
				"Content should be set and match the provided instance");
	}

	@Test
	@Tag("valid")
	public void testBuilderSupportsAuthorFieldSetting() {
		Content mockContent = Mockito.mock(Content.class);
		String dummyAuthor = "Test Author";
		MemoryEntry entryWithAuthor = MemoryEntry.builder().content(mockContent).author(dummyAuthor).build();
		assertEquals((Object) dummyAuthor, (Object) entryWithAuthor.author(), "Author should match the value set");
		MemoryEntry entryWithNullAuthor = MemoryEntry.builder().content(mockContent).author(null).build();
		assertNull((Object) entryWithNullAuthor.author(), "Author should be null when set to null explicitly");
	}

	@Test
	@Tag("valid")
	public void testBuilderSupportsSettingTimestampWithString() {
		// NOTE: The original test failed due to ambiguous timestamp method (probably
		// overload: timestamp(String) and timestamp(Instant))
		// To avoid ambiguity, we split the test into two, and ensure the type is made
		// explicit!
		Content mockContent = Mockito.mock(Content.class);
		String timestampStr = "2024-04-01T12:00:00Z";
		MemoryEntry entryStr = MemoryEntry.builder().content(mockContent).timestamp(timestampStr).build();
		assertEquals((Object) timestampStr, (Object) entryStr.timestamp(), "Timestamp should match string passed");
	}

	@Test
	@Tag("valid")
	public void testBuilderSupportsSettingTimestampWithInstant() {
		// NOTE: See above for details; use explicit Instant to remove ambiguity
		Content mockContent = Mockito.mock(Content.class);
		Instant instant = Instant.parse("2024-04-01T12:00:00Z");
		MemoryEntry entryInstant = MemoryEntry.builder().content(mockContent).timestamp(instant).build();
		// Assuming the .timestamp() method of MemoryEntry returns the String
		// representation of the Instant
		assertEquals((Object) instant.toString(), (Object) entryInstant.timestamp(),
				"Timestamp should match Instant string value");
	}

	@Test
	@Tag("invalid")
	public void testBuilderFailsWhenRequiredContentMissing() {
		MemoryEntry.Builder builder = MemoryEntry.builder();
		Exception exception = assertThrows(NullPointerException.class, () -> {
			builder.build();
		});
		assertNotNull((Object) exception, "Exception should be thrown when required content is missing");
	}

	@Test
	@Tag("valid")
	public void testBuilderHandlesNullOptionalFieldsGracefully() {
		Content mockContent = Mockito.mock(Content.class);
		MemoryEntry entry = MemoryEntry.builder().content(mockContent).author(null).timestamp((String) null).build();
		assertNotNull((Object) entry, "MemoryEntry should be created successfully with null optional fields");
		assertNull((Object) entry.author(), "Author should be null");
		assertNull((Object) entry.timestamp(), "Timestamp should be null");
	}

	@Test
	@Tag("valid")
	public void testBuilderSupportsMethodChaining() {
		Content mockContent = Mockito.mock(Content.class);
		String author = "Chain Author";
		String timestamp = "2024-04-02T08:00:00Z";
		MemoryEntry entry = MemoryEntry.builder().content(mockContent).author(author).timestamp(timestamp).build();
		assertNotNull((Object) entry, "Method chaining should produce a valid MemoryEntry");
		assertSame((Object) mockContent, (Object) entry.content(), "Chained content should match");
		assertEquals((Object) author, (Object) entry.author(), "Chained author should match");
		assertEquals((Object) timestamp, (Object) entry.timestamp(), "Chained timestamp should match");
	}

	@Test
	@Tag("integration")
	public void testBuilderReturnsCorrectImplementationType() {
		MemoryEntry.Builder builder = MemoryEntry.builder();
		assertTrue(
				(builder.getClass().getName().contains("AutoValue_MemoryEntry$Builder")
						|| builder.getClass().getName().contains("AutoValue_MemoryEntry.Builder")),
				"Builder should be of AutoValue_MemoryEntry.Builder implementation type");
	}

}