/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-maven-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=builder_c332b1f3a8
ROOST_METHOD_SIG_HASH=builder_80041265ae

Scenario 1: Successfully Create a New Builder Instance

Details:
  TestName: builderReturnsNonNullBuilderInstance
  Description: This test verifies that the static builder() method successfully creates and returns a new Builder instance. The test ensures that the factory method properly instantiates the AutoValue-generated Builder class and that the returned object is not null.
  
Execution:
  Arrange: No specific setup is required as this is a static factory method test.
  Act: Invoke MemoryEntry.builder() to obtain a Builder instance.
  Assert: Use assertNotNull() to verify that the returned Builder instance is not null.
  
Validation:
  The assertion verifies that the builder() method correctly instantiates and returns a Builder object. This is critical because the Builder is the primary mechanism for creating MemoryEntry instances in the application. A null return value would prevent any MemoryEntry objects from being created, breaking the entire memory management functionality. This test ensures the basic factory pattern implementation is working correctly.

---

Scenario 2: Builder Instance is of Correct Type

Details:
  TestName: builderReturnsCorrectBuilderType
  Description: This test validates that the builder() method returns an instance of the correct Builder type. It ensures that the returned object is indeed a MemoryEntry.Builder instance, confirming proper type safety and AutoValue code generation.
  
Execution:
  Arrange: No specific setup is required.
  Act: Call MemoryEntry.builder() to get a Builder instance.
  Assert: Use assertInstanceOf() or assertTrue() with instanceof to verify the returned object is an instance of MemoryEntry.Builder.
  
Validation:
  This assertion confirms that the builder() method returns the correct type as specified in the method signature. Type correctness is essential for compile-time safety and proper method chaining in the builder pattern. This test ensures that the AutoValue annotation processor has correctly generated the Builder class and that the factory method returns the appropriate type.

---

Scenario 3: Multiple Builder Instances are Independent

Details:
  TestName: builderCreatesIndependentInstances
  Description: This test verifies that multiple calls to the builder() method return separate, independent Builder instances. This ensures that each builder can be configured independently without affecting other builders, which is crucial for thread safety and proper builder pattern implementation.
  
Execution:
  Arrange: No specific setup is required.
  Act: Call MemoryEntry.builder() twice to obtain two separate Builder instances (builder1 and builder2).
  Assert: Use assertNotSame() to verify that the two Builder instances are different objects in memory.
  
Validation:
  The assertion verifies that each call to builder() creates a new instance rather than returning a singleton or cached instance. This is important because builders are typically mutable objects that accumulate state. If the same instance were returned, concurrent modifications could lead to race conditions or unexpected behavior. This test ensures proper isolation between different builder instances, which is essential for correct application behavior in multi-threaded environments or when creating multiple MemoryEntry objects.

---

Scenario 4: Builder Can Be Used to Build MemoryEntry

Details:
  TestName: builderCanConstructValidMemoryEntry
  Description: This test validates the end-to-end functionality of the builder() method by using the returned Builder to construct a complete MemoryEntry object. It ensures that the Builder returned by the factory method is fully functional and can be used to create valid MemoryEntry instances.
  
Execution:
  Arrange: Create a Content object to use as the required content field.
  Act: Call MemoryEntry.builder(), set the required content field using content(), and invoke build() to create a MemoryEntry instance.
  Assert: Use assertNotNull() to verify that the build() method successfully creates a MemoryEntry object.
  
Validation:
  This assertion verifies the complete builder workflow from factory method invocation to final object creation. It confirms that the Builder returned by builder() is properly initialized and can successfully construct MemoryEntry objects. This is a critical integration test that ensures the builder pattern implementation is complete and functional. If this test fails, it indicates a fundamental problem with either the builder() factory method or the Builder class itself, which would prevent any MemoryEntry objects from being created in the application.

---

Scenario 5: Builder Returned Has Default State

Details:
  TestName: builderReturnsBuilderWithDefaultState
  Description: This test verifies that the Builder instance returned by the builder() method is in a clean, default state without any pre-configured values. This ensures that each new builder starts fresh and doesn't carry over any state from previous operations.
  
Execution:
  Arrange: No specific setup is required.
  Act: Call MemoryEntry.builder() to obtain a Builder instance, then attempt to build a MemoryEntry without setting any fields.
  Assert: Use assertThrows() to verify that calling build() without setting required fields throws an IllegalStateException or similar exception.
  
Validation:
  This assertion confirms that the builder starts in a default state where required fields (like content) are not set. This is important because it ensures that the builder enforces the requirement for mandatory fields and doesn't have any hidden pre-configured values. A builder that starts with pre-configured values could lead to unexpected behavior where developers think they're creating a fresh object but are actually getting pre-populated data. This test ensures proper initialization and validation behavior of the builder pattern.

---

Scenario 6: Builder Method is Thread-Safe for Concurrent Calls

Details:
  TestName: builderIsThreadSafeForConcurrentInvocations
  Description: This test validates that the static builder() method can be safely called from multiple threads concurrently without causing race conditions or returning corrupted Builder instances. This is important for applications that create MemoryEntry objects in multi-threaded environments.
  
Execution:
  Arrange: Create multiple threads (e.g., 10 threads) that will concurrently call the builder() method.
  Act: Execute all threads simultaneously, each calling MemoryEntry.builder() multiple times and storing the results in a thread-safe collection.
  Assert: Verify that all returned Builder instances are non-null and that the total count matches the expected number of invocations.
  
Validation:
  This assertion ensures that the static factory method is thread-safe and can handle concurrent access without issues. Since the builder() method is likely to be called from various parts of a multi-threaded application, it's crucial that it doesn't have any hidden state or synchronization issues. This test verifies that the method can safely create independent Builder instances even under concurrent load, which is essential for application stability and correctness in production environments.

---

Scenario 7: Builder Method Consistency Across Multiple Invocations

Details:
  TestName: builderReturnsConsistentBuilderType
  Description: This test verifies that the builder() method consistently returns Builder instances of the same class type across multiple invocations. This ensures that the AutoValue code generation is stable and that the factory method behavior is predictable.
  
Execution:
  Arrange: No specific setup is required.
  Act: Call MemoryEntry.builder() multiple times (e.g., 5 times) and collect the class types of the returned Builder instances.
  Assert: Verify that all returned Builder instances have the same class type using assertEquals() on their getClass() results.
  
Validation:
  This assertion confirms that the builder() method consistently returns the same type of Builder across multiple calls. This is important for ensuring that the AutoValue annotation processor generates stable code and that there are no dynamic class loading issues or version conflicts. Consistent type returns are essential for proper polymorphism, method resolution, and overall application stability. Any variation in the returned class type could indicate serious issues with the build process or runtime class loading.

*/

// ********RoostGPT********

package com.google.adk.memory;
import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNotSame;
import static org.junit.jupiter.api.Assertions.assertThrows;
import com.google.genai.types.Content;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.*;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.google.auto.value.AutoValue;
import java.time.Instant;
import javax.annotation.Nullable;

class MemoryEntryBuilderTest {
    @Test
    @Tag("valid")
    void builderReturnsNonNullBuilderInstance() {
        // Act
        MemoryEntry.Builder builder = MemoryEntry.builder();
        // Assert
        assertNotNull(builder, "Builder instance should not be null");
    }
    @Test
    @Tag("valid")
    void builderReturnsCorrectBuilderType() {
        // Act
        MemoryEntry.Builder builder = MemoryEntry.builder();
        // Assert
        assertInstanceOf(MemoryEntry.Builder.class, builder, 
            "Returned instance should be of type MemoryEntry.Builder");
    }
    @Test
    @Tag("valid")
    void builderCreatesIndependentInstances() {
        // Act
        MemoryEntry.Builder builder1 = MemoryEntry.builder();
        MemoryEntry.Builder builder2 = MemoryEntry.builder();
        // Assert
        assertNotSame(builder1, builder2, 
            "Multiple calls to builder() should return different instances");
    }
    @Test
    @Tag("integration")
    void builderCanConstructValidMemoryEntry() {
        // Arrange
        Content content = Content.builder()
            .role("user")
            .addText("Test content")
            .build();
        // Act
        MemoryEntry.Builder builder = MemoryEntry.builder();
        MemoryEntry memoryEntry = builder
            .content(content)
            .author("test-author")
            .timestamp("2024-01-01T00:00:00Z")
            .build();
        // Assert
        assertNotNull(memoryEntry, "Built MemoryEntry should not be null");
        assertNotNull(memoryEntry.content(), "Content should not be null");
        assertEquals("test-author", memoryEntry.author(), "Author should match");
        assertEquals("2024-01-01T00:00:00Z", memoryEntry.timestamp(), "Timestamp should match");
    }
    @Test
    @Tag("invalid")
    void builderReturnsBuilderWithDefaultState() {
        // Act
        MemoryEntry.Builder builder = MemoryEntry.builder();
        // Assert
        assertThrows(IllegalStateException.class, () -> builder.build(),
            "Building without required fields should throw IllegalStateException");
    }
    @Test
    @Tag("valid")
    void builderIsThreadSafeForConcurrentInvocations() throws InterruptedException {
        // Arrange
        int threadCount = 10;
        int invocationsPerThread = 100;
        ExecutorService executorService = Executors.newFixedThreadPool(threadCount);
        CountDownLatch latch = new CountDownLatch(threadCount);
        List<MemoryEntry.Builder> builders = Collections.synchronizedList(new ArrayList<>());
        // Act
        for (int i = 0; i < threadCount; i++) {
            executorService.submit(() -> {
                try {
                    for (int j = 0; j < invocationsPerThread; j++) {
                        MemoryEntry.Builder builder = MemoryEntry.builder();
                        builders.add(builder);
                    }
                } finally {
                    latch.countDown();
                }
            });
        }
        latch.await(10, TimeUnit.SECONDS);
        executorService.shutdown();
        executorService.awaitTermination(10, TimeUnit.SECONDS);
        // Assert
        assertEquals(threadCount * invocationsPerThread, builders.size(),
            "All builder instances should be created successfully");
        
        for (MemoryEntry.Builder builder : builders) {
            assertNotNull(builder, "Each builder instance should not be null");
        }
    }
    @Test
    @Tag("valid")
    void builderReturnsConsistentBuilderType() {
        // Arrange
        int invocationCount = 5;
        List<Class<?>> builderClasses = new ArrayList<>();
        // Act
        for (int i = 0; i < invocationCount; i++) {
            MemoryEntry.Builder builder = MemoryEntry.builder();
            builderClasses.add(builder.getClass());
        }
        // Assert
        Class<?> firstClass = builderClasses.get(0);
        for (Class<?> builderClass : builderClasses) {
            assertEquals(firstClass, builderClass,
                "All builder instances should have the same class type");
        }
    }
    @Test
    @Tag("valid")
    void builderMethodIsAccessible() {
        // Act & Assert
        assertDoesNotThrow(() -> MemoryEntry.builder(),
            "Builder method should be accessible and not throw any exceptions");
    }
    @Test
    @Tag("integration")
    void builderSupportsMethodChaining() {
        // Arrange
        Content content = Content.builder()
            .role("user")
            .addText("Test content")
            .build();
        // Act
        MemoryEntry memoryEntry = MemoryEntry.builder()
            .content(content)
            .author("test-author")
            .timestamp("2024-01-01T00:00:00Z")
            .build();
        // Assert
        assertNotNull(memoryEntry, "Method chaining should produce a valid MemoryEntry");
        assertEquals("test-author", memoryEntry.author(), "Author should be set correctly");
    }
    @Test
    @Tag("boundary")
    void builderHandlesNullableFields() {
        // Arrange
        Content content = Content.builder()
            .role("user")
            .addText("Test content")
            .build();
        // Act
        MemoryEntry memoryEntry = MemoryEntry.builder()
            .content(content)
            .author(null)
            .timestamp(null)
            .build();
        // Assert
        assertNotNull(memoryEntry, "MemoryEntry should be created with null optional fields");
        assertNotNull(memoryEntry.content(), "Content should not be null");
    }
    @Test
    @Tag("valid")
    void multipleBuilderInstancesCanBuildIndependently() {
        // Arrange
        Content content1 = Content.builder()
            .role("user")
            .addText("Content 1")
            .build();
        
        Content content2 = Content.builder()
            .role("assistant")
            .addText("Content 2")
            .build();
        MemoryEntry.Builder builder1 = MemoryEntry.builder();
        MemoryEntry.Builder builder2 = MemoryEntry.builder();
        // Act
        MemoryEntry entry1 = builder1
            .content(content1)
            .author("author1")
            .timestamp("2024-01-01T00:00:00Z")
            .build();
        MemoryEntry entry2 = builder2
            .content(content2)
            .author("author2")
            .timestamp("2024-01-02T00:00:00Z")
            .build();
        // Assert
        assertNotNull(entry1, "First entry should be built successfully");
        assertNotNull(entry2, "Second entry should be built successfully");
        assertEquals("author1", entry1.author(), "First entry should have correct author");
        assertEquals("author2", entry2.author(), "Second entry should have correct author");
        assertNotSame(entry1, entry2, "Entries should be different instances");
    }
}