/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-maven-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=builder_c78465a311
ROOST_METHOD_SIG_HASH=builder_80041265ae

Scenario 1: Verify that builder method returns a non-null Builder instance

Details:
  TestName: builderReturnsNonNullBuilderInstance
  Description: This test verifies that the static builder() method returns a non-null Builder instance. The builder() method is the entry point for constructing SearchMemoryResponse objects using the builder pattern, and it must always return a valid Builder instance.
Execution:
  Arrange: No setup required as this is a static method call with no dependencies.
  Act: Invoke SearchMemoryResponse.builder() to obtain a Builder instance.
  Assert: Use assertNotNull() to verify that the returned Builder instance is not null.
Validation:
  The assertion verifies that the builder() method successfully creates and returns a Builder instance. This is critical because a null return value would cause NullPointerException in subsequent builder operations. This test ensures the basic contract of the builder pattern is maintained, allowing clients to safely chain builder method calls.

Scenario 2: Verify that builder method returns a Builder instance of correct type

Details:
  TestName: builderReturnsCorrectBuilderType
  Description: This test confirms that the builder() method returns an instance that is assignable to the Builder type. This ensures type safety and that the returned object can be used with all Builder methods.
Execution:
  Arrange: No setup required.
  Act: Call SearchMemoryResponse.builder() and capture the returned object.
  Assert: Use assertInstanceOf() or assertTrue() with instanceof to verify the returned object is an instance of SearchMemoryResponse.Builder.
Validation:
  This assertion ensures that the builder() method returns the correct type as declared in its signature. This is important for type safety and ensures that the AutoValue generated implementation correctly implements the Builder interface. It validates that clients can safely cast and use the returned Builder for constructing SearchMemoryResponse objects.

Scenario 3: Verify that builder initializes with empty memories list by default

Details:
  TestName: builderInitializesWithEmptyMemoriesList
  Description: This test verifies that the Builder returned by builder() method is pre-initialized with an empty ImmutableList for memories. According to the implementation, setMemories(ImmutableList.of()) is called during builder creation, which should set an empty list as the default value.
Execution:
  Arrange: No setup required.
  Act: Call SearchMemoryResponse.builder() to get a Builder instance, then call build() on it to create a SearchMemoryResponse object.
  Assert: Use assertNotNull() to verify the memories() list is not null, and assertEquals() or assertTrue() to verify that memories().isEmpty() returns true and memories().size() equals 0.
Validation:
  This assertion verifies that the builder provides a sensible default value for the memories field. An empty list is a safe default that prevents NullPointerException when accessing memories() on a SearchMemoryResponse built without explicitly setting memories. This test ensures that clients can create valid SearchMemoryResponse objects without having to explicitly set all fields, following the principle of safe defaults in builder patterns.

Scenario 4: Verify that multiple calls to builder method return independent Builder instances

Details:
  TestName: multipleBuilderCallsReturnIndependentInstances
  Description: This test ensures that each call to builder() returns a new, independent Builder instance. This is important to prevent shared state between different builder instances, which could lead to unexpected behavior when multiple SearchMemoryResponse objects are being constructed concurrently or sequentially.
Execution:
  Arrange: No setup required.
  Act: Call SearchMemoryResponse.builder() twice to obtain two Builder instances (builder1 and builder2).
  Assert: Use assertNotSame() to verify that builder1 and builder2 are different object instances (not the same reference).
Validation:
  This assertion verifies that the builder() method creates a new Builder instance on each invocation rather than returning a singleton or cached instance. This is crucial for thread safety and preventing unintended state sharing. If the same Builder instance were returned, modifications to one builder would affect others, leading to bugs. This test ensures proper isolation between different builder usage contexts.

Scenario 5: Verify that builder can be used to build a valid SearchMemoryResponse object

Details:
  TestName: builderCanBuildValidSearchMemoryResponse
  Description: This test verifies the end-to-end functionality of the builder() method by using the returned Builder to construct a complete SearchMemoryResponse object. This ensures that the Builder returned by builder() is fully functional and properly initialized.
Execution:
  Arrange: No setup required.
  Act: Call SearchMemoryResponse.builder() to get a Builder, then call build() on the Builder to create a SearchMemoryResponse instance.
  Assert: Use assertNotNull() to verify that the built SearchMemoryResponse object is not null, and verify that it is an instance of SearchMemoryResponse class.
Validation:
  This assertion validates the complete builder workflow from creation to object construction. It ensures that the Builder returned by builder() is properly configured with all necessary defaults and can successfully create a valid SearchMemoryResponse object. This is a critical integration test that verifies the builder pattern implementation works correctly for the most basic use case.

Scenario 6: Verify that builder method is idempotent and consistent

Details:
  TestName: builderMethodIsIdempotentAndConsistent
  Description: This test verifies that calling builder() multiple times produces Builder instances that behave consistently. While the instances should be different objects, they should all be initialized with the same default state (empty memories list).
Execution:
  Arrange: No setup required.
  Act: Call SearchMemoryResponse.builder() twice to get two Builder instances, then build SearchMemoryResponse objects from each builder.
  Assert: Verify that both built SearchMemoryResponse objects have memories lists that are empty (size 0) and that both memories() calls return non-null ImmutableList instances.
Validation:
  This assertion ensures consistency in the builder() method's behavior across multiple invocations. Each Builder should start with the same default state, providing predictable behavior for clients. This test validates that the initialization logic (setMemories(ImmutableList.of())) is consistently applied to every new Builder instance, ensuring reliable and predictable API behavior.

Scenario 7: Verify that Builder returned by builder can chain method calls

Details:
  TestName: builderSupportsMethodChaining
  Description: This test verifies that the Builder instance returned by builder() supports method chaining, which is a fundamental characteristic of the builder pattern. The setMemories method should return the Builder instance to allow fluent API usage.
Execution:
  Arrange: Create a test ImmutableList of MemoryEntry objects (can be empty for this test).
  Act: Call SearchMemoryResponse.builder().setMemories(testList) and verify the return value is a Builder instance.
  Assert: Use assertNotNull() to verify that setMemories() returns a non-null value, and verify it is an instance of Builder.
Validation:
  This assertion validates that the builder pattern is properly implemented with method chaining support. Method chaining improves code readability and allows for more concise object construction. This test ensures that clients can write fluent code like builder().setMemories(list).build() without intermediate variable assignments.

Scenario 8: Verify that builder creates Builder with proper AutoValue implementation

Details:
  TestName: builderCreatesAutoValueGeneratedBuilder
  Description: This test verifies that the builder() method returns an AutoValue-generated Builder implementation (AutoValue_SearchMemoryResponse.Builder). This ensures that the AutoValue annotation processing has been correctly applied and the generated code is being used.
Execution:
  Arrange: No setup required.
  Act: Call SearchMemoryResponse.builder() to obtain a Builder instance.
  Assert: Verify that the Builder instance's class name contains "AutoValue_SearchMemoryResponse" or that it is an instance of the expected AutoValue-generated class.
Validation:
  This assertion ensures that the AutoValue code generation is working correctly and that the builder() method is using the generated implementation. AutoValue provides immutability guarantees and proper equals/hashCode implementations. This test validates that the build infrastructure is correctly configured and that the AutoValue processor has generated the necessary code.

*/

// ********RoostGPT********

package com.google.adk.memory;
import static com.google.common.truth.Truth.assertThat;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNotSame;
import static org.junit.jupiter.api.Assertions.assertTrue;
import com.google.common.collect.ImmutableList;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.*;
import com.google.auto.value.AutoValue;
import java.util.List;

class SearchMemoryResponseBuilderTest {
    @Test
    @Tag("valid")
    void builderReturnsNonNullBuilderInstance() {
        SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
        
        assertNotNull(builder);
    }
    @Test
    @Tag("valid")
    void builderReturnsCorrectBuilderType() {
        SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
        
        assertInstanceOf(SearchMemoryResponse.Builder.class, builder);
        assertTrue(builder instanceof SearchMemoryResponse.Builder);
    }
    @Test
    @Tag("valid")
    void builderInitializesWithEmptyMemoriesList() {
        SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
        SearchMemoryResponse response = builder.build();
        
        assertNotNull(response.memories());
        assertTrue(response.memories().isEmpty());
        assertThat(response.memories().size()).isEqualTo(0);
    }
    @Test
    @Tag("valid")
    void multipleBuilderCallsReturnIndependentInstances() {
        SearchMemoryResponse.Builder builder1 = SearchMemoryResponse.builder();
        SearchMemoryResponse.Builder builder2 = SearchMemoryResponse.builder();
        
        assertNotSame(builder1, builder2);
        assertThat(builder1).isNotSameInstanceAs(builder2);
    }
    @Test
    @Tag("integration")
    void builderCanBuildValidSearchMemoryResponse() {
        SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
        SearchMemoryResponse response = builder.build();
        
        assertNotNull(response);
        assertInstanceOf(SearchMemoryResponse.class, response);
    }
    @Test
    @Tag("valid")
    void builderMethodIsIdempotentAndConsistent() {
        SearchMemoryResponse.Builder builder1 = SearchMemoryResponse.builder();
        SearchMemoryResponse.Builder builder2 = SearchMemoryResponse.builder();
        
        SearchMemoryResponse response1 = builder1.build();
        SearchMemoryResponse response2 = builder2.build();
        
        assertNotNull(response1.memories());
        assertNotNull(response2.memories());
        assertThat(response1.memories().size()).isEqualTo(0);
        assertThat(response2.memories().size()).isEqualTo(0);
        assertTrue(response1.memories().isEmpty());
        assertTrue(response2.memories().isEmpty());
    }
    @Test
    @Tag("valid")
    void builderSupportsMethodChaining() {
        ImmutableList<MemoryEntry> testList = ImmutableList.of();
        
        SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
        SearchMemoryResponse.Builder chainedBuilder = builder.setMemories(testList);
        
        assertNotNull(chainedBuilder);
        assertInstanceOf(SearchMemoryResponse.Builder.class, chainedBuilder);
    }
    @Test
    @Tag("integration")
    void builderCreatesAutoValueGeneratedBuilder() {
        SearchMemoryResponse.Builder builder = SearchMemoryResponse.builder();
        
        String builderClassName = builder.getClass().getName();
        assertThat(builderClassName).contains("AutoValue_SearchMemoryResponse");
    }
    @Test
    @Tag("valid")
    void builderWithEmptyMemoriesListCanBuildSuccessfully() {
        SearchMemoryResponse response = SearchMemoryResponse.builder().build();
        
        assertNotNull(response);
        assertNotNull(response.memories());
        assertThat(response.memories()).isEmpty();
    }
    @Test
    @Tag("integration")
    void builderChainedWithSetMemoriesAndBuildWorks() {
        ImmutableList<MemoryEntry> emptyList = ImmutableList.of();
        
        SearchMemoryResponse response = SearchMemoryResponse.builder()
                .setMemories(emptyList)
                .build();
        
        assertNotNull(response);
        assertNotNull(response.memories());
        assertThat(response.memories()).isEmpty();
    }
    @Test
    @Tag("valid")
    void multipleBuilderInstancesProduceDifferentObjects() {
        SearchMemoryResponse response1 = SearchMemoryResponse.builder().build();
        SearchMemoryResponse response2 = SearchMemoryResponse.builder().build();
        
        assertNotNull(response1);
        assertNotNull(response2);
        assertNotSame(response1, response2);
    }
    @Test
    @Tag("valid")
    void builderDefaultStateIsConsistentAcrossInvocations() {
        SearchMemoryResponse.Builder builder1 = SearchMemoryResponse.builder();
        SearchMemoryResponse.Builder builder2 = SearchMemoryResponse.builder();
        SearchMemoryResponse.Builder builder3 = SearchMemoryResponse.builder();
        
        SearchMemoryResponse response1 = builder1.build();
        SearchMemoryResponse response2 = builder2.build();
        SearchMemoryResponse response3 = builder3.build();
        
        assertThat(response1.memories()).isEmpty();
        assertThat(response2.memories()).isEmpty();
        assertThat(response3.memories()).isEmpty();
    }
}