/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-maven-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=memories_8e2d54404c
ROOST_METHOD_SIG_HASH=memories_8e2d54404c

Scenario 1: Retrieve memories from a SearchMemoryResponse with multiple MemoryEntry objects

Details:
  TestName: memoriesReturnsMultipleMemoryEntries
  Description: This test verifies that the memories() method correctly returns an ImmutableList containing multiple MemoryEntry objects when the SearchMemoryResponse is built with a list of memory entries. It ensures that the method properly retrieves all memory entries that were set during the object construction.
Execution:
  Arrange: Create multiple MemoryEntry mock objects or test doubles. Build a SearchMemoryResponse instance using the builder pattern and set the memories list with the created MemoryEntry objects.
  Act: Invoke the memories() method on the SearchMemoryResponse instance.
  Assert: Use JUnit assertions to verify that the returned ImmutableList is not null, has the expected size matching the number of MemoryEntry objects added, and contains all the expected MemoryEntry objects in the correct order.
Validation:
  The assertion aims to verify that the memories() method returns the complete list of memory entries that were provided during object construction. This is significant because it ensures that the SearchMemoryResponse correctly stores and retrieves memory search results, which is fundamental to the memory search functionality. The test validates that no data is lost during the building process and that the immutability contract is maintained.

Scenario 2: Retrieve memories from a SearchMemoryResponse with an empty list

Details:
  TestName: memoriesReturnsEmptyListWhenNoMemoriesSet
  Description: This test checks that the memories() method returns an empty ImmutableList when a SearchMemoryResponse is created without explicitly setting any memory entries. It validates the default behavior when the builder is used without calling setMemories() or when an empty list is provided.
Execution:
  Arrange: Create a SearchMemoryResponse instance using the builder pattern without setting any memories, or explicitly set an empty list.
  Act: Invoke the memories() method on the SearchMemoryResponse instance.
  Assert: Use JUnit assertions to verify that the returned ImmutableList is not null, is empty (size equals 0), and that calling isEmpty() returns true.
Validation:
  This assertion verifies that the memories() method handles the case where no memory entries exist gracefully by returning an empty collection rather than null. This is important for preventing NullPointerException in client code and follows best practices for collection-returning methods. The test ensures that the default initialization in the builder (ImmutableList.of()) works correctly.

Scenario 3: Verify immutability of the returned memories list

Details:
  TestName: memoriesReturnsImmutableList
  Description: This test ensures that the ImmutableList returned by the memories() method is truly immutable and cannot be modified after retrieval. It validates that the returned collection adheres to the immutability contract of ImmutableList.
Execution:
  Arrange: Create a SearchMemoryResponse instance with a list of MemoryEntry objects using the builder.
  Act: Invoke the memories() method to retrieve the ImmutableList. Attempt to modify the returned list using methods that would modify a mutable list (this will throw an exception).
  Assert: Use JUnit assertions to verify that attempting to modify the list (e.g., using add(), remove(), or clear() methods) throws an UnsupportedOperationException. Also verify that the original list remains unchanged.
Validation:
  This test validates that the memories() method returns a truly immutable collection, which is crucial for maintaining data integrity and preventing unintended modifications to the search results. The immutability ensures thread-safety and prevents bugs caused by accidental mutations. This is particularly important in a memory search context where results should remain consistent after retrieval.

Scenario 4: Retrieve memories from a SearchMemoryResponse with a single MemoryEntry

Details:
  TestName: memoriesReturnsSingleMemoryEntry
  Description: This test verifies that the memories() method correctly returns an ImmutableList containing exactly one MemoryEntry object when the SearchMemoryResponse is built with a single memory entry. It ensures proper handling of the boundary case with minimal data.
Execution:
  Arrange: Create a single MemoryEntry mock object or test double. Build a SearchMemoryResponse instance using the builder and set the memories list with the single MemoryEntry object.
  Act: Invoke the memories() method on the SearchMemoryResponse instance.
  Assert: Use JUnit assertions to verify that the returned ImmutableList is not null, has a size of 1, and contains the exact MemoryEntry object that was added.
Validation:
  The assertion confirms that the memories() method correctly handles the minimal case of a single memory entry. This is important for validating that the method works correctly regardless of the collection size, including edge cases. It ensures that single-result searches are handled properly, which is a common scenario in memory search operations.

Scenario 5: Verify memories list maintains insertion order

Details:
  TestName: memoriesMaintainsInsertionOrder
  Description: This test checks that the memories() method returns an ImmutableList that preserves the order in which MemoryEntry objects were added during the building of the SearchMemoryResponse. It validates that the ordering semantics are maintained.
Execution:
  Arrange: Create multiple distinct MemoryEntry objects in a specific order. Build a SearchMemoryResponse instance using the builder and set the memories list with the MemoryEntry objects in the predetermined order.
  Act: Invoke the memories() method on the SearchMemoryResponse instance.
  Assert: Use JUnit assertions to verify that the returned ImmutableList contains the MemoryEntry objects in the exact same order they were added. Compare each element at each index position.
Validation:
  This test ensures that the memories() method preserves the insertion order of memory entries, which may be important for maintaining relevance rankings or temporal ordering in search results. The preservation of order is a key characteristic of ImmutableList and is crucial for applications that depend on the sequence of search results. This validates that the conversion from List to ImmutableList maintains ordering semantics.

Scenario 6: Retrieve memories multiple times returns the same instance

Details:
  TestName: memoriesReturnsConsistentResultsOnMultipleCalls
  Description: This test verifies that calling the memories() method multiple times on the same SearchMemoryResponse instance returns consistent results. It checks whether the method returns the same ImmutableList instance or equivalent instances with the same content.
Execution:
  Arrange: Create a SearchMemoryResponse instance with a list of MemoryEntry objects using the builder.
  Act: Invoke the memories() method multiple times on the same SearchMemoryResponse instance, storing each result.
  Assert: Use JUnit assertions to verify that all returned ImmutableList instances contain the same MemoryEntry objects in the same order. Optionally verify that the same instance is returned (reference equality) if the implementation caches the result.
Validation:
  This assertion validates the consistency and idempotency of the memories() method. Multiple calls should return the same data, ensuring predictable behavior. This is important for application logic that may call the method multiple times and expect consistent results. It also validates that the AutoValue implementation correctly handles the abstract getter method.

Scenario 7: Verify memories list with null MemoryEntry objects if allowed

Details:
  TestName: memoriesHandlesNullMemoryEntries
  Description: This test checks how the memories() method handles a list that contains null MemoryEntry objects, if such a scenario is possible given the builder's validation. It verifies whether nulls are preserved or if they cause an exception during building or retrieval.
Execution:
  Arrange: Attempt to create a SearchMemoryResponse instance using the builder with a list containing null MemoryEntry objects. This may throw an exception during building if nulls are not allowed.
  Act: If the build succeeds, invoke the memories() method on the SearchMemoryResponse instance.
  Assert: Use JUnit assertions to verify either that the build process throws an appropriate exception (like NullPointerException or IllegalArgumentException), or if nulls are allowed, that the returned ImmutableList contains the null values at the expected positions.
Validation:
  This test validates the null-handling behavior of the SearchMemoryResponse class. Since ImmutableList.copyOf() typically does not allow null elements, this test likely validates that attempting to create a SearchMemoryResponse with null entries fails appropriately. This is important for ensuring data integrity and preventing null-related bugs in downstream code that processes memory search results.

Scenario 8: Retrieve memories from SearchMemoryResponse built with List parameter

Details:
  TestName: memoriesWorksWithListParameterInBuilder
  Description: This test verifies that the memories() method correctly returns memory entries when the SearchMemoryResponse is built using the setMemories(List<MemoryEntry>) method variant that accepts a List parameter rather than an ImmutableList.
Execution:
  Arrange: Create a mutable List (such as ArrayList) containing MemoryEntry objects. Build a SearchMemoryResponse instance using the builder's setMemories(List<MemoryEntry>) method.
  Act: Invoke the memories() method on the SearchMemoryResponse instance.
  Assert: Use JUnit assertions to verify that the returned ImmutableList contains all the MemoryEntry objects from the original List, in the same order, and that the returned list is immutable.
Validation:
  This test ensures that the builder's convenience method for accepting a List parameter correctly converts the mutable list to an ImmutableList. It validates that the ImmutableList.copyOf() conversion works properly and that the resulting SearchMemoryResponse contains the expected data. This is important because it allows clients to use standard Java collections when building the response object.

Scenario 9: Verify memories list independence from original source list

Details:
  TestName: memoriesIsIndependentFromSourceList
  Description: This test verifies that the ImmutableList returned by memories() is independent from the original List used to build the SearchMemoryResponse. Modifications to the original source list should not affect the SearchMemoryResponse's memories.
Execution:
  Arrange: Create a mutable List containing MemoryEntry objects. Build a SearchMemoryResponse instance using the builder with this list. After building, modify the original source list by adding or removing elements.
  Act: Invoke the memories() method on the SearchMemoryResponse instance after the source list has been modified.
  Assert: Use JUnit assertions to verify that the returned ImmutableList contains only the original MemoryEntry objects that were present when the SearchMemoryResponse was built, and does not reflect any modifications made to the source list afterward.
Validation:
  This test validates the defensive copying behavior of the builder, ensuring that the SearchMemoryResponse is truly immutable and isolated from external changes. This is crucial for maintaining data integrity and preventing bugs caused by unexpected mutations. It confirms that ImmutableList.copyOf() creates a defensive copy rather than maintaining a reference to the original list.

Scenario 10: Retrieve memories with large number of MemoryEntry objects

Details:
  TestName: memoriesHandlesLargeNumberOfEntries
  Description: This test verifies that the memories() method correctly handles and returns a large collection of MemoryEntry objects, testing the scalability and performance characteristics of the implementation.
Execution:
  Arrange: Create a large list (e.g., 1000 or 10000) of MemoryEntry mock objects. Build a SearchMemoryResponse instance using the builder with this large list.
  Act: Invoke the memories() method on the SearchMemoryResponse instance.
  Assert: Use JUnit assertions to verify that the returned ImmutableList has the expected size matching the large number of entries, contains all the expected entries, and that the operation completes within a reasonable time frame.
Validation:
  This test validates that the memories() method can handle large result sets efficiently, which is important for real-world applications where memory searches might return many results. It ensures that there are no performance bottlenecks or memory issues when dealing with large collections. This test is significant for validating the scalability of the memory search functionality.

*/

// ********RoostGPT********

package com.google.adk.memory;
import static com.google.common.truth.Truth.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;
import com.google.common.collect.ImmutableList;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.*;
import com.google.auto.value.AutoValue;

class SearchMemoryResponseMemoriesTest {
  @Test
  @Tag("valid")
  void memoriesReturnsMultipleMemoryEntries() {
    // Arrange
    MemoryEntry entry1 = createMockMemoryEntry("author1", "timestamp1");
    MemoryEntry entry2 = createMockMemoryEntry("author2", "timestamp2");
    MemoryEntry entry3 = createMockMemoryEntry("author3", "timestamp3");
    SearchMemoryResponse response =
        SearchMemoryResponse.builder()
            .setMemories(ImmutableList.of(entry1, entry2, entry3))
            .build();
    // Act
    ImmutableList<MemoryEntry> memories = response.memories();
    // Assert
    assertThat(memories).isNotNull();
    assertThat(memories).hasSize(3);
    assertThat(memories).containsExactly(entry1, entry2, entry3).inOrder();
  }
  @Test
  @Tag("boundary")
  void memoriesReturnsEmptyListWhenNoMemoriesSet() {
    // Arrange
    SearchMemoryResponse response = SearchMemoryResponse.builder().build();
    // Act
    ImmutableList<MemoryEntry> memories = response.memories();
    // Assert
    assertThat(memories).isNotNull();
    assertThat(memories).isEmpty();
    assertThat(memories.size()).isEqualTo(0);
  }
  @Test
  @Tag("valid")
  void memoriesReturnsImmutableList() {
    // Arrange
    MemoryEntry entry1 = createMockMemoryEntry("author1", "timestamp1");
    MemoryEntry entry2 = createMockMemoryEntry("author2", "timestamp2");
    SearchMemoryResponse response =
        SearchMemoryResponse.builder().setMemories(ImmutableList.of(entry1, entry2)).build();
    // Act
    ImmutableList<MemoryEntry> memories = response.memories();
    // Assert
    assertThrows(UnsupportedOperationException.class, () -> {
      memories.add(createMockMemoryEntry("author3", "timestamp3"));
    });
    assertThrows(UnsupportedOperationException.class, () -> {
      memories.remove(0);
    });
    assertThrows(UnsupportedOperationException.class, memories::clear);
    assertThat(memories).hasSize(2);
  }
  @Test
  @Tag("boundary")
  void memoriesReturnsSingleMemoryEntry() {
    // Arrange
    MemoryEntry entry = createMockMemoryEntry("author1", "timestamp1");
    SearchMemoryResponse response =
        SearchMemoryResponse.builder().setMemories(ImmutableList.of(entry)).build();
    // Act
    ImmutableList<MemoryEntry> memories = response.memories();
    // Assert
    assertThat(memories).isNotNull();
    assertThat(memories).hasSize(1);
    assertThat(memories.get(0)).isEqualTo(entry);
  }
  @Test
  @Tag("valid")
  void memoriesMaintainsInsertionOrder() {
    // Arrange
    MemoryEntry entry1 = createMockMemoryEntry("author1", "timestamp1");
    MemoryEntry entry2 = createMockMemoryEntry("author2", "timestamp2");
    MemoryEntry entry3 = createMockMemoryEntry("author3", "timestamp3");
    MemoryEntry entry4 = createMockMemoryEntry("author4", "timestamp4");
    SearchMemoryResponse response =
        SearchMemoryResponse.builder()
            .setMemories(ImmutableList.of(entry1, entry2, entry3, entry4))
            .build();
    // Act
    ImmutableList<MemoryEntry> memories = response.memories();
    // Assert
    assertThat(memories).isNotNull();
    assertThat(memories).hasSize(4);
    assertThat(memories.get(0)).isEqualTo(entry1);
    assertThat(memories.get(1)).isEqualTo(entry2);
    assertThat(memories.get(2)).isEqualTo(entry3);
    assertThat(memories.get(3)).isEqualTo(entry4);
    assertThat(memories).containsExactly(entry1, entry2, entry3, entry4).inOrder();
  }
  @Test
  @Tag("valid")
  void memoriesReturnsConsistentResultsOnMultipleCalls() {
    // Arrange
    MemoryEntry entry1 = createMockMemoryEntry("author1", "timestamp1");
    MemoryEntry entry2 = createMockMemoryEntry("author2", "timestamp2");
    SearchMemoryResponse response =
        SearchMemoryResponse.builder().setMemories(ImmutableList.of(entry1, entry2)).build();
    // Act
    ImmutableList<MemoryEntry> memories1 = response.memories();
    ImmutableList<MemoryEntry> memories2 = response.memories();
    ImmutableList<MemoryEntry> memories3 = response.memories();
    // Assert
    assertThat(memories1).containsExactly(entry1, entry2).inOrder();
    assertThat(memories2).containsExactly(entry1, entry2).inOrder();
    assertThat(memories3).containsExactly(entry1, entry2).inOrder();
    assertThat(memories1).isEqualTo(memories2);
    assertThat(memories2).isEqualTo(memories3);
  }
  @Test
  @Tag("invalid")
  void memoriesHandlesNullMemoryEntries() {
    // Arrange & Act & Assert
    List<MemoryEntry> listWithNull = new ArrayList<>();
    listWithNull.add(createMockMemoryEntry("author1", "timestamp1"));
    listWithNull.add(null);
    listWithNull.add(createMockMemoryEntry("author2", "timestamp2"));
    assertThrows(NullPointerException.class, () -> {
      SearchMemoryResponse.builder().setMemories(listWithNull).build();
    });
  }
  @Test
  @Tag("valid")
  void memoriesWorksWithListParameterInBuilder() {
    // Arrange
    MemoryEntry entry1 = createMockMemoryEntry("author1", "timestamp1");
    MemoryEntry entry2 = createMockMemoryEntry("author2", "timestamp2");
    MemoryEntry entry3 = createMockMemoryEntry("author3", "timestamp3");
    List<MemoryEntry> mutableList = new ArrayList<>();
    mutableList.add(entry1);
    mutableList.add(entry2);
    mutableList.add(entry3);
    SearchMemoryResponse response =
        SearchMemoryResponse.builder().setMemories(mutableList).build();
    // Act
    ImmutableList<MemoryEntry> memories = response.memories();
    // Assert
    assertThat(memories).isNotNull();
    assertThat(memories).hasSize(3);
    assertThat(memories).containsExactly(entry1, entry2, entry3).inOrder();
    assertThrows(UnsupportedOperationException.class, () -> {
      memories.add(createMockMemoryEntry("author4", "timestamp4"));
    });
  }
  @Test
  @Tag("valid")
  void memoriesIsIndependentFromSourceList() {
    // Arrange
    MemoryEntry entry1 = createMockMemoryEntry("author1", "timestamp1");
    MemoryEntry entry2 = createMockMemoryEntry("author2", "timestamp2");
    List<MemoryEntry> sourceList = new ArrayList<>();
    sourceList.add(entry1);
    sourceList.add(entry2);
    SearchMemoryResponse response =
        SearchMemoryResponse.builder().setMemories(sourceList).build();
    // Modify source list after building
    sourceList.add(createMockMemoryEntry("author3", "timestamp3"));
    sourceList.remove(0);
    // Act
    ImmutableList<MemoryEntry> memories = response.memories();
    // Assert
    assertThat(memories).isNotNull();
    assertThat(memories).hasSize(2);
    assertThat(memories).containsExactly(entry1, entry2).inOrder();
    assertThat(sourceList).hasSize(2);
    assertThat(sourceList).doesNotContain(entry1);
  }
  @Test
  @Tag("valid")
  void memoriesHandlesLargeNumberOfEntries() {
    // Arrange
    int largeSize = 10000;
    List<MemoryEntry> largeList = new ArrayList<>();
    for (int i = 0; i < largeSize; i++) {
      largeList.add(createMockMemoryEntry("author" + i, "timestamp" + i));
    }
    SearchMemoryResponse response =
        SearchMemoryResponse.builder().setMemories(largeList).build();
    // Act
    long startTime = System.currentTimeMillis();
    ImmutableList<MemoryEntry> memories = response.memories();
    long endTime = System.currentTimeMillis();
    // Assert
    assertThat(memories).isNotNull();
    assertThat(memories).hasSize(largeSize);
    assertThat(memories.get(0).author()).isEqualTo("author0");
    assertThat(memories.get(largeSize - 1).author()).isEqualTo("author" + (largeSize - 1));
    assertThat(endTime - startTime).isLessThan(5000);
  }
  private MemoryEntry createMockMemoryEntry(String author, String timestamp) {
    MemoryEntry entry = mock(MemoryEntry.class);
    when(entry.author()).thenReturn(author);
    when(entry.timestamp()).thenReturn(timestamp);
    when(entry.content()).thenReturn(mock(Content.class));
    return entry;
  }
}