/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-jan-5 using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=loadAgent_cf429451cb
ROOST_METHOD_SIG_HASH=loadAgent_3a5efc3d63

Scenario 1: Load Agent Successfully with Valid Name

Details:
  TestName: loadAgentWithValidName
  Description: This test verifies that the loadAgent method successfully retrieves and returns a BaseAgent instance when provided with a valid agent name that exists in the agents map. This is the primary happy path scenario for the method.
Execution:
  Arrange: Create a mock BaseAgent instance with a specific name (e.g., "testAgent"). Initialize AgentStaticLoader with this agent. Store the expected agent reference.
  Act: Invoke loadAgent method with the valid agent name "testAgent".
  Assert: Verify that the returned BaseAgent is not null and is the same instance as the expected agent using assertEquals or assertSame.
Validation:
  The assertion verifies that the method correctly retrieves the agent from the internal ImmutableMap when a valid name is provided. This is critical for the core functionality of the loader, ensuring that agents can be successfully loaded and used by the application. The test confirms that the mapping between agent names and instances is working correctly.

Scenario 2: Throw IllegalArgumentException When Name is Null

Details:
  TestName: loadAgentWithNullName
  Description: This test ensures that the loadAgent method properly validates input by throwing an IllegalArgumentException when a null value is passed as the agent name parameter. This validates the defensive programming approach and input validation.
Execution:
  Arrange: Create an AgentStaticLoader instance with at least one mock BaseAgent. Prepare to catch IllegalArgumentException.
  Act: Invoke loadAgent method with null as the name parameter.
  Assert: Use assertThrows to verify that IllegalArgumentException is thrown. Optionally verify the exception message contains "Agent name cannot be null or empty".
Validation:
  This assertion confirms that the method properly handles null input and prevents potential NullPointerException or unexpected behavior downstream. Input validation is crucial for maintaining system stability and providing clear error messages to callers. This test ensures that the contract of the method is enforced at the boundary.

Scenario 3: Throw IllegalArgumentException When Name is Empty String

Details:
  TestName: loadAgentWithEmptyString
  Description: This test verifies that the loadAgent method rejects empty string values by throwing an IllegalArgumentException. An empty string is considered invalid input as it cannot represent a valid agent name.
Execution:
  Arrange: Create an AgentStaticLoader instance with at least one mock BaseAgent. Prepare to catch IllegalArgumentException.
  Act: Invoke loadAgent method with an empty string "" as the name parameter.
  Assert: Use assertThrows to verify that IllegalArgumentException is thrown with an appropriate error message.
Validation:
  The assertion ensures that empty strings are treated as invalid input, preventing lookups with meaningless keys. This is important for maintaining data integrity and providing clear feedback about invalid requests. The test validates that the method distinguishes between null and empty strings but treats both as invalid.

Scenario 4: Throw IllegalArgumentException When Name is Whitespace Only

Details:
  TestName: loadAgentWithWhitespaceOnlyName
  Description: This test checks that the loadAgent method properly handles strings containing only whitespace characters (spaces, tabs, etc.) by throwing an IllegalArgumentException. The method uses trim() to detect such cases.
Execution:
  Arrange: Create an AgentStaticLoader instance with at least one mock BaseAgent. Prepare test data with whitespace-only strings like "   ", "\t", or " \n ".
  Act: Invoke loadAgent method with a whitespace-only string as the name parameter.
  Assert: Use assertThrows to verify that IllegalArgumentException is thrown.
Validation:
  This assertion confirms that the method's validation logic correctly identifies whitespace-only strings as invalid input through the trim().isEmpty() check. This prevents attempts to load agents with effectively empty names, which would be semantically meaningless. The test ensures robust input validation beyond just null and empty string checks.

Scenario 5: Throw NoSuchElementException When Agent Does Not Exist

Details:
  TestName: loadAgentWithNonExistentName
  Description: This test verifies that the loadAgent method throws a NoSuchElementException when attempting to load an agent that does not exist in the agents map. This tests the error handling for missing agents.
Execution:
  Arrange: Create an AgentStaticLoader instance with one or more mock BaseAgent instances with known names (e.g., "agent1", "agent2"). Prepare a non-existent agent name like "nonExistentAgent".
  Act: Invoke loadAgent method with the non-existent agent name.
  Assert: Use assertThrows to verify that NoSuchElementException is thrown. Verify the exception message contains "Agent not found: nonExistentAgent".
Validation:
  The assertion ensures that the method provides clear feedback when a requested agent cannot be found, using an appropriate exception type (NoSuchElementException) that semantically represents the error condition. This is important for error handling in calling code and for debugging purposes. The test validates that the method distinguishes between validation errors (IllegalArgumentException) and lookup failures (NoSuchElementException).

Scenario 6: Load Agent with Name Containing Leading Whitespace

Details:
  TestName: loadAgentWithLeadingWhitespace
  Description: This test verifies the behavior when an agent name with leading whitespace is provided. Since the validation uses trim().isEmpty(), a name like " validAgent" would pass validation but fail lookup if the actual agent name doesn't include the whitespace.
Execution:
  Arrange: Create a mock BaseAgent with name "validAgent" (no whitespace). Initialize AgentStaticLoader with this agent.
  Act: Invoke loadAgent method with " validAgent" (with leading space).
  Assert: Use assertThrows to verify that NoSuchElementException is thrown, as the trimmed validation passes but the map lookup fails.
Validation:
  This assertion verifies that the method's validation and lookup logic work correctly when names have leading whitespace. The validation passes because trim().isEmpty() returns false, but the lookup fails because ImmutableMap.get() uses the exact string with whitespace. This test highlights the importance of understanding that validation only checks for empty/null, not exact matching.

Scenario 7: Load Agent with Name Containing Trailing Whitespace

Details:
  TestName: loadAgentWithTrailingWhitespace
  Description: This test checks the behavior when an agent name with trailing whitespace is provided. Similar to leading whitespace, this should pass validation but fail during lookup if the agent was registered without trailing whitespace.
Execution:
  Arrange: Create a mock BaseAgent with name "validAgent" (no whitespace). Initialize AgentStaticLoader with this agent.
  Act: Invoke loadAgent method with "validAgent " (with trailing space).
  Assert: Use assertThrows to verify that NoSuchElementException is thrown.
Validation:
  The assertion confirms that trailing whitespace in the agent name causes a lookup failure even though validation passes. This test is important for understanding the exact matching behavior of the map lookup and ensures that callers must provide exact agent names without extraneous whitespace.

Scenario 8: Load Multiple Different Agents Successfully

Details:
  TestName: loadMultipleDifferentAgents
  Description: This test verifies that the loadAgent method can successfully retrieve multiple different agents from the loader when called multiple times with different valid agent names. This tests the method's consistency and reliability across multiple invocations.
Execution:
  Arrange: Create multiple mock BaseAgent instances with different names (e.g., "agent1", "agent2", "agent3"). Initialize AgentStaticLoader with all these agents.
  Act: Invoke loadAgent method multiple times with each agent name.
  Assert: Verify that each call returns the correct corresponding BaseAgent instance using assertEquals or assertSame for each agent.
Validation:
  This assertion ensures that the internal ImmutableMap correctly maintains multiple agent mappings and that the loadAgent method can reliably retrieve any agent from the collection. This test validates the scalability of the loader and confirms that multiple agents don't interfere with each other's retrieval.

Scenario 9: Load Same Agent Multiple Times Returns Same Instance

Details:
  TestName: loadSameAgentMultipleTimes
  Description: This test verifies that calling loadAgent multiple times with the same agent name returns the same BaseAgent instance each time, confirming that the method doesn't create new instances but retrieves the existing one.
Execution:
  Arrange: Create a mock BaseAgent with a specific name. Initialize AgentStaticLoader with this agent.
  Act: Invoke loadAgent method multiple times with the same agent name and store each returned reference.
  Assert: Use assertSame to verify that all returned references point to the exact same object instance.
Validation:
  The assertion confirms that the method returns references to the same agent instance rather than creating copies, which is important for maintaining state consistency and memory efficiency. This test validates that the loader acts as a registry rather than a factory, which is the expected behavior based on the class design.

Scenario 10: Load Agent with Case Sensitive Name

Details:
  TestName: loadAgentWithCaseSensitiveName
  Description: This test verifies that agent name lookup is case-sensitive by attempting to load an agent with a name that differs only in case from an existing agent name. This tests the exact matching behavior of the map lookup.
Execution:
  Arrange: Create a mock BaseAgent with name "TestAgent". Initialize AgentStaticLoader with this agent.
  Act: Invoke loadAgent method with "testagent" (different case).
  Assert: Use assertThrows to verify that NoSuchElementException is thrown.
Validation:
  The assertion confirms that the ImmutableMap lookup is case-sensitive and that agent names must match exactly including case. This is important for understanding the contract of the method and ensuring that callers use precise agent names. The test validates that "TestAgent" and "testagent" are treated as different keys.

Scenario 11: Load Agent from Empty Loader

Details:
  TestName: loadAgentFromEmptyLoader
  Description: This test verifies the behavior when attempting to load an agent from an AgentStaticLoader that was initialized with no agents. This tests the edge case of an empty agent collection.
Execution:
  Arrange: Create an AgentStaticLoader instance with no agents (empty varargs array).
  Act: Invoke loadAgent method with any valid non-empty agent name.
  Assert: Use assertThrows to verify that NoSuchElementException is thrown.
Validation:
  The assertion ensures that the method correctly handles the case where the agents map is empty, throwing an appropriate exception rather than returning null or causing other errors. This test validates that the loader can be instantiated with no agents and still maintains correct error handling behavior.

Scenario 12: Load Agent with Special Characters in Name

Details:
  TestName: loadAgentWithSpecialCharactersInName
  Description: This test verifies that the loadAgent method can successfully retrieve agents whose names contain special characters such as hyphens, underscores, dots, or other non-alphanumeric characters.
Execution:
  Arrange: Create mock BaseAgent instances with names containing special characters (e.g., "agent-1", "agent_2", "agent.3", "agent@4"). Initialize AgentStaticLoader with these agents.
  Act: Invoke loadAgent method with each special character name.
  Assert: Verify that each call successfully returns the correct BaseAgent instance.
Validation:
  The assertion confirms that the method and underlying ImmutableMap correctly handle agent names with special characters, which may be common in real-world scenarios. This test ensures that the loader doesn't impose unnecessary restrictions on agent naming conventions beyond the null/empty validation.

Scenario 13: Load Agent with Very Long Name

Details:
  TestName: loadAgentWithVeryLongName
  Description: This test verifies that the loadAgent method can handle agent names of significant length without performance issues or errors. This tests the method's robustness with edge case input sizes.
Execution:
  Arrange: Create a mock BaseAgent with a very long name (e.g., 1000+ characters). Initialize AgentStaticLoader with this agent.
  Act: Invoke loadAgent method with the very long agent name.
  Assert: Verify that the method successfully returns the correct BaseAgent instance.
Validation:
  The assertion ensures that the method doesn't have arbitrary length restrictions and can handle long agent names that might occur in certain scenarios. This test validates that the string comparison and map lookup operations work correctly regardless of string length, which is important for robustness.

Scenario 14: Load Agent with Unicode Characters in Name

Details:
  TestName: loadAgentWithUnicodeCharactersInName
  Description: This test verifies that the loadAgent method correctly handles agent names containing Unicode characters from various languages and symbol sets, ensuring international character support.
Execution:
  Arrange: Create mock BaseAgent instances with names containing Unicode characters (e.g., "агент", "代理", "وكيل", "🤖agent"). Initialize AgentStaticLoader with these agents.
  Act: Invoke loadAgent method with each Unicode name.
  Assert: Verify that each call successfully returns the correct BaseAgent instance.
Validation:
  The assertion confirms that the method properly supports internationalization and can handle agent names in various languages and character sets. This is important for applications that may be used globally or need to support non-ASCII agent identifiers. The test validates that string comparison works correctly with Unicode characters.

Scenario 15: Verify Exception Message for Null Name

Details:
  TestName: verifyExceptionMessageForNullName
  Description: This test specifically validates that the exception message thrown for null agent names is clear and informative, helping developers understand what went wrong.
Execution:
  Arrange: Create an AgentStaticLoader instance with at least one mock BaseAgent.
  Act: Invoke loadAgent method with null as the name parameter and catch the IllegalArgumentException.
  Assert: Verify that the exception message equals "Agent name cannot be null or empty" using assertEquals on the exception message.
Validation:
  The assertion ensures that the error message provides clear guidance about the validation failure, which is crucial for debugging and developer experience. Good error messages reduce troubleshooting time and improve code maintainability. This test validates that the exception not only has the correct type but also provides meaningful information.

Scenario 16: Verify Exception Message for Non-Existent Agent

Details:
  TestName: verifyExceptionMessageForNonExistentAgent
  Description: This test validates that the exception message thrown when an agent is not found includes the requested agent name, making it easier to identify which agent lookup failed.
Execution:
  Arrange: Create an AgentStaticLoader instance with known agents. Prepare a non-existent agent name like "missingAgent".
  Act: Invoke loadAgent method with the non-existent name and catch the NoSuchElementException.
  Assert: Verify that the exception message contains "Agent not found: missingAgent" using assertTrue with message.contains() or assertEquals.
Validation:
  The assertion confirms that the error message includes the specific agent name that was requested, which is essential for debugging in systems with multiple agents. This contextual information in the exception message helps developers quickly identify configuration or naming issues. The test ensures that error reporting is as helpful as possible.

Scenario 17: Load Agent After Loader Initialization

Details:
  TestName: loadAgentAfterLoaderInitialization
  Description: This test verifies that agents can be loaded immediately after the AgentStaticLoader is initialized, confirming that the constructor properly sets up the internal state.
Execution:
  Arrange: Create a mock BaseAgent with a specific name. Initialize AgentStaticLoader with this agent in the constructor.
  Act: Immediately invoke loadAgent method with the agent name without any intermediate operations.
  Assert: Verify that the method successfully returns the correct BaseAgent instance.
Validation:
  The assertion ensures that the AgentStaticLoader is fully functional immediately after construction and that the ImmutableMap is properly initialized in the constructor. This test validates the initialization logic and confirms that there are no lazy initialization issues or timing problems.

Scenario 18: Load Agent with Name Matching Exactly

Details:
  TestName: loadAgentWithExactNameMatch
  Description: This test explicitly verifies that agent names must match exactly, character-for-character, including all aspects of the string such as case, whitespace, and special characters.
Execution:
  Arrange: Create a mock BaseAgent with a specific name like "ExactAgentName". Initialize AgentStaticLoader with this agent.
  Act: Invoke loadAgent method with the exact same string "ExactAgentName".
  Assert: Verify that the method successfully returns the correct BaseAgent instance using assertNotNull and assertSame.
Validation:
  The assertion confirms the exact matching behavior of the map lookup, which is fundamental to understanding how the loader works. This test serves as documentation of the expected behavior and ensures that the string comparison is performed correctly without any normalization or transformation.

Scenario 19: Verify No Side Effects on Repeated Calls

Details:
  TestName: verifyNoSideEffectsOnRepeatedCalls
  Description: This test verifies that calling loadAgent multiple times does not cause any side effects or state changes in the loader or the returned agents, confirming the method's idempotent nature.
Execution:
  Arrange: Create a mock BaseAgent with a specific name. Initialize AgentStaticLoader with this agent.
  Act: Invoke loadAgent method multiple times (e.g., 10 times) with the same agent name.
  Assert: Verify that all calls return successfully and that each returned instance is the same object using assertSame.
Validation:
  The assertion ensures that the loadAgent method is a pure query operation that doesn't modify state, which is important for thread safety and predictable behavior. This test validates that the method can be called repeatedly without causing issues, which is essential for methods that may be called frequently in production systems.

Scenario 20: Load Agent with Single Character Name

Details:
  TestName: loadAgentWithSingleCharacterName
  Description: This test verifies that the loadAgent method correctly handles agent names consisting of a single character, testing the minimum valid name length edge case.
Execution:
  Arrange: Create a mock BaseAgent with a single character name like "A" or "1". Initialize AgentStaticLoader with this agent.
  Act: Invoke loadAgent method with the single character name.
  Assert: Verify that the method successfully returns the correct BaseAgent instance.
Validation:
  The assertion confirms that there is no minimum length requirement beyond non-empty for agent names, and that single character names are valid. This test validates that the validation logic (trim().isEmpty()) correctly allows single character strings, which is important for understanding the full range of valid inputs.

*/

// ********RoostGPT********

package com.google.adk.web;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.google.adk.agents.BaseAgent;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class AgentStaticLoaderLoadAgentTest {

  private BaseAgent mockAgent1;

  private BaseAgent mockAgent2;

  private BaseAgent mockAgent3;

  private AgentStaticLoader loader;

  @BeforeEach
  void setUp() {
    mockAgent1 = mock(BaseAgent.class);
    mockAgent2 = mock(BaseAgent.class);
    mockAgent3 = mock(BaseAgent.class);
  }

  @Test
  @Tag("valid")
  void loadAgentWithValidName() {
    when(mockAgent1.name()).thenReturn("testAgent");
    loader = new AgentStaticLoader(mockAgent1);
    BaseAgent result = loader.loadAgent("testAgent");
    assertNotNull(result);
    assertSame(mockAgent1, result);
  }

  @Test
  @Tag("invalid")
  void loadAgentWithNullName() {
    when(mockAgent1.name()).thenReturn("testAgent");
    loader = new AgentStaticLoader(mockAgent1);
    IllegalArgumentException exception =
        assertThrows(IllegalArgumentException.class, () -> loader.loadAgent(null));
    assertEquals("Agent name cannot be null or empty", exception.getMessage());
  }

  @Test
  @Tag("invalid")
  void loadAgentWithEmptyString() {
    when(mockAgent1.name()).thenReturn("testAgent");
    loader = new AgentStaticLoader(mockAgent1);
    IllegalArgumentException exception =
        assertThrows(IllegalArgumentException.class, () -> loader.loadAgent(""));
    assertEquals("Agent name cannot be null or empty", exception.getMessage());
  }

  @Test
  @Tag("boundary")
  void loadAgentWithWhitespaceOnlyName() {
    when(mockAgent1.name()).thenReturn("testAgent");
    loader = new AgentStaticLoader(mockAgent1);
    IllegalArgumentException exception =
        assertThrows(IllegalArgumentException.class, () -> loader.loadAgent("   "));
    assertEquals("Agent name cannot be null or empty", exception.getMessage());
  }

  @Test
  @Tag("invalid")
  void loadAgentWithNonExistentName() {
    when(mockAgent1.name()).thenReturn("agent1");
    when(mockAgent2.name()).thenReturn("agent2");
    loader = new AgentStaticLoader(mockAgent1, mockAgent2);
    NoSuchElementException exception =
        assertThrows(NoSuchElementException.class, () -> loader.loadAgent("nonExistentAgent"));
    assertTrue(exception.getMessage().contains("Agent not found: nonExistentAgent"));
  }

  @Test
  @Tag("boundary")
  void loadAgentWithLeadingWhitespace() {
    when(mockAgent1.name()).thenReturn("validAgent");
    loader = new AgentStaticLoader(mockAgent1);
    NoSuchElementException exception =
        assertThrows(NoSuchElementException.class, () -> loader.loadAgent(" validAgent"));
    assertTrue(exception.getMessage().contains("Agent not found:  validAgent"));
  }

  @Test
  @Tag("boundary")
  void loadAgentWithTrailingWhitespace() {
    when(mockAgent1.name()).thenReturn("validAgent");
    loader = new AgentStaticLoader(mockAgent1);
    NoSuchElementException exception =
        assertThrows(NoSuchElementException.class, () -> loader.loadAgent("validAgent "));
    assertTrue(exception.getMessage().contains("Agent not found: validAgent "));
  }

  @Test
  @Tag("valid")
  void loadMultipleDifferentAgents() {
    when(mockAgent1.name()).thenReturn("agent1");
    when(mockAgent2.name()).thenReturn("agent2");
    when(mockAgent3.name()).thenReturn("agent3");
    loader = new AgentStaticLoader(mockAgent1, mockAgent2, mockAgent3);
    BaseAgent result1 = loader.loadAgent("agent1");
    BaseAgent result2 = loader.loadAgent("agent2");
    BaseAgent result3 = loader.loadAgent("agent3");
    assertSame(mockAgent1, result1);
    assertSame(mockAgent2, result2);
    assertSame(mockAgent3, result3);
  }

  @Test
  @Tag("valid")
  void loadSameAgentMultipleTimes() {
    when(mockAgent1.name()).thenReturn("testAgent");
    loader = new AgentStaticLoader(mockAgent1);
    BaseAgent result1 = loader.loadAgent("testAgent");
    BaseAgent result2 = loader.loadAgent("testAgent");
    BaseAgent result3 = loader.loadAgent("testAgent");
    assertSame(result1, result2);
    assertSame(result2, result3);
    assertSame(mockAgent1, result1);
  }

  @Test
  @Tag("boundary")
  void loadAgentWithCaseSensitiveName() {
    when(mockAgent1.name()).thenReturn("TestAgent");
    loader = new AgentStaticLoader(mockAgent1);
    NoSuchElementException exception =
        assertThrows(NoSuchElementException.class, () -> loader.loadAgent("testagent"));
    assertTrue(exception.getMessage().contains("Agent not found: testagent"));
  }

  @Test
  @Tag("boundary")
  void loadAgentFromEmptyLoader() {
    loader = new AgentStaticLoader();
    NoSuchElementException exception =
        assertThrows(NoSuchElementException.class, () -> loader.loadAgent("anyAgent"));
    assertTrue(exception.getMessage().contains("Agent not found: anyAgent"));
  }

  @Test
  @Tag("valid")
  void loadAgentWithSpecialCharactersInName() {
    BaseAgent agent1 = mock(BaseAgent.class);
    BaseAgent agent2 = mock(BaseAgent.class);
    BaseAgent agent3 = mock(BaseAgent.class);
    BaseAgent agent4 = mock(BaseAgent.class);
    when(agent1.name()).thenReturn("agent-1");
    when(agent2.name()).thenReturn("agent_2");
    when(agent3.name()).thenReturn("agent.3");
    when(agent4.name()).thenReturn("agent@4");
    loader = new AgentStaticLoader(agent1, agent2, agent3, agent4);
    BaseAgent result1 = loader.loadAgent("agent-1");
    BaseAgent result2 = loader.loadAgent("agent_2");
    BaseAgent result3 = loader.loadAgent("agent.3");
    BaseAgent result4 = loader.loadAgent("agent@4");
    assertSame(agent1, result1);
    assertSame(agent2, result2);
    assertSame(agent3, result3);
    assertSame(agent4, result4);
  }

  @Test
  @Tag("boundary")
  void loadAgentWithVeryLongName() {
    String longName = "a".repeat(1000);
    when(mockAgent1.name()).thenReturn(longName);
    loader = new AgentStaticLoader(mockAgent1);
    BaseAgent result = loader.loadAgent(longName);
    assertNotNull(result);
    assertSame(mockAgent1, result);
  }

  @Test
  @Tag("valid")
  void loadAgentWithUnicodeCharactersInName() {
    BaseAgent agent1 = mock(BaseAgent.class);
    BaseAgent agent2 = mock(BaseAgent.class);
    BaseAgent agent3 = mock(BaseAgent.class);
    BaseAgent agent4 = mock(BaseAgent.class);
    when(agent1.name()).thenReturn("агент");
    when(agent2.name()).thenReturn("代理");
    when(agent3.name()).thenReturn("وكيل");
    when(agent4.name()).thenReturn("🤖agent");
    loader = new AgentStaticLoader(agent1, agent2, agent3, agent4);
    BaseAgent result1 = loader.loadAgent("агент");
    BaseAgent result2 = loader.loadAgent("代理");
    BaseAgent result3 = loader.loadAgent("وكيل");
    BaseAgent result4 = loader.loadAgent("🤖agent");
    assertSame(agent1, result1);
    assertSame(agent2, result2);
    assertSame(agent3, result3);
    assertSame(agent4, result4);
  }

  @Test
  @Tag("invalid")
  void verifyExceptionMessageForNullName() {
    when(mockAgent1.name()).thenReturn("testAgent");
    loader = new AgentStaticLoader(mockAgent1);
    IllegalArgumentException exception =
        assertThrows(IllegalArgumentException.class, () -> loader.loadAgent(null));
    assertEquals("Agent name cannot be null or empty", exception.getMessage());
  }

  @Test
  @Tag("invalid")
  void verifyExceptionMessageForNonExistentAgent() {
    when(mockAgent1.name()).thenReturn("existingAgent");
    loader = new AgentStaticLoader(mockAgent1);
    NoSuchElementException exception =
        assertThrows(NoSuchElementException.class, () -> loader.loadAgent("missingAgent"));
    assertEquals("Agent not found: missingAgent", exception.getMessage());
  }

  @Test
  @Tag("valid")
  void loadAgentAfterLoaderInitialization() {
    when(mockAgent1.name()).thenReturn("immediateAgent");
    loader = new AgentStaticLoader(mockAgent1);
    BaseAgent result = loader.loadAgent("immediateAgent");
    assertNotNull(result);
    assertSame(mockAgent1, result);
  }

  @Test
  @Tag("valid")
  void loadAgentWithExactNameMatch() {
    when(mockAgent1.name()).thenReturn("ExactAgentName");
    loader = new AgentStaticLoader(mockAgent1);
    BaseAgent result = loader.loadAgent("ExactAgentName");
    assertNotNull(result);
    assertSame(mockAgent1, result);
  }

  @Test
  @Tag("valid")
  void verifyNoSideEffectsOnRepeatedCalls() {
    when(mockAgent1.name()).thenReturn("repeatAgent");
    loader = new AgentStaticLoader(mockAgent1);
    BaseAgent result1 = loader.loadAgent("repeatAgent");
    BaseAgent result2 = loader.loadAgent("repeatAgent");
    BaseAgent result3 = loader.loadAgent("repeatAgent");
    BaseAgent result4 = loader.loadAgent("repeatAgent");
    BaseAgent result5 = loader.loadAgent("repeatAgent");
    BaseAgent result6 = loader.loadAgent("repeatAgent");
    BaseAgent result7 = loader.loadAgent("repeatAgent");
    BaseAgent result8 = loader.loadAgent("repeatAgent");
    BaseAgent result9 = loader.loadAgent("repeatAgent");
    BaseAgent result10 = loader.loadAgent("repeatAgent");
    assertSame(mockAgent1, result1);
    assertSame(result1, result2);
    assertSame(result2, result3);
    assertSame(result3, result4);
    assertSame(result4, result5);
    assertSame(result5, result6);
    assertSame(result6, result7);
    assertSame(result7, result8);
    assertSame(result8, result9);
    assertSame(result9, result10);
  }

  @Test
  @Tag("boundary")
  void loadAgentWithSingleCharacterName() {
    when(mockAgent1.name()).thenReturn("A");
    when(mockAgent2.name()).thenReturn("1");
    loader = new AgentStaticLoader(mockAgent1, mockAgent2);
    BaseAgent result1 = loader.loadAgent("A");
    BaseAgent result2 = loader.loadAgent("1");
    assertNotNull(result1);
    assertNotNull(result2);
    assertSame(mockAgent1, result1);
    assertSame(mockAgent2, result2);
  }
}
