/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test Java-ADK-11-02_clone using AI Type Claude AI and AI Model claude-opus-4-6

ROOST_METHOD_HASH=loadAgent_cf429451cb
ROOST_METHOD_SIG_HASH=loadAgent_3a5efc3d63

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/Java-ADK-11-02_clone/b3b53859-1621-403b-9bca-a5d4d56046d9/source/adk-java/dev/src/test/java/com/google/adk/web/AgentStaticLoaderTest.java
Tests:
    "@Test
public void testAgentStaticLoaderApproach() {
    BaseAgent testAgent = LlmAgent.builder().name("test_agent").model("gemini-2.0-flash-lite").description("Test agent for demonstrating AgentStaticLoader").instruction("You are a test agent.").build();
    AgentStaticLoader staticLoader = new AgentStaticLoader(testAgent);
    assertTrue(staticLoader.listAgents().contains("test_agent"));
    assertEquals(testAgent, staticLoader.loadAgent("test_agent"));
    assertEquals("test_agent", staticLoader.loadAgent("test_agent").name());
}
"Scenario 1: Successfully load an existing agent by name

Details:
  TestName: loadAgentWithValidNameReturnsCorrectAgent
  Description: Verify that calling loadAgent with a valid agent name that exists in the loader returns the correct BaseAgent instance.
Execution:
  Arrange: Create a BaseAgent instance with a known name (e.g., "my_agent") and construct an AgentStaticLoader with that agent.
  Act: Call loadAgent("my_agent") on the AgentStaticLoader instance.
  Assert: Assert that the returned BaseAgent is the same instance as the one originally provided, and that its name matches "my_agent".
Validation:
  The assertion verifies that the loader correctly retrieves and returns the agent mapped to the given name. This is the primary happy-path scenario ensuring the core lookup functionality works as expected.

---

Scenario 2: Throw IllegalArgumentException when name is null

Details:
  TestName: loadAgentWithNullNameThrowsIllegalArgumentException
  Description: Verify that passing null as the agent name to loadAgent throws an IllegalArgumentException with an appropriate message.
Execution:
  Arrange: Create an AgentStaticLoader with at least one valid agent.
  Act: Call loadAgent(null) on the AgentStaticLoader instance.
  Assert: Assert that an IllegalArgumentException is thrown and the message contains "Agent name cannot be null or empty".
Validation:
  The assertion confirms that the method properly validates input and rejects null values. This guards against NullPointerException deeper in the code and provides a clear error message to the caller.

---

Scenario 3: Throw IllegalArgumentException when name is an empty string

Details:
  TestName: loadAgentWithEmptyNameThrowsIllegalArgumentException
  Description: Verify that passing an empty string ("") as the agent name to loadAgent throws an IllegalArgumentException.
Execution:
  Arrange: Create an AgentStaticLoader with at least one valid agent.
  Act: Call loadAgent("") on the AgentStaticLoader instance.
  Assert: Assert that an IllegalArgumentException is thrown and the message contains "Agent name cannot be null or empty".
Validation:
  The assertion ensures that empty strings are treated as invalid input, preventing accidental lookups with meaningless keys. This is an important edge case for input validation.

---

Scenario 4: Throw IllegalArgumentException when name is a whitespace-only string

Details:
  TestName: loadAgentWithWhitespaceOnlyNameThrowsIllegalArgumentException
  Description: Verify that passing a string consisting only of whitespace characters (e.g., "   ") to loadAgent throws an IllegalArgumentException.
Execution:
  Arrange: Create an AgentStaticLoader with at least one valid agent.
  Act: Call loadAgent("   ") on the AgentStaticLoader instance.
  Assert: Assert that an IllegalArgumentException is thrown and the message contains "Agent name cannot be null or empty".
Validation:
  The assertion verifies that the trim().isEmpty() check correctly identifies whitespace-only strings as invalid. This prevents agents from being looked up with names that appear empty after trimming.

---

Scenario 5: Throw NoSuchElementException when agent name does not exist

Details:
  TestName: loadAgentWithNonExistentNameThrowsNoSuchElementException
  Description: Verify that passing a name that does not correspond to any loaded agent throws a NoSuchElementException with a message indicating the missing agent.
Execution:
  Arrange: Create an AgentStaticLoader with an agent named "existing_agent".
  Act: Call loadAgent("non_existent_agent") on the AgentStaticLoader instance.
  Assert: Assert that a NoSuchElementException is thrown and the message contains "Agent not found: non_existent_agent".
Validation:
  The assertion confirms that the method correctly distinguishes between existing and non-existing agents and provides a descriptive error message. This is critical for debugging when an incorrect agent name is used.

---

Scenario 6: Load the correct agent when multiple agents are registered

Details:
  TestName: loadAgentFromMultipleAgentsReturnsCorrectOne
  Description: Verify that when the AgentStaticLoader is initialized with multiple agents, loadAgent returns the correct agent corresponding to the requested name.
Execution:
  Arrange: Create three distinct BaseAgent instances with names "agent_a", "agent_b", and "agent_c". Construct an AgentStaticLoader with all three agents.
  Act: Call loadAgent("agent_b") on the AgentStaticLoader instance.
  Assert: Assert that the returned agent's name is "agent_b" and that it is the exact same instance as the one originally created for "agent_b".
Validation:
  The assertion verifies that the internal ImmutableMap correctly maps each agent by name and that the lookup retrieves the precise agent requested, even when multiple agents are present.

---

Scenario 7: Throw NoSuchElementException for a name with leading/trailing whitespace that does not match any agent

Details:
  TestName: loadAgentWithNameContainingLeadingTrailingSpacesThrowsNoSuchElementException
  Description: Verify that a name with leading or trailing spaces (e.g., " my_agent ") does not match an agent named "my_agent" because the lookup uses the untrimmed name, resulting in a NoSuchElementException.
Execution:
  Arrange: Create an AgentStaticLoader with an agent named "my_agent".
  Act: Call loadAgent(" my_agent ") on the AgentStaticLoader instance.
  Assert: Assert that a NoSuchElementException is thrown, since the map key "my_agent" does not match " my_agent ".
Validation:
  The assertion verifies that the method does not trim the name before performing the lookup (trimming is only used for the empty check). This confirms that agent name matching is exact, which is important for consistent and predictable behavior.

---

Scenario 8: Throw IllegalArgumentException when name is a single tab character

Details:
  TestName: loadAgentWithTabCharacterNameThrowsIllegalArgumentException
  Description: Verify that passing a string containing only a tab character ("\t") to loadAgent throws an IllegalArgumentException, since trim() removes tabs and the result is empty.
Execution:
  Arrange: Create an AgentStaticLoader with at least one valid agent.
  Act: Call loadAgent("\t") on the AgentStaticLoader instance.
  Assert: Assert that an IllegalArgumentException is thrown with the message "Agent name cannot be null or empty".
Validation:
  The assertion confirms that the trim() method handles various whitespace characters (not just spaces) and that such inputs are correctly rejected. This covers an edge case for non-standard whitespace input.

---

Scenario 9: Load agent from a loader initialized with a single agent

Details:
  TestName: loadAgentFromSingleAgentLoaderReturnsAgent
  Description: Verify that an AgentStaticLoader initialized with exactly one agent can successfully return that agent when loadAgent is called with the correct name.
Execution:
  Arrange: Create a single BaseAgent instance with the name "solo_agent" and construct an AgentStaticLoader with only that agent.
  Act: Call loadAgent("solo_agent") on the AgentStaticLoader instance.
  Assert: Assert that the returned BaseAgent is not null and is the same instance as the one provided during construction.
Validation:
  The assertion verifies the simplest valid use case — a single agent in the loader. This ensures the loader works correctly even with the minimal configuration.

---

Scenario 10: Throw NoSuchElementException for a case-sensitive name mismatch

Details:
  TestName: loadAgentWithDifferentCaseNameThrowsNoSuchElementException
  Description: Verify that agent name lookup is case-sensitive. If an agent is registered as "MyAgent", calling loadAgent("myagent") should throw a NoSuchElementException.
Execution:
  Arrange: Create an AgentStaticLoader with an agent named "MyAgent".
  Act: Call loadAgent("myagent") on the AgentStaticLoader instance.
  Assert: Assert that a NoSuchElementException is thrown with a message containing "Agent not found: myagent".
Validation:
  The assertion confirms that the ImmutableMap-based lookup is case-sensitive, which is the default behavior for string keys. This is important to ensure that agent names are treated precisely and no unintended matches occur due to case insensitivity.

---

Scenario 11: Throw IllegalArgumentException when name is a newline character

Details:
  TestName: loadAgentWithNewlineCharacterNameThrowsIllegalArgumentException
  Description: Verify that passing a string containing only a newline character ("\n") to loadAgent throws an IllegalArgumentException, since trim() removes newline characters and the result is empty.
Execution:
  Arrange: Create an AgentStaticLoader with at least one valid agent.
  Act: Call loadAgent("\n") on the AgentStaticLoader instance.
  Assert: Assert that an IllegalArgumentException is thrown with the message "Agent name cannot be null or empty".
Validation:
  The assertion ensures that newline-only strings are treated as empty after trimming, reinforcing the robustness of the input validation against various whitespace-like characters.

---

Scenario 12: Throw NoSuchElementException with correct agent name in the error message

Details:
  TestName: loadAgentNotFoundExceptionMessageContainsRequestedName
  Description: Verify that when a NoSuchElementException is thrown, the exception message includes the exact name that was requested, aiding in debugging.
Execution:
  Arrange: Create an AgentStaticLoader with an agent named "registered_agent".
  Act: Call loadAgent("unknown_agent_xyz") on the AgentStaticLoader instance and capture the exception.
  Assert: Assert that the NoSuchElementException message is exactly "Agent not found: unknown_agent_xyz".
Validation:
  The assertion verifies that the error message is informative and includes the specific agent name that was not found. This is important for operational debugging and logging purposes.

*/

// ********RoostGPT********

package com.google.adk.web;

import static com.google.common.truth.Truth.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;
import com.google.adk.agents.BaseAgent;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.*;
import static com.google.common.collect.ImmutableList.toImmutableList;
import static com.google.common.collect.ImmutableMap.toImmutableMap;
import static java.util.Arrays.stream;
import static java.util.function.Function.identity;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import javax.annotation.Nonnull;

public class AgentStaticLoaderLoadAgentTest {

	private BaseAgent mockAgentA;

	private BaseAgent mockAgentB;

	private BaseAgent mockAgentC;

	private BaseAgent mockMyAgent;

	private BaseAgent mockSoloAgent;

	private BaseAgent mockCaseSensitiveAgent;

	@BeforeEach
	void setUp() {
		mockAgentA = mock(BaseAgent.class);
		when(mockAgentA.name()).thenReturn("agent_a");
		mockAgentB = mock(BaseAgent.class);
		when(mockAgentB.name()).thenReturn("agent_b");
		mockAgentC = mock(BaseAgent.class);
		when(mockAgentC.name()).thenReturn("agent_c");
		mockMyAgent = mock(BaseAgent.class);
		when(mockMyAgent.name()).thenReturn("my_agent");
		mockSoloAgent = mock(BaseAgent.class);
		when(mockSoloAgent.name()).thenReturn("solo_agent");
		mockCaseSensitiveAgent = mock(BaseAgent.class);
		when(mockCaseSensitiveAgent.name()).thenReturn("MyAgent");
	}

	@Test
	@Tag("valid")
	void loadAgentWithValidNameReturnsCorrectAgent() {
		AgentStaticLoader loader = new AgentStaticLoader(mockMyAgent);
		BaseAgent result = loader.loadAgent("my_agent");
		assertSame(mockMyAgent, result);
		assertThat(result.name()).isEqualTo("my_agent");
	}

	@Test
	@Tag("invalid")
	void loadAgentWithNullNameThrowsIllegalArgumentException() {
		AgentStaticLoader loader = new AgentStaticLoader(mockMyAgent);
		IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> loader.loadAgent(null));
		assertThat(exception.getMessage()).contains("Agent name cannot be null or empty");
	}

	@Test
	@Tag("invalid")
	void loadAgentWithEmptyNameThrowsIllegalArgumentException() {
		AgentStaticLoader loader = new AgentStaticLoader(mockMyAgent);
		IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> loader.loadAgent(""));
		assertThat(exception.getMessage()).contains("Agent name cannot be null or empty");
	}

	@Test
	@Tag("boundary")
	void loadAgentWithWhitespaceOnlyNameThrowsIllegalArgumentException() {
		AgentStaticLoader loader = new AgentStaticLoader(mockMyAgent);
		IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
				() -> loader.loadAgent("   "));
		assertThat(exception.getMessage()).contains("Agent name cannot be null or empty");
	}

	@Test
	@Tag("invalid")
	void loadAgentWithNonExistentNameThrowsNoSuchElementException() {
		BaseAgent existingAgent = mock(BaseAgent.class);
		when(existingAgent.name()).thenReturn("existing_agent");
		AgentStaticLoader loader = new AgentStaticLoader(existingAgent);
		NoSuchElementException exception = assertThrows(NoSuchElementException.class,
				() -> loader.loadAgent("non_existent_agent"));
		assertThat(exception.getMessage()).contains("Agent not found: non_existent_agent");
	}

	@Test
	@Tag("valid")
	void loadAgentFromMultipleAgentsReturnsCorrectOne() {
		AgentStaticLoader loader = new AgentStaticLoader(mockAgentA, mockAgentB, mockAgentC);
		BaseAgent result = loader.loadAgent("agent_b");
		assertSame(mockAgentB, result);
		assertThat(result.name()).isEqualTo("agent_b");
	}

	@Test
	@Tag("boundary")
	void loadAgentWithNameContainingLeadingTrailingSpacesThrowsNoSuchElementException() {
		AgentStaticLoader loader = new AgentStaticLoader(mockMyAgent);
		NoSuchElementException exception = assertThrows(NoSuchElementException.class,
				() -> loader.loadAgent(" my_agent "));
		assertThat(exception.getMessage()).contains("Agent not found:");
	}

	@Test
	@Tag("boundary")
	void loadAgentWithTabCharacterNameThrowsIllegalArgumentException() {
		AgentStaticLoader loader = new AgentStaticLoader(mockMyAgent);
		IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> loader.loadAgent("\t"));
		assertThat(exception.getMessage()).contains("Agent name cannot be null or empty");
	}

	@Test
	@Tag("valid")
	void loadAgentFromSingleAgentLoaderReturnsAgent() {
		AgentStaticLoader loader = new AgentStaticLoader(mockSoloAgent);
		BaseAgent result = loader.loadAgent("solo_agent");
		assertNotNull(result);
		assertSame(mockSoloAgent, result);
	}

	@Test
	@Tag("invalid")
	void loadAgentWithDifferentCaseNameThrowsNoSuchElementException() {
		AgentStaticLoader loader = new AgentStaticLoader(mockCaseSensitiveAgent);
		NoSuchElementException exception = assertThrows(NoSuchElementException.class,
				() -> loader.loadAgent("myagent"));
		assertThat(exception.getMessage()).contains("Agent not found: myagent");
	}

	@Test
	@Tag("boundary")
	void loadAgentWithNewlineCharacterNameThrowsIllegalArgumentException() {
		AgentStaticLoader loader = new AgentStaticLoader(mockMyAgent);
		IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> loader.loadAgent("\n"));
		assertThat(exception.getMessage()).contains("Agent name cannot be null or empty");
	}

	@Test
	@Tag("invalid")
	void loadAgentNotFoundExceptionMessageContainsRequestedName() {
		BaseAgent registeredAgent = mock(BaseAgent.class);
		when(registeredAgent.name()).thenReturn("registered_agent");
		AgentStaticLoader loader = new AgentStaticLoader(registeredAgent);
		NoSuchElementException exception = assertThrows(NoSuchElementException.class,
				() -> loader.loadAgent("unknown_agent_xyz"));
		assertThat(exception.getMessage()).isEqualTo("Agent not found: unknown_agent_xyz");
	}

}