/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test Java-ADK-11-02_clone using AI Type Claude AI and AI Model claude-opus-4-6

ROOST_METHOD_HASH=listAgents_a5d8927a63
ROOST_METHOD_SIG_HASH=listAgents_ec9d5bef7e

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/Java-ADK-11-02_clone/b3b53859-1621-403b-9bca-a5d4d56046d9/source/adk-java/dev/src/test/java/com/google/adk/web/AgentStaticLoaderTest.java
Tests:
    "@Test
public void testAgentStaticLoaderApproach() {
    BaseAgent testAgent = LlmAgent.builder().name("test_agent").model("gemini-2.0-flash-lite").description("Test agent for demonstrating AgentStaticLoader").instruction("You are a test agent.").build();
    AgentStaticLoader staticLoader = new AgentStaticLoader(testAgent);
    assertTrue(staticLoader.listAgents().contains("test_agent"));
    assertEquals(testAgent, staticLoader.loadAgent("test_agent"));
    assertEquals("test_agent", staticLoader.loadAgent("test_agent").name());
}
"Scenario 1: List agents returns a single agent name when loader is constructed with one agent

Details:
  TestName: listAgentsReturnsSingleAgentNameWhenOneAgentProvided
  Description: Verify that when an AgentStaticLoader is constructed with exactly one BaseAgent, the listAgents method returns an ImmutableList containing exactly that agent's name.
Execution:
  Arrange: Create a single BaseAgent with a known name (e.g., "agent_one") and construct an AgentStaticLoader with that agent.
  Act: Call listAgents() on the AgentStaticLoader instance.
  Assert: Assert that the returned list has size 1 and contains the string "agent_one".
Validation:
  This assertion verifies that the method correctly extracts the key set from the internal agents map and returns it as an ImmutableList. It confirms the basic functionality of listAgents when a single agent is loaded.

---

Scenario 2: List agents returns multiple agent names when loader is constructed with multiple agents

Details:
  TestName: listAgentsReturnsMultipleAgentNamesWhenMultipleAgentsProvided
  Description: Verify that when an AgentStaticLoader is constructed with multiple BaseAgent instances, the listAgents method returns an ImmutableList containing all of their names.
Execution:
  Arrange: Create three BaseAgent instances with distinct names (e.g., "agent_alpha", "agent_beta", "agent_gamma") and construct an AgentStaticLoader with all three.
  Act: Call listAgents() on the AgentStaticLoader instance.
  Assert: Assert that the returned list has size 3 and contains "agent_alpha", "agent_beta", and "agent_gamma".
Validation:
  This assertion verifies that the method correctly handles multiple agents and returns all their names. It ensures the varargs constructor properly populates the internal map and that listAgents reflects all entries.

---

Scenario 3: List agents returns an empty list when no agents are provided

Details:
  TestName: listAgentsReturnsEmptyListWhenNoAgentsProvided
  Description: Verify that when an AgentStaticLoader is constructed with no agents (empty varargs), the listAgents method returns an empty ImmutableList.
Execution:
  Arrange: Construct an AgentStaticLoader with no arguments (i.e., new AgentStaticLoader()).
  Act: Call listAgents() on the AgentStaticLoader instance.
  Assert: Assert that the returned list is empty (size 0) and that isEmpty() returns true.
Validation:
  This assertion verifies the edge case where no agents are loaded. The method should gracefully return an empty list rather than throwing an exception or returning null. This is important for defensive programming and ensuring the loader works correctly in degenerate cases.

---

Scenario 4: List agents returns an ImmutableList that cannot be modified

Details:
  TestName: listAgentsReturnsImmutableList
  Description: Verify that the list returned by listAgents is an instance of ImmutableList and cannot be modified (e.g., attempting to add an element throws an UnsupportedOperationException).
Execution:
  Arrange: Create a BaseAgent with a known name and construct an AgentStaticLoader with it.
  Act: Call listAgents() on the AgentStaticLoader instance and attempt to add a new element to the returned list.
  Assert: Assert that the returned list is an instance of ImmutableList and that calling add() on it throws an UnsupportedOperationException.
Validation:
  This assertion verifies the immutability contract of the return type. Since the method signature declares ImmutableList<String>, callers should not be able to mutate the returned collection. This is significant for thread safety and ensuring the internal state of the loader cannot be corrupted externally.

---

Scenario 5: List agents returns consistent results on repeated calls

Details:
  TestName: listAgentsReturnsConsistentResultsOnRepeatedCalls
  Description: Verify that calling listAgents multiple times on the same AgentStaticLoader instance returns the same set of agent names each time.
Execution:
  Arrange: Create two BaseAgent instances with names "agent_x" and "agent_y" and construct an AgentStaticLoader with them.
  Act: Call listAgents() twice on the AgentStaticLoader instance, storing the results in two separate variables.
  Assert: Assert that both returned lists contain the same elements and have the same size.
Validation:
  This assertion verifies idempotency of the listAgents method. Since the internal agents map is final and immutable, repeated calls should always yield the same results. This is important for ensuring predictable behavior in applications that may query the agent list multiple times.

---

Scenario 6: List agents contains only agent names and no other data

Details:
  TestName: listAgentsContainsOnlyAgentNamesAsStrings
  Description: Verify that the list returned by listAgents contains only the names (String keys) of the agents and that each element matches the name of a corresponding agent that was provided during construction.
Execution:
  Arrange: Create two BaseAgent instances with names "service_agent" and "helper_agent" and construct an AgentStaticLoader with them.
  Act: Call listAgents() on the AgentStaticLoader instance.
  Assert: Assert that every element in the returned list is one of "service_agent" or "helper_agent", and that the list size equals 2.
Validation:
  This assertion verifies that the method correctly maps from the internal ImmutableMap's key set to a list of strings. It ensures no extraneous or unexpected entries appear in the result, confirming the integrity of the data flow from constructor to listAgents.

---

Scenario 7: List agents does not return null

Details:
  TestName: listAgentsNeverReturnsNull
  Description: Verify that the listAgents method never returns null, even when the loader is constructed with no agents.
Execution:
  Arrange: Construct an AgentStaticLoader with no arguments.
  Act: Call listAgents() on the AgentStaticLoader instance.
  Assert: Assert that the returned value is not null.
Validation:
  This assertion verifies the non-null contract of the method, which is annotated with @Nonnull. Returning null would violate the method's contract and could cause NullPointerExceptions in calling code. This test ensures robustness of the API.

---

Scenario 8: List agents with two agents having distinct names preserves both names

Details:
  TestName: listAgentsPreservesDistinctAgentNames
  Description: Verify that when two agents with completely different names are provided, both names appear in the returned list from listAgents.
Execution:
  Arrange: Create two BaseAgent instances with names "first_agent" and "second_agent" and construct an AgentStaticLoader with both.
  Act: Call listAgents() on the AgentStaticLoader instance.
  Assert: Assert that the returned list contains both "first_agent" and "second_agent" and has exactly 2 elements.
Validation:
  This assertion confirms that the loader correctly stores and retrieves multiple distinct agent names. It validates the fundamental mapping behavior where each agent's name serves as a unique key in the internal map and is faithfully returned by listAgents.

*/

// ********RoostGPT********

package com.google.adk.web;

import static com.google.common.truth.Truth.assertThat;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;
import com.google.adk.agents.BaseAgent;
import com.google.common.collect.ImmutableList;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.*;
import static com.google.common.collect.ImmutableList.toImmutableList;
import static com.google.common.collect.ImmutableMap.toImmutableMap;
import static java.util.Arrays.stream;
import static java.util.function.Function.identity;
import com.google.common.collect.ImmutableMap;
import java.util.NoSuchElementException;
import javax.annotation.Nonnull;

public class AgentStaticLoaderListAgentsTest {

	private BaseAgent createMockAgent(String name) {
		BaseAgent agent = mock(BaseAgent.class);
		when(agent.name()).thenReturn(name);
		return agent;
	}

	@Test
	@Tag("valid")
	void listAgentsReturnsSingleAgentNameWhenOneAgentProvided() {
		// Arrange
		BaseAgent agentOne = createMockAgent("agent_one");
		AgentStaticLoader loader = new AgentStaticLoader(agentOne);
		// Act
		ImmutableList<String> result = loader.listAgents();
		// Assert
		assertThat(result).hasSize(1);
		assertThat(result).contains("agent_one");
	}

	@Test
	@Tag("valid")
	void listAgentsReturnsMultipleAgentNamesWhenMultipleAgentsProvided() {
		// Arrange
		BaseAgent agentAlpha = createMockAgent("agent_alpha");
		BaseAgent agentBeta = createMockAgent("agent_beta");
		BaseAgent agentGamma = createMockAgent("agent_gamma");
		AgentStaticLoader loader = new AgentStaticLoader(agentAlpha, agentBeta, agentGamma);
		// Act
		ImmutableList<String> result = loader.listAgents();
		// Assert
		assertThat(result).hasSize(3);
		assertThat(result).containsExactly("agent_alpha", "agent_beta", "agent_gamma");
	}

	@Test
	@Tag("boundary")
	void listAgentsReturnsEmptyListWhenNoAgentsProvided() {
		// Arrange
		AgentStaticLoader loader = new AgentStaticLoader();
		// Act
		ImmutableList<String> result = loader.listAgents();
		// Assert
		assertThat(result).isEmpty();
		assertThat(result).hasSize(0);
	}

	@Test
	@Tag("valid")
	void listAgentsReturnsImmutableList() {
		// Arrange
		BaseAgent agent = createMockAgent("test_agent");
		AgentStaticLoader loader = new AgentStaticLoader(agent);
		// Act
		ImmutableList<String> result = loader.listAgents();
		// Assert
		assertThat(result).isInstanceOf(ImmutableList.class);
		assertThrows(UnsupportedOperationException.class, () -> result.add("new_agent"));
	}

	@Test
	@Tag("valid")
	void listAgentsReturnsConsistentResultsOnRepeatedCalls() {
		// Arrange
		BaseAgent agentX = createMockAgent("agent_x");
		BaseAgent agentY = createMockAgent("agent_y");
		AgentStaticLoader loader = new AgentStaticLoader(agentX, agentY);
		// Act
		ImmutableList<String> firstResult = loader.listAgents();
		ImmutableList<String> secondResult = loader.listAgents();
		// Assert
		assertThat(firstResult).hasSize(secondResult.size());
		assertThat(firstResult).containsExactlyElementsIn(secondResult);
	}

	@Test
	@Tag("valid")
	void listAgentsContainsOnlyAgentNamesAsStrings() {
		// Arrange
		BaseAgent serviceAgent = createMockAgent("service_agent");
		BaseAgent helperAgent = createMockAgent("helper_agent");
		AgentStaticLoader loader = new AgentStaticLoader(serviceAgent, helperAgent);
		// Act
		ImmutableList<String> result = loader.listAgents();
		// Assert
		assertThat(result).hasSize(2);
		for (String name : result) {
			assertThat(name).isAnyOf("service_agent", "helper_agent");
		}
	}

	@Test
	@Tag("boundary")
	void listAgentsNeverReturnsNull() {
		// Arrange
		AgentStaticLoader loader = new AgentStaticLoader();
		// Act
		ImmutableList<String> result = loader.listAgents();
		// Assert
		assertNotNull(result);
		assertThat(result).isNotNull();
	}

	@Test
	@Tag("valid")
	void listAgentsPreservesDistinctAgentNames() {
		// Arrange
		BaseAgent firstAgent = createMockAgent("first_agent");
		BaseAgent secondAgent = createMockAgent("second_agent");
		AgentStaticLoader loader = new AgentStaticLoader(firstAgent, secondAgent);
		// Act
		ImmutableList<String> result = loader.listAgents();
		// Assert
		assertThat(result).hasSize(2);
		assertThat(result).contains("first_agent");
		assertThat(result).contains("second_agent");
	}

}