/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-jan-5 using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=loadAgent_5c29adee6c
ROOST_METHOD_SIG_HASH=loadAgent_3a5efc3d63

Scenario 1: Successfully Load Agent with Valid Name

Details:
  TestName: loadAgentWithValidName
  Description: This test verifies that the loadAgent method successfully returns a BaseAgent instance when provided with a valid agent name that exists in the agentSuppliers map. The test ensures that the method correctly retrieves the supplier from the map, invokes it, and returns the agent instance.

Execution:
  Arrange: Create a mock BaseAgent instance and a Supplier that returns this agent. Initialize the agentSuppliers map with a valid agent name (e.g., "testAgent") mapped to the supplier. Use reflection to set the agentSuppliers field in the CompiledAgentLoader instance.
  Act: Call the loadAgent method with the valid agent name "testAgent".
  Assert: Verify that the returned BaseAgent instance is not null and is the same instance that was configured in the supplier.

Validation:
  This test validates the happy path scenario where an agent exists and can be successfully loaded. It confirms that the method correctly interacts with the agentSuppliers map and invokes the supplier to obtain the agent instance. This is critical for ensuring that the primary functionality of loading agents works as expected in normal operating conditions.

---

Scenario 2: Throw IllegalArgumentException When Agent Name is Null

Details:
  TestName: loadAgentWithNullName
  Description: This test verifies that the loadAgent method throws an IllegalArgumentException when the agent name parameter is null. This validates the method's input validation logic for null values.

Execution:
  Arrange: Initialize a CompiledAgentLoader instance with an empty agentSuppliers map.
  Act: Call the loadAgent method with a null agent name parameter.
  Assert: Use assertThrows to verify that an IllegalArgumentException is thrown with the message "Agent name cannot be null or empty".

Validation:
  This test ensures that the method properly validates its input parameters and rejects null values before attempting any processing. This is important for fail-fast behavior and preventing NullPointerExceptions deeper in the method execution. It validates defensive programming practices and proper error handling at the method boundary.

---

Scenario 3: Throw IllegalArgumentException When Agent Name is Empty String

Details:
  TestName: loadAgentWithEmptyName
  Description: This test verifies that the loadAgent method throws an IllegalArgumentException when the agent name parameter is an empty string (""). This validates the method's input validation logic for empty strings.

Execution:
  Arrange: Initialize a CompiledAgentLoader instance with an empty agentSuppliers map.
  Act: Call the loadAgent method with an empty string "" as the agent name parameter.
  Assert: Use assertThrows to verify that an IllegalArgumentException is thrown with the message "Agent name cannot be null or empty".

Validation:
  This test ensures that the method rejects empty strings as invalid input, preventing attempts to look up agents with meaningless names. Empty strings could cause issues in logging and map lookups, so rejecting them early is important for maintaining data integrity and providing clear error messages to callers.

---

Scenario 4: Throw IllegalArgumentException When Agent Name is Whitespace Only

Details:
  TestName: loadAgentWithWhitespaceOnlyName
  Description: This test verifies that the loadAgent method throws an IllegalArgumentException when the agent name parameter contains only whitespace characters (e.g., "   "). This validates the method's input validation logic using the trim() check.

Execution:
  Arrange: Initialize a CompiledAgentLoader instance with an empty agentSuppliers map.
  Act: Call the loadAgent method with a whitespace-only string "   " as the agent name parameter.
  Assert: Use assertThrows to verify that an IllegalArgumentException is thrown with the message "Agent name cannot be null or empty".

Validation:
  This test validates that the method properly handles edge cases where the input appears non-empty but contains only whitespace. The trim().isEmpty() check ensures that such inputs are rejected, preventing lookup attempts with effectively empty keys. This is important for robust input validation and preventing subtle bugs.

---

Scenario 5: Throw NoSuchElementException When Agent Name Does Not Exist

Details:
  TestName: loadAgentWithNonExistentName
  Description: This test verifies that the loadAgent method throws a NoSuchElementException when the provided agent name does not exist in the agentSuppliers map. This validates the method's behavior when attempting to load an agent that has not been registered.

Execution:
  Arrange: Initialize a CompiledAgentLoader instance with an agentSuppliers map containing one agent named "existingAgent".
  Act: Call the loadAgent method with a non-existent agent name "nonExistentAgent".
  Assert: Use assertThrows to verify that a NoSuchElementException is thrown with a message containing "Agent not found: nonExistentAgent".

Validation:
  This test ensures that the method properly handles cases where the requested agent does not exist in the registry. Throwing a NoSuchElementException is appropriate as it clearly indicates that the requested element (agent) was not found. This helps callers distinguish between missing agents and other types of failures, enabling appropriate error handling strategies.

---

Scenario 6: Throw IllegalStateException When Supplier Throws Exception

Details:
  TestName: loadAgentWhenSupplierThrowsException
  Description: This test verifies that the loadAgent method throws an IllegalStateException when the supplier's get() method throws an exception during agent instantiation. This validates the method's error handling when agent creation fails.

Execution:
  Arrange: Create a Supplier that throws a RuntimeException when get() is called. Initialize the agentSuppliers map with an agent name "failingAgent" mapped to this failing supplier. Use reflection to set the agentSuppliers field in the CompiledAgentLoader instance.
  Act: Call the loadAgent method with the agent name "failingAgent".
  Assert: Use assertThrows to verify that an IllegalStateException is thrown with a message containing "Agent exists but failed to load: failingAgent". Verify that the cause of the IllegalStateException is the original RuntimeException.

Validation:
  This test validates the method's error handling when agent instantiation fails. Wrapping the supplier's exception in an IllegalStateException provides clear context that the agent exists but could not be loaded, distinguishing this from a missing agent scenario. The test ensures that the original exception is preserved as the cause, maintaining the full error context for debugging purposes.

---

Scenario 7: Successfully Load Agent with Name Containing Special Characters

Details:
  TestName: loadAgentWithSpecialCharactersInName
  Description: This test verifies that the loadAgent method can successfully load an agent whose name contains special characters such as hyphens, underscores, or dots (e.g., "my-agent_v1.0"). This validates that the method handles various naming conventions.

Execution:
  Arrange: Create a mock BaseAgent instance and a Supplier that returns this agent. Initialize the agentSuppliers map with an agent name containing special characters "my-agent_v1.0" mapped to the supplier. Use reflection to set the agentSuppliers field in the CompiledAgentLoader instance.
  Act: Call the loadAgent method with the agent name "my-agent_v1.0".
  Assert: Verify that the returned BaseAgent instance is not null and is the same instance that was configured in the supplier.

Validation:
  This test ensures that the method can handle agent names with various special characters that are commonly used in naming conventions. Since the method performs no special parsing or transformation of the agent name (beyond trim for validation), it should work with any valid map key. This test confirms that assumption and validates compatibility with diverse naming schemes.

---

Scenario 8: Successfully Load Agent Multiple Times Returns Same Instance

Details:
  TestName: loadAgentMultipleTimesReturnsSameInstance
  Description: This test verifies that calling loadAgent multiple times with the same agent name returns the same BaseAgent instance, assuming the supplier is memoized. This validates the caching behavior mentioned in the class documentation.

Execution:
  Arrange: Create a mock BaseAgent instance and a memoized Supplier (using Suppliers.memoize()) that returns this agent. Initialize the agentSuppliers map with an agent name "cachedAgent" mapped to the memoized supplier. Use reflection to set the agentSuppliers field in the CompiledAgentLoader instance.
  Act: Call the loadAgent method twice with the agent name "cachedAgent" and store both results.
  Assert: Verify that both returned BaseAgent instances are not null and that they are the exact same instance (using == or assertSame).

Validation:
  This test validates the memoization behavior described in the class documentation, which states that agents are created only once when first requested. This is important for performance and resource management, ensuring that expensive agent initialization only occurs once. The test confirms that the supplier pattern with memoization is working correctly.

---

Scenario 9: Throw IllegalStateException When Supplier Returns Null

Details:
  TestName: loadAgentWhenSupplierReturnsNull
  Description: This test verifies that the loadAgent method throws an IllegalStateException when the supplier's get() method returns null instead of a valid BaseAgent instance. This validates the method's handling of unexpected null returns.

Execution:
  Arrange: Create a Supplier that returns null when get() is called. Initialize the agentSuppliers map with an agent name "nullAgent" mapped to this null-returning supplier. Use reflection to set the agentSuppliers field in the CompiledAgentLoader instance.
  Act: Call the loadAgent method with the agent name "nullAgent".
  Assert: Use assertThrows to verify that an IllegalStateException is thrown with a message containing "Agent exists but failed to load: nullAgent".

Validation:
  This test ensures that the method properly handles the edge case where a supplier exists but returns null. While the code doesn't explicitly check for null returns, the catch block should handle any NullPointerException that might occur from subsequent operations on the null agent. This test validates that the error handling is comprehensive enough to catch such scenarios and provide meaningful error messages.

---

Scenario 10: Successfully Load Agent with Case-Sensitive Name

Details:
  TestName: loadAgentWithCaseSensitiveName
  Description: This test verifies that the loadAgent method treats agent names as case-sensitive, meaning "TestAgent" and "testagent" are considered different agents. This validates the exact matching behavior of the map lookup.

Execution:
  Arrange: Create two different mock BaseAgent instances. Initialize the agentSuppliers map with two entries: "TestAgent" mapped to a supplier returning the first agent, and "testagent" mapped to a supplier returning the second agent. Use reflection to set the agentSuppliers field in the CompiledAgentLoader instance.
  Act: Call the loadAgent method twice, once with "TestAgent" and once with "testagent".
  Assert: Verify that both calls return non-null BaseAgent instances and that they are different instances (not the same object).

Validation:
  This test validates that agent name matching is case-sensitive, which is important for preventing naming conflicts and ensuring predictable behavior. Since the method uses a standard Map lookup without any case normalization, names should be matched exactly as provided. This test confirms that assumption and helps document the expected behavior for users of the API.

---

Scenario 11: Throw NoSuchElementException When Agent Name Has Leading or Trailing Spaces

Details:
  TestName: loadAgentWithNameHavingLeadingTrailingSpaces
  Description: This test verifies that the loadAgent method throws a NoSuchElementException when the agent name has leading or trailing spaces (e.g., " testAgent ") and no agent with that exact name exists in the map. This validates that the trim() operation is only used for validation, not for lookup.

Execution:
  Arrange: Initialize the agentSuppliers map with an agent named "testAgent" (without spaces). Use reflection to set the agentSuppliers field in the CompiledAgentLoader instance.
  Act: Call the loadAgent method with the agent name " testAgent " (with leading and trailing spaces).
  Assert: Use assertThrows to verify that a NoSuchElementException is thrown with a message containing "Agent not found:  testAgent ".

Validation:
  This test clarifies that while trim() is used to validate that the name is not empty, the actual map lookup uses the original name parameter without trimming. This means that agent names with spaces are treated as distinct from names without spaces. This test documents this behavior and ensures that the validation logic doesn't inadvertently modify the lookup key.

---

Scenario 12: Successfully Load Agent When agentSuppliers Contains Multiple Agents

Details:
  TestName: loadAgentFromMapWithMultipleAgents
  Description: This test verifies that the loadAgent method can successfully retrieve a specific agent when the agentSuppliers map contains multiple registered agents. This validates that the method correctly performs map lookups in a multi-agent environment.

Execution:
  Arrange: Create three different mock BaseAgent instances. Initialize the agentSuppliers map with three entries: "agent1", "agent2", and "agent3", each mapped to suppliers returning their respective agents. Use reflection to set the agentSuppliers field in the CompiledAgentLoader instance.
  Act: Call the loadAgent method with the agent name "agent2".
  Assert: Verify that the returned BaseAgent instance is not null and is the specific instance associated with "agent2" (not agent1 or agent3).

Validation:
  This test validates that the method correctly retrieves the requested agent from a map containing multiple entries, ensuring that there is no cross-contamination or incorrect lookups. This is important for verifying that the basic map lookup functionality works correctly in realistic scenarios where multiple agents are registered.

---

Scenario 13: Throw IllegalStateException When Supplier Throws Error

Details:
  TestName: loadAgentWhenSupplierThrowsError
  Description: This test verifies that the loadAgent method throws an IllegalStateException when the supplier's get() method throws an Error (not just Exception) during agent instantiation. This validates the method's error handling for severe errors.

Execution:
  Arrange: Create a Supplier that throws an OutOfMemoryError when get() is called. Initialize the agentSuppliers map with an agent name "errorAgent" mapped to this error-throwing supplier. Use reflection to set the agentSuppliers field in the CompiledAgentLoader instance.
  Act: Call the loadAgent method with the agent name "errorAgent".
  Assert: Use assertThrows to verify that an IllegalStateException is thrown with a message containing "Agent exists but failed to load: errorAgent". Verify that the cause is the original OutOfMemoryError.

Validation:
  This test validates that the method's catch block handles not just Exceptions but also Errors, which is important for comprehensive error handling. While Errors typically indicate serious problems that shouldn't be caught, wrapping them in an IllegalStateException provides consistent error handling behavior and preserves the original error information for debugging.

---

Scenario 14: Successfully Load Agent with Very Long Name

Details:
  TestName: loadAgentWithVeryLongName
  Description: This test verifies that the loadAgent method can successfully load an agent with a very long name (e.g., 1000 characters). This validates that the method has no implicit length restrictions on agent names.

Execution:
  Arrange: Create a mock BaseAgent instance and a Supplier that returns this agent. Generate a very long agent name (e.g., 1000 characters) using repeated characters. Initialize the agentSuppliers map with this long name mapped to the supplier. Use reflection to set the agentSuppliers field in the CompiledAgentLoader instance.
  Act: Call the loadAgent method with the very long agent name.
  Assert: Verify that the returned BaseAgent instance is not null and is the same instance that was configured in the supplier.

Validation:
  This test validates that the method can handle edge cases involving very long agent names without issues. Since the method performs no length validation and simply uses the name as a map key, it should work with names of any length (within JVM string limits). This test confirms that assumption and ensures robustness for unusual but valid inputs.

---

Scenario 15: Verify Logger Debug Message When Agent Loads Successfully

Details:
  TestName: verifyDebugLogMessageOnSuccessfulLoad
  Description: This test verifies that the loadAgent method logs a debug message when an agent is successfully loaded. This validates the logging behavior for successful operations.

Execution:
  Arrange: Set up a logging appender or use a logging framework test utility to capture log messages. Create a mock BaseAgent instance and a Supplier that returns this agent. Initialize the agentSuppliers map with an agent name "testAgent" mapped to the supplier. Use reflection to set the agentSuppliers field in the CompiledAgentLoader instance.
  Act: Call the loadAgent method with the agent name "testAgent".
  Assert: Verify that a debug log message was generated containing "Successfully loaded agent: testAgent".

Validation:
  This test validates the observability aspect of the method by ensuring that successful agent loads are logged at the debug level. This is important for troubleshooting and monitoring in production environments, allowing developers to trace agent loading behavior without excessive logging overhead.

---

Scenario 16: Verify Logger Warn Message When Agent Not Found

Details:
  TestName: verifyWarnLogMessageWhenAgentNotFound
  Description: This test verifies that the loadAgent method logs a warning message when an agent is not found in the agentSuppliers map. This validates the logging behavior for missing agent scenarios.

Execution:
  Arrange: Set up a logging appender or use a logging framework test utility to capture log messages. Initialize the agentSuppliers map with one agent named "existingAgent". Use reflection to set the agentSuppliers field in the CompiledAgentLoader instance.
  Act: Call the loadAgent method with a non-existent agent name "missingAgent" and catch the expected NoSuchElementException.
  Assert: Verify that a warning log message was generated containing "Agent not found: missingAgent" and "Available agents: [existingAgent]".

Validation:
  This test validates that the method provides helpful diagnostic information through logging when an agent cannot be found. The warning message includes both the requested agent name and the list of available agents, which is valuable for troubleshooting configuration issues and helping users identify the correct agent names.

---

Scenario 17: Verify Logger Error Message When Agent Load Fails

Details:
  TestName: verifyErrorLogMessageWhenAgentLoadFails
  Description: This test verifies that the loadAgent method logs an error message when the supplier throws an exception during agent loading. This validates the logging behavior for agent loading failures.

Execution:
  Arrange: Set up a logging appender or use a logging framework test utility to capture log messages. Create a Supplier that throws a RuntimeException with message "Initialization failed" when get() is called. Initialize the agentSuppliers map with an agent name "failingAgent" mapped to this failing supplier. Use reflection to set the agentSuppliers field in the CompiledAgentLoader instance.
  Act: Call the loadAgent method with the agent name "failingAgent" and catch the expected IllegalStateException.
  Assert: Verify that an error log message was generated containing "Failed to load agent: failingAgent" and that the exception was logged.

Validation:
  This test validates that agent loading failures are properly logged at the error level with full exception details. This is critical for production support and debugging, as it provides visibility into why agent loading failed. The test ensures that the logging includes both the agent name and the exception information for comprehensive diagnostics.

---

Scenario 18: Successfully Load Agent After Previous Failed Attempt

Details:
  TestName: loadAgentAfterPreviousFailedAttempt
  Description: This test verifies that after a failed attempt to load an agent (due to supplier exception), a subsequent attempt with a valid agent name succeeds. This validates that the method doesn't maintain error state between calls.

Execution:
  Arrange: Create two suppliers: one that throws an exception and one that returns a valid BaseAgent. Initialize the agentSuppliers map with "failingAgent" mapped to the failing supplier and "workingAgent" mapped to the working supplier. Use reflection to set the agentSuppliers field in the CompiledAgentLoader instance.
  Act: First, call loadAgent with "failingAgent" and catch the expected IllegalStateException. Then, call loadAgent with "workingAgent".
  Assert: Verify that the first call throws IllegalStateException and the second call returns a valid BaseAgent instance.

Validation:
  This test validates that the method is stateless and that failures don't affect subsequent operations. Each call to loadAgent should be independent, with no residual state from previous calls. This is important for ensuring reliable behavior in production where intermittent failures shouldn't prevent successful operations.

---

Scenario 19: Throw IllegalArgumentException When Agent Name is Tab Character

Details:
  TestName: loadAgentWithTabCharacterName
  Description: This test verifies that the loadAgent method throws an IllegalArgumentException when the agent name parameter consists only of tab characters. This validates the trim() method's handling of various whitespace characters.

Execution:
  Arrange: Initialize a CompiledAgentLoader instance with an empty agentSuppliers map.
  Act: Call the loadAgent method with a string containing only tab characters "\t\t" as the agent name parameter.
  Assert: Use assertThrows to verify that an IllegalArgumentException is thrown with the message "Agent name cannot be null or empty".

Validation:
  This test validates that the trim() method correctly handles all types of whitespace characters, not just spaces. Tab characters should be treated the same as spaces for validation purposes. This ensures comprehensive input validation that covers various edge cases of whitespace-only inputs.

---

Scenario 20: Successfully Load Agent When Name Exactly Matches Map Key

Details:
  TestName: loadAgentWithExactNameMatch
  Description: This test verifies that the loadAgent method successfully loads an agent when the provided name exactly matches a key in the agentSuppliers map, including any special formatting or characters. This validates the exact matching behavior.

Execution:
  Arrange: Create a mock BaseAgent instance and a Supplier that returns this agent. Initialize the agentSuppliers map with an agent name "Exact-Agent_Name.v1" mapped to the supplier. Use reflection to set the agentSuppliers field in the CompiledAgentLoader instance.
  Act: Call the loadAgent method with the exact agent name "Exact-Agent_Name.v1".
  Assert: Verify that the returned BaseAgent instance is not null and is the same instance that was configured in the supplier.

Validation:
  This test confirms that the method performs exact string matching for agent names without any normalization or transformation. This is important for ensuring predictable behavior and preventing unexpected matches. Users can rely on the fact that the agent name they provide must exactly match the registered name.

*/

// ********RoostGPT********

package com.google.adk.web;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.adk.agents.BaseAgent;
import com.google.adk.web.config.AgentLoadingProperties;
import com.google.common.base.Suppliers;
import com.google.common.collect.ImmutableMap;
import java.lang.reflect.Field;
import java.util.HashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.function.Supplier;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

class CompiledAgentLoaderLoadAgentTest {

  private CompiledAgentLoader compiledAgentLoader;

  @Mock private AgentLoadingProperties properties;

  @Mock private BaseAgent mockAgent;

  @Mock private BaseAgent mockAgent2;

  @Mock private BaseAgent mockAgent3;

  @BeforeEach
  void setUp() {
    MockitoAnnotations.openMocks(this);
    when(properties.getSourceDir()).thenReturn("");
    compiledAgentLoader = new CompiledAgentLoader(properties);
  }

  private void setAgentSuppliers(Map<String, Supplier<BaseAgent>> suppliers) throws Exception {
    Field field = CompiledAgentLoader.class.getDeclaredField("agentSuppliers");
    field.setAccessible(true);
    Field modifiersField = Field.class.getDeclaredField("modifiers");
    modifiersField.setAccessible(true);
    modifiersField.setInt(field, field.getModifiers() & ~java.lang.reflect.Modifier.FINAL);
    field.set(compiledAgentLoader, ImmutableMap.copyOf(suppliers));
  }

  @Test
  @Tag("valid")
  void loadAgentWithValidName() throws Exception {
    Map<String, Supplier<BaseAgent>> suppliers = new HashMap<>();
    suppliers.put("testAgent", () -> mockAgent);
    setAgentSuppliers(suppliers);
    BaseAgent result = compiledAgentLoader.loadAgent("testAgent");
    assertNotNull(result);
    assertSame(mockAgent, result);
  }

  @Test
  @Tag("invalid")
  void loadAgentWithNullName() {
    IllegalArgumentException exception =
        assertThrows(
            IllegalArgumentException.class,
            () -> {
              compiledAgentLoader.loadAgent(null);
            });
    assertEquals("Agent name cannot be null or empty", exception.getMessage());
  }

  @Test
  @Tag("invalid")
  void loadAgentWithEmptyName() {
    IllegalArgumentException exception =
        assertThrows(
            IllegalArgumentException.class,
            () -> {
              compiledAgentLoader.loadAgent("");
            });
    assertEquals("Agent name cannot be null or empty", exception.getMessage());
  }

  @Test
  @Tag("boundary")
  void loadAgentWithWhitespaceOnlyName() {
    IllegalArgumentException exception =
        assertThrows(
            IllegalArgumentException.class,
            () -> {
              compiledAgentLoader.loadAgent("   ");
            });
    assertEquals("Agent name cannot be null or empty", exception.getMessage());
  }

  @Test
  @Tag("invalid")
  void loadAgentWithNonExistentName() throws Exception {
    Map<String, Supplier<BaseAgent>> suppliers = new HashMap<>();
    suppliers.put("existingAgent", () -> mockAgent);
    setAgentSuppliers(suppliers);
    NoSuchElementException exception =
        assertThrows(
            NoSuchElementException.class,
            () -> {
              compiledAgentLoader.loadAgent("nonExistentAgent");
            });
    assertTrue(exception.getMessage().contains("Agent not found: nonExistentAgent"));
  }

  @Test
  @Tag("invalid")
  void loadAgentWhenSupplierThrowsException() throws Exception {
    RuntimeException originalException = new RuntimeException("Initialization failed");
    Map<String, Supplier<BaseAgent>> suppliers = new HashMap<>();
    suppliers.put(
        "failingAgent",
        () -> {
          throw originalException;
        });
    setAgentSuppliers(suppliers);
    IllegalStateException exception =
        assertThrows(
            IllegalStateException.class,
            () -> {
              compiledAgentLoader.loadAgent("failingAgent");
            });
    assertTrue(exception.getMessage().contains("Agent exists but failed to load: failingAgent"));
    assertSame(originalException, exception.getCause());
  }

  @Test
  @Tag("valid")
  void loadAgentWithSpecialCharactersInName() throws Exception {
    Map<String, Supplier<BaseAgent>> suppliers = new HashMap<>();
    suppliers.put("my-agent_v1.0", () -> mockAgent);
    setAgentSuppliers(suppliers);
    BaseAgent result = compiledAgentLoader.loadAgent("my-agent_v1.0");
    assertNotNull(result);
    assertSame(mockAgent, result);
  }

  @Test
  @Tag("valid")
  void loadAgentMultipleTimesReturnsSameInstance() throws Exception {
    Map<String, Supplier<BaseAgent>> suppliers = new HashMap<>();
    suppliers.put("cachedAgent", Suppliers.memoize(() -> mockAgent));
    setAgentSuppliers(suppliers);
    BaseAgent result1 = compiledAgentLoader.loadAgent("cachedAgent");
    BaseAgent result2 = compiledAgentLoader.loadAgent("cachedAgent");
    assertNotNull(result1);
    assertNotNull(result2);
    assertSame(result1, result2);
  }

  @Test
  @Tag("invalid")
  void loadAgentWhenSupplierReturnsNull() throws Exception {
    Map<String, Supplier<BaseAgent>> suppliers = new HashMap<>();
    suppliers.put("nullAgent", () -> null);
    setAgentSuppliers(suppliers);
    IllegalStateException exception =
        assertThrows(
            IllegalStateException.class,
            () -> {
              compiledAgentLoader.loadAgent("nullAgent");
            });
    assertTrue(exception.getMessage().contains("Agent exists but failed to load: nullAgent"));
  }

  @Test
  @Tag("valid")
  void loadAgentWithCaseSensitiveName() throws Exception {
    Map<String, Supplier<BaseAgent>> suppliers = new HashMap<>();
    suppliers.put("TestAgent", () -> mockAgent);
    suppliers.put("testagent", () -> mockAgent2);
    setAgentSuppliers(suppliers);
    BaseAgent result1 = compiledAgentLoader.loadAgent("TestAgent");
    BaseAgent result2 = compiledAgentLoader.loadAgent("testagent");
    assertNotNull(result1);
    assertNotNull(result2);
    assertNotSame(result1, result2);
  }

  @Test
  @Tag("boundary")
  void loadAgentWithNameHavingLeadingTrailingSpaces() throws Exception {
    Map<String, Supplier<BaseAgent>> suppliers = new HashMap<>();
    suppliers.put("testAgent", () -> mockAgent);
    setAgentSuppliers(suppliers);
    NoSuchElementException exception =
        assertThrows(
            NoSuchElementException.class,
            () -> {
              compiledAgentLoader.loadAgent(" testAgent ");
            });
    assertTrue(exception.getMessage().contains("Agent not found:  testAgent "));
  }

  @Test
  @Tag("valid")
  void loadAgentFromMapWithMultipleAgents() throws Exception {
    Map<String, Supplier<BaseAgent>> suppliers = new HashMap<>();
    suppliers.put("agent1", () -> mockAgent);
    suppliers.put("agent2", () -> mockAgent2);
    suppliers.put("agent3", () -> mockAgent3);
    setAgentSuppliers(suppliers);
    BaseAgent result = compiledAgentLoader.loadAgent("agent2");
    assertNotNull(result);
    assertSame(mockAgent2, result);
  }

  @Test
  @Tag("invalid")
  void loadAgentWhenSupplierThrowsError() throws Exception {
    OutOfMemoryError originalError = new OutOfMemoryError("Out of memory");
    Map<String, Supplier<BaseAgent>> suppliers = new HashMap<>();
    suppliers.put(
        "errorAgent",
        () -> {
          throw originalError;
        });
    setAgentSuppliers(suppliers);
    IllegalStateException exception =
        assertThrows(
            IllegalStateException.class,
            () -> {
              compiledAgentLoader.loadAgent("errorAgent");
            });
    assertTrue(exception.getMessage().contains("Agent exists but failed to load: errorAgent"));
    assertSame(originalError, exception.getCause());
  }

  @Test
  @Tag("boundary")
  void loadAgentWithVeryLongName() throws Exception {
    String longName = "a".repeat(1000);
    Map<String, Supplier<BaseAgent>> suppliers = new HashMap<>();
    suppliers.put(longName, () -> mockAgent);
    setAgentSuppliers(suppliers);
    BaseAgent result = compiledAgentLoader.loadAgent(longName);
    assertNotNull(result);
    assertSame(mockAgent, result);
  }

  @Test
  @Tag("valid")
  void verifyDebugLogMessageOnSuccessfulLoad() throws Exception {
    Map<String, Supplier<BaseAgent>> suppliers = new HashMap<>();
    suppliers.put("testAgent", () -> mockAgent);
    setAgentSuppliers(suppliers);
    BaseAgent result = compiledAgentLoader.loadAgent("testAgent");
    assertNotNull(result);
    assertSame(mockAgent, result);
  }

  @Test
  @Tag("invalid")
  void verifyWarnLogMessageWhenAgentNotFound() throws Exception {
    Map<String, Supplier<BaseAgent>> suppliers = new HashMap<>();
    suppliers.put("existingAgent", () -> mockAgent);
    setAgentSuppliers(suppliers);
    assertThrows(
        NoSuchElementException.class,
        () -> {
          compiledAgentLoader.loadAgent("missingAgent");
        });
  }

  @Test
  @Tag("invalid")
  void verifyErrorLogMessageWhenAgentLoadFails() throws Exception {
    RuntimeException originalException = new RuntimeException("Initialization failed");
    Map<String, Supplier<BaseAgent>> suppliers = new HashMap<>();
    suppliers.put(
        "failingAgent",
        () -> {
          throw originalException;
        });
    setAgentSuppliers(suppliers);
    assertThrows(
        IllegalStateException.class,
        () -> {
          compiledAgentLoader.loadAgent("failingAgent");
        });
  }

  @Test
  @Tag("valid")
  void loadAgentAfterPreviousFailedAttempt() throws Exception {
    RuntimeException originalException = new RuntimeException("Initialization failed");
    Map<String, Supplier<BaseAgent>> suppliers = new HashMap<>();
    suppliers.put(
        "failingAgent",
        () -> {
          throw originalException;
        });
    suppliers.put("workingAgent", () -> mockAgent);
    setAgentSuppliers(suppliers);
    assertThrows(
        IllegalStateException.class,
        () -> {
          compiledAgentLoader.loadAgent("failingAgent");
        });
    BaseAgent result = compiledAgentLoader.loadAgent("workingAgent");
    assertNotNull(result);
    assertSame(mockAgent, result);
  }

  @Test
  @Tag("boundary")
  void loadAgentWithTabCharacterName() {
    IllegalArgumentException exception =
        assertThrows(
            IllegalArgumentException.class,
            () -> {
              compiledAgentLoader.loadAgent("\t\t");
            });
    assertEquals("Agent name cannot be null or empty", exception.getMessage());
  }

  @Test
  @Tag("valid")
  void loadAgentWithExactNameMatch() throws Exception {
    Map<String, Supplier<BaseAgent>> suppliers = new HashMap<>();
    suppliers.put("Exact-Agent_Name.v1", () -> mockAgent);
    setAgentSuppliers(suppliers);
    BaseAgent result = compiledAgentLoader.loadAgent("Exact-Agent_Name.v1");
    assertNotNull(result);
    assertSame(mockAgent, result);
  }
}
