/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-repo using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=model_646889c46e
ROOST_METHOD_SIG_HASH=model_acc033d54d

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/adk-java-repo/87694200-c46c-408c-b0b1-408cb60f3b49/source/adk-java/core/src/test/java/com/google/adk/tools/retrieval/VertexAiRagRetrievalTest.java
Tests:
    "@Test
public void processLlmRequest_gemini2Model_addVertexRagStoreToConfig() {

    boolean useVertexAi = Boolean.parseBoolean(System.getenv("GOOGLE_GENAI_USE_VERTEXAI"));
    ImmutableList<RagResource> ragResources = ImmutableList.of(RagResource.newBuilder().setRagCorpus("corpus1").build());
    Double vectorDistanceThreshold = 0.5;
    VertexAiRagRetrieval tool = new VertexAiRagRetrieval("testTool", "test description", vertexRagServiceClient, "projects/test-project/locations/us-central1", ragResources, vectorDistanceThreshold);
    LlmRequest.Builder llmRequestBuilder = LlmRequest.builder().model("gemini-2-pro");
    ToolContext toolContext = ToolContext.builder(new InvocationContext(
    null,
    null,
    null,
    Optional.empty(),
    Optional.empty(),
    null,
    null, Session.builder("123").build(),
    Optional.empty(),
    null,
    false)).functionCallId("functionCallId").build();
    tool.processLlmRequest(llmRequestBuilder, toolContext).blockingAwait();
    if (useVertexAi) {

        assertThat(llmRequestBuilder.build().config().get().tools().get()).containsExactly(Tool.builder().retrieval(Retrieval.builder().vertexRagStore(VertexRagStore.builder().ragResources(ImmutableList.of(VertexRagStoreRagResource.builder().ragCorpus("corpus1").build())).vectorDistanceThreshold(0.5).build()).build()).build());
    } else {

        assertThat(llmRequestBuilder.build().config().get().tools().get()).containsExactly(Tool.builder().functionDeclarations(ImmutableList.of(FunctionDeclaration.builder().name("testTool").description("test description").parameters(Schema.builder().properties(ImmutableMap.of("query", Schema.builder().description("The query to retrieve.").type("STRING").build())).type("OBJECT").build()).build())).build());
    }
}
"
    "@Test
public void processLlmRequest_otherModel_doNotAddVertexRagStoreToConfig() {
    ImmutableList<RagResource> ragResources = ImmutableList.of(RagResource.newBuilder().setRagCorpus("corpus1").build());
    Double vectorDistanceThreshold = 0.5;
    VertexAiRagRetrieval tool = new VertexAiRagRetrieval("testTool", "test description", vertexRagServiceClient, "projects/test-project/locations/us-central1", ragResources, vectorDistanceThreshold);
    LlmRequest.Builder llmRequestBuilder = LlmRequest.builder().model("gemini-1-pro");
    ToolContext toolContext = ToolContext.builder(new InvocationContext(
    null,
    null,
    null,
    Optional.empty(),
    Optional.empty(),
    null,
    null, Session.builder("123").build(),
    Optional.empty(),
    null,
    false)).functionCallId("functionCallId").build();
    GenerateContentConfig initialConfig = GenerateContentConfig.builder().build();
    llmRequestBuilder.config(initialConfig);
    tool.processLlmRequest(llmRequestBuilder, toolContext).blockingAwait();
    assertThat(llmRequestBuilder.build().config().get().tools().get()).containsExactly(Tool.builder().functionDeclarations(ImmutableList.of(FunctionDeclaration.builder().name("testTool").description("test description").parameters(Schema.builder().properties(ImmutableMap.of("query", Schema.builder().description("The query to retrieve.").type("STRING").build())).type("OBJECT").build()).build())).build());
}
"

File Path: /var/tmp/Roost/RoostGPT/adk-java-repo/87694200-c46c-408c-b0b1-408cb60f3b49/source/adk-java/core/src/test/java/com/google/adk/agents/LlmAgentTest.java
Tests:
    "@Test
public void resolveModel_withModelName_resolvesFromRegistry() {
    String modelName = "test-model";
    TestLlm testLlm = createTestLlm(LlmResponse.builder().build());
    LlmRegistry.registerLlm(modelName, (name) -> testLlm);
    LlmAgent agent = createTestAgentBuilder(testLlm).model(modelName).build();
    Model resolvedModel = agent.resolvedModel();
    assertThat(resolvedModel.modelName()).hasValue(modelName);
    assertThat(resolvedModel.model()).hasValue(testLlm);
}
"

File Path: /var/tmp/Roost/RoostGPT/adk-java-repo/87694200-c46c-408c-b0b1-408cb60f3b49/source/adk-java/core/src/test/java/com/google/adk/tools/LongRunningFunctionToolTest.java
Tests:
    "@Test
private void setUpAgentAndRunner(List<LlmResponse> llmResponses, FunctionTool tool, String description) {
    testLlm = new TestLlm(llmResponses);
    agent = LlmAgent.builder().name("root_agent").model(testLlm).tools(ImmutableList.of(tool)).description(description).build();
    runner = new Runner(agent, "test_app", artifactService, sessionService, memoryService, null, new ResumabilityConfig(false));
    session = runner.sessionService().createSession(runner.appName(), "test-user-id", new ConcurrentHashMap<>(), null).blockingGet();
}
"

File Path: /var/tmp/Roost/RoostGPT/adk-java-repo/87694200-c46c-408c-b0b1-408cb60f3b49/source/adk-java/core/src/test/java/com/google/adk/tools/ExampleToolTest.java
Tests:
    "@Test
public void processLlmRequest_withInlineExamples_appendsFewShot() {
    ExampleTool tool = ExampleTool.builder().addExample(makeExample("qin", "qout")).build();
    InvocationContext ctx = newContext();
    LlmRequest.Builder builder = LlmRequest.builder().model("gemini-2.0-flash");
    tool.processLlmRequest(builder, ToolContext.builder(ctx).build()).blockingAwait();
    LlmRequest updated = builder.build();
    assertThat(updated.getSystemInstructions()).isNotEmpty();
    String si = String.join("\n", updated.getSystemInstructions());
    assertThat(si).contains("Begin few-shot");
    assertThat(si).contains("qin");
    assertThat(si).contains("qout");
}
"
    "@Test
public void fromConfig_withInlineExamples_buildsTool() throws Exception {
    BaseTool.ToolArgsConfig args = new BaseTool.ToolArgsConfig();

    args.setAdditionalProperty("examples", ImmutableList.of(ImmutableMap.of("input", Content.fromParts(Part.fromText("q")), "output", ImmutableList.of(Content.fromParts(Part.fromText("a"))))));
    ExampleTool tool = ExampleTool.fromConfig(args);
    InvocationContext ctx = newContext();
    LlmRequest.Builder builder = LlmRequest.builder().model("gemini-2.0-flash");
    tool.processLlmRequest(builder, ToolContext.builder(ctx).build()).blockingAwait();
    String si = String.join("\n", builder.build().getSystemInstructions());
    assertThat(si).contains("q");
    assertThat(si).contains("a");
}
"
    "@Test
public void fromConfig_withProviderReference_buildsTool() throws Exception {
    BaseTool.ToolArgsConfig args = new BaseTool.ToolArgsConfig();
    args.setAdditionalProperty("examples", ExampleToolTest.ProviderHolder.class.getName() + ".EXAMPLES");
    ExampleTool tool = ExampleTool.fromConfig(args);
    InvocationContext ctx = newContext();
    LlmRequest.Builder builder = LlmRequest.builder().model("gemini-2.0-flash");
    tool.processLlmRequest(builder, ToolContext.builder(ctx).build()).blockingAwait();
    String si = String.join("\n", builder.build().getSystemInstructions());
    assertThat(si).contains("Begin few-shot");
    assertThat(si).contains("qin");
    assertThat(si).contains("qout");
}
"

File Path: /var/tmp/Roost/RoostGPT/adk-java-repo/87694200-c46c-408c-b0b1-408cb60f3b49/source/adk-java/core/src/test/java/com/google/adk/models/LlmRequestTest.java
Tests:
    "@Test
public void builder_defaultValues_setsSensibleDefaults() {
    LlmRequest request = LlmRequest.builder().build();
    assertThat(request.model()).isEmpty();
    assertThat(request.contents()).isEmpty();
    assertThat(request.config()).isEmpty();
    assertThat(request.liveConnectConfig()).isNotNull();
    assertThat(request.liveConnectConfig().temperature()).isEmpty();
    assertThat(request.liveConnectConfig().systemInstruction()).isEmpty();
    assertThat(request.tools()).isEmpty();
}
"

File Path: /var/tmp/Roost/RoostGPT/adk-java-repo/87694200-c46c-408c-b0b1-408cb60f3b49/source/adk-java/core/src/test/java/com/google/adk/tools/streaming/StreamingToolTest.java
Tests:
    "@Test
public void runLive_asyncFunctionCall_succeeds() throws Exception {
    Part functionCall = Part.builder().functionCall(FunctionCall.builder().name("getWeather").args(ImmutableMap.of("location", "San Francisco", "unit", "celsius")).build()).build();
    LlmResponse response1 = LlmResponse.builder().content(Content.builder().role("model").parts(ImmutableList.of(functionCall)).build()).turnComplete(false).build();
    LlmResponse response2 = LlmResponse.builder().turnComplete(true).build();
    TestLlm testLlm = new TestLlm(ImmutableList.of(response1, response2));
    LlmAgent rootAgent = LlmAgent.builder().name("root_agent").model(testLlm).tools(ImmutableList.of(FunctionTool.create(StreamingToolTest.class, "getWeather"))).build();
    InMemoryRunner runner = new InMemoryRunner(rootAgent);
    LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
    liveRequestQueue.send(LiveRequest.builder().blob(Part.fromBytes("What is the weather in San Francisco?".getBytes(UTF_8), "audio/pcm").inlineData().get()).build());
    Session session = runner.sessionService().createSession("test-app", "test-user").blockingGet();
    List<Event> resEvents = runner.runLive(session, liveRequestQueue, BIDI_STREAMING_RUN_CONFIG).toList().blockingGet();
    assertThat(resEvents).isNotNull();
    assertThat(resEvents).isNotEmpty();
    boolean functionCallFound = false;
    boolean functionResponseFound = false;
    for (Event event : resEvents) {
        if (event.content().isPresent()) {
            for (Part part : event.content().get().parts().orElse(ImmutableList.of())) {
                if (part.functionCall().isPresent()) {
                    FunctionCall fc = part.functionCall().get();
                    if (fc.name().get().equals("getWeather")) {
                        functionCallFound = true;
                        assertThat(fc.args().get().get("location")).isEqualTo("San Francisco");
                        assertThat(fc.args().get().get("unit")).isEqualTo("celsius");
                    }
                } else if (part.functionResponse().isPresent()) {
                    FunctionResponse fr = part.functionResponse().get();
                    if (fr.name().get().equals("getWeather")) {
                        functionResponseFound = true;
                        assertThat(fr.response().get().get("temperature")).isEqualTo(22);
                        assertThat(fr.response().get().get("condition")).isEqualTo("sunny");
                    }
                }
            }
        }
    }
    assertThat(functionCallFound).isTrue();
    assertThat(functionResponseFound).isTrue();
}
"
    "@Test
public void runLive_functionCall_returnsErrors() throws Exception {
    Part functionCall = Part.builder().functionCall(FunctionCall.builder().name("getWeatherWithError").args(ImmutableMap.of("location", "Invalid Location")).build()).build();
    LlmResponse response1 = LlmResponse.builder().content(Content.builder().role("model").parts(ImmutableList.of(functionCall)).build()).turnComplete(false).build();
    LlmResponse response2 = LlmResponse.builder().turnComplete(true).build();
    TestLlm testLlm = new TestLlm(ImmutableList.of(response1, response2));
    LlmAgent rootAgent = LlmAgent.builder().name("root_agent").model(testLlm).tools(ImmutableList.of(FunctionTool.create(StreamingToolTest.class, "getWeatherWithError"))).build();
    InMemoryRunner runner = new InMemoryRunner(rootAgent);
    LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
    liveRequestQueue.send(LiveRequest.builder().blob(Part.fromBytes("What is weather in Invalid Location?".getBytes(UTF_8), "audio/pcm").inlineData().get()).build());
    Session session = runner.sessionService().createSession("test-app", "test-user").blockingGet();
    List<Event> resEvents = runner.runLive(session, liveRequestQueue, BIDI_STREAMING_RUN_CONFIG).toList().blockingGet();
    assertThat(resEvents).isNotNull();
    assertThat(resEvents).isNotEmpty();
    boolean functionCallFound = false;
    boolean functionResponseFound = false;
    for (Event event : resEvents) {
        if (event.content().isPresent()) {
            for (Part part : event.content().get().parts().orElse(ImmutableList.of())) {
                if (part.functionCall().isPresent()) {
                    FunctionCall fc = part.functionCall().get();
                    if (fc.name().get().equals("getWeatherWithError")) {
                        functionCallFound = true;
                        assertThat(fc.args().get().get("location")).isEqualTo("Invalid Location");
                    }
                } else if (part.functionResponse().isPresent()) {
                    FunctionResponse fr = part.functionResponse().get();
                    if (fr.name().get().equals("getWeatherWithError")) {
                        functionResponseFound = true;
                        assertThat(fr.response().get().get("error")).isEqualTo("Location not found");
                    }
                }
            }
        }
    }
    assertThat(functionCallFound).isTrue();
    assertThat(functionResponseFound).isTrue();
}
"
    "@Test
public void runLive_videoStreamingTool_receivesVideoFramesAndSendsResultsToLlm() throws Exception {

    Part functionCall = Part.builder().functionCall(FunctionCall.builder().name("monitorVideoStream").args(ImmutableMap.of()).build()).build();
    LlmResponse response1 = LlmResponse.builder().content(Content.builder().role("model").parts(ImmutableList.of(functionCall)).build()).turnComplete(false).build();
    LlmResponse response2 = LlmResponse.builder().turnComplete(true).build();
    TestLlm testLlm = new TestLlm(ImmutableList.of(response1, response2));
    LlmAgent rootAgent = LlmAgent.builder().name("root_agent").model(testLlm).tools(ImmutableList.of(FunctionTool.create(StreamingTools.class, "monitorVideoStream"), FunctionTool.create(StreamingTools.class, "stopStreaming"))).build();
    InMemoryRunner runner = new InMemoryRunner(rootAgent);
    LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
    Session session = runner.sessionService().createSession("test-app", "test-user").blockingGet();

    liveRequestQueue.send(LiveRequest.builder().content(Content.fromParts(Part.fromText("Monitor the video stream"))).build());
    liveRequestQueue.send(LiveRequest.builder().blob(Part.fromBytes("fake_jpeg_data_1".getBytes(UTF_8), "image/jpeg").inlineData().get()).build());
    liveRequestQueue.send(LiveRequest.builder().blob(Part.fromBytes("fake_jpeg_data_2".getBytes(UTF_8), "image/jpeg").inlineData().get()).build());
    liveRequestQueue.send(LiveRequest.builder().blob(Part.fromBytes("fake_jpeg_data_3".getBytes(UTF_8), "image/jpeg").inlineData().get()).build());

    List<Event> resEvents = runner.runLive(session, liveRequestQueue, BIDI_STREAMING_RUN_CONFIG).toList().blockingGet();

    assertThat(testLlm.waitForStreamingToolResults("monitorVideoStream", 3, Duration.ofSeconds(20))).isTrue();

    boolean functionCallFound = resEvents.stream().anyMatch(event -> event.content().isPresent() && event.content().get().parts().orElse(ImmutableList.of()).stream().anyMatch(part -> part.functionCall().isPresent() && part.functionCall().get().name().get().equals("monitorVideoStream")));
    assertThat(functionCallFound).isTrue();

    ImmutableList<LiveRequest> liveRequestHistory = testLlm.getLiveRequestHistory();
    List<String> sentToolOutputsToLlm = new ArrayList<>();
    for (LiveRequest request : liveRequestHistory) {
        if (request.content().isPresent()) {
            Content content = request.content().get();
            if (content.role().orElse("").equals("user")) {
                String text = content.text();
                if (text != null && text.startsWith("Function monitorVideoStream returned:")) {
                    sentToolOutputsToLlm.add(text);
                }
            }
        }
    }
    assertThat(sentToolOutputsToLlm).containsExactly("Function monitorVideoStream returned: {people_count_alert=Processed frame: detected 2" + " people}", "Function monitorVideoStream returned: {people_count_alert=Processed frame: detected 2" + " people}", "Function monitorVideoStream returned: {people_count_alert=Processed frame: detected 2" + " people}").inOrder();
}
"
    "@Test
public void runLive_stopStreamingTool() throws Exception {
    Part startFunctionCall = Part.builder().functionCall(FunctionCall.builder().name("monitorStockPrice").args(ImmutableMap.of("stockSymbol", "TSLA")).build()).build();
    Part stopFunctionCall = Part.builder().functionCall(FunctionCall.builder().name("stopStreaming").args(ImmutableMap.of("functionName", "monitorStockPrice")).build()).build();
    LlmResponse response1 = LlmResponse.builder().content(Content.builder().role("model").parts(ImmutableList.of(startFunctionCall)).build()).turnComplete(false).build();
    LlmResponse response2 = LlmResponse.builder().content(Content.builder().role("model").parts(ImmutableList.of(stopFunctionCall)).build()).turnComplete(false).build();
    LlmResponse response3 = LlmResponse.builder().turnComplete(true).build();
    TestLlm testLlm = new TestLlm(ImmutableList.of(response1, response2, response3));
    LlmAgent rootAgent = LlmAgent.builder().name("root_agent").model(testLlm).tools(ImmutableList.of(FunctionTool.create(StreamingTools.class, "monitorStockPrice"), FunctionTool.create(StreamingTools.class, "stopStreaming"))).build();
    InMemoryRunner runner = new InMemoryRunner(rootAgent);
    LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
    liveRequestQueue.send(LiveRequest.builder().content(Content.fromParts(Part.fromText("Monitor TSLA and then stop"))).build());
    Session session = runner.sessionService().createSession("test-app", "test-user").blockingGet();
    List<Event> resEvents = runner.runLive(session, liveRequestQueue, BIDI_STREAMING_RUN_CONFIG).toList().blockingGet();
    assertThat(resEvents).isNotNull();
    assertThat(resEvents.size()).isAtLeast(1);
    boolean monitorCallFound = resEvents.stream().anyMatch(event -> event.content().isPresent() && event.content().get().parts().orElse(ImmutableList.of()).stream().anyMatch(part -> part.functionCall().isPresent() && part.functionCall().get().name().get().equals("monitorStockPrice") && part.functionCall().get().args().get().get("stockSymbol").equals("TSLA")));
    assertThat(monitorCallFound).isTrue();
    boolean stopCallFound = resEvents.stream().anyMatch(event -> event.content().isPresent() && event.content().get().parts().orElse(ImmutableList.of()).stream().anyMatch(part -> part.functionCall().isPresent() && part.functionCall().get().name().get().equals("stopStreaming") && part.functionCall().get().args().get().get("functionName").equals("monitorStockPrice")));
    assertThat(stopCallFound).isTrue();
}
"
    "@Test
public void runLive_streamingTool_responsesAreSentAsUserContentToLlm() throws Exception {
    Part functionCall = Part.builder().functionCall(FunctionCall.builder().name("monitorStockPrice").args(ImmutableMap.of("stockSymbol", "GOOG")).build()).build();
    LlmResponse response1 = LlmResponse.builder().content(Content.builder().role("model").parts(ImmutableList.of(functionCall)).build()).turnComplete(false).build();
    LlmResponse response2 = LlmResponse.builder().turnComplete(true).build();
    TestLlm testLlm = new TestLlm(ImmutableList.of(response1, response2));
    LlmAgent rootAgent = LlmAgent.builder().name("root_agent").model(testLlm).tools(ImmutableList.of(FunctionTool.create(StreamingTools.class, "monitorStockPrice"), FunctionTool.create(StreamingTools.class, "stopStreaming"))).build();
    InMemoryRunner runner = new InMemoryRunner(rootAgent);
    LiveRequestQueue liveRequestQueue = new LiveRequestQueue();
    liveRequestQueue.send(LiveRequest.builder().content(Content.fromParts(Part.fromText("Monitor GOOG stock price"))).build());
    Session session = runner.sessionService().createSession("test-app", "test-user").blockingGet();
    List<Event> resEvents = runner.runLive(session, liveRequestQueue, BIDI_STREAMING_RUN_CONFIG).toList().blockingGet();
    assertThat(resEvents).isNotNull();
    assertThat(resEvents).isNotEmpty();
    boolean functionCallFound = false;
    for (Event event : resEvents) {
        if (event.content().isPresent()) {
            for (Part part : event.content().get().parts().orElse(ImmutableList.of())) {
                if (part.functionCall().isPresent()) {
                    FunctionCall fc = part.functionCall().get();
                    if (fc.name().get().equals("monitorStockPrice")) {
                        functionCallFound = true;
                        assertThat(fc.args().get().get("stockSymbol")).isEqualTo("GOOG");
                    }
                }
            }
        }
    }
    assertThat(functionCallFound).isTrue();
    ImmutableList<LiveRequest> liveRequestHistory = testLlm.getLiveRequestHistory();
    List<String> sentPriceAlertsToLlm = new ArrayList<>();
    for (LiveRequest request : liveRequestHistory) {
        if (request.content().isPresent()) {
            Content content = request.content().get();


            if (content.role().orElse("").equals("user")) {
                String text = content.text();

                if (text.startsWith("Function monitorStockPrice returned:")) {
                    sentPriceAlertsToLlm.add(text);
                }
            }
        }
    }
    assertThat(sentPriceAlertsToLlm).containsExactly("Function monitorStockPrice returned: {price_alert=Stock GOOG price: $150}", "Function monitorStockPrice returned: {price_alert=Stock GOOG price: $155}", "Function monitorStockPrice returned: {price_alert=Stock GOOG price: $160}").inOrder();
}
"

File Path: /var/tmp/Roost/RoostGPT/adk-java-repo/87694200-c46c-408c-b0b1-408cb60f3b49/source/adk-java/core/src/test/java/com/google/adk/models/ApigeeLlmTest.java
Tests:
    "@Test
public void generateContent_stripsApigeePrefixAndSendsToDelegate() {
    when(mockGeminiDelegate.generateContent(any(), anyBoolean())).thenReturn(Flowable.empty());
    ApigeeLlm llm = new ApigeeLlm("apigee/gemini/v1/gemini-1.5-flash", mockGeminiDelegate);
    LlmRequest request = LlmRequest.builder().model("apigee/gemini/v1/gemini-1.5-flash").contents(ImmutableList.of(Content.builder().parts(Part.fromText("hi")).build())).build();
    llm.generateContent(request, true).test().assertNoErrors();
    ArgumentCaptor<LlmRequest> requestCaptor = ArgumentCaptor.forClass(LlmRequest.class);
    verify(mockGeminiDelegate).generateContent(requestCaptor.capture(), eq(true));
    assertThat(requestCaptor.getValue().model()).hasValue("gemini-1.5-flash");
}
"

File Path: /var/tmp/Roost/RoostGPT/adk-java-repo/87694200-c46c-408c-b0b1-408cb60f3b49/source/adk-java/core/src/test/java/com/google/adk/agents/AgentWithMemoryTest.java
Tests:
    "@Test
public void agentRemembersUserNameWithMemoryTool() throws Exception {
    String userId = "test-user";
    String agentName = "test-agent";
    Part functionCall = Part.builder().functionCall(FunctionCall.builder().name("loadMemory").args(ImmutableMap.of("query", "what is my name?")).build()).build();
    TestLlm testLlm = new TestLlm(ImmutableList.of(LlmResponse.builder().content(Content.builder().parts(Part.fromText("OK, I'll remember that.")).role("model").build()).build(), LlmResponse.builder().content(Content.builder().role("model").parts(ImmutableList.of(functionCall)).build()).build(), LlmResponse.builder().content(Content.builder().

    parts(Part.fromText("Your name is James.")).role("model").build()).build()));
    LlmAgent agent = LlmAgent.builder().name(agentName).model(testLlm).tools(ImmutableList.of(new LoadMemoryTool())).build();
    InMemoryRunner runner = new InMemoryRunner(agent);
    String sessionId = runner.sessionService().createSession(agentName, userId).blockingGet().id();
    Content firstMessage = Content.fromParts(Part.fromText("My name is James"));
    var unused = runner.runAsync(userId, sessionId, firstMessage, RunConfig.builder().build()).toList().blockingGet();

    Session updatedSession = runner.sessionService().getSession("test-agent", userId, sessionId, Optional.empty()).blockingGet();

    runner.memoryService().addSessionToMemory(updatedSession).blockingAwait();
    Content secondMessage = Content.fromParts(Part.fromText("what is my name?"));
    unused = runner.runAsync(userId, updatedSession.id(), secondMessage, RunConfig.builder().build()).toList().blockingGet();

    LlmRequest lastRequest = testLlm.getLastRequest();
    Content functionResponseContent = Iterables.getLast(lastRequest.contents());
    Optional<Part> functionResponsePart = functionResponseContent.parts().get().stream().filter(p -> p.functionResponse().isPresent()).findFirst();
    assertThat(functionResponsePart).isPresent();
    FunctionResponse functionResponse = functionResponsePart.get().functionResponse().get();
    assertThat(functionResponse.name()).hasValue("loadMemory");
    assertThat(functionResponse.response().get().toString()).contains("My name is James");
}
"

File Path: /var/tmp/Roost/RoostGPT/adk-java-repo/87694200-c46c-408c-b0b1-408cb60f3b49/source/adk-java/core/src/test/java/com/google/adk/agents/ConfigAgentUtilsTest.java
Tests:
    "@Test
public void fromConfig_withModel_setsModelOnAgent() throws IOException, ConfigurationException {
    File configFile = tempFolder.newFile("with_model.yaml");
    Files.writeString(configFile.toPath(), "name: modelAgent\n" + "description: Agent with a model\n" + "instruction: test instruction\n" + "agent_class: LlmAgent\n" + "model: \"gemini-pro\"\n");
    String configPath = configFile.getAbsolutePath();
    BaseAgent agent = ConfigAgentUtils.fromConfig(configPath);
    assertThat(agent).isInstanceOf(LlmAgent.class);
    LlmAgent llmAgent = (LlmAgent) agent;
    assertThat(llmAgent.model()).isPresent();
    assertThat(llmAgent.model().get().modelName()).hasValue("gemini-pro");
}
"
    "@Test
public void fromConfig_withEmptyModel_doesNotSetModelOnAgent() throws IOException, ConfigurationException {
    File configFile = tempFolder.newFile("empty_model.yaml");
    Files.writeString(configFile.toPath(), "name: emptyModelAgent\n" + "description: Agent with an empty model\n" + "instruction: test instruction\n" + "agent_class: LlmAgent\n" + "model: \"\"\n");
    String configPath = configFile.getAbsolutePath();
    BaseAgent agent = ConfigAgentUtils.fromConfig(configPath);
    assertThat(agent).isInstanceOf(LlmAgent.class);
    LlmAgent llmAgent = (LlmAgent) agent;
    assertThat(llmAgent.model()).isEmpty();
}
"
    "@Test
public void fromConfig_withMcpToolsetSseParams_loadsToolset() throws IOException, ConfigurationException {
    File configFile = tempFolder.newFile("with_mcp_sse_toolset.yaml");
    Files.writeString(configFile.toPath(), """
        name: mcp_sse_agent
        model: gemini-1.5-flash
        instruction: You are an agent that uses an MCP toolset with SSE connection.
        description: Agent with SSE-based MCP toolset for event streaming
        agent_class: LlmAgent
        tools:
          - name: McpToolset
            args:
              sse_server_params:
                url: "http:
                sse_endpoint: "/events"
                headers:
                  Authorization: "Bearer test-token"
                  Content-Type: "text/event-stream"
                  X-Custom-Header: "custom-value"
                timeout: 10000
                sse_read_timeout: 300000
              tool_filter:
                - "allowed_tool_1"
                - "allowed_tool_2"
                - "allowed_tool_3"
        """);
    String configPath = configFile.getAbsolutePath();
    BaseAgent agent = ConfigAgentUtils.fromConfig(configPath);
    assertThat(agent).isInstanceOf(LlmAgent.class);
    LlmAgent llmAgent = (LlmAgent) agent;
    assertThat(llmAgent.name()).isEqualTo("mcp_sse_agent");
    assertThat(llmAgent.description()).isEqualTo("Agent with SSE-based MCP toolset for event streaming");
    assertThat(llmAgent.instruction()).isNotNull();
    assertThat(llmAgent.instruction().toString()).contains("You are an agent that uses an MCP toolset with SSE connection.");
    assertThat(llmAgent.model()).isPresent();
    assertThat(llmAgent.toolsets()).hasSize(1);
    assertThat(llmAgent.toolsets().get(0)).isInstanceOf(McpToolset.class);
    String originalYaml = Files.readString(configFile.toPath());
    assertThat(originalYaml).contains("sse_server_params");
    assertThat(originalYaml).contains("sse_endpoint");
    assertThat(originalYaml).contains("sse_read_timeout");
    assertThat(originalYaml).contains("tool_filter");
    assertThat(originalYaml).contains("agent_class");
}
"
    "@Test
public void fromConfig_withIncludeContentsAndOtherFields_parsesAllFieldsCorrectly() throws IOException, ConfigurationException {
    File configFile = tempFolder.newFile("complete_config.yaml");
    Files.writeString(configFile.toPath(), """
        name: completeAgent
        description: Agent with all fields including include_contents
        instruction: You are a complete test agent
        agent_class: LlmAgent
        model: gemini-1.5-flash
        include_contents: none
        output_key: testOutput
        disallow_transfer_to_parent: true
        disallow_transfer_to_peers: false
        tools:
          - name: google_search
        """);
    String configPath = configFile.getAbsolutePath();
    BaseAgent agent = ConfigAgentUtils.fromConfig(configPath);
    assertThat(agent).isInstanceOf(LlmAgent.class);
    LlmAgent llmAgent = (LlmAgent) agent;
    assertThat(llmAgent.name()).isEqualTo("completeAgent");
    assertThat(llmAgent.description()).isEqualTo("Agent with all fields including include_contents");
    assertThat(llmAgent.includeContents()).isEqualTo(LlmAgent.IncludeContents.NONE);
    assertThat(llmAgent.outputKey()).hasValue("testOutput");
    assertThat(llmAgent.disallowTransferToParent()).isTrue();
    assertThat(llmAgent.disallowTransferToPeers()).isFalse();
    assertThat(llmAgent.tools()).hasSize(1);
    assertThat(llmAgent.model()).isPresent();
}
"
    "@Test
public void fromConfig_withOutputKeyAndOtherFields_parsesAllFields() throws IOException, ConfigurationException {
    File configFile = tempFolder.newFile("output_key_complete.yaml");
    Files.writeString(configFile.toPath(), """
        agent_class: LlmAgent
        name: CompleteAgentWithOutputKey
        model: gemini-2.0-flash
        description: Agent with output key and other configurations
        instruction: Process and store output
        output_key: result_data
        include_contents: NONE
        disallow_transfer_to_parent: true
        disallow_transfer_to_peers: false
        """);
    String configPath = configFile.getAbsolutePath();
    BaseAgent agent = ConfigAgentUtils.fromConfig(configPath);
    assertThat(agent).isInstanceOf(LlmAgent.class);
    LlmAgent llmAgent = (LlmAgent) agent;
    assertThat(llmAgent.name()).isEqualTo("CompleteAgentWithOutputKey");
    assertThat(llmAgent.outputKey()).hasValue("result_data");
    assertThat(llmAgent.includeContents()).isEqualTo(LlmAgent.IncludeContents.NONE);
    assertThat(llmAgent.disallowTransferToParent()).isTrue();
    assertThat(llmAgent.disallowTransferToPeers()).isFalse();
    assertThat(llmAgent.model()).isPresent();
}
"
    "@Test
public void fromConfig_withGenerateContentConfigSafetySettings() throws IOException, ConfigurationException {
    File configFile = tempFolder.newFile("generate_content_config_safety.yaml");
    Files.writeString(configFile.toPath(), """
        agent_class: LlmAgent
        model: gemini-2.5-flash
        name: root_agent
        description: dice agent
        instruction: You are a helpful assistant
        generate_content_config:
          safety_settings:
            - category: HARM_CATEGORY_DANGEROUS_CONTENT
              threshold: 'OFF'
        """);
    String configPath = configFile.getAbsolutePath();
    BaseAgent agent = ConfigAgentUtils.fromConfig(configPath);
    assertThat(agent).isInstanceOf(LlmAgent.class);
    LlmAgent llmAgent = (LlmAgent) agent;
    assertThat(llmAgent.name()).isEqualTo("root_agent");
    assertThat(llmAgent.description()).isEqualTo("dice agent");
    assertThat(llmAgent.model()).isPresent();
    assertThat(llmAgent.model().get().modelName()).hasValue("gemini-2.5-flash");
    assertThat(llmAgent.generateContentConfig()).isPresent();
    GenerateContentConfig config = llmAgent.generateContentConfig().get();
    assertThat(config).isNotNull();
    assertThat(config.safetySettings()).isPresent();
    assertThat(config.safetySettings().get()).hasSize(1);

    assertThat(config.safetySettings().get().get(0).category()).isPresent();
    assertThat(config.safetySettings().get().get(0).category().get().toString()).isEqualTo("HARM_CATEGORY_DANGEROUS_CONTENT");
    assertThat(config.safetySettings().get().get(0).threshold()).isPresent();
    assertThat(config.safetySettings().get().get(0).threshold().get().toString()).isEqualTo("OFF");
}
"
    "@Test
public void fromConfig_withExamplesList_appendsExamplesInFlow() throws IOException, ConfigurationException {

    ComponentRegistry originalRegistry = ComponentRegistry.getInstance();
    class TestRegistry extends ComponentRegistry {

        TestRegistry() {
            super();
        }
    }
    ComponentRegistry testRegistry = new TestRegistry();
    Example example = Example.builder().input(Content.fromParts(Part.fromText("qin"))).output(ImmutableList.of(Content.fromParts(Part.fromText("qout")))).build();
    testRegistry.register("multi_agent_llm_config.example_tool", ExampleTool.builder().addExample(example).build());
    ComponentRegistry.setInstance(testRegistry);
    File configFile = tempFolder.newFile("with_examples.yaml");
    Files.writeString(configFile.toPath(), """
        name: examples_agent
        description: Agent with examples configured via tool
        instruction: You are a test agent
        agent_class: LlmAgent
        model: gemini-2.0-flash
        tools:
          - name: multi_agent_llm_config.example_tool
        """);
    String configPath = configFile.getAbsolutePath();
    BaseAgent agent;
    try {
        agent = ConfigAgentUtils.fromConfig(configPath);
    } finally {
        ComponentRegistry.setInstance(originalRegistry);
    }
    assertThat(agent).isInstanceOf(LlmAgent.class);
    LlmAgent llmAgent = (LlmAgent) agent;

    LlmRequest.Builder requestBuilder = LlmRequest.builder().model("gemini-2.0-flash");
    InvocationContext context = TestUtils.createInvocationContext(agent);
    llmAgent.canonicalTools(new ReadonlyContext(context)).concatMapCompletable(tool -> tool.processLlmRequest(requestBuilder, ToolContext.builder(context).build())).blockingAwait();
    LlmRequest updated = requestBuilder.build();

    assertThat(updated.getSystemInstructions()).isNotEmpty();
}
"
    "@Test
public void testLlmAgentConfigAccessors() {
    LlmAgentConfig config = new LlmAgentConfig();
    assertThat(config.agentClass()).isEqualTo("LlmAgent");
    config.setModel("test-model");
    assertThat(config.model()).isEqualTo("test-model");
    config.setInstruction("test instruction");
    assertThat(config.instruction()).isEqualTo("test instruction");
    config.setDisallowTransferToParent(true);
    assertThat(config.disallowTransferToParent()).isTrue();
    config.setDisallowTransferToPeers(false);
    assertThat(config.disallowTransferToPeers()).isFalse();
    config.setOutputKey("test-output-key");
    assertThat(config.outputKey()).isEqualTo("test-output-key");
    config.setIncludeContents(LlmAgent.IncludeContents.NONE);
    assertThat(config.includeContents()).isEqualTo(LlmAgent.IncludeContents.NONE);
    GenerateContentConfig contentConfig = GenerateContentConfig.builder().temperature(0.8f).build();
    config.setGenerateContentConfig(contentConfig);
    assertThat(config.generateContentConfig()).isEqualTo(contentConfig);
    List<LlmAgentConfig.CallbackRef> beforeAgentCallbacks = new ArrayList<>();
    beforeAgentCallbacks.add(new LlmAgentConfig.CallbackRef("callback1"));
    config.setBeforeAgentCallbacks(beforeAgentCallbacks);
    assertThat(config.beforeAgentCallbacks()).hasSize(1);
    assertThat(config.beforeAgentCallbacks().get(0).name()).isEqualTo("callback1");
    List<LlmAgentConfig.CallbackRef> afterAgentCallbacks = new ArrayList<>();
    afterAgentCallbacks.add(new LlmAgentConfig.CallbackRef("callback2"));
    config.setAfterAgentCallbacks(afterAgentCallbacks);
    assertThat(config.afterAgentCallbacks()).hasSize(1);
    assertThat(config.afterAgentCallbacks().get(0).name()).isEqualTo("callback2");
    List<LlmAgentConfig.CallbackRef> beforeModelCallbacks = new ArrayList<>();
    beforeModelCallbacks.add(new LlmAgentConfig.CallbackRef("callback3"));
    config.setBeforeModelCallbacks(beforeModelCallbacks);
    assertThat(config.beforeModelCallbacks()).hasSize(1);
    assertThat(config.beforeModelCallbacks().get(0).name()).isEqualTo("callback3");
    List<LlmAgentConfig.CallbackRef> afterModelCallbacks = new ArrayList<>();
    afterModelCallbacks.add(new LlmAgentConfig.CallbackRef("callback4"));
    config.setAfterModelCallbacks(afterModelCallbacks);
    assertThat(config.afterModelCallbacks()).hasSize(1);
    assertThat(config.afterModelCallbacks().get(0).name()).isEqualTo("callback4");
    List<LlmAgentConfig.CallbackRef> beforeToolCallbacks = new ArrayList<>();
    beforeToolCallbacks.add(new LlmAgentConfig.CallbackRef("callback5"));
    config.setBeforeToolCallbacks(beforeToolCallbacks);
    assertThat(config.beforeToolCallbacks()).hasSize(1);
    assertThat(config.beforeToolCallbacks().get(0).name()).isEqualTo("callback5");
    List<LlmAgentConfig.CallbackRef> afterToolCallbacks = new ArrayList<>();
    afterToolCallbacks.add(new LlmAgentConfig.CallbackRef("callback6"));
    config.setAfterToolCallbacks(afterToolCallbacks);
    assertThat(config.afterToolCallbacks()).hasSize(1);
    assertThat(config.afterToolCallbacks().get(0).name()).isEqualTo("callback6");
    List<BaseTool.ToolConfig> tools = new ArrayList<>();
    BaseTool.ToolConfig toolConfig = new BaseTool.ToolConfig();
    toolConfig.setName("test-tool");
    tools.add(toolConfig);
    config.setTools(tools);
    assertThat(config.tools()).hasSize(1);
    assertThat(config.tools().get(0).name()).isEqualTo("test-tool");
}
"

File Path: /var/tmp/Roost/RoostGPT/adk-java-repo/87694200-c46c-408c-b0b1-408cb60f3b49/source/adk-java/core/src/test/java/com/google/adk/tools/BaseToolTest.java
Tests:
    "@Test
public void processLlmRequestNoDeclarationReturnsSameRequest() {
    BaseTool tool = new BaseTool("test_tool", "test_description") {

        @Override
        public Optional<FunctionDeclaration> declaration() {
            return Optional.empty();
        }

        @Override
        public Single<Map<String, Object>> runAsync(Map<String, Object> args, ToolContext toolContext) {
            return Single.just(null);
        }
    };
    LlmRequest llmRequest = LlmRequest.builder().model("Senatus Populusque Romanus").build();
    LlmRequest.Builder llmRequestBuilder = llmRequest.toBuilder();
    Completable unused = tool.processLlmRequest(llmRequestBuilder,
    null);
    assertThat(llmRequestBuilder.build()).isEqualTo(llmRequest);
}
"
    "@Test
public void processLlmRequestWithGoogleSearchToolAddsToolToConfig() {
    FunctionDeclaration functionDeclaration = FunctionDeclaration.builder().name("test_function").build();
    GoogleSearchTool googleSearchTool = new GoogleSearchTool();
    LlmRequest llmRequest = LlmRequest.builder().config(GenerateContentConfig.builder().tools(ImmutableList.of(Tool.builder().functionDeclarations(ImmutableList.of(functionDeclaration)).build())).build()).model("gemini-2").build();
    LlmRequest.Builder llmRequestBuilder = llmRequest.toBuilder();
    Completable unused = googleSearchTool.processLlmRequest(llmRequestBuilder,
    null);
    LlmRequest updatedLlmRequest = llmRequestBuilder.build();
    assertThat(updatedLlmRequest.config()).isPresent();
    assertThat(updatedLlmRequest.config().get().tools()).isPresent();
    assertThat(updatedLlmRequest.config().get().tools().get()).containsExactly(Tool.builder().functionDeclarations(ImmutableList.of(functionDeclaration)).build(), Tool.builder().googleSearch(GoogleSearch.builder().build()).build());
}
"
    "@Test
public void processLlmRequestWithGoogleSearchRetrievalToolAddsToolToConfig() {
    GoogleSearchTool googleSearchTool = new GoogleSearchTool();
    LlmRequest llmRequest = LlmRequest.builder().config(GenerateContentConfig.builder().build()).model("gemini-1").build();
    LlmRequest.Builder llmRequestBuilder = llmRequest.toBuilder();
    Completable unused = googleSearchTool.processLlmRequest(llmRequestBuilder,
    null);
    LlmRequest updatedLlmRequest = llmRequestBuilder.build();
    assertThat(updatedLlmRequest.config()).isPresent();
    assertThat(updatedLlmRequest.config().get().tools()).isPresent();
    assertThat(updatedLlmRequest.config().get().tools().get()).containsExactly(Tool.builder().googleSearchRetrieval(GoogleSearchRetrieval.builder().build()).build());
}
"
    "@Test
public void processLlmRequestWithUrlContextToolAddsToolToConfig() {
    FunctionDeclaration functionDeclaration = FunctionDeclaration.builder().name("test_function").build();
    UrlContextTool urlContextTool = new UrlContextTool();
    LlmRequest llmRequest = LlmRequest.builder().config(GenerateContentConfig.builder().tools(ImmutableList.of(Tool.builder().functionDeclarations(ImmutableList.of(functionDeclaration)).build())).build()).model("gemini-2").build();
    LlmRequest.Builder llmRequestBuilder = llmRequest.toBuilder();
    Completable unused = urlContextTool.processLlmRequest(llmRequestBuilder,
    null);
    LlmRequest updatedLlmRequest = llmRequestBuilder.build();
    assertThat(updatedLlmRequest.config()).isPresent();
    assertThat(updatedLlmRequest.config().get().tools()).isPresent();
    assertThat(updatedLlmRequest.config().get().tools().get()).containsExactly(Tool.builder().functionDeclarations(ImmutableList.of(functionDeclaration)).build(), Tool.builder().urlContext(UrlContext.builder().build()).build());
}
"
    "@Test
public void processLlmRequestWithBuiltInCodeExecutionToolAddsToolToConfig() {
    BuiltInCodeExecutionTool builtInCodeExecutionTool = new BuiltInCodeExecutionTool();
    LlmRequest llmRequest = LlmRequest.builder().config(GenerateContentConfig.builder().build()).model("gemini-2").build();
    LlmRequest.Builder llmRequestBuilder = llmRequest.toBuilder();
    Completable unused = builtInCodeExecutionTool.processLlmRequest(llmRequestBuilder,
    null);
    LlmRequest updatedLlmRequest = llmRequestBuilder.build();
    assertThat(updatedLlmRequest.config()).isPresent();
    assertThat(updatedLlmRequest.config().get().tools()).isPresent();
    assertThat(updatedLlmRequest.config().get().tools().get()).containsExactly(Tool.builder().codeExecution(ToolCodeExecution.builder().build()).build());
}
"

File Path: /var/tmp/Roost/RoostGPT/adk-java-repo/87694200-c46c-408c-b0b1-408cb60f3b49/source/adk-java/core/src/test/java/com/google/adk/flows/llmflows/BasicTest.java
Tests:
    "@Test
public void processRequest_populatesBasicFields() {
    RequestProcessingResult result = basicProcessor.processRequest(testContext, initialRequest).blockingGet();
    LlmRequest updatedRequest = result.updatedRequest();
    assertThat(updatedRequest.model()).hasValue(TEST_MODEL_NAME);
    assertThat(updatedRequest.config()).isPresent();
    assertThat(updatedRequest.config().get().temperature()).isNotEqualTo(TEST_GEN_CONFIG.temperature());
    assertThat(updatedRequest.liveConnectConfig()).isNotNull();
    assertThat(updatedRequest.liveConnectConfig().responseModalities().get()).isEmpty();
    assertThat(result.events()).isEmpty();
}
"
    "@Test
public void processRequest_usesAgentConfigAndSchema() {
    LlmAgent agentWithConfig = LlmAgent.builder().name("agentWithConfig").model(testLlm).generateContentConfig(TEST_GEN_CONFIG).outputSchema(TEST_OUTPUT_SCHEMA).build();
    InvocationContext contextWithConfig = createInvocationContext(agentWithConfig);
    RequestProcessingResult result = basicProcessor.processRequest(contextWithConfig, initialRequest).blockingGet();
    LlmRequest updatedRequest = result.updatedRequest();
    assertThat(updatedRequest.model()).hasValue(testLlm.model());
    assertThat(updatedRequest.config()).isPresent();
    assertThat(updatedRequest.config().get().temperature()).isEqualTo(TEST_GEN_CONFIG.temperature());
    assertThat(updatedRequest.config().get().responseSchema()).hasValue(TEST_OUTPUT_SCHEMA);
    assertThat(updatedRequest.config().get().responseMimeType()).hasValue("application/json");
    assertThat(result.events()).isEmpty();
}
"
    "@Test
public void processRequest_buildsLiveConnectConfigFromRunConfig() {
    RunConfig runConfig = RunConfig.builder().setResponseModalities(ImmutableList.of(new Modality(Modality.Known.TEXT))).build();
    LlmAgent agentWithConfig = LlmAgent.builder().name("agentWithConfig").model(testLlm).build();
    InvocationContext contextWithRunConfig = createInvocationContext(agentWithConfig, runConfig);
    RequestProcessingResult result = basicProcessor.processRequest(contextWithRunConfig, initialRequest).blockingGet();
    LlmRequest updatedRequest = result.updatedRequest();
    assertThat(updatedRequest.liveConnectConfig()).isNotNull();
    assertThat(updatedRequest.liveConnectConfig().responseModalities().get()).containsExactly(new Modality(Modality.Known.TEXT));
    assertThat(result.events()).isEmpty();
}
"
    "@Test
public void processRequest_buildsLiveConnectConfigFromRunConfig_responseModalities() {
    RunConfig runConfig = RunConfig.builder().setResponseModalities(ImmutableList.of(new Modality(Modality.Known.TEXT))).build();
    LlmAgent agentWithConfig = LlmAgent.builder().name("agentWithConfig").model(testLlm).build();
    InvocationContext contextWithRunConfig = createInvocationContext(agentWithConfig, runConfig);
    RequestProcessingResult result = basicProcessor.processRequest(contextWithRunConfig, initialRequest).blockingGet();
    LlmRequest updatedRequest = result.updatedRequest();
    assertThat(updatedRequest.liveConnectConfig()).isNotNull();
    assertThat(updatedRequest.liveConnectConfig().responseModalities().get()).containsExactly(new Modality(Modality.Known.TEXT));
    assertThat(updatedRequest.liveConnectConfig().speechConfig()).isEmpty();
    assertThat(updatedRequest.liveConnectConfig().outputAudioTranscription()).isEmpty();
    assertThat(result.events()).isEmpty();
}
"
    "@Test
public void processRequest_buildsLiveConnectConfigFromRunConfig_speechConfig() {
    RunConfig runConfig = RunConfig.builder().setSpeechConfig(TEST_SPEECH_CONFIG).build();
    LlmAgent agentWithConfig = LlmAgent.builder().name("agentWithConfig").model(testLlm).build();
    InvocationContext contextWithRunConfig = createInvocationContext(agentWithConfig, runConfig);
    RequestProcessingResult result = basicProcessor.processRequest(contextWithRunConfig, initialRequest).blockingGet();
    LlmRequest updatedRequest = result.updatedRequest();
    assertThat(updatedRequest.liveConnectConfig()).isNotNull();
    assertThat(updatedRequest.liveConnectConfig().responseModalities().get()).isEmpty();
    assertThat(updatedRequest.liveConnectConfig().speechConfig()).hasValue(TEST_SPEECH_CONFIG);
    assertThat(updatedRequest.liveConnectConfig().outputAudioTranscription()).isEmpty();
    assertThat(result.events()).isEmpty();
}
"
    "@Test
public void processRequest_buildsLiveConnectConfigFromRunConfig_outputAudioTranscription() {
    RunConfig runConfig = RunConfig.builder().setOutputAudioTranscription(TEST_AUDIO_TRANSCRIPTION_CONFIG).build();
    LlmAgent agentWithConfig = LlmAgent.builder().name("agentWithConfig").model(testLlm).build();
    InvocationContext contextWithRunConfig = createInvocationContext(agentWithConfig, runConfig);
    RequestProcessingResult result = basicProcessor.processRequest(contextWithRunConfig, initialRequest).blockingGet();
    LlmRequest updatedRequest = result.updatedRequest();
    assertThat(updatedRequest.liveConnectConfig()).isNotNull();
    assertThat(updatedRequest.liveConnectConfig().responseModalities().get()).isEmpty();
    assertThat(updatedRequest.liveConnectConfig().speechConfig()).isEmpty();
    assertThat(updatedRequest.liveConnectConfig().outputAudioTranscription()).hasValue(TEST_AUDIO_TRANSCRIPTION_CONFIG);
    assertThat(result.events()).isEmpty();
}
"
    "@Test
public void processRequest_buildsLiveConnectConfigFromRunConfig_inputAudioTranscription() {
    RunConfig runConfig = RunConfig.builder().setInputAudioTranscription(TEST_AUDIO_TRANSCRIPTION_CONFIG).build();
    LlmAgent agentWithConfig = LlmAgent.builder().name("agentWithConfig").model(testLlm).build();
    InvocationContext contextWithRunConfig = createInvocationContext(agentWithConfig, runConfig);
    RequestProcessingResult result = basicProcessor.processRequest(contextWithRunConfig, initialRequest).blockingGet();
    LlmRequest updatedRequest = result.updatedRequest();
    assertThat(updatedRequest.liveConnectConfig()).isNotNull();
    assertThat(updatedRequest.liveConnectConfig().responseModalities().get()).isEmpty();
    assertThat(updatedRequest.liveConnectConfig().speechConfig()).isEmpty();
    assertThat(updatedRequest.liveConnectConfig().inputAudioTranscription()).hasValue(TEST_AUDIO_TRANSCRIPTION_CONFIG);
    assertThat(result.events()).isEmpty();
}
"
    "@Test
public void processRequest_buildsLiveConnectConfigFromRunConfig_allFields() {
    RunConfig runConfig = RunConfig.builder().setResponseModalities(ImmutableList.of(new Modality(Modality.Known.AUDIO))).setSpeechConfig(TEST_SPEECH_CONFIG).setOutputAudioTranscription(TEST_AUDIO_TRANSCRIPTION_CONFIG).setInputAudioTranscription(TEST_AUDIO_TRANSCRIPTION_CONFIG).build();
    LlmAgent agentWithConfig = LlmAgent.builder().name("agentWithConfig").model(testLlm).build();
    InvocationContext contextWithRunConfig = createInvocationContext(agentWithConfig, runConfig);
    RequestProcessingResult result = basicProcessor.processRequest(contextWithRunConfig, initialRequest).blockingGet();
    LlmRequest updatedRequest = result.updatedRequest();
    assertThat(updatedRequest.liveConnectConfig()).isNotNull();
    assertThat(updatedRequest.liveConnectConfig().responseModalities().get()).containsExactly(new Modality(Modality.Known.AUDIO));
    assertThat(updatedRequest.liveConnectConfig().speechConfig()).hasValue(TEST_SPEECH_CONFIG);
    assertThat(updatedRequest.liveConnectConfig().outputAudioTranscription()).hasValue(TEST_AUDIO_TRANSCRIPTION_CONFIG);
    assertThat(updatedRequest.liveConnectConfig().inputAudioTranscription()).hasValue(TEST_AUDIO_TRANSCRIPTION_CONFIG);
    assertThat(result.events()).isEmpty();
}
"

File Path: /var/tmp/Roost/RoostGPT/adk-java-repo/87694200-c46c-408c-b0b1-408cb60f3b49/source/adk-java/core/src/test/java/com/google/adk/testing/TestUtils.java
Tests:
    "@Test
public static LlmAgent.Builder createTestAgentBuilder(BaseLlm llm) {
    return LlmAgent.builder().name("test agent").description("test agent description").model(llm);
}
"Scenario 1: Verify model() returns the correct model name when initialized with a standard model name

Details:
  TestName: modelReturnsCorrectModelNameWhenInitializedWithStandardName
  Description: This test verifies that the model() method correctly returns the model name that was passed to the constructor when using a standard model name like "gemini-1.5-flash".

Execution:
  Arrange: Create a concrete implementation of BaseLlm (using a test subclass or mock) with the model name "gemini-1.5-flash".
  Act: Call the model() method on the BaseLlm instance.
  Assert: Assert that the returned value equals "gemini-1.5-flash".

Validation:
  The assertion verifies that the model() method correctly returns the model name stored in the private final field. This is important because the model name is used throughout the application to identify which LLM is being used for content generation and routing requests to the appropriate backend.

---

Scenario 2: Verify model() returns the correct model name when initialized with a versioned model name

Details:
  TestName: modelReturnsCorrectModelNameWhenInitializedWithVersionedName
  Description: This test verifies that the model() method correctly returns a versioned model name like "gemini-1.5-flash-001" that was passed to the constructor.

Execution:
  Arrange: Create a concrete implementation of BaseLlm with the model name "gemini-1.5-flash-001".
  Act: Call the model() method on the BaseLlm instance.
  Assert: Assert that the returned value equals "gemini-1.5-flash-001".

Validation:
  The assertion confirms that versioned model names are preserved exactly as provided. This is critical for ensuring that specific model versions can be targeted when needed for reproducibility or compatibility reasons.

---

Scenario 3: Verify model() returns an empty string when initialized with an empty string

Details:
  TestName: modelReturnsEmptyStringWhenInitializedWithEmptyString
  Description: This test verifies that the model() method returns an empty string when the BaseLlm is initialized with an empty string as the model name.

Execution:
  Arrange: Create a concrete implementation of BaseLlm with an empty string "" as the model name.
  Act: Call the model() method on the BaseLlm instance.
  Assert: Assert that the returned value equals "".

Validation:
  The assertion verifies that the model() method does not modify or transform the input value. An empty model name might be used in scenarios where the model is determined dynamically or when a default model should be used by the underlying implementation.

---

Scenario 4: Verify model() returns null when initialized with null

Details:
  TestName: modelReturnsNullWhenInitializedWithNull
  Description: This test verifies the behavior of model() when the BaseLlm is initialized with a null model name.

Execution:
  Arrange: Create a concrete implementation of BaseLlm with null as the model name.
  Act: Call the model() method on the BaseLlm instance.
  Assert: Assert that the returned value is null.

Validation:
  The assertion confirms that the model() method returns exactly what was stored, including null values. This test is important for understanding edge case behavior and ensuring that null handling is consistent throughout the application.

---

Scenario 5: Verify model() returns the correct model name with special characters

Details:
  TestName: modelReturnsCorrectModelNameWithSpecialCharacters
  Description: This test verifies that the model() method correctly handles model names containing special characters like slashes, which might be used in prefixed model names (e.g., "apigee/gemini/v1/gemini-1.5-flash").

Execution:
  Arrange: Create a concrete implementation of BaseLlm with the model name "apigee/gemini/v1/gemini-1.5-flash".
  Act: Call the model() method on the BaseLlm instance.
  Assert: Assert that the returned value equals "apigee/gemini/v1/gemini-1.5-flash".

Validation:
  The assertion verifies that model names with path-like structures or special characters are preserved exactly. This is important for supporting various model naming conventions used by different providers or routing mechanisms.

---

Scenario 6: Verify model() returns the correct model name with numeric suffix

Details:
  TestName: modelReturnsCorrectModelNameWithNumericSuffix
  Description: This test verifies that the model() method correctly returns model names that include numeric suffixes like "gemini-2.0-flash" or "gemini-2-pro".

Execution:
  Arrange: Create a concrete implementation of BaseLlm with the model name "gemini-2.0-flash".
  Act: Call the model() method on the BaseLlm instance.
  Assert: Assert that the returned value equals "gemini-2.0-flash".

Validation:
  The assertion confirms that model names with version numbers in various formats are handled correctly. This is essential for supporting the evolving naming conventions of LLM models across different generations.

---

Scenario 7: Verify model() returns consistent value on multiple calls

Details:
  TestName: modelReturnsConsistentValueOnMultipleCalls
  Description: This test verifies that the model() method returns the same value consistently across multiple invocations, confirming the immutability of the model field.

Execution:
  Arrange: Create a concrete implementation of BaseLlm with the model name "gemini-1.5-flash".
  Act: Call the model() method multiple times (at least 3 times) on the same BaseLlm instance.
  Assert: Assert that all returned values are equal to "gemini-1.5-flash" and equal to each other.

Validation:
  The assertion verifies that the model name is immutable and consistent. Since the model field is declared as final, this test confirms that the implementation correctly maintains immutability, which is important for thread safety and predictable behavior.

---

Scenario 8: Verify model() returns the correct model name with whitespace

Details:
  TestName: modelReturnsModelNameWithWhitespacePreserved
  Description: This test verifies that the model() method preserves any whitespace in the model name, even though this would typically be an invalid model name.

Execution:
  Arrange: Create a concrete implementation of BaseLlm with the model name " gemini-1.5-flash " (with leading and trailing spaces).
  Act: Call the model() method on the BaseLlm instance.
  Assert: Assert that the returned value equals " gemini-1.5-flash " including the whitespace.

Validation:
  The assertion confirms that the model() method does not perform any trimming or sanitization of the input. This is important for understanding the exact behavior of the method and ensuring that any validation or sanitization is handled at the appropriate layer.

---

Scenario 9: Verify model() returns the correct model name for different LLM providers

Details:
  TestName: modelReturnsCorrectModelNameForDifferentProviders
  Description: This test verifies that the model() method correctly handles model names from different providers, such as "gemini-pro", "gemini-2.5-flash", or custom model identifiers.

Execution:
  Arrange: Create a concrete implementation of BaseLlm with the model name "gemini-2.5-flash".
  Act: Call the model() method on the BaseLlm instance.
  Assert: Assert that the returned value equals "gemini-2.5-flash".

Validation:
  The assertion verifies that the model() method works correctly with various model naming patterns used across different LLM providers and versions. This ensures flexibility in supporting multiple model types within the same framework.

---

Scenario 10: Verify model() returns the correct model name with hyphenated format

Details:
  TestName: modelReturnsCorrectModelNameWithHyphenatedFormat
  Description: This test verifies that the model() method correctly handles model names with multiple hyphens, which is a common naming convention for LLM models.

Execution:
  Arrange: Create a concrete implementation of BaseLlm with the model name "gemini-1-pro".
  Act: Call the model() method on the BaseLlm instance.
  Assert: Assert that the returned value equals "gemini-1-pro".

Validation:
  The assertion confirms that hyphenated model names are preserved correctly. This is important because many LLM models use hyphenated naming conventions to indicate model family, version, and variant.

*/

// ********RoostGPT********

package com.google.adk.models;

import static com.google.common.truth.Truth.assertThat;

import io.reactivex.rxjava3.core.Flowable;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class BaseLlmModelTest {

  // Concrete implementation of BaseLlm for testing purposes
  private static class TestBaseLlm extends BaseLlm {

    public TestBaseLlm(String model) {
      super(model);
    }

    @Override
    public Flowable<LlmResponse> generateContent(LlmRequest llmRequest, boolean stream) {
      return Flowable.empty();
    }

    @Override
    public BaseLlmConnection connect(LlmRequest llmRequest) {
      return null;
    }
  }

  @Test
  @Tag("valid")
  void modelReturnsCorrectModelNameWhenInitializedWithStandardName() {
    // Arrange
    String expectedModelName = "gemini-1.5-flash";
    BaseLlm baseLlm = new TestBaseLlm(expectedModelName);
    // Act
    String actualModelName = baseLlm.model();
    // Assert
    assertThat(actualModelName).isEqualTo(expectedModelName);
  }

  @Test
  @Tag("valid")
  void modelReturnsCorrectModelNameWhenInitializedWithVersionedName() {
    // Arrange
    String expectedModelName = "gemini-1.5-flash-001";
    BaseLlm baseLlm = new TestBaseLlm(expectedModelName);
    // Act
    String actualModelName = baseLlm.model();
    // Assert
    assertThat(actualModelName).isEqualTo(expectedModelName);
  }

  @Test
  @Tag("boundary")
  void modelReturnsEmptyStringWhenInitializedWithEmptyString() {
    // Arrange
    String expectedModelName = "";
    BaseLlm baseLlm = new TestBaseLlm(expectedModelName);
    // Act
    String actualModelName = baseLlm.model();
    // Assert
    assertThat(actualModelName).isEqualTo(expectedModelName);
  }

  @Test
  @Tag("boundary")
  void modelReturnsNullWhenInitializedWithNull() {
    // Arrange
    BaseLlm baseLlm = new TestBaseLlm(null);
    // Act
    String actualModelName = baseLlm.model();
    // Assert
    assertThat(actualModelName).isNull();
  }

  @Test
  @Tag("valid")
  void modelReturnsCorrectModelNameWithSpecialCharacters() {
    // Arrange
    String expectedModelName = "apigee/gemini/v1/gemini-1.5-flash";
    BaseLlm baseLlm = new TestBaseLlm(expectedModelName);
    // Act
    String actualModelName = baseLlm.model();
    // Assert
    assertThat(actualModelName).isEqualTo(expectedModelName);
  }

  @Test
  @Tag("valid")
  void modelReturnsCorrectModelNameWithNumericSuffix() {
    // Arrange
    String expectedModelName = "gemini-2.0-flash";
    BaseLlm baseLlm = new TestBaseLlm(expectedModelName);
    // Act
    String actualModelName = baseLlm.model();
    // Assert
    assertThat(actualModelName).isEqualTo(expectedModelName);
  }

  @Test
  @Tag("valid")
  void modelReturnsConsistentValueOnMultipleCalls() {
    // Arrange
    String expectedModelName = "gemini-1.5-flash";
    BaseLlm baseLlm = new TestBaseLlm(expectedModelName);
    // Act
    String firstCall = baseLlm.model();
    String secondCall = baseLlm.model();
    String thirdCall = baseLlm.model();
    // Assert
    assertThat(firstCall).isEqualTo(expectedModelName);
    assertThat(secondCall).isEqualTo(expectedModelName);
    assertThat(thirdCall).isEqualTo(expectedModelName);
    assertThat(firstCall).isEqualTo(secondCall);
    assertThat(secondCall).isEqualTo(thirdCall);
  }

  @Test
  @Tag("boundary")
  void modelReturnsModelNameWithWhitespacePreserved() {
    // Arrange
    String expectedModelName = " gemini-1.5-flash ";
    BaseLlm baseLlm = new TestBaseLlm(expectedModelName);
    // Act
    String actualModelName = baseLlm.model();
    // Assert
    assertThat(actualModelName).isEqualTo(expectedModelName);
  }

  @Test
  @Tag("valid")
  void modelReturnsCorrectModelNameForDifferentProviders() {
    // Arrange
    String expectedModelName = "gemini-2.5-flash";
    BaseLlm baseLlm = new TestBaseLlm(expectedModelName);
    // Act
    String actualModelName = baseLlm.model();
    // Assert
    assertThat(actualModelName).isEqualTo(expectedModelName);
  }

  @Test
  @Tag("valid")
  void modelReturnsCorrectModelNameWithHyphenatedFormat() {
    // Arrange
    String expectedModelName = "gemini-1-pro";
    BaseLlm baseLlm = new TestBaseLlm(expectedModelName);
    // Act
    String actualModelName = baseLlm.model();
    // Assert
    assertThat(actualModelName).isEqualTo(expectedModelName);
  }
}
