/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-repo using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=generateContent_816aec4086
ROOST_METHOD_SIG_HASH=generateContent_816aec4086

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/adk-java-repo/87694200-c46c-408c-b0b1-408cb60f3b49/source/adk-java/core/src/test/java/com/google/adk/models/ApigeeLlmTest.java
Tests:
    "@Test
public void generateContent_stripsApigeePrefixAndSendsToDelegate() {
    when(mockGeminiDelegate.generateContent(any(), anyBoolean())).thenReturn(Flowable.empty());
    ApigeeLlm llm = new ApigeeLlm("apigee/gemini/v1/gemini-1.5-flash", mockGeminiDelegate);
    LlmRequest request = LlmRequest.builder().model("apigee/gemini/v1/gemini-1.5-flash").contents(ImmutableList.of(Content.builder().parts(Part.fromText("hi")).build())).build();
    llm.generateContent(request, true).test().assertNoErrors();
    ArgumentCaptor<LlmRequest> requestCaptor = ArgumentCaptor.forClass(LlmRequest.class);
    verify(mockGeminiDelegate).generateContent(requestCaptor.capture(), eq(true));
    assertThat(requestCaptor.getValue().model()).hasValue("gemini-1.5-flash");
}
"
    "@Test
public void build_withTrailingSlashInModel_parsesVersionAndModelId() {
    when(mockGeminiDelegate.generateContent(any(), anyBoolean())).thenReturn(Flowable.empty());
    ApigeeLlm llm = new ApigeeLlm("apigee/gemini/v1/", mockGeminiDelegate);
    LlmRequest request = LlmRequest.builder().contents(ImmutableList.of(Content.builder().parts(Part.fromText("hi")).build())).build();
    assertThrows(IllegalArgumentException.class, () -> llm.generateContent(request, false));
    verify(mockGeminiDelegate, never()).generateContent(any(), anyBoolean());
}
"

File Path: /var/tmp/Roost/RoostGPT/adk-java-repo/87694200-c46c-408c-b0b1-408cb60f3b49/source/adk-java/core/src/test/java/com/google/adk/testing/TestLlm.java
Tests:
    "@Test
public Flowable<LlmResponse> generateContent(LlmRequest llmRequest, boolean stream) {
    llmRequests.add(llmRequest);
    if (error.isPresent()) {
        return Flowable.error(error.get());
    }
    if (this.responseSequence != null) {

        int currentIndex = responseIndex.getAndIncrement();
        if (currentIndex < responseSequence.size()) {
            LlmResponse nextResponse = responseSequence.get(currentIndex);
            return Flowable.just(nextResponse);
        } else {
            return Flowable.error(new NoSuchElementException("TestLlm (List mode) out of responses. Requested response for LLM call " + llmRequests.size() + " (index " + currentIndex + ") but only " + responseSequence.size() + " were configured."));
        }
    } else if (this.responsesSupplier != null) {

        return responsesSupplier.get();
    } else {

        return Flowable.error(new IllegalStateException("TestLlm not initialized with responses."));
    }
}
"Scenario 1: Generate Content with Valid Request in Streaming Mode

Details:
  TestName: generateContentWithValidRequestStreamingMode
  Description: Verify that the generateContent method correctly processes a valid LlmRequest when streaming mode is enabled. This test ensures the method returns a Flowable that emits LlmResponse objects when stream parameter is true.

Execution:
  Arrange: Create a concrete implementation of BaseLlm for testing purposes. Prepare a valid LlmRequest with appropriate content and model configuration.
  Act: Invoke generateContent method with the prepared LlmRequest and stream parameter set to true.
  Assert: Verify that the returned Flowable is not null and emits expected LlmResponse objects without errors.

Validation:
  This assertion verifies that the streaming functionality works correctly when enabled. The significance of this test is to ensure that real-time response streaming is properly supported, which is critical for applications requiring incremental content delivery from the LLM.

---

Scenario 2: Generate Content with Valid Request in Non-Streaming Mode

Details:
  TestName: generateContentWithValidRequestNonStreamingMode
  Description: Verify that the generateContent method correctly processes a valid LlmRequest when streaming mode is disabled. This test ensures the method returns a Flowable that emits a single complete LlmResponse when stream parameter is false.

Execution:
  Arrange: Create a concrete implementation of BaseLlm for testing purposes. Prepare a valid LlmRequest with appropriate content and model configuration.
  Act: Invoke generateContent method with the prepared LlmRequest and stream parameter set to false.
  Assert: Verify that the returned Flowable emits exactly one LlmResponse and completes successfully.

Validation:
  This assertion verifies that non-streaming mode returns a complete response in a single emission. This is important for use cases where the entire response is needed before processing can begin.

---

Scenario 3: Generate Content with Null LlmRequest

Details:
  TestName: generateContentWithNullRequest
  Description: Verify the behavior of generateContent method when a null LlmRequest is passed. This test ensures proper error handling for invalid input parameters.

Execution:
  Arrange: Create a concrete implementation of BaseLlm for testing purposes.
  Act: Invoke generateContent method with null as the LlmRequest parameter and any boolean value for stream.
  Assert: Verify that the method either throws a NullPointerException or returns a Flowable that emits an error.

Validation:
  This assertion verifies that the method handles null input gracefully. Proper null handling is essential for preventing unexpected runtime failures and providing meaningful error messages to callers.

---

Scenario 4: Generate Content with Empty Content in LlmRequest

Details:
  TestName: generateContentWithEmptyContentRequest
  Description: Verify the behavior of generateContent method when the LlmRequest contains empty content. This test ensures the method handles edge cases where no actual content is provided.

Execution:
  Arrange: Create a concrete implementation of BaseLlm. Prepare an LlmRequest with empty or minimal content.
  Act: Invoke generateContent method with the empty content request and stream set to false.
  Assert: Verify the appropriate response or error handling for empty content scenarios.

Validation:
  This assertion verifies that the method properly handles requests with no meaningful content. This is important for input validation and preventing unnecessary API calls to the underlying LLM service.

---

Scenario 5: Generate Content Verifies Model Name Consistency

Details:
  TestName: generateContentPreservesModelName
  Description: Verify that the generateContent method uses the model name configured in the BaseLlm instance. This test ensures the model field is properly utilized during content generation.

Execution:
  Arrange: Create a concrete implementation of BaseLlm with a specific model name (e.g., "gemini-1.5-flash"). Prepare a valid LlmRequest.
  Act: Invoke generateContent method and capture the model information used in the request processing.
  Assert: Verify that the model name from the BaseLlm instance is correctly associated with the generation request.

Validation:
  This assertion verifies that the model configuration is properly maintained and used. This is critical for ensuring requests are routed to the correct LLM model as specified during initialization.

---

Scenario 6: Generate Content Returns Flowable That Can Be Subscribed Multiple Times

Details:
  TestName: generateContentFlowableSupportsMultipleSubscriptions
  Description: Verify that the Flowable returned by generateContent can be subscribed to multiple times, ensuring proper reactive stream behavior.

Execution:
  Arrange: Create a concrete implementation of BaseLlm. Prepare a valid LlmRequest.
  Act: Invoke generateContent method and subscribe to the returned Flowable multiple times.
  Assert: Verify that each subscription receives the expected LlmResponse without interference.

Validation:
  This assertion verifies the reactive stream contract is properly implemented. Multiple subscription support is important for scenarios where the same response needs to be processed by different consumers.

---

Scenario 7: Generate Content with Stream Toggle Produces Different Behavior

Details:
  TestName: generateContentStreamToggleAffectsBehavior
  Description: Verify that toggling the stream parameter between true and false produces different emission patterns from the returned Flowable.

Execution:
  Arrange: Create a concrete implementation of BaseLlm. Prepare identical LlmRequests for both streaming and non-streaming calls.
  Act: Invoke generateContent twice with the same request but different stream parameter values.
  Assert: Verify that streaming mode may emit multiple partial responses while non-streaming mode emits a single complete response.

Validation:
  This assertion verifies that the stream parameter correctly influences the response delivery mechanism. This distinction is crucial for applications that need to choose between immediate partial results and complete responses.

---

Scenario 8: Generate Content Handles Large Content Request

Details:
  TestName: generateContentWithLargeContentRequest
  Description: Verify that the generateContent method can handle LlmRequests with large content payloads without memory issues or timeouts.

Execution:
  Arrange: Create a concrete implementation of BaseLlm. Prepare an LlmRequest with a large content payload.
  Act: Invoke generateContent method with the large content request.
  Assert: Verify that the method processes the request and returns a valid Flowable without throwing OutOfMemoryError or similar exceptions.

Validation:
  This assertion verifies the method's robustness when handling large inputs. This is important for production scenarios where users may submit extensive prompts or documents for processing.

---

Scenario 9: Generate Content with Special Characters in Request

Details:
  TestName: generateContentWithSpecialCharactersInRequest
  Description: Verify that the generateContent method correctly handles LlmRequests containing special characters, unicode, or escape sequences in the content.

Execution:
  Arrange: Create a concrete implementation of BaseLlm. Prepare an LlmRequest with content containing special characters, emojis, or multi-byte unicode characters.
  Act: Invoke generateContent method with the special character content request.
  Assert: Verify that the method processes the request without encoding errors and returns appropriate responses.

Validation:
  This assertion verifies proper handling of diverse character sets. This is essential for internationalization support and handling user-generated content that may contain various character types.

---

Scenario 10: Generate Content Flowable Properly Handles Backpressure

Details:
  TestName: generateContentFlowableHandlesBackpressure
  Description: Verify that the Flowable returned by generateContent properly handles backpressure scenarios where the subscriber cannot keep up with emissions.

Execution:
  Arrange: Create a concrete implementation of BaseLlm. Prepare a valid LlmRequest. Set up a slow subscriber that introduces delays.
  Act: Invoke generateContent method with streaming enabled and subscribe with a slow consumer.
  Assert: Verify that the Flowable respects backpressure signals and does not overflow the subscriber's buffer.

Validation:
  This assertion verifies compliance with reactive streams backpressure handling. Proper backpressure management is critical for preventing memory issues in high-throughput scenarios.

*/

// ********RoostGPT********

package com.google.adk.models;

import static com.google.common.truth.Truth.assertThat;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.mock;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import io.reactivex.rxjava3.core.Flowable;
import io.reactivex.rxjava3.subscribers.TestSubscriber;
import java.util.Optional;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class BaseLlmGenerateContentTest {

  private static final String TEST_MODEL_NAME = "gemini-1.5-flash";

  private TestBaseLlm testBaseLlm;

  // Concrete implementation for testing purposes
  private static class TestBaseLlm extends BaseLlm {

    private Flowable<LlmResponse> mockResponse;

    private boolean throwOnNull = false;

    public TestBaseLlm(String model) {
      super(model);
    }

    public void setMockResponse(Flowable<LlmResponse> response) {
      this.mockResponse = response;
    }

    public void setThrowOnNull(boolean throwOnNull) {
      this.throwOnNull = throwOnNull;
    }

    @Override
    public Flowable<LlmResponse> generateContent(LlmRequest llmRequest, boolean stream) {
      if (throwOnNull && llmRequest == null) {
        throw new NullPointerException("LlmRequest cannot be null");
      }
      if (mockResponse != null) {
        return mockResponse;
      }
      if (stream) {
        LlmResponse response1 = mock(LlmResponse.class);
        LlmResponse response2 = mock(LlmResponse.class);
        return Flowable.just(response1, response2);
      } else {
        LlmResponse response = mock(LlmResponse.class);
        return Flowable.just(response);
      }
    }

    @Override
    public BaseLlmConnection connect(LlmRequest llmRequest) {
      return mock(BaseLlmConnection.class);
    }
  }

  @BeforeEach
  void setUp() {
    testBaseLlm = new TestBaseLlm(TEST_MODEL_NAME);
  }

  @Test
  @Tag("valid")
  void generateContentWithValidRequestStreamingMode() {
    // Arrange
    LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of()).build();
    // Act
    Flowable<LlmResponse> result = testBaseLlm.generateContent(llmRequest, true);
    // Assert
    assertNotNull(result);
    TestSubscriber<LlmResponse> testSubscriber = result.test();
    testSubscriber.awaitDone(5, TimeUnit.SECONDS);
    testSubscriber.assertNoErrors();
    testSubscriber.assertComplete();
    assertThat(testSubscriber.values().size()).isGreaterThan(0);
  }

  @Test
  @Tag("valid")
  void generateContentWithValidRequestNonStreamingMode() {
    // Arrange
    LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of()).build();
    // Act
    Flowable<LlmResponse> result = testBaseLlm.generateContent(llmRequest, false);
    // Assert
    assertNotNull(result);
    TestSubscriber<LlmResponse> testSubscriber = result.test();
    testSubscriber.awaitDone(5, TimeUnit.SECONDS);
    testSubscriber.assertNoErrors();
    testSubscriber.assertComplete();
    testSubscriber.assertValueCount(1);
  }

  @Test
  @Tag("invalid")
  void generateContentWithNullRequest() {
    // Arrange
    testBaseLlm.setThrowOnNull(true);
    // Act & Assert
    assertThrows(
        NullPointerException.class,
        () -> {
          testBaseLlm.generateContent(null, false);
        });
  }

  @Test
  @Tag("boundary")
  void generateContentWithEmptyContentRequest() {
    // Arrange
    LlmRequest llmRequest =
        LlmRequest.builder().contents(ImmutableList.of()).tools(ImmutableMap.of()).build();
    // Act
    Flowable<LlmResponse> result = testBaseLlm.generateContent(llmRequest, false);
    // Assert
    assertNotNull(result);
    TestSubscriber<LlmResponse> testSubscriber = result.test();
    testSubscriber.awaitDone(5, TimeUnit.SECONDS);
    testSubscriber.assertNoErrors();
  }

  @Test
  @Tag("valid")
  void generateContentPreservesModelName() {
    // Arrange
    String expectedModelName = "gemini-1.5-flash";
    TestBaseLlm llm = new TestBaseLlm(expectedModelName);
    LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of()).build();
    // Act
    String actualModelName = llm.model();
    Flowable<LlmResponse> result = llm.generateContent(llmRequest, false);
    // Assert
    assertThat(actualModelName).isEqualTo(expectedModelName);
    assertNotNull(result);
  }

  @Test
  @Tag("valid")
  void generateContentFlowableSupportsMultipleSubscriptions() {
    // Arrange
    LlmResponse mockResponse = mock(LlmResponse.class);
    testBaseLlm.setMockResponse(Flowable.just(mockResponse));
    LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of()).build();
    // Act
    Flowable<LlmResponse> result = testBaseLlm.generateContent(llmRequest, false);
    // Assert - First subscription
    TestSubscriber<LlmResponse> subscriber1 = result.test();
    subscriber1.awaitDone(5, TimeUnit.SECONDS);
    subscriber1.assertNoErrors();
    subscriber1.assertValueCount(1);
    // Assert - Second subscription
    TestSubscriber<LlmResponse> subscriber2 = result.test();
    subscriber2.awaitDone(5, TimeUnit.SECONDS);
    subscriber2.assertNoErrors();
    subscriber2.assertValueCount(1);
  }

  @Test
  @Tag("valid")
  void generateContentStreamToggleAffectsBehavior() {
    // Arrange
    LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of()).build();
    // Act
    Flowable<LlmResponse> streamingResult = testBaseLlm.generateContent(llmRequest, true);
    Flowable<LlmResponse> nonStreamingResult = testBaseLlm.generateContent(llmRequest, false);
    // Assert
    TestSubscriber<LlmResponse> streamingSubscriber = streamingResult.test();
    streamingSubscriber.awaitDone(5, TimeUnit.SECONDS);

    TestSubscriber<LlmResponse> nonStreamingSubscriber = nonStreamingResult.test();
    nonStreamingSubscriber.awaitDone(5, TimeUnit.SECONDS);
    // Streaming mode should emit multiple responses
    assertThat(streamingSubscriber.values().size()).isGreaterThan(1);
    // Non-streaming mode should emit single response
    assertThat(nonStreamingSubscriber.values().size()).isEqualTo(1);
  }

  @Test
  @Tag("boundary")
  void generateContentWithLargeContentRequest() {
    // Arrange
    StringBuilder largeContent = new StringBuilder();
    for (int i = 0; i < 10000; i++) {
      largeContent.append("This is a large content payload for testing. ");
    }

    LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of()).build();
    // Act
    Flowable<LlmResponse> result = testBaseLlm.generateContent(llmRequest, false);
    // Assert
    assertNotNull(result);
    TestSubscriber<LlmResponse> testSubscriber = result.test();
    testSubscriber.awaitDone(10, TimeUnit.SECONDS);
    testSubscriber.assertNoErrors();
  }

  @Test
  @Tag("boundary")
  void generateContentWithSpecialCharactersInRequest() {
    // Arrange
    String specialContent = "Special chars: émoji 🎉 中文 العربية \n\t\\\"'";
    LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of()).build();
    // Act
    Flowable<LlmResponse> result = testBaseLlm.generateContent(llmRequest, false);
    // Assert
    assertNotNull(result);
    TestSubscriber<LlmResponse> testSubscriber = result.test();
    testSubscriber.awaitDone(5, TimeUnit.SECONDS);
    testSubscriber.assertNoErrors();
    testSubscriber.assertComplete();
  }

  @Test
  @Tag("integration")
  void generateContentFlowableHandlesBackpressure() {
    // Arrange
    LlmResponse response1 = mock(LlmResponse.class);
    LlmResponse response2 = mock(LlmResponse.class);
    LlmResponse response3 = mock(LlmResponse.class);

    testBaseLlm.setMockResponse(
        Flowable.just(response1, response2, response3).onBackpressureBuffer());

    LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of()).build();
    // Act
    Flowable<LlmResponse> result = testBaseLlm.generateContent(llmRequest, true);
    // Assert with controlled backpressure
    TestSubscriber<LlmResponse> testSubscriber = new TestSubscriber<>(1);
    result.subscribe(testSubscriber);

    testSubscriber.request(1);
    testSubscriber.request(1);

    testSubscriber.awaitDone(5, TimeUnit.SECONDS);
    testSubscriber.assertNoErrors();
  }

  @Test
  @Tag("valid")
  void generateContentWithModelOptionalInRequest() {
    // Arrange
    LlmRequest llmRequest =
        LlmRequest.builder().model("custom-model").contents(ImmutableList.of()).build();
    // Act
    Flowable<LlmResponse> result = testBaseLlm.generateContent(llmRequest, false);
    // Assert
    assertNotNull(result);
    assertThat(llmRequest.model()).isEqualTo(Optional.of("custom-model"));
    TestSubscriber<LlmResponse> testSubscriber = result.test();
    testSubscriber.awaitDone(5, TimeUnit.SECONDS);
    testSubscriber.assertNoErrors();
  }

  @Test
  @Tag("valid")
  void modelMethodReturnsCorrectModelName() {
    // Arrange
    String expectedModel = "gemini-1.5-flash-001";
    TestBaseLlm llm = new TestBaseLlm(expectedModel);
    // Act
    String actualModel = llm.model();
    // Assert
    assertThat(actualModel).isEqualTo(expectedModel);
    assertNotNull(actualModel);
  }
}
