/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-maven-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=generateContent_816aec4086
ROOST_METHOD_SIG_HASH=generateContent_816aec4086

Scenario 1: Generate Content with Valid Request and Streaming Enabled

Details:
  TestName: generateContentWithValidRequestAndStreamingEnabled
  Description: This test verifies that the generateContent method correctly processes a valid LlmRequest with streaming enabled (stream = true). It ensures that the method returns a Flowable that emits one or more LlmResponse objects when streaming is requested.
Execution:
  Arrange: Create a concrete implementation of BaseLlm with a valid model name (e.g., "gemini-1.5-flash"). Create a valid LlmRequest object with appropriate input parameters. Set the stream parameter to true.
  Act: Invoke the generateContent method with the prepared LlmRequest and stream=true.
  Assert: Verify that the returned Flowable is not null. Verify that the Flowable emits at least one LlmResponse object. Verify that all emitted LlmResponse objects are not null.
Validation:
  The assertion verifies that when streaming is enabled, the method returns a valid Flowable that can emit multiple LlmResponse chunks. This is critical for applications that need real-time streaming responses from the LLM, such as chatbots or interactive AI assistants. The test ensures the streaming functionality works as expected and provides progressive responses to the client.

Scenario 2: Generate Content with Valid Request and Streaming Disabled

Details:
  TestName: generateContentWithValidRequestAndStreamingDisabled
  Description: This test validates that the generateContent method correctly handles a valid LlmRequest when streaming is disabled (stream = false). It ensures that exactly one complete LlmResponse is returned in the Flowable.
Execution:
  Arrange: Create a concrete implementation of BaseLlm with a valid model name (e.g., "gemini-1.5-flash-001"). Create a valid LlmRequest object. Set the stream parameter to false.
  Act: Invoke the generateContent method with the prepared LlmRequest and stream=false.
  Assert: Verify that the returned Flowable is not null. Verify that the Flowable emits exactly one LlmResponse object. Verify that the emitted LlmResponse is complete and not null.
Validation:
  This assertion confirms that when streaming is disabled, the method returns a single, complete LlmResponse rather than multiple chunks. This is important for use cases where the application needs the entire response at once, such as batch processing or when displaying complete answers. The test ensures the non-streaming mode provides a complete response in a single emission.

Scenario 3: Generate Content with Null LlmRequest

Details:
  TestName: generateContentWithNullLlmRequest
  Description: This test checks the method's behavior when a null LlmRequest is passed as a parameter. It verifies proper error handling for invalid input.
Execution:
  Arrange: Create a concrete implementation of BaseLlm with a valid model name. Set the llmRequest parameter to null. Set stream to either true or false.
  Act: Invoke the generateContent method with null as the llmRequest parameter.
  Assert: Verify that the method either throws a NullPointerException or IllegalArgumentException, or returns a Flowable that emits an error signal.
Validation:
  This test ensures that the method properly handles null input, which is a common edge case. Proper null handling prevents unexpected application crashes and provides clear error messages to developers. The test validates that the method follows defensive programming practices and fails gracefully when given invalid input.

Scenario 4: Generate Content with Empty LlmRequest

Details:
  TestName: generateContentWithEmptyLlmRequest
  Description: This test verifies the method's behavior when an empty or minimally populated LlmRequest is provided, containing no meaningful content or parameters.
Execution:
  Arrange: Create a concrete implementation of BaseLlm. Create an LlmRequest object with empty or default values (no prompt, no parameters). Set stream to true or false.
  Act: Invoke the generateContent method with the empty LlmRequest.
  Assert: Verify that the method either returns a Flowable that emits an error, or returns an empty/default LlmResponse, or throws an appropriate exception.
Validation:
  This assertion validates that the method can handle edge cases where the request lacks meaningful content. This is important for robustness, as it ensures the system doesn't attempt to process invalid or incomplete requests. The test helps identify whether the implementation requires validation of request content before processing.

Scenario 5: Generate Content with Streaming True Returns Multiple Responses

Details:
  TestName: generateContentWithStreamingTrueReturnsMultipleResponses
  Description: This test specifically validates that when streaming is enabled, the Flowable can emit multiple LlmResponse objects that should be merged to form complete content.
Execution:
  Arrange: Create a concrete implementation of BaseLlm that simulates streaming behavior. Create a valid LlmRequest. Set stream to true.
  Act: Invoke the generateContent method with stream=true and collect all emitted LlmResponse objects.
  Assert: Verify that the Flowable emits more than one LlmResponse object. Verify that each response contains partial content that can be merged. Verify that the sequence completes successfully.
Validation:
  This test confirms the streaming behavior works correctly by emitting multiple response chunks. This is essential for real-time applications where users expect to see progressive output as the LLM generates content. The test ensures that the streaming implementation properly chunks the response and that all parts can be combined to form the complete answer.

Scenario 6: Generate Content with Streaming False Returns Single Response

Details:
  TestName: generateContentWithStreamingFalseReturnsSingleResponse
  Description: This test ensures that when streaming is disabled, the Flowable emits exactly one LlmResponse containing the complete content, not multiple chunks.
Execution:
  Arrange: Create a concrete implementation of BaseLlm. Create a valid LlmRequest. Set stream to false.
  Act: Invoke the generateContent method with stream=false and collect all emitted items.
  Assert: Verify that the Flowable emits exactly one LlmResponse. Verify that this single response contains complete content. Verify that no additional emissions occur after the first response.
Validation:
  This assertion validates that non-streaming mode provides the entire response in a single emission, which is the expected behavior for synchronous-style operations. This is important for applications that need to process the complete response at once, such as generating reports or performing analysis on the full output.

Scenario 7: Generate Content Flowable Completes Successfully

Details:
  TestName: generateContentFlowableCompletesSuccessfully
  Description: This test verifies that the returned Flowable completes successfully after emitting all LlmResponse objects, regardless of streaming mode.
Execution:
  Arrange: Create a concrete implementation of BaseLlm. Create a valid LlmRequest. Set stream to either true or false.
  Act: Invoke the generateContent method and subscribe to the returned Flowable.
  Assert: Verify that the Flowable completes without errors. Verify that the onComplete signal is received. Verify that no onError signal is emitted.
Validation:
  This test ensures that the Flowable lifecycle is properly managed and completes successfully after delivering all responses. Proper completion is crucial for resource management and allows subscribers to know when the content generation is finished. This is particularly important in reactive programming to prevent resource leaks and ensure proper cleanup.

Scenario 8: Generate Content Flowable Handles Errors Gracefully

Details:
  TestName: generateContentFlowableHandlesErrorsGracefully
  Description: This test validates that when an error occurs during content generation, the Flowable properly emits an error signal to subscribers.
Execution:
  Arrange: Create a concrete implementation of BaseLlm that simulates an error condition (e.g., network failure, API error). Create a valid LlmRequest. Set stream to either true or false.
  Act: Invoke the generateContent method and subscribe to the returned Flowable with an error handler.
  Assert: Verify that the Flowable emits an error signal. Verify that the error is of the expected type. Verify that no further emissions occur after the error.
Validation:
  This assertion confirms that the method properly propagates errors through the Flowable, allowing subscribers to handle failures appropriately. Error handling is critical for building resilient applications that can recover from failures or provide meaningful feedback to users when content generation fails.

Scenario 9: Generate Content with Different Model Names

Details:
  TestName: generateContentWithDifferentModelNames
  Description: This test verifies that the generateContent method works correctly with different model names specified in the BaseLlm instance (e.g., "gemini-1.5-flash", "gemini-1.5-flash-001").
Execution:
  Arrange: Create multiple concrete implementations of BaseLlm, each with a different model name. Create a valid LlmRequest. Set stream to true or false.
  Act: Invoke the generateContent method on each BaseLlm instance with different models.
  Assert: Verify that each invocation returns a valid Flowable. Verify that responses are generated according to the specified model. Verify that the model field is correctly used in the generation process.
Validation:
  This test ensures that the method respects the model configuration and can work with different LLM model variants. This is important for applications that need to support multiple models or allow users to choose between different model versions based on their requirements for speed, accuracy, or cost.

Scenario 10: Generate Content Maintains Backpressure in Streaming Mode

Details:
  TestName: generateContentMaintainsBackpressureInStreamingMode
  Description: This test validates that the Flowable returned by generateContent properly handles backpressure when streaming is enabled, ensuring that the producer doesn't overwhelm the consumer.
Execution:
  Arrange: Create a concrete implementation of BaseLlm. Create a valid LlmRequest. Set stream to true. Create a slow subscriber that processes items with delay.
  Act: Invoke the generateContent method with stream=true and subscribe with a backpressure strategy.
  Assert: Verify that the Flowable respects backpressure signals. Verify that no items are dropped or lost. Verify that the producer slows down when the consumer cannot keep up.
Validation:
  This assertion confirms that the streaming implementation properly handles backpressure, which is a key feature of reactive streams. Proper backpressure handling prevents memory issues and ensures that fast producers don't overwhelm slow consumers, which is critical for stable and efficient streaming applications.

Scenario 11: Generate Content with Concurrent Requests

Details:
  TestName: generateContentWithConcurrentRequests
  Description: This test verifies that the generateContent method can handle multiple concurrent requests without interference or data corruption.
Execution:
  Arrange: Create a concrete implementation of BaseLlm. Create multiple different LlmRequest objects. Set stream to true or false for each request.
  Act: Invoke the generateContent method concurrently with multiple requests from different threads.
  Assert: Verify that each Flowable returns responses corresponding to its specific request. Verify that there is no cross-contamination between concurrent requests. Verify that all requests complete successfully.
Validation:
  This test ensures thread-safety and proper isolation between concurrent requests, which is essential for multi-user applications or systems that process multiple requests in parallel. The test validates that the implementation can scale and handle concurrent load without compromising data integrity.

Scenario 12: Generate Content Flowable Can Be Subscribed Multiple Times

Details:
  TestName: generateContentFlowableCanBeSubscribedMultipleTimes
  Description: This test checks whether the Flowable returned by generateContent can be subscribed to multiple times and whether each subscription receives the same or different responses.
Execution:
  Arrange: Create a concrete implementation of BaseLlm. Create a valid LlmRequest. Set stream to either true or false. Get the Flowable from generateContent.
  Act: Subscribe to the same Flowable instance multiple times.
  Assert: Verify the behavior based on the implementation (cold vs hot observable). If cold, verify that each subscription triggers a new content generation. If hot, verify that subscriptions share the same stream.
Validation:
  This assertion validates the subscription semantics of the returned Flowable, which affects how the method can be used in reactive pipelines. Understanding whether the Flowable is cold or hot is important for proper resource management and avoiding unintended multiple executions of expensive operations.

Scenario 13: Generate Content with Large LlmRequest

Details:
  TestName: generateContentWithLargeLlmRequest
  Description: This test verifies that the method can handle large LlmRequest objects with extensive prompts or parameters without performance degradation or errors.
Execution:
  Arrange: Create a concrete implementation of BaseLlm. Create an LlmRequest with a very large prompt (e.g., thousands of tokens) and extensive parameters. Set stream to true or false.
  Act: Invoke the generateContent method with the large LlmRequest.
  Assert: Verify that the method processes the request successfully. Verify that the Flowable emits valid responses. Verify that there are no memory or performance issues.
Validation:
  This test ensures that the method can handle edge cases involving large inputs, which is important for applications that need to process extensive context or complex prompts. The test validates that the implementation is robust enough to handle real-world scenarios where requests may be significantly larger than average.

Scenario 14: Generate Content Streaming Mode Emits Responses in Order

Details:
  TestName: generateContentStreamingModeEmitsResponsesInOrder
  Description: This test validates that when streaming is enabled, the Flowable emits LlmResponse objects in the correct sequential order.
Execution:
  Arrange: Create a concrete implementation of BaseLlm that generates multiple response chunks. Create a valid LlmRequest. Set stream to true.
  Act: Invoke the generateContent method with stream=true and collect all emitted responses with their emission order.
  Assert: Verify that responses are emitted in the correct sequential order. Verify that the order matches the expected generation sequence. Verify that no responses are emitted out of order.
Validation:
  This assertion confirms that streaming maintains proper ordering of response chunks, which is critical for correctly reconstructing the complete content. Out-of-order responses would result in garbled or incorrect output, making this test essential for ensuring the quality and correctness of streaming responses.

Scenario 15: Generate Content Returns Flowable Immediately

Details:
  TestName: generateContentReturnsFlowableImmediately
  Description: This test verifies that the generateContent method returns a Flowable immediately without blocking, regardless of whether the actual content generation is complete.
Execution:
  Arrange: Create a concrete implementation of BaseLlm. Create a valid LlmRequest. Set stream to either true or false.
  Act: Measure the time taken to invoke generateContent and receive the Flowable reference (not waiting for emissions).
  Assert: Verify that the method returns the Flowable reference immediately (within a very short time threshold). Verify that the method does not block waiting for content generation to complete.
Validation:
  This test ensures that the method follows reactive programming principles by returning immediately and allowing asynchronous processing. Immediate return is crucial for non-blocking applications and ensures that the calling thread is not held up waiting for potentially long-running LLM operations.

*/

// ********RoostGPT********

package com.google.adk.models;

import static com.google.common.truth.Truth.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.*;

import io.reactivex.rxjava3.core.Flowable;
import io.reactivex.rxjava3.subscribers.TestSubscriber;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class BaseLlmGenerateContentTest {

  private TestBaseLlm baseLlm;

  private TestBaseLlm baseLlmWithDifferentModel;

  @Mock private LlmRequest mockLlmRequest;

  @BeforeEach
  public void setUp() {
    MockitoAnnotations.openMocks(this);
    baseLlm = new TestBaseLlm("gemini-1.5-flash");
    baseLlmWithDifferentModel = new TestBaseLlm("gemini-1.5-flash-001");
  }

  @Test
  @Tag("valid")
  public void generateContentWithValidRequestAndStreamingEnabled() {
    LlmRequest request = LlmRequest.builder().build();
    baseLlm.setStreamingResponses(3);
    Flowable<LlmResponse> flowable = baseLlm.generateContent(request, true);
    assertThat(flowable).isNotNull();
    TestSubscriber<LlmResponse> testSubscriber = flowable.test();
    testSubscriber.awaitDone(5, TimeUnit.SECONDS);
    testSubscriber.assertNoErrors();
    testSubscriber.assertComplete();
    assertThat(testSubscriber.values()).isNotEmpty();
    assertThat(testSubscriber.values().size()).isAtLeast(1);
    for (LlmResponse response : testSubscriber.values()) {
      assertThat(response).isNotNull();
    }
  }

  @Test
  @Tag("valid")
  public void generateContentWithValidRequestAndStreamingDisabled() {
    LlmRequest request = LlmRequest.builder().build();
    baseLlm.setStreamingResponses(1);
    Flowable<LlmResponse> flowable = baseLlm.generateContent(request, false);
    assertThat(flowable).isNotNull();
    TestSubscriber<LlmResponse> testSubscriber = flowable.test();
    testSubscriber.awaitDone(5, TimeUnit.SECONDS);
    testSubscriber.assertNoErrors();
    testSubscriber.assertComplete();
    testSubscriber.assertValueCount(1);
    assertThat(testSubscriber.values().get(0)).isNotNull();
  }

  @Test
  @Tag("invalid")
  public void generateContentWithNullLlmRequest() {
    baseLlm.setShouldThrowOnNull(true);
    assertThrows(
        NullPointerException.class,
        () -> {
          baseLlm.generateContent(null, true);
        });
  }

  @Test
  @Tag("boundary")
  public void generateContentWithEmptyLlmRequest() {
    LlmRequest emptyRequest = LlmRequest.builder().build();
    baseLlm.setStreamingResponses(1);
    Flowable<LlmResponse> flowable = baseLlm.generateContent(emptyRequest, false);
    assertThat(flowable).isNotNull();
    TestSubscriber<LlmResponse> testSubscriber = flowable.test();
    testSubscriber.awaitDone(5, TimeUnit.SECONDS);
    testSubscriber.assertNoErrors();
    testSubscriber.assertComplete();
  }

  @Test
  @Tag("valid")
  public void generateContentWithStreamingTrueReturnsMultipleResponses() {
    LlmRequest request = LlmRequest.builder().build();
    baseLlm.setStreamingResponses(5);
    Flowable<LlmResponse> flowable = baseLlm.generateContent(request, true);
    TestSubscriber<LlmResponse> testSubscriber = flowable.test();
    testSubscriber.awaitDone(5, TimeUnit.SECONDS);
    testSubscriber.assertNoErrors();
    testSubscriber.assertComplete();
    assertThat(testSubscriber.values().size()).isGreaterThan(1);
    for (LlmResponse response : testSubscriber.values()) {
      assertThat(response).isNotNull();
    }
  }

  @Test
  @Tag("valid")
  public void generateContentWithStreamingFalseReturnsSingleResponse() {
    LlmRequest request = LlmRequest.builder().build();
    baseLlm.setStreamingResponses(1);
    Flowable<LlmResponse> flowable = baseLlm.generateContent(request, false);
    TestSubscriber<LlmResponse> testSubscriber = flowable.test();
    testSubscriber.awaitDone(5, TimeUnit.SECONDS);
    testSubscriber.assertNoErrors();
    testSubscriber.assertComplete();
    testSubscriber.assertValueCount(1);
    assertThat(testSubscriber.values().get(0)).isNotNull();
  }

  @Test
  @Tag("valid")
  public void generateContentFlowableCompletesSuccessfully() {
    LlmRequest request = LlmRequest.builder().build();
    baseLlm.setStreamingResponses(2);
    Flowable<LlmResponse> flowable = baseLlm.generateContent(request, true);
    TestSubscriber<LlmResponse> testSubscriber = flowable.test();
    testSubscriber.awaitDone(5, TimeUnit.SECONDS);
    testSubscriber.assertComplete();
    testSubscriber.assertNoErrors();
  }

  @Test
  @Tag("invalid")
  public void generateContentFlowableHandlesErrorsGracefully() {
    LlmRequest request = LlmRequest.builder().build();
    baseLlm.setShouldError(true);
    Flowable<LlmResponse> flowable = baseLlm.generateContent(request, true);
    TestSubscriber<LlmResponse> testSubscriber = flowable.test();
    testSubscriber.awaitDone(5, TimeUnit.SECONDS);
    testSubscriber.assertError(RuntimeException.class);
    testSubscriber.assertNotComplete();
  }

  @Test
  @Tag("valid")
  public void generateContentWithDifferentModelNames() {
    LlmRequest request = LlmRequest.builder().build();
    baseLlm.setStreamingResponses(1);
    baseLlmWithDifferentModel.setStreamingResponses(1);
    Flowable<LlmResponse> flowable1 = baseLlm.generateContent(request, false);
    Flowable<LlmResponse> flowable2 = baseLlmWithDifferentModel.generateContent(request, false);
    assertThat(flowable1).isNotNull();
    assertThat(flowable2).isNotNull();

    TestSubscriber<LlmResponse> testSubscriber1 = flowable1.test();
    TestSubscriber<LlmResponse> testSubscriber2 = flowable2.test();

    testSubscriber1.awaitDone(5, TimeUnit.SECONDS);
    testSubscriber2.awaitDone(5, TimeUnit.SECONDS);

    testSubscriber1.assertNoErrors();
    testSubscriber2.assertNoErrors();
    testSubscriber1.assertComplete();
    testSubscriber2.assertComplete();

    assertThat(baseLlm.model()).isEqualTo("gemini-1.5-flash");
    assertThat(baseLlmWithDifferentModel.model()).isEqualTo("gemini-1.5-flash-001");
  }

  @Test
  @Tag("valid")
  @Timeout(10)
  public void generateContentMaintainsBackpressureInStreamingMode() {
    LlmRequest request = LlmRequest.builder().build();
    baseLlm.setStreamingResponses(100);
    Flowable<LlmResponse> flowable = baseLlm.generateContent(request, true);
    TestSubscriber<LlmResponse> testSubscriber = flowable.onBackpressureBuffer().test(10);
    testSubscriber.awaitCount(10);
    assertThat(testSubscriber.values().size()).isAtLeast(10);
    testSubscriber.cancel();
  }

  @Test
  @Tag("integration")
  public void generateContentWithConcurrentRequests() throws InterruptedException {
    LlmRequest request1 = LlmRequest.builder().build();
    LlmRequest request2 = LlmRequest.builder().build();
    LlmRequest request3 = LlmRequest.builder().build();

    baseLlm.setStreamingResponses(2);

    CountDownLatch latch = new CountDownLatch(3);
    List<TestSubscriber<LlmResponse>> subscribers = new ArrayList<>();
    Thread thread1 =
        new Thread(
            () -> {
              TestSubscriber<LlmResponse> sub = baseLlm.generateContent(request1, true).test();
              subscribers.add(sub);
              latch.countDown();
            });
    Thread thread2 =
        new Thread(
            () -> {
              TestSubscriber<LlmResponse> sub = baseLlm.generateContent(request2, false).test();
              subscribers.add(sub);
              latch.countDown();
            });
    Thread thread3 =
        new Thread(
            () -> {
              TestSubscriber<LlmResponse> sub = baseLlm.generateContent(request3, true).test();
              subscribers.add(sub);
              latch.countDown();
            });
    thread1.start();
    thread2.start();
    thread3.start();
    latch.await(10, TimeUnit.SECONDS);
    for (TestSubscriber<LlmResponse> subscriber : subscribers) {
      subscriber.awaitDone(5, TimeUnit.SECONDS);
      subscriber.assertNoErrors();
      subscriber.assertComplete();
      assertThat(subscriber.values()).isNotEmpty();
    }
  }

  @Test
  @Tag("valid")
  public void generateContentFlowableCanBeSubscribedMultipleTimes() {
    LlmRequest request = LlmRequest.builder().build();
    baseLlm.setStreamingResponses(2);
    Flowable<LlmResponse> flowable = baseLlm.generateContent(request, true);
    TestSubscriber<LlmResponse> testSubscriber1 = flowable.test();
    TestSubscriber<LlmResponse> testSubscriber2 = flowable.test();
    testSubscriber1.awaitDone(5, TimeUnit.SECONDS);
    testSubscriber2.awaitDone(5, TimeUnit.SECONDS);
    testSubscriber1.assertNoErrors();
    testSubscriber2.assertNoErrors();
    testSubscriber1.assertComplete();
    testSubscriber2.assertComplete();

    assertThat(testSubscriber1.values()).isNotEmpty();
    assertThat(testSubscriber2.values()).isNotEmpty();
  }

  @Test
  @Tag("boundary")
  public void generateContentWithLargeLlmRequest() {
    LlmRequest largeRequest = LlmRequest.builder().build();
    baseLlm.setStreamingResponses(1);
    Flowable<LlmResponse> flowable = baseLlm.generateContent(largeRequest, false);
    assertThat(flowable).isNotNull();
    TestSubscriber<LlmResponse> testSubscriber = flowable.test();
    testSubscriber.awaitDone(10, TimeUnit.SECONDS);
    testSubscriber.assertNoErrors();
    testSubscriber.assertComplete();
    assertThat(testSubscriber.values()).isNotEmpty();
  }

  @Test
  @Tag("valid")
  public void generateContentStreamingModeEmitsResponsesInOrder() {
    LlmRequest request = LlmRequest.builder().build();
    baseLlm.setStreamingResponses(5);
    baseLlm.setOrderedResponses(true);
    Flowable<LlmResponse> flowable = baseLlm.generateContent(request, true);
    TestSubscriber<LlmResponse> testSubscriber = flowable.test();
    testSubscriber.awaitDone(5, TimeUnit.SECONDS);
    testSubscriber.assertNoErrors();
    testSubscriber.assertComplete();
    List<LlmResponse> responses = testSubscriber.values();
    assertThat(responses.size()).isGreaterThan(1);

    for (int i = 0; i < responses.size(); i++) {
      assertThat(responses.get(i)).isNotNull();
    }
  }

  @Test
  @Tag("valid")
  @Timeout(2)
  public void generateContentReturnsFlowableImmediately() {
    LlmRequest request = LlmRequest.builder().build();
    baseLlm.setStreamingResponses(10);
    long startTime = System.currentTimeMillis();
    Flowable<LlmResponse> flowable = baseLlm.generateContent(request, true);
    long endTime = System.currentTimeMillis();
    assertThat(flowable).isNotNull();
    assertThat(endTime - startTime).isLessThan(1000L);
  }

  private static class TestBaseLlm extends BaseLlm {

    private int streamingResponses = 1;

    private boolean shouldError = false;

    private boolean shouldThrowOnNull = false;

    private boolean orderedResponses = false;

    public TestBaseLlm(String model) {
      super(model);
    }

    public void setStreamingResponses(int count) {
      this.streamingResponses = count;
    }

    public void setShouldError(boolean shouldError) {
      this.shouldError = shouldError;
    }

    public void setShouldThrowOnNull(boolean shouldThrowOnNull) {
      this.shouldThrowOnNull = shouldThrowOnNull;
    }

    public void setOrderedResponses(boolean orderedResponses) {
      this.orderedResponses = orderedResponses;
    }

    @Override
    public Flowable<LlmResponse> generateContent(LlmRequest llmRequest, boolean stream) {
      if (llmRequest == null && shouldThrowOnNull) {
        throw new NullPointerException("LlmRequest cannot be null");
      }
      if (shouldError) {
        return Flowable.error(new RuntimeException("Simulated error"));
      }
      if (stream) {
        return Flowable.range(0, streamingResponses).map(i -> createMockResponse(i));
      } else {
        return Flowable.just(createMockResponse(0));
      }
    }

    @Override
    public BaseLlmConnection connect(LlmRequest llmRequest) {
      return null;
    }

    private LlmResponse createMockResponse(int index) {
      return mock(LlmResponse.class);
    }
  }
}
