/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-jan-9 using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=build_a5a48bce54
ROOST_METHOD_SIG_HASH=build_6248639c03

Scenario 1: Build with only modelName set (the minimal required case)

Details:
  TestName: buildWithModelNameOnly
  Description: This scenario verifies that the build method constructs a Gemini instance correctly when only the modelName field is set. The method should use the default client setup as per the else clause.
Execution:
  Arrange: Create a Builder instance and set a valid modelName. Do not set apiClient, apiKey, or vertexCredentials.
  Act: Call build() on the Builder.
  Assert: The returned Gemini object should be constructed with the default client (created with TRACKING_HEADERS) and the provided modelName.
Validation:
  The assertion verifies that build() adequately falls back to the default client setup when no authentication or explicit client information is supplied. This ensures that the Gemini object can be constructed with the minimal configuration required for basic use cases.

Scenario 2: Build with apiClient explicitly set

Details:
  TestName: buildWithExplicitApiClient
  Description: This scenario confirms that when an explicit apiClient is set in the Builder, the build() method creates the Gemini instance using this apiClient, regardless of whether apiKey or vertexCredentials are also provided.
Execution:
  Arrange: Create a Builder, set modelName, and provide a non-null Client instance via apiClient(). Optionally set apiKey and/or vertexCredentials.
  Act: Call build() on the Builder.
  Assert: The returned Gemini instance should be constructed with the explicit Client and modelName. The other authentication values should be ignored.
Validation:
  This assures that the Builder prioritizes explicit client configuration—critical for advanced use cases or when clients are pre-configured for testing, multi-tenancy, or specific networking requirements.

Scenario 3: Build with only apiKey provided

Details:
  TestName: buildWithApiKeyOnly
  Description: Tests that when only apiKey is set (and modelName is set), build() constructs a Gemini using the apiKey—generating its own Client and applying TRACKING_HEADERS.
Execution:
  Arrange: Instantiate a Builder, set the modelName and apiKey. Do not set apiClient or vertexCredentials.
  Act: Call build().
  Assert: Gemini instance should use apiKey for authentication, and internally create a Client with the specified headers.
Validation:
  This checks the correct authentication path is selected and the object can be used with API key authentication as intended for typical API customers.

Scenario 4: Build with only vertexCredentials provided

Details:
  TestName: buildWithVertexCredentialsOnly
  Description: Verifies that the build() method constructs Gemini with vertexCredentials when this is the only authentication provided (along with required modelName).
Execution:
  Arrange: Create a Builder and set modelName and vertexCredentials. Do not set apiClient or apiKey.
  Act: Call build().
  Assert: Gemini instance should be created with a Client built using the VertexCredentials for authentication.
Validation:
  Ensures correct usage for Google Cloud customers who use Vertex AI authentication, validating the prioritization in the builder logic.

Scenario 5: Build prioritizes apiClient over apiKey and vertexCredentials

Details:
  TestName: buildWithApiClientAndOthers
  Description: Checks that when apiClient, apiKey, and vertexCredentials are all set on the Builder, the returned Gemini instance uses apiClient, confirming documented precedence rules.
Execution:
  Arrange: Instantiate a Builder and set modelName, apiClient, apiKey, and vertexCredentials.
  Act: Call build().
  Assert: Gemini instance should be constructed with the explicit apiClient only.
Validation:
  Confirms the Builder precedence: apiClient (if non-null) is always used first, ensuring users’ explicit configurations are respected and side effects from unintended credentials mixing are avoided.

Scenario 6: Build prioritizes apiKey over vertexCredentials

Details:
  TestName: buildWithApiKeyAndVertexCredentials
  Description: Ensures that when apiKey and vertexCredentials are both set (but apiClient is not set), build() constructs Gemini with apiKey.
Execution:
  Arrange: Configure a Builder with modelName, apiKey, and vertexCredentials; leave apiClient unset.
  Act: Call build().
  Assert: Gemini instance should use the apiKey, verify the Client internal to Gemini is set up for API key authentication.
Validation:
  Tests the documented logic that apiKey takes priority over vertexCredentials, helping to avoid security/configuration misunderstandings when both are present.

Scenario 7: Build throws NullPointerException if modelName is not set

Details:
  TestName: buildThrowsIfModelNameNotSet
  Description: Verifies that the build() method enforces a non-null modelName. If modelName is never set, build() should throw a NullPointerException.
Execution:
  Arrange: Instantiate a Builder without setting modelName. Optionally set apiClient/apiKey/vertexCredentials.
  Act: Call build().
  Assert: A NullPointerException is thrown with the expected message.
Validation:
  Ensures that modelName is a required field for Gemini instantiation, protecting against invalid object creation and early error signaling for developers.

Scenario 8: Build with all authentication fields unset (only modelName set)

Details:
  TestName: buildWithNoAuthFields
  Description: Verifies the fallback behavior when only modelName is provided, with no credentials or Client. Ensures the Builder generates a Client using the default settings (TRACKING_HEADERS).
Execution:
  Arrange: Builder is created and modelName is set. apiClient, apiKey, and vertexCredentials are all left unset.
  Act: Call build().
  Assert: Gemini object uses internally created Client with default TRACKING_HEADERS.
Validation:
  Checks robustness of the Builder, ensuring it can handle minimal input and produce a functional Gemini instance for non-authenticated or local scenarios.

Scenario 9: Build with explicitly null values for credentials

Details:
  TestName: buildWithExplicitNullsForCredentials
  Description: Confirms that if apiClient, apiKey, or vertexCredentials are explicitly set to null before build is called, the method treats them as absent, leading to default Client instantiation.
Execution:
  Arrange: Builder has modelName set. Explicitly set apiClient(null), apiKey(null), and vertexCredentials(null).
  Act: Call build().
  Assert: Returned Gemini instance should be built as if those fields were never set, matching default-client fallback behavior.
Validation:
  Validates that the Builder is resilient to explicit null settings, preventing subtle bugs where fields may be reset or cleared intentionally.

Scenario 10: Multiple calls to Builder setters and build

Details:
  TestName: buildWithSetterReassignment
  Description: Assesses that setting fields multiple times follows expected precedence on build(), and Builder maintains last-assigned value.
Execution:
  Arrange: Builder created; set modelName, apiKey, vertexCredentials, then reassign apiKey, reassign apiClient (overriding previous auth values).
  Act: Call build().
  Assert: Gemini should be built using the value last assigned (i.e., apiClient if it was assigned last).
Validation:
  Ensures the Builder is robust to configuration changes and allows users to reconfigure authentication strategies pre-build, matching expected fluent-builder semantics.

Scenario 11: Build with empty string as apiKey

Details:
  TestName: buildWithEmptyApiKey
  Description: Verifies the outcome when the apiKey is set to an empty string (""), which is not null but likely invalid. Checks whether an exception is raised or if it tries to build a Gemini object.
Execution:
  Arrange: Builder instantiated, set modelName and apiKey("").
  Act: Call build().
  Assert: Should validate if Gemini can be constructed with an empty apiKey, or if downstream logic protests (e.g., via Objects.requireNonNull, etc).
Validation:
  Ensures edge cases with default/empty values are properly handled, especially important in API contexts where empty strings may represent misconfiguration.

Scenario 12: Build with minimal required modelName (edge case values)

Details:
  TestName: buildWithMinimalModelNameContent
  Description: Confirms the Builder can handle minimal or "empty" valid values for modelName (such as a one-character string).
Execution:
  Arrange: Builder instance, set modelName("a"), leave all other fields unset.
  Act: Call build().
  Assert: Gemini should be created with "a" as modelName, using the default client.
Validation:
  Confirms that the Builder does not enforce semantic correctness of modelName (other than non-null), and supports edge-case naming.

*/

// ********RoostGPT********

package com.google.adk.models;

import static com.google.common.base.StandardSystemProperty.JAVA_VERSION;
import com.google.genai.Client;
import com.google.genai.types.HttpOptions;
import com.google.genai.types.LiveConnectConfig;
import com.google.auth.GoogleCredentials;
import com.google.common.collect.ImmutableMap;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.genai.ResponseStream;
import com.google.genai.types.Candidate;
import com.google.genai.types.Content;
import com.google.genai.types.FinishReason;
import com.google.genai.types.GenerateContentConfig;
import com.google.genai.types.GenerateContentResponse;
import com.google.genai.types.Part;
import com.google.genai.types.GenerateContentResponseUsageMetadata;
import io.reactivex.rxjava3.core.Flowable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Assertions;
import org.mockito.Mockito;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.junit.jupiter.api.*;
import com.google.adk.Version;

public class BuilderBuildTest {

	private static final Map<String, String> TRACKING_HEADERS = ImmutableMap.of("tracking-header1", "value1");

	/**
	 * Utility method to access Builder. Assumes Gemini and Builder are visible for tests.
	 */
	private Gemini.Builder createBuilder() {
		return Gemini.builder();
	}

	/**
	 * Scenario 1: Build with only modelName set (the minimal required case)
	 */
	@Test
	@Tag("valid")
	public void testBuildWithModelNameOnly() {
		Gemini.Builder builder = createBuilder();
		String testModelName = "test-model";
		builder.modelName(testModelName);
		Gemini gemini = builder.build();
		Assertions.assertNotNull((Object) gemini);
		// Can't access gemini.modelName directly; validate constructed behavior
		Assertions.assertTrue((boolean) (Objects.equals(testModelName, getPrivateField(gemini, "modelName"))));
		Assertions.assertNotNull((Object) getPrivateField(gemini, "apiClient"));
		Assertions.assertNull(getPrivateField(gemini, "apiKey"));
		Assertions.assertNull(getPrivateField(gemini, "vertexCredentials"));
	}

	/**
	 * Scenario 2: Build with apiClient explicitly set
	 */
	@Test
	@Tag("valid")
	public void testBuildWithExplicitApiClient() {
		Gemini.Builder builder = createBuilder();
		String testModelName = "test-model-client";
		Client mockClient = Mockito.mock(Client.class);
		builder.modelName(testModelName);
		builder.apiClient(mockClient);
		builder.apiKey("shouldBeIgnored");
		VertexCredentials mockVc = Mockito.mock(VertexCredentials.class);
		builder.vertexCredentials(mockVc);
		Gemini gemini = builder.build();
		Assertions.assertNotNull((Object) gemini);
		Assertions.assertTrue((boolean) (Objects.equals(testModelName, getPrivateField(gemini, "modelName"))));
		Assertions.assertEquals(mockClient, (Object) getPrivateField(gemini, "apiClient"));
		Assertions.assertNull(getPrivateField(gemini, "apiKey"));
		Assertions.assertNull(getPrivateField(gemini, "vertexCredentials"));
	}

	/**
	 * Scenario 3: Build with only apiKey provided
	 */
	@Test
	@Tag("valid")
	public void testBuildWithApiKeyOnly() {
		Gemini.Builder builder = createBuilder();
		String testModelName = "test-model-apikey";
		String testApiKey = "sample-key";
		builder.modelName(testModelName);
		builder.apiKey(testApiKey);
		Gemini gemini = builder.build();
		Assertions.assertNotNull((Object) gemini);
		Assertions.assertTrue((boolean) (Objects.equals(testModelName, getPrivateField(gemini, "modelName"))));
		Assertions.assertEquals(testApiKey, (String) getPrivateField(gemini, "apiKey"));
		Assertions.assertNull(getPrivateField(gemini, "apiClient"));
		Assertions.assertNull(getPrivateField(gemini, "vertexCredentials"));
	}

	/**
	 * Scenario 4: Build with only vertexCredentials provided
	 */
	@Test
	@Tag("valid")
	public void testBuildWithVertexCredentialsOnly() {
		Gemini.Builder builder = createBuilder();
		String testModelName = "test-model-vertex";
		VertexCredentials vertexCredentials = Mockito.mock(VertexCredentials.class);
		builder.modelName(testModelName);
		builder.vertexCredentials(vertexCredentials);
		Gemini gemini = builder.build();
		Assertions.assertNotNull((Object) gemini);
		Assertions.assertTrue((boolean) (Objects.equals(testModelName, getPrivateField(gemini, "modelName"))));
		Assertions.assertEquals(vertexCredentials, (Object) getPrivateField(gemini, "vertexCredentials"));
		Assertions.assertNull(getPrivateField(gemini, "apiKey"));
		Assertions.assertNull(getPrivateField(gemini, "apiClient"));
	}

	/**
	 * Scenario 5: Build prioritizes apiClient over apiKey and vertexCredentials
	 */
	@Test
	@Tag("valid")
	public void testBuildWithApiClientAndOthers() {
		Gemini.Builder builder = createBuilder();
		String testModelName = "test-model-priority";
		Client priorityClient = Mockito.mock(Client.class);
		builder.modelName(testModelName);
		builder.apiClient(priorityClient);
		builder.apiKey("someKey");
		builder.vertexCredentials(Mockito.mock(VertexCredentials.class));
		Gemini gemini = builder.build();
		Assertions.assertNotNull((Object) gemini);
		Assertions.assertTrue((boolean) (Objects.equals(testModelName, getPrivateField(gemini, "modelName"))));
		Assertions.assertEquals(priorityClient, (Object) getPrivateField(gemini, "apiClient"));
		Assertions.assertNull(getPrivateField(gemini, "apiKey"));
		Assertions.assertNull(getPrivateField(gemini, "vertexCredentials"));
	}

	/**
	 * Scenario 6: Build prioritizes apiKey over vertexCredentials
	 */
	@Test
	@Tag("valid")
	public void testBuildWithApiKeyAndVertexCredentials() {
		Gemini.Builder builder = createBuilder();
		String testModelName = "test-model-apikey-priority";
		String priorityApiKey = "priority-key";
		VertexCredentials mockVertex = Mockito.mock(VertexCredentials.class);
		builder.modelName(testModelName);
		builder.apiKey(priorityApiKey);
		builder.vertexCredentials(mockVertex);
		Gemini gemini = builder.build();
		Assertions.assertNotNull((Object) gemini);
		Assertions.assertTrue((boolean) (Objects.equals(testModelName, getPrivateField(gemini, "modelName"))));
		Assertions.assertEquals(priorityApiKey, (String) getPrivateField(gemini, "apiKey"));
		Assertions.assertNull(getPrivateField(gemini, "apiClient"));
		Assertions.assertNull(getPrivateField(gemini, "vertexCredentials"));
	}

	/**
	 * Scenario 7: Build throws NullPointerException if modelName is not set
	 */
	@Test
	@Tag("invalid")
	public void testBuildThrowsIfModelNameNotSet() {
		Gemini.Builder builder = createBuilder();
		builder.apiKey("no-model-name");
		NullPointerException npe = Assertions.assertThrows(NullPointerException.class, () -> builder.build());
		Assertions.assertTrue((boolean) npe.getMessage().contains("modelName must be set."));
	}

	/**
	 * Scenario 8: Build with all authentication fields unset (only modelName set)
	 */
	@Test
	@Tag("boundary")
	public void testBuildWithNoAuthFields() {
		Gemini.Builder builder = createBuilder();
		String modelName = "no-auth-model";
		builder.modelName(modelName);
		Gemini gemini = builder.build();
		Assertions.assertTrue((boolean) (Objects.equals(modelName, getPrivateField(gemini, "modelName"))));
		Assertions.assertNotNull((Object) getPrivateField(gemini, "apiClient"));
		Assertions.assertNull(getPrivateField(gemini, "apiKey"));
		Assertions.assertNull(getPrivateField(gemini, "vertexCredentials"));
	}

	/**
	 * Scenario 9: Build with explicitly null values for credentials
	 */
	@Test
	@Tag("boundary")
	public void testBuildWithExplicitNullsForCredentials() {
		Gemini.Builder builder = createBuilder();
		String modelName = "nulls-model";
		builder.modelName(modelName);
		builder.apiClient(null);
		builder.apiKey(null);
		builder.vertexCredentials(null);
		Gemini gemini = builder.build();
		Assertions.assertTrue((boolean) (Objects.equals(modelName, getPrivateField(gemini, "modelName"))));
		Assertions.assertNotNull((Object) getPrivateField(gemini, "apiClient"));
		Assertions.assertNull(getPrivateField(gemini, "apiKey"));
		Assertions.assertNull(getPrivateField(gemini, "vertexCredentials"));
	}

	/**
	 * Scenario 10: Multiple calls to Builder setters and build
	 */
	@Test
	@Tag("integration")
	public void testBuildWithSetterReassignment() {
		Gemini.Builder builder = createBuilder();
		String modelName = "reassign-model";
		builder.modelName(modelName);
		builder.apiKey("first-key");
		builder.vertexCredentials(Mockito.mock(VertexCredentials.class));
		builder.apiKey("second-key");
		Client reassignedClient = Mockito.mock(Client.class);
		builder.apiClient(reassignedClient);
		Gemini gemini = builder.build();
		Assertions.assertTrue((boolean) (Objects.equals(modelName, getPrivateField(gemini, "modelName"))));
		Assertions.assertEquals(reassignedClient, (Object) getPrivateField(gemini, "apiClient"));
		Assertions.assertNull(getPrivateField(gemini, "apiKey"));
		Assertions.assertNull(getPrivateField(gemini, "vertexCredentials"));
	}

	/**
	 * Scenario 11: Build with empty string as apiKey
	 */
	@Test
	@Tag("boundary")
	public void testBuildWithEmptyApiKey() {
		Gemini.Builder builder = createBuilder();
		String modelName = "empty-key-model";
		builder.modelName(modelName);
		builder.apiKey("");
		Gemini gemini = builder.build();
		Assertions.assertTrue((boolean) (Objects.equals(modelName, getPrivateField(gemini, "modelName"))));
		Assertions.assertEquals("", (String) getPrivateField(gemini, "apiKey"));
		Assertions.assertNull(getPrivateField(gemini, "apiClient"));
		Assertions.assertNull(getPrivateField(gemini, "vertexCredentials"));
	}

	/**
	 * Scenario 12: Build with minimal required modelName (edge case values)
	 */
	@Test
	@Tag("boundary")
	public void testBuildWithMinimalModelNameContent() {
		Gemini.Builder builder = createBuilder();
		builder.modelName("a");
		Gemini gemini = builder.build();
		Assertions.assertTrue((boolean) (Objects.equals("a", getPrivateField(gemini, "modelName"))));
		Assertions.assertNotNull((Object) getPrivateField(gemini, "apiClient"));
		Assertions.assertNull(getPrivateField(gemini, "apiKey"));
		Assertions.assertNull(getPrivateField(gemini, "vertexCredentials"));
	}

	/**
	 * Utility method relying on reflection to access private fields for assertions.
	 */
	private Object getPrivateField(Object instance, String fieldName) {
		try {
			java.lang.reflect.Field f = instance.getClass().getDeclaredField(fieldName);
			f.setAccessible(true);
			return f.get(instance);
		}
		catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

}