/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-repo using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=modelName_423c161ca3
ROOST_METHOD_SIG_HASH=modelName_2d01dc01ba

Scenario 1: Setting a Valid Model Name with Full Path Including Provider and Version

Details:
  TestName: setModelNameWithFullPathIncludingProviderAndVersion
  Description: Verify that the modelName method correctly sets a model name that includes the provider, version, and model ID in the format "apigee/vertex_ai/v1/gemini-2.5-flash".

Execution:
  Arrange: Create a new Builder instance using ApigeeLlm.builder().
  Act: Call the modelName method with the string "apigee/vertex_ai/v1/gemini-2.5-flash".
  Assert: Verify that the method returns the same Builder instance (for method chaining).

Validation:
  The assertion verifies that the builder pattern is correctly implemented by returning the same Builder instance. This is essential for fluent API design, allowing users to chain multiple configuration calls together when constructing an ApigeeLlm instance.

---

Scenario 2: Setting a Valid Model Name with Provider Only

Details:
  TestName: setModelNameWithProviderOnly
  Description: Verify that the modelName method correctly sets a model name that includes only the provider and model ID in the format "apigee/gemini/gemini-2.5-flash".

Execution:
  Arrange: Create a new Builder instance using ApigeeLlm.builder().
  Act: Call the modelName method with the string "apigee/gemini/gemini-2.5-flash".
  Assert: Verify that the method returns the same Builder instance.

Validation:
  The assertion confirms that the builder correctly accepts model strings with provider specification but without explicit version. This validates support for the optional version component in the model string format.

---

Scenario 3: Setting a Valid Model Name with Version Only

Details:
  TestName: setModelNameWithVersionOnly
  Description: Verify that the modelName method correctly sets a model name that includes only the version and model ID in the format "apigee/v1/gemini-2.5-flash".

Execution:
  Arrange: Create a new Builder instance using ApigeeLlm.builder().
  Act: Call the modelName method with the string "apigee/v1/gemini-2.5-flash".
  Assert: Verify that the method returns the same Builder instance.

Validation:
  The assertion ensures that the builder accepts model strings where the provider is omitted but the version is specified. This tests the flexibility of the model string format.

---

Scenario 4: Setting a Minimal Valid Model Name

Details:
  TestName: setMinimalValidModelName
  Description: Verify that the modelName method correctly sets a minimal model name containing only the prefix and model ID in the format "apigee/gemini-2.5-flash".

Execution:
  Arrange: Create a new Builder instance using ApigeeLlm.builder().
  Act: Call the modelName method with the string "apigee/gemini-2.5-flash".
  Assert: Verify that the method returns the same Builder instance.

Validation:
  The assertion validates that the simplest valid model string format is accepted. This is important for users who want to use default provider and version settings.

---

Scenario 5: Setting a Null Model Name

Details:
  TestName: setNullModelName
  Description: Verify that the modelName method accepts a null value without throwing an exception during the setter call (validation occurs at build time).

Execution:
  Arrange: Create a new Builder instance using ApigeeLlm.builder().
  Act: Call the modelName method with null.
  Assert: Verify that the method returns the same Builder instance without throwing an exception.

Validation:
  The assertion confirms that the modelName setter does not perform validation and simply stores the value. This follows the builder pattern convention where validation typically occurs during the build() call rather than during individual setter calls.

---

Scenario 6: Setting an Empty String Model Name

Details:
  TestName: setEmptyStringModelName
  Description: Verify that the modelName method accepts an empty string without throwing an exception during the setter call.

Execution:
  Arrange: Create a new Builder instance using ApigeeLlm.builder().
  Act: Call the modelName method with an empty string "".
  Assert: Verify that the method returns the same Builder instance.

Validation:
  The assertion verifies that the setter method does not validate the input and accepts any string value. Validation of the model string format is deferred to the build() method.

---

Scenario 7: Method Chaining with Multiple Builder Methods

Details:
  TestName: methodChainingWithMultipleBuilderMethods
  Description: Verify that the modelName method can be chained with other builder methods like proxyUrl and customHeaders.

Execution:
  Arrange: Create a new Builder instance using ApigeeLlm.builder() and prepare a HashMap for custom headers.
  Act: Chain modelName("apigee/gemini-2.5-flash") with proxyUrl("https://proxy.example.com") and customHeaders(customHeadersMap).
  Assert: Verify that the final result is a Builder instance that can be used to build an ApigeeLlm.

Validation:
  The assertion confirms that the fluent builder API works correctly, allowing users to configure multiple properties in a single statement. This is a key usability feature of the builder pattern.

---

Scenario 8: Overwriting Previously Set Model Name

Details:
  TestName: overwritePreviouslySetModelName
  Description: Verify that calling modelName multiple times overwrites the previous value with the new one.

Execution:
  Arrange: Create a new Builder instance using ApigeeLlm.builder().
  Act: Call modelName("apigee/gemini/model1") followed by modelName("apigee/vertex_ai/model2").
  Assert: Verify that the method returns the same Builder instance after each call.

Validation:
  The assertion ensures that the builder correctly handles multiple calls to the same setter, with the last value taking precedence. This is standard behavior for builder patterns and allows users to modify configurations before building.

---

Scenario 9: Setting Model Name with Vertex AI Provider

Details:
  TestName: setModelNameWithVertexAiProvider
  Description: Verify that the modelName method correctly accepts a model string specifying the vertex_ai provider.

Execution:
  Arrange: Create a new Builder instance using ApigeeLlm.builder().
  Act: Call the modelName method with the string "apigee/vertex_ai/gemini-2.5-flash".
  Assert: Verify that the method returns the same Builder instance.

Validation:
  The assertion validates that the builder accepts Vertex AI provider specification. This is important for users who need to explicitly route requests through Vertex AI rather than relying on environment variables.

---

Scenario 10: Setting Model Name with Beta Version

Details:
  TestName: setModelNameWithBetaVersion
  Description: Verify that the modelName method correctly accepts a model string with a beta version specification like "v1beta".

Execution:
  Arrange: Create a new Builder instance using ApigeeLlm.builder().
  Act: Call the modelName method with the string "apigee/vertex_ai/v1beta/gemini-2.5-flash".
  Assert: Verify that the method returns the same Builder instance.

Validation:
  The assertion confirms that the builder accepts version strings that include beta or other suffixes. This supports users who need to access preview or beta API versions.

---

Scenario 11: Setting Model Name with Special Characters in Model ID

Details:
  TestName: setModelNameWithSpecialCharactersInModelId
  Description: Verify that the modelName method accepts model strings where the model ID contains hyphens and numbers.

Execution:
  Arrange: Create a new Builder instance using ApigeeLlm.builder().
  Act: Call the modelName method with the string "apigee/gemini-2.5-flash-001".
  Assert: Verify that the method returns the same Builder instance.

Validation:
  The assertion ensures that model IDs with common naming conventions (hyphens, version numbers) are accepted by the setter. This reflects real-world model naming patterns.

---

Scenario 12: Setting Model Name with Whitespace

Details:
  TestName: setModelNameWithWhitespace
  Description: Verify that the modelName method accepts a string containing leading or trailing whitespace without modification.

Execution:
  Arrange: Create a new Builder instance using ApigeeLlm.builder().
  Act: Call the modelName method with the string "  apigee/gemini-2.5-flash  ".
  Assert: Verify that the method returns the same Builder instance.

Validation:
  The assertion confirms that the setter does not trim or modify the input string. Any validation or normalization would occur during the build() phase, maintaining separation of concerns in the builder pattern.

*/

// ********RoostGPT********

package com.google.adk.models;

import static com.google.common.truth.Truth.assertThat;

import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class BuilderModelNameTest {

  private ApigeeLlm.Builder builder;

  @BeforeEach
  void setUp() {
    builder = ApigeeLlm.builder();
  }

  @Test
  @Tag("valid")
  void setModelNameWithFullPathIncludingProviderAndVersion() {
    // Arrange
    String modelName = "apigee/vertex_ai/v1/gemini-2.5-flash";
    // Act
    ApigeeLlm.Builder result = builder.modelName(modelName);
    // Assert
    assertThat(result).isSameInstanceAs(builder);
  }

  @Test
  @Tag("valid")
  void setModelNameWithProviderOnly() {
    // Arrange
    String modelName = "apigee/gemini/gemini-2.5-flash";
    // Act
    ApigeeLlm.Builder result = builder.modelName(modelName);
    // Assert
    assertThat(result).isSameInstanceAs(builder);
  }

  @Test
  @Tag("valid")
  void setModelNameWithVersionOnly() {
    // Arrange
    String modelName = "apigee/v1/gemini-2.5-flash";
    // Act
    ApigeeLlm.Builder result = builder.modelName(modelName);
    // Assert
    assertThat(result).isSameInstanceAs(builder);
  }

  @Test
  @Tag("valid")
  void setMinimalValidModelName() {
    // Arrange
    String modelName = "apigee/gemini-2.5-flash";
    // Act
    ApigeeLlm.Builder result = builder.modelName(modelName);
    // Assert
    assertThat(result).isSameInstanceAs(builder);
  }

  @Test
  @Tag("boundary")
  void setNullModelName() {
    // Arrange
    String modelName = null;
    // Act
    ApigeeLlm.Builder result = builder.modelName(modelName);
    // Assert
    assertThat(result).isSameInstanceAs(builder);
  }

  @Test
  @Tag("boundary")
  void setEmptyStringModelName() {
    // Arrange
    String modelName = "";
    // Act
    ApigeeLlm.Builder result = builder.modelName(modelName);
    // Assert
    assertThat(result).isSameInstanceAs(builder);
  }

  @Test
  @Tag("valid")
  void methodChainingWithMultipleBuilderMethods() {
    // Arrange
    Map<String, String> customHeadersMap = new HashMap<>();
    customHeadersMap.put("X-Custom-Header", "value");
    // Act
    ApigeeLlm.Builder result =
        builder
            .modelName("apigee/gemini-2.5-flash")
            .proxyUrl("https://proxy.example.com")
            .customHeaders(customHeadersMap);
    // Assert
    assertThat(result).isNotNull();
    assertThat(result).isInstanceOf(ApigeeLlm.Builder.class);
  }

  @Test
  @Tag("valid")
  void overwritePreviouslySetModelName() {
    // Arrange
    String firstModelName = "apigee/gemini/model1";
    String secondModelName = "apigee/vertex_ai/model2";
    // Act
    ApigeeLlm.Builder result1 = builder.modelName(firstModelName);
    ApigeeLlm.Builder result2 = builder.modelName(secondModelName);
    // Assert
    assertThat(result1).isSameInstanceAs(builder);
    assertThat(result2).isSameInstanceAs(builder);
  }

  @Test
  @Tag("valid")
  void setModelNameWithVertexAiProvider() {
    // Arrange
    String modelName = "apigee/vertex_ai/gemini-2.5-flash";
    // Act
    ApigeeLlm.Builder result = builder.modelName(modelName);
    // Assert
    assertThat(result).isSameInstanceAs(builder);
  }

  @Test
  @Tag("valid")
  void setModelNameWithBetaVersion() {
    // Arrange
    String modelName = "apigee/vertex_ai/v1beta/gemini-2.5-flash";
    // Act
    ApigeeLlm.Builder result = builder.modelName(modelName);
    // Assert
    assertThat(result).isSameInstanceAs(builder);
  }

  @Test
  @Tag("valid")
  void setModelNameWithSpecialCharactersInModelId() {
    // Arrange
    String modelName = "apigee/gemini-2.5-flash-001";
    // Act
    ApigeeLlm.Builder result = builder.modelName(modelName);
    // Assert
    assertThat(result).isSameInstanceAs(builder);
  }

  @Test
  @Tag("boundary")
  void setModelNameWithWhitespace() {
    // Arrange
    String modelName = "  apigee/gemini-2.5-flash  ";
    // Act
    ApigeeLlm.Builder result = builder.modelName(modelName);
    // Assert
    assertThat(result).isSameInstanceAs(builder);
  }
}
