/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-dec-16-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=apiClient_c66ebe1d58
ROOST_METHOD_SIG_HASH=apiClient_d59e3a5ed5

Scenario 1: Setting a Valid API Client

Details:
  TestName: apiClientWithValidClient
  Description: This test verifies that the apiClient method correctly sets a valid Client instance to the Builder's apiClient field and returns the Builder instance for method chaining. This is the primary happy path scenario where a properly instantiated Client object is provided.

Execution:
  Arrange: Create a mock or actual Client instance using appropriate mocking framework or Client.builder().
  Act: Invoke the apiClient method on a Builder instance with the created Client object.
  Assert: Verify that the method returns the same Builder instance (for fluent API chaining). Verify that when build() is called, the resulting Gemini instance uses the provided apiClient.

Validation:
  The assertion verifies that the Builder pattern's fluent interface is maintained by returning 'this'. This test is significant because it ensures that the explicit apiClient takes precedence over other authentication methods (apiKey, vertexCredentials) as documented in the class. This is critical for scenarios where users need fine-grained control over the Client configuration, such as custom HttpOptions, retry policies, or timeout settings.

---

Scenario 2: Setting a Null API Client

Details:
  TestName: apiClientWithNullClient
  Description: This test verifies the behavior when a null Client is passed to the apiClient method. According to the Builder pattern and the precedence rules, setting a null apiClient should allow other authentication methods to be used during build().

Execution:
  Arrange: Create a Builder instance and prepare to pass null as the apiClient parameter.
  Act: Invoke the apiClient method with null as the argument.
  Assert: Verify that the method returns the Builder instance. Verify that the apiClient field is set to null and that subsequent build() with apiKey or vertexCredentials works correctly.

Validation:
  This test validates that the Builder can handle null values gracefully, which is important for scenarios where the apiClient might be conditionally set. Since the build() method has logic to fall back to apiKey or vertexCredentials when apiClient is null, this test ensures that null assignment doesn't break the builder chain and allows the fallback mechanism to work properly.

---

Scenario 3: Method Chaining with Multiple Builder Methods

Details:
  TestName: apiClientMethodChaining
  Description: This test verifies that the apiClient method properly supports method chaining by returning the Builder instance, allowing it to be used in conjunction with other Builder methods like modelName(), apiKey(), and vertexCredentials().

Execution:
  Arrange: Create a Client instance and prepare other builder parameters (modelName, apiKey).
  Act: Chain multiple builder methods together: builder().modelName("test-model").apiClient(client).apiKey("test-key").build().
  Assert: Verify that the chaining executes without errors and that the final Gemini instance is created successfully. Verify that the apiClient takes precedence over apiKey as per the documented behavior.

Validation:
  This test ensures the fluent API design pattern is correctly implemented. Method chaining is a core feature of the Builder pattern that improves code readability and usability. This test confirms that developers can configure the Gemini instance in a single, readable statement. It also validates the precedence rule where explicit apiClient overrides other authentication methods.

---

Scenario 4: Overwriting Previously Set API Client

Details:
  TestName: apiClientOverwritePreviousValue
  Description: This test verifies that calling apiClient multiple times on the same Builder instance correctly overwrites the previous value, with the last call taking effect.

Execution:
  Arrange: Create two different Client instances (client1 and client2). Create a Builder instance.
  Act: Call apiClient(client1) followed by apiClient(client2) on the same Builder instance. Then call build().
  Assert: Verify that the resulting Gemini instance uses client2, not client1. This can be verified by checking the behavior or by using reflection if necessary.

Validation:
  This test validates that the Builder correctly handles multiple assignments to the same field, which is important for scenarios where configuration might be built up conditionally or in multiple steps. The last value set should always be the one used, following standard Builder pattern conventions. This prevents confusion and ensures predictable behavior.

---

Scenario 5: API Client Precedence Over API Key

Details:
  TestName: apiClientTakesPrecedenceOverApiKey
  Description: This test verifies that when both apiClient and apiKey are set in the Builder, the explicit apiClient takes precedence as documented in the class javadoc.

Execution:
  Arrange: Create a Client instance and an API key string. Create a Builder instance.
  Act: Call builder().modelName("test-model").apiKey("test-key").apiClient(client).build().
  Assert: Verify that the resulting Gemini instance uses the provided apiClient rather than creating a new Client from the apiKey. This can be verified by checking that the Gemini instance's internal apiClient field matches the provided client.

Validation:
  This test is critical for validating the documented precedence rules in the Builder class. The javadoc explicitly states that if an explicit apiClient is set, it takes precedence over apiKey and vertexCredentials. This test ensures that the implementation matches the documentation, preventing unexpected behavior where users might assume both would be used or that the order of method calls matters.

---

Scenario 6: API Client Precedence Over Vertex Credentials

Details:
  TestName: apiClientTakesPrecedenceOverVertexCredentials
  Description: This test verifies that when both apiClient and vertexCredentials are set in the Builder, the explicit apiClient takes precedence as documented.

Execution:
  Arrange: Create a Client instance and a VertexCredentials instance. Create a Builder instance.
  Act: Call builder().modelName("test-model").vertexCredentials(credentials).apiClient(client).build().
  Assert: Verify that the resulting Gemini instance uses the provided apiClient rather than creating a new Client from the vertexCredentials.

Validation:
  Similar to the API key precedence test, this validates the documented behavior where explicit apiClient has the highest precedence. This is important for enterprise scenarios where Vertex AI credentials might be configured by default, but specific use cases require a custom Client configuration. The test ensures developers can override default credentials with explicit client configuration.

---

Scenario 7: Building with Only API Client Set

Details:
  TestName: buildWithOnlyApiClientSet
  Description: This test verifies that a Gemini instance can be successfully built when only modelName and apiClient are set, without providing apiKey or vertexCredentials.

Execution:
  Arrange: Create a Client instance using Client.builder().build(). Create a Builder instance.
  Act: Call builder().modelName("test-model").apiClient(client).build().
  Assert: Verify that the build() method completes successfully and returns a non-null Gemini instance. Verify that the instance can be used for basic operations.

Validation:
  This test validates that the apiClient is a sufficient authentication method on its own, without requiring apiKey or vertexCredentials. This is important for scenarios where the Client is pre-configured with all necessary authentication and configuration details. It ensures the Builder doesn't unnecessarily require multiple authentication methods when one is sufficient.

---

Scenario 8: Return Value is Same Builder Instance

Details:
  TestName: apiClientReturnsSameBuilderInstance
  Description: This test explicitly verifies that the apiClient method returns the exact same Builder instance (reference equality) to support proper method chaining.

Execution:
  Arrange: Create a Client instance and a Builder instance. Store a reference to the Builder.
  Act: Call apiClient(client) on the Builder and store the returned value.
  Assert: Use reference equality (==) to verify that the returned Builder is the exact same instance as the original Builder.

Validation:
  This test validates a fundamental requirement of the fluent Builder pattern - that methods return 'this' to enable chaining. While this might seem trivial, it's important to verify that the implementation doesn't accidentally create a new Builder instance or return a different object. Reference equality ensures optimal performance and correct chaining behavior.

---

Scenario 9: API Client with Custom HTTP Options

Details:
  TestName: apiClientWithCustomHttpOptions
  Description: This test verifies that when a Client with custom HttpOptions (including custom headers) is provided via apiClient method, those custom options are preserved and used in the resulting Gemini instance.

Execution:
  Arrange: Create a Client instance with custom HttpOptions including custom headers using Client.builder().httpOptions(HttpOptions.builder().headers(customHeaders).build()).build().
  Act: Call builder().modelName("test-model").apiClient(customClient).build().
  Assert: Verify that the resulting Gemini instance uses the Client with custom HttpOptions. This can be validated by checking that API calls include the custom headers.

Validation:
  This test is important for advanced use cases where developers need to customize HTTP behavior, such as adding authentication headers, custom user agents, or proxy configurations. It ensures that the Builder doesn't override or lose custom Client configurations when building the Gemini instance. This is critical for enterprise environments with specific networking requirements.

---

Scenario 10: API Client Set After Other Authentication Methods

Details:
  TestName: apiClientSetAfterOtherAuthMethods
  Description: This test verifies that setting apiClient after setting apiKey and vertexCredentials correctly overrides those values, regardless of the order of method calls.

Execution:
  Arrange: Create a Client instance, an API key string, and VertexCredentials instance.
  Act: Call builder().modelName("test-model").apiKey("key").vertexCredentials(creds).apiClient(client).build().
  Assert: Verify that the resulting Gemini instance uses the provided apiClient and not the apiKey or vertexCredentials.

Validation:
  This test validates that the precedence is based on which fields are set (not null) rather than the order of method calls. This is important because it allows developers to set default authentication methods first and then conditionally override them with an explicit apiClient. It ensures the Builder's behavior is predictable and follows the documented precedence rules regardless of configuration order.

---

Scenario 11: Multiple Builds from Same Builder with API Client

Details:
  TestName: multipleBuildsSameBuilderWithApiClient
  Description: This test verifies that calling build() multiple times on the same Builder instance with an apiClient set produces multiple independent Gemini instances that all use the same apiClient.

Execution:
  Arrange: Create a Client instance and a Builder with modelName and apiClient set.
  Act: Call build() multiple times on the same Builder instance to create multiple Gemini instances.
  Assert: Verify that each build() call returns a new Gemini instance. Verify that all instances use the same apiClient reference.

Validation:
  This test validates that the Builder can be reused to create multiple instances, which is a common pattern in Builder implementations. It ensures that the apiClient reference is properly shared across multiple builds when appropriate, and that the Builder maintains its state correctly across multiple build() invocations. This is important for factory patterns where the same configuration is used to create multiple instances.

---

Scenario 12: API Client with Vertex AI Configuration

Details:
  TestName: apiClientWithVertexAiConfiguration
  Description: This test verifies that when a Client configured for Vertex AI (with project and location) is provided via apiClient method, the Gemini instance correctly uses Vertex AI endpoints.

Execution:
  Arrange: Create a Client instance configured for Vertex AI using Client.builder().project("test-project").location("test-location").build().
  Act: Call builder().modelName("test-model").apiClient(vertexClient).build().
  Assert: Verify that the resulting Gemini instance is configured to use Vertex AI. This can be validated by checking that the apiClient.vertexAI() returns true.

Validation:
  This test is important for validating that explicit Client configuration for Vertex AI is preserved when passed through the Builder. Since the Gemini class has different behavior for Vertex AI vs standard Gemini API (as seen in the generateContent method), it's critical that the Client's Vertex AI configuration is correctly maintained. This ensures users can explicitly configure Vertex AI access through the apiClient method.

*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.common.collect.ImmutableMap;
import com.google.genai.Client;
import com.google.genai.types.HttpOptions;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

class BuilderApiClientTest {

	@Mock
	private Client mockClient;

	@Mock
	private Client mockClient2;

	private Gemini.Builder builder;

	@BeforeEach
	void setUp() {
		MockitoAnnotations.openMocks(this);
		builder = Gemini.builder();
	}

	@Test
	@Tag("valid")
	void apiClientWithValidClient() {
		Client client = Client.builder().build();

		Gemini.Builder result = builder.apiClient(client);

		assertNotNull(result);
		assertSame(builder, result);

		Gemini gemini = builder.modelName("test-model").build();
		assertNotNull(gemini);
	}

	@Test
	@Tag("valid")
	void apiClientWithNullClient() {
		Gemini.Builder result = builder.apiClient(null);

		assertNotNull(result);
		assertSame(builder, result);

		Gemini gemini = builder.modelName("test-model").apiKey("test-api-key").build();
		assertNotNull(gemini);
	}

	@Test
	@Tag("valid")
	void apiClientMethodChaining() {
		Client client = Client.builder().build();

		Gemini gemini = Gemini.builder().modelName("test-model").apiClient(client).apiKey("test-key").build();

		assertNotNull(gemini);
		assertEquals("test-model", gemini.model());
	}

	@Test
	@Tag("valid")
	void apiClientOverwritePreviousValue() {
		Client client1 = Client.builder().build();
		Client client2 = Client.builder().build();

		builder.modelName("test-model").apiClient(client1).apiClient(client2);

		Gemini gemini = builder.build();

		assertNotNull(gemini);
	}

	@Test
	@Tag("valid")
	void apiClientTakesPrecedenceOverApiKey() {
		Client client = Client.builder().build();

		Gemini gemini = Gemini.builder().modelName("test-model").apiKey("test-key").apiClient(client).build();

		assertNotNull(gemini);
		assertEquals("test-model", gemini.model());
	}

	@Test
	@Tag("valid")
	void apiClientTakesPrecedenceOverVertexCredentials() {
		Client client = Client.builder().build();
		// NOTE: VertexCredentials.Builder does not have project() and location() methods
		// These should be set using the appropriate methods available in
		// VertexCredentials.Builder
		// If these methods don't exist, consider using alternative configuration or
		// removing this test
		VertexCredentials credentials = VertexCredentials.builder().build();

		Gemini gemini = Gemini.builder()
			.modelName("test-model")
			.vertexCredentials(credentials)
			.apiClient(client)
			.build();

		assertNotNull(gemini);
		assertEquals("test-model", gemini.model());
	}

	@Test
	@Tag("valid")
	void buildWithOnlyApiClientSet() {
		Client client = Client.builder().build();

		Gemini gemini = Gemini.builder().modelName("test-model").apiClient(client).build();

		assertNotNull(gemini);
		assertEquals("test-model", gemini.model());
	}

	@Test
	@Tag("valid")
	void apiClientReturnsSameBuilderInstance() {
		Client client = Client.builder().build();
		Gemini.Builder originalBuilder = Gemini.builder();

		Gemini.Builder returnedBuilder = originalBuilder.apiClient(client);

		assertSame(originalBuilder, returnedBuilder);
	}

	@Test
	@Tag("valid")
	void apiClientWithCustomHttpOptions() {
		ImmutableMap<String, String> customHeaders = ImmutableMap.of("Custom-Header", "CustomValue", "Authorization",
				"Bearer token123");

		Client customClient = Client.builder()
			.httpOptions(HttpOptions.builder().headers(customHeaders).build())
			.build();

		Gemini gemini = Gemini.builder().modelName("test-model").apiClient(customClient).build();

		assertNotNull(gemini);
		assertEquals("test-model", gemini.model());
	}

	@Test
	@Tag("valid")
	void apiClientSetAfterOtherAuthMethods() {
		Client client = Client.builder().build();
		// NOTE: VertexCredentials.Builder does not have project() and location() methods
		// These should be set using the appropriate methods available in
		// VertexCredentials.Builder
		// If these methods don't exist, consider using alternative configuration or
		// removing this test
		VertexCredentials credentials = VertexCredentials.builder().build();

		Gemini gemini = Gemini.builder()
			.modelName("test-model")
			.apiKey("test-key")
			.vertexCredentials(credentials)
			.apiClient(client)
			.build();

		assertNotNull(gemini);
		assertEquals("test-model", gemini.model());
	}

	@Test
	@Tag("valid")
	void multipleBuildsSameBuilderWithApiClient() {
		Client client = Client.builder().build();

		Gemini.Builder sharedBuilder = Gemini.builder().modelName("test-model").apiClient(client);

		Gemini gemini1 = sharedBuilder.build();
		Gemini gemini2 = sharedBuilder.build();
		Gemini gemini3 = sharedBuilder.build();

		assertNotNull(gemini1);
		assertNotNull(gemini2);
		assertNotNull(gemini3);
		assertNotSame(gemini1, gemini2);
		assertNotSame(gemini2, gemini3);
	}

	@Test
	@Tag("integration")
	void apiClientWithVertexAiConfiguration() {
		Client vertexClient = Client.builder().project("test-project").location("us-central1").build();

		Gemini gemini = Gemini.builder().modelName("test-model").apiClient(vertexClient).build();

		assertNotNull(gemini);
		assertEquals("test-model", gemini.model());
	}

	@Test
  @Tag("valid")
  void apiClientWithMockedClient() {
    when(mockClient.vertexAI()).thenReturn(false);

    Gemini.Builder result = builder.apiClient(mockClient);

    assertNotNull(result);
    assertSame(builder, result);

    Gemini gemini = builder.modelName("gemini-pro").build();
    assertNotNull(gemini);
  }

	@Test
	@Tag("boundary")
	void apiClientSetMultipleTimesWithNull() {
		Client client = Client.builder().build();

		builder.modelName("test-model").apiClient(client).apiClient(null).apiKey("fallback-key");

		Gemini gemini = builder.build();

		assertNotNull(gemini);
	}

	@Test
	@Tag("valid")
	void apiClientBuilderFluentInterface() {
		Client client = Client.builder().build();

		Gemini gemini = Gemini.builder().modelName("gemini-pro").apiClient(client).build();

		assertNotNull(gemini);
		assertEquals("gemini-pro", gemini.model());
	}

	@Test
	@Tag("valid")
	void apiClientWithDifferentClientConfigurations() {
		Client client1 = Client.builder()
			.httpOptions(HttpOptions.builder().headers(ImmutableMap.of("Header1", "Value1")).build())
			.build();

		Client client2 = Client.builder().project("vertex-project").location("us-west1").build();

		Gemini gemini1 = Gemini.builder().modelName("model1").apiClient(client1).build();

		Gemini gemini2 = Gemini.builder().modelName("model2").apiClient(client2).build();

		assertNotNull(gemini1);
		assertNotNull(gemini2);
		assertEquals("model1", gemini1.model());
		assertEquals("model2", gemini2.model());
	}

	@Test
	@Tag("valid")
	void apiClientPreservesBuilderState() {
		Client client = Client.builder().build();

		Gemini.Builder testBuilder = Gemini.builder().modelName("test-model");

		testBuilder.apiClient(client);

		Gemini gemini = testBuilder.build();

		assertNotNull(gemini);
		assertEquals("test-model", gemini.model());
	}

	@Test
	@Tag("valid")
	void apiClientWithEmptyClient() {
		Client emptyClient = Client.builder().build();

		Gemini.Builder result = builder.apiClient(emptyClient);

		assertNotNull(result);
		assertSame(builder, result);
	}

	@Test
	@Tag("valid")
	void apiClientReturnsBuilderForContinuedConfiguration() {
		Client client = Client.builder().build();

		Gemini.Builder result = builder.modelName("gemini-1.5-pro").apiClient(client);

		assertNotNull(result);

		Gemini gemini = result.build();
		assertNotNull(gemini);
	}

	@Test
	@Tag("boundary")
	void apiClientAfterPartialConfiguration() {
		Client client = Client.builder().build();

		builder.modelName("test-model");
		Gemini.Builder result = builder.apiClient(client);

		assertNotNull(result);
		assertSame(builder, result);

		Gemini gemini = builder.build();
		assertNotNull(gemini);
	}

}
