/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-repo using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=build_2a52dae09f
ROOST_METHOD_SIG_HASH=build_8cfd748976

Scenario 1: Build with Valid Simple Model Name

Details:
  TestName: buildWithValidSimpleModelName
  Description: Verify that the build method successfully creates an ApigeeLlm instance when provided with a valid simple model name format (apigee/<model_id>).

Execution:
  Arrange: Create a Builder instance and set the modelName to "apigee/gemini-2.5-flash" and set a valid proxyUrl.
  Act: Call the build() method on the Builder instance.
  Assert: Verify that the returned ApigeeLlm instance is not null.

Validation:
  The assertion verifies that a valid simple model string passes validation and creates an ApigeeLlm instance. This is significant because it confirms the basic model string format is accepted by the builder.

---

Scenario 2: Build with Valid Vertex AI Provider Model Name

Details:
  TestName: buildWithValidVertexAiProviderModelName
  Description: Verify that the build method successfully creates an ApigeeLlm instance when provided with a model name that includes the vertex_ai provider.

Execution:
  Arrange: Create a Builder instance and set the modelName to "apigee/vertex_ai/gemini-2.5-flash" and set a valid proxyUrl.
  Act: Call the build() method on the Builder instance.
  Assert: Verify that the returned ApigeeLlm instance is not null.

Validation:
  The assertion confirms that model strings with the vertex_ai provider are correctly validated and processed. This is important for users who explicitly want to use Vertex AI as their backend.

---

Scenario 3: Build with Valid Gemini Provider Model Name

Details:
  TestName: buildWithValidGeminiProviderModelName
  Description: Verify that the build method successfully creates an ApigeeLlm instance when provided with a model name that includes the gemini provider.

Execution:
  Arrange: Create a Builder instance and set the modelName to "apigee/gemini/gemini-2.5-flash" and set a valid proxyUrl.
  Act: Call the build() method on the Builder instance.
  Assert: Verify that the returned ApigeeLlm instance is not null.

Validation:
  The assertion confirms that model strings with the gemini provider are correctly validated. This ensures users can explicitly specify the Gemini provider.

---

Scenario 4: Build with Valid Three Component Model Name Including Version

Details:
  TestName: buildWithValidThreeComponentModelNameIncludingVersion
  Description: Verify that the build method successfully creates an ApigeeLlm instance when provided with a full three-component model name (provider/version/model_id).

Execution:
  Arrange: Create a Builder instance and set the modelName to "apigee/vertex_ai/v1beta/gemini-2.5-flash" and set a valid proxyUrl.
  Act: Call the build() method on the Builder instance.
  Assert: Verify that the returned ApigeeLlm instance is not null.

Validation:
  The assertion verifies that the complete model string format with provider, version, and model_id is accepted. This is crucial for users who need to specify a particular API version.

---

Scenario 5: Build with Valid Two Component Model Name with Version Only

Details:
  TestName: buildWithValidTwoComponentModelNameWithVersionOnly
  Description: Verify that the build method successfully creates an ApigeeLlm instance when provided with a model name that includes only version and model_id.

Execution:
  Arrange: Create a Builder instance and set the modelName to "apigee/v1/gemini-2.5-flash" and set a valid proxyUrl.
  Act: Call the build() method on the Builder instance.
  Assert: Verify that the returned ApigeeLlm instance is not null.

Validation:
  The assertion confirms that model strings with version prefix (starting with 'v') and model_id are valid. This supports the use case where users want to specify API version without explicitly naming the provider.

---

Scenario 6: Build with Invalid Model Name Missing Apigee Prefix

Details:
  TestName: buildWithInvalidModelNameMissingApigeePrefix
  Description: Verify that the build method throws an IllegalArgumentException when the model name does not start with "apigee/".

Execution:
  Arrange: Create a Builder instance and set the modelName to "gemini-2.5-flash" (missing apigee/ prefix).
  Act: Call the build() method on the Builder instance.
  Assert: Verify that an IllegalArgumentException is thrown with a message containing "Invalid model string".

Validation:
  The assertion ensures that model strings without the required "apigee/" prefix are rejected. This validation is critical to ensure proper routing through the Apigee proxy.

---

Scenario 7: Build with Invalid Model Name Empty After Prefix

Details:
  TestName: buildWithInvalidModelNameEmptyAfterPrefix
  Description: Verify that the build method throws an IllegalArgumentException when the model name is just "apigee/" with nothing following.

Execution:
  Arrange: Create a Builder instance and set the modelName to "apigee/".
  Act: Call the build() method on the Builder instance.
  Assert: Verify that an IllegalArgumentException is thrown.

Validation:
  The assertion confirms that an empty model part after the prefix is rejected. This prevents invalid API calls with no model specified.

---

Scenario 8: Build with Invalid Model Name Trailing Slash

Details:
  TestName: buildWithInvalidModelNameTrailingSlash
  Description: Verify that the build method throws an IllegalArgumentException when the model name ends with a trailing slash.

Execution:
  Arrange: Create a Builder instance and set the modelName to "apigee/gemini-2.5-flash/".
  Act: Call the build() method on the Builder instance.
  Assert: Verify that an IllegalArgumentException is thrown.

Validation:
  The assertion ensures that model strings with trailing slashes (resulting in empty last component) are rejected. This prevents malformed API requests.

---

Scenario 9: Build with Invalid Three Component Model Name Wrong Provider

Details:
  TestName: buildWithInvalidThreeComponentModelNameWrongProvider
  Description: Verify that the build method throws an IllegalArgumentException when a three-component model name has an invalid provider.

Execution:
  Arrange: Create a Builder instance and set the modelName to "apigee/invalid_provider/v1/gemini-2.5-flash".
  Act: Call the build() method on the Builder instance.
  Assert: Verify that an IllegalArgumentException is thrown.

Validation:
  The assertion confirms that only "vertex_ai" and "gemini" are accepted as valid providers in three-component model strings. This ensures proper backend routing.

---

Scenario 10: Build with Invalid Three Component Model Name Wrong Version Format

Details:
  TestName: buildWithInvalidThreeComponentModelNameWrongVersionFormat
  Description: Verify that the build method throws an IllegalArgumentException when a three-component model name has a version that doesn't start with 'v'.

Execution:
  Arrange: Create a Builder instance and set the modelName to "apigee/vertex_ai/beta/gemini-2.5-flash".
  Act: Call the build() method on the Builder instance.
  Assert: Verify that an IllegalArgumentException is thrown.

Validation:
  The assertion ensures that version components must start with 'v' (e.g., v1, v1beta). This enforces the expected API version format.

---

Scenario 11: Build with Null Model Name

Details:
  TestName: buildWithNullModelName
  Description: Verify that the build method throws an exception when the model name is null.

Execution:
  Arrange: Create a Builder instance without setting the modelName (leaving it null).
  Act: Call the build() method on the Builder instance.
  Assert: Verify that a NullPointerException or IllegalArgumentException is thrown.

Validation:
  The assertion confirms that null model names are not accepted. This is essential for preventing null pointer exceptions during API calls.

---

Scenario 12: Build with Custom Headers

Details:
  TestName: buildWithCustomHeaders
  Description: Verify that the build method successfully creates an ApigeeLlm instance when custom headers are provided.

Execution:
  Arrange: Create a Builder instance, set a valid modelName "apigee/gemini-2.5-flash", set a valid proxyUrl, and set customHeaders with key-value pairs like {"Authorization": "Bearer token"}.
  Act: Call the build() method on the Builder instance.
  Assert: Verify that the returned ApigeeLlm instance is not null.

Validation:
  The assertion confirms that custom headers can be passed through the builder. This is important for authentication and other custom header requirements when communicating with the Apigee proxy.

---

Scenario 13: Build with Empty Custom Headers Map

Details:
  TestName: buildWithEmptyCustomHeadersMap
  Description: Verify that the build method successfully creates an ApigeeLlm instance when an empty custom headers map is provided.

Execution:
  Arrange: Create a Builder instance, set a valid modelName "apigee/gemini-2.5-flash", set a valid proxyUrl, and set customHeaders to an empty HashMap.
  Act: Call the build() method on the Builder instance.
  Assert: Verify that the returned ApigeeLlm instance is not null.

Validation:
  The assertion confirms that empty custom headers are handled gracefully. This ensures the builder works correctly when no additional headers are needed.

---

Scenario 14: Build with Invalid Model Name Four Components

Details:
  TestName: buildWithInvalidModelNameFourComponents
  Description: Verify that the build method throws an IllegalArgumentException when the model name has more than three components after the apigee prefix.

Execution:
  Arrange: Create a Builder instance and set the modelName to "apigee/vertex_ai/v1/extra/gemini-2.5-flash".
  Act: Call the build() method on the Builder instance.
  Assert: Verify that an IllegalArgumentException is thrown.

Validation:
  The assertion ensures that model strings with too many components are rejected. The validation logic only accepts 1, 2, or 3 components after the prefix.

---

Scenario 15: Build with Valid Gemini Provider and Version

Details:
  TestName: buildWithValidGeminiProviderAndVersion
  Description: Verify that the build method successfully creates an ApigeeLlm instance when provided with gemini provider and version.

Execution:
  Arrange: Create a Builder instance and set the modelName to "apigee/gemini/v1/gemini-2.5-flash" and set a valid proxyUrl.
  Act: Call the build() method on the Builder instance.
  Assert: Verify that the returned ApigeeLlm instance is not null.

Validation:
  The assertion confirms that the gemini provider with explicit version is correctly validated. This supports users who want to use a specific Gemini API version.

---

Scenario 16: Build with Model Name Containing Special Characters in Model ID

Details:
  TestName: buildWithModelNameContainingSpecialCharactersInModelId
  Description: Verify that the build method successfully creates an ApigeeLlm instance when the model ID contains hyphens and numbers.

Execution:
  Arrange: Create a Builder instance and set the modelName to "apigee/gemini-2.5-flash-001" and set a valid proxyUrl.
  Act: Call the build() method on the Builder instance.
  Assert: Verify that the returned ApigeeLlm instance is not null.

Validation:
  The assertion confirms that model IDs with common naming patterns (hyphens, numbers) are accepted. This is important as many model names follow this convention.

---

Scenario 17: Build with Invalid Two Component Model Name Invalid First Component

Details:
  TestName: buildWithInvalidTwoComponentModelNameInvalidFirstComponent
  Description: Verify that the build method throws an IllegalArgumentException when a two-component model name has a first component that is neither a provider nor starts with 'v'.

Execution:
  Arrange: Create a Builder instance and set the modelName to "apigee/invalid/gemini-2.5-flash".
  Act: Call the build() method on the Builder instance.
  Assert: Verify that an IllegalArgumentException is thrown.

Validation:
  The assertion ensures that two-component model strings must have either a valid provider (vertex_ai, gemini) or a version (starting with 'v') as the first component.

---

Scenario 18: Build with Proxy URL Set

Details:
  TestName: buildWithProxyUrlSet
  Description: Verify that the build method successfully creates an ApigeeLlm instance when a proxy URL is explicitly provided.

Execution:
  Arrange: Create a Builder instance, set a valid modelName "apigee/gemini-2.5-flash", and set proxyUrl to "https://my-apigee-proxy.example.com".
  Act: Call the build() method on the Builder instance.
  Assert: Verify that the returned ApigeeLlm instance is not null.

Validation:
  The assertion confirms that explicitly provided proxy URLs are accepted. This is essential for configuring the Apigee proxy endpoint.

---

Scenario 19: Build with Model Name Only Apigee Prefix No Slash

Details:
  TestName: buildWithModelNameOnlyApigeePrefixNoSlash
  Description: Verify that the build method throws an IllegalArgumentException when the model name is just "apigee" without the trailing slash.

Execution:
  Arrange: Create a Builder instance and set the modelName to "apigee".
  Act: Call the build() method on the Builder instance.
  Assert: Verify that an IllegalArgumentException is thrown.

Validation:
  The assertion ensures that the model string must include the "apigee/" prefix with the slash. This enforces the correct format for model identification.

---

Scenario 20: Build with Valid Version Starting with v1beta

Details:
  TestName: buildWithValidVersionStartingWithV1beta
  Description: Verify that the build method successfully creates an ApigeeLlm instance when the version component is "v1beta".

Execution:
  Arrange: Create a Builder instance and set the modelName to "apigee/vertex_ai/v1beta/gemini-2.5-flash" and set a valid proxyUrl.
  Act: Call the build() method on the Builder instance.
  Assert: Verify that the returned ApigeeLlm instance is not null.

Validation:
  The assertion confirms that beta versions (v1beta, v2beta, etc.) are accepted as valid version strings. This supports access to preview API features.

*/

// ********RoostGPT********

package com.google.adk.models;

import static com.google.common.truth.Truth.assertThat;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

public class BuilderBuildTest {

  @Test
  @Tag("valid")
  void buildWithValidSimpleModelName() {
    ApigeeLlm.Builder builder =
        ApigeeLlm.builder()
            .modelName("apigee/gemini-2.5-flash")
            .proxyUrl("https://proxy.example.com");
    ApigeeLlm result = builder.build();
    assertNotNull(result);
  }

  @Test
  @Tag("valid")
  void buildWithValidVertexAiProviderModelName() {
    ApigeeLlm.Builder builder =
        ApigeeLlm.builder()
            .modelName("apigee/vertex_ai/gemini-2.5-flash")
            .proxyUrl("https://proxy.example.com");
    ApigeeLlm result = builder.build();
    assertNotNull(result);
  }

  @Test
  @Tag("valid")
  void buildWithValidGeminiProviderModelName() {
    ApigeeLlm.Builder builder =
        ApigeeLlm.builder()
            .modelName("apigee/gemini/gemini-2.5-flash")
            .proxyUrl("https://proxy.example.com");
    ApigeeLlm result = builder.build();
    assertNotNull(result);
  }

  @Test
  @Tag("valid")
  void buildWithValidThreeComponentModelNameIncludingVersion() {
    ApigeeLlm.Builder builder =
        ApigeeLlm.builder()
            .modelName("apigee/vertex_ai/v1beta/gemini-2.5-flash")
            .proxyUrl("https://proxy.example.com");
    ApigeeLlm result = builder.build();
    assertNotNull(result);
  }

  @Test
  @Tag("valid")
  void buildWithValidTwoComponentModelNameWithVersionOnly() {
    ApigeeLlm.Builder builder =
        ApigeeLlm.builder()
            .modelName("apigee/v1/gemini-2.5-flash")
            .proxyUrl("https://proxy.example.com");
    ApigeeLlm result = builder.build();
    assertNotNull(result);
  }

  @Test
  @Tag("invalid")
  void buildWithInvalidModelNameMissingApigeePrefix() {
    ApigeeLlm.Builder builder =
        ApigeeLlm.builder().modelName("gemini-2.5-flash").proxyUrl("https://proxy.example.com");
    IllegalArgumentException exception =
        assertThrows(IllegalArgumentException.class, builder::build);
    assertThat(exception.getMessage()).contains("Invalid model string");
  }

  @Test
  @Tag("invalid")
  void buildWithInvalidModelNameEmptyAfterPrefix() {
    ApigeeLlm.Builder builder =
        ApigeeLlm.builder().modelName("apigee/").proxyUrl("https://proxy.example.com");
    assertThrows(IllegalArgumentException.class, builder::build);
  }

  @Test
  @Tag("invalid")
  void buildWithInvalidModelNameTrailingSlash() {
    ApigeeLlm.Builder builder =
        ApigeeLlm.builder()
            .modelName("apigee/gemini-2.5-flash/")
            .proxyUrl("https://proxy.example.com");
    assertThrows(IllegalArgumentException.class, builder::build);
  }

  @Test
  @Tag("invalid")
  void buildWithInvalidThreeComponentModelNameWrongProvider() {
    ApigeeLlm.Builder builder =
        ApigeeLlm.builder()
            .modelName("apigee/invalid_provider/v1/gemini-2.5-flash")
            .proxyUrl("https://proxy.example.com");
    assertThrows(IllegalArgumentException.class, builder::build);
  }

  @Test
  @Tag("invalid")
  void buildWithInvalidThreeComponentModelNameWrongVersionFormat() {
    ApigeeLlm.Builder builder =
        ApigeeLlm.builder()
            .modelName("apigee/vertex_ai/beta/gemini-2.5-flash")
            .proxyUrl("https://proxy.example.com");
    assertThrows(IllegalArgumentException.class, builder::build);
  }

  @Test
  @Tag("invalid")
  void buildWithNullModelName() {
    ApigeeLlm.Builder builder = ApigeeLlm.builder().proxyUrl("https://proxy.example.com");
    assertThrows(Exception.class, builder::build);
  }

  @Test
  @Tag("valid")
  void buildWithCustomHeaders() {
    Map<String, String> customHeaders = new HashMap<>();
    customHeaders.put("Authorization", "Bearer token");
    customHeaders.put("X-Custom-Header", "custom-value");
    ApigeeLlm.Builder builder =
        ApigeeLlm.builder()
            .modelName("apigee/gemini-2.5-flash")
            .proxyUrl("https://proxy.example.com")
            .customHeaders(customHeaders);
    ApigeeLlm result = builder.build();
    assertNotNull(result);
  }

  @Test
  @Tag("valid")
  void buildWithEmptyCustomHeadersMap() {
    ApigeeLlm.Builder builder =
        ApigeeLlm.builder()
            .modelName("apigee/gemini-2.5-flash")
            .proxyUrl("https://proxy.example.com")
            .customHeaders(new HashMap<>());
    ApigeeLlm result = builder.build();
    assertNotNull(result);
  }

  @Test
  @Tag("invalid")
  void buildWithInvalidModelNameFourComponents() {
    ApigeeLlm.Builder builder =
        ApigeeLlm.builder()
            .modelName("apigee/vertex_ai/v1/extra/gemini-2.5-flash")
            .proxyUrl("https://proxy.example.com");
    assertThrows(IllegalArgumentException.class, builder::build);
  }

  @Test
  @Tag("valid")
  void buildWithValidGeminiProviderAndVersion() {
    ApigeeLlm.Builder builder =
        ApigeeLlm.builder()
            .modelName("apigee/gemini/v1/gemini-2.5-flash")
            .proxyUrl("https://proxy.example.com");
    ApigeeLlm result = builder.build();
    assertNotNull(result);
  }

  @Test
  @Tag("valid")
  void buildWithModelNameContainingSpecialCharactersInModelId() {
    ApigeeLlm.Builder builder =
        ApigeeLlm.builder()
            .modelName("apigee/gemini-2.5-flash-001")
            .proxyUrl("https://proxy.example.com");
    ApigeeLlm result = builder.build();
    assertNotNull(result);
  }

  @Test
  @Tag("invalid")
  void buildWithInvalidTwoComponentModelNameInvalidFirstComponent() {
    ApigeeLlm.Builder builder =
        ApigeeLlm.builder()
            .modelName("apigee/invalid/gemini-2.5-flash")
            .proxyUrl("https://proxy.example.com");
    assertThrows(IllegalArgumentException.class, builder::build);
  }

  @Test
  @Tag("valid")
  void buildWithProxyUrlSet() {
    ApigeeLlm.Builder builder =
        ApigeeLlm.builder()
            .modelName("apigee/gemini-2.5-flash")
            .proxyUrl("https://my-apigee-proxy.example.com");
    ApigeeLlm result = builder.build();
    assertNotNull(result);
  }

  @Test
  @Tag("invalid")
  void buildWithModelNameOnlyApigeePrefixNoSlash() {
    ApigeeLlm.Builder builder =
        ApigeeLlm.builder().modelName("apigee").proxyUrl("https://proxy.example.com");
    assertThrows(IllegalArgumentException.class, builder::build);
  }

  @Test
  @Tag("valid")
  void buildWithValidVersionStartingWithV1beta() {
    ApigeeLlm.Builder builder =
        ApigeeLlm.builder()
            .modelName("apigee/vertex_ai/v1beta/gemini-2.5-flash")
            .proxyUrl("https://proxy.example.com");
    ApigeeLlm result = builder.build();
    assertNotNull(result);
  }
}
