/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-jan-9 using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=modelName_423c161ca3
ROOST_METHOD_SIG_HASH=modelName_2d01dc01ba

Scenario 1: Setting the modelName to a valid, typical Gemini model string

Details:
  TestName: setModelNameWithValidString
  Description: This scenario verifies that calling the modelName method with a valid and commonly expected model name string correctly sets the modelName field in the Builder instance and that the Builder instance itself is returned for method chaining.
Execution:
  Arrange: Create a new Gemini.Builder instance.
  Act: Invoke the modelName method with a sample valid model name such as "gemini-2.0-flash".
  Assert: Confirm that the modelName field in the Builder reflects the provided value and the returned object is the same Builder instance.
Validation:
  This assertion protects against bugs where model names are not properly assigned or the method does not support chaining, which is critical for builder-style usage and ensuring fluent API behavior.

Scenario 2: Setting the modelName to null

Details:
  TestName: setModelNameWithNull
  Description: This scenario examines the behavior when the modelName method is called with null. It checks whether the Builder properly assigns null to the modelName field and still returns the Builder instance for chainability.
Execution:
  Arrange: Instantiate a fresh Builder.
  Act: Call modelName with a null parameter.
  Assert: Ensure that the internal modelName field is null after invocation and the returned object is the Builder itself.
Validation:
  This ensures the method does not throw unexpected exceptions on null input and that subsequent calls, such as build(), deliberately handle this case (e.g., build() should throw a NullPointerException if modelName remains unset).

Scenario 3: Setting the modelName to an empty string

Details:
  TestName: setModelNameWithEmptyString
  Description: Verifies how the Builder behaves if modelName is set to an empty string. The test checks that the internal field reflects the empty input and returns the Builder for further calls.
Execution:
  Arrange: Create a Gemini.Builder object.
  Act: Call modelName with an empty string ("").
  Assert: Confirm that the modelName field is now set to "" and that the method returns the Builder for chaining.
Validation:
  This scenario validates robustness for possibly invalid or edge-case model names, ensuring error handling or proper propagation in subsequent build steps if empty strings are unsupported as model names.

Scenario 4: Chaining modelName calls (overwriting the previously set modelName)

Details:
  TestName: chainModelNameOverridesPrevious
  Description: Checks that calling modelName multiple times consecutively updates the modelName field to the last value provided, and that the returned object is always the same Builder instance.
Execution:
  Arrange: Create a Gemini.Builder instance.
  Act: Call modelName with one string (e.g., "first-model"), then call modelName again with another string ("second-model").
  Assert: The modelName field should match "second-model"; returned value should be the same Builder on each call.
Validation:
  Ensures that users can update the model name during builder configuration, and that the builder always holds the latest value provided, supporting a flexible and user-friendly API.

Scenario 5: Setting modelName to a string consisting only of whitespace

Details:
  TestName: setModelNameWithWhitespaceString
  Description: Tests the behavior when the modelName is set to a string comprised solely of whitespace (e.g., "   "). Checks that the white space is preserved if that's the expected model name, and that the Builder is returned for chaining.
Execution:
  Arrange: Create a Gemini.Builder.
  Act: Call modelName with a string containing only white spaces.
  Assert: The modelName field is set to the whitespace string, and the Builder instance is returned.
Validation:
  Validates that the method does not trim or otherwise alter the input, which may be important if whitespace in model names is (improperly or per design) allowed.

Scenario 6: Verifying method chainability with modelName and other builder methods

Details:
  TestName: builderMethodChainingAfterModelName
  Description: Ensures that after invoking modelName, the returned Builder supports further chained configuration (e.g., apiClient, apiKey), enabling fluent builder usage.
Execution:
  Arrange: Create a Gemini.Builder.
  Act: Chain calls such as builder.modelName("some-model").apiKey("api-key").
  Assert: All fields (modelName and apiKey) are set as expected; each call returns the same Builder instance.
Validation:
  Confirms that modelName does not break the builder chain and is consistent with the API’s design for fluent configuration.

Scenario 7: Setting the modelName to a very long string

Details:
  TestName: setModelNameWithVeryLongString
  Description: Challenges the method with a very long input, verifying that there is no arbitrary truncation, error, or memory issue.
Execution:
  Arrange: Instantiate a Builder.
  Act: Call modelName with a string of several thousand characters.
  Assert: The modelName field contains the exact input value; returned object is still the Builder.
Validation:
  Ensures that the Builder can accommodate large model name values and does not enforce undocumented size constraints.

Scenario 8: Setting the modelName to a string with special or Unicode characters

Details:
  TestName: setModelNameWithUnicodeAndSpecialChars
  Description: Verifies that the builder supports model names containing symbols, accents, or Unicode characters, reflecting them without corruption.
Execution:
  Arrange: Create a Builder instance.
  Act: Invoke modelName with a value such as "môdèl-💎-βeta".
  Assert: The modelName field holds the exact Unicode string; method returns the Builder.
Validation:
  This demonstrates support for internationalization or versioning scenarios where non-ASCII model names may be valid.

Scenario 9: Ensuring method does not impact unrelated Builder fields

Details:
  TestName: modelNameDoesNotAffectOtherFields
  Description: Confirms that setting the modelName field does not alter the values of apiKey, apiClient, or vertexCredentials in the Builder.
Execution:
  Arrange: Create a Builder; set all fields (apiKey, apiClient, vertexCredentials) to known values.
  Act: Call modelName with a new string.
  Assert: All other fields retain their original values.
Validation:
  Verifies encapsulation and ensures that setting modelName is side-effect free for other configuration options.

Scenario 10: Confirming returned object identity is unchanged

Details:
  TestName: modelNameReturnsSameBuilderInstance
  Description: Explicitly checks that calling modelName always returns the original Builder instance, supporting method chaining and consistency.
Execution:
  Arrange: Create a Builder.
  Act: Save the reference, call modelName, and compare references.
  Assert: The returned object reference is identical to the original Builder.
Validation:
  This property is critical for correct builder chaining and user expectations.


*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.genai.Client;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

// Assuming Gemini, VertexCredentials classes are available in this package.
public class BuilderModelNameTest {

	// Helper to access Gemini.Builder via official API: Gemini.builder()
	private Gemini.Builder newBuilderInstance() {
		// Since the constructor is private, use a static factory method.
		// Assuming Gemini exposes a static builder() factory (common pattern).
		return Gemini.builder();
	}

	@Test
	@Tag("valid")
	public void testSetModelNameWithValidString() {
		Gemini.Builder builder = newBuilderInstance();
		String validModelName = "gemini-2.0-flash";
		Gemini.Builder returnedBuilder = builder.modelName(validModelName);
		assertSame((Object) builder, (Object) returnedBuilder, "Returned Builder should be the same instance");
		try {
			java.lang.reflect.Field modelNameField = Gemini.Builder.class.getDeclaredField("modelName");
			modelNameField.setAccessible(true);
			Object value = modelNameField.get(builder);
			assertEquals((String) validModelName, (String) value, "modelName field should be set correctly");
		}
		catch (Exception e) {
			fail("Reflection access failed: " + e.getMessage());
		}
	}

	@Test
	@Tag("invalid")
	public void testSetModelNameWithNull() {
		Gemini.Builder builder = newBuilderInstance();
		Gemini.Builder returnedBuilder = builder.modelName(null);
		assertSame((Object) builder, (Object) returnedBuilder, "Returned Builder should be the same instance");
		try {
			java.lang.reflect.Field modelNameField = Gemini.Builder.class.getDeclaredField("modelName");
			modelNameField.setAccessible(true);
			Object value = modelNameField.get(builder);
			assertNull((String) value, "modelName field should be null when set with null");
		}
		catch (Exception e) {
			fail("Reflection access failed: " + e.getMessage());
		}
	}

	@Test
	@Tag("invalid")
	public void testSetModelNameWithEmptyString() {
		Gemini.Builder builder = newBuilderInstance();
		String emptyModelName = "";
		Gemini.Builder returnedBuilder = builder.modelName(emptyModelName);
		assertSame((Object) builder, (Object) returnedBuilder, "Returned Builder should be the same instance");
		try {
			java.lang.reflect.Field modelNameField = Gemini.Builder.class.getDeclaredField("modelName");
			modelNameField.setAccessible(true);
			Object value = modelNameField.get(builder);
			assertEquals((String) emptyModelName, (String) value, "modelName field should be an empty string");
		}
		catch (Exception e) {
			fail("Reflection access failed: " + e.getMessage());
		}
	}

	@Test
	@Tag("valid")
	public void testChainModelNameOverridesPrevious() {
		Gemini.Builder builder = newBuilderInstance();
		String firstValue = "first-model";
		String secondValue = "second-model";
		Gemini.Builder returnedAfterFirst = builder.modelName(firstValue);
		Gemini.Builder returnedAfterSecond = builder.modelName(secondValue);
		assertSame((Object) builder, (Object) returnedAfterFirst, "Returned Builder should be the same on first call");
		assertSame((Object) builder, (Object) returnedAfterSecond,
				"Returned Builder should be the same on second call");
		try {
			java.lang.reflect.Field modelNameField = Gemini.Builder.class.getDeclaredField("modelName");
			modelNameField.setAccessible(true);
			Object value = modelNameField.get(builder);
			assertEquals((String) secondValue, (String) value, "modelName should be overwritten to last call value");
		}
		catch (Exception e) {
			fail("Reflection access failed: " + e.getMessage());
		}
	}

	@Test
	@Tag("boundary")
	public void testSetModelNameWithWhitespaceString() {
		Gemini.Builder builder = newBuilderInstance();
		String whitespaceString = "   ";
		Gemini.Builder returnedBuilder = builder.modelName(whitespaceString);
		assertSame((Object) builder, (Object) returnedBuilder, "Returned Builder should be the same instance");
		try {
			java.lang.reflect.Field modelNameField = Gemini.Builder.class.getDeclaredField("modelName");
			modelNameField.setAccessible(true);
			Object value = modelNameField.get(builder);
			assertEquals((String) whitespaceString, (String) value, "modelName should preserve whitespace");
		}
		catch (Exception e) {
			fail("Reflection access failed: " + e.getMessage());
		}
	}

	@Test
	@Tag("integration")
	public void testBuilderMethodChainingAfterModelName() {
		Gemini.Builder builder = newBuilderInstance();
		String expectedModelName = "some-model";
		String expectedApiKey = "api-key";
		Gemini.Builder returnedBuilder = builder.modelName(expectedModelName).apiKey(expectedApiKey);
		assertSame((Object) builder, (Object) returnedBuilder, "Chaining should return the same builder instance");
		try {
			java.lang.reflect.Field modelNameField = Gemini.Builder.class.getDeclaredField("modelName");
			modelNameField.setAccessible(true);
			Object modelNameValue = modelNameField.get(builder);
			java.lang.reflect.Field apiKeyField = Gemini.Builder.class.getDeclaredField("apiKey");
			apiKeyField.setAccessible(true);
			Object apiKeyValue = apiKeyField.get(builder);
			assertEquals((String) expectedModelName, (String) modelNameValue, "modelName set via chaining");
			assertEquals((String) expectedApiKey, (String) apiKeyValue, "apiKey set via chaining");
		}
		catch (Exception e) {
			fail("Reflection access failed: " + e.getMessage());
		}
	}

	@Test
	@Tag("boundary")
	public void testSetModelNameWithVeryLongString() {
		Gemini.Builder builder = newBuilderInstance();
		String longString = new String(new char[8192]).replace('\0', 'a'); // 8KB string
		Gemini.Builder returnedBuilder = builder.modelName(longString);
		assertSame((Object) builder, (Object) returnedBuilder, "Returned Builder should be the same instance");
		try {
			java.lang.reflect.Field modelNameField = Gemini.Builder.class.getDeclaredField("modelName");
			modelNameField.setAccessible(true);
			Object value = modelNameField.get(builder);
			assertEquals((String) longString, (String) value, "modelName field should accept long strings");
		}
		catch (Exception e) {
			fail("Reflection access failed: " + e.getMessage());
		}
	}

	@Test
	@Tag("boundary")
	public void testSetModelNameWithUnicodeAndSpecialChars() {
		Gemini.Builder builder = newBuilderInstance();
		String unicodeModelName = "môdèl-💎-βeta";
		Gemini.Builder returnedBuilder = builder.modelName(unicodeModelName);
		assertSame((Object) builder, (Object) returnedBuilder, "Returned Builder should return the same instance");
		try {
			java.lang.reflect.Field modelNameField = Gemini.Builder.class.getDeclaredField("modelName");
			modelNameField.setAccessible(true);
			Object value = modelNameField.get(builder);
			assertEquals((String) unicodeModelName, (String) value, "modelName must support Unicode/special chars");
		}
		catch (Exception e) {
			fail("Reflection access failed: " + e.getMessage());
		}
	}

	@Test
	@Tag("integration")
	public void testModelNameDoesNotAffectOtherFields() {
		Gemini.Builder builder = newBuilderInstance();
		Client mockClient = mock(Client.class);
		String testApiKey = "test-api-key";
		VertexCredentials mockVertexCredentials = mock(VertexCredentials.class);
		// apiClient, apiKey and vertexCredentials are setup before modelName is set
		builder.apiClient((Client) mockClient)
			.apiKey((String) testApiKey)
			.vertexCredentials((VertexCredentials) mockVertexCredentials);
		Gemini.Builder returnedBuilder = builder.modelName("irrelevant-model");
		assertSame((Object) builder, (Object) returnedBuilder, "Returned Builder should be the same instance");
		try {
			java.lang.reflect.Field apiClientField = Gemini.Builder.class.getDeclaredField("apiClient");
			apiClientField.setAccessible(true);
			Object apiClientValue = apiClientField.get(builder);
			java.lang.reflect.Field apiKeyField = Gemini.Builder.class.getDeclaredField("apiKey");
			apiKeyField.setAccessible(true);
			Object apiKeyValue = apiKeyField.get(builder);
			java.lang.reflect.Field vertexCredentialsField = Gemini.Builder.class.getDeclaredField("vertexCredentials");
			vertexCredentialsField.setAccessible(true);
			Object vertexCredentialsValue = vertexCredentialsField.get(builder);
			assertSame((Object) mockClient, apiClientValue, "apiClient should be unchanged");
			assertEquals((String) testApiKey, (String) apiKeyValue, "apiKey should be unchanged");
			assertSame((Object) mockVertexCredentials, vertexCredentialsValue, "vertexCredentials should be unchanged");
		}
		catch (Exception e) {
			fail("Reflection access failed: " + e.getMessage());
		}
	}

	@Test
	@Tag("valid")
	public void testModelNameReturnsSameBuilderInstance() {
		Gemini.Builder builder = newBuilderInstance();
		Gemini.Builder returnedBuilder = builder.modelName("just-a-test-model");
		assertSame((Object) builder, (Object) returnedBuilder, "Returned Builder must always be the same instance");
	}

}
