/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-dec-16-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=apiKey_6f7fe65f1f
ROOST_METHOD_SIG_HASH=apiKey_f645a7d0cc

Scenario 1: Setting API Key with Valid Non-Null String

Details:
  TestName: apiKeyWithValidNonNullString
  Description: This test verifies that the apiKey method correctly sets a valid non-null API key string and returns the Builder instance for method chaining. The test ensures that the builder pattern works as expected when a valid API key is provided.
Execution:
  Arrange: Create a new Builder instance using Gemini.builder(). Prepare a valid non-null API key string (e.g., "test-api-key-12345").
  Act: Invoke the apiKey method on the Builder instance with the valid API key string and capture the returned Builder instance.
  Assert: Verify that the returned object is the same Builder instance (method chaining works correctly). Verify that when build() is called with a valid modelName, the Gemini instance is created successfully without throwing exceptions.
Validation:
  The assertion verifies that the apiKey method properly stores the API key value and returns the Builder instance to enable fluent API design. This is critical for the builder pattern implementation, allowing developers to chain multiple configuration methods. The test ensures that a valid API key can be set and used to construct a Gemini instance.

Scenario 2: Setting API Key with Null Value

Details:
  TestName: apiKeyWithNullValue
  Description: This test verifies the behavior when a null value is passed to the apiKey method. It checks whether the method accepts null values and how the Builder handles this scenario during the build process.
Execution:
  Arrange: Create a new Builder instance using Gemini.builder(). Prepare a null value for the API key.
  Act: Invoke the apiKey method on the Builder instance with null value and capture the returned Builder instance.
  Assert: Verify that the method returns the Builder instance without throwing an exception. Verify that the apiKey field is set to null in the Builder.
Validation:
  This test validates that the apiKey method itself does not perform null validation and accepts null values. The null validation, if required, should be handled during the build() method execution. This test is important to understand the method's contract and when validation occurs in the builder lifecycle.

Scenario 3: Setting API Key with Empty String

Details:
  TestName: apiKeyWithEmptyString
  Description: This test verifies that the apiKey method accepts an empty string as a valid input and properly stores it in the Builder instance.
Execution:
  Arrange: Create a new Builder instance using Gemini.builder(). Prepare an empty string ("") for the API key.
  Act: Invoke the apiKey method on the Builder instance with the empty string and capture the returned Builder instance.
  Assert: Verify that the returned object is the same Builder instance. Verify that the empty string is stored in the apiKey field.
Validation:
  The assertion confirms that the apiKey method does not validate the content of the string and accepts empty strings. This test is significant for understanding edge cases where developers might accidentally pass empty strings, and it helps document the expected behavior in such scenarios.

Scenario 4: Setting API Key with Whitespace-Only String

Details:
  TestName: apiKeyWithWhitespaceOnlyString
  Description: This test verifies the behavior when the apiKey method receives a string containing only whitespace characters (spaces, tabs, newlines).
Execution:
  Arrange: Create a new Builder instance using Gemini.builder(). Prepare a whitespace-only string (e.g., "   ", "\t", "\n") for the API key.
  Act: Invoke the apiKey method on the Builder instance with the whitespace-only string and capture the returned Builder instance.
  Assert: Verify that the returned object is the same Builder instance. Verify that the whitespace string is stored without modification.
Validation:
  This test validates that the apiKey method does not trim or validate the content of the provided string. It's important for understanding how the method handles potentially invalid but non-null inputs, which helps developers understand when and where validation should occur.

Scenario 5: Method Chaining with Multiple Builder Methods

Details:
  TestName: apiKeyMethodChainingWithOtherBuilderMethods
  Description: This test verifies that the apiKey method properly supports method chaining by returning the Builder instance, allowing it to be used in combination with other Builder methods like modelName().
Execution:
  Arrange: Create a new Builder instance using Gemini.builder(). Prepare a valid API key string and a valid model name string.
  Act: Chain multiple method calls including apiKey() and modelName() on the Builder instance, then call build().
  Assert: Verify that the method chaining executes without exceptions. Verify that the resulting Gemini instance is created successfully with both the API key and model name properly set.
Validation:
  This assertion confirms that the apiKey method correctly implements the builder pattern by returning 'this', enabling fluent API usage. This is crucial for the usability of the Builder class, as it allows developers to configure multiple properties in a single statement chain.

Scenario 6: Overwriting Previously Set API Key

Details:
  TestName: apiKeyOverwritingPreviousValue
  Description: This test verifies that calling the apiKey method multiple times on the same Builder instance overwrites the previously set API key value with the new value.
Execution:
  Arrange: Create a new Builder instance using Gemini.builder(). Prepare two different API key strings (e.g., "first-api-key" and "second-api-key").
  Act: Call the apiKey method twice on the same Builder instance with different API key values. Build the Gemini instance with a valid model name.
  Assert: Verify that the Builder uses the most recently set API key value (the second one). Verify that the first API key value is completely replaced.
Validation:
  This test validates that the apiKey method follows the standard builder pattern behavior where subsequent calls to the same setter method replace previous values rather than accumulating them. This is important for understanding the Builder's state management and preventing confusion about which value will be used.

Scenario 7: Setting API Key with Very Long String

Details:
  TestName: apiKeyWithVeryLongString
  Description: This test verifies that the apiKey method can handle very long strings without throwing exceptions or truncating the value.
Execution:
  Arrange: Create a new Builder instance using Gemini.builder(). Prepare a very long string (e.g., 10000 characters) for the API key.
  Act: Invoke the apiKey method on the Builder instance with the very long string and capture the returned Builder instance.
  Assert: Verify that the returned object is the same Builder instance. Verify that the method executes without throwing exceptions. Verify that the full string is stored without truncation.
Validation:
  This assertion confirms that the apiKey method does not impose length restrictions on the input string. This test is important for understanding the method's limitations and ensuring it can handle edge cases involving unusually long API keys, even if such keys are unlikely in practice.

Scenario 8: Setting API Key with Special Characters

Details:
  TestName: apiKeyWithSpecialCharacters
  Description: This test verifies that the apiKey method correctly handles strings containing special characters, including symbols, unicode characters, and escape sequences.
Execution:
  Arrange: Create a new Builder instance using Gemini.builder(). Prepare an API key string containing special characters (e.g., "api-key-!@#$%^&*()_+-=[]{}|;:',.<>?/~`").
  Act: Invoke the apiKey method on the Builder instance with the special character string and capture the returned Builder instance.
  Assert: Verify that the returned object is the same Builder instance. Verify that the special characters are stored exactly as provided without modification or escaping.
Validation:
  This test validates that the apiKey method treats the input as a plain string without performing any character encoding, escaping, or filtering. This is important for ensuring that API keys with special characters (which may be valid in certain systems) are preserved correctly.

Scenario 9: API Key Precedence Over Vertex Credentials

Details:
  TestName: apiKeyTakesPrecedenceOverVertexCredentials
  Description: This test verifies that when both apiKey and vertexCredentials are set on the Builder, the apiKey takes precedence according to the documented behavior in the Builder class.
Execution:
  Arrange: Create a new Builder instance using Gemini.builder(). Prepare a valid API key string and a valid VertexCredentials instance. Set a valid model name.
  Act: Call both apiKey() and vertexCredentials() methods on the Builder instance, then call build().
  Assert: Verify that the resulting Gemini instance is created successfully. Verify that the instance uses the API key-based client rather than the Vertex credentials-based client.
Validation:
  This assertion confirms the documented precedence order in the Builder class where apiKey takes priority over vertexCredentials. This test is crucial for ensuring that the Builder behaves predictably when multiple authentication methods are configured, preventing ambiguity in production code.

Scenario 10: API Key Does Not Take Precedence Over Explicit API Client

Details:
  TestName: apiKeyDoesNotOverrideExplicitApiClient
  Description: This test verifies that when both an explicit apiClient and apiKey are set on the Builder, the explicit apiClient takes precedence as documented in the Builder class.
Execution:
  Arrange: Create a new Builder instance using Gemini.builder(). Prepare a valid API key string and a mock or real Client instance. Set a valid model name.
  Act: Call both apiClient() and apiKey() methods on the Builder instance, then call build().
  Assert: Verify that the resulting Gemini instance is created successfully. Verify that the instance uses the explicitly provided Client instance rather than creating a new one from the API key.
Validation:
  This test validates the documented precedence hierarchy where an explicit apiClient has the highest priority. This is important for scenarios where developers need fine-grained control over the Client configuration and want to ensure their custom client is used regardless of other authentication methods set on the Builder.

Scenario 11: Return Value is Same Builder Instance

Details:
  TestName: apiKeyReturnsSameBuilderInstance
  Description: This test explicitly verifies that the apiKey method returns the exact same Builder instance (reference equality) to support proper method chaining.
Execution:
  Arrange: Create a new Builder instance using Gemini.builder(). Prepare a valid API key string.
  Act: Invoke the apiKey method on the Builder instance and capture the returned value.
  Assert: Use reference equality (==) to verify that the returned Builder instance is the exact same object as the original Builder instance.
Validation:
  This assertion confirms that the method returns 'this' rather than creating a new Builder instance, which is essential for the builder pattern's fluent API design. This test ensures memory efficiency and proper builder pattern implementation, as creating new instances would break method chaining and waste resources.

Scenario 12: Setting API Key After Setting Model Name

Details:
  TestName: apiKeyAfterModelName
  Description: This test verifies that the order of method calls on the Builder does not affect the functionality, specifically testing setting the API key after setting the model name.
Execution:
  Arrange: Create a new Builder instance using Gemini.builder(). Prepare a valid model name string and a valid API key string.
  Act: Call modelName() first, then apiKey(), and finally build() on the Builder instance.
  Assert: Verify that the Gemini instance is created successfully. Verify that both the model name and API key are properly configured in the resulting instance.
Validation:
  This test validates that the Builder methods are order-independent, which is a key characteristic of well-designed builder patterns. This ensures developers can configure the Builder in any order that makes sense for their code organization without affecting the final result.

*/

// ********RoostGPT********

package com.google.adk.models;

import static com.google.common.truth.Truth.assertThat;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.mock;
import com.google.genai.Client;
import com.google.genai.types.HttpOptions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.*;
import static com.google.common.base.StandardSystemProperty.JAVA_VERSION;
import com.google.adk.Version;
import com.google.common.collect.ImmutableMap;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.genai.ResponseStream;
import com.google.genai.types.Candidate;
import com.google.genai.types.Content;
import com.google.genai.types.FinishReason;
import com.google.genai.types.GenerateContentConfig;
import com.google.genai.types.GenerateContentResponse;
import com.google.genai.types.LiveConnectConfig;
import com.google.genai.types.Part;
import io.reactivex.rxjava3.core.Flowable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

class BuilderApiKeyTest {

	private Gemini.Builder builder;

	@BeforeEach
	void setUp() {
		builder = Gemini.builder();
	}

	@Test
	@Tag("valid")
	void apiKeyWithValidNonNullString() {
		String validApiKey = "test-api-key-12345";

		Gemini.Builder returnedBuilder = builder.apiKey(validApiKey);

		assertThat(returnedBuilder).isSameInstanceAs(builder);
		Gemini gemini = builder.modelName("gemini-pro").build();
		assertNotNull(gemini);
	}

	@Test
	@Tag("invalid")
	void apiKeyWithNullValue() {
		Gemini.Builder returnedBuilder = builder.apiKey(null);

		assertThat(returnedBuilder).isSameInstanceAs(builder);
		assertThat(returnedBuilder).isNotNull();
	}

	@Test
	@Tag("boundary")
	void apiKeyWithEmptyString() {
		String emptyApiKey = "";

		Gemini.Builder returnedBuilder = builder.apiKey(emptyApiKey);

		assertThat(returnedBuilder).isSameInstanceAs(builder);
		assertNotNull(returnedBuilder);
	}

	@Test
	@Tag("boundary")
	void apiKeyWithWhitespaceOnlyString() {
		String whitespaceApiKey = "   \t\n";

		Gemini.Builder returnedBuilder = builder.apiKey(whitespaceApiKey);

		assertThat(returnedBuilder).isSameInstanceAs(builder);
		assertNotNull(returnedBuilder);
	}

	@Test
	@Tag("valid")
	void apiKeyMethodChainingWithOtherBuilderMethods() {
		String validApiKey = "test-api-key-12345";
		String validModelName = "gemini-pro";

		Gemini gemini = builder.modelName(validModelName).apiKey(validApiKey).build();

		assertNotNull(gemini);
		assertThat(gemini.model()).isEqualTo(validModelName);
	}

	@Test
	@Tag("valid")
	void apiKeyOverwritingPreviousValue() {
		String firstApiKey = "first-api-key";
		String secondApiKey = "second-api-key";

		builder.apiKey(firstApiKey);
		builder.apiKey(secondApiKey);
		Gemini gemini = builder.modelName("gemini-pro").build();

		assertNotNull(gemini);
	}

	@Test
	@Tag("boundary")
	void apiKeyWithVeryLongString() {
		StringBuilder longApiKey = new StringBuilder();
		for (int i = 0; i < 10000; i++) {
			longApiKey.append("a");
		}

		Gemini.Builder returnedBuilder = builder.apiKey(longApiKey.toString());

		assertThat(returnedBuilder).isSameInstanceAs(builder);
		assertNotNull(returnedBuilder);
	}

	@Test
    @Tag("valid")
    void apiKeyWithSpecialCharacters() {
        String specialCharApiKey = "api-key-!@#$%^&*()_+-=[]{}|;:',.<>?/~"";

        Gemini.Builder returnedBuilder = builder.apiKey(specialCharApiKey);

        assertThat(returnedBuilder).isSameInstanceAs(builder);
        assertNotNull(returnedBuilder);
    }

	@Test
	@Tag("valid")
	void apiKeyTakesPrecedenceOverVertexCredentials() {
		// NOTE: VertexCredentials.Builder does not have project() and location() methods.
		// Based on the provided information, these methods return Optional values but are
		// not setters.
		// The builder pattern for VertexCredentials needs to be verified in the actual
		// implementation.
		// This test may need adjustment based on the actual VertexCredentials.Builder
		// API.
		String validApiKey = "test-api-key-12345";
		VertexCredentials vertexCredentials = VertexCredentials.builder().build();

		Gemini gemini = builder.modelName("gemini-pro")
			.apiKey(validApiKey)
			.vertexCredentials(vertexCredentials)
			.build();

		assertNotNull(gemini);
	}

	@Test
	@Tag("valid")
	void apiKeyDoesNotOverrideExplicitApiClient() {
		String validApiKey = "test-api-key-12345";
		Client mockClient = Client.builder().httpOptions(HttpOptions.builder().build()).build();

		Gemini gemini = builder.modelName("gemini-pro").apiClient(mockClient).apiKey(validApiKey).build();

		assertNotNull(gemini);
	}

	@Test
	@Tag("valid")
	void apiKeyReturnsSameBuilderInstance() {
		String validApiKey = "test-api-key-12345";

		Gemini.Builder returnedBuilder = builder.apiKey(validApiKey);

		assertThat(returnedBuilder == builder).isTrue();
	}

	@Test
	@Tag("valid")
	void apiKeyAfterModelName() {
		String validModelName = "gemini-pro";
		String validApiKey = "test-api-key-12345";

		Gemini gemini = builder.modelName(validModelName).apiKey(validApiKey).build();

		assertNotNull(gemini);
		assertThat(gemini.model()).isEqualTo(validModelName);
	}

	@Test
	@Tag("valid")
	void apiKeyWithUnicodeCharacters() {
		String unicodeApiKey = "api-key-测试-🔑-αβγ";

		Gemini.Builder returnedBuilder = builder.apiKey(unicodeApiKey);

		assertThat(returnedBuilder).isSameInstanceAs(builder);
		assertNotNull(returnedBuilder);
	}

	@Test
	@Tag("valid")
	void apiKeyMultipleChainedCalls() {
		String apiKey1 = "first-key";
		String apiKey2 = "second-key";
		String apiKey3 = "third-key";

		Gemini.Builder returnedBuilder = builder.apiKey(apiKey1).apiKey(apiKey2).apiKey(apiKey3);

		assertThat(returnedBuilder).isSameInstanceAs(builder);
		Gemini gemini = builder.modelName("gemini-pro").build();
		assertNotNull(gemini);
	}

	@Test
	@Tag("valid")
	void apiKeyWithNumericString() {
		String numericApiKey = "1234567890";

		Gemini.Builder returnedBuilder = builder.apiKey(numericApiKey);

		assertThat(returnedBuilder).isSameInstanceAs(builder);
		assertNotNull(returnedBuilder);
	}

	@Test
	@Tag("valid")
	void apiKeyWithMixedCaseString() {
		String mixedCaseApiKey = "TeSt-ApI-KeY-123";

		Gemini.Builder returnedBuilder = builder.apiKey(mixedCaseApiKey);

		assertThat(returnedBuilder).isSameInstanceAs(builder);
		assertNotNull(returnedBuilder);
	}

	@Test
	@Tag("valid")
	void apiKeyBeforeAndAfterOtherMethods() {
		String validApiKey = "test-api-key";
		String validModelName = "gemini-pro";

		Gemini gemini = builder.apiKey(validApiKey).modelName(validModelName).apiKey(validApiKey).build();

		assertNotNull(gemini);
	}

	@Test
	@Tag("boundary")
	void apiKeyWithSingleCharacter() {
		String singleCharApiKey = "a";

		Gemini.Builder returnedBuilder = builder.apiKey(singleCharApiKey);

		assertThat(returnedBuilder).isSameInstanceAs(builder);
		assertNotNull(returnedBuilder);
	}

	@Test
	@Tag("valid")
	void apiKeyWithHyphenatedString() {
		String hyphenatedApiKey = "test-api-key-with-many-hyphens";

		Gemini.Builder returnedBuilder = builder.apiKey(hyphenatedApiKey);

		assertThat(returnedBuilder).isSameInstanceAs(builder);
		assertNotNull(returnedBuilder);
	}

	@Test
	@Tag("valid")
	void apiKeyWithUnderscoreString() {
		String underscoreApiKey = "test_api_key_with_underscores";

		Gemini.Builder returnedBuilder = builder.apiKey(underscoreApiKey);

		assertThat(returnedBuilder).isSameInstanceAs(builder);
		assertNotNull(returnedBuilder);
	}

}