/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-repo using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=customHeaders_a1e628bbb9
ROOST_METHOD_SIG_HASH=customHeaders_6d66c908fd

Scenario 1: Setting Custom Headers with Valid Non-Empty Map

Details:
  TestName: customHeadersWithValidNonEmptyMap
  Description: Verify that the customHeaders method correctly sets a non-empty map of custom headers and returns the Builder instance for method chaining.

Execution:
  Arrange: Create a new Builder instance using ApigeeLlm.builder(). Prepare a Map<String, String> containing multiple header key-value pairs such as "Authorization" -> "Bearer token123" and "X-Custom-Header" -> "customValue".
  Act: Invoke the customHeaders method on the Builder instance with the prepared map.
  Assert: Verify that the returned object is the same Builder instance (for method chaining). After calling build() with valid modelName and proxyUrl, verify that the HttpOptions contains the custom headers.

Validation:
  The assertion verifies that the Builder correctly stores the custom headers map and returns itself for fluent API chaining. This is significant because custom headers are essential for authentication, tracing, and other API-specific requirements when communicating through an Apigee proxy.

---

Scenario 2: Setting Custom Headers with Empty Map

Details:
  TestName: customHeadersWithEmptyMap
  Description: Verify that the customHeaders method accepts an empty map without throwing an exception and properly stores it.

Execution:
  Arrange: Create a new Builder instance using ApigeeLlm.builder(). Prepare an empty HashMap<String, String>.
  Act: Invoke the customHeaders method on the Builder instance with the empty map.
  Assert: Verify that the returned object is the same Builder instance. The method should complete without throwing any exception.

Validation:
  The assertion confirms that the method handles empty maps gracefully. This is important because users may want to explicitly clear or reset custom headers, and the system should not fail when no custom headers are needed.

---

Scenario 3: Setting Custom Headers with Null Value

Details:
  TestName: customHeadersWithNullMap
  Description: Verify the behavior of the customHeaders method when a null map is passed as the parameter.

Execution:
  Arrange: Create a new Builder instance using ApigeeLlm.builder().
  Act: Invoke the customHeaders method on the Builder instance with null as the parameter.
  Assert: Verify that the returned object is the same Builder instance. Note that when build() is called, the constructor handles null customHeaders by checking if customHeaders != null before adding them to httpOptionsBuilder.

Validation:
  The assertion verifies that the method accepts null without immediate failure. The constructor logic shows that null customHeaders are handled safely (the if condition checks for null). This test ensures defensive programming practices are in place.

---

Scenario 4: Method Chaining with customHeaders

Details:
  TestName: customHeadersSupportsMethodChaining
  Description: Verify that the customHeaders method returns the Builder instance to support fluent method chaining with other builder methods like modelName and proxyUrl.

Execution:
  Arrange: Prepare a Map<String, String> with custom headers.
  Act: Chain multiple builder methods together: ApigeeLlm.builder().modelName("apigee/gemini-2.5-flash").proxyUrl("https://proxy.example.com").customHeaders(customHeadersMap).
  Assert: Verify that the chain completes successfully and returns a Builder instance that can be used to call build().

Validation:
  The assertion confirms that the Builder pattern is correctly implemented, allowing users to configure all options in a single fluent chain. This is essential for clean, readable code when constructing ApigeeLlm instances.

---

Scenario 5: Overwriting Previously Set Custom Headers

Details:
  TestName: customHeadersOverwritesPreviousHeaders
  Description: Verify that calling customHeaders multiple times overwrites the previously set headers rather than merging them.

Execution:
  Arrange: Create a Builder instance. Prepare two different maps: firstMap with "Header1" -> "Value1" and secondMap with "Header2" -> "Value2".
  Act: Call customHeaders(firstMap) followed by customHeaders(secondMap) on the same Builder instance.
  Assert: Verify that after the second call, only the headers from secondMap are retained (the field is directly assigned, not merged).

Validation:
  The assertion verifies the assignment behavior of the customHeaders method. Since the implementation uses direct assignment (this.customHeaders = customHeaders), subsequent calls will replace rather than merge. This is important for users to understand when configuring headers.

---

Scenario 6: Custom Headers with Special Characters in Values

Details:
  TestName: customHeadersWithSpecialCharactersInValues
  Description: Verify that the customHeaders method correctly handles header values containing special characters such as colons, semicolons, and spaces.

Execution:
  Arrange: Create a Builder instance. Prepare a Map<String, String> with headers containing special characters, e.g., "Content-Type" -> "application/json; charset=utf-8" and "X-Request-ID" -> "req:123:456".
  Act: Invoke the customHeaders method with the prepared map.
  Assert: Verify that the method returns the Builder instance and accepts the headers without modification or exception.

Validation:
  The assertion confirms that the method does not perform any validation or transformation on header values, allowing standard HTTP header formats. This is crucial for real-world scenarios where headers often contain complex values.

---

Scenario 7: Custom Headers Integration with Build Process

Details:
  TestName: customHeadersIntegratedInBuildProcess
  Description: Verify that custom headers set via the customHeaders method are properly integrated into the HttpOptions when the build() method is called.

Execution:
  Arrange: Create a Builder instance. Set modelName to "apigee/gemini-2.5-flash", proxyUrl to "https://proxy.example.com", and customHeaders to a map containing "X-API-Key" -> "test-key".
  Act: Call build() to create the ApigeeLlm instance, then retrieve the HttpOptions using getHttpOptions().
  Assert: Verify that the HttpOptions headers contain both the TRACKING_HEADERS and the custom headers.

Validation:
  The assertion verifies the end-to-end integration of custom headers in the built ApigeeLlm instance. The constructor merges TRACKING_HEADERS with customHeaders using ImmutableMap.builder(), ensuring both are present in the final HTTP configuration.

---

Scenario 8: Custom Headers with Single Entry Map

Details:
  TestName: customHeadersWithSingleEntryMap
  Description: Verify that the customHeaders method correctly handles a map containing only a single header entry.

Execution:
  Arrange: Create a Builder instance. Prepare a Map<String, String> with a single entry: "Authorization" -> "Bearer token".
  Act: Invoke the customHeaders method with the single-entry map.
  Assert: Verify that the method returns the Builder instance and the single header is properly stored.

Validation:
  The assertion confirms that the method works correctly with minimal input. This is a common use case where only authentication headers need to be added to requests.

---

Scenario 9: Custom Headers Using ImmutableMap

Details:
  TestName: customHeadersWithImmutableMap
  Description: Verify that the customHeaders method accepts an ImmutableMap as input since ImmutableMap is imported and commonly used in the codebase.

Execution:
  Arrange: Create a Builder instance. Create an ImmutableMap<String, String> using ImmutableMap.of("X-Trace-Id", "trace123", "X-Span-Id", "span456").
  Act: Invoke the customHeaders method with the ImmutableMap.
  Assert: Verify that the method returns the Builder instance and accepts the ImmutableMap without exception.

Validation:
  The assertion confirms compatibility with ImmutableMap, which is used throughout the codebase (as seen in TRACKING_HEADERS). This ensures consistency in how maps are handled across the application.

---

Scenario 10: Custom Headers with Empty String Values

Details:
  TestName: customHeadersWithEmptyStringValues
  Description: Verify that the customHeaders method accepts headers with empty string values without throwing an exception.

Execution:
  Arrange: Create a Builder instance. Prepare a Map<String, String> with an entry containing an empty value: "X-Optional-Header" -> "".
  Act: Invoke the customHeaders method with the prepared map.
  Assert: Verify that the method returns the Builder instance and does not throw an exception.

Validation:
  The assertion confirms that the method does not validate header values for emptiness. While empty header values may not be meaningful in HTTP, the Builder should not restrict this at the configuration level.

*/

// ********RoostGPT********

package com.google.adk.models;

import static com.google.common.truth.Truth.assertThat;

import com.google.common.collect.ImmutableMap;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class BuilderCustomHeadersTest {

  private ApigeeLlm.Builder builder;

  @BeforeEach
  void setUp() {
    builder = ApigeeLlm.builder();
  }

  @Test
  @Tag("valid")
  void customHeadersWithValidNonEmptyMap() {
    // Arrange
    Map<String, String> customHeaders = new HashMap<>();
    customHeaders.put("Authorization", "Bearer token123");
    customHeaders.put("X-Custom-Header", "customValue");
    // Act
    ApigeeLlm.Builder result = builder.customHeaders(customHeaders);
    // Assert
    assertThat(result).isSameInstanceAs(builder);
  }

  @Test
  @Tag("valid")
  void customHeadersWithEmptyMap() {
    // Arrange
    Map<String, String> emptyHeaders = new HashMap<>();
    // Act
    ApigeeLlm.Builder result = builder.customHeaders(emptyHeaders);
    // Assert
    assertThat(result).isSameInstanceAs(builder);
  }

  @Test
  @Tag("boundary")
  void customHeadersWithNullMap() {
    // Arrange & Act
    ApigeeLlm.Builder result = builder.customHeaders(null);
    // Assert
    assertThat(result).isSameInstanceAs(builder);
  }

  @Test
  @Tag("valid")
  void customHeadersSupportsMethodChaining() {
    // Arrange
    Map<String, String> customHeaders = new HashMap<>();
    customHeaders.put("X-API-Key", "test-key");
    // Act
    ApigeeLlm.Builder chainedBuilder =
        ApigeeLlm.builder()
            .modelName("apigee/gemini-2.5-flash")
            .proxyUrl("https://proxy.example.com")
            .customHeaders(customHeaders);
    // Assert
    assertThat(chainedBuilder).isNotNull();
  }

  @Test
  @Tag("valid")
  void customHeadersOverwritesPreviousHeaders() {
    // Arrange
    Map<String, String> firstMap = new HashMap<>();
    firstMap.put("Header1", "Value1");
    Map<String, String> secondMap = new HashMap<>();
    secondMap.put("Header2", "Value2");
    // Act
    builder.customHeaders(firstMap);
    ApigeeLlm.Builder result = builder.customHeaders(secondMap);
    // Assert
    assertThat(result).isSameInstanceAs(builder);
  }

  @Test
  @Tag("valid")
  void customHeadersWithSpecialCharactersInValues() {
    // Arrange
    Map<String, String> customHeaders = new HashMap<>();
    customHeaders.put("Content-Type", "application/json; charset=utf-8");
    customHeaders.put("X-Request-ID", "req:123:456");
    // Act
    ApigeeLlm.Builder result = builder.customHeaders(customHeaders);
    // Assert
    assertThat(result).isSameInstanceAs(builder);
  }

  @Test
  @Tag("integration")
  void customHeadersIntegratedInBuildProcess() {
    // Arrange
    Map<String, String> customHeaders = new HashMap<>();
    customHeaders.put("X-API-Key", "test-key");
    // Act
    ApigeeLlm apigeeLlm =
        ApigeeLlm.builder()
            .modelName("apigee/gemini-2.5-flash")
            .proxyUrl("https://proxy.example.com")
            .customHeaders(customHeaders)
            .build();
    // Assert
    assertThat(apigeeLlm).isNotNull();
    assertThat(apigeeLlm.getHttpOptions()).isNotNull();
    assertThat(apigeeLlm.getHttpOptions().headers()).isPresent();
    assertThat(apigeeLlm.getHttpOptions().headers().get().get("X-API-Key")).isEqualTo("test-key");
  }

  @Test
  @Tag("valid")
  void customHeadersWithSingleEntryMap() {
    // Arrange
    Map<String, String> singleEntryMap = new HashMap<>();
    singleEntryMap.put("Authorization", "Bearer token");
    // Act
    ApigeeLlm.Builder result = builder.customHeaders(singleEntryMap);
    // Assert
    assertThat(result).isSameInstanceAs(builder);
  }

  @Test
  @Tag("valid")
  void customHeadersWithImmutableMap() {
    // Arrange
    ImmutableMap<String, String> immutableHeaders =
        ImmutableMap.of("X-Trace-Id", "trace123", "X-Span-Id", "span456");
    // Act
    ApigeeLlm.Builder result = builder.customHeaders(immutableHeaders);
    // Assert
    assertThat(result).isSameInstanceAs(builder);
  }

  @Test
  @Tag("boundary")
  void customHeadersWithEmptyStringValues() {
    // Arrange
    Map<String, String> headersWithEmptyValue = new HashMap<>();
    headersWithEmptyValue.put("X-Optional-Header", "");
    // Act
    ApigeeLlm.Builder result = builder.customHeaders(headersWithEmptyValue);
    // Assert
    assertThat(result).isSameInstanceAs(builder);
  }

  @Test
  @Tag("integration")
  void customHeadersPreservedAfterBuild() {
    // Arrange
    Map<String, String> customHeaders = new HashMap<>();
    customHeaders.put("X-Custom-Auth", "custom-auth-value");
    customHeaders.put("X-Request-Source", "test-source");
    // Act
    ApigeeLlm apigeeLlm =
        ApigeeLlm.builder()
            .modelName("apigee/vertex_ai/v1/gemini-pro")
            .proxyUrl("https://api-proxy.example.com")
            .customHeaders(customHeaders)
            .build();
    // Assert
    assertThat(apigeeLlm).isNotNull();
    assertThat(apigeeLlm.getHttpOptions()).isNotNull();
    // headers() returns Optional<Map<String, String>>, need to call get() to unwrap
    assertThat(apigeeLlm.getHttpOptions().headers()).isPresent();
    Map<String, String> resultHeaders = apigeeLlm.getHttpOptions().headers().get();
    assertThat(resultHeaders).isNotNull();
    assertThat(resultHeaders.get("X-Custom-Auth")).isEqualTo("custom-auth-value");
    assertThat(resultHeaders.get("X-Request-Source")).isEqualTo("test-source");
  }

  @Test
  @Tag("valid")
  void customHeadersReturnsSameBuilderForFluentApi() {
    // Arrange
    Map<String, String> headers1 = ImmutableMap.of("Header1", "Value1");
    Map<String, String> headers2 = ImmutableMap.of("Header2", "Value2");
    // Act
    ApigeeLlm.Builder builder1 = ApigeeLlm.builder();
    ApigeeLlm.Builder result1 = builder1.customHeaders(headers1);
    ApigeeLlm.Builder result2 = result1.customHeaders(headers2);
    // Assert
    assertThat(result1).isSameInstanceAs(builder1);
    assertThat(result2).isSameInstanceAs(builder1);
  }

  @Test
  @Tag("valid")
  void customHeadersWithLargeMap() {
    // Arrange
    Map<String, String> largeHeaders = new HashMap<>();
    for (int i = 0; i < 50; i++) {
      largeHeaders.put("X-Header-" + i, "Value-" + i);
    }
    // Act
    ApigeeLlm.Builder result = builder.customHeaders(largeHeaders);
    // Assert
    assertThat(result).isSameInstanceAs(builder);
  }

  @Test
  @Tag("valid")
  void customHeadersWithUnicodeValues() {
    // Arrange
    Map<String, String> unicodeHeaders = new HashMap<>();
    unicodeHeaders.put("X-Unicode-Header", "值中文");
    unicodeHeaders.put("X-Emoji-Header", "🚀");
    // Act
    ApigeeLlm.Builder result = builder.customHeaders(unicodeHeaders);
    // Assert
    assertThat(result).isSameInstanceAs(builder);
  }
}
