/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-dec-16-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=vertexCredentials_05534933e8
ROOST_METHOD_SIG_HASH=vertexCredentials_ad6dd8135d

Scenario 1: Set Valid VertexCredentials

Details:
  TestName: vertexCredentialsWithValidCredentials
  Description: This test verifies that the vertexCredentials method correctly sets a valid VertexCredentials object in the Builder and returns the Builder instance for method chaining. It ensures that the builder pattern works as expected when a non-null VertexCredentials object is provided.
Execution:
  Arrange: Create a mock or valid VertexCredentials object. Instantiate a new Builder instance using Gemini.builder().
  Act: Invoke the vertexCredentials method on the Builder instance, passing the created VertexCredentials object.
  Assert: Verify that the method returns the same Builder instance (for method chaining). Verify that when build() is subsequently called with a valid modelName, the Gemini instance is created successfully without throwing exceptions.
Validation:
  The assertion verifies that the Builder correctly stores the VertexCredentials and returns itself for fluent API usage. This is significant because it ensures the builder pattern is properly implemented, allowing developers to chain multiple configuration methods. The test confirms that valid credentials can be set and used to construct a Gemini instance, which is essential for Vertex AI authentication scenarios.

Scenario 2: Set Null VertexCredentials

Details:
  TestName: vertexCredentialsWithNullCredentials
  Description: This test checks the behavior when null is passed to the vertexCredentials method. It verifies that the Builder accepts null values without throwing an exception during the setter call, though the build() method may handle null differently.
Execution:
  Arrange: Instantiate a new Builder instance using Gemini.builder(). Set a valid modelName on the builder.
  Act: Invoke the vertexCredentials method with null as the parameter.
  Assert: Verify that the method returns the Builder instance without throwing a NullPointerException. Verify that calling build() after setting null vertexCredentials creates a Gemini instance with a default client (since null credentials should be handled gracefully in the build method).
Validation:
  This assertion verifies that the setter method itself is null-safe and doesn't immediately fail when null is provided. This is important for builder flexibility, as developers might want to conditionally set credentials. The test ensures that the builder can handle scenarios where credentials are not provided, falling back to default client construction behavior.

Scenario 3: Method Chaining with VertexCredentials

Details:
  TestName: vertexCredentialsReturnsBuilderForChaining
  Description: This test validates that the vertexCredentials method returns the Builder instance, enabling fluent method chaining with other builder methods like modelName, apiKey, or apiClient.
Execution:
  Arrange: Create a valid VertexCredentials object. Instantiate a new Builder instance.
  Act: Chain multiple builder methods together: builder.modelName("gemini-2.0-flash").vertexCredentials(vertexCredentials).
  Assert: Verify that the chaining executes without errors. Verify that the final build() call produces a valid Gemini instance with the correct modelName and credentials configured.
Validation:
  This test confirms that the builder pattern's fluent interface works correctly, allowing developers to configure multiple properties in a single statement. This is crucial for code readability and usability, as it's a common pattern in modern Java APIs. The test ensures that the vertexCredentials method integrates seamlessly with other builder methods.

Scenario 4: VertexCredentials Takes Precedence Over Nothing

Details:
  TestName: vertexCredentialsUsedWhenNoOtherCredentialsSet
  Description: This test verifies that when only vertexCredentials is set (without apiKey or apiClient), the built Gemini instance uses the VertexCredentials for authentication.
Execution:
  Arrange: Create a valid VertexCredentials object with specific project and location values. Create a Builder instance and set only modelName and vertexCredentials.
  Act: Call build() on the builder to create a Gemini instance.
  Assert: Verify that the Gemini instance is created successfully. Verify that the internal apiClient is configured with the Vertex AI settings (this may require reflection or package-private access for thorough validation, or simply verify no exceptions are thrown).
Validation:
  This assertion validates that vertexCredentials is properly used when it's the only authentication mechanism provided. This is essential for Vertex AI use cases where developers want to use service account credentials or other Vertex-specific authentication. The test ensures the builder correctly prioritizes vertexCredentials when no other authentication methods are specified.

Scenario 5: ApiKey Takes Precedence Over VertexCredentials

Details:
  TestName: apiKeyTakesPrecedenceOverVertexCredentials
  Description: This test verifies the precedence order documented in the Builder class, ensuring that when both apiKey and vertexCredentials are set, the apiKey is used for client construction.
Execution:
  Arrange: Create a valid VertexCredentials object and a valid API key string. Create a Builder instance and set modelName, apiKey, and vertexCredentials.
  Act: Call build() on the builder to create a Gemini instance.
  Assert: Verify that the Gemini instance is created successfully. Verify that the instance uses the API key authentication method rather than Vertex credentials (the constructor with apiKey should be invoked).
Validation:
  This test confirms the documented precedence behavior where apiKey takes priority over vertexCredentials. This is important for developers who might set multiple authentication methods and need to understand which one will be used. The test ensures predictable behavior when multiple credential types are configured.

Scenario 6: ApiClient Takes Precedence Over VertexCredentials

Details:
  TestName: apiClientTakesPrecedenceOverVertexCredentials
  Description: This test validates that when both an explicit apiClient and vertexCredentials are set, the explicit apiClient is used, as documented in the Builder class.
Execution:
  Arrange: Create a mock or valid Client instance. Create a valid VertexCredentials object. Create a Builder instance and set modelName, apiClient, and vertexCredentials.
  Act: Call build() on the builder to create a Gemini instance.
  Assert: Verify that the Gemini instance is created successfully. Verify that the Gemini instance uses the explicitly provided apiClient rather than constructing one from vertexCredentials.
Validation:
  This assertion verifies the highest precedence in the authentication hierarchy: explicit apiClient overrides all other authentication methods. This is critical for advanced use cases where developers need full control over the Client configuration. The test ensures that when an explicit client is provided, it's always used regardless of other credential settings.

Scenario 7: Multiple Calls to VertexCredentials

Details:
  TestName: vertexCredentialsOverwritesPreviousValue
  Description: This test checks that calling vertexCredentials multiple times on the same Builder instance results in the last value being used, following standard builder pattern behavior.
Execution:
  Arrange: Create two different VertexCredentials objects (credentials1 and credentials2). Create a Builder instance and set a valid modelName.
  Act: Call vertexCredentials(credentials1) followed by vertexCredentials(credentials2) on the same builder instance. Then call build().
  Assert: Verify that the Gemini instance is created successfully. Verify that the instance uses credentials2 (the last set value) rather than credentials1.
Validation:
  This test confirms that the builder follows the standard pattern where subsequent calls to the same setter method overwrite previous values. This is important for builder usability, as developers might conditionally set values and expect the last call to take effect. The test ensures predictable behavior when the same configuration method is called multiple times.

Scenario 8: VertexCredentials with Empty Optional Values

Details:
  TestName: vertexCredentialsWithEmptyOptionals
  Description: This test verifies that the Builder correctly handles VertexCredentials objects where the Optional fields (project, location, credentials) are empty.
Execution:
  Arrange: Create a VertexCredentials object with empty Optional values for project, location, and credentials. Create a Builder instance and set modelName and the vertexCredentials.
  Act: Call build() on the builder to create a Gemini instance.
  Assert: Verify that the Gemini instance is created successfully without throwing exceptions. Verify that the apiClient is constructed with default settings when no optional values are present.
Validation:
  This assertion validates that the Builder gracefully handles VertexCredentials with empty Optional fields, which is a valid scenario. This is important because not all Vertex AI configurations require explicit project, location, or credentials (they might be inferred from environment). The test ensures robustness when dealing with minimal credential configurations.

Scenario 9: VertexCredentials with All Optional Values Present

Details:
  TestName: vertexCredentialsWithAllOptionalsPresent
  Description: This test verifies that when VertexCredentials contains all Optional values (project, location, credentials), the Builder correctly applies all of them to the apiClient configuration.
Execution:
  Arrange: Create a VertexCredentials object with non-empty Optional values for project, location, and credentials. Create a Builder instance and set modelName and vertexCredentials.
  Act: Call build() on the builder to create a Gemini instance.
  Assert: Verify that the Gemini instance is created successfully. Verify that the apiClient is configured with all the provided values from VertexCredentials (may require reflection or integration testing to fully validate).
Validation:
  This test confirms that the Builder properly extracts and applies all configuration values from a fully-populated VertexCredentials object. This is essential for complete Vertex AI configurations where project, location, and specific credentials are all required. The test ensures that no configuration data is lost during the building process.

Scenario 10: VertexCredentials Integration with ModelName

Details:
  TestName: vertexCredentialsWithModelName
  Description: This test validates that vertexCredentials works correctly in conjunction with the modelName method, ensuring both configurations are properly applied to the final Gemini instance.
Execution:
  Arrange: Create a valid VertexCredentials object. Create a Builder instance. Set a specific modelName (e.g., "gemini-2.0-flash") and the vertexCredentials.
  Act: Call build() to create a Gemini instance.
  Assert: Verify that the Gemini instance is created successfully. Verify that the instance has the correct modelName and uses the provided vertexCredentials for authentication.
Validation:
  This assertion ensures that vertexCredentials and modelName configurations don't interfere with each other and both are correctly applied to the Gemini instance. This is important because these are the two essential configurations for creating a functional Gemini client with Vertex AI. The test validates the integration of multiple builder methods.

Scenario 11: VertexCredentials Return Value Verification

Details:
  TestName: vertexCredentialsReturnsSameBuilderInstance
  Description: This test explicitly verifies that the vertexCredentials method returns the exact same Builder instance (not a new one), which is essential for proper builder pattern implementation.
Execution:
  Arrange: Create a valid VertexCredentials object. Create a Builder instance and store a reference to it.
  Act: Call vertexCredentials on the builder and store the returned value.
  Assert: Use assertSame or reference equality check to verify that the returned Builder is the exact same instance as the original builder.
Validation:
  This test confirms that the builder pattern is correctly implemented by returning 'this' rather than creating a new Builder instance. This is crucial for performance and proper method chaining behavior. The test ensures that the builder maintains its identity throughout the configuration process, which is a fundamental requirement of the builder pattern.

*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.auth.oauth2.GoogleCredentials;
import com.google.genai.Client;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

class BuilderVertexCredentialsTest {

	@Mock
	private GoogleCredentials mockGoogleCredentials;

	@Mock
	private Client mockClient;

	private Gemini.Builder builder;

	@BeforeEach
	void setUp() {
		MockitoAnnotations.openMocks(this);
		builder = Gemini.builder();
	}

	@Test
	@Tag("valid")
	void vertexCredentialsWithValidCredentials() {
		// Arrange
		VertexCredentials validCredentials = VertexCredentials.builder()
			.project("test-project")
			.location("us-central1")
			.credentials(mockGoogleCredentials)
			.build();
		// Act
		Gemini.Builder result = builder.vertexCredentials(validCredentials);
		// Assert
		assertNotNull(result);
		assertSame(builder, result);

		// Verify build works with valid modelName
		assertDoesNotThrow(() -> {
			Gemini gemini = result.modelName("gemini-2.0-flash").build();
			assertNotNull(gemini);
		});
	}

	@Test
	@Tag("valid")
	void vertexCredentialsWithNullCredentials() {
		// Arrange
		builder.modelName("gemini-2.0-flash");
		// Act
		Gemini.Builder result = builder.vertexCredentials(null);
		// Assert
		assertNotNull(result);
		assertSame(builder, result);

		// Verify build creates instance with default client
		assertDoesNotThrow(() -> {
			Gemini gemini = result.build();
			assertNotNull(gemini);
		});
	}

	@Test
	@Tag("valid")
	void vertexCredentialsReturnsBuilderForChaining() {
		// Arrange
		VertexCredentials validCredentials = VertexCredentials.builder()
			.project("test-project")
			.location("us-central1")
			.build();
		// Act & Assert
		assertDoesNotThrow(() -> {
			Gemini gemini = builder.modelName("gemini-2.0-flash").vertexCredentials(validCredentials).build();

			assertNotNull(gemini);
			assertEquals("gemini-2.0-flash", gemini.model());
		});
	}

	@Test
	@Tag("valid")
	void vertexCredentialsUsedWhenNoOtherCredentialsSet() {
		// Arrange
		VertexCredentials validCredentials = VertexCredentials.builder()
			.project("test-project")
			.location("us-central1")
			.credentials(mockGoogleCredentials)
			.build();
		// Act
		Gemini gemini = builder.modelName("gemini-2.0-flash").vertexCredentials(validCredentials).build();
		// Assert
		assertNotNull(gemini);
		assertEquals("gemini-2.0-flash", gemini.model());
	}

	@Test
	@Tag("valid")
	void apiKeyTakesPrecedenceOverVertexCredentials() {
		// Arrange
		VertexCredentials validCredentials = VertexCredentials.builder()
			.project("test-project")
			.location("us-central1")
			.build();
		String apiKey = "test-api-key-12345";
		// Act
		Gemini gemini = builder.modelName("gemini-2.0-flash")
			.apiKey(apiKey)
			.vertexCredentials(validCredentials)
			.build();
		// Assert
		assertNotNull(gemini);
		assertEquals("gemini-2.0-flash", gemini.model());
	}

	@Test
	@Tag("valid")
	void apiClientTakesPrecedenceOverVertexCredentials() {
		// Arrange
		VertexCredentials validCredentials = VertexCredentials.builder()
			.project("test-project")
			.location("us-central1")
			.build();
		// Act
		Gemini gemini = builder.modelName("gemini-2.0-flash")
			.apiClient(mockClient)
			.vertexCredentials(validCredentials)
			.build();
		// Assert
		assertNotNull(gemini);
		assertEquals("gemini-2.0-flash", gemini.model());
	}

	@Test
	@Tag("valid")
	void vertexCredentialsOverwritesPreviousValue() {
		// Arrange
		VertexCredentials credentials1 = VertexCredentials.builder().project("project-1").location("us-west1").build();

		VertexCredentials credentials2 = VertexCredentials.builder().project("project-2").location("us-east1").build();
		// Act
		Gemini gemini = builder.modelName("gemini-2.0-flash")
			.vertexCredentials(credentials1)
			.vertexCredentials(credentials2)
			.build();
		// Assert
		assertNotNull(gemini);
		assertEquals("gemini-2.0-flash", gemini.model());
	}

	@Test
	@Tag("boundary")
	void vertexCredentialsWithEmptyOptionals() {
		// Arrange
		VertexCredentials emptyCredentials = VertexCredentials.builder().build();
		// Act
		Gemini gemini = builder.modelName("gemini-2.0-flash").vertexCredentials(emptyCredentials).build();
		// Assert
		assertNotNull(gemini);
		assertEquals("gemini-2.0-flash", gemini.model());
	}

	@Test
	@Tag("valid")
	void vertexCredentialsWithAllOptionalsPresent() {
		// Arrange
		VertexCredentials fullCredentials = VertexCredentials.builder()
			.project("full-project")
			.location("europe-west1")
			.credentials(mockGoogleCredentials)
			.build();
		// Act
		Gemini gemini = builder.modelName("gemini-2.0-flash").vertexCredentials(fullCredentials).build();
		// Assert
		assertNotNull(gemini);
		assertEquals("gemini-2.0-flash", gemini.model());

		// Verify all optionals are present
		assertTrue(fullCredentials.project().isPresent());
		assertTrue(fullCredentials.location().isPresent());
		assertTrue(fullCredentials.credentials().isPresent());
	}

	@Test
	@Tag("integration")
	void vertexCredentialsWithModelName() {
		// Arrange
		VertexCredentials validCredentials = VertexCredentials.builder()
			.project("integration-project")
			.location("asia-southeast1")
			.credentials(mockGoogleCredentials)
			.build();
		String modelName = "gemini-2.0-flash";
		// Act
		Gemini gemini = builder.modelName(modelName).vertexCredentials(validCredentials).build();
		// Assert
		assertNotNull(gemini);
		assertEquals(modelName, gemini.model());
	}

	@Test
	@Tag("valid")
	void vertexCredentialsReturnsSameBuilderInstance() {
		// Arrange
		VertexCredentials validCredentials = VertexCredentials.builder().project("test-project").build();
		Gemini.Builder originalBuilder = builder;
		// Act
		Gemini.Builder returnedBuilder = builder.vertexCredentials(validCredentials);
		// Assert
		assertSame(originalBuilder, returnedBuilder);
	}

	@Test
	@Tag("valid")
	void vertexCredentialsWithMinimalConfiguration() {
		// Arrange
		VertexCredentials minimalCredentials = VertexCredentials.builder().project("minimal-project").build();
		// Act
		Gemini.Builder result = builder.vertexCredentials(minimalCredentials);
		// Assert
		assertNotNull(result);
		assertSame(builder, result);
	}

	@Test
	@Tag("valid")
	void vertexCredentialsMultipleChainedCalls() {
		// Arrange
		VertexCredentials credentials = VertexCredentials.builder()
			.project("chained-project")
			.location("us-central1")
			.build();
		// Act
		Gemini.Builder result = builder.modelName("gemini-2.0-flash")
			.vertexCredentials(credentials)
			.modelName("gemini-pro");
		// Assert
		assertNotNull(result);
		assertSame(builder, result);

		Gemini gemini = result.build();
		assertNotNull(gemini);
		assertEquals("gemini-pro", gemini.model());
	}

	@Test
	@Tag("valid")
	void vertexCredentialsWithProjectOnly() {
		// Arrange
		VertexCredentials projectOnlyCredentials = VertexCredentials.builder().project("project-only").build();
		// Act
		Gemini gemini = builder.modelName("gemini-2.0-flash").vertexCredentials(projectOnlyCredentials).build();
		// Assert
		assertNotNull(gemini);
		assertTrue(projectOnlyCredentials.project().isPresent());
		assertEquals("project-only", projectOnlyCredentials.project().get());
	}

	@Test
	@Tag("valid")
	void vertexCredentialsWithLocationOnly() {
		// Arrange
		VertexCredentials locationOnlyCredentials = VertexCredentials.builder().location("location-only").build();
		// Act
		Gemini gemini = builder.modelName("gemini-2.0-flash").vertexCredentials(locationOnlyCredentials).build();
		// Assert
		assertNotNull(gemini);
		assertTrue(locationOnlyCredentials.location().isPresent());
		assertEquals("location-only", locationOnlyCredentials.location().get());
	}

	@Test
	@Tag("valid")
	void vertexCredentialsWithCredentialsOnly() {
		// Arrange
		VertexCredentials credentialsOnly = VertexCredentials.builder().credentials(mockGoogleCredentials).build();
		// Act
		Gemini gemini = builder.modelName("gemini-2.0-flash").vertexCredentials(credentialsOnly).build();
		// Assert
		assertNotNull(gemini);
		assertTrue(credentialsOnly.credentials().isPresent());
	}

	@Test
	@Tag("valid")
	void vertexCredentialsSetAfterApiKey() {
		// Arrange
		VertexCredentials credentials = VertexCredentials.builder().project("test-project").build();
		String apiKey = "test-api-key";
		// Act
		Gemini gemini = builder.modelName("gemini-2.0-flash").apiKey(apiKey).vertexCredentials(credentials).build();
		// Assert
		assertNotNull(gemini);
	}

	@Test
	@Tag("valid")
	void vertexCredentialsSetBeforeApiKey() {
		// Arrange
		VertexCredentials credentials = VertexCredentials.builder().project("test-project").build();
		String apiKey = "test-api-key";
		// Act
		Gemini gemini = builder.modelName("gemini-2.0-flash").vertexCredentials(credentials).apiKey(apiKey).build();
		// Assert
		assertNotNull(gemini);
	}

	@Test
	@Tag("valid")
	void vertexCredentialsBuilderReusability() {
		// Arrange
		VertexCredentials credentials = VertexCredentials.builder().project("reusable-project").build();
		// Act
		builder.modelName("gemini-2.0-flash").vertexCredentials(credentials);
		Gemini gemini1 = builder.build();

		Gemini.Builder newBuilder = Gemini.builder();
		newBuilder.modelName("gemini-pro").vertexCredentials(credentials);
		Gemini gemini2 = newBuilder.build();
		// Assert
		assertNotNull(gemini1);
		assertNotNull(gemini2);
		assertNotSame(gemini1, gemini2);
	}

}
