/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test maven-adkjava-github using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=close_4be23fe575
ROOST_METHOD_SIG_HASH=close_3eadcb718b

Scenario 1: Closing with a valid Throwable when connection is still open

Details:
  TestName: closeWithValidThrowableWhenOpen
  Description: This test verifies that when the close(Throwable) method is invoked with a non-null Throwable and the connection has not been previously closed, the connection will close properly, signal error on the response processor, and update the closed flag.
Execution:
  Arrange: Set up a GeminiLlmConnection instance. Mock or ensure that closed is false, sessionFuture's state as done or not as needed, and provide a valid Throwable (such as RuntimeException).
  Act: Call the close(Throwable) method with the non-null Throwable.
  Assert: Check that the closed flag is set to true, the responseProcessor received onError with the provided Throwable, and that sessionFuture is either cancelled or closed as per its state.
Validation:
  This assertion verifies that closing with a valid Throwable only works when the connection is not already closed. It ensures correct error propagation for downstream consumers and proper resource cleanup.

Scenario 2: Closing with a valid Throwable when connection is already closed

Details:
  TestName: closeWithValidThrowableWhenAlreadyClosed
  Description: This scenario validates that calling close(Throwable) after the connection is already closed (closed = true) does not affect the response processor again or re-close the session.
Execution:
  Arrange: Set up GeminiLlmConnection instance and simulate that closed is already true. Supply a non-null Throwable.
  Act: Call close(Throwable) method.
  Assert: Confirm that responseProcessor does not receive additional signals and sessionFuture is unaffected.
Validation:
  This ensures no duplicate events or side effects occur if close(Throwable) is invoked multiple times or after connection is already closed, maintaining proper resource and state management.

Scenario 3: Closing with null Throwable throws NullPointerException

Details:
  TestName: closeWithNullThrowableThrowsException
  Description: Tests that passing a null Throwable to the close(Throwable) method throws a NullPointerException as enforced by Objects.requireNonNull.
Execution:
  Arrange: Create a GeminiLlmConnection instance with suitable mocks and dependencies.
  Act: Call close(null).
  Assert: Expect NullPointerException to be thrown.
Validation:
  The validation confirms that null is an invalid input for close(Throwable) and the method fail-fast guards against invalid usage.

Scenario 4: Closing with a Throwable when sessionFuture is done

Details:
  TestName: closeWithThrowableWhenSessionFutureIsDone
  Description: When sessionFuture is already done, verify that close(Throwable) closes the session using sessionFuture.thenAccept and that responseProcessor signals the error.
Execution:
  Arrange: Mock sessionFuture to return isDone = true and provide a valid AsyncSession. Provide a valid Throwable.
  Act: Invoke close(Throwable).
  Assert: Check that sessionFuture.thenAccept is called to close the AsyncSession, responseProcessor signals onError, and closed flag is set.
Validation:
  This test validates proper logic when the session is established, confirming error propagation and correct session shutdown regardless of the error cause.

Scenario 5: Closing with a Throwable when sessionFuture is not done

Details:
  TestName: closeWithThrowableWhenSessionFutureNotDone
  Description: If the sessionFuture is not done, this scenario checks that close(Throwable) cancels sessionFuture and signals error through responseProcessor.
Execution:
  Arrange: Mock sessionFuture to return isDone = false. Provide a valid Throwable.
  Act: Call close(Throwable).
  Assert: Confirm that sessionFuture.cancel(false) is called, responseProcessor signals onError, and closed flag is true.
Validation:
  Verifies that the connection cleanup logic is correctly followed when the session is not yet established.

Scenario 6: Closing with a Throwable after previous close(null)

Details:
  TestName: closeWithThrowableAfterPreviousCloseNull
  Description: Ensures that if close(null) was previously called to close connection, subsequent close(Throwable) with any Throwable does not re-trigger error signals or repeat cleanup.
Execution:
  Arrange: Close GeminiLlmConnection with close(null), then attempt close(Throwable) with a non-null Throwable.
  Act: Execute close(null) then close(Throwable).
  Assert: Check that no further errors are signaled and that cleanup logic is not re-executed.
Validation:
  This scenario safeguards state consistency and idempotency of the close operation, preventing repeated resource cleanup or duplicate error notifications.

Scenario 7: Closing with a CompletionException as Throwable

Details:
  TestName: closeWithCompletionExceptionThrowable
  Description: Validate handling when the Throwable is of type CompletionException. Ensure that error signaling properly propagates the cause of the CompletionException.
Execution:
  Arrange: Provide a CompletionException with a specific cause. Set up GeminiLlmConnection accordingly.
  Act: Call close(Throwable) with a CompletionException.
  Assert: Confirm responseProcessor receives the inner cause as the error, not the wrapper CompletionException, closed flag is true, and session cleanup logic is executed.
Validation:
  This is significant for correct diagnostic propagation, ensuring consumers receive the true cause of error rather than just the wrapper exception.

Scenario 8: Closing with a Throwable while AsyncSession is null in sessionFuture

Details:
  TestName: closeWithThrowableWhenAsyncSessionIsNull
  Description: Checks handling of connection closure when sessionFuture is done but gives null for AsyncSession, ensuring error signaling and cleanup logic do not break.
Execution:
  Arrange: Mock sessionFuture to be done and return null on thenAccept for closing session. Provide a valid Throwable.
  Act: Call close(Throwable).
  Assert: ResponseProcessor signals onError, closed flag is true. No exceptions are thrown during session closing even though session is null.
Validation:
  Ensures resilience to edge cases where session is unexpectedly null, which may happen if connection failed or was never fully established.

Scenario 9: Closing with a Throwable does not signal completion

Details:
  TestName: closeWithThrowableDoesNotSignalCompletion
  Description: Verifies that when close(Throwable) is called, the response processor signals error and does not signal completion (onComplete), maintaining correct Rx event semantics for errors.
Execution:
  Arrange: Provide a GeminiLlmConnection, valid Throwable, and mock the responseProcessor.
  Act: Call close(Throwable).
  Assert: Confirm that onError is called on responseProcessor, but onComplete is not.
Validation:
  Important for Rx stream semantics: completion is not signaled in error paths, ensuring consumers handle the error as intended.

Scenario 10: Closing with a Throwable after error has already been signaled

Details:
  TestName: closeWithThrowableAfterErrorAlreadySignaled
  Description: This scenario checks that even if responseProcessor has already been terminated due to previous error, invoking close(Throwable) does not cause additional errors or improper emitter behavior.
Execution:
  Arrange: Set up GeminiLlmConnection where responseProcessor has already received an error. Provide another non-null Throwable.
  Act: Call close(Throwable).
  Assert: Confirm that no new errors are signaled after terminal event, and closed flag remains true.
Validation:
  The test verifies Rx contract is upheld: after a terminal event, no further signals are emitted, preserving downstream consumer reliability.

Scenario 11: Closing with a Throwable when responseProcessor is already completed

Details:
  TestName: closeWithThrowableWhenResponseProcessorCompleted
  Description: Ensures that calling close(Throwable) after responseProcessor has already been completed (onComplete called) does not emit error, maintaining correct Rx terminal state.
Execution:
  Arrange: Simulate responseProcessor as completed (onComplete already called). Provide a valid Throwable.
  Act: Call close(Throwable).
  Assert: Confirm no new error signals are emitted by responseProcessor, closed flag remains unchanged.
Validation:
  Proper Rx behavior is preserved, avoiding illegal sequence of Rx signals and maintaining correct closure semantics.

Scenario 12: Closing with a Throwable, checking logger interaction

Details:
  TestName: closeWithThrowableLogsDebugProperly
  Description: This test checks that logger.debug is called with the correct parameters when close(Throwable) is invoked, verifying that logging covers the error and closure event as per implementation.
Execution:
  Arrange: Provide a mock Logger and a valid Throwable. Instantiate GeminiLlmConnection as needed.
  Act: Invoke close(Throwable).
  Assert: Verify logger.debug is called with the appropriate closure message and Throwable.
Validation:
  Logging correctness ensures future diagnostic, monitoring, and production issue analysis are facilitated by capturing closure and error events.

Scenario 13: Closing with a Throwable in concurrent environment

Details:
  TestName: closeWithThrowableInConcurrentEnvironment
  Description: Validates thread safety by closing GeminiLlmConnection with a Throwable from multiple threads; only one closure should succeed, and others should have no effect.
Execution:
  Arrange: Instantiate GeminiLlmConnection and provide a valid Throwable. Simulate multiple threads calling close(Throwable) simultaneously.
  Act: Execute concurrent close(Throwable) calls.
  Assert: Only one thread should successfully change the closed flag and signal error, others see no effect or repeat signals.
Validation:
  Confirms AtomicBoolean is used correctly and close operation is thread-safe, avoiding duplicate or race-condition based signals and side effects.

Scenario 14: Closing with a Throwable does not interrupt sessionFuture if already completed

Details:
  TestName: closeWithThrowableSessionFutureAlreadyCompleted
  Description: Ensures that if sessionFuture is already completed and contains AsyncSession, it is closed but not interrupted, and the cleanup code behaves as expected.
Execution:
  Arrange: Mock sessionFuture to be isDone = true, with a completed AsyncSession. Provide a valid Throwable.
  Act: Call close(Throwable).
  Assert: Confirm sessionFuture.thenAccept is executed and session is closed gracefully without interruption, responseProcessor signals error.
Validation:
  Ensures graceful closure of ongoing session when error occurs after session establishment, protecting connections and resources.

Scenario 15: Closing with a Throwable cancels sessionFuture if not started

Details:
  TestName: closeWithThrowableCancelsUnstartedSessionFuture
  Description: If the sessionFuture has not begun or has not completed, verify that close(Throwable) cancels sessionFuture and signals error immediately.
Execution:
  Arrange: Mock sessionFuture as not done, not yet started. Provide a valid Throwable.
  Act: Invoke close(Throwable).
  Assert: sessionFuture.cancel(false) is called, responseProcessor signals error, closed flag is set.
Validation:
  Important to prevent resource leaks and lingering sessions, ensuring prompt cancellation and error notification when closing before session initiation.

*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.genai.AsyncSession;
import com.google.genai.Client;
import com.google.genai.types.LiveConnectConfig;
import io.reactivex.rxjava3.processors.PublishProcessor;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;
import java.util.concurrent.atomic.AtomicBoolean;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.mockito.Mockito;
import org.slf4j.Logger;

public class GeminiLlmConnectionClose214Test {

  // Helper method to instantiate GeminiLlmConnection with mocks
  private GeminiLlmConnection createGeminiLlmConnectionWithMocks(
      CompletableFuture<AsyncSession> sessionFuture,
      AtomicBoolean closed,
      PublishProcessor<LlmResponse> processor,
      Logger logger) {
    Client apiClient = mock(Client.class);
    LiveConnectConfig connectConfig = mock(LiveConnectConfig.class);
    GeminiLlmConnection connection =
        Mockito.mock(
            GeminiLlmConnection.class,
            Mockito.withSettings()
                .useConstructor(apiClient, "test-model", connectConfig)
                .defaultAnswer(Mockito.CALLS_REAL_METHODS));
    // Inject internal field mocks into the real object (for unit testing only)
    try {
      java.lang.reflect.Field field = GeminiLlmConnection.class.getDeclaredField("sessionFuture");
      field.setAccessible(true);
      field.set(connection, sessionFuture);
      java.lang.reflect.Field closedField = GeminiLlmConnection.class.getDeclaredField("closed");
      closedField.setAccessible(true);
      closedField.set(connection, closed);
      java.lang.reflect.Field processorField =
          GeminiLlmConnection.class.getDeclaredField("responseProcessor");
      processorField.setAccessible(true);
      processorField.set(connection, processor);
      java.lang.reflect.Field loggerField = GeminiLlmConnection.class.getDeclaredField("logger");
      loggerField.setAccessible(true);
      loggerField.set(connection, logger);
    } catch (Exception pEx) {
      throw new RuntimeException(pEx);
    }
    return connection;
  }

  @Test
  @Tag("valid")
  public void testCloseWithValidThrowableWhenOpen() {
    AtomicBoolean closed = new AtomicBoolean(false);
    CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
    when(sessionFuture.isDone()).thenReturn(true);
    AsyncSession session = mock(AsyncSession.class);
    PublishProcessor<LlmResponse> processor = mock(PublishProcessor.class);
    Logger logger = mock(Logger.class);
    GeminiLlmConnection connection =
        createGeminiLlmConnectionWithMocks(sessionFuture, closed, processor, logger);
    RuntimeException error = new RuntimeException("test error");
    ArgumentCaptor<Throwable> errCaptor = ArgumentCaptor.forClass(Throwable.class);
    // Stub thenAccept to close session and simulate
    when(sessionFuture.thenAccept(any())).thenReturn(null);
    connection.close(error);
    assertTrue(closed.get(), "Closed flag should be 'true' after close");
    verify(processor).onError(error);
    verify(logger).debug(anyString(), eq(error));
    verify(sessionFuture).thenAccept(any());
  }

  @Test
  @Tag("boundary")
  public void testCloseWithValidThrowableWhenAlreadyClosed() {
    AtomicBoolean closed = new AtomicBoolean(true);
    CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
    PublishProcessor<LlmResponse> processor = mock(PublishProcessor.class);
    Logger logger = mock(Logger.class);
    GeminiLlmConnection connection =
        createGeminiLlmConnectionWithMocks(sessionFuture, closed, processor, logger);
    RuntimeException error = new RuntimeException("test error");
    connection.close(error);
    assertTrue(closed.get(), "Closed flag should remain 'true'");
    verify(processor, never()).onError(any());
    verify(logger, never()).debug(anyString(), any());
    verify(sessionFuture, never()).thenAccept(any());
    verify(sessionFuture, never()).cancel(anyBoolean());
  }

  @Test
  @Tag("invalid")
  public void testCloseWithNullThrowableThrowsException() {
    AtomicBoolean closed = new AtomicBoolean(false);
    CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
    PublishProcessor<LlmResponse> processor = mock(PublishProcessor.class);
    Logger logger = mock(Logger.class);
    GeminiLlmConnection connection =
        createGeminiLlmConnectionWithMocks(sessionFuture, closed, processor, logger);
    assertThrows(NullPointerException.class, () -> connection.close(null));
  }

  @Test
  @Tag("valid")
  public void testCloseWithThrowableWhenSessionFutureIsDone() {
    AtomicBoolean closed = new AtomicBoolean(false);
    CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
    when(sessionFuture.isDone()).thenReturn(true);
    AsyncSession session = mock(AsyncSession.class);
    PublishProcessor<LlmResponse> processor = mock(PublishProcessor.class);
    Logger logger = mock(Logger.class);
    GeminiLlmConnection connection =
        createGeminiLlmConnectionWithMocks(sessionFuture, closed, processor, logger);
    RuntimeException error = new RuntimeException();
    when(sessionFuture.thenAccept(any())).thenReturn(null);
    connection.close(error);
    assertTrue(closed.get());
    verify(processor).onError(error);
    verify(logger).debug(anyString(), eq(error));
    verify(sessionFuture).thenAccept(any());
  }

  @Test
  @Tag("valid")
  public void testCloseWithThrowableWhenSessionFutureNotDone() {
    AtomicBoolean closed = new AtomicBoolean(false);
    CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
    when(sessionFuture.isDone()).thenReturn(false);
    PublishProcessor<LlmResponse> processor = mock(PublishProcessor.class);
    Logger logger = mock(Logger.class);
    GeminiLlmConnection connection =
        createGeminiLlmConnectionWithMocks(sessionFuture, closed, processor, logger);
    RuntimeException error = new RuntimeException();
    connection.close(error);
    assertTrue(closed.get());
    verify(processor).onError(error);
    verify(logger).debug(anyString(), eq(error));
    verify(sessionFuture).cancel(false);
    verify(sessionFuture, never()).thenAccept(any());
  }

  @Test
  @Tag("boundary")
  public void testCloseWithThrowableAfterPreviousCloseNull() {
    AtomicBoolean closed = new AtomicBoolean(false);
    CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
    PublishProcessor<LlmResponse> processor = mock(PublishProcessor.class);
    Logger logger = mock(Logger.class);
    GeminiLlmConnection connection =
        createGeminiLlmConnectionWithMocks(sessionFuture, closed, processor, logger);
    connection.close(new RuntimeException("first")); // should close
    connection.close(new RuntimeException("second")); // should not re-close
    assertTrue(closed.get());
    verify(processor, times(1)).onError(any());
    verify(logger, times(1)).debug(anyString(), any());
    verify(sessionFuture, atLeastOnce()).thenAccept(any());
  }

  @Test
  @Tag("boundary")
  public void testCloseWithCompletionExceptionThrowable() {
    AtomicBoolean closed = new AtomicBoolean(false);
    CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
    PublishProcessor<LlmResponse> processor = mock(PublishProcessor.class);
    Logger logger = mock(Logger.class);
    RuntimeException cause = new RuntimeException("completion cause");
    CompletionException completionException = new CompletionException(cause);
    GeminiLlmConnection connection =
        createGeminiLlmConnectionWithMocks(sessionFuture, closed, processor, logger);
    connection.close(completionException);
    assertTrue(closed.get());
    verify(processor).onError(completionException);
    verify(logger).debug(anyString(), eq(completionException));
  }

  @Test
  @Tag("boundary")
  public void testCloseWithThrowableWhenAsyncSessionIsNull() {
    AtomicBoolean closed = new AtomicBoolean(false);
    CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
    when(sessionFuture.isDone()).thenReturn(true);
    PublishProcessor<LlmResponse> processor = mock(PublishProcessor.class);
    Logger logger = mock(Logger.class);
    GeminiLlmConnection connection =
        createGeminiLlmConnectionWithMocks(sessionFuture, closed, processor, logger);
    RuntimeException error = new RuntimeException();
    when(sessionFuture.thenAccept(any()))
        .thenAnswer(
            i -> {
              ((java.util.function.Consumer<AsyncSession>) i.getArgument(0)).accept(null);
              return null;
            });
    connection.close(error);
    assertTrue(closed.get());
    verify(processor).onError(error);
    verify(logger).debug(anyString(), eq(error));
  }

  @Test
  @Tag("valid")
  public void testCloseWithThrowableDoesNotSignalCompletion() {
    AtomicBoolean closed = new AtomicBoolean(false);
    CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
    PublishProcessor<LlmResponse> processor = mock(PublishProcessor.class);
    Logger logger = mock(Logger.class);
    RuntimeException error = new RuntimeException();
    GeminiLlmConnection connection =
        createGeminiLlmConnectionWithMocks(sessionFuture, closed, processor, logger);
    connection.close(error);
    verify(processor, times(1)).onError(error);
    verify(processor, never()).onComplete();
  }

  @Test
  @Tag("boundary")
  public void testCloseWithThrowableAfterErrorAlreadySignaled() {
    AtomicBoolean closed = new AtomicBoolean(false);
    CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
    PublishProcessor<LlmResponse> processor = mock(PublishProcessor.class);
    Logger logger = mock(Logger.class);
    RuntimeException error1 = new RuntimeException("first");
    RuntimeException error2 = new RuntimeException("second");
    GeminiLlmConnection connection =
        createGeminiLlmConnectionWithMocks(sessionFuture, closed, processor, logger);
    connection.close(error1);
    connection.close(error2);
    assertTrue(closed.get());
    verify(processor, times(1)).onError(error1);
    verify(processor, never()).onError(error2);
  }

  @Test
  @Tag("boundary")
  public void testCloseWithThrowableWhenResponseProcessorCompleted() {
    AtomicBoolean closed = new AtomicBoolean(false);
    CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
    PublishProcessor<LlmResponse> processor = mock(PublishProcessor.class);
    Logger logger = mock(Logger.class);
    GeminiLlmConnection connection =
        createGeminiLlmConnectionWithMocks(sessionFuture, closed, processor, logger);
    // Simulate processor already completed
    doNothing().when(processor).onComplete();
    connection.close(new RuntimeException("completed"));
    connection.close(new RuntimeException("error after complete"));
    assertTrue(closed.get());
    verify(processor, times(1)).onError(any());
    verify(processor, atLeastOnce()).onComplete();
  }

  @Test
  @Tag("integration")
  public void testCloseWithThrowableLogsDebugProperly() {
    AtomicBoolean closed = new AtomicBoolean(false);
    CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
    PublishProcessor<LlmResponse> processor = mock(PublishProcessor.class);
    Logger logger = mock(Logger.class);
    GeminiLlmConnection connection =
        createGeminiLlmConnectionWithMocks(sessionFuture, closed, processor, logger);
    RuntimeException error = new RuntimeException();
    connection.close(error);
    verify(logger).debug(contains("Closing GeminiConnection."), eq(error));
  }

  @Test
  @Tag("boundary")
  public void testCloseWithThrowableInConcurrentEnvironment() throws InterruptedException {
    AtomicBoolean closed = new AtomicBoolean(false);
    CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
    PublishProcessor<LlmResponse> processor = mock(PublishProcessor.class);
    Logger logger = mock(Logger.class);
    GeminiLlmConnection connection =
        createGeminiLlmConnectionWithMocks(sessionFuture, closed, processor, logger);
    Throwable error = new RuntimeException();
    int threads = 5;
    Thread[] ts = new Thread[threads];
    for (int i = 0; i < threads; i++) {
      ts[i] =
          new Thread(
              () -> {
                connection.close(error);
              });
    }
    for (int i = 0; i < threads; i++) {
      ts[i].start();
    }
    for (int i = 0; i < threads; i++) {
      ts[i].join();
    }
    assertTrue(closed.get());
    // Only one onError and one logger debug should happen
    verify(processor, atMost(1)).onError(error);
    verify(logger, atMost(1)).debug(anyString(), eq(error));
  }

  @Test
  @Tag("boundary")
  public void testCloseWithThrowableSessionFutureAlreadyCompleted() {
    AtomicBoolean closed = new AtomicBoolean(false);
    CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
    when(sessionFuture.isDone()).thenReturn(true);
    AsyncSession session = mock(AsyncSession.class);
    PublishProcessor<LlmResponse> processor = mock(PublishProcessor.class);
    Logger logger = mock(Logger.class);
    GeminiLlmConnection connection =
        createGeminiLlmConnectionWithMocks(sessionFuture, closed, processor, logger);
    when(sessionFuture.thenAccept(any())).thenReturn(null);
    connection.close(new RuntimeException("error"));
    assertTrue(closed.get());
    verify(processor).onError(any());
    verify(logger).debug(anyString(), any());
    verify(sessionFuture).thenAccept(any());
    verify(sessionFuture, never()).cancel(anyBoolean());
  }

  @Test
  @Tag("boundary")
  public void testCloseWithThrowableCancelsUnstartedSessionFuture() {
    AtomicBoolean closed = new AtomicBoolean(false);
    CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
    when(sessionFuture.isDone()).thenReturn(false);
    PublishProcessor<LlmResponse> processor = mock(PublishProcessor.class);
    Logger logger = mock(Logger.class);
    GeminiLlmConnection connection =
        createGeminiLlmConnectionWithMocks(sessionFuture, closed, processor, logger);
    connection.close(new RuntimeException("error"));
    assertTrue(closed.get());
    verify(processor, times(1)).onError(any());
    verify(sessionFuture, times(1)).cancel(false);
    verify(sessionFuture, never()).thenAccept(any());
    verify(logger).debug(anyString(), any());
  }
}
