/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test maven-adkjava-github using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=ensureModelResponse_58ec2cf7ec
ROOST_METHOD_SIG_HASH=ensureModelResponse_dbd125c9c0

Scenario 1: Handles an empty contents list

Details:
  TestName: handlesEmptyContentsList
  Description: This test verifies that when an empty contents list is provided to the ensureModelResponse method, it appends a "user" Content containing the standard CONTINUE_OUTPUT_MESSAGE and returns a list containing only that content.
Execution:
  Arrange: Prepare an empty ImmutableList<Content>.
  Act: Call ensureModelResponse with the empty list as input.
  Assert: Use JUnit assertions to check that the returned list contains exactly one Content, with role "user" and parts containing the CONTINUE_OUTPUT_MESSAGE.
Validation:
  This assertion confirms that the method properly handles an empty input list by prompting the model to produce a response, ensuring prompt behavior consistency.


Scenario 2: Last content is from the user

Details:
  TestName: preservesUserAsLastContent
  Description: This test checks that if the last Content in the list has the role "user" (case-insensitive), the returned list remains unchanged and no extra Content is appended.
Execution:
  Arrange: Create a list with one or more Content objects, ensuring that the last Content has the role "user".
  Act: Pass the list to ensureModelResponse.
  Assert: Assert that the returned list is equal to the input list (reference or value equality where applicable).
Validation:
  This assertion verifies that the method does not modify lists where the required conditions are already met, preserving the correct list state.


Scenario 3: Last content is not from the user

Details:
  TestName: appendsUserContentIfLastNotUser
  Description: The test checks that if the last Content object in the list has a role other than "user" (such as "model" or "system"), a new "user" Content—with the CONTINUE_OUTPUT_MESSAGE—is appended.
Execution:
  Arrange: Prepare a list where the last Content’s role is something other than "user" (e.g., "model").
  Act: Invoke ensureModelResponse with the list.
  Assert: Assert that the returned list has one more element than the input, and that the last element is a Content with role "user" and the CONTINUE_OUTPUT_MESSAGE.
Validation:
  This ensures that the model will always be prompted to respond, no matter the previous sender, preserving correct interaction sequence.


Scenario 4: Last content’s role is "USER" in different case

Details:
  TestName: correctlyHandlesCaseInsensitiveUserRole
  Description: This test checks that the method properly recognizes the role "user" regardless of casing (e.g., "USER", "User", "uSeR"), and does not append an extra content.
Execution:
  Arrange: Prepare a list where the last Content’s role is "USER" (upper-case or mixed-case).
  Act: Call ensureModelResponse with this list.
  Assert: Assert that the output is the same as the input (no appended content).
Validation:
  This tests and confirms case-insensitive comparison logic, safeguarding against edge-case errors in role values.


Scenario 5: Last content’s role is missing (empty Optional)

Details:
  TestName: appendsUserContentIfRoleMissing
  Description: This scenario verifies that if the last Content in the list has a missing or empty role (i.e., its role Optional is empty), the method appends "user" Content prompting a response.
Execution:
  Arrange: Create a list where the last Content has an empty Optional for role.
  Act: Pass this list to ensureModelResponse.
  Assert: Assert that a new "user" Content is appended with CONTINUE_OUTPUT_MESSAGE.
Validation:
  Validates that the method functions correctly even if metadata is incomplete, guaranteeing a response-prompting last content.


Scenario 6: Only one Content in the list, role is not "user"

Details:
  TestName: handlesSingleNonUserContent
  Description: Ensures that with a single Content in the list with a non-"user" role, a "user" Content is appended at the end.
Execution:
  Arrange: Prepare a list with one Content, role set to "model" or any non-"user" value.
  Act: Call ensureModelResponse.
  Assert: Check that the result has two elements, with the second having role "user".
Validation:
  Validates that the prompting logic works for minimal non-empty lists.


Scenario 7: List contains several contents, last has null parts

Details:
  TestName: appendsUserContentEvenIfPartsNull
  Description: Verifies that if the last Content's role is not "user", and its parts are null, the method still appends the "user" Content.
Execution:
  Arrange: Prepare a list in which the last Content has a valid non-user role and its parts Optional is empty.
  Act: Call ensureModelResponse with this list.
  Assert: Assert the appended "user" Content is present at the end.
Validation:
  Ensures robustness to underlying data types and absent message parts.


Scenario 8: Input list is immutable

Details:
  TestName: returnsImmutableListType
  Description: Checks that the returned list maintains immutability by returning an ImmutableList, regardless of input mutability.
Execution:
  Arrange: Create either a mutable List or an ImmutableList of Content.
  Act: Pass to ensureModelResponse.
  Assert: Assert that the returned value is an instance of ImmutableList.
Validation:
  Confirms the contract of returning immutable collections, as expected by downstream consumers.


Scenario 9: Input list contains contents with manually modified parts

Details:
  TestName: doesNotModifyOriginalContentParts
  Description: This test ensures that the method does not alter the existing Content or Part objects in the input list; only a new Content may be appended if necessary.
Execution:
  Arrange: Create a list with multiple Content and Part objects populated with random data.
  Act: Call ensureModelResponse.
  Assert: Assert that the input list's Content and Part objects remain unchanged, aside from possible appending.
Validation:
  Ensures non-destructive method behavior, guaranteeing data integrity.


Scenario 10: Large input list

Details:
  TestName: handlesLargeContentListEfficiently
  Description: Checks whether the method can process and return large lists without errors or performance degradation, and appropriately appends "user" Content if the last is not "user".
Execution:
  Arrange: Create a large list of Content objects (1000+ items), last item role set to "model".
  Act: Pass this list to ensureModelResponse.
  Assert: Check that the returned list has input size + 1 and last Content has role "user".
Validation:
  Validates method scalability and consistency with larger conversation histories.


Scenario 11: Last content’s role is "user" but parts field is empty

Details:
  TestName: preservesUserRoleContentEvenIfPartsEmpty
  Description: Ensures that if the last Content has role "user" but parts Optional is empty or empty list, the input list is returned unmodified.
Execution:
  Arrange: Prepare a list where last Content has role "user" and parts is either Optional.empty or an empty list.
  Act: Invoke ensureModelResponse.
  Assert: Assert returned list equals input list.
Validation:
  Confirms role alone governs behavior, not message content, as specified in business logic.


Scenario 12: Input list is already a valid conversation (multiple user/model pairs)

Details:
  TestName: preservesValidConversationThreads
  Description: Verifies that for a conversation history ending with a "user" content, regardless of conversation length or pairing, no change occurs.
Execution:
  Arrange: Create a list mixing user/model roles, ending with "user".
  Act: Pass to ensureModelResponse.
  Assert: Assert returned list matches input.
Validation:
  Ensures stability for existing valid histories and prevents unintended mutations.


Scenario 13: Last content’s role is whitespace or blank string

Details:
  TestName: appendsUserContentIfRoleIsBlank
  Description: Checks that if the last Content’s role is present but blank string or whitespace, the method appends the "user" Content.
Execution:
  Arrange: Prepare a list with last Content role set to "" or " ".
  Act: Pass to ensureModelResponse.
  Assert: Assert that "user" Content with CONTINUE_OUTPUT_MESSAGE is appended.
Validation:
  Ensures blank or whitespace roles are treated as invalid, maintaining response prompt logic.

*/

// ********RoostGPT********

package com.google.adk.models;

import static com.google.common.collect.ImmutableList.toImmutableList;
import static org.junit.jupiter.api.Assertions.*;

import com.google.common.collect.ImmutableList;
import com.google.genai.types.Content;
import com.google.genai.types.Part;
import java.util.List;
import java.util.stream.Stream;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

public class GeminiUtilEnsureModelResponseTest {

	@Test
	@Tag("boundary")
	public void testHandlesEmptyContentsList() {
		ImmutableList<Content> emptyContents = ImmutableList.of();
		List<Content> result = GeminiUtil.ensureModelResponse(emptyContents);
		assertEquals(1, result.size());
		Content lastContent = result.get(0);
		assertEquals("user", lastContent.role().orElse(""));
		assertTrue(lastContent.parts().isPresent());
		assertEquals(1, lastContent.parts().get().size());
		assertEquals(GeminiUtil.CONTINUE_OUTPUT_MESSAGE, lastContent.parts().get().get(0).text().orElse(""));
	}

	@Test
	@Tag("valid")
	public void testPreservesUserAsLastContent() {
		Content userContent = Content.builder()
			.parts(ImmutableList.of(Part.fromText("Sample question")))
			.role("user")
			.build();
		ImmutableList<Content> contents = ImmutableList.of(userContent);
		List<Content> result = GeminiUtil.ensureModelResponse(contents);
		assertEquals(contents, result);
	}

	@Test
	@Tag("invalid")
	public void testAppendsUserContentIfLastNotUser() {
		Content modelContent = Content.builder()
			.parts(ImmutableList.of(Part.fromText("model answer")))
			.role("model")
			.build();
		ImmutableList<Content> contents = ImmutableList.of(modelContent);
		List<Content> result = GeminiUtil.ensureModelResponse(contents);
		assertEquals(contents.size() + 1, result.size());
		Content lastContent = result.get(result.size() - 1);
		assertEquals("user", lastContent.role().orElse(""));
		assertTrue(lastContent.parts().isPresent());
		assertEquals(1, lastContent.parts().get().size());
		assertEquals(GeminiUtil.CONTINUE_OUTPUT_MESSAGE, lastContent.parts().get().get(0).text().orElse(""));
	}

	@Test
	@Tag("boundary")
	public void testCorrectlyHandlesCaseInsensitiveUserRole() {
		Content userContentMixedCase = Content.builder()
			.parts(ImmutableList.of(Part.fromText("User question")))
			.role("UsEr")
			.build();
		ImmutableList<Content> contents = ImmutableList.of(userContentMixedCase);
		List<Content> result = GeminiUtil.ensureModelResponse(contents);
		assertEquals(contents, result);
	}

	@Test
	@Tag("boundary")
	public void testAppendsUserContentIfRoleMissing() {
		Content missingRoleContent = Content.builder()
			.parts(ImmutableList.of(Part.fromText("no role present")))
			.build();
		ImmutableList<Content> contents = ImmutableList.of(missingRoleContent);
		List<Content> result = GeminiUtil.ensureModelResponse(contents);
		assertEquals(contents.size() + 1, result.size());
		Content lastContent = result.get(result.size() - 1);
		assertEquals("user", lastContent.role().orElse(""));
		assertTrue(lastContent.parts().isPresent());
		assertEquals(GeminiUtil.CONTINUE_OUTPUT_MESSAGE, lastContent.parts().get().get(0).text().orElse(""));
	}

	@Test
	@Tag("boundary")
	public void testHandlesSingleNonUserContent() {
		Content singleModel = Content.builder()
			.parts(ImmutableList.of(Part.fromText("some text")))
			.role("model")
			.build();
		ImmutableList<Content> contents = ImmutableList.of(singleModel);
		List<Content> result = GeminiUtil.ensureModelResponse(contents);
		assertEquals(2, result.size());
		assertEquals("user", result.get(1).role().orElse(""));
		assertEquals(GeminiUtil.CONTINUE_OUTPUT_MESSAGE, result.get(1).parts().get().get(0).text().orElse(""));
	}

	@Test
	@Tag("boundary")
	public void testAppendsUserContentEvenIfPartsNull() {
		Content modelContentNoParts = Content.builder().role("model").build(); // no parts
		ImmutableList<Content> contents = ImmutableList.of(modelContentNoParts);
		List<Content> result = GeminiUtil.ensureModelResponse(contents);
		assertEquals(2, result.size());
		Content lastContent = result.get(1);
		assertEquals("user", lastContent.role().orElse(""));
		assertEquals(GeminiUtil.CONTINUE_OUTPUT_MESSAGE, lastContent.parts().get().get(0).text().orElse(""));
	}

	@Test
	@Tag("boundary")
	public void testReturnsImmutableListType() {
		Content userContent = Content.builder().parts(ImmutableList.of(Part.fromText("some"))).role("user").build();
		List<Content> mutableList = Stream.of(userContent).collect(toImmutableList()); // mutable
																						// imitation
																						// not
																						// needed,
																						// always
																						// produces
																						// ImmutableList
		List<Content> result = GeminiUtil.ensureModelResponse(mutableList);
		assertTrue(result instanceof ImmutableList);
	}

	@Test
	@Tag("valid")
	public void testDoesNotModifyOriginalContentParts() {
		Part part1 = Part.fromText("one");
		Part part2 = Part.fromText("two");
		Content modelContent = Content.builder().parts(ImmutableList.of(part1, part2)).role("model").build();
		ImmutableList<Content> inputContents = ImmutableList.of(modelContent);
		List<Content> result = GeminiUtil.ensureModelResponse(inputContents);
		// Verify that existing content and parts remain referenced and unchanged
		Content originalContent = inputContents.get(0);
		Content resultContent = result.get(0);
		assertSame(originalContent, resultContent);
		assertEquals(originalContent.parts(), resultContent.parts());
		// If appended, appended is a new Content, not altering originals
		if (result.size() > inputContents.size()) {
			assertEquals("user", result.get(result.size() - 1).role().orElse(""));
		}
	}

	@Test
	@Tag("integration")
	public void testHandlesLargeContentListEfficiently() {
		int size = 1000; // Large list
		ImmutableList.Builder<Content> builder = ImmutableList.builder();
		for (int i = 0; i < size - 1; i++) {
			builder.add(Content.builder()
				.parts(ImmutableList.of(Part.fromText("entry " + i))) // TODO: change
																		// value for
																		// specific cases
				.role(i % 2 == 0 ? "user" : "model")
				.build());
		}
		// Last element is not user
		builder.add(Content.builder().parts(ImmutableList.of(Part.fromText("last"))).role("model").build());
		ImmutableList<Content> largeList = builder.build();
		List<Content> result = GeminiUtil.ensureModelResponse(largeList);
		assertEquals(size + 1, result.size());
		assertEquals("user", result.get(result.size() - 1).role().orElse(""));
		assertEquals(GeminiUtil.CONTINUE_OUTPUT_MESSAGE,
				result.get(result.size() - 1).parts().get().get(0).text().orElse(""));
	}

	@Test
	@Tag("valid")
	public void testPreservesUserRoleContentEvenIfPartsEmpty() {
		Content userContentNoParts = Content.builder().role("user").build(); // parts
																				// Optional.empty
		ImmutableList<Content> contents = ImmutableList.of(userContentNoParts);
		List<Content> result = GeminiUtil.ensureModelResponse(contents);
		assertEquals(contents, result);
	}

	@Test
	@Tag("valid")
	public void testPreservesValidConversationThreads() {
		Content c1 = Content.builder().parts(ImmutableList.of(Part.fromText("hi"))).role("user").build();
		Content c2 = Content.builder().parts(ImmutableList.of(Part.fromText("hello"))).role("model").build();
		Content c3 = Content.builder().parts(ImmutableList.of(Part.fromText("How are you?"))).role("user").build();
		ImmutableList<Content> contents = ImmutableList.of(c1, c2, c3);
		List<Content> result = GeminiUtil.ensureModelResponse(contents);
		assertEquals(contents, result);
	}

	@Test
	@Tag("invalid")
	public void testAppendsUserContentIfRoleIsBlank() {
		Content blankRoleContent = Content.builder()
			.parts(ImmutableList.of(Part.fromText("blank role")))
			.role("") // blank string
			.build();
		ImmutableList<Content> contents = ImmutableList.of(blankRoleContent);
		List<Content> result = GeminiUtil.ensureModelResponse(contents);
		assertEquals(contents.size() + 1, result.size());
		Content lastContent = result.get(result.size() - 1);
		assertEquals("user", lastContent.role().orElse(""));
		assertEquals(GeminiUtil.CONTINUE_OUTPUT_MESSAGE, lastContent.parts().get().get(0).text().orElse(""));
		// whitespace case
		Content spaceRoleContent = Content.builder()
			.parts(ImmutableList.of(Part.fromText("role space")))
			.role(" ")
			.build();
		ImmutableList<Content> contentsSpace = ImmutableList.of(spaceRoleContent);
		List<Content> resultSpace = GeminiUtil.ensureModelResponse(contentsSpace);
		assertEquals(contentsSpace.size() + 1, resultSpace.size());
		Content lastContentSpace = resultSpace.get(resultSpace.size() - 1);
		assertEquals("user", lastContentSpace.role().orElse(""));
		assertEquals(GeminiUtil.CONTINUE_OUTPUT_MESSAGE, lastContentSpace.parts().get().get(0).text().orElse(""));
	}

}
