/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test maven-adkjava-github using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=getPart0FromLlmResponse_f59ea731c7
ROOST_METHOD_SIG_HASH=getPart0FromLlmResponse_baf5d31ca9

Scenario 1: Extracting the first part when LlmResponse contains content with a non-empty parts list

Details:
  TestName: returnsFirstPartWhenContentHasNonEmptyParts
  Description: This test ensures that when the LlmResponse contains a Content object whose parts list is not empty, the method returns the first Part in that list wrapped in an Optional.
Execution:
  Arrange: Create a mock or dummy LlmResponse with a Content whose parts list contains at least one Part.
  Act: Call GeminiUtil.getPart0FromLlmResponse with this LlmResponse.
  Assert: Verify that the result is an Optional containing the first Part in the list.
Validation:
  The assertion checks that the method successfully extracts the initial Part from the content, proving correct traversal and mapping. This scenario is significant because it validates the primary use case of the method.

Scenario 2: Returning empty Optional when LlmResponse content is not present

Details:
  TestName: returnsEmptyOptionalWhenContentIsAbsent
  Description: This test checks that if LlmResponse’s content() method returns Optional.empty(), the method returns Optional.empty().
Execution:
  Arrange: Create an LlmResponse where content() returns Optional.empty().
  Act: Invoke GeminiUtil.getPart0FromLlmResponse with this response.
  Assert: Assert that the result is Optional.empty().
Validation:
  The validation is to confirm that the absence of content leads to a correct empty result, avoiding NullPointerException and consistent with Optional API design.

Scenario 3: Returning empty Optional when Content parts are not present

Details:
  TestName: returnsEmptyOptionalWhenContentPartsAreAbsent
  Description: This test validates the scenario where Content.parts() returns Optional.empty(), and the method should return Optional.empty().
Execution:
  Arrange: Prepare an LlmResponse with a Content whose parts() returns Optional.empty().
  Act: Call the method under test.
  Assert: Check that the returned Optional is empty.
Validation:
  This verifies that missing parts does not yield erroneous data, reflecting proper stream chaining and absence handling.

Scenario 4: Returning empty Optional when Content parts list is empty

Details:
  TestName: returnsEmptyOptionalWhenContentPartsListIsEmpty
  Description: This scenario checks if even when parts() is present but the list itself is empty, the method returns Optional.empty().
Execution:
  Arrange: Construct an LlmResponse with Content; parts() returns an empty ImmutableList.
  Act: Run GeminiUtil.getPart0FromLlmResponse.
  Assert: Assert that the output is Optional.empty().
Validation:
  Ensures that the filter(parts -> !parts.isEmpty()) logic works, preventing access to nonexistent elements.

Scenario 5: Correct extraction when multiple parts are present

Details:
  TestName: returnsFirstPartWhenMultiplePartsPresent
  Description: This test ensures that when Content's parts list contains several Part objects, the returned Optional contains strictly the first Part.
Execution:
  Arrange: Design an LlmResponse with Content where parts() returns a list of two or more Part instances.
  Act: Call GeminiUtil.getPart0FromLlmResponse.
  Assert: Validate that the Optional contains the first Part and not any subsequent ones.
Validation:
  Verifies correct ordering and mapping in extraction, ensuring business logic about "first" element.

Scenario 6: Returning empty Optional when LlmResponse is null

Details:
  TestName: returnsEmptyOptionalWhenLlmResponseIsNull
  Description: This test checks the behavior of the method when passed a null LlmResponse. The method should handle null firewalls gracefully and return Optional.empty().
Execution:
  Arrange: Pass null as the LlmResponse argument.
  Act: Call GeminiUtil.getPart0FromLlmResponse.
  Assert: Validate that an Optional.empty() is returned without throwing an exception.
Validation:
  Critical for robustness, ensuring null inputs do not trigger runtime errors, suitable for defensive programming in public APIs.

Scenario 7: Returning empty Optional when Content.roles are present but unrelated

Details:
  TestName: ignoresContentRoleWhenExtractingParts
  Description: Validates that the Content's role field (such as "user", "system", etc.) does not affect extraction—only the presence and content of parts is relevant.
Execution:
  Arrange: Build an LlmResponse where Content has a role but parts is empty or absent.
  Act: Invoke GeminiUtil.getPart0FromLlmResponse on this response.
  Assert: Expect Optional.empty() as output.
Validation:
  Asserts that business logic is focused on parts, decoupled from unrelated metadata.

Scenario 8: Returning the correct Part object when Part contains multiple possible fields

Details:
  TestName: returnsFirstPartRegardlessOfPartDataFields
  Description: Confirms that the method extracts the first Part independent of which fields are set on that Part (e.g., text, inlineData, fileData, thoughts).
Execution:
  Arrange: Create Content.parts with Part objects differing in field population.
  Act: Use GeminiUtil.getPart0FromLlmResponse.
  Assert: Ensure the first Part, regardless of field population, is returned.
Validation:
  Important for application data consistency, demonstrating that the method’s logic is not field-type dependent for Part extraction.

Scenario 9: Returning empty Optional if Content.parts contains all null or invalid Part elements

Details:
  TestName: returnsEmptyOptionalWhenAllPartsAreNull
  Description: Tests handling where Content.parts returns a list of Part elements, but all elements are null or invalid.
Execution:
  Arrange: LlmResponse content with parts() as a list containing only null or invalid Part references.
  Act: Invoke GeminiUtil.getPart0FromLlmResponse.
  Assert: Check for Optional.empty().
Validation:
  Confirms method resilience against malformed data in the parts collection.

Scenario 10: Returning the first Part when only one Part is present in Content.parts

Details:
  TestName: returnsFirstPartWhenOnlyOnePartExists
  Description: When Content.parts contains exactly one valid Part, the method should return that Part in an Optional.
Execution:
  Arrange: Build LlmResponse with Content containing a single Part in the parts list.
  Act: Invoke GeminiUtil.getPart0FromLlmResponse.
  Assert: Assert the Optional contains the only Part present.
Validation:
  Validates correct behavior when input size is minimal, ensuring expected performance in edge-of-normal scenarios.

Scenario 11: Returning empty Optional when Content.parts is present but all elements are filtered (via thought or other logic, if applicable)

Details:
  TestName: returnsEmptyOptionalWhenPartsFilteredOut
  Description: Tests the case when Content.parts is present but (if any custom logic or filters exist upstream, e.g., thought elements) all are filtered out, resulting in an empty list.
Execution:
  Arrange: Build LlmResponse with Content whose parts exist but contain only elements that would be filtered out earlier.
  Act: Call GeminiUtil.getPart0FromLlmResponse.
  Assert: Validate that Optional.empty() is returned.
Validation:
  Ensures correctness in presence of preprocessing that may remove all elements, emphasizing robustness for chained computations.

*/

// ********RoostGPT********

package com.google.adk.models;

import static com.google.common.collect.ImmutableList.toImmutableList;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import com.google.common.base.Ascii;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import com.google.common.collect.Iterables;
import com.google.genai.types.Blob;
import com.google.genai.types.Content;
import com.google.genai.types.FileData;
import com.google.genai.types.Part;
import java.util.Optional;
import java.util.List;
import java.util.stream.Stream;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import org.mockito.Mockito;
import org.junit.jupiter.api.*;

/**
 * Test suite for GeminiUtil.getPart0FromLlmResponse.
 */
public class GeminiUtilGetPart0FromLlmResponseTest {

	@Test
	@Tag("valid")
	@DisplayName("returnsFirstPartWhenContentHasNonEmptyParts")
	public void testReturnsFirstPartWhenContentHasNonEmptyParts() {
		Part expectedPart = Part.fromText("Expected Text");
		Content content = Content.builder().parts(ImmutableList.of(expectedPart)).build();
		LlmResponse llmResponse = Mockito.mock(LlmResponse.class);
		Mockito.when(llmResponse.content()).thenReturn(Optional.of(content));
		Optional<Part> result = GeminiUtil.getPart0FromLlmResponse(llmResponse);
		assertTrue(result.isPresent());
		assertEquals((Part) expectedPart, result.get());
	}

	@Test
	@Tag("invalid")
	@DisplayName("returnsEmptyOptionalWhenContentIsAbsent")
	public void testReturnsEmptyOptionalWhenContentIsAbsent() {
		LlmResponse llmResponse = Mockito.mock(LlmResponse.class);
		Mockito.when(llmResponse.content()).thenReturn(Optional.empty());
		Optional<Part> result = GeminiUtil.getPart0FromLlmResponse(llmResponse);
		assertEquals(Optional.empty(), result);
	}

	@Test
	@Tag("invalid")
	@DisplayName("returnsEmptyOptionalWhenContentPartsAreAbsent")
	public void testReturnsEmptyOptionalWhenContentPartsAreAbsent() {
		Content content = Mockito.mock(Content.class);
		Mockito.when(content.parts()).thenReturn(Optional.empty());
		LlmResponse llmResponse = Mockito.mock(LlmResponse.class);
		Mockito.when(llmResponse.content()).thenReturn(Optional.of(content));
		Optional<Part> result = GeminiUtil.getPart0FromLlmResponse(llmResponse);
		assertEquals(Optional.empty(), result);
	}

	@Test
	@Tag("invalid")
	@DisplayName("returnsEmptyOptionalWhenContentPartsListIsEmpty")
	public void testReturnsEmptyOptionalWhenContentPartsListIsEmpty() {
		Content content = Content.builder().parts(ImmutableList.<Part>of()).build();
		LlmResponse llmResponse = Mockito.mock(LlmResponse.class);
		Mockito.when(llmResponse.content()).thenReturn(Optional.of(content));
		Optional<Part> result = GeminiUtil.getPart0FromLlmResponse(llmResponse);
		assertEquals(Optional.empty(), result);
	}

	@Test
	@Tag("valid")
	@DisplayName("returnsFirstPartWhenMultiplePartsPresent")
	public void testReturnsFirstPartWhenMultiplePartsPresent() {
		Part part1 = Part.fromText("One");
		Part part2 = Part.fromText("Two");
		Part part3 = Part.fromText("Three");
		Content content = Content.builder().parts(ImmutableList.of(part1, part2, part3)).build();
		LlmResponse llmResponse = Mockito.mock(LlmResponse.class);
		Mockito.when(llmResponse.content()).thenReturn(Optional.of(content));
		Optional<Part> result = GeminiUtil.getPart0FromLlmResponse(llmResponse);
		assertTrue(result.isPresent());
		assertEquals((Part) part1, result.get());
	}

	@Test
	@Tag("invalid")
	@DisplayName("returnsEmptyOptionalWhenLlmResponseIsNull")
	public void testReturnsEmptyOptionalWhenLlmResponseIsNull() {
		Optional<Part> result = GeminiUtil.getPart0FromLlmResponse(null);
		assertEquals(Optional.empty(), result);
	}

	@Test
	@Tag("boundary")
	@DisplayName("ignoresContentRoleWhenExtractingParts")
	public void testIgnoresContentRoleWhenExtractingParts() {
		Content content = Content.builder().role("user").parts(Optional.empty()).build();
		LlmResponse llmResponse = Mockito.mock(LlmResponse.class);
		Mockito.when(llmResponse.content()).thenReturn(Optional.of(content));
		Optional<Part> result = GeminiUtil.getPart0FromLlmResponse(llmResponse);
		assertEquals(Optional.empty(), result);
	}

	@Test
	@Tag("boundary")
	@DisplayName("returnsFirstPartRegardlessOfPartDataFields")
	public void testReturnsFirstPartRegardlessOfPartDataFields() {
		Part partWithFileData = Part.builder()
			.fileData(FileData.builder().fileUri(Optional.of("dummyUri")).mimeType(Optional.of("text/plain")).build())
			.build();
		Part partWithInlineData = Part.builder()
			.inlineData(Blob.builder().data(Optional.of(new byte[4])).mimeType(Optional.of("application/pdf")).build())
			.build();
		Part partWithText = Part.fromText("Some Text");
		Content content = Content.builder()
			.parts(ImmutableList.of(partWithInlineData, partWithFileData, partWithText))
			.build();
		LlmResponse llmResponse = Mockito.mock(LlmResponse.class);
		Mockito.when(llmResponse.content()).thenReturn(Optional.of(content));
		Optional<Part> result = GeminiUtil.getPart0FromLlmResponse(llmResponse);
		assertTrue(result.isPresent());
		assertEquals((Part) partWithInlineData, result.get());
	}

	@Test
	@Tag("invalid")
	@DisplayName("returnsEmptyOptionalWhenAllPartsAreNull")
	public void testReturnsEmptyOptionalWhenAllPartsAreNull() {
		Content content = Mockito.mock(Content.class);
		// Provide list with only nulls; builder would not allow nulls, but mock can
		// return whatever
		Mockito.when(content.parts()).thenReturn(Optional.of(ImmutableList.of(null, null)));
		LlmResponse llmResponse = Mockito.mock(LlmResponse.class);
		Mockito.when(llmResponse.content()).thenReturn(Optional.of(content));
		Optional<Part> result = GeminiUtil.getPart0FromLlmResponse(llmResponse);
		assertEquals(Optional.ofNullable(null), result);
	}

	@Test
	@Tag("boundary")
	@DisplayName("returnsFirstPartWhenOnlyOnePartExists")
	public void testReturnsFirstPartWhenOnlyOnePartExists() {
		Part singlePart = Part.fromText("Solo Part");
		Content content = Content.builder().parts(ImmutableList.of(singlePart)).build();
		LlmResponse llmResponse = Mockito.mock(LlmResponse.class);
		Mockito.when(llmResponse.content()).thenReturn(Optional.of(content));
		Optional<Part> result = GeminiUtil.getPart0FromLlmResponse(llmResponse);
		assertTrue(result.isPresent());
		assertEquals((Part) singlePart, result.get());
	}

	@Test
	@Tag("invalid")
	@DisplayName("returnsEmptyOptionalWhenPartsFilteredOut")
	public void testReturnsEmptyOptionalWhenPartsFilteredOut() {
		Content content = Content.builder().parts(ImmutableList.of()).build();
		LlmResponse llmResponse = Mockito.mock(LlmResponse.class);
		Mockito.when(llmResponse.content()).thenReturn(Optional.of(content));
		Optional<Part> result = GeminiUtil.getPart0FromLlmResponse(llmResponse);
		assertEquals(Optional.empty(), result);
	}

}