/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test maven-adkjava-github using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=sendRealtime_70893b6869
ROOST_METHOD_SIG_HASH=sendRealtime_d672acb596

Scenario 1: Sending a valid Blob when the sessionFuture is completed successfully

Details:
  TestName: sendRealtimeWithValidBlobAndSessionCompletesSuccessfully
  Description: This test is designed to verify that the sendRealtime method correctly sends a valid Blob object when the underlying sessionFuture completes successfully and returns a functional AsyncSession. It checks that the resulting Completable completes without errors, confirming that the Blob is accepted and processed.

Execution:
  Arrange: Create a mock AsyncSession and set up sessionFuture to complete successfully with it. Prepare a valid Blob mock instance.
  Act: Invoke sendRealtime with the prepared Blob.
  Assert: Use JUnit assertions to verify that the Completable completes without error.
Validation:
  The assertion confirms that the method operates as expected under normal conditions, ensuring correct interaction between sessionFuture, AsyncSession, and Blob transmission. This validates business logic for normal real-time input handling.

Scenario 2: Sending a null Blob triggers an exception from AsyncSession

Details:
  TestName: sendRealtimeWithNullBlobCausesException
  Description: This scenario examines the method’s behavior when a null Blob is passed. The AsyncSession’s sendRealtimeInput expects a valid Blob and may throw an exception upon receiving null. The test focuses on ensuring that sendRealtime propagates this error into its returned Completable.

Execution:
  Arrange: Mock AsyncSession to throw a NullPointerException or equivalent error if sendRealtimeInput is called with null. Set up sessionFuture to complete with the AsyncSession.
  Act: Call sendRealtime with a null Blob value.
  Assert: Assert that the returned Completable emits an error (such as NullPointerException).
Validation:
  This assertion verifies robust input validation and error propagation, ensuring that sendRealtime does not silently ignore invalid input, and users are notified of malformed requests.

Scenario 3: The sessionFuture fails with a CompletionException

Details:
  TestName: sendRealtimeSessionFutureFailsWithCompletionException
  Description: The test covers the case where sessionFuture completes exceptionally (e.g., with CompletionException). It checks whether sendRealtime’s Completable propagates this error accordingly so that callers can react to session initialization failures.

Execution:
  Arrange: Configure sessionFuture to complete exceptionally with a CompletionException.
  Act: Invoke sendRealtime with any valid Blob instance.
  Assert: Assert that the returned Completable emits the CompletionException or its underlying cause.
Validation:
  This confirms that session initialization errors are communicated back through sendRealtime and not masked, preserving reliability and transparency of the connection logic.

Scenario 4: AsyncSession.sendRealtimeInput throws an exception

Details:
  TestName: sendRealtimeAsyncSessionThrowsException
  Description: This test inspects the scenario where, despite sessionFuture completing normally, AsyncSession’s sendRealtimeInput throws an exception (such as SocketException). The test ensures that sendRealtime’s Completable emits this exception, maintaining error propagation.

Execution:
  Arrange: Mock AsyncSession so that sendRealtimeInput throws a SocketException. Set sessionFuture to complete with this AsyncSession.
  Act: Invoke sendRealtime with a valid Blob.
  Assert: Assert that the returned Completable emits the SocketException.
Validation:
  The assertion checks error handling during real-time transmission, ensuring that the connection implementation does not fail silently if lower-level transmission fails.

Scenario 5: sendRealtime called after connection is closed

Details:
  TestName: sendRealtimeAfterConnectionClosedDoesNotSend
  Description: This scenario tests the business logic where sendRealtime is invoked after closed has been set to true and the session is considered terminated. The expectation is that either no action occurs or an error is emitted, confirming that resources aren’t accessed post-closure.

Execution:
  Arrange: Manually set the closed AtomicBoolean to true. Prepare a valid Blob and sessionFuture that would normally succeed.
  Act: Call sendRealtime with a valid Blob.
  Assert: Assert that the Completable either completes immediately (no-op) or emits an appropriate error indicating closure.
Validation:
  Verifies the connection safety behavior, ensuring resources aren’t used after closure, which protects system stability and prevents resource leaks.

Scenario 6: sessionFuture is not yet completed when sendRealtime is invoked

Details:
  TestName: sendRealtimeWaitsForSessionFutureCompletion
  Description: This scenario explores the asynchronous nature of sessionFuture. The test checks that sendRealtime waits for sessionFuture to complete and then submits the Blob, ensuring correct sequencing and non-blocking behavior.

Execution:
  Arrange: Set sessionFuture to be incomplete initially, completing later with a valid AsyncSession. Prepare a valid Blob.
  Act: Call sendRealtime and complete sessionFuture in a separate thread.
  Assert: Assert that the returned Completable does not complete until sessionFuture does.
Validation:
  Confirms adherence to asynchronous contract, maintaining responsive design and correct sequencing of real-time inputs.

Scenario 7: sendRealtime with an invalid Blob (e.g., malformed or unsupported content)

Details:
  TestName: sendRealtimeWithInvalidBlobCausesTransmissionFailure
  Description: Tests transmission failure caused by a Blob that is malformed or unsupported by the AsyncSession. The test verifies that AsyncSession rejects the Blob and that the error is surfaced through the Completable.

Execution:
  Arrange: Mock AsyncSession so that sendRealtimeInput throws a specific exception for invalid Blob. Prepare such a Blob and set sessionFuture to complete with the mock session.
  Act: Call sendRealtime with the invalid Blob.
  Assert: Assert that the Completable emits the expected transmission failure exception.
Validation:
  Ensures robustness against malformed input and validates error reporting for unsupported Blob types.

Scenario 8: Handling cancellation of sessionFuture before sendRealtime completes

Details:
  TestName: sendRealtimeSessionFutureCancelledBeforeCompletion
  Description: This scenario checks how sendRealtime behaves if sessionFuture is cancelled prior to its completion. The expectation is that sendRealtime fails gracefully and does not attempt transmission when sessionFuture is cancelled.

Execution:
  Arrange: Set up sessionFuture to be cancelled before sendRealtime is invoked. Prepare a valid Blob instance.
  Act: Invoke sendRealtime with the Blob, after sessionFuture’s cancellation.
  Assert: Assert that the Completable emits a CancellationException or completes without transmission.
Validation:
  Verifies resilient behavior when underlying session cannot be acquired, ensuring that the system handles cancellation gracefully and avoids undefined states.

Scenario 9: sendRealtime called with a Blob of large size

Details:
  TestName: sendRealtimeWithLargeBlobHandlesTransmission
  Description: This test explores the method’s ability to handle a Blob of large size, verifying performance, streaming, and error handling for oversized transmission. It ensures AsyncSession processes large media correctly and that sendRealtime’s Completable reflects completion or failure.

Execution:
  Arrange: Mock AsyncSession that can accept large Blob or trigger an error due to size constraints. Prepare a large Blob instance and set sessionFuture to complete with the session.
  Act: Call sendRealtime with the large Blob.
  Assert: Assert that the Completable completes or emits an error depending on AsyncSession’s handling.
Validation:
  Validates the connection’s scalability and robustness for real-time media transmission, ensuring system limits are respected.

Scenario 10: Multiple sendRealtime calls in rapid succession

Details:
  TestName: sendRealtimeHandlesMultipleRapidCalls
  Description: This scenario tests concurrency and sequencing by invoking sendRealtime multiple times in rapid succession. It analyzes whether the connection handles parallel submissions safely and all Completables return correct completion or error.

Execution:
  Arrange: Set up sessionFuture to complete with a mock AsyncSession that safely processes multiple inputs. Prepare several valid Blob instances.
  Act: Invoke sendRealtime several times in quick succession with different Blobs.
  Assert: Assert that all returned Completables complete successfully and no errors are thrown.
Validation:
  Ensures the method’s thread safety, resilience and proper sequencing for real-time high-throughput scenarios, validating that the connection is ready for production loads.

*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.genai.AsyncSession;
import com.google.genai.Client;
import com.google.genai.types.Blob;
import com.google.genai.types.LiveConnectConfig;
import com.google.genai.types.LiveSendRealtimeInputParameters;
import io.reactivex.rxjava3.core.Completable;
import java.net.SocketException;
import java.util.concurrent.CancellationException;
import java.util.concurrent.CompletableFuture;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class GeminiLlmConnectionSendRealtimeTest {

  private Client mockClient;

  private LiveConnectConfig mockConfig;

  private AsyncSession mockSession;

  private CompletableFuture<AsyncSession> sessionFuture;

  private GeminiLlmConnection connection;

  private Blob validBlob;

  private Blob invalidBlob;

  private Blob largeBlob;

  @BeforeEach
  void setup() {
    mockClient = mock(Client.class);
    mockConfig = mock(LiveConnectConfig.class);
    mockSession = mock(AsyncSession.class);
    sessionFuture = new CompletableFuture<>();
    validBlob = mock(Blob.class);
    invalidBlob = mock(Blob.class);
    largeBlob = mock(Blob.class);
    when(mockClient.async.live.connect(anyString(), any(LiveConnectConfig.class)))
        .thenReturn(sessionFuture);
    // TODO: Change "test-model" to desired model name
    connection = new GeminiLlmConnection(mockClient, "test-model", mockConfig);
  }

  @Test
  @Tag("valid")
  public void testSendRealtimeWithValidBlobAndSessionCompletesSuccessfully() {
    when(mockSession.sendRealtimeInput(any(LiveSendRealtimeInputParameters.class)))
        .thenReturn(CompletableFuture.completedFuture(null));
    sessionFuture.complete(mockSession);
    Completable completable = connection.sendRealtime(validBlob);
    assertDoesNotThrow(completable::blockingAwait); // Valid Completable completes successfully
  }

  @Test
  @Tag("invalid")
  public void testSendRealtimeWithNullBlobCausesException() {
    when(mockSession.sendRealtimeInput(any(LiveSendRealtimeInputParameters.class)))
        .thenThrow(new NullPointerException("Blob cannot be null"));
    sessionFuture.complete(mockSession);
    Completable completable = connection.sendRealtime(null);
    assertThrows(NullPointerException.class, completable::blockingAwait); // Exception is thrown
  }

  @Test
  @Tag("invalid")
  public void testSendRealtimeSessionFutureFailsWithCompletionException() {
    sessionFuture.completeExceptionally(
        new java.util.concurrent.CompletionException(
            "Session failed", new RuntimeException("Underlying cause")));
    Completable completable = connection.sendRealtime(validBlob);
    assertThrows(java.util.concurrent.CompletionException.class, completable::blockingAwait);
  }

  @Test
  @Tag("invalid")
  public void testSendRealtimeAsyncSessionThrowsException() {
    when(mockSession.sendRealtimeInput(any(LiveSendRealtimeInputParameters.class)))
        .thenThrow(new SocketException("Transmission failed"));
    sessionFuture.complete(mockSession);
    Completable completable = connection.sendRealtime(validBlob);
    assertThrows(SocketException.class, completable::blockingAwait); // AsyncSession throws
  }

  @Test
  @Tag("boundary")
  public void testSendRealtimeAfterConnectionClosedDoesNotSend() throws Exception {
    // Close connection before send
    sessionFuture.complete(mockSession);
    connection.close(); // sets closed to true
    Completable completable = connection.sendRealtime(validBlob);
    // Depending on implementation, may complete noop or fail (usually completes)
    assertDoesNotThrow(completable::blockingAwait); // Should not send after close,
    // completes
  }

  @Test
  @Tag("integration")
  public void testSendRealtimeWaitsForSessionFutureCompletion() throws Exception {
    CompletableFuture<AsyncSession> deferredSessionFuture = new CompletableFuture<>();
    when(mockClient.async.live.connect(anyString(), any(LiveConnectConfig.class)))
        .thenReturn(deferredSessionFuture);
    GeminiLlmConnection conn = new GeminiLlmConnection(mockClient, "test-model", mockConfig);
    Completable completable = conn.sendRealtime(validBlob);
    // Session not ready: Completable should not complete yet
    assertThrows(
        java.util.concurrent.TimeoutException.class,
        () -> completable.timeout(100, java.util.concurrent.TimeUnit.MILLISECONDS).blockingAwait());
    when(mockSession.sendRealtimeInput(any(LiveSendRealtimeInputParameters.class)))
        .thenReturn(CompletableFuture.completedFuture(null));
    deferredSessionFuture.complete(mockSession);
    // After complete, should complete
    assertDoesNotThrow(completable::blockingAwait);
  }

  @Test
  @Tag("invalid")
  public void testSendRealtimeWithInvalidBlobCausesTransmissionFailure() {
    when(mockSession.sendRealtimeInput(any(LiveSendRealtimeInputParameters.class)))
        .thenThrow(new IllegalArgumentException("Invalid Blob format"));
    sessionFuture.complete(mockSession);
    Completable completable = connection.sendRealtime(invalidBlob);
    assertThrows(IllegalArgumentException.class, completable::blockingAwait);
  }

  @Test
  @Tag("boundary")
  public void testSendRealtimeSessionFutureCancelledBeforeCompletion() {
    sessionFuture.cancel(false);
    Completable completable = connection.sendRealtime(validBlob);
    assertThrows(CancellationException.class, completable::blockingAwait); // Should
    // emit
    // CancellationException
  }

  @Test
  @Tag("boundary")
  public void testSendRealtimeWithLargeBlobHandlesTransmission() {
    when(mockSession.sendRealtimeInput(any(LiveSendRealtimeInputParameters.class)))
        .thenReturn(CompletableFuture.completedFuture(null));
    sessionFuture.complete(mockSession);
    Completable completable = connection.sendRealtime(largeBlob);
    assertDoesNotThrow(completable::blockingAwait); // Completes for large blob if supported
  }

  @Test
  @Tag("integration")
  public void testSendRealtimeHandlesMultipleRapidCalls() {
    when(mockSession.sendRealtimeInput(any(LiveSendRealtimeInputParameters.class)))
        .thenReturn(CompletableFuture.completedFuture(null));
    sessionFuture.complete(mockSession);
    Blob blob1 = mock(Blob.class);
    Blob blob2 = mock(Blob.class);
    Blob blob3 = mock(Blob.class);
    Completable c1 = connection.sendRealtime(blob1);
    Completable c2 = connection.sendRealtime(blob2);
    Completable c3 = connection.sendRealtime(blob3);
    assertDoesNotThrow(c1::blockingAwait);
    assertDoesNotThrow(c2::blockingAwait);
    assertDoesNotThrow(c3::blockingAwait);
  }
}
