/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test maven-adkjava-github using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=prepareGenenerateContentRequest_1d11c15a2c
ROOST_METHOD_SIG_HASH=prepareGenenerateContentRequest_5633670894

Scenario 1: Request is sanitized and thoughts are stripped, with empty content list

Details:
  TestName: sanitizeTrueStripThoughtsTrueEmptyContents
  Description: This test checks the case where prepareGenenerateContentRequest is called with sanitize set to true and stripThoughts set to true, but the input LlmRequest has an empty contents list. The test targets how the method populates the contents with a default user message.

Execution:
  Arrange: Create an LlmRequest with empty contents and config set to empty or default.
  Act: Call prepareGenenerateContentRequest with the request, sanitize=true, stripThoughts=true.
  Assert: The result should have a contents list containing only one Content entry with the user role and a Part whose text is CONTINUE_OUTPUT_MESSAGE.

Validation:
  This assertion confirms that when no content is present, the utility method ensures model response by injecting a new user Content with the standardized continue output message, regardless of sanitization and thought filtering. This behavior ensures that the API always has a prompt to act upon, serving proper request formation.

---

Scenario 2: Request is sanitized, thoughts are not stripped, with existing user content as last message

Details:
  TestName: sanitizeTrueStripThoughtsFalseUserContentLast
  Description: This test evaluates the path where sanitize is true, stripThoughts is false, and the LlmRequest contents already end with a Content having the role "user". It validates that no extra user content is appended and existing contents remain.

Execution:
  Arrange: Construct an LlmRequest with contents containing at least one Content with role="user" as the last entry, all with non-thought parts, and with config fields set.
  Act: Invoke prepareGenenerateContentRequest(request, true, false).
  Assert: The result should contain sanitized versions of the original contents (displayName removed from blobs and fileData), ending with the original "user" Content, with no duplication of CONTINUE_OUTPUT_MESSAGE Content.

Validation:
  This assertion ensures that when the input already ends with a user message, no redundant user prompts are added, maintaining the intended request flow. It also validates that when stripThoughts is false, no parts are removed due to thoughts.

---

Scenario 3: Request is not sanitized, thoughts are stripped, last message not from user

Details:
  TestName: sanitizeFalseStripThoughtsTrueLastNotUser
  Description: This scenario checks the case where the input contents do not end with a user role, sanitize is false, and thoughts should be stripped. It also validates that a user Content is appended with the CONTINUE_OUTPUT_MESSAGE.

Execution:
  Arrange: Create an LlmRequest where the last Content has role "assistant" and includes both thought and non-thought Part items.
  Act: Call prepareGenenerateContentRequest with sanitize=false and stripThoughts=true.
  Assert: The result should include the original contents (last Content with only non-thought Parts remaining) plus a newly appended user Content with the CONTINUE_OUTPUT_MESSAGE Part.

Validation:
  This ensures the method always guarantees a user input at the end of the request and that the stripThoughts operation applies as intended, removing thought parts only.

---

Scenario 4: Request is sanitized, thoughts are stripped, with displayName fields present

Details:
  TestName: sanitizeTrueStripThoughtsTrueRemoveDisplayName
  Description: Ensures that when contents Parts have Blobs or FileData with displayName present, these are removed by the method, and, in addition, thought parts are stripped.

Execution:
  Arrange: Build an LlmRequest containing Content objects with Part objects that have Blob (with displayName), FileData (with displayName), as well as thought and non-thought parts.
  Act: Call prepareGenenerateContentRequest with sanitize=true, stripThoughts=true.
  Assert: The result should have corresponding Parts in which Blob and FileData displayName attributes are not present (other fields preserved), and any thought parts are removed.

Validation:
  This assertion confirms the method’s data sanitization requirement for the Gemini API backend and validates that unnecessary metadata (like displayName) is not sent, and that thoughts are always removed when required.

---

Scenario 5: Request is not sanitized and does not strip thoughts, various content/part configurations

Details:
  TestName: sanitizeFalseStripThoughtsFalsePreserveAll
  Description: Ensures that with sanitize and stripThoughts both false, the request contents and all parts are preserved as-is (unless a user Content must still be added).

Execution:
  Arrange: Create an LlmRequest with multiple Content objects containing various roles, thought and non-thought Parts, and ending with a Content role that is not "user".
  Act: Call prepareGenenerateContentRequest with sanitize=false, stripThoughts=false.
  Assert: The result should be the same as the input except for a new user Content with CONTINUE_OUTPUT_MESSAGE appended to the end.

Validation:
  This test ensures that the method does not modify existing contents or parts unless required to append a model prompt Content (if not already present), verifying minimal side effects when both sanitize and stripThoughts are disabled.

---

Scenario 6: Request is sanitized, content config includes labels

Details:
  TestName: sanitizeTrueConfigLabelsPresent
  Description: Checks that if the input LlmRequest config contains labels, these are removed as part of the request sanitization, regardless of contents.

Execution:
  Arrange: Construct an LlmRequest with an explicit config.labels() present with some key-value pairs, optionally with empty contents.
  Act: Call prepareGenenerateContentRequest with sanitize=true (stripThoughts can be true/false).
  Assert: The result’s config must no longer have any labels associated (should be empty), all other fields kept as expected.

Validation:
  This scenario verifies compliance with backend requirements, ensuring that label fields are never sent when sanitization is enabled, which otherwise could lead to rejected requests.

---

Scenario 7: Request contains contents with no parts

Details:
  TestName: contentNoPartsAppendUserContent
  Description: Tests that if contents are present but at least one Content has empty or absent parts, and ends with a role other than "user", a user Content with CONTINUE_OUTPUT_MESSAGE is appended.

Execution:
  Arrange: Create an LlmRequest with a contents list where one or more Content entries' parts are missing or empty, and final Content has role != "user".
  Act: Call prepareGenenerateContentRequest (sanitize and stripThoughts may be arbitrary).
  Assert: The result will include all the original contents (with parts as is), followed by a Content with role "user" and CONTINUE_OUTPUT_MESSAGE.

Validation:
  The test checks robustness in the face of incomplete part data, ensuring that even when Content entries lack parts, a follow-up user Content is always appended, sustaining protocol requirements.

---

Scenario 8: Request with only thought parts in all contents, stripThoughts enabled

Details:
  TestName: onlyThoughtPartsAllStrippedResultPartsEmpty
  Description: This test addresses the edge case where every Content in the input contains only Part items with thought set to true, and stripThoughts is enabled.

Execution:
  Arrange: Construct an LlmRequest where all Content entries include only thought parts, and ends with role "user".
  Act: Call prepareGenenerateContentRequest with stripThoughts set to true.
  Assert: All contents in the result have empty part lists (i.e., parts count is zero), with the same number of Content objects as originally.

Validation:
  This case ensures that the stripping logic removes all thought parts, potentially resulting in Content entries with empty part lists. It confirms that no Content entries are dropped even if left empty.

---

Scenario 9: Request with last Content role in nonstandard case (e.g., "User", "USER"), ensure user content is not appended

Details:
  TestName: lastContentRoleCaseInsensitiveUserNoAppend
  Description: When the final Content contains the role "User" or "USER" (capitalized differently), ensure case-insensitive comparison is used and no additional user Content is appended.

Execution:
  Arrange: Prepare an LlmRequest with last Content role="USER", and other content before it.
  Act: Call prepareGenenerateContentRequest with arbitrary sanitize and stripThoughts values.
  Assert: The output contents are the same (no appended user Content).

Validation:
  This test guarantees compliance with case-insensitive definition for "user", so message-prompting logic is robust across case variations.

---

Scenario 10: Request with all fields empty but config labels are set, and both sanitize and stripThoughts are true

Details:
  TestName: emptyContentConfigLabelsSanitizeAndThoughts
  Description: Examines the scenario where LlmRequest contents are empty but config has labels, and both sanitize and stripThoughts are enabled.

Execution:
  Arrange: Create an LlmRequest with contents as empty list and config with labels present.
  Act: Call prepareGenenerateContentRequest with sanitize=true, stripThoughts=true.
  Assert: The output config labels are empty, and contents list contains only one user Content with CONTINUE_OUTPUT_MESSAGE.

Validation:
  Validates both sanitization (labels removal) and guarantee of model response via appending user Content, ensuring both are applied for empty initial requests.

---

Scenario 11: Request has one content, one part, thought false, role user, no sanitization/stripping

Details:
  TestName: singleUserPartNoSanitizeNoStrip
  Description: Ensures that when only one Content and one Part exists, with no thought flag and user role, and both sanitize and stripThoughts are false, the result is identical to input.

Execution:
  Arrange: Compose an LlmRequest with single Content (role="user") with one Part, none of displayName, config fields, or thought present.
  Act: Call prepareGenenerateContentRequest with sanitize=false, stripThoughts=false.
  Assert: Output contents are exactly the same as input, with no Content added or modified.

Validation:
  Confirms method does not modify requests that already meet model expectation and require no changes.

---

Scenario 12: Request includes Content with null or absent role

Details:
  TestName: contentWithNoRoleResultsInUserContentAppended
  Description: Validates behavior when Content objects lack a role property, ensuring user Content is appended.

Execution:
  Arrange: Construct LlmRequest where at least one or all Content entries have no role value set.
  Act: Call prepareGenenerateContentRequest with arbitrary sanitize and stripThoughts.
  Assert: The result appends a user Content with CONTINUE_OUTPUT_MESSAGE at the end.

Validation:
  Ensures logic correctly enforces model response prompt even when roles are missing in provided Content entries.

---

Scenario 13: Content list is empty, both sanitize and stripThoughts are false

Details:
  TestName: emptyContentsNoSanitizeNoStrip
  Description: Ensures that even if both sanitize and stripThoughts are false, an empty contents LlmRequest results in a user-prompt Content being appended.

Execution:
  Arrange: Create LlmRequest with empty contents.
  Act: Call prepareGenenerateContentRequest with sanitize=false, stripThoughts=false.
  Assert: Result contains exactly one Content with CONTINUE_OUTPUT_MESSAGE and role "user".

Validation:
  Affirms that empty-contents logic is not dependent on sanitize or stripThoughts settings.

---

Scenario 14: Mix of content entries with and without parts, thoughts present, partial stripThoughts

Details:
  TestName: mixedContentPartialThoughtsStrip
  Description: Given an LlmRequest with some Content entries having thoughts true, others not, and some without thoughts or parts, with stripThoughts=true, checks selective removal.

Execution:
  Arrange: Construct a contents list where some Parts are thought, some are not, some entries have empty/missing parts.
  Act: Call prepareGenenerateContentRequest with stripThoughts=true.
  Assert: Contents Parts lists in the result only retain non-thought parts.

Validation:
  Verifies partial application of stripThoughts logic, ensuring only thought-labeled Parts are excluded, but all Content objects remain present.

---

Scenario 15: Request with non-user final Content that has only thought part, stripThoughts enabled

Details:
  TestName: nonUserFinalContentWithThoughtOnlyThenAppendUser
  Description: If final Content is not "user" and only has a thought, stripThoughts leaves it with no parts, and a user Content needs to be appended.

Execution:
  Arrange: Create an LlmRequest ending with Content(role="assistant") with a single thought Part.
  Act: Call prepareGenenerateContentRequest with stripThoughts=true.
  Assert: Output includes all original contents (last with empty parts) plus an appended user Content with CONTINUE_OUTPUT_MESSAGE.

Validation:
  Ensures chaining of both stripThoughts logic and guarantee of model-prompt message, even when all user content is effectively lost to thought-stripping.

---

*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import com.google.genai.types.Blob;
import com.google.genai.types.Content;
import com.google.genai.types.FileData;
import com.google.genai.types.Part;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

public class GeminiUtilPrepareGenenerateContentRequest175Test {

	private static final String USER_ROLE = "user";

	private static final String ASSISTANT_ROLE = "assistant";

	@Test
	@Tag("boundary")
	public void testSanitizeTrueStripThoughtsTrueEmptyContents() {
		LlmRequest input = LlmRequest.builder().contents(ImmutableList.of()).config(Optional.empty()).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(input, true, true);
		List<Content> resultContents = result.contents();
		assertEquals(1, resultContents.size());
		Content onlyContent = resultContents.get(0);
		assertEquals(USER_ROLE, onlyContent.role().get());
		assertEquals(1, onlyContent.parts().get().size());
		Part part = onlyContent.parts().get().get(0);
		assertEquals(GeminiUtil.CONTINUE_OUTPUT_MESSAGE, part.text().get());
	}

	@Test
	@Tag("valid")
	public void testSanitizeTrueStripThoughtsFalseUserContentLast() {
		Part userPart = Part.fromText("A user input");
		Content userContent = Content.builder().role(USER_ROLE).parts(ImmutableList.of(userPart)).build();
		Blob blobWithDisplayName = Blob.builder()
			.data(Optional.of(new byte[] { 1, 2 }))
			.mimeType(Optional.of("image/png"))
			.displayName(Optional.of("MyPic")) // TODO: Will be removed on sanitize
			.build();
		Part blobPart = Part.builder().inlineData(Optional.of(blobWithDisplayName)).build();
		FileData fileDataWithDisplayName = FileData.builder()
			.fileUri(Optional.of("fake://file"))
			.mimeType(Optional.of("foo/bar"))
			.displayName(Optional.of("Doc")) // TODO: Will be removed on sanitize
			.build();
		Part filePart = Part.builder().fileData(Optional.of(fileDataWithDisplayName)).build();
		Content assistantContent = Content.builder()
			.role(ASSISTANT_ROLE)
			.parts(ImmutableList.of(blobPart, filePart))
			.build();
		LlmRequest input = LlmRequest.builder()
			.contents(ImmutableList.of(assistantContent, userContent))
			.config(Optional.empty())
			.build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(input, true, false);
		List<Content> outputContents = result.contents();
		assertEquals(2, outputContents.size());
		Content lastContent = outputContents.get(1);
		assertEquals(USER_ROLE, lastContent.role().get());
		assertEquals("A user input", lastContent.parts().get().get(0).text().get());
		Part outBlobPart = outputContents.get(0).parts().get().get(0);
		assertTrue(outBlobPart.inlineData().isPresent());
		Blob sanitizedBlob = outBlobPart.inlineData().get();
		assertTrue(sanitizedBlob.displayName().isEmpty());
		Part outFilePart = outputContents.get(0).parts().get().get(1);
		assertTrue(outFilePart.fileData().isPresent());
		FileData sanitizedFileData = outFilePart.fileData().get();
		assertTrue(sanitizedFileData.displayName().isEmpty());
	}

	@Test
	@Tag("boundary")
	public void testSanitizeFalseStripThoughtsTrueLastNotUser() {
		Part thoughtPart = Part.builder().text(Optional.of("I think")).thought(Optional.of(true)).build();
		Part nonThoughtPart = Part.builder().text(Optional.of("Assistant speaks")).thought(Optional.of(false)).build();
		Content assistantContent = Content.builder()
			.role(ASSISTANT_ROLE)
			.parts(ImmutableList.of(thoughtPart, nonThoughtPart))
			.build();
		LlmRequest input = LlmRequest.builder().contents(ImmutableList.of(assistantContent)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(input, false, true);
		List<Content> resultContents = result.contents();
		assertEquals(2, resultContents.size());
		Content strippedContent = resultContents.get(0);
		ImmutableList<Part> parts = strippedContent.parts().get();
		assertEquals(1, parts.size());
		assertEquals("Assistant speaks", parts.get(0).text().get());
		Content appendedContent = resultContents.get(1);
		assertEquals(USER_ROLE, appendedContent.role().get());
		assertEquals(GeminiUtil.CONTINUE_OUTPUT_MESSAGE, appendedContent.parts().get().get(0).text().get());
	}

	@Test
	@Tag("valid")
	public void testSanitizeTrueStripThoughtsTrueRemoveDisplayName() {
		Blob blobWithDisplayName = Blob.builder()
			.data(Optional.of(new byte[] { 5, 4, 3 }))
			.mimeType(Optional.of("type/xyz"))
			.displayName(Optional.of("BlobFile")) // TODO
			.build();
		Part blobPart = Part.builder().inlineData(Optional.of(blobWithDisplayName)).thought(Optional.of(false)).build();
		FileData fileDataWithDisplayName = FileData.builder()
			.fileUri(Optional.of("uri://something"))
			.mimeType(Optional.of("app/unknown"))
			.displayName(Optional.of("FileDisplay")) // TODO
			.build();
		Part filePart = Part.builder()
			.fileData(Optional.of(fileDataWithDisplayName))
			.thought(Optional.of(false))
			.build();
		Part thoughtPart = Part.builder().text(Optional.of("Irrelevant")).thought(Optional.of(true)).build();
		Content nonUserContent = Content.builder()
			.role(ASSISTANT_ROLE)
			.parts(ImmutableList.of(blobPart, filePart, thoughtPart))
			.build();
		LlmRequest input = LlmRequest.builder().contents(ImmutableList.of(nonUserContent)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(input, true, true);
		List<Content> output = result.contents();
		// Should have original content with sanitized blob/file, no thought part, and
		// appended user
		// content
		assertEquals(2, output.size());
		Content sanitizedContent = output.get(0);
		ImmutableList<Part> sanitizedParts = sanitizedContent.parts().get();
		assertEquals(2, sanitizedParts.size());
		assertTrue(sanitizedParts.stream().noneMatch(part -> part.thought().orElse(false)));
		Blob blobSanitized = sanitizedParts.get(0).inlineData().get();
		assertTrue(blobSanitized.displayName().isEmpty());
		FileData fileSanitized = sanitizedParts.get(1).fileData().get();
		assertTrue(fileSanitized.displayName().isEmpty());
		Content appendedUser = output.get(1);
		assertEquals(USER_ROLE, appendedUser.role().get());
		assertEquals(GeminiUtil.CONTINUE_OUTPUT_MESSAGE, appendedUser.parts().get().get(0).text().get());
	}

	@Test
	@Tag("integration")
	public void testSanitizeFalseStripThoughtsFalsePreserveAll() {
		Part p1 = Part.fromText("First content");
		Part p2 = Part.builder().text(Optional.of("second")).thought(Optional.of(true)).build();
		Content c1 = Content.builder().role(ASSISTANT_ROLE).parts(ImmutableList.of(p1, p2)).build();
		Part p3 = Part.builder().text(Optional.of("third")).thought(Optional.of(false)).build();
		Content c2 = Content.builder().role(ASSISTANT_ROLE).parts(ImmutableList.of(p3)).build();
		LlmRequest input = LlmRequest.builder().contents(ImmutableList.of(c1, c2)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(input, false, false);
		List<Content> resultContents = result.contents();
		assertEquals(3, resultContents.size());
		for (int i = 0; i < 2; i++) {
			Content orig = input.contents().get(i);
			Content res = resultContents.get(i);
			assertEquals(orig.role(), res.role());
			assertEquals(orig.parts().get().size(), res.parts().get().size());
			for (int j = 0; j < orig.parts().get().size(); ++j) {
				assertEquals(orig.parts().get().get(j).text(), res.parts().get().get(j).text());
			}
		}
		Content appendedUser = resultContents.get(2);
		assertEquals(USER_ROLE, appendedUser.role().get());
		assertEquals(GeminiUtil.CONTINUE_OUTPUT_MESSAGE, appendedUser.parts().get().get(0).text().get());
	}

	@Test
	@Tag("valid")
	public void testSanitizeTrueConfigLabelsPresent() {
		GenerateContentConfig configWithLabels = GenerateContentConfig.builder()
			.labels(ImmutableMap.of("foo", "bar"))
			.build();
		LlmRequest input = LlmRequest.builder()
			.contents(ImmutableList.of())
			.config(Optional.of(configWithLabels))
			.build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(input, true, false);
		Optional<GenerateContentConfig> outConfigOpt = result.config();
		assertTrue(outConfigOpt.isPresent());
		GenerateContentConfig outConfig = outConfigOpt.get();
		assertEquals(0, outConfig.labels().get().size());
	}

	@Test
	@Tag("boundary")
	public void testContentNoPartsAppendUserContent() {
		Content c1 = Content.builder().role(ASSISTANT_ROLE).parts(Optional.empty()).build();
		Content c2 = Content.builder().role(ASSISTANT_ROLE).parts(ImmutableList.of()).build();
		LlmRequest input = LlmRequest.builder().contents(ImmutableList.of(c1, c2)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(input, false, true);
		List<Content> out = result.contents();
		assertEquals(3, out.size());
		assertTrue(out.get(0).parts().isEmpty() || out.get(0).parts().get().isEmpty());
		assertTrue(out.get(1).parts().isEmpty() || out.get(1).parts().get().isEmpty());
		Content appendedUser = out.get(2);
		assertEquals(USER_ROLE, appendedUser.role().get());
		assertEquals(GeminiUtil.CONTINUE_OUTPUT_MESSAGE, appendedUser.parts().get().get(0).text().get());
	}

	@Test
	@Tag("boundary")
	public void testOnlyThoughtPartsAllStrippedResultPartsEmpty() {
		Part thoughtPartA = Part.builder().text(Optional.of("Thought A")).thought(Optional.of(true)).build();
		Part thoughtPartB = Part.builder().text(Optional.of("Thought B")).thought(Optional.of(true)).build();
		Content c1 = Content.builder().role(USER_ROLE).parts(ImmutableList.of(thoughtPartA)).build();
		Content c2 = Content.builder().role(USER_ROLE).parts(ImmutableList.of(thoughtPartB)).build();
		LlmRequest input = LlmRequest.builder().contents(ImmutableList.of(c1, c2)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(input, false, true);
		List<Content> out = result.contents();
		assertEquals(2, out.size());
		out.forEach(content -> assertTrue(content.parts().get().isEmpty()));
	}

	@Test
	@Tag("boundary")
	public void testLastContentRoleCaseInsensitiveUserNoAppend() {
		Content c1 = Content.builder().role("User").parts(ImmutableList.of(Part.fromText("Hello"))).build();
		Content c2 = Content.builder().role("USER").parts(ImmutableList.of(Part.fromText("World"))).build();
		LlmRequest input = LlmRequest.builder().contents(ImmutableList.of(c1, c2)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(input, false, false);
		assertEquals(2, result.contents().size());
		assertEquals("USER", result.contents().get(1).role().get());
	}

	@Test
	@Tag("valid")
	public void testEmptyContentConfigLabelsSanitizeAndThoughts() {
		GenerateContentConfig configWithLabels = GenerateContentConfig.builder()
			.labels(ImmutableMap.of("a", "b", "x", "y"))
			.build();
		LlmRequest input = LlmRequest.builder()
			.contents(ImmutableList.of())
			.config(Optional.of(configWithLabels))
			.build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(input, true, true);
		assertEquals(1, result.contents().size());
		Content userContent = result.contents().get(0);
		assertEquals(USER_ROLE, userContent.role().get());
		Part part = userContent.parts().get().get(0);
		assertEquals(GeminiUtil.CONTINUE_OUTPUT_MESSAGE, part.text().get());
		assertTrue(result.config().isPresent());
		assertEquals(0, result.config().get().labels().get().size());
	}

	@Test
	@Tag("valid")
	public void testSingleUserPartNoSanitizeNoStrip() {
		Part part = Part.fromText("Single Part");
		Content c = Content.builder().role(USER_ROLE).parts(ImmutableList.of(part)).build();
		LlmRequest input = LlmRequest.builder().contents(ImmutableList.of(c)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(input, false, false);
		assertEquals(1, result.contents().size());
		Content outContent = result.contents().get(0);
		assertEquals(USER_ROLE, outContent.role().get());
		assertEquals("Single Part", outContent.parts().get().get(0).text().get());
	}

	@Test
	@Tag("boundary")
	public void testContentWithNoRoleResultsInUserContentAppended() {
		Content c1 = Content.builder().parts(ImmutableList.of(Part.fromText("Part1"))).build();
		Content c2 = Content.builder().parts(ImmutableList.of(Part.fromText("Part2"))).build();
		LlmRequest input = LlmRequest.builder().contents(ImmutableList.of(c1, c2)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(input, false, false);
		assertEquals(3, result.contents().size());
		Content appendedUser = result.contents().get(2);
		assertEquals(USER_ROLE, appendedUser.role().get());
		assertEquals(GeminiUtil.CONTINUE_OUTPUT_MESSAGE, appendedUser.parts().get().get(0).text().get());
	}

	@Test
	@Tag("boundary")
	public void testEmptyContentsNoSanitizeNoStrip() {
		LlmRequest input = LlmRequest.builder().contents(ImmutableList.of()).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(input, false, false);
		assertEquals(1, result.contents().size());
		Content userContent = result.contents().get(0);
		assertEquals(USER_ROLE, userContent.role().get());
		Part part = userContent.parts().get().get(0);
		assertEquals(GeminiUtil.CONTINUE_OUTPUT_MESSAGE, part.text().get());
	}

	@Test
	@Tag("valid")
	public void testMixedContentPartialThoughtsStrip() {
		Part t1 = Part.builder().text(Optional.of("T1")).thought(Optional.of(true)).build();
		Part n1 = Part.builder().text(Optional.of("N1")).thought(Optional.of(false)).build();
		Content c1 = Content.builder().role(ASSISTANT_ROLE).parts(ImmutableList.of(t1, n1)).build();
		Part n2 = Part.builder().text(Optional.of("N2")).build();
		Content c2 = Content.builder().role(ASSISTANT_ROLE).parts(ImmutableList.of(n2)).build();
		Content c3 = Content.builder().role(ASSISTANT_ROLE).parts(ImmutableList.of()).build();
		LlmRequest input = LlmRequest.builder().contents(ImmutableList.of(c1, c2, c3)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(input, false, true);
		List<Content> out = result.contents();
		assertEquals(4, out.size());
		ImmutableList<Part> partsC1 = out.get(0).parts().get();
		assertEquals(1, partsC1.size());
		assertTrue(partsC1.get(0).thought().orElse(false) == false);
		ImmutableList<Part> partsC2 = out.get(1).parts().get();
		assertEquals(1, partsC2.size());
		assertTrue(partsC2.get(0).thought().isEmpty());
		ImmutableList<Part> partsC3 = out.get(2).parts().get();
		assertEquals(0, partsC3.size());
		Content appendedUser = out.get(3);
		assertEquals(USER_ROLE, appendedUser.role().get());
		assertEquals(GeminiUtil.CONTINUE_OUTPUT_MESSAGE, appendedUser.parts().get().get(0).text().get());
	}

	@Test
	@Tag("boundary")
	public void testNonUserFinalContentWithThoughtOnlyThenAppendUser() {
		Part thoughtOnly = Part.builder().text(Optional.of("Secret thought")).thought(Optional.of(true)).build();
		Content assistantThoughtContent = Content.builder()
			.role(ASSISTANT_ROLE)
			.parts(ImmutableList.of(thoughtOnly))
			.build();
		LlmRequest input = LlmRequest.builder().contents(ImmutableList.of(assistantThoughtContent)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(input, false, true);
		assertEquals(2, result.contents().size());
		Content strippedContent = result.contents().get(0);
		assertTrue(strippedContent.parts().get().isEmpty());
		Content appendedUser = result.contents().get(1);
		assertEquals(USER_ROLE, appendedUser.role().get());
		assertEquals(GeminiUtil.CONTINUE_OUTPUT_MESSAGE, appendedUser.parts().get().get(0).text().get());
	}

}
