/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test maven-adkjava-github using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=sanitizeRequestForGeminiApi_d79761c834
ROOST_METHOD_SIG_HASH=sanitizeRequestForGeminiApi_b033ad6a3c

Scenario 1: Sanitizing a Request with Empty Contents List

Details:
  TestName: sanitizeRequestWithEmptyContents
  Description: This test checks the behavior of sanitizeRequestForGeminiApi when the LlmRequest has an empty contents list. It ensures the method does not throw and correctly propagates changes only to the config (if applicable), with contents remaining empty.
Execution:
  Arrange: Create an LlmRequest with an empty contents list and a basic config object.
  Act: Invoke sanitizeRequestForGeminiApi with that LlmRequest.
  Assert: Verify that the returned LlmRequest still has an empty contents list and other fields are unaltered except for potential config label cleanup.
Validation:
  The assertion is focused on confirming the method's early-return logic for empty content, ensuring defensive handling and no modifications to unintended fields. This is vital for preventing regressions when the input has no content parts.

Scenario 2: Removing Config Labels When Present

Details:
  TestName: removeConfigLabelsIfPresent
  Description: Checks if sanitizeRequestForGeminiApi correctly removes config labels from the request by emptying them when config.labels() is present in the input.
Execution:
  Arrange: Create an LlmRequest with a config object containing non-empty labels, and at least one dummy content.
  Act: Call sanitizeRequestForGeminiApi with this request.
  Assert: Validate that the returned request's config has labels as an empty ImmutableMap.
Validation:
  This assertion is important to guarantee compatibility with Gemini API requirements (no labels in config), preventing backend errors.

Scenario 3: Contents Parts List is Empty or Not Present

Details:
  TestName: handleContentsWithNoParts
  Description: Assess if the sanitizer avoids altering content when contents.parts() field is empty or non-present (Optional.empty()).
Execution:
  Arrange: Construct an LlmRequest with contents, but for each Content the parts field is either not set or an empty Optional.
  Act: Pass this request to sanitizeRequestForGeminiApi.
  Assert: Check that the parts field remains untouched and no additional alterations are made.
Validation:
  This confirms the method only transforms the necessary objects when present, respecting content structure and avoiding null or optional-related failures.

Scenario 4: Stripping DisplayName from Blob.inlineData

Details:
  TestName: removeInlineDataDisplayNameIfPresent
  Description: Verifies that the method removes the displayName property if present on a Blob object within each Part's inlineData field. Other Blob fields like data and mimeType are preserved.
Execution:
  Arrange: Compose an LlmRequest with a Content containing a Part holding a Blob with data, mimeType, and displayName all set.
  Act: Use sanitizeRequestForGeminiApi on the request.
  Assert: The output LlmRequest's Blob should no longer have displayName, but should keep data and mimeType.
Validation:
  The assertion ensures compliance with backend restrictions on displayName in inlineData, stopping possible rejections at the Gemini API.

Scenario 5: Stripping DisplayName from FileData.fileData

Details:
  TestName: removeFileDataDisplayNameIfPresent
  Description: Tests that when fileData().displayName() is present in a Part, sanitizeRequestForGeminiApi strips only this attribute, keeping fileUri and mimeType untouched.
Execution:
  Arrange: Build an LlmRequest with a Part containing FileData; set fileUri, mimeType, and displayName to values.
  Act: Pass the request to sanitizeRequestForGeminiApi.
  Assert: Ensure displayName is removed from the resulting FileData, but fileUri and mimeType are preserved.
Validation:
  This ensures only restricted fields (displayName) are removed, maintaining required file attachment data for Gemini API operations.

Scenario 6: Preserving Blobs and FileData without DisplayName

Details:
  TestName: keepBlobsAndFileDataWithoutDisplayName
  Description: Checks the sanitizer leaves Blob and FileData objects untouched if displayName is absent (i.e., Optional.empty()).
Execution:
  Arrange: Formulate an LlmRequest with Blobs and FileData, omitting displayName. Set data and mimeType as appropriate.
  Act: Call sanitizeRequestForGeminiApi.
  Assert: All fields are preserved, and no attributes are removed since displayName is not present.
Validation:
  Verifies no data loss or field mutation occurs unnecessarily, protecting valid request attributes.

Scenario 7: Multiple Contents and Parts Sanitization

Details:
  TestName: sanitizeMultipleContentsAndParts
  Description: Validates correct iterative operation, ensuring that displaying name is removed from all eligible Blobs and FileData across multiple Content and Part objects in a request.
Execution:
  Arrange: Make an LlmRequest with several Content entries, each with several Parts, distributed with a mixture of displayName presence on inlineData and fileData.
  Act: Apply sanitizeRequestForGeminiApi.
  Assert: Confirm all displayNames are consistently stripped where present, with other metadata intact.
Validation:
  Ensures scaler logic applies throughout hierarchies, fulfilling bulk sanitization requirements typical of true Gemini requests.

Scenario 8: Request with No Config

Details:
  TestName: handleRequestWithoutConfig
  Description: Tests method behavior when the incoming LlmRequest has no config object, i.e., config() returns Optional.empty().
Execution:
  Arrange: Create an LlmRequest without setting the config field but with some contents.
  Act: Call sanitizeRequestForGeminiApi.
  Assert: Ensure the request is processed without error and contents are sanitized as needed, while config remains empty.
Validation:
  Essential to confirm appropriate handling of optional config and that content sanitation is not skipped or cascaded incorrectly when no config is present.

Scenario 9: Content has Multiple Parts with Mixed InlineData and FileData

Details:
  TestName: sanitizeMixedBlobAndFileDataParts
  Description: Examines that sanitizer correctly processes Content with several Parts, some having Blob with displayName, some with FileData with displayName, and some without either.
Execution:
  Arrange: Construct Contents where various combinations of Blob and FileData with and without displayName occur across Parts.
  Act: Use sanitizeRequestForGeminiApi on this request.
  Assert: Only the displayName fields are removed wherever present; unrelated Parts remain unchanged.
Validation:
  Checks that the sanitizer handles mixed scenarios and only alters the relevant fields, preserving integrity elsewhere.

Scenario 10: Maintain Other LlmRequest Fields Unchanged

Details:
  TestName: preserveUnrelatedFields
  Description: Ensures that fields of LlmRequest other than config.labels, contents.parts.inlineData.displayName, and contents.parts.fileData.displayName are not unintentionally modified.
Execution:
  Arrange: Create LlmRequest with additional fields set to arbitrary values.
  Act: Pass this request to sanitizeRequestForGeminiApi.
  Assert: Validate that all fields not specifically subject to sanitization remain exactly the same.
Validation:
  Prevents regressions where the sanitizer would mutate fields outside its intended scope, securing request consistency.

Scenario 11: Original Request is Not Mutated

Details:
  TestName: inputRequestIsImmutable
  Description: Verifies that the input LlmRequest and its child objects (config, content, part, blob, fileData) are not mutated after the sanitizer runs.
Execution:
  Arrange: Build the original LlmRequest and keep references. Call sanitizeRequestForGeminiApi.
  Act: Inspect the original object structure and values (apart from the resulting sanitized version).
  Assert: Assert that no field in the original objects has been changed.
Validation:
  This enforces immutability and safe functional-style transformations, protecting from unexpected side-effects in the calling code.

Scenario 12: All Possible Combination of Part Data

Details:
  TestName: handleAllPartDataCombinations
  Description: Examines a Part with only text (no Blob or FileData), one with Blob only, one with FileData only, and one with both Blob and FileData (with/without displayName).
Execution:
  Arrange: Set up an LlmRequest with a Content having four Parts, each representing a unique combination.
  Act: Sanitize the request.
  Assert: Confirm only those attributes relevant to displayName are pruned, and all other combinations are left as-is.
Validation:
  Asserts completeness of scope in sanitizer logic, ensuring no data is lost from parts with only textual or other data.

Scenario 13: Labels in Config is Already Empty

Details:
  TestName: skipLabelSanitizationIfAlreadyEmpty
  Description: When the config.labels() is already an empty map, confirms no redundant mutation, and the object is returned as expected.
Execution:
  Arrange: LlmRequest with config.labels set to empty ImmutableMap.
  Act: Call sanitizeRequestForGeminiApi.
  Assert: The output config.labels remains empty, and no new object instance is unnecessarily created if semantics dictate.
Validation:
  Verifies sanitizer idempotence for this field, ensuring efficiency and preventing complex chaining side-effects.

Scenario 14: Part Contains No InlineData or FileData

Details:
  TestName: skipPartWithoutBlobOrFileData
  Description: If a Part does not contain inlineData nor fileData, ensures the sanitizer does not perform unnecessary operations or create replacements.
Execution:
  Arrange: Create a request with such Part.
  Act: Run the sanitizer.
  Assert: Same part object or equal values is present.
Validation:
  Guards against wasteful or incorrect logic when optional fields are not applicable.

Scenario 15: DisplayName Present But Optional is Empty

Details:
  TestName: doNotSanitizeWhenDisplayNameOptionalIsEmpty
  Description: Checks that if Blob.inlineData() or FileData.fileData() is present but their displayName() returns Optional.empty(), sanitizer does not alter these fields.
Execution:
  Arrange: Request with Blob and FileData, each with displayName absent (Optional.empty).
  Act: Call sanitizer.
  Assert: No sanitization or field removal takes place in this scenario.
Validation:
  Validates correct handling of Java Optionals, preventing accidental removal of valid attributes.

Scenario 16: Content Without Parts Optional Field

Details:
  TestName: handleContentWithoutPartsField
  Description: Covers a Content object where parts() field itself is not present (i.e., returns Optional.empty()), ensuring the method skips sanitization and retains content as-is.
Execution:
  Arrange: LlmRequest with Content where parts() returns Optional.empty().
  Act: Sanitize the LlmRequest.
  Assert: The Content object is unchanged after sanitization.
Validation:
  Validates robust handling of incomplete or variably composed model objects, making the utility resilient.

Scenario 17: Large Nested Structure Performance/Correctness

Details:
  TestName: sanitizeLargeDeeplyNestedStructure
  Description: Simulate a large request with many nested Contents and deeply nested Parts, many of which include displayName, to ensure sanitizer can scale and does not drop data.
Execution:
  Arrange: Build a sizable LlmRequest with several hundred Contents and Parts, some repeated displayName presence.
  Act: Run sanitizeRequestForGeminiApi.
  Assert: Performance remains reasonable, and all applicable displayNames are removed.
Validation:
  Confirms reliability and scalability, ensuring the utility remains suitable for large batch operations typical in production.


*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.*;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import com.google.genai.types.Blob;
import com.google.genai.types.Content;
import com.google.genai.types.FileData;
import com.google.genai.types.Part;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class GeminiUtilSanitizeRequestForGeminiApiTest {

	@Test
	@Tag("boundary")
	public void testSanitizeRequestWithEmptyContents() {
		GenerateContentConfig config = GenerateContentConfig.builder()
			.labels(Optional.of(ImmutableMap.of("foo", "bar")))
			.build();
		LlmRequest request = LlmRequest.builder().contents(ImmutableList.of()).config(Optional.of(config)).build();
		LlmRequest result = GeminiUtil.sanitizeRequestForGeminiApi(request);
		assertEquals(0, ((List<?>) result.contents()).size(), "Contents list should be empty");
		assertTrue(result.config().isPresent(), "Config should be present");
		assertTrue(result.config().get().labels().isPresent(), "Labels should be present after sanitization");
		assertEquals(ImmutableMap.of(), result.config().get().labels().get(), "Labels should be empty map");
	}

	@Test
	@Tag("valid")
	public void testRemoveConfigLabelsIfPresent() {
		Map<String, String> labels = ImmutableMap.of("label1", "value1");
		GenerateContentConfig config = GenerateContentConfig.builder().labels(Optional.of(labels)).build();
		Content content = Content.builder().parts(ImmutableList.of(Part.fromText("test"))).build();
		LlmRequest request = LlmRequest.builder()
			.config(Optional.of(config))
			.contents(ImmutableList.of(content))
			.build();
		LlmRequest result = GeminiUtil.sanitizeRequestForGeminiApi(request);
		assertTrue(result.config().isPresent());
		assertTrue(result.config().get().labels().isPresent());
		assertEquals(ImmutableMap.of(), result.config().get().labels().get());
	}

	@Test
	@Tag("valid")
	public void testHandleContentsWithNoParts() {
		Content content = Content.builder().parts(Optional.empty()).build();
		LlmRequest request = LlmRequest.builder().contents(ImmutableList.of(content)).build();
		LlmRequest result = GeminiUtil.sanitizeRequestForGeminiApi(request);
		assertEquals(content, result.contents().get(0), "Content without parts should remain the same");
	}

	@Test
	@Tag("valid")
	public void testRemoveInlineDataDisplayNameIfPresent() {
		Blob blob = Blob.builder()
			.data(Optional.of("BINARY_DATA"))
			.mimeType(Optional.of("image/png"))
			.displayName(Optional.of("displayname"))
			.build();
		Part part = Part.builder().inlineData(Optional.of(blob)).build();
		Content content = Content.builder().parts(ImmutableList.of(part)).build();
		LlmRequest request = LlmRequest.builder().contents(ImmutableList.of(content)).build();
		LlmRequest result = GeminiUtil.sanitizeRequestForGeminiApi(request);
		Blob sanitizedBlob = result.contents().get(0).parts().get().get(0).inlineData().get();
		assertTrue(sanitizedBlob.data().isPresent());
		assertEquals(blob.data().get(), sanitizedBlob.data().get());
		assertTrue(sanitizedBlob.mimeType().isPresent());
		assertEquals(blob.mimeType().get(), sanitizedBlob.mimeType().get());
		assertTrue(sanitizedBlob.displayName().isEmpty(), "displayName must be removed");
	}

	@Test
	@Tag("valid")
	public void testRemoveFileDataDisplayNameIfPresent() {
		FileData fileData = FileData.builder()
			.fileUri(Optional.of("file://test-uri"))
			.mimeType(Optional.of("application/pdf"))
			.displayName(Optional.of("ShouldBeRemoved"))
			.build();
		Part part = Part.builder().fileData(Optional.of(fileData)).build();
		Content content = Content.builder().parts(ImmutableList.of(part)).build();
		LlmRequest request = LlmRequest.builder().contents(ImmutableList.of(content)).build();
		LlmRequest result = GeminiUtil.sanitizeRequestForGeminiApi(request);
		FileData sanitizedFileData = result.contents().get(0).parts().get().get(0).fileData().get();
		assertTrue(sanitizedFileData.fileUri().isPresent());
		assertEquals(fileData.fileUri().get(), sanitizedFileData.fileUri().get());
		assertTrue(sanitizedFileData.mimeType().isPresent());
		assertEquals(fileData.mimeType().get(), sanitizedFileData.mimeType().get());
		assertTrue(sanitizedFileData.displayName().isEmpty(), "displayName must be removed");
	}

	@Test
	@Tag("valid")
	public void testKeepBlobsAndFileDataWithoutDisplayName() {
		Blob blob = Blob.builder()
			.data(Optional.of("BINARY_DATA"))
			.mimeType(Optional.of("image/png"))
			.displayName(Optional.empty())
			.build();
		FileData fileData = FileData.builder()
			.fileUri(Optional.of("file://test-uri"))
			.mimeType(Optional.of("application/pdf"))
			.displayName(Optional.empty())
			.build();
		Part part = Part.builder().inlineData(Optional.of(blob)).fileData(Optional.of(fileData)).build();
		Content content = Content.builder().parts(ImmutableList.of(part)).build();
		LlmRequest request = LlmRequest.builder().contents(ImmutableList.of(content)).build();
		LlmRequest result = GeminiUtil.sanitizeRequestForGeminiApi(request);
		Part sanitizedPart = result.contents().get(0).parts().get().get(0);
		assertTrue(sanitizedPart.inlineData().isPresent());
		assertTrue(sanitizedPart.inlineData().get().displayName().isEmpty());
		assertTrue(sanitizedPart.fileData().isPresent());
		assertTrue(sanitizedPart.fileData().get().displayName().isEmpty());
		assertEquals(blob.data().get(), sanitizedPart.inlineData().get().data().get());
		assertEquals(fileData.fileUri().get(), sanitizedPart.fileData().get().fileUri().get());
	}

	@Test
	@Tag("valid")
	public void testSanitizeMultipleContentsAndParts() {
		Blob blobWithDisplayName = Blob.builder()
			.data(Optional.of("data"))
			.mimeType(Optional.of("mime"))
			.displayName(Optional.of("name"))
			.build();
		Blob blobNoDisplayName = Blob.builder()
			.data(Optional.of("dataND"))
			.mimeType(Optional.of("mimeND"))
			.displayName(Optional.empty())
			.build();
		FileData fdWithDisplayName = FileData.builder()
			.fileUri(Optional.of("uri"))
			.mimeType(Optional.of("mime"))
			.displayName(Optional.of("name"))
			.build();
		FileData fdNoDisplayName = FileData.builder()
			.fileUri(Optional.of("uriND"))
			.mimeType(Optional.of("mimeND"))
			.displayName(Optional.empty())
			.build();
		Part p1 = Part.builder().inlineData(Optional.of(blobWithDisplayName)).build();
		Part p2 = Part.builder().inlineData(Optional.of(blobNoDisplayName)).build();
		Part p3 = Part.builder().fileData(Optional.of(fdWithDisplayName)).build();
		Part p4 = Part.builder().fileData(Optional.of(fdNoDisplayName)).build();
		Content c1 = Content.builder().parts(ImmutableList.of(p1, p2)).build();
		Content c2 = Content.builder().parts(ImmutableList.of(p3, p4)).build();
		LlmRequest request = LlmRequest.builder().contents(ImmutableList.of(c1, c2)).build();
		LlmRequest result = GeminiUtil.sanitizeRequestForGeminiApi(request);
		List<Content> contents = result.contents();
		Blob sanitizedBlob = contents.get(0).parts().get().get(0).inlineData().get();
		assertTrue(sanitizedBlob.displayName().isEmpty());
		assertEquals("data", sanitizedBlob.data().get());
		Blob sanitizedBlobNoDisplay = contents.get(0).parts().get().get(1).inlineData().get();
		assertTrue(sanitizedBlobNoDisplay.displayName().isEmpty());
		assertEquals("dataND", sanitizedBlobNoDisplay.data().get());
		FileData sanitizedFd = contents.get(1).parts().get().get(0).fileData().get();
		assertTrue(sanitizedFd.displayName().isEmpty());
		assertEquals("uri", sanitizedFd.fileUri().get());
		FileData sanitizedFdNoName = contents.get(1).parts().get().get(1).fileData().get();
		assertTrue(sanitizedFdNoName.displayName().isEmpty());
		assertEquals("uriND", sanitizedFdNoName.fileUri().get());
	}

	@Test
	@Tag("boundary")
	public void testHandleRequestWithoutConfig() {
		Part part = Part.fromText("Hello!");
		Content content = Content.builder().parts(ImmutableList.of(part)).build();
		LlmRequest request = LlmRequest.builder().contents(ImmutableList.of(content)).config(Optional.empty()).build();
		LlmRequest result = GeminiUtil.sanitizeRequestForGeminiApi(request);
		assertTrue(result.config().isEmpty(), "Config should remain empty");
		assertEquals(content.parts(), result.contents().get(0).parts());
	}

	@Test
	@Tag("valid")
	public void testSanitizeMixedBlobAndFileDataParts() {
		Blob blobWithDisplayName = Blob.builder()
			.data(Optional.of("data"))
			.mimeType(Optional.of("mime"))
			.displayName(Optional.of("name"))
			.build();
		FileData fdWithDisplayName = FileData.builder()
			.fileUri(Optional.of("uri"))
			.mimeType(Optional.of("mime"))
			.displayName(Optional.of("name"))
			.build();
		Part p1 = Part.builder().inlineData(Optional.of(blobWithDisplayName)).fileData(Optional.empty()).build();
		Part p2 = Part.builder().inlineData(Optional.empty()).fileData(Optional.of(fdWithDisplayName)).build();
		Part p3 = Part.builder().build(); // No blob or fileData
		Content content = Content.builder().parts(ImmutableList.of(p1, p2, p3)).build();
		LlmRequest request = LlmRequest.builder().contents(ImmutableList.of(content)).build();
		LlmRequest result = GeminiUtil.sanitizeRequestForGeminiApi(request);
		Part sanitizedP1 = result.contents().get(0).parts().get().get(0);
		Part sanitizedP2 = result.contents().get(0).parts().get().get(1);
		Part sanitizedP3 = result.contents().get(0).parts().get().get(2);
		assertTrue(sanitizedP1.inlineData().isPresent());
		assertTrue(sanitizedP1.inlineData().get().displayName().isEmpty());
		assertTrue(sanitizedP2.fileData().isPresent());
		assertTrue(sanitizedP2.fileData().get().displayName().isEmpty());
		assertTrue(sanitizedP3.inlineData().isEmpty());
		assertTrue(sanitizedP3.fileData().isEmpty());
	}

	@Test
	@Tag("valid")
	public void testPreserveUnrelatedFields() {
		Part part = Part.fromText("test");
		Content content = Content.builder().parts(ImmutableList.of(part)).role("user").build();
		LlmRequest request = LlmRequest.builder()
			.contents(ImmutableList.of(content))
			.liveConnectConfig(LiveConnectConfig.builder().build())
			.tools(ImmutableMap.of("dummyTool", new BaseTool() {
			})) // TODO: Set meaningful dummy tool instance if needed
			.build();
		LlmRequest result = GeminiUtil.sanitizeRequestForGeminiApi(request);
		assertEquals(request.liveConnectConfig(), result.liveConnectConfig());
		assertEquals(request.tools(), result.tools());
		assertEquals(content.role(), result.contents().get(0).role());
	}

	@Test
	@Tag("valid")
	public void testInputRequestIsImmutable() {
		Blob blob = Blob.builder()
			.displayName(Optional.of("name"))
			.data(Optional.of("d"))
			.mimeType(Optional.of("mime"))
			.build();
		Part part = Part.builder().inlineData(Optional.of(blob)).build();
		Content content = Content.builder().parts(ImmutableList.of(part)).build();
		LlmRequest originalRequest = LlmRequest.builder().contents(ImmutableList.of(content)).build();
		GeminiUtil.sanitizeRequestForGeminiApi(originalRequest);
		assertTrue(originalRequest.contents().get(0).parts().get().get(0).inlineData().get().displayName().isPresent());
		assertEquals("name",
				originalRequest.contents().get(0).parts().get().get(0).inlineData().get().displayName().get());
	}

	@Test
	@Tag("valid")
	public void testHandleAllPartDataCombinations() {
		Part onlyTextPart = Part.fromText("text");
		Blob onlyBlob = Blob.builder().displayName(Optional.of("name")).data(Optional.of("data")).build();
		Part onlyBlobPart = Part.builder().inlineData(Optional.of(onlyBlob)).build();
		FileData onlyFileData = FileData.builder()
			.displayName(Optional.of("fdname"))
			.fileUri(Optional.of("uri"))
			.build();
		Part onlyFileDataPart = Part.builder().fileData(Optional.of(onlyFileData)).build();
		Blob bothBlob = Blob.builder().displayName(Optional.of("bname")).data(Optional.of("data")).build();
		FileData bothFileData = FileData.builder()
			.displayName(Optional.of("fdname2"))
			.fileUri(Optional.of("uri2"))
			.build();
		Part bothPart = Part.builder().inlineData(Optional.of(bothBlob)).fileData(Optional.of(bothFileData)).build();
		Content content = Content.builder()
			.parts(ImmutableList.of(onlyTextPart, onlyBlobPart, onlyFileDataPart, bothPart))
			.build();
		LlmRequest request = LlmRequest.builder().contents(ImmutableList.of(content)).build();
		LlmRequest result = GeminiUtil.sanitizeRequestForGeminiApi(request);
		List<Part> parts = result.contents().get(0).parts().get();
		assertTrue(parts.get(0).text().isPresent());
		assertTrue(parts.get(1).inlineData().isPresent());
		assertTrue(parts.get(1).inlineData().get().displayName().isEmpty());
		assertTrue(parts.get(2).fileData().isPresent());
		assertTrue(parts.get(2).fileData().get().displayName().isEmpty());
		assertTrue(parts.get(3).inlineData().get().displayName().isEmpty());
		assertTrue(parts.get(3).fileData().get().displayName().isEmpty());
	}

	@Test
	@Tag("boundary")
	public void testSkipLabelSanitizationIfAlreadyEmpty() {
		GenerateContentConfig config = GenerateContentConfig.builder().labels(Optional.of(ImmutableMap.of())).build();
		Content content = Content.builder().parts(ImmutableList.of(Part.fromText("test"))).build();
		LlmRequest request = LlmRequest.builder()
			.config(Optional.of(config))
			.contents(ImmutableList.of(content))
			.build();
		LlmRequest result = GeminiUtil.sanitizeRequestForGeminiApi(request);
		assertEquals(ImmutableMap.of(), result.config().get().labels().get());
	}

	@Test
	@Tag("valid")
	public void testSkipPartWithoutBlobOrFileData() {
		Part part = Part.builder().build();
		Content content = Content.builder().parts(ImmutableList.of(part)).build();
		LlmRequest request = LlmRequest.builder().contents(ImmutableList.of(content)).build();
		LlmRequest result = GeminiUtil.sanitizeRequestForGeminiApi(request);
		Part sanitizedPart = result.contents().get(0).parts().get().get(0);
		assertTrue(sanitizedPart.inlineData().isEmpty());
		assertTrue(sanitizedPart.fileData().isEmpty());
	}

	@Test
	@Tag("valid")
	public void testDoNotSanitizeWhenDisplayNameOptionalIsEmpty() {
		Blob blob = Blob.builder()
			.data(Optional.of("BINARY_DATA"))
			.mimeType(Optional.of("image/png"))
			.displayName(Optional.empty())
			.build();
		FileData fileData = FileData.builder()
			.fileUri(Optional.of("file://test-uri"))
			.mimeType(Optional.of("application/pdf"))
			.displayName(Optional.empty())
			.build();
		Part part = Part.builder().inlineData(Optional.of(blob)).fileData(Optional.of(fileData)).build();
		Content content = Content.builder().parts(ImmutableList.of(part)).build();
		LlmRequest request = LlmRequest.builder().contents(ImmutableList.of(content)).build();
		LlmRequest result = GeminiUtil.sanitizeRequestForGeminiApi(request);
		Part sanitizedPart = result.contents().get(0).parts().get().get(0);
		assertTrue(sanitizedPart.inlineData().isPresent());
		assertTrue(sanitizedPart.inlineData().get().displayName().isEmpty());
		assertTrue(sanitizedPart.fileData().isPresent());
		assertTrue(sanitizedPart.fileData().get().displayName().isEmpty());
	}

	@Test
	@Tag("boundary")
	public void testHandleContentWithoutPartsField() {
		Content content = Content.builder().parts(Optional.empty()).build();
		LlmRequest request = LlmRequest.builder().contents(ImmutableList.of(content)).build();
		LlmRequest result = GeminiUtil.sanitizeRequestForGeminiApi(request);
		assertEquals(content, result.contents().get(0));
	}

	@Test
	@Tag("integration")
	public void testSanitizeLargeDeeplyNestedStructure() {
		ImmutableList.Builder<Content> contentBuilder = ImmutableList.builder();
		for (int i = 0; i < 500; i++) {
			ImmutableList.Builder<Part> partBuilder = ImmutableList.builder();
			for (int j = 0; j < 5; j++) {
				String dnValue = (j % 2 == 0) ? "DN" + i + "_" + j : null;
				Blob blob = Blob.builder()
					.data(Optional.of("B" + i + "_" + j))
					.mimeType(Optional.of("image/png"))
					.displayName(Optional.ofNullable(dnValue))
					.build();
				partBuilder.add(Part.builder().inlineData(Optional.of(blob)).build());
			}
			contentBuilder.add(Content.builder().parts(partBuilder.build()).build());
		}
		LlmRequest request = LlmRequest.builder().contents(contentBuilder.build()).build();
		LlmRequest result = GeminiUtil.sanitizeRequestForGeminiApi(request);
		for (Content c : result.contents()) {
			for (Part p : c.parts().get()) {
				assertTrue(p.inlineData().isPresent());
				assertTrue(p.inlineData().get().displayName().isEmpty());
			}
		}
	}

}
