/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-maven-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=builder_2187989d2f
ROOST_METHOD_SIG_HASH=builder_80041265ae

Scenario 1: Successfully Create Builder Instance

Details:
  TestName: builderReturnsNewBuilderInstance
  Description: This test verifies that the builder() static method successfully creates and returns a new Builder instance. It checks that the method returns a non-null Builder object that can be used to construct Gemini instances.
Execution:
  Arrange: No setup required as this is a static factory method.
  Act: Invoke Gemini.builder() to obtain a Builder instance.
  Assert: Use assertNotNull to verify that the returned Builder instance is not null.
Validation:
  The assertion verifies that the builder() method correctly instantiates and returns a Builder object. This is critical as the Builder pattern is the primary way to construct Gemini instances with various configuration options. The test ensures that clients can always obtain a valid Builder to start the construction process.

Scenario 2: Builder Returns Different Instances on Multiple Calls

Details:
  TestName: builderReturnsNewInstanceOnEachCall
  Description: This test ensures that each call to the builder() method returns a distinct Builder instance, preventing shared state between different builder instances. This verifies that the factory method creates fresh instances rather than reusing a singleton.
Execution:
  Arrange: No setup required.
  Act: Call Gemini.builder() twice to obtain two Builder instances.
  Assert: Use assertNotSame to verify that the two Builder instances are different objects.
Validation:
  This assertion confirms that the builder() method follows the standard factory pattern by creating new instances on each invocation. This is important to prevent unintended state sharing between different Gemini construction processes. If the same instance were returned, modifications to one builder could affect another, leading to unpredictable behavior.

Scenario 3: Builder Instance is of Correct Type

Details:
  TestName: builderReturnsCorrectType
  Description: This test validates that the object returned by the builder() method is actually an instance of the Gemini.Builder class, ensuring type safety and correct implementation.
Execution:
  Arrange: No setup required.
  Act: Invoke Gemini.builder() to get a Builder instance.
  Assert: Use assertInstanceOf or assertTrue with instanceof to verify the returned object is of type Gemini.Builder.
Validation:
  This assertion ensures type correctness of the factory method's return value. It verifies that the builder() method returns the expected Builder type, which is essential for compile-time and runtime type safety. This test would catch any implementation errors where the wrong type might be returned.

Scenario 4: Builder Can Be Used to Set Model Name

Details:
  TestName: builderAllowsModelNameConfiguration
  Description: This test verifies that the Builder instance returned by builder() can be used to configure the model name through method chaining, which is a fundamental requirement of the builder pattern.
Execution:
  Arrange: No setup required.
  Act: Call Gemini.builder() and then invoke modelName() method on the returned Builder with a test model name.
  Assert: Verify that the modelName() method returns a Builder instance (for method chaining) using assertNotNull.
Validation:
  This test ensures that the Builder returned by the factory method is fully functional and supports the fluent API pattern. The ability to chain method calls is a key characteristic of the builder pattern, and this test confirms that the Builder instance is properly initialized and ready for configuration.

Scenario 5: Builder Can Be Used to Set API Key

Details:
  TestName: builderAllowsApiKeyConfiguration
  Description: This test confirms that the Builder instance obtained from builder() supports setting an API key through the apiKey() method, enabling authentication configuration.
Execution:
  Arrange: No setup required.
  Act: Call Gemini.builder() and then invoke apiKey() method with a test API key string.
  Assert: Verify that the apiKey() method returns a Builder instance using assertNotNull.
Validation:
  This assertion validates that the Builder supports API key configuration, which is one of the primary authentication methods for the Gemini API. The test ensures that the Builder instance is properly initialized to accept and store API key credentials for subsequent Gemini instance creation.

Scenario 6: Builder Can Be Used to Set API Client

Details:
  TestName: builderAllowsApiClientConfiguration
  Description: This test verifies that the Builder returned by builder() can accept a custom Client instance through the apiClient() method, allowing advanced configuration scenarios.
Execution:
  Arrange: Create a mock or stub Client instance.
  Act: Call Gemini.builder() and invoke apiClient() method with the Client instance.
  Assert: Verify that the apiClient() method returns a Builder instance using assertNotNull.
Validation:
  This test ensures that the Builder supports explicit Client configuration, which is the highest priority authentication method according to the class documentation. This flexibility is important for scenarios where clients need custom HTTP configurations, retry policies, or other advanced settings.

Scenario 7: Builder Can Be Used to Set Vertex Credentials

Details:
  TestName: builderAllowsVertexCredentialsConfiguration
  Description: This test confirms that the Builder instance supports setting Vertex AI credentials through the vertexCredentials() method, enabling Vertex AI authentication.
Execution:
  Arrange: Create a mock or stub VertexCredentials instance.
  Act: Call Gemini.builder() and invoke vertexCredentials() method with the credentials.
  Assert: Verify that the vertexCredentials() method returns a Builder instance using assertNotNull.
Validation:
  This assertion validates that the Builder supports Vertex AI credential configuration, which is an alternative authentication method for accessing Gemini models through Google Cloud's Vertex AI platform. The test ensures the Builder is properly initialized to handle this authentication approach.

Scenario 8: Builder Supports Method Chaining for Multiple Configurations

Details:
  TestName: builderSupportsMethodChaining
  Description: This test verifies that the Builder returned by builder() supports fluent method chaining by setting multiple configuration options in sequence.
Execution:
  Arrange: Prepare test values for model name and API key.
  Act: Call Gemini.builder().modelName(testModelName).apiKey(testApiKey).
  Assert: Verify that the final result is a non-null Builder instance using assertNotNull.
Validation:
  This test confirms that the Builder implements the fluent interface pattern correctly, allowing multiple configuration methods to be chained together. This is a fundamental characteristic of the builder pattern and essential for providing a clean, readable API for constructing Gemini instances with multiple configuration options.

Scenario 9: Builder Instance Can Be Stored and Reused

Details:
  TestName: builderInstanceCanBeStoredAndReused
  Description: This test verifies that a Builder instance obtained from builder() can be stored in a variable and reused for multiple configuration calls, supporting flexible construction patterns.
Execution:
  Arrange: No setup required.
  Act: Call Gemini.builder() and store the result in a variable, then invoke multiple configuration methods on the stored instance.
  Assert: Verify that each method call returns a non-null Builder instance using assertNotNull.
Validation:
  This test ensures that Builder instances maintain their state correctly and can be used in scenarios where configuration is built up over multiple statements rather than in a single fluent chain. This flexibility is important for complex construction scenarios where configuration values might come from different sources.

Scenario 10: Multiple Builders Can Be Created Independently

Details:
  TestName: multipleBuilderInstancesAreIndependent
  Description: This test verifies that multiple Builder instances created by calling builder() multiple times are independent and do not share state, ensuring isolation between different construction processes.
Execution:
  Arrange: No setup required.
  Act: Create two Builder instances by calling Gemini.builder() twice, configure each with different values.
  Assert: Verify that both builders are non-null and are different instances using assertNotNull and assertNotSame.
Validation:
  This test confirms that the builder() factory method creates truly independent Builder instances, preventing any potential state leakage between different Gemini construction processes. This is critical for thread safety and preventing unexpected behavior when multiple Gemini instances are being constructed concurrently or sequentially in the same application.

*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNotSame;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;

import com.google.genai.Client;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class GeminiBuilderTest {

  @Test
  @Tag("valid")
  void builderReturnsNewBuilderInstance() {
    // Arrange - No setup required as this is a static factory method
    // Act
    Gemini.Builder builder = Gemini.builder();
    // Assert
    assertNotNull(builder, "Builder instance should not be null");
  }

  @Test
  @Tag("valid")
  void builderReturnsNewInstanceOnEachCall() {
    // Arrange - No setup required
    // Act
    Gemini.Builder builder1 = Gemini.builder();
    Gemini.Builder builder2 = Gemini.builder();
    // Assert
    assertNotSame(builder1, builder2, "Each call to builder() should return a different instance");
  }

  @Test
  @Tag("valid")
  void builderReturnsCorrectType() {
    // Arrange - No setup required
    // Act
    Gemini.Builder builder = Gemini.builder();
    // Assert
    assertTrue(
        builder instanceof Gemini.Builder,
        "Returned object should be an instance of Gemini.Builder");
  }

  @Test
  @Tag("valid")
  void builderAllowsModelNameConfiguration() {
    // Arrange
    String testModelName = "gemini-pro";
    // Act
    Gemini.Builder builder = Gemini.builder();
    Gemini.Builder result = builder.modelName(testModelName);
    // Assert
    assertNotNull(
        result, "modelName() should return a non-null Builder instance for method chaining");
  }

  @Test
  @Tag("valid")
  void builderAllowsApiKeyConfiguration() {
    // Arrange
    String testApiKey = "test-api-key-12345";
    // Act
    Gemini.Builder builder = Gemini.builder();
    Gemini.Builder result = builder.apiKey(testApiKey);
    // Assert
    assertNotNull(result, "apiKey() should return a non-null Builder instance for method chaining");
  }

  @Test
  @Tag("valid")
  void builderAllowsApiClientConfiguration() {
    // Arrange
    Client mockClient = mock(Client.class);
    // Act
    Gemini.Builder builder = Gemini.builder();
    Gemini.Builder result = builder.apiClient(mockClient);
    // Assert
    assertNotNull(
        result, "apiClient() should return a non-null Builder instance for method chaining");
  }

  @Test
  @Tag("valid")
  void builderAllowsVertexCredentialsConfiguration() {
    // Arrange
    VertexCredentials mockCredentials = mock(VertexCredentials.class);
    // Act
    Gemini.Builder builder = Gemini.builder();
    Gemini.Builder result = builder.vertexCredentials(mockCredentials);
    // Assert
    assertNotNull(
        result,
        "vertexCredentials() should return a non-null Builder instance for method chaining");
  }

  @Test
  @Tag("valid")
  void builderSupportsMethodChaining() {
    // Arrange
    String testModelName = "gemini-pro";
    String testApiKey = "test-api-key-12345";
    // Act
    Gemini.Builder result = Gemini.builder().modelName(testModelName).apiKey(testApiKey);
    // Assert
    assertNotNull(result, "Method chaining should return a non-null Builder instance");
  }

  @Test
  @Tag("valid")
  void builderInstanceCanBeStoredAndReused() {
    // Arrange
    String testModelName = "gemini-pro";
    String testApiKey = "test-api-key-12345";
    // Act
    Gemini.Builder builder = Gemini.builder();
    Gemini.Builder result1 = builder.modelName(testModelName);
    Gemini.Builder result2 = builder.apiKey(testApiKey);
    // Assert
    assertNotNull(result1, "First configuration method should return a non-null Builder instance");
    assertNotNull(result2, "Second configuration method should return a non-null Builder instance");
  }

  @Test
  @Tag("valid")
  void multipleBuilderInstancesAreIndependent() {
    // Arrange
    String modelName1 = "gemini-pro";
    String modelName2 = "gemini-ultra";
    String apiKey1 = "api-key-1";
    String apiKey2 = "api-key-2";
    // Act
    Gemini.Builder builder1 = Gemini.builder();
    builder1.modelName(modelName1).apiKey(apiKey1);
    Gemini.Builder builder2 = Gemini.builder();
    builder2.modelName(modelName2).apiKey(apiKey2);
    // Assert
    assertNotNull(builder1, "First builder instance should not be null");
    assertNotNull(builder2, "Second builder instance should not be null");
    assertNotSame(
        builder1, builder2, "Builder instances should be independent and not share state");
  }

  @Test
  @Tag("valid")
  void builderSupportsComplexMethodChainingWithMultipleConfigurations() {
    // Arrange
    String testModelName = "gemini-pro";
    String testApiKey = "test-api-key-12345";
    Client mockClient = mock(Client.class);
    // Act
    Gemini.Builder result =
        Gemini.builder().modelName(testModelName).apiKey(testApiKey).apiClient(mockClient);
    // Assert
    assertNotNull(result, "Complex method chaining should return a non-null Builder instance");
  }

  @Test
  @Tag("valid")
  void builderCanBeCreatedMultipleTimesInSequence() {
    // Arrange - No setup required
    // Act
    Gemini.Builder builder1 = Gemini.builder();
    Gemini.Builder builder2 = Gemini.builder();
    Gemini.Builder builder3 = Gemini.builder();
    // Assert
    assertNotNull(builder1, "First builder should not be null");
    assertNotNull(builder2, "Second builder should not be null");
    assertNotNull(builder3, "Third builder should not be null");
    assertNotSame(builder1, builder2, "First and second builders should be different instances");
    assertNotSame(builder2, builder3, "Second and third builders should be different instances");
    assertNotSame(builder1, builder3, "First and third builders should be different instances");
  }

  @Test
  @Tag("valid")
  void builderSupportsAllConfigurationMethodsInChain() {
    // Arrange
    String testModelName = "gemini-pro";
    String testApiKey = "test-api-key-12345";
    Client mockClient = mock(Client.class);
    VertexCredentials mockCredentials = mock(VertexCredentials.class);
    // Act
    Gemini.Builder result =
        Gemini.builder()
            .modelName(testModelName)
            .apiKey(testApiKey)
            .apiClient(mockClient)
            .vertexCredentials(mockCredentials);
    // Assert
    assertNotNull(result, "Builder should support all configuration methods in a chain");
  }
}
