/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test maven-adkjava-github using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=close_b12577365b
ROOST_METHOD_SIG_HASH=close_f5c48e2806

Scenario 1: Closing a GemeniLlmConnection before the session is established

Details:
  TestName: closeBeforeSessionEstablished
  Description: This test checks the behavior of calling the close() method when the connection's CompletableFuture<AsyncSession> (sessionFuture) is not yet completed. It simulates closing the connection right after object construction, before the session is established.
Execution:
  Arrange:
    - Mock all dependencies (Client, LiveConnectConfig, etc.).
    - Instantiate GeminiLlmConnection with mocks.
    - Optionally, ensure the sessionFuture is not completed (i.e., isDone() returns false).
  Act:
    - Call the close() method on the GeminiLlmConnection instance.
  Assert:
    - Verify that closed becomes true.
    - Confirm that sessionFuture.cancel(false) is called.
    - Assert that responseProcessor.onComplete() is called.
  Validation:
    This validates that resources are properly freed and the connection is marked as closed even if the session was never established, preventing resource leaks or further state transitions after closure.

Scenario 2: Closing a GeminiLlmConnection after the session is established but before any messages are exchanged

Details:
  TestName: closeAfterSessionEstablished
  Description: This test ensures that close() correctly finishes the connection if the AsyncSession is already established but no data has been exchanged yet. It checks cleanup steps for already-completed sessionFuture.
Execution:
  Arrange:
    - Mock dependencies.
    - Instantiate GeminiLlmConnection.
    - Complete sessionFuture to indicate a ready AsyncSession.
    - Ensure closed is false.
  Act:
    - Call close() on the GeminiLlmConnection instance.
  Assert:
    - closed is set to true.
    - sessionFuture.thenAccept(...) is called with the session to do closure.
    - responseProcessor.onComplete() is called.
  Validation:
    This validates that, when closed, the session’s resources are released and observers are notified completion even in the best-case immediate connection scenario.

Scenario 3: Closing after connection error has already occurred

Details:
  TestName: closeAfterConnectionError
  Description: This test verifies that calling close() after a connection error does not perform double-close logic. It ensures that closeInternal runs only once using AtomicBoolean.
Execution:
  Arrange:
    - Instantiate and initialize GeminiLlmConnection.
    - Simulate a previous connection error so closed is already true (possibly by calling closeInternal with a throwable or via error handling method).
  Act:
    - Call close() again on the same instance.
  Assert:
    - closed remains true.
    - No further calls to responseProcessor.onComplete() or onError().
    - No additional attempts to cancel/close sessionFuture.
  Validation:
    This validation checks idempotency of the close operation and guards against accidental double resource release or multiple notifications to subscribers.

Scenario 4: Closing a GeminiLlmConnection with active subscribers on its responseFlowable

Details:
  TestName: closeWithActiveSubscribers
  Description: This test ensures that closing the connection (via close()) notifies all active observers of the Flowable with an onComplete event. It checks RxJava contract adherence.
Execution:
  Arrange:
    - Mock dependencies and sessionFuture.
    - Instantiate GeminiLlmConnection.
    - Subscribe mock observers/consumers to responseFlowable.
  Act:
    - Call close() on the instance.
  Assert:
    - All observers receive onComplete notification.
    - The connection is marked as closed.
  Validation:
    This ensures that all subscribers are properly notified of completion, allowing clients to clean up and stop expecting further emissions.

Scenario 5: Verifying thread-safety of close() under concurrent calls

Details:
  TestName: closeIsThreadSafe
  Description: This test aims to ensure that close() remains thread-safe and idempotent if invoked concurrently from different threads.
Execution:
  Arrange:
    - Mock and instantiate GeminiLlmConnection.
    - (Optionally) setup sessionFuture for both isDone = true/false cases.
  Act:
    - Spawn multiple threads calling close() simultaneously.
  Assert:
    - Only one thread executes cleanup logic (responseProcessor.onComplete / sessionFuture cancellation/closure).
    - closed is true at the end, and no observable side effects occur due to racing.
  Validation:
    Thread-safety validation protects against race-condition-induced resource leaks or inconsistent states in a multi-threaded environment.

Scenario 6: Ensuring close() does not throw if already closed

Details:
  TestName: closeDoesNotThrowIfAlreadyClosed
  Description: This test checks that invoking close() repeatedly (after closure) does not throw exceptions or cause erroneous behavior.
Execution:
  Arrange:
    - Instantiate GeminiLlmConnection.
    - Call close() once.
  Act:
    - Call close() again.
  Assert:
    - No exceptions or errors are thrown.
    - No repeated calls/effects.
  Validation:
    This guards against regressions where calling close multiple times could destabilize the object or produce runtime errors.

Scenario 7: ResponseProcessor receives onComplete with null Throwable

Details:
  TestName: responseProcessorCompletesWhenThrowableIsNull
  Description: This test validates that if close() is called (which invokes closeInternal with null), responseProcessor.onComplete() is triggered rather than onError.
Execution:
  Arrange:
    - Mock responseProcessor.
    - (Optionally) ensure sessionFuture and closed are set to trigger correct path.
  Act:
    - Call close() on the connection.
  Assert:
    - responseProcessor.onComplete() invoked, and onError() not called.
  Validation:
    This ensures that RxJava subscribers are signaled for successful completion, as per method’s intent, when no error condition exists.

Scenario 8: Session future is cancelled if not yet completed on close

Details:
  TestName: sessionFutureCancelledIfNotDone
  Description: Verifies that if the internal sessionFuture has not yet completed when close() is called, it is properly cancelled.
Execution:
  Arrange:
    - Mock sessionFuture (isDone() returns false).
    - Instantiate GeminiLlmConnection.
  Act:
    - Call close().
  Assert:
    - sessionFuture.cancel(false) is called.
  Validation:
    Ensures proper resource management to avoid holding open session attempts or memory leaks when the user abandons the connection early.

Scenario 9: Session is closed if future is done when close() called

Details:
  TestName: closeSessionIfSessionFutureDone
  Description: Checks that if close() is called and the sessionFuture was completed, the AsyncSession’s close operations are triggered.
Execution:
  Arrange:
    - sessionFuture is completed with a mock AsyncSession.
    - The session supports close() method.
    - Instantiate GeminiLlmConnection.
  Act:
    - Call close().
  Assert:
    - closeSessionIgnoringErrors is invoked with the session.
  Validation:
    Ensures that application does not leak session resources for sessions already connected at shutdown.

Scenario 10: Verify logger debug invocation on close

Details:
  TestName: loggerDebugCalledOnClose
  Description: Validates that GeminiLlmConnection logs a debug message when close() is called, helpful for diagnosis and monitoring.
Execution:
  Arrange:
    - Use a mock logger.
    - Instantiate GeminiLlmConnection.
  Act:
    - Call close().
  Assert:
    - logger.debug("Closing GeminiConnection.", null) is invoked at appropriate point.
  Validation:
    Logging on closure can help in monitoring and understanding lifecycle issues in production scenarios.

Scenario 11: ResponseProcessor and session not notified if already closed

Details:
  TestName: noNotificationOnSubsequentClose
  Description: Checks that calling close() after the connection is already closed does not result in repeated RxJava or session cleanups.
Execution:
  Arrange:
    - Instantiate GeminiLlmConnection.
    - Call close() once to close it.
  Act:
    - Call close() again.
  Assert:
    - responseProcessor is not signaled again.
    - sessionFuture.cancel or closeSessionIgnoringErrors is not called again.
  Validation:
    Strengthens contract adherence regarding single-close semantics, important for reliable connection lifecycle handling in applications.

*/

// ********RoostGPT********

package com.google.adk.models;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.*;
import com.google.genai.AsyncSession;
import com.google.genai.Client;
import com.google.genai.types.LiveConnectConfig;
import io.reactivex.rxjava3.processors.PublishProcessor;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.InOrder;
import org.mockito.Mockito;
import java.util.Objects;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.atomic.AtomicBoolean;
import org.slf4j.Logger;
import org.junit.jupiter.api.*;
import static com.google.common.collect.ImmutableList.toImmutableList;
import com.google.common.collect.ImmutableList;
import com.google.genai.types.Blob;
import com.google.genai.types.Content;
import com.google.genai.types.FinishReason;
import com.google.genai.types.FunctionCall;
import com.google.genai.types.FunctionResponse;
import com.google.genai.types.LiveSendClientContentParameters;
import com.google.genai.types.LiveSendRealtimeInputParameters;
import com.google.genai.types.LiveSendToolResponseParameters;
import com.google.genai.types.LiveServerContent;
import com.google.genai.types.LiveServerMessage;
import com.google.genai.types.LiveServerToolCall;
import com.google.genai.types.Part;
import io.reactivex.rxjava3.core.Completable;
import io.reactivex.rxjava3.core.Flowable;
import java.net.SocketException;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CompletionException;
import org.slf4j.LoggerFactory;

public class GeminiLlmConnectionCloseTest {

	@Test
    @Tag("boundary")
    public void testCloseBeforeSessionEstablished() {
        Client client = mock(Client.class, RETURNS_DEEP_STUBS);
        LiveConnectConfig connectConfig = mock(LiveConnectConfig.class);
        PublishProcessor responseProcessor = mock(PublishProcessor.class);
        String modelName = "test-model"; // TODO: replace with actual model name if needed
        // Override GeminiLlmConnection internals for testability
        GeminiLlmConnection conn = Mockito.spy(
            new GeminiLlmConnection(client, modelName, connectConfig)
        );
        CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
        AtomicBoolean closed = new AtomicBoolean(false);
        doReturn(sessionFuture).when(conn).sessionFuture;
        doReturn(closed).when(conn).closed;
        doReturn(responseProcessor).when(conn).responseProcessor;
        when(sessionFuture.isDone()).thenReturn(false);
        conn.close();
        verify(sessionFuture).cancel(false);
        verify(responseProcessor).onComplete();
        assert ((AtomicBoolean)conn.closed).get();
    }

	@Test
    @Tag("boundary")
    public void testCloseAfterSessionEstablished() {
        Client client = mock(Client.class, RETURNS_DEEP_STUBS);
        LiveConnectConfig connectConfig = mock(LiveConnectConfig.class);
        PublishProcessor responseProcessor = mock(PublishProcessor.class);
        AsyncSession session = mock(AsyncSession.class);
        String modelName = "test-model"; // TODO: replace with actual model name if needed
        GeminiLlmConnection conn = Mockito.spy(
            new GeminiLlmConnection(client, modelName, connectConfig)
        );
        CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
        AtomicBoolean closed = new AtomicBoolean(false);
        doReturn(sessionFuture).when(conn).sessionFuture;
        doReturn(closed).when(conn).closed;
        doReturn(responseProcessor).when(conn).responseProcessor;
        when(sessionFuture.isDone()).thenReturn(true);
        when(sessionFuture.thenAccept(any())).thenAnswer(invocation -> {
            ((java.util.function.Consumer<AsyncSession>)invocation.getArgument(0)).accept(session);
            return null;
        });
        conn.close();
        verify(sessionFuture, never()).cancel(false);
        verify(sessionFuture).thenAccept(any());
        verify(responseProcessor).onComplete();
        assert ((AtomicBoolean)conn.closed).get();
    }

	@Test
    @Tag("boundary")
    public void testCloseAfterConnectionError() {
        Client client = mock(Client.class, RETURNS_DEEP_STUBS);
        LiveConnectConfig connectConfig = mock(LiveConnectConfig.class);
        PublishProcessor responseProcessor = mock(PublishProcessor.class);
        String modelName = "test-model"; // TODO: replace with actual model name if needed
        GeminiLlmConnection conn = Mockito.spy(
            new GeminiLlmConnection(client, modelName, connectConfig)
        );
        CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
        AtomicBoolean closed = new AtomicBoolean(true);
        doReturn(sessionFuture).when(conn).sessionFuture;
        doReturn(closed).when(conn).closed;
        doReturn(responseProcessor).when(conn).responseProcessor;
        conn.close();
        verify(responseProcessor, never()).onComplete();
        verify(responseProcessor, never()).onError(any());
        verify(sessionFuture, never()).cancel(false);
        verify(sessionFuture, never()).thenAccept(any());
        assert ((AtomicBoolean)conn.closed).get();
    }

	@Test
    @Tag("integration")
    public void testCloseWithActiveSubscribers() {
        Client client = mock(Client.class, RETURNS_DEEP_STUBS);
        LiveConnectConfig connectConfig = mock(LiveConnectConfig.class);
        String modelName = "test-model"; // TODO: replace with actual model name if needed
        GeminiLlmConnection conn = Mockito.spy(
            new GeminiLlmConnection(client, modelName, connectConfig)
        );
        PublishProcessor responseProcessor = PublishProcessor.create();
        CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
        doReturn(sessionFuture).when(conn).sessionFuture;
        doReturn(responseProcessor).when(conn).responseProcessor;
        doReturn(new AtomicBoolean(false)).when(conn).closed;
        AtomicBoolean onCompleteCalled = new AtomicBoolean(false);
        AtomicBoolean onNextCalled = new AtomicBoolean(false);
        conn.receive().subscribe(
            data -> onNextCalled.set(true),
            throwable -> {},
            () -> onCompleteCalled.set(true)
        );
        conn.close();
        assert onCompleteCalled.get();
        assert ((AtomicBoolean)conn.closed).get();
    }

	@Test
    @Tag("boundary")
    public void testCloseIsThreadSafe() throws Exception {
        Client client = mock(Client.class, RETURNS_DEEP_STUBS);
        LiveConnectConfig connectConfig = mock(LiveConnectConfig.class);
        String modelName = "test-model"; // TODO: replace with actual model name if needed
        GeminiLlmConnection conn = Mockito.spy(
            new GeminiLlmConnection(client, modelName, connectConfig)
        );
        PublishProcessor responseProcessor = mock(PublishProcessor.class);
        CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
        AtomicBoolean closed = new AtomicBoolean(false);
        doReturn(sessionFuture).when(conn).sessionFuture;
        doReturn(closed).when(conn).closed;
        doReturn(responseProcessor).when(conn).responseProcessor;
        when(sessionFuture.isDone()).thenReturn(false);
        Runnable closeAction = conn::close;
        Thread t1 = new Thread(closeAction);
        Thread t2 = new Thread(closeAction);
        Thread t3 = new Thread(closeAction);
        t1.start(); t2.start(); t3.start();
        t1.join(); t2.join(); t3.join();
        verify(sessionFuture, atLeastOnce()).cancel(false);
        verify(responseProcessor, atLeastOnce()).onComplete();
        assert ((AtomicBoolean)conn.closed).get();
    }

	@Test
    @Tag("boundary")
    public void testCloseDoesNotThrowIfAlreadyClosed() {
        Client client = mock(Client.class, RETURNS_DEEP_STUBS);
        LiveConnectConfig connectConfig = mock(LiveConnectConfig.class);
        String modelName = "test-model"; // TODO: replace with actual model name if needed
        GeminiLlmConnection conn = Mockito.spy(
            new GeminiLlmConnection(client, modelName, connectConfig)
        );
        PublishProcessor responseProcessor = mock(PublishProcessor.class);
        CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
        AtomicBoolean closed = new AtomicBoolean(false);
        doReturn(sessionFuture).when(conn).sessionFuture;
        doReturn(closed).when(conn).closed;
        doReturn(responseProcessor).when(conn).responseProcessor;
        conn.close();
        conn.close();
        verify(responseProcessor, times(1)).onComplete();
        verify(sessionFuture, times(1)).cancel(false);
        assert ((AtomicBoolean)conn.closed).get();
    }

	@Test
    @Tag("valid")
    public void testResponseProcessorCompletesWhenThrowableIsNull() {
        Client client = mock(Client.class, RETURNS_DEEP_STUBS);
        LiveConnectConfig connectConfig = mock(LiveConnectConfig.class);
        String modelName = "test-model"; // TODO: replace with actual model name if needed
        GeminiLlmConnection conn = Mockito.spy(
            new GeminiLlmConnection(client, modelName, connectConfig)
        );
        PublishProcessor responseProcessor = mock(PublishProcessor.class);
        CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
        AtomicBoolean closed = new AtomicBoolean(false);
        doReturn(sessionFuture).when(conn).sessionFuture;
        doReturn(closed).when(conn).closed;
        doReturn(responseProcessor).when(conn).responseProcessor;
        conn.close();
        verify(responseProcessor, times(1)).onComplete();
        verify(responseProcessor, never()).onError(any());
    }

	@Test
    @Tag("boundary")
    public void testSessionFutureCancelledIfNotDone() {
        Client client = mock(Client.class, RETURNS_DEEP_STUBS);
        LiveConnectConfig connectConfig = mock(LiveConnectConfig.class);
        String modelName = "test-model"; // TODO: replace with actual model name if needed
        GeminiLlmConnection conn = Mockito.spy(
            new GeminiLlmConnection(client, modelName, connectConfig)
        );
        PublishProcessor responseProcessor = mock(PublishProcessor.class);
        CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
        AtomicBoolean closed = new AtomicBoolean(false);
        doReturn(sessionFuture).when(conn).sessionFuture;
        doReturn(closed).when(conn).closed;
        doReturn(responseProcessor).when(conn).responseProcessor;
        when(sessionFuture.isDone()).thenReturn(false);
        conn.close();
        verify(sessionFuture, times(1)).cancel(false);
    }

	@Test
    @Tag("integration")
    public void testCloseSessionIfSessionFutureDone() {
        Client client = mock(Client.class, RETURNS_DEEP_STUBS);
        LiveConnectConfig connectConfig = mock(LiveConnectConfig.class);
        AsyncSession session = mock(AsyncSession.class);
        String modelName = "test-model"; // TODO: replace with actual model name if needed
        GeminiLlmConnection conn = Mockito.spy(
            new GeminiLlmConnection(client, modelName, connectConfig)
        );
        PublishProcessor responseProcessor = mock(PublishProcessor.class);
        CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
        AtomicBoolean closed = new AtomicBoolean(false);
        doReturn(sessionFuture).when(conn).sessionFuture;
        doReturn(closed).when(conn).closed;
        doReturn(responseProcessor).when(conn).responseProcessor;
        when(sessionFuture.isDone()).thenReturn(true);
        when(sessionFuture.thenAccept(any())).thenAnswer(invocation -> {
            ((java.util.function.Consumer<AsyncSession>)invocation.getArgument(0)).accept(session);
            return null;
        });
        conn.close();
        verify(sessionFuture, never()).cancel(false);
        verify(sessionFuture).thenAccept(any());
        verify(responseProcessor).onComplete();
        assert ((AtomicBoolean)conn.closed).get();
    }

	@Test
    @Tag("valid")
    public void testLoggerDebugCalledOnClose() {
        Client client = mock(Client.class, RETURNS_DEEP_STUBS);
        LiveConnectConfig connectConfig = mock(LiveConnectConfig.class);
        String modelName = "test-model"; // TODO: replace with actual model name if needed
        Logger logger = mock(Logger.class);
        GeminiLlmConnection conn = Mockito.spy(
            new GeminiLlmConnection(client, modelName, connectConfig)
        );
        PublishProcessor responseProcessor = mock(PublishProcessor.class);
        CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
        AtomicBoolean closed = new AtomicBoolean(false);
        doReturn(sessionFuture).when(conn).sessionFuture;
        doReturn(closed).when(conn).closed;
        doReturn(responseProcessor).when(conn).responseProcessor;
        doReturn(logger).when(conn).logger;
        conn.close();
        verify(logger).debug(eq("Closing GeminiConnection."), eq(null));
    }

	@Test
    @Tag("boundary")
    public void testNoNotificationOnSubsequentClose() {
        Client client = mock(Client.class, RETURNS_DEEP_STUBS);
        LiveConnectConfig connectConfig = mock(LiveConnectConfig.class);
        String modelName = "test-model"; // TODO: replace with actual model name if needed
        GeminiLlmConnection conn = Mockito.spy(
            new GeminiLlmConnection(client, modelName, connectConfig)
        );
        PublishProcessor responseProcessor = mock(PublishProcessor.class);
        CompletableFuture<AsyncSession> sessionFuture = mock(CompletableFuture.class);
        AtomicBoolean closed = new AtomicBoolean(false);
        doReturn(sessionFuture).when(conn).sessionFuture;
        doReturn(closed).when(conn).closed;
        doReturn(responseProcessor).when(conn).responseProcessor;
        when(sessionFuture.isDone()).thenReturn(false);
        conn.close();
        conn.close();
        verify(responseProcessor, times(1)).onComplete();
        verify(sessionFuture, times(1)).cancel(false);
    }

}