/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-dec-17-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=prepareGenenerateContentRequest_3310317bd1
ROOST_METHOD_SIG_HASH=prepareGenenerateContentRequest_1be48efb9a

Scenario 1: Valid LlmRequest with sanitize true

Details:
  TestName: prepareGenerateContentRequestWithValidRequestAndSanitizeTrue
  Description: This test verifies that when a valid LlmRequest is provided with sanitize parameter set to true, the method correctly delegates to the overloaded prepareGenenerateContentRequest method with sanitize=true and stripThoughts=true as default parameters.
Execution:
  Arrange: Create a valid LlmRequest object with sample content containing user role and text parts. Set sanitize parameter to true.
  Act: Invoke prepareGenenerateContentRequest(llmRequest, true) method.
  Assert: Verify that the returned LlmRequest is not null and that the method processes the request correctly by checking that contents are present and properly formatted.
Validation:
  The assertion verifies that the method successfully delegates to the three-parameter overload with stripThoughts defaulted to true. This ensures backward compatibility and proper default behavior when the two-parameter method is called. This is significant as it maintains the expected API behavior for existing code that uses the two-parameter version.

Scenario 2: Valid LlmRequest with sanitize false

Details:
  TestName: prepareGenerateContentRequestWithValidRequestAndSanitizeFalse
  Description: This test checks that when a valid LlmRequest is provided with sanitize parameter set to false, the method correctly passes this parameter to the overloaded method without applying sanitization logic.
Execution:
  Arrange: Create a valid LlmRequest object with content that includes display names in FileData and Blob objects. Set sanitize parameter to false.
  Act: Invoke prepareGenenerateContentRequest(llmRequest, false) method.
  Assert: Verify that the returned LlmRequest maintains the original display names and other properties that would be removed during sanitization.
Validation:
  This assertion confirms that when sanitize is false, the request is not modified by sanitization logic, preserving all original data including display names. This is important for scenarios where the request is being sent to backends that support these additional parameters, such as Vertex AI.

Scenario 3: LlmRequest with empty contents list and sanitize true

Details:
  TestName: prepareGenerateContentRequestWithEmptyContentsAndSanitizeTrue
  Description: This test validates the behavior when an LlmRequest with an empty contents list is provided with sanitize set to true, ensuring the method handles edge cases gracefully.
Execution:
  Arrange: Create an LlmRequest object with an empty contents list. Set sanitize parameter to true.
  Act: Invoke prepareGenenerateContentRequest(llmRequest, true) method.
  Assert: Verify that the returned LlmRequest contains a user content with CONTINUE_OUTPUT_MESSAGE to ensure model response.
Validation:
  The assertion verifies that the method properly handles empty content lists by adding a default user message to prompt model response. This is critical for maintaining API compatibility and ensuring the model always has appropriate input to generate a response.

Scenario 4: LlmRequest with last content role as model and sanitize true

Details:
  TestName: prepareGenerateContentRequestWithLastContentRoleAsModelAndSanitizeTrue
  Description: This test ensures that when the last content in the request has a role of "model" instead of "user", the method appends a user content with CONTINUE_OUTPUT_MESSAGE.
Execution:
  Arrange: Create an LlmRequest with multiple Content objects where the last one has role "model". Set sanitize parameter to true.
  Act: Invoke prepareGenenerateContentRequest(llmRequest, true) method.
  Assert: Verify that the returned LlmRequest has an additional user content appended at the end with CONTINUE_OUTPUT_MESSAGE.
Validation:
  This assertion confirms that the method correctly identifies when the last content is not from the user and adds the necessary prompt to ensure the model generates a response. This is essential for proper conversation flow in the Gemini API.

Scenario 5: LlmRequest with last content role as user and sanitize true

Details:
  TestName: prepareGenerateContentRequestWithLastContentRoleAsUserAndSanitizeTrue
  Description: This test verifies that when the last content already has a "user" role, no additional content is appended to the request.
Execution:
  Arrange: Create an LlmRequest with multiple Content objects where the last one has role "user". Set sanitize parameter to true.
  Act: Invoke prepareGenenerateContentRequest(llmRequest, true) method.
  Assert: Verify that the returned LlmRequest has the same number of contents as the original request without any additional user content appended.
Validation:
  The assertion ensures that the method does not unnecessarily modify requests that already end with user content, maintaining efficiency and avoiding redundant data. This is important for optimizing API calls and maintaining clean conversation history.

Scenario 6: LlmRequest with content containing inline data with display name and sanitize true

Details:
  TestName: prepareGenerateContentRequestWithInlineDataDisplayNameAndSanitizeTrue
  Description: This test validates that when sanitize is true, display names in Blob objects within inline data are properly removed to ensure Gemini API compatibility.
Execution:
  Arrange: Create an LlmRequest with Content containing Part objects that have inlineData with Blob objects including displayName. Set sanitize parameter to true.
  Act: Invoke prepareGenenerateContentRequest(llmRequest, true) method.
  Assert: Verify that the returned LlmRequest has the display names removed from all Blob objects in inline data while preserving other properties like data and mimeType.
Validation:
  This assertion confirms that the sanitization process correctly removes display names from inline data, which is necessary for Gemini API backend compatibility. This prevents runtime errors when sending requests to backends that don't support this parameter.

Scenario 7: LlmRequest with content containing file data with display name and sanitize true

Details:
  TestName: prepareGenerateContentRequestWithFileDataDisplayNameAndSanitizeTrue
  Description: This test ensures that when sanitize is true, display names in FileData objects are properly removed to maintain Gemini API compatibility.
Execution:
  Arrange: Create an LlmRequest with Content containing Part objects that have fileData with FileData objects including displayName. Set sanitize parameter to true.
  Act: Invoke prepareGenenerateContentRequest(llmRequest, true) method.
  Assert: Verify that the returned LlmRequest has the display names removed from all FileData objects while preserving fileUri and mimeType properties.
Validation:
  The assertion verifies that the sanitization logic correctly handles FileData objects by removing unsupported display names. This is crucial for preventing request failures when interacting with the Gemini API backend that doesn't support this parameter.

Scenario 8: LlmRequest with config containing labels and sanitize true

Details:
  TestName: prepareGenerateContentRequestWithConfigLabelsAndSanitizeTrue
  Description: This test checks that when sanitize is true and the request config contains labels, those labels are removed to ensure backend compatibility.
Execution:
  Arrange: Create an LlmRequest with a config object that includes labels in an ImmutableMap. Set sanitize parameter to true.
  Act: Invoke prepareGenenerateContentRequest(llmRequest, true) method.
  Assert: Verify that the returned LlmRequest has an empty labels map in the config while other config properties remain unchanged.
Validation:
  This assertion ensures that the sanitization process removes labels from the config when they are present, preventing compatibility issues with backends that don't support this feature. This is important for maintaining cross-backend compatibility.

Scenario 9: LlmRequest with null or empty parts in content and sanitize true

Details:
  TestName: prepareGenerateContentRequestWithEmptyPartsAndSanitizeTrue
  Description: This test validates the handling of Content objects that have empty or absent parts lists when sanitize is true.
Execution:
  Arrange: Create an LlmRequest with Content objects that have empty Optional parts or empty ImmutableList of parts. Set sanitize parameter to true.
  Act: Invoke prepareGenenerateContentRequest(llmRequest, true) method.
  Assert: Verify that the returned LlmRequest handles empty parts gracefully without throwing exceptions and maintains the content structure.
Validation:
  The assertion confirms that the method properly handles edge cases where content parts are empty or absent, ensuring robustness and preventing null pointer exceptions. This is essential for defensive programming and handling various input scenarios.

Scenario 10: LlmRequest with mixed content roles and sanitize false

Details:
  TestName: prepareGenerateContentRequestWithMixedRolesAndSanitizeFalse
  Description: This test verifies behavior when a request contains multiple contents with alternating user and model roles, with sanitize set to false.
Execution:
  Arrange: Create an LlmRequest with multiple Content objects having alternating "user" and "model" roles, ending with a model role. Set sanitize parameter to false.
  Act: Invoke prepareGenenerateContentRequest(llmRequest, false) method.
  Assert: Verify that the returned LlmRequest appends a user content with CONTINUE_OUTPUT_MESSAGE since the last role is not user, even though sanitize is false.
Validation:
  This assertion ensures that the ensureModelResponse logic is applied regardless of the sanitize parameter value, maintaining proper conversation flow. This is critical because ensuring the last message is from the user is a requirement for model response generation, independent of sanitization.

Scenario 11: LlmRequest with content containing thought parts and sanitize true

Details:
  TestName: prepareGenerateContentRequestWithThoughtPartsAndSanitizeTrue
  Description: This test validates that when stripThoughts is defaulted to true (via the two-parameter method), parts marked as thoughts are removed from the content.
Execution:
  Arrange: Create an LlmRequest with Content containing Part objects where some parts have the thought field set to true. Set sanitize parameter to true.
  Act: Invoke prepareGenenerateContentRequest(llmRequest, true) method.
  Assert: Verify that the returned LlmRequest has all parts with thought=true removed while preserving other parts.
Validation:
  The assertion confirms that the default behavior of the two-parameter method includes stripping thoughts, which is important for cleaning up internal reasoning steps before sending to the API. This ensures that only relevant content is included in the final request.

Scenario 12: LlmRequest with case-insensitive user role and sanitize true

Details:
  TestName: prepareGenerateContentRequestWithCaseInsensitiveUserRoleAndSanitizeTrue
  Description: This test ensures that the role comparison is case-insensitive when determining if the last content is from the user.
Execution:
  Arrange: Create an LlmRequest with the last Content having role "USER" (uppercase) or "UsEr" (mixed case). Set sanitize parameter to true.
  Act: Invoke prepareGenenerateContentRequest(llmRequest, true) method.
  Assert: Verify that the returned LlmRequest does not append an additional user content since the role comparison should be case-insensitive.
Validation:
  This assertion verifies that the method uses case-insensitive comparison (via Ascii.equalsIgnoreCase) when checking roles, ensuring robust handling of role strings regardless of casing. This is important for API flexibility and preventing unnecessary content additions.

Scenario 13: LlmRequest with content having absent role and sanitize true

Details:
  TestName: prepareGenerateContentRequestWithAbsentRoleAndSanitizeTrue
  Description: This test checks the behavior when Content objects have an absent role (empty Optional) with sanitize set to true.
Execution:
  Arrange: Create an LlmRequest with Content objects where the role is an empty Optional. Set sanitize parameter to true.
  Act: Invoke prepareGenenerateContentRequest(llmRequest, true) method.
  Assert: Verify that the returned LlmRequest appends a user content with CONTINUE_OUTPUT_MESSAGE since the absent role is treated as not being "user".
Validation:
  The assertion ensures that absent roles are handled correctly by treating them as non-user roles, which triggers the addition of a user prompt. This is important for handling malformed or incomplete content objects gracefully.

Scenario 14: LlmRequest with multiple parts including text and file data and sanitize true

Details:
  TestName: prepareGenerateContentRequestWithMultiplePartTypesAndSanitizeTrue
  Description: This test validates that the method correctly processes Content with multiple Part types (text, inline data, file data) when sanitize is true.
Execution:
  Arrange: Create an LlmRequest with Content containing multiple Part objects of different types: text parts, parts with inlineData, and parts with fileData. Set sanitize parameter to true.
  Act: Invoke prepareGenenerateContentRequest(llmRequest, true) method.
  Assert: Verify that the returned LlmRequest preserves all part types while applying appropriate sanitization (removing display names from Blob and FileData objects).
Validation:
  This assertion confirms that the method handles heterogeneous part collections correctly, applying sanitization only where needed while preserving the overall structure. This is essential for supporting rich multimodal content in requests.

Scenario 15: LlmRequest with no config and sanitize true

Details:
  TestName: prepareGenerateContentRequestWithNoConfigAndSanitizeTrue
  Description: This test ensures that the method handles requests without a config object gracefully when sanitize is true.
Execution:
  Arrange: Create an LlmRequest without a config object (empty Optional). Set sanitize parameter to true.
  Act: Invoke prepareGenenerateContentRequest(llmRequest, true) method.
  Assert: Verify that the returned LlmRequest processes successfully without throwing exceptions and maintains the absence of config.
Validation:
  The assertion verifies that the method handles optional config gracefully, ensuring robustness when config is not provided. This is important for supporting minimal request configurations and preventing null pointer exceptions.

*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import com.google.genai.types.Blob;
import com.google.genai.types.Content;
import com.google.genai.types.FileData;
import com.google.genai.types.GenerateContentConfig;
import com.google.genai.types.Part;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class GeminiUtilPrepareGenenerateContentRequestTest {

	private LlmRequest.Builder requestBuilder;

	@BeforeEach
	void setUp() {
		requestBuilder = LlmRequest.builder();
	}

	@Test
	@Tag("valid")
	void prepareGenerateContentRequestWithValidRequestAndSanitizeTrue() {
		Part textPart = Part.fromText("Hello, how are you?");
		Content userContent = Content.builder().parts(ImmutableList.of(textPart)).role("user").build();
		LlmRequest llmRequest = requestBuilder.contents(ImmutableList.of(userContent)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, true);
		assertNotNull(result);
		assertFalse(result.contents().isEmpty());
		assertEquals(1, result.contents().size());
		assertTrue(result.contents().get(0).parts().isPresent());
	}

	@Test
	@Tag("valid")
	void prepareGenerateContentRequestWithValidRequestAndSanitizeFalse() {
		Blob blobWithDisplayName = Blob.builder().mimeType("image/png").displayName("test-image").build();
		Part partWithBlob = Part.builder().inlineData(blobWithDisplayName).build();
		Content userContent = Content.builder().parts(ImmutableList.of(partWithBlob)).role("user").build();
		LlmRequest llmRequest = requestBuilder.contents(ImmutableList.of(userContent)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, false);
		assertNotNull(result);
		assertTrue(result.contents().get(0).parts().isPresent());
		Part resultPart = result.contents().get(0).parts().get().get(0);
		assertTrue(resultPart.inlineData().isPresent());
		assertTrue(resultPart.inlineData().get().displayName().isPresent());
		assertEquals("test-image", resultPart.inlineData().get().displayName().get());
	}

	@Test
	@Tag("boundary")
	void prepareGenerateContentRequestWithEmptyContentsAndSanitizeTrue() {
		LlmRequest llmRequest = requestBuilder.contents(ImmutableList.of()).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, true);
		assertNotNull(result);
		assertEquals(1, result.contents().size());
		assertTrue(result.contents().get(0).parts().isPresent());
		assertEquals(GeminiUtil.CONTINUE_OUTPUT_MESSAGE,
				result.contents().get(0).parts().get().get(0).text().orElse(""));
	}

	@Test
	@Tag("valid")
	void prepareGenerateContentRequestWithLastContentRoleAsModelAndSanitizeTrue() {
		Content userContent = Content.builder()
			.parts(ImmutableList.of(Part.fromText("User message")))
			.role("user")
			.build();
		Content modelContent = Content.builder()
			.parts(ImmutableList.of(Part.fromText("Model response")))
			.role("model")
			.build();
		LlmRequest llmRequest = requestBuilder.contents(ImmutableList.of(userContent, modelContent)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, true);
		assertNotNull(result);
		assertEquals(3, result.contents().size());
		assertEquals("user", result.contents().get(2).role().orElse(""));
		assertEquals(GeminiUtil.CONTINUE_OUTPUT_MESSAGE,
				result.contents().get(2).parts().get().get(0).text().orElse(""));
	}

	@Test
	@Tag("valid")
	void prepareGenerateContentRequestWithLastContentRoleAsUserAndSanitizeTrue() {
		Content userContent1 = Content.builder()
			.parts(ImmutableList.of(Part.fromText("First message")))
			.role("user")
			.build();
		Content modelContent = Content.builder()
			.parts(ImmutableList.of(Part.fromText("Model response")))
			.role("model")
			.build();
		Content userContent2 = Content.builder()
			.parts(ImmutableList.of(Part.fromText("Second message")))
			.role("user")
			.build();
		LlmRequest llmRequest = requestBuilder.contents(ImmutableList.of(userContent1, modelContent, userContent2))
			.build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, true);
		assertNotNull(result);
		assertEquals(3, result.contents().size());
		assertEquals("user", result.contents().get(2).role().orElse(""));
	}

	@Test
	@Tag("valid")
	void prepareGenerateContentRequestWithInlineDataDisplayNameAndSanitizeTrue() {
		Blob blobWithDisplayName = Blob.builder().mimeType("image/png").displayName("test-image").build();
		Part partWithBlob = Part.builder().inlineData(blobWithDisplayName).build();
		Content userContent = Content.builder().parts(ImmutableList.of(partWithBlob)).role("user").build();
		LlmRequest llmRequest = requestBuilder.contents(ImmutableList.of(userContent)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, true);
		assertNotNull(result);
		assertTrue(result.contents().get(0).parts().isPresent());
		Part resultPart = result.contents().get(0).parts().get().get(0);
		assertTrue(resultPart.inlineData().isPresent());
		assertFalse(resultPart.inlineData().get().displayName().isPresent());
		assertTrue(resultPart.inlineData().get().mimeType().isPresent());
	}

	@Test
	@Tag("valid")
	void prepareGenerateContentRequestWithFileDataDisplayNameAndSanitizeTrue() {
		FileData fileDataWithDisplayName = FileData.builder()
			.fileUri("gs://bucket/file.pdf")
			.mimeType("application/pdf")
			.displayName("test-file")
			.build();
		Part partWithFileData = Part.builder().fileData(fileDataWithDisplayName).build();
		Content userContent = Content.builder().parts(ImmutableList.of(partWithFileData)).role("user").build();
		LlmRequest llmRequest = requestBuilder.contents(ImmutableList.of(userContent)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, true);
		assertNotNull(result);
		assertTrue(result.contents().get(0).parts().isPresent());
		Part resultPart = result.contents().get(0).parts().get().get(0);
		assertTrue(resultPart.fileData().isPresent());
		assertFalse(resultPart.fileData().get().displayName().isPresent());
		assertTrue(resultPart.fileData().get().fileUri().isPresent());
		assertTrue(resultPart.fileData().get().mimeType().isPresent());
	}

	@Test
	@Tag("valid")
	void prepareGenerateContentRequestWithConfigLabelsAndSanitizeTrue() {
		GenerateContentConfig config = GenerateContentConfig.builder()
			.labels(ImmutableMap.of("key1", "value1", "key2", "value2"))
			.build();
		Content userContent = Content.builder()
			.parts(ImmutableList.of(Part.fromText("Test message")))
			.role("user")
			.build();
		LlmRequest llmRequest = requestBuilder.contents(ImmutableList.of(userContent)).config(config).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, true);
		assertNotNull(result);
		assertTrue(result.config().isPresent());
		assertTrue(result.config().get().labels().isPresent());
		assertTrue(result.config().get().labels().get().isEmpty());
	}

	@Test
	@Tag("boundary")
	void prepareGenerateContentRequestWithEmptyPartsAndSanitizeTrue() {
		Content contentWithEmptyParts = Content.builder().parts(ImmutableList.of()).role("user").build();
		LlmRequest llmRequest = requestBuilder.contents(ImmutableList.of(contentWithEmptyParts)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, true);
		assertNotNull(result);
		assertFalse(result.contents().isEmpty());
		assertTrue(result.contents().get(0).parts().isPresent());
	}

	@Test
	@Tag("valid")
	void prepareGenerateContentRequestWithMixedRolesAndSanitizeFalse() {
		Content userContent1 = Content.builder()
			.parts(ImmutableList.of(Part.fromText("User message 1")))
			.role("user")
			.build();
		Content modelContent1 = Content.builder()
			.parts(ImmutableList.of(Part.fromText("Model response 1")))
			.role("model")
			.build();
		Content userContent2 = Content.builder()
			.parts(ImmutableList.of(Part.fromText("User message 2")))
			.role("user")
			.build();
		Content modelContent2 = Content.builder()
			.parts(ImmutableList.of(Part.fromText("Model response 2")))
			.role("model")
			.build();
		LlmRequest llmRequest = requestBuilder
			.contents(ImmutableList.of(userContent1, modelContent1, userContent2, modelContent2))
			.build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, false);
		assertNotNull(result);
		assertEquals(5, result.contents().size());
		assertEquals("user", result.contents().get(4).role().orElse(""));
		assertEquals(GeminiUtil.CONTINUE_OUTPUT_MESSAGE,
				result.contents().get(4).parts().get().get(0).text().orElse(""));
	}

	@Test
	@Tag("valid")
	void prepareGenerateContentRequestWithThoughtPartsAndSanitizeTrue() {
		Part thoughtPart = Part.builder().text("This is a thought").thought(true).build();
		Part regularPart = Part.fromText("This is regular text");
		Content userContent = Content.builder().parts(ImmutableList.of(thoughtPart, regularPart)).role("user").build();
		LlmRequest llmRequest = requestBuilder.contents(ImmutableList.of(userContent)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, true);
		assertNotNull(result);
		assertTrue(result.contents().get(0).parts().isPresent());
		assertEquals(1, result.contents().get(0).parts().get().size());
		assertEquals("This is regular text", result.contents().get(0).parts().get().get(0).text().orElse(""));
	}

	@Test
	@Tag("valid")
	void prepareGenerateContentRequestWithCaseInsensitiveUserRoleAndSanitizeTrue() {
		Content userContentUpperCase = Content.builder()
			.parts(ImmutableList.of(Part.fromText("Test message")))
			.role("USER")
			.build();
		LlmRequest llmRequest = requestBuilder.contents(ImmutableList.of(userContentUpperCase)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, true);
		assertNotNull(result);
		assertEquals(1, result.contents().size());
	}

	@Test
	@Tag("boundary")
	void prepareGenerateContentRequestWithAbsentRoleAndSanitizeTrue() {
		Content contentWithoutRole = Content.builder().parts(ImmutableList.of(Part.fromText("Test message"))).build();
		LlmRequest llmRequest = requestBuilder.contents(ImmutableList.of(contentWithoutRole)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, true);
		assertNotNull(result);
		assertEquals(2, result.contents().size());
		assertEquals("user", result.contents().get(1).role().orElse(""));
		assertEquals(GeminiUtil.CONTINUE_OUTPUT_MESSAGE,
				result.contents().get(1).parts().get().get(0).text().orElse(""));
	}

	@Test
	@Tag("valid")
	void prepareGenerateContentRequestWithMultiplePartTypesAndSanitizeTrue() {
		Part textPart = Part.fromText("Text content");
		Blob blob = Blob.builder().mimeType("image/jpeg").displayName("image").build();
		Part inlineDataPart = Part.builder().inlineData(blob).build();
		FileData fileData = FileData.builder()
			.fileUri("gs://bucket/file.pdf")
			.mimeType("application/pdf")
			.displayName("document")
			.build();
		Part fileDataPart = Part.builder().fileData(fileData).build();
		Content userContent = Content.builder()
			.parts(ImmutableList.of(textPart, inlineDataPart, fileDataPart))
			.role("user")
			.build();
		LlmRequest llmRequest = requestBuilder.contents(ImmutableList.of(userContent)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, true);
		assertNotNull(result);
		assertTrue(result.contents().get(0).parts().isPresent());
		assertEquals(3, result.contents().get(0).parts().get().size());
		assertFalse(result.contents().get(0).parts().get().get(1).inlineData().get().displayName().isPresent());
		assertFalse(result.contents().get(0).parts().get().get(2).fileData().get().displayName().isPresent());
	}

	@Test
	@Tag("boundary")
	void prepareGenerateContentRequestWithNoConfigAndSanitizeTrue() {
		Content userContent = Content.builder()
			.parts(ImmutableList.of(Part.fromText("Test message")))
			.role("user")
			.build();
		LlmRequest llmRequest = requestBuilder.contents(ImmutableList.of(userContent)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, true);
		assertNotNull(result);
		assertFalse(result.config().isPresent());
		assertFalse(result.contents().isEmpty());
	}

}
