/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test maven-adkjava-github using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=generateContent_ec6992cb48
ROOST_METHOD_SIG_HASH=generateContent_c08b9769fe

Scenario 1: GenerateContent with Non-Streaming, Happy Path

Details:
  TestName: generateContentNonStreamingReturnsExpectedResponse
  Description: This test verifies that when the generateContent method is called with the stream parameter set to false, a single request is sent to the model and the correct LlmResponse is returned. It checks that the standard request-response logic is triggered, the model name is selected correctly, the config is passed, and the output Flowable emits the expected results.

Execution:
  Arrange:
    - Create a mock Client where async.models.generateContent returns a completed CompletableFuture with a mock GenerateContentResponse.
    - Stub LlmResponse.create to wrap the response and produce a known LlmResponse.
    - Prepare a minimal LlmRequest with or without optional fields.
    - Construct a Gemini instance using the mock Client.
  Act:
    - Call the generateContent method with the test LlmRequest and stream=false.
  Assert:
    - Assert that the resulting Flowable emits exactly one LlmResponse with the expected values.
    - Assert that apiClient.async.models.generateContent was called with the correct effective model name, contents, and config.

Validation:
  This assertion confirms that the non-streaming code path correctly adapts the input request, calls the expected async client method, and correctly transforms the returned value. It validates that critical model selection and config logic is integrated end-to-end, protecting core business logic.


Scenario 2: GenerateContent with Streaming, Happy Path, Emission Filtering

Details:
  TestName: generateContentStreamingFiltersAndProcessesResponses
  Description: This test checks that when the stream parameter is true, the method uses the streaming logic: sending a streaming request, processing GenerateContentResponse objects via processRawResponses, and filtering LlmResponses that do not match required criteria (at least one Part with functionCall, functionResponse, or non-blank text).

Execution:
  Arrange:
    - Create a mock Client with async.models.generateContentStream returning a CompletableFuture containing a mock ResponseStream<GenerateContentResponse>.
    - Prepare mock GenerateContentResponse objects so some produce LlmResponses meeting filter criteria, and some do not.
    - Set up processRawResponses to simulate partial and complete LlmResponses as expected.
    - Create a basic LlmRequest.
    - Initialize the Gemini instance.
  Act:
    - Call generateContent with the LlmRequest and stream=true.
  Assert:
    - Assert that the output Flowable only emits LlmResponses matching the filter condition.
    - Verify that the streaming client method was called correctly with effective model name, contents, and config.

Validation:
  This scenario ensures that the streaming path is correctly engaged and that filtering logic is functioning: only LlmResponses with a non-empty parts list, where at least one part contains a function call, function response, or non-blank text, are emitted. This preserves the intended output structure and user-facing behavior.


Scenario 3: Custom Model Name in LlmRequest Overrides Default

Details:
  TestName: customModelNameInRequestIsUsed
  Description: This test ensures that if an explicit model name is present in the incoming LlmRequest, it is used instead of the default model name for outgoing generateContent/generateContentStream client calls.

Execution:
  Arrange:
    - Construct an LlmRequest with model().isPresent() == true and a distinctive model name.
    - Mock the Client as in previous scenarios.
    - Build a Gemini instance with a different default model name.
  Act:
    - Call generateContent with the LlmRequest (stream either true or false).
  Assert:
    - Assert via mock interactions that the client received the LlmRequest’s model name as effectiveModelName.
    - (For Flowable contents, assert that results are generated as usual.)

Validation:
  This test is important to verify that request-specified model selection is respected, allowing dynamic model use cases and avoiding unexpected defaulting behavior.


Scenario 4: Null Config in LlmRequest

Details:
  TestName: handlesNullGenerateContentConfigGracefully
  Description: Tests the method with an LlmRequest where config() is absent/Optional.empty(). The scenario checks that calls to the model are correctly made with a null config argument, and no NullPointerExceptions occur.

Execution:
  Arrange:
    - Create an LlmRequest with config() returning Optional.empty().
    - Prepare the Client mock to capture the config argument.
    - Set up typical stubbing for API returns.
  Act:
    - Call generateContent with this LlmRequest for both streaming and non-streaming.
  Assert:
    - Assert that the called config argument is null.
    - Verify that the rest of the roundtrip proceeds as normal, with valid Flowable output.

Validation:
  This confirms robust handling of absent config and ensures compliance with the client API, preventing exceptions caused by null propagation.


Scenario 5: Filtering Skips LlmResponses Without Content Parts

Details:
  TestName: filteredStreamingSkipsResponsesWithoutRelevantParts
  Description: For the streaming scenario, this test verifies that any LlmResponse whose content.parts() is empty or whose parts contain neither functionCall nor functionResponse, nor non-blank text is excluded from the output by the filter.

Execution:
  Arrange:
    - Prepare GenerateContentResponse mocks that, when processed, yield LlmResponses with: (a) content.parts() == empty, (b) content.parts() containing only blank text, (c) only functionCall present, (d) only functionResponse present.
    - Control processRawResponses to emit these LlmResponses.
    - Use a Gemini instance as normal.
  Act:
    - Call generateContent with stream=true.
  Assert:
    - Assert that only LlmResponses with at least one part containing a function call, function response, or non-blank text are emitted.

Validation:
  This ensures the filtering logic precisely matches the documented condition (non-empty, relevant parts), protecting consumers from incomplete or irrelevant data.


Scenario 6: Handling of Downstream Exceptions in Client Calls

Details:
  TestName: propagateExceptionsFromApiClient
  Description: The test verifies that if the underlying client (apiClient.async.models.generateContent or generateContentStream) throws an exception or returns a failed CompletableFuture, the Flowable propagated by generateContent emits this error and does not complete successfully.

Execution:
  Arrange:
    - Use mock Client that throws or returns exceptionally-completed Futures.
    - Set up minimal LlmRequest.
    - Gemini with this Client.
  Act:
    - Call generateContent with stream false and then with stream true, in each case attempting to collect terminal errors from the returned Flowable.
  Assert:
    - Assert that the Flowable emits an error (exception), matching the simulated cause.

Validation:
  This scenario verifies that unexpected lower-level failures are not swallowed but are surfaced to the caller, preserving error transparency.


Scenario 7: Uses Prepared, Adapted LlmRequest

Details:
  TestName: callsPrepareGenenerateContentRequestWithExpectedArguments
  Description: Ensures that generateContent always invokes GeminiUtil.prepareGenenerateContentRequest with the original LlmRequest, !apiClient.vertexAI() as the flag, and false as the stripThoughts parameter, using its result for downstream processing.

Execution:
  Arrange:
    - Spy or mock GeminiUtil.prepareGenenerateContentRequest to capture the arguments.
    - Mock apiClient so its vertexAI() response is known (e.g., true/false).
    - Provide a dummy LlmRequest.
    - Construct Gemini.
  Act:
    - Call generateContent (stream true/false) and allow call-through.
  Assert:
    - Assert that GeminiUtil.prepareGenenerateContentRequest was called with original LlmRequest, expected boolean (inverse of apiClient.vertexAI()), and false.
    - Assert the returned object from this call was actually used.

Validation:
  This validates key input pre-processing business logic: that requests are always properly adapted according to backend type and convention.


Scenario 8: Handles Empty Streaming Responses

Details:
  TestName: handlesEmptyStreamingApiResponse
  Description: Simulates a streaming client call whose ResponseStream emits no GenerateContentResponse and verifies that generateContent (streaming mode) results in a Flowable that completes without emitting any LlmResponse.

Execution:
  Arrange:
    - Mock Client to return an empty ResponseStream for generateContentStream.
    - Set up all stubs so processRawResponses invoked on empty input produces an empty Flowable.
  Act:
    - Call generateContent with stream=true.
    - Subscribe to the Flowable and collect emissions.
  Assert:
    - Assert that the Flowable emits no items and completes successfully.

Validation:
  This verifies correct handling of streaming edge cases where the backend produces no events, ensuring subscribers see no erroneous data or indefinite hanging.


Scenario 9: Streaming LlmResponses with Both Function Call and Non-blank Text

Details:
  TestName: streamingEmitsResponseWithFunctionCallAndText
  Description: Confirms that a streaming response including a Part with both functionCall present and non-blank text passes through the filter and is emitted to the user.

Execution:
  Arrange:
    - Prepare a mock GenerateContentResponse processed into LlmResponse whose content.parts list has a Part with a valid function call and non-blank text.
    - Configure the Client and processRawResponses as usual.
  Act:
    - Call generateContent (stream=true).
  Assert:
    - Assert that this LlmResponse is emitted.

Validation:
  Ensures that multi-faceted responses with both function call and text are considered valid by the filter, thus validating complex use cases involving function-invoking models.


Scenario 10: Falls Back to Default Model if LlmRequest Model Absent

Details:
  TestName: usesDefaultModelNameIfRequestModelAbsent
  Description: Validates that if LlmRequest.model() is Optional.empty(), then Gemini falls back to the model name supplied at construction, and this name is sent to the API client.

Execution:
  Arrange:
    - Construct Gemini with a specific model name.
    - Make LlmRequest whose model().isEmpty().
    - Use stubs to observe the actual string sent to the Client method.
  Act:
    - Call generateContent (stream true/false).
  Assert:
    - Assert that the client is called with the default model name.

Validation:
  Protects from defaulting regressions when faced with requests not setting their own model, ensuring predictability and traceability.


Scenario 11: Handles Null Content in LlmResponse for Filtering

Details:
  TestName: streamingSkipsLlmResponseWithNullContent
  Description: Verifies that if LlmResponse.content() returns absent/empty, the filtering in the streaming code path skips such responses, yielding no emission.

Execution:
  Arrange:
    - Simulate a GenerateContentResponse that, when processed, results in an LlmResponse with content() == Optional.empty().
    - Mock processRawResponses to emit this response.
  Act:
    - Call generateContent with streaming.
  Assert:
    - Assert that the Flowable emits no such LlmResponse.

Validation:
  This verifies that nullability is respected and does not create spurious output, thus enforcing robust filter logic.


Scenario 12: Requests with Empty List of Parts (Streaming Mode)

Details:
  TestName: streamingSkipsResponsesWithEmptyPartsList
  Description: Tests that LlmResponses having content.parts() present but returning an empty list are filtered out in streaming mode.

Execution:
  Arrange:
    - Set up a streaming call to emit a LlmResponse whose content.parts() returns an empty list.
    - Spied or stubbed processRawResponses and content object as needed.
  Act:
    - Call generateContent (stream=true).
  Assert:
    - Verify that no such LlmResponse is emitted.

Validation:
  Ensures the filter checks for a non-empty list of parts, as intended.


Scenario 13: All-Blank-Text Parts Are Filtered Out in Streaming

Details:
  TestName: streamingSkipsResponsesWithOnlyBlankText
  Description: Ensures that if content.parts() are present but all Part.text() are blank or missing (and there are no functionCall or functionResponse members), such responses are filtered and not emitted.

Execution:
  Arrange:
    - Set up processRawResponses to emit a LlmResponse with content.parts() containing Parts, but their text() is blank/null and no function elements.
  Act:
    - Call generateContent (stream=true).
  Assert:
    - Assert that this is not emitted by the resulting Flowable.

Validation:
  Prevents empty, irrelevant responses from leaking into the user flow.


Scenario 14: Multiple Streaming Chunks with Mixed Validity

Details:
  TestName: streamingEmitsOnlyValidlyFilteredChunks
  Description: Simulate a series of streaming responses, some matching filter criteria and some not, and check that only valid responses are emitted (mixed valid/invalid).

Execution:
  Arrange:
    - Control processRawResponses to emit a sequence of LlmResponses, some with functionCall/text, some empty or blank.
  Act:
    - Call generateContent (stream=true).
  Assert:
    - Only valid items are output.

Validation:
  This checks flow control with streaming, ensuring filter state across multiple chunks.


Scenario 15: Large Contents List Handling (Stress Test)

Details:
  TestName: handlesLargeContentsListCorrectly
  Description: Tests that generateContent can gracefully handle a large LlmRequest.contents list, ensuring that neither the adaptation, client call, nor post-processing path truncates, crashes, or degrades unintentionally.

Execution:
  Arrange:
    - Prepare an LlmRequest with a very large or deeply nested contents list.
    - Set up Client and processRawResponses to handle appropriately sized test data.
  Act:
    - Call generateContent (stream false or true).
  Assert:
    - Assert that the full contents list is passed and results are present.

Validation:
  Stress-tests the method for memory or overflow issues, ensuring production robustness.


Scenario 16: Streaming Respects Partial LlmResponse Marking

Details:
  TestName: streamingMarksPartialResponsesCorrectly
  Description: If processRawResponses emits LlmResponses marked as partial (i.e., toBuilder().partial(true) in partial streaming logic) and not partial (finished), this test verifies that the partial flag is preserved in the responses out of generateContent.

Execution:
  Arrange:
    - Set up processRawResponses to emit LlmResponses with .partial(true) and .partial(false).
  Act:
    - Call generateContent with stream=true.
  Assert:
    - Verify that partial markings match the streaming scenario.

Validation:
  Ensures users can distinguish partial from complete outputs, crucial for interactive UIs.


Scenario 17: Respects VertexAI vs Non-VertexAI API Flag

Details:
  TestName: preparesRequestBasedOnVertexAIFlag
  Description: Checks that the stream/non-stream code paths call GeminiUtil.prepareGenenerateContentRequest with ‘false’ only when stripThoughts is required as per !apiClient.vertexAI(), and that flipping the apiClient.vertexAI() state switches this behavior.

Execution:
  Arrange:
    - Mock/spying behavior as in Scenario 7, but explicitly toggle apiClient.vertexAI() between true and false.
  Act:
    - Call generateContent and capture arguments.
  Assert:
    - The boolean value is inverted as expected.

Validation:
  This tests the business rule for API flag switching on the request preparation logic.


Scenario 18: All Optional Fields Unset in LlmRequest

Details:
  TestName: worksWhenLlmRequestOptionalsUnset
  Description: Ensures that all paths work correctly (and no unexpected null or default issues arise) when LlmRequest.model() and config() are Optional.empty().

Execution:
  Arrange:
    - Prepare a minimal LlmRequest with model and config both absent.
    - Usual test scaffolding.
  Act:
    - Call generateContent both streamed and non-streamed.
  Assert:
    - See that defaults are chosen, and method operates as usual.

Validation:
  Verifies business logic for defaulting and optional handling.


Scenario 19: Config Passed Through for Streaming

Details:
  TestName: passesConfigThroughInStreamingCalls
  Description: Verifies that if LlmRequest has a config present, it is forwarded to the client’s streaming API with the correct value.

Execution:
  Arrange:
    - LlmRequest with config present.
    - Mock client to observe config value.
  Act:
    - Call generateContent with stream=true.
  Assert:
    - Correct config is passed.

Validation:
  Checks positive config propagation in the streaming path.


Scenario 20: Completion Guarantees For Non-Streaming Path

Details:
  TestName: nonStreamingAlwaysCompletesOrErrors
  Description: In the non-streaming path, checks that upon successful or erroneous client call, the returned Flowable always terminates (completes or emits error).

Execution:
  Arrange:
    - Provide stub client responses for both resolved and failed Futures.
  Act:
    - Call generateContent (stream=false).
  Assert:
    - Assert that subscriptions either complete with an LlmResponse or error, never hang.

Validation:
  Protects application from indefinite awaits, ensuring prompt feedback.


*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.genai.Client;
import com.google.genai.ResponseStream;
import com.google.genai.types.Content;
import com.google.genai.types.GenerateContentConfig;
import com.google.genai.types.GenerateContentResponse;
import com.google.genai.types.Part;
import io.reactivex.rxjava3.core.Flowable;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.mockito.MockedStatic;
import org.mockito.Mockito;

public class GeminiGenerateContentTest extends BaseLlm {

  public GeminiGenerateContentTest() {
    super("dummy-model");
  }

  @Test
  @Tag("valid")
  @DisplayName("GenerateContent with Non-Streaming, Happy Path")
  public void testGenerateContentNonStreamingReturnsExpectedResponse() {
    // Arrange
    Client apiClient = mock(Client.class);
    Client.Async async = mock(Client.Async.class);
    Client.Async.Models models = mock(Client.Async.Models.class);
    when(apiClient.async).thenReturn(async);
    when(async.models).thenReturn(models);
    String expectedModel = "test-model";
    List<Content> contents =
        List.of(Content.builder().role("user").parts(Part.fromText("say hello")).build());
    GenerateContentConfig config = GenerateContentConfig.builder().build();
    LlmRequest llmRequest = mock(LlmRequest.class);
    when(llmRequest.config()).thenReturn(Optional.of(config));
    when(llmRequest.model()).thenReturn(Optional.empty());
    when(llmRequest.contents()).thenReturn(contents);
    GenerateContentResponse genResponse =
        GenerateContentResponse.builder().candidates(List.of()).build();
    CompletableFuture<GenerateContentResponse> completableResponse =
        CompletableFuture.completedFuture(genResponse);
    when(models.generateContent(eq(expectedModel), eq(contents), eq(config)))
        .thenReturn(completableResponse);
    Gemini gemini = new Gemini(expectedModel, apiClient);
    MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class);
    geminiUtilMock
        .when(
            () ->
                GeminiUtil.prepareGenenerateContentRequest(eq(llmRequest), anyBoolean(), eq(false)))
        .thenReturn(llmRequest);
    MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
    LlmResponse expectedLlmResponse = mock(LlmResponse.class);
    llmResponseMock.when(() -> LlmResponse.create(genResponse)).thenReturn(expectedLlmResponse);
    // Act
    Flowable<LlmResponse> flowable = gemini.generateContent(llmRequest, false);
    List<LlmResponse> actualResponses = flowable.toList().blockingGet();
    // Assert
    assertEquals(1, actualResponses.size());
    assertSame(expectedLlmResponse, actualResponses.get(0));
    verify(models, times(1)).generateContent(eq(expectedModel), eq(contents), eq(config));
    geminiUtilMock.close();
    llmResponseMock.close();
  }

  @Test
  @Tag("valid")
  @DisplayName("GenerateContent with Streaming, Happy Path, Emission Filtering")
  public void testGenerateContentStreamingFiltersAndProcessesResponses() {
    // Arrange
    Client apiClient = mock(Client.class);
    Client.Async async = mock(Client.Async.class);
    Client.Async.Models models = mock(Client.Async.Models.class);
    when(apiClient.async).thenReturn(async);
    when(async.models).thenReturn(models);
    String expectedModel = "test-model";
    List<Content> contents =
        List.of(Content.builder().role("user").parts(Part.fromText("stream?")).build());
    GenerateContentConfig config = GenerateContentConfig.builder().build();
    LlmRequest llmRequest = mock(LlmRequest.class);
    when(llmRequest.config()).thenReturn(Optional.of(config));
    when(llmRequest.model()).thenReturn(Optional.empty());
    when(llmRequest.contents()).thenReturn(contents);
    ResponseStream<GenerateContentResponse> responseStream = mock(ResponseStream.class);
    List<GenerateContentResponse> streamingResponses =
        List.of(
            GenerateContentResponse.builder().candidates(List.of()).build(),
            GenerateContentResponse.builder().candidates(List.of()).build());
    when(responseStream.iterator()).thenReturn(streamingResponses.iterator());
    CompletableFuture<ResponseStream<GenerateContentResponse>> completedFuture =
        CompletableFuture.completedFuture(responseStream);
    when(models.generateContentStream(eq(expectedModel), eq(contents), eq(config)))
        .thenReturn(completedFuture);
    Gemini gemini = new Gemini(expectedModel, apiClient);
    MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class);
    geminiUtilMock
        .when(
            () ->
                GeminiUtil.prepareGenenerateContentRequest(eq(llmRequest), anyBoolean(), eq(false)))
        .thenReturn(llmRequest);
    MockedStatic(Gemini.class);
    MockedStatic<Gemini> geminiStatic = Mockito.mockStatic(Gemini.class);
    MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
    // Prepare two LlmResponses, one valid, one invalid for the filter
    Part validPart = mock(Part.class);
    when(validPart.functionCall()).thenReturn(Optional.of("call"));
    when(validPart.functionResponse()).thenReturn(Optional.empty());
    when(validPart.text()).thenReturn(Optional.of("some text"));
    Part invalidPart = mock(Part.class);
    when(invalidPart.functionCall()).thenReturn(Optional.empty());
    when(invalidPart.functionResponse()).thenReturn(Optional.empty());
    when(invalidPart.text()).thenReturn(Optional.of(""));
    Content validContent = Content.builder().role("model").parts(validPart).build();
    Content invalidContent = Content.builder().role("model").parts(invalidPart).build();
    LlmResponse validResponse = mock(LlmResponse.class);
    when(validResponse.content()).thenReturn(Optional.of(validContent));
    LlmResponse invalidResponse = mock(LlmResponse.class);
    when(invalidResponse.content()).thenReturn(Optional.of(invalidContent));
    List<LlmResponse> rawLlmResponses = List.of(validResponse, invalidResponse);
    MockedStatic<Gemini> geminiUtilProcessRawResponses = mockStatic(Gemini.class);
    geminiUtilProcessRawResponses
        .when(() -> Gemini.processRawResponses(any()))
        .thenReturn(Flowable.fromIterable(rawLlmResponses));
    // Act
    Flowable<LlmResponse> flowable = gemini.generateContent(llmRequest, true);
    List<LlmResponse> emittedResponses = flowable.toList().blockingGet();
    // Assert
    assertTrue(emittedResponses.contains(validResponse));
    assertFalse(emittedResponses.contains(invalidResponse));
    verify(models, times(1)).generateContentStream(eq(expectedModel), eq(contents), eq(config));
    geminiUtilMock.close();
    llmResponseMock.close();
    geminiUtilProcessRawResponses.close();
    geminiStatic.close();
  }

  @Test
  @Tag("valid")
  @DisplayName("Custom Model Name in LlmRequest Overrides Default")
  public void testCustomModelNameInRequestIsUsed() {
    // Arrange
    Client apiClient = mock(Client.class);
    Client.Async async = mock(Client.Async.class);
    Client.Async.Models models = mock(Client.Async.Models.class);
    when(apiClient.async).thenReturn(async);
    when(async.models).thenReturn(models);
    String builderDefault = "default-model";
    String customModel = "custom-model";
    LlmRequest llmRequest = mock(LlmRequest.class);
    when(llmRequest.model()).thenReturn(Optional.of(customModel));
    when(llmRequest.contents()).thenReturn(List.of());
    GenerateContentConfig config = GenerateContentConfig.builder().build();
    when(llmRequest.config()).thenReturn(Optional.of(config));
    GenerateContentResponse genResponse = GenerateContentResponse.builder().build();
    CompletableFuture<GenerateContentResponse> completableResponse =
        CompletableFuture.completedFuture(genResponse);
    when(models.generateContent(eq(customModel), any(), any())).thenReturn(completableResponse);
    Gemini gemini = new Gemini(builderDefault, apiClient);
    MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class);
    geminiUtilMock
        .when(() -> GeminiUtil.prepareGenenerateContentRequest(any(), anyBoolean(), eq(false)))
        .thenReturn(llmRequest);
    MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
    LlmResponse expectedLlmResponse = mock(LlmResponse.class);
    llmResponseMock.when(() -> LlmResponse.create(genResponse)).thenReturn(expectedLlmResponse);
    // Act
    Flowable<LlmResponse> flowable = gemini.generateContent(llmRequest, false);
    List<LlmResponse> results = flowable.toList().blockingGet();
    // Assert
    assertEquals(1, results.size());
    assertSame(expectedLlmResponse, results.get(0));
    verify(models).generateContent(eq(customModel), eq(llmRequest.contents()), eq(config));
    geminiUtilMock.close();
    llmResponseMock.close();
  }

  @Test
  @Tag("boundary")
  @DisplayName("Null Config in LlmRequest")
  public void testHandlesNullGenerateContentConfigGracefully() {
    // Arrange
    Client apiClient = mock(Client.class);
    Client.Async async = mock(Client.Async.class);
    Client.Async.Models models = mock(Client.Async.Models.class);
    when(apiClient.async).thenReturn(async);
    when(async.models).thenReturn(models);
    String modelName = "model-null-config";
    LlmRequest llmRequest = mock(LlmRequest.class);
    when(llmRequest.config()).thenReturn(Optional.empty());
    when(llmRequest.model()).thenReturn(Optional.empty());
    when(llmRequest.contents()).thenReturn(List.of());
    GenerateContentResponse genResponse = GenerateContentResponse.builder().build();
    CompletableFuture<GenerateContentResponse> completableResponse =
        CompletableFuture.completedFuture(genResponse);
    ArgumentCaptor<GenerateContentConfig> configCaptor =
        ArgumentCaptor.forClass(GenerateContentConfig.class);
    when(models.generateContent(eq(modelName), any(), configCaptor.capture()))
        .thenReturn(completableResponse);
    Gemini gemini = new Gemini(modelName, apiClient);
    MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class);
    geminiUtilMock
        .when(
            () ->
                GeminiUtil.prepareGenenerateContentRequest(eq(llmRequest), anyBoolean(), eq(false)))
        .thenReturn(llmRequest);
    MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
    LlmResponse expectedLlmResponse = mock(LlmResponse.class);
    llmResponseMock.when(() -> LlmResponse.create(genResponse)).thenReturn(expectedLlmResponse);
    // Act
    Flowable<LlmResponse> flowable = gemini.generateContent(llmRequest, false);
    List<LlmResponse> responses = flowable.toList().blockingGet();
    // Assert
    assertEquals(1, responses.size());
    assertSame(expectedLlmResponse, responses.get(0));
    assertNull(configCaptor.getValue());
    geminiUtilMock.close();
    llmResponseMock.close();
  }

  @Test
  @Tag("boundary")
  @DisplayName("Filtering Skips LlmResponses Without Content Parts")
  public void testFilteredStreamingSkipsResponsesWithoutRelevantParts() {
    // Arrange
    Client apiClient = mock(Client.class);
    Client.Async async = mock(Client.Async.class);
    Client.Async.Models models = mock(Client.Async.Models.class);
    when(apiClient.async).thenReturn(async);
    when(async.models).thenReturn(models);
    String modelName = "test-model-filter";
    LlmRequest llmRequest = mock(LlmRequest.class);
    when(llmRequest.config()).thenReturn(Optional.of(GenerateContentConfig.builder().build()));
    when(llmRequest.model()).thenReturn(Optional.empty());
    when(llmRequest.contents()).thenReturn(List.of());
    ResponseStream<GenerateContentResponse> responseStream = mock(ResponseStream.class);
    CompletableFuture<ResponseStream<GenerateContentResponse>> completedFuture =
        CompletableFuture.completedFuture(responseStream);
    when(models.generateContentStream(eq(modelName), any(), any())).thenReturn(completedFuture);
    Gemini gemini = new Gemini(modelName, apiClient);
    // Prepare responses: (a) no parts, (b) only blank part, (c) valid
    Part blankPart = mock(Part.class);
    when(blankPart.text()).thenReturn(Optional.of(""));
    when(blankPart.functionCall()).thenReturn(Optional.empty());
    when(blankPart.functionResponse()).thenReturn(Optional.empty());
    Content emptyPartsContent = Content.builder().role("model").parts(new ArrayList<>()).build();
    Content blankTextContent = Content.builder().role("model").parts(blankPart).build();
    LlmResponse respNoParts = mock(LlmResponse.class);
    when(respNoParts.content()).thenReturn(Optional.of(emptyPartsContent));
    LlmResponse respBlankParts = mock(LlmResponse.class);
    when(respBlankParts.content()).thenReturn(Optional.of(blankTextContent));
    // Only function call part
    Part functionCallPart = mock(Part.class);
    when(functionCallPart.text()).thenReturn(Optional.of(" "));
    when(functionCallPart.functionCall()).thenReturn(Optional.of("funcCall"));
    when(functionCallPart.functionResponse()).thenReturn(Optional.empty());
    Content functionCallContent = Content.builder().role("model").parts(functionCallPart).build();
    LlmResponse respFunctionCall = mock(LlmResponse.class);
    when(respFunctionCall.content()).thenReturn(Optional.of(functionCallContent));
    List<LlmResponse> inputResponses = List.of(respNoParts, respBlankParts, respFunctionCall);
    MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class);
    geminiUtilMock
        .when(() -> GeminiUtil.prepareGenenerateContentRequest(any(), anyBoolean(), eq(false)))
        .thenReturn(llmRequest);
    MockedStatic<Gemini> geminiStatic = mockStatic(Gemini.class);
    geminiStatic
        .when(() -> Gemini.processRawResponses(any()))
        .thenReturn(Flowable.fromIterable(inputResponses));
    // Act
    Flowable<LlmResponse> flowable = gemini.generateContent(llmRequest, true);
    List<LlmResponse> emitted = flowable.toList().blockingGet();
    // Assert: Only respFunctionCall should be emitted
    assertFalse(emitted.contains(respNoParts));
    assertFalse(emitted.contains(respBlankParts));
    assertTrue(emitted.contains(respFunctionCall));
    geminiUtilMock.close();
    geminiStatic.close();
  }

  @Test
  @Tag("invalid")
  @DisplayName("Handling of Downstream Exceptions in Client Calls")
  public void testPropagateExceptionsFromApiClient() {
    // Arrange
    Client apiClient = mock(Client.class);
    Client.Async async = mock(Client.Async.class);
    Client.Async.Models models = mock(Client.Async.Models.class);
    when(apiClient.async).thenReturn(async);
    when(async.models).thenReturn(models);
    String modelName = "test-propagate-exception";
    LlmRequest llmRequest = mock(LlmRequest.class);
    when(llmRequest.config()).thenReturn(Optional.empty());
    when(llmRequest.model()).thenReturn(Optional.empty());
    when(llmRequest.contents()).thenReturn(List.of());
    Gemini gemini = new Gemini(modelName, apiClient);
    // Simulate generateContent throwing
    CompletableFuture<GenerateContentResponse> exceptionalFuture = new CompletableFuture<>();
    exceptionalFuture.completeExceptionally(new RuntimeException("failtest"));
    when(models.generateContent(eq(modelName), eq(List.of()), eq(null)))
        .thenReturn(exceptionalFuture);
    MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class);
    geminiUtilMock
        .when(() -> GeminiUtil.prepareGenenerateContentRequest(any(), anyBoolean(), eq(false)))
        .thenReturn(llmRequest);
    // Act & Assert
    assertThrows(
        RuntimeException.class,
        () -> {
          gemini.generateContent(llmRequest, false).blockingFirst();
        });
    // Streaming path
    CompletableFuture<ResponseStream<GenerateContentResponse>> exceptionalStream =
        new CompletableFuture<>();
    exceptionalStream.completeExceptionally(new RuntimeException("streamfail"));
    when(models.generateContentStream(eq(modelName), eq(List.of()), eq(null)))
        .thenReturn(exceptionalStream);
    assertThrows(
        RuntimeException.class,
        () -> {
          gemini.generateContent(llmRequest, true).blockingFirst();
        });
    geminiUtilMock.close();
  }

  @Test
  @Tag("integration")
  @DisplayName("Uses Prepared, Adapted LlmRequest")
  public void testCallsPrepareGenenerateContentRequestWithExpectedArguments() {
    // Arrange
    Client apiClient = mock(Client.class);
    Client.Async async = mock(Client.Async.class);
    Client.Async.Models models = mock(Client.Async.Models.class);
    when(apiClient.async).thenReturn(async);
    when(async.models).thenReturn(models);
    String modelName = "integration-adapt";
    LlmRequest llmRequest = mock(LlmRequest.class);
    LlmRequest preparedRequest = mock(LlmRequest.class);
    // Set up apiClient.vertexAI() returns true
    when(apiClient.vertexAI()).thenReturn(true);
    when(llmRequest.config()).thenReturn(Optional.empty());
    when(llmRequest.model()).thenReturn(Optional.empty());
    when(llmRequest.contents()).thenReturn(List.of());
    when(preparedRequest.config()).thenReturn(Optional.empty());
    when(preparedRequest.model()).thenReturn(Optional.empty());
    when(preparedRequest.contents()).thenReturn(List.of());
    GenerateContentResponse genResponse = GenerateContentResponse.builder().build();
    CompletableFuture<GenerateContentResponse> completableResponse =
        CompletableFuture.completedFuture(genResponse);
    when(models.generateContent(eq(modelName), eq(List.of()), eq(null)))
        .thenReturn(completableResponse);
    Gemini gemini = new Gemini(modelName, apiClient);
    try (MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
      geminiUtilMock
          .when(
              () ->
                  GeminiUtil.prepareGenenerateContentRequest(eq(llmRequest), eq(false), eq(false)))
          .thenReturn(preparedRequest);
      MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
      LlmResponse expectedLlmResponse = mock(LlmResponse.class);
      llmResponseMock.when(() -> LlmResponse.create(genResponse)).thenReturn(expectedLlmResponse);
      // Act
      Flowable<LlmResponse> flowable = gemini.generateContent(llmRequest, false);
      List<LlmResponse> responses = flowable.toList().blockingGet();
      // Assert
      assertEquals(1, responses.size());
      assertSame(expectedLlmResponse, responses.get(0));
      geminiUtilMock.verify(
          () -> GeminiUtil.prepareGenenerateContentRequest(eq(llmRequest), eq(false), eq(false)),
          times(1));
      llmResponseMock.close();
    }
  }

  @Test
  @Tag("boundary")
  @DisplayName("Handles Empty Streaming Responses")
  public void testHandlesEmptyStreamingApiResponse() {
    // Arrange
    Client apiClient = mock(Client.class);
    Client.Async async = mock(Client.Async.class);
    Client.Async.Models models = mock(Client.Async.Models.class);
    when(apiClient.async).thenReturn(async);
    when(async.models).thenReturn(models);
    String modelName = "empty-stream";
    LlmRequest llmRequest = mock(LlmRequest.class);
    when(llmRequest.config()).thenReturn(Optional.empty());
    when(llmRequest.model()).thenReturn(Optional.empty());
    when(llmRequest.contents()).thenReturn(List.of());
    ResponseStream<GenerateContentResponse> responseStream = mock(ResponseStream.class);
    when(responseStream.iterator()).thenReturn(new ArrayList<GenerateContentResponse>().iterator());
    CompletableFuture<ResponseStream<GenerateContentResponse>> completedFuture =
        CompletableFuture.completedFuture(responseStream);
    when(models.generateContentStream(eq(modelName), eq(List.of()), eq(null)))
        .thenReturn(completedFuture);
    Gemini gemini = new Gemini(modelName, apiClient);
    MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class);
    geminiUtilMock
        .when(
            () ->
                GeminiUtil.prepareGenenerateContentRequest(eq(llmRequest), anyBoolean(), eq(false)))
        .thenReturn(llmRequest);
    MockedStatic<Gemini> geminiStatic = mockStatic(Gemini.class);
    geminiStatic.when(() -> Gemini.processRawResponses(any())).thenReturn(Flowable.empty());
    // Act
    Flowable<LlmResponse> flowable = gemini.generateContent(llmRequest, true);
    List<LlmResponse> results = flowable.toList().blockingGet();
    // Assert
    assertEquals(0, results.size());
    geminiUtilMock.close();
    geminiStatic.close();
  }

  @Test
  @Tag("valid")
  @DisplayName("Streaming LlmResponses with Both Function Call and Non-blank Text")
  public void testStreamingEmitsResponseWithFunctionCallAndText() {
    // Arrange
    Client apiClient = mock(Client.class);
    Client.Async async = mock(Client.Async.class);
    Client.Async.Models models = mock(Client.Async.Models.class);
    when(apiClient.async).thenReturn(async);
    when(async.models).thenReturn(models);
    String modelName = "stream-func-call-text";
    LlmRequest llmRequest = mock(LlmRequest.class);
    when(llmRequest.config()).thenReturn(Optional.of(GenerateContentConfig.builder().build()));
    when(llmRequest.model()).thenReturn(Optional.empty());
    when(llmRequest.contents()).thenReturn(List.of());
    ResponseStream<GenerateContentResponse> responseStream = mock(ResponseStream.class);
    CompletableFuture<ResponseStream<GenerateContentResponse>> completedFuture =
        CompletableFuture.completedFuture(responseStream);
    when(models.generateContentStream(eq(modelName), eq(List.of()), any()))
        .thenReturn(completedFuture);
    Gemini gemini = new Gemini(modelName, apiClient);
    Part validPart = mock(Part.class);
    when(validPart.functionCall()).thenReturn(Optional.of("call"));
    when(validPart.text()).thenReturn(Optional.of("hello"));
    when(validPart.functionResponse()).thenReturn(Optional.empty());
    Content validContent = Content.builder().role("model").parts(validPart).build();
    LlmResponse validResponse = mock(LlmResponse.class);
    when(validResponse.content()).thenReturn(Optional.of(validContent));
    MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class);
    geminiUtilMock
        .when(() -> GeminiUtil.prepareGenenerateContentRequest(any(), anyBoolean(), eq(false)))
        .thenReturn(llmRequest);
    MockedStatic<Gemini> geminiStatic = mockStatic(Gemini.class);
    geminiStatic
        .when(() -> Gemini.processRawResponses(any()))
        .thenReturn(Flowable.just(validResponse));
    // Act
    Flowable<LlmResponse> flowable = gemini.generateContent(llmRequest, true);
    List<LlmResponse> results = flowable.toList().blockingGet();
    // Assert
    assertEquals(1, results.size());
    assertSame(validResponse, results.get(0));
    geminiUtilMock.close();
    geminiStatic.close();
  }

  @Test
  @Tag("boundary")
  @DisplayName("Falls Back to Default Model if LlmRequest Model Absent")
  public void testUsesDefaultModelNameIfRequestModelAbsent() {
    // Arrange
    Client apiClient = mock(Client.class);
    Client.Async async = mock(Client.Async.class);
    Client.Async.Models models = mock(Client.Async.Models.class);
    when(apiClient.async).thenReturn(async);
    when(async.models).thenReturn(models);
    String defaultModelName = "my-default-model";
    LlmRequest llmRequest = mock(LlmRequest.class);
    when(llmRequest.model()).thenReturn(Optional.empty());
    when(llmRequest.contents()).thenReturn(List.of());
    when(llmRequest.config()).thenReturn(Optional.empty());
    GenerateContentResponse genResponse = GenerateContentResponse.builder().build();
    CompletableFuture<GenerateContentResponse> completableResponse =
        CompletableFuture.completedFuture(genResponse);
    when(models.generateContent(eq(defaultModelName), eq(List.of()), eq(null)))
        .thenReturn(completableResponse);
    Gemini gemini = new Gemini(defaultModelName, apiClient);
    MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class);
    geminiUtilMock
        .when(() -> GeminiUtil.prepareGenenerateContentRequest(any(), eq(true), eq(false)))
        .thenReturn(llmRequest);
    MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
    LlmResponse expectedLlmResponse = mock(LlmResponse.class);
    llmResponseMock.when(() -> LlmResponse.create(genResponse)).thenReturn(expectedLlmResponse);
    // Act
    Flowable<LlmResponse> flowable = gemini.generateContent(llmRequest, false);
    List<LlmResponse> responses = flowable.toList().blockingGet();
    // Assert
    assertEquals(1, responses.size());
    assertSame(expectedLlmResponse, responses.get(0));
    verify(models).generateContent(eq(defaultModelName), eq(List.of()), eq(null));
    geminiUtilMock.close();
    llmResponseMock.close();
  }

  @Test
  @Tag("boundary")
  @DisplayName("Handles Null Content in LlmResponse for Filtering")
  public void testStreamingSkipsLlmResponseWithNullContent() {
    // Arrange
    Client apiClient = mock(Client.class);
    Client.Async async = mock(Client.Async.class);
    Client.Async.Models models = mock(Client.Async.Models.class);
    when(apiClient.async).thenReturn(async);
    when(async.models).thenReturn(models);
    String modelName = "stream-null-content";
    LlmRequest llmRequest = mock(LlmRequest.class);
    when(llmRequest.config()).thenReturn(Optional.of(GenerateContentConfig.builder().build()));
    when(llmRequest.model()).thenReturn(Optional.empty());
    when(llmRequest.contents()).thenReturn(List.of());
    ResponseStream<GenerateContentResponse> responseStream = mock(ResponseStream.class);
    CompletableFuture<ResponseStream<GenerateContentResponse>> completedFuture =
        CompletableFuture.completedFuture(responseStream);
    when(models.generateContentStream(eq(modelName), eq(List.of()), any()))
        .thenReturn(completedFuture);
    Gemini gemini = new Gemini(modelName, apiClient);
    LlmResponse nullContentResponse = mock(LlmResponse.class);
    when(nullContentResponse.content()).thenReturn(Optional.empty());
    MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class);
    geminiUtilMock
        .when(() -> GeminiUtil.prepareGenenerateContentRequest(any(), anyBoolean(), eq(false)))
        .thenReturn(llmRequest);
    MockedStatic<Gemini> geminiStatic = mockStatic(Gemini.class);
    geminiStatic
        .when(() -> Gemini.processRawResponses(any()))
        .thenReturn(Flowable.just(nullContentResponse));
    // Act
    Flowable<LlmResponse> flowable = gemini.generateContent(llmRequest, true);
    List<LlmResponse> emitted = flowable.toList().blockingGet();
    // Assert: No emission
    assertEquals(0, emitted.size());
    geminiUtilMock.close();
    geminiStatic.close();
  }

  @Test
  @Tag("boundary")
  @DisplayName("Requests with Empty List of Parts (Streaming Mode)")
  public void testStreamingSkipsResponsesWithEmptyPartsList() {
    // Arrange
    Client apiClient = mock(Client.class);
    Client.Async async = mock(Client.Async.class);
    Client.Async.Models models = mock(Client.Async.Models.class);
    when(apiClient.async).thenReturn(async);
    when(async.models).thenReturn(models);
    String modelName = "stream-empty-parts";
    LlmRequest llmRequest = mock(LlmRequest.class);
    when(llmRequest.config()).thenReturn(Optional.of(GenerateContentConfig.builder().build()));
    when(llmRequest.model()).thenReturn(Optional.empty());
    when(llmRequest.contents()).thenReturn(List.of());
    ResponseStream<GenerateContentResponse> responseStream = mock(ResponseStream.class);
    CompletableFuture<ResponseStream<GenerateContentResponse>> completedFuture =
        CompletableFuture.completedFuture(responseStream);
    when(models.generateContentStream(eq(modelName), eq(List.of()), any()))
        .thenReturn(completedFuture);
    Gemini gemini = new Gemini(modelName, apiClient);
    Content emptyPartsContent = Content.builder().role("model").parts(new ArrayList<>()).build();
    LlmResponse emptyPartsResponse = mock(LlmResponse.class);
    when(emptyPartsResponse.content()).thenReturn(Optional.of(emptyPartsContent));
    MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class);
    geminiUtilMock
        .when(() -> GeminiUtil.prepareGenenerateContentRequest(any(), anyBoolean(), eq(false)))
        .thenReturn(llmRequest);
    MockedStatic<Gemini> geminiStatic = mockStatic(Gemini.class);
    geminiStatic
        .when(() -> Gemini.processRawResponses(any()))
        .thenReturn(Flowable.just(emptyPartsResponse));
    // Act
    Flowable<LlmResponse> flowable = gemini.generateContent(llmRequest, true);
    List<LlmResponse> emitted = flowable.toList().blockingGet();
    // Assert: No emission
    assertEquals(0, emitted.size());
    geminiUtilMock.close();
    geminiStatic.close();
  }

  @Test
  @Tag("boundary")
  @DisplayName("All-Blank-Text Parts Are Filtered Out in Streaming")
  public void testStreamingSkipsResponsesWithOnlyBlankText() {
    // Arrange
    Client apiClient = mock(Client.class);
    Client.Async async = mock(Client.Async.class);
    Client.Async.Models models = mock(Client.Async.Models.class);
    when(apiClient.async).thenReturn(async);
    when(async.models).thenReturn(models);
    String modelName = "stream-blank-text";
    LlmRequest llmRequest = mock(LlmRequest.class);
    when(llmRequest.config()).thenReturn(Optional.of(GenerateContentConfig.builder().build()));
    when(llmRequest.model()).thenReturn(Optional.empty());
    when(llmRequest.contents()).thenReturn(List.of());
    ResponseStream<GenerateContentResponse> responseStream = mock(ResponseStream.class);
    CompletableFuture<ResponseStream<GenerateContentResponse>> completedFuture =
        CompletableFuture.completedFuture(responseStream);
    when(models.generateContentStream(eq(modelName), eq(List.of()), any()))
        .thenReturn(completedFuture);
    Gemini gemini = new Gemini(modelName, apiClient);
    Part blankPart = mock(Part.class);
    when(blankPart.text()).thenReturn(Optional.of(""));
    when(blankPart.functionCall()).thenReturn(Optional.empty());
    when(blankPart.functionResponse()).thenReturn(Optional.empty());
    Content blankTextContent = Content.builder().role("model").parts(blankPart).build();
    LlmResponse blankResponse = mock(LlmResponse.class);
    when(blankResponse.content()).thenReturn(Optional.of(blankTextContent));
    MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class);
    geminiUtilMock
        .when(() -> GeminiUtil.prepareGenenerateContentRequest(any(), anyBoolean(), eq(false)))
        .thenReturn(llmRequest);
    MockedStatic<Gemini> geminiStatic = mockStatic(Gemini.class);
    geminiStatic
        .when(() -> Gemini.processRawResponses(any()))
        .thenReturn(Flowable.just(blankResponse));
    // Act
    Flowable<LlmResponse> flowable = gemini.generateContent(llmRequest, true);
    List<LlmResponse> emitted = flowable.toList().blockingGet();
    // Assert: Should not emit blank text response
    assertEquals(0, emitted.size());
    geminiUtilMock.close();
    geminiStatic.close();
  }

  @Test
  @Tag("boundary")
  @DisplayName("Multiple Streaming Chunks with Mixed Validity")
  public void testStreamingEmitsOnlyValidlyFilteredChunks() {
    // Arrange
    Client apiClient = mock(Client.class);
    Client.Async async = mock(Client.Async.class);
    Client.Async.Models models = mock(Client.Async.Models.class);
    when(apiClient.async).thenReturn(async);
    when(async.models).thenReturn(models);
    String modelName = "stream-mixed-chunks";
    LlmRequest llmRequest = mock(LlmRequest.class);
    when(llmRequest.config()).thenReturn(Optional.of(GenerateContentConfig.builder().build()));
    when(llmRequest.model()).thenReturn(Optional.empty());
    when(llmRequest.contents()).thenReturn(List.of());
    ResponseStream<GenerateContentResponse> responseStream = mock(ResponseStream.class);
    CompletableFuture<ResponseStream<GenerateContentResponse>> completedFuture =
        CompletableFuture.completedFuture(responseStream);
    when(models.generateContentStream(eq(modelName), eq(List.of()), any()))
        .thenReturn(completedFuture);
    Gemini gemini = new Gemini(modelName, apiClient);
    Part validPart = mock(Part.class);
    when(validPart.text()).thenReturn(Optional.of("some valid text"));
    when(validPart.functionCall()).thenReturn(Optional.empty());
    when(validPart.functionResponse()).thenReturn(Optional.empty());
    Content validContent = Content.builder().role("model").parts(validPart).build();
    LlmResponse validResponse = mock(LlmResponse.class);
    when(validResponse.content()).thenReturn(Optional.of(validContent));
    Part blankPart = mock(Part.class);
    when(blankPart.text()).thenReturn(Optional.of(""));
    when(blankPart.functionCall()).thenReturn(Optional.empty());
    when(blankPart.functionResponse()).thenReturn(Optional.empty());
    Content blankContent = Content.builder().role("model").parts(blankPart).build();
    LlmResponse blankResponse = mock(LlmResponse.class);
    when(blankResponse.content()).thenReturn(Optional.of(blankContent));
    LlmResponse nullContentResponse = mock(LlmResponse.class);
    when(nullContentResponse.content()).thenReturn(Optional.empty());
    List<LlmResponse> inputResponses = List.of(validResponse, blankResponse, nullContentResponse);
    MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class);
    geminiUtilMock
        .when(() -> GeminiUtil.prepareGenenerateContentRequest(any(), anyBoolean(), eq(false)))
        .thenReturn(llmRequest);
    MockedStatic<Gemini> geminiStatic = mockStatic(Gemini.class);
    geminiStatic
        .when(() -> Gemini.processRawResponses(any()))
        .thenReturn(Flowable.fromIterable(inputResponses));
    // Act
    Flowable<LlmResponse> flowable = gemini.generateContent(llmRequest, true);
    List<LlmResponse> emitted = flowable.toList().blockingGet();
    // Assert: Only validResponse emitted
    assertTrue(emitted.contains(validResponse));
    assertFalse(emitted.contains(blankResponse));
    assertFalse(emitted.contains(nullContentResponse));
    geminiUtilMock.close();
    geminiStatic.close();
  }

  @Test
  @Tag("boundary")
  @DisplayName("Large Contents List Handling (Stress Test)")
  public void testHandlesLargeContentsListCorrectly() {
    // Arrange
    Client apiClient = mock(Client.class);
    Client.Async async = mock(Client.Async.class);
    Client.Async.Models models = mock(Client.Async.Models.class);
    when(apiClient.async).thenReturn(async);
    when(async.models).thenReturn(models);
    String modelName = "large-list";
    int size = 1000; // TODO: Adjust for very large size as needed
    List<Content> contents = new ArrayList<>(size);
    for (int i = 0; i < size; i++) {
      contents.add(Content.builder().role("user").parts(Part.fromText("test " + i)).build());
    }
    LlmRequest llmRequest = mock(LlmRequest.class);
    when(llmRequest.contents()).thenReturn(contents);
    when(llmRequest.config()).thenReturn(Optional.empty());
    when(llmRequest.model()).thenReturn(Optional.empty());
    GenerateContentResponse genResponse = GenerateContentResponse.builder().build();
    CompletableFuture<GenerateContentResponse> completableResponse =
        CompletableFuture.completedFuture(genResponse);
    when(models.generateContent(eq(modelName), eq(contents), eq(null)))
        .thenReturn(completableResponse);
    Gemini gemini = new Gemini(modelName, apiClient);
    MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class);
    geminiUtilMock
        .when(() -> GeminiUtil.prepareGenenerateContentRequest(any(), anyBoolean(), eq(false)))
        .thenReturn(llmRequest);
    MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
    LlmResponse expectedLlmResponse = mock(LlmResponse.class);
    llmResponseMock.when(() -> LlmResponse.create(genResponse)).thenReturn(expectedLlmResponse);
    // Act
    Flowable<LlmResponse> flowable = gemini.generateContent(llmRequest, false);
    List<LlmResponse> responses = flowable.toList().blockingGet();
    // Assert
    assertEquals(1, responses.size());
    assertSame(expectedLlmResponse, responses.get(0));
    verify(models).generateContent(eq(modelName), eq(contents), eq(null));
    geminiUtilMock.close();
    llmResponseMock.close();
  }

  @Test
  @Tag("boundary")
  @DisplayName("Streaming Respects Partial LlmResponse Marking")
  public void testStreamingMarksPartialResponsesCorrectly() {
    // Arrange
    Client apiClient = mock(Client.class);
    Client.Async async = mock(Client.Async.class);
    Client.Async.Models models = mock(Client.Async.Models.class);
    when(apiClient.async).thenReturn(async);
    when(async.models).thenReturn(models);
    String modelName = "partial-stream";
    LlmRequest llmRequest = mock(LlmRequest.class);
    when(llmRequest.config()).thenReturn(Optional.of(GenerateContentConfig.builder().build()));
    when(llmRequest.model()).thenReturn(Optional.empty());
    when(llmRequest.contents()).thenReturn(List.of());
    ResponseStream<GenerateContentResponse> responseStream = mock(ResponseStream.class);
    CompletableFuture<ResponseStream<GenerateContentResponse>> completedFuture =
        CompletableFuture.completedFuture(responseStream);
    when(models.generateContentStream(eq(modelName), eq(List.of()), any()))
        .thenReturn(completedFuture);
    Gemini gemini = new Gemini(modelName, apiClient);
    LlmResponse partialResponse = mock(LlmResponse.class);
    when(partialResponse.content())
        .thenReturn(
            Optional.of(Content.builder().role("model").parts(Part.fromText("partial")).build()));
    when(partialResponse.partial()).thenReturn(Optional.of(true));
    LlmResponse nonPartialResponse = mock(LlmResponse.class);
    when(nonPartialResponse.content())
        .thenReturn(
            Optional.of(Content.builder().role("model").parts(Part.fromText("complete")).build()));
    when(nonPartialResponse.partial()).thenReturn(Optional.of(false));
    List<LlmResponse> inputResponses = List.of(partialResponse, nonPartialResponse);
    MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class);
    geminiUtilMock
        .when(() -> GeminiUtil.prepareGenenerateContentRequest(any(), anyBoolean(), eq(false)))
        .thenReturn(llmRequest);
    MockedStatic<Gemini> geminiStatic = mockStatic(Gemini.class);
    geminiStatic
        .when(() -> Gemini.processRawResponses(any()))
        .thenReturn(Flowable.fromIterable(inputResponses));
    // Act
    Flowable<LlmResponse> flowable = gemini.generateContent(llmRequest, true);
    List<LlmResponse> emitted = flowable.toList().blockingGet();
    // Assert
    assertTrue(emitted.stream().anyMatch(l -> l.partial().orElse(false)));
    assertTrue(emitted.stream().anyMatch(l -> !l.partial().orElse(true)));
    geminiUtilMock.close();
    geminiStatic.close();
  }

  @Test
  @Tag("integration")
  @DisplayName("Respects VertexAI vs Non-VertexAI API Flag")
  public void testPreparesRequestBasedOnVertexAIFlag() {
    // Arrange
    Client apiClient = mock(Client.class);
    Client.Async async = mock(Client.Async.class);
    Client.Async.Models models = mock(Client.Async.Models.class);
    when(apiClient.async).thenReturn(async);
    when(async.models).thenReturn(models);
    String modelName = "vertex-flag";
    LlmRequest llmRequest = mock(LlmRequest.class);
    LlmRequest preparedRequestTrue = mock(LlmRequest.class);
    LlmRequest preparedRequestFalse = mock(LlmRequest.class);
    when(llmRequest.config()).thenReturn(Optional.empty());
    when(llmRequest.model()).thenReturn(Optional.empty());
    when(llmRequest.contents()).thenReturn(List.of());
    GenerateContentResponse genResponse = GenerateContentResponse.builder().build();
    CompletableFuture<GenerateContentResponse> completableResponse =
        CompletableFuture.completedFuture(genResponse);
    when(models.generateContent(eq(modelName), eq(List.of()), eq(null)))
        .thenReturn(completableResponse);
    Gemini geminiTrue = new Gemini(modelName, apiClient);
    Gemini geminiFalse = new Gemini(modelName, apiClient);
    when(apiClient.vertexAI()).thenReturn(false);
    MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class);
    geminiUtilMock
        .when(() -> GeminiUtil.prepareGenenerateContentRequest(eq(llmRequest), eq(true), eq(false)))
        .thenReturn(preparedRequestTrue);
    geminiUtilMock
        .when(
            () -> GeminiUtil.prepareGenenerateContentRequest(eq(llmRequest), eq(false), eq(false)))
        .thenReturn(preparedRequestFalse);
    MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
    LlmResponse expectedLlmResponse = mock(LlmResponse.class);
    llmResponseMock.when(() -> LlmResponse.create(genResponse)).thenReturn(expectedLlmResponse);
    // Act
    geminiTrue.generateContent(llmRequest, false).toList().blockingGet();
    geminiUtilMock.verify(
        () -> GeminiUtil.prepareGenenerateContentRequest(eq(llmRequest), eq(true), eq(false)),
        times(1));
    when(apiClient.vertexAI()).thenReturn(true);
    geminiFalse.generateContent(llmRequest, false).toList().blockingGet();
    geminiUtilMock.verify(
        () -> GeminiUtil.prepareGenenerateContentRequest(eq(llmRequest), eq(false), eq(false)),
        times(1));
    geminiUtilMock.close();
    llmResponseMock.close();
  }

  @Test
  @Tag("boundary")
  @DisplayName("All Optional Fields Unset in LlmRequest")
  public void testWorksWhenLlmRequestOptionalsUnset() {
    // Arrange
    Client apiClient = mock(Client.class);
    Client.Async async = mock(Client.Async.class);
    Client.Async.Models models = mock(Client.Async.Models.class);
    when(apiClient.async).thenReturn(async);
    when(async.models).thenReturn(models);
    String modelName = "unset-optionals";
    LlmRequest llmRequest = mock(LlmRequest.class);
    when(llmRequest.model()).thenReturn(Optional.empty());
    when(llmRequest.config()).thenReturn(Optional.empty());
    when(llmRequest.contents()).thenReturn(List.of());
    GenerateContentResponse genResponse = GenerateContentResponse.builder().build();
    CompletableFuture<GenerateContentResponse> completableResponse =
        CompletableFuture.completedFuture(genResponse);
    when(models.generateContent(eq(modelName), eq(List.of()), eq(null)))
        .thenReturn(completableResponse);
    Gemini gemini = new Gemini(modelName, apiClient);
    MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class);
    geminiUtilMock
        .when(() -> GeminiUtil.prepareGenenerateContentRequest(any(), anyBoolean(), eq(false)))
        .thenReturn(llmRequest);
    MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
    LlmResponse response = mock(LlmResponse.class);
    llmResponseMock.when(() -> LlmResponse.create(genResponse)).thenReturn(response);
    // Act
    Flowable<LlmResponse> flowable = gemini.generateContent(llmRequest, false);
    List<LlmResponse> emitted = flowable.toList().blockingGet();
    // Assert
    assertEquals(1, emitted.size());
    assertSame(response, emitted.get(0));
    geminiUtilMock.close();
    llmResponseMock.close();
  }

  @Test
  @Tag("integration")
  @DisplayName("Config Passed Through for Streaming")
  public void testPassesConfigThroughInStreamingCalls() {
    // Arrange
    Client apiClient = mock(Client.class);
    Client.Async async = mock(Client.Async.class);
    Client.Async.Models models = mock(Client.Async.Models.class);
    when(apiClient.async).thenReturn(async);
    when(async.models).thenReturn(models);
    String modelName = "stream-pass-config";
    GenerateContentConfig config = GenerateContentConfig.builder().build();
    LlmRequest llmRequest = mock(LlmRequest.class);
    when(llmRequest.config()).thenReturn(Optional.of(config));
    when(llmRequest.model()).thenReturn(Optional.empty());
    when(llmRequest.contents()).thenReturn(List.of());
    ResponseStream<GenerateContentResponse> responseStream = mock(ResponseStream.class);
    CompletableFuture<ResponseStream<GenerateContentResponse>> completedFuture =
        CompletableFuture.completedFuture(responseStream);
    when(models.generateContentStream(eq(modelName), eq(List.of()), eq(config)))
        .thenReturn(completedFuture);
    Gemini gemini = new Gemini(modelName, apiClient);
    MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class);
    geminiUtilMock
        .when(() -> GeminiUtil.prepareGenenerateContentRequest(any(), anyBoolean(), eq(false)))
        .thenReturn(llmRequest);
    MockedStatic<Gemini> geminiStatic = mockStatic(Gemini.class);
    geminiStatic.when(() -> Gemini.processRawResponses(any())).thenReturn(Flowable.empty());
    // Act
    gemini.generateContent(llmRequest, true).toList().blockingGet();
    // Assert
    verify(models).generateContentStream(eq(modelName), eq(List.of()), eq(config));
    geminiUtilMock.close();
    geminiStatic.close();
  }

  @Test
  @Tag("boundary")
  @DisplayName("Completion Guarantees For Non-Streaming Path")
  public void testNonStreamingAlwaysCompletesOrErrors() {
    // Arrange
    Client apiClient = mock(Client.class);
    Client.Async async = mock(Client.Async.class);
    Client.Async.Models models = mock(Client.Async.Models.class);
    when(apiClient.async).thenReturn(async);
    when(async.models).thenReturn(models);
    String modelName = "completion-guarantee";
    LlmRequest llmRequest = mock(LlmRequest.class);
    when(llmRequest.model()).thenReturn(Optional.empty());
    when(llmRequest.config()).thenReturn(Optional.empty());
    when(llmRequest.contents()).thenReturn(List.of());
    // Successful completion
    GenerateContentResponse genResponse = GenerateContentResponse.builder().build();
    CompletableFuture<GenerateContentResponse> completableResponse =
        CompletableFuture.completedFuture(genResponse);
    when(models.generateContent(eq(modelName), eq(List.of()), eq(null)))
        .thenReturn(completableResponse);
    Gemini gemini = new Gemini(modelName, apiClient);
    MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class);
    geminiUtilMock
        .when(() -> GeminiUtil.prepareGenenerateContentRequest(any(), anyBoolean(), eq(false)))
        .thenReturn(llmRequest);
    MockedStatic<LlmResponse> llmResponseMock = mockStatic(LlmResponse.class);
    LlmResponse response = mock(LlmResponse.class);
    llmResponseMock.when(() -> LlmResponse.create(genResponse)).thenReturn(response);
    // Act
    List<LlmResponse> successfulList =
        gemini.generateContent(llmRequest, false).toList().blockingGet();
    assertEquals(1, successfulList.size());
    assertSame(response, successfulList.get(0));
    // Failed completion
    CompletableFuture<GenerateContentResponse> failedFuture = new CompletableFuture<>();
    failedFuture.completeExceptionally(new RuntimeException("fail"));
    when(models.generateContent(eq(modelName), eq(List.of()), eq(null))).thenReturn(failedFuture);
    assertThrows(
        RuntimeException.class,
        () -> {
          gemini.generateContent(llmRequest, false).blockingFirst();
        });
    geminiUtilMock.close();
    llmResponseMock.close();
  }
}
