/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-dec-16-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=builder_2187989d2f
ROOST_METHOD_SIG_HASH=builder_80041265ae

Scenario 1: Successfully Create Builder Instance

Details:
  TestName: builderReturnsNewBuilderInstance
  Description: This test verifies that the builder() static method successfully creates and returns a new Builder instance. The test ensures that the factory method is functioning correctly and provides a valid Builder object for constructing Gemini instances.

Execution:
  Arrange: No specific setup is required as this is a static factory method test.
  Act: Invoke the Gemini.builder() static method to obtain a Builder instance.
  Assert: Use JUnit assertions to verify that the returned object is not null and is an instance of Gemini.Builder class.

Validation:
  The assertion verifies that the builder() method returns a valid, non-null Builder instance. This is critical because the Builder pattern is the primary way to construct Gemini objects with various configuration options. The test ensures that clients can successfully obtain a Builder to configure and create Gemini instances with different authentication methods (API key, Vertex credentials, or explicit client).

Scenario 2: Builder Returns Unique Instances on Multiple Calls

Details:
  TestName: builderReturnsUniqueInstancesOnMultipleCalls
  Description: This test verifies that each invocation of the builder() method returns a distinct Builder instance rather than a singleton or cached instance. This ensures that multiple Builder instances can be created independently without sharing state.

Execution:
  Arrange: No specific setup is required.
  Act: Call Gemini.builder() twice to obtain two separate Builder instances.
  Assert: Use JUnit assertions to verify that the two Builder instances are not the same object reference (using assertNotSame or comparing object identity).

Validation:
  This assertion confirms that the builder() method follows the standard Builder pattern by creating new instances on each call. This is important because it ensures that different parts of an application can independently configure and build Gemini instances without interfering with each other's configuration. If the same Builder instance were returned, it could lead to unexpected state sharing and configuration conflicts.

Scenario 3: Builder Instance Can Be Used to Set Model Name

Details:
  TestName: builderInstanceAllowsModelNameConfiguration
  Description: This test verifies that the Builder instance returned by the builder() method can be used to configure the Gemini object by setting the model name. This ensures the Builder is fully functional and not just a placeholder object.

Execution:
  Arrange: Obtain a Builder instance by calling Gemini.builder().
  Act: Invoke the modelName() method on the Builder instance with a valid model name (e.g., "gemini-2.0-flash").
  Assert: Verify that the modelName() method returns a Builder instance (for method chaining) and does not throw any exceptions.

Validation:
  This test validates that the Builder returned by the builder() method is a fully functional Builder instance that supports the fluent API pattern. The ability to set the model name is fundamental to creating a Gemini instance, and this test ensures that the Builder can be used for its intended purpose. The test also implicitly verifies that the Builder supports method chaining, which is a key characteristic of the Builder pattern.

Scenario 4: Builder Instance Can Be Used to Set API Key

Details:
  TestName: builderInstanceAllowsApiKeyConfiguration
  Description: This test verifies that the Builder instance returned by the builder() method can be used to configure authentication via API key. This ensures that one of the primary authentication methods is accessible through the Builder.

Execution:
  Arrange: Obtain a Builder instance by calling Gemini.builder().
  Act: Invoke the apiKey() method on the Builder instance with a test API key string.
  Assert: Verify that the apiKey() method returns a Builder instance and does not throw any exceptions.

Validation:
  This test confirms that the Builder supports API key-based authentication configuration, which is one of the three authentication methods available for Gemini. The test ensures that clients can use the Builder to configure Gemini instances with API key authentication, which is commonly used for Google Gemini API access. The successful execution of this method is essential for building Gemini instances that authenticate using API keys.

Scenario 5: Builder Instance Can Be Used to Set Vertex Credentials

Details:
  TestName: builderInstanceAllowsVertexCredentialsConfiguration
  Description: This test verifies that the Builder instance returned by the builder() method can be used to configure authentication via Vertex AI credentials. This ensures that Vertex AI authentication is supported through the Builder.

Execution:
  Arrange: Create a mock or test VertexCredentials instance. Obtain a Builder instance by calling Gemini.builder().
  Act: Invoke the vertexCredentials() method on the Builder instance with the test VertexCredentials.
  Assert: Verify that the vertexCredentials() method returns a Builder instance and does not throw any exceptions.

Validation:
  This test validates that the Builder supports Vertex AI credential-based authentication, which is the second authentication method available for Gemini. This is particularly important for enterprise users who access Gemini through Google Cloud's Vertex AI platform. The test ensures that the Builder can be configured with Vertex credentials, enabling the construction of Gemini instances that authenticate through Vertex AI.

Scenario 6: Builder Instance Can Be Used to Set API Client

Details:
  TestName: builderInstanceAllowsApiClientConfiguration
  Description: This test verifies that the Builder instance returned by the builder() method can be used to configure an explicit Client instance. This ensures that advanced users can provide their own pre-configured Client for maximum flexibility.

Execution:
  Arrange: Create a mock or test Client instance. Obtain a Builder instance by calling Gemini.builder().
  Act: Invoke the apiClient() method on the Builder instance with the test Client.
  Assert: Verify that the apiClient() method returns a Builder instance and does not throw any exceptions.

Validation:
  This test confirms that the Builder supports explicit Client configuration, which is the third and most flexible authentication method. This allows advanced users to provide a fully configured Client instance with custom settings, headers, or authentication mechanisms. The test ensures that the Builder can accommodate this use case, providing maximum flexibility for users who need fine-grained control over the API client configuration.

Scenario 7: Builder Method Is Thread-Safe for Concurrent Access

Details:
  TestName: builderMethodIsThreadSafeForConcurrentAccess
  Description: This test verifies that the builder() static method can be safely called from multiple threads concurrently without causing race conditions or returning corrupted Builder instances. This ensures thread safety in multi-threaded applications.

Execution:
  Arrange: Create multiple threads that will concurrently call Gemini.builder().
  Act: Execute the threads simultaneously, each calling Gemini.builder() and storing the returned Builder instance.
  Assert: Verify that all threads successfully obtained valid, non-null Builder instances and that no exceptions were thrown during concurrent access.

Validation:
  This test validates that the builder() method is thread-safe, which is critical for applications that may need to create multiple Gemini instances concurrently from different threads. Since the method creates new instances rather than managing shared state, it should be inherently thread-safe, but this test confirms that behavior. Thread safety is essential for enterprise applications and frameworks that may use Gemini in concurrent contexts.

Scenario 8: Builder Instance Supports Method Chaining

Details:
  TestName: builderInstanceSupportsMethodChaining
  Description: This test verifies that the Builder instance returned by builder() supports fluent method chaining by allowing multiple configuration methods to be called in sequence. This ensures the Builder follows the fluent API pattern.

Execution:
  Arrange: Obtain a Builder instance by calling Gemini.builder().
  Act: Chain multiple configuration methods together (e.g., modelName().apiKey()) in a single statement.
  Assert: Verify that the chained method calls execute successfully without throwing exceptions and that each method returns a Builder instance.

Validation:
  This test confirms that the Builder implements the fluent API pattern correctly, allowing for readable and concise configuration code. Method chaining is a key characteristic of the Builder pattern and improves code readability by allowing configuration to be expressed in a single, flowing statement. This test ensures that developers can use the Builder in the idiomatic way expected from Builder pattern implementations.

*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.genai.Client;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class GeminiBuilderTest {

	@Test
	@Tag("valid")
	@DisplayName("builderReturnsNewBuilderInstance")
	void builderReturnsNewBuilderInstance() {
		Gemini.Builder builder = Gemini.builder();

		assertNotNull(builder);
		assertTrue(builder instanceof Gemini.Builder);
	}

	@Test
	@Tag("valid")
	@DisplayName("builderReturnsUniqueInstancesOnMultipleCalls")
	void builderReturnsUniqueInstancesOnMultipleCalls() {
		Gemini.Builder builder1 = Gemini.builder();
		Gemini.Builder builder2 = Gemini.builder();

		assertNotNull(builder1);
		assertNotNull(builder2);
		assertNotSame(builder1, builder2);
	}

	@Test
	@Tag("valid")
	@DisplayName("builderInstanceAllowsModelNameConfiguration")
	void builderInstanceAllowsModelNameConfiguration() {
		Gemini.Builder builder = Gemini.builder();

		assertDoesNotThrow(() -> {
			Gemini.Builder result = builder.modelName("gemini-2.0-flash");
			assertNotNull(result);
			assertTrue(result instanceof Gemini.Builder);
		});
	}

	@Test
	@Tag("valid")
	@DisplayName("builderInstanceAllowsApiKeyConfiguration")
	void builderInstanceAllowsApiKeyConfiguration() {
		Gemini.Builder builder = Gemini.builder();

		assertDoesNotThrow(() -> {
			Gemini.Builder result = builder.apiKey("test-api-key-12345");
			assertNotNull(result);
			assertTrue(result instanceof Gemini.Builder);
		});
	}

	@Test
	@Tag("valid")
	@DisplayName("builderInstanceAllowsVertexCredentialsConfiguration")
	void builderInstanceAllowsVertexCredentialsConfiguration() {
		Gemini.Builder builder = Gemini.builder();
		VertexCredentials mockCredentials = VertexCredentials.builder().build();

		assertDoesNotThrow(() -> {
			Gemini.Builder result = builder.vertexCredentials(mockCredentials);
			assertNotNull(result);
			assertTrue(result instanceof Gemini.Builder);
		});
	}

	@Test
	@Tag("valid")
	@DisplayName("builderInstanceAllowsApiClientConfiguration")
	void builderInstanceAllowsApiClientConfiguration() {
		Gemini.Builder builder = Gemini.builder();
		Client mockClient = Client.builder().apiKey("test-key").build();

		assertDoesNotThrow(() -> {
			Gemini.Builder result = builder.apiClient(mockClient);
			assertNotNull(result);
			assertTrue(result instanceof Gemini.Builder);
		});
	}

	@Test
	@Tag("valid")
	@DisplayName("builderMethodIsThreadSafeForConcurrentAccess")
	void builderMethodIsThreadSafeForConcurrentAccess() throws InterruptedException {
		int threadCount = 10;
		ExecutorService executorService = Executors.newFixedThreadPool(threadCount);
		CountDownLatch latch = new CountDownLatch(threadCount);
		List<Gemini.Builder> builders = new ArrayList<>();
		AtomicInteger successCount = new AtomicInteger(0);
		AtomicInteger exceptionCount = new AtomicInteger(0);
		for (int i = 0; i < threadCount; i++) {
			executorService.submit(() -> {
				try {
					Gemini.Builder builder = Gemini.builder();
					synchronized (builders) {
						builders.add(builder);
					}
					if (builder != null) {
						successCount.incrementAndGet();
					}
				}
				catch (Exception e) {
					exceptionCount.incrementAndGet();
				}
				finally {
					latch.countDown();
				}
			});
		}
		assertTrue(latch.await(5, TimeUnit.SECONDS));
		executorService.shutdown();
		assertEquals(threadCount, successCount.get());
		assertEquals(0, exceptionCount.get());
		assertEquals(threadCount, builders.size());

		for (Gemini.Builder builder : builders) {
			assertNotNull(builder);
		}
	}

	@Test
	@Tag("valid")
	@DisplayName("builderInstanceSupportsMethodChaining")
	void builderInstanceSupportsMethodChaining() {
		assertDoesNotThrow(() -> {
			Gemini.Builder result = Gemini.builder().modelName("gemini-2.0-flash").apiKey("test-api-key");

			assertNotNull(result);
			assertTrue(result instanceof Gemini.Builder);
		});
	}

	@Test
	@Tag("valid")
	@DisplayName("builderInstanceSupportsCompleteMethodChaining")
	void builderInstanceSupportsCompleteMethodChaining() {
		Client mockClient = Client.builder().apiKey("test-key").build();

		assertDoesNotThrow(() -> {
			Gemini.Builder result = Gemini.builder().modelName("gemini-2.0-flash").apiClient(mockClient);

			assertNotNull(result);
		});
	}

	@Test
	@Tag("valid")
	@DisplayName("builderInstanceSupportsVertexCredentialsChaining")
	void builderInstanceSupportsVertexCredentialsChaining() {
		VertexCredentials credentials = VertexCredentials.builder().build();

		assertDoesNotThrow(() -> {
			Gemini.Builder result = Gemini.builder().modelName("gemini-2.0-flash").vertexCredentials(credentials);

			assertNotNull(result);
		});
	}

	@Test
	@Tag("boundary")
	@DisplayName("builderReturnsValidInstanceWithNoConfiguration")
	void builderReturnsValidInstanceWithNoConfiguration() {
		Gemini.Builder builder = Gemini.builder();

		assertNotNull(builder);
		assertDoesNotThrow(() -> builder.toString());
	}

	@Test
	@Tag("valid")
	@DisplayName("multipleBuilderCallsReturnIndependentInstances")
	void multipleBuilderCallsReturnIndependentInstances() {
		Gemini.Builder builder1 = Gemini.builder().modelName("model-1");
		Gemini.Builder builder2 = Gemini.builder().modelName("model-2");

		assertNotNull(builder1);
		assertNotNull(builder2);
		assertNotSame(builder1, builder2);
	}

	@Test
	@Tag("valid")
	@DisplayName("builderInstanceCanBeReusedForMultipleConfigurations")
	void builderInstanceCanBeReusedForMultipleConfigurations() {
		Gemini.Builder builder = Gemini.builder();

		assertDoesNotThrow(() -> {
			builder.modelName("gemini-1.0");
			builder.modelName("gemini-2.0");
			builder.apiKey("key-1");
			builder.apiKey("key-2");
		});

		assertNotNull(builder);
	}

	@Test
	@Tag("integration")
	@DisplayName("builderCanBeUsedToBuildGeminiInstanceWithApiKey")
	void builderCanBeUsedToBuildGeminiInstanceWithApiKey() {
		assertDoesNotThrow(() -> {
			Gemini gemini = Gemini.builder().modelName("gemini-2.0-flash").apiKey("test-api-key-12345").build();

			assertNotNull(gemini);
		});
	}

	@Test
	@Tag("integration")
	@DisplayName("builderCanBeUsedToBuildGeminiInstanceWithClient")
	void builderCanBeUsedToBuildGeminiInstanceWithClient() {
		Client client = Client.builder().apiKey("test-key").build();

		assertDoesNotThrow(() -> {
			Gemini gemini = Gemini.builder().modelName("gemini-2.0-flash").apiClient(client).build();

			assertNotNull(gemini);
		});
	}

	@Test
	@Tag("valid")
	@DisplayName("builderStaticMethodIsAccessibleFromClass")
	void builderStaticMethodIsAccessibleFromClass() {
		assertDoesNotThrow(() -> {
			Gemini.Builder builder = Gemini.builder();
			assertNotNull(builder);
		});
	}

}
