/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-dec-17-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=prepareGenenerateContentRequest_1d11c15a2c
ROOST_METHOD_SIG_HASH=prepareGenenerateContentRequest_5633670894

Scenario 1: Both sanitize and stripThoughts flags are false

Details:
  TestName: prepareGenerateContentRequestWithNoSanitizeAndNoStripThoughts
  Description: This test verifies that when both sanitize and stripThoughts parameters are set to false, the method only ensures that the last content is from the user role by calling ensureModelResponse, without performing any sanitization or thought stripping operations.
Execution:
  Arrange: Create an LlmRequest with a list of Content objects where the last content has a role other than "user" (e.g., "model"). Set sanitize to false and stripThoughts to false.
  Act: Invoke prepareGenenerateContentRequest with the created LlmRequest, sanitize=false, and stripThoughts=false.
  Assert: Verify that the returned LlmRequest contains the original contents plus an additional user content with CONTINUE_OUTPUT_MESSAGE. Verify that no sanitization occurred (e.g., labels are still present if they were in the original request). Verify that thought parts are still present if they existed in the original request.
Validation:
  This assertion verifies that when both flags are disabled, the method performs minimal processing - only ensuring the conversation ends with a user message to prompt a model response. This is important for scenarios where the request is already properly formatted and no additional processing is needed.

Scenario 2: sanitize is true and stripThoughts is false

Details:
  TestName: prepareGenerateContentRequestWithSanitizeAndNoStripThoughts
  Description: This test checks that when sanitize is true and stripThoughts is false, the method sanitizes the request by removing labels and display names from inline data and file data, ensures model response, but does not strip thought parts.
Execution:
  Arrange: Create an LlmRequest with config containing labels, and contents with parts containing inlineData with displayName and fileData with displayName. Also include parts marked as thoughts. Set sanitize to true and stripThoughts to false.
  Act: Invoke prepareGenenerateContentRequest with the created LlmRequest, sanitize=true, and stripThoughts=false.
  Assert: Verify that the returned LlmRequest has no labels in the config. Verify that displayName is removed from both inlineData and fileData. Verify that thought parts are still present. Verify that the last content is from "user" role.
Validation:
  This assertion confirms that sanitization removes Vertex AI-specific parameters (labels, display names) to ensure compatibility with the Gemini API backend, while preserving thought parts when stripThoughts is disabled. This is crucial for maintaining API compatibility while retaining internal metadata.

Scenario 3: sanitize is false and stripThoughts is true

Details:
  TestName: prepareGenerateContentRequestWithNoSanitizeAndStripThoughts
  Description: This test validates that when sanitize is false and stripThoughts is true, the method strips out parts marked as thoughts and ensures model response, but does not perform sanitization.
Execution:
  Arrange: Create an LlmRequest with config containing labels, and contents with parts where some parts have thought set to true. Set sanitize to false and stripThoughts to true.
  Act: Invoke prepareGenenerateContentRequest with the created LlmRequest, sanitize=false, and stripThoughts=true.
  Assert: Verify that the returned LlmRequest still contains labels in the config (no sanitization). Verify that all parts with thought=true are removed from the contents. Verify that parts with thought=false or no thought field are retained. Verify that the last content is from "user" role.
Validation:
  This assertion ensures that thought stripping works independently of sanitization, removing internal reasoning parts while preserving the original request structure. This is important for scenarios where we want to hide the model's internal reasoning process from the final output.

Scenario 4: Both sanitize and stripThoughts are true

Details:
  TestName: prepareGenerateContentRequestWithSanitizeAndStripThoughts
  Description: This test verifies that when both sanitize and stripThoughts are true, the method performs both sanitization and thought stripping operations, along with ensuring model response.
Execution:
  Arrange: Create an LlmRequest with config containing labels, contents with parts containing inlineData with displayName, fileData with displayName, and some parts marked as thoughts. Set sanitize to true and stripThoughts to true.
  Act: Invoke prepareGenenerateContentRequest with the created LlmRequest, sanitize=true, and stripThoughts=true.
  Assert: Verify that the returned LlmRequest has no labels in the config. Verify that displayName is removed from both inlineData and fileData. Verify that all parts with thought=true are removed. Verify that the last content is from "user" role.
Validation:
  This assertion confirms that both operations can be performed together, producing a fully sanitized and thought-stripped request suitable for the Gemini API. This is the most common use case for production scenarios where we need maximum compatibility and clean output.

Scenario 5: Empty contents list with sanitize true

Details:
  TestName: prepareGenerateContentRequestWithEmptyContentsAndSanitize
  Description: This test checks the behavior when the LlmRequest has an empty contents list and sanitize is true.
Execution:
  Arrange: Create an LlmRequest with an empty contents list and config containing labels. Set sanitize to true and stripThoughts to true.
  Act: Invoke prepareGenenerateContentRequest with the created LlmRequest, sanitize=true, and stripThoughts=true.
  Assert: Verify that the returned LlmRequest has no labels in the config. Verify that a new user content with CONTINUE_OUTPUT_MESSAGE is added to the contents list (from ensureModelResponse).
Validation:
  This assertion verifies that the method handles empty contents gracefully by adding a user prompt to initiate model response, while still performing sanitization. This is important for edge cases where a conversation might start without any initial content.

Scenario 6: Contents list ending with user role

Details:
  TestName: prepareGenerateContentRequestWithLastContentAsUser
  Description: This test validates that when the contents list already ends with a user role content, no additional user content is added.
Execution:
  Arrange: Create an LlmRequest with contents where the last content has role="user". Set sanitize to false and stripThoughts to false.
  Act: Invoke prepareGenenerateContentRequest with the created LlmRequest, sanitize=false, and stripThoughts=false.
  Assert: Verify that the returned LlmRequest has the same number of contents as the original. Verify that no CONTINUE_OUTPUT_MESSAGE was added. Verify that the last content still has role="user".
Validation:
  This assertion ensures that the method does not add redundant user prompts when the conversation already ends appropriately. This prevents unnecessary message duplication and maintains conversation flow integrity.

Scenario 7: Contents with parts containing only thought=false

Details:
  TestName: prepareGenerateContentRequestWithThoughtFalseParts
  Description: This test checks that parts with thought explicitly set to false are retained when stripThoughts is true.
Execution:
  Arrange: Create an LlmRequest with contents containing parts where thought is explicitly set to false. Set sanitize to false and stripThoughts to true.
  Act: Invoke prepareGenenerateContentRequest with the created LlmRequest, sanitize=false, and stripThoughts=true.
  Assert: Verify that all parts with thought=false are retained in the returned LlmRequest. Verify that the content structure remains intact.
Validation:
  This assertion confirms that the stripThoughts operation only removes parts where thought=true, not parts where thought is explicitly false. This is important for maintaining parts that are explicitly marked as non-thoughts.

Scenario 8: Contents with parts containing no thought field

Details:
  TestName: prepareGenerateContentRequestWithNoThoughtField
  Description: This test validates that parts without a thought field are retained when stripThoughts is true.
Execution:
  Arrange: Create an LlmRequest with contents containing parts that do not have a thought field at all. Set sanitize to false and stripThoughts to true.
  Act: Invoke prepareGenenerateContentRequest with the created LlmRequest, sanitize=false, and stripThoughts=true.
  Assert: Verify that all parts without a thought field are retained in the returned LlmRequest. Verify that the content structure remains intact.
Validation:
  This assertion ensures that parts without the thought field are treated as non-thoughts and are preserved. This is the default behavior for most parts and is critical for maintaining normal conversation content.

Scenario 9: Contents with mixed thought values

Details:
  TestName: prepareGenerateContentRequestWithMixedThoughtValues
  Description: This test checks the behavior when contents have a mix of parts with thought=true, thought=false, and no thought field.
Execution:
  Arrange: Create an LlmRequest with contents containing multiple parts: some with thought=true, some with thought=false, and some without a thought field. Set sanitize to false and stripThoughts to true.
  Act: Invoke prepareGenenerateContentRequest with the created LlmRequest, sanitize=false, and stripThoughts=true.
  Assert: Verify that only parts with thought=true are removed. Verify that parts with thought=false and parts without a thought field are retained. Verify the order of remaining parts is preserved.
Validation:
  This assertion validates the selective filtering logic of stripThoughts, ensuring it correctly identifies and removes only the thought parts while preserving all other content. This is important for complex conversations with mixed content types.

Scenario 10: Contents with empty parts list

Details:
  TestName: prepareGenerateContentRequestWithEmptyPartsList
  Description: This test validates the behavior when a Content object has an empty parts list.
Execution:
  Arrange: Create an LlmRequest with contents where one or more Content objects have an empty parts list. Set sanitize to false and stripThoughts to true.
  Act: Invoke prepareGenenerateContentRequest with the created LlmRequest, sanitize=false, and stripThoughts=true.
  Assert: Verify that Content objects with empty parts lists are preserved in the returned LlmRequest. Verify that no errors occur during processing.
Validation:
  This assertion ensures that the method handles edge cases gracefully, such as Content objects without parts. This is important for robustness and preventing null pointer exceptions.

Scenario 11: Sanitize with no labels in config

Details:
  TestName: prepareGenerateContentRequestSanitizeWithNoLabels
  Description: This test checks that sanitization works correctly when the config does not contain labels.
Execution:
  Arrange: Create an LlmRequest with config that does not contain labels, but has contents with inlineData and fileData with displayName. Set sanitize to true and stripThoughts to false.
  Act: Invoke prepareGenenerateContentRequest with the created LlmRequest, sanitize=true, and stripThoughts=false.
  Assert: Verify that the config remains unchanged (no labels were present to remove). Verify that displayName is removed from inlineData and fileData. Verify that the request is otherwise intact.
Validation:
  This assertion confirms that sanitization handles cases where labels are not present, focusing only on removing display names from file data. This ensures the method is robust to different config structures.

Scenario 12: Sanitize with inlineData without displayName

Details:
  TestName: prepareGenerateContentRequestSanitizeInlineDataWithoutDisplayName
  Description: This test validates that sanitization preserves inlineData that does not have a displayName.
Execution:
  Arrange: Create an LlmRequest with contents containing parts with inlineData that has data and mimeType but no displayName. Set sanitize to true and stripThoughts to false.
  Act: Invoke prepareGenenerateContentRequest with the created LlmRequest, sanitize=true, and stripThoughts=false.
  Assert: Verify that the inlineData is preserved with its data and mimeType intact. Verify that no modifications are made to inlineData without displayName.
Validation:
  This assertion ensures that sanitization only removes displayName when present and does not affect inlineData that is already compatible with the Gemini API. This is important for avoiding unnecessary data manipulation.

Scenario 13: Sanitize with fileData without displayName

Details:
  TestName: prepareGenerateContentRequestSanitizeFileDataWithoutDisplayName
  Description: This test checks that sanitization preserves fileData that does not have a displayName.
Execution:
  Arrange: Create an LlmRequest with contents containing parts with fileData that has fileUri and mimeType but no displayName. Set sanitize to true and stripThoughts to false.
  Act: Invoke prepareGenenerateContentRequest with the created LlmRequest, sanitize=true, and stripThoughts=false.
  Assert: Verify that the fileData is preserved with its fileUri and mimeType intact. Verify that no modifications are made to fileData without displayName.
Validation:
  This assertion confirms that sanitization is selective and only removes displayName from fileData when present, leaving properly formatted fileData unchanged. This maintains data integrity for already compatible requests.

Scenario 14: Contents ending with model role

Details:
  TestName: prepareGenerateContentRequestWithLastContentAsModel
  Description: This test validates that when the last content has role="model", a user content with CONTINUE_OUTPUT_MESSAGE is appended.
Execution:
  Arrange: Create an LlmRequest with contents where the last content has role="model". Set sanitize to false and stripThoughts to false.
  Act: Invoke prepareGenenerateContentRequest with the created LlmRequest, sanitize=false, and stripThoughts=false.
  Assert: Verify that the returned LlmRequest has one more content than the original. Verify that the last content has role="user" and contains a part with text equal to CONTINUE_OUTPUT_MESSAGE.
Validation:
  This assertion ensures that the method correctly identifies when the conversation ends with a model response and adds a user prompt to continue the conversation. This is essential for maintaining proper conversation flow in multi-turn interactions.

Scenario 15: Contents ending with role in different case

Details:
  TestName: prepareGenerateContentRequestWithLastContentRoleDifferentCase
  Description: This test checks that role comparison is case-insensitive when determining if the last content is from the user.
Execution:
  Arrange: Create an LlmRequest with contents where the last content has role="USER" (uppercase). Set sanitize to false and stripThoughts to false.
  Act: Invoke prepareGenenerateContentRequest with the created LlmRequest, sanitize=false, and stripThoughts=false.
  Assert: Verify that the returned LlmRequest has the same number of contents as the original (no additional user content added). Verify that the last content still has role="USER".
Validation:
  This assertion confirms that the role comparison in ensureModelResponse is case-insensitive, treating "USER", "user", and "User" as equivalent. This is important for handling variations in role formatting from different sources.

Scenario 16: Contents with no role specified

Details:
  TestName: prepareGenerateContentRequestWithLastContentNoRole
  Description: This test validates the behavior when the last content does not have a role specified.
Execution:
  Arrange: Create an LlmRequest with contents where the last content has no role (empty Optional). Set sanitize to false and stripThoughts to false.
  Act: Invoke prepareGenenerateContentRequest with the created LlmRequest, sanitize=false, and stripThoughts=false.
  Assert: Verify that the returned LlmRequest has one more content than the original. Verify that the last content has role="user" and contains CONTINUE_OUTPUT_MESSAGE.
Validation:
  This assertion ensures that when the role is not specified, the method treats it as non-user and adds a user prompt. This is important for handling incomplete or malformed content objects.

Scenario 17: Multiple contents all with thought=true

Details:
  TestName: prepareGenerateContentRequestWithAllThoughtParts
  Description: This test checks the behavior when all parts in all contents have thought=true and stripThoughts is enabled.
Execution:
  Arrange: Create an LlmRequest with multiple contents, where all parts in all contents have thought=true. Set sanitize to false and stripThoughts to true.
  Act: Invoke prepareGenenerateContentRequest with the created LlmRequest, sanitize=false, and stripThoughts=true.
  Assert: Verify that all contents in the returned LlmRequest have empty parts lists. Verify that the content objects themselves are retained but with no parts. Verify that a user content with CONTINUE_OUTPUT_MESSAGE is added at the end.
Validation:
  This assertion validates that stripThoughts removes all thought parts while preserving the content structure, and that ensureModelResponse still adds a user prompt when needed. This is important for scenarios where the entire conversation consists of internal reasoning.

Scenario 18: Sanitize with both inlineData and fileData in same part

Details:
  TestName: prepareGenerateContentRequestSanitizeWithBothInlineAndFileData
  Description: This test validates sanitization when a part contains both inlineData with displayName and fileData with displayName.
Execution:
  Arrange: Create an LlmRequest with contents containing a part that has both inlineData with displayName and fileData with displayName. Set sanitize to true and stripThoughts to false.
  Act: Invoke prepareGenenerateContentRequest with the created LlmRequest, sanitize=true, and stripThoughts=false.
  Assert: Verify that displayName is removed from both inlineData and fileData in the same part. Verify that data and mimeType are preserved for both inlineData and fileData.
Validation:
  This assertion ensures that sanitization handles complex parts with multiple data types correctly, removing displayName from all applicable fields. This is important for comprehensive sanitization of complex requests.

Scenario 19: StripThoughts with content having no parts Optional

Details:
  TestName: prepareGenerateContentRequestStripThoughtsWithNoPartsOptional
  Description: This test checks the behavior when a Content object has parts as an empty Optional.
Execution:
  Arrange: Create an LlmRequest with contents where one Content object has parts as Optional.empty(). Set sanitize to false and stripThoughts to true.
  Act: Invoke prepareGenenerateContentRequest with the created LlmRequest, sanitize=false, and stripThoughts=true.
  Assert: Verify that the Content with empty Optional parts is preserved in the returned LlmRequest. Verify that no errors occur during processing.
Validation:
  This assertion ensures that the stripThoughts operation handles Optional.empty() gracefully, treating it as an empty list. This is important for robustness when dealing with incomplete content objects.

Scenario 20: Complex scenario with all operations

Details:
  TestName: prepareGenerateContentRequestComplexScenario
  Description: This test validates a complex scenario with multiple contents, mixed thought values, display names, labels, and ending with a model role.
Execution:
  Arrange: Create an LlmRequest with config containing labels, multiple contents with mixed parts (some with thought=true, some with thought=false, some with no thought field), parts with inlineData and fileData containing displayName, and the last content having role="model". Set sanitize to true and stripThoughts to true.
  Act: Invoke prepareGenenerateContentRequest with the created LlmRequest, sanitize=true, and stripThoughts=true.
  Assert: Verify that labels are removed from config. Verify that displayName is removed from all inlineData and fileData. Verify that all parts with thought=true are removed. Verify that parts with thought=false or no thought field are retained. Verify that a user content with CONTINUE_OUTPUT_MESSAGE is added at the end.
Validation:
  This assertion validates the complete functionality of the method in a realistic complex scenario, ensuring all operations work together correctly. This is the most comprehensive test and represents real-world usage patterns.

*/

// ********RoostGPT********

package com.google.adk.models;

import static com.google.common.collect.ImmutableList.toImmutableList;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import com.google.genai.types.Blob;
import com.google.genai.types.Content;
import com.google.genai.types.FileData;
import com.google.genai.types.Part;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.*;
import com.google.common.base.Ascii;
import com.google.common.collect.Iterables;
import java.util.stream.Stream;

class GeminiUtilPrepareGenenerateContentRequest225Test {

	@Test
	@Tag("valid")
	void prepareGenerateContentRequestWithNoSanitizeAndNoStripThoughts() {
		Part part = Part.builder().text("Test message").build();
		Content modelContent = Content.builder().parts(ImmutableList.of(part)).role("model").build();
		LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(modelContent)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, false, false);
		assertNotNull(result);
		assertEquals(2, result.contents().size());
		assertEquals("model", result.contents().get(0).role().orElse(""));
		assertEquals("user", result.contents().get(1).role().orElse(""));
		assertTrue(result.contents().get(1).parts().get().get(0).text().orElse("").contains("Continue output"));
	}

	@Test
	@Tag("valid")
	void prepareGenerateContentRequestWithSanitizeAndNoStripThoughts() {
		Blob blobWithDisplayName = Blob.builder()
			.data(new byte[] { 1, 2, 3 })
			.mimeType("image/png")
			.displayName("testImage")
			.build();
		FileData fileDataWithDisplayName = FileData.builder()
			.fileUri("gs://test/file")
			.mimeType("application/pdf")
			.displayName("testFile")
			.build();
		Part partWithInlineData = Part.builder().inlineData(blobWithDisplayName).build();
		Part partWithFileData = Part.builder().fileData(fileDataWithDisplayName).build();
		Part thoughtPart = Part.builder().text("Thought").thought(true).build();

		Content content = Content.builder()
			.parts(ImmutableList.of(partWithInlineData, partWithFileData, thoughtPart))
			.role("user")
			.build();

		LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, true, false);
		assertNotNull(result);
		assertFalse(result.contents().get(0).parts().get().get(0).inlineData().get().displayName().isPresent());
		assertFalse(result.contents().get(0).parts().get().get(1).fileData().get().displayName().isPresent());
		assertEquals(3, result.contents().get(0).parts().get().size());
	}

	@Test
	@Tag("valid")
	void prepareGenerateContentRequestWithNoSanitizeAndStripThoughts() {
		Part thoughtPart = Part.builder().text("Thought").thought(true).build();
		Part normalPart = Part.builder().text("Normal").thought(false).build();
		Part noThoughtPart = Part.builder().text("No thought field").build();

		Content content = Content.builder()
			.parts(ImmutableList.of(thoughtPart, normalPart, noThoughtPart))
			.role("user")
			.build();

		LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, false, true);
		assertNotNull(result);
		assertEquals(2, result.contents().get(0).parts().get().size());
		assertFalse(result.contents().get(0).parts().get().stream().anyMatch(p -> p.thought().orElse(false)));
	}

	@Test
	@Tag("valid")
	void prepareGenerateContentRequestWithSanitizeAndStripThoughts() {
		Blob blobWithDisplayName = Blob.builder()
			.data(new byte[] { 1, 2, 3 })
			.mimeType("image/png")
			.displayName("testImage")
			.build();
		FileData fileDataWithDisplayName = FileData.builder()
			.fileUri("gs://test/file")
			.mimeType("application/pdf")
			.displayName("testFile")
			.build();
		Part partWithInlineData = Part.builder().inlineData(blobWithDisplayName).build();
		Part partWithFileData = Part.builder().fileData(fileDataWithDisplayName).build();
		Part thoughtPart = Part.builder().text("Thought").thought(true).build();

		Content content = Content.builder()
			.parts(ImmutableList.of(partWithInlineData, partWithFileData, thoughtPart))
			.role("user")
			.build();

		LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, true, true);
		assertNotNull(result);
		assertFalse(result.contents().get(0).parts().get().get(0).inlineData().get().displayName().isPresent());
		assertFalse(result.contents().get(0).parts().get().get(1).fileData().get().displayName().isPresent());
		assertEquals(2, result.contents().get(0).parts().get().size());
	}

	@Test
	@Tag("boundary")
	void prepareGenerateContentRequestWithEmptyContentsAndSanitize() {
		LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of()).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, true, true);
		assertNotNull(result);
		assertEquals(1, result.contents().size());
		assertEquals("user", result.contents().get(0).role().orElse(""));
		assertTrue(result.contents().get(0).parts().get().get(0).text().orElse("").contains("Continue output"));
	}

	@Test
	@Tag("valid")
	void prepareGenerateContentRequestWithLastContentAsUser() {
		Part part = Part.builder().text("User message").build();
		Content userContent = Content.builder().parts(ImmutableList.of(part)).role("user").build();

		LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(userContent)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, false, false);
		assertNotNull(result);
		assertEquals(1, result.contents().size());
		assertEquals("user", result.contents().get(0).role().orElse(""));
	}

	@Test
	@Tag("valid")
	void prepareGenerateContentRequestWithThoughtFalseParts() {
		Part thoughtFalsePart1 = Part.builder().text("Part 1").thought(false).build();
		Part thoughtFalsePart2 = Part.builder().text("Part 2").thought(false).build();

		Content content = Content.builder()
			.parts(ImmutableList.of(thoughtFalsePart1, thoughtFalsePart2))
			.role("user")
			.build();

		LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, false, true);
		assertNotNull(result);
		assertEquals(2, result.contents().get(0).parts().get().size());
		assertTrue(result.contents().get(0).parts().get().stream().allMatch(p -> p.thought().orElse(true) == false));
	}

	@Test
	@Tag("valid")
	void prepareGenerateContentRequestWithNoThoughtField() {
		Part part1 = Part.builder().text("Part 1").build();
		Part part2 = Part.builder().text("Part 2").build();

		Content content = Content.builder().parts(ImmutableList.of(part1, part2)).role("user").build();

		LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, false, true);
		assertNotNull(result);
		assertEquals(2, result.contents().get(0).parts().get().size());
	}

	@Test
	@Tag("valid")
	void prepareGenerateContentRequestWithMixedThoughtValues() {
		Part thoughtTruePart = Part.builder().text("Thought").thought(true).build();
		Part thoughtFalsePart = Part.builder().text("Not thought").thought(false).build();
		Part noThoughtPart = Part.builder().text("No field").build();

		Content content = Content.builder()
			.parts(ImmutableList.of(thoughtTruePart, thoughtFalsePart, noThoughtPart))
			.role("user")
			.build();

		LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, false, true);
		assertNotNull(result);
		assertEquals(2, result.contents().get(0).parts().get().size());
		assertEquals("Not thought", result.contents().get(0).parts().get().get(0).text().orElse(""));
		assertEquals("No field", result.contents().get(0).parts().get().get(1).text().orElse(""));
	}

	@Test
	@Tag("boundary")
	void prepareGenerateContentRequestWithEmptyPartsList() {
		Content emptyPartsContent = Content.builder().parts(ImmutableList.of()).role("user").build();

		LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(emptyPartsContent)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, false, true);
		assertNotNull(result);
		assertEquals(1, result.contents().size());
		assertTrue(result.contents().get(0).parts().get().isEmpty());
	}

	@Test
	@Tag("valid")
	void prepareGenerateContentRequestSanitizeWithNoLabels() {
		Blob blobWithDisplayName = Blob.builder()
			.data(new byte[] { 1, 2, 3 })
			.mimeType("image/png")
			.displayName("testImage")
			.build();
		FileData fileDataWithDisplayName = FileData.builder()
			.fileUri("gs://test/file")
			.mimeType("application/pdf")
			.displayName("testFile")
			.build();
		Part partWithInlineData = Part.builder().inlineData(blobWithDisplayName).build();
		Part partWithFileData = Part.builder().fileData(fileDataWithDisplayName).build();

		Content content = Content.builder()
			.parts(ImmutableList.of(partWithInlineData, partWithFileData))
			.role("user")
			.build();

		LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, true, false);
		assertNotNull(result);
		assertFalse(result.contents().get(0).parts().get().get(0).inlineData().get().displayName().isPresent());
		assertFalse(result.contents().get(0).parts().get().get(1).fileData().get().displayName().isPresent());
	}

	@Test
	@Tag("valid")
	void prepareGenerateContentRequestSanitizeInlineDataWithoutDisplayName() {
		Blob blobWithoutDisplayName = Blob.builder().data(new byte[] { 1, 2, 3 }).mimeType("image/png").build();
		Part partWithInlineData = Part.builder().inlineData(blobWithoutDisplayName).build();

		Content content = Content.builder().parts(ImmutableList.of(partWithInlineData)).role("user").build();

		LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, true, false);
		assertNotNull(result);
		assertTrue(result.contents().get(0).parts().get().get(0).inlineData().isPresent());
		assertArrayEquals(new byte[] { 1, 2, 3 },
				result.contents().get(0).parts().get().get(0).inlineData().get().data().orElse(new byte[0]));
		assertEquals("image/png",
				result.contents().get(0).parts().get().get(0).inlineData().get().mimeType().orElse(""));
	}

	@Test
	@Tag("valid")
	void prepareGenerateContentRequestSanitizeFileDataWithoutDisplayName() {
		FileData fileDataWithoutDisplayName = FileData.builder()
			.fileUri("gs://test/file")
			.mimeType("application/pdf")
			.build();
		Part partWithFileData = Part.builder().fileData(fileDataWithoutDisplayName).build();

		Content content = Content.builder().parts(ImmutableList.of(partWithFileData)).role("user").build();

		LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, true, false);
		assertNotNull(result);
		assertTrue(result.contents().get(0).parts().get().get(0).fileData().isPresent());
		assertEquals("gs://test/file",
				result.contents().get(0).parts().get().get(0).fileData().get().fileUri().orElse(""));
		assertEquals("application/pdf",
				result.contents().get(0).parts().get().get(0).fileData().get().mimeType().orElse(""));
	}

	@Test
	@Tag("valid")
	void prepareGenerateContentRequestWithLastContentAsModel() {
		Part part = Part.builder().text("Model response").build();
		Content modelContent = Content.builder().parts(ImmutableList.of(part)).role("model").build();

		LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(modelContent)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, false, false);
		assertNotNull(result);
		assertEquals(2, result.contents().size());
		assertEquals("user", result.contents().get(1).role().orElse(""));
		assertEquals(GeminiUtil.CONTINUE_OUTPUT_MESSAGE,
				result.contents().get(1).parts().get().get(0).text().orElse(""));
	}

	@Test
	@Tag("valid")
	void prepareGenerateContentRequestWithLastContentRoleDifferentCase() {
		Part part = Part.builder().text("User message").build();
		Content userContent = Content.builder().parts(ImmutableList.of(part)).role("USER").build();

		LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(userContent)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, false, false);
		assertNotNull(result);
		assertEquals(1, result.contents().size());
		assertEquals("USER", result.contents().get(0).role().orElse(""));
	}

	@Test
	@Tag("boundary")
	void prepareGenerateContentRequestWithLastContentNoRole() {
		Part part = Part.builder().text("Message").build();
		Content contentNoRole = Content.builder().parts(ImmutableList.of(part)).build();

		LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(contentNoRole)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, false, false);
		assertNotNull(result);
		assertEquals(2, result.contents().size());
		assertEquals("user", result.contents().get(1).role().orElse(""));
		assertEquals(GeminiUtil.CONTINUE_OUTPUT_MESSAGE,
				result.contents().get(1).parts().get().get(0).text().orElse(""));
	}

	@Test
	@Tag("boundary")
	void prepareGenerateContentRequestWithAllThoughtParts() {
		Part thoughtPart1 = Part.builder().text("Thought 1").thought(true).build();
		Part thoughtPart2 = Part.builder().text("Thought 2").thought(true).build();

		Content content1 = Content.builder().parts(ImmutableList.of(thoughtPart1)).role("user").build();
		Content content2 = Content.builder().parts(ImmutableList.of(thoughtPart2)).role("model").build();

		LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content1, content2)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, false, true);
		assertNotNull(result);
		assertEquals(3, result.contents().size());
		assertTrue(result.contents().get(0).parts().get().isEmpty());
		assertTrue(result.contents().get(1).parts().get().isEmpty());
		assertEquals("user", result.contents().get(2).role().orElse(""));
	}

	@Test
	@Tag("valid")
	void prepareGenerateContentRequestSanitizeWithBothInlineAndFileData() {
		Blob blobWithDisplayName = Blob.builder()
			.data(new byte[] { 1, 2, 3 })
			.mimeType("image/png")
			.displayName("testImage")
			.build();
		FileData fileDataWithDisplayName = FileData.builder()
			.fileUri("gs://test/file")
			.mimeType("application/pdf")
			.displayName("testFile")
			.build();
		Part part = Part.builder().inlineData(blobWithDisplayName).fileData(fileDataWithDisplayName).build();

		Content content = Content.builder().parts(ImmutableList.of(part)).role("user").build();

		LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, true, false);
		assertNotNull(result);
		assertFalse(result.contents().get(0).parts().get().get(0).inlineData().get().displayName().isPresent());
		assertFalse(result.contents().get(0).parts().get().get(0).fileData().get().displayName().isPresent());
		assertArrayEquals(new byte[] { 1, 2, 3 },
				result.contents().get(0).parts().get().get(0).inlineData().get().data().orElse(new byte[0]));
		assertEquals("gs://test/file",
				result.contents().get(0).parts().get().get(0).fileData().get().fileUri().orElse(""));
	}

	@Test
	@Tag("boundary")
	void prepareGenerateContentRequestStripThoughtsWithNoPartsOptional() {
		Content contentWithNoParts = Content.builder().role("user").build();

		LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(contentWithNoParts)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, false, true);
		assertNotNull(result);
		assertEquals(1, result.contents().size());
	}

	@Test
	@Tag("integration")
	void prepareGenerateContentRequestComplexScenario() {
		Blob blobWithDisplayName = Blob.builder()
			.data(new byte[] { 1, 2, 3 })
			.mimeType("image/png")
			.displayName("testImage")
			.build();
		FileData fileDataWithDisplayName = FileData.builder()
			.fileUri("gs://test/file")
			.mimeType("application/pdf")
			.displayName("testFile")
			.build();

		Part thoughtPart = Part.builder().text("Thought").thought(true).build();
		Part normalPart = Part.builder().text("Normal").thought(false).build();
		Part noThoughtPart = Part.builder().text("No thought").build();
		Part partWithInlineData = Part.builder().inlineData(blobWithDisplayName).build();
		Part partWithFileData = Part.builder().fileData(fileDataWithDisplayName).build();

		Content content1 = Content.builder()
			.parts(ImmutableList.of(thoughtPart, normalPart, partWithInlineData))
			.role("user")
			.build();
		Content content2 = Content.builder()
			.parts(ImmutableList.of(noThoughtPart, partWithFileData))
			.role("model")
			.build();

		LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(content1, content2)).build();
		LlmRequest result = GeminiUtil.prepareGenenerateContentRequest(llmRequest, true, true);
		assertNotNull(result);
		assertEquals(3, result.contents().size());
		assertEquals(2, result.contents().get(0).parts().get().size());
		assertFalse(result.contents().get(0).parts().get().get(1).inlineData().get().displayName().isPresent());
		assertEquals(2, result.contents().get(1).parts().get().size());
		assertFalse(result.contents().get(1).parts().get().get(1).fileData().get().displayName().isPresent());
		assertEquals("user", result.contents().get(2).role().orElse(""));
		assertEquals(GeminiUtil.CONTINUE_OUTPUT_MESSAGE,
				result.contents().get(2).parts().get().get(0).text().orElse(""));
	}

}