/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test maven-adkjava-github using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=sendContent_002f7a9a3a
ROOST_METHOD_SIG_HASH=sendContent_f9ade81376

Scenario 1: Verify Behavior When Content is Null

Details:
  TestName: contentIsNullThrowsNullPointerException
  Description: This test checks that the sendContent method throws a NullPointerException if the provided Content argument is null.

Execution:
  Arrange: Prepare the GeminiLlmConnection instance. No Content object is created (explicitly using null).
  Act: Invoke the sendContent method with null as the argument.
  Assert: Assert that a NullPointerException is thrown with the message "content cannot be null".
Validation:
  This assertion validates that the method enforces non-null Content input, thereby protecting against null pointer dereferences and enforcing contract correctness.

Scenario 2: Content Has No Parts

Details:
  TestName: contentWithNoPartsTriggersSendClientContentInternal
  Description: This test checks that when the provided Content object has no parts (content.parts() is empty), sendClientContentInternal is called, returning the appropriate Completable.

Execution:
  Arrange: Create a Content instance with empty parts (parts() returns Optional.empty() or an empty list). Mock dependencies as necessary.
  Act: Call sendContent with this Content object.
  Assert: Assert that sendClientContentInternal is invoked with a LiveSendClientContentParameters containing only this Content, turnComplete set to true, and that the returned Completable matches the one provided by sendClientContentInternal.
Validation:
  This test ensures the method correctly identifies Content instances with no parts and routes them to sendClientContentInternal, establishing basic routing for empty input cases.

Scenario 3: Content Parts List is Present but Empty

Details:
  TestName: contentWithEmptyPartsListTriggersSendClientContentInternal
  Description: This test checks that if the Content.parts() returns an Optional containing an empty list, sendClientContentInternal is called.

Execution:
  Arrange: Create a Content object whose parts() method returns Optional.of(emptyList()).
  Act: Call sendContent with this Content.
  Assert: Assert that sendClientContentInternal is called with the expected parameters and that the returned Completable reflects this action.
Validation:
  This assertion confirms that not only the absence of parts, but also an explicitly empty part list, results in fallback to the correct internal handling path.

Scenario 4: All Content Parts Are FunctionResponses

Details:
  TestName: allPartsAreFunctionResponsesTriggersSendToolResponseInternal
  Description: This test checks that if every Part in Content contains a FunctionResponse, the method calls sendToolResponseInternal with the correct parameters.

Execution:
  Arrange: Create a Content with parts consisting only of Part instances returning present Optional<FunctionResponse> objects. Mock extractFunctionResponses to return all FunctionResponses as present. Mock sendToolResponseInternal to return a known Completable.
  Act: Call sendContent with the prepared Content.
  Assert: Assert that sendToolResponseInternal is called with LiveSendToolResponseParameters containing all the FunctionResponses, and ensure the returned Completable matches the one from the internal method.
Validation:
  This test ensures that the method dispatches correctly when the content is a set of tool responses, supporting more complex application use cases and function-calling flows.

Scenario 5: Not All Parts Are FunctionResponses

Details:
  TestName: somePartsAreNotFunctionResponsesTriggersSendClientContentInternal
  Description: This test checks that if only some (not all) Parts in Content contain FunctionResponses, sendClientContentInternal is invoked, not sendToolResponseInternal.

Execution:
  Arrange: Construct a Content object with a mixture of Part instances: some returning Optional.of(FunctionResponse), some returning Optional.empty(). Mock sendClientContentInternal to return a known Completable.
  Act: Call sendContent with this Content instance.
  Assert: Assert that sendClientContentInternal is called (and not sendToolResponseInternal), and that the returned Completable is as expected.
Validation:
  This test verifies that the method only treats Content as tool responses when all parts meet the criteria, thereby guarding against partially-formed inputs and ensuring safe/expected internal logic.

Scenario 6: Content Parts Do Not Contain Any FunctionResponses

Details:
  TestName: noFunctionResponsesInPartsTriggersSendClientContentInternal
  Description: This test checks the case where the Content has parts, but none contain a FunctionResponse; sendClientContentInternal should be invoked.

Execution:
  Arrange: Create a Content object with multiple Part instances, each returning Optional.empty() for functionResponse(). Mock sendClientContentInternal.
  Act: Call sendContent.
  Assert: Assert that sendClientContentInternal is invoked and the method returns its Completable.
Validation:
  This ensures that general, non-function-response content is handled as non-tool messages, which is essential for standard conversation exchange in application logic.

Scenario 7: FunctionResponses Extraction Returns Empty

Details:
  TestName: extractFunctionResponsesReturnsEmptyTriggersSendClientContentInternal
  Description: This test ensures that if extractFunctionResponses returns Optional.empty(), the method proceeds to call sendClientContentInternal.

Execution:
  Arrange: Prepare a Content and mock extractFunctionResponses to always return Optional.empty(), regardless of parts.
  Act: Call sendContent.
  Assert: Assert that sendClientContentInternal is called, and the returned Completable matches expectations.
Validation:
  This test is important in verifying that the fallback path is robust even if the internal extraction logic returns an empty result for complex content.

Scenario 8: FunctionResponses Extraction Throws Exception

Details:
  TestName: extractFunctionResponsesThrowsExceptionPropagates
  Description: This test ensures that if extractFunctionResponses throws a runtime exception, that exception propagates through sendContent.

Execution:
  Arrange: Mock extractFunctionResponses for a Content instance to throw a RuntimeException.
  Act: Call sendContent and catch any exception thrown.
  Assert: Assert that the same RuntimeException is propagated.
Validation:
  The test ensures transparent propagation of unexpected exceptions, allowing calling code to handle such cases in a controlled manner.

Scenario 9: sendToolResponseInternal Throws Exception

Details:
  TestName: sendToolResponseInternalThrowsExceptionPropagates
  Description: This test ensures that if sendToolResponseInternal throws an exception, the method propagates it to the caller.

Execution:
  Arrange: Prepare Content whose extractFunctionResponses returns a populated Optional. Mock sendToolResponseInternal to throw a RuntimeException when called.
  Act: Call sendContent and catch any exception.
  Assert: Assert that the RuntimeException is propagated as expected.
Validation:
  It validates that critical internal failures bubble up and are not silently caught, supporting easier diagnosis and robust error handling strategy.

Scenario 10: sendClientContentInternal Throws Exception

Details:
  TestName: sendClientContentInternalThrowsExceptionPropagates
  Description: This test ensures that if sendClientContentInternal throws an exception, the method propagates it.

Execution:
  Arrange: Prepare Content that resolves to client content (function responses extraction returns empty). Mock sendClientContentInternal to throw a RuntimeException.
  Act: Call sendContent.
  Assert: Assert that the RuntimeException is propagated through.
Validation:
  It confirms that exceptions from client-content path are visible to higher layers and are not inadvertently masked.

Scenario 11: Correct Parameters Passed to sendToolResponseInternal

Details:
  TestName: functionResponsesCorrectlyMappedToToolResponseParameters
  Description: This test checks that FunctionResponses extracted from Content parts are mapped correctly and supplied to the LiveSendToolResponseParameters builder as expected.

Execution:
  Arrange: Build a Content object with specific FunctionResponse values in its parts. Mock sendToolResponseInternal to verify that it receives parameters with the exact List<FunctionResponse>.
  Act: Call sendContent.
  Assert: Assert that the parameters passed are precisely those contained in the Content parts.
Validation:
  This deep validation safeguards that data transformation complies with expectations, critical when building requests for an external service.

Scenario 12: Correct Parameters Passed to sendClientContentInternal

Details:
  TestName: contentCorrectlyWrappedInClientContentParameters
  Description: This test checks that when Content does not contain all FunctionResponses, it is wrapped as the turns member in LiveSendClientContentParameters with turnComplete being true.

Execution:
  Arrange: Build a Content instance and ensure extractFunctionResponses returns empty. Mock sendClientContentInternal to verify parameter values.
  Act: Call sendContent.
  Assert: Assert that the Content is present in the turns parameter, and turnComplete is set to true in the invoked parameters.
Validation:
  It verifies that content is sent to the server in the format required by the LiveSendClientContentParameters schema, which is essential for protocol compliance and conversation state management.

Scenario 13: Concurrency – Multiple Calls to sendContent

Details:
  TestName: sendContentIsThreadSafeForSimultaneousCalls
  Description: This test examines behavior when sendContent is invoked in parallel by multiple threads, especially around content routing and Completable returns.

Execution:
  Arrange: Use several Content instances with varying parts. Use concurrency to call sendContent simultaneously, and mock internal methods to record invocation order, arguments, and results.
  Act: Launch threads to call sendContent.
  Assert: Assert that each call produces the expected result given the input, and no data races or consistency issues are observed.
Validation:
  This scenario ensures thread safety and API stability under concurrent usage, which is frequently required in large-scale production deployments.

Scenario 14: Session Future Has Not Been Completed Yet

Details:
  TestName: sessionFutureNotCompletedYetHandling
  Description: This test checks if sendContent can properly handle the scenario when the underlying sessionFuture is not yet completed (simulating connection latency).

Execution:
  Arrange: Set up GeminiLlmConnection with a CompletableFuture<AsyncSession> that is not yet completed. Create Content that should lead to sendClientContentInternal call.
  Act: Call sendContent.
  Assert: Assert that the returned Completable will not terminate until the sessionFuture completes, and that after completing the future, the sequence continues as expected.
Validation:
  This test validates asynchronous handover and ensures that late session connections do not cause deadlocks or immediate failures.

Scenario 15: sendContent Called After Connection is Closed

Details:
  TestName: sendContentAfterClosedConnectionHandling
  Description: This test verifies the behavior of sendContent if the GeminiLlmConnection has already been closed (closed field set to true).

Execution:
  Arrange: Close the GeminiLlmConnection or set its closed flag. Provide any Content object.
  Act: Try calling sendContent.
  Assert: Assert whether the method still processes (as implementation does not explicitly check closed), or if a relevant exception or warning is produced.
Validation:
  This test ensures application robustness in "dead" connection states, helping detect potential resource leaks or protocol errors if clients attempt interaction post-closure.

*/

// ********RoostGPT********

package com.google.adk.models;

import static com.google.common.collect.ImmutableList.toImmutableList;
import com.google.common.collect.ImmutableList;
import com.google.genai.Client;
import com.google.genai.types.Blob;
import com.google.genai.types.Content;
import com.google.genai.types.FinishReason;
import com.google.genai.types.FunctionCall;
import com.google.genai.types.FunctionResponse;
import com.google.genai.types.LiveConnectConfig;
import com.google.genai.types.LiveSendClientContentParameters;
import com.google.genai.types.LiveSendRealtimeInputParameters;
import com.google.genai.types.LiveSendToolResponseParameters;
import com.google.genai.types.LiveServerContent;
import com.google.genai.types.LiveServerMessage;
import com.google.genai.types.LiveServerToolCall;
import com.google.genai.types.Part;
import io.reactivex.rxjava3.core.Completable;
import io.reactivex.rxjava3.core.Flowable;
import io.reactivex.rxjava3.processors.PublishProcessor;
import java.net.SocketException;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.atomic.AtomicBoolean;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import com.google.genai.AsyncSession;
import java.util.concurrent.CompletionException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@ExtendWith(MockitoExtension.class)
public class GeminiLlmConnectionSendContentTest {

	@Mock
	private Client mockApiClient;

	@Mock
	private LiveConnectConfig mockConnectConfig;

	@Mock
	private CompletableFuture<AsyncSession> mockSessionFuture;

	@Mock
	private AsyncSession mockAsyncSession;

	@Mock
	private Completable mockCompletable;

	private GeminiLlmConnection geminiConnection;

	private String modelName = "test-model"; // TODO: change as per actual model

	@BeforeEach
    public void setup() {
        when(mockApiClient.async()).thenReturn(new Client.Async() {
            @Override public Client.Live live() {
                return new Client.Live() {
                    @Override
                    public CompletableFuture<AsyncSession> connect(String model, LiveConnectConfig config) {
                        return mockSessionFuture;
                    }
                };
            }
        });
        geminiConnection = Mockito.spy(new GeminiLlmConnection(mockApiClient, modelName, mockConnectConfig));
        // Patch sessionFuture for test
        doReturn(mockSessionFuture).when(geminiConnection).sessionFuture;
    }

	@Test
	@Tag("invalid")
	public void testContentIsNullThrowsNullPointerException() {
		NullPointerException exception = Assertions.assertThrows(NullPointerException.class,
				() -> geminiConnection.sendContent(null));
		Assertions.assertEquals("content cannot be null", exception.getMessage());
	}

	@Test
	@Tag("boundary")
	public void testContentWithNoPartsTriggersSendClientContentInternal() {
		Content content = mock(Content.class);
		when(content.parts()).thenReturn(Optional.empty());
		Completable expectedCompletable = mock(Completable.class);
		doReturn(expectedCompletable).when(geminiConnection)
			.sendClientContentInternal(any(LiveSendClientContentParameters.class));
		Completable actual = geminiConnection.sendContent(content);
		ArgumentCaptor<LiveSendClientContentParameters> captor = ArgumentCaptor
			.forClass(LiveSendClientContentParameters.class);
		verify(geminiConnection, times(1)).sendClientContentInternal(captor.capture());
		LiveSendClientContentParameters params = captor.getValue();
		Assertions.assertTrue(params.turns().contains(content));
		Assertions.assertTrue(params.turnComplete());
		Assertions.assertSame(expectedCompletable, actual);
	}

	@Test
	@Tag("boundary")
	public void testContentWithEmptyPartsListTriggersSendClientContentInternal() {
		Content content = mock(Content.class);
		when(content.parts()).thenReturn(Optional.of(ImmutableList.of()));
		Completable expectedCompletable = mock(Completable.class);
		doReturn(expectedCompletable).when(geminiConnection)
			.sendClientContentInternal(any(LiveSendClientContentParameters.class));
		Completable actual = geminiConnection.sendContent(content);
		ArgumentCaptor<LiveSendClientContentParameters> captor = ArgumentCaptor
			.forClass(LiveSendClientContentParameters.class);
		verify(geminiConnection, times(1)).sendClientContentInternal(captor.capture());
		LiveSendClientContentParameters params = captor.getValue();
		Assertions.assertTrue(params.turns().contains(content));
		Assertions.assertTrue(params.turnComplete());
		Assertions.assertSame(expectedCompletable, actual);
	}

	@Test
	@Tag("valid")
	public void testAllPartsAreFunctionResponsesTriggersSendToolResponseInternal() {
		FunctionResponse fr1 = mock(FunctionResponse.class);
		FunctionResponse fr2 = mock(FunctionResponse.class);
		Part p1 = mock(Part.class);
		Part p2 = mock(Part.class);
		when(p1.functionResponse()).thenReturn(Optional.of(fr1));
		when(p2.functionResponse()).thenReturn(Optional.of(fr2));
		Content content = mock(Content.class);
		when(content.parts()).thenReturn(Optional.of(ImmutableList.of(p1, p2)));
		doReturn(Optional.of(ImmutableList.of(fr1, fr2))).when(geminiConnection).extractFunctionResponses(content);
		Completable expectedCompletable = mock(Completable.class);
		doReturn(expectedCompletable).when(geminiConnection)
			.sendToolResponseInternal(any(LiveSendToolResponseParameters.class));
		Completable actual = geminiConnection.sendContent(content);
		ArgumentCaptor<LiveSendToolResponseParameters> captor = ArgumentCaptor
			.forClass(LiveSendToolResponseParameters.class);
		verify(geminiConnection, times(1)).sendToolResponseInternal(captor.capture());
		LiveSendToolResponseParameters params = captor.getValue();
		Assertions.assertEquals(ImmutableList.of(fr1, fr2), params.functionResponses());
		Assertions.assertSame(expectedCompletable, actual);
	}

	@Test
	@Tag("boundary")
	public void testSomePartsAreNotFunctionResponsesTriggersSendClientContentInternal() {
		FunctionResponse fr1 = mock(FunctionResponse.class);
		Part p1 = mock(Part.class);
		Part p2 = mock(Part.class);
		when(p1.functionResponse()).thenReturn(Optional.of(fr1));
		when(p2.functionResponse()).thenReturn(Optional.empty());
		Content content = mock(Content.class);
		when(content.parts()).thenReturn(Optional.of(ImmutableList.of(p1, p2)));
		doReturn(Optional.empty()).when(geminiConnection).extractFunctionResponses(content);
		Completable expectedCompletable = mock(Completable.class);
		doReturn(expectedCompletable).when(geminiConnection)
			.sendClientContentInternal(any(LiveSendClientContentParameters.class));
		Completable actual = geminiConnection.sendContent(content);
		verify(geminiConnection, times(1)).sendClientContentInternal(any(LiveSendClientContentParameters.class));
		verify(geminiConnection, times(0)).sendToolResponseInternal(any(LiveSendToolResponseParameters.class));
		Assertions.assertSame(expectedCompletable, actual);
	}

	@Test
	@Tag("valid")
	public void testNoFunctionResponsesInPartsTriggersSendClientContentInternal() {
		Part p1 = mock(Part.class);
		Part p2 = mock(Part.class);
		when(p1.functionResponse()).thenReturn(Optional.empty());
		when(p2.functionResponse()).thenReturn(Optional.empty());
		Content content = mock(Content.class);
		when(content.parts()).thenReturn(Optional.of(ImmutableList.of(p1, p2)));
		doReturn(Optional.empty()).when(geminiConnection).extractFunctionResponses(content);
		Completable expectedCompletable = mock(Completable.class);
		doReturn(expectedCompletable).when(geminiConnection)
			.sendClientContentInternal(any(LiveSendClientContentParameters.class));
		Completable actual = geminiConnection.sendContent(content);
		verify(geminiConnection, times(1)).sendClientContentInternal(any(LiveSendClientContentParameters.class));
		verify(geminiConnection, times(0)).sendToolResponseInternal(any(LiveSendToolResponseParameters.class));
		Assertions.assertSame(expectedCompletable, actual);
	}

	@Test
	@Tag("boundary")
	public void testExtractFunctionResponsesReturnsEmptyTriggersSendClientContentInternal() {
		Content content = mock(Content.class);
		doReturn(Optional.empty()).when(geminiConnection).extractFunctionResponses(content);
		Completable expectedCompletable = mock(Completable.class);
		doReturn(expectedCompletable).when(geminiConnection)
			.sendClientContentInternal(any(LiveSendClientContentParameters.class));
		Completable actual = geminiConnection.sendContent(content);
		verify(geminiConnection, times(1)).sendClientContentInternal(any(LiveSendClientContentParameters.class));
		verify(geminiConnection, times(0)).sendToolResponseInternal(any(LiveSendToolResponseParameters.class));
		Assertions.assertSame(expectedCompletable, actual);
	}

	@Test
	@Tag("invalid")
	public void testExtractFunctionResponsesThrowsExceptionPropagates() {
		Content content = mock(Content.class);
		RuntimeException ex = new RuntimeException("Extraction Failure");
		doThrow(ex).when(geminiConnection).extractFunctionResponses(content);
		RuntimeException result = Assertions.assertThrows(RuntimeException.class,
				() -> geminiConnection.sendContent(content));
		Assertions.assertSame(ex, result);
	}

	@Test
	@Tag("invalid")
	public void testSendToolResponseInternalThrowsExceptionPropagates() {
		FunctionResponse fr = mock(FunctionResponse.class);
		Part p = mock(Part.class);
		when(p.functionResponse()).thenReturn(Optional.of(fr));
		Content content = mock(Content.class);
		when(content.parts()).thenReturn(Optional.of(ImmutableList.of(p)));
		doReturn(Optional.of(ImmutableList.of(fr))).when(geminiConnection).extractFunctionResponses(content);
		RuntimeException ex = new RuntimeException("ToolResponse Error");
		doThrow(ex).when(geminiConnection).sendToolResponseInternal(any(LiveSendToolResponseParameters.class));
		RuntimeException thrown = Assertions.assertThrows(RuntimeException.class,
				() -> geminiConnection.sendContent(content));
		Assertions.assertSame(ex, thrown);
	}

	@Test
	@Tag("invalid")
	public void testSendClientContentInternalThrowsExceptionPropagates() {
		Content content = mock(Content.class);
		doReturn(Optional.empty()).when(geminiConnection).extractFunctionResponses(content);
		RuntimeException ex = new RuntimeException("ClientContentInternal Error");
		doThrow(ex).when(geminiConnection).sendClientContentInternal(any(LiveSendClientContentParameters.class));
		RuntimeException thrown = Assertions.assertThrows(RuntimeException.class,
				() -> geminiConnection.sendContent(content));
		Assertions.assertSame(ex, thrown);
	}

	@Test
	@Tag("valid")
	public void testFunctionResponsesCorrectlyMappedToToolResponseParameters() {
		FunctionResponse fr1 = mock(FunctionResponse.class);
		FunctionResponse fr2 = mock(FunctionResponse.class);
		Part p1 = mock(Part.class);
		Part p2 = mock(Part.class);
		when(p1.functionResponse()).thenReturn(Optional.of(fr1));
		when(p2.functionResponse()).thenReturn(Optional.of(fr2));
		Content content = mock(Content.class);
		when(content.parts()).thenReturn(Optional.of(ImmutableList.of(p1, p2)));
		doReturn(Optional.of(ImmutableList.of(fr1, fr2))).when(geminiConnection).extractFunctionResponses(content);
		Completable expectedCompletable = mock(Completable.class);
		doReturn(expectedCompletable).when(geminiConnection)
			.sendToolResponseInternal(any(LiveSendToolResponseParameters.class));
		geminiConnection.sendContent(content);
		ArgumentCaptor<LiveSendToolResponseParameters> captor = ArgumentCaptor
			.forClass(LiveSendToolResponseParameters.class);
		verify(geminiConnection, times(1)).sendToolResponseInternal(captor.capture());
		List<FunctionResponse> capturedResponses = captor.getValue().functionResponses();
		Assertions.assertEquals(ImmutableList.of(fr1, fr2), capturedResponses);
	}

	@Test
	@Tag("valid")
	public void testContentCorrectlyWrappedInClientContentParameters() {
		Content content = mock(Content.class);
		doReturn(Optional.empty()).when(geminiConnection).extractFunctionResponses(content);
		Completable expectedCompletable = mock(Completable.class);
		doReturn(expectedCompletable).when(geminiConnection)
			.sendClientContentInternal(any(LiveSendClientContentParameters.class));
		geminiConnection.sendContent(content);
		ArgumentCaptor<LiveSendClientContentParameters> captor = ArgumentCaptor
			.forClass(LiveSendClientContentParameters.class);
		verify(geminiConnection, times(1)).sendClientContentInternal(captor.capture());
		LiveSendClientContentParameters params = captor.getValue();
		Assertions.assertTrue(params.turns().contains(content));
		Assertions.assertTrue(params.turnComplete());
	}

	@Test
	@Tag("integration")
	public void testSendContentIsThreadSafeForSimultaneousCalls() throws Exception {
		Content content1 = mock(Content.class);
		Content content2 = mock(Content.class);
		doReturn(Optional.empty()).when(geminiConnection).extractFunctionResponses(content1);
		doReturn(Optional.empty()).when(geminiConnection).extractFunctionResponses(content2);
		Completable completable1 = mock(Completable.class);
		Completable completable2 = mock(Completable.class);
		doReturn(completable1).when(geminiConnection)
			.sendClientContentInternal(any(LiveSendClientContentParameters.class));
		doReturn(completable2).when(geminiConnection)
			.sendClientContentInternal(any(LiveSendClientContentParameters.class));
		Runnable r1 = () -> {
			Completable c = geminiConnection.sendContent(content1);
			Assertions.assertNotNull(c);
		};
		Runnable r2 = () -> {
			Completable c = geminiConnection.sendContent(content2);
			Assertions.assertNotNull(c);
		};
		Thread thread1 = new Thread(r1);
		Thread thread2 = new Thread(r2);
		thread1.start();
		thread2.start();
		thread1.join();
		thread2.join();
	}

	@Test
    @Tag("boundary")
    public void testSessionFutureNotCompletedYetHandling() throws Exception {
        Content content = mock(Content.class);
        doReturn(Optional.empty())
                .when(geminiConnection)
                .extractFunctionResponses(content);
        CompletableFuture<AsyncSession> incompleteSessionFuture = new CompletableFuture<>();
        doReturn(incompleteSessionFuture).when(geminiConnection).sessionFuture;
        Completable expectedCompletable = mock(Completable.class);
        // Patch sendClientContentInternal to simulate waiting
        doReturn(expectedCompletable)
                .when(geminiConnection)
                .sendClientContentInternal(any(LiveSendClientContentParameters.class));
        // Since sendContent returns a Completable that is derived from sessionFuture, this test ensures no immediate error/failure
        Completable actualCompletable = geminiConnection.sendContent(content);
        Assertions.assertNotNull(actualCompletable);
        incompleteSessionFuture.complete(mockAsyncSession);
    }

	@Test
	@Tag("boundary")
	public void testSendContentAfterClosedConnectionHandling() {
		Content content = mock(Content.class);
		doReturn(Optional.empty()).when(geminiConnection).extractFunctionResponses(content);
		Completable expectedCompletable = mock(Completable.class);
		doReturn(expectedCompletable).when(geminiConnection)
			.sendClientContentInternal(any(LiveSendClientContentParameters.class));
		// Close the connection
		geminiConnection.close();
		// The implementation does not check closed in sendContent - so it will still
		// process
		Completable returned = geminiConnection.sendContent(content);
		Assertions.assertSame(expectedCompletable, returned);
	}

}