/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test maven-adkjava-github using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=receive_900b8d07f7
ROOST_METHOD_SIG_HASH=receive_e4e6b5b51a

Scenario 1: Method returns the correct Flowable instance for responses

Details:
  TestName: returnsResponseFlowableInstance
  Description: This test checks if the receive() method returns the same Flowable instance (responseFlowable) associated with the GeminiLlmConnection object. The scenario validates the linkage between the method and the field, ensuring subscribers to receive() always get the responses published via responseProcessor.

Execution:
  Arrange: Create a GeminiLlmConnection object with valid injected mocks/stubs for apiClient, modelName, and connectConfig.
  Act: Call receive() on the created object and obtain the result.
  Assert: Verify that the returned Flowable instance is exactly the responseFlowable field of the connection object.
Validation:
  The assertion verifies that the method does not create new Flowable instances, ensuring response distribution is consistent and that consumers/subscribers observe the same data stream as designed. This maintains architectural guarantees of the connection's response delivery mechanism.

Scenario 2: Subscriber receives published LlmResponse objects

Details:
  TestName: subscriberReceivesPublishedResponses
  Description: This test ensures that when LlmResponse objects are published to the responseProcessor, any observer subscribed to the Flowable obtained from receive() will collect these responses. It simulates response delivery scenarios.

Execution:
  Arrange: Set up a GeminiLlmConnection instance, subscribe a test observer to the Flowable from receive(), and publish multiple valid LlmResponse objects to the responseProcessor.
  Act: Push LlmResponse objects into responseProcessor.
  Assert: The test observer receives the expected LlmResponse objects and records their arrival in the correct order.
Validation:
  This validates the core mechanism of response propagation from the model to consumers, confirming subscribers obtain the full set of responses and the method reliably exposes response streams.

Scenario 3: Completes Flowable when connection is closed without error

Details:
  TestName: flowableCompletesOnCleanClose
  Description: This scenario checks that if close() is called on GeminiLlmConnection with no error, the Flowable returned from receive() completes and subscribers are notified of completion.

Execution:
  Arrange: Instantiate GeminiLlmConnection and subscribe a mock/test observer to the Flowable from receive().
  Act: Call close() on the connection instance.
  Assert: The observer is notified when the Flowable completes.
Validation:
  The assertion guarantees proper resource signaling and cleanup, confirming the application behavior where subscribers are informed that no more responses will arrive after an orderly shutdown.

Scenario 4: Propagates error to Flowable when connection is closed with exception

Details:
  TestName: flowableErrorsOnCloseWithException
  Description: The test checks that if close(Throwable) is called with an error/exception, this error is propagated to subscribers of the Flowable returned from receive().

Execution:
  Arrange: Prepare a GeminiLlmConnection, subscribe a test observer to receive(), and simulate connection closing by calling close(Throwable) with a test exception.
  Act: Invoke close(Throwable) on the object with a sample Throwable.
  Assert: The observer receives the error notification and the Flowable fails.
Validation:
  The test proves that exception signaling is handled appropriately, so consumers are reliably notified about error conditions on closure—critical for correct error-handling behaviors.

Scenario 5: Flowable delivers error when connection setup fails

Details:
  TestName: flowableErrorsOnConnectionFailure
  Description: This scenario covers the case where GeminiLlmConnection fails to connect, causing handleConnectionError to emit an error on responseProcessor. It checks that the Flowable from receive() propagates this error to subscribers.

Execution:
  Arrange: Instantiate GeminiLlmConnection with a mock Client configured to fail connection, subscribe to receive(), trigger connection failure, and publish error via responseProcessor as handleConnectionError would.
  Act: Simulate a connection failure and observe Flowable behavior.
  Assert: Observer receives the error that was reported during connection setup.
Validation:
  This ensures that connection errors are surfaced to users of receive() immediately, providing transparency for connection lifecycle failures.

Scenario 6: Flowable delivers error when a receive operation fails

Details:
  TestName: flowableErrorsOnReceiveOperationFailure
  Description: Verifies that if handleReceiveError is triggered, responseProcessor emits an error, and the Flowable from receive() propagates it to all subscribers, reflecting issues during message receipt.

Execution:
  Arrange: Create and subscribe to receive() on GeminiLlmConnection, simulate a receive operation failing by invoking handleReceiveError, and inject a throwable.
  Act: Trigger handleReceiveError with a sample Throwable.
  Assert: Subscriber receives the same error propagated through Flowable.
Validation:
  This assures the robustness of error propagation throughout the receive pipeline, ensuring consumers can react properly to runtime message receiving errors.

Scenario 7: Multiple subscribers receive the same published responses

Details:
  TestName: multipleSubscribersReceiveResponses
  Description: The test checks that multiple subscribers attached to the Flowable returned from receive() each receive all published LlmResponse messages, ensuring multicasting.

Execution:
  Arrange: Instantiate GeminiLlmConnection, attach multiple test observers/subscribers to receive(), and publish several LlmResponse objects into responseProcessor.
  Act: Publish responses through responseProcessor.
  Assert: Each observer receives all responses in the correct sequence.
Validation:
  This confirms the method's multicasting design, ensuring that all registered consumers receive identical streams—a key requirement for collaborative or parallel response processing.

Scenario 8: Returns the serialized Flowable (thread safety assurance)

Details:
  TestName: returnsSerializedFlowableForThreadSafety
  Description: Validates that receive() returns a serialized (thread-safe) Flowable, so any concurrent subscriptions or onNext calls won’t result in sequence or threading issues.

Execution:
  Arrange: Setup GeminiLlmConnection and check that the Flowable returned from receive() is serialized using test methods for serialization or thread safety.
  Act: Retrieve the Flowable and check its serialization property.
  Assert: Flowable is confirmed to be thread-safe and serialized.
Validation:
  The test provides assurances for thread safety and sequencing, affirming the design intent of responseFlowable to reliably handle concurrent use-cases.

Scenario 9: Flowable completes only once after close is called multiple times

Details:
  TestName: flowableCompletesOnceAfterMultipleCloses
  Description: This scenario checks that even if close() is called multiple times, the Flowable returned from receive() completes exactly once, with no redundant signals to subscribers.

Execution:
  Arrange: Subscribe to receive() on GeminiLlmConnection and call close() on the instance repeatedly.
  Act: Invoke close() several times.
  Assert: Observer receives a single completion event and nothing more.
Validation:
  This test confirms idempotence of the closing mechanism, preventing resource leaks or repeated completion notifications, upholding stable and predictable connection shutdown behavior.

*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.google.genai.Client;
import com.google.genai.types.LiveConnectConfig;
import io.reactivex.rxjava3.core.Flowable;
import io.reactivex.rxjava3.processors.PublishProcessor;
import io.reactivex.rxjava3.subscribers.TestSubscriber;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.MockedConstruction;

public class GeminiLlmConnectionReceiveTest {

  // Helper method to construct a GeminiLlmConnection instance with mocks
  private GeminiLlmConnection createConnectionWithMocks() {
    Client mockClient = mock(Client.class, RETURNS_DEEP_STUBS);
    LiveConnectConfig mockConfig = mock(LiveConnectConfig.class);
    String modelName = "test-model";
    return new GeminiLlmConnection(mockClient, modelName, mockConfig);
  }

  @Test
  @Tag("valid")
  public void testReturnsResponseFlowableInstance() {
    GeminiLlmConnection conn = createConnectionWithMocks();
    Flowable<LlmResponse> flowable = conn.receive();
    assertSame(
        flowable, conn.receive(), "receive() should return the same Flowable instance each time");
  }

  @Test
  @Tag("valid")
  public void testSubscriberReceivesPublishedResponses() {
    GeminiLlmConnection conn = createConnectionWithMocks();
    Flowable<LlmResponse> flowable = conn.receive();
    TestSubscriber<LlmResponse> subscriber = new TestSubscriber<>();
    flowable.subscribe(subscriber);
    // Publish two responses
    LlmResponse resp1 = LlmResponse.builder().build();
    LlmResponse resp2 = LlmResponse.builder().build();
    PublishProcessor<LlmResponse> processor = getResponseProcessor(conn);
    processor.onNext(resp1);
    processor.onNext(resp2);
    processor.onComplete();
    subscriber.assertValues((LlmResponse) resp1, (LlmResponse) resp2);
    subscriber.assertComplete();
  }

  @Test
  @Tag("valid")
  public void testFlowableCompletesOnCleanClose() {
    GeminiLlmConnection conn = createConnectionWithMocks();
    TestSubscriber<LlmResponse> subscriber = new TestSubscriber<>();
    conn.receive().subscribe(subscriber);
    conn.close();
    subscriber.assertComplete();
  }

  @Test
  @Tag("invalid")
  public void testFlowableErrorsOnCloseWithException() {
    GeminiLlmConnection conn = createConnectionWithMocks();
    TestSubscriber<LlmResponse> subscriber = new TestSubscriber<>();
    conn.receive().subscribe(subscriber);
    Throwable error = new RuntimeException("Expected error");
    conn.close(error);
    subscriber.assertError((Throwable) error);
  }

  @Test
  @Tag("invalid")
  public void testFlowableErrorsOnConnectionFailure() {
    Client mockClient = mock(Client.class, RETURNS_DEEP_STUBS);
    LiveConnectConfig mockConfig = mock(LiveConnectConfig.class);
    String modelName = "test-model";
    GeminiLlmConnection conn;
    try (MockedConstruction<GeminiLlmConnection> ignored =
        mockConstruction(
            GeminiLlmConnection.class,
            (mock, context) -> {
              // No additional stubbing needed
            })) {
      conn = new GeminiLlmConnection(mockClient, modelName, mockConfig);
    }
    TestSubscriber<LlmResponse> subscriber = new TestSubscriber<>();
    conn.receive().subscribe(subscriber);
    Throwable connectError = new RuntimeException("Connection failed");
    invokeHandleConnectionError(conn, connectError);
    subscriber.assertError(
        (Throwable) connectError.getCause() == null ? connectError : connectError.getCause());
  }

  @Test
  @Tag("invalid")
  public void testFlowableErrorsOnReceiveOperationFailure() {
    GeminiLlmConnection conn = createConnectionWithMocks();
    TestSubscriber<LlmResponse> subscriber = new TestSubscriber<>();
    conn.receive().subscribe(subscriber);
    Throwable receiveError = new RuntimeException("Receive failed");
    invokeHandleReceiveError(conn, receiveError);
    subscriber.assertError((Throwable) receiveError);
  }

  @Test
  @Tag("valid")
  public void testMultipleSubscribersReceiveResponses() {
    GeminiLlmConnection conn = createConnectionWithMocks();
    TestSubscriber<LlmResponse> sub1 = new TestSubscriber<>();
    TestSubscriber<LlmResponse> sub2 = new TestSubscriber<>();
    Flowable<LlmResponse> flowable = conn.receive();
    flowable.subscribe(sub1);
    flowable.subscribe(sub2);
    LlmResponse resp1 = LlmResponse.builder().build();
    LlmResponse resp2 = LlmResponse.builder().build();
    PublishProcessor<LlmResponse> processor = getResponseProcessor(conn);
    processor.onNext(resp1);
    processor.onNext(resp2);
    processor.onComplete();
    sub1.assertValues((LlmResponse) resp1, (LlmResponse) resp2);
    sub1.assertComplete();
    sub2.assertValues((LlmResponse) resp1, (LlmResponse) resp2);
    sub2.assertComplete();
  }

  @Test
  @Tag("valid")
  public void testReturnsSerializedFlowableForThreadSafety() {
    GeminiLlmConnection conn = createConnectionWithMocks();
    Flowable<LlmResponse> flowable = conn.receive();
    assertTrue(flowable.isSerialized(), "Flowable should be serialized for thread safety");
  }

  @Test
  @Tag("boundary")
  public void testFlowableCompletesOnceAfterMultipleCloses() {
    GeminiLlmConnection conn = createConnectionWithMocks();
    TestSubscriber<LlmResponse> subscriber = new TestSubscriber<>();
    conn.receive().subscribe(subscriber);
    conn.close();
    conn.close();
    conn.close();
    subscriber.assertComplete();
    assertEquals(
        1, subscriber.completions(), "Flowable should complete only once despite multiple closes");
  }

  // Helper methods to access protected/private fields for test (reflection)
  private PublishProcessor<LlmResponse> getResponseProcessor(GeminiLlmConnection conn) {
    try {
      java.lang.reflect.Field field =
          GeminiLlmConnection.class.getDeclaredField("responseProcessor");
      field.setAccessible(true);
      return (PublishProcessor<LlmResponse>) field.get(conn);
    } catch (Exception ex) {
      throw new IllegalStateException("Could not access responseProcessor", ex);
    }
  }

  private void invokeHandleConnectionError(GeminiLlmConnection conn, Throwable error) {
    try {
      java.lang.reflect.Method m =
          GeminiLlmConnection.class.getDeclaredMethod("handleConnectionError", Throwable.class);
      m.setAccessible(true);
      m.invoke(conn, error);
    } catch (Exception ex) {
      throw new RuntimeException(ex);
    }
  }

  private void invokeHandleReceiveError(GeminiLlmConnection conn, Throwable error) {
    try {
      java.lang.reflect.Method m =
          GeminiLlmConnection.class.getDeclaredMethod("handleReceiveError", Throwable.class);
      m.setAccessible(true);
      m.invoke(conn, error);
    } catch (Exception ex) {
      throw new RuntimeException(ex);
    }
  }
}
