/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-jan-9 using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=processRawResponses_490580de43
ROOST_METHOD_SIG_HASH=processRawResponses_b550986252

Scenario 1: Process Single Raw Response with Non-Blank Text Content

Details:
  TestName: processSingleRawResponseWithNonBlankTextContent
  Description: This test verifies that when a single GenerateContentResponse containing non-blank text is processed, the method correctly accumulates the text and emits a partial LlmResponse with the text content marked as partial.

Execution:
  Arrange: Create a mock GenerateContentResponse with a Part containing non-blank text (e.g., "Hello World"). Create a Flowable containing this single response. Mock GeminiUtil.getPart0FromLlmResponse to return the Part with text.
  Act: Invoke processRawResponses with the Flowable of the single raw response.
  Assert: Verify that the resulting Flowable emits exactly one LlmResponse. Verify that the emitted response contains the text "Hello World", has partial flag set to true, and the content role is "model".

Validation:
  This test ensures that the basic text accumulation and emission logic works correctly for a single streaming chunk. It validates that partial responses are properly marked and that text content is correctly extracted and wrapped in an LlmResponse object. This is fundamental to the streaming response processing functionality.

---

Scenario 2: Process Multiple Raw Responses with Accumulated Text

Details:
  TestName: processMultipleRawResponsesWithAccumulatedText
  Description: This test verifies that when multiple GenerateContentResponse objects with text chunks are processed sequentially, the method accumulates the text correctly and emits partial responses for each chunk.

Execution:
  Arrange: Create multiple GenerateContentResponse objects with text chunks ("Hello", " ", "World"). Create a Flowable emitting these responses in sequence. Mock GeminiUtil.getPart0FromLlmResponse to return appropriate Parts for each response.
  Act: Invoke processRawResponses with the Flowable of multiple raw responses.
  Assert: Verify that the resulting Flowable emits three partial LlmResponse objects with texts "Hello", " ", and "World" respectively. Verify all have partial flag set to true.

Validation:
  This test validates the streaming accumulation behavior where text is emitted incrementally as it arrives. It ensures that each chunk is processed independently and emitted as a partial response, which is critical for real-time streaming user experiences.

---

Scenario 3: Process Raw Response with Thought Content

Details:
  TestName: processRawResponseWithThoughtContent
  Description: This test verifies that when a GenerateContentResponse contains a Part marked as thought (thought flag is true), the method correctly processes it as thinking content and emits it with the thought flag preserved.

Execution:
  Arrange: Create a GenerateContentResponse with a Part containing text "Thinking..." and thought flag set to true. Create a Flowable with this response. Mock GeminiUtil.getPart0FromLlmResponse to return the thought Part.
  Act: Invoke processRawResponses with the Flowable containing the thought response.
  Assert: Verify that the emitted LlmResponse contains a Part with thought flag set to true, contains the text "Thinking...", has partial flag set to true, and role is "model".

Validation:
  This test ensures that thought content is distinguished from regular text content and processed through the separate thought accumulation path. This is important for models that expose their reasoning process, allowing applications to display thinking steps differently from final outputs.

---

Scenario 4: Process Raw Response with Blank Text

Details:
  TestName: processRawResponseWithBlankText
  Description: This test verifies that when a GenerateContentResponse contains blank or empty text, the method processes it as a control signal and emits the processed LlmResponse without accumulating text.

Execution:
  Arrange: Create a GenerateContentResponse with a Part containing blank text ("" or whitespace only). Create a Flowable with this response. Mock GeminiUtil.getPart0FromLlmResponse to return the Part with blank text. Mock GeminiUtil.shouldEmitAccumulatedText to return false.
  Act: Invoke processRawResponses with the Flowable containing the blank text response.
  Assert: Verify that the emitted LlmResponse is the processed version of the raw response (created via LlmResponse.create), and no additional partial text responses are emitted.

Validation:
  This test validates the handling of control or metadata responses that don't contain actual text content. Such responses might contain finish reasons, usage metadata, or other control information that should be passed through without text accumulation.

---

Scenario 5: Process Raw Responses with Accumulated Text Emission Trigger

Details:
  TestName: processRawResponsesWithAccumulatedTextEmissionTrigger
  Description: This test verifies that when accumulated text exists and a response triggers emission (via GeminiUtil.shouldEmitAccumulatedText returning true), the method emits the accumulated text as a complete (non-partial) response and resets the accumulator.

Execution:
  Arrange: Create a sequence of responses: first with text "Hello World", second with blank text that triggers emission. Mock GeminiUtil.getPart0FromLlmResponse appropriately. Mock GeminiUtil.shouldEmitAccumulatedText to return true for the second response.
  Act: Invoke processRawResponses with the Flowable of these responses.
  Assert: Verify that two responses are emitted: first a partial response with "Hello World", then a complete (non-partial) response with "Hello World", followed by the processed blank response.

Validation:
  This test ensures that the method correctly handles emission triggers, which signal that accumulated content should be finalized and emitted as a complete unit. This is important for maintaining proper message boundaries in streaming responses.

---

Scenario 6: Process Raw Responses with Accumulated Thought Text Emission

Details:
  TestName: processRawResponsesWithAccumulatedThoughtTextEmission
  Description: This test verifies that when accumulated thought text exists and a response triggers emission, the method emits the accumulated thought text as a complete thinking response and resets the thought accumulator.

Execution:
  Arrange: Create a sequence of responses: first with thought text "Analyzing...", second with blank text that triggers emission. Mock GeminiUtil.getPart0FromLlmResponse and GeminiUtil.shouldEmitAccumulatedText appropriately.
  Act: Invoke processRawResponses with the Flowable of these responses.
  Assert: Verify that a partial thought response with "Analyzing..." is emitted first, then a complete thought response with "Analyzing..." (thought flag true, partial false), followed by the processed blank response.

Validation:
  This test validates the separate accumulation and emission path for thought content, ensuring that thinking steps are properly aggregated and emitted when signaled, maintaining the distinction between reasoning and output content.

---

Scenario 7: Process Raw Responses Ending with STOP Finish Reason

Details:
  TestName: processRawResponsesEndingWithStopFinishReason
  Description: This test verifies that when the final raw response has a STOP finish reason and accumulated text exists, the method emits the accumulated text as a final complete response after all streaming responses.

Execution:
  Arrange: Create a sequence of responses: first with text "Final text", second with STOP finish reason. Mock the Candidate and FinishReason to return STOP. Mock GeminiUtil.getPart0FromLlmResponse appropriately.
  Act: Invoke processRawResponses with the Flowable of these responses.
  Assert: Verify that a partial response with "Final text" is emitted during streaming, and then a final complete response with "Final text" is emitted at the end (via the deferred Flowable).

Validation:
  This test ensures that when streaming completes normally (STOP finish reason), any remaining accumulated content is properly emitted as a final response. This prevents data loss and ensures clients receive all generated content even if the final chunk wasn't explicitly emitted during streaming.

---

Scenario 8: Process Raw Responses Ending with STOP and Accumulated Thought Text

Details:
  TestName: processRawResponsesEndingWithStopAndAccumulatedThoughtText
  Description: This test verifies that when the final raw response has a STOP finish reason and accumulated thought text exists, the method emits the accumulated thought text as a final complete thinking response.

Execution:
  Arrange: Create a sequence of responses: first with thought text "Final thinking", second with STOP finish reason. Mock the response structure to return STOP finish reason. Mock GeminiUtil.getPart0FromLlmResponse appropriately.
  Act: Invoke processRawResponses with the Flowable of these responses.
  Assert: Verify that a partial thought response is emitted during streaming, and then a final complete thought response (with thought flag true) is emitted at the end.

Validation:
  This test validates that thought content is properly finalized when streaming completes, ensuring that reasoning steps are fully captured and emitted even if they weren't explicitly completed during the streaming phase.

---

Scenario 9: Process Raw Responses Ending with Non-STOP Finish Reason

Details:
  TestName: processRawResponsesEndingWithNonStopFinishReason
  Description: This test verifies that when the final raw response has a finish reason other than STOP (e.g., MAX_TOKENS, SAFETY), the method does not emit any additional final responses even if accumulated text exists.

Execution:
  Arrange: Create a sequence of responses: first with text "Incomplete", second with MAX_TOKENS finish reason. Mock the Candidate and FinishReason to return MAX_TOKENS. Mock GeminiUtil.getPart0FromLlmResponse appropriately.
  Act: Invoke processRawResponses with the Flowable of these responses.
  Assert: Verify that only the partial response with "Incomplete" is emitted during streaming, and no additional final response is emitted from the deferred Flowable.

Validation:
  This test ensures that when streaming terminates abnormally (due to token limits, safety filters, etc.), the method doesn't emit accumulated content as if it were complete. This prevents misleading clients into thinking the response was fully generated when it was actually truncated.

---

Scenario 10: Process Empty Raw Responses Flowable

Details:
  TestName: processEmptyRawResponsesFlowable
  Description: This test verifies that when an empty Flowable of raw responses is provided, the method returns an empty Flowable without emitting any responses or throwing exceptions.

Execution:
  Arrange: Create an empty Flowable<GenerateContentResponse>.
  Act: Invoke processRawResponses with the empty Flowable.
  Assert: Verify that the resulting Flowable completes without emitting any items. Verify no exceptions are thrown.

Validation:
  This test validates the edge case handling when no responses are received from the API. This could occur due to network issues, immediate errors, or other exceptional conditions. The method should handle this gracefully without crashing.

---

Scenario 11: Process Raw Response with No Part Available

Details:
  TestName: processRawResponseWithNoPartAvailable
  Description: This test verifies that when GeminiUtil.getPart0FromLlmResponse returns an empty Optional (no Part available), the method handles it gracefully and emits the processed response without attempting text extraction.

Execution:
  Arrange: Create a GenerateContentResponse. Mock GeminiUtil.getPart0FromLlmResponse to return Optional.empty(). Mock GeminiUtil.shouldEmitAccumulatedText to return false.
  Act: Invoke processRawResponses with a Flowable containing this response.
  Assert: Verify that the processed LlmResponse is emitted without any text content. Verify no NullPointerException or other exceptions are thrown.

Validation:
  This test ensures robustness when responses don't contain the expected Part structure. This could happen with malformed responses or responses containing only metadata. The method should handle this gracefully without crashing.

---

Scenario 12: Process Raw Responses with Mixed Text and Thought Content

Details:
  TestName: processRawResponsesWithMixedTextAndThoughtContent
  Description: This test verifies that when raw responses contain a mix of regular text and thought text, the method correctly separates and accumulates them independently, emitting appropriate responses for each type.

Execution:
  Arrange: Create a sequence of responses: first with regular text "Answer:", second with thought text "reasoning...", third with regular text "42". Mock GeminiUtil.getPart0FromLlmResponse to return appropriate Parts with correct thought flags.
  Act: Invoke processRawResponses with the Flowable of mixed responses.
  Assert: Verify that three partial responses are emitted in order: regular text "Answer:", thought text "reasoning..." (with thought flag), and regular text "42". Verify that text and thought accumulators are maintained separately.

Validation:
  This test validates that the method correctly handles interleaved regular and thought content, maintaining separate accumulation buffers for each type. This is crucial for models that intermix reasoning steps with actual output, ensuring proper categorization and display of each content type.

---

Scenario 13: Process Raw Responses with Both Accumulators Having Content at STOP

Details:
  TestName: processRawResponsesWithBothAccumulatorsHavingContentAtStop
  Description: This test verifies that when streaming ends with STOP finish reason and both text and thought accumulators contain content, the method emits both as final complete responses in the correct order (thought first, then text).

Execution:
  Arrange: Create a sequence of responses: first with thought text "Thinking", second with regular text "Answer", third with STOP finish reason. Mock the response structure appropriately.
  Act: Invoke processRawResponses with the Flowable of these responses.
  Assert: Verify that partial responses are emitted during streaming, and at the end, two final complete responses are emitted: first the complete thought response, then the complete text response.

Validation:
  This test ensures that when both types of accumulated content exist at stream completion, both are properly finalized and emitted in the correct order. This maintains the logical flow of reasoning followed by conclusion, which is important for user experience.

---

Scenario 14: Process Raw Response with Null Last Response Holder

Details:
  TestName: processRawResponseWithNullLastResponseHolder
  Description: This test verifies that when the deferred final emission logic executes but no responses were ever processed (lastRawResponseHolder is null), the method returns an empty Flowable without errors.

Execution:
  Arrange: Create a Flowable that completes immediately without emitting any GenerateContentResponse objects, causing the lastRawResponseHolder to remain null.
  Act: Invoke processRawResponses with this Flowable.
  Assert: Verify that the resulting Flowable completes without emitting any items and without throwing exceptions.

Validation:
  This test validates the null-safety of the final emission logic. In edge cases where the stream completes without any responses, the method should handle the null lastRawResponseHolder gracefully without causing NullPointerException.

---

Scenario 15: Process Raw Responses with Multiple Emission Triggers

Details:
  TestName: processRawResponsesWithMultipleEmissionTriggers
  Description: This test verifies that when multiple responses trigger accumulated text emission throughout the stream, the method correctly emits and resets the accumulator each time, maintaining proper state across multiple emission cycles.

Execution:
  Arrange: Create a sequence of responses: text "Part1", blank (trigger), text "Part2", blank (trigger), text "Part3". Mock GeminiUtil.shouldEmitAccumulatedText to return true for blank responses.
  Act: Invoke processRawResponses with the Flowable of these responses.
  Assert: Verify that the emission sequence is: partial "Part1", complete "Part1", blank response, partial "Part2", complete "Part2", blank response, partial "Part3". Verify that the accumulator is properly reset after each emission.

Validation:
  This test ensures that the accumulation and emission cycle can repeat multiple times within a single stream, with proper state management. This is important for long-running streams that may have multiple logical message boundaries or checkpoints.

---

Scenario 16: Process Raw Response with Part Having No Text Method Result

Details:
  TestName: processRawResponseWithPartHavingNoTextMethodResult
  Description: This test verifies that when a Part's text() method returns an empty Optional, the method treats it as blank text and processes accordingly without attempting to accumulate null values.

Execution:
  Arrange: Create a GenerateContentResponse with a Part where text() returns Optional.empty(). Mock GeminiUtil.getPart0FromLlmResponse to return this Part. Mock GeminiUtil.shouldEmitAccumulatedText to return false.
  Act: Invoke processRawResponses with a Flowable containing this response.
  Assert: Verify that the processed LlmResponse is emitted without text accumulation. Verify that no NullPointerException occurs when accessing the text.

Validation:
  This test validates null-safety when extracting text from Parts. Some Parts may not contain text (e.g., function calls, inline data), and the method should handle these gracefully without attempting to accumulate null or missing text values.

---

Scenario 17: Process Raw Responses with Whitespace-Only Text

Details:
  TestName: processRawResponsesWithWhitespaceOnlyText
  Description: This test verifies that when a Part contains only whitespace characters (spaces, tabs, newlines), the method treats it as blank text and does not accumulate or emit it as content.

Execution:
  Arrange: Create a GenerateContentResponse with a Part containing only whitespace ("   \n\t  "). Mock GeminiUtil.getPart0FromLlmResponse to return this Part. Mock GeminiUtil.shouldEmitAccumulatedText to return false.
  Act: Invoke processRawResponses with a Flowable containing this response.
  Assert: Verify that no partial text response is emitted for the whitespace. Verify that only the processed raw response is emitted (following the blank text path).

Validation:
  This test ensures that whitespace-only content is not treated as meaningful text. The isBlank() check should filter out such content, preventing emission of empty or whitespace-only responses that would not be useful to clients.

---

Scenario 18: Process Raw Responses with Finish Reason but No Candidates

Details:
  TestName: processRawResponsesWithFinishReasonButNoCandidates
  Description: This test verifies that when the final response has no candidates (empty Optional), the method treats it as non-STOP and does not emit final accumulated content.

Execution:
  Arrange: Create a sequence of responses: first with text "Content", second with no candidates (candidates() returns Optional.empty()). Mock GeminiUtil.getPart0FromLlmResponse appropriately.
  Act: Invoke processRawResponses with the Flowable of these responses.
  Assert: Verify that only the partial response with "Content" is emitted. Verify that no final complete response is emitted from the deferred logic.

Validation:
  This test validates handling of malformed or incomplete final responses that lack candidate information. Without candidates, the finish reason cannot be determined, so the method should not assume successful completion and should not emit accumulated content as final.

---

Scenario 19: Process Raw Responses with Candidate but No Finish Reason

Details:
  TestName: processRawResponsesWithCandidateButNoFinishReason
  Description: This test verifies that when the final response has a candidate but no finish reason (finishReason() returns Optional.empty()), the method treats it as non-STOP and does not emit final accumulated content.

Execution:
  Arrange: Create a sequence of responses: first with text "Content", second with a candidate but finishReason() returning Optional.empty(). Mock the response structure appropriately.
  Act: Invoke processRawResponses with the Flowable of these responses.
  Assert: Verify that only the partial response with "Content" is emitted. Verify that no final complete response is emitted from the deferred logic.

Validation:
  This test ensures that without an explicit STOP finish reason, the method does not assume successful completion. Missing finish reasons might indicate errors or incomplete responses, so accumulated content should not be finalized.

---

Scenario 20: Process Raw Responses with Accumulated Text and No Emission Trigger

Details:
  TestName: processRawResponsesWithAccumulatedTextAndNoEmissionTrigger
  Description: This test verifies that when accumulated text exists but blank responses do not trigger emission (shouldEmitAccumulatedText returns false), the accumulated text is not emitted until the final STOP.

Execution:
  Arrange: Create a sequence of responses: text "Accumulating", blank (no trigger), STOP. Mock GeminiUtil.shouldEmitAccumulatedText to return false for the blank response.
  Act: Invoke processRawResponses with the Flowable of these responses.
  Assert: Verify that only a partial response with "Accumulating" is emitted during streaming, the blank response is emitted as-is, and then a final complete response with "Accumulating" is emitted at STOP.

Validation:
  This test validates that emission triggers are properly respected. Not all blank responses should trigger emission; the GeminiUtil.shouldEmitAccumulatedText logic determines when accumulated content should be finalized, allowing for flexible control over message boundaries.

---

Scenario 21: Process Raw Responses with Thought Flag False Explicitly

Details:
  TestName: processRawResponsesWithThoughtFlagFalseExplicitly
  Description: This test verifies that when a Part has thought() returning Optional.of(false), the method treats it as regular text content and accumulates it in the text accumulator, not the thought accumulator.

Execution:
  Arrange: Create a GenerateContentResponse with a Part containing text "Regular" and thought() returning Optional.of(false). Mock GeminiUtil.getPart0FromLlmResponse to return this Part.
  Act: Invoke processRawResponses with a Flowable containing this response.
  Assert: Verify that a partial regular text response (not thought) is emitted with "Regular". Verify that the text accumulator is used, not the thought accumulator.

Validation:
  This test ensures that the thought flag is properly evaluated, distinguishing between explicitly false (regular text) and absent/empty Optional. The orElse(false) logic should handle both cases correctly, routing content to the appropriate accumulator.

---

Scenario 22: Process Raw Responses with Large Accumulated Text

Details:
  TestName: processRawResponsesWithLargeAccumulatedText
  Description: This test verifies that the method can handle accumulation of large amounts of text across many streaming chunks without performance degradation or memory issues.

Execution:
  Arrange: Create a sequence of 1000 responses, each containing a text chunk of 100 characters. Mock GeminiUtil.getPart0FromLlmResponse appropriately for each response.
  Act: Invoke processRawResponses with the Flowable of these responses.
  Assert: Verify that 1000 partial responses are emitted, each containing the respective chunk. Verify that the StringBuilder accumulation works correctly for large text volumes.

Validation:
  This test validates the scalability and performance of the text accumulation mechanism. Long-running streams with many chunks should be handled efficiently without memory leaks or performance issues, ensuring the method is production-ready for real-world usage.

---

Scenario 23: Process Raw Responses with Concurrent Text and Thought Accumulation

Details:
  TestName: processRawResponsesWithConcurrentTextAndThoughtAccumulation
  Description: This test verifies that when text and thought content are interleaved and accumulated simultaneously, both accumulators maintain their state independently without interference.

Execution:
  Arrange: Create a sequence: thought "Step1", text "Output1", thought "Step2", text "Output2", blank (trigger both). Mock GeminiUtil.shouldEmitAccumulatedText to return true for the blank response.
  Act: Invoke processRawResponses with the Flowable of these responses.
  Assert: Verify that partial responses are emitted for each chunk, then complete responses for both accumulated thought ("Step1Step2") and accumulated text ("Output1Output2") are emitted when triggered.

Validation:
  This test ensures that the two independent accumulators (text and thought) can operate concurrently without state corruption. This is critical for models that generate both reasoning and output simultaneously, requiring proper isolation between the two content streams.

---

Scenario 24: Process Raw Responses with Empty String Text

Details:
  TestName: processRawResponsesWithEmptyStringText
  Description: This test verifies that when a Part contains an empty string ("") as text, the method treats it as blank and does not accumulate or emit it as content.

Execution:
  Arrange: Create a GenerateContentResponse with a Part containing empty string text (""). Mock GeminiUtil.getPart0FromLlmResponse to return this Part. Mock GeminiUtil.shouldEmitAccumulatedText to return false.
  Act: Invoke processRawResponses with a Flowable containing this response.
  Assert: Verify that no partial text response is emitted. Verify that only the processed raw response is emitted (following the blank text path).

Validation:
  This test validates that empty strings are properly identified as blank content by the isBlank() check. Empty strings should not result in emission of meaningless responses, maintaining clean output streams for clients.

---

Scenario 25: Process Raw Responses Logging Behavior

Details:
  TestName: processRawResponsesLoggingBehavior
  Description: This test verifies that the method logs appropriate trace and debug messages at key processing points, aiding in debugging and monitoring of streaming response processing.

Execution:
  Arrange: Create a sequence of responses with various content types. Set up a test logger or logger spy to capture log messages. Mock GeminiUtil methods appropriately.
  Act: Invoke processRawResponses with the Flowable of responses.
  Assert: Verify that trace-level logs are generated for each raw streaming response. Verify that debug-level logs are generated for responses to emit. Verify that log messages contain relevant information about the processing state.

Validation:
  This test ensures that the logging infrastructure is properly integrated and provides useful diagnostic information. Proper logging is essential for production debugging, performance monitoring, and understanding the flow of streaming responses through the system.

*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;
import com.google.genai.types.Candidate;
import com.google.genai.types.Content;
import com.google.genai.types.FinishReason;
import com.google.genai.types.GenerateContentResponse;
import com.google.genai.types.Part;
import io.reactivex.rxjava3.core.Flowable;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.MockedStatic;
import org.junit.jupiter.api.*;
import static com.google.common.base.StandardSystemProperty.JAVA_VERSION;
import com.google.adk.Version;
import com.google.common.collect.ImmutableMap;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.genai.Client;
import com.google.genai.ResponseStream;
import com.google.genai.types.GenerateContentConfig;
import com.google.genai.types.HttpOptions;
import com.google.genai.types.LiveConnectConfig;
import java.util.ArrayList;
import java.util.Objects;
import java.util.concurrent.CompletableFuture;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

class GeminiProcessRawResponsesTest {

	@BeforeEach
	void setUp() {
		// Setup common test fixtures if needed
	}

	@Test
	@Tag("valid")
	void processSingleRawResponseWithNonBlankTextContent() {
		Part mockPart = Part.fromText("Hello World");
		GenerateContentResponse mockResponse = GenerateContentResponse.builder()
			.candidates(List.of(Candidate.builder().content(Content.builder().parts(mockPart).build()).build()))
			.build();
		try (MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
			geminiUtilMock.when(() -> GeminiUtil.getPart0FromLlmResponse(any())).thenReturn(Optional.of(mockPart));
			Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse);
			List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();
			assertEquals(1, results.size());
			assertTrue(results.get(0).partial().orElse(false));
			assertTrue(results.get(0).content().isPresent());
			assertEquals("Hello World", results.get(0).content().get().parts().get().get(0).text().orElse(""));
		}
	}

	@Test
	@Tag("valid")
	void processMultipleRawResponsesWithAccumulatedText() {
		Part part1 = Part.fromText("Hello");
		Part part2 = Part.fromText(" ");
		Part part3 = Part.fromText("World");
		GenerateContentResponse response1 = createResponseWithPart(part1);
		GenerateContentResponse response2 = createResponseWithPart(part2);
		GenerateContentResponse response3 = createResponseWithPart(part3);
		try (MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
			geminiUtilMock.when(() -> GeminiUtil.getPart0FromLlmResponse(any()))
				.thenReturn(Optional.of(part1), Optional.of(part2), Optional.of(part3));
			Flowable<GenerateContentResponse> rawResponses = Flowable.just(response1, response2, response3);
			List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();
			assertEquals(3, results.size());
			assertTrue(results.get(0).partial().orElse(false));
			assertTrue(results.get(1).partial().orElse(false));
			assertTrue(results.get(2).partial().orElse(false));
		}
	}

	@Test
	@Tag("valid")
	void processRawResponseWithThoughtContent() {
		Part thoughtPart = Part.fromText("Thinking...").toBuilder().thought(true).build();
		GenerateContentResponse mockResponse = createResponseWithPart(thoughtPart);
		try (MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
			geminiUtilMock.when(() -> GeminiUtil.getPart0FromLlmResponse(any())).thenReturn(Optional.of(thoughtPart));
			Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse);
			List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();
			assertEquals(1, results.size());
			assertTrue(results.get(0).partial().orElse(false));
			assertTrue(results.get(0).content().isPresent());
			assertTrue(results.get(0).content().get().parts().get().get(0).thought().orElse(false));
		}
	}

	@Test
	@Tag("boundary")
	void processRawResponseWithBlankText() {
		Part blankPart = Part.fromText("");
		GenerateContentResponse mockResponse = createResponseWithPart(blankPart);
		try (MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
			geminiUtilMock.when(() -> GeminiUtil.getPart0FromLlmResponse(any())).thenReturn(Optional.of(blankPart));
			geminiUtilMock.when(() -> GeminiUtil.shouldEmitAccumulatedText(any())).thenReturn(false);
			Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse);
			List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();
			assertEquals(1, results.size());
		}
	}

	@Test
	@Tag("valid")
	void processRawResponsesWithAccumulatedTextEmissionTrigger() {
		Part textPart = Part.fromText("Hello World");
		Part blankPart = Part.fromText("");
		GenerateContentResponse response1 = createResponseWithPart(textPart);
		GenerateContentResponse response2 = createResponseWithPart(blankPart);
		try (MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
			geminiUtilMock.when(() -> GeminiUtil.getPart0FromLlmResponse(any()))
				.thenReturn(Optional.of(textPart), Optional.of(blankPart));
			geminiUtilMock.when(() -> GeminiUtil.shouldEmitAccumulatedText(any())).thenReturn(false, true);
			Flowable<GenerateContentResponse> rawResponses = Flowable.just(response1, response2);
			List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();
			assertTrue(results.size() >= 2);
			assertTrue(results.get(0).partial().orElse(false));
		}
	}

	@Test
	@Tag("valid")
	void processRawResponsesWithAccumulatedThoughtTextEmission() {
		Part thoughtPart = Part.fromText("Analyzing...").toBuilder().thought(true).build();
		Part blankPart = Part.fromText("");
		GenerateContentResponse response1 = createResponseWithPart(thoughtPart);
		GenerateContentResponse response2 = createResponseWithPart(blankPart);
		try (MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
			geminiUtilMock.when(() -> GeminiUtil.getPart0FromLlmResponse(any()))
				.thenReturn(Optional.of(thoughtPart), Optional.of(blankPart));
			geminiUtilMock.when(() -> GeminiUtil.shouldEmitAccumulatedText(any())).thenReturn(false, true);
			Flowable<GenerateContentResponse> rawResponses = Flowable.just(response1, response2);
			List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();
			assertTrue(results.size() >= 2);
			assertTrue(results.stream()
				.anyMatch(r -> r.content()
					.flatMap(Content::parts)
					.map(parts -> parts.stream().anyMatch(p -> p.thought().orElse(false)))
					.orElse(false)));
		}
	}

	@Test
	@Tag("valid")
	void processRawResponsesEndingWithStopFinishReason() {
		Part textPart = Part.fromText("Final text");
		GenerateContentResponse response1 = createResponseWithPart(textPart);
		GenerateContentResponse response2 = createResponseWithFinishReason(FinishReason.Known.STOP);
		try (MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
			geminiUtilMock.when(() -> GeminiUtil.getPart0FromLlmResponse(any()))
				.thenReturn(Optional.of(textPart), Optional.of(Part.fromText("")));
			Flowable<GenerateContentResponse> rawResponses = Flowable.just(response1, response2);
			List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();
			assertTrue(results.size() >= 2);
			assertTrue(results.stream().anyMatch(r -> r.partial().orElse(false)));
		}
	}

	@Test
	@Tag("valid")
	void processRawResponsesEndingWithStopAndAccumulatedThoughtText() {
		Part thoughtPart = Part.fromText("Final thinking").toBuilder().thought(true).build();
		GenerateContentResponse response1 = createResponseWithPart(thoughtPart);
		GenerateContentResponse response2 = createResponseWithFinishReason(FinishReason.Known.STOP);
		try (MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
			geminiUtilMock.when(() -> GeminiUtil.getPart0FromLlmResponse(any()))
				.thenReturn(Optional.of(thoughtPart), Optional.of(Part.fromText("")));
			Flowable<GenerateContentResponse> rawResponses = Flowable.just(response1, response2);
			List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();
			assertTrue(results.size() >= 1);
		}
	}

	@Test
	@Tag("valid")
	void processRawResponsesEndingWithNonStopFinishReason() {
		Part textPart = Part.fromText("Incomplete");
		GenerateContentResponse response1 = createResponseWithPart(textPart);
		GenerateContentResponse response2 = createResponseWithFinishReason(FinishReason.Known.MAX_TOKENS);
		try (MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
			geminiUtilMock.when(() -> GeminiUtil.getPart0FromLlmResponse(any()))
				.thenReturn(Optional.of(textPart), Optional.of(Part.fromText("")));
			Flowable<GenerateContentResponse> rawResponses = Flowable.just(response1, response2);
			List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();
			assertTrue(results.size() >= 1);
		}
	}

	@Test
	@Tag("boundary")
	void processEmptyRawResponsesFlowable() {
		Flowable<GenerateContentResponse> emptyFlowable = Flowable.empty();
		List<LlmResponse> results = Gemini.processRawResponses(emptyFlowable).toList().blockingGet();
		assertEquals(0, results.size());
	}

	@Test
	@Tag("boundary")
	void processRawResponseWithNoPartAvailable() {
		GenerateContentResponse mockResponse = GenerateContentResponse.builder().build();
		try (MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
			geminiUtilMock.when(() -> GeminiUtil.getPart0FromLlmResponse(any())).thenReturn(Optional.empty());
			geminiUtilMock.when(() -> GeminiUtil.shouldEmitAccumulatedText(any())).thenReturn(false);
			Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse);
			List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();
			assertEquals(1, results.size());
		}
	}

	@Test
	@Tag("valid")
	void processRawResponsesWithMixedTextAndThoughtContent() {
		Part regularPart1 = Part.fromText("Answer:");
		Part thoughtPart = Part.fromText("reasoning...").toBuilder().thought(true).build();
		Part regularPart2 = Part.fromText("42");
		GenerateContentResponse response1 = createResponseWithPart(regularPart1);
		GenerateContentResponse response2 = createResponseWithPart(thoughtPart);
		GenerateContentResponse response3 = createResponseWithPart(regularPart2);
		try (MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
			geminiUtilMock.when(() -> GeminiUtil.getPart0FromLlmResponse(any()))
				.thenReturn(Optional.of(regularPart1), Optional.of(thoughtPart), Optional.of(regularPart2));
			Flowable<GenerateContentResponse> rawResponses = Flowable.just(response1, response2, response3);
			List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();
			assertEquals(3, results.size());
		}
	}

	@Test
	@Tag("valid")
	void processRawResponsesWithBothAccumulatorsHavingContentAtStop() {
		Part thoughtPart = Part.fromText("Thinking").toBuilder().thought(true).build();
		Part regularPart = Part.fromText("Answer");
		GenerateContentResponse response1 = createResponseWithPart(thoughtPart);
		GenerateContentResponse response2 = createResponseWithPart(regularPart);
		GenerateContentResponse response3 = createResponseWithFinishReason(FinishReason.Known.STOP);
		try (MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
			geminiUtilMock.when(() -> GeminiUtil.getPart0FromLlmResponse(any()))
				.thenReturn(Optional.of(thoughtPart), Optional.of(regularPart), Optional.of(Part.fromText("")));
			Flowable<GenerateContentResponse> rawResponses = Flowable.just(response1, response2, response3);
			List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();
			assertTrue(results.size() >= 2);
		}
	}

	@Test
	@Tag("boundary")
	void processRawResponseWithNullLastResponseHolder() {
		Flowable<GenerateContentResponse> emptyFlowable = Flowable.empty();
		List<LlmResponse> results = Gemini.processRawResponses(emptyFlowable).toList().blockingGet();
		assertEquals(0, results.size());
	}

	@Test
	@Tag("valid")
	void processRawResponsesWithMultipleEmissionTriggers() {
		Part part1 = Part.fromText("Part1");
		Part blankPart1 = Part.fromText("");
		Part part2 = Part.fromText("Part2");
		Part blankPart2 = Part.fromText("");
		Part part3 = Part.fromText("Part3");
		GenerateContentResponse response1 = createResponseWithPart(part1);
		GenerateContentResponse response2 = createResponseWithPart(blankPart1);
		GenerateContentResponse response3 = createResponseWithPart(part2);
		GenerateContentResponse response4 = createResponseWithPart(blankPart2);
		GenerateContentResponse response5 = createResponseWithPart(part3);
		try (MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
			geminiUtilMock.when(() -> GeminiUtil.getPart0FromLlmResponse(any()))
				.thenReturn(Optional.of(part1), Optional.of(blankPart1), Optional.of(part2), Optional.of(blankPart2),
						Optional.of(part3));
			geminiUtilMock.when(() -> GeminiUtil.shouldEmitAccumulatedText(any()))
				.thenReturn(false, true, false, true, false);
			Flowable<GenerateContentResponse> rawResponses = Flowable.just(response1, response2, response3, response4,
					response5);
			List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();
			assertTrue(results.size() >= 5);
		}
	}

	@Test
	@Tag("boundary")
	void processRawResponseWithPartHavingNoTextMethodResult() {
		Part mockPart = mock(Part.class);
		when(mockPart.text()).thenReturn(Optional.empty());
		when(mockPart.thought()).thenReturn(Optional.empty());
		GenerateContentResponse mockResponse = GenerateContentResponse.builder().build();
		try (MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
			geminiUtilMock.when(() -> GeminiUtil.getPart0FromLlmResponse(any())).thenReturn(Optional.of(mockPart));
			geminiUtilMock.when(() -> GeminiUtil.shouldEmitAccumulatedText(any())).thenReturn(false);
			Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse);
			List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();
			assertEquals(1, results.size());
		}
	}

	@Test
	@Tag("boundary")
	void processRawResponsesWithWhitespaceOnlyText() {
		Part whitespacePart = Part.fromText("   \n\t  ");
		GenerateContentResponse mockResponse = createResponseWithPart(whitespacePart);
		try (MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
			geminiUtilMock.when(() -> GeminiUtil.getPart0FromLlmResponse(any()))
				.thenReturn(Optional.of(whitespacePart));
			geminiUtilMock.when(() -> GeminiUtil.shouldEmitAccumulatedText(any())).thenReturn(false);
			Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse);
			List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();
			assertEquals(1, results.size());
		}
	}

	@Test
	@Tag("boundary")
	void processRawResponsesWithFinishReasonButNoCandidates() {
		Part textPart = Part.fromText("Content");
		GenerateContentResponse response1 = createResponseWithPart(textPart);
		GenerateContentResponse response2 = GenerateContentResponse.builder().build();
		try (MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
			geminiUtilMock.when(() -> GeminiUtil.getPart0FromLlmResponse(any()))
				.thenReturn(Optional.of(textPart), Optional.of(Part.fromText("")));
			Flowable<GenerateContentResponse> rawResponses = Flowable.just(response1, response2);
			List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();
			assertTrue(results.size() >= 1);
		}
	}

	@Test
	@Tag("boundary")
	void processRawResponsesWithCandidateButNoFinishReason() {
		Part textPart = Part.fromText("Content");
		GenerateContentResponse response1 = createResponseWithPart(textPart);
		GenerateContentResponse response2 = GenerateContentResponse.builder()
			.candidates(List.of(Candidate.builder().build()))
			.build();
		try (MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
			geminiUtilMock.when(() -> GeminiUtil.getPart0FromLlmResponse(any()))
				.thenReturn(Optional.of(textPart), Optional.of(Part.fromText("")));
			Flowable<GenerateContentResponse> rawResponses = Flowable.just(response1, response2);
			List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();
			assertTrue(results.size() >= 1);
		}
	}

	@Test
	@Tag("valid")
	void processRawResponsesWithAccumulatedTextAndNoEmissionTrigger() {
		Part textPart = Part.fromText("Accumulating");
		Part blankPart = Part.fromText("");
		GenerateContentResponse response1 = createResponseWithPart(textPart);
		GenerateContentResponse response2 = createResponseWithPart(blankPart);
		GenerateContentResponse response3 = createResponseWithFinishReason(FinishReason.Known.STOP);
		try (MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
			geminiUtilMock.when(() -> GeminiUtil.getPart0FromLlmResponse(any()))
				.thenReturn(Optional.of(textPart), Optional.of(blankPart), Optional.of(Part.fromText("")));
			geminiUtilMock.when(() -> GeminiUtil.shouldEmitAccumulatedText(any())).thenReturn(false);
			Flowable<GenerateContentResponse> rawResponses = Flowable.just(response1, response2, response3);
			List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();
			assertTrue(results.size() >= 2);
		}
	}

	@Test
	@Tag("valid")
	void processRawResponsesWithThoughtFlagFalseExplicitly() {
		Part regularPart = Part.fromText("Regular").toBuilder().thought(false).build();
		GenerateContentResponse mockResponse = createResponseWithPart(regularPart);
		try (MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
			geminiUtilMock.when(() -> GeminiUtil.getPart0FromLlmResponse(any())).thenReturn(Optional.of(regularPart));
			Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse);
			List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();
			assertEquals(1, results.size());
			assertTrue(results.get(0).partial().orElse(false));
		}
	}

	@Test
	@Tag("valid")
	void processRawResponsesWithLargeAccumulatedText() {
		StringBuilder largeTextBuilder = new StringBuilder();
		for (int i = 0; i < 100; i++) {
			largeTextBuilder.append("0123456789");
		}
		String chunk = largeTextBuilder.toString();
		Part textPart = Part.fromText(chunk);
		GenerateContentResponse mockResponse = createResponseWithPart(textPart);
		try (MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
			geminiUtilMock.when(() -> GeminiUtil.getPart0FromLlmResponse(any())).thenReturn(Optional.of(textPart));
			Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse);
			List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();
			assertEquals(1, results.size());
			assertTrue(results.get(0).content().isPresent());
		}
	}

	@Test
	@Tag("valid")
	void processRawResponsesWithConcurrentTextAndThoughtAccumulation() {
		Part thought1 = Part.fromText("Step1").toBuilder().thought(true).build();
		Part text1 = Part.fromText("Output1");
		Part thought2 = Part.fromText("Step2").toBuilder().thought(true).build();
		Part text2 = Part.fromText("Output2");
		Part blankPart = Part.fromText("");
		GenerateContentResponse response1 = createResponseWithPart(thought1);
		GenerateContentResponse response2 = createResponseWithPart(text1);
		GenerateContentResponse response3 = createResponseWithPart(thought2);
		GenerateContentResponse response4 = createResponseWithPart(text2);
		GenerateContentResponse response5 = createResponseWithPart(blankPart);
		try (MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
			geminiUtilMock.when(() -> GeminiUtil.getPart0FromLlmResponse(any()))
				.thenReturn(Optional.of(thought1), Optional.of(text1), Optional.of(thought2), Optional.of(text2),
						Optional.of(blankPart));
			geminiUtilMock.when(() -> GeminiUtil.shouldEmitAccumulatedText(any()))
				.thenReturn(false, false, false, false, true);
			Flowable<GenerateContentResponse> rawResponses = Flowable.just(response1, response2, response3, response4,
					response5);
			List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();
			assertTrue(results.size() >= 4);
		}
	}

	@Test
	@Tag("boundary")
	void processRawResponsesWithEmptyStringText() {
		Part emptyPart = Part.fromText("");
		GenerateContentResponse mockResponse = createResponseWithPart(emptyPart);
		try (MockedStatic<GeminiUtil> geminiUtilMock = mockStatic(GeminiUtil.class)) {
			geminiUtilMock.when(() -> GeminiUtil.getPart0FromLlmResponse(any())).thenReturn(Optional.of(emptyPart));
			geminiUtilMock.when(() -> GeminiUtil.shouldEmitAccumulatedText(any())).thenReturn(false);
			Flowable<GenerateContentResponse> rawResponses = Flowable.just(mockResponse);
			List<LlmResponse> results = Gemini.processRawResponses(rawResponses).toList().blockingGet();
			assertEquals(1, results.size());
		}
	}

	private GenerateContentResponse createResponseWithPart(Part part) {
		return GenerateContentResponse.builder()
			.candidates(List.of(Candidate.builder().content(Content.builder().parts(part).build()).build()))
			.build();
	}

	private GenerateContentResponse createResponseWithFinishReason(FinishReason.Known finishReason) {
		// Create a mock FinishReason that returns the expected Known enum
		FinishReason mockFinishReason = mock(FinishReason.class);
		when(mockFinishReason.knownEnum()).thenReturn(finishReason);

		return GenerateContentResponse.builder()
			.candidates(List.of(Candidate.builder().finishReason(mockFinishReason).build()))
			.build();
	}

}