/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test maven-adkjava-github using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=create_c0b4ba7866
ROOST_METHOD_SIG_HASH=create_c0b4ba7866

Scenario 1: Create LLM for Gemini Model Name

Details:
  TestName: createLlmWithGeminiModelName
  Description: This test checks that the create method in the LlmFactory, when provided a valid Gemini model name (e.g., "gemini-1.5-pro"), returns a new instance of the Gemini implementation of BaseLlm. The scenario targets correctness of regex-based factory selection for registered models.

Execution:
  Arrange: Ensure that the Gemini LlmFactory is registered for names matching "gemini-.*".
  Act: Call create with modelName set to "gemini-1.5-pro".
  Assert: Use JUnit assertions to verify that the returned instance is non-null and of type Gemini.
Validation:
  This assertion verifies that the method correctly identifies and processes model names matching the "gemini-.*" pattern, ensuring the appropriate factory is invoked and the expected LLM instance is created.

Scenario 2: Create LLM for Apigee Model Name

Details:
  TestName: createLlmWithApigeeModelName
  Description: This test evaluates whether the create method returns an ApigeeLlm instance when given a model name starting with "apigee/" (e.g., "apigee/model-a"). This checks correct factory selection for multiple regex patterns.

Execution:
  Arrange: Confirm the ApigeeLlm factory is registered for "apigee/.*" model names.
  Act: Call create with modelName set to "apigee/model-a".
  Assert: Use JUnit assertions to verify the returned instance is non-null and of type ApigeeLlm.
Validation:
  The assertion ensures that registering multiple factories with different regex patterns works and the correct factory is invoked depending on the modelName prefix.

Scenario 3: Create LLM with Unregistered Model Name

Details:
  TestName: createLlmWithUnknownModelName
  Description: This test covers the scenario where a model name does not match any registered factory pattern (e.g., "unknown-model-xyz"). It ensures the method throws the expected IllegalArgumentException when given an unsupported model name.

Execution:
  Arrange: Confirm that llmFactories does not contain a pattern that matches "unknown-model-xyz".
  Act: Call create with modelName set to "unknown-model-xyz".
  Assert: Use JUnit assertions to check that an IllegalArgumentException is thrown with the message indicating "Unsupported model".
Validation:
  The validation guarantees that no unintended models are processed and proper error handling is in place for unregistered patterns, enforcing registry integrity.

Scenario 4: Create LLM for Boundary Model Name Matching Multiple Patterns

Details:
  TestName: createLlmWithAmbiguousModelName
  Description: This scenario tests behavior when a modelName could match multiple registered patterns (e.g., "gemini-apigee-test" if both "gemini-.*" and ".*apigee.*" are registered). It ensures the first matching factory in the iteration order is selected.

Execution:
  Arrange: Register "gemini-.*" and ".*apigee.*" factories with distinct implementations.
  Act: Call create with modelName set to "gemini-apigee-test".
  Assert: Use JUnit assertions to validate which factory was chosen based on registration order.
Validation:
  This assertion ensures predictability in pattern matching when multiple regexes are eligible, clarifying behavior regarding factory selection precedence.

Scenario 5: Create LLM with Null Model Name

Details:
  TestName: createLlmWithNullModelName
  Description: This test verifies the response of the create method when passed a null as the modelName. The target is to observe if the method handles null gracefully or throws a NullPointerException.

Execution:
  Arrange: Ensure factories are registered; prepare to call create with a null modelName.
  Act: Call create with modelName set to null.
  Assert: Use JUnit assertions to check for NullPointerException, IllegalArgumentException, or required behavior.
Validation:
  This scenario validates input safety and robustness against null values, emphasizing safety in registry API usage.

Scenario 6: Create LLM with Empty String Model Name

Details:
  TestName: createLlmWithEmptyModelName
  Description: This scenario checks what happens if the create method is called with an empty string as modelName, which does not match any registered factory pattern.

Execution:
  Arrange: Register typical factories and ensure no pattern matches an empty string.
  Act: Call create with modelName set to "" (empty string).
  Assert: Use JUnit assertions to verify that an IllegalArgumentException is thrown or to check if an edge-case factory handles it.
Validation:
  This assertion verifies graceful error handling and correct restriction of allowed model names, preventing unexpected behavior for empty input.

Scenario 7: Create LLM When Factory Throws an Exception Internally

Details:
  TestName: createLlmFactoryThrowsException
  Description: This test evaluates how the create method handles the case where a factory exists and matches the pattern, but its internal creation logic throws a runtime exception (e.g., IllegalStateException).

Execution:
  Arrange: Register a custom factory that throws a runtime exception when invoked.
  Act: Call create with a modelName that triggers this factory.
  Assert: Use JUnit assertions to check that the thrown exception by the factory is propagated.
Validation:
  This scenario confirms that exceptions are not suppressed and propagate correctly, helping downstream systems diagnose factory failures.

Scenario 8: Create LLM with Very Long Model Name

Details:
  TestName: createLlmWithLongModelName
  Description: This test checks if the create method and its factories can safely handle extremely long model names (e.g., strings with thousands of characters), without crashing or performance degradation.

Execution:
  Arrange: Craft a long model name string that matches a registered factory pattern.
  Act: Invoke create with the long model name.
  Assert: Use JUnit assertions to ensure a valid LLM instance is returned and no exception is thrown.
Validation:
  This assertion tests input boundaries and ensures the registry is robust against abnormally large model names.

Scenario 9: Create LLM After Factory Deregistration

Details:
  TestName: createLlmAfterFactoryDeregistration
  Description: The test evaluates what happens if a factory is deregistered (removed or replaced with a different implementation) and create is called with a formerly valid model name.

Execution:
  Arrange: Register a factory for a pattern, then remove or replace it.
  Act: Call create with a modelName that previously matched the old factory pattern.
  Assert: Use JUnit assertions to confirm updated factory logic is applied or exception thrown.
Validation:
  This ensures dynamic registration and deregistration works as intended and verifies consistency of registry state between changes.

Scenario 10: Create LLM with Factory Registered for Exact Model Name

Details:
  TestName: createLlmWithExactModelNameRegistration
  Description: Test involves registering an LlmFactory with a regex pattern that matches an exact model name (e.g., "special-model-123"), checking if the registry supports exact as well as pattern matching.

Execution:
  Arrange: Register an LlmFactory using the regex "special-model-123".
  Act: Call create with modelName set to "special-model-123".
  Assert: Use JUnit assertions to verify the appropriate LLM instance is created.
Validation:
  This scenario confirms registry flexibility, supporting both exact and broad regex patterns, for precise factory selection.

Scenario 11: Create LLM With Factory Matching Empty Regex

Details:
  TestName: createLlmWithEmptyRegexPattern
  Description: This test registers a factory with an empty string as the match pattern and checks if the implementation processes all model names or none.

Execution:
  Arrange: Register an LlmFactory using an empty regex "" and observe its matching behavior.
  Act: Call create with various modelName values.
  Assert: Use JUnit assertions to check which modelNames are accepted by the empty regex factory.
Validation:
  This scenario explores edge cases in regex matching and registry pattern logic, ensuring no unintentional broad matches or failures.

Scenario 12: Create LLM Handling Concurrent Factory Modification

Details:
  TestName: createLlmWithConcurrentFactoryModification
  Description: This test evaluates the thread safety by modifying the llmFactories map concurrently while calling create from multiple threads, validating the registry’s atomic and consistent behavior.

Execution:
  Arrange: Start multiple threads that register or deregister factories for overlapping patterns.
  Act: Simultaneously invoke create with various modelNames.
  Assert: Use JUnit assertions to check creation consistency, absence of race conditions, and correct LLM instance generation.
Validation:
  This validates thread safety requirements, leveraging ConcurrentHashMap for reliable concurrent modifications without corrupting registry state.

Scenario 13: Create LLM After RegisterTestLlm Is Used

Details:
  TestName: createLlmAfterRegisterTestLlm
  Description: The test targets the interaction between factory registration using registerTestLlm and the creation method, confirming that test-specific factories override previous registrations and cached instances are cleared.

Execution:
  Arrange: Register a normal factory for a pattern, call create at least once, then call registerTestLlm for the same pattern with a test-specific factory.
  Act: Call create again with a matching modelName.
  Assert: Use JUnit assertions to verify cached instances are cleared and the new factory is used for creation.
Validation:
  This confirms test isolation and the correct refreshing of registry state when using the testing registration facility.

Scenario 14: Create LLM With Special Characters in Model Name

Details:
  TestName: createLlmWithSpecialCharactersInModelName
  Description: This test checks the handling of model names containing special regex characters (e.g., "+", "*", "[", "]", etc.) ensuring proper escaping or selection by registered factories.

Execution:
  Arrange: Register factories with patterns covering special characters.
  Act: Call create with modelNames containing special characters.
  Assert: Use JUnit assertions to verify correct factory matching and instance creation.
Validation:
  This ensures the create method and registration logic correctly parse and match model names containing special and reserved regex characters.

*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.*;

import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.function.Executable;
import org.mockito.Mockito;

@DisplayName("LlmFactory.create Tests")
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class LlmFactoryCreateTest {

	// Basic mock implementations for BaseLlm subtypes
	public static class BaseLlm {

	}

	public static class Gemini extends BaseLlm {

	}

	public static class ApigeeLlm extends BaseLlm {

	}

	public static class TestLlm extends BaseLlm {

	}

	public static class SpecialCharLlm extends BaseLlm {

	}

	public static class LongModelNameLlm extends BaseLlm {

	}

	public static class EmptyRegexLlm extends BaseLlm {

	}

	// Nested factory class imitation for testing purposes
	public static class LlmFactory {

		public BaseLlm create(String modelName) {
			// TODO: Add custom logic as needed for mock
			return null;
		}

	}

	// Parent registry imitation for test isolation
	public static class LlmRegistry {

		static final Map<String, LlmFactory> llmFactories = new ConcurrentHashMap<>();
		static final Map<String, BaseLlm> instances = new ConcurrentHashMap<>();

		public static void registerLlm(String modelNamePattern, LlmFactory factory) {
			llmFactories.put(modelNamePattern, factory);
		}

		public static BaseLlm getLlm(String modelName) {
			return instances.computeIfAbsent(modelName, LlmRegistry::createLlm);
		}

		private static BaseLlm createLlm(String modelName) {
			for (Map.Entry<String, LlmFactory> entry : llmFactories.entrySet()) {
				if (modelName != null && modelName.matches(entry.getKey())) {
					return entry.getValue().create(modelName);
				}
			}
			throw new IllegalArgumentException("Unsupported model: " + modelName);
		}

		static void registerTestLlm(String modelNamePattern, LlmFactory factory) {
			llmFactories.put(modelNamePattern, factory);
			instances.keySet().removeIf(modelName -> modelName != null && modelName.matches(modelNamePattern));
		}

	}

	@BeforeEach
	public void beforeEach() {
		LlmRegistry.llmFactories.clear();
		LlmRegistry.instances.clear();
	}

	@Test
	@Tag("valid")
	@DisplayName("Create LLM for Gemini Model Name")
	public void testCreateLlmWithGeminiModelName() {
		LlmFactory geminiFactory = Mockito.mock(LlmFactory.class);
		Mockito.when(geminiFactory.create(Mockito.eq("gemini-1.5-pro"))).thenReturn((BaseLlm) new Gemini());
		LlmRegistry.registerLlm("gemini-.*", geminiFactory);
		BaseLlm result = LlmRegistry.getLlm("gemini-1.5-pro");
		assertNotNull((Object) result);
		assertTrue(result instanceof Gemini, "Expected instance of Gemini");
	}

	@Test
	@Tag("valid")
	@DisplayName("Create LLM for Apigee Model Name")
	public void testCreateLlmWithApigeeModelName() {
		LlmFactory apigeeFactory = Mockito.mock(LlmFactory.class);
		Mockito.when(apigeeFactory.create(Mockito.eq("apigee/model-a"))).thenReturn((BaseLlm) new ApigeeLlm());
		LlmRegistry.registerLlm("apigee/.*", apigeeFactory);
		BaseLlm result = LlmRegistry.getLlm("apigee/model-a");
		assertNotNull((Object) result);
		assertTrue(result instanceof ApigeeLlm, "Expected instance of ApigeeLlm");
	}

	@Test
	@Tag("invalid")
	@DisplayName("Create LLM with Unregistered Model Name")
	public void testCreateLlmWithUnknownModelName() {
		Executable act = () -> LlmRegistry.getLlm("unknown-model-xyz");
		IllegalArgumentException ex = assertThrows(IllegalArgumentException.class, act);
		assertTrue(ex.getMessage().contains("Unsupported model"),
				"Exception message should contain 'Unsupported model'");
	}

	@Test
	@Tag("boundary")
	@DisplayName("Create LLM for Boundary Model Name Matching Multiple Patterns")
	public void testCreateLlmWithAmbiguousModelName() {
		// Register Gemini first, then Apigee pattern
		LlmFactory geminiFactory = Mockito.mock(LlmFactory.class);
		LlmFactory apigeeFactory = Mockito.mock(LlmFactory.class);
		Mockito.when(geminiFactory.create(Mockito.eq("gemini-apigee-test"))).thenReturn((BaseLlm) new Gemini());
		Mockito.when(apigeeFactory.create(Mockito.eq("gemini-apigee-test"))).thenReturn((BaseLlm) new ApigeeLlm());
		LlmRegistry.registerLlm("gemini-.*", geminiFactory);
		LlmRegistry.registerLlm(".*apigee.*", apigeeFactory);
		BaseLlm result = LlmRegistry.getLlm("gemini-apigee-test");
		assertNotNull((Object) result);
		assertTrue(result instanceof Gemini, "Expected the first factory match (Gemini)");
	}

	@Test
	@Tag("invalid")
	@DisplayName("Create LLM with Null Model Name")
	public void testCreateLlmWithNullModelName() {
		LlmFactory anyFactory = Mockito.mock(LlmFactory.class);
		LlmRegistry.registerLlm(".*", anyFactory);
		Executable act = () -> LlmRegistry.getLlm(null);
		assertThrows(IllegalArgumentException.class, act, "Should throw for null modelName");
	}

	@Test
	@Tag("invalid")
	@DisplayName("Create LLM with Empty String Model Name")
	public void testCreateLlmWithEmptyModelName() {
		LlmFactory geminiFactory = Mockito.mock(LlmFactory.class);
		LlmRegistry.registerLlm("gemini-.*", geminiFactory);
		Executable act = () -> LlmRegistry.getLlm("");
		IllegalArgumentException ex = assertThrows(IllegalArgumentException.class, act);
		assertTrue(ex.getMessage().contains("Unsupported model"),
				"Exception message should contain 'Unsupported model'");
	}

	@Test
	@Tag("boundary")
	@DisplayName("Create LLM When Factory Throws an Exception Internally")
	public void testCreateLlmFactoryThrowsException() {
		LlmFactory brokenFactory = Mockito.mock(LlmFactory.class);
		Mockito.when(brokenFactory.create(Mockito.eq("broken-model")))
			.thenThrow(new IllegalStateException("Factory failed"));
		LlmRegistry.registerLlm("broken-.*", brokenFactory);
		Executable act = () -> LlmRegistry.getLlm("broken-model");
		IllegalStateException ex = assertThrows(IllegalStateException.class, act);
		assertEquals((Object) "Factory failed", (Object) ex.getMessage());
	}

	@Test
	@Tag("boundary")
	@DisplayName("Create LLM with Very Long Model Name")
	public void testCreateLlmWithLongModelName() {
		String longModelName = "long-" + "A".repeat(5000); // 5005 chars total
		LlmFactory longFactory = Mockito.mock(LlmFactory.class);
		Mockito.when(longFactory.create(Mockito.eq(longModelName))).thenReturn((BaseLlm) new LongModelNameLlm());
		LlmRegistry.registerLlm("long-.*", longFactory);
		BaseLlm result = LlmRegistry.getLlm(longModelName);
		assertNotNull((Object) result);
		assertTrue(result instanceof LongModelNameLlm, "Expected instance of LongModelNameLlm");
	}

	@Test
	@Tag("integration")
	@DisplayName("Create LLM After Factory Deregistration")
	public void testCreateLlmAfterFactoryDeregistration() {
		String pattern = "special-dereg-.*";
		LlmFactory oldFactory = Mockito.mock(LlmFactory.class);
		LlmFactory newFactory = Mockito.mock(LlmFactory.class);
		Mockito.when(oldFactory.create(Mockito.eq("special-dereg-model"))).thenReturn((BaseLlm) new TestLlm());
		LlmRegistry.registerLlm(pattern, oldFactory);
		BaseLlm first = LlmRegistry.getLlm("special-dereg-model");
		assertTrue(first instanceof TestLlm);
		// Deregister and re-register with different factory
		Mockito.when(newFactory.create(Mockito.eq("special-dereg-model"))).thenReturn((BaseLlm) new Gemini());
		LlmRegistry.registerLlm(pattern, newFactory);
		// Instances cache will have previous instance, so need to clear to test factory
		// change
		LlmRegistry.instances.remove("special-dereg-model");
		BaseLlm second = LlmRegistry.getLlm("special-dereg-model");
		assertTrue(second instanceof Gemini, "Expected instance from new factory after deregistration");
	}

	@Test
	@Tag("valid")
	@DisplayName("Create LLM with Factory Registered for Exact Model Name")
	public void testCreateLlmWithExactModelNameRegistration() {
		String exactModel = "special-model-123";
		LlmFactory exactFactory = Mockito.mock(LlmFactory.class);
		Mockito.when(exactFactory.create(Mockito.eq(exactModel))).thenReturn((BaseLlm) new TestLlm());
		LlmRegistry.registerLlm("special-model-123", exactFactory);
		BaseLlm result = LlmRegistry.getLlm(exactModel);
		assertNotNull((Object) result);
		assertTrue(result instanceof TestLlm, "Expected exact match TestLlm");
	}

	@Test
	@Tag("boundary")
	@DisplayName("Create LLM With Factory Matching Empty Regex")
	public void testCreateLlmWithEmptyRegexPattern() {
		LlmFactory emptyRegexFactory = Mockito.mock(LlmFactory.class);
		Mockito.when(emptyRegexFactory.create(Mockito.eq(""))).thenReturn((BaseLlm) new EmptyRegexLlm());
		LlmRegistry.registerLlm("", emptyRegexFactory);
		BaseLlm result = LlmRegistry.getLlm("");
		assertNotNull((Object) result);
		assertTrue(result instanceof EmptyRegexLlm, "Expected factory to handle empty string when empty regex is used");
	}

	@Test
	@Tag("integration")
	@DisplayName("Create LLM Handling Concurrent Factory Modification")
	public void testCreateLlmWithConcurrentFactoryModification() {
		Set<BaseLlm> createdLlms = new HashSet<>();
		Runnable registrar = () -> {
			LlmFactory factory = Mockito.mock(LlmFactory.class);
			Mockito.when(factory.create(Mockito.anyString())).thenAnswer(inv -> new TestLlm());
			for (int i = 0; i < 10; i++) {
				LlmRegistry.registerLlm("^concurrent-" + i + ".*", factory);
			}
		};
		Thread t1 = new Thread(registrar);
		Thread t2 = new Thread(registrar);
		t1.start();
		t2.start();
		try {
			t1.join();
			t2.join();
		}
		catch (InterruptedException e) {
			fail("Threads interrupted");
		}
		for (int i = 0; i < 10; i++) {
			String modelName = "concurrent-" + i + "-test";
			BaseLlm llm = LlmRegistry.getLlm(modelName);
			assertNotNull((Object) llm, "Created llm must not be null for concurrent modification");
			createdLlms.add(llm);
		}
		assertEquals(10, createdLlms.size(), "Should create unique LLMs for each concurrent model");
	}

	@Test
	@Tag("integration")
	@DisplayName("Create LLM After RegisterTestLlm Is Used")
	public void testCreateLlmAfterRegisterTestLlm() {
		String pattern = "test-isolation-.*";
		LlmFactory normalFactory = Mockito.mock(LlmFactory.class);
		LlmFactory testFactory = Mockito.mock(LlmFactory.class);
		Mockito.when(normalFactory.create(Mockito.eq("test-isolation-abc"))).thenReturn((BaseLlm) new TestLlm());
		LlmRegistry.registerLlm(pattern, normalFactory);
		BaseLlm first = LlmRegistry.getLlm("test-isolation-abc");
		assertTrue(first instanceof TestLlm);
		// Register test-specific factory
		Mockito.when(testFactory.create(Mockito.eq("test-isolation-abc"))).thenReturn((BaseLlm) new Gemini());
		LlmRegistry.registerTestLlm(pattern, testFactory);
		BaseLlm second = LlmRegistry.getLlm("test-isolation-abc");
		assertTrue(second instanceof Gemini, "Expected new factory from registerTestLlm and cache refresh");
	}

	@Test
	@Tag("valid")
	@DisplayName("Create LLM With Special Characters in Model Name")
	public void testCreateLlmWithSpecialCharactersInModelName() {
		LlmFactory specialFactory = Mockito.mock(LlmFactory.class);
		Mockito.when(specialFactory.create(Mockito.eq("special+regex*model[test]")))
			.thenReturn((BaseLlm) new SpecialCharLlm());
		// Register with explicit pattern that matches those characters
		LlmRegistry.registerLlm("special\\+regex\\*model\\[test\\]", specialFactory);
		BaseLlm result = LlmRegistry.getLlm("special+regex*model[test]");
		assertNotNull((Object) result);
		assertTrue(result instanceof SpecialCharLlm,
				"Factory should match and create for regex-special char modelName");
	}

}
