/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-maven-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=content_7d325c5bf7
ROOST_METHOD_SIG_HASH=content_7d325c5bf7

Scenario 1: Content is Present in LlmResponse

Details:
  TestName: contentReturnsPresentOptionalWhenContentExists
  Description: This test verifies that the content() method returns an Optional containing a Content object when the LlmResponse has been built with valid content. This tests the normal, successful case where content is available in the response.
Execution:
  Arrange: Create a Content object using appropriate builder or factory method. Build an LlmResponse instance using the builder and set the content using the content(Content) method.
  Act: Invoke the content() method on the LlmResponse instance.
  Assert: Use JUnit assertions to verify that the returned Optional is present (isPresent() returns true) and that the contained Content object matches the expected Content object.
Validation:
  This assertion verifies that when content is explicitly set during LlmResponse construction, the content() method correctly returns it wrapped in an Optional. This is critical for the normal flow of the application where LLM responses contain actual content that needs to be processed. The test ensures that the Optional pattern is correctly implemented for non-null content values.

Scenario 2: Content is Absent in LlmResponse

Details:
  TestName: contentReturnsEmptyOptionalWhenContentNotSet
  Description: This test verifies that the content() method returns an empty Optional when the LlmResponse is built without setting any content. This tests the case where no content is available in the response.
Execution:
  Arrange: Build an LlmResponse instance using the builder without calling the content() setter method, leaving content unset.
  Act: Invoke the content() method on the LlmResponse instance.
  Assert: Use JUnit assertions to verify that the returned Optional is empty (isEmpty() returns true or isPresent() returns false).
Validation:
  This assertion verifies that when no content is set during LlmResponse construction, the content() method correctly returns an empty Optional rather than null or throwing an exception. This is important for handling cases where the LLM response doesn't contain content (e.g., error responses, blocked responses). The Optional pattern provides a safe way to handle the absence of content without null pointer exceptions.

Scenario 3: Content Set Using Optional.of()

Details:
  TestName: contentReturnsPresentOptionalWhenSetViaOptional
  Description: This test verifies that the content() method returns the correct Content when the LlmResponse is built using the content(Optional<Content>) builder method with a present Optional.
Execution:
  Arrange: Create a Content object. Build an LlmResponse instance using the builder and set the content using content(Optional.of(contentObject)).
  Act: Invoke the content() method on the LlmResponse instance.
  Assert: Use JUnit assertions to verify that the returned Optional is present and contains the expected Content object.
Validation:
  This assertion verifies that the builder correctly handles setting content via an Optional parameter. This is important because the builder provides multiple ways to set content, and all should work correctly. This test ensures consistency in the API regardless of which builder method is used.

Scenario 4: Content Set Using Optional.empty()

Details:
  TestName: contentReturnsEmptyOptionalWhenSetViaEmptyOptional
  Description: This test verifies that the content() method returns an empty Optional when the LlmResponse is built using the content(Optional<Content>) builder method with an empty Optional.
Execution:
  Arrange: Build an LlmResponse instance using the builder and set the content using content(Optional.empty()).
  Act: Invoke the content() method on the LlmResponse instance.
  Assert: Use JUnit assertions to verify that the returned Optional is empty.
Validation:
  This assertion verifies that explicitly setting an empty Optional for content results in the content() method returning an empty Optional. This tests the edge case where content is explicitly set to absent, which should behave the same as not setting content at all. This ensures the builder handles Optional parameters correctly.

Scenario 5: Content from GenerateContentResponse with Candidates

Details:
  TestName: contentReturnsPresentOptionalWhenCreatedFromResponseWithCandidates
  Description: This test verifies that when an LlmResponse is created from a GenerateContentResponse containing candidates with content, the content() method returns the content from the first candidate.
Execution:
  Arrange: Create a Content object. Create a Candidate object with the content set. Create a GenerateContentResponse with a list containing the candidate. Build an LlmResponse using the response(GenerateContentResponse) builder method.
  Act: Invoke the content() method on the LlmResponse instance.
  Assert: Use JUnit assertions to verify that the returned Optional is present and contains the Content from the first candidate.
Validation:
  This assertion verifies the integration between LlmResponse and GenerateContentResponse. When creating an LlmResponse from a GenerateContentResponse, the content should be extracted from the first candidate. This is critical for the normal use case where LlmResponse wraps the raw API response and provides convenient access to the content.

Scenario 6: Content from GenerateContentResponse with Empty Candidates List

Details:
  TestName: contentReturnsEmptyOptionalWhenResponseHasEmptyCandidatesList
  Description: This test verifies that when an LlmResponse is created from a GenerateContentResponse with an empty candidates list, the content() method returns an empty Optional.
Execution:
  Arrange: Create a GenerateContentResponse with an empty candidates list. Build an LlmResponse using the response(GenerateContentResponse) builder method.
  Act: Invoke the content() method on the LlmResponse instance.
  Assert: Use JUnit assertions to verify that the returned Optional is empty.
Validation:
  This assertion verifies that when the GenerateContentResponse contains no candidates, the LlmResponse correctly represents the absence of content. This is an edge case that can occur when the LLM response is blocked or encounters an error before generating candidates. The test ensures graceful handling of this scenario.

Scenario 7: Content from GenerateContentResponse with Candidate but No Content

Details:
  TestName: contentReturnsEmptyOptionalWhenCandidateHasNoContent
  Description: This test verifies that when an LlmResponse is created from a GenerateContentResponse containing a candidate without content, the content() method returns an empty Optional.
Execution:
  Arrange: Create a Candidate object without setting content (content is empty Optional). Create a GenerateContentResponse with a list containing this candidate. Build an LlmResponse using the response(GenerateContentResponse) builder method.
  Act: Invoke the content() method on the LlmResponse instance.
  Assert: Use JUnit assertions to verify that the returned Optional is empty.
Validation:
  This assertion verifies that when a candidate exists but doesn't have content (possibly due to an error or blocking), the LlmResponse correctly represents the absence of content. This is important for error handling scenarios where the response structure exists but content generation failed.

Scenario 8: Content Immutability After Building

Details:
  TestName: contentRemainsConsistentAcrossMultipleCalls
  Description: This test verifies that calling the content() method multiple times on the same LlmResponse instance returns consistent results, demonstrating immutability.
Execution:
  Arrange: Create a Content object. Build an LlmResponse instance with the content set.
  Act: Invoke the content() method multiple times on the same LlmResponse instance.
  Assert: Use JUnit assertions to verify that all invocations return the same Optional with the same Content object (using reference equality or equals()).
Validation:
  This assertion verifies the immutability of the LlmResponse object. Since LlmResponse is an AutoValue class, it should be immutable, and the content() method should always return the same value. This is important for thread safety and predictable behavior in concurrent environments.

Scenario 9: Content from Static Create Method with Candidates

Details:
  TestName: contentReturnsPresentOptionalWhenCreatedViaStaticCreateWithCandidates
  Description: This test verifies that when an LlmResponse is created using the static create(List<Candidate>) method with candidates containing content, the content() method returns the content from the first candidate.
Execution:
  Arrange: Create a Content object. Create a Candidate with the content set. Create a list containing the candidate. Create an LlmResponse using LlmResponse.create(candidatesList).
  Act: Invoke the content() method on the LlmResponse instance.
  Assert: Use JUnit assertions to verify that the returned Optional is present and contains the expected Content.
Validation:
  This assertion verifies that the static factory method create(List<Candidate>) correctly initializes the LlmResponse with content from the candidates. This is an alternative construction method that should produce the same result as using the builder with a GenerateContentResponse.

Scenario 10: Content from Static Create Method with GenerateContentResponse

Details:
  TestName: contentReturnsPresentOptionalWhenCreatedViaStaticCreateWithResponse
  Description: This test verifies that when an LlmResponse is created using the static create(GenerateContentResponse) method, the content() method returns the content from the response's first candidate.
Execution:
  Arrange: Create a Content object. Create a Candidate with the content set. Create a GenerateContentResponse with the candidate. Create an LlmResponse using LlmResponse.create(response).
  Act: Invoke the content() method on the LlmResponse instance.
  Assert: Use JUnit assertions to verify that the returned Optional is present and contains the expected Content.
Validation:
  This assertion verifies that the static factory method create(GenerateContentResponse) correctly initializes the LlmResponse with content. This provides a convenient way to create LlmResponse instances from API responses and should correctly extract and expose the content.

Scenario 11: Content After Using toBuilder

Details:
  TestName: contentRemainsUnchangedAfterToBuilder
  Description: This test verifies that creating a new LlmResponse using toBuilder() from an existing instance preserves the content value when no modifications are made.
Execution:
  Arrange: Create a Content object. Build an LlmResponse instance with the content set. Use toBuilder() to get a builder from the instance, then build a new LlmResponse without modifications.
  Act: Invoke the content() method on both the original and the new LlmResponse instances.
  Assert: Use JUnit assertions to verify that both instances return the same content (equal Optional values).
Validation:
  This assertion verifies that the toBuilder() method correctly copies all properties, including content, to the new builder. This is important for creating modified copies of LlmResponse instances while preserving unchanged properties. The test ensures that the builder pattern is correctly implemented for immutable objects.

Scenario 12: Content Modified via toBuilder

Details:
  TestName: contentReflectsModificationWhenChangedViaToBuilder
  Description: This test verifies that when using toBuilder() to create a modified copy of an LlmResponse with different content, the content() method returns the new content.
Execution:
  Arrange: Create two different Content objects. Build an initial LlmResponse with the first content. Use toBuilder() and set the second content, then build a new LlmResponse.
  Act: Invoke the content() method on both LlmResponse instances.
  Assert: Use JUnit assertions to verify that the original instance returns the first content and the new instance returns the second content.
Validation:
  This assertion verifies that modifications made through toBuilder() are correctly reflected in the new instance while the original remains unchanged. This demonstrates proper immutability and the builder pattern's ability to create modified copies. This is important for scenarios where response objects need to be transformed or updated.

*/

// ********RoostGPT********

package com.google.adk.models;

import static com.google.common.truth.Truth.assertThat;

import com.google.genai.types.Candidate;
import com.google.genai.types.Content;
import com.google.genai.types.FinishReason;
import com.google.genai.types.GenerateContentResponse;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class LlmResponseContentTest {

  @Test
  @Tag("valid")
  void contentReturnsPresentOptionalWhenContentExists() {
    Content expectedContent = Content.builder().role("user").build();

    LlmResponse response = LlmResponse.builder().content(expectedContent).build();

    Optional<Content> actualContent = response.content();

    assertThat(actualContent.isPresent()).isTrue();
    assertThat(actualContent.get()).isEqualTo(expectedContent);
  }

  @Test
  @Tag("boundary")
  void contentReturnsEmptyOptionalWhenContentNotSet() {
    LlmResponse response = LlmResponse.builder().build();

    Optional<Content> actualContent = response.content();

    assertThat(actualContent.isEmpty()).isTrue();
  }

  @Test
  @Tag("valid")
  void contentReturnsPresentOptionalWhenSetViaOptional() {
    Content expectedContent = Content.builder().role("assistant").build();

    LlmResponse response = LlmResponse.builder().content(Optional.of(expectedContent)).build();

    Optional<Content> actualContent = response.content();

    assertThat(actualContent.isPresent()).isTrue();
    assertThat(actualContent.get()).isEqualTo(expectedContent);
  }

  @Test
  @Tag("boundary")
  void contentReturnsEmptyOptionalWhenSetViaEmptyOptional() {
    LlmResponse response = LlmResponse.builder().content(Optional.empty()).build();

    Optional<Content> actualContent = response.content();

    assertThat(actualContent.isEmpty()).isTrue();
  }

  @Test
  @Tag("integration")
  void contentReturnsPresentOptionalWhenCreatedFromResponseWithCandidates() {
    Content expectedContent = Content.builder().role("model").build();
    Candidate candidate = Candidate.builder().content(expectedContent).build();
    GenerateContentResponse generateResponse =
        GenerateContentResponse.builder().candidates(Collections.singletonList(candidate)).build();

    LlmResponse response = LlmResponse.builder().response(generateResponse).build();

    Optional<Content> actualContent = response.content();

    assertThat(actualContent.isPresent()).isTrue();
    assertThat(actualContent.get()).isEqualTo(expectedContent);
  }

  @Test
  @Tag("boundary")
  void contentReturnsEmptyOptionalWhenResponseHasEmptyCandidatesList() {
    GenerateContentResponse generateResponse =
        GenerateContentResponse.builder().candidates(Collections.emptyList()).build();

    LlmResponse response = LlmResponse.builder().response(generateResponse).build();

    Optional<Content> actualContent = response.content();

    assertThat(actualContent.isEmpty()).isTrue();
  }

  @Test
  @Tag("boundary")
  void contentReturnsEmptyOptionalWhenCandidateHasNoContent() {
    Candidate candidate = Candidate.builder().finishReason(new FinishReason("STOP")).build();
    GenerateContentResponse generateResponse =
        GenerateContentResponse.builder().candidates(Collections.singletonList(candidate)).build();

    LlmResponse response = LlmResponse.builder().response(generateResponse).build();

    Optional<Content> actualContent = response.content();

    assertThat(actualContent.isEmpty()).isTrue();
  }

  @Test
  @Tag("valid")
  void contentRemainsConsistentAcrossMultipleCalls() {
    Content expectedContent = Content.builder().role("user").build();

    LlmResponse response = LlmResponse.builder().content(expectedContent).build();

    Optional<Content> firstCall = response.content();
    Optional<Content> secondCall = response.content();
    Optional<Content> thirdCall = response.content();

    assertThat(firstCall.isPresent()).isTrue();
    assertThat(secondCall.isPresent()).isTrue();
    assertThat(thirdCall.isPresent()).isTrue();
    assertThat(firstCall.get()).isSameInstanceAs(secondCall.get());
    assertThat(secondCall.get()).isSameInstanceAs(thirdCall.get());
  }

  @Test
  @Tag("integration")
  void contentReturnsPresentOptionalWhenCreatedViaStaticCreateWithCandidates() {
    Content expectedContent = Content.builder().role("assistant").build();
    Candidate candidate = Candidate.builder().content(expectedContent).build();
    List<Candidate> candidates = Collections.singletonList(candidate);

    LlmResponse response = LlmResponse.create(candidates);

    Optional<Content> actualContent = response.content();

    assertThat(actualContent.isPresent()).isTrue();
    assertThat(actualContent.get()).isEqualTo(expectedContent);
  }

  @Test
  @Tag("integration")
  void contentReturnsPresentOptionalWhenCreatedViaStaticCreateWithResponse() {
    Content expectedContent = Content.builder().role("model").build();
    Candidate candidate = Candidate.builder().content(expectedContent).build();
    GenerateContentResponse generateResponse =
        GenerateContentResponse.builder().candidates(Collections.singletonList(candidate)).build();

    LlmResponse response = LlmResponse.create(generateResponse);

    Optional<Content> actualContent = response.content();

    assertThat(actualContent.isPresent()).isTrue();
    assertThat(actualContent.get()).isEqualTo(expectedContent);
  }

  @Test
  @Tag("valid")
  void contentRemainsUnchangedAfterToBuilder() {
    Content expectedContent = Content.builder().role("user").build();

    LlmResponse originalResponse = LlmResponse.builder().content(expectedContent).build();

    LlmResponse newResponse = originalResponse.toBuilder().build();

    Optional<Content> originalContent = originalResponse.content();
    Optional<Content> newContent = newResponse.content();

    assertThat(originalContent.isPresent()).isTrue();
    assertThat(newContent.isPresent()).isTrue();
    assertThat(originalContent.get()).isEqualTo(newContent.get());
  }

  @Test
  @Tag("valid")
  void contentReflectsModificationWhenChangedViaToBuilder() {
    Content firstContent = Content.builder().role("user").build();
    Content secondContent = Content.builder().role("assistant").build();

    LlmResponse originalResponse = LlmResponse.builder().content(firstContent).build();

    LlmResponse modifiedResponse = originalResponse.toBuilder().content(secondContent).build();

    Optional<Content> originalContent = originalResponse.content();
    Optional<Content> modifiedContent = modifiedResponse.content();

    assertThat(originalContent.isPresent()).isTrue();
    assertThat(modifiedContent.isPresent()).isTrue();
    assertThat(originalContent.get()).isEqualTo(firstContent);
    assertThat(modifiedContent.get()).isEqualTo(secondContent);
    assertThat(originalContent.get()).isNotEqualTo(modifiedContent.get());
  }

  @Test
  @Tag("boundary")
  void contentReturnsEmptyOptionalWhenResponseHasNoCandidates() {
    GenerateContentResponse generateResponse = GenerateContentResponse.builder().build();

    LlmResponse response = LlmResponse.builder().response(generateResponse).build();

    Optional<Content> actualContent = response.content();

    assertThat(actualContent.isEmpty()).isTrue();
  }

  @Test
  @Tag("integration")
  void contentReturnsFirstCandidateContentWhenMultipleCandidatesExist() {
    Content firstContent = Content.builder().role("model").build();
    Content secondContent = Content.builder().role("assistant").build();

    Candidate firstCandidate = Candidate.builder().content(firstContent).build();
    Candidate secondCandidate = Candidate.builder().content(secondContent).build();

    List<Candidate> candidates = new ArrayList<>();
    candidates.add(firstCandidate);
    candidates.add(secondCandidate);

    GenerateContentResponse generateResponse =
        GenerateContentResponse.builder().candidates(candidates).build();

    LlmResponse response = LlmResponse.builder().response(generateResponse).build();

    Optional<Content> actualContent = response.content();

    assertThat(actualContent.isPresent()).isTrue();
    assertThat(actualContent.get()).isEqualTo(firstContent);
  }

  @Test
  @Tag("boundary")
  void contentReturnsEmptyOptionalWhenBuilderSetToNull() {
    LlmResponse response = LlmResponse.builder().content((Content) null).build();

    Optional<Content> actualContent = response.content();

    assertThat(actualContent.isEmpty()).isTrue();
  }

  @Test
  @Tag("valid")
  void contentPreservesAllContentProperties() {
    Content expectedContent = Content.builder().role("user").build();

    LlmResponse response = LlmResponse.builder().content(expectedContent).build();

    Optional<Content> actualContent = response.content();

    assertThat(actualContent.isPresent()).isTrue();
    assertThat(actualContent.get().role()).isEqualTo(expectedContent.role());
  }
}
