/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test maven-adkjava-github using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=registerLlm_39033090dc
ROOST_METHOD_SIG_HASH=registerLlm_6d1828529e

Scenario 1: Registering a New Factory with a Unique Pattern

Details:
  TestName: registerUniquePatternFactory
  Description: This test checks that when registerLlm is called with a unique model name pattern and a corresponding factory, the llmFactories map is updated to contain the provided pattern mapped to the provided factory.
Execution:
  Arrange: Prepare a unique model name pattern and create a mock or dummy LlmFactory instance.
  Act: Call LlmRegistry.registerLlm with the unique pattern and the factory.
  Assert: Check that llmFactories contains the new pattern as key, and that the corresponding value is the factory instance passed in.
Validation:
  The assertion verifies that new LLM providers can be added to the registry, ensuring extensibility. This is critical to allow the dynamic registration of different Large Language Model factories.

Scenario 2: Overwriting an Existing Pattern with a New Factory

Details:
  TestName: overwriteExistingFactoryPattern
  Description: This test ensures that when registerLlm is called with a pattern that already exists in llmFactories, the factory associated with that pattern is replaced by the new factory.
Execution:
  Arrange: Use a pattern already present in llmFactories (e.g., "gemini-.*") and register a factory under that pattern. Prepare a different factory for the same pattern.
  Act: Call LlmRegistry.registerLlm again with the same pattern but with the new factory.
  Assert: Verify that llmFactories now maps the pattern to the new factory and not the previous one.
Validation:
  The assertion checks that pattern-to-factory associations are not immutable and can be updated. This is significant for modifying model behaviors or implementing hotfixes.

Scenario 3: Registering a Factory with an Empty String Pattern

Details:
  TestName: registerFactoryWithEmptyPattern
  Description: This scenario tests the registry’s behavior when registerLlm is called with an empty string pattern as the model name pattern.
Execution:
  Arrange: Create a mock or dummy LlmFactory instance.
  Act: Call LlmRegistry.registerLlm with an empty string pattern and the dummy factory.
  Assert: Check that llmFactories contains an entry with the empty string as the key and the provided factory as its value.
Validation:
  This confirms whether the registry accepts empty string patterns and how they are represented. Such an edge case could impact pattern matching logic elsewhere.

Scenario 4: Registering a Factory with a Null Pattern

Details:
  TestName: registerFactoryWithNullPattern
  Description: This test verifies how registerLlm handles null as the modelNamePattern argument, specifically whether it throws NullPointerException or accepts and stores it.
Execution:
  Arrange: Create a dummy LlmFactory instance.
  Act: Call LlmRegistry.registerLlm with null as the modelNamePattern and the dummy factory.
  Assert: Observe if a NullPointerException is thrown or if llmFactories contains a null key.
Validation:
  This probes the method’s robustness and null safety, which has implications for program stability and defensive coding.

Scenario 5: Registering a Factory with a Null Factory Argument

Details:
  TestName: registerNullFactory
  Description: This scenario checks behavior when registerLlm is called with a valid pattern but null as the factory argument.
Execution:
  Arrange: Use any non-empty string as the pattern.
  Act: Call LlmRegistry.registerLlm with that pattern and null as the factory.
  Assert: Verify whether llmFactories contains the pattern mapped to a null value, or whether an exception is thrown.
Validation:
  This ensures that the registry’s contract for non-null factories is clear. Allowing null factories could cause downstream failures when LLM creation is attempted.

Scenario 6: Concurrent Registration of Multiple Factories

Details:
  TestName: concurrentRegistrationOfFactories
  Description: This test validates the thread-safety of registerLlm by simultaneously registering multiple factories with different patterns from multiple threads.
Execution:
  Arrange: Prepare several unique model name patterns and corresponding dummy factories. Create multiple threads, each calling registerLlm with its own pattern and factory.
  Act: Start all threads concurrently and wait for completion.
  Assert: After all threads complete, verify that llmFactories contains all the registered patterns with the correct associated factories.
Validation:
  This assesses that the internal map remains consistent and accurate under concurrent modifications, leveraging ConcurrentHashMap for thread safety.

Scenario 7: Registering a Factory with a Regex Pattern Already Used by a Built-in Factory

Details:
  TestName: overrideBuiltInPattern
  Description: This scenario tests registering a new factory under a pattern already used in the static block initialization (such as "apigee/.*") and checks if the built-in mapping is correctly replaced.
Execution:
  Arrange: Prepare a new factory for a built-in pattern, such as "apigee/.*".
  Act: Call LlmRegistry.registerLlm with "apigee/.*" and the new factory.
  Assert: Check that llmFactories maps "apigee/.*" to the new factory instance, not the built-in one.
Validation:
  This proves the design allows clients to override default factory registrations, allowing flexibility and customization.

Scenario 8: Registering the Same Pattern Multiple Times With the Same Factory

Details:
  TestName: registerIdenticalPatternAndFactoryMultipleTimes
  Description: This test checks the behavior when registerLlm is called multiple times with the same pattern and factory instance.
Execution:
  Arrange: Use a specific pattern and the same factory instance.
  Act: Call LlmRegistry.registerLlm with the same pattern and factory twice or more in succession.
  Assert: Verify that llmFactories still contains exactly one entry for the pattern, mapped to the factory.
Validation:
  Confirms idempotency for repeated registrations of identical (pattern, factory) pairs, which is valuable for configuration code that may run multiple times.

Scenario 9: Registering a Factory with a Regex Pattern That Matches No Intended Model Names

Details:
  TestName: registerUnmatchablePattern
  Description: This scenario tests registration of a factory with a pattern that cannot match any realistic model name (e.g., a pattern like "$^" which matches nothing).
Execution:
  Arrange: Prepare the unmatchable regex pattern and a dummy factory.
  Act: Call LlmRegistry.registerLlm with this pattern and the dummy factory.
  Assert: Check that llmFactories contains the pattern with the factory.
Validation:
  Verifies that registration logic does not validate the usefulness or matchability of the pattern. This is important to note for debugging or cleaning up unused registrations.

Scenario 10: Registering or Overwriting a Factory While Instances Already Exist for Some Patterns

Details:
  TestName: registerFactoryWhenInstancesExist
  Description: This test examines what happens when registerLlm is called for a pattern that already has instances cached in the instances map (even though registerTestLlm explicitly clears such instances but registerLlm does not).
Execution:
  Arrange: Use the pattern to register and create some cached BaseLlm instances via getLlm using previously registered factories.
  Act: Call LlmRegistry.registerLlm with the pattern but a new factory.
  Assert: Check that llmFactories points to the new factory, but the existing cached instances remain unchanged in the instances map for existing model names.
Validation:
  Demonstrates the separation of the factories (llmFactories) from the cached instances, illustrating how existing cached instances are unaffected by factory re-registration, which might lead to subtle bugs or stale data unless handled.

Scenario 11: Registering a Factory with a Very Large Pattern String

Details:
  TestName: registerFactoryWithVeryLargePattern
  Description: This scenario ensures that registerLlm can handle extremely large regex pattern strings as keys.
Execution:
  Arrange: Create a very long string (e.g., thousands of characters) to use as modelNamePattern and a dummy factory.
  Act: Call LlmRegistry.registerLlm with the large pattern key and the factory.
  Assert: Verify that llmFactories contains the large pattern as a key mapped to the correct factory.
Validation:
  This test checks for any performance or resource management issues with large pattern strings, ensuring the system remains robust regardless of registration key size.

*/

// ********RoostGPT********

package com.google.adk.models;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.mockito.Mockito;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import org.junit.jupiter.api.*;

// Dummy implementation for BaseLlm to allow compilation and mocking
class LlmRegistryRegisterLlmTest {

}

interface LlmFactory {

	BaseLlm create(String modelName);

}

class LlmRegistryRegisterLlmTest {

	private static final Map<String, BaseLlm> instances = new ConcurrentHashMap<>();

	private static final Map<String, LlmFactory> llmFactories = new ConcurrentHashMap<>();

	private LlmRegistry() { }

	public static void registerLlm(String modelNamePattern, LlmFactory factory) {
		llmFactories.put(modelNamePattern, factory);
	}

	public static BaseLlm getLlm(String modelName) {
		return instances.computeIfAbsent(modelName, LlmRegistry::createLlm);
	}

	private static BaseLlm createLlm(String modelName) {
		for (Map.Entry<String, LlmFactory> entry : llmFactories.entrySet()) {
			if (modelName.matches(entry.getKey())) {
				return entry.getValue().create(modelName);
			}
		}
		throw new IllegalArgumentException("Unsupported model: " + modelName);
	}

	static void registerTestLlm(String modelNamePattern, LlmFactory factory) {
		llmFactories.put(modelNamePattern, factory);
		instances.keySet().removeIf(modelName -> modelName.matches(modelNamePattern));
	}

	// For test visibility, only for tests, resets (not part of production code in
	// reality)
	static void clearRegistryForTest() {
		llmFactories.clear();
		instances.clear();
	}

}

class LlmRegistryRegisterLlmTest {

	@BeforeEach
	void setUp() {
		LlmRegistry.clearRegistryForTest();
	}

	@AfterEach
	void tearDown() {
		LlmRegistry.clearRegistryForTest();
	}

	@Test
	@Tag("valid")
	public void testRegisterUniquePatternFactory() {
		String pattern = "gpt-.*";
		LlmFactory factory = Mockito.mock(LlmFactory.class);
		LlmRegistry.registerLlm(pattern, factory);
		Assertions.assertSame((LlmFactory) factory, (LlmFactory) getFactories().get(pattern),
				"Factory should be registered for unique pattern");
	}

	@Test
	@Tag("valid")
	public void testOverwriteExistingFactoryPattern() {
		String pattern = "gemini-.*";
		LlmFactory initialFactory = Mockito.mock(LlmFactory.class);
		LlmRegistry.registerLlm(pattern, initialFactory);
		LlmFactory newFactory = Mockito.mock(LlmFactory.class);
		LlmRegistry.registerLlm(pattern, newFactory);
		Assertions.assertSame((LlmFactory) newFactory, (LlmFactory) getFactories().get(pattern),
				"Factory should be overwritten for existing pattern");
	}

	@Test
	@Tag("boundary")
	public void testRegisterFactoryWithEmptyPattern() {
		String pattern = "";
		LlmFactory factory = Mockito.mock(LlmFactory.class);
		LlmRegistry.registerLlm(pattern, factory);
		Assertions.assertSame((LlmFactory) factory, (LlmFactory) getFactories().get(""),
				"Factory should be registered for empty pattern string");
	}

	@Test
    @Tag("invalid")
    public void testRegisterFactoryWithNullPattern() {
        LlmFactory factory = Mockito.mock(LlmFactory.class);
        // There was a Java compilation error: invalid method declaration; return type required.
        // This was likely because the method signature in interface/
class LlmRegistryRegisterLlmTest wrong in prior version.
        // Suggestion: Ensure business logic for registerLlm checks for null argument and throws NullPointerException.
        Assertions.assertThrows(NullPointerException.class, () -> {
            LlmRegistry.registerLlm(null, factory);
        }, "Registering with null pattern should throw NullPointerException");
    }

	@Test
	@Tag("invalid")
	public void testRegisterNullFactory() {
		String pattern = "llama-.*";
		// Business logic allows null factory registration; map will contain null value
		// for this pattern.
		Assertions.assertDoesNotThrow(() -> {
			LlmRegistry.registerLlm(pattern, null);
		}, "Registering with null factory should not throw");
		Assertions.assertNull((LlmFactory) getFactories().get(pattern),
				"Factory mapping should be null for this pattern");
	}

	@Test
	@Tag("integration")
	public void testConcurrentRegistrationOfFactories() throws InterruptedException {
		int threadCount = 10; // TODO: Change thread count as per real config if needed
		Thread[] threads = new Thread[threadCount];
		String[] patterns = new String[threadCount];
		LlmFactory[] factories = new LlmFactory[threadCount];
		for (int i = 0; i < threadCount; i++) {
			patterns[i] = "model-" + i;
			factories[i] = Mockito.mock(LlmFactory.class);
			final String finalPattern = patterns[i];
			final LlmFactory finalFactory = factories[i];
			threads[i] = new Thread(() -> LlmRegistry.registerLlm(finalPattern, finalFactory));
		}
		for (Thread t : threads) {
			t.start();
		}
		for (Thread t : threads) {
			t.join();
		}
		Map<String, LlmFactory> regFactories = getFactories();
		for (int i = 0; i < threadCount; i++) {
			Assertions.assertSame((LlmFactory) factories[i], (LlmFactory) regFactories.get(patterns[i]),
					"Factory should be correctly registered under concurrent access for pattern " + patterns[i]);
		}
	}

	@Test
	@Tag("valid")
	public void testOverrideBuiltInPattern() {
		String pattern = "apigee/.*";
		LlmFactory initialBuiltinFactory = Mockito.mock(LlmFactory.class);
		LlmRegistry.registerLlm(pattern, initialBuiltinFactory);
		LlmFactory overriddenFactory = Mockito.mock(LlmFactory.class);
		LlmRegistry.registerLlm(pattern, overriddenFactory);
		Assertions.assertSame((LlmFactory) overriddenFactory, (LlmFactory) getFactories().get(pattern),
				"Built-in factory should be replaced by new factory for the same pattern");
	}

	@Test
	@Tag("valid")
	public void testRegisterIdenticalPatternAndFactoryMultipleTimes() {
		String pattern = "bard-.*";
		LlmFactory factory = Mockito.mock(LlmFactory.class);
		LlmRegistry.registerLlm(pattern, factory);
		LlmRegistry.registerLlm(pattern, factory);
		Map<String, LlmFactory> regFactories = getFactories();
		Assertions.assertEquals(1,
				regFactories.entrySet()
					.stream()
					.filter(e -> e.getKey().equals(pattern) && e.getValue() == factory)
					.count(),
				"Registering same factory same pattern multiple times should not duplicate entries");
	}

	@Test
	@Tag("boundary")
	public void testRegisterUnmatchablePattern() {
		String unmatchablePattern = "$^";
		LlmFactory factory = Mockito.mock(LlmFactory.class);
		LlmRegistry.registerLlm(unmatchablePattern, factory);
		Assertions.assertSame((LlmFactory) factory, (LlmFactory) getFactories().get(unmatchablePattern),
				"Factory should be registered even if pattern matches no model names");
	}

	@Test
	@Tag("integration")
	public void testRegisterFactoryWhenInstancesExist() {
		String pattern = "cohere-.*";
		String modelName = "cohere-model-v1";
		LlmFactory firstFactory = Mockito.mock(LlmFactory.class);
		BaseLlm firstLlm = new BaseLlm();
		Mockito.when(firstFactory.create(modelName)).thenReturn(firstLlm);
		LlmRegistry.registerLlm(pattern, firstFactory);
		BaseLlm cachedLlm = LlmRegistry.getLlm(modelName);
		LlmFactory newFactory = Mockito.mock(LlmFactory.class);
		LlmRegistry.registerLlm(pattern, newFactory);
		// llmFactories should contain the new factory
		Assertions.assertSame((LlmFactory) newFactory, (LlmFactory) getFactories().get(pattern),
				"Factory should be replaced in registry");
		// Cached instance should be unchanged (not recreated)
		Assertions.assertSame((BaseLlm) cachedLlm, (BaseLlm) getInstances().get(modelName),
				"Existing cached instance should remain unchanged when factory is replaced");
	}

	@Test
	@Tag("boundary")
	public void testRegisterFactoryWithVeryLargePattern() {
		StringBuilder sb = new StringBuilder();
		for (int i = 0; i < 5000; i++)
			sb.append("x");
		String veryLargePattern = sb.toString();
		LlmFactory factory = Mockito.mock(LlmFactory.class);
		LlmRegistry.registerLlm(veryLargePattern, factory);
		Assertions.assertSame((LlmFactory) factory, (LlmFactory) getFactories().get(veryLargePattern),
				"Factory should be registered for very large pattern string");
	}

	// Helper methods using reflection to access static fields for tests
	@SuppressWarnings("unchecked")
	private static Map<String, LlmFactory> getFactories() {
		try {
			java.lang.reflect.Field field = LlmRegistry.class.getDeclaredField("llmFactories");
			field.setAccessible(true);
			return (Map<String, LlmFactory>) field.get(null);
		}
		catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

	@SuppressWarnings("unchecked")
	private static Map<String, BaseLlm> getInstances() {
		try {
			java.lang.reflect.Field field = LlmRegistry.class.getDeclaredField("instances");
			field.setAccessible(true);
			return (Map<String, BaseLlm>) field.get(null);
		}
		catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

}