/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test maven-adkjava-github using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=registerTestLlm_14ec6c33f6
ROOST_METHOD_SIG_HASH=registerTestLlm_b0e327d7c8

Scenario 1: Registering a new test LLM factory for a unique pattern

Details:
  TestName: registerFactoryWithUniquePatternClearsNoInstances
  Description: This test verifies that when registerTestLlm is called with a pattern that does not match any existing model names in the instances cache, the new factory is registered to llmFactories and no entries are removed from instances.

Execution:
  Arrange:
    - Prepare a modelNamePattern (e.g., "test-model-.*") that does not match any keys present in instances.
    - Provide a dummy implementation for LlmFactory.
    - Ensure instances contains only keys not matching the pattern.
  Act:
    - Call registerTestLlm with the pattern and factory.
  Assert:
    - llmFactories should contain the new pattern mapped to the new factory.
    - All previous entries in instances remain unchanged.

Validation:
    This assertion checks that the method correctly associates the pattern with the factory and does not unnecessarily remove unrelated cached models, ensuring precise test isolation without unwanted side-effects.

Scenario 2: Registering a new test LLM factory that matches existing cached instances

Details:
  TestName: registerFactoryMatchingExistingInstancesRemovesMatchingInstances
  Description: This test ensures that when registerTestLlm is called with a pattern matching keys already present in the instances cache, all such cached entries are removed while the new factory is registered.

Execution:
  Arrange:
    - Insert several entries into instances, including keys that match a test pattern (e.g., "test-model-1", "test-model-2" matching "test-model-.*").
    - Add other non-matching instances.
    - Create a dummy LlmFactory.
  Act:
    - Invoke registerTestLlm with "test-model-.*" and the factory.
  Assert:
    - All instances with keys matching "test-model-.*" have been removed from instances.
    - All other instances remain.
    - llmFactories maps the pattern to the new factory.

Validation:
    This verifies the core function of the method: to guarantee that new test registrations invalidate existing matching caches for proper isolation and reuse of correct factories.

Scenario 3: Overwriting an existing factory for a pattern

Details:
  TestName: overwriteExistingFactoryReplacesWithTestFactory
  Description: Verifies that calling registerTestLlm for a pattern already in llmFactories will replace the old factory with the new one.

Execution:
  Arrange:
    - Before the test, ensure llmFactories contains an entry for a pattern (e.g., "pattern1") mapped to some old factory.
    - Create a different LlmFactory.
  Act:
    - Invoke registerTestLlm with "pattern1" and the new factory.
  Assert:
    - llmFactories.get("pattern1") refers to the new factory.

Validation:
    This assertion confirms that test registrations can override production factories, allowing for controlled replacement for testing behaviors.

Scenario 4: Registering with a pattern that matches no instance and no previous factory

Details:
  TestName: registerNewPatternWhenNoPriorFactoryOrInstance
  Description: Checks the behavior when adding a test factory for a pattern that has neither cached instances nor an existing factory in the registry.

Execution:
  Arrange:
    - Pick a unique pattern not present in llmFactories or matching any model name in instances.
    - Set up a new dummy LlmFactory.
  Act:
    - Call registerTestLlm.
  Assert:
    - llmFactories includes the pattern-to-factory mapping.
    - No entries removed from instances.

Validation:
    This test ensures safe idempotent addition of new patterns and that unrelated caches are unaffected, guaranteeing registry integrity.

Scenario 5: Registering multiple times with the same pattern

Details:
  TestName: registerTestLlmCalledMultipleTimesWithSamePattern
  Description: Checks that calling registerTestLlm multiple times for the same pattern always replaces the factory and clears matching instances.

Execution:
  Arrange:
    - Add one or more instance(s) to instances with names matching the test pattern.
    - Register a first LlmFactory via registerTestLlm.
    - Add another instance matching the same pattern after the first registration.
  Act:
    - Call registerTestLlm again with the same pattern but a new factory.
  Assert:
    - Only the last factory is mapped for the pattern in llmFactories.
    - All instances matching the pattern are removed after each call.

Validation:
    This ensures the method's repeatability and guarantees that no stale factories or instance caches persist after repeated registrations.

Scenario 6: Registering with an empty regex pattern

Details:
  TestName: registerWithEmptyPatternClearsAllInstances
  Description: Validates the case when registerTestLlm is called with an empty string as the regex pattern. In regex, an empty string matches all strings, thus all instances should be removed.

Execution:
  Arrange:
    - Populate instances with several model names.
    - Set up a dummy factory.
  Act:
    - Call registerTestLlm with "" (empty string) as pattern.
  Assert:
    - All entries in instances are removed.
    - llmFactories maps "" to the new factory.

Validation:
    This test guards against accidental test pollution by ensuring a blank pattern wipes the cache and the mapping behaves as per regex logic.

Scenario 7: Registering with a null factory

Details:
  TestName: registerWithNullFactory
  Description: Determines the class behavior if a null value is supplied for the factory parameter (even though it is likely an error, the code above does not prohibit it).

Execution:
  Arrange:
    - Choose a new modelNamePattern.
    - Ensure no prior entries in llmFactories or matching instances.
  Act:
    - Invoke registerTestLlm with the new pattern and null for the factory.
  Assert:
    - llmFactories maps the pattern to null.

Validation:
    This checks defensive robustness, confirming the internal map can accept a null value for a factory and what impact this might have on later LLM creation attempts.

Scenario 8: Registering with a null modelNamePattern

Details:
  TestName: registerWithNullPatternThrowsOrAccepts
  Description: Evaluates system response when modelNamePattern is null. The expected result depends on system behavior (exception or acceptance). Since ConcurrentHashMap allows null values for neither keys nor values, this may throw a NullPointerException.

Execution:
  Arrange:
    - Create a dummy factory.
  Act:
    - Attempt to call registerTestLlm with null as pattern.
  Assert:
    - Either a NullPointerException is thrown, or llmFactories does not allow the mapping.

Validation:
    This test is important to catch invalid usages and enforce integrity of the factory registry for expected and well-formed inputs.

Scenario 9: Registering with a modelNamePattern that matches all possible model names (e.g., ".*")

Details:
  TestName: registerGlobalPatternClearsAllInstances
  Description: Verifies that using a global catch-all pattern causes all entries in instances to be removed for complete test isolation.

Execution:
  Arrange:
    - Populate instances with diverse model names.
    - Prepare a catch-all regex ".*".
    - Set up a dummy factory.
  Act:
    - Call registerTestLlm with pattern ".*".
  Assert:
    - instances is empty afterwards.
    - llmFactories maps ".*" to the supplied factory.

Validation:
    This is crucial for broad clean-up scenarios, e.g., global testing resets, ensuring no previous LLM instance remains cached.

Scenario 10: Registering while concurrent access occurs

Details:
  TestName: concurrentRegisterTestLlmRemainsThreadSafe
  Description: Tests for thread safety by calling registerTestLlm from multiple threads with potentially overlapping or different patterns, confirming no data races or inconsistent states in llmFactories or instances.

Execution:
  Arrange:
    - Start with several model names in instances.
    - Prepare multiple factories and patterns, some overlapping, some distinct.
  Act:
    - In multiple threads, simultaneously call registerTestLlm with different patterns and factories.
  Assert:
    - After all threads complete, llmFactories and instances maps are in a valid, consistent state (no duplicate or orphaned entries, correct mappings).

Validation:
    This test is significant for ensuring the integrity of the central registry under parallel operations, reflecting real-world system loads.

Scenario 11: Registering a factory that replaces a default-production mapping

Details:
  TestName: registerTestFactoryOverridesDefaultFactory
  Description: Ensures that if a pattern corresponds to a factory already added by static initialization (e.g., for "gemini-.*"), calling registerTestLlm removes cached instances and replaces the factory for testing purposes.

Execution:
  Arrange:
    - Ensure instances contains models matching "gemini-.*".
    - Confirm llmFactories has the default mapping for "gemini-.*".
    - Set up a test LlmFactory.
  Act:
    - Call registerTestLlm with "gemini-.*" and test factory.
  Assert:
    - llmFactories maps "gemini-.*" to the test factory (not the default).
    - All instances with model names matching "gemini-.*" are removed.

Validation:
    This ensures that test logic can override production defaults, a vital feature for comprehensive and isolated test scenarios.

Scenario 12: Registering with a factory that is already mapped (same instance)

Details:
  TestName: registerSameFactoryInstanceIsIdempotent
  Description: Verifies that providing the same factory object for the same pattern does not alter the registry state or remove unrelated instances unless they match the pattern.

Execution:
  Arrange:
    - Add a pattern-factory mapping to llmFactories.
    - Add entries to instances, some matching, some not matching.
  Act:
    - Call registerTestLlm again with the same pattern and same factory instance.
  Assert:
    - llmFactories and instances reflect only the effects on matching keys; the rest remain unchanged.

Validation:
    Assures that repeated registrations with the same parameters are safe and do not cause side effects beyond what is intended by the specification.

Scenario 13: Registering with a pattern that contains regex special characters

Details:
  TestName: registerPatternWithSpecialRegexCharacters
  Description: Validates the registry’s correct handling of regex patterns that include special characters (e.g., "prod-model\\d{3}") and that instance clearing and factory mapping occur as expected.

Execution:
  Arrange:
    - Add instances with keys such as "prod-model123" or "prod-model000" that match the pattern.
    - Set up an appropriate pattern and factory.
  Act:
    - Call registerTestLlm with the special regex pattern.
  Assert:
    - All instances whose keys match the regex are removed.
    - The factory is correctly mapped in llmFactories.

Validation:
    This ensures robust handling of diverse regex patterns, reducing the risk of bugs from misinterpretation or improper regex processing.


*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.mockito.Mockito;

class LlmRegistryRegisterTestLlmTest {

	// Dummy implementation for BaseLlm and LlmFactory, as required for tests.
	static class DummyLlm extends BaseLlm {

	}

	static class DummyFactory implements LlmFactory {

		@Override
		public BaseLlm create(String modelName) {
			return new DummyLlm();
		}

	}

	@BeforeEach
	void setUp() {
		// Clear the static maps before each test
		LlmRegistry.llmFactories.clear();
		LlmRegistry.instances.clear();
	}

	@Test
	@Tag("valid")
	public void testRegisterFactoryWithUniquePatternClearsNoInstances() {
		// Arrange
		LlmRegistry.instances.put("existing-model", new DummyLlm());
		String pattern = "test-model-.*";
		LlmFactory factory = new DummyFactory();
		// Act
		LlmRegistry.registerTestLlm(pattern, factory);
		// Assert
		assertSame(factory, LlmRegistry.llmFactories.get(pattern));
		assertTrue(LlmRegistry.instances.containsKey("existing-model"));
	}

	@Test
	@Tag("valid")
	public void testRegisterFactoryMatchingExistingInstancesRemovesMatchingInstances() {
		// Arrange
		LlmRegistry.instances.put("test-model-1", new DummyLlm());
		LlmRegistry.instances.put("test-model-2", new DummyLlm());
		LlmRegistry.instances.put("other-model", new DummyLlm());
		String pattern = "test-model-.*";
		LlmFactory factory = new DummyFactory();
		// Act
		LlmRegistry.registerTestLlm(pattern, factory);
		// Assert
		assertSame(factory, LlmRegistry.llmFactories.get(pattern));
		assertFalse(LlmRegistry.instances.containsKey("test-model-1"));
		assertFalse(LlmRegistry.instances.containsKey("test-model-2"));
		assertTrue(LlmRegistry.instances.containsKey("other-model"));
	}

	@Test
	@Tag("valid")
	public void testOverwriteExistingFactoryReplacesWithTestFactory() {
		// Arrange
		String pattern = "pattern1";
		LlmFactory oldFactory = Mockito.mock(LlmFactory.class);
		LlmFactory newFactory = new DummyFactory();
		LlmRegistry.llmFactories.put(pattern, oldFactory);
		// Act
		LlmRegistry.registerTestLlm(pattern, newFactory);
		// Assert
		assertSame(newFactory, LlmRegistry.llmFactories.get(pattern));
	}

	@Test
	@Tag("valid")
	public void testRegisterNewPatternWhenNoPriorFactoryOrInstance() {
		// Arrange
		String pattern = "unique-pattern-.*"; // TODO: Change to actual pattern if needed
		LlmFactory factory = new DummyFactory();
		// Act
		LlmRegistry.registerTestLlm(pattern, factory);
		// Assert
		assertSame(factory, LlmRegistry.llmFactories.get(pattern));
		assertEquals(0, LlmRegistry.instances.size());
	}

	@Test
	@Tag("valid")
	public void testRegisterTestLlmCalledMultipleTimesWithSamePattern() {
		// Arrange
		String pattern = "multi-model-.*";
		LlmRegistry.instances.put("multi-model-1", new DummyLlm());
		LlmFactory factory1 = new DummyFactory();
		LlmRegistry.registerTestLlm(pattern, factory1);
		LlmRegistry.instances.put("multi-model-2", new DummyLlm());
		LlmFactory factory2 = new DummyFactory();
		// Act
		LlmRegistry.registerTestLlm(pattern, factory2);
		// Assert
		assertSame(factory2, LlmRegistry.llmFactories.get(pattern));
		assertFalse(LlmRegistry.instances.containsKey("multi-model-1"));
		assertFalse(LlmRegistry.instances.containsKey("multi-model-2"));
	}

	@Test
	@Tag("boundary")
	public void testRegisterWithEmptyPatternClearsAllInstances() {
		// Arrange
		LlmRegistry.instances.put("modelA", new DummyLlm());
		LlmRegistry.instances.put("modelB", new DummyLlm());
		String pattern = "";
		LlmFactory factory = new DummyFactory();
		// Act
		LlmRegistry.registerTestLlm(pattern, factory);
		// Assert
		assertEquals(0, LlmRegistry.instances.size());
		assertSame(factory, LlmRegistry.llmFactories.get(pattern));
	}

	@Test
	@Tag("invalid")
	public void testRegisterWithNullFactory() {
		// Arrange
		String pattern = "null-factory-pattern";
		// Act
		LlmRegistry.registerTestLlm(pattern, null);
		// Assert
		assertNull(LlmRegistry.llmFactories.get(pattern));
	}

	@Test
	@Tag("invalid")
	public void testRegisterWithNullPatternThrowsOrAccepts() {
		// Arrange
		LlmFactory factory = new DummyFactory();
		// Act & Assert
		assertThrows(NullPointerException.class, () -> LlmRegistry.registerTestLlm(null, factory));
	}

	@Test
	@Tag("boundary")
	public void testRegisterGlobalPatternClearsAllInstances() {
		// Arrange
		LlmRegistry.instances.put("modelX", new DummyLlm());
		LlmRegistry.instances.put("another-model", new DummyLlm());
		String pattern = ".*";
		LlmFactory factory = new DummyFactory();
		// Act
		LlmRegistry.registerTestLlm(pattern, factory);
		// Assert
		assertEquals(0, LlmRegistry.instances.size());
		assertSame(factory, LlmRegistry.llmFactories.get(pattern));
	}

	@Test
	@Tag("integration")
	public void testConcurrentRegisterTestLlmRemainsThreadSafe() throws InterruptedException {
		// Arrange
		LlmRegistry.instances.put("thread-model-1", new DummyLlm());
		LlmRegistry.instances.put("thread-model-2", new DummyLlm());
		LlmRegistry.instances.put("keep-model", new DummyLlm());
		LlmFactory factoryA = new DummyFactory();
		LlmFactory factoryB = new DummyFactory();
		String patternA = "thread-model-.*";
		String patternB = "keep-model";
		Thread t1 = new Thread(() -> LlmRegistry.registerTestLlm(patternA, factoryA));
		Thread t2 = new Thread(() -> LlmRegistry.registerTestLlm(patternB, factoryB));
		// Act
		t1.start();
		t2.start();
		t1.join();
		t2.join();
		// Assert
		assertSame(factoryA, LlmRegistry.llmFactories.get(patternA));
		assertSame(factoryB, LlmRegistry.llmFactories.get(patternB));
		assertFalse(LlmRegistry.instances.containsKey("thread-model-1"));
		assertFalse(LlmRegistry.instances.containsKey("thread-model-2"));
		assertTrue(LlmRegistry.instances.containsKey("keep-model") || !LlmRegistry.instances.containsKey("keep-model"));
		// The last assertion depends on thread interleaving, so validity is confirmed by
		// no exceptions
		// and map consistency.
	}

	@Test
	@Tag("integration")
	public void testRegisterTestFactoryOverridesDefaultFactory() {
		// Arrange
		String pattern = "gemini-.*";
		LlmRegistry.llmFactories.put(pattern, Mockito.mock(LlmFactory.class)); // Simulate
																				// default
		LlmRegistry.instances.put("gemini-abc", new DummyLlm());
		LlmRegistry.instances.put("gemini-xyz", new DummyLlm());
		LlmFactory testFactory = new DummyFactory();
		// Act
		LlmRegistry.registerTestLlm(pattern, testFactory);
		// Assert
		assertSame(testFactory, LlmRegistry.llmFactories.get(pattern));
		assertFalse(LlmRegistry.instances.containsKey("gemini-abc"));
		assertFalse(LlmRegistry.instances.containsKey("gemini-xyz"));
	}

	@Test
	@Tag("valid")
	public void testRegisterSameFactoryInstanceIsIdempotent() {
		// Arrange
		String pattern = "idempotent-.*";
		DummyFactory factory = new DummyFactory();
		LlmRegistry.llmFactories.put(pattern, factory);
		LlmRegistry.instances.put("idempotent-model-1", new DummyLlm());
		LlmRegistry.instances.put("other-model", new DummyLlm());
		// Act
		LlmRegistry.registerTestLlm(pattern, factory);
		// Assert
		assertSame(factory, LlmRegistry.llmFactories.get(pattern));
		assertFalse(LlmRegistry.instances.containsKey("idempotent-model-1"));
		assertTrue(LlmRegistry.instances.containsKey("other-model"));
	}

	@Test
	@Tag("boundary")
	public void testRegisterPatternWithSpecialRegexCharacters() {
		// Arrange
		String pattern = "prod-model\\d{3}";
		LlmRegistry.instances.put("prod-model123", new DummyLlm());
		LlmRegistry.instances.put("prod-model000", new DummyLlm());
		LlmRegistry.instances.put("prod-model", new DummyLlm());
		LlmFactory factory = new DummyFactory();
		// Act
		LlmRegistry.registerTestLlm(pattern, factory);
		// Assert
		assertFalse(LlmRegistry.instances.containsKey("prod-model123"));
		assertFalse(LlmRegistry.instances.containsKey("prod-model000"));
		assertTrue(LlmRegistry.instances.containsKey("prod-model"));
		assertSame(factory, LlmRegistry.llmFactories.get(pattern));
	}

}
