/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-repo using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=registerTestLlm_14ec6c33f6
ROOST_METHOD_SIG_HASH=registerTestLlm_b0e327d7c8

Scenario 1: Register a New Test LLM Factory with a Simple Pattern

Details:
  TestName: registerNewTestLlmFactoryWithSimplePattern
  Description: Verify that a new LLM factory can be registered with a simple regex pattern that does not match any existing cached instances. This tests the basic registration functionality without cache invalidation.

Execution:
  Arrange: Create a mock LlmFactory that returns a mock BaseLlm instance. Define a unique model name pattern (e.g., "test-model-.*") that does not match any existing cached instances.
  Act: Call registerTestLlm with the unique pattern and the mock factory.
  Assert: Verify that the factory is added to llmFactories by subsequently calling getLlm with a matching model name and confirming the mock factory is used.

Validation:
  The assertion verifies that the factory registration mechanism works correctly for new patterns. This is significant because it ensures test environments can inject custom LLM implementations without affecting production configurations.

---

Scenario 2: Register Test LLM Factory That Overrides Existing Factory

Details:
  TestName: registerTestLlmFactoryOverridesExistingFactory
  Description: Verify that registering a test LLM factory with a pattern that already exists in llmFactories will override the previous factory entry.

Execution:
  Arrange: First register a factory with a specific pattern (e.g., "override-test-.*"). Then create a different mock factory to replace it.
  Act: Call registerTestLlm with the same pattern but the new mock factory.
  Assert: Verify that when getLlm is called with a matching model name, the new factory is used instead of the original one.

Validation:
  This assertion confirms that the ConcurrentHashMap's put behavior correctly replaces existing entries. This is critical for test isolation where tests may need to override default or previously registered factories.

---

Scenario 3: Clear Cached Instances Matching the Registered Pattern

Details:
  TestName: clearCachedInstancesMatchingRegisteredPattern
  Description: Verify that when a test LLM factory is registered, any cached instances in the instances map that match the pattern are removed to ensure test isolation.

Execution:
  Arrange: First, call getLlm with a model name (e.g., "cache-test-model-1") to populate the instances cache. Ensure the pattern "cache-test-.*" would match this cached instance.
  Act: Call registerTestLlm with the pattern "cache-test-.*" and a new mock factory.
  Assert: Verify that subsequent calls to getLlm with "cache-test-model-1" use the new factory rather than returning the previously cached instance.

Validation:
  This validates the cache invalidation logic that removes matching instances. This is essential for test isolation, ensuring that tests do not inadvertently use stale cached LLM instances from previous test runs or production code.

---

Scenario 4: Register Test LLM with Pattern Matching Multiple Cached Instances

Details:
  TestName: registerTestLlmClearsMultipleCachedInstances
  Description: Verify that when a test LLM factory is registered with a broad pattern, all cached instances matching that pattern are removed from the cache.

Execution:
  Arrange: Populate the instances cache with multiple model names that match a common pattern (e.g., "multi-cache-a", "multi-cache-b", "multi-cache-c" all matching "multi-cache-.*"). Also add an instance that does not match (e.g., "other-model").
  Act: Call registerTestLlm with the pattern "multi-cache-.*" and a mock factory.
  Assert: Verify that all matching instances are removed from cache while the non-matching instance ("other-model") remains cached.

Validation:
  This confirms that the removeIf operation correctly identifies and removes all matching entries while preserving non-matching ones. This is important for selective cache invalidation in complex test scenarios.

---

Scenario 5: Register Test LLM with Pattern That Matches No Cached Instances

Details:
  TestName: registerTestLlmWithNoMatchingCachedInstances
  Description: Verify that registering a test LLM factory with a pattern that matches no existing cached instances does not cause errors and the factory is still registered correctly.

Execution:
  Arrange: Ensure the instances cache contains entries that do not match the pattern to be registered (e.g., cache contains "existing-model" but pattern is "non-matching-.*").
  Act: Call registerTestLlm with the pattern "non-matching-.*" and a mock factory.
  Assert: Verify that the factory is registered and existing cached instances remain unchanged.

Validation:
  This validates that the method handles the case where no cache invalidation is needed gracefully. The removeIf operation should complete without errors even when no elements match the predicate.

---

Scenario 6: Register Test LLM with Empty Pattern String

Details:
  TestName: registerTestLlmWithEmptyPatternString
  Description: Verify the behavior when an empty string is provided as the model name pattern. An empty regex pattern has specific matching behavior that should be understood.

Execution:
  Arrange: Create a mock factory and prepare an empty string as the pattern.
  Act: Call registerTestLlm with an empty string pattern and the mock factory.
  Assert: Verify that the factory is registered with the empty string key and observe the matching behavior when getLlm is called.

Validation:
  This tests an edge case where the pattern is empty. Understanding this behavior is important for preventing unexpected matches or errors in test configurations.

---

Scenario 7: Register Test LLM with Exact Match Pattern (No Regex)

Details:
  TestName: registerTestLlmWithExactMatchPattern
  Description: Verify that a pattern without regex special characters works as an exact match for model names.

Execution:
  Arrange: Create a mock factory and use a literal string pattern (e.g., "exact-model-name") without regex metacharacters.
  Act: Call registerTestLlm with the literal pattern and the mock factory.
  Assert: Verify that only the exact model name matches and similar names (e.g., "exact-model-name-extended") do not use this factory.

Validation:
  This confirms that literal patterns work correctly for exact matching scenarios. This is useful when tests need to mock a specific model without affecting similar model names.

---

Scenario 8: Register Test LLM with Complex Regex Pattern

Details:
  TestName: registerTestLlmWithComplexRegexPattern
  Description: Verify that complex regex patterns with multiple metacharacters are correctly used for both factory registration and cache invalidation.

Execution:
  Arrange: Create cached instances with names like "model-v1.0", "model-v2.5", "model-v10.0". Create a mock factory and a complex pattern like "model-v\\d+\\.\\d+".
  Act: Call registerTestLlm with the complex regex pattern and the mock factory.
  Assert: Verify that all matching cached instances are cleared and the factory is correctly registered.

Validation:
  This validates that the regex matching works correctly for sophisticated patterns. This is important for test scenarios that need precise control over which models are mocked.

---

Scenario 9: Register Test LLM with Null Factory

Details:
  TestName: registerTestLlmWithNullFactory
  Description: Verify the behavior when a null factory is provided to the registerTestLlm method.

Execution:
  Arrange: Prepare a valid pattern string and a null reference for the factory parameter.
  Act: Call registerTestLlm with the valid pattern and null factory.
  Assert: Observe whether a NullPointerException is thrown or if null is stored in the map, and verify subsequent behavior when getLlm is called with a matching model name.

Validation:
  This tests error handling for invalid input. Understanding this behavior helps ensure robust test setup and prevents cryptic errors during test execution.

---

Scenario 10: Concurrent Registration and Cache Access

Details:
  TestName: concurrentRegistrationAndCacheAccess
  Description: Verify that registerTestLlm operates correctly in a concurrent environment where multiple threads may be registering factories and accessing the cache simultaneously.

Execution:
  Arrange: Set up multiple threads that simultaneously call registerTestLlm with different patterns and getLlm with various model names.
  Act: Execute all threads concurrently and allow them to complete.
  Assert: Verify that no ConcurrentModificationException occurs and that the final state of llmFactories and instances is consistent.

Validation:
  This validates the thread-safety of the registration and cache invalidation operations. Since both maps are ConcurrentHashMap, the operations should be thread-safe, which is critical for parallel test execution.

*/

// ********RoostGPT********

package com.google.adk.models;

import static com.google.common.truth.Truth.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.lang.reflect.Field;
import java.util.Map;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class LlmRegistryRegisterTestLlmTest {

  @BeforeEach
  void setUp() throws Exception {
    // Clear the static maps before each test for isolation
    clearStaticMaps();
  }

  private void clearStaticMaps() throws Exception {
    Field instancesField = LlmRegistry.class.getDeclaredField("instances");
    instancesField.setAccessible(true);
    ((Map<?, ?>) instancesField.get(null)).clear();
    Field factoriesField = LlmRegistry.class.getDeclaredField("llmFactories");
    factoriesField.setAccessible(true);
    ((Map<?, ?>) factoriesField.get(null)).clear();
  }

  @SuppressWarnings("unchecked")
  private Map<String, BaseLlm> getInstancesMap() throws Exception {
    Field instancesField = LlmRegistry.class.getDeclaredField("instances");
    instancesField.setAccessible(true);
    return (Map<String, BaseLlm>) instancesField.get(null);
  }

  @SuppressWarnings("unchecked")
  private Map<String, LlmRegistry.LlmFactory> getFactoriesMap() throws Exception {
    Field factoriesField = LlmRegistry.class.getDeclaredField("llmFactories");
    factoriesField.setAccessible(true);
    return (Map<String, LlmRegistry.LlmFactory>) factoriesField.get(null);
  }

  @Test
  @Tag("valid")
  void registerNewTestLlmFactoryWithSimplePattern() throws Exception {
    // Arrange
    BaseLlm mockLlm = mock(BaseLlm.class);
    LlmRegistry.LlmFactory mockFactory = mock(LlmRegistry.LlmFactory.class);
    when(mockFactory.create("test-model-123")).thenReturn(mockLlm);
    // Act
    LlmRegistry.registerTestLlm("test-model-.*", mockFactory);
    // Assert
    Map<String, LlmRegistry.LlmFactory> factories = getFactoriesMap();
    assertThat(factories).containsKey("test-model-.*");

    BaseLlm result = LlmRegistry.getLlm("test-model-123");
    assertThat(result).isEqualTo(mockLlm);
  }

  @Test
  @Tag("valid")
  void registerTestLlmFactoryOverridesExistingFactory() throws Exception {
    // Arrange
    BaseLlm originalMockLlm = mock(BaseLlm.class);
    LlmRegistry.LlmFactory originalFactory = mock(LlmRegistry.LlmFactory.class);
    when(originalFactory.create("override-test-model")).thenReturn(originalMockLlm);
    LlmRegistry.registerTestLlm("override-test-.*", originalFactory);
    BaseLlm newMockLlm = mock(BaseLlm.class);
    LlmRegistry.LlmFactory newFactory = mock(LlmRegistry.LlmFactory.class);
    when(newFactory.create("override-test-model")).thenReturn(newMockLlm);
    // Act
    LlmRegistry.registerTestLlm("override-test-.*", newFactory);
    // Assert
    BaseLlm result = LlmRegistry.getLlm("override-test-model");
    assertThat(result).isEqualTo(newMockLlm);
  }

  @Test
  @Tag("valid")
  void clearCachedInstancesMatchingRegisteredPattern() throws Exception {
    // Arrange
    BaseLlm originalMockLlm = mock(BaseLlm.class);
    LlmRegistry.LlmFactory originalFactory = mock(LlmRegistry.LlmFactory.class);
    when(originalFactory.create("cache-test-model-1")).thenReturn(originalMockLlm);
    LlmRegistry.registerLlm("cache-test-.*", originalFactory);

    // Populate cache
    BaseLlm cachedInstance = LlmRegistry.getLlm("cache-test-model-1");
    assertThat(cachedInstance).isEqualTo(originalMockLlm);
    BaseLlm newMockLlm = mock(BaseLlm.class);
    LlmRegistry.LlmFactory newFactory = mock(LlmRegistry.LlmFactory.class);
    when(newFactory.create("cache-test-model-1")).thenReturn(newMockLlm);
    // Act
    LlmRegistry.registerTestLlm("cache-test-.*", newFactory);
    // Assert
    BaseLlm result = LlmRegistry.getLlm("cache-test-model-1");
    assertThat(result).isEqualTo(newMockLlm);
  }

  @Test
  @Tag("valid")
  void registerTestLlmClearsMultipleCachedInstances() throws Exception {
    // Arrange
    BaseLlm mockLlmA = mock(BaseLlm.class);
    BaseLlm mockLlmB = mock(BaseLlm.class);
    BaseLlm mockLlmC = mock(BaseLlm.class);
    BaseLlm mockLlmOther = mock(BaseLlm.class);
    LlmRegistry.LlmFactory multiFactory = mock(LlmRegistry.LlmFactory.class);
    when(multiFactory.create("multi-cache-a")).thenReturn(mockLlmA);
    when(multiFactory.create("multi-cache-b")).thenReturn(mockLlmB);
    when(multiFactory.create("multi-cache-c")).thenReturn(mockLlmC);
    LlmRegistry.LlmFactory otherFactory = mock(LlmRegistry.LlmFactory.class);
    when(otherFactory.create("other-model")).thenReturn(mockLlmOther);
    LlmRegistry.registerLlm("multi-cache-.*", multiFactory);
    LlmRegistry.registerLlm("other-model", otherFactory);
    // Populate cache
    LlmRegistry.getLlm("multi-cache-a");
    LlmRegistry.getLlm("multi-cache-b");
    LlmRegistry.getLlm("multi-cache-c");
    LlmRegistry.getLlm("other-model");
    Map<String, BaseLlm> instances = getInstancesMap();
    assertThat(instances).hasSize(4);
    BaseLlm newMockLlm = mock(BaseLlm.class);
    LlmRegistry.LlmFactory newFactory = mock(LlmRegistry.LlmFactory.class);
    when(newFactory.create("multi-cache-a")).thenReturn(newMockLlm);
    // Act
    LlmRegistry.registerTestLlm("multi-cache-.*", newFactory);
    // Assert
    assertThat(instances).hasSize(1);
    assertThat(instances).containsKey("other-model");
    assertThat(instances).doesNotContainKey("multi-cache-a");
    assertThat(instances).doesNotContainKey("multi-cache-b");
    assertThat(instances).doesNotContainKey("multi-cache-c");
  }

  @Test
  @Tag("valid")
  void registerTestLlmWithNoMatchingCachedInstances() throws Exception {
    // Arrange
    BaseLlm existingMockLlm = mock(BaseLlm.class);
    LlmRegistry.LlmFactory existingFactory = mock(LlmRegistry.LlmFactory.class);
    when(existingFactory.create("existing-model")).thenReturn(existingMockLlm);
    LlmRegistry.registerLlm("existing-model", existingFactory);
    LlmRegistry.getLlm("existing-model");
    Map<String, BaseLlm> instances = getInstancesMap();
    assertThat(instances).hasSize(1);
    BaseLlm newMockLlm = mock(BaseLlm.class);
    LlmRegistry.LlmFactory newFactory = mock(LlmRegistry.LlmFactory.class);
    when(newFactory.create("non-matching-test")).thenReturn(newMockLlm);
    // Act
    LlmRegistry.registerTestLlm("non-matching-.*", newFactory);
    // Assert
    assertThat(instances).hasSize(1);
    assertThat(instances).containsKey("existing-model");

    Map<String, LlmRegistry.LlmFactory> factories = getFactoriesMap();
    assertThat(factories).containsKey("non-matching-.*");
  }

  @Test
  @Tag("boundary")
  void registerTestLlmWithEmptyPatternString() throws Exception {
    // Arrange
    BaseLlm mockLlm = mock(BaseLlm.class);
    LlmRegistry.LlmFactory mockFactory = mock(LlmRegistry.LlmFactory.class);
    when(mockFactory.create("")).thenReturn(mockLlm);
    // Act
    LlmRegistry.registerTestLlm("", mockFactory);
    // Assert
    Map<String, LlmRegistry.LlmFactory> factories = getFactoriesMap();
    assertThat(factories).containsKey("");
  }

  @Test
  @Tag("valid")
  void registerTestLlmWithExactMatchPattern() throws Exception {
    // Arrange
    BaseLlm exactMockLlm = mock(BaseLlm.class);
    LlmRegistry.LlmFactory exactFactory = mock(LlmRegistry.LlmFactory.class);
    when(exactFactory.create("exact-model-name")).thenReturn(exactMockLlm);
    // Act
    LlmRegistry.registerTestLlm("exact-model-name", exactFactory);
    // Assert
    BaseLlm result = LlmRegistry.getLlm("exact-model-name");
    assertThat(result).isEqualTo(exactMockLlm);
    // Verify that extended name does not match
    assertThrows(
        IllegalArgumentException.class,
        () -> {
          LlmRegistry.getLlm("exact-model-name-extended");
        });
  }

  @Test
  @Tag("valid")
  void registerTestLlmWithComplexRegexPattern() throws Exception {
    // Arrange
    BaseLlm mockLlmV1 = mock(BaseLlm.class);
    BaseLlm mockLlmV2 = mock(BaseLlm.class);
    BaseLlm mockLlmV10 = mock(BaseLlm.class);
    LlmRegistry.LlmFactory originalFactory = mock(LlmRegistry.LlmFactory.class);
    when(originalFactory.create("model-v1.0")).thenReturn(mockLlmV1);
    when(originalFactory.create("model-v2.5")).thenReturn(mockLlmV2);
    when(originalFactory.create("model-v10.0")).thenReturn(mockLlmV10);
    LlmRegistry.registerLlm("model-v\\d+\\.\\d+", originalFactory);
    // Populate cache
    LlmRegistry.getLlm("model-v1.0");
    LlmRegistry.getLlm("model-v2.5");
    LlmRegistry.getLlm("model-v10.0");
    Map<String, BaseLlm> instances = getInstancesMap();
    assertThat(instances).hasSize(3);
    BaseLlm newMockLlm = mock(BaseLlm.class);
    LlmRegistry.LlmFactory newFactory = mock(LlmRegistry.LlmFactory.class);
    when(newFactory.create("model-v1.0")).thenReturn(newMockLlm);
    // Act
    LlmRegistry.registerTestLlm("model-v\\d+\\.\\d+", newFactory);
    // Assert
    assertThat(instances).isEmpty();

    Map<String, LlmRegistry.LlmFactory> factories = getFactoriesMap();
    assertThat(factories).containsKey("model-v\\d+\\.\\d+");
  }

  @Test
  @Tag("invalid")
  void registerTestLlmWithNullFactory() throws Exception {
    // Arrange
    String validPattern = "null-factory-test-.*";
    // Act & Assert
    // ConcurrentHashMap does not allow null values, so this should throw
    // NullPointerException
    assertThrows(
        NullPointerException.class,
        () -> {
          LlmRegistry.registerTestLlm(validPattern, null);
        });
  }

  @Test
  @Tag("integration")
  void concurrentRegistrationAndCacheAccess() throws Exception {
    // Arrange
    int threadCount = 10;
    ExecutorService executor = Executors.newFixedThreadPool(threadCount);
    CountDownLatch startLatch = new CountDownLatch(1);
    CountDownLatch doneLatch = new CountDownLatch(threadCount);
    // Pre-register some factories
    for (int i = 0; i < 5; i++) {
      final int index = i;
      BaseLlm mockLlm = mock(BaseLlm.class);
      LlmRegistry.LlmFactory factory = mock(LlmRegistry.LlmFactory.class);
      when(factory.create("concurrent-model-" + index)).thenReturn(mockLlm);
      LlmRegistry.registerLlm("concurrent-model-" + index, factory);
    }
    // Act
    for (int i = 0; i < threadCount; i++) {
      final int threadIndex = i;
      executor.submit(
          () -> {
            try {
              startLatch.await();

              // Some threads register new factories
              if (threadIndex % 2 == 0) {
                BaseLlm mockLlm = mock(BaseLlm.class);
                LlmRegistry.LlmFactory factory = mock(LlmRegistry.LlmFactory.class);
                when(factory.create("thread-model-" + threadIndex)).thenReturn(mockLlm);
                LlmRegistry.registerTestLlm("thread-model-" + threadIndex, factory);
              }

              // Some threads access the cache
              if (threadIndex < 5) {
                try {
                  LlmRegistry.getLlm("concurrent-model-" + threadIndex);
                } catch (IllegalArgumentException e) {
                  // Expected if factory was cleared
                }
              }
            } catch (InterruptedException e) {
              Thread.currentThread().interrupt();
            } finally {
              doneLatch.countDown();
            }
          });
    }
    startLatch.countDown();

    // Assert
    boolean completed = doneLatch.await(10, TimeUnit.SECONDS);
    assertThat(completed).isTrue();

    executor.shutdown();
    executor.awaitTermination(5, TimeUnit.SECONDS);
    // Verify no exceptions occurred and maps are in consistent state
    Map<String, LlmRegistry.LlmFactory> factories = getFactoriesMap();
    assertThat(factories).isNotNull();

    Map<String, BaseLlm> instances = getInstancesMap();
    assertThat(instances).isNotNull();
  }
}
