/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-repo using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=getLlm_7f9a36d638
ROOST_METHOD_SIG_HASH=getLlm_66c37a084b

Scenario 1: Retrieve LLM Instance for Valid Gemini Model Name

Details:
  TestName: getLlmForValidGeminiModelName
  Description: Verify that the getLlm method returns a valid BaseLlm instance when provided with a model name that matches the Gemini pattern (e.g., "gemini-1.5-pro"). This tests the default factory registration for Gemini models.

Execution:
  Arrange: Prepare a valid Gemini model name string such as "gemini-1.5-pro".
  Act: Call LlmRegistry.getLlm("gemini-1.5-pro").
  Assert: Verify that the returned object is not null and is an instance of BaseLlm.

Validation:
  The assertion confirms that the registry correctly matches the model name against the "gemini-.*" pattern and uses the registered factory to create a Gemini instance. This is critical for ensuring that the default Gemini model support works as expected in the application.

---

Scenario 2: Retrieve LLM Instance for Valid Apigee Model Name

Details:
  TestName: getLlmForValidApigeeModelName
  Description: Verify that the getLlm method returns a valid BaseLlm instance when provided with a model name that matches the Apigee pattern (e.g., "apigee/my-model"). This tests the default factory registration for Apigee models.

Execution:
  Arrange: Prepare a valid Apigee model name string such as "apigee/custom-model".
  Act: Call LlmRegistry.getLlm("apigee/custom-model").
  Assert: Verify that the returned object is not null and is an instance of BaseLlm.

Validation:
  The assertion confirms that the registry correctly matches the model name against the "apigee/.*" pattern and creates an ApigeeLlm instance. This validates the multi-provider support in the registry.

---

Scenario 3: Retrieve Cached LLM Instance on Subsequent Calls

Details:
  TestName: getLlmReturnsCachedInstanceOnSubsequentCalls
  Description: Verify that calling getLlm with the same model name multiple times returns the same cached instance rather than creating a new one each time. This tests the caching mechanism using ConcurrentHashMap.

Execution:
  Arrange: Prepare a valid model name string such as "gemini-1.5-flash".
  Act: Call LlmRegistry.getLlm("gemini-1.5-flash") twice and store both results.
  Assert: Verify that both returned instances are the same object reference (using assertSame).

Validation:
  The assertion confirms that the computeIfAbsent method properly caches instances, preventing unnecessary object creation and ensuring consistent behavior across the application. This is important for resource management and maintaining state consistency.

---

Scenario 4: Throw IllegalArgumentException for Unsupported Model Name

Details:
  TestName: getLlmThrowsExceptionForUnsupportedModelName
  Description: Verify that the getLlm method throws an IllegalArgumentException when provided with a model name that does not match any registered factory pattern.

Execution:
  Arrange: Prepare an unsupported model name string such as "unsupported-model-xyz".
  Act: Call LlmRegistry.getLlm("unsupported-model-xyz") and expect an exception.
  Assert: Verify that an IllegalArgumentException is thrown with a message containing "Unsupported model".

Validation:
  The assertion confirms that the registry properly handles unknown model names by throwing a descriptive exception. This is essential for providing clear error feedback to developers when they attempt to use an unregistered model.

---

Scenario 5: Handle Null Model Name Parameter

Details:
  TestName: getLlmWithNullModelName
  Description: Verify the behavior of getLlm when a null model name is passed. The method should either throw a NullPointerException or handle the null gracefully.

Execution:
  Arrange: Prepare a null value for the model name parameter.
  Act: Call LlmRegistry.getLlm(null) and capture any exception.
  Assert: Verify that a NullPointerException or IllegalArgumentException is thrown.

Validation:
  The assertion confirms that the method handles null input appropriately. This is important for defensive programming and ensuring the application fails fast with clear error messages when invalid input is provided.

---

Scenario 6: Handle Empty String Model Name

Details:
  TestName: getLlmWithEmptyStringModelName
  Description: Verify that the getLlm method throws an IllegalArgumentException when provided with an empty string as the model name, since no factory pattern should match an empty string.

Execution:
  Arrange: Prepare an empty string "" for the model name parameter.
  Act: Call LlmRegistry.getLlm("") and expect an exception.
  Assert: Verify that an IllegalArgumentException is thrown with a message indicating unsupported model.

Validation:
  The assertion confirms that empty strings are not silently accepted and are properly rejected. This prevents potential issues with invalid model configurations in the application.

---

Scenario 7: Retrieve LLM Instance with Custom Registered Factory

Details:
  TestName: getLlmWithCustomRegisteredFactory
  Description: Verify that after registering a custom LLM factory using registerLlm, the getLlm method correctly uses the new factory to create instances for matching model names.

Execution:
  Arrange: Register a custom factory using LlmRegistry.registerLlm("custom-.*", modelName -> mockBaseLlm) with a mock or test implementation.
  Act: Call LlmRegistry.getLlm("custom-test-model").
  Assert: Verify that the returned instance is the one created by the custom factory.

Validation:
  The assertion confirms that the registry's extensibility mechanism works correctly, allowing applications to register their own LLM implementations. This is crucial for supporting custom or third-party LLM providers.

---

Scenario 8: Thread Safety When Multiple Threads Request Same Model

Details:
  TestName: getLlmIsThreadSafeForConcurrentAccess
  Description: Verify that when multiple threads simultaneously call getLlm with the same model name, only one instance is created and all threads receive the same cached instance.

Execution:
  Arrange: Create multiple threads that will concurrently call getLlm with the same model name "gemini-concurrent-test".
  Act: Execute all threads simultaneously and collect the returned BaseLlm instances from each thread.
  Assert: Verify that all threads received the same instance reference.

Validation:
  The assertion confirms that the ConcurrentHashMap-based caching mechanism properly handles concurrent access, preventing race conditions and ensuring thread safety. This is critical for multi-threaded applications.

---

Scenario 9: Different Model Names Return Different Instances

Details:
  TestName: getLlmReturnsDifferentInstancesForDifferentModelNames
  Description: Verify that calling getLlm with different model names returns distinct BaseLlm instances, not the same cached instance.

Execution:
  Arrange: Prepare two different valid model names such as "gemini-1.5-pro" and "gemini-1.5-flash".
  Act: Call getLlm for both model names and store the results.
  Assert: Verify that the two returned instances are not the same object reference (using assertNotSame).

Validation:
  The assertion confirms that the caching mechanism correctly distinguishes between different model names and creates separate instances for each. This ensures that different model configurations are properly isolated.

---

Scenario 10: Model Name with Special Characters in Gemini Pattern

Details:
  TestName: getLlmWithGeminiModelNameContainingSpecialCharacters
  Description: Verify that the getLlm method correctly handles Gemini model names that contain various characters like numbers, hyphens, and dots (e.g., "gemini-2.0-flash-exp").

Execution:
  Arrange: Prepare a Gemini model name with special characters such as "gemini-2.0-flash-exp".
  Act: Call LlmRegistry.getLlm("gemini-2.0-flash-exp").
  Assert: Verify that the returned object is not null and is a valid BaseLlm instance.

Validation:
  The assertion confirms that the regex pattern "gemini-.*" correctly matches model names with various character combinations. This is important for supporting the full range of Gemini model naming conventions.

*/

// ********RoostGPT********

package com.google.adk.models;

import static com.google.common.truth.Truth.assertThat;
import static org.junit.jupiter.api.Assertions.assertNotSame;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

class LlmRegistryGetLlmTest {

  private BaseLlm mockBaseLlm;

  @BeforeEach
  void setUp() {
    mockBaseLlm = Mockito.mock(BaseLlm.class);
  }

  @AfterEach
  void tearDown() {
    // Clean up any test registrations
  }

  @Test
  @Tag("valid")
  void getLlmForValidGeminiModelName() {
    // Arrange
    String modelName = "gemini-1.5-pro";

    // Act
    BaseLlm result = LlmRegistry.getLlm(modelName);

    // Assert
    assertThat(result).isNotNull();
    assertThat(result).isInstanceOf(BaseLlm.class);
  }

  @Test
  @Tag("valid")
  void getLlmForValidApigeeModelName() {
    // Arrange
    String modelName = "apigee/custom-model";

    // Act
    BaseLlm result = LlmRegistry.getLlm(modelName);

    // Assert
    assertThat(result).isNotNull();
    assertThat(result).isInstanceOf(BaseLlm.class);
  }

  @Test
  @Tag("valid")
  void getLlmReturnsCachedInstanceOnSubsequentCalls() {
    // Arrange
    String modelName = "gemini-1.5-flash";

    // Act
    BaseLlm firstCall = LlmRegistry.getLlm(modelName);
    BaseLlm secondCall = LlmRegistry.getLlm(modelName);

    // Assert
    assertSame(firstCall, secondCall, "Both calls should return the same cached instance");
  }

  @Test
  @Tag("invalid")
  void getLlmThrowsExceptionForUnsupportedModelName() {
    // Arrange
    String unsupportedModelName = "unsupported-model-xyz";

    // Act & Assert
    IllegalArgumentException exception =
        assertThrows(
            IllegalArgumentException.class, () -> LlmRegistry.getLlm(unsupportedModelName));

    assertThat(exception.getMessage()).contains("Unsupported model");
  }

  @Test
  @Tag("invalid")
  void getLlmWithNullModelName() {
    // Arrange
    String nullModelName = null;

    // Act & Assert
    assertThrows(NullPointerException.class, () -> LlmRegistry.getLlm(nullModelName));
  }

  @Test
  @Tag("boundary")
  void getLlmWithEmptyStringModelName() {
    // Arrange
    String emptyModelName = "";

    // Act & Assert
    IllegalArgumentException exception =
        assertThrows(IllegalArgumentException.class, () -> LlmRegistry.getLlm(emptyModelName));

    assertThat(exception.getMessage()).contains("Unsupported model");
  }

  @Test
  @Tag("valid")
  void getLlmWithCustomRegisteredFactory() {
    // Arrange
    String customPattern = "custom-test-.*";
    String customModelName = "custom-test-model";
    BaseLlm customMockLlm = Mockito.mock(BaseLlm.class);

    LlmRegistry.registerTestLlm(customPattern, modelName -> customMockLlm);

    // Act
    BaseLlm result = LlmRegistry.getLlm(customModelName);

    // Assert
    assertThat(result).isNotNull();
    assertSame(customMockLlm, result, "Should return the instance from custom factory");
  }

  @Test
  @Tag("integration")
  void getLlmIsThreadSafeForConcurrentAccess() throws InterruptedException {
    // Arrange
    String modelName = "gemini-concurrent-test";
    int threadCount = 10;
    ExecutorService executor = Executors.newFixedThreadPool(threadCount);
    CountDownLatch startLatch = new CountDownLatch(1);
    CountDownLatch doneLatch = new CountDownLatch(threadCount);
    List<BaseLlm> results = Collections.synchronizedList(new ArrayList<>());

    // Register a test factory for this specific model
    LlmRegistry.registerTestLlm("gemini-concurrent-.*", modelName1 -> Mockito.mock(BaseLlm.class));

    // Act
    for (int i = 0; i < threadCount; i++) {
      executor.submit(
          () -> {
            try {
              startLatch.await();
              BaseLlm llm = LlmRegistry.getLlm(modelName);
              results.add(llm);
            } catch (InterruptedException e) {
              Thread.currentThread().interrupt();
            } finally {
              doneLatch.countDown();
            }
          });
    }

    startLatch.countDown();
    doneLatch.await(10, TimeUnit.SECONDS);
    executor.shutdown();

    // Assert
    assertThat(results).hasSize(threadCount);
    BaseLlm firstInstance = results.get(0);
    for (BaseLlm instance : results) {
      assertSame(firstInstance, instance, "All threads should receive the same cached instance");
    }
  }

  @Test
  @Tag("valid")
  void getLlmReturnsDifferentInstancesForDifferentModelNames() {
    // Arrange
    String modelName1 = "gemini-1.5-pro";
    String modelName2 = "gemini-1.5-flash";

    // Act
    BaseLlm instance1 = LlmRegistry.getLlm(modelName1);
    BaseLlm instance2 = LlmRegistry.getLlm(modelName2);

    // Assert
    assertThat(instance1).isNotNull();
    assertThat(instance2).isNotNull();
    assertNotSame(instance1, instance2, "Different model names should return different instances");
  }

  @Test
  @Tag("boundary")
  void getLlmWithGeminiModelNameContainingSpecialCharacters() {
    // Arrange
    String modelName = "gemini-2.0-flash-exp";

    // Act
    BaseLlm result = LlmRegistry.getLlm(modelName);

    // Assert
    assertThat(result).isNotNull();
    assertThat(result).isInstanceOf(BaseLlm.class);
  }
}
