/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-maven-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=location_d0ffa263fc
ROOST_METHOD_SIG_HASH=location_d0ffa263fc

Scenario 1: Verify location returns empty Optional when not set

Details:
  TestName: locationReturnsEmptyOptionalWhenNotSet
  Description: This test verifies that the location() method returns an empty Optional when no location value has been set during the VertexCredentials object construction. This tests the default behavior when the location is not provided.
Execution:
  Arrange: Create a VertexCredentials object using the builder without setting a location value.
  Act: Invoke the location() method on the created VertexCredentials instance.
  Assert: Use JUnit assertions to verify that the returned Optional is empty using Optional.isEmpty() or assertFalse(optional.isPresent()).
Validation:
  The assertion verifies that when no location is explicitly set, the method returns an empty Optional rather than null or throwing an exception. This is important for null-safety and follows the Optional pattern for representing absent values. This behavior allows calling code to safely check for the presence of a location without risking NullPointerException.

Scenario 2: Verify location returns Optional containing the set value

Details:
  TestName: locationReturnsOptionalWithSetValue
  Description: This test verifies that the location() method returns an Optional containing the exact string value that was set using the builder's setLocation(String) method. This validates the basic getter functionality for a populated location field.
Execution:
  Arrange: Create a VertexCredentials object using the builder and set a specific location value (e.g., "us-central1") using setLocation(String).
  Act: Invoke the location() method on the created VertexCredentials instance.
  Assert: Use JUnit assertions to verify that the returned Optional is present and contains the expected location string value using assertTrue(optional.isPresent()) and assertEquals("us-central1", optional.get()).
Validation:
  The assertion confirms that the location value is correctly stored and retrieved through the location() method. This is critical for ensuring that the Vertex AI location configuration is properly maintained throughout the object's lifecycle. The location is essential for routing API requests to the correct Google Cloud region.

Scenario 3: Verify location returns Optional containing value when set with Optional parameter

Details:
  TestName: locationReturnsValueWhenSetWithOptional
  Description: This test verifies that the location() method correctly returns the value when the location was set using the builder's setLocation(Optional<String>) method with a non-empty Optional. This tests the alternative builder method signature.
Execution:
  Arrange: Create a VertexCredentials object using the builder and set the location using setLocation(Optional.of("europe-west4")).
  Act: Invoke the location() method on the created VertexCredentials instance.
  Assert: Use JUnit assertions to verify that the returned Optional contains the expected value using assertTrue(optional.isPresent()) and assertEquals("europe-west4", optional.get()).
Validation:
  This assertion validates that both builder method signatures (setLocation(String) and setLocation(Optional<String>)) work correctly and produce the same result. This is important for API flexibility, allowing callers to use whichever method signature is more convenient for their use case.

Scenario 4: Verify location returns empty Optional when set with null string

Details:
  TestName: locationReturnsEmptyOptionalWhenSetWithNull
  Description: This test verifies that when the location is explicitly set to null using setLocation(@Nullable String), the location() method returns an empty Optional. This tests the null-handling behavior of the builder.
Execution:
  Arrange: Create a VertexCredentials object using the builder and explicitly set the location to null using setLocation((String) null).
  Act: Invoke the location() method on the created VertexCredentials instance.
  Assert: Use JUnit assertions to verify that the returned Optional is empty using assertFalse(optional.isPresent()) or assertTrue(optional.isEmpty()).
Validation:
  The assertion confirms that null values are properly converted to empty Optionals, maintaining null-safety throughout the API. This prevents NullPointerException and follows Java best practices for handling absent values. This is particularly important when location data might come from external sources that could provide null values.

Scenario 5: Verify location returns empty Optional when set with empty Optional

Details:
  TestName: locationReturnsEmptyOptionalWhenSetWithEmptyOptional
  Description: This test verifies that when the location is set using setLocation(Optional.empty()), the location() method returns an empty Optional. This validates proper handling of explicitly empty Optional values.
Execution:
  Arrange: Create a VertexCredentials object using the builder and set the location using setLocation(Optional.empty()).
  Act: Invoke the location() method on the created VertexCredentials instance.
  Assert: Use JUnit assertions to verify that the returned Optional is empty using assertFalse(optional.isPresent()).
Validation:
  This assertion ensures that empty Optionals passed to the builder are preserved and returned correctly. This maintains consistency in the API's Optional handling and ensures that explicitly absent values are treated the same way as unset values.

Scenario 6: Verify location returns correct value with special characters

Details:
  TestName: locationReturnsValueWithSpecialCharacters
  Description: This test verifies that the location() method correctly handles and returns location strings containing special characters, hyphens, and numbers, which are common in Google Cloud region identifiers.
Execution:
  Arrange: Create a VertexCredentials object using the builder and set a location with special characters like "asia-northeast1" or "us-west2-a".
  Act: Invoke the location() method on the created VertexCredentials instance.
  Assert: Use JUnit assertions to verify that the returned Optional contains the exact string including all special characters using assertEquals with the expected value.
Validation:
  The assertion confirms that the location field preserves the exact string value without any transformation or sanitization. This is crucial because Google Cloud location identifiers have specific formats that must be preserved exactly for API calls to work correctly.

Scenario 7: Verify location returns correct value with empty string

Details:
  TestName: locationReturnsOptionalWithEmptyString
  Description: This test verifies the behavior when an empty string ("") is set as the location value. This tests edge case handling for empty but non-null strings.
Execution:
  Arrange: Create a VertexCredentials object using the builder and set the location to an empty string using setLocation("").
  Act: Invoke the location() method on the created VertexCredentials instance.
  Assert: Use JUnit assertions to verify that the returned Optional is present and contains an empty string using assertTrue(optional.isPresent()) and assertEquals("", optional.get()).
Validation:
  This assertion validates that empty strings are treated as valid values distinct from null or absent values. This distinction is important for scenarios where an empty location might have different semantics than an unset location, though in practice this might indicate a configuration error.

Scenario 8: Verify location immutability after object creation

Details:
  TestName: locationValueRemainsImmutableAfterCreation
  Description: This test verifies that the location value returned by location() remains consistent across multiple invocations, confirming the immutability of the VertexCredentials object as enforced by AutoValue.
Execution:
  Arrange: Create a VertexCredentials object using the builder with a specific location value (e.g., "us-east1").
  Act: Invoke the location() method multiple times on the same VertexCredentials instance.
  Assert: Use JUnit assertions to verify that all invocations return Optionals with the same value and that the values are equal using assertEquals for each pair of results.
Validation:
  The assertion confirms that VertexCredentials is truly immutable and that the location() method consistently returns the same value. This is critical for thread-safety and predictable behavior in concurrent environments. The AutoValue annotation should guarantee this, but explicit testing confirms the expected behavior.

Scenario 9: Verify location returns value after building with all fields set

Details:
  TestName: locationReturnsValueWhenAllFieldsSet
  Description: This test verifies that the location() method correctly returns the location value when a VertexCredentials object is built with all fields (project, location, and credentials) populated. This ensures no interference between fields.
Execution:
  Arrange: Create a VertexCredentials object using the builder with all fields set: project, location (e.g., "us-central1"), and credentials (can use a mock or null GoogleCredentials).
  Act: Invoke the location() method on the created VertexCredentials instance.
  Assert: Use JUnit assertions to verify that the returned Optional contains the expected location value.
Validation:
  This assertion ensures that setting other fields in the builder does not affect the location field's storage or retrieval. This validates proper field isolation in the AutoValue-generated class and confirms that each field is independently managed.

Scenario 10: Verify location Optional type safety

Details:
  TestName: locationReturnsOptionalOfStringType
  Description: This test verifies that the location() method returns an Optional of the correct generic type (Optional<String>) and that the contained value is indeed a String instance.
Execution:
  Arrange: Create a VertexCredentials object using the builder with a location value set.
  Act: Invoke the location() method and retrieve the value from the Optional.
  Assert: Use JUnit assertions to verify that the returned Optional's contained value is an instance of String using assertInstanceOf or assertTrue with instanceof check.
Validation:
  This assertion confirms type safety and that the generic type parameter is correctly maintained. While Java's type system should guarantee this at compile time, this test provides runtime verification and documents the expected type contract of the method.

*/

// ********RoostGPT********

package com.google.adk.models;
import static org.junit.jupiter.api.Assertions.*;
import com.google.auth.oauth2.GoogleCredentials;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import java.util.Optional;
import org.junit.jupiter.api.*;
import com.google.auto.value.AutoValue;
import javax.annotation.Nullable;

class VertexCredentialsLocationTest {
    @Test
    @Tag("valid")
    void locationReturnsEmptyOptionalWhenNotSet() {
        VertexCredentials credentials = VertexCredentials.builder().build();
        
        Optional<String> location = credentials.location();
        
        assertTrue(location.isEmpty());
        assertFalse(location.isPresent());
    }
    @Test
    @Tag("valid")
    void locationReturnsOptionalWithSetValue() {
        VertexCredentials credentials = VertexCredentials.builder()
                .setLocation("us-central1")
                .build();
        
        Optional<String> location = credentials.location();
        
        assertTrue(location.isPresent());
        assertEquals("us-central1", location.get());
    }
    @Test
    @Tag("valid")
    void locationReturnsValueWhenSetWithOptional() {
        VertexCredentials credentials = VertexCredentials.builder()
                .setLocation(Optional.of("europe-west4"))
                .build();
        
        Optional<String> location = credentials.location();
        
        assertTrue(location.isPresent());
        assertEquals("europe-west4", location.get());
    }
    @Test
    @Tag("valid")
    void locationReturnsEmptyOptionalWhenSetWithNull() {
        VertexCredentials credentials = VertexCredentials.builder()
                .setLocation((String) null)
                .build();
        
        Optional<String> location = credentials.location();
        
        assertFalse(location.isPresent());
        assertTrue(location.isEmpty());
    }
    @Test
    @Tag("valid")
    void locationReturnsEmptyOptionalWhenSetWithEmptyOptional() {
        VertexCredentials credentials = VertexCredentials.builder()
                .setLocation(Optional.empty())
                .build();
        
        Optional<String> location = credentials.location();
        
        assertFalse(location.isPresent());
    }
    @Test
    @Tag("boundary")
    void locationReturnsValueWithSpecialCharacters() {
        String locationWithSpecialChars = "asia-northeast1";
        VertexCredentials credentials = VertexCredentials.builder()
                .setLocation(locationWithSpecialChars)
                .build();
        
        Optional<String> location = credentials.location();
        
        assertTrue(location.isPresent());
        assertEquals("asia-northeast1", location.get());
    }
    @Test
    @Tag("boundary")
    void locationReturnsValueWithSpecialCharactersZone() {
        String locationWithZone = "us-west2-a";
        VertexCredentials credentials = VertexCredentials.builder()
                .setLocation(locationWithZone)
                .build();
        
        Optional<String> location = credentials.location();
        
        assertTrue(location.isPresent());
        assertEquals("us-west2-a", location.get());
    }
    @Test
    @Tag("boundary")
    void locationReturnsOptionalWithEmptyString() {
        VertexCredentials credentials = VertexCredentials.builder()
                .setLocation("")
                .build();
        
        Optional<String> location = credentials.location();
        
        assertTrue(location.isPresent());
        assertEquals("", location.get());
    }
    @Test
    @Tag("valid")
    void locationValueRemainsImmutableAfterCreation() {
        VertexCredentials credentials = VertexCredentials.builder()
                .setLocation("us-east1")
                .build();
        
        Optional<String> location1 = credentials.location();
        Optional<String> location2 = credentials.location();
        Optional<String> location3 = credentials.location();
        
        assertTrue(location1.isPresent());
        assertTrue(location2.isPresent());
        assertTrue(location3.isPresent());
        assertEquals(location1.get(), location2.get());
        assertEquals(location2.get(), location3.get());
        assertEquals("us-east1", location1.get());
        assertEquals("us-east1", location2.get());
        assertEquals("us-east1", location3.get());
    }
    @Test
    @Tag("integration")
    void locationReturnsValueWhenAllFieldsSet() {
        VertexCredentials credentials = VertexCredentials.builder()
                .setProject("test-project")
                .setLocation("us-central1")
                .setCredentials((GoogleCredentials) null)
                .build();
        
        Optional<String> location = credentials.location();
        
        assertTrue(location.isPresent());
        assertEquals("us-central1", location.get());
    }
    @Test
    @Tag("valid")
    void locationReturnsOptionalOfStringType() {
        VertexCredentials credentials = VertexCredentials.builder()
                .setLocation("us-west1")
                .build();
        
        Optional<String> location = credentials.location();
        
        assertTrue(location.isPresent());
        assertInstanceOf(String.class, location.get());
    }
    @Test
    @Tag("valid")
    void locationReturnsConsistentOptionalReference() {
        VertexCredentials credentials = VertexCredentials.builder()
                .setLocation("asia-south1")
                .build();
        
        Optional<String> location = credentials.location();
        
        assertTrue(location.isPresent());
        assertEquals("asia-south1", location.get());
        assertNotNull(location);
    }
    @Test
    @Tag("boundary")
    void locationReturnsValueWithLongRegionName() {
        String longLocationName = "northamerica-northeast1";
        VertexCredentials credentials = VertexCredentials.builder()
                .setLocation(longLocationName)
                .build();
        
        Optional<String> location = credentials.location();
        
        assertTrue(location.isPresent());
        assertEquals("northamerica-northeast1", location.get());
    }
    @Test
    @Tag("valid")
    void locationReturnsEmptyOptionalWhenOnlyOtherFieldsSet() {
        VertexCredentials credentials = VertexCredentials.builder()
                .setProject("test-project")
                .setCredentials((GoogleCredentials) null)
                .build();
        
        Optional<String> location = credentials.location();
        
        assertTrue(location.isEmpty());
    }
    @Test
    @Tag("integration")
    void locationReturnsValueIndependentOfProjectField() {
        VertexCredentials credentials = VertexCredentials.builder()
                .setProject("different-project")
                .setLocation("europe-north1")
                .build();
        
        Optional<String> location = credentials.location();
        
        assertTrue(location.isPresent());
        assertEquals("europe-north1", location.get());
    }
}